### ISSUE TITLE
Random errors on loading pages in Firefox when a braille display is connected

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8967] opened 2018-11-21 11:58 UTC
### Steps to reproduce:
1. Visit https://danielmayr.at/abc/
2. Use the Access-Keys A, Q, W, S, X and Y to move between those six static HTML sites.
### Actual behaviour:
Random errors on loading pages. [Here](https://github.com/nvaccess/nvda/files/2604099/NVDA.2018.4beta1_Firefox.63.0.3_Error.on.loading.page.log) is the logfile. Start reading from line 674.
### Expected behaviour:
No errors on loading pages.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA 2018.4 Beta 1
#### Windows version:
Windows 7, SP1, 64-Bit
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 63.0.3 Portable
#### Other information about your system:
Installed Firefox Add-ons:
+ Noise 2.2.2
+ uBlock Origin 1.17.2
#### Does the issue still occur after restarting your PC?
Not tried.
#### Have you tried any other versions of NVDA?
No errors with NVDA 2018.1 (installed).
CC: @michaelDCurran, @MarcoZehe and @jcsteh

**Comment by leonardder** [comment] 2018-11-22 17:41
Could you try this with an installed copy?

**Comment by jcsteh** [comment] 2018-11-23 01:46
Not critical for the release, as these exceptions should have no user impact and users won't be aware of them in a final release. They should still be caught somewhere, though. I think the issue is that braille tries to access the document after it has died in response to a caret movement. The question is why the caret movement fires when the document is dead... or why braille handles it so late.

This also probably isn't Firefox specific, although timing may mean reproducing it is highly dependent on circumstances. I haven't tested it myself.

**Comment by DrSooom** [comment] 2019-07-29 16:14
This issue still exists in NVDA 2019.2 Beta-18176 Portable with Firefox 68.0.1 (64-Bit, portable) on Win7x64 with a connected Optelec ALVA BC680. [Here](https://github.com/nvaccess/nvda/files/3443175/8967_NVDA.2019.2.Beta-18176_Firefox.68.0.1.txt) is the logfile which contains two sections due to the option "Automatically set system focus to focusable elements in Browse Mode".

**Comment by Adriani90** [comment] 2020-05-23 12:06
@DrSooom I cannot reproduce with NVDA alpha-20220,1c4519a6 and Firefox 76. I tried about 100 times and no error, no matter if fmove focus to focusable elements in on or off.

Can you reproduce this also without a braille display connected? Or is it only reproducible when you have your braille display connected?

**Comment by DrSooom** [comment] 2020-05-23 13:52
It is still reproducible with [NVDA Alpha-20220](https://ci.appveyor.com/api/buildjobs/xavna59rlpn715sm/artifacts/output/nvda_snapshot_alpha-20220,1c4519a6.exe) and Firefox 76.0.1 (64-bit) with a connected Optelec ALVA BC680 on Win7x64. Here is the [new logfile](https://github.com/nvaccess/nvda/files/4671854/8967_NVDA.2020.2.Alpha-20220_Firefox.76.0.1.txt). See line 70 in compare to line 110, which then contains the error. These errors don't occur when no braille display is connected.

**Comment by Adriani90** [comment] 2023-05-06 13:05
@DrSooom are you still having this issue in NVDA 2023.1 and Firefox 112?

**Comment by DrSooom** [comment] 2023-06-22 02:26
Sadly, I have to inform you that I currently do not have the necessary time to check this issue in the depth that I think is required due to several health problems. Thank you for your understanding.

btw: Since Firefox 113.0 the new option "accessibility.cache.enabled" is automatically set to "true". More information about this new feature is available in [this Mozilla Accessibility blogpost](https://blog.mozilla.org/accessibility/firefox-113-accessibility-performance/).

**Comment by seanbudd** [comment] 2023-06-22 02:30
Closing as abandoned

**Closed by seanbudd** 2023-06-22 02:30 UTC
Labels: app/firefox

**Comment by XLTechie** [comment] 2023-06-22 02:58
@DrSooom very sorry to hear about your health. Hopefully for your sake such 
things can be resolved soonest!
