### ISSUE TITLE
Some loss of focus on web pages

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7391] opened 2017-07-13 16:22 UTC
I'm locating some focus failures when performing a search on a web page.
What happens is that shortly after triggering the nvda search window with ctrl + nvda + fe perform a search, the focus goes to the result more after pressing down arrow the focus does not continue next to the text found, the focus goes to the beginning from page.
I was able to reproduce with a frequent frequency in several web pages, more especially as the following sections:
Using the chrome open the page www.freedomscientific.com.
Press ctrl + nvda + f.
Type "download"
Press enter.
Press down arrow.
Now see that the focus stops coming out of the word download and goes to another location on the page to be to the top of the page.
This does not happen every time, sometimes it is necessary to restart nvda with ctrl + alt + n and repeat the tests to see the problem.
I've seen this happen on other random web pages.
I believe that it is possible to see what happens with the log below, through the texts said by nvda.
I ran the tests with the plug-ins turned off and the problem was also reproduced.

NVDA version:

next 14176
NVDA Installed or portable:
Installed 

Windows version:
windows 10 1563.413
Name and version of other software in use when reproducing the issue:

chrome 59

### Othersue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
yes

Input: kb(laptop):enter
IO - speech.speak (12:57:40.236):
Speaking [u'Portugu\xeas (Brasil) - Portugu\xeas (Brasil ABNT)']
IO - speech.speak (12:57:40.282):
Speaking [u'Freedom Scientific Home Page  documento']
IO - speech.speak (12:57:40.288):
Speaking [u'desconhecido']
IO - tones.beep (12:57:40.407):
Beep at pitch 798.359375, for 40 ms, left volume 65, right volume 19
IO - speech.speak (12:57:40.430):
Speaking [u'Freedom Scientific Home Page  documento']
IO - speech.speak (12:57:40.509):
Speaking [u'Skip to main content', u'linque']
IO - speech.speak (12:57:40.525):
Speaking [u'Freedom Scientific Home Page  documento']
IO - speech.speak (12:57:40.532):
Speaking [u'linque', u'Skip to main content']
IO - speech.speak (12:57:40.584):
Speaking [u'marca navega\xe7\xe3o ', u'lista com 6 itens', u'clic\xe1vel', u'linque', u'DOWNLOADS']
IO - speech.speak (12:57:40.602):
Speaking [u'cursor Desconhecido']
IO - inputCore.InputManager.executeGesture (12:57:44.351):
Input: kb(laptop):downArrow
IO - speech.speak (12:57:44.388):
Speaking [u'visitado  linque', u'gr\xe1fico  clic\xe1vel', u'Freedom Scientific']
IO - tones.beep (12:57:44.558):
Beep at pitch 773.4375, for 40 ms, left volume 64, right volume 20
IO - speech.speak (12:57:44.579):
Speaking [u'Freedom Scientific Home Page  documento']
IO - speech.speak (12:57:44.625):
Speaking [u'Freedom Scientific', u'gr\xe1fico  clic\xe1vel', u'visitado  linque  Freedom Scientific']
IO - speech.speak (12:57:44.632):
Speaking [u'Freedom Scientific Home Page  documento']
IO - speech.speak (12:57:44.640):
Speaking [u'visitado  linque', u'gr\xe1fico  clic\xe1vel', u'Freedom Scientific']
IO - inputCore.InputManager.executeGesture (12:57:58.211):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (12:57:58.456):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0A00A690>
Python class mro: (<class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 15712) at address 4e6f170>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'59.0.3071.115'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 4391742L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 96832224
windowStyle: 1445986304
windowThreadID: 10580
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible2) ptr=0x9128394 at a06f530>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=4391742, objectID=-4, childID=-518844
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 windowHandle: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 uniqueID: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 role: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 states: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 attributes: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by bhavyashah** [comment] 2017-07-20 16:21
Confirmed. Using Chrome 59 stable with NVDA version 2017.2, I was able to successfully and consistently replicate the described behaviour in the following manner:
* Press NVDA+Ctrl+F and enter 'download' and hit Enter.
* Press Ctrl+Home to go to the start of the document.
* Press NVDA+F3 to arrive back at the 'Downloads' link.
Expected Result: NVDA jumps to the said link and nothing out-of-the-blue happens.
Actual Result: NVDA does jump to the Downloads link but along with that speaks a chunk of unnecesary and extraneous information. The below pasted log snippet should be adequate:
IO - inputCore.InputManager.executeGesture (21:47:40):
Input: kb(laptop):NVDA+f3
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'navigation landmark ', u'list with 6 items', u'link', u'DOWNLOADS']
DEBUG - treeInterceptorHandler.update (21:47:40):
Adding new treeInterceptor to runningTable: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x04A8D090>
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'Freedom Scientific Home Page  document']
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'Main Menu  list']
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'navigation landmark ', u'list with 6 items', u'DOWNLOADS', u'\xa0submenu.', u'link']
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'Freedom Scientific Home Page  document']
IO - speech.speak (21:47:40):
Speaking [LangChangeCommand ('en'), u'link', u'DOWNLOADS']
This is when Automatic Say All on page load is disabled. When enabled, after the above has been spoken, NVDA proceeds to perform a say all for all text after the Downloads link for no apparent reason. Restarting NVDA with add-ons disabled does not affect results.

**Comment by bhavyashah** [comment] 2017-08-03 05:57
No rush, but thought I'd maybe CC @jcsteh and @feerrenrut to kindly request a more technical diagnosis of this issue as and when convenient.

**Comment by jcsteh** [comment] 2017-08-03 06:28
I think Chrome is killing the document accessible when the focus moves in this case and is then creating a new document accessible. This is probably due to some change which requires it to rebuild the tree (maybe CSS), but it should never regenerate the document accessible. This needs to be confirmed and a bug filed with Chromium if I'm correct.

**Comment by jcsteh** [comment] 2017-09-05 02:35
Filed www.crbug.com/761882

**Comment by ehollig** [comment] 2017-12-27 18:29
It appears from [ChromiumIssue:761882](www.crbug.com/761882) that this issue has been resolved. However, when performing the above steps, I receive an error message and the cursor does not move when I search for the entire word "Download". If I search for the word "down", everything works as expected.

**Comment by fernando-jose-silva** [comment] 2017-12-28 14:25
Thank you very much, I can still reproduce the problem.

**Comment by Adriani90** [comment] 2019-04-24 12:36
@fernando-jose-silva the behavior changed alot in Chrome since then. Is this issue still reproducible for you in Chrome 74 with NVDA 2019.1.1?

**Comment by fernando-jose-silva** [comment] 2019-04-24 16:53
Thank you very much, I no longer have this problem.

**Comment by Adriani90** [comment] 2019-04-24 17:38
Thank you Fernando for reporting back. Closing as works for me.

**Closed by Adriani90** 2019-04-24 17:38 UTC
Labels: Chrome, GoogleWork, needsExternalFix, p2, worksforme
