### ISSUE TITLE
Support material design icon version 5 and above

### ISSUE THREAD

**Issue by agreedSkiing** [nvaccess/nvda#13403] opened 2022-03-01 10:32 UTC
### Is your feature request related to a problem? Yes.
We recently noticed that the icon mdi-menu-down with the code \"F35D\" from version 4 of the mdi font library works fine in chrome and Firefox to activate with space or enter when it is used in a menu with NVDA is active, but when we upgraded our download mdi font package to version 6 we found out that the code has been changed to \"F035D\" and that our menu now can't be activated anymore in chromium browsers even though the icon looks the same whilst nvda I active. Our nvda test have been made with version 2021.3.1 as a standalone/usb installation.

The icon mdi-menu-down code/text content change happened in version 5.0.45
### Describe the solution you'd like
Add support for new mdi library

### Describe alternatives you've considered
Keeping using mdi versions below 5.0.45

### Additional context
None.

**Comment by seanbudd** [comment] 2022-03-02 22:53
These needs a minimal HTML example and clearer steps to reproduce.
Please create a [codepen](https://codepen.io/).
Without this information, it is hard to determine if this a problem with mdi, the implementation of mdi or NVDA.

**Comment by agreedSkiing** [comment] 2022-03-03 06:35
Well here is the library that we use included with a marterial design version 5.0.45 include by default
https://codepen.io/majs-majs/pen/NWweMve
and a second for same library with an override for the last v4 version (4.9.95)  of material design icon.
https://codepen.io/majs-majs/pen/rNYovKx

**Comment by Adriani90** [comment] 2023-04-14 08:32
This affects only browse mode in Chromium browsers. In focus mode the icon action works as expected.

Since it only affects browse mode of NVDA, I think this needs to be investigated in NVDA itself.

I can imagine such icons are often used in browser based games or WBTs, so it would be important for an user to be able to interact with these icons also in browse mode.

In Firefox it works fine.

**Comment by Adriani90** [comment] 2024-12-05 00:17
Updated test with NVDA 2024.4.1 in Firefox 133 and Chrome canary 133:
* In browse mode, button and label are separated and are rendered each on its own line in NVDA's virtual browse mode document.
* Actually button and label are treated as different objects on the same level of hierarchy, but they are not associated.
* In focus mode, only the unlabelled button role is reported by NVDA, and not the label.
* When pressing enter on a button, nothing is reported although new elements appear. I guess the propper aria attribute is missing here.

@SaschaCowley is this wrong web authoring here? Or is NVDA really not supporting these types of material design elements?
I am not sure, but I think Jaws has the same problem.

**Comment by SaschaCowley** [comment] 2024-12-08 22:58
The authoring of these examples is completely non-semantic and does not contain the ARIA roles or focus handling necessary to make it at all meaningful to a screen reader. Closing as invalid.

**Closed by SaschaCowley** 2024-12-08 22:58 UTC
Labels: needs-triage
