### ISSUE TITLE
nvda doesn't read the items in a chm treeview

### ISSUE THREAD

**Issue by vlad-a-c** [nvaccess/nvda#11814] opened 2020-11-05 23:53 UTC
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
hello.
i'm not sure exactly why is this happening but since this version on, 2020.4, nvda doesn't read the items in a chm treeview. it says unknown.

**Comment by Adriani90** [comment] 2020-11-06 19:59
Closing as duplicate of #11797

**Closed by Adriani90** 2020-11-06 19:59 UTC
Labels: close/duplicate
