### ISSUE TITLE
aria-active Does Not Update According to NVDA in Chrome

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#10728] opened 2020-01-29 07:33 UTC
### Steps to reproduce:

1. Using NVDA 2019.2.1 and latest version of Chrome, visit:
https://react-dom-bug.stackblitz.io/home
2. There are 2 links at the top, home and dash-board. Click on "dash-board"
3. Observe that "Home" is still the selected element according to NVDA, but when you inspect the elements, dash-board is the only element with aria-selected="page".

### Actual behavior:

When you hit enter on the "dash-board" link, and aria-active is switched from home without reloading the page, NVDA still says that home is the active link.

### Expected behavior:

NVDA should say "Current Page dash-board" when you click on dash-board and "Current page home" when you click on home.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.2.1

#### Windows version:

10 64 Bit

#### Name and version of other software in use when reproducing the issue:

Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

**Comment by glin** [comment] 2020-02-08 22:26
By aria-active, did you mean aria-current? If so, I'm seeing the same issue with aria-current and NVDA 2019.2 + Chrome 80.0.3987.87. I don't see this issue with NVDA + Firefox 72.0.2 or NVDA + Edge 44.

**Comment by Adriani90** [comment] 2020-04-19 13:32
I can reprotuce this in any browser, also Firefox and Edge Cromium. In the best case NVDA reports only "current page" but does not report which current page this is.
For Firefox cc: @MarcoZehe or @jcsteh 

For Cromium maybe cc: @leventhal.

**Comment by jcsteh** [comment] 2020-04-19 22:55
Can't reproduce in Firefox. When I activate "Dash Board", then read both links in browse mode, only "Dash Board" is reported as current page.

**Comment by Adriani90** [comment] 2020-07-17 21:49
This works now as expected in Chrome 84 and Firefox 78 with NVDA last alpha. I am closing as works for me.

**Closed by Adriani90** 2020-07-17 21:49 UTC
Labels: close/worksforme
