### ISSUE TITLE
Can't access extension functions such as NoScript

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#8722] opened 2018-09-05 19:29 UTC
### Steps to reproduce:

Open Firefox. Press shift-f10 or context menu key. Choose the NoScript menu option and press enter.

### Actual behavior:

The focus goes back to the website that was open.

### Expected behavior:

NoScript options should appear to forbid or permit JavaScript from specific domains etc.

#### NVDA Installed/portable/running from source:

Installed.

#### NVDA version:

2018.2.1

#### Windows version:

8.1 home 64-bit

#### Name and version of other software in use when reproducing the issue:

Firefox 62.0 64-bit, NoScript 10.1.9.1.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

No.

**Comment by lukaszgo1** [comment] 2019-09-24 13:09
It is possible that it is a duplicate of #9552. @bingen13 Can you reproduce it with latest Firefox?

**Comment by bingen13** [comment] 2019-09-24 13:31
No. The NoScript item on the context menu no longer says submenu like it used to, but pressing enter on it does give me the options again. Seems to have been fixed.

**Comment by Adriani90** [comment] 2019-09-24 19:29
Thanks for reporting. Closing as works for me.

**Closed by Adriani90** 2019-09-24 19:29 UTC
Labels: worksforme
