### ISSUE TITLE
problem downloading nvda updates

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#13281] opened 2022-01-25 23:03 UTC
Hello. I can not download the new version of nvda alfa when searching for updates, the new version is found, but when I click download after a few seconds, an error occurs when downloading the update.

**Comment by cary-rowen** [comment] 2022-01-26 02:59
It should now work as expected.

**Comment by leonardder** [comment] 2022-01-26 07:26
Thanks for opening an issue. This is a known problem to us. It looks like Appveyor silently introduced a max download limit or 1 gigabyte for appveyor organisations. This means that as soon as around 40 instances of NVDA have been downloaded from Appveyor, the daily limit is hit and you;'ll have to wait for another day.
Pretty sure this is very high priority for NV Access folks.

**Comment by Brian1Gaff** [comment] 2022-01-26 08:16
Its been going on for at least two days here, and is really an impossible 
restriction for software that relies on user testing for its progress.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2022-01-26 08:18
Confirmed on two days now.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "nikita" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, January 25, 2022 11:03 PM
Subject: [nvaccess/nvda] problem downloading nvda updates (Issue #13281)

**Comment by xingkong0113** [comment] 2022-01-26 11:44
Just now I encountered the same problem when downloading the alpha version

**Comment by feerrenrut** [comment] 2022-01-27 04:45
NV Access is aware of the issue and is looking into alternatives.

**Comment by leonardder** [comment] 2022-01-31 10:03
@feerrenrut It looks like this issue is fixed somehow. Could you elaborate on the fix?

**Comment by feerrenrut** [comment] 2022-01-31 10:08
This was fixed on the weekend. Alphas are now served directly from nvaccess.org rather than from appveyor. The backend to the update check was modified to provide a different URL.

**Closed by feerrenrut** 2022-01-31 10:08 UTC
Labels: p2
