### ISSUE TITLE
intermittent minute long freezes

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#15249] opened 2023-08-02 05:55 UTC
### Steps to reproduce:

Use the computer as usual. Saw this happening twice while arrowing around in a webpage with Firefox, alt tabbing to Thunderbird etc, so don't think this is application specific

### Actual behavior:

Use of wasapi is enabled by default in the snapshot version I'm using. Unsure if that is a contributing factor.

NVDA plays beep sounds to indicate errors a few times, and stays silent when pressing commands. NVDA only recovers from its freeze a minute later and speech resumes normally.

### Expected behavior:

This doesn't happen

### NVDA logs, crash dumps and other attachments:
[freeze.txt](https://github.com/nvaccess/nvda/files/12236525/freeze.txt)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-28759,72545d76 (2023.3.0.28759)

#### Windows version:
Version 22H2 (OS Build 19045.3208)

#### Name and version of other software in use when reproducing the issue:
Firefox, Thunderbird, probably others

#### Does the issue still occur after restarting your computer?
Unknown, I saw this happening today, will keep a lookout for it

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, but I'll be updating to the latest snapshot to see if it still happens there

#### If NVDA add-ons are disabled, is your problem still occurring?
Unknown

**Comment by Adriani90** [comment] 2023-08-02 07:20
cc: @jcsteh

**Comment by Brian1Gaff** [comment] 2023-08-02 07:31
Try disabling add ons. If you have browser nav or sound schemes on the system, I find it more likely to do daft things like that. I think both interact with the wav playing code and if  more than one thing tries it at the same time you get a cascade of watchdog thread parameters, then a bleep, then it can come back or do it again. I guess it depends on whether what you do during the silent time makes it come out. Of cours I'd also advise a complete reboot of windows, since odd things do tend to happen from time to time that have no logic at all!

Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by Neurrone** [comment] 2023-08-03 04:02
wasapi is still enabled, but I haven't seen this happening again in a day after upgrading from 28759,72545d76 (2023.3.0.28759) to alpha-28824,1f247185 (2023.3.0.28824)

**Comment by Neurrone** [comment] 2023-08-13 15:46
I just saw this happening a few times today, reopening.

I just updated to Windows 11 22H2 today, and observed this in Firefox. Though I don't think the Firefox bit is significant, since I happened to be doing lots of web browsing.

Here's the latest freeze logs.
[freeze 2.txt](https://github.com/nvaccess/nvda/files/12329849/freeze.2.txt)

**Comment by Neurrone** [comment] 2023-08-14 02:40
Possibly related to #15150

**Comment by Neurrone** [comment] 2023-08-14 04:46
Here's another one, except that this time, it never recovers after being frozen even after waiting for 5 mins.

[freeze 3.txt](https://github.com/nvaccess/nvda/files/12331535/freeze.3.txt)

**Comment by jcsteh** [comment] 2023-08-31 03:26
These are all freezing in `WasapiWavePlayer._idleCheck`. Duplicate of #15150.

**Closed by jcsteh** 2023-08-31 03:26 UTC
Labels: bug/freeze, p2, triaged
