### ISSUE TITLE
When navigating through a threaded conversation in Teams, keyboard focus moves to emoji menu and NVDA reads "menu

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#14355] opened 2022-11-09 20:54 UTC
Note: this issue doesn't occur with Narrator or JAWS.

### Steps to reproduce:
In Microsoft Teams, press Ctrl+3 to navigate to the Teams/Channels part of the application
In the list of teams/channels, arrow down to a channel and press Enter
With focus on the "new conversation button" press Shift+Tab
Focus lands in the conversation list - Toggle off browse mode 
Arrow up to a conversation with a reply added to it
Press Enter to interact with the conversation
Arrow down to the reply

### Actual behavior:

New conversation button
shift+tab
Threaded conversation with 1 replies, from John Doe, test, started on Monday, November 7, 2022 12:45:44 PM. 1 replies, 0 new. Last reply by John Doe on Monday, November 7, 2022 12:47:07 PM. Press Enter to drill in to reply and read messages. Press Enter again to drill into a message for other actions.  Use Escape to pop out. Use the down arrow key to focus on the Reply button. Press Enter to start your reply section
enter
Message from John Doe. test. Sent on Monday, November 7, 2022 12:45:44 PM. Press Enter to explore message content, then use Escape to shift focus back to the message.  section
down arrow
Reply from John Doe. menu

### Expected behavior:
In this case, NVDA is reading the sender and "menu", rather than the sender, message, time, etc. NVDA shouldn't read menu at all here.
Reply from John Doe. test 2. Sent on Monday, November 7, 2022 12:47:07 PM. Press Enter to explore message content, then use Escape to shift focus back to the message.  section

### NVDA logs, crash dumps and other attachments:
Speaking [LangChangeCommand ('en_US'), 'New conversation', 'button', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:48:38.673) - winInputHook (13060):
Input: kb(laptop):shift+tab
IO - speech.speech.speak (12:48:38.683) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'shift+tab']
IO - speech.speech.speak (12:48:39.466) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'Threaded conversation with 1 replies, from Jeremy Curry, test, started on Monday, November 7, 2022 12:45:44 PM. 1 replies, 0 new. Last reply by Jeremy Curry on Monday, November 7, 2022 12:47:07 PM. Press Enter to drill in to reply and read messages. Press Enter again to drill into a message for other actions.\xa0 Use Escape to pop out. Use the down arrow key to focus on the Reply button. Press Enter to start your reply', 'section', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:48:40.934) - winInputHook (13060):
Input: kb(laptop):enter
IO - speech.speech.speak (12:48:40.961) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'enter']
IO - speech.speech.speak (12:48:41.204) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'Message from Jeremy Curry. test. Sent on Monday, November 7, 2022 12:45:44 PM. Press Enter to explore message content, then use Escape to shift focus back to the message.', 'section', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:48:41.979) - winInputHook (13060):
Input: kb(laptop):downArrow
IO - speech.speech.speak (12:48:42.006) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'down arrow']
IO - speech.speech.speak (12:48:42.294) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'Reply from Jeremy Curry. test 2. Sent on Monday, November 7, 2022 12:47:07 PM. Press Enter to explore message content, then use Escape to shift focus back to the message.', 'section', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:48:42.800) - MainThread (12472):
Speaking [LangChangeCommand ('en_US'), 'menu', CancellableSpeech (still valid)]
DEBUGWARNING - RPC process 19956 (Teams.exe) (12:48:42.920) - Dummy-6 (17432):
Thread 2024, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 870:
Offset 7434 out of range. Returnning NULL

#### NVDA installed/portable/running from source:
Repros in all cases

#### NVDA version:
2022.3.1

#### Windows version:
22H2 OS Build 22623.885

#### Name and version of other software in use when reproducing the issue:
Microsoft Teams - 
1.5.00.31029 
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Repros in 2022.2.1

**Comment by michaelDCurran** [comment] 2022-11-09 22:57
This is a duplicate of #14238  also filed by @msftedad , however, this issue has clearer steps to reproduce.
I am able to reproduce this issue.
This is not the first time we have seen this behaviour though. It was first filed in issue #11821 and was apparently fixed in pr #11822 , however the fix obviously no longer works. I shall look into this.

Technically:
Every time a message is focused, Chromium is sending an EVENT_MENU_POPUPSTART MSAA winEvent. NVDA is (correctly in my opinion) reporting the appearance of the menu, as this is what would happen if a true context menu appeared. It is difficult for us to differentiate between real ones and this (incorrect) one.
I will follow up with Google and Chromium to better understand the exact situations that cause them to fire an EVENT_MENU_POPUPSTART. But I would also appreciate knowing from Teams, how / why they are creating a (presumably visible) menu every time a message is focused. It would be much better if this did not have an ARIA role of menu, especially if they do not want the AT to perform its default menu behaviour.
I accept the fact that Narrator / Jaws are not affected by this bug, thus why we will look into what we can do / what Google can do. as well. But I would still strongly argue, that this is very bad accessibility UX and that menu should not be conveyed to ATs, unless it is actually active.

**Comment by michaelDCurran** [comment] 2022-11-10 05:58
My conversation about this with Google has suggested this may be a bug in Chromium, in that the MENU_POPUPSTART event should only be fired if focus is within the menu already. Google would appreciate if Teams could file a Chromium bug and or contribute a fix to Chromium themselves.
Alternatively, I would recommend that teams does not put a role of menu on that node when a message gets focus, which will also suppress the menu event.

**Comment by jcsteh** [comment] 2022-11-10 12:29
Firefox would fire this event in this case as well. It's worth noting that restricting this event to only fire when the menu has focus would break cases where a menu opens but an item inside the menu isn't focused, as happens with native Windows context menus. Arguably, that's a bad pattern anyway - a menu item or the menu itself should probably be focused - but this happens in the wild on the web; e.g. the Options menu for GitHub comments.

**Comment by alexstinewaystar** [comment] 2022-11-10 14:55
Good morning,

Is there any chance this could be modified for Teams only? I personally would not like it either to start adding exclusions for applications but it is greatly effecting the ability for me to work efficiently. Switching to Narrator all day or trying to read threads on my phone are not practical solutions long term.

Thanks.

**Comment by michaelDCurran** [comment] 2022-11-11 05:32
Here is a try build of NVDA 2022.4beta3 with the fix for Teams.
https://ci.appveyor.com/api/buildjobs/cnjspv3390ky6oo9/artifacts/output%2Fnvda_snapshot_try-i14355-27146%2C58b7eaec.exe
Please test this and confirm here that the issue is fixed.
If this is so, this fix will be in NVDA 2022.4beta4 and then NVDA 2022.4 which should be available by early December.

**Comment by alexstinewaystar** [comment] 2022-11-11 19:43
@michaelDCurran Thanks for the faster than expected fix. I can confirm the issue is gone on messages and I did not notice any regressions around other Teams menus.

My biggest hope is that one day Microsoft (@msftedad) will pay attention to such UI changes as it comes with big impacts for assistive technology users.

Looking forward to the release and thanks again!

**Closed** 2022-11-24 04:42 UTC
Labels: blocked/needs-external-fix, p2, triaged
