### ISSUE TITLE
Table navigation is deceiving in firefox with gmail

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#7141] opened 2017-05-04 03:24 UTC
1. open gmail.
2.make sure focus mode is on, and move into the table.
3. try alt+control+arrowing around. 
Expectation:
Things like the contents of the columns are read.
Actual:
The columns (With exception of col 1) read as blank when there is in fact data in them.

**Comment by derekriemer** [comment] 2017-06-28 03:13
should I label this browse mode?

**Comment by jcsteh** [comment] 2017-06-29 02:28
These table navigation commands are actually from the RowWithFakeNavigation behaviour. They're intended to be used with XUL stuff like Thunderbird, not with HTML. We probably either shouldn't allow table navigation here at all or we should fall back to browse mode table navigation somehow. In the short-term, I'm leaning towards the former.

**Comment by Adriani90** [comment] 2019-04-03 23:08
Still reproducible in NVDA 2019.1 and Firefox 66.0.2.

**Comment by Adriani90** [comment] 2019-12-05 23:12
I get following error in focus mode from time to time when using table navigation commands in the message list:

```
IO - inputCore.InputManager.executeGesture (00:07:30.283) - winInputHook (9808):
Input: kb(laptop):alt+control+upArrow
ERROR - scriptHandler.executeScript (00:07:30.317) - MainThread (11600):
error executing script: <bound method RowWithFakeNavigation.script_moveToPreviousRow of <NVDAObjects.Dynamic_RowWithFakeNavigationMozillaIAccessible object at 0x055B4990>> with gesture 'Alt+Strg+Pfeiltaste nach oben'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "NVDAObjects\behaviors.pyc", line 625, in script_moveToPreviousRow
  File "NVDAObjects\behaviors.pyc", line 615, in _moveToRow
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1162, in _get_columnNumber
NotImplementedError
```

**Comment by Adriani90** [comment] 2019-12-05 23:13
And doing the same in browse mode I get following errors from time to time:

```
IO - inputCore.InputManager.executeGesture (00:08:16.952) - winInputHook (9808):
Input: kb(laptop):alt+control+rightArrow
IO - inputCore.logTimeSinceInput (00:08:17.027) - MainThread (11600):
0.075 sec since input
IO - speech.speak (00:08:17.027) - MainThread (11600):
Speaking ['Tabellenrand']
IO - inputCore.logTimeSinceInput (00:08:17.042) - MainThread (11600):
0.090 sec since input
IO - speech.speak (00:08:17.042) - MainThread (11600):
Speaking ['00:01']
IO - inputCore.InputManager.executeGesture (00:08:17.322) - winInputHook (9808):
Input: kb(laptop):alt+control+leftArrow
IO - inputCore.logTimeSinceInput (00:08:17.372) - MainThread (11600):
0.050 sec since input
IO - speech.speak (00:08:17.372) - MainThread (11600):
Speaking ['Leer']
ERROR - unhandled exception (00:08:17.367) - winInputHook (9808):
Traceback (most recent call last):
  File "wx\core.pyc", line 3240, in <lambda>
  File "wx\core.pyc", line 3284, in __init__
  File "wx\core.pyc", line 3305, in Start
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread
ERROR - unhandled exception (00:08:17.412) - winInputHook (9808):
Traceback (most recent call last):
  File "wx\core.pyc", line 3240, in <lambda>
wx._core.wxAssertionError: C++ assertion "wxThread::IsMain()" failed at ..\..\src\common\timerimpl.cpp(60) in wxTimerImpl::Start(): timer can only be started from the main thread
IO - inputCore.InputManager.executeGesture (00:08:17.561) - winInputHook (9808):
Input: kb(laptop):alt+control+leftArrow
ERROR - scriptHandler.executeScript (00:08:17.432) - MainThread (11600):
error executing script: <bound method DocumentWithTableNavigation.script_previousColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0502D650>> with gesture 'Alt+Strg+Pfeiltaste nach links'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "documentBase.pyc", line 185, in script_previousColumn
  File "documentBase.pyc", line 167, in _tableMovementScriptHelper
  File "browseMode.pyc", line 1289, in _set_selection
  File "NVDAObjects\IAccessible\mozilla.pyc", line 51, in setFocus
  File "api.pyc", line 287, in processPendingEvents
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\common\evtloopcmn.cpp(110) in wxEventLoopBase::Yield(): wxYield called recursively
```

cc: @feerrenrut

**Comment by Adriani90** [comment] 2020-05-02 19:26
Solved now, it works correctly in NVDA alpha-20097,6a573cd9 and Firefox 75. Closing as works for me.

**Closed by Adriani90** 2020-05-02 19:26 UTC
Labels: close/worksforme
