### ISSUE TITLE
NVDA's virtual buffer command for skipping links produces an error when there are no links to skip

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10561] opened 2019-11-29 12:00 UTC
### Steps to reproduce:
1. Install the latest NVDA alpha build (though the problem is reproducible for some time now).
2. Open a browser and load a page in it. The less links/blocks of links it has - the better.
3. When the page loads, execute the command to go forward or backward passed blocks of links (N and Shift+N by default).

### Actual behavior:
When there are no more links/blocks of links to be skipped, NVDA will play its error sound, but will not report that there are no more links/blocks of links to be skipped.

### Expected behavior:
When there are no more links/blocks of links to be skipped, NVDA should only report that there are no more links/blocks of links to be skipped.

### System configuration
- Operating system: Windows 10 Pro version 1909 (build 18363.476), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- JAWS version: 2019.1909.28 ENU for 64-bit.
- JAWS version: 2020.1911.82 ENU for 64-bit.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your PC?
Yes - it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - v2019.2.1 - it behaves as it should.
[nvda-old.log](https://github.com/nvaccess/nvda/files/3905073/nvda-old.log)

**Comment by lukaszgo1** [comment] 2019-11-29 13:12
Duplicate of #10038. If it is indeed a regression it might be wort fixing it before 2019.3. cc @feerrenrut @michaelDCurran

**Closed** 2019-11-29 15:24 UTC
