### ISSUE TITLE
HandyTech Active Braille: toggling and using ATC from NVDA

### ISSUE THREAD

**Issue by codeofdusk** [nvaccess/nvda#11955] opened 2020-12-21 08:19 UTC
### Is your feature request related to a problem? Please describe.
When using the Active Braille from HandyTech, it's unclear how to enable or use ATC.

Space+b1+b4 and space+b1+b4+b8 seem to do nothing with NVDA.

NVDA seems to have the ability to toggle ATC (see line 714 of brailleDisplayDrivers/handyTech.py) but this seems not to be exposed in the GUI, as either an option in the Braille settings panel or as an input gesture.

Am I missing something obvious?
### Describe the solution you'd like
A GUI or config option to toggle ATC.

### Describe alternatives you've considered
None.

Cc @leonardder, @FelixGruetzmacher.

**Comment by codeofdusk** [comment] 2020-12-21 08:38
Hmmm, so ATC seems to be enabled on the driver level but the display doesn't move to the next line when I reach the end.

```python console
>>> from braille import handler
>>> handler.display
<brailleDisplayDrivers.handyTech.BrailleDisplayDriver object at 0x05B80AD0>
>>> handler.display.atc
True
```

**Comment by leonardder** [comment] 2020-12-21 08:46
There's only support for the ATC toggle in the driver, not for the functionality. Cc @FelixGruetzmacher

**Comment by leonardder** [comment] 2020-12-21 08:47
Closing as duplicate of #4775

**Closed by leonardder** 2020-12-21 08:47 UTC
