### ISSUE TITLE
[Suggestion] suggest NVDA adding a sound alert if it reaches the end

### ISSUE THREAD

**Issue by lstar4ever** [nvaccess/nvda#5936] opened 2016-05-08 10:59 UTC
I found that for Voiceover on IOS device, the Voiceover will have sound alert if the focus is at the end.
And I find this very helpful and hope it can be implemented into NVDA as well.

**Comment by bhavyashah** [comment] 2017-08-24 07:48
Duplicate of #4285

**Comment by ehollig** [comment] 2017-08-24 13:32
Thank you @bhavyashah, I knew there was a duplicate for this, but could not find it. Closing as duplicate

**Closed by ehollig** 2017-08-24 13:32 UTC
