### ISSUE TITLE
Error building NVDA source master

### ISSUE THREAD

**Issue by mg-bledig** [nvaccess/nvda#14000] opened 2022-08-09 08:19 UTC
After cloning the nvda master and running Scons source, the following error occurs:

```cmd
Ensuring NVDA Python virtual environment
call py -m SCons source
scons: Reading SConscript files ...
Warning: Building with 1 concurrent job while 4 CPU threads are available. Running SCONS with the parameter '-j4' may le
ad to a faster build.
scons: done reading SConscript files.
scons: Building targets ...
cl /Fobuild\x86\remote\inputLangChange.obj /c build\x86\remote\inputLangChange.cpp /TP /EHsc /nologo /std:c++17 /Od /MT
/W3 /WX /DUNICODE /D_CRT_SECURE_NO_DEPRECATE /DLOGLEVEL=15 /D_WIN32_WINNT=_WIN32_WINNT_WIN7 /DNDEBUG /Iinclude /Iinclude
\wil\include /Imiscdeps\include /Ibuild\x86 /Z7
inputLangChange.cpp
build\x86\remote\inputLangChange.cpp(17): fatal error C1083: Cannot open include file: 'VersionHelpers.h': No such file
or directory
scons: *** [build\x86\remote\inputLangChange.obj] Error 2
scons: building terminated because of errors.
Deactivating NVDA Python virtual environment
```

I have tried all of the following to try and resolve the issue:

I have performed a submodule sync "git submodule sync --recursive && git submodule update --init --recursive"

all attempts have failed, and have cleaned my copy of the source of currently built files: using "git clean -xdi" and building from scratch again. The problem still persists

**Comment by CyrilleB79** [comment] 2022-08-09 20:33
Hi @mg-bledig

Did you pass the `--recursive` option to the `git clone` command?

**Comment by mg-bledig** [comment] 2022-08-10 08:10
Yes i did

**Comment by seanbudd** [comment] 2022-08-11 06:19
Can you retry setting up your NVDA environment from scratch i.e. reclone, install all dependencies, etc.
It seems likely that the Visual Studio dependencies are not installed correctly.

The log provided is not from a clean build, we need to see a full log from a fresh developer environment.

**Comment by mg-bledig** [comment] 2022-08-11 18:02
> 

I totally revamp my computer. Re-installed MS-Windows 10, re-installed MS-Visual Studio2019, re-installed Python version 3.7.9. Then cloned the nvda- master repository and ran scons source. This time it worked.

What concerns me is what happened. If something broke on my side, what was it so if it happens again, a more easier fix can be implemented. I most certainly will be keeping a watch on this one as I have no idea as to what happen Thanks for the help.
.

**Comment by seanbudd** [comment] 2022-08-12 01:21
Closing this issue as can't reproduce

**Closed by seanbudd** 2022-08-12 01:21 UTC
Labels: component/build
