### ISSUE TITLE
Out of sync focus and virtual cursor if a web dialog sets focus onto a button programmatically.

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#10831] opened 2020-03-02 09:40 UTC
### Steps to reproduce:

1. In Firefox, open a new tab and type about:logins to open the new logins manager.
2. Tab to the list of items and select one with the arrow keys.
3. Tab forward to the Delete button. Notice that as you tab, you hear NVDA go from focus to browse mode.
4. Hit Space to activate the Delete button.
5. After the dialog opens, and NVDA reads the dialog, observe that on the braille display, the Delete button shows to be in focus, and NVDA+Tab also says the Delete button is in focus. Hit Space.

### Actual behavior:

The Cancel button is activated, and the item is not deleted.

### Expected behavior:

The Delete button should be activated and the item deleted.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.3.1.

#### Windows version:

10.0 19H2.

#### Name and version of other software in use when reproducing the issue:

Firefox 73 release, 74 beta, 75 nightly.

#### Other information about your system:

Freedom Scientific Focus display connected.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, 2020.1 Alpha, same behavior.

### More observations

After step 4 above, NVDA starts speaking the dialog top to bottom, and interspersed, speaks the Delete button. It repeats it later when it goes through all the buttons of the dialog. The last item it reads is the Cancel button. The following behavior can be observed:

* A connected braille display shows the Delete button. It does not follow the virtual cursor as NVDA reads the dialog top to bottom.
* NVDA+Tab also reports the Delete button being in focus.
* The button being executed, however, is the Cancel button, since that is the button the automatic reading of the web dialog with browse mode lands on.

At least two questions arise from this:
1. Why does the braille display not follow the reading cursor?
2. Why does NVDA+Tab still report the Delete button to be in focus? The Advanced setting to have the virtual cursor set focus onto items it reads, is the default, not changed to the experimental "Don't focus focusable items" setting.

CC @jcsteh

**Comment by jcsteh** [comment] 2020-03-02 11:12
I haven't tested this yet, but answering your questions:

>     1. Why does the braille display not follow the reading cursor?

Sounds like a bug.

>     2. Why does NVDA+Tab still report the Delete button to be in focus? The Advanced setting to have the virtual cursor set focus onto items it reads, is the default, not changed to the experimental "Don't focus focusable items" setting.

NVDA only focuses things under the cursor when you manually move the cursor. Say all scrolls, but does not focus. The reason is that focus incurs more of a performance penalty and can also be more intrusive if the website does silly things on focus. You shouldn't rely on NVDA+tab as an indicator of what will be activated when you press space or enter, not just because of this but also because of actionable things that aren't focusable.

This one is tricky. On one hand, you want the focus to be honoured. On the other hand, if NVDA always snapped the cursor to the focus in dialogs, a lot of dialogs wouldn't get their context read, which is one of the reasons people were pushing for browse mode in dialogs in the first place.

**Comment by Adriani90** [comment] 2020-10-06 21:30
@MarcoZehe could you please give an update on this, using last Firefox and NVDA 2020.3 RC1, considering Jamie's feedback above?

**Comment by Adriani90** [comment] 2024-11-13 20:11
This issue is not reproducible anymore in NvDA 2024.4.1 and Firefox 132, closing as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-11-13 20:11 UTC
Labels: close/worksforme
