### ISSUE TITLE
Ability to show the minimum and last tested NVDA versions of an add-on in the descriptions of the add on store.

### ISSUE THREAD

**Issue by GeorgeWu3** [nvaccess/nvda#15776] opened 2023-11-12 19:09 UTC
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
It will be nice if the add on store  displays the minimum and last tested NVDA versions of an add-on in the description field. The only way I can check it is to go to the about add on button on a downloaded add on I have installed externally, or I downloaded an add on in Github from the add-on stores github page.

**Comment by Adriani90** [comment] 2023-11-17 23:16
With NVDA 2023.3, In the addon store when you focus an addon and press tab multiple times, there are two edit fields. one for the description and one for "more details". In the edit field for more details you can read the minimum and the last tested NVDA version of the currently focused addon. So it works as expected. Closing as works for me.

**Comment by GeorgeWu3** [comment] 2023-11-17 23:33
Doesn't show up on any of the add-ons when I hit down arrow on the more details field.

**Comment by Adriani90** [comment] 2023-11-18 00:27
Are you looking on addons which are available? or on addons which are incompatible? This information is only available for addons with status incompatible. Fir addons with status "available", the minimum and the last tested NVDA version is the current NVDA version you are running on your system so it doesn't show up in the more details field.

**Comment by GeorgeWu3** [comment] 2023-11-18 00:36
I'm browsing through addons that are compatible.
I wish it shows the minimum and last tested NVDA versions on add-ons that are compatible.

**Comment by Adriani90** [comment] 2023-11-18 10:32
Could you explain more exactly the use case for what you need this? The minimum version and the last tested version are the same when the addon is compatible. And this is the NVDA version you have installed on your system if the addon is shown as compatible.

**Comment by lukaszgo1** [comment] 2023-11-18 14:56
I see several reasons why the info should be shown regardless if the add-on is compatible or not:
- In the old add-ons manager it was possible to show the compatibility range from the about add-on dialog for all add-ons, so the current state can be theoretically considered a regression
- If I have a friend who is, for whatever reason, using older NVDA and I want to recommend a cool add-on I found to them, it is useful to see what is the minimum NVDA version required by the add-on
- When I'm on NVDA 2023.3 and considering upgrade to 2024.1, it is also useful to look at the last tested for my most important add-ons, to asses if I can safely upgrade, or if it is still too early, as my add-ons are not compatible yet

**Comment by GeorgeWu3** [comment] 2023-11-19 03:34
Some people, like me, arcurious to know what is the minimum NVDA version of a particular add on is. That's why.

**Comment by Nael-Sayegh** [comment] 2024-01-12 10:10
Hello,
I agree with @lukaszgo1, the ability to display both the minimum version and the last tested version for an available extension has several advantages.
It would be very interesting to have it shown in the more details field.

**Comment by CyrilleB79** [comment] 2024-01-12 10:46
@Adriani90 wrote:
> The minimum version and the last tested version are the same when the addon is compatible. And this is the NVDA version you have installed on your system if the addon is shown as compatible.

To avoid confusion, I'd like to report that this statement is not correct at all.
For example, I am running NVDA 2023.3 and have Outlook Extended add-on version 2.3. Looking at the manifest, you will see that the minimum compatible NVDA version is 2019.3 and the last tested NVDA version is 2023.1. Still it is running and not incompatible.

@lukaszgo1 has listed various reasons to support the current request. Among those:
> * If I have a friend who is, for whatever reason, using older NVDA and I want to recommend a cool add-on I found to them, it is useful to see what is the minimum NVDA version required by the add-on

This information may be useful in some cases. But beware that this information is not complete to know if you can recommend the add-on to your friend.
E.g. Windows App Essential add-on version 24.01.1 is compatible with 2023.3 only. So running NVDA 2023.3, you will see that the add-on has last tested NVDA version to 2023.3 and min NVDA version to 2023.3.
Though, I am sure that running NVDA 2023.2, you will find an older version of this add-on in the store.

Even if it should not be the main use case, another use case is for add-on developers. As an add-on developer or tester, I do not count anymore the number of time I have had to go to see the manifest of an add-on since the Add-on Store is in place; before, I was using the "About" dialog of the Add-on Manager.

**Closed** 2024-01-23 23:23 UTC
Labels: p5, triaged, feature/addon-store
