### ISSUE TITLE
Modify the function assigned to NVDA + F9 and F10 to allow selecting the text as well as copying

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4636] opened 2014-11-20 19:42 UTC
**Reported by blindbhavya on 2014-11-20 19:42**
Hi,
I have been encountering several situations in recent times, especially in large Word documents where I need to cut a portion of text, or simply select a portion of text to overwrite it with other text.
However, currently, NVDA only allows the user to easily copy text, however, I propose it be modified into selecting text. This would allow easy cutting and overwriting of text, rather than only copying of text.
Hope I was clear enough
**Blocking #5316**

**Comment by feerrenrut** [comment] 2016-06-08 08:14
To clarify the behaviour:
NVDA+F10 (when selection not possible) will report "Can't select, press twice to copy"

The thought behind requiring a double press of F10 to copy rather than auto copying when selection is not posible is to try not to be destructive to the clipboard content.

**Comment by nvaccessAuto** [comment] 2016-06-24 01:39
Incubated in 733ece0cdd2287873117fc5bd8e84d42f1d71adc.

**Comment by derekriemer** [comment] 2016-06-24 04:10
Hi,
After incubating: I tested this in the bash shell provided with git for windows.
error executing script: <bound method GlobalCommands.script_review_copy of <globalCommands.GlobalCommands object at 0x04CD6CD0>> with gesture u"shift+NVDA+'"
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "globalCommands.pyc", line 1774, in script_review_copy
  File "textInfos\offsets.pyc", line 494, in updateSelection
  File "displayModel.pyc", line 559, in _setSelectionOffsets
TypeError: Expanded selections not supported

STR:
1. Open git bach.
2. issue the yes command, and then after half a second, type ctrl+c. Alternatively, just type git log or something that produces output.
3. Go to a point in the output, nvda+f9.
4. go to a later point, nvda+f10.
Thanks.

**Comment by nvaccessAuto** [comment] 2016-06-24 07:29
Incubated in 50cf2623afb120faebbd3e92c54c38ec585c192a.

**Comment by feerrenrut** [comment] 2016-06-24 07:32
Thanks @derekriemer. This should now be fixed.

**Comment by jcsteh** [comment] 2016-08-05 02:29
Merged in 5b51eae.

**Closed by jcsteh** 2016-08-05 02:29 UTC
Labels: enhancement, goodForNewDev, incubating

**Comment by leonardder** [comment] 2016-08-24 12:47
Honestly, I think the following string is slightly vague:
"Can't select text, press twice to copy"
I'm afraid it is not clear enough that, even though the text is not selected, it is yet marked for copying. I'd like to suggest to make this more clear in an alternative string, which can be included in 2016.4. I'm sorry I did not report this before the translation freeze.

**Comment by leonardder** [comment] 2016-08-24 12:53
Also, I belief that "Press twice to copy or reset the start marker" is not clear. "Or" should be "and", and "reset" should be "remove or empty".

**Comment by jcsteh** [comment] 2016-08-24 12:59
Bleh, English ambiguity. It doesn't mean pressing twice will do both. It 
means either you should press twice to copy, or alternatively, you 
should reset the start marker (with NVDA+f9). We can't say "NVDA+f9" 
because the binding might have changed and/or there might be multiple 
bindings.

**Comment by leonardder** [comment] 2016-08-24 13:18
Ah, so now I understand. But, either I"m just stupid, or it is really not very clearly chosen. It is at least ambiguous as you say indeed. I thought it had to be "and" since pressing nvda+f10 twice both copies to the clipboard and resets the start marker to the initial, undefined state.
How about something like "Press twice to copy or initiate a new selection by resetting the sart marker"?

**Comment by jcsteh** [comment] 2016-08-24 22:24
I agree it needs clarification. The challenge here is that we want to 
keep these messages brief, but brevity and ambiguity are often enemies. :)

**Comment by mohdshara** [comment] 2016-08-25 08:45
Hi.
instead of "Can't select text, press twice to copy", why not say "text marked, press twice to copy".

I can confirm that in Firefox upon selecting text this way NVDA stays silent. I also experience times when NVDA stays silent in notepad once you select this way. However, in notepad there's no reliable way to reproduce.

**Comment by jcsteh** [comment] 2016-08-26 09:32
> instead of "Can't select text, press twice to copy", why not say "text marked, press twice to copy".

Because that doesn't explain why the first press didn't actually achieve anything. The command is documented as selecting text on the first press. If it just said "Text marked", the user would wonder why it wasn't selected. Saying "Can't select text" makes it clear that it isn't possible in this case.

> I can confirm that in Firefox upon selecting text this way NVDA stays silent.

I'm addressing that in #6307.

**Comment by derekriemer** [comment] 2016-08-26 21:42
Hi:

The eclipse thing can be disregarded. Somehow it is working today, when 
it failed yesterday, no clue why.


On 6/24/2016 1:32 AM, Reef Turner wrote:
>
> Thanks @derekriemer <https://github.com/derekriemer>. This should now 
> be fixed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/4636#issuecomment-228276894>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivWXFdyvhvbgUQpxzEzvk5zsBUeaiks5qO4gFgaJpZM4IwtBM>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194
