### ISSUE TITLE
Blank cells cause NVDA not to read all headings in Excel 2010 in Windows7

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5139] opened 2015-06-03 23:13 UTC
**Reported by andrewd on 2015-06-03 23:13**
None

**Comment by ehollig** [comment] 2017-10-18 14:45
@feerrenrut, it appears the post in https://github.com/nvaccess/nvda/issues/5139#issue-116050601 is unavailable. I am not quite sure what the original post is requesting, but all headers read correctly in the attached document in Excel 2016

**Comment by feerrenrut** [comment] 2017-10-19 03:58
Thanks @ehollig. Could you add what you did when trying to reproduce this and close the issue as "works for me"

**Comment by ehollig** [comment] 2017-10-19 14:34
1. Open the [sample.xlsx](https://github.com/nvaccess/nvda/files/1395025/sample.xlsx)
2. Press down arrow to "A6". NVDA reads "5".
3. Press right arrow. NVDA reads the cell headers, including, "First name", "Phone", "Email", "In person", "Connect", etc.
4. Navigate with the arrow keys to "J21". NVDA reads, "20  has formula  J21  Comments"
5. Press left arrow. NVDA reads each header and the cell contents, including, "Connect count", "In person count", "Confirmed", "Connect", "In person", etc.

All seems like expected behavior to me. Closing as worksforme

**Closed by ehollig** 2017-10-19 14:34 UTC
Labels: bug, Microsoft Office support
