### ISSUE TITLE
Make it possible for Input Gestures dialog to present gestures in context sensitive and comprehensive collections

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#15715] opened 2023-10-30 13:34 UTC
### Is your feature request related to a problem? Please describe.
When the time comes to edit input gestures, I often wish to do this for gestures that are not contextually usable.  A good example of this is the new browse mode gestures to move to next/previous tab, group, or article.  I just want to hop into Input Gestures and be able to get to these gestures whether they can be used in the current context or not in order to assign them, whether I can use them at this very moment or not.

### Describe the solution you'd like
I would love to see a radio button grouping above the Filter edit box for two states: Context Sensitive and All Input Gestures

### Describe alternatives you've considered
The other option I've considered is just removing context sensitivity entirely for the Input Gestures dialog, as I am seldom looking for an input gesture that "only applies in my current context."  I almost always open at what amounts to a random time to assign or deassign a gesture whether it's appropriate for what I'm doing at that very moment or not.

### Additional context
I believe this is why issues such as #15711 arise.  I have not as yet been able to find that option because I've not been "in the right context" for it to appear when working with the Input Gestures dialog.  I just want to be able to get at whatever input gesture I'm seeking to tweak at any time the Input Gestures dialog is invoked, or at least have that option rather than the presented gestures only being appropriate for the current context.

**Comment by LittleStar-VIP** [comment] 2023-10-31 05:40
I am also loking for an input dialogue that is not context sensitive, so that I can easily look for all the available input gestures.

If some users prefer the current layout, could we just adobt the layout like the current addon store, which we can show addons of specific channel. 
So for input gesture, there can also be an option to show all input gestures, show input gestures only available at the current context.

**Comment by audiogamer22** [comment] 2023-12-10 17:24
I agree that this would be useful. We should have as much control over our screen reader as we can and tweeking it like this would be nice.

**Comment by Adriani90** [comment] 2024-03-27 21:01
Closing as duplicate of #10775.

**Closed by Adriani90** 2024-03-27 21:01 UTC
Labels: close/duplicate, p5, feature/input-gestures, triaged
