### ISSUE TITLE
Possible to get huge amounts of non-existent lines of spaces on certain webpages

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13352] opened 2022-02-17 01:53 UTC
### Steps to reproduce:
1. Turn on indent reporting in NVDA
2. Go to the following website: https://banana-cream-pi.github.io/about.html. Note: I've seen this in other places, but this is just the most recent one.
3. Hold up arrow.
4. After doing that for a few seconds, press down arrow again.
### Actual behavior:
A ton of blank spaces are reported that don't actually exist. Pressing down arrow returns you to the actual page content.
### Expected behavior:
I'm not sure what HTML magic is happening in these cases, but NVDA should handle them gracefully, like it does with all other websites.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.3.1
#### Windows version:
Windows 10 21H1 (x64) build 19043.15264
#### Name and version of other software in use when reproducing the issue:
The Brave web browser.
#### Other information about your system:
N/a
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I've seen this on a few older versions, but I can't recall them off the top of my head.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Qchristensen** [comment] 2022-02-17 03:42
This page has the word "ABOUT" written using ASCII text on ten lines using 8's and full stops and gravs `.  The line above and the line below this word seem to extend the same width, but made entirely of spaces.  So effectively there is a whole bunch of screen reader irrelevant text, not just the spaces.

The text is formatted as <PRE> (Preformatted) which specifically preserves spaces.  

I don't have an answer offhand for why up arrow in this instance is only moving back one space though.

**Comment by TheQuinbox** [comment] 2022-02-17 04:33
I saw a discussion on Twitter, where I think it was @jcsteh said it was an issue with something relating to virtual buffers. Not sure though

**Comment by jcsteh** [comment] 2022-02-17 04:40
Yeah, this happens if there are more than 100 (or browse mode max chars per line) spaces on a line. There's probably another issue open for this already, but I'm not sure. It's probably a bug [somewhere around here](https://github.com/nvaccess/nvda/blob/7afc3ed/nvdaHelper/vbufBase/storage.cpp#L1173).

**Comment by CyrilleB79** [comment] 2022-02-17 08:10
Maybe related to #13317?

**Comment by zahra21** [comment] 2022-08-09 17:20
hi. i confirmed it.
nvda 2022.1 portable.
firefox 102 32 bit.

**Comment by CyrilleB79** [comment] 2023-12-14 21:16
Closing as duplicate of #2812 (and #13317)

**Comment by CyrilleB79** [comment] 2023-12-14 21:17
Closing as duplicate of #2812 (and #13317)

**Closed by CyrilleB79** 2023-12-14 21:16 UTC
Labels: blocked/needs-sample
