### ISSUE TITLE
Add search / filter to speech dictionary

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13918] opened 2022-07-18 09:27 UTC
### Is your feature request related to a problem? Please describe.

Requested by Andrzej via email:  He has added numerous entries to his speech dictionary and would love to have the ability to easily find an entry.

### Describe the solution you'd like

My suggestion is a filter box similar to the input navigation dialog.

### Describe alternatives you've considered

A "Search" edit could also work, but since we already have a "filter" in other dialogs, a filter would be consistent.

**Comment by CyrilleB79** [comment] 2022-07-18 10:33
This is a duplicate of #2478. Thanks.

**Comment by seanbudd** [comment] 2022-07-18 22:33
Closing as duplicate of #2478

**Closed by seanbudd** 2022-07-18 22:33 UTC

**Comment by Qchristensen** [comment] 2022-07-19 01:21
Thanks - sorry I missed it when I originally searched!
