### ISSUE TITLE
NVDA not reading the equation fields in microsoft word

### ISSUE THREAD

**Issue by Aarushb** [nvaccess/nvda#12966] opened 2021-10-20 20:08 UTC
### Steps to reproduce:
1. Open a blank word document. (word 2013 or higher)
2. Press 'ault+equals' to open up the equation field.
3. Type something like '\alpha ' or '\sqrt 2' and then press enter. Clearly, it doesn't read them the way it should.
4. Now go to NVDA menu>settings>advanced>'Use UI Automation to access Microsoft Word document controls when available  check box  checked  Alt+w'
5. After doing this, try the steps above and NVDA will now read all the equations and symbols in the field.
### Actual behavior:
'2'
### Expected behavior:
'link    Equation  page 6  baseline  square root of 2'
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.2
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
MS word(office 365)
#### Other information about your system:
Core I7 third generation, 8 GB ram.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All versions starting from 2019.1 , similar behavior.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
##extra information
NVDA seems to perform better overall with the above setting enabled, and is a lot more responsive. With it off, there is a noticeable delay when interacting with word to this day, but there are also some nasty bugs when having it on such as NVDA not reading auto-numberring, table sells, etc. It would be nice if everything could be integrated into the sr by default  itself without having the advance features on.
[bug_sample.docx](https://github.com/nvaccess/nvda/files/7384001/bug_sample.docx)
This is a docx file with a sample equation, as well as the equation's content in plaintext.

**Comment by seanbudd** [comment] 2021-10-20 22:43
Closing this as it's a duplicate of #4631 - please do test this with alpha, or 2021.3 beta when it is released.

**Closed by seanbudd** 2021-10-20 22:43 UTC
