### ISSUE TITLE
when enabling or disabling browse mode in chrome, page google.com i have this error

### ISSUE THREAD

**Issue by nunotfc** [nvaccess/nvda#14375] opened 2022-11-15 10:19 UTC
### Steps to reproduce:
1. Open google chrome.
2. open the page google.com, or https://www.google.pt
3. set browse mode to manual.
4. focus in an editable field and press space.
5. type something, delete 3 or 4 characters, press arrow up and down keys, and press escape.
I can leave browse mode, but an error sound comes, and this log message apears, sometimes, i can't navegate trough searchc suggestions in the same edit box, just trowing this error.
### Actual behavior:

NVDA throwing error when browse mode is activated or deactivated randomly, not all times it happens, and can't navigate through suggestions inside an edit box

### Expected behavior:

NVDA should enter and exit browse mode without any problems and let to choose the suggestions. for example, if searched "how i can do" i would be able to select with arrow keys the "food" suggestion.

### NVDA logs, crash dumps and other attachments:
```
ERROR - eventHandler.executeEvent (10:02:32.885) - MainThread (9380):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x08690430> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "browseMode.pyc", line 1345, in event_caret
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 255, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1649, in event_caret
  File "NVDAObjects\__init__.pyc", line 1254, in event_caret
  File "review.pyc", line 178, in handleCaretMove
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 120, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 232, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Erro não especificado', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (10:02:32.892) - MainThread (9380):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x08690430> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "browseMode.pyc", line 1345, in event_caret
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\behaviors.pyc", line 255, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1649, in event_caret
  File "NVDAObjects\__init__.pyc", line 1254, in event_caret
  File "review.pyc", line 178, in handleCaretMove
  File "documentBase.pyc", line 74, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 120, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 232, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Erro não especificado', (None, None, None, 0, None))
```

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
2022.4 beta 3
#### Windows version:
Windows 11 Version 22H2 (build 22621.819) 64 bit

#### Name and version of other software in use when reproducing the issue:
Google chrome 107.0.5304.107 (64 bits)
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, 2022.3, all betas and recent alphas
#### If NVDA add-ons are disabled, is your problem still occurring?
yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes.

**Comment by seanbudd** [comment] 2022-11-15 23:12
Welcome @nunotfc ,

We are unable to process this issue as it stands.

Please fill out the issue template fully. What is the expected behaviour in this situation? Does this issue prevent you from performing a task? NVDA betas log errors with errors sounds, but in cases like these it is possible that error is not an issue, and the warning should be suppressed.
What is the version of Chrome you are using?

Kind Regards,
NV Access Software Developers

**Comment by feerrenrut** [comment] 2022-11-22 03:42
@seanbudd Information on the issue was hidden on this issue, it was within the HTML comment blocks: `<!--  here -->`. I've moved it out of these blocks.

**Comment by michaelDCurran** [comment] 2022-11-22 03:45
I'm unable to reproduce this.
Can you please attach an NVDA log set to debug showing the issue being reproduced.

**Comment by nunotfc** [comment] 2022-11-22 12:25
[nvda.log](https://github.com/nvaccess/nvda/files/10067323/nvda.log)

**Comment by CyrilleB79** [comment] 2023-01-19 12:21
@seanbudd the requested information has been provided. Could you remove blocked/needs-info label please?

**Comment by Adriani90** [comment] 2023-03-10 20:57
Closing as duplicate of #8968.

**Closed by Adriani90** 2023-03-10 20:57 UTC
Labels: close/duplicate, p1, triaged, blocked/needs-technical-investigation
