### ISSUE TITLE
NVDA does not report address bar autofill in Firefox

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#9340] opened 2019-03-02 16:58 UTC
### Steps to reproduce:
1. Install the latest version of Firefox.
2. Launch it and press Control+L to go to the address field.
3. Start typing an URL address of a previously visited or bookmarked website.

### Actual behavior:
Firefox starts automatically completing the URL address, but NVDA does not report the auto-completion.

### Expected behavior:
NVDA should report the auto-completion done by Firefox.

### System configuration
- Operating system: Windows 10 Pro version 1809 (build 17763.316), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-16874,8573a05b, in bulgarian.
- Firefox version: 65.0.2, 32-bit, in bulgarian.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

#### Notes:
This is a regression, maybe in Firefox itself. It was working better in earlier versions of the browser. It starts working normally after the focus goes someplace else and then returns to the address bar (e.g. by pressing ALT once to go to the menu bar and pressing it once again to return to the address bar).

**Comment by DrSooom** [comment] 2019-03-03 13:04
CC: @michaelDCurran, @jcsteh and @MarcoZehe

**Comment by jcsteh** [comment] 2019-03-03 23:41
There are two kinds of autocompletion that occur:

1. Suggestions. These appear in a dropdown list and the active suggestion is highlighted. Prior to Firefox 64, the active suggestion would keep getting focus whenever you typed, but this caused excessive verbosity and meant that, for example, pressing backspace wouldn't report the character you erased (because the text box no longer had focus).
2. Autofill. As well as the suggestions, the URL for the active suggestion is automatically filled into the text box. The autofilled part is selected so that when you type more text, you erase the autofilled portion, making way for a new suggestion. As an example of how NVDA announces this, if I type "go" in my address bar, NVDA says "selected ogle.com/", indicating that in addition to my "go", Firefox filled "ogle.com/", making "google.com/".

By default, both of these are enabled. As noted in point 1 above, suggestions are no longer automatically focused because this creates problems. You can investigate the suggestions by pressing down/up arrows. However, autofill is still reported for me as described in point 2 above (though I personally turn this off normally).

Are you talking about suggestions or autofill?
Is autofill not being reported for you?
Did you perhaps disable autofill? You can check by going to about:config and looking for browser.urlbar.autoFill. It should be true if it is enabled.
Do suggestions get reported for you when you press down/up arrows?

**Comment by k-kolev1985** [comment] 2019-03-04 07:30
@jcsteh I'm talking about autofill. And yes, it is enabled in about:config - I just checked (besides that - I can see that the browser autofills the address as I type). Autocomplete suggestions in the drop-down list read when I use up/down arrow keys. But to make NVDA read the autofill initially, I have to move the focus out of the address bar (e.g. go to the menu bar with ALT) and return back to the address bar - then NVDA reads autofill. And BTW - when reading of autofill does not work, pressing the NVDA command to read the current line, NVDA reports "blank".

**Comment by jcsteh** [comment] 2019-03-05 03:12
Thanks for the info. I can't seem to reproduce this. Do you have any NVDA add-ons enabled? If so, could you please test with them disabled? Thanks.

**Comment by k-kolev1985** [comment] 2019-03-05 07:44
I've tried with NVDA add-ons disabled, but it is the same. I then tried with browser add-ons disabled - still the same. I don't know what's going on...

**Comment by DrSooom** [comment] 2019-03-05 17:55
Please maximaze the Firefox window with Win+ArrowUp and try again.

**Comment by k-kolev1985** [comment] 2019-03-05 18:40
If I'm not mistaking, in programs like Firefox and in cases such as this, it shouldn't matter - the information in question is not captured via the so called "on-screen model". Even if I'm wrong about this, my Firefox window is maximized (it always is).

**Comment by DrSooom** [comment] 2019-03-06 08:22
Could you please download [Firefox Portable 65.0.2](https://portableapps.com/apps/internet/firefox_portable) and try it with a clean potable version of Firefox too?

**Comment by k-kolev1985** [comment] 2019-03-06 12:35
@DrSooom No, the issue does not occur with the portable copy of Firefox. So, it is probably something in my Firefox configuration. But what - that is the million dollar question... :-)

**Comment by k-kolev1985** [comment] 2019-03-06 15:01
@DrSooom The first 2 are present in my copy of Firefox and are set to "true". Setting the 2nd one to "false" disables autofill, which feature I actually want to use and is the one discussed in this ticket.

The last two ones are not present in my copy of Firefox.

**Comment by DrSooom** [comment] 2019-03-06 16:05
That's because I was searching on Firefox 56.0.2, which I want to update very soon – hopefully after the next backup.

**Comment by jcsteh** [comment] 2019-10-22 23:36
Probably https://bugzilla.mozilla.org/show_bug.cgi?id=1590216

**Comment by jcsteh** [comment] 2020-02-26 06:45
Fixed in Firefox 74 (currently in beta).

**Closed by jcsteh** 2020-02-26 06:45 UTC
Labels: Firefox, needsExternalFix
