### ISSUE TITLE
Automatic reading of subtitles does not work for certain YouTube videos

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#10625] opened 2019-12-14 20:33 UTC
I've noticed that there are certain YouTube videos where NVDA does not automatically read the subtitles. I know that the subtitles are there because they can be seen if you arrow around toward the top of the video player.
In order to read them, you have to continuously check that part of the page to see if it has changed. Unfortunately, I'm not sure what is different about certain videos that causes NVDA to ignore the subtitles.
I'll provide an example of a video where the subtitles read automatically, as well as one where they do not.

### Steps to reproduce:
- Open [this video.](https://www.youtube.com/watch?v=o4gEmLpxHHk)
- Toggle on the subtitles option and press play.

### Actual behavior:
NVDA does not automatically read the subtitles as they appear. 

### Expected behavior:
NVDA should read the subtitles automatically. For an example, use [this video](https://www.youtube.com/watch?v=XVQlnP5Yu2A) instead.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
8.1

#### Name and version of other software in use when reproducing the issue:
Tested with Firefox 71.0 and Google Chrome 79.0.3945.79

#### Does the issue still occur after restarting your PC?
Yes. It's been an issue for a long time.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I know the issue occurs in previous versions of NVDA, but I haven't done any specific testing. This definitely isn't a new issue.

**Comment by Adriani90** [comment] 2023-05-06 00:08
Closing as duplicate of #8337.

**Closed by Adriani90** 2023-05-06 00:08 UTC
Labels: close/duplicate
