### ISSUE TITLE
MUI Stepper not working in Firefox (on laptop monitor) when NVDA is running

### ISSUE THREAD

**Issue by haze9greg** [nvaccess/nvda#13088] opened 2021-11-23 19:41 UTC
### Steps to reproduce:
1. Plug in dock to laptop, and on laptop screen...
2. Turn on NVDA
3. Open link in Firefox: [MUI Non-linear stepper](https://v4.mui.com/components/steppers/#:~:text=NEXT-,Non%2Dlinear,-Non%2Dlinear%20steppers)
4. Tab to one of the steps
5. Click Space or Enter on the step

### Actual behavior:
- Stepper loses focus
- Scroll jumps to top of screen
- Step is not accessed, new step content is not shown

### Expected behavior:
- New step should retain focus and become active step
- New step content should be displayed
 

#### NVDA version:
2021.1

#### Windows version:
10

#### Name and version of other software in use when reproducing the issue:
- Firefox 94.0.2

#### Other information about your system:
- Laptop screen
- NVDA running

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2024-03-18 21:49
@haze9greg are you reproducing this in focus mode? Or in browse mode? In browse mode I don't see any loss of focus, but in focus mode NVDA reads the title of the page and not the step.
cc: @jcsteh any suggestions here?

**Comment by Adriani90** [comment] 2024-11-28 21:33
Ok I manages to reproduce this in focus modem, but it seems we can close this as invalid. The focus management is incorrect since after pressing all the next steps, after the last step, the focusable element disappears and the focus is redirected to something without a tabindex (e.g. plain text, progress bar, unabailable next button etc. So for the focus redirection you should use something else after the steps are completed 8e.g. a promt dialog, a focusable unavailable button with tabindex etc.

Closing as invalid since this is related to web authoring error.

**Closed by Adriani90** 2024-11-28 21:33 UTC
Labels: close/invalid
