### ISSUE TITLE
Add table location (when in a table) announced by report current location

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5921] opened 2016-05-03 01:48 UTC
When in a table (in Word or on the Web), there is currently no way of checking which row / column you are in short of moving to another cell (or in Word, moving to another program and back).

**Comment by derekriemer** [comment] 2016-05-03 02:15
Confirmed.


On 5/2/2016 7:48 PM, Quentin Christensen wrote:
>
> When in a table (in Word or on the Web), there is currently no way of 
> checking which row / column you are in short of moving to another cell 
> (or in Word, moving to another program and back).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5921>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by ehollig** [comment] 2017-09-12 23:07
Closing, as this sounds like a duplicate of #3462.

**Closed by ehollig** 2017-09-12 23:07 UTC
