### ISSUE TITLE
Bug of NVDA 2024.2 and 2024.1

### ISSUE THREAD

**Issue by EricD30** [nvaccess/nvda#16853] opened 2024-07-14 09:34 UTC
Hello, 
For a few months, approximately the update of NVDA2024.1, I have a compatibility problem between NVDA and my entire MICROSOFT account (Microsoft 365, Edge, OneDrive). How can this problem be solved? Is it widespread? Thank you 

#System configuration
#--------------------------
#### Other information about your system:Computer HP ZBook Fury G10 16" with Microsoft Windows Defender. Testing was conducted with NVDA 2024.2, NVDA 2023.3.4, and Microsoft Office 365.

#Other questions
#---------------------

**Comment by a11yChief** [comment] 2024-07-14 15:27
When you say a compatibility problem, could you please be more specific about the actual behaviour you're seeing, both before and after the update that caused the behaviour to change?

As in, is something now not being read when it used to be, and if you downgrade to the older version that previously worked, is it still the case that it works as expected?

Anyone working on this project will need way more specific detail to fix the issue.

**Comment by EricD30** [comment] 2024-07-14 18:55
At the NVDA level itself, there are no problems except when the computer "comes out" from standby. But it seems, after some basic tests, that NVDA has an impact on the Microsoft account login of Windows and its associated services.

**Comment by EricD30** [comment] 2024-07-14 18:55
Otherwise NVDA as such works cleanly

**Comment by josephsl** [comment] 2024-07-14 19:23
Hi, are you talking about login prompt (after returning from standby)? To make sure, please give us steps to reproduce so people can help you troubleshoot it. Thanks.

**Comment by Adriani90** [comment] 2024-07-14 19:27
What exactly is the impact about? Is it a crash?, Or is something different with the keyboard?
If the later, then this is expected behavior because NVDA starts in browse mode in the login window.

**Comment by josephsl** [comment] 2024-07-14 19:29
HI, the browse mode note applies when signing into Microsoft services using an MSA (Microsoft Account). I assume login prompt because the original poster talked about standby, which does not use browse mode at all. Thanks,

**Comment by Adriani90** [comment] 2024-07-14 19:47
We need exact steps to reproduce, actual behavior and expected behavior.
Me at least I cannot reproduce any issue with my MS 365 account. I guess without clear issue description this issue cannot be investigated further.

**Comment by EricD30** [comment] 2024-07-14 19:56
There are two parallel problems. The first is that "blocks" all Microsoft services and the second is that NVDA does not restart when waking from sleep. The second one is probably a configuration problem

**Comment by josephsl** [comment] 2024-07-14 20:08
Hi, for the second issue, if it concerns NVDA not speaking when you wake the computer up, then it might be something documented here recently. As for the first problem, as Adriani and others pointed out, we need more info such as exact steps to reproduce (complete with keyboard input and NVDA’s speech/braille output), what you were trying to do, what NVDA is doing instead, and being more specific about what you mean by “cannot access Microsoft services”. If we (NVDA developers) cannot get an answer to any of these in a more concrete manner, then we can either wait until we get answers from you, revisit this issue after several months to years, or close it. Thanks.

**Comment by EricD30** [comment] 2024-07-14 20:14
Traduire du texte avec votre appareil photo
There are no specific actions. When NVDA 2024.1 or 2024.2 is launched, access to all Microsoft services is blocked but as soon as version 2023.3.4 is installed there are no more problems

**Comment by Adriani90** [comment] 2024-07-14 20:29
Do you get any warning dialog popping up? Something like access denied?Can you start Microsoft Word for example?What hapens exactly when you want to access your Microsoft account?Are you trying to access your account via the Internet browser?Where did you download NVDA from?Are all your add-ons disabled in NVDA?Von meinem iPhone gesendetAm 14.07.2024 um 22:14 schrieb EricD30 ***@***.***>:﻿
Traduire du texte avec votre appareil photo
There are no specific actions. When NVDA 2024.1 or 2024.2 is launched, access to all Microsoft services is blocked but as soon as version 2023.3.4 is installed there are no more problems

**Comment by josephsl** [comment] 2024-07-14 20:33
Hi,

Okay, at least that narrows down the scope a bit. Try:

1. Launch NVDA 2024.2 (or even better, try with NVDA 2024.3 beta 2).
2. Notice that you can't access Microsoft services.
3. Press NVDA+F1 to open log viewer, then select all, copy the selection, paste it into a new file and upload the just pasted log file as an attachment.

We need the log to help us get a better idea of what's going on. Once we parse the first log, we will ask you for a debug log so we can figure out exactly what was going in terms of input and output. Or, even better, you can submit the debug log right now (install NVDA 2024.3 beta 2 or create a portable copy of it, start NVDA, then restart NVDA with debug logging enabled (NVDA+Q, then select the last option)).

Another reason for analyzing the log: I wonder if this is the same problem reported elsewhere where NVDA thinks it is running on unsupported Windows release when in fact you are indeed running a supported Windows release. If not, then it makes it a bit harder to pinpoint exactly what happened in 2024.1 release to cause this oddity.

Thanks.

**Comment by Adriani90** [comment] 2024-07-15 08:29
I am closing this one since the template has not been filled with important info helping investigate. If you want to check whether this problem is widely spread, please use the NVDA mailing list on groups.io
Otherwise please open a new issue with clearer information according to the template.

**Closed by Adriani90** 2024-07-15 08:29 UTC
Labels: close/invalid
