### ISSUE TITLE
`ui.browseableMessage()` broken since alpha-21356,ae4ea8f9

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#11834] opened 2020-11-17 07:07 UTC
### Steps to reproduce:
1. Open the NVDA Python console (default: NVDA+CTRL+z).
2. Execute the following instructions:
   `import ui;ui.browseableMessage("This is a test!", "Test")`

### Actual behavior:
NVDA crashes with the following in the log:

```
CRITICAL - watchdog._crashHandler (07:43:28.223) - Dummy-5 (12140):
NVDA crashed! Minidump written to C:\Users\andre\AppData\Local\Temp\nvda.log\..\nvda_crash.dmp
INFO - watchdog._crashHandler (07:43:30.437) - Dummy-5 (12140):
Listing stacks for Python threads:
Python stack for thread 12140 (Dummy-5):
  File "watchdog.pyc", line 213, in _crashHandler
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 4144 (virtualBuffers.MSHTML.VirtualBuffer.loadBuffer):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "virtualBuffers\__init__.pyc", line 444, in _loadBuffer

Python stack for thread 10748 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x05BCACD8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 12044 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 120, in _watcher

Python stack for thread 10612 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 7352 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 315, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 3700 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2187, in func

Python stack for thread 13092 (MainThread):
  File "nvda.pyw", line 247, in <module>
  File "core.pyc", line 568, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1062, in Notify
  File "core.pyc", line 538, in run
  File "queueHandler.pyc", line 88, in pumpAll
  File "queueHandler.pyc", line 55, in flushQueue
  File "eventHandler.pyc", line 65, in _queueEventCallback
  File "eventHandler.pyc", line 241, in executeEvent
  File "eventHandler.pyc", line 284, in doPreGainFocus
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1121, in event_focusEntered
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 762, in _get_name
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

INFO - watchdog._crashHandler (07:43:30.438) - Dummy-5 (12140):
Restarting due to crash
```

### Expected behavior:
No crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-21359,aecff99a

#### Windows version:
10 Insider (64-bit) build 20251.1

#### Name and version of other software in use when reproducing the issue:
Reproducible with NVDA+f when quickly pressed two times in Word, Firefox, etc. And in a lot of other situations.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Bug introduced in a recent alpha build.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by JulienCochuyt** [comment] 2020-11-17 09:16
I confirm I can reproduce the described error with latest alpha 21364 as well as running from source.
Note the error is not confined to the Python console. It can also be triggered by using `NVDA+f` twice quickly to report formatting.

**Comment by CyrilleB79** [comment] 2020-11-17 09:28
This issue seems a regression from PR #9079 (commit ae4ea8f90420d1c00afa251f90abc2b59f35f826).
Cc @derekriemer

**Comment by CyrilleB79** [comment] 2020-11-17 09:29
Additional note: this issue also occurs when using Internet Explorer.
Seems normal since ui.browseableMessage opens an IE-like window.

**Comment by josephsl** [comment] 2020-11-17 09:35
Hi, confirmed. @DerekRiemer, I think it may have started with MSHTML code edits you made to refactor live region handling. To check, run an alpha snapshot built last week, not this week. Thanks.

**Comment by gregjozk** [comment] 2020-11-17 12:29
confirmed in Firefox with nvda+f twice quickly (alpha 21356...)

**Comment by gregjozk** [comment] 2020-11-17 12:31
and also in Chrome

**Comment by amirsol81** [comment] 2020-11-17 14:39
For the record, the last alpha which doesn't exhibit this issue is 21351. It started with 21356 as mentioned in #11834

**Comment by gregjozk** [comment] 2020-11-17 19:33
oh sorry for spamming. did not read title of an issue.

2020-11-17 15:39 GMT+01.00, amirsol81 <notifications@github.com>:

**Comment by leonardder** [comment] 2020-11-18 06:57
@derekriemer took his hands off this pr, so strictly spoken, I am sort of responsible now...
I'm working on a pr that reverts the changes from #9079 related to mshtml. That gives us the time to investigate the underlying issue. I think it is too much to revert the complete pr.

**Comment by beqabeqa473** [comment] 2020-11-19 06:36
hi.

i faced a problem today and bysected an issue.
wanted to open an issue but saw already openned one.

commit ae4ea8f90420d1c00afa251f90abc2b59f35f826 broke previous behaviour.

**Comment by feerrenrut** [comment] 2020-11-20 08:20
Is anyone willing to share the minidump so we can look into the cause of this?

**Comment by feerrenrut** [comment] 2020-11-20 08:29
Re-opening this issue, it would be good to get to the bottom of this and reintroduce feature.

**Comment by beqabeqa473** [comment] 2020-11-20 08:31
Hello.

here is a dump

https://gozaltech.org/Files/nvda_crash.dmp

**Comment by gregjozk** [comment] 2020-11-20 08:44
[nvda logs and dumps.zip](https://github.com/nvaccess/nvda/files/5572287/nvda.logs.and.dumps.zip)

minidump and logs on debug warnings level
this one has been done in ff but same was seen also in chrome. not tested in word or other programs.

note: pr, which reverts some changes, fixes it in chrome and ff.

**Comment by feerrenrut** [comment] 2020-11-24 09:10
To be clear, the issue was resolved with ["Revert live region changes to mshtml virtual buffer #11838"](https://github.com/nvaccess/nvda/pull/11838). However, it also reverts the feature. I'm keeping this issue open so that we can understand what cased the problem and reintroduce the feature with any fixes required.

**Closed** 2020-11-30 09:19 UTC
Labels: bug/crash
