### ISSUE TITLE
nvda is slower to start in login window

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7682] opened 2017-10-23 02:19 UTC
When I was using windows 10 build 15063 64bits when turning on the computer when it was displayed the window to enter the password of entry in windows nvda took a maximum of 2 seconds to read.
I have now upgraded to build 16299.19 64bits and right after the computer shows the window to enter the password the nvda for some time it takes up to 30 seconds to start reading the logon window.
Does anyone else have this feature?
And someone from the experts could investigate?
In the rest the machine runs at good speed.
I did not change the machine, I just updated the windows.
### Steps to reproduce:
NVDA version:
14541
NVDA Installed or portable:
instaled
Other information:
Windows version:
windows 10 16299.19 
Have you tried any other versions of NVDA?
> Please list them and the result
yes

**Comment by leonardder** [comment] 2017-10-24 05:25
Could you please re-enable the "Use NVDA on the Windows logon screen (requires administrator privileges)" setting in the general settings? And, with re-enable, I mean disabling it, pressing ok, reopening the dialog and enabling again. Curious if the problem still persists after that. This problem doesn't sound familiar to me, even though I'm using two systems with this build.
cc @JosephSL

**Comment by fernando-jose-silva** [comment] 2017-10-24 10:26
Thank you for checking and ripped.


Enviado do meu iPhone

Em 24 de out de 2017, à(s) 03:25, Leonard de Ruijter <notifications@github.com> escreveu:

**Comment by Brian1Gaff** [comment] 2017-10-24 12:34
No but I have found on at least one machine that windows is slow to enable 
sound in any way shape or form making one think its sluggish. I've seen it 
on 7 and 10.
 I now don't bother with a log in, but when I did the only fix was to use 
that old program that compressed the registry files that we used to use on 
XP.
 Something to do with the way things load at start up perhaps?
 Just a thought.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by fernando-jose-silva** [comment] 2017-10-25 12:50
I unchecked and re-marked the beginning of nvda in the login window, and now nvda takes about 12 seconds to talk.
Thank you very much.

**Comment by Adriani90** [comment] 2019-04-30 22:10
@fernando-jose-silva are you still having this issue in Windows 10 1809 Update with NVDA 2019.1.1?

**Comment by fernando-jose-silva** [comment] 2019-05-01 02:14
I believe that it can close the call, everything works at a reasonable speed now.
everything updated:
nvda 17110
windows 10 18362.

**Comment by Adriani90** [comment] 2019-05-01 08:07
Closing as works for me. Fernando you can also close issues which you created by yourself if you notice that they are not reproducible anymore. Just write a comment on those issues how you tested and press "close and comment". Thanks very much for your availability, this is very appreciated!

**Closed by Adriani90** 2019-05-01 08:07 UTC
Labels: worksforme
