### ISSUE TITLE
NVDA reads both title and aria-label

### ISSUE THREAD

**Issue by avimaymon** [nvaccess/nvda#11764] opened 2020-10-15 12:22 UTC
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Steps to reproduce:
Add both a `title` and an `aria-label` to an element and read it with a screen reader
### Actual behavior:
The screen reader reads both of them
### Expected behavior:
The screen reader should read only the `aria-label` if exists, if not - it will read the `title` or other text
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Any HTML page
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment] 2020-10-15 20:13
This is a duplicate of #7841. Closing as such.

**Closed by Adriani90** 2020-10-15 20:13 UTC
Labels: close/duplicate
