### ISSUE TITLE
In Excel, on using CTRLSEMI COLON, NVDA announces unknown instead of the date

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#6254] opened 2016-08-10 10:21 UTC
1. Open and Excel sheet.
2. on a blank cell, use CTRL+SEMICOLON.
3. thedate is automatically filled in

**Comment by jcsteh** [comment] 2016-08-11 01:49
I can't reproduce this. In both Excel 2010 and 2016, NVDA reports I've entered an "edit" field along with the date.

What version of Excel is this? What happens if you press f2 to just edit the cell?

**Comment by ehollig** [comment] 2017-08-01 02:32
In Office 2016, I experience the same results as https://github.com/nvaccess/nvda/issues/6254#issuecomment-239054545. It would be helpful to know which version of Excel is being used that experiences this issue. CC @sumandogra

**Comment by ehollig** [comment] 2017-10-13 16:18
Closing as worksforme per above comments.

**Closed by ehollig** 2017-10-13 16:18 UTC
