### ISSUE TITLE
ADA_NVDA is not reading the fields in correct order by navigating screens through Tab

### ISSUE THREAD

**Issue by nkopanathi** [nvaccess/nvda#12743] opened 2021-08-17 14:20 UTC
### Steps to reproduce:
1. Start a new application
2. Navigate to Next screens through Tab key and select Skip to main Content link on the next screen when tab for the first time
### Actual behavior:
NVDA is not reading the fields in correct order by navigating screens through Tab
### Expected behavior:
NVDA should read the fields in correct order by navigating screens through Tab
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1
#### Windows version:
Windows10 Enterprise
#### Name and version of other software in use when reproducing the issue:
Didn't used any other software
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Tried with 2019.1 NVDA version, still facing the issue
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment] 2021-08-19 01:26
@nkopanathi welcome to the NVDA project.

Unfortunately this issue does not adequately describe the situation, and we will not be able to investigate. Please note that GitHub issues (on the NVDA project) are intended for a technical audience, willing to investigate, test, and debug the project.
If you are looking for end user support, please consider the [options to get help](https://www.nvaccess.org/get-help/) on the NV Access website. 

> Start a new application

Which application?

>NVDA is not reading the fields in correct order by navigating screens through Tab

Which fields? Please give some specific examples.

I'm going to close this issue. However if more information is provided and the issue can be progressed I'll re-open it.

**Closed by feerrenrut** 2021-08-19 01:26 UTC

**Comment by nkopanathi** [comment] 2021-08-19 07:44
Please re-open the ticket, Here the application means the new form which contains the multiple screens while navigating in the application. and I provided the example fields in the screen which NVDA is not reading in the order.

**Comment by feerrenrut** [comment] 2021-08-19 09:25
This still isn't clear. It sounds like you might be talking about a web browser, if so which one (Edge, Chrome, Firefox?) and with which website. As it stands, this issue can not be progressed.

**Comment by nkopanathi** [comment] 2021-08-19 10:58
Attached the video evidence for our website which was tested in chrome browser, please check and let me know which details I need to provide to make it clear

**Comment by feerrenrut** [comment] 2021-08-20 04:04
There is no video attached. This is a bug tracker for NVDA. You'll need to do your own investigation and clearly demonstrate a potential bug in NVDA. For an issue in a website, please provide us with a minimal test case to reproduce the issue.

**Comment by feerrenrut** [comment] 2021-08-20 04:11
The video URL is in the edit history of the description. It was added and then removed. The video does not describe the steps taken when using NVDA. It also isn't accessible, note that many of the developers who work on NVDA are blind.

Most of the time, issues like this are web authoring error, or a lack of understanding on how to use the screen reader. To progress this issue, please provide a minimal test case and the exact steps taken when using NVDA  to show this behavior is caused by a bug in NVDA. The information is requested in the issue template and described in the linked explainer: https://github.com/nvaccess/nvda/blob/master/devDocs/githubIssueTemplateExplanationAndExamples.md

**Comment by abhaytalreja** [comment] 2021-08-23 15:37
@feerrenrut Thank you for your time. As part of our contract, we are not allowed to share application details on a public forum. However, here are the details. Attached is a screenshot of a form (basic user info)

> If you could share an email or private chat, I can quickly share the link to our website and steps to reproduce the problems.

Some more details for you to traige.

- We have a React JS app,
- For any page that we open up the order in which NVDA reads the fields is based on the DOM. However, for the SPA app, the fields NVDA reads are not in the correct order. 

Here is an example of a page.
![Basic User Form](https://user-images.githubusercontent.com/1915902/130473913-97ef9ce1-6e09-4bde-81df-f2487e21bc20.png)

The order in which NVDA reads (sees) the page is as below (Speech Viewer)

- New?
- clickable  main landmark    Next  button  
- Last Name  alert
- Suffix  alert
- Middle Name  alert
- First Name  alert
- Other Names  alert

However, the expected page should read like below:
- New?
- clickable  main landmark   
- First Name  alert
- Middle Name  alert
- Last Name  alert
- Suffix  alert
- Other Names  alert
- Previous  button 
- Next  button 

So the question we have is:

- Is there an issue in which NVDA reads the page order for React JS application? - if you could share the issue id, that will be great.
- Do we need to handle React JS apps differently for NVDA to read the order correctly? - We have followed the wcga standards for creating our pages.

**Comment by feerrenrut** [comment] 2021-08-24 09:36
We can't help you debug your react JS application in this way. If you can share a minimal sample, which you believe highlights a bug in NVDA, we can look at it. If you would like consulting services from NV Access, please refer to https://www.nvaccess.org/services/

> Is there an issue in which NVDA reads the page order for React JS application? - if you could share the issue id, that will be great.

Not to my knowledge. Note that NVDA is only aware of information exposed by the browser, it does not consume a "react js application" and does not even consume the HTML. The browser exposes the accessibility information via an accessibility API.

> Do we need to handle React JS apps differently for NVDA to read the order correctly? - We have followed the wcga standards for creating our pages.

You'll need to provide a minimal plain HTML sample to demonstrate the issue. Look at the order of information in the accessibility (Dev) tools of Chrome / Firefox. NVDA does not need to be running in order to do this. Is this in the order you expect?

Can you fix the DOM order?

**Comment by abhaytalreja** [comment] 2021-08-24 14:44
@feerrenrut Excellent pointer to check Accessibility tab. Very helpful.
I did run the Accessibility tab and checked the show order. The order looks correct but NVDA doesn't read correctly.

![Accessibility Order](https://user-images.githubusercontent.com/1915902/130636030-07775e09-fa54-4684-90ce-16c9164f8800.png)

In the meanwhile, I will work to create a simple app (page) and try and get more information for you.
