### ISSUE TITLE
inconsistent behavior when opening buttons that contain submenu

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9407] opened 2019-03-25 18:12 UTC
### Steps to reproduce:
Open a call in github
Walk with the arrows until a comment made by you or that you have the elevation to edit.
Before the comment you have 2 buttons:
Add your reaction
In this button you can press enter, the options will be displayed and you can find the options with arrows below.
There is another button:
Show options
Press enter on this button.
### Actual behavior:
Nothing happens.

### Expected behavior:
When pressing enter on the Show options button the submenu must be opened
And it should be possible to navigate the displayed options with arrows.
The same occurs in the Add your reaction button
Can I open the button submenu
Show options
with alt + arrow below, and I can navigate the options with arrows.
But how can I open the Add your reaction submenu
  with enter, I want to believe that it should be possible to open the submenu of the Show options button with enter.
nvda is set to not switch between focus mode and navigation mode automatically.
I noticed this now when trying to edit a comment.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 16933
#### Windows version:
10 17763.379
#### Name and version of other software in use when reproducing the issue:
chrome 73
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2019-03-25 20:05
I can also reproduce this issue.

**Comment by Adriani90** [comment] 2019-03-25 20:06
You must switch to focus mode, press space on the aria submenu and then it gets expanded. This is actually not intuitive as most people use browse mode to navigate a website more often than focus mode.

**Comment by ehollig** [comment] 2019-11-21 19:09
@fernando-jose-silva and @Adriani90 is this still the case? Github may have made some changes since this issue was opened.

**Comment by Adriani90** [comment] 2019-11-21 19:27
This is not reproducible anymore in NVDA alpha-19256,3cd482f5 and Chrome 78 or Firefox 70.
Closing as works for me.

**Closed by Adriani90** 2019-11-21 19:27 UTC
Labels: worksforme
