### ISSUE TITLE
Play "beep" for capitals" when coresponding is checked also while navigating word by word

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7780] opened 2017-11-19 01:14 UTC
Steps to reproduce:
1. Open a document and write a few words where which word begins with a capital lletter
2. Write one or two words where there are more than one capital letter contained (even it is wrong spell)
3. Go to NVDA menu / voice and activate "beep for capitals"
4. Navigate through the text word by word holding down the ctrl key.

Expected behavior:
NVDA should play a beep for every word which contains capitals.

Actual behavior:
NVDA just reads the word without reporting capitals.

System configuration:
NVDA version:
All

NVDA Installed or portable:
both

Other information:

Windows version:
all

Name and version of other software in use when reproducing the issue:
All edit fields, MS Word, Outlook etc.

Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
Yes, all

**Comment by Adriani90** [comment] 2017-11-19 01:18
I would like to mention that this should only apply when "beep for capitals" is activated.

**Comment by ehollig** [comment] 2017-11-19 01:28
Duplicate of #6360

**Closed by ehollig** 2017-11-19 01:28 UTC
