### ISSUE TITLE
Window Title is repeated when Chrome menu is launched before "Chrome Button" is announced

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7266] opened 2017-06-08 09:14 UTC
### Steps to reproduce:
1. Open Chrome
2. Press alt to launch the menu.
3. Log sneppet below.:

IO - speech.speak (04:57:04.426):
Speaking [LangChangeCommand (u'en_US'), u'iPad Drag and Drop, Multitasking, and Split View in iOS 11: Everything you need to know! | iMore  document']
IO - speech.speak (04:57:04.430):
Speaking [LangChangeCommand (u'en_US'), u'link', u'Skip to main content']
IO - speech.speak (04:57:10.101):
Speaking [LangChangeCommand (u'en_US'), u'iPad Drag and Drop, Multitasking, and Split View in iOS 11: Everything you need to know! | iMore  window']
IO - speech.speak (04:57:10.108):
Speaking [LangChangeCommand (u'en_US'), u'main  tool bar']
IO - speech.speak (04:57:10.111):
Speaking [LangChangeCommand (u'en_US'), u'Chrome  menu button  subMenu  Customise and control Google Chrome']

### Expected behavior:
NVDA should announce "Chrome button ..."

### Actual behavior:
Window title is repeated before the announcement is made. Log snippet shows that the alt press is not recognized by NVDA.

### System configuration:
NVDA version:
NVDA version next-14098,66f26bb2

NVDA Installed or portable:
installed
Other information:
Chrome Version 61.0.3122.0 (Official Build) canary (64-bit)

Windows version:
Windows 10 Version 1703 Build 16199.100

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes.

Have you tried any other versions of NVDA?
NVDA 2017-2. Behavior is replicated.

**Comment by PratikP1** [comment] 2017-06-19 20:11
In Chrome Canary 61.0.3135.0, the verbosity still exists but the alt key is now recognized. Focus is placed on the Chrome menu button.

**Comment by Adriani90** [comment] 2019-04-17 21:59
@PratikP1 the verbosity reduced to ""Chrome menu button submenu" when pressing alt. I am testing with NVDA 2019.1.1 and Chrome 73. So I cannot reproduce this issue. Are you still having this problem?

**Comment by Adriani90** [comment] 2019-12-15 20:48
Not reproducible with NVDA 2019.3 Beta 1 on Chrome 79. Closing as works for me.

**Closed by Adriani90** 2019-12-15 20:48 UTC
Labels: Chrome, GoogleWork, p3, worksforme
