### ISSUE TITLE
NVDA causes the VS 2019 .NET 5.0 Forms Designer to lock up

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#12146] opened 2021-03-10 12:44 UTC
### Steps to reproduce:

1. Run Visual Studio Community Edition 2019 and update to the latest release v16.9.1.
2. Create a new WinForms App (.NET framework). make sure that it is the second one in the default list of templates. The first one is for .NET 4.7.2, but we want the second one which is for .NET 5.0.
3. Go through the rest of the wizard and let it generate itself. It will first complain about .NET 5.0 not yet being installed, and install it in the background.
4. Once the form designer gains focus, press CTRL+Alt+X to go to the toolbox, tap L a b for Label, and press Enter to add a label to the blank form.
5. This is when things start to get bad. NVDA will slow down with VS 2019, keystrokes take long to process. To test, open and close the View menu, for example.
6. Now, while still in the Form designer, press Tab.
7. You may still be OK, or you may already be frozen. You can try to press F7. If it opens the editor with your forms1.cs file, you're still good. Press Shift+F7 to go back to the form designer, and maybe press F4 to go to properties view.
8. Repeat steps 6 and 7 a few times, trying to tab around and editing properties.

### Actual behavior:

NVDA is very sluggish with VS 2019. And eventually it will cause VS 2019 to become unresponsive (the title bar gets the "Not Responding" text, and it won't recover from it, even after an NVDA restart. Observations:

1. It is worse with Braille active than without, but even without, you'll eventually manage to hang VS.
2. The WinTen Apps add-on has a bearing, too, although with the 20210310 version, this is less of a problem. @josephsl has the details on what he did to fix it, it had something to do with a COM exception being raised.
3. All of this does not happen with JAWS 2021 latest update. JAWS, too, does not speak anything when tabbing through the .NET 5.0 WinForms designer, but at least it doesn't cause VS 2019 to freeze and eventually crash.

### Expected behavior:

NVDA should be smooth and not cause hangs or crashes in VS 2019.

#### NVDA installed/portable/running from source:
 Installed And Portable.
#### Name and version of other software in use when reproducing the issue: 

Microsoft Visual Studio Community 2019
Version 16.9.1
VisualStudio.16.Release/16.9.1+31105.61
Microsoft .NET Framework
Version 4.8.04084

Installierte Version: Community

Visual C++ 2019   00435-60000-00000-AA291
Microsoft Visual C++ 2019

Allgemeine Azure-Tools   1.10
Bietet allgemeine Dienste für die Verwendung durch Azure Mobile Services und Microsoft Azure-Tools.

ASP.NET and Web Tools 2019   16.9.688.6828
ASP.NET and Web Tools 2019

Azure App Service-Tools v3.0.0   16.9.688.6828
Azure App Service-Tools v3.0.0

C#-Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
C#-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

IntelliCode-Erweiterung   1.0
Detaillierte Informationen zur IntelliCode Visual Studio-Erweiterung

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++-Assistenten   1.0
Microsoft Visual C++-Assistenten

NuGet-Paket-Manager   5.9.0
NuGet-Paket-Manager in Visual Studio. Weitere Informationen zu NuGet finden Sie unter https://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Testadapter für Boost.Test   1.0
Aktiviert Visual Studio-Testtools mit Komponententests, die für Boost.Test geschrieben wurden. Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

Testadapter für Google Test   1.0
Ermöglicht die Verwendung von Visual Studio-Testtools mit Komponententests, die für Google Test geschrieben wurden. Die Nutzungsbedingungen und Drittanbieterhinweise stehen im Installationsverzeichnis der Erweiterung zur Verfügung.

TypeScript-Tools   16.0.30201.2001
TypeScript-Tools für Microsoft Visual Studio

VC-Paket für Microsoft Visual Studio   1.0
VC-Paket für Microsoft Visual Studio

Visual Basic-Tools   3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
Visual Basic-Komponenten, die in der IDE verwendet werden. Abhängig von Ihrem Projekttyp und den zugehörigen Einstellungen kann eine andere Version des Compilers verwendet werden.

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools

Visual Studio-Tools für CMake   1.0
Visual Studio-Tools für CMake

Visual Studio Code-Debugadapter-Hostpaket   1.0
Interopebene zum Hosten der Visual Studio Code-Adapter in Visual Studio

#### Other information about your system:

Braille Display: Handy Tech Active Star.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

At @leonardder 's request, tried NVDA 2020.3. It is a little better, in that it takes longer to cause the freeze, but it does expose the same bug.

#### If add-ons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

N/A.

There are a few log files that I made while reproducing the bug. Here they are:
[NVDA freezes with VS 2019.zip](https://github.com/nvaccess/nvda/files/6115874/NVDA.freezes.with.VS.2019.zip)
.

**Comment by cary-rowen** [comment] 2021-03-10 13:01
I encountered the same problem, and the use of NVDA with VS is very slow in my case, even in the code editing area

**Comment by cary-rowen** [comment] 2021-03-17 05:44
Yes, I can reproduce this problem completely, I use the latest alpha-21974, But the narrator is perfect.
The following is the log, I hope it will help:
[nvda.log](https://github.com/nvaccess/nvda/files/6153985/nvda.log)

**Comment by leonardder** [comment] 2021-03-17 06:44
I think we should consider implementing shouldProcessUIAPropertyChangedEvent on the VisualStudio appModule to further rate limit the amount of events processed by NVDA. I'm pretty sure that there's a lot of garbage handled by NVDA and silently dropped afterwards, however since handling every single event takes a short amount of time, many events result in much time getting lost.

**Comment by cary-rowen** [comment] 2021-03-17 10:40
Yes, this causes NVDA to navigate very slowly in VS.

**Comment by cyrmax** [comment] 2022-01-09 05:40
I have the same problem on NVDA 2021.3.1.
In .net windows forms designer NVDA stops reading anything, visual studio goes to "not responding" state, keyboard starts to respond very slowly and the only solution for me is to try to use alt+f4 and try to close not responding program. 

I am using Visual Studio 2022.

**Comment by beqabeqa473** [comment] 2022-01-09 06:45
Coompletely agree with that.

It is a case from the beginning of implementing winforms in dotnet core.

On 1/9/22, Kirill Belousov ***@***.***> wrote:
> I have the same problem on NVDA 2021.3.1.
> In .net windows forms designer NVDA stops reading anything, visual studio
> goes to "not responding" state, keyboard starts to respond very slowly and
> the only solution for me is to try to use alt+f4 and try to close not
> responding program.
>
> I am using Visual Studio 2022.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/12146#issuecomment-1008234529
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by cary-rowen** [comment] 2022-01-17 10:02
@leonardder @feerrenrut 

I think this issue is urgent enough, does NVAccess have any plans to fix it in the near future?

Thanks

**Comment by Tanya-Solyanik** [comment] 2022-03-09 02:26
This will be fixed in Visual Studio 17.2 preview that will be released on 3/15 for applications that target .NET 6.0. Other versions of .NET will be serviced in the next servicing event.

**Comment by cary-rowen** [comment] 2022-03-09 11:26
@Tanya-Solyanik 
Thanks for the update, it sounds like it would be nice.

**Comment by Adriani90** [comment] 2023-03-28 22:16
@leonardder, @MarcoZehe, @akash07k, @cary-rowen, @cyrmax, @beqabeqa473 could you please test NVDA last alpha version and report your results? How is the performance now?

**Comment by Adriani90** [comment] 2023-09-14 22:01
@akash07k, @cary-rowen could you please follow up on my question above? Is this issue still occuring with NVDA 2023.2? The comments above suggest this should be fixed now in VS 17.2 or newer sub versions of VS 2019.

**Comment by cary-rowen** [comment] 2023-09-20 00:39
I can only confirm that the issue cannot be reproduced in WPF using VS2022 .net6.0 or 7.0.

**Comment by beqabeqa473** [comment] 2023-09-20 06:09
issue with winforms on vs17.7 and .net 7 doesn't occur.

On 9/20/23, Rowen ***@***.***> wrote:
> I can only confirm that the issue cannot be reproduced in WPF using VS2022
> .net6.0 or 7.0.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/12146#issuecomment-1726719843
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by leonardder** [comment] 2023-09-20 06:34
In that case, let's close this. .NET 5 is out of support anyway.

**Closed by leonardder** 2023-09-20 06:34 UTC
Labels: performance, app/visual-studio
