### ISSUE TITLE
In the elements list dialog, sometimes link text doesn't apear correctly

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#5828] opened 2016-03-21 18:10 UTC
I don't have steps to reproduce this, but today I'm finding it on Github. I suspect it has to do with opening the links list when the page is not fully loaded.
The link text appears with two links together. The first link text is half-cut, and it apears combined with the first part of the second.

**Comment by leonardder** [comment] 2017-07-15 13:47
Hmm, if the page isn't fully loaded, it is likely that the elements list will give inaccurate results.
@JCSTeh: Do you think we should a consider a refresh button in the elements list? If not, I'd go for a close as invalid.

**Comment by jcsteh** [comment] 2017-07-17 02:12
I don't think a refresh button is a good idea; it's fairly ugly and it's easy enough to just close the dialog and reopen.

Ideally, it'd be good to find a solution to this problem. That'd involve somehow making it less dependent on offsets. P3 because there's a workaround and it doesn't occur that often.

**Comment by Adriani90** [comment] 2019-02-18 23:42
@sukiletxe can you still reproduce this issue with last NVDA alpha and last versions of browsers?

**Comment by sukiletxe** [comment] 2019-02-19 10:43
This works for me now, thanks for CC'ing. Just tested with the famous World War I article, this thread and another repo page in GitHub. If these aren't appropriate, feel free to suggest another page.

**Comment by leonardder** [comment] 2019-02-19 10:57
Closing as works for me.

**Closed by leonardder** 2019-02-19 10:57 UTC
Labels: p3
