### ISSUE TITLE
Skype: NVDA freezes on the 'chat app widget document graphic advertisement' control in Skype

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#5984] opened 2016-05-22 05:19 UTC
Steps to reproduce
1 Open a chat window (either a contact or a group).
2 Keep tabbing until you land on the Insert Emoticon or Emoji control.
3 Upon tabbing again, you will land on something NVDA reads as
‘Chat app widget document graphic advertisement’
The buggy part of this control is that NVDA gets stuck in this control, as you nened to at least tab literally ten or so times (or Shift + tab) to get out of this and back to your actual Skype chat interface.

Note: This is quite easily reproducible, but still not absolutely consistent, as in some chat windows, sometimes, this control just does not exist.

Test Environment
Windows 8.1 Pro 64 bit
Skype™   Version 7.23.0.105 (downloaded from Skype’s official website, and not the pre-integrated system app)

**Comment by jcsteh** [comment] 2016-06-23 19:58
Duplicate of #5975.

**Closed by jcsteh** 2016-06-23 19:58 UTC
Labels: duplicate
