### ISSUE TITLE
nvd's pich slider ends up being at 51 when we set it to 50

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#14472] opened 2022-12-24 08:08 UTC
this is a strange bug, but when i use espeeck as my sinthesizer, when i set the pich slider to 50 in voice settings, as soon as i press ok or aply button, the pich ends up being at 51 and not in 50: note: this bug only happens with eespeeck ng, it works fine as i tested with microsoft speech api vertion 5 and windows onecare voices. nvda vertion: 2022.3.3.

**Comment by amirmahdifard** [comment] 2022-12-24 08:11
to your questions: it stil happens after doing com registration tool: stil happens when i restart my computer: stil happens after disabeling all addons.

**Comment by amirmahdifard** [comment] 2022-12-24 08:17
expected: the pich slider should stay at 50 and not 51: actual: the pich slider remanes at 51 when we press ok button:  steps: select eespeeck ng as your sinth, and set the pich to 50 amd press kk or aply button: you see it flyes up to 51.

**Comment by Brian1Gaff** [comment] 2022-12-24 12:19
I imagine that this is a kind of quantising error in the values Espeak can 
manage incrementally, IE it is not able to step its parameters to such a 
fine granular setting.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment] 2022-12-27 22:25
This is a duplicate of https://github.com/nvaccess/nvda/issues/9811, closing for the same reason as that issue.

**Closed by seanbudd** 2022-12-27 22:25 UTC
