### ISSUE TITLE
The radio buttons in ‘Link Settings’ window, like ‘People in Microsoft with the link’ are announced as ‘Selected Not checked’ when selected.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13496] opened 2022-03-16 17:39 UTC
### Steps to reproduce:
Step 1: Start NVDA
Step 2: Open the Excel application and create the new workbook
Step 3: Navigate to share link and select it
Step 4: Share window gets displayed 
Step 5: Navigate to the ‘Link Settings’ window and observe the issue.

### Actual behavior:
The radio buttons in ‘Link Settings’ window, like ‘People in Microsoft with the link’ are announced as ‘Selected Not checked’ when selected.

### Expected behavior:
The radio buttons in ‘Link Settings’ window, like ‘People in Microsoft with the link’ should be announced as ‘Selected when link is selected. 

### System configuration
OS Version: Win 11 Build (22489.1000)
Word Application Version: 2112 (Build 14715.20000)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA Version 2021.3.3

#### Windows version:
Window 11, Version 21H2 (OS Build 22000.556)

#### Does the issue still occur after restarting your computer?
Yes

**Comment by michaelDCurran** [comment] 2022-10-26 18:04
Duplicate of #13298

**Closed by michaelDCurran** 2022-10-26 18:04 UTC
Labels: p4, triaged
