### ISSUE TITLE
NVDA closes chrome!

### ISSUE THREAD

**Issue by ManiaCs213** [nvaccess/nvda#9418] opened 2019-03-29 08:38 UTC
### **
Hello!When trying to choose the category for a video on Youtube after i open the list to choose the category and pressing down arrow or up arrow the chrome closes instantly.**

**Comment by lukaszgo1** [comment] 2019-03-29 10:01
@ManiaCs213 Could you please update the issue according to the issue template? Even though the issue draft isn't filled it looks similar to #9410 and #9364 cc @michaelDCurran  @feerrenrut

**Comment by Adriani90** [comment] 2019-03-29 18:46
Duplicate of #9364, this is also related to a list box / combo box.

**Closed by Adriani90** 2019-03-29 18:46 UTC
Labels: duplicate
