### ISSUE TITLE
Windows 10 NVDA OCR Crashing NVDA

### ISSUE THREAD

**Issue by ironcross32** [nvaccess/nvda#9472] opened 2019-04-09 06:28 UTC
### Steps to reproduce:
This issue is intermittent and mostly happens within Reaper. It msotly happens when trying to OCR certain VSTi plugins
### Actual behavior:
NVDA will crash and then recover from said crash after attempting to OCR a plugin window, which never used to be the case.
### Expected behavior:
NVDA should scan the window, and report the text found just as with any other attempted OCR.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2019.1
#### Windows version:
Windows 10:  Version 1809 (OS Build 17763.404)
#### Name and version of other software in use when reproducing the issue:
Reaper v5.97/x64
#### Other information about your system:
Laptop, screen is on, issue only started occurring in this version of NVDA
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no
[nvda-old.log](https://github.com/nvaccess/nvda/files/3057439/nvda-old.log)

[logs.zip](https://github.com/nvaccess/nvda/files/3057445/logs.zip)

**Comment by lukaszgo1** [comment] 2019-04-09 21:16
@ironcross32 Could you please try to reprorduce it with all add-ons disabled? The log mentions Eloquence add-on in particular.

**Comment by ironcross32** [comment] 2019-04-09 22:40
I did that before writing up this issue. While the log was in effect during addons, with no addons running and speech falling back to one core, same result.

**Comment by Adriani90** [comment] 2019-04-16 21:27
cc: @jcsteh, @leonardder

**Comment by jcsteh** [comment] 2019-04-16 22:06
Could you please provide a crash dump? If you press Windows+r and type %temp% (note the percent signs), there should be a file called nvda_crash.dmp.

**Comment by Adriani90** [comment] 2019-04-16 23:38
There is a crash dump in the logs.zip file in the description. But for what ever reason I cannot read the content of the file.

 

 

 

Von: James Teh <notifications@github.com> 
Gesendet: Mittwoch, 17. April 2019 00:06
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Windows 10 NVDA OCR Crashing NVDA (#9472)

 

Could you please provide a crash dump? If you press Windows+r and type %temp% (note the percent signs), there should be a file called nvda_crash.dmp.

**Comment by jcsteh** [comment] 2019-04-17 01:42
My apologies. I missed that. You'd need to examine that with a Windows
debugger like WinDBG. That's fairly complicated stuff. :)

**Comment by ironcross32** [comment] 2019-04-17 08:26
Yes its binary data, is this not standard practice? I'm not sure what you're asking me for.

**Comment by Adriani90** [comment] 2019-04-17 13:11
No that's ok, it was me not knowing how exactly to see the Content. I am not very experienced in development stuff yet. :-) Sorry for any confusions.

**Comment by ironcross32** [comment] 2019-04-17 19:25
OK, I must admit, that one had me shaking my head a bit :)

**Comment by Adriani90** [comment] 2020-01-19 19:46
@ironcross32 are you still having this issue in NVDA 2019.3 Beta 2? I cannot reproduce it. Please also try to maximize the window before reproducing it.

**Comment by Adriani90** [comment] 2020-05-16 22:26
No update on this issue since more than one year from the initial author, I am closing this as abandoned. Please feel free to comment on it if you are still having this issue and we can reopen.

**Comment by ironcross32** [comment] 2021-10-12 18:35
This is an old issue caused by a system that two weeks later, died a horrible death. It's no longer relevant.

**Comment by lukaszgo1** [comment] 2021-10-12 19:33
@feerrenrut  @seanbudd  Can this be reopened please?

**Comment by seanbudd** [comment] 2021-10-14 00:02
I'm going to reopen this issue so it isn't lost, but please fill out a new issue template so we can investigate this issue.

**Comment by leonardder** [comment] 2021-10-19 05:37
Could you please try with add-ons disabled @vortex1024?

**Comment by Adriani90** [comment] 2023-08-29 17:58
cc: @jcsteh the last two comments here might be relevant also for implementing the continuous OCR recognition.

**Comment by jcsteh** [comment] 2023-08-29 23:11
If I remember correctly, the continuous OCR I implemented (and @leonardder has now taken over) explicitly waits for the callback to be called before scheduling any further refreshes. So, this should never be called concurrently.

**Comment by Adriani90** [comment] 2024-06-25 19:10
I am closing this as the crash does not occur. If there is a crash occuring in different scenarios, please open a new issue with exact steps to reproduce or further details.

**Closed by Adriani90** 2024-06-25 19:10 UTC
Labels: close/worksforme, bug/crash, feature/ocr
