### ISSUE TITLE
NVDA is reading source/JavaScript code in IE 11

### ISSUE THREAD

**Issue by vinaychaudhary1504** [nvaccess/nvda#10733] opened 2020-01-30 10:34 UTC
### Steps to reproduce:
1) Turn on NVDA
2) Go-to : https://www.bankofamerica.com in IE
3) By using tab key, navigate to Help link at top right corner.
4) After the help link is open, user will get a model dialogue to select state.
5) you will be seeing NVDA is reading span Element. As <span class='spa-input-label--required'>*</span>

### Actual behavior:
NVDA is reading source/JavaScript code.

### Expected behavior:
It Should not read the JavaScript code, as it is giving a wrong impression to blind people

#### NVDA installed/portable/running from source:
NVDA installed in laptop (window 10)
#### NVDA version:
2019.2.1
#### Windows version:
Windows 10

**Comment by CyrilleB79** [comment] 2020-01-30 15:06
Yes, I have already had this issue on a page of an application internal to my company. It has appeared a long time ago and I had always thought that it was due to a poor implementation of this old application, so I did not raise any issue.
After quick test, I can tell that this issue is present in 2019.3beta3 and in 2018.3 but not in 2017.3.

**Comment by Adriani90** [comment] 2020-01-30 16:04
@CyrilleB79 could you try to find out which version after 2017.3 is the first where this issue is reproducible? Is it maybe since version 2017.4?

**Comment by CyrilleB79** [comment] 2020-01-30 16:23
NVDA 2017.4 is OK. The regression has appeared in NVDA 2018.1.

**Comment by tapper82** [comment] 2020-01-30 16:43
Use Firefox! As IE11 is being replaced by Edge it would be a waste of time for NVDA devs to fix IE bugs. IMO.

**Comment by feerrenrut** [comment] 2020-01-30 19:24
While this is a regression, and has a nasty outcome, it is not likely to affect many users. @tapper82 in some organizations IE MUST be used for certain internal sites. I agree that this isn't ideal.

**Comment by Adriani90** [comment] 2020-01-30 21:33
At least not many private users. In corporate environment however there are many users which live with these issues and the work is really not efficient in IE with NVDA, especially because more and more bugs appear.
If you look for Internet explorer in the issue tracker here you will see how many people created issues regarding to this application. I guess it affects still quite a log of people but there seems to exist a consensus in the developers community that this is not the case. I gon't really know how this impression has been created, actually Reef we could start a community wide survey on internet explorer to have a clear picture on that. What do you think?

**Comment by JulienCochuyt** [comment] 2020-05-14 22:25
@Adriani90 wrote:
> At least not many private users. In corporate environment however there are many users which live with these issues and the work is really not efficient in IE with NVDA, especially because more and more bugs appear.

I agree: I still have quite a few customers stuck with IE11 for business applications that badly suffer from this situation.

**Comment by feerrenrut** [comment] 2020-06-12 16:00
Regarding a survey, you can [check web aim 8](https://webaim.org/projects/screenreadersurvey8/#browsers).

It's worth noting that Microsoft claims IE11 will [continue to be supported on Windows 10 and 8.1](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge). This is helpful to be aware of, IE11 doesn't look like it is going away soon. Though it is [not recommended to be used as a web browser](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-perils-of-using-internet-explorer-as-your-default-browser/ba-p/331732), it is not being updated to support new web standards, and web developers rarely test with it. Of course, using it with an "only compatible with IE" internal system is a different case. Unfortunately these cases are often quite difficult for us to fix without involvement from the company who has the internal system. We often need (HTML samples) to understand and fix an issue. Of course it is possible for these companies to contact NV Access or other organizations that work on NVDA to provide non-public samples (under NDA if necessary).  

Due to limited resources, we have to prioritize and focus on what we think is most important. Our typical focus is on supporting the needs of end users. Personally I would feel uncomfortable about providing free support for business at the cost of the needs of home, independent, or general users.

Broadly generalizing, companies (especially for profit companies) should be considering the cost of their own systems and whether it is appropriate to keep these systems updated, modify them for use with modern browsers, or purchase other tools to support their blind employees, or of course they are welcome to contribute to NVDA directly (or hire developers) to meet their needs. For instance I think that  Bank of America probably has the resources to address this issue by updating their website. I believe there are laws for this in the US.

Finally, these issues can also be reported directly to Microsoft. Ideally they would be investigated first to ensure that the issue is within IE, if that is the case we can put forward a much stronger case about what needs to change.

I hope this is helpful, I and NV Access want what is best for our users but sometimes that means making difficult decisions. Of course, we make these decisions on a case by case basis, and want NVDA be the best it can be.

To summarize:
- Do raise an issue here.
- Do speak to your employers about the difficulties you have using these systems.
- Do provide suggestions to your employer (contact NV Access or other developers to solve the problem, contact the vendor of the internal system)
- Do provide feedback to Microsoft.

In this particular case the asterisk indicates the field is required. The HTML for the control is:
```
<label class="spa-input-label ada-hidden" for="stateSelectModal">Your Location: <span class="spa-input-label--required">*</span>
<div class="wrap">
<select class="spa-input-select state-select" id="stateSelectModal">
<option value="">Select State</option><option value="AL">Alabama</option>
<option value="AK">Alaska</option><option value="AZ">Arizona</option>
</select>
</div>
```

NVDA 2020.1 reads this as `Your Location: *  combo box  Select State  collapsed`
With: 
```
Internet Explorer  Version: 11.900.18362.0
Update Versions: 11.0.195
(KB4561603)
```

I'll close this issue as 'works for me', if this is not the case for you please provide the output you hear (copy from speech viewer), the version of IE11 and version of NVDA you tested with.

**Closed by feerrenrut** 2020-06-12 16:00 UTC
Labels: app/internet-explorer, bug, bug/regression, p3

**Comment by CyrilleB79** [comment] 2020-06-16 21:16
@feerrenrut in this issue I have commented with a similar issue regarding a website of my company. The issue is was not present in NVDA 2017.4 and appeared in NVDA 2018.1. It is still present in NVDA2020.1 and in last alpha.
I have re-created a simplified example exhibiting this 2018.1 regression since I cannot give a link to this internal page. Here is the simplified example: [SimpleExamplePage.zip](https://github.com/nvaccess/nvda/files/4789133/SimpleExamplePage.zip).
Is it worth opening a separate issue for this? Even if I understand that it would not be a priority?
Note that this does not seem to be the same issue as #7059 since #7059 is already present in NVDA 2017.1 (according to the author of the issue) as well as in NVDA 2017.4 (according to my tests), whereas my issue is only present in NVDA 2018.1 and not in NVDA 2017.4.

**Comment by feerrenrut** [comment] 2020-06-17 11:03
@CyrilleB79 Yes, please create a separate issue.
