### ISSUE TITLE
Mouse event fired incorrectly when NVDA is paired with firefox

### ISSUE THREAD

**Issue by stevenbriscoeca** [nvaccess/nvda#7646] opened 2017-10-04 13:55 UTC
This bug has been found in this repo https://github.com/ten1seven/what-input/issues/68#issuecomment-334036581. It might be NVDA causing it.

### Steps to reproduce:
Notes : **Use NVDA and firefox.**

@ten1seven created this codepen to test: https://codepen.io/ten1seven/pen/yzPYrb?editors=1010

- Open the console
- Navigate by keyboard to the checkbox with your keyboard
- Use the spacebar to toggle the value of the checkbox

### Expected behavior:
In other browsers, you should see the keyup/keydown events firing, but with NVDA+Firefox only mouse events fire, even down to the checkbox itself. (comment taken from https://github.com/ten1seven/what-input/issues/68#issuecomment-334036581)

### System configuration:
NVDA version:
> 2017.2

Windows version:
>Microsoft Windows 7 [version 6.1.7601]

**Comment by Adriani90** [comment] 2018-11-20 07:50
@stephenbe is this issue still reproducible in NVDA with last Alpha?
cc: @jcsteh

**Comment by stephenbe** [comment] 2018-11-20 13:55
Hi @Adriani90 yes I just tried it in alpha-16281,2b96213a and it the same result

**Comment by Adriani90** [comment] 2020-01-11 22:18
cc: @feerrenrut

**Comment by jcsteh** [comment] 2020-03-31 03:46
Probably the same as #4903. In browse mode, space/enter is overridden to activate (which is a click for a checkbox).

**Comment by Adriani90** [comment] 2020-12-08 21:41
@jcsteh does it mean that in focus mode this should work as expected?

**Comment by jcsteh** [comment] 2020-12-14 02:16
Yes.

**Comment by Adriani90** [comment] 2023-05-05 19:00
I don't see a difference here between Firefox and other browsers like Chrome or Edge.

@jcsteh given that such custom key events are mostly meant to work in focus mode rather than browse mode, is it ok to close this? Or is there a use case for this to work in browse mode as well?

**Comment by Adriani90** [comment] 2024-05-09 20:46
I am closing as per comments above.

**Closed by Adriani90** 2024-05-09 20:46 UTC
Labels: close/invalid, app/firefox

**Comment by Littlemad** [comment] 2025-03-20 11:06
Hi, sorry to comment in here, but I would like understand why it is closed as invalid if you could explain @Adriani90 @jcsteh . I find myself as developer the need to distinguish the behaviour between mouse click and keyboard activation, to be able to move focus in the right place when activating a button to show a modal. I understand that this issue is not yet solved and it is on going since 2017. Without this difference I cannot force the focus on a modal because it would appear as well for people that don't need to see a focus. (I immagine that the focus is relevant for people that interact with the keyboard and people with the mouse don't need to have a focus to be visible). Could someone give some clarification? Thank you.

**Comment by SaschaCowley** [comment] 2025-03-20 23:14
1. You should be managing focus in dialogs anyway (mouse users don't necessarily exclusively use the mouse, and keyboard users don't necessarily exclusively use the keyboard).
2. If you're that concerned (which arguably you shouldn't be), the [`focus-visible` pseudo class](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible) may be of interest.
