### ISSUE TITLE
Backspace Key and Control Key Behaving Unexpectedly

### ISSUE THREAD

**Issue by ironcross32** [nvaccess/nvda#6040] opened 2016-06-05 13:59 UTC
I am raising this issue on behalf of another user. I would be glad to serve as liaison between this user and whomever takes on this issue.

User is reporting an intermittent issue whereupon the backspace key, when being used to edit documents, fails to speak characters being deleted. Also, the control key in a specific application appears to be stuck, i.e. pressed down and not behaving in the expected manner. The application in question is RS Games. User has informed me that he/she has contacted the developer(s) of said application and has thence been informed that the issue is not being generated from this application

The user feels that these behaviors are significantly likelier to occur if the laptop were to be closed, (entering a suspend state), and re-opened.

**Comment by Brian1Gaff** [comment] 2016-06-05 15:25
I do not know the software. Is it paid for software? Which version of windows is being run. I have most certainly seen nevda log as if control or windows key is pressed when its not, but a quick restart usually fixes this one. If the delete is actually deleting maybe the machine is running erratically in some way in the software. I did have an oldish machine of a friend of mine which had a Braille display mess about this way a while back last year though, but his new machine, apparently is fine..
 So more info might be handy for anyone looking into this. Bear in mind that if a dev or even another user like me cannot duplicate the issue its going to be a pig to fix it!

Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: ironcross32 
  To: nvaccess/nvda 
  Sent: Sunday, June 05, 2016 2:59 PM
  Subject: [nvaccess/nvda] Backspace Key and Control Key Behaving Unexpectedly (#6040)


  I am raising this issue on behalf of another user. I would be glad to serve as liaison between this user and whomever takes on this issue.

  User is reporting an intermittent issue whereupon the backspace key, when being used to edit documents, fails to speak characters being deleted. Also, the control key in a specific application appears to be stuck, i.e. pressed down and not behaving in the expected manner. The application in question is RS Games. User has informed me that he/she has contacted the developer(s) of said application and has thence been informed that the issue is not being generated from this application

  The user feels that these behaviors are significantly likelier to occur if the laptop were to be closed, (entering a suspend state), and re-opened.

**Comment by ironcross32** [comment] 2016-06-05 19:00
The application is a client in which board and card games can be  played with others over the internet. It provides sound effects and outputs test through the screen reader. I suggested stopping NVDA before closing the laptop and starting it when he/she wishes to resume using it. The user claims this has not stopped the issue. I understand that intermittent/transient issues will be hard to nail down.

Thanks for your help.

**Comment by derekriemer** [comment] 2016-06-05 19:35
Can you please ask your friend to rapidly mash the control key or backspace key after this occurs? If it releases the key this is a behavior I have seen before. If not this is Behavior from what I have seen.

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by ehollig** [comment] 2017-09-12 23:13
@ironcross32, do you know if this is still an issue? If so, more information, such as a debug log may be useful to debug the issue.

**Comment by ehollig** [comment] 2017-10-13 16:03
Closing as invalid. If this is still an issue, please provide the requested information in https://github.com/nvaccess/nvda/issues/6040#issuecomment-329010206 and this issue can be reopened.

**Closed by ehollig** 2017-10-13 16:03 UTC
