### ISSUE TITLE
aria-hidden="true" element in an input's label is read aloud by NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5006] opened 2015-03-30 13:07 UTC
**Reported by jmuheim on 2015-03-30 13:07**
I'm curious why a <span>, that is set invisible to screenreaders using aria-hidden="true" is still read aloud when its associated input field is focused in forms mode?

<label for="name">
  <span aria-hidden="true">*</span>
  Name
</label>
<input type="text" id="name" />

In browse mode, the asterisk "*" is ignored by NVDA. In focus mode, its read aloud.

Live example here (focus the "Name" input): http://base.sirius.uberspace.de/en/user/sign_up

Is this expected behaviour? In my opinion, hidden elements shouldn't be read aloud when in focus mode, too.

**Comment by jcsteh** [comment] 2016-04-06 22:23
Actually, this is a duplicate of #4162.

**Closed by jcsteh** 2016-04-06 22:23 UTC
Labels: duplicate, enhancement, needsExternalFix
