### ISSUE TITLE
Strip silence from SAPI 5 utterances

### ISSUE THREAD

**Issue by nicopn** [nvaccess/nvda#17174] opened 2024-09-15 15:06 UTC
### Is your feature request related to a problem? Please describe.
There are many SAPI voices that have silence at the beginning and/or end of their utterances, making them less responsive.
### Describe the solution you'd like
When using SAPI, synthesize the text, but before sending it to the audio device, remove all silent or near-silent samples from the beginning and end. This will improve responsivity in those voices
### Describe alternatives you've considered
None
### Additional context
N/A

**Comment by seanbudd** [comment] 2024-09-16 03:01
Closing as duplicate of #13284

**Closed by seanbudd** 2024-09-16 03:01 UTC
