### ISSUE TITLE
Cannot set entire rows or columns as headers in Excel

### ISSUE THREAD

**Issue by msviolafangirl** [nvaccess/nvda#12884] opened 2021-09-28 16:46 UTC
### Steps to reproduce:
1. Open excel.
2. Press shift+space to select an entire row or shift+control+down arrow to select an entire column.
3. Press NVDA+shift+C or NVDA+shift+R.

### Actual behavior:
When I select an entire row or column of cells using shift+space or shift+control+down arrow and then press NVDA+shift+C/R to set it as a column/row header, I wind up typing the letter C or R into the cell rather than setting a column/row header. When I only have a single cell slected/in focus, I can set auto column and row header reading as intended.

q### Expected behavior:
I should be able to set automatic column or row header reading when I select entire rows or columns of cells.

#### NVDA installed/portable/running from source:
Installed.

#### Windows version:
Windows 10 21H1 x64 buiold 19043.1237

#### Name and version of other software in use when reproducing the issue:
Excel 16/365, Excel 2007

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by adilhusain-s** [comment] 2022-04-13 11:51
the issue still persists.
* issue can be reproduced when excel UIA support is enabled from nvda advance option( Use UI Automation to access Microsoft Excel spreadsheet controls when available)  

* when excel UIA support is disabled, NVDA can't navigate in excel efficiently. (announces stale content I. E. previous row/column data)
however, row/column headers can be set when UIA support is disabled. 


 
could you please address this issue?


NVDA version:  2021.3.5
windows 10 version:  Version 21H2 (OS Build 19044.1586)
office 365 Microsoft® Excel® for Microsoft 365 MSO (16.0.14326.20850) 64-bit

**Comment by CyrilleB79** [comment] 2023-10-11 07:46
@msviolafangirl, in the User guide, paragraph Excel, [Automatic Column and Row Header Reading](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#ExcelAutomaticColumnAndRowHeaderReading), it is written:
> After moving to the first cell in the column or row containing the headers, use one of the following commands:

And then the `NVDA+shift+C` commands are described as follows:
> Pressing this once tells NVDA this is the first header cell in the row that contains column headers, which should be automatically announced when moving between columns below this row. Pressing twice will clear the setting.

and the equivalent `NVDA+shift+R` description follows.

Thus it's clear from the User Guide that this command applies only to one cell, not to a selection of many cells or even a full row or column.

If you still need to be able to apply these commands on a full selected row/column, please explain why, and why selecting the first cell is not enough.

**Comment by Adriani90** [comment] 2023-10-11 08:58
I can imagine a selected cell range set as header could beuseful, but this is so dynamic that it is really inefficient to define the row and column headers in this way. Especially when cell ranges for headers would differ depending on the position in the table. in order to simplify this, NVDA should provide support of reporting headers when header cells are merged, but there is another issue already requesting it.

Actually, if you make let's say a1 as column header and a2 as row header, then you will hear the correct headers reported by NVDA in every cell. The reporting of headers starts at the cell coordinates at which you set them.
I am closing this issue because  there is no clear use case for setting a whole row or column as header.

**Closed by Adriani90** 2023-10-11 08:58 UTC
Labels: app/microsoft-office
