### ISSUE TITLE
MSWord, problem navigating by sentence

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5805] opened 2016-03-10 12:22 UTC
Open a Word document and move by sentence using alt+downArrow or alt+upArrow. All works fine.
Then switch to browse mode using NVDA+space and switch back to normal mode.
You'll notice that now, alt+downArrow or alt+upArrow don't work anymore.
Tested with NVDA 2016.1 with all addons disabled.

**Comment by leonardder** [comment] 2017-07-15 13:43
I can reproduce this with Word 2016.

CC @MichaelDCurran

**Comment by jcsteh** [comment] 2017-07-17 02:20
Probably something to do with the collapseOrExpandControl script used to support alt+up/down for combo boxes in browse mode. We'd need to somehow make binding of these optional for browse mode document subclasses.

**Comment by jcsteh** [comment] 2017-07-17 02:21
P3 because there's a workaround (switch to focus mode), but it's certainly tedious.

**Comment by Adriani90** [comment] 2019-02-12 14:30
cc: @mltony

**Comment by Adriani90** [comment] 2020-05-02 16:01
In case this issue is meant to occur in browse mode, this is a duplicate of #5463. Closing as duplicate. Please correct me if I missunderstood this issue and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-02 16:01 UTC
Labels: app/microsoft-office, bug, close/duplicate, p3
