### ISSUE TITLE
Enhancing NVDA's performance on Microsoft Word 2013

### ISSUE THREAD

**Issue by afrim-maja** [nvaccess/nvda#5851] opened 2016-04-03 17:15 UTC
Hello, 
I am a new user of NVDA. I use it primarily for some programs which require me to use the mouse, or sometimes as a very quick and replaceable alternative to my primary first Screen reader Jaws. I really want to fully switch to NVDA, because I love its extensive features and its possibility of customisation.
My main problem is Microsoft word. I have to use it daily, hour after hour because I study linguistics and I need to write a lot. NVDA serves a noticeably laggy, slow performance on Microsoft word, especially on documents which go up to 50 pages or more. On a 600 page book, NVDA is nearly unusable because it takes around 3 seconds to read a line. Reading the document character by character takes three to five seconds, and in some instances it crashes. Another problem I would like to include related to Word is that when pressing the end key, the cursor will move to the end of the document or page. I do not really know why it happens because it should normally go to the end of the line.
To conclude this issue, I would like to take the time to wholeheartedly thank in advance the NVDA team for the precious work it has done during all this years. I am very sorry if I have not followed the write procedure to report an issue because this is my first time I post here. I am looking forward to receiving an answer to my problem and I would be very grateful if this issue was investigated.
Yours sincerely, 
Afrim

**Comment by derekriemer** [comment] 2016-04-03 21:32
You have posted this to the right place. I have noticed this as well, 
although it doesn't seem to be the case for everyone. Are there any 
sample texts you can provide (you could send a text privately to a 
developer if need be). I have found some slowness issues in documents 
and reported them before, but those were related to browse mode. Also, 
does NVDA performance in word decrease over time, as I think I have 
experienced this, and I am curious if a reboot of NVDA when performance 
helps you fix it. (technical, this only seems to happen in complex rich 
text documents mainly with braille displays, and with complex tables and 
such. I am wondering if NVDA injects code into winword, because if so, a 
memory leak might be to blame).

On 4/3/2016 11:16 AM, afrim-maja wrote:
>
> Hello,
> I am a new user of NVDA. I use it primarily for some programs which 
> require me to use the mouse, or sometimes as a very quick and 
> replaceable alternative to my primary first Screen reader Jaws. I 
> really want to fully switch to NVDA, because I love its extensive 
> features and its possibility of customisation.
> My main problem is Microsoft word. I have to use it daily, hour after 
> hour because I study linguistics and I need to write a lot. NVDA 
> serves a noticeably laggy, slow performance on Microsoft word, 
> especially on documents which go up to 50 pages or more. On a 600 page 
> book, NVDA is nearly unusable because it takes around 3 seconds to 
> read a line. Reading the document character by character takes three 
> to five seconds, and in some instances it crashes. Another problem I 
> would like to include related to Word is that when pressing the end 
> key, the cursor will move to the end of the document or page. I do not 
> really know why it happens because it should normally go to the end of 
> the line.
> To conclude this issue, I would like to take the time to 
> wholeheartedly thank in advance the NVDA team for the precious work it 
> has done during all this years. I am very sorry if I have not followed 
> the write procedure to report an issue because this is my first time I 
> post here. I am looking forward to receiving an answer to my problem 
> and I would be very grateful if this issue was investigated.
> Yours sincerely,
> Afrim
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5851>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by afrim-maja** [comment] 2016-04-03 22:23
Hi derekriemer, 
Yes, it is true that it is not the case for everyone and I agree because my desktop computer does not face so much this kind of issue. This is basically due to its 3.0 GHZ processor which has enough room to cover NVDA even if it is lagging. Memory and the processor is a cause of this problem, but it is also very strange that NVDA does not crash in a webpage full of headings, lists, tables and lots of text while at the same time, two other screen readers I try, (Jaws and window eyes) do crash. In my experience, I find firefox and internet explorer potentially risky for my computer, because if they crash along with the screen reader, you may be forced to restart the PC. NVDA particularly lags on microsoft word, and the bigger the document is, the higher the lag will be. It is not the case that NVDA crashes, but it acts very slowly. Restarting NVDA won't make any difference; it will go again to the same state. If you could let me know, where could I send the text samples for testing? Should I upload them here?
Cheers.

**Comment by ehollig** [comment] 2017-08-16 20:19
Hello @afrim-maja, are you still experiencing this issue? If so, are there any example documents experiencing this issue that you could attach to this issue?

**Comment by bhavyashah** [comment] 2017-08-17 04:40
I have a test case to share. However, it is about 57 mb in size. Thus, would you like me to share its Google Drive URL or would you rather I attached it to Github? I am not even sure if Github will accept a 57 mb Word file... I would appreciate a clarification.

**Comment by Adriani90** [comment] 2019-02-04 15:31
cc: @michaelDCurran I think your recent pull request improves Performance significantly. We should test if this one is fixed by that pr. Is there a try build for that?

**Comment by afrim-maja** [comment] 2019-02-04 19:39
Now I am using NVDA with Microsoft Office 2016, but the situation has improved quite a lot. It isn't still where it should be, but it is highly more improved than three years ago when this issue was opened.
There is one area in Microsoft Word, however, where NVDA lags considerably: tables.

**Comment by michaelDCurran** [comment] 2019-02-05 00:37
Here is a try build for pr #9217 which may improve performance in MS Word:

https://ci.appveyor.com/api/buildjobs/w6uunh61ul06w9g8/artifacts/output%2Fnvda_snapshot_try-speedUpMSWordObjectModel-16707%2C4c8d75d1.exe


Note that if testing with Office 2016, the experimental UI automation 
support for MS Word must be turned off in NVDA.

**Comment by Adriani90** [comment] 2019-02-05 20:22
I tested as following:
* Try build with MS Word 2010
1. Created a table with 500 rows and 20 columns
2. in document formating settings enabled "pages", "editor revisions", "Table", "Cell coordinates" and "spell errors".
3. Navigated with arrow keys through the table
4. Navigated with ctrl+alt+arrow keys through the table
5. Pressed ctrl+alt+down arrow and held it pressed a few seconds.
Result: slightly improved performance, but NVDA is still somehow slow in tabless in MS Word. But faster than in NVDA Alpha 16691,10590C87 in any case.

* Try build with MS Word 365, UIA disabled:
Same steps as described above.
Result: Slightly improved performance, but much slower than in MS Word 2010 though. Here enabling UIA brings significant performance improvement. But enabling UIA causes page numbers not to be reported anymore.

Note: when pages are disabled in document formating settings, the performance is much better in every version of MS Word. But this is also the case in Alpha 16691,10590C87.

**Comment by Adriani90** [comment] 2019-02-05 20:31
Conclusion: The try build improves performance in MS Word. Testing in a more real environment where more documents are open while working will show the real improvement.

**Comment by leonardder** [comment] 2019-02-07 06:19
I also share your findings that the reporting of pages causes a significant performance degradation in many cases.

**Comment by michaelDCurran** [comment] 2019-02-07 06:33
This is caused by the fact that section numbers and text column numbers 
are also announced along with pages when report pages is on.

I am tempted to remove reporting of section numbers all together as they 
are rare, and would usually be conveyed by other means, plus you can 
read the section number on the status bar if you wish.

As for text column number: This is the most costly, but removing it does 
remove important info. However,  the user would still notice the column 
break character between the columns, and now they can also press 
NVDA+numpadDelete, which tells them how far from the left edge they are. 
In a two column page this is quite a good indicator. In deed, we could 
add both text column and section number to NVDA+numpadDelete to have it 
on request.

We could add a new config option specifically for text columns and 
section numbers, but I feel that it obviously wouldn't be on by default, 
and I'd think hardly anyone would ever bother turning it on due to the 
performance issues.


What are peoples' thoughts on this?

**Comment by michaelDCurran** [comment] 2019-02-07 06:34
Oh, and the UIA implementation cannot support section numbers or text 
column reporting automatically. Though we could still add it to 
NVDA+numpadDelete which falls back to the object model anyway.

**Comment by leonardder** [comment] 2019-02-07 07:12
> In deed, we could add both text column and section number to NVDA+numpadDelete to have it on request. 

This makes sense to me.

> We could add a new config option specifically for text columns and section numbers, but I feel that it obviously wouldn't be on by default, and I'd think hardly anyone would ever bother turning it on due to the performance issues.

I tend to agree with that. Just limit it to NVDA+numpadDelete. We can always add a separate config item later on if people insist on it.

**Comment by Adriani90** [comment] 2019-02-07 09:15
I agree with this approach as well but with the condition that NVDA reports how many text columns and how many sections are in the document when entering it.

**Comment by Adriani90** [comment] 2019-02-07 09:38
Then the user would at least know that there are sections and text columns. It is not an ideal solution, especially when documents are converted from pdfs with ocr into MS Word. ABBYY Finereader produces in most cases Word documents with multiple text columns and sections.

**Comment by lukaszgo1** [comment] 2019-02-07 14:56
While reporting text columns and section nubmers by pressing particular command sound reasonable assigning it to NVDA+delete would require having review cursor in the Word window almost all the time when working with it. I do not know how many users  works with review not following focus all the time like I do, but for me reporting it with separate command, or one which do not require review cursor movement would be beneficial.

**Comment by leonardder** [comment] 2019-02-07 15:04
I think it starts making more and more sense to implement a nvda+numpadDelete equivalent for the system caret. Isn't there an issue for this already?

**Comment by Adriani90** [comment] 2019-04-01 16:48
In tables with big paragraphs of text in one cell the performance is still not good but it is much better.

**Comment by Adriani90** [comment] 2023-03-05 22:08
The performance in MS Word has improved significantly during last versions of NVDA. I am not sure if we can close this until a specific case will be reported which show a significant performance drop. I will let this decision to NV Access if they want to close it for now or not.

**Comment by seanbudd** [comment] 2023-03-06 00:12
I am going to close this as stale. New issues should be opened, with specific information, for current performances issues.

**Closed by seanbudd** 2023-03-06 00:12 UTC
Labels: performance, app/microsoft-office
