### ISSUE TITLE
Browse mode: provide a quick navigation key for area menu items on websites

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8313] opened 2018-05-21 09:12 UTC
### Steps to reproduce:
1. Open this website
https://github.com/nvaccess/nvda/issues
2. Log in with your account and open an issue you have created
3. Look for "edit comment"

### Expected behavior:
NVDA should provide a quick navigation key for menu items to find such items much faster.

### Actual behavior:
In the past, "edit comment" was a button, now it is a menu item. It would be more confortable to have a coresponding quick navigation key for this. It applies to several websites.

### System configuration:
NVDA version:
NVDA 2018.1.1

NVDA Installed or portable:
Installed

Windows version:
Windows 10.0.17134

Name and version of other software in use when reproducing the issue:
Google crome 66, Firefox 60.0.1

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
No

**Comment by leonardder** [comment] 2018-05-21 10:15
Duplicate of #7695.

**Closed by leonardder** 2018-05-21 10:15 UTC
