### ISSUE TITLE
Windows 10: the state of some checkboxes is not announced when pressing space bar to toggle them

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5653] opened 2016-01-05 14:24 UTC
Here is an example:
select a file, open the context menu, and then the "open with" submenu.
Open the dialog "choose another application".
back tab once, you should get a checkbox "always use this program".
When you get to it bu tabbing, you can hear if it is checked or not.
When pressing the spacebar to toggle it, nothing is announced, you need to tab and backtab to know the state of the box.

**Comment by Brian1Gaff** [comment] 2016-01-05 17:13
I do not know if this is so for others, but in some cases this effect seems 
to also occur in Windows 7 in the next branch, as does lots of extra error 
dings in the searchboxes  in that operating system, in the latter case there 
seems to be no ill effects other than on the nerves of me.
 :-)

The checkbox issue seems hit and miss in windows 7, otherwise I'd have made 
more of it. its as if something get  forgotten to be spoken sometimes.


--------------------------------------------------

**Comment by jcsteh** [comment] 2016-01-07 06:16
Does this behave as expected if you restart NVDA and immediately try 
again? I can reproduce it sometimes, but a restart fixes it.

Technical: I suspect this is yet another case of UIA events going 
missing after a while, rather like #5470.

**Comment by MichelSuch** [comment] 2016-01-07 06:21
Hi,

You are right, just after restarting NVDA, the problem does not occur.
It makes me remember that sometimes, I encounter the same problem when 
trying to select a file in the explorer by pressing ctrl+space.
selected or unselected is not announced and restarting NVDA fixes the 
problem.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by derekriemer** [comment] 2016-01-07 06:23
This also seems to occur in win 8.1 occasionally when opening the start 
screen where the new thing popping up is not spoken and a restart cures it.

On 1/6/2016 11:21 PM, MichelSuch wrote:
> Hi,
>
> You are right, just after restarting NVDA, the problem does not occur.
> It makes me remember that sometimes, I encounter the same problem when
> trying to select a file in the explorer by pressing ctrl+space.
> selected or unselected is not announced and restarting NVDA fixes the
> problem.
>
>
> Michel SUCH
>
> michel.such@free.fr
> Skype : michel.such
> Twitter : @SuchMichel
>
> Le 07/01/2016 07:16, James Teh a écrit :
> > Does this behave as expected if you restart NVDA and immediately try
> > again? I can reproduce it sometimes, but a restart fixes it.
> >
> > Technical: I suspect this is yet another case of UIA events going
> > missing after a while, rather like #5470.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5653#issuecomment-169565334>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5653#issuecomment-169565841>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by MichelSuch** [comment] 2016-01-07 09:53
Over this, some NVDA's features seem to degrade if you let NVDA run very 
long.
For example, in the tchat window of skype, notification of user typing 
become announced twice, and sometimes typed message are nomore announced 
until you restart NVDA.


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by jcsteh** [comment] 2016-01-28 23:25
Closing as duplicate of #5470, since it seems to be the same underlying issue.

**Closed by jcsteh** 2016-01-28 23:25 UTC
Labels: duplicate
