### ISSUE TITLE
Double or more repeating when using role="status" and Firefox.

### ISSUE THREAD

**Issue by ggazila** [nvaccess/nvda#13409] opened 2022-03-01 18:37 UTC
I have a problem when I try to display dynamic content with `role="status"`. And it works as expected only if I have only one dynamic value. But if there are two dynamic values and I use NVDA with Firefox I see the problem. In that case, the text reads at least two times and I must use `aria-atomic=true `to see all text in `<div>` container.

This problem is only reproducible with NVDA + Firefox. 

### Steps to reproduce:
Run the last version of NVDA.
Go to https://ggazila.github.io/nvda-example/. 
You'll see two buttons. Under the first button I use `<div role="status" aria-atomic="true">...<div>`. Under the seconde one I use `<div role="status" aria-atomic="true">...<div>`. Click the buttons

Above an example of such text
`Found Y results for Y` where X and Y are some random dynamic values. 
You can find the source code by the [link](https://github.com/ggazila/nvda-example/blob/main/src/App.tsx)
### Actual behavior:
Observe that NVDA reads text twice in the first example and reads only some symbols in the second example. There is the screenshot with more details - https://imgur.com/a/HEaJBRJ
### Expected behavior:
NVDA reads text only once as it works with NVDA+Chrome or JAWS+Firefox
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version 2021.3.3
#### Windows version:
Windows 10 Home 21H1

#### Name and version of other software in use when reproducing the issue:
Firefox 98.0
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I tried Version 2020.4. Behaviour is the same
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2024-02-20 21:24
This is not reproducible anymore with NVDA last alpha and Firefox 123 as well as Chrom or Edge 122. Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-02-20 21:24 UTC
Labels: close/worksforme, needs-triage
