### ISSUE TITLE
Speech Viewer and Voice Output are not insync

### ISSUE THREAD

**Issue by lnnus** [nvaccess/nvda#6080] opened 2016-06-16 14:39 UTC
Voice Output skipped reading out the focused field while Speech Viewer captured all using Chrome.

**Comment by jcsteh** [comment] 2016-06-16 15:09
Please provide thorough details, including exact steps to reproduce the 
problem and a test case if necessary.

**Comment by lnnus** [comment] 2016-06-16 16:02
1. Bring up NVDA Speech Viewer and turn on the voice volume
2. Open Chrome browse and start to navigate to the application
3. When one of the Confirmation modal popped up, there is focus on the edit text required field (ex. Package name ) 
-> The NVDA speaker did not read out that focused field but jumped to alert info. However, on Speech Viewer, it captured the focused field and the alert info (see the attachment)  


[NVDA Voice and Speech Viewer.docx](https://github.com/nvaccess/nvda/files/318821/NVDA.Voice.and.Speech.Viewer.docx)

Thanks for your support.

**Comment by jcsteh** [comment] 2016-06-16 16:16
> 2. Open Chrome browse and start to navigate to the application

What application? Please provide a URL or a test page that reproduces the issue.

**Comment by Olina-Roy** [comment] 2017-08-02 19:14
Hey! Was this issue resolved.I am facing a similar issue where the reader is logging about the required edit field but not reading as a voice output.NVDA is directly reading the alert message of the previous field.

**Comment by ehollig** [comment] 2017-08-02 19:24
@Olina-Roy, if you are experiencing the exact same issue, please provide exact steps to reproduce, including the program you used, version of NVDA, what you experienced, and the expected behavior. If it is a similar issue but not the same, please open a new ticket explaining the issue.
@jcsteh does the attachment provide any additional information that would allow for replication of the issue, or is there not enough information provided.

**Comment by Olina-Roy** [comment] 2017-08-04 13:57
@ehollig, I have opened issue #7475.

**Comment by PratikP1** [comment] 2017-08-04 14:30
Based on my testing of #7475, there are factors such as synthesizer used and whether "speak typed word" is switched on which affect this behavior. I am wondering If the same applies here. @lnnus, can we get the following details?
1. NVDA version
2. Browser version
3. URL where the problem occurred or another location where the same happens.
4. Synthesizer used.
5. DO you have "speak typed words) on or off?

**Comment by ehollig** [comment] 2017-10-13 15:45
@lnnus, it would be helpful if you could provide thorough details, including exact steps to reproduce the problem and a test case if necessary. It appears the attachment you have provided contains images, and actual text cases are recommended.

**Comment by feerrenrut** [comment] 2017-10-25 11:06
I had a look at the attachment, while I can see that the problem is some text is displayed in speech viewer that was not heard by the user, there is nothing to go on as to why this might be the case. The URL does not look like something open to the public. Again, I would request an example web site that we can play with, a log file with debug level logging would also be handy.

**Comment by ehollig** [comment] 2018-02-18 01:15
@lnnus, can you provide the requested information in https://github.com/nvaccess/nvda/issues/6080#issuecomment-339294662?
Specifically, can you provide an example website that we can play with that demonstrates this issue, and a log file with debug level logging?

**Comment by ehollig** [comment] 2018-10-26 00:28
Unfortunately, we have not heard from the original author of this issue in over 2 years, and additional information, such as an example website to use, as well as a debug log to look at has been requested but not provided. Closing as invalid for now, unless we are able to get the requested information to proceed with this issue.

**Closed by ehollig** 2018-10-26 00:28 UTC
