### ISSUE TITLE
NVDA read error order of a input box for a Qt application

### ISSUE THREAD

**Issue by pauzhang-61** [nvaccess/nvda#16958] opened 2024-08-05 03:23 UTC
### Steps to reproduce:
1. Open a input box(QLineEdit)
2.  Input number "1234567890" in the input box
3.  Cursor in '0' and then down to '1'; 
4.  NVDA reads as "0988655321"
5.  Cursor back from '1' to '0'
6. It will read as "2345678800"
### Actual behavior:
0
9
8
8
6
5
5
3
2
1
2
3
4
5
6
7
8
8
0
0

### Expected behavior:
0
9
8
7
6
5
4
3
2
1
1
2
3
4
5
6
7
8
9
0
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/user-attachments/files/16490404/nvda.log)

#### NVDA installed/portable/running from source:
Installed from the download app.
#### NVDA version:
Version: 2024.2 (2024.2.0.32555)
#### Windows version:
Windows 10 Pro 22H2  19045.4651
#### Name and version of other software in use when reproducing the issue:
Qt application
![image](https://github.com/user-attachments/assets/5c2467a2-a695-4823-9c89-d4afa41b4b09)
![fc9a1983-35a7-4efc-84f0-a23d4a29db60](https://github.com/user-attachments/assets/7598b120-4483-4dc3-bcee-7aa8023cee38)
From stack, I can see the wrong targetPoint
#### Does the issue still occur after restarting your computer?
Yes. it happens every time.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. they are the same. But no issues in Jaws
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment] 2024-08-06 00:41
Welcome @pauzhang-61 ,

We are unable to process this issue as it stands.
To be able to reproduce this issue, we need a code sample.
Provide a minimal example application so we can test with it.
Please provide source code and a compiled example.

Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images. This would be a copy/paste of text.

Kind Regards,
NV Access Software Developers

**Comment by pauzhang-61** [comment] 2024-08-06 02:54
Thanks @seanbudd for your quick response. 

Here is the source code of example : 
[WidgetTest.zip](https://github.com/user-attachments/files/16504646/WidgetTest.zip)


Here is the compiled example:  WidgetTest.exe

[build-WidgetTest-Qt6_5_2_online-Release.zip](https://github.com/user-attachments/files/16504672/build-WidgetTest-Qt6_5_2_online-Release.zip)

**Comment by pauzhang-61** [comment] 2024-08-07 05:03
@seanbudd  do you need me to provide any more information?

**Comment by seanbudd** [comment] 2024-08-07 06:18
adding context rich, equivalent information, image descriptions to the images in your issue would be appreciated, so that our non-sighted developers can understand the information. Is it possible to print that stack trace to text somehow?

**Comment by pauzhang-61** [comment] 2024-08-08 09:20
In the example, there is a window named "MainWindow" and 3 buttons: "min" button, "max" button and "close" button.

There are three components with vertical layouts on the screen.  
1.  The top part is a Text and an input box.  The text name is TextEdit. Input box can be input anything.
2.  The middle part is a Text and an input box.  The text name is LineEdit. Input box can be input anything.
3.  The bottom part is a Text and an input box.  The text name is PlainTextEdit. Input box can be input anything. 

The information/steps I provided in the ticket are as follows: I input the number 1234567890 in the input box of the middle part and then see the issues.

Steps to reproduce:
Focus on the middle part of the component (LineEdit): 
1. Enter the number "1234567890" into the input box. 
2. Start the cursor at the number '0' and move it one by one until it reaches the number '1'. 
3. NVDA reads it as "0988655321". 
4. Move the cursor back from '1' to '0'. 
5. It will be read as "2345678800".

Actual behavior from NVDA Speech Viewer: 
0
9
8
8
6
5
5
3
2
1
2
3
4
5
6
7
8
8
0
0

Expected behavior:
0
9
8
7
6
5
4
3
2
1
1
2
3
4
5
6
7
8
9
0

**Comment by hwf1324** [comment] 2024-08-09 08:09
I tested the provided WidgetTest sample application using the latest alpha.

The test results were different for the three edit boxes.

And it didn't reproduce the behaviour in this issue description.

For 'TextEdit', an error is reported when the mouse enters any area of this edit box, but the text content is read correctly.

```log
IO - speech.speech.speak (15:50:50.309) - MainThread (9344):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - speech.speech.speak (15:50:52.463) - MainThread (9344):
Speaking ['TextEdit']
ERROR - eventHandler.executeEvent (15:50:55.056) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x010F1E10> with extra args of {'x': 842, 'y': 266}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:50:55.082) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x010F1E10> with extra args of {'x': 842, 'y': 269}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:50:55.119) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x010F1E10> with extra args of {'x': 842, 'y': 270}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
IO - speech.speech.speak (15:50:55.175) - MainThread (9344):
Speaking ['1234567890']
IO - inputCore.InputManager.executeGesture (15:50:59.429) - winInputHook (23532):
Input: kb(laptop):NVDA+control+shift+f1
```

For 'LineEdit', it functions correctly when the mouse enters from a range with text, but also reports an error when there is no text or when it enters an area with no text (e.g. entering an edit box from the right side of the edit box). This edit box seems to be single line, so vertical blank areas with text areas are also normal.

```log
IO - speech.speech.speak (15:49:49.703) - MainThread (9344):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - speech.speech.speak (15:49:51.576) - MainThread (9344):
Speaking ['LineEdit']
IO - speech.speech.speak (15:49:53.103) - MainThread (9344):
Speaking ['1234567890']
ERROR - eventHandler.executeEvent (15:49:56.296) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 901, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.318) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 903, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.359) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 905, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.408) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 909, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.443) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 910, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.505) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 911, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:49:56.538) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x0634B9B0> with extra args of {'x': 912, 'y': 450}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
IO - inputCore.InputManager.executeGesture (15:49:59.972) - winInputHook (23532):
Input: kb(laptop):NVDA+control+shift+f1
```

As for 'PlainTextEdit', it would be completely impossible to navigate with the mouse.

```log
IO - speech.speech.speak (15:51:57.656) - MainThread (9344):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - speech.speech.speak (15:51:59.632) - MainThread (9344):
Speaking ['PlainTextEdit']
ERROR - eventHandler.executeEvent (15:52:00.774) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x01111910> with extra args of {'x': 849, 'y': 611}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:52:00.805) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x01111910> with extra args of {'x': 850, 'y': 615}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:52:00.837) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x01111910> with extra args of {'x': 851, 'y': 618}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
ERROR - eventHandler.executeEvent (15:52:00.867) - MainThread (9344):
error executing event: mouseMove on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x01111910> with extra args of {'x': 851, 'y': 619}
Traceback (most recent call last):
  File "eventHandler.pyc", line 353, in executeEvent
  File "eventHandler.pyc", line 119, in __init__
  File "eventHandler.pyc", line 128, in next
  File "NVDAObjects\__init__.pyc", line 1289, in event_mouseMove
  File "api.pyc", line 275, in setReviewPosition
  File "NVDAObjects\UIA\__init__.pyc", line 1085, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 526, in __init__
ValueError: Unknown position None
IO - inputCore.InputManager.executeGesture (15:52:02.243) - winInputHook (23532):
Input: kb(laptop):NVDA+control+shift+f1
```

They seem to have the same error type, maybe something to do with the UIA implementation?

By the way the tabIndex of this sample program seems to be wrong.

**Comment by pauzhang-61** [comment] 2024-08-12 02:45
@hwf1324  Thanks for your testing!

So it is not a mouse event, it is a key event!

When you test the app, you will need to press the arrow key to navigate it.  We can reproduce it every time.

Would it be possible to have a live debug session and I can show you how to reproduce it.

**Comment by hwf1324** [comment] 2024-08-12 02:55
Ah, sorry for the translation, I didn't realise it was the input cursor.

I've just re-tested and there is no speech output when the left and right arrows move between characters in my case.

**Comment by pauzhang-61** [comment] 2024-08-12 02:59
@hwf1324  this is also an issue seeing in nvda sometimes.

You can try it again and it will work.

**Comment by pauzhang-61** [comment] 2024-08-12 03:00
You can try it in LineEdit (the middle one)!

**Comment by hwf1324** [comment] 2024-08-12 03:12
I retried, and I have to start NVDA after this example programme is open in order to access it (i.e. this programme has to be opened first, and then NVDA restarted, which is a serious problem). But my left and right arrow navigation is fine and I don't encounter an error with this problem

**Comment by hwf1324** [comment] 2024-08-12 03:19
```log
IO - speech.speech.speak (11:18:49.355) - MainThread (5888):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - inputCore.InputManager.executeGesture (11:18:51.419) - winInputHook (5084):
Input: kb(laptop):1
IO - speech.speech.speak (11:18:51.453) - MainThread (5888):
Speaking [CharacterModeCommand(True), '1', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:51.862) - winInputHook (5084):
Input: kb(laptop):2
IO - speech.speech.speak (11:18:51.890) - MainThread (5888):
Speaking [CharacterModeCommand(True), '2', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:52.243) - winInputHook (5084):
Input: kb(laptop):3
IO - speech.speech.speak (11:18:52.265) - MainThread (5888):
Speaking [CharacterModeCommand(True), '3', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:52.685) - winInputHook (5084):
Input: kb(laptop):4
IO - speech.speech.speak (11:18:52.714) - MainThread (5888):
Speaking [CharacterModeCommand(True), '4', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:53.158) - winInputHook (5084):
Input: kb(laptop):5
IO - speech.speech.speak (11:18:53.179) - MainThread (5888):
Speaking [CharacterModeCommand(True), '5', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:53.621) - winInputHook (5084):
Input: kb(laptop):6
IO - speech.speech.speak (11:18:53.636) - MainThread (5888):
Speaking [CharacterModeCommand(True), '6', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:54.065) - winInputHook (5084):
Input: kb(laptop):7
IO - speech.speech.speak (11:18:54.091) - MainThread (5888):
Speaking [CharacterModeCommand(True), '7', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:54.536) - winInputHook (5084):
Input: kb(laptop):8
IO - speech.speech.speak (11:18:54.554) - MainThread (5888):
Speaking [CharacterModeCommand(True), '8', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:54.992) - winInputHook (5084):
Input: kb(laptop):9
IO - speech.speech.speak (11:18:55.004) - MainThread (5888):
Speaking [CharacterModeCommand(True), '9', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:55.507) - winInputHook (5084):
Input: kb(laptop):0
IO - speech.speech.speak (11:18:55.542) - MainThread (5888):
Speaking [CharacterModeCommand(True), '0', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:56.752) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:56.773) - MainThread (5888):
Caret move detected using event. Elapsed 0.00701189 sec, retries 1
IO - speech.speech.speak (11:18:56.782) - MainThread (5888):
Speaking [CharacterModeCommand(True), '0', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:57.286) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:57.304) - MainThread (5888):
Caret move detected using event. Elapsed 0.00763535 sec, retries 1
IO - speech.speech.speak (11:18:57.312) - MainThread (5888):
Speaking [CharacterModeCommand(True), '9', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:57.753) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:57.773) - MainThread (5888):
Caret move detected using event. Elapsed 0.00931573 sec, retries 1
IO - speech.speech.speak (11:18:57.777) - MainThread (5888):
Speaking [CharacterModeCommand(True), '8', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:58.179) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:58.194) - MainThread (5888):
Caret move detected using event. Elapsed 0.00450873 sec, retries 1
IO - speech.speech.speak (11:18:58.201) - MainThread (5888):
Speaking [CharacterModeCommand(True), '7', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:58.640) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:58.646) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:18:58.649) - MainThread (5888):
Speaking [CharacterModeCommand(True), '6', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:59.104) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:59.120) - MainThread (5888):
Caret move detected using event. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:18:59.135) - MainThread (5888):
Speaking [CharacterModeCommand(True), '5', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:18:59.552) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:18:59.557) - MainThread (5888):
Caret move detected using event. Elapsed 0.00199938 sec, retries 1
IO - speech.speech.speak (11:18:59.559) - MainThread (5888):
Speaking [CharacterModeCommand(True), '4', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:00.009) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:00.014) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:00.017) - MainThread (5888):
Speaking [CharacterModeCommand(True), '3', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:00.510) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:00.526) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:00.532) - MainThread (5888):
Speaking [CharacterModeCommand(True), '2', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:00.979) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:00.998) - MainThread (5888):
Caret move detected using event. Elapsed 0.00706124 sec, retries 1
IO - speech.speech.speak (11:19:01.007) - MainThread (5888):
Speaking [CharacterModeCommand(True), '1', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:02.777) - winInputHook (5084):
Input: kb(laptop):leftArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:02.900) - MainThread (5888):
Caret didn't move before timeout. Elapsed: 0.114657 sec
IO - speech.speech.speak (11:19:02.907) - MainThread (5888):
Speaking [CharacterModeCommand(True), '1', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:03.706) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:03.712) - MainThread (5888):
Caret move detected using event. Elapsed 0.00200033 sec, retries 1
IO - speech.speech.speak (11:19:03.716) - MainThread (5888):
Speaking [CharacterModeCommand(True), '2', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:04.127) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:04.136) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:04.139) - MainThread (5888):
Speaking [CharacterModeCommand(True), '3', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:04.547) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:04.553) - MainThread (5888):
Caret move detected using event. Elapsed 0.00114059 sec, retries 1
IO - speech.speech.speak (11:19:04.556) - MainThread (5888):
Speaking [CharacterModeCommand(True), '4', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:04.955) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:04.967) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:04.970) - MainThread (5888):
Speaking [CharacterModeCommand(True), '5', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:05.467) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:05.484) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:05.491) - MainThread (5888):
Speaking [CharacterModeCommand(True), '6', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:05.911) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:05.923) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:05.931) - MainThread (5888):
Speaking [CharacterModeCommand(True), '7', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:06.315) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:06.320) - MainThread (5888):
Caret move detected using event. Elapsed 0.00235868 sec, retries 1
IO - speech.speech.speak (11:19:06.323) - MainThread (5888):
Speaking [CharacterModeCommand(True), '8', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:06.762) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:06.768) - MainThread (5888):
Caret move detected using event. Elapsed 0.00299954 sec, retries 1
IO - speech.speech.speak (11:19:06.771) - MainThread (5888):
Speaking [CharacterModeCommand(True), '9', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:07.194) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:07.200) - MainThread (5888):
Caret move detected using bookmarks. Elapsed 0 sec, retries 0
IO - speech.speech.speak (11:19:07.204) - MainThread (5888):
Speaking [CharacterModeCommand(True), '0', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:08.659) - winInputHook (5084):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (11:19:08.675) - MainThread (5888):
Caret move detected using event. Elapsed 0.00468302 sec, retries 1
IO - speech.speech.speak (11:19:08.682) - MainThread (5888):
Speaking [CharacterModeCommand(True), '0', EndUtteranceCommand()]
IO - inputCore.InputManager.executeGesture (11:19:12.408) - winInputHook (5084):
Input: kb(laptop):NVDA+control+shift+f1
```

**Comment by pauzhang-61** [comment] 2024-08-12 03:25
how many text do you input? like me? 1234567890?

can you send me the nvda speech viewer?

**Comment by hwf1324** [comment] 2024-08-12 03:27
I tried 2024.1 and this issue does exist. However, today NVDA 2024.3rc1 has been released, which means the official version 2024.3 is coming soon, can you try this version to see if this issue exists? I can confirm that at least in the latest alpha version this issue is fixed.

**Comment by pauzhang-61** [comment] 2024-08-12 03:32
My version is 2024.2.  

How can I get the 2024.3rc1 ?

**Comment by hwf1324** [comment] 2024-08-12 03:36
> [NVDA development snapshots](https://www.nvaccess.org/files/nvda/snapshots/): Automatically generated builds of the project in its current state of development

A preview version can be found at the bottom of this page. An alpha development snapshot can also be downloaded from this page.

**Comment by pauzhang-61** [comment] 2024-08-12 03:52
[nvda_2024.3.txt](https://github.com/user-attachments/files/16577216/nvda_2024.3.txt)

I retested with 2024.3rc1. there is still issue. 

for example: 1234567890;  it should read 1234567890

but it read as 2345678900

**Comment by pauzhang-61** [comment] 2024-08-12 03:54
for example: 
Comment
0
9
8
7
6
5
4
3
2
1
2
3
4
5
6
7
8
9
0
0


But it should be 098765432**11**234567890

**Comment by pauzhang-61** [comment] 2024-08-12 03:57
The old version is randomly read like 335, but now this issue is gone. But the first '1' is always missed!

**Comment by hwf1324** [comment] 2024-08-12 04:14
This is the normal behaviour of the current edit cursor, when moving the cursor left or right, it will read aloud the characters to the right of the cursor. In some edit boxes, when you continue to move the cursor beyond the edge, it will repeat the characters of the corresponding edge (such as this edit box).

**Comment by pauzhang-61** [comment] 2024-08-12 05:23
Good to know, Thanks!

When will the 2024.3 be released?

**Comment by seanbudd** [comment] 2024-08-12 05:36
Closing as fixed. 2024.3 should be released next Monday

**Comment by pauzhang-61** [comment] 2024-08-12 06:41
Great!

**Closed** 2024-11-19 17:23 UTC
Labels: close/worksforme, blocked/needs-info, needs-triage
