### ISSUE TITLE
NVDA and extended select lists

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#6046] opened 2016-06-07 16:11 UTC
I have realised problems abound with multiple select lists in different browsers:
1. Not sure if this is the right behaviour, but the single letter shortcut,  'C' does not move to these lists.
2. The single letter shortcut, 'L' for lists does move to these items in Firefox but not Internet Explorer.
3. In Firefox, when using tab to move through a form,  the label for the list is reported along with the current item. In Internet Explorer, only the word 'list' is reported.

**Comment by PratikP1** [comment] 2016-06-07 16:15
Can you please provide example page/pages where you find this behavior?

**Comment by fisher729** [comment] 2016-06-07 16:30
Try
http://www.freedomscientific.com/Training/Surfs-Up/WebTrack.htm
in multiple browsers. Move to the list with the L shortcut, etc.

**Comment by jcsteh** [comment] 2016-07-06 01:24
We decided:

* The c single letter navigation key should jump to select size > 1.
* The l single letter navigation key should not jump to select size > 1.

Note that this issue also covers a problem regarding labelling in IE (point 3 in the description). We'll probably need to address that separately, but how we do that is an open question.

**Comment by Adriani90** [comment] 2019-02-24 20:35
The only thing which is still reproducible in IE11 is
1. Press l: no list is recognized
2. Navigate in browse mode from edit field to edit field with arrow key: the label is not read. Only when using focus mode the label is read properly.

The second issue about reading label is also reproducible in Firefox 75.0.1. In Chrome everything works correctly.

**Comment by Adriani90** [comment] 2019-12-14 17:37
Related issue: #10624.

**Comment by Adriani90** [comment] 2023-03-09 00:20
I am closing this in favor of #10624 since that issue contains a still valid test case and shows better the different type of lists.

**Closed by Adriani90** 2023-03-09 00:20 UTC
Labels: close/duplicate, p2
