### ISSUE TITLE
treeview items in x64 expose wrong position

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#8179] opened 2018-04-13 13:21 UTC
### Steps to reproduce:
run any app compiled in x64 mode, for example installer msiexec. i've used latest nodejs setup file.
click next untill components selection screen.
navigate to components selection treeview

this effect can be seen also in latest version of teamtalk classic x64 build

### Expected behavior:
nvda should speak count of items for example (1 of 10) in treeview

### Actual behavior:
nvda speaks item 1 of 1 every time you navigate with arrow keys

### System configuration:
windows 10 16.299
NVDA version:
latest next

NVDA Installed or portable:
installed

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
yes, all versions of 2017 and 2018.1.1

**Comment by Adriani90** [comment] 2019-05-06 18:10
@Robert-J-H is this maybe a duplicate of #4611?

**Comment by Robert-J-H** [comment] 2019-05-07 06:05
@Adriani90
Yes, but the issue I was referring to there is #7041.
It is all describing the same thing.
Let's make a summary bug for all position related issues.
Other things that come to my mind spontaneously:
[] wrong number of elements in "Taskbar/Running Applications"
[] wrong number of elements in lists with checkboxes (header is being counted).
[] Wrong number of tabs for some application (e.g. twice as many as there should be)
[] wrong number of menu elements (separators and dividers are being counted)

**Comment by Adriani90** [comment] 2019-05-07 08:22
Thanks Robert for replying. I think it makes sense to continue the discussion on this topic on #7041 and to create new issues if some bugs are out of scope. But as far as I understand your statement they all have the same origine. So I am closing this in favor of #7041.

**Closed by Adriani90** 2019-05-07 08:22 UTC
Labels: duplicate
