### ISSUE TITLE
In VS code, NVDA is reading out  extra info after every suggestion.

### ISSUE THREAD

**Issue by balajip881** [nvaccess/nvda#15573] opened 2023-10-04 01:36 UTC
### Steps to reproduce:
open vscode  test/test.js file
type fun and accept  suggestion   function by tabbing 

### Actual behavior:

 screen reader is reading out  "test.js  editor  has auto complete  multi line  function " 

After every suggestion acceptance (tabbing) or  pressing space, focus shifts from  suggestion widget to vscode editor.  
when ever editor gets focus screen reader is reading out filename and auto complete and line content.
For every line, there will be many  suggestions, after every suggestion i need to press ctrl to stop nvda. 

### Expected behavior:
After refocusing from quick suggestion onto editor,
1. when suggestion,  acceptance,  announce suggestion only. do not announce unwanted info like file name and line content and other info like auto complete.
2. when suggestion rejection by pressing space, do not speak anything. 

#### NVDA installed/portable/running from source:
windows msi installer 
#### Windows version:
Edition	Windows 10 Pro
Version	22H2

#### Name and version of other software in use when reproducing the issue:
vscode  x64 1.80.2
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

It is default behaviour of any screen reader  to announce role state, and values. Here i need a improvement to NVDA so that  Refocuing onto editor after completion.
It is not limited to one version of NVDA , Windows and Vscode.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes 
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes 

I have raised same issue in Vscode also. they told me to raise it in NVDA issues as it is a screen reader problem. You can track the issue here.
https://github.com/microsoft/vscode/issues/194255

**Comment by leonardder** [comment] 2023-10-04 05:56
As pointed out in https://github.com/microsoft/vscode/issues/194255, this is not trivial to fix. In my opinion, it is neither the screen readers nor the application authors that have to fix this, rather the browser vendor/accessibility standards authors.
See for example [this](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-both/) aria example. This is best practice but yet the same problem occurs.
When using aria descendant, the browser communicates focus changes to the screen reader. Rather, I'd say it would be better to use a separate kind of event to communicate active descendants. For example, UIA has a difference between a real focus event and the element selected event.
That said, may be there is a way to distinguish ARIA active descendant focus events from real ones, in which case we can change the behaviour in the screen reader. May be @jcsteh knows this.

**Comment by jcsteh** [comment] 2023-10-05 05:11
This is a duplicate of #10887.

**Closed by jcsteh** 2023-10-05 05:11 UTC
Labels: close/duplicate
