### ISSUE TITLE
Don't reannounce focus after switching to focus mode.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#11359] opened 2020-07-08 19:51 UTC
### Steps to reproduce:

1. Ensure the new "Automatically set system focus to focusable elements" is set.
2. Move browse mode to a focusable element.
3. Press NVDA+space.

### Actual behavior:

NVDA announces the element because it gains focus.

### Expected behavior:

To most users, nothing happened, they simply changed modes. We might want to suppress this announcement of focus changing to make it seem like nothing actually happened, because to most users, focus and browse modes location are one in the same. Subsequently, we might want to cause nvda+tab to report where browse mode is, not the real focus, as these concepts bog the user in details and make NVDA harder to use.

#### NVDA version:

alpha-20514,e87d8ab1

**Comment by Adriani90** [comment] 2020-07-08 21:27
Closing as duplicate of #11304.

**Closed by Adriani90** 2020-07-08 21:27 UTC
Labels: close/duplicate
