### ISSUE TITLE
Latency noticeably increases on laptops when unplugged vs connected to AC power

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8824] opened 2018-10-06 06:21 UTC
### Steps to reproduce:

On battery power, use NVDA normally.

### Actual behavior:

There is much higher latency between a keypress, and NVDA's response when plugged in vs running on AC power (a fraction of a second), so much so that it feels unusable and affects your productivity.

### Expected behavior:

No noticeable increase in latency when running on battery.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
All recent versions of NVDA, including 2018.3.2, alpha-16149,e713f614

#### Windows version:
Windows 10 1803 and 1709, possibly earlier versions as well

#### Name and version of other software in use when reproducing the issue:
This is very noticeable on Firefox when browsing, but can be felt when doing anything with NVDA.

#### Other information about your system:
The default power plan is the balanced plan. Besides the list of settings that you can configure in advanced power plan settings, there are numerous other hidden settings that you can enable and configure, some of which is probably responsible for this behaviour.

I've experienced this on my Thinkpad T480 and an Xps 13 9360, and have heard other reports of this as well. 

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes

**Comment by leonardder** [comment] 2018-10-06 06:47
This issue is not caused by NVDA itself. Therefore, I'm closing this as can't fix. I'd advise to ask for assistance on the users list to have this fixed for your specific cases.

I always base my personal power plan of preference on the high performance plan.

**Closed by leonardder** 2018-10-06 06:47 UTC

**Comment by Brian1Gaff** [comment] 2018-10-06 07:04
Almost certainly a power setting issue I'd say as you surmise. Not very much 
software makers would be able to do about it though.
 Its a bit like the old Apple phone slow down system to save on batteries 
and stopping it just running out of power.
 I would imagine one  needs to find out the monitoring software for power 
and knobble it, but that will have an effect on battery life, ie how long it 
can run on the battery.

Even an old core duo xp laptop does this to some extent back in 2013.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Neurrone** [comment] 2018-10-06 08:40
@leonardder I realize this can't be fixed within NVDA itself, but was hoping to use this issue as a discussion platform and if necessary, try to get help from Microsoft to resolve this.

**Comment by jscholes** [comment] 2018-10-06 08:58
Presumably if your entire system is less responsive on battery, every piece of software will be impacted.  So there's not much, if anything, we could discuss here which would be specific to NVDA, unless NVDA is the only piece of software to respond slower to keypresses and every other application continues to work fine.

**Comment by Neurrone** [comment] 2018-10-06 09:00
@jscholes yeah, just NVDA, since imperceptible latency is a requirement for productive use. Its a lot like trying to use NVDA with bluetooth headphones.

**Comment by jscholes** [comment] 2018-10-06 09:11
So there's no problem in other applications, such as media players, audio games or any other program which can cause your computer to make a noise?  Is the responsiveness okay when NVDA is already speaking and you carry out a second action, or while another application is playing audio?  This still sounds like a power-related problem that you're only noticing in NVDA because of how you interact with the screen reader.

**Comment by Brian1Gaff** [comment] 2018-10-06 10:07
There are some sound drivers that seem to have latency if you do not have 
the machine make a sound for a few seconds, but this still sounds like a 
power issue to me.
 Does the machine use an SSD or a normal hard drive?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Brian1Gaff** [comment] 2018-10-06 10:11
Because nvda tends to be in one core of the processor any throttling back 
will probably be seen more in 32 bit programs I have noticed this with 
Firefox for example, assuming a good quantity of ram of course.

I'm not up on the latency of the latest version of Narrator, but it would be 
interesting to find out if this has the same problems.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Neurrone** [comment] 2018-10-30 12:15
@valiant8086 thanks. I'm interested to find out which setting specifically gets rid of this issue, other than just adjusting the power plan to high performance.
