### ISSUE TITLE
NVDA commands not working

### ISSUE THREAD

**Issue by ejensen1031** [nvaccess/nvda#17270] opened 2024-10-09 20:20 UTC
### Steps to reproduce: 
Download NVDA from nvaccess.org. Install application on my work laptop (Dell G7 2018). Start application. Application will not stop reading any text cursor hovers over. Attempt to use keyboard commands to stop speech (have used both Insert + q and Ctrl). Nothing happens. Open PDF document in Adobe Acrobat. Attempt to use keyboard command to read whole page (Insert + a). Screen reader says not supported by this document. Speech still will not stop and commands do not work. Uninstall application and restart computer.
### Actual behavior:
When I install NVDA on my computer, none of the suggested keyboard commands work. Typing the command on my laptop's keyboard either triggers no response at all or, in the specific case of trying to use NVDA to read a PDF document in Adobe Acrobat Pro, says the action is "not supported by this document". While using NVDA, it reads all text that my cursor is hovering over CONSTANTLY, which other users who have used NVDA successfully have said is not their experience. As stated earlier, the suggested commands to stop speech trigger absolutely no response when entered on my keyboard. I can only get the application to stop speaking if I uninstall it from my computer.

### Expected behavior:
I have tried a number of NVDA support resources and tried the commands they suggest for stopping NVDA speech and reading PDFs in Adobe Acrobat using NVDA, but none of them work when I use them

#### Does the issue still occur after restarting your computer?
Yes I have restarted my computer and reinstalled the application many times.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I have only tried the most recent version of NVDA as of 9 October 2024
#### If NVDA add-ons are disabled, is your problem still occurring?
I have not been able to disable NVDA icons as no window ever opens when I install and activate the screen reader
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I cannot access the tools menu most of the time when I download the application

**Comment by ejensen1031** [comment] 2024-10-09 20:31
I was able to fix the Acrobat issue by changing my settings but the command to stop speech still does not work. Nothing happens when I enter it. I have tried both Insert + s, Caps Lock +s, and pressing Ctrl and none of them have worked. Any advice?

**Comment by Adriani90** [comment] 2024-10-09 20:32
This sounds like a weird issue. Are you running NVDA as administrator? Or as an user?
Which security software is installed on your Laptop?

**Comment by ejensen1031** [comment] 2024-10-09 20:34
I'm running it as a user. I do have Webroot SecureAnywhere installed, but other than that it's just the standard windows security

**Comment by ejensen1031** [comment] 2024-10-09 20:35
Restarting my computer causes the application to close, but the issue persists when I open NVDA again

**Comment by seanbudd** [comment] 2024-10-21 23:24
Welcome @ejensen1031 ,

We are unable to process this issue as it stands.

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2024-10-21 23:26
After further investigation the cause of this appears to be WebRoot SecureAnywhere. Please remove this application. Closing this issue as invalid

- https://github.com/nvaccess/nvda/issues/6324
- https://nvda.groups.io/g/nvda/topic/6482570#msg30541

**Closed by seanbudd** 2024-10-21 23:26 UTC
Labels: blocked/needs-info, needs-triage
