### ISSUE TITLE
NVDA_issue with Chrome/IE browser for elements with attribute 'attr.aria-label'

### ISSUE THREAD

**Issue by akumbhar4** [nvaccess/nvda#11207] opened 2020-05-26 14:01 UTC
NVDA Version - 2019.3.1

Chrome - Version 80.0.3987.132 (Official Build) (64-bit)

Was testing for one of the application on Chrome browser using NVDA tool. NVDA was not reading the extra content present for the elements on the page with attribute ' attr.aria-label'.
while JAWS, ChromeVox Classic Extension are able to read the content

Thanks,
Amol

**Comment by Adriani90** [comment] 2020-05-26 14:58
Could you please provide a link to an example or a minimal test case to reproduce?

**Comment by Adriani90** [comment] 2020-05-26 15:03
I tent to think this is related or maybe even a duplicate of #6209.
But we need a test case to be sure if this is the case.

**Comment by akumbhar4** [comment] 2020-05-26 16:13
Actually this is for client application. I won't be able to provide the
application URL.
I will check with developers for code snippet and get back to you.

Thanks & Regards
Amol

**Comment by bhavyashah** [comment] 2020-06-20 14:42
@akumbhar4  This is a friendly reminder to check for a code snippet and share with us a test case for this problem.

**Comment by akumbhar4** [comment] 2020-06-26 11:40
Hi team,

here the code snippet.

<img width="538" alt="Capture" src="https://user-images.githubusercontent.com/65961802/85853247-17369d80-b7aa-11ea-8cd9-19d4b2522de5.PNG">


here we are facing issue for below code in NVDA

[attr.aria-label]="currentAccountText + ' ' + availableBalancetext + ' ' + caAvailableBalance + ' euro '"

Thanks

**Comment by geebru** [comment] 2020-08-25 15:01
@akumbhar4 I know this issue is from  June but it's still open so figured I'd chime in with a comment (if others see this issue):

In the application itself, is the attribute rendering out correctly to `aria-label="accountText..."` or is it staying `attr.aria-label="accountText..."`. The latter means Angular isn't parsing that attribute's value correctly, nor the attribute itself, so it's not actually rendering it out as an aria-label, which might be why NVDA doesn't read it (as that's not a valid attribute).

**Comment by feerrenrut** [comment] 2020-08-28 07:39
@akumbhar4 Could you use the inspect element tool in a web browser to copy the produced HTML? You can of course remove any sensitive content. 

The code snippet you posted previously is not very helpful since it depends on many other aspects of how your site is "built".

It is most likely that the issue as @geebru mentions, a problem with the production of the site which should be directed to the developers of the site.

**Comment by daplo** [comment] 2021-06-15 02:04
Hi team, 
the best example is buttons at official Angular page: https://material.angular.io/components/button/overview
Please test Icon, Fab and mini Fab buttons. 

example rendered HTML:
`<button 
    _ngcontent-brd-c133="" 
    mat-fab="" 
    color="warn" 
    aria-label="Example icon button with a home icon" 
    class="mat-focus-indicator mat-fab mat-button-base mat-warn">
    <span class="mat-button-wrapper">
        <mat-icon _ngcontent-brd-c133="" 
            role="img" class="mat-icon notranslate 
            material-icons mat-icon-no-color" 
            aria-hidden="true" data-mat-icon-type="font">home</mat-icon>    
    </span>
    <span 
        matripple="" 
        class="mat-ripple mat-button-ripple mat-button-ripple-round"></span>
    <span class="mat-button-focus-overlay"></span>
</button>`

**Comment by feerrenrut** [comment] 2021-08-09 04:04
The example from https://github.com/nvaccess/nvda/issues/11207#issuecomment-861114091, in code pen with superfluous attributes removed: https://codepen.io/reefturner/pen/MWmzzdv

With NVDA 2021.1, using this example I can't reproduce the issue, in both browse mode and focus mode the button label is read as expected:
```
browse mode
button    before  
blank
button    Example icon button with a home icon

focus mode
before  button
Example icon button with a home icon  button
```

I have also tested the Icon, Fab and mini Fab buttons on the official Angular page: https://material.angular.io/components/button/overview

Since I can't reproduce the problem I'm closing this issue.

**Closed by feerrenrut** 2021-08-09 04:04 UTC
