### ISSUE TITLE
Search term read before context menu items are spoken on Win10 1607 start screen

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6256] opened 2016-08-10 10:35 UTC
On the start screen when i type a search term (e.g "out" for outlook), when I press the applications key to bring up the context menu, my search term (out) is spoken before context menu items are read.

**Comment by josephsl** [comment] 2016-08-10 18:26
Hi, which version of Windows is this (8, 8.1, 10)? Thanks.

**Comment by Neurrone** [comment] 2016-08-10 23:36
Win10 anniversary. Forgot to mention that important detail somehow...

**Comment by josephsl** [comment] 2016-08-10 23:52
Hi,

Confirmed.

CC @MichaelDCurran, @jcsteh, @feerrenrut, @derekriemer and others.

Technical: argh, context menu itself does not let NVDA know that it has appeared (or perhaps NVDA is choosing to ignore it). According to accevent, at least UIA did notice you typed something, but when context menu appeared, no discernable event was fired.

Can anyone who has access to SDK 14393's accevent try and reproduce so we can find out if this is a UIA implementation problem? If it turns out it's a MS thing, it might be too late to get it into a CU (unless someone from MS says they're working on it), so our best bet is to send a word once Redstone 2 hits the air for Insiders. Thanks.

**Comment by Neurrone** [comment] 2016-08-10 23:55
My bet is that its an implementation problem on Microsoft's end, because other screen readers have trouble with detecting the context menu as well.

**Comment by jcsteh** [comment] 2016-08-11 03:47
It's true that nothing is fired when the context menu appears. However, this context menu is weird anyway; it acts like the search suggestions in that the items don't actually get focus.

That said, just like the suggestions, the speech for the search term should be "cut off" (cancelled) before the speech for the context menu item, and that is what I see here. If I listen very closely, I might hear a tiny chunk of the search term, but it's hardly audible. It seems @Neurrone and @josephsl see different results here, which puzzles me a great deal.

Are you saying that after pressing the applications key (which will speak nothing), every time you press down arrow, you hear, for example, "out" before the context menu item?

**Comment by Neurrone** [comment] 2016-08-11 07:25
It gets quickly cut off, but it is still audible. Maybe the bigger issue might be the events not firing properly.

**Comment by josephsl** [comment] 2016-08-11 07:32
Hi, the other side of this issue is wrong role for this context menu – we expect a popup menu, but it is in fact a list, coupled with event issue as noted earlier. Thanks.

**Comment by jcsteh** [comment] 2016-08-12 05:09
> It gets quickly cut off, but it is still audible.

Sure, but the fact that it is cut off quickly makes this a much more trivial issue than the original report suggested; I thought you were suggesting the whole word was read. How much of the word do you hear? Here, I only hear a tiny glitch, barely even a syllable. Do you see the same effect when moving between search suggestions?

**Comment by Neurrone** [comment] 2016-08-12 14:40
Oh, sorry I didn't mention upfront that this is relatively trivial.

When arrowing through context menu items, I do few a short part of the search term which does get quickly cut off.

The other issue I just noticed is that if your search term has multiple results, arrowing through the results either reads part of the search term, or when you press the arrow key, it reads part of the newly selected item, which gets quickly cut off, and then the item is read again, in full, if that makes any sense.

**Comment by bhavyashah** [comment] 2018-08-19 03:04
@josephsl Since you are always on the latest Windows 10 build, could you please provide a status update for this ticket?

**Comment by josephsl** [comment] 2018-08-19 03:33
Hi, this still happens in latest Insider Preview (17700 series). Thanks.

**Comment by Adriani90** [comment] 2019-03-08 21:57
Did anyone report this already to Microsoft?

**Comment by Adriani90** [comment] 2020-05-02 19:37
This works as expected in Windows 10 1909 Update with NVDA alpha-20097,6a573cd9. Closing as works for me.

**Closed by Adriani90** 2020-05-02 19:37 UTC
Labels: close/worksforme
