### ISSUE TITLE
Key Commands File: Missing Default Input Gestures

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9509] opened 2019-04-22 09:09 UTC
When taking a look through the Input Gestures dialog, I've noticed the following default gestures that are missing from the Key Commands file - could these be added for completeness? See below:

Logs information about the current navigator object which is useful to developers and activates the log viewer so the information can be examined.

Speaks the filename of the active application along with the name of the currently loaded appModule

**Comment by DrSooom** [comment] 2019-04-22 12:53
@elliott94: Which NVDA version was used? And as I said before in issue #9507, please always completely fill out one of the both drafts, otherwise your issues will get closed. Thanks.

**Comment by elliott94** [comment] 2019-04-22 14:34
Tested with an Alpha build; however, these have been missing for some time now.

**Comment by lukaszgo1** [comment] 2019-04-22 14:35
This is a duplicate of #1506. Initially only CTRL+NVDA+F1 is mentioned but at the end of the duscussion @ehollig also mentions NVDA+F1.

**Comment by Adriani90** [comment] 2021-08-18 09:46
Closing as duplicate.

**Closed by Adriani90** 2021-08-18 09:46 UTC
Labels: close/duplicate
