### ISSUE TITLE
Battery Status: Announce Time until Full Charge in Windows 10

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10456] opened 2019-11-02 21:09 UTC
### Describe the solution you'd like

As of Windows 10, my understanding is that the operating system allows users to view the estimated time until the battery has finished charging when the device is connected to power. Is there any way that we could somehow add this into NVDA's battery status command? I haven't yet found out if an API exists that could easily translate this information.

**Comment by leonardder** [comment] 2019-11-07 14:10
Duplicate of #6309

**Closed by leonardder** 2019-11-07 14:10 UTC
