### ISSUE TITLE
Add-On Store Dialog is always triggering "Changes were made" dialog, whether changes were made or not.

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#15719] opened 2023-10-30 22:14 UTC
### Steps to reproduce:
Open NVDA Add-On Store, make no changes, close the dialog via either ALT + F4 or by clicking on the red close X at the upper left

### Actual behavior:
Even when no add-on has been touched (as in none are re-enabled or disables), as soon as the dialog closes the standard NVDA dialog asking, "Changes were made to add-ons. You must restart NVDA for these changes to take effect.  Would you like to restart now?"

### Expected behavior:
The above mentioned dialog should never appear if no changes to Add-Ons have been made while it's open.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3
#### Windows version:
Windows 11, Version 22H2, Build 22621.2428
#### Name and version of other software in use when reproducing the issue:
Not directly relevant
#### Other information about your system:
LG Gram 16, i5 12th Gen processor, 16 GB RAM, 1TB NVMe SSD
#### Does the issue still occur after restarting your computer?
Have not restarted
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.  The note about NVDA having been started with Add-Ons disabled did appear at the top of the Add-Ons Store dialog.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2023-10-30 22:23
This issue is tricky to reproduce. Could you please provide a log with debug logging enabled? We need to know the add-on data causing this.

**Comment by seanbudd** [comment] 2023-10-30 22:23
This issue is tricky to reproduce. Could you please provide a log with debug logging enabled? We need to know the add-on data causing this.

**Comment by britechguy** [comment] 2023-10-30 22:32
Sure.  Do I need to do anything other than have debug logging enabled?  If not, I can fire NVDA up in a short while with debug level logging and send along the log.

**Comment by seanbudd** [comment] 2023-10-30 22:33
Can you reproduce the issue with logging enabled. Thanks

**Comment by britechguy** [comment] 2023-10-30 22:47
I have restarted my computer before running NVDA with debug level logging, so now I can say the system has been restarted after the COM Registration Fixing Tool was run.  No change in behavior.  The log is attached.
[NVDA_2023.3_Log.txt](https://github.com/nvaccess/nvda/files/13210395/NVDA_2023.3_Log.txt)

**Comment by Brian1Gaff** [comment] 2023-10-31 11:27
I have never seen this in Windows 7, However since updating the Win 10 machine yesterday, several oddities have occurred so I don't feel that its fair to accept what that does, since I think Windows has broken.
Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by Nael-Sayegh** [comment] 2023-12-02 18:59
Hello,
I also notice the same issue as @britechguy.
Whenever I exit the addonstore, I constantly get the message to restart NVDA whether I make modifications or not.
I'm using Windows 11 and NVDA 2023.3.
I hope a solution for this problem will be found quickly.

**Comment by CyrilleB79** [comment] 2023-12-02 22:28
An improvement would be that if an add-on remains pendinginstall, i.e. if installation cannot complete after restart, a warning message is displayed to the user; today, there is only an error logged.
There was a GitHub issue about it but I cannot find it for now.

**Comment by Adriani90** [comment] 2023-12-03 00:50
Was closing this issue intentional?

**Comment by britechguy** [comment] 2023-12-03 04:45
> Was closing this issue intentional?

If it was, I have no idea why.  If there's another issue about this same thing (and I don't recall one having been mentioned) it would be good to have that mentioned as part of any closure.

**Comment by CyrilleB79** [comment] 2023-12-03 08:55
Sorry, closing was not intentional.

**Comment by seanbudd** [comment] 2023-12-08 03:45
@britechguy In addition to @lukaszgo1's steps for more information, could you please share your `addonsState.pickle` found in your NVDA user config folder?

**Comment by britechguy** [comment] 2023-12-15 00:20
Am I safe in presuming this will "hit the streets" with NVDA 2024.1?

**Comment by seanbudd** [comment] 2023-12-15 00:34
@britechguy - correct

**Comment by lukaszgo1** [comment] 2023-12-15 11:42
@britechguy Since the approach which has been merged to beta creates its own issues, and therefore it is possible may have to be reverted or at the very least rethought, would you be willing to share the result of Python console commands / state file as @seanbudd  and I asked in the comments above? This ensures we can be certain that whatever is implemented indeed addresses this issue, since until now without access to the requested info it has been necessary to rely on educated guesses.

**Comment by Adriani90** [comment] 2023-12-15 12:33
Reopening, see discussion in #15927.

**Comment by britechguy** [comment] 2023-12-17 00:09
I am sorry it's taken me so long to get around to dealing with this.  I've been slammed for a couple of weeks.

I have just tried what @lukaszgo1 asked for in message comment: https://github.com/nvaccess/nvda/issues/15719#issuecomment-1837457899 

Lo and behold, and for reasons I cannot explain, I am no longer getting the "Changes were made" dialog triggering when no changes were made.  I am using NVDA 2023.3 (2023.3.0.29780).  I am not getting this message triggering whether I have started NVDA with add-ons active or disabled.  This is a change from what I had been experiencing for weeks when playing with the Add-On Store.

**Comment by britechguy** [comment] 2023-12-17 00:10
If you all need me to try something else, do let me know.

**Comment by seanbudd** [comment] 2023-12-17 22:57
This issue is no longer investigable, as it can't be reproduced any more and the results from the python console were not shared.
I think we should close this as can't reproduce until we can get a log with more information and clearer steps to reproduce.

**Comment by lukaszgo1** [comment] 2023-12-18 16:13
I've tried to address this in #15937. At the very least it adds additional logging which should be helpful in similar cases. Obviously we won't be able to tell what caused this issue in the first place. I agree this should be closed.

**Closed** 2023-12-18 19:33 UTC
Labels: p4, blocked/needs-info, triaged, feature/addon-store
