### ISSUE TITLE
 Tables with Irregular Headers in chrome 

### ISSUE THREAD

**Issue by sigal-barak** [nvaccess/nvda#15803] opened 2023-11-19 10:28 UTC
### Steps to reproduce:
NVDA 2023.3 version 
does not  reading properly table Headres in Irregular/multi-level tables in 
chrome 119.0.6045.160
EDGE Version 119.0.2151.72 (Official build) (64-bit)
works properly in firefox.why?
I navigate either using down arrow( like regular text) ,or the NVDA way -Ctrl + Alt and use the arrow keys to move from cell to cell.
example : see this table
https://www.w3.org/WAI/tutorials/tables/irregular/
this is the NVDA speech viewer reading the table headers
Produced Mars, Produced Venus, Mars Produced, Mars Sold, Venus Produced, Venus Sold.

![Screenshot_2](https://github.com/nvaccess/nvda/assets/12710671/fed0e3dc-601f-464b-83f9-2d239b77cdf1)

### Actual behavior:
 
this is the NVDA speech viewer reading the table headers
Produced Mars, Produced Venus, Mars Produced, Mars Sold, Venus Produced, Venus Sold.
 

### Expected behavior:
 
Mars Produced, Mars Sold ,  Venus Produced , Venus Sold.
 
#### NVDA installed/portable/running from source:
2023.3
#### NVDA version:
2023.3
#### Windows version:
windows 10
#### Name and version of other software in use when reproducing the issue:
chrome 119.0.6045.160 

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment] 2023-11-19 11:16
Because you did not fill out the template, I'd suspect this might not be investigated. For example, what you call the latest version of something, may not be, and Chrome is a case in point, they are always tweaking it, so specific builds of everything are important for being able to see what is actually going on.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: sigal-barak 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Sunday, November 19, 2023 10:28 AM
  Subject: [nvaccess/nvda] Tables with Irregular Headers in chrome (Issue #15803)



  Each of the questions and sections below start with multiple hash symbols (#). Place your answers and information on the blank line below each question.
  -->

  Steps to reproduce:
  NVDA latest version , does not reading properly table Headres in Irregular/multi-level tables in chrome .
  works properly in firefox.why?
  example : see this table
  https://www.w3.org/WAI/tutorials/tables/irregular/
  this is the NVDA speech viewer reading the table headers
  Produced Mars, Produced Venus, Mars Produced, Mars Sold, Venus Produced, Venus Sold.



  Actual behavior:
  Expected behavior:
  NVDA logs, crash dumps and other attachments:
  System configuration
  NVDA installed/portable/running from source:
  latest version

  NVDA version:
  latest version

  Windows version:
  windows 10

  Name and version of other software in use when reproducing the issue:
  chrome

  Other questions
  Does the issue still occur after restarting your computer?
  Have you tried any other versions of NVDA? If so, please report their behaviors.
  no

  If NVDA add-ons are disabled, is your problem still occurring?
  Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

**Comment by Adriani90** [comment] 2023-11-19 20:50
Please explain in more detail step by step how you navigate the table with NVDA.

**Comment by sigal-barak** [comment] 2023-11-20 06:53
> Please explain in more detail step by step how you navigate the table with NVDA.

thank you , I navigate either using down arrow , like regular text ,or the NVDA way -Ctrl + Alt and use the arrow keys to move from cell to cell.

**Comment by Adriani90** [comment] 2024-10-13 15:30
Closing as duplicate of #15657.

**Closed by Adriani90** 2024-10-13 15:30 UTC
Labels: close/duplicate, p3, app/chrome, app/edge/anaheim, triaged, blocked/needs-technical-investigation
