### ISSUE TITLE
in NVDA next version latest version the dialog for downloading /postponing update is not displayed

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#8083] opened 2018-03-14 07:33 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. check for updates from the help menu
> 2. after the check is completed, press the OK button,
> 3. notice the error sound with the following log

### Expected behavior:
> dialog with options what to do with the update should come in.

### Actual behavior:
> we have error sound with he dialog not showing up.

### System configuration:
NVDA version:
> next-14945,86530c0a

NVDA Installed or portable: portable

Other information:
> latest wx python enhancements, like a good showstopper. the log says that:
ERROR - unhandled exception (08:32:41.224):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 981, in Notify
  File "updateCheck.pyc", line 426, in _guiExecNotify
  File "updateCheck.pyc", line 517, in _downloadSuccess
  File "updateCheck.pyc", line 356, in __init__
AttributeError: 'module' object has no attribute 'CENTER_ON_SCREEN'

Windows version:
> version 1709 build 16299

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA? no
> Please list them and the result

**Comment by josephsl** [comment] 2018-03-14 07:38
Hi, this has to do with the fact that wxPython 4 does not include CENTER_ON_SCREEN flag. CC @LeonardDer

**Comment by zstanecic** [comment] 2018-03-14 07:43
This is a showstopper, if you planto have it included in 2018.2

Wysłane z aplikacji Poczta dla Windows 10

Od: Joseph Lee
Wysłano: środa, 14 marca 2018 08:39
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] in NVDA next version latest version the dialogfor downloading /postponing update is not displayed (#8083)

Hi, this has to do with the fact that wxPython 4 does not include CENTER_ON_SCREEN flag. CC @LeonardDer

**Comment by leonardder** [comment] 2018-03-14 07:45
This is strictly spoken a bug that is caused by conflicting code in next. I can fix this quite easily, but that will mean that the wx pr has to be merged into master first before the postponing updates pr will be.

**Comment by josephsl** [comment] 2018-03-14 07:49
Hi, sure. I think it might be best to just use wx.CENTER instead (or wx.Center function). Thanks.

**Comment by Brian1Gaff** [comment] 2018-03-14 12:49
Yes its the same on windows 7.

ERROR - unhandled exception (12:45:51.444):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 981, in Notify
  File "updateCheck.pyc", line 426, in _guiExecNotify
  File "updateCheck.pyc", line 517, in _downloadSuccess
  File "updateCheck.pyc", line 356, in __init__
AttributeError: 'module' object has no attribute 'CENTER_ON_SCREEN'


Brian

**Comment by Brian1Gaff** [comment] 2018-03-14 16:31
I've done a manual update from the downloaded copy in %temp%
 Does this mean that the next update should work properly again?

Brian

**Comment by josephsl** [comment] 2018-03-14 16:32
Hi, no, automatic update is still broken until the code responsible for it gets merged into next. Thanks.

**Comment by leonardder** [comment] 2018-03-15 05:01
This is fixed in the most recent Next snapshot, which can be downloaded manually.

Steps to reproduce:

1. Run the most recent next snapshot (i.e. next-14949)
2. Paste the following into a python console and press enter: `import versionInfo; versionInfo.updateVersionType="snapshot:master"`
3. Check for updates. NVDA will download a master snapshot.
4. The install/postpone dialog shows up as expected.

**Closed by leonardder** 2018-03-15 05:01 UTC

**Comment by leonardder** [comment] 2018-03-15 05:03
Note that a much easier way will be installing the most recent next snapshot and waiting for the next next snapshot to be released. However, this seems to be a waterproof testing scenario.
