### ISSUE TITLE
Improve the experience of NVDA Settings - Document Formatting settings

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10427] opened 2019-10-25 23:12 UTC
hi
When using NVDA Settings - Document Formatting, it is confusing to set items to be tiled in the window.

### Is your feature request related to a problem? Please describe.
The check box of the NVDA Settings - Document Formatting setting item is classified into a list box, for example, the following example:
Document Formatting lists:
Font name check box
Comments check box
### Describe the solution you'd like
Set the checkbox of the NVDA Settings - Document Formatting setting to a list box
### Describe alternatives you've considered
none
### Additional context
none
thanks

**Comment by leonardder** [comment] 2019-10-26 10:59
Duplicate of #8699

**Closed by leonardder** 2019-10-26 10:59 UTC

**Comment by josephsl** [comment] 2019-10-26 16:20
Hi, I think this is a duplicate of another request. CC @DerekRiemer
