### ISSUE TITLE
NVDA not offering Browse Mode for custom browser app

### ISSUE THREAD

**Issue by yolpsoftware** [nvaccess/nvda#13493] opened 2022-03-16 11:44 UTC
Our software runs a Chromium browser control. Out of some reason, the browser seems to be not recognized by NVDA as a browser, because it is not possible to switch from Focus Mode to Browse Mode.

This is either a bug in NVDA, or a problem with our app. In the second case, we need to know how to adapt our application such that NVDA recognizes it as a browser, or simply as "browse mode ready".

### Steps to reproduce:

1. Create a .NET WinForms application which contains a CEF (Chromium Embedded Framework) browser control. One example would be the `CefSharp.WinForms.Example` in the [CefSharp codebase](https://github.com/cefsharp/CefSharp) (download the whole codebase, open the solution [CefSharp3.sln](https://github.com/cefsharp/CefSharp/blob/master/CefSharp3.sln) in Visual Studio and select the "CefSharp.WinForms.Example" as the startup project).
2. Run the project while NVDA is running.
3. Press NVDA+Space (Insert+Space).

### Actual behavior:

NVDA does not switch from Focus Mode to Browse Mode.

### Expected behavior:

NVDA should switch from Focus Mode to Browse Mode, so that the text contents in the browser are read by NVDA.

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

2021.3.1

#### Windows version:

Windows 10 Home 21H2

#### Name and version of other software in use when reproducing the issue:

CefSharp 99.2.90.0

#### Other information about your system:

-

#### Does the issue still occur after restarting your computer?

yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

no

#### If NVDA add-ons are disabled, is your problem still occurring?

no add-ons installed

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

yes

**Comment by leonardder** [comment] 2022-03-18 13:14
Is anything holding you back from using Webview 2?

I tried to follow the steps to reproduce, but am getting an enormous bunch of errors and therefore can't build the project.

**Comment by yolpsoftware** [comment] 2022-03-18 14:36
> Is anything holding you back from using Webview 2?

Not sure whether there is a hard requirement for CEF. But at least it would involve refactoring a large codebase.

> I tried to follow the steps to reproduce, but am getting an enormous bunch of errors and therefore can't build the project.

I just created a stripped-down demo [here](https://github.com/yolpsoftware/WinFormsCefTest). Please open this in Visual Studio, switch to Release mode and simply run it. (if there are errors, you might need to "Restore Nuget Packages" by right-clicking on the Solution in Solution Explorer).

Same issue in that demo.

**Comment by leonardder** [comment] 2022-03-18 14:44
The demo works for me.
Normally, NVDA uses the IAccessible2 API to get accessibility information from Chrome. With this embedded version of Chrome, NVDA seems to be unable to query the IAccessible2 interfaces and falls back to plain IAccessible/MSAA. I've seen this in embeded Chrome versions in Qt as well. Pretty sure it is a problem in the embedded version of Chrome.

**Comment by yolpsoftware** [comment] 2022-03-18 14:57
I have just added a second project, which uses Webview 2 instead of CEF.

Same issue there. NVDA does not switch to Browse Mode when Insert+Space is pressed.

Is there a Webview 2 scenario which has been tested to support Browse Mode?

**Comment by leonardder** [comment] 2022-03-18 15:02
When below
`webView21.Source = new Uri("https://en.wikipedia.org/wiki");`
I add:
`webView21.Focus();`
It works like a charm here.

**Comment by yolpsoftware** [comment] 2022-03-18 15:09
Right. Thanks.

**Comment by amaitland** [comment] 2022-03-18 19:32
Try using the following command line arg.

https://peter.sh/experiments/chromium-command-line-switches/#force-renderer-accessibility

See https://github.com/cefsharp/CefSharp/wiki/General-Usage#cefsettings-and-browsersettings for example of setting command line arg.

**Comment by yolpsoftware** [comment] 2022-03-22 08:11
I tried `--force-renderer-accessibility` both in our app and in the [cefclient.exe official build](https://cef-builds.spotifycdn.com/cef_binary_99.2.12%2Bg2977b3a%2Bchromium-99.0.4844.74_windows32.tar.bz2). No difference, Insert+Space still doesn't work.

**Comment by yolpsoftware** [comment] 2022-03-22 10:03
Please note that JAWS is able to use Browse Mode on `cefclient.exe`. Steps to reproduce:

* Download the [official build of CEF](https://cef-builds.spotifycdn.com/cef_binary_99.2.12%2Bg2977b3a%2Bchromium-99.0.4844.74_windows32.tar.bz2).
* Start it with `cefclient.exe --multi-threaded-message-loop --no-sandbox`.
* Run JAWS or NVDA.
* You will see that JAWS offers to step through the website page by pressing the Down Arrow Key. NVDA however does not read the page contents.
* Compare this to an actual browser (Chrome, Firefox, Edge, Safari) or to another web control like Microsoft WebView2, where NVDA reads the document when the user presses the Down Arrow.

**Comment by leonardder** [comment] 2022-03-22 10:16
Do I need to build cefclient myself? I can't find an executable in the tarball you mentioned.
Does JAWS browse mode work in your test app?

**Comment by yolpsoftware** [comment] 2022-03-22 12:18
My fault, I posted the wrong link, sorry! Here's the one with the client:

https://cef-builds.spotifycdn.com/cef_binary_99.2.13%2Bgd9af866%2Bchromium-99.0.4844.83_windows32_client.tar.bz2

Unzip it and switch to the Release folder, then run `cefclient.exe --multi-threaded-message-loop --no-sandbox`.

Yes, JAWS seems to offer browse mode, both in our actual app and in `cefclient.exe`.

**Comment by leonardder** [comment] 2022-03-22 12:40
Interesting enough, as long as I leave out the `--multi-threaded-message-loop`, browse mode works fine here. Why would this parameter be required?

**Comment by yolpsoftware** [comment] 2022-03-22 12:58
Right. Thanks Leonard. Gonna investigate.

**Comment by lukaszgo1** [comment] 2022-03-22 14:01
Assuming this issue occurs only when browser control is in a separate thread this is indeed an NVDA issue but should be closed as a duplicate of #8553

**Comment by leonardder** [comment] 2022-03-22 14:07
pretty sure this can indeed be classified as a duplicate of #8553. Closing this issue in favor of that one.

**Comment by leonardder** [comment] 2022-03-26 07:58
I wrote a proto type to address this. See #13542

**Closed by leonardder** 2022-03-26 07:58 UTC
Labels: blocked/needs-external-fix, triaged
