### ISSUE TITLE
NVDA stops responding in tables with many rows

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#10952] opened 2020-04-07 15:29 UTC
The table has two columns and 1685 rows full of both English and Swahili words. When navigating to the table using down arrow, NVDA remains quiet. after sometimes, it says not responding.
### Steps to reproduce:
1. press windows key
2. press tab once to reach the navigation list
3. press down arrow several times to reach the document folder
4. press enter to open the document folder
5. press down arrow several times to reach the file with that table
6. press enter to open the file
7. press down arrow to first read the text without a table
8. go on pressing down arrow several times to reach the table with two columns and 1685 rows
9. NVDA remains silent
10. after sometimes, NVDA says "not responding"
### Expected behavior:
it should be able to load quickly and read any table regardless of the number of rows and columns. it should not say "not responding."
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NonVisual Desktop Access (NVDA) Version: 2020.1beta1

#### Windows version:
Version: Windows 10.0.19592 Build 19592

#### Name and version of other software in use when reproducing the issue:
Microsoft word 2019 Professional+
#### Other information about your system:
Machine name: DESKTOP-C28GVKH
Machine Id: {7DF14EB0-F3A0-49E1-A882-0E29E93F09A1}
Operating System: Windows 10 Pro Insider Preview 64-bit (10.0, Build 19592) (19592.rs_prerelease.200321-1719)
Language: English (Regional Setting: English)
System Manufacturer: HP
System Model: HP ENVY x360 Convertible 15-cn0xxx
BIOS: InsydeH2O Version 05.12.09F.22 (type: BIOS)
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
Memory: 16384MB RAM
Available OS Memory: 16218MB RAM
Page File: 5433MB used, 13216MB available
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, their behaviours are the same with this version
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, but it is the same

#### Does the issue still occur after restarting your Computer?
Yes
Attachment:
[Istilahi za KiSwahili cha kompyuta - 1.docx](https://github.com/nvaccess/nvda/files/4447641/Istilahi.za.KiSwahili.cha.kompyuta.-.1.docx)
[Istilahi za KiSwahili cha kompyuta - 1.docx](https://github.com/nvaccess/nvda/files/4447647/Istilahi.za.KiSwahili.cha.kompyuta.-.1.docx)
[Istilahi za KiSwahili cha kompyuta - 1.docx](https://github.com/nvaccess/nvda/files/4447648/Istilahi.za.KiSwahili.cha.kompyuta.-.1.docx)
[Istilahi za KiSwahili cha kompyuta - 1.docx](https://github.com/nvaccess/nvda/files/4447653/Istilahi.za.KiSwahili.cha.kompyuta.-.1.docx)

**Comment by Adriani90** [comment] 2020-04-08 09:06
Please try following and report back your results:
1. In NVDA settings / document formating settings, disable the reporting of pages and try to reproduce it again
2. If this problem is still visible, then please disable also the reporting for tables and cell coordinates.

I cannot reproduce it with reporting of pages disabled in MS Word 2016 and NVDA 2019.3.1.

**Comment by jacobchawala** [comment] 2020-04-09 14:16
Yes, I have disabled the reporting of pages, but the issue remained the same. I again disabled the reporting for tables and cell coordinates, but the issue remained the same. I am using Microsoft office 2019.

**Comment by feerrenrut** [comment] 2020-04-09 15:11
I don't think the intention was to close this issue, I'll reopen it.

**Comment by Adriani90** [comment] 2023-03-01 15:38
@jacobchawala could you please test with NVDA 2022.4? Is this problem still occuring?

**Comment by Adriani90** [comment] 2023-09-06 19:39
I cannot reproduce this with NVDA 2023.2, the performance is very good unless you enable reporting of pages in document formating settings of NVDA. And even then the performance is significantly lower but NVDA does not freeze or stops responding. Closing this as works for me.

**Closed by Adriani90** 2023-09-06 19:39 UTC
Labels: close/worksforme, app/microsoft-office
