### ISSUE TITLE
It should be possible to report spelling errors on the braille display

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6763] opened 2017-01-19 15:50 UTC
In softwares that support it, spelling errors can be reported playing a specific sound.
I've been asked by asked by a student that uses to work in a class room if it would be possible to alternatively have spelling errors reported on the braille display, for example by underlining the word with dots 7 and 8, or in any other way.
He uses to work in class with only braille activated (no synthesizer) to not disturb other pupils.

**Comment by pzajda** [comment] 2017-01-20 13:58
Hello,

There is the sound indicator which can be used without voice synth.
But it does not allow the user to be informed of a spelling error when reading the text only with Braille display.
A braille indication might be a very good solution to be able to use NVDA only with a braille display and totally mute the computer to avoid disturbing anybody with sounds.

Thanks and best regards.

**Comment by jcsteh** [comment] 2017-01-25 00:30
P2 because braille-only users don't know about this information otherwise. Note that this is also covered by (and will probably get rolled into) #6785.

**Comment by leonardder** [comment] 2017-04-25 07:16
This seems to be a duplicate of #3022

**Comment by leonardder** [comment] 2018-09-15 07:48
Closing as duplicate of #3022. I gave #3022 priority 2, based on the priority of this duplicate.

**Closed by leonardder** 2018-09-15 07:48 UTC
Labels: p2
