### ISSUE TITLE
Visual Studio: Line numbering related errors

### ISSUE THREAD

**Issue by RudolfWeeber** [nvaccess/nvda#10032] opened 2019-08-03 12:52 UTC
* Line numbers are brailled 3x on empty lines
* Cursor routing keys are off by n characters, where n = number of digits in the line number +1

## Steps to reproduce:
* In visual Studio 2019, enable line numbering (tools->options->editor->all langauges->[X] line numbering).
* Open a text file in the editor

### Actual behavior:
* Placing the cursor on an empty lines, the line number is brailled 3x rather than 1x.
* Pressing a routing key places the cursor too far to the right (1 char per line number digit + 1  for the space before the actual code begins)

### Expected behavior:
Braille line numbers only once, on routing key press, cursor lands at the letter under the routing key

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2rc

#### Windows version:
Win10

#### Name and version of other software in use when reproducing the issue:
Visual Studio 2019.2 (community edition)

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The 3x-brailling of the line numbers was also present in 2019.1. Did not check the routing keys, there

**Comment by leonardder** [comment] 2019-09-19 06:35
NVDA now uses UIA to read the contents of the code editor. I think we should make it possible to use the object model based TextInfo instead.

**Comment by Adriani90** [comment] 2020-12-08 21:18
@leonardder have been any changes to this behavior since your last comment?

**Comment by christopherpross** [comment] 2021-04-13 17:36
yeah the behavior is still the same, the strange thing is, that the speech is not recieving the thribble line numbers, only the braille display is showing it. The textinfo is also showing only one line number.

**Comment by Adriani90** [comment] 2024-06-28 21:52
@christopherpross, @RudolfWeeber are you still having this issue with NVDA 2024.2 and Visual Studio 2022 last update?

**Comment by christopherpross** [comment] 2024-06-28 22:01
@Adriani90  
I cannot check that, because my braille display is broken right now. I could give you feedback in the next week, but think the bug is not fixed.

**Comment by christopherpross** [comment] 2024-07-17 07:20
@Adriani90 
I can not longer reproduce this issue. If linenumbers are activated in visual studio 2022, the linenumbers are not read or printed in braille unless the option in nvda is activated. If this is the case, the linenumbers are correctly on the brailledisplay.

**Comment by Adriani90** [comment] 2024-07-17 07:51
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2024-07-17 07:51 UTC
Labels: close/worksforme, app/visual-studio

**Comment by LeonarddeR** [comment] 2024-07-17 07:53
This was apparently fixed in ef31b1d560
