### ISSUE TITLE
NVDA working with notepad3 will cause Notepad3 to exit unexpectedly

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12019] opened 2021-01-30 10:19 UTC
### Steps to reproduce:
1. Download Notepad3 from the following URL: https://www.rizonesoft.com/download/3943/
2. Unzip Notepad3_5.20.915.1.zip, Then unzip Notepad3_5.20.915.1_x64.zip
3. Execute Notepad3.exe in the Unzipped directory
4. Press Left arrow or Right arrow in the editing area of Notepad3

### Actual behavior:
notepad3 exits after a brief silence from NVDA.

### Expected behavior:
Notepad3 did not exit, it can work with NVDA, just like in other editors.

#### NVDA installed/portable/running from source:
installed and portable.

#### NVDA version:
NVDA2020.4 Beta4 and alpha-21672.

#### Windows version:
Windows 10 20H2 (64-bit) build 19042.746

#### Name and version of other software in use when reproducing the issue:
Notepad3 V5.20.915.1 x64, installed and portable.

#### Other information about your system:
Narrator can work with notepad3, there is no such problem.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by dingpengyu** [comment] 2021-01-30 12:35
cc
@feerrenrut 
The same problem occurs with NVDA alpha-21672.

**Comment by feerrenrut** [comment] 2021-02-03 09:18
Please attach an NVDA log to help us narrow down the issue. It is most likely that Notepad3 has a bug in its accessibility implementation. Has any previous version of NVDA worked with Notepad3

**Comment by cary-rowen** [comment] 2021-02-03 15:11
[nvda_log.txt](https://github.com/nvaccess/nvda/files/5919314/nvda_log.txt)
hello @feerrenrut 
The above is the NVDA log. It may be useful to start reading from line 170.
    I tested NVDA2017.3, NVDA2019.2.1, NVDA2020.4Beta4 and the latest Alpha version to reproduce this problem, but Narrator and JAWS do not have this problem.

**Comment by feerrenrut** [comment] 2021-02-04 08:42
While it's useful to know that Narrator and JAWS don't encounter the same issue, it doesn't mean that the issue is caused by NVDA. NVDA is likely using different accessibility API calls to interact with the application. 

Thank you for supplying the log, I've had a look through this now, and unfortunately don't see any clues about what might be the issue. I checked the Notepad3 project issues and found [Screen Reader compatibility: please go back to typedef long Sci_PositionCR, the standard Scintilla definition #2978](https://github.com/rizonesoft/Notepad3/issues/2978) which looks like it could be the culprit. Good news it is fixed, please try the build listed on that issue or build Notepad3 yourself. I have built the latest master and can confirm release mode x64 build does not crash with the instructions provided on this issue.

**Comment by cary-rowen** [comment] 2021-02-04 14:01
Thanks for the hard work you have done.
@feerrenrut

**Comment by feerrenrut** [comment] 2021-02-05 06:07
Please let me know if you have tried that build, if it works then we can close this issue.

**Comment by cary-rowen** [comment] 2021-02-05 07:14
Hello, I have tried this build and it works as expected. You can close this issue.
Thanks again for your work.
@feerrenrut

**Comment by feerrenrut** [comment] 2021-02-05 07:22
Thanks @cary-rowen

**Closed by feerrenrut** 2021-02-05 07:22 UTC
