### ISSUE TITLE
nvda does not pronounce characters in git bash latest version

### ISSUE THREAD

**Issue by jeanbrazcosta** [nvaccess/nvda#11842] opened 2020-11-18 15:47 UTC
Hello, since I installed the latest version of git 2.29, NVDA stopped reading characters by pressing left and right arrows inside git bash.

Reading is only performed when using the scanning cursor.

To reproduce the problem:

1: install the new version of git 2.29:

2: Open git bach and type for example: git status:

3: try to hear the characters typed by pressing left arrows.

NVDA version: 2020.3 instaled

Windows Version: 10.0.19041 Build 19041

Git version: 2020-10-29)
[nvda.log](https://github.com/nvaccess/nvda/files/5561147/nvda.log)

**Comment by JulienCochuyt** [comment] 2020-12-09 22:29
Confirmed on latest master (d3ba21a3a) ran from source under Windows 10 20H2 19042.630 with Git for Windows v2.29.2(3) and MinTTY.

When moving the cursor at the command prompt by any means (keyboard or braille cursor routing) speech reports "space" and the character at that position on the braille display is indeed replaced by a space.

cc @codeofdusk

**Comment by Adriani90** [comment] 2020-12-10 16:02
@JulienCochuyt is this similar to #9102?

**Comment by JulienCochuyt** [comment] 2020-12-10 17:30
@Adriani90 wrote:
>is this similar to #9102?

I do not know if there is a relationship, but the symptoms are quite different.
Unlike in #9102, here typed characters are echoed fine.
They only somehow disappear from speech and braille when the cursor moves back to them.
I just checked: It not only happens on the Bash command prompt, but also in unrelated prompts like sftp or editors like vim or nano.
I guess retrieving the character at the cursor is broken altogether at least with recent MinTTY.

**Comment by JulienCochuyt** [comment] 2020-12-12 09:53
This is IMHO most likely a duplicate of #11660, with the time lapse between MSYS2 and Git for Windows releases.

**Comment by JulienCochuyt** [comment] 2020-12-13 07:18
Confirmed.
Closing as duplicate of #11660.

**Closed by JulienCochuyt** 2020-12-13 07:18 UTC
