### ISSUE TITLE
warn the user when they reach the last cell of a table, informing them that pressing a Tab again will create a new row (for MS Word)

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4686] opened 2014-12-12 17:19 UTC
**Reported by bhavyashah on 2014-12-12 17:19**
JAWS gives a warning when a user is tabbing around an editable table. When the user reaches the last cell of the table by tabbing, NVDA should also announce the the user has reached the last cell of the table and tabbing again will create a new row.
I guess this announcement should be specific to MS Word, because that is the program where a Tab creates a new row. This announcement can also be made in other situations/programs where Tab creates a new row.
This comes in the scope of a screen reader, because while reviewing a document, a screen reader user would not know that the next Tab would unnecessarily create a new row, which would have to be undone.

**Comment by bhavyashah** [comment] 2017-09-30 18:17
Duplicate of #3018

**Comment by ehollig** [comment] 2017-09-30 18:35
Closing as duplicate of #3018

**Closed by ehollig** 2017-09-30 18:35 UTC
Labels: enhancement, Microsoft Office support
