### ISSUE TITLE
Increasing indent forever!

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#10260] opened 2019-09-21 21:13 UTC
### Steps to reproduce:

1. open https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/ in firefox.
2. go to the bottom of the page.
3. read by line up, until you enter the terminal, and keep going.

### Actual behavior:

NVDA starts reporting a line, the next time arrow up is pressed in the terminal, it reports the same line indented by 1 space, and adds 1 more space every time up arrow is pressed, until 100 spaces is reached.

### Expected behavior:

It moves past that line.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
Version: alpha-18633,65a2c3c2

#### Windows version:

Windows version: Windows 10Ver1809 (64-bit) build 17763.737

#### Name and version of other software in use when reproducing the issue:

Firefox: 71.0a1 (2019-09-15) (64-bit)

**Comment by jcsteh** [comment] 2019-12-14 01:33
Probably the same underlying issue as #2812. Possibly a duplicate, though #2812 talks specifically about a pre tag, where I think it's possible to manifest this in other ways and I haven't checked the real world example Derek provided.

**Comment by Adriani90** [comment] 2020-01-11 20:36
@derekriemer is this hapenning regardless of howmany characters per line is set up in NVDA's browse mode settings?

**Comment by derekriemer** [comment] 2020-01-13 06:57
Okay this is very weird.

Go to that page.
set the line length to 103.
Move up from just below the $ like we were doing before. You'll see exactly one space then indent increases forever, at least I thought it was forever. It stops near the line length boundary.

Now set it to 104. Try it again. For me, the increasing indent doesn't reproduce here, or from what I can tell, anywhere above this threshold.

Now, set it to 102, 101, 100, etc.
Notice how the increasing indent starts out indented by n+1 spaces, where n is the offset from 103. I.e. 103-(103-1)+n
This continues until the number of indents is 50, where it resets back to 1.
Also, once the indent gets low enough, weird things happen when using the down arrow (it just gets stuck).

**Comment by Adriani90** [comment] 2023-03-08 23:36
@jcsteh, @derekriemer I cannot reproduce this issue anymore in Firefox 110.0.1 and NVDA last alpha. Are you still able to reproduce it?

**Comment by Adriani90** [comment] 2023-03-17 00:04
Ok then I am closing this one for now, let's reopen it when a concrete example test case appears.

**Closed by Adriani90** 2023-03-17 00:04 UTC
