### ISSUE TITLE
NVDA reading iframe title twice

### ISSUE THREAD

**Issue by ianmclean2011** [nvaccess/nvda#6408] opened 2016-09-27 16:16 UTC
I've noticed that NVDA seems to be reading my iframe titles twice. The first time it says the title, followed by iframe. The second time it says the title, followed by document. For example, with 

```
<iframe title="Hello">
```

NVDA would read: Hello iframe Hello document.

I've only checked it in Firefox (version 42). I tried NVDA version 2016.2, and 2016.3.

**Comment by feerrenrut** [comment] 2016-10-07 03:04
I think we need a more detailed description of how to reproduce this issue. Particularly whether this happens when cursoring around or when tabbing around the document.

Todo:
- [ ] Attach a test case html file to the issue.
- [ ] Include more detailed how to reproduce steps.

**Comment by feerrenrut** [comment] 2016-10-14 05:10
## How I tested this:

- Using the attached html files (unzip them) [TestIFrameHtml.zip](https://github.com/nvaccess/nvda/files/528695/TestIFrameHtml.zip)
 - This contains two html files, The first, `iFrameTitleTest.html` has some text before and after an IFrame element. The IFrame element uses the second html file (`IFrameContent.html`) as its source.
- navigate to the unzipped directory in a shell with access to python
- run `python -m SimpleHTTPServer` you should get output like: `Serving HTTP on 0.0.0.0 port 8000`
- open your browser with URL: `http:\\127.0.0.1:8000\iFrameTitleTest.html`

## Testing with 2016.3 (run from launcher):

### Chrome (version 53):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> Yo this is the IFrame title
> out of IFrame
> This text is after the iFrame.

### FireFox (version 48):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content. 
> out of IFrame
> This text is after the iFrame.

### Internet Explorer (version 11.321):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> frame
> This is the IFrame Content.  
> out of frame
> This text is after the iFrame.

### Edge (version 38.14393.0.0):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> 
> blank
> This is the IFrame Content. 
> 
> blank
> This text is after the iFrame.

## Testing with next 13643,b38d31ee from Thu Oct 13 11:33:26 2016 run with launcher.

### Chrome (version 54 - updated while performing the tests):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content.
> out of IFrame
> This text is after the iFrame.

### FireFox (version 49.0.1 - updated while performing the tests):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content. 
> out of IFrame
> This text is after the iFrame.

### Internet Explorer (version 11.321):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> frame
> This is the IFrame Content.
> out of frame
> This text is after the iFrame.

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> blank
> IFrame
> This is the IFrame Content. 
> out of IFrame
> blank
> This text is after the iFrame.

## Testing by running from source with commit b38d31ee (same as the 'next' version used)

### Chrome (version 54)

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content.
> out of IFrame
> This text is after the iFrame.

### Firefox (version 49.0.1)

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content. 
> out of IFrame
> This text is after the iFrame.

### Internet Explorer (version 11.321):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> frame
> This is the IFrame Content.  
> out of frame
> This text is after the iFrame.

### Edge (version 38.14393.0.0):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> 
> blank
> IFrame
> This is the IFrame Content. 
> out of IFrame
> blank
> This text is after the iFrame.

## Note:
Since several of the browsers updated after the first test with 2016.3, I ran it again.

## Testing with 2016.3 (run from launcher):

### Chrome (version 54)

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content.
> out of IFrame
> This text is after the iFrame.

### Firefox (version 49.0.1)

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> IFrame
> This is the IFrame Content. 
> out of IFrame
> This text is after the iFrame.

### Internet Explorer (version 11.321):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> frame
> This is the IFrame Content.  
> out of frame
> This text is after the iFrame.

### Edge (version 38.14393.0.0):

> This is a test document to check the behavior of iFrame titles. An iFrame is up next.
> 
> blank
> This is the IFrame Content. 
> 
> blank
> This text is after the iFrame.

## Conclusions

- The initial behavior where the IFrame title was spoken in Chrome seems to have gone now that the version is 54.
- The Edge behavior has changed between `2016.3` and `next`. NVDA now reports entering and exiting the IFrame.

**Comment by feerrenrut** [comment] 2016-10-14 05:12
In short, @ianmclean2011 I'm not able to reproduce the behaviour you described. Would you mind trying this again? Or perhaps my example html differs from yours?

**Comment by feerrenrut** [comment] 2016-10-14 09:36
Note: #6465 will change the wording of "IFrame" to "Frame". This fixes the inconsistencies seen here between Internet explorer and chrome / firefox.

**Comment by feerrenrut** [comment] 2016-11-02 02:20
I'm going to close this issue since we are unable to reproduce it, please re-open the issue if you have more information and we will look into it further.

**Closed by feerrenrut** 2016-11-02 02:20 UTC

**Comment by derekriemer** [comment] 2016-11-02 02:47
put the worksforme label on this.
