### ISSUE TITLE
Chrome Browser [Omnibox]: Announces 'unselected' when a user types the second letter of a keyword search result

### ISSUE THREAD

**Issue by cdkim1212** [nvaccess/nvda#13521] opened 2022-03-21 19:32 UTC
### Steps to reproduce:
1. Turn on NVDA and Chrome Browser
1. Activate keyword search by typing a letter that corresponds to a saved keyword search in the omnibox
type the second letter of the result that has been selected in the suggestion list

### Actual behavior:
Announce the remaining string result and "selected" at the end of the string announcement

### Expected behavior:
NVDA announces the letter typed and then says "unselected" (this happens for the second letter as well as any letters after the second one)
Note: Sometimes it announces the entire result and at the end says "selected instead" instead of "unselected"

#### NVDA installed/portable/running from source:
N/A

#### NVDA version: 
2021.3.4

#### Windows version:
Windows 10 Version 20H2 (Build 19042.1526)

#### Name and version of other software in use when reproducing the issue:
Chrome Browser Version 101.0.4919.0

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2021.3.3. Same behavior occurs

#### If NVDA add-ons are disabled, is your problem still occurring?
N/A

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by feerrenrut** [comment] 2022-03-28 05:01
This looks like a duplicate of https://github.com/nvaccess/nvda/issues/13145 which contains more information that this issue.
Closing this issue, triaging #13145 instead.

**Closed by feerrenrut** 2022-03-28 05:01 UTC
