### ISSUE TITLE
Bug Report - NVDA does not announce correct information of list items on ‘Microsoft 365' control while navigating in browse mode using arrow keys - in most Microsoft web pages headers

### ISSUE THREAD

**Issue by codetigers314159** [nvaccess/nvda#11965] opened 2020-12-22 18:14 UTC
### Steps to reproduce: Open any Microsoft page with a UHF (Universal header and footer): 

example1: [https://www.microsoft.com/en-us](url)
example2: [https://www.microsoft.com/en-us/howtotell/default.aspx](url)

Summary:

- Step 1: Enable NVDA and Open the above URL in chrome browser.
- Step 2: Navigate to **‘All Microsoft’** button using tab key and activate it.
- Step 3: Navigate to **‘Microsoft 365’** control using down arrow key in browse mode.
- Step 4: Observe whether NVDA announces correct information of **list items** or not.

 In all cases it is announcing list items twice - sometimes the same count, sometimes not the same count - confusing.

Example 1 - Microsoft main page (for US):

Please open url: [https://www.microsoft.com/en-us/](url)

1a) If there is some announcement on the top please close/exit it.

2a) The items below are for the US English pages (en-us) - the user has another language it may be reflected in the Ms page.
Most Microsoft pages have localization for all major countries, our research shows this bug is present in all of them.

3a) Now you are at the Universal Header (UH)  that has The Microsoft (or Ms) logo and company name, then Microsoft 365, Office, Windows, Surface, Xbox, Deals, Support. Then on the right side we have 'All Microsoft', Search, Cart and Sign In.
 
4a) The issue or bug is with the 'All Microsoft' anchor or control.

5a) Turn on NVDA (any recent version), open the page above, navigate in browse mode:

6a) Click left of the MS icon, tab via the menu until 'Microsoft 365', press enter, the large window opens with the 1st column that says 'Software'. Then click the down arrow key and we get this message that is confusing for user with visual disabilities:

'list  with 7 items  list  with 7 items  link    Windows Apps'  (from the NVDA speech viewer).

Example 2 - MS HTT page (How to tell)

Please open url example2 : [https://www.microsoft.com/en-us/howtotell/](url)

1b) If there is some announcement on the top please close/exit it.

2b) The items below are for the US English pages (en-us)

3b) Now you are at the Universal Header (UH)  that has The Microsoft (or Ms) logo and company name, then **How to Tell**, Home, What to look for, Shop, Licensing, Report counterfeit.  Then on the right side we have 'All Microsoft', Search, Cart and Sign In.
 
4b) The issue or bug is with the 'All Microsoft' anchor or control.

5b) Turn on NVDA (any recent version), open the page above, navigate in browse mode:

6b) Click left of the MS icon, tab via the menu until 'Microsoft 365', press enter, the large window opens with the 1st column that says 'Software'. Then click the down arrow key and we get this message that is confusing for user with visual disabilities:

(from the NVDA Speech Viewer with some previous details)

Report counterfeit  link  
navigation landmark    list  with 1 items  All Microsoft expand to see list of Microsoft products and services  button  collapsed  
expanded
list  with 8 items  list  with 7 items  link    Microsoft 365

### Actual behavior:

We are discussing the possible bug where the NVDA reads a list twice like above, and 
in most the count of items is different (or 1 off?) like in: 

list  with 8 items  list  with 7 items  link    Microsoft 365

### Expected behavior:

NVDA should announce correct information of list items on ‘Microsoft 365 control while navigating in browse mode using arrow keys.

NVDA should announce as "list with 7 items link Microsoft 365" - in both examples.

### System configuration

Test env#1:

Laptop:
Screen Reader: NVDA (2020.3) 
OS: Windows 10 Enterprise (OS build	19042.685)
Version	20H2
Installed on	‎9/‎29/‎2020
Experience	Windows Feature Experience Pack 120.2212.551.0

Browsers:
MS Edge - Version 87.0.664.60 (Official build) (64-bit) - uses Chrome libs
Chrome - Version 87.0.4280.88 (Official Build) (64-bit)

Test Env#2 Older windows, older NVDA

OS: Win 10 Version 2004 (OS Build 19587.1000) 
Browser: Chrome Version (80.0.3987.149)
Screen Reader: NVDA(2019.3.1)

#### NVDA installed/portable/running from source:

installed on windows

#### NVDA version:

Screen Reader: NVDA(2019.3.1)
and
Screen Reader: NVDA (2020.3)  latest download

#### Windows version:

OS: Windows 10 Enterprise (OS build	19042.685)
and
OS: Win 10 Version 2004 (OS Build 19587.1000) 

#### Name and version of other software in use when reproducing the issue:

n/a

#### Other information about your system:

n/a

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes - several versions, including the latest version, same issue.

#### If addons are disabled, is your problem still occurring?

no addons. Also happens in Chrome incognito.
In edge removed all extensions etc - same problem.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes - did not make any difference.

### NVDA LOG Files - speech viewer - HTT url - up to incorrect message list:

Welcome to NVDA  dialog  Welcome to NVDA!
Most commands for controlling NVDA require you to hold down the NVDA key while pressing other keys.
By default, the numpad Insert and main Insert keys may both be used as the NVDA key.
You can also configure NVDA to use the CapsLock as the NVDA key.
Press NVDA+n at any time to activate the NVDA menu.
From this menu, you can configure NVDA, get help and access other NVDA functions.
Options  grouping
Keyboard layout:  combo box  laptop  collapsed  Alt+k
FolderView
prod irpms
New Tab - Google Chrome
Address and search bar  edit  has auto complete  Ctrl+L  microsoft.com/en-us/howtotell/default.aspx
New Tab  document
:host { --cr-icon-button-fill-color: var(--google-grey-refresh-700); --cr-icon-button-icon-start-offset: 0; --cr-icon-button-icon-size: 20px; --cr-icon-button-size: 36px; --cr-icon-button-height: var(--cr-icon-button-size); --cr-icon-button-transition: 150ms ease-in-out; --cr-icon-button-width: var(--cr-icon-button-size); -webkit-tap-highlight-color: transparent; border-radius: 4px; color: var(--cr-icon-button-stroke-color, var(--cr-icon-button-fill-color)); cursor: pointer; display: inline-flex; flex-shrink: 0; height: var(--cr-icon-button-height); margin-inline-end: var(--cr-icon-button-margin-end, var(--cr-icon-ripple-margin)); margin-inline-start: var(--cr-icon-button-margin-start); outline: none; user-select: none; vertical-align: middle; width: var(--cr-icon-button-width); } :host([disabled]) { cursor: initial; opacity: var(--cr-disabled-opacity); pointer-events: none; } :host(.no-overlap) { --cr-icon-button-margin-end: 0; --cr-icon-button-margin-start: 0; } :host-context([dir=rtl]):host(:not([dir=ltr])) { transform: scaleX(-1); } :host(:not([iron-icon])) #maskedImage { -webkit-mask-image: var(--cr-icon-image); -webkit-mask-position: center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: var(--cr-icon-button-icon-size); background-color: var(--cr-icon-button-fill-color); height: 100%; transition: background-color var(--cr-icon-button-transition); width: 100%; } #icon { align-items: center; border-radius: 4px; display: flex; height: 100%; justify-content: center; padding-inline-start: var(--cr-icon-button-icon-start-offset); position: relative; width: 100%; } iron-icon { --iron-icon-fill-color: var(--cr-icon-button-fill-color); --iron-icon-stroke-color: var(--cr-icon-button-stroke-color, none); --iron-icon-height: var(--cr-icon-button-icon-size); --iron-icon-width: var(--cr-icon-button-icon-size); transition: fill var(--cr-icon-button-transition), stroke var(--cr-icon-button-transition); } paper-ripple { --paper-ripple-opacity: var(--cr-icon-button-ripple-opacity, .21); } @media (prefers-color-scheme: dark) { :host { --cr-icon-button-fill-color: var(--google-grey-refresh-500); } paper-ripple { --paper-ripple-opacity: var(--cr-icon-button-ripple-opacity, .4); } }   button    More actions  HTT prod  visited  link    HTT prod
New Tab
visited  link    button    :host { --cr-icon-button-fill-color: var(--google-grey-refresh-700); 

How To Tell - Home
clickable  link    Skip to main content
banner landmark    visited  link    Microsoft
visited  link    How to Tell
Contextual menu  navigation landmark    list  with 5 items  visited  link    Home  link    What to look for  link    Shop  link    Licensing  link    Report counterfeit  out of list
navigation landmark    list  with 1 items  button  collapsed    All Microsoft expand to see list of Microsoft products and services  out of list
search landmark    button  collapsed    Search Microsoft.com
link    0 items in shopping cart
link    Sign in to your account
main landmark    graphic    Home Page Banner
heading    level 2  Learn, verify and buy with confidence
clickable  banner landmark    Microsoft  visited  link  
How to Tell  visited  link  
Contextual menu  navigation landmark    list  with 5 items  Home  visited  link  
What to look for  link  
Shop  link  
Licensing  link  
Report counterfeit  link  
navigation landmark    list  with 1 items  All Microsoft expand to see list of Microsoft products and services  button  collapsed  
expanded
list  with 8 items  list  with 7 items  visited  link    Microsoft 365

---- invalid list above

### NVDA LOG File :

INFO - __main__ (14:02:13.135) - MainThread (45472):
Starting NVDA version 2020.3
INFO - core.main (14:02:13.312) - MainThread (45472):
Config dir: C:\Users\v-ragarc\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (14:02:13.312) - MainThread (45472):
Loading config: C:\Users\v-ragarc\AppData\Roaming\nvda\nvda.ini
INFO - core.main (14:02:13.760) - MainThread (45472):
Using Windows version 10.0.19042 workstation
INFO - core.main (14:02:13.760) - MainThread (45472):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (14:02:13.761) - MainThread (45472):
Using comtypes version 1.1.7
INFO - core.main (14:02:13.761) - MainThread (45472):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDrivers.espeak.SynthDriver.__init__ (14:02:14.057) - MainThread (45472):
Using eSpeak NG version b'1.49.3 dev'
INFO - synthDriverHandler.setSynth (14:02:14.122) - MainThread (45472):
Loaded synthDriver espeak
INFO - core.main (14:02:14.123) - MainThread (45472):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (14:02:14.124) - MainThread (45472):
Braille input initialized
INFO - braille.initialize (14:02:14.124) - MainThread (45472):
Using liblouis version 3.14.0
INFO - braille.initialize (14:02:14.126) - MainThread (45472):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (14:02:14.130) - MainThread (45472):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (14:02:14.293) - MainThread (45472):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:02:14.308) - _UIAHandler.UIAHandler.MTAThread (69424):
UIAutomation: IUIAutomation6
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (14:02:14.458) - MainThread (45472):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (14:02:14.459) - MainThread (45472):
No user gesture map
INFO - core.main (14:02:14.501) - MainThread (45472):
NVDA initialized
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (14:02:14.638) - MainThread (45472):
No CLDR data for locale en_GB
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getFormatFieldAndOffsets (14:02:56.156) - MainThread (45472):
could not get attributes
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 233, in _getFormatFieldAndOffsets
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467263, 'Not implemented', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (14:02:56.697) - MainThread (45472):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - Python warning (14:03:09.959) - MainThread (45472):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:549: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2WindowHandle (14:03:36.481) - MainThread (45472):
IAccessible2::windowHandle failed: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (14:03:39.888) - MainThread (45472):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - Python warning (14:03:39.919) - MainThread (45472):
C:\Program Files (x86)\NVDA\library.zip\api.py:287: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (14:06:16.778) - MainThread (45472):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (14:06:58.064) - MainThread (45472):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

**Comment by Adriani90** [comment] 2023-02-06 14:53
@codetigers314159 do you still see this issue with the last Chrome and Edge versions and the last version of NVDA?

cc: @seanbudd

**Comment by Adriani90** [comment] 2023-04-12 22:30
I cannot reproduce this issue with NVDA last alpha in Chrome or Edge 113. I think it might be reproducible when you turn off autmatic set focus to focusable elements in browse mode settings of NVDA or with nVDA+8. how ever, since that automatic focus synchronisation between NVDA's virtual cursor and system focus will be removed in the future, that setting will not be relevant anymore. I am closing this issue as works for me. If you still have this issue please comment with updated steps to reproduce and we can reopen.
Make sure to turn off automatic set focus to focusable elements in NVDA's browse mode settings when reproducing this issue.

**Closed by Adriani90** 2023-04-12 22:30 UTC
Labels: close/worksforme

**Comment by XLTechie** [comment] 2023-04-12 22:52
> I cannot reproduce this issue with NVDA last alpha in Chrome or Edge 113. I think it might be reproducible when you turn off autmatic set focus to focusable
> elements in browse mode settings of NVDA or with nVDA+8. how ever, since that automatic focus synchronisation between NVDA's virtual cursor and system focus
> will be removed in the future, that setting will not be relevant anymore.

@Adriani90 If the setting goes away, the effect will be that it's always 'off'. 
Therefore, if you can replicate this with the setting off, it remains relevant 
as that will be the future condition, will it not?
