### ISSUE TITLE
Please use po file to make documentation translation.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#12576] opened 2021-06-23 11:52 UTC
Hi all:
I think all translators know when they were making  document translation,  They must looked for all subversion to find what paragraph had been changed. It is waste all translator's time. Please use po file to replace txt2tag and to allow more and more translator to join our team. NVDA addon community is the best demo site to let us know that it is a good solution. Please all translators come out to discuss this. Thanks!

**Comment by gregjozk** [comment] 2021-06-23 13:09
inside revision folder is also file, where differences between previous and current version of original documentation has been listed. it is enough for me. moreover, when working with longer text, I prefer to work with Notepad++ instead of poedit.
another suggestion, could be this discussion moved to translation mailing list?

best regards,
Jožef

**Comment by bdorer** [comment] 2021-06-23 13:59
I disregard. If you use userGuide-structureDifferences and you sync
userguide with original the you see very quickly where changes are in
userGuide-newRevisions\revisionNumber\differences.txt so I wote for closing.

**Comment by cary-rowen** [comment] 2021-06-23 14:05
If you use po files, it may be easier for novices to learn, because not everyone is technically proficient, but their translation skills may be great.
Regarding the detailed changes in the long text, it is undeniable that git diff has its advantages, but I hope that more people will participate in the translation, and I hope it will be more friendly to novices.

**Comment by vgjh2005** [comment] 2021-06-24 09:11
Hi:
@bdorer 
@gregjozk
Had you made NVDA addon comunity site translation? We just need to press down arror to look for what it is then translate it to our language. Now, we need to open the diff file , open the t2t file, then jump to the specific position then select some thing to define ether delete or change them. 
The second, because of upgrade process, some content need to be changed one more time. So, diff file isn't a convinient way for all translator members.
If it is a po file, we just need to change it at once in the end of the translation deadline. 
We needn't to open more file, we needn't to open different files for the whole translate process, we needn't to jump to the different place all the time. Our time is most valued.
So please reconsider this resolution. Thanks!

**Comment by xingkong0113** [comment] 2021-06-30 22:54
I support using .po to replace txt2tags.
On the other hand, .po can reduce the size of the translation repository.

**Comment by ehollig** [comment] 2023-02-24 16:44
What is the status of this? It sounds as this issue should be discussed and resolved on the translators mailing list

**Comment by Adriani90** [comment] 2023-02-27 10:29
I think a solution for this needs to come from the community, every string has to be defined with _() and this means NV Access has to define the string length and so on every time a new release of NVDA is planed. For GUI translations .po files are nice, but for user guides and so on this might mean a pain for developers.

**Comment by ruifontes** [comment] 2023-02-27 12:06
And why not create a script to transform t2t files in po files?
It is not the way community uses to translate the add-ons readme.md files?
I, not a programer, have wrote a small add-on to transform readme.md in nvda.po files to strongly speed up translation using the automatic translation and suggestions of POEdit...

**Comment by Adriani90** [comment] 2023-02-27 13:02
@ruifontes the userguide, changes file and keycommands file are formated in git flavour markdown while the addon documentation is not. This means every NVDA core doc would have to be restructured from scratch, including the automated tasks that are implemented such as synchronisation between userguide and keycommands document etc.
For more details see the discussion in #8734, #9840 and #9968.

**Comment by Adriani90** [comment] 2023-02-27 13:06
I would rather say before re-structuring all the documents, find an alternative translation system which displays the t2t files into a web based module or something like that. In that case even .po files could be transfered in a web based module and you wouldn't need any external software on your PC to translate NVDA. The problem is, most of these kind of translation systems are paid solutions, none of them is completely free.

**Comment by dpy013** [comment] 2023-03-01 10:53
> I would rather say before re-structuring all the documents, find an alternative translation system which displays the t2t files into a web based module or something like that. In that case even .po files could be transfered in a web based module and you wouldn't need any external software on your PC to translate NVDA. The problem is, most of these kind of translation systems are paid solutions, none of them is completely free.

hi You can see
[weblate](https://github.com/WeblateOrg/weblate)

**Comment by Adriani90** [comment] 2024-11-24 23:04
This is now solved, and the translation is migrated to Crowdin and can be performed via po files.
As far as I know only the symbols.dic file is still not po but this is not really needed.
Closing as works for me.

**Closed by Adriani90** 2024-11-24 23:04 UTC
Labels: close/worksforme
