### ISSUE TITLE
SQL Server Management Studio 2014: Incorrect Announcement of selected item in Object Explorer

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5517] opened 2015-11-19 20:05 UTC
Whilst navigating within the Object Explorer in SSMS, during 9 out of 10 cursor moves NVDA will output the incorrect object that currently has focus. When using Object Navigation to examine the current object that has focus, NVDA seems to think that the object is invisible, despite it saying seconds earlier that it was the object that the cursor moved over. This issue currently means that when attempting to carry out an operation on an object, it's necessary to invoke the Properties dialog to get a proper idea of which object has focus which is time consuming when a database contains many different tables.

I realise that SSMS is probably not going to be the most widely used pieces of software; would an NVDA + F1 help in this situation?

**Comment by albzan** [comment] 2015-12-19 08:09
Hello, I solved in Windows 8.1 relying on UI Automation to identify the name and states of selected item with a small appModule attached. Unfortunately it doesn't work with Windows 10.
Is there something changed in UI Automation implementation on this system? It seems to fail retrieving the correct focused element because it reads an element without STATE_FOCUSED.

I add another info about this. Probably it's not a problem related to an internal cache of NVDA because if you reload NVDA it doesn't restart reading correctly but it still continue to report the wrong selected element. You have to definitely restart Management Studio.

Finally anyone can test this using the SQL Server Express and deploying a test database like AdvetureWorks. With the Express distribution you can install SQL Server Management Studio Express which has the same problem. The problem afflicts SQL Server Management Studio 2012 and 2016 preview.

Other screen readers like JFW and Window-Eyes works well with this type of control

Thanks

Alberto

[ssms.zip](https://github.com/nvaccess/nvda/files/67414/ssms.zip)

**Comment by albzan** [comment] 2015-12-19 16:55
This solved for me... however if someone have suggestion on how to better code it, please feel free to send it back!

Thank you

Alberto
[ssms.zip](https://github.com/nvaccess/nvda/files/67530/ssms.zip)

**Comment by jcsteh** [comment] 2015-12-20 02:32
Happy to try to look into this at some point--it really should work if it's just a SysTreeView32--but given limited time, exact steps to get what we need set up download links, options, etc.) and then reproduce the issue (including creation steps, etc.) would save a lot of time. Otherwise, we have to learn how to use the thing instead of testing the actual problem. Thanks.

**Comment by albzan** [comment] 2015-12-20 09:28
It is a sysTreeView32 with some troubles. Also using the appModule above, the number of accChild continues to increase, it doesn't clean up the list. 
To clean up the list of children you have to close and restart the program. Restarting only NVDA doesn't make any change.
The interesting thing is that nether JAWS nor WE seems to have this problem, maybe they rely on other events to get the current focused element.

To replicate you have to:
1. Download and install SQL Server Express. During the installation you have to choose as a component Management software from the list of software to be installed
2. Open SQL Server Management Studio (ssms) and connect to your local machine. If you have set it (default) you can log in with your Windows credential and so you do not have to specify any username or password
3. You are in the Object Explorer now. Open the tree view and the first item is "Databases"
4. Open the context menu and select Attach...
5. Attach any database file like the classic AdventureWorks -  https://msftdbprodsamples.codeplex.com/downloads/get/165399
6. Explore the tree view a bit, open tables, views and then come back to the previous level.
You will quickly note that NVDA forget the position completely.

I think the most time consuming activity is the SQL Server Express setup. If you need more help contact me. If you know, however, a way to force an app to clean up its IAccessible tree, please reply to this.

Thanks for all

Alberto

**Comment by jcsteh** [comment] 2015-12-20 10:01
Because tree views don't have flat children, child ids aren't a simple 
counter. I think it's pretty normal for the child ids to keep increasing.

Unless you've checked and can confirm otherwise, it's entirely possible 
that JAWS/W-E have scripts to work around this.

To be honest, I still don't really understand the problem as reported. 
You mention that NVDA "forgets" the position, but it's unclear to me as 
to what it actually reports. Once the problem starts occurring, does it 
report the correct item and than an incorrect item or is it just always 
incorrect?

**Comment by albzan** [comment] 2015-12-20 10:30
Hi,

It's easy let's take an example
You have the following list

base : level 0
Databases : level 1
Management : level 1
Security : level 1

Under Databases you have :
AdventureWorks : level 2
Under AdventureWorks you have
Tables : level 3
Views : level 3
Programmability : level 3
Under Tables you have
Table1 : level 4
Table2 : level 4
Table3 : level 4

Now you want to go to table3 so you procede:
base  : level 0 : press right arrow down arrow
Databases  : level 1 : press right arrow down arrow
adventureworks : level 2 :  press right arrow down arrow
tables : level 2 : press right arrow down arrow
table1 : level 3 : press down arrow
table2 : level 3 : press down arrow
table3 : level 3 : press down arrow

Ok we are here, and NVDA annouce table3 (it doesn't break the first time for few elements)
Now you want to go back to the "tables" node and you press left arrow or backspace
NVDA will annouce
Management
or Security
and then still if you restart NVDA it continues announcing inconsistent nodes name.
Is it more clear now?

Alberto

**Comment by jcsteh** [comment] 2015-12-20 10:33
That's bizarre. That would suggest the control is firing completely 
incorrect MSAA events. Two questions:

1. Can you please provide devInfo (NVDA+f1) for one of these items?
2. Does Narrator exhibit this issue?

**Comment by albzan** [comment] 2015-12-20 10:44
1. yes, I selected one database (level2) named "ERP_BRIDGE" under Databases and NVDA after few databases (nodes at level 2 under "Databases" level 1) started announcing wrong nodes. In this case it announce "Management" which is another node at level 1 (sibling of "Databases").
Here is the devInfos:
Developer info for navigator object:
name: u'Management'
role: ROLE_TREEVIEWITEM
states: STATE_COLLAPSED, STATE_INVISIBLE, STATE_OFFSCREEN, STATE_SELECTABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.Dynamic_TreeViewItemOutlineItemIAccessible object at 0x0534F850>
Python class mro: (<class 'NVDAObjects.Dynamic_TreeViewItemOutlineItemIAccessible'>, <class 'NVDAObjects.IAccessible.sysTreeView32.TreeViewItem'>, <class 'NVDAObjects.IAccessible.OutlineItem'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'NTDB2/Management'
location: (68, 1545, 75, 18)
value: None
appModule: <'appModuleHandler' (appName u'ssms', process ID 3476) at address 51fba30>
appModule.productName: u'Microsoft SQL Server'
appModule.productVersion: u'13.0.900.73'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 67044
windowClassName: u'WindowsForms10.SysTreeView32.app.0.34f5582_r50_ad1'
windowControlID: 67044
windowStyle: 1445988397
windowThreadID: 6380
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x680750 at 5165ee0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=67044, objectID=-4, childID=81
IAccessible accName: u'Management'
IAccessible accRole: ROLE_SYSTEM_OUTLINEITEM
IAccessible accState: STATE_SYSTEM_SELECTABLE, STATE_SYSTEM_OFFSCREEN, STATE_SYSTEM_INVISIBLE, STATE_SYSTEM_COLLAPSED, STATE_SYSTEM_VALID (2196480)
IAccessible accDescription: u'NTDB2/Management'
IAccessible accValue: u'1'

I determine that it is wrong because it has not STATE_SELECTED (0x4) in MSAA. When NVDA announce correctly elements has STATE_SELECTED in states. Also the current focused child has a 0x2 in accStates (if you look to my script I search until I've found a & 2 accState).

2. Also with Narrator you have the same problem.

One note: In Windows 8.1 and earlier relying on UIA worked fine (something like BrokenBrokenMsoCommandBar. You can see this approach in my first message here in GitHub.
With windows 10 this stopped working for me.

Thanks

Alberto

**Comment by jcsteh** [comment] 2015-12-20 11:28
Can you please try refusing focus events for unfocused items? Something like this should do it (untested):

```
	def event_NVDAObject_init(self, obj):
		if obj.role == controlTypes.ROLE_TREEVIEWITEM and not obj.hasFocus:
			obj.shouldAllowIAccessibleFocusEvent = False
```

**Comment by albzan** [comment] 2015-12-20 11:37
Hi,

Yes I already tried it. The result is that NVDA does not speak anything
The correct node doesn't throw any event.
If I force the focus with the method you have show me in a previous message ssms crashes.

Alberto

**Comment by jcsteh** [comment] 2015-12-20 11:43
Here's a ridiculous thought.

1. Get focus onto one of those broken items.
2. Open the Python console.
3. Paste the following and press enter:

 `nav.IAccessibleObject.accParent.accName(nav.event_childID)`

Is the name the correct name for the focus or incorrect?

**Comment by albzan** [comment] 2015-12-20 11:46
incorrect

**Comment by albzan** [comment] 2015-12-20 11:51
Is it possible to intercept the raw event call in some way?
Thanks

**Comment by jcsteh** [comment] 2015-12-20 11:53
It is, but it'd require modifying the source. You're probably better off 
using a tool like AccProbe or AccEvent. That way, you can factor NVDA 
out altogether and just deal with MSAA directly.

Given how messed up this is, I'm honestly thinking other screen readers 
just have scripts to work around it.

**Comment by albzan** [comment] 2015-12-20 12:03
Thanks for all!
JAWS doesn't have any specific script for ssms, I'm pretty sure about this. Probably they use different strategies for sysTreeView32 that aren't affected to this behavior.

**Comment by albzan** [comment] 2015-12-20 15:03
I opened a ticket in Microsoft connect.
https://connect.microsoft.com/SQLServer/feedback/details/2150142

**Comment by Adriani90** [comment] 2018-12-10 13:57
@albzan are there any further updates regarding this issue?

**Comment by albzan** [comment] 2018-12-10 17:12
@Adriani90 No news, the accessibility of the app degradated more in version 2017 because of the use of a broken WpfTextEditor. I developed an appModule to fix this also in Visual Studio.
In this appModule I've added also the workaround already mentioned. If the tree is not too large, it works great. When it slows down, you've to refresh the subtree of the treeview where you want to navigate into.
Github Project (fork of another addon):
https://github.com/albzan/visualStudioAddon

**Comment by robinettl** [comment] 2018-12-17 23:44
So a good 3 years since this issue has been opened and no solution yet?  As someone who donates as much and as often as possible to NVDA, I expect these types of issues to be addressed a reasonable amount of time.  If we know that other screen readers like JAWS and WindowEyes can successfully navigate the SSMS object browser tree, there's no excuse for NVDA not being able to do the same -- especially after it's been a known issue this long.  I work in an Information Technology role where I must use SSMS on a daily basis.  My productivity is terribly impacted because of this issue.  Being able to navigate the object browser is what I would consider bare-minimum core functionality, yet here we are, with it still broekn.  I am unfortunately not developer, just a longtime user, but this is the only place we can apparently place support requests/bug reports, so I'm adding onto this thread in the hopes the NVDA developers will take this issue more seriously and implement a solution.  I am frankly floored that no such fix is in place yet.  Also, please do not blame Microsoft because then we get into that endless back-and-forth about whose fault it is rather than just focusing on getting it resolved for your users who rely on this.

**Comment by Adriani90** [comment] 2019-02-06 17:01
cc: @qchristensen, @feerrenrut

**Comment by Qchristensen** [comment] 2019-07-30 02:40
Has anyone looked into this issue lately?  It is still being reported and appears to be quite frustrating for those who need to use this.

Also is anyone able to please confirm whether this only affects SQL SMS 2014 (as per the issue title) or whether it is still present in later versions?  According to: https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017 the most recent version is:
Release number: 18.2
Build number: 15.0.18142.0
Release date: July 25, 2019

**Comment by Qchristensen** [comment] 2019-07-30 03:07
Update from user:
Issue tested in SSMS 2012, 2014 and 2017 (not sure which build), and this issue is also exhibited with Narrator (but not Jaws).

**Comment by leonardder** [comment] 2019-10-18 12:37
I can not reproduce this in SSMS 18 (15.0.18178.0), whatever year is associated to that version number, I assume 2018?

**Comment by Luke-Robinett** [comment] 2020-01-24 23:33
I'm thrilled to discover that it looks like this issue is finally resolved as of SSMS 18! I tried multiple times to trigger the bug but couldn't. NVDA seems to be traversing the object browser as expected now. Fantastic!

**Comment by ehollig** [comment] 2020-01-26 03:09
Closing as worksforme based on comment above.

**Closed by ehollig** 2020-01-26 03:09 UTC
Labels: App specific
