### ISSUE TITLE
<time> Element makes NVDA create a new line, how can I make it inline?

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#7073] opened 2017-04-13 14:33 UTC
I want to announce a time element within a heading.

When using a `<time>` tag, NVDA makes a new line after the time, resulting in something like this:

> 12th of april, heading level x
> Title content, heading level x

I tried to force the `display` property to `inline`, but it didn't change the behaviour.

When using a `<span>` instead of `<time>`, it's announced as expected:

> 12th of april, Title content, heading level x

Look at the following codepen which demonstrates both cases:

http://codepen.io/jmuheim/pen/KmKOZO

Why does this happen? Does it have to do with the `position: absolute` property of the `.sr-only` class?

**Comment by jcsteh** [comment] 2017-04-14 04:16
What browsers/versions did you test this with? Thanks.

**Comment by jmuheim** [comment] 2017-04-14 10:48
Firefox newest version. NVDA newest version.

**Comment by jage9** [comment] 2017-04-23 23:09
On this [page,](https://www.blindbargains.com/b/17083) it displays inline when use screen layout is selected and as a separate line when it is not. Some might argue that the element is deserving of its own line when screen layout is disabled, but I could go either way on this one. How is NVDA handling other similar elements which do not break up the flow of a web page and are meant more for tagging? I would suggest that NVDA should just ignore this element and display inline since it has no baring on the page itself and is not visually distinct.

**Comment by Adriani90** [comment] 2019-04-12 23:02
this is still reproducible in NVDA 2019.1 and firefox 66.0.3.

**Comment by Adriani90** [comment] 2019-04-12 23:04
Note that in Chrome both implementations display the time and the activity each on a separate line. But when pressin h in browse mode to navigate heading by heading, both lines 8time and activity) are reported together.

**Comment by jcsteh** [comment] 2019-04-15 07:05
> Why does this happen? Does it have to do with the `position: absolute` property of the `.sr-only` class?

Yes. That element gets an effective style of display: block when you do this. (You can see this if you query `window.getComputedStyle(timeElement).display`.) There isn't really a good way to get around this.

Interestingly, setting role="presentation" on the time element will probably fix this because it will hide the semantics of the time element (including its display type). That probably somewhat defeats the point of using the time element, though.

**Comment by jcsteh** [comment] 2019-04-15 07:05
Closing as cantfix.

**Closed by jcsteh** 2019-04-15 07:05 UTC
