### ISSUE TITLE
System focus does not move to edit field when "Automatic focus mode for caret movement" is enabled.

### ISSUE THREAD

**Issue by artindk** [nvaccess/nvda#11663] opened 2020-09-24 22:07 UTC
### Steps to reproduce:
1: Enable the option "Automatic focus mode for caret movement" in the browse mode settings of NVDA.
2: Go to a website with edit fields.
3: Use the arrow keys to go to an edit field.

### Actual behavior:
Focus mode is turned on, but system focus is not moved to the edit field. Because of this it is not possible to type in the edit field. To be able to type text anyway, you must switch to browse mode and then press enter or space. Then focus mode is turned on again and the system focus is moved to the edit field.

### Expected behavior:
When you get to an edit field with the arrow keys, NVDA switches to focus mode and the system focus moves to the edit field.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.3beta3
#### Windows version:
Windows 10 1909 (64-bit) build 18363.1082
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 85.0.564.51 and Firefox 80.0.1
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
In previous versions of NVDA this works as expected, the problem is caused by changes in NVDA2020.3.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by artindk** [comment] 2020-09-25 07:00
I have similar problems with combo boxes.

**Comment by lukaszgo1** [comment] 2020-09-25 09:33
This is a duplicate of #11654 @feerrenrut @michaelDCurran Are you planning to fix this for 2020.3? If not I'm afraid we should reconsider making focus focusable elements disabled by default as experience with it disabled and "Automatic focus mode for caret movements" enabled is sub optimal to put it politely. Also cc @jcsteh and @leonardder  who have worked on focus focusable elements in the past.

**Comment by fisher729** [comment] 2020-09-25 09:59
Hi.

I can confirm this issue. One would argue that this is a specific use case, and that, rather than disabling it by default altogether, this bug should be looked into further, as it is present when it's enabled.

**Comment by Brian1Gaff** [comment] 2020-09-25 10:15
Yes, I've been having odd things happening on web sites since using the new 
beta 3 as well, but not actually managed to figure out a one thing that 
creates the issue, its as if you need to visit some parts twice to make them 
work right.
 Sorry cannot be more specific.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by leonardder** [comment] 2020-09-25 10:42
Is there a step sequence that is always reproducible and that isn't 
hidden behind a login?

**Comment by lukaszgo1** [comment] 2020-09-25 11:01
You can use page of this issue as an example:
1. In the browse mode  settings ensure that "Automatic focus mode for caret movement" is enabled and "Automatically set system focus to focusable elements" is  disabled.
2. Move to the comment edit field with letter e.
3. move with arrows to the field until focus mode activates automatically.
4. Try to type into the field.

**Comment by leonardder** [comment] 2020-09-25 17:26
Yes, I can reproduce this now. Investigating the cause.

**Comment by lukaszgo1** [comment] 2020-09-25 17:44
@fisher729 @artindk Could you please confirm that this issue is no longer reproducible with [this build](https://ci.appveyor.com/api/buildjobs/33iveog3w1298s22/artifacts/output%2Fnvda_snapshot_pr11665-21047%2C854b0137.exe)?

**Comment by artindk** [comment] 2020-09-25 19:04
I have tested several website with the build and it now seems to work as expected.

**Comment by VovaMobile** [comment] 2020-09-26 07:50
Thanks, with latest snapshot sites works correctly. I was pleased to be involved in improving the future version of NVDA.

**Closed** 2020-09-30 07:53 UTC
