### ISSUE TITLE
Focus is locked after selecting dropdown menu item in Excel

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13850] opened 2022-06-28 04:35 UTC
[test.xlsx](https://github.com/nvaccess/nvda/files/8997726/test.xlsx)

### Steps to reproduce:
1. Download the provided excel file(test.xlsx);
2. Press Alt+Down Arrow in cell A2, then select any item from the drop-down menu and press Enter.
### Actual behavior:
Focus is locked, pressing the four arrows NVDA is silent.
The following information can be seen in the log viewer:
```
Developer info for navigator object:
name: ''
role: Role.LISTITEM
roleText: None
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.UIA.ListItem object at 0x00D0B8B0>
Python class mro: (<class 'NVDAObjects.UIA.ListItem'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=0, top=0, width=0, height=0)
value: None
```
### Expected behavior:
The focus should not be locked, use the four arrows to move between cells.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2022.1,2022.2,2022.3Alpha
#### Windows version:
Windows 10 21H2 (x64) build 19044.1766
#### Name and version of other software in use when reproducing the issue:
MSO (Version 2205 Build 16.0.15225.20278) 64-bit
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
None
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2023-04-05 13:43
Closing as duplicate of #10401.

**Closed by Adriani90** 2023-04-05 13:43 UTC
Labels: close/duplicate, app/microsoft-office, p2, triaged
