### ISSUE TITLE
Speaking long string freezes NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4669] opened 2014-12-05 06:32 UTC
**Reported by tspivey on 2014-12-05 06:32**
Problem:
Long strings will freeze NVDA when spoken.

Normally this wouldn't occur, but sometimes when editing files (in scintilla-based editors with word wrap disabled),
they come up.

STR:

```
s1 = 'test '*5000
s2 = 'a'*5000
ui.message(s)
```

More details:

```
t1 = time.time();tmp = characterProcessing.processSpeechSymbols("en", s1, 300);print time.time() - t1
s1: 0.043S, rounded
s2: 0.005S, rounded
processText eventually processes the dictionary, this can be slow on such large strings.
t1 = time.time();tmp = speechDictHandler.processText(s1);print time.time() - t1
s1: 0.015S
s2: 2.0S
With a real speech dictionary of 14 entries (11 default + 3 voice), s1 takes ~11.4S and s2 takes 2.4.
s2 doesn't increase much. Maybe one of my regexes is slow.
```

I admit, s2 is a corner case, and I'm probably not going to encounter it outside of testing.
S1 is pretty long, 25k. I've accidentally hit longer, though. HTML files with no newlines.
When NVDA freezes, it's difficult to get it back up again.

Possible solutions:
1. Beep or otherwise speak a message for long lines and ignore them.
   I don't like this one, because we have to define long line. Ignoring s2, 10k? That's nothing if I don't have a speech dictionary and just use builtin, and depends on its size.
   I'm not even yet considering how long it takes the synth to start speaking.
2. Split long lines into chunks.
   Slightly better, if we can figure out what'll tipically work for not freezing things for too long, and what a long line is. We still have to define that
   If done right, the line should speak quickly, albeit with a few extra pauses and possibly broken speech dictionary regexes. I don't think I'd bother listening to the entire thing;
   tipically I'd realize "long line", and turn on word wrap to go through it properly.

**Comment by josephsl** [comment] 2016-10-10 21:21
Hi,

This was brought up last night when someone sent a long string over Remote Support session that resulted in clients crashing.

Thanks.

**Comment by Adriani90** [comment] 2019-01-04 23:04
@tspivey, @camlorn can you still reproduce this issue?
@josephsl did you hear any new reports from users? I didn't ever see this issue.

**Comment by Adriani90** [comment] 2019-01-20 00:35
@sonor3000, @novalis7747 did you encounter this issue on VM maybe? Or could you test if you can reproduce it? Maybe also trying NVDA remote. Thank you very much!

**Comment by Adriani90** [comment] 2019-05-05 18:06
We do not have updated from almost three years on this issue. I am closing it for now. If you have time to test if this is still reproducible, please comment on it and we can reopen the discussion. Thanks!.

**Comment by tspivey** [comment] 2019-05-05 21:20
[Here is a test case](https://jsbin.com/fogocej/edit?html,output). Wait 10 seconds or so and be prepared for your machine to become unusable. Tested with OneCore, Firefox and Chrome.

**Comment by Adriani90** [comment] 2019-05-05 22:00
Reopening.

@feerrenrut would a p2 be reasonable for this?

**Comment by feerrenrut** [comment] 2019-05-06 11:25
Yes, I have added the p2 label.

**Comment by akalaiva** [comment] 2020-04-02 16:45
I notice this same issue with a long string of text or large content inserted into a div.

**Comment by VantageKR** [comment] 2020-04-16 09:46
Have been experiencing NVDA simply not reading long lines anymore, when using gvim via a plugin that interfaces with gvim via OLE automation. This worked perfectly before this most recent version of NVDA. Have also experienced NVDA hanging when say the Windows console outputs a lot of text - this did not happen before. Unfortunately, reverting to an older NVDA does not solve this problem, but I'm unable to determine why this is the case. Another issue with the latest NVDA is that the error tree in the DBeaver database IDE, which is based on Eclipse, does not voice anymore. So, really unsure why things have gotten so terrible. I've tried disabling all add ons, tried different synts: problems persist.

**Comment by thgcode** [comment] 2022-03-05 18:04
`I'm having this same issue on NVDA 2021.3.3, I created some artificial test cases to reproduce but it occurs on real programs:
1. Open NVDA Python Console.

2. Paste this code and be prepared for the crash:

`import speech;speech.speak("a" * 128 * 1024)`

3. However, if you try speaking the string directly on the synthesizer (eSpeak in my case), it works:
`import synthDriverHandler;import time;synth = synthDriverHandler.getSynth();synth.speak("a" * 128 * 1024);time.sleep(2)`

**Comment by thgcode** [comment] 2022-03-05 21:21
As a follow up, I think I found one of the problems. If you try to give the text to the speechDictHandler.processText function, it is taking a lot of time to complete. If this function is disabled (replacing it with a lambda for example), NVDA still lags, but returns in seconds.

**Comment by thgcode** [comment] 2022-03-05 22:51
It seems there is  a particular regexp on the builtin.dic NVDA dictionary file is causing the problem. I'm not sure of which one but I tested removing the file from my installation and it spoke the long string.

**Comment by Neurrone** [comment] 2022-03-06 04:10
Hi, I've just stumbled across this as well in #13432.

I'd like to request a prioritization of this issue, because of how it is much more severe than a normal crash. I had to restart the entire computer to get speech back. Its also something that an end user can't really do anything about e.g, the only way you know the file has the potential to crash NVDA is by looking at it first, which then causes said crash.

**Comment by Adriani90** [comment] 2022-03-06 12:33
cc: @michaelDCurran

**Comment by feerrenrut** [comment] 2022-03-11 05:50
I'm going to close this and re-open #13432, since that is newer, uses the issue template and based on a real world use case, rather than python console input. Reviewing the comments here I note https://github.com/nvaccess/nvda/issues/4669#issuecomment-489464407 which seems to have been overlooked.

**Closed by feerrenrut** 2022-03-11 05:50 UTC
Labels: bug, component/speech, p2
