### ISSUE TITLE
NVDA doesn't announce typed characters in Win10 powershell

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6575] opened 2016-11-19 05:47 UTC
This happens even if the announce typed characters setting is on.

**Comment by josephsl** [comment] 2016-11-19 05:49
Hi, how about for earlier versions such as Windows 8.x? Thanks.

**Comment by Neurrone** [comment] 2016-11-19 06:27
Am not able to test that right now, anyone has an earlier version of windows?

**Comment by Adriani90** [comment] 2019-03-18 22:00
@bdorer, @novalis7747 could you please test in an older Windows version if this is  also reproducible?
In Windows 10, NVDA announces just "space space space" for every character I type. cc: @leonardder

**Comment by bdorer** [comment] 2019-03-18 22:44
hmm, I'm able to test this arround 2019-04-20. At the moment I have only 
access to Windows 10.

Am 18.03.2019 um 23:00 schrieb Adriani90:

**Comment by Novalis7747** [comment] 2019-03-19 06:42
it dowsn’t work in different versions of Win10, but it works in Win7SP1. Can’t test it with Win8 or Win8.1….

**Comment by lukaszgo1** [comment] 2019-03-19 07:04
Will test on Win 8 and 8.1 in a few days

**Comment by bdorer** [comment] 2019-10-08 21:12
With latest NVDA-alpha NVDA reads the first char I type and then speaks 
space space and so on.
I do not have an older windows at hand.

Am 18.03.2019 um 23:00 schrieb Adriani90:

**Comment by Adriani90** [comment] 2020-12-08 21:46
Is this somehow similar to #9102? If yes, then I would close this one in favor of #9102 because the description is more detailed there.
cc: @codeofdusk

**Comment by bdorer** [comment] 2021-05-08 09:11
@codeofdusk if I remember correctly you worked on powershell support, right? If so, may you could look in to this?

**Comment by codeofdusk** [comment] 2021-05-08 13:52
Yes, I have worked recently on console support.

I can't reproduce this, could you please try a few things?
* In advanced settings, what is the state of "use the new typed character support in legacy Windows consoles"? If it's on, does disabling it change behaviour?
* In advanced settings, what is the state of "use UI Automation to access Windows Console when available"? If it's off, does enabling it change behaviour?

**Comment by Adriani90** [comment] 2024-12-13 18:02
This seems fixed now, testing with NVDA 2024.4.1. Closing as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-12-13 18:02 UTC
Labels: close/worksforme, component/speech
