### ISSUE TITLE
NVDA+TAB reports incorrect information in browse mode

### ISSUE THREAD

**Issue by geoffshang** [nvaccess/nvda#13766] opened 2022-06-03 12:28 UTC
### Steps to reproduce:

1.  Go to http://thespicerack.org/nvda_test.html and enter browse mode if necessary.
2. Explore the document.  You will notice that this is a document with 5 links numbered 1 through 5 (for simplicity).
3. Arrow to link 2.
4. Press NVDA+TAB.  NVDA says "nvda_test document focused read-only".
5. Press TAB.  NVDA says "3 link"
6. Press NVDA+TAB.  NVDA says "3 link focus linked".
7. Arrow to link 4.  NVDA says "link 4".
8. Press NVDA+TABB. NVDA says "3 link focused linked"

### Actual behavior:

NVDA only reports the correct focus with NVDA+TAB in browse mode when the focus has been moved by the TAB key.  If you arrow to an element, NVDA+TAB in browse mode still reports the previously tabbed-to item, even though tabbing will move to the next actual element instead of the one after the one reported.

### Expected behavior:

NVDA+TAB should report the currently focused element.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2022.1 (also seen with recent 2021 version/s)

#### Windows version:

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎01/‎03/‎2022
OS build	19044.1706
Serial number	PF3DJ787
Experience	Windows Feature Experience Pack 120.2212.4170.0

#### Name and version of other software in use when reproducing the issue:

Mozilla Firefox version 101.0 (64-bit) (and at  least two previous versions)
Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)
Microsoft EdgeVersion 102.0.1245.30 (Official build) (64-bit)

#### Other information about your system:

This PC was installed fresh on 1 March.  I noticed it pretty quickly after receiving it.  I don't recall noticing it previously but can't say for sure that it wasn't happening on my previous PC.  I have another laptop but I've not tested on that one (I can do that if wanted).

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Late 2021.x versions (end of March and onward) did the same thing.

#### If NVDA add-ons are disabled, is your problem still occurring?

No add-ons are installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

I've not tried it but I don't expect it to make a difference.

**Comment by CyrilleB79** [comment] 2022-06-03 15:41
Actually, it's not a bug, it's a feature.

Pressing NVDA+Tab report the focused object.
Until recently, the focus was automatically following the navigation in browse mode.
In newer versions of NVDA however, the focus does not follow when navigating in browse mode.

If you want to have the previous experience, i.e. have the focus follow the browse mode cursor when it reaches focusable elements, you should enable the option "Automatically set system focus to focusable elements" in Browse mode settings.
You can also use the shortcut NVDA+8 to toggle this option more quickly.
Hope this helps.

If this answer is a solution to your issue, please close this ticket. If not, please be more specific.
Thanks.

**Comment by seanbudd** [comment] 2022-06-09 06:00
Thanks @CyrilleB79 - closing as unplanned

**Closed by seanbudd** 2022-06-09 06:00 UTC
