### ISSUE TITLE
[NVDA + firefox] : On new element on page, or focus switch NVDA repeats the windows title

### ISSUE THREAD

**Issue by mdahamiwal** [nvaccess/nvda#7185] opened 2017-05-18 05:53 UTC
### Steps to reproduce:
 1. Open Firefox
 2. Browse to https://dev.office.com/fabric#/components/callout
 3. Navigate to "show callout" button in right pane.
 4. Press the button - this opens a callout dialog and moves focus to "Go to Microsoft" link inside the dialog but NVDA announces windows title and document name in between. check following speech reader output:

### Speech reader output:
Show callout
button
Office UI Fabric - Mozilla Firefox
unknown
Office UI Fabric - Mozilla Firefox
Office UI Fabric  document
clickable
button
Hide callout
Go to microsoft
link

The behavior is correct with Edge + Narrator, Firefox + Narrator.

### Expected behavior:
NVDA should only announce the new dialog in the page and not the window title. It creates a lot of noise.

### Actual behavior:
NVDA announces window's title after every dialog open and sometimes on focus changes as well.

### System configuration:
NVDA version: 2017.1

NVDA Installed or portable: Installed

Other information:
Physical machine Windows 10 Version 1607 Build 15063.296

Name and version of other software in use when reproducing the issue:
Firefox version: 53.0.2 (32-bit)

### Other questions:

Have you tried any other versions of NVDA?
> Yes, it reproduces even with 2016 version

**Comment by jcsteh** [comment] 2017-05-18 05:55
Please provide the speech viewer output as text, rather than a screen shot,
as many of the developers (including myself) are totally blind. Thanks.

**Comment by mdahamiwal** [comment] 2017-05-18 06:01
@jcsteh, sorry for I was not aware of that, I have updated the description with speech viewer text, Thanks

**Comment by FelixGruetzmacher** [comment] 2017-06-02 12:13
The same also often happens on Google Inbox, but mostly while in a subgroup, rarely at top-level.

**Comment by jcsteh** [comment] 2017-06-05 04:08
I assume you're referring to the first "Simple callout" variant?

I can't reproduce this (with any of them). Here's log output from me moving to the button using first letter navigation and then pressing enter:

> ```
> IO - inputCore.InputManager.executeGesture (14:04:11.845):
> Input: kb(desktop):b
> IO - speech.speak (14:04:11.875):
> Speaking [u'Show callout', u'button']
> IO - inputCore.InputManager.executeGesture (14:04:12.351):
> Input: kb(desktop):enter
> IO - speech.speak (14:04:12.655):
> Speaking [u'Go to microsoft', u'link']
> ```

Perhaps this is fixed in a later Firefox version. I'm testing with Firefox Nightly 55.0a1 (2017-05-22) (64-bit).

The key here is the "unknown" that you're seeing in the middle. I don't see this, but that means something got focus which quickly disappeared before the final thing got focus. That could either be because the page moved the focus twice or because some CSS caused the focused node to be regenerated for accessibility purposes.

**Comment by ehollig** [comment] 2018-04-18 20:51
I am not able to reproduce this issue using Firefox 58. I opened the above link and activated the "show callout" button and did not experience the speech output that @mdahamiwal describes. Closing, but If this is still an issue, we can reopen.

**Closed by ehollig** 2018-04-18 20:51 UTC
