### ISSUE TITLE
advanced sleep mode for applications

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5353] opened 2015-09-11 20:56 UTC
**Reported by JamaicanUser on 2015-09-11 20:56**
Hello.
This is just a suggestion. What if the sleep mode functionality could be more advanced to deal with self-voicing applications. Something like this could work.
1. Pressing the toggle sleep mode once toggles the mode on or off (currently the case).
2. Pressing the keystroke thrice quickly toggles the application's sleep mode permanently. This means that when NVDA is closed and restarted. To turn sleep mode on permanently while it is off for the application, press the keystroke once. This will however not affect the global setting. To toggle permanent sleep mode, press the keystroke thrice quickly again.
Just a suggestion, but I hope it does not fall flat.

**Comment by bhavyashah** [comment] 2017-08-19 11:48
To summarize:
* The proposed feature request is to enable and disable a permanent application specific sleep mode when NVDA+Shift+Z (keystroke to toggle sleep mode on and off for the active application, at least in the laptop keyboard layout) is pressed twice.
* This would be extremely useful in self-voicing applications, and would help us address certain other tickets as well which request automatic disabling of NVDA while in Kurzweil (a self-voicing OCR program).
* However, a hurdle in the implementation of such a functionality, as noted by @brian1gaff's https://github.com/nvaccess/nvda/issues/5353#issuecomment-155343255, is that certain software, e.g. Dolphin Guide, contain more than one executable which would result in all of them being treated as separate apps by NVDA.

**Comment by Brian1Gaff** [comment] 2017-08-19 16:41
Yes this is what happens of course with the old global app module we used to 
use, ie you needed one for each executable, also of course any delay between 
tends to make nvda mutter things randomly, depending on the timings of 
events in the next exe file being loaded or the previous 1 stopped.


In the main  there are ways around some of these things now, but some 
programs work better than others do.
 I try not to use self voicing programs myself, as strange effects can 
occur. I have to use Newsbridge, written by the same team as original Guide, 
and the inbuilt voice is SAppi5 and on dialogues like open its extremely 
laggy compared to nvda!


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment] 2017-08-19 20:36
Could something like this be achieved with configuration profiles?

1. Open the program that is self voicing.
2. Press NVDA+N, C, Alt+N
3. Give the configuration profile a name
4. Press tab, and down arrow to current application.
5. Press Enter
6. Press NVDA+Shift+Z to turn sleep mode on.

Now, whenever the application is switched to, NVDA will be in sleep mode. Testing using notepad as a program and it worked every time. @brian1Gaff, are there instances where this solution would not work? How often do programs have multiple executables where this would not work?

**Comment by ehollig** [comment] 2017-08-19 21:04
Actually, when looking at #3721, this is not possible quite yet.

**Comment by lukaszgo1** [comment] 2019-05-29 12:45
Isn't this one a duplicate of #3721?

**Comment by Adriani90** [comment] 2019-05-29 14:42
Yes this is a duplicate. Closing.
Thanks for picking this up.

**Closed** 2019-05-29 14:43 UTC
Labels: duplicate, enhancement
