### ISSUE TITLE
In a pdf alternative text of text tagged as "Formula" is not read.  

### ISSUE THREAD

**Issue by u-fischer** [nvaccess/nvda#8598] opened 2018-08-06 14:11 UTC
### Steps to reproduce:

Open the attached pdf in Adobe reader (or pro), start nvda and let read the text

### Actual behavior:

On both pages only the sentence "Ein Satz ohne Umlaute." is spoken. 

### Expected behavior:

At least on one of the pages the `/Alt` text of the formula (`Dies ist eine Formel`/`Dies ist eine zweite Formel`) should be spoken.

The in-built text-to-speech of adobe speeks both  `/Alt` texts (but only if there is also some text besides the formula on the page).

#### NVDA Installed/portable/running from source:

portable version

#### NVDA version:

2018.2.1

#### Windows version:

Windows 10

#### Name and version of other software in use when reproducing the issue:

Adobe Pro DC and Adobe Reader DC 2018.011.20055 and 

### Other questions:

The pdf is uncompressed and so can be inspected. preflight says that its syntax is correct. 

The `/Alt` text of the formula on the first page is in the page stream, in the properties of the BDC operator:

~~~~
/Formula<</MCID 1 /Alt <FEFF00440069006500730020006900730074002000650069006E006500200046006F0072006D0065006C>>> BDC
~~~~

The `/Alt` text of the second formula is in the `/StructElem` object:

~~~~
13 0 obj
<< /Type /StructElem /S /Formula /P 4 0 R /K <</Type /MCR /Pg 15 0 R /MCID 1>>  /Alt <FEFF00440069006500730020006900730074002000650069006E00650020007A0077006500690074006500200046006F0072006D0065006C>>>
endobj
~~~~

#### Have you tried any other versions of NVDA?

No. 

[ex-formula-problem.pdf](https://github.com/nvaccess/nvda/files/2262848/ex-formula-problem.pdf)

**Comment by AlexandrKozlovskiy** [comment] 2019-10-09 15:10
Hello everybody. Yes,problem with formula exists even in nvda 2019.2.1 in windows 10 64 bytes.

**Comment by siddharthalodha** [comment] 2020-06-22 16:11
This issue is still there in the latest version

**Comment by AlexandrKozlovskiy** [comment] 2020-08-05 00:48
Sorry for very late reply. Yes,this issue actual for nvda 2020.2,but in adobe reader for mac with voiceover i,and probably others,haven't this problem,so this is probably issue of nvda.

**Comment by PaulRayius** [comment] 2022-07-25 18:57
This is still an issue in 2022.2.

**Comment by PaulRayius** [comment] 2023-07-27 19:54
This is still an issue in Acrobat 2023.003.20244 - 64 bit.

**Comment by Adriani90** [comment] 2024-10-31 17:37
With NVDA2024.4 and Adobe Acrobat (64-bit) (24.004.20220) this issue is not reproducible anymore. I am closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-10-31 17:37 UTC
Labels: close/worksforme, app/adobe/acrobat
