### ISSUE TITLE
NVDA reads nothing in some multiline edit box

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#8691] opened 2018-08-29 10:31 UTC
From NVDA 2018.1 and probably previous, it seems an old problem, and still with alpha-15933. In some HTML pages, and (for example) with UBlock Origin personal filters box.

### Steps to reproduce:

* Go, for example, to this page:
https://edabit.com/challenge/3LpBLgNRyaHMvNb4j
* Search and press enter on tab "code";
* Search the multiline edit box that should contain the code, and activate it.

### Actual behavior:

Moving with arrows and other commands, NVDA reads nothing. The unique way to notice the content is to move at the top of editbox with control+home, then select all with control+shift+end; doing so, NVDA reads the selected text.
Obviously, writing something in this situation is very unconfortable.

#### Other information

I don't know if it's useful, but setting on debug (alpha-15933), log says:

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:10:34.473):
accRole failed: (-2147024809, 'Parametro non corretto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (12:10:34.474):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:10:34.523):
accRole failed: (-2147024809, 'Parametro non corretto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:10:34.526):
accRole failed: (-2147024809, 'Parametro non corretto.', (None, None, None, 0, None))
DEBUG - editableText.EditableText._hasCaretMoved (12:10:34.635):
Caret didn't move before timeout. Elapsed: 100 ms

**Comment by leonardder** [comment] 2018-08-29 10:43
What browser is this?

**Comment by ABuffEr** [comment] 2018-08-29 11:41
Ah, sorry. Log from Chrome. But in Firefox the behaviour (I don't know the log) is the same.

**Comment by jawhien** [comment] 2018-08-29 15:16
Hello.
I also noticed this problem. use the browser of SeaMonkey. Exactly the same or very similar behavior is observed in PhpMyAdmin, if you write SQL code.

**Comment by Brian1Gaff** [comment] 2018-08-29 19:05
Is there a less geeky site to show this. I noticed a javascript warning when 
i opened that page in waterfox, but really I'm out of my depth on that site.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ABuffEr** [comment] 2018-08-29 20:27
Thanks jawhien for your report. It is a browser independent problem at this time, I think...
Brian, if you are able to find another sites, well... do it. But JavaScript is everywhere (sometimes really indispensable), and a search of this type is already not easy, and probably not necessary.
In any case, the reported is not first site where I encountered the problem, but months passed, I don't remember other examples now.

**Comment by Brian1Gaff** [comment] 2018-08-30 08:42
I have seen some very sluggish edit fields though, the Alexa app  for the 
echo devices is pretty slow when I try to type in a message for feedback for 
example.
 I'm not using a clunker machine either.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Neurrone** [comment] 2018-08-30 15:32
@ABuffEr as I suspected, this is caused by the inaccessible CodeMirror library many sites use for code editing. This will be fixed in the [upcoming CodeMirror rewrite](https://codemirror.net/6/).

**Comment by ABuffEr** [comment] 2018-08-31 16:40
I looked at UBlock extension, and effectively it uses this library. So, we can only hope it'll be released soon...
Thanks @Neurrone for info.

**Comment by ABuffEr** [comment] 2018-11-29 12:53
I close the issue as unrelated to NVDA, waiting for new version of CodeMirror library with improved accessibility, as reported by @neurrone. Until that moment, obviously the problem still occurs, after release I consider if open this issue again.

**Closed** 2018-11-29 12:53 UTC
