### ISSUE TITLE
Highcharts Donut chart is read as pie chart

### ISSUE THREAD

**Issue by SwathiMicro** [nvaccess/nvda#8966] opened 2018-11-21 10:14 UTC
### Steps to reproduce:
Any donut chart in highcharts is given pie dimensions instead of donut.
Please find the below link an example from highcharts where the type is given as pie instead of donut.

Also we could not find much examples in highcharts demo for donut chart.

https://www.highcharts.com/demo/pie-donut
https://codepen.io/pen/?editors=1010.

Look in JS file. sample code:

Highcharts.chart('container', {
  chart: {
    type: 'pie'
  },

### Actual behavior:
Donut should be given the type as donut instead of pie.

### Expected behavior:
Donut chart should be read as donut when we use the same it may cause the chart to be read as pie instead of donut.

### System configuration:
Windows 10 OS 1806, 64 bit OS

#### NVDA Installed/portable/running from source:
NVDA installed

#### NVDA version:
2018.2.1

#### Windows version:
 Windows 10

#### Name and version of other software in use when reproducing the issue:
Chrome Browser

### Other questions:
Please provide us with more samples where we do not have inner circle and that exactly represents the donut.

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by DrSooom** [comment] 2018-11-21 12:08
@SwathiMicro: Please completely fill out the draft. Thanks.

**Comment by ehollig** [comment] 2018-11-21 18:36
@SwathiMicro please completely fill out the template. Also, do you have an example where this exists where we can take a look?

**Comment by SwathiMicro** [comment] 2018-11-22 05:55
Template have been filled, let us know if this is expected that pie and donut similar .

**Comment by Adriani90** [comment] 2024-05-28 17:42
The charts are read properly as donut charts in NVDA 2024.2 Beta, Firefox 126 or Chrome Canary 127 and Edge stable 125. I cannot reproduce this issue.
I am closing as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-05-28 17:42 UTC
Labels: close/worksforme
