### ISSUE TITLE
Announces aria-label twice on svg group element

### ISSUE THREAD

**Issue by amunguia** [nvaccess/nvda#8169] opened 2018-04-12 11:21 UTC
### Steps to reproduce:

1. Open the html file in the attached zip file in Firefox. The html page has an embedded svg document. 2. Tab through the elements on the page. 

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
When you land on the svg group element with the aria label "This is a cool rectangle", NVDA verbalizes this only once.

### Actual behavior:
 When you land on the svg group element, NVDA verbalizes this twice.

### System configuration:
I've seen this on desktop (mac and windows machines) using various Firefox versions from 56 - 59 and different NVDA versions.

**Comment by pkra** [comment] 2018-05-23 15:28
This also happens with arial-labelledby pointing to a title.

The duplicate voicing does not occur with IE11, Edge, Chrome (on a Windows 10 VM). On the other hand, e.g., JAWS and MS Narrator do not voice anything in Firefox which is clearly worse.

Sample: https://codepen.io/pkra/full/bMxPxN/ 

I also noticed that there's #4782 which was filed for IE specifically (no version specified) and claims Firefox does not have a problem (but that issue precedes Firefox Quantum).

**Comment by Adriani90** [comment] 2019-01-11 20:50
@pkra I cannot find your attachment. Could you please upload it to this issue? Thanks.

**Comment by pkra** [comment] 2019-01-12 19:13
@Adriani90 sure [here](https://codepen.io/pkra/share/zip/bMxPxN) but I think the issue has been fixed in the mean time.

**Comment by Adriani90** [comment] 2019-01-12 23:39
@pkra for some reason NVDA seems not to read it as well. If I tab around in focus mode I don't land on any svg group element. When arrowing in browse mode, NVDA reports a grafic at the end of the page but I don't think this is the svg because there is nothing with "this is a cool rectangle". The same behavior is in Chrome and IE.

**Comment by Adriani90** [comment] 2019-01-12 23:40
cc: @jcsteh

**Comment by pkra** [comment] 2019-01-13 15:53
@Adriani90 the svg's textual representation in my sample would be left-parenthesis upper G comma upper H right-parenthesis". (I'm not the OP so my sample is different.) As I wrote, it's fine now.

**Comment by Adriani90** [comment] 2019-01-13 16:13
@pkra thank you very much for the clarification. I can confirm it works properly. Closing as works for me.

**Closed by Adriani90** 2019-01-13 16:13 UTC
Labels: worksforme

**Comment by pkra** [comment] 2019-01-13 21:08
Thanks for cleaning up, @Adriani90.
