### ISSUE TITLE
browse mode in libreoffice

### ISSUE THREAD

**Issue by ilyaru91** [nvaccess/nvda#11356] opened 2020-07-08 13:53 UTC
Can you please add browse mode to libreoffice

**Comment by Brian1Gaff** [comment] 2020-07-08 15:13
I seem to recall this already exist somewhere along with associated issues 
like say all stopping etc. Do these all need an external fix by the folk 
writing libra office?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2020-07-08 21:34
Closing as duplicate of #5453.

**Closed by Adriani90** 2020-07-08 21:34 UTC
Labels: close/duplicate
