### ISSUE TITLE
NVDA changes the volume of the synth significantly while navigating

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15305] opened 2023-08-17 16:26 UTC
### Steps to reproduce:
1. Open NVDA
2. Chose any synthesizer
3. Via the synth settings ring, change the volume of the synth to 5 percent (it works also with 10 percent but the effect is clearer with 5 percent at least on my end.)
4. while using the laptop speakers, Navigate in a document, website or anywhere else with arrow keys or tab

### Actual behavior:
The volume of the synth is changing significantly while you navigate and NVDA is reporting stuff. It doesn't matter which synth is in use or whether WASAPI is enabled or not.

### Expected behavior:
The volume should stay at the same level.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-28861,705687b3 (2023.3.0.28861)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment] 2023-08-17 16:27
The user impact is that the reporting is often misunderstood since some parts are reported with lower volume while others are reported with a higher volume.

**Comment by ABuffEr** [comment] 2023-08-17 16:54
Many many thanks for reporting this!
It makes me crazy at least from two weeks, but I have particular hearing conditions and equipments, so I was not sure whether it's a NVDA issue.
I can add:
* Windows 10 22H2 (build SO 19045.3324);
* NVDA 2023.2beta2, alpha from 28850 (maybe previous too);
* it seems to happen more easily if you do something that produces a sound, like switching focus/navigation mode, launching a failing search on page, etc.

**Comment by tspivey** [comment] 2023-08-17 17:00
Try disabling enhancements on your sound card and see if you still have the problem.
This depends on your machine; some let you do it from the Enhancements tab of the playback device properties, others have a separate application.

A quick way to get to the sound control panel is to press Windows+r and run mmsys.cpl. Once there, find your playback device and press Properties, then find the Enhancements tab if there is one. Check the box that says Disable all enhancements.

**Comment by ABuffEr** [comment] 2023-08-17 17:13
> Try disabling enhancements on your sound card and see if you still have the problem.

No enhancements here. No difference even enabling/disabling exclusive mode on sound card by apps.
I changed nothing on my audio since this issue appeared. No setting, no driver updating, just reinstallation trying to fix. Maybe Windows has installed some updates, but nothing else. I restored power plan, reset some tweaks... no change.

**Comment by ABuffEr** [comment] 2023-08-18 15:15
CC: @jcsteh, even if WASAPI seems no directly related.

**Comment by jcsteh** [comment] 2023-08-18 23:07
If you can't reproduce this on headphones, this is very unlikely to have anything to do with NVDA. Because laptop speakers are rather small, manufacturers often have to compensate with tweaks which compress/enhance the audio in some way. Normally, this is done through driver audio enhancements which can be disabled, but maybe it isn't always this way.

**Comment by ABuffEr** [comment] 2023-08-19 17:46
> If you can't reproduce this on headphones, this is very unlikely to have anything to do with NVDA.

Sadly, and dramatically, I verified it right in the headphones.

**Comment by seanbudd** [comment] 2023-08-22 00:08
Can someone who can reproduce this perform a bisect so we know the commit this was introduced in

**Comment by ABuffEr** [comment] 2023-08-22 15:39
Hi @seanbudd,
I can just try various alpha, until to find one with the issue. What's the first alpha to integrate WASAPI implementation? It's a reasonable starting point, I think.

**Comment by Adriani90** [comment] 2023-08-22 15:59
Yes in my case disabling signal enhancements  solves this issue.
I can reproduce this issue even in NVDA 2021.1, this does not have anything to do with WASAPI.

Not sure NVDA can do anything about it, as Jamie pointed out. Thanks for the explanation.

Feel free to close this issue, although disabling signal enhancements is not an intuitive setting to find for novice users, maybe this should be noted in the user guide at least.
Another alternative would be to make NVDA tweak and disable this signal enhancement automatically as soon as the synth volume is set at 10 percent or less and enable it again as soon as the synth volume is above 10 percent.

**Comment by ABuffEr** [comment] 2023-08-22 16:24
> Another alternative would be to make NVDA tweak and disable this signal enhancement automatically as soon as the synth volume is set at 10 percent or less and enable it again as soon as the synth volume is above 10 percent.

Hi @Adriani90,
so if you set the voice volume to 80% or more, and system volume to 10 or 12%, you can reproduce the issue?
Yes, I know, it's a strange setting...
Maybe I found the cause, then...

**Comment by Adriani90** [comment] 2023-08-23 18:02
@ABuffEr setting the sound to lower volume and the synth to higher volume as you suggested, I cannot reproduce this issue, even when signal enhancements are enabled.

**Comment by ABuffEr** [comment] 2023-08-23 18:14
Damn. Ok, @Adriani90, thanks anyway. At this point I Think it's something in my software or hardware configuration, extremely difficult to track and reproduce. Feel free to close the issue.

**Closed** 2023-08-29 02:31 UTC
Labels: close/worksforme, p2, triaged
