### ISSUE TITLE
Enhancement for the beta Notification

### ISSUE THREAD

**Issue by BrianOlesen02** [nvaccess/nvda#17188] opened 2024-09-18 16:39 UTC
Dear NVDA
I have an idea I hope you’ll consider worth working on.
I’m super happy for participating in the beta program, and I’m so proud of all the great effort you put into this world class screen reader.
There is just one thing I really miss, when I get an update notification.
I wish you’d include a direct link in the notification, where we can read about the specific news for this particular iteration of NVDA.
Another more somewhat demanding way to do it is including some text in the window, but this probably would require internationalization. But a link to at least the English text would help a lot.
I believe that many just update their NVDA not knowing a single bit about what is going on with the version.

Best regards
Brian

**Comment by Adriani90** [comment] 2024-09-18 20:40
Welcome to the NVDA community. Thanks for reporting, I am Closing this one as duplicate of #17189 which you created shortly afterwards.

**Closed by Adriani90** 2024-09-18 20:40 UTC
Labels: close/duplicate

**Comment by BrianOlesen02** [comment] 2024-09-18 21:29
Hi,

Thank you

 

Fra: Adriani90 ***@***.***> 
Sendt: 18. september 2024 22:41
Til: nvaccess/nvda ***@***.***>
Cc: BrianOlesen02 ***@***.***>; Author ***@***.***>
Emne: Re: [nvaccess/nvda] Enhancement for the beta Notification (Issue #17188)

 

Welcome to the NVDA community. Thanks for reporting, I am Closing this one as duplicate of #17189 <https://github.com/nvaccess/nvda/issues/17189>  which you created shortly afterwards.
