### ISSUE TITLE
Attempt to cancel speech for expired focus events: dialog title discarded when finding text in browse mode

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11144] opened 2020-05-11 07:18 UTC
### Steps to reproduce:
1. Enable Attempt to cancel speech for expired focus events (set it to yes)
2. Open a browse mode document, e.g. in Firefox
3. Press Ctrl+NVDA+f to open the NVDA find dialog.

### Actual behavior:
NVDA only announces:
```
Type the text you wish to find  edit
```

`Find  dialog` is shown by the speech viewer, but it is interrupted immediately.

### Expected behavior:
NVDA announces:
```
Find  dialog
Type the text you wish to find  edit
```

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20175,9967903a

#### Windows version:
Windows 10 2004 19041.208

#### Name and version of other software in use when reproducing the issue:
Firefox 76.0.1

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, n/a

**Comment by lukaszgo1** [comment] 2020-06-16 19:36
Hi @feerrenrut I'm afraid this issue is not fixed for me with NVDA version alpha-20339,975d39d1 and Firefox Nightly 79 - dialog title is still discarded when it opens. @leonardder Can you confirm?

**Comment by feerrenrut** [comment] 2020-06-17 11:14
yes I can still reproduce this with the NVDA find dialog. I was using the run dialog (windows key + r) as an example when attempting to fix this issue. The issue here is that the title does not seem to be a direct focus ancestor of the edit control, at least that is what the "speechManager" debug logging says (enabled via advanced panel).

**Comment by feerrenrut** [comment] 2020-06-17 11:14
The run dialog, however, does seem to be fixed.

**Comment by feerrenrut** [comment] 2020-10-27 16:29
This should be fixed now, can anyone confirm?

**Comment by lukaszgo1** [comment] 2020-11-15 22:47
cannot reproduce with NVDA version alpha-21348,6af30832.

**Comment by feerrenrut** [comment] 2020-11-16 10:37
Thanks @lukaszgo1

**Closed by feerrenrut** 2020-11-16 10:37 UTC
Labels: component/speech
