### ISSUE TITLE
strange issue in latest espeak in nvda

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#7533] opened 2017-08-28 10:59 UTC
hello all.

i wasn't updating nvda next a while and today decided to update.

i discovered the following:

in georgian variant of espeak numbers 3 and 7 are spoken in english and in conjunction with other numbers these numbers aren't spoken at all.

**Comment by ehollig** [comment] 2017-08-28 13:18
Could you provide an example of the issue you are experiencing? When I type the numbers "3" or "7" and use ESpeak georgian, NVDA announces სამი (sami) for the number 3, and შვიდი (švidi) for the number 7.

**Comment by beqabeqa473** [comment] 2017-08-28 13:22
for me, it announces three and seven

On 8/28/17, Ethan Holliger <notifications@github.com> wrote:
> Could you provide an example of the issue you are experiencing? When I type
> the numbers "3" or "7" and use ESpeak georgian, NVDA announces სამი (sami)
> for the number 3, and შვიდი (švidi) for the number 7.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/7533#issuecomment-325350836


-- 
with best regards beqa

**Comment by beqabeqa473** [comment] 2017-08-28 14:07
i downloaded the latest next snapshot, created portable copy without
any old configs and addons and still experience this problem, when
espeak synthesizer set to georgian voice, without autolanguage
switching announces 3 and 7 as three and seven.

On 8/28/17, Beqa Gozalishvili <beqaprogger@gmail.com> wrote:
> for me, it announces three and seven
>
> On 8/28/17, Ethan Holliger <notifications@github.com> wrote:
>> Could you provide an example of the issue you are experiencing? When I
>> type
>> the numbers "3" or "7" and use ESpeak georgian, NVDA announces სამი
>> (sami)
>> for the number 3, and შვიდი (švidi) for the number 7.
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/7533#issuecomment-325350836
>
>
> --
> with best regards beqa
>


-- 
with best regards beqa

**Comment by ehollig** [comment] 2017-08-28 15:11
Confirmed when using portable Next14342,fc5b54d4. Seems to be alright in portable NVDA 2017.3 stable.
## STR

1. Launch Next14342,fc5b54d4
2. Change ESpeak voice to georgian
3. Open notepad and type the number "3 7"
4. Notice NVDA announces "three" and "seven" when speak typed characters is on
5. Press the up arrow to read by line
### Expected result
NVDA reports სამი (sami) for the number 3, and შვიდი (švidi) for the number 7.
### Actual result
NVDA reports "three for the number 3 and "seven for the number 7. When reading by line, NVDA reports nothing.

Note that from my tests, this appears to work correctly in 2017.3 stable.

**Comment by Brian1Gaff** [comment] 2017-08-28 16:32
Could this be a side effect of the way numbers can be read with the new 
configurable options?
 Just a thought. I don't use this language but it does seem odd otherwise.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by beqabeqa473** [comment] 2017-08-29 17:00
hello all.

one more issue was discovered.

i don't know if it is espeak issue bbut anyway, try to read the following line character by character
[■ ▶ ▮▮] ® Juventa, Erica Curran - Move Into Light (Koven Remix) ★  EXCLUSIVE! for club5485048 ★ [track at ➨ 04.11.2013] - Dubstep 4:22

you will get unrecoverable freeze of computer

**Comment by beqabeqa473** [comment] 2017-08-30 06:35
hi.

what can be done to fix these issues?

**Comment by Mary5958** [comment] 2017-09-01 20:43
I can reproduce the issues with 3 and 7 in Georgian, also 7 in Kannada; as if the translations of those numbers disappeared from Espeak-ng's dictionaries for those languages in the commits they were updated to in the more recent Next NVDA versions since August 24-25 or so. Seems to be more an Espeak-ng issue.

**Comment by feerrenrut** [comment] 2017-09-11 03:16
This seems to have been raised with espeak-ng: https://github.com/espeak-ng/espeak-ng/issues/302

**Comment by ehollig** [comment] 2018-11-20 04:17
This appears to be fixed in ESpeak 1.49.3 as https://github.com/espeak-ng/espeak-ng/issues/302 and https://github.com/espeak-ng/espeak-ng/issues/332 (both with the same cause) are closed. Closing this issue.

**Closed by ehollig** 2018-11-20 04:17 UTC
Labels: needsExternalFix
