### ISSUE TITLE
NonVisual Desktop Access (NVDA) Not Pressed being spoken in some dialogue items

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#5584] opened 2015-12-05 12:29 UTC
NonVisual Desktop Access (NVDA)
Version: next-12878,004ece4

Problem. On certain dialogue items, the words not pressed seem to be being spoken for no apparent reason. All next snaps prior to this one work as expected in the same situations.
 Here is the complete log of my version  but only showing start up the problem and the  close down.

INFO - __main__ (12:09:17):
Starting NVDA
INFO - core.main (12:09:18):
Config dir: C:\Documents and Settings\brian\Application Data\nvda
DEBUG - core.main (12:09:18):
setting language to Windows
INFO - core.main (12:09:18):
NVDA version next-12878,004ece4
INFO - core.main (12:09:18):
Using Windows version 5.1.2600 service pack 3 workstation
INFO - core.main (12:09:18):
Using Python version 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
INFO - core.main (12:09:18):
Using comtypes version 0.6.2
DEBUG - core.main (12:09:18):
Initializing addons system.
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Listing add-ons from C:\Documents and Settings\brian\Application Data\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Found add-on extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Found add-on fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Found add-on goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Found add-on resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Loading add-on from C:\Documents and Settings\brian\Application Data\nvda\addons\Speech Hub
DEBUG - addonHandler._getAvailableAddonsFromPath (12:09:18):
Found add-on Speech Hub
DEBUG - core.main (12:09:18):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (12:09:18):
Addon extendedWinamp added to appModules package path
DEBUG - addonHandler.Addon.addToPackagePath (12:09:18):
Addon goldwave added to appModules package path
DEBUG - core.main (12:09:18):
Initializing NVDAHelper
DEBUG - core.main (12:09:18):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (12:09:18):
Loading speech dictionary 'C:\Documents and Settings\brian\Application Data\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (12:09:18):
16 loaded records.
DEBUG - speechDictHandler.SpeechDict.load (12:09:18):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (12:09:18):
3 loaded records.
DEBUG - core.main (12:09:18):
Initializing speech
DEBUG - addonHandler.Addon.addToPackagePath (12:09:18):
Addon Speech Hub added to synthDrivers package path
INFO - synthDrivers.espeak.SynthDriver.__init__ (12:09:18):
Using eSpeak version 1.48.15  16.Apr.15
DEBUG - speechDictHandler.SpeechDict.load (12:09:19):
Loading speech dictionary 'C:\Documents and Settings\brian\Application Data\nvda\speechDicts\espeak-english.dic'...
DEBUG - speechDictHandler.SpeechDict.load (12:09:19):
2 loaded records.
INFO - synthDriverHandler.setSynth (12:09:19):
Loaded synthDriver espeak
INFO - core.main (12:09:19):
Using wx version 3.0.2.0 msw (classic)
DEBUG - core.main (12:09:19):
Initializing braille
INFO - braille.initialize (12:09:19):
Using liblouis version 2.6.5
INFO - braille.BrailleHandler.setDisplayByName (12:09:19):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (12:09:19):
Initializing braille input
INFO - brailleInput.initialize (12:09:19):
Braille input initialized
DEBUG - core.main (12:09:19):
Initializing displayModel
DEBUG - core.main (12:09:19):
Initializing GUI
DEBUG - core.main (12:09:19):
initializing Java Access Bridge support
DEBUG - core.main (12:09:19):
Initializing winConsole support
DEBUG - core.main (12:09:19):
Initializing UIA support
WARNING - core.main (12:09:19):
UIA not available
DEBUG - core.main (12:09:19):
Initializing IAccessible support
DEBUG - core.main (12:09:19):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (12:09:19):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (12:09:19):
No user gesture map
DEBUG - core.main (12:09:19):
Initializing keyboard handler
DEBUG - core.main (12:09:19):
initializing mouse handler
DEBUG - core.main (12:09:19):
Initializing touchHandler
DEBUGWARNING - touchHandler.initialize (12:09:19):
Touch only supported on Windows 8 and higher
DEBUG - core.main (12:09:19):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (12:09:19):
Addon fakeClipboardAnouncement added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (12:09:19):
Addon resourceMonitor added to globalPlugins package path
DEBUG - core.main (12:09:19):
Initializing core pump
DEBUG - core.main (12:09:19):
Initializing watchdog
DEBUG - core.main (12:09:19):
initializing updateCheck
INFO - core.main (12:09:19):
NVDA initialized
DEBUG - core.main (12:09:19):
entering wx application main loop
IO - speech.speak (12:09:19):
Speaking [LangChangeCommand ('en_GB'), u'MASTER 2 (I:) Properties  dialog']
IO - speech.speak (12:09:19):
Speaking [LangChangeCommand ('en_GB'), u'tab control']
IO - speech.speak (12:09:19):
Speaking [LangChangeCommand ('en_GB'), u'Tools  tab  selected  3 of 5']
IO - inputCore.InputManager.executeGesture (12:09:24):
Input: kb(desktop):tab
IO - speech.speak (12:09:25):
Speaking [LangChangeCommand ('en_GB'), u'Tools  property page']
IO - speech.speak (12:09:25):
Speaking [LangChangeCommand ('en_GB'), u'Error-checking  grouping  This option will check the volume for errors.']
IO - speech.speak (12:09:25):
Speaking [LangChangeCommand ('en_GB'), u'Check Now...  button  Alt+c']
IO - inputCore.InputManager.executeGesture (12:09:28):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:09:28):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:09:28):
Adding generator 1
IO - speech.speak (12:09:28):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:09:28):
generator 1 finished
IO - speech.speak (12:09:28):
Speaking [LangChangeCommand ('en_GB'), u'Check Disk MASTER 2 (I:)  dialog']
IO - speech.speak (12:09:28):
Speaking [LangChangeCommand ('en_GB'), u'Start  button  Alt+s']
IO - inputCore.InputManager.executeGesture (12:09:32):
Input: kb(desktop):tab
IO - speech.speak (12:09:32):
Speaking [LangChangeCommand ('en_GB'), u'Cancel  button']
IO - inputCore.InputManager.executeGesture (12:09:33):
Input: kb(desktop):tab
IO - speech.speak (12:09:33):
Speaking [LangChangeCommand ('en_GB'), u'Check disk options  grouping']
IO - speech.speak (12:09:33):
Speaking [LangChangeCommand ('en_GB'), u'Automatically fix file system errors  check box  not checked  Alt+a']
IO - inputCore.InputManager.executeGesture (12:09:39):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:09:39):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:09:39):
Adding generator 2
DEBUG - queueHandler.pumpAll (12:09:39):
generator 2 finished
IO - speech.speak (12:09:39):
Speaking [LangChangeCommand ('en_GB'), u'checked  not pressed']
IO - inputCore.InputManager.executeGesture (12:09:44):
Input: kb(desktop):tab
IO - speech.speak (12:09:44):
Speaking [LangChangeCommand ('en_GB'), u'Scan for and attempt recovery of bad sectors  check box  not checked  Alt+n']
IO - inputCore.InputManager.executeGesture (12:09:46):
Input: kb(desktop):tab
IO - speech.speak (12:09:47):
Speaking [LangChangeCommand ('en_GB'), u'Start  button  Alt+s']
IO - inputCore.InputManager.executeGesture (12:09:48):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:09:48):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:09:48):
Adding generator 3
IO - speech.speak (12:09:48):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:09:49):
generator 3 finished
IO - speech.speak (12:09:49):
Speaking [LangChangeCommand ('en_GB'), u'unavailable  not pressed']
IO - tones.beep (12:09:50):
Beep at pitch 666.915289265, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:09:50):
Speaking [LangChangeCommand ('en_GB'), u'65 percent']
IO - tones.beep (12:09:50):
Beep at pitch 1129.41478986, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:09:50):
Speaking [LangChangeCommand ('en_GB'), u'84 percent']
IO - tones.beep (12:09:50):
Beep at pitch 1490.27174976, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:09:50):
Speaking [LangChangeCommand ('en_GB'), u'94 percent']
IO - tones.beep (12:09:50):
Beep at pitch 1619.5302651, for 40 ms, left volume 50, right volume 50
IO - tones.beep (12:09:50):
Beep at pitch 1711.87270745, for 40 ms, left volume 50, right volume 50
IO - speech.speak (12:09:53):
Speaking [LangChangeCommand ('en_GB'), u'Checking Disk MASTER 2 (I:)  dialog  Disk Check Complete.']
IO - speech.speak (12:09:53):
Speaking [LangChangeCommand ('en_GB'), u'OK  button']
IO - inputCore.InputManager.executeGesture (12:09:57):
Input: kb(desktop):space
IO - speech._speakSpellingGen (12:09:57):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (12:09:57):
Adding generator 4
IO - speech.speak (12:09:57):
Speaking [LangChangeCommand ('en_GB'), u'pressed']
DEBUG - queueHandler.pumpAll (12:09:57):
generator 4 finished
IO - speech.speak (12:09:57):
Speaking [LangChangeCommand ('en_GB'), u'MASTER 2 (I:) Properties  dialog']
IO - speech.speak (12:09:57):
Speaking [LangChangeCommand ('en_GB'), u'Tools  property page']
IO - speech.speak (12:09:57):
Speaking [LangChangeCommand ('en_GB'), u'Error-checking  grouping  This option will check the volume for errors.']
IO - speech.speak (12:09:57):
Speaking [LangChangeCommand ('en_GB'), u'Check Now...  button  Alt+c']
IO - inputCore.InputManager.executeGesture (12:10:00):
Input: kb(desktop):control+alt+r
INFO - core.main (12:10:01):
Exiting
DEBUG - core._terminate (12:10:01):
Terminating updateCheck
DEBUG - core._terminate (12:10:01):
Terminating watchdog
DEBUG - core._terminate (12:10:01):
Terminating global plugin handler
DEBUG - core._terminate (12:10:01):
Terminating gui
INFO - config.ConfigManager.save (12:10:01):
Base configuration saved
DEBUG - core._terminate (12:10:01):
Terminating treeInterceptorHandler
DEBUG - core._terminate (12:10:01):
Terminating IAccessible support
DEBUG - core._terminate (12:10:01):
Terminating UIA support
DEBUG - core._terminate (12:10:01):
Terminating winConsole support
DEBUG - core._terminate (12:10:01):
Terminating Java Access Bridge support
DEBUG - core._terminate (12:10:01):
Terminating app module handler
DEBUG - core._terminate (12:10:01):
Terminating NVDAHelper
DEBUG - core._terminate (12:10:01):
Terminating touchHandler
DEBUG - core._terminate (12:10:01):
Terminating keyboard handler
DEBUG - core._terminate (12:10:01):
Terminating mouseHandler
DEBUG - core._terminate (12:10:01):
Terminating inputCore
DEBUG - core._terminate (12:10:01):
Terminating brailleInput
DEBUG - core._terminate (12:10:01):
Terminating braille
DEBUG - core._terminate (12:10:01):
Terminating speech
DEBUG - core._terminate (12:10:01):
Terminating addonHandler
DEBUG - core.main (12:10:02):
core done
INFO - __main__ (12:10:02):
NVDA exit

Note that this was just  a demo, it also happens in the nvda checkboxes etc. and others of course
This is Windows XP.

**Comment by jcsteh** [comment] 2015-12-07 02:27
Duplicate of #5580.

**Closed by jcsteh** 2015-12-07 02:27 UTC
Labels: duplicate
