### ISSUE TITLE
nvda don't speak properly on taskbar in windows 11

### ISSUE THREAD

**Issue by dhvajdhyani** [nvaccess/nvda#13251] opened 2022-01-18 06:04 UTC
### Steps to reproduce:
make the change in the code which is used in windows 11 and make it like windows 10
### Actual behavior:
it  speaks desktop windows xml sourse 
### Expected behavior:
it should speak taskbar
#### NVDA installed/portable/running from source:
windows 11 home  nvda 2021.3.1 installed 
#### NVDA version:
2021.3.1
#### Windows version:
windows 11 home
#### Name and version of other software in use when reproducing the issue:
every software 
#### Does the issue still occur after restarting your computer?
yes 
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by josephsl** [comment] 2022-01-18 06:11
Hi, does NVDA say anything else when you use NVDA 2021.2? Thanks.

**Comment by dhvajdhyani** [comment] 2022-01-18 06:31
No it speaks  only desktop windows xml source11:42, 18 January 2022, Joseph Lee ***@***.***>:
Hi, does NVDA say anything else when you use NVDA 2021.2? Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-01-18 06:49
Hi, when I did try with NVDA 2021.2 and 2021.3.1 on a Windows 11 system, when I press Windows+T to go to Taskbar, NVDA did announce the first icon which was File Explorer. I’m wondering if other Windows 11 users can reproduce this issue, otherwise I’m afraid this might be unique to your system. Thanks.

**Comment by dhvajdhyani** [comment] 2022-01-18 07:04
But try with mouse pad12:19, 18 January 2022, Joseph Lee ***@***.***>:
Hi, when I did try with NVDA 2021.2 and 2021.3.1 on a Windows 11 system, when I press Windows+T to go to Taskbar, NVDA did announce the first icon which was File Explorer. I’m wondering if other Windows 11 users can reproduce this issue, otherwise I’m afraid this might be unique to your system. Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-01-18 07:20
Hi, ah, I know what you are talking about then (next time, could you post that info under steps to reproduce section please?). This announcement is caused by the new UI framework Microsoft is using in Windows 11, and as such, I don’t think it can be resolved with NVDA I’m afraid. Thanks (sorry).

**Comment by dhvajdhyani** [comment] 2022-01-18 07:52
Ok so what can be done12:51, 18 January 2022, Joseph Lee ***@***.***>:
Hi, ah, I know what you are talking about then (next time, could you post that info under steps to reproduce section please?). This announcement is caused by the new UI framework Microsoft is using in Windows 11, and as such, I don’t think it can be resolved with NVDA I’m afraid. Thanks (sorry).



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-01-18 07:59
Hi, nothing really, I think. Thanks.

**Comment by dhvajdhyani** [comment] 2022-01-18 08:10
Ohh13:29, 18 January 2022, Joseph Lee ***@***.***>:
Hi, nothing really, I think. Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by dhvajdhyani** [comment] 2022-01-18 08:22
Can you talk. To Microsoft for it13:40, 18 January 2022, dhvajdhyani ***@***.***>:Ohh13:29, 18 January 2022, Joseph Lee ***@***.***>:
Hi, nothing really, I think. Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi 
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-01-18 08:26
Hi, I advise sending a feedback to Microsoft using Feedback Hub for his one. Thanks.

**Comment by dhvajdhyani** [comment] 2022-01-18 10:29
But u also give  feedback 13:56, 18 January 2022, Joseph Lee ***@***.***>:
Hi, I advise sending a feedback to Microsoft using Feedback Hub for his one. Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-01-18 15:27
Hi, I see. Thanks.

**Comment by dhvajdhyani** [comment] 2022-01-18 15:35
Okay20:57, 18 January 2022, Joseph Lee ***@***.***>:
Hi, I see. Thanks.



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by Qchristensen** [comment] 2022-02-17 05:39
Can someone please clarify exactly what the issue is here, the reproduction steps and what happens?  The title is the only comment which gives any clue.

**Comment by dhvajdhyani** [comment] 2022-02-17 07:00
Nvda taskbar bug  with mouse11:09, 17 February 2022, Quentin Christensen ***@***.***>:
Can someone please clarify exactly what the issue is here, the reproduction steps and what happens?  The title is the only comment which gives any clue.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi

**Comment by josephsl** [comment] 2022-05-02 06:35
Hi,

Few updates in May 2022:

* This is also reproducible with touch.
* This can be resolved partially if DesktopWindowXamlSource windows are reclassified as UIA elements, but it doens't work on all apps.

I vote to close this issue as #13506 provides details we need to resolve this partially.

Thanks.

**Closed by josephsl** 2022-05-02 06:35 UTC

**Comment by dhvajdhyani** [comment] 2022-05-16 03:45
OkayThank you12:05 pm, 2 May 2022, Joseph Lee ***@***.***>:
Hi,
Few updates in May 2022:

This is also reproducible with touch.
This can be resolved partially if DesktopWindowXamlSource windows are reclassified as UIA elements, but it doens't work on all apps.

I vote to close this issue as #13506 provides details we need to resolve this partially.
Thanks.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
--project cordenator and communication executive chakshumathi
