### ISSUE TITLE
RFC on Long-term code maintenance: remove duplicates, broken Windows API wrapper structures and functions, linting standardization

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8139] opened 2018-04-02 03:54 UTC
Hi,

This RFC (request for comments) proposal is meant to be a meta-issue on code maintenance concerns, bug reports, suggestions, and formulating long-term strategies for code cleanup:

Over the years, NV Access and contributors worked together to ensure equal access to technology by screen reader users. These were done through code contributions, translations, documentation efforts, online gatherings and other venues. Of these, code contributions made significant impact on uniting people's passions and skills through code that brought life-changing experiences to users around the world, with user count rising daily.

Although code contributions brought many new features and experiences, as well as refining existing functionality, one area that wasn't addressed extensively was code maintenance. Every NVDA release served to recognize hard work of code contributors who made impact on lives of people. At the same time, performance issues or broken features and code paths were reported by users and developers, some of them rather serious to a point where resources were spent trying to come up with workarounds for old issues from the past that was thought patched by newer NVDA versions.

The issue of code maintenance - specifically, broken code paths - was revisited recently via a Gitter conversation where a developer pointed out a broken function in winUser module (wrapper for user32.dll functions). After investigating this, another developer concluded that this was perhaps broken for a while and asked others to report similar code paths. However, as of this moment, NVDA ships with broken assumptions about some Windows API functions, as well as including duplicate classes, white space inconsistencies, compatibility problems for future imports and other issues.

Thus it is proposed that we go through the entire NVDA source code and come up with a strategy to reduce code clutter, update our assumptions and attitudes about API routines, update class hierarchy, make white spacing consistent and make it so code maintenance could be made a bit easier. Another proposal is to introduce a linter for NVDA Core contributions and perhaps a style guide so people can abide by some sort of a standardization.

At the moment the following issues with NVDA Core source code have been identified:

* White space inconsistencies around object assignment (=) in various modules, specifically GUI subsystem.
* One or more broken functions in winUser wrapper module.
* appModules.Explorer.SuggestionListItem versus NVDAObjects.UIA.SuggestionListItem.
* Lines that appear to be empty when in fact it is filled with tabs.
* Import problems for the future, including _winreg versus winreg.
* Inconsistent copyright headers between python and C++ files/helper modules.
* Outdated docstring for certain functions, classes and modules.

Reasons for proposing a community-wide linting project for the entire NVDA code base:

* To identify possible issues for porting to Python 3 from source code level (#7105).
* To serve as a way to summarize expectations from contributors in the future.
* To present a unified "identity" via consistent source code (unified identity as in allowing people to glimpse the NVDA culture and get a feel of the community effort through consistent source code presentation).

Reasons for not proceeding with this proposal:

* Burden and resource allocation issues for NV Access, the community, and outsiders.
* Uncovering one issue may lead to uncovering deeper issues that may result in rethinking the NVDA architecture.
* People have unique coding styles and assumptions.

As NV Access and the NVDA community celebrate twelve years of NVDA's service to the wider community this month, it gives us a golden opportunity to think about how far this screen reader has come, as well as think about short-term and long-term strategies. One way to make NVDA better in the long term is not just feature additions and enhancements; it is looking at the screen reader's progress and future from one of the lifelines that powers its current state: source code. In order for code maintenance issues to be addressed, not only participation from NV Access and key third-party contributors are needed, but others should help, including those outside the NVDA community (including academics, researchers, Python experts, sighted developers and users, future stakeholders, organizations and others). Only through a community effort can this proposal proceed, and only through a community effort will we see NVDA source code become more maintainable in the future, especially as we continue to journey toward Python 3 and other technologies.

Community comments are appreciated. Thanks.

**Comment by josephsl** [comment] 2018-04-02 03:59
CC @dglee42, @CToth, @TSpivey, @MichaelDCurran, @feerrenrut, @JCSTeh, @DerekRiemer, @LeonardDer and other stakeholders. Only those who are seriously concerned about or thinking of improving NVDA Core source code should comment, otherwise it will lead to noise (yes, I set this bar really high because source code is one of the key lifelines of a software project, especially for an international project as NVDA). Thanks.

**Comment by nvdaes** [comment] 2018-04-02 04:59
Hi, reading this I remember a PR opened by me long time ago:
https://github.com/nvaccess/nvda/pull/5937

Though maybe necessary to prioritize bugs and adding new features, a possible strategy maybe someone take care about suggestion concerning broken functions, misspellings, etc. Sometimes I study code in NVDA's core, but I don't pay attention since this perhaps is not a priority.
PS: The mentioned PR is quite old and I would need to look at it again if addressed.
Cheers

**Comment by leonardder** [comment] 2018-04-02 10:29
[**@josephsl**](https://github.com/josephsl) commented on [2 Apr 2018, 05:54 CEST](https://github.com/nvaccess/nvda/issues/8139#issue-310387817 "2018-04-02T03:54:05Z - Replied by Github Reply Comments"):
> At the moment the following issues with NVDA Core source code have been identified:

To me, I'd say it would be better to file separate issues for these and, instead of a meta ticket, use something like a wiki page. That's just my personal preference though.

> * White space inconsistencies around object assignment (=) in various modules, specifically GUI subsystem.

This is a tricky one. This can be solved quite easily, but leads to a massive amount of line changes and therefore a huge review burden. I wonder whether and how this could be automatized and properly tested.

> * One or more broken functions in winUser wrapper module.

Please elaborate (i.e. what functions, and how are they broken?) Especially for this issue, a separate issue has my preference.

> * Import problems for the future, including _winreg versus winreg.

I think these should be kept out of scope for this issue.

> * Inconsistent copyright headers between python and C++ files/helper modules.

Add to that the inconsistent order of header lines. Some files have their name on the first line, others don't.

> * Outdated docstring for certain functions, classes and modules.

Please elaborate (i.e. what modules, what functions and how are they out of date?)

**Comment by josephsl** [comment] 2018-04-02 14:39
Hi,

Although wiki does allow faster edits and slightly better collaboration, it isn't ideal for cases where coordination is essential. Also, when people submit pull requests, they won't be able to reference wiki pages via hashes.

As for specific:

* _winreg versus winreg: I believe it is still in scope because we have different files importing just the former, while at least one braille display driver module coerces the module name. Although it is better to address this as part of Python 3 transition, I think it is still relevant to this one.
* Broken functions: one example is winUser.getClientRect, as reported by someone on Gitter.
* Docstring: UIA handler, for instance (doesn't have a docstring at the moment).

Thanks.

**Comment by Brian1Gaff** [comment] 2018-04-02 15:50
This may be a naive comment, but..
 Is there no trace utility that can monitor routines and see what uses them 
and when? This at least might give some indication of any changes needed and 
how it might impact on the  usage if they were adapted to work more 
efficiently. Of course if you make a routine do more, then you need to find 
all the places where the writer has made their own version due to the 
shortcomings of the original.
 Been there done that in my youth. And no I'm not up to trying this with 
Python etc these days, Those were simpler times.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by josephsl** [comment] 2018-04-02 16:01
Hi, if you want to trace NVDA’s execution, then you need to be running it from source code where you do have full power of Python and C++. But at the moment, the focus of this one isn’t tracing – it is code maintenance strategies. Thanks.

**Comment by feerrenrut** [comment] 2018-04-03 23:41
There seem to be several different issues here. Broken code should have issues / PRs filed so we can fix asap. Same goes with improvements to docstrings, I would suggest keeping PRs for docstrings limited to single files / classes / functions. 

In terms of more general code style consistency and clean up, as well as errors that could be caught by linting tools / static analysis tools, I'm totally for it. However, my suggestion is that the first step is to ensure that new code changes meet some standard. Doing this manually in code review is hard, it's very easy to miss small things. A better way is to introduce an automated step in the build system to lint / analyse the code base. This can lint the code base and compare the output against a baseline. An increase in (or new) errors is a failure, a decrease in errors requires updating the baseline. The rules used for the linting should be published so that people can configure their editors to warn them of errors as they go.

**Comment by Robert-J-H** [comment] 2018-04-06 15:24
Hi
There's also the winKernel.py module which should be analyzed.
Firstly, I don't understand why not the ctypes paradigm is used for defining functions, i.e. with prototype and params.
A lot of functions are simply defined as e.g.

def readProcessMemory(*args):
    return kernel32.ReadProcessMemory(args)

This is hardly helpful for debugging.

Here is a concrete issue where exactly this function causes problems:

Use SVN Update from the context menu to e.g. update your translations.
The popped up window has a list
windowClassName=u'SysListView32'

It can't be read.
The trace is something like:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 389, in _get_name
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 336, in _getColumnContent
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 328, in _getColumnContentRaw
  File "winKernel.pyc", line 202, in readProcessMemory
ArgumentError: argument 2: <type 'exceptions.OverflowError'>: long int too long to convert

and indeed, after inserting a debug print for the passed 'args' we get the following:

>>> focus.name
2416 <type 'int'>
861470720 <type 'int'>
<cparam 'P' (05C4A9B8)> <type 'CArgObject'>
12 <type 'int'>
None <type 'NoneType'>
2620 <type 'int'>
861470720 <type 'int'>
<cparam 'P' (05631A08)> <type 'CArgObject'>
80 <type 'int'>
None <type 'NoneType'>
2620 <type 'int'>
1085558287168 <type 'long'>
<ctypes.c_wchar_Array_8 object at 0x05C4A5D0> <class 'ctypes.c_wchar_Array_8'>
16 <type 'int'>
None <type 'NoneType'>

Here is the fingerprint for the function:
API("kernel32", "ReadProcessMemory" , hProcess, &lpBaseAddress, &lpBuffer, nSize, &lpNumberOfBytesWritten)  


Now, it is finally clear that the huge number that causes the problem is a pointer.
Unfortunately, the function doesn't accept a 64-bit pointer, at least not in this fashion.
We're under python 32-bit and so is ctypes.

Anyway, my point is that a cleaner function definition wouldn't have forced me to do all the research in a zillion files and web pages.

Best
Robert

**Comment by Robert-J-H** [comment] 2018-04-13 07:13
I've opened an issue for the above mentioned problem:
#8175

**Comment by Adriani90** [comment] 2018-06-12 11:31
Is there a clear strategy on how to proceed with this? I suggest implementing WX Python 4 and Python 3.6 first and then brainstorm next year at NVDACon on what has to be improved and create a concept for next steps.

**Comment by josephsl** [comment] 2018-06-12 15:16
Hi, more towards wxPython 4 and Python 3.7. I’m sure the opportunity will present itself as we transition to Python 3.7. Thanks.

**Comment by derekriemer** [comment] 2018-06-21 09:38
I am closing this as invalid. Please open more specific issues in the future.

**Closed by derekriemer** 2018-06-21 09:38 UTC
