### ISSUE TITLE
NVDA Continues To Use 8-Dot Braille Table For Output When A 6-Dot Table Has Been Selected

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#8497] opened 2018-07-10 17:37 UTC
The Nemeth Searchable Database site allows users to review sample .BRF files demonstrating how symbols and terms are used.
http://accessibility.pearson.com/nemethdatabase/
Unfortunately, even when the English 6-dot computer braille table is selected for output, Dot 7 is still shown, making the .BRF content difficult to read.

### Steps to reproduce:
1.  Press NVDA+N, select Prefferences, followed by Settings.
2.  Down Arrow to the Braille category, and Tab to Output Table.
3.  Press E until "English (U.S.) 6 dot computer braille" is chosen, and press Enter.
4.  Open the database URL in any browser:  http://accessibility.pearson.com/nemethdatabase/
5.  Press H until you reach a definition heading such as "Absolute Value."  (Note that the words Absolute and Value still have Dot 7 raised under their capital letters.)
6.  Open either of the sample .BRF links, "Nemeth in EBAE," or "Nemeth within UEB."
7.  Note that Dot 7 is raised under all the letters in the file.

### Actual behavior:
Dot 7 is still present, even after 6-dot English computer braille is selected as the output table.

### Expected behavior:
Only 6-dot braille should be used to display content.

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
V2018.2

#### Windows version:
Windows 10 Version	10.0.15063 Build 15063

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes, V2018.1 with the same results.

**Comment by derekriemer** [comment] 2018-07-12 02:59
Can you try this with any older versions of NVDA? I saw this with the braille table for UEB but thought it was an isolated case.

**Comment by RD-Brown** [comment] 2018-07-12 03:13
Dear Derek,

Confirmed with V2018.1.  I don't currently have an older version installed on my system.

Dan

**Comment by dkager** [comment] 2018-07-15 09:32
This is a problem in the [liblouis](https://github.com/liblouis/liblouis) braille table and should be reported to that project. The en-us-comp6.ctb file contains this line:

> include latinLetterDef8Dots.uti

**Comment by dkager** [comment] 2018-07-15 09:46
I did some more searching; closing this as duplicate of #4014.

**Closed by dkager** 2018-07-15 09:46 UTC
Labels: Braille, needsExternalFix
