### ISSUE TITLE
Spanish Braille issues

### ISSUE THREAD

**Issue by jharris171185** [nvaccess/nvda#16061] opened 2024-01-18 03:41 UTC
Hello,
I am new to github and have never posted here before, but there is a major issue I must bring to your attention. In NVDA 2023.3.1 and earlier, there are major problems in the Spanish grade 1 table. I will outline these below. I have been using Spanish Braille since high school, so know exactly how the symbols in question should be written.
1. When attempting to write a period (.) by using dot 3, I get an apostrophe (') instead, as if I were writing in English.
2. When trying to write both a regular question mark (?) as well as the inverted question mark (¿) with the dots 2-6, instead it gives me the number five (5) as if I were writing in nemeth. Same with dots 2-3 for the semicolon (;). Dot 2, for the comma, seems to work. In Spanish, like in English, Nemeth is not necessary in grades 1 and 2, as we can easily use a number sign followed by the numbers as we would always write them.
3. With dots 2-3-5, you are able to write a regular exclamation mark (!) but not the inverted exclamation mark (¡).
I know I probably haven't filled this thing out as you may want it, however I have provided easy to reproduce steps to varify the veracity of my claims, and I can also confirm that the symbols in question work propperly, even in other platforms that use Liblouis, such as iOS, and even the old Soft Braille Keyboard on Android. NVDA and JAWS both are the only places or programs I have seen these not work propperly. I can also reproduce this on both my Focus 40 Blue as well as my Orbit Reader 20.
Thanks in advance for your help in getting this fixed.
Sincerely,
Justin Harris

**Comment by Adriani90** [comment] 2024-01-20 13:04
Closing as duplicate of #10246.

**Closed by Adriani90** 2024-01-20 13:04 UTC
Labels: close/duplicate
