### ISSUE TITLE
ESpeak American English voice sounds very different in 2022.3

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#14225] opened 2022-10-09 12:53 UTC
### Steps to reproduce:
Use NVDA with these settings, though not all of them may be required:

* ESpeak synthesizer
* English (American) dialect (note that this is NOT the new New York dialect, just regular American English)
* Max voice (ESpeak's default)
* 100% speech rate, no rate boost

### Actual behavior:

The voice sounds... wrong. When compared to 2022.2 and, well, all the NVDA versions I've used for ten years, this new ESpeak sounds wrong. Sometimes, there are bits of crackling, as though the voice were coming through a microphone that was clipping. Some phonemes are extended further than they should be, specifically, I've noticed this happens with some N and R sounds.This, and perhaps other changes, make the overall pacing of the synthesizer sound different, and less easy to understand. I changed no settings after the upgrade. Other dialects don't seem to have this problem, though I have little pre-2022.3 experience with them, so couldn't identify them as easily.

### Expected behavior:

ESpeak's Max voice in American English should sound how it did before this upgrade.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2022.3 public release

#### Windows version:
Windows 10, 21H2

#### Name and version of other software in use when reproducing the issue:
N/A, happens everywhere

#### Other information about your system:
Nothing applicable I can think of

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this (2022.3) is the first time I noticed this change.

#### If NVDA add-ons are disabled, is your problem still occurring?
I don't think this applies.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Again, a speech change, so this shouldn't apply.

**Comment by zstanecic** [comment] 2022-10-09 13:25
Hi,

This is something you need to open issue for espeak devs.

Thanks, 

Zvonimir

 

From: Alex Hall ***@***.***> 
Sent: Sunday, October 9, 2022 2:54 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] ESpeak American English voice sounds very different in 2022.3 (Issue #14225)

 


Steps to reproduce:


Use NVDA with these settings, though not all of them may be required:

*	ESpeak synthesizer
*	English (American) dialect (note that this is NOT the new New York dialect, just regular American English)
*	Max voice (ESpeak's default)
*	100% speech rate, no rate boost


Actual behavior:


The voice sounds... wrong. When compared to 2022.2 and, well, all the NVDA versions I've used for ten years, this new ESpeak sounds wrong. Sometimes, there are bits of crackling, as though the voice were coming through a microphone that was clipping. Some phonemes are extended further than they should be, specifically, I've noticed this happens with some N and R sounds.This, and perhaps other changes, make the overall pacing of the synthesizer sound different, and less easy to understand. I changed no settings after the upgrade. Other dialects don't seem to have this problem, though I have little pre-2022.3 experience with them, so couldn't identify them as easily.


Expected behavior:


ESpeak's Max voice in American English should sound how it did before this upgrade.


NVDA logs, crash dumps and other attachments:


System configuration


NVDA installed/portable/running from source:


installed


NVDA version:


2022.3 public release


Windows version:


Windows 10, 21H2


Name and version of other software in use when reproducing the issue:


N/A, happens everywhere


Other information about your system:


Nothing applicable I can think of


Other questions


Does the issue still occur after restarting your computer?


yes


Have you tried any other versions of NVDA? If so, please report their behaviors.


Yes, this (2022.3) is the first time I noticed this change.


If NVDA add-ons are disabled, is your problem still occurring?


I don't think this applies.


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


Again, a speech change, so this shouldn't apply.

**Comment by mehgcap** [comment] 2022-10-09 13:50
Update: the fix, which I only found thanks to a Twitter reply, is this: set your speech rate to about 20, then enable rate boost. Something changed, though I'm not sure if the setting was with NVDA or ESpeak, and 100% no longer means what it did. I never would have found this out without that helpful tweet. I feel that NVDA should show a notice to the user if it detects that ESpeak is that user's synthesizer of choice at the time of the update.

**Comment by CyrilleB79** [comment] 2022-10-09 21:30
This issue is the same as #13952 and thus is considered a duplicate of #13876.

For the record, the root cause of this issue on eSpeak's side is espeak-ng/espeak-ng#131.

With NVDA 2022.2, if you were using eSpeak rate 100%, rate boost off, you should now use eSpeak at rate 19% and rate boost on with NVDA 2022.3 to get the same voice.

**Comment by seanbudd** [comment] 2022-10-09 23:09
Closing as duplicate of #13876

**Closed** 2022-10-09 23:09 UTC

**Comment by seanbudd** [comment] 2022-10-10 01:50
> I feel that NVDA should show a notice to the user if it detects that ESpeak is that user's synthesizer of choice at the time of the update.

This is quite an unusual pattern for NVDA, we don't tend to warn users in NVDA when changes occur.
Note that this is listed in the change log as a bug fix.
We might want to consider covering this change in In-Process @Qchristensen .

"When rate boost is off, eSpeak's rate does not drop anymore between rates 99% and 100%. (#13876)"

**Comment by Qchristensen** [comment] 2022-10-10 02:07
Sean, thanks for the heads up, I'll definitely include this in In-Process next week: https://www.nvaccess.org/category/in-process/

We usually try to change features in such a way that existing users of a setting would not notice a change to how they have it set.  Occasionally, if the change is to fix a bug, (as here), it can lead to a change in behaviour, as it has fro @mehgcap in this case.  Apologies for the inconvenience!

**Comment by CyrilleB79** [comment] 2022-10-10 07:41
Thinking again to it, I may have implemented a config upgrade for eSpeak users using eSpeak at rate 100% RB off to modify it to rate 19% RB on. This would have allowed a smoother transition.

Anyway, now it's too late for such a solution. Communicating the impact of the change is now the only path. In-process is definitely a good channel for it.

@Qchristensen feel free to e-mail me if you want me to review in-process wording for this topic before releasing.
