### ISSUE TITLE
Could do these in Narrator, how to do them in NVDA?

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10294] opened 2019-09-28 13:28 UTC
Win 10 / NVDA portable 2019.2 / Laptop layout

Hello. Moving on from Narrator and was wondering if someone could help me replicate the following functionality in NVDA?

1. In Firefox with Narrator I could just point the mouse at a paragraph and it would read out the whole paragraph. In NVDA it just reads a line at a time.How can I replicate the Narrator behaviour? This is the biggest bugbear as in Narrator I could just whizz through, for example, the messages on a message board, quickly getting a sense of whether I wanted to read the whole thing or move on. Having to drag the mouse down bit by bit, or fiddle with navigation is making the whole process laborious and warying.

2. The reading of message boxes. In NarratorI could press CAPS+W and it would read out the whole message box for me. How do I replicate that in NVDA? Fiddling about with object navigation can be tricky as it is often not clear that I am at the point the text can be read, amd the routes to this point can be different in different msg boxes. Again, in Narrator it was just press CAPS+W and you were sorted.

3. With Narrator if I was checking the spelling of a word character-by-character in notepad say, and was unsure of what the letter was, all I had to do was hold for a moment and Narrator would then state a word to correspond to the letter. For example, if unsure if I was hearing a "n" or an "m", just wait a moment and Narrator would follow up with a "Mike" or a "November". I know I can press CAPS+,twice, but sometimes that reads out a letter from somewhere else, if the review cursor is not synced to the caret. So again, several bits of fiddling required when in Narrator this could happen very simply.

Please do not let the comments hear make it seem that I dislike NVDA. It is a big improvement on Narrator in almost everyother way. But for the above bugbears.

If nothing else, please help with 1. as that is the one issue that may well end up being a deal-breaker for me. Not reading out paragraphs, and the fiddling required to get around this, is getting very grating in my Firefox usage.

Thanks.

**Comment by JulienCochuyt** [comment] 2019-09-28 15:14
1. What is you text unit setting in the mouse category of the preferences? Does setting it to "paragraph" behaves as you'd expect?

2. You can read a whole dialog box with  `NVDA+B`

**Comment by TechHorseG** [comment] 2019-09-28 15:42
Thanks for response.

1. It is set to paragraph. I have also tried other res settings just in case. And in Edge it does read out whole paragraphs. Narrator reads out paragraphs in both.

2. Not FOR all boxes unfortunately. For example the WARNING msg boxes of FreeFileSync.

**Comment by CyrilleB79** [comment] 2019-09-30 11:36
For point 3, it is not (yet ?) supported natively in NVDA.
However an add-on currently in development may fit your needs.

Download link for last release:
https://davidacm.github.io/getlatest/gh/davidacm/EnhancedPhoneticReading

Github repo:
https://github.com/davidacm/EnhancedPhoneticReading

**Comment by JulienCochuyt** [comment] 2019-10-01 04:37
(Did some issue tracker mining)
Point 1 is indeed reported as broken by issue #2940.

**Comment by TechHorseG** [comment] 2019-10-03 15:04
Re point 1, let me add my voice to those asking for an option to 'read whole text node' (assuming I have understood that correctly). Or just _some_ way. Narrator reads whole paragraphs in Firefox so clearly it must be technically possible.

Thanks for the addon. Made extensive use of that feature in Narrator as I often cannot tell whether George has stated a v, b, n or m. That addon makes life simpler. Thanks again.

**Comment by Adriani90** [comment] 2020-01-18 21:06
For point 3 there is issue #8822.
For point 2, please open a new issue with exact stepts to reproduce so that we can exactly see what the issue is.
As of now I am closing this one. Thanks for reporting.

**Closed by Adriani90** 2020-01-18 21:06 UTC
