### ISSUE TITLE
It's not Possible to Change Rate in Espeak

### ISSUE THREAD

**Issue by Marlin86** [nvaccess/nvda#8242] opened 2018-05-07 15:31 UTC
1. Using the most recent next version, select Espeak as your Synthesizer;
2. Try to change its rate using tab or arrow keys.

Note that the rate keeps the same ever you press ok or apply and this problem doesn't occurs when using other synthesizers.

**Comment by derekriemer** [comment] 2018-05-08 06:03
There was some massive regression with the update to easpeak. This'll need fixed.

**Comment by michaelDCurran** [comment] 2018-05-08 07:54
Duplicate of #8231 which is now fixed in Next.

**Closed by michaelDCurran** 2018-05-08 07:54 UTC
