### ISSUE TITLE
Wrong informations on selecting text in a web page's virtual buffer

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#6921] opened 2017-02-26 18:41 UTC
NVDA no longer says correctly the number of characters I have just selected by pressing control-a in a web page. To reproduce, enter into any web page e.g.: http://oralux.org/. Press control-a to select all, and pay attention to what is said. Then press any arrow key to undo the selection, and press control-a again. NVDA will say another thing, which sometimes is a different number of characters, other times it simply reads the beginning of the page's contents. Also, if you press control-c to copy the select text, pasting it into an editor will reveal that NVDA haven't copied the entire text, particularly the last lines.

The bug started in 2017.1. I'm using Firefox 47.0.2.

**Comment by feerrenrut** [comment] 2017-03-14 09:25
@Cleversn Thanks for creating the issue.

- Can you clarify how you determined that the bug started in 2017.1?
- Have you tested earlier versions of NVDA against Firefox 47.0.2?
- If so, which versions?

**Comment by Cleversn** [comment] 2017-03-14 13:44
Hello, I'm sorry, it in fact seems that the bug manifests also in previous NVDA versions. I tested it now in NVDA 2015.4 and Firefox 50.0, and it occurs too, albeit the spoken informations are less discrepant, i.e., the number of characters vary less. In addition, just for info, it never occurs in Internet Explorer.

**Comment by jcsteh** [comment] 2017-03-21 05:55
Duplicate of #6909.

**Closed by jcsteh** 2017-03-21 05:55 UTC
