### ISSUE TITLE
NVDA does not focus on the microsoft office administration dialog box

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8760] opened 2018-09-18 19:02 UTC
### Steps to reproduce:
To do this test, you need to access the office's corporate account administration page.
I am working in a company and I have this need at the moment.
Go to:
outlook.com/ (company domain name)
Now click
Application Launcher
now navigate to:
Go to the Office 365 Administration Center
Now at the bottom of the page
there is a place that the nvda utters:
App.
press enter to enter the application within the page.
Now enter a user name to search.
Walk with the arrow keys down to find a user.

### Actual behavior:
Walk with arrows and tabo through this page.
A person with vision reported that nvda is focused on a page behind another page that was opened where there are various controls to perform for the user, such as resetting password, which is the option I need right now.
### Expected behavior:
After locating the person with the arrow keys or below and pressing enter, the navigational focus of nvda should go to the new dialog where there are the options of the activities that can be executed with the user, in case there is option that more accurate is the one of Password Reset.

#### NVDA Installed/portable/running from source:
instal
#### NVDA version:
alfa 16026
#### Windows version:
10 17134.285
#### Name and version of other software in use when reproducing the issue:
chrome 69
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?

no

**Comment by Adriani90** [comment] 2019-12-20 21:29
@fernando-jose-silva are you still having this issue with NVDA 2019.3 Beta 1 in Chrome 79?

**Comment by fernando-jose-silva** [comment] 2019-12-23 01:43
Unfortunately I no longer have access to this tool.
Thanks.

**Comment by Adriani90** [comment] 2019-12-23 14:56
Thanks for reporting back. Closing because it will not be possible to reproduce this without someone with access to that tool. If someone still has this problem, please comment on this issue and we can reopen it. Thanks.

**Closed by Adriani90** 2019-12-23 14:56 UTC
