### ISSUE TITLE
The latest snapshot for NVDA!

### ISSUE THREAD

**Issue by BEdenhofer** [nvaccess/nvda#8068] opened 2018-03-08 22:57 UTC
I've recently downloaded the latest snapshot of NVDA, and it launched, and a message comes up saying error registering remote hook, and there's a button that says okay, so I space on it, and everything is fine after that I can reproduce this problem, everytime I reload NVDA!

**Comment by josephsl** [comment] 2018-03-08 22:58
Hi, isn’t this yet another duplicate of an issue not long ago? Thanks.

**Comment by Brian1Gaff** [comment] 2018-03-09 10:24
Was not this cured by changing the file bundled with nvda?
 Brian

bglists

**Comment by dkager** [comment] 2018-03-10 13:16
@BEdenhofer I updated your report to remove the issue template you hadn't used. Please take note of it next time. :)

**Comment by BEdenhofer** [comment] 2018-03-11 02:50
Okay.

**Comment by tapper82** [comment] 2018-04-02 05:15
If this is fixed I rec emend this be closed. I cant reproduce  this bug on windows 7 or windows 10.

**Comment by dkager** [comment] 2018-04-02 08:31
Closing because of a lack of information. If the problem still occurs, please open a new issue and follow the issue template so that we have more information to go by. Also provide a clear issue title that describes the problem. Finally, check to make sure there is not already an open issue that deals with the problem.

**Closed by dkager** 2018-04-02 08:31 UTC
