### ISSUE TITLE
NVDA acting differently with regard to a web table when viewing same page in Firefox vs. Chromium-based browsers

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#11831] opened 2020-11-11 17:16 UTC
### Actual behavior:  In all Chromium-based browsers, there is a table, and you land in row one, column one, which so happens to be blank, with the real data immediately afterward.  It appears these are used as place holders, but the T shortcut always finds a table.

In Firefox, no table is found and NVDA says, "Nonex Table," which I presume is shorthand for non-existent table

**Comment by lukaszgo1** [comment] 2020-11-15 22:06
cc @jcsteh

**Comment by jcsteh** [comment] 2020-11-15 23:59
Firefox has heuristics which treat this as a layout table. This is not unreasonable in this case, since the table serves no semantic purpose whatsoever; the first column is entirely blank, so there's no point in having rows and columns at all. Chromium has heuristics for determining layout tables as well, but they're slightly different to Firefox's. If you don't like this, you can enable "Include layout tables" in NVDA's browse mode settings, but note that you'll get a lot of extraneous nonsense if you do.

**Comment by britechguy** [comment] 2020-11-16 00:11
The problem being, the exact same webpage is behaving differently under Firefox and Chromium-based web browsers using NVDA.

Your suggestion does nothing to address the underlying inconsistency, which should not exist, period.

I should not have to adjust NVDA settings on a by-browser-I'm-using basis for something like this.

No solution has been achieved, including in the suggested course of action.  This issue still requires addressing, as it will certainly not be limited to this specific instance.  NVDA should do the same thing, on the same page, regardless of the browser in which a given page is open.

**Comment by jcsteh** [comment] 2020-11-16 00:28
In areas like these where guesswork heuristics are used, there is always going to be some inconsistency because guesswork heuristics are inherently not standardised across browsers. They're provided to help the user where possible. If you want to argue that full consistency and standards compliance should always be the goal, all tables should technically be treated as tables, in which case you should enable inclusion of layout tables, after which you will get a fully consistent experience.

I guess NVDA could do its own layout table detection and not rely on the browser, but that would be up to the NVDA core developers, of which I am not one. I will reopen this on that basis and let them triage.

**Comment by britechguy** [comment] 2020-11-16 00:31
Thank you.

I understand what you're saying, including the part about potential for inconsistency, but feel this is not an instance where there should be one.  

There is just no way that any typical user is going to understand why there is a huge difference between how NVDA interacts with the same page.  And I can't figure out why, if both browsers actually give NVDA the information that there is a layout table, that NVDA does not act consistently based upon that information.  Of course, both browsers may not be, but an end user wouldn't know that, either.

**Comment by jcsteh** [comment] 2020-11-16 00:35
To clarify (I guess this wasn't clear), figuring out whether something is a layout table is guesswork if the web author doesn't explicitly specify (which 99% of the time they don't). Different browsers have different heuristics for making that guess; as I said, it's a guess, so it can't be standardised. Technically, standardisation would dictate that this guesswork shouldn't exist at all, but pragmatically, this hurts users more than it helps them. The author could also fix this by explicitly specifying that this is a data table (or a layout table, whichever they believe to be true).

**Comment by Adriani90** [comment] 2024-03-18 23:25
The design of the website changed and the table seems accessible now both in Firefox and Chromium browsers. Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-03-18 23:25 UTC
Labels: close/worksforme

**Comment by BabyElias** [comment] 2024-07-10 02:57
Hey, can someone let me know about what changes needed to be done in the table to be accessible in firefox as well? Facing the same issue.

**Comment by Adriani90** [comment] 2024-07-10 04:20
Please provide a minimal test case, otherwise it is difficult to give any competent advice.

**Comment by BabyElias** [comment] 2024-07-10 06:06
This is how the table is read in Chrome, without any issues. With all contents within the table properly read out.
![image](https://github.com/nvaccess/nvda/assets/95405559/37320238-236c-440d-ad0d-174c1d5f206c)

This is how the table reads like in firefox. The contents of the table are not read out by NVDA and there's an unnecessary 'Not selected' attribute coming from no idea where.
![image](https://github.com/nvaccess/nvda/assets/95405559/c108bfff-d961-4bf4-80aa-f5655e07b071)

**Comment by Adriani90** [comment] 2024-07-10 06:33
Here are alot of blind developers., so please describe your screenshots.By minimal test case I mean a html or any code snippet for this table. You can create one on codepen for example.Von meinem iPhone gesendetAm 10.07.2024 um 08:07 schrieb Anoushka Jha ***@***.***>:﻿
This is how the table is read in Chrome, without any issues. With all contents within the table properly read out.
image.png (view on web)
This is how the table reads like in firefox. The contents of the table are not read out by NVDA and there's an unnecessary 'Not selected' attribute coming from no idea where.
image.png (view on web)

**Comment by BabyElias** [comment] 2024-07-10 08:20
Didn't have an idea about that. 
The code sample can be found here : https://github.com/BabyElias/kolibri-design-system/blob/gsoc-table/lib/KTable/index.vue
and the tables can be viewed at this link : https://deploy-preview-669--kolibri-design-system.netlify.app/playground/
The problem as mentioned in the screenshots is, 
With Chrome browser, the screen reader output is perfect. It highlights the cell contents when placed over the cell. But with firefox browser, it announces "not selected row x column y column header" and not the actual cell content. The 'not selected' text is also very ambiguous since there is no such code-piece that has a checked attribute in the table.

**Comment by Adriani90** [comment] 2024-07-10 11:28
@BabyElias your issue seems rather a duplicate of #12997. I will post the link there as well.
