### ISSUE TITLE
In Office 2016 ribbons/tabs, NVDA repeats info

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6740] opened 2017-01-16 22:32 UTC
STR
# Open Outlook.
# press alt+f to enter the file tab.
# Press down arrow multiple times to read items.

When tabs are present, NVDA speaks the item twice followed by the short-cut key. The first is "X tab" then X followed by its associated shortcut key. For example "info tab, info alt, f, i." See log below. This occurs in all Office 2016 applications. Example drawn from Outlook. This repetition does not occur when the menu item is not a tab.

Log:

IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'Inbox - ppatel@ezfire.net - Outlook']
IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'Table View  table']
IO - speech.speak (17:13:34):
Speaking [LangChangeCommand ('en'), u'From Corey Malone, Subject ADA (we talked on twitter, Received Fri 1/6/2017 4:27 PM, Size 147 KB, Conversation ADA (we talked on twitter,  row 1  column 1  level 1']
IO - inputCore.InputManager.executeGesture (17:13:37):
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (17:13:40):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:40):
Speaking [LangChangeCommand ('en'), u'Info  tab  selected  Info  Alt, F, I  ']
IO - inputCore.InputManager.executeGesture (17:13:42):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:42):
Speaking [LangChangeCommand ('en'), u'Open & Export  tab  selected  Open & Export  Alt, F, O  ']
IO - inputCore.InputManager.executeGesture (17:13:44):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:44):
Speaking [LangChangeCommand ('en'), u'Save As  Alt, F, A  ']
IO - inputCore.InputManager.executeGesture (17:13:45):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:45):
Speaking [LangChangeCommand ('en'), u'Save\xa0Attachments  unavailable  Alt, F, M  ']
IO - inputCore.InputManager.executeGesture (17:13:48):
Input: kb(laptop):downArrow
IO - speech.speak (17:13:48):
Speaking [LangChangeCommand ('en'), u'Print  tab  selected  Print  Alt, F, P  ']

**Comment by josephsl** [comment] 2017-01-16 22:49
Hi,

Try:

1. Open NVDA menu/Preferences/Object presentation.
2. Turn off "Report object descriptions" and press ENTER.

Technical: UIA exposes control label as the description and NVDA sees these menu items as tabs. Also, these controls have different UIA class names depending on if it's a plain menu item or a tab.

I'd personally leave this alone unless users can justify that duplicate announcement issue vshould be fixed. Thanks

CC @MichaelDCurran, @feerrenrut

**Comment by PratikP1** [comment] 2017-01-16 23:28
While this is a good temporary solution, it does not remove the need to address the problem. The question is whether turning off object description altogether outweighs the easy fix.

**Comment by jcsteh** [comment] 2017-01-17 00:11
It's probably worth filing a bug with Microsoft. They shouldn't be exposing
the label in two places.

**Comment by PratikP1** [comment] 2017-01-17 00:12
I’ve already done that.

**Comment by PratikP1** [comment] 2017-01-17 00:13
Already done.

**Comment by Adriani90** [comment] 2019-03-30 18:06
The issue is still reproducible in MS Office Word, Excel, Powerpoint and Outlook.

**Comment by Adriani90** [comment] 2020-02-27 21:22
I think needs external fix is not appropriate here. Maybe this could be fixed in NVDA, I guess NVDA catches the information from two sources at the same time.
cc: @lukaszgo1 what do you think?

**Comment by Adriani90** [comment] 2023-03-07 11:08
This is fixed as of now with MS Office 2016, MS Office 365 and NVDA 2022.3.1 and 2022.4. Closing as works for me.

**Closed by Adriani90** 2023-03-07 11:08 UTC
Labels: close/worksforme, blocked/needs-external-fix, app/microsoft-office
