### ISSUE TITLE
Timing issues in virtual buffers

### ISSUE THREAD

**Issue by FelixGruetzmacher** [nvaccess/nvda#6586] opened 2016-11-23 09:20 UTC
The following was observed with Firefox, Internet Explorer and Chrome Canary in their respective current versions at time of writing.
Browse mode navigation is not deterministic when done quickly.
Example:
- Go to www.heise.de
- Wait until page fully loaded
- Go to start of page
- Hit h five times, allowing a second to pass in between, and make a note of the heading arrived at
- Return to top of page
- Hit h five times with 200 ms or less in between
- Observe that the browse mode cursor does not reliably end up on the heading previously noted
Another example:
- Make sure automatic focus mode for focus changes is on, but automatic focus mode for caret movement is off
- Go to www.google.com
- Hit esc to enter browse mode
- Alternate between holding down arrow and holding up arrow until at end or beginning of page respectively
- Observe that focus mode sporadically turns on although preference would prohibit this

**Comment by feerrenrut** [comment] 2016-11-27 07:09
This seems like something that should be fixed to improve confidence in NVDA, and enable users to maximise their efficiency when navigating pages. Sporadic differences in behaviour can be quite off putting, particularly to new users.

Setting the priority 2 label to look into this. Consider altering the priority once the cost to fix is known.

**Comment by jcsteh** [comment] 2016-11-27 07:21
This is a duplicate of #2039, though I understand this mightn't be obvious
to most.

**Comment by Brian1Gaff** [comment] 2016-11-27 09:06
Does this also  cause the issue where auto say all on page load fails, 
normally on the first page loaded in a session but sometimes others. 
Certainly one sees the same processor spike in this condition. I always used 
to think this was just my clunkers but since I have some four core  machines 
running 7 and 10 and this still intermittently happens, particularly in 
firefox, then it does make me wonder a little.
 I have also noticed some weird effects in pages, such as the update checker 
from file Hippo which launches the default browser and sometimes either 
misses the part with the list of programs you need to updddate altogether, 
or just the download links for them. I suspect his is indeed  driven by 
javascript as has been said, and a refresh can fix it.
 The other instance is on BBC I player tv sites where either the embedded 
object will not show up, or the prompt for do you have a tv licence is 
missing, making the page unusable until a  refresh.
 Not game stoppers just irritating when they occur.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by feerrenrut** [comment] 2016-11-28 01:53
Closing this issue, since it is a duplicate of #2039

**Closed by feerrenrut** 2016-11-28 01:53 UTC
Labels: duplicate, p2
