### ISSUE TITLE
Delay of around 7 seconds when changing to application using configuration profiles other than normal

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#8032] opened 2018-02-23 05:21 UTC
Example:
1. Open Firefox
2. Visit Configuration profiles from NVDA.
3. Create a new profile called Web and assign it to the application.

When switching between Firefox and other applications, significant delays are encountered.
This is true of any application for which a separate config profile is created, e.g. Microsoft Word.
This behaviour has been observed 
in NExt and Master builds of NVDA this week. Behaviour does not occur NVDA 2017.4. Behaviour is present in NVDA 2018.1 RC1.

**Comment by josephsl** [comment] 2018-02-23 05:23
Hi, what speech synthesizer and/or Windows version are you using? Also, is this FF58? Lastly, what about creating and switching to profiles for other apps (such as Notepad or Chrome)? Thanks.

**Comment by leonardder** [comment] 2018-02-23 05:44
Are you using a braille display by any chance?

**Comment by sjtaylor82** [comment] 2018-02-23 05:45
I certainly do intermittently, but Braille is currently set to No Braille.

**Comment by michaelDCurran** [comment] 2018-02-23 05:49
If you Restart NVDA with add-ons disabled, do you still experience the 
delay?

**Comment by sjtaylor82** [comment] 2018-02-23 05:50
HI Mick, Yes I do.

However, I have just changed braille input from UEB grade 2, to grade 1, 
and back to grade 2 again, still set to no braille.

I no longer can replicate the issue!

Come to think of it, this only started after recently using a HIMS 
braille display

**Comment by josephsl** [comment] 2018-02-23 05:53
Hi, uh oh, @LeonardDer… Okay, please report back after you use NVDA without a braille display for a day (complete with switching back and forth between normal configuration and FF profile) and see if you can reproduce this. If it does turn out to be an issue while using a specific display, then we need to test if folks using other display models can reproduce this problem. Thanks.

**Comment by michaelDCurran** [comment] 2018-02-23 05:53
No doubt NVDA was still configured to load the Hims driver. but as it 
was not connected or in range, it was falling back to No Braille.


I think I should be able to reproduce this situation with another 
braille display connected by bluetooth and out of range.

Thanks for reporting the issue.

**Comment by michaelDCurran** [comment] 2018-02-23 05:58
Technical:
I think the issue is that when Braille handles a config switch, it 
compares the configured display name (in this case Hims) with the 
currently loaded display name (in this case No Braille). As they don't 
match, then Braille thinks it needs to reload the display. In some cases 
(such as a bluetooth device being out of range) this could take a 
significant delay to  search and fail.
We need to somehow track that No Braille was loaded due to another 
failed device.

**Comment by josephsl** [comment] 2018-02-23 06:03
CC @DKager, @JCSTeh

**Comment by leonardder** [comment] 2018-02-23 16:21
After discussing this with Mick, it has been decided not to fix this in 2018.1. This is not an issue caused by the new Hims driver, however it might be the case that the new driver, due to the native way of interfacing with bluetooth devices, makes this issue more prevalent than it was before.

It will be fixed as part of braille display auto detection (#1271, #7741).

**Closed** 2018-07-17 06:57 UTC
Labels: Braille, Configuration profiles, performance
