### ISSUE TITLE
SAPI4 crashes in alpha-21882,528d5708

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#12152] opened 2021-03-11 11:18 UTC
### Steps to reproduce:
1. Install SAPI4 along with a synthesizer. The SAPI4 runtimes can be found at http://web.archive.org/web/20150910165037/http://activex.microsoft.com/activex/controls/sapi/spchapi.exe, and a free and legal synthesizer can be found at http://web.archive.org/web/20150910005021if_/http://activex.microsoft.com/activex/controls/agent2/tv_enua.exe.
2. Load sapi4.
### Actual behavior:
The synthesizer loads, but NVDA crashes soon after.
### Expected behavior:
No Crash.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
alpha-21882,528d5708
#### Windows version:
Windows 10, Build 21327.
#### Name and version of other software in use when reproducing the issue:
N/A.
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, alpha-21877,8e4b189b works normally.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by lukaszgo1** [comment] 2021-03-11 12:21
Confirmed on my machine. Log is as follows:

```

ERROR - queueHandler.flushQueue (13:16:42.587) - MainThread (5676):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 146, in cancelSpeech
  File "speech\manager.pyc", line 767, in cancel
  File "synthDrivers\sapi4.pyc", line 123, in cancel
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
OSError: exception: access violation reading 0x8BF0558B
CRITICAL - watchdog._crashHandler (13:16:42.957) - MainThread (5676):
NVDA crashed! Minidump written to C:\Users\Lukasz\AppData\Local\Temp\nvda.log\..\nvda_crash.dmp
INFO - watchdog._crashHandler (13:16:43.937) - MainThread (5676):
Listing stacks for Python threads:
Python stack for thread 5968 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x0709BDB8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 932, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 558, in wait
  File "threading.pyc", line 302, in wait

Python stack for thread 5504 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 932, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 112, in _watcher
  File "winKernel.pyc", line 204, in waitForSingleObject

Python stack for thread 6536 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 932, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 5348 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 932, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 329, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 302, in wait

Python stack for thread 5600 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 932, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2193, in func

Python stack for thread 5676 (MainThread):
  File "nvda.pyw", line 264, in <module>
  File "core.pyc", line 567, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "watchdog.pyc", line 213, in _crashHandler
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

INFO - watchdog._crashHandler (13:16:43.937) - MainThread (5676):
Restarting due to crash

```

[Dump file](https://github.com/nvaccess/nvda/files/6122890/nvda_crash.zip)

**Comment by leonardder** [comment] 2021-03-11 17:10
Can this be reproduced with the build from https://github.com/nvaccess/nvda/pull/12155 ?

**Comment by leonardder** [comment] 2021-03-11 17:12
Can this be reproduced with the build from https://github.com/nvaccess/nvda/pull/12155 ?

**Comment by Mohamed00** [comment] 2021-03-11 18:04
Yes, I can still reproduce it in that try build.

**Comment by lukaszgo1** [comment] 2021-03-11 18:10
I can confirm it is still reproducible with the build from #12155 There is a difference however - the build from #12155 does not provide any logging whatsoever after switching to SAPI4 and just crashes, whereas with ComTypes 1.1.7 I was able to get the log from my comment above.

**Comment by Mohamed00** [comment] 2021-03-27 14:46
This is still happening as of alpha-22160,656ecb5f. Interestingly, it turns out that SAPI4 technically loads normally, however it only crashes when it actually speaks something. For example, if you load SAPI4 with speech off, it works fine, however if you change speech modes, which causes something to be spoken, it crashes.

**Comment by zstanecic** [comment] 2021-03-30 10:06
Hi to all!
Log of the sapi4 synth using the latest alpha and NVDA.
Note that even with addons disabled, sapi4 makes problems and the remote addon logs are not there
INFO - synthDriverHandler.setSynth (12:03:16.400) - MainThread (6484):
Loaded synthDriver sapi4
ERROR - eventHandler.executeEvent (12:03:16.894) - MainThread (6484):
error executing event: gainFocus on <NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at 0x074F78C8> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
INFO - braille.BrailleHandler.setDisplayByName (12:03:16.961) - braille._BgThread (8284):
Loaded braille display driver noBraille, current display has 0 cells.
ERROR - queueHandler.flushQueue (12:03:19.266) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - eventHandler.executeEvent (12:03:21.254) - MainThread (6484):
error executing event: focusEntered on <NVDAObjects.Dynamic_NvdaDialogEmptyDescriptionNvdaDialogDialogIAccessibleWindowNVDAObject object at 0x0597BC88> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1131, in event_focusEntered
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:21.845) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - eventHandler.executeEvent (12:03:22.986) - MainThread (6484):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x04986AA8> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 105, in next
  File "appModules\nvda.pyc", line 86, in event_gainFocus
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:23.403) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - eventHandler.executeEvent (12:03:25.495) - MainThread (6484):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x04981B80> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 105, in next
  File "appModules\nvda.pyc", line 86, in event_gainFocus
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:26.242) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - eventHandler.executeEvent (12:03:26.287) - MainThread (6484):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x04981C10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 105, in next
  File "appModules\nvda.pyc", line 86, in event_gainFocus
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
INFO - braille.BrailleHandler.setDisplayByName (12:03:26.428) - braille._BgThread (8284):
Loaded braille display driver noBraille, current display has 0 cells.
ERROR - queueHandler.flushQueue (12:03:27.051) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - eventHandler.executeEvent (12:03:27.102) - MainThread (6484):
error executing event: focusEntered on <NVDAObjects.IAccessible.Groupbox object at 0x04986DD8> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1131, in event_focusEntered
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:27.466) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x051973F8
ERROR - unhandled exception (12:03:28.371) - MainThread (6484):
wx._core.wxAssertionError: C++ assertion ""GetWindow() != 0"" failed at ..\..\src\common\wincmn.cpp(3919) in wxWindowAccessible::GetDescription(): 

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
ERROR - eventHandler.executeEvent (12:03:28.750) - MainThread (6484):
error executing event: focusEntered on <NVDAObjects.Dynamic_DialogIAccessibleWindowNVDAObject object at 0x05926BF8> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1131, in event_focusEntered
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:30.239) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x08EC1170
ERROR - eventHandler.executeEvent (12:03:31.111) - MainThread (6484):
error executing event: focusEntered on <NVDAObjects.Dynamic_NvdaDialogDialogIAccessibleWindowNVDAObject object at 0x04986D30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\__init__.pyc", line 1131, in event_focusEntered
  File "speech\__init__.pyc", line 455, in speakObject
  File "speech\__init__.pyc", line 756, in speak
  File "speech\manager.pyc", line 264, in speak
  File "speech\manager.pyc", line 421, in _pushNextSpeech
  File "synthDrivers\sapi4.pyc", line 121, in speak
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x00015880
ERROR - queueHandler.flushQueue (12:03:31.728) - MainThread (6484):
Error in func cancelSpeech
Traceback (most recent call last):
  File "queueHandler.pyc", line 55, in flushQueue
  File "speech\__init__.pyc", line 127, in cancelSpeech
  File "speech\manager.pyc", line 749, in cancel
  File "synthDrivers\sapi4.pyc", line 124, in cancel
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: exception: access violation writing 0x08EC1170
INFO - synthDrivers.espeak.SynthDriver.__init__ (12:03:32.093) - MainThread (6484):
Using eSpeak NG version 1.51-dev
INFO - synthDriverHandler.setSynth (12:03:32.238) - MainThread (6484):
Loaded synthDriver espeak
ERROR - unhandled exception (12:03:32.312) - MainThread (6484):
Traceback (most recent call last):
  File "wx\core.pyc", line 3407, in <lambda>
  File "gui\settingsDialogs.pyc", line 1392, in refreshGui
RuntimeError: wrapped C/C++ object of type BoxSizer has been deleted
INFO - braille.BrailleHandler.setDisplayByName (12:03:33.836) - braille._BgThread (8284):
Loaded braille display driver noBraille, current display has 0 cells.
The synthesizer used was syntalk 1..6/

**Comment by zstanecic** [comment] 2021-03-30 10:08
All in all, spi  4 liads, but without speech.

**Comment by cary-rowen** [comment] 2021-03-30 12:03
The latest Alpha version can still be reproduced

**Comment by lukaszgo1** [comment] 2021-04-09 09:17
cc @michaelDCurran Would you be able to look into this? At the very least this should be added to 2021.1 milestone.

**Comment by zstanecic** [comment] 2021-04-09 09:28
This should be added to the 21.1 milestone, as some users will refuse to upgrade to the new version, especiallz those using sapi4 sznths.

**Comment by michaelDCurran** [comment] 2021-04-12 07:48
I have managed to create a minimal testcase outside of NVDA which reproduces the issue.
It seems as though the stack becomes corrupted as the call to our ITTSBufNotifySynk's TextDataStarted method completes, and control goes back to the SAPI4 engine. Then as that function in the engine returns, it jumps to an invalid address.
I can trace the calls through Python and Windows code, but for the engine itself there are probably no debugging symbols available. The engine linked on this issue is very very old.
I can confirm however that this crash only occurs in Python 3.8 and not 3.7. 
It may have something to do with Python 3.8's new vectorcall calling convention, or perhaps a bug in the upgraded libffi library, or even perhaps this ctypes bug:
https://bugs.python.org/issue41021
I don't think that this is something we can work around in NVDA itself. And therefore, the only options currently are either to stay on Python 3.7, or remove the SAPI4 driver from NVDA (it is a very old technology).
But, before we take any drastic action: it would be really helpful if someone can point me to where I can still get the SAPI4 sdk? I had it many years back, but can't find it now. I need the header files in there to verify that our definition of the interfaces are absolutely correct. It is possible that there was a mistake, but it just happened to work up to now. 
Also, can this issue be reproduced with another engine other than the one linked on this issue? and if so, is there any way I can get access to test another one that causes the issue? I really need to rule out this is not just a bug in the TrueVoice engine itself.

**Comment by cary-rowen** [comment] 2021-04-12 10:09
I will share another engine to help you troubleshoot problems. Although this is a very old technology, there are still many people using it:
If the installation interface is in Chinese, then you only need to press Alt + Y to complete the installation.
I tested that NVDA2020.4 can work with this engine.
But the latest Alpha cannot work with this engine.
https://www.dropbox.com/s/3njaa8jrplutk24/IBM_ViaVoice_TTS_Runtime-V6.405.exe?dl=0

**Comment by lukaszgo1** [comment] 2021-04-12 10:23
@michaelDCurran  SAPI 4 SDK can be downloaded from: http://grossgang.com/tts/sapi_voices/SAPI4SDK.exe
I don't think this crash is engine specific I've reproduced it with a commercial Polish synth. Its demo can be downloaded from: http://speak3.altix.pl/demo/SpeakDemo.exe though I'm not sure about limitations of the demo version.
Another alternative would be to reimplement SAPI 4 support in a different language C, C++ and interface with the dll from Python right?


How popular SAPI4 really is amongst our users - I believe we have stats for that?

Also there are two other issues which seems to be related i.e. invalid memory after COM call #12254 and #12154 both probably introduced by Python 3.8.

**Comment by michaelDCurran** [comment] 2021-04-12 22:59
Another possibly related cPython issue: https://bugs.python.org/issue38748

**Comment by zstanecic** [comment] 2021-04-13 04:29
Note: if this cannot be fixed, it will be better to remove this and let people tell that synths are unsupported, discontinued and no longer developed. The good example is the speak3 synthesizer which Łukasz mentioned. The demo version of this synth is no longer updated, and this version is from the year 2013. Altix sells this stills, but it is not actively developed. 
Another popular sapi4 synth among polish users is syntalk, which is no longer developed, but it is accurate for polish language in such a way, that there is no misinterpretation of the spoken text,.
There is no demo version, but installation files are available on the net, even on the grossgang website mentioned here.
hint: filename st16sapi.exe
another synthesizer which is used, but this time in croatia, serbia and former Yugoslav republics except slovenia is WinTalker voice, produced and no longer maintained by rosasoft. 
What i propose for now is to remove sapi4 completely, and tel users to use external solution. 
As i know, speech hub by Isaac Porat supports the sapi4 driver.

**Comment by leonardder** [comment] 2021-04-13 05:39
> The only options currently are either to stay on Python 3.7, or remove the SAPI4 driver from NVDA (it is a very old technology).

I'd be curious to know how it behaves on Python 3.9. Would you be able to share your test case?

**Comment by michaelDCurran** [comment] 2021-04-13 07:42
My minimal testcase also crashes in Python 3.9.
This is looking more and more like stack corruption in the libFFI library, which is used by ctypes.
If this is causing problems for SAPI4, it may be causing problems in other places. Probably anywhere where a Python callback is called from outside of Python, though the particular calling convention may affect things.
This may be also what is making UI Automation unstable on Windows Server 2012: #12154 
 Here is my minimal testcase: 
[sapi4crash.zip](https://github.com/nvaccess/nvda/files/6301983/sapi4crash.zip)

Set up a Python virtual environment with comtypes 1.1.8 installed.
Run sapi4_bad.py
and then
sapi4_good.py
Under Python 3.7 they both run fine.
Under Python 3.8 and 3.9 sapi4_bad.py throws an OSError. 
sapi4_good.py uses sapi4helper.dll, see sapi4helper.cpp, which is a wrapper around the call to ITTSCentral::TextData, which takes a Python callback to receive the bookmarks, rather than Python implementing a full ITTSBufNotifySink. Its calling convention is also cdecl, not STDCALL.
I have also successfully modified NVDA's sapi4 driver to use sapi4helper.dll and the crash goes away.
However, as I have said above, I am not at all convinced this ps the fault of, or specific to, sapi4. I think this ia a huge flaw in libFFI / Python 3.8+ and could be causing other instabilities.

**Comment by zstanecic** [comment] 2021-04-13 08:00
So, as i see we are not going to downgrade python?

Is there any fix in the comtypes master branch for this?

**Comment by michaelDCurran** [comment] 2021-04-13 08:16
Downgrading Python is not out of the question yet. But a bit more research is still required.

**Comment by michaelDCurran** [comment] 2021-04-14 18:50
I have commented on the existing Python issue: https://bugs.python.org/issue38748 and attached another minimal testcase, which I have now gotten down to a __stdcall Python callback that takes a long and a long long.

**Comment by michaelDCurran** [comment] 2021-04-15 10:34
I have made a try build of NVDA downgraded to Python 3.7, but otherwise identical to NVDA master at the time of this comment:
https://ci.appveyor.com/api/buildjobs/9j0yrsjmphluhd9n/artifacts/output%2Fnvda_snapshot_try-py37-22369%2C439dc27a.exe
Please test the SAPI4 synthDriver in this build and report if SAPI4 is again working for you. It seems to be working well for me.

**Comment by zstanecic** [comment] 2021-04-15 10:46
Hi,

It works.

But is there any way to make sapi4 work on py 3.8?

I am afraid that in the future we will need to drop this, or there will be a problem.

**Comment by michaelDCurran** [comment] 2021-04-15 11:12
There is a very serious bug in Python 3.8+ which causes stack corruption 
on certain Python callbacks via ctypes.

that bug must be fixed in Python / LibFFI to ensure NVDA's stability.

**Comment by zstanecic** [comment] 2021-04-15 11:19
Where this issue can be followed?

**Comment by michaelDCurran** [comment] 2021-04-15 11:20
https://bugs.python.org/issue38748

**Comment by zstanecic** [comment] 2021-04-15 11:22
What can be done in the meantime to fix this?

Are our backwards compatibility changes safe?

**Comment by michaelDCurran** [comment] 2021-04-15 11:39
Depending on the results that come from people testing this try build as 
I have requested here and on another issue, I may soon create a pr to 
downgrade to Python 3.7.

The only PRs that needed to be reverted were:

* Updating brlAPI to a Python 3.8 build

* Switching to using Python's own pgettext

* calling os.add_dll_directory when loading liblouis.


None of these PRs have any user visible changes.


The rest of the Python 3.8 work, including the switch to a virtual 
environment etc is all compatible with Python 3.7 and can remain.


Obviously we do want to upgrade to Python 3.8+ as soon as we can, but 
this would be currently irresponsible as we now know this includes a 
very serious stack corruption bug which could be affecting much more 
than just SAPI4.

**Comment by lukaszgo1** [comment] 2021-04-15 13:01
I can also confirm SAPI 4 works for me with this try build.

**Comment by cary-rowen** [comment] 2021-04-15 13:52
Yes, this internal version can continue to use the SAPI4 synthesizer
@michaelDCurran

**Comment by Mohamed00** [comment] 2021-04-15 18:25
Also confirmed, I can no longer reproduce the SAPI4 crash in this build.

**Closed** 2021-04-20 04:19 UTC

**Comment by leonardder** [comment] 2021-04-28 16:05
@michaelDCurran It turns out that https://bugs.python.org/issue38748 contains a question for a small unit test. I guess that can help in fixing the bug when provided.

**Comment by michaelDCurran** [comment] 2021-04-28 23:37
Yep saw that. I'll look into that after NVDA 2021.1 is released if the 
other person on the issue has not got to it first.
