### ISSUE TITLE
Down Arrow Key in NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4947] opened 2015-02-25 07:39 UTC
**Reported by reach2akram on 2015-02-25 07:39**
I am using NVDA to test my application, when I am navigating the page using down arrow its reading line by line. I think this is the known behavior of NVDA.

I encountered the below situation.
## Original Text shown on Page :

A triangle with two sides equal in length. Because of this it has an axis of symmetry. The angle that intersects the axis of symmetry is called the apex angle. The other two angles are called the base angles. The base angles have the same size.  Check this material resource
## '''Quadratic Functions and Models Synchronous Session Whiteboard (WBD)''' 

Text 'Quadratic Functions and Models Synchronous Session Whiteboard (WBD) ' is a link.
1. Now start reading the Content using the down arrow.
2. When Screen reader reached at the below content it reads it like -

The base angles have the same size.  Check this material resource 
link
Quadratic Functions 
link
and Models Synchronous Session Whiteboard (WBD)

So in this way it looks like to a Blind person that there are two links.

Please suggest me that how can I overcome with this situation.

Hope I am able to explain my problem.

Screen shot attached of the speech viewer.

**Comment by leonardder** [comment] 2017-07-28 17:32
Closing as duplicate of #374.

**Closed by leonardder** 2017-07-28 17:32 UTC
Labels: task
