### ISSUE TITLE
Outlook: Unneeded text for flagged messages

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11937] opened 2020-12-13 11:06 UTC
### Steps to reproduce:

Tested with both Outlook 2010 and 2016; I'm unsure whether this can also be reproduced in later versions.

1. Find any message, right-click it, choose "Follow Up" and then select one of the available options

2. Navigate back to the message

### Actual behavior:

NVDA outputs the text "flag status red flag" before then announcing the remainder of the message info

### Expected behavior:

To cut out some unneeded output, NVDA could just say the words "red flag" before the message.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.3

#### Windows version:

10

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes

**Comment by Adriani90** [comment] 2023-04-18 14:21
This is not reproducible with Outlook 2016 or newer, both with UIA enabled or disabled. Tested with NVDA 2022.3 and 2023.1. Closing as works for me.

**Closed by Adriani90** 2023-04-18 14:21 UTC
Labels: close/worksforme
