### ISSUE TITLE
Bug using routing cursor in latest alpha

### ISSUE THREAD

**Issue by Oreonan** [nvaccess/nvda#12010] opened 2021-01-23 17:17 UTC
### Steps to reproduce:
- Select a text (for example in a text editor)
- Try to move cursor in a cell using routing cursor on braille display

### Actual behavior:
- Cursor doesn't move, and selection is still present

### Expected behavior:
- Moving cursor to cell and deselect text

#### NVDA installed/portable/running from source:
- Installed

#### NVDA version:
- alpha-21668,e8f14f9a

#### Windows version:
- 10.0.19042.746

#### Name and version of other software in use when reproducing the issue:
- Notepad for example

#### Does the issue still occur after restarting your computer?
- Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- No

#### If addons are disabled, is your problem still occuring?
- Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
- No

**Comment by CyrilleB79** [comment] 2021-01-23 20:26
Regarding routing cursors, #11922 was merged quite recently.
@JulienCochuyt may this be related?

@Oreonan (or anyone else able to reproduce), would you be able to test on source code the following commits:
* code based on commit 5daf693f3aae504c414b3b62a7f651af929952aa: the build just before #11922 was merged
* code based on commit 33cd507817fbefbc0d1c46db13ea8768cde00c25: first build including #11922

I do not have any braille display here at home to try to reproduce.

**Comment by Oreonan** [comment] 2021-02-04 20:58
Yes, I think it's this PR who cause problems.

**Comment by lukaszgo1** [comment] 2021-02-15 16:42
Confirmed as a regression from #11922. The following is in the log  after pressing a routing button:

ERROR - scriptHandler.executeScript (17:41:20.708) - MainThread (3856):
error executing script: <bound method GlobalCommands.script_braille_routeTo of <globalCommands.GlobalCommands object at 0x05445050>> with gesture 'routing'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "globalCommands.pyc", line 2735, in script_braille_routeTo
  File "braille.pyc", line 1852, in routeTo
  File "braille.pyc", line 1449, in routeTo
  File "braille.pyc", line 1095, in routeTo
  File "braille.pyc", line 1069, in getTextInfoForBraillePos
TypeError: list indices must be integers or slices, not NoneType


cc @JulienCochuyt

**Comment by bramd** [comment] 2021-02-18 15:02
Another, hard to reproduce, bug that might be related is the cursor routing in textareas on Chromium-based browsers. In many textareas pressing a routing button routes to the wrong location within that textarea. Usually a few lines above where the cursor should route.

**Comment by CyrilleB79** [comment] 2021-03-19 08:10
@feerrenrut, @seanbudd, would you consider labeling this issue for NVDA 2021.1, since it is a regression in current alpha stage (already present befor py38)?
Thanks.

**Comment by MarcoZehe** [comment] 2021-03-19 08:17
I can also confirm both routing key problems, that in NotePad and that in Chromium-based browsers.

**Comment by MichelSuch** [comment] 2021-03-19 08:17
I would add that this is a very annoying problem.




Michel Such ***@***.***>
------------------------------------------------------------------------
Expert NVDA certifié 2019
Le 19/03/2021 à 09:11, Cyrille Bougot a écrit :

**Comment by feerrenrut** [comment] 2021-03-22 05:37
I can reproduce this issue with the braille viewer and notepad.exe, using the hover mouse to route option.

**Closed** 2021-03-23 08:36 UTC

**Comment by bramd** [comment] 2021-04-11 22:33
@feerrenrut I would like to reopen this, since a specific issue in textareas seems still be present.

STR:
1. Use Chrome/Chromium based Edge
2. Open `data:text/html,<textarea>foobarfoobarfoobarbazasdfasdfasdf%0Aasdfasdfasdf</textarea>`
3. Add a new line at the end of the textarea
4. Press routing somewhere in that line

Expected: routing moves cursor to clicked position
Actual: Cursor moves back to the first line

After some testing it seems to be specific to added text that was not initially there on page load. Also, when pressing routing again on a character where the cursor is, the cursor moves unexpectedly to another location in the text.

**Comment by MarcoZehe** [comment] 2021-04-12 04:55
Confirmed, this is still present for me also.

**Comment by feerrenrut** [comment] 2021-04-13 13:00
@bramd I'd prefer if a new issue. It may be independent and deserves the usual set of questions (from the template).

**Comment by CyrilleB79** [comment] 2021-04-17 20:47
@bramd, @MarcoZehe and @Oreonan:
Just a reminder: if you still experiment the issue described in https://github.com/nvaccess/nvda/issues/12010#issuecomment-817383795 and you want to have a chance for it to be fixed in 2021.1, you should open a new issue on this topic.
