### ISSUE TITLE
SayAll on long bits of text seems to fail randomly

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5339] opened 2015-09-09 15:19 UTC
**Reported by RichCaloggero on 2015-09-09 15:19**
Mostly experienced in Firefox on long bits of text like a full-length article. SayAll seems to either quit completely after a while, or randomly skip to previously read text and re-read it.

**Comment by ehollig** [comment] 2017-07-11 18:36
I am not able to replicate this.
Tested using SayAll using Firefox 54.0.1 (32-bit) on a Wikipedia article.
@jcsteh any ideas?

**Comment by ehollig** [comment] 2017-08-22 21:43
Duplicate of #1726

**Closed by ehollig** 2017-08-22 21:43 UTC
Labels: bug
