### ISSUE TITLE
Live Regions are Not Displayed in Braille

### ISSUE THREAD

**Issue by slannon97** [nvaccess/nvda#7756] opened 2017-11-14 08:32 UTC
When live region information on a web page changes, the new information is only spoken through speech. The Braille display does not update to show this information. I am using NVDA 2017.3 on Windows 10 build 16299.19. I'm using Chrome 62.0.3202.94. I also tested this in Internet Explorer 11 and receive the same result.

For an example, go to https://dequeuniversity.com/library/aria/content-feedback/liveregion-playground and set up a live region by checking the "use role defaults" radio button and the "every 5 seconds" radio button. Finally, press the submit button and observe that NVDA speaks changes but the Braille Display continues to show the line of text NVDA is focused on. It should do something such as displaying a flash message containing the updated information that is spoken.

**Comment by feerrenrut** [comment] 2017-11-15 10:15
@slannon97 could you please update the description to include instructions for how to demonstrate the problem, please include the URL to the web page you are using, and the name of the web browser you are using.

**Comment by slannon97** [comment] 2017-11-15 17:11
I've updated the description. Let me know if you need more information.

**Comment by leonardder** [comment] 2017-11-21 07:15
I belief this is intentional, but @jcsteh probably knows more. Anyhow, I think it's great if it would at least be possible to enable brailling of live regions. It should, however, be system or braille keyboard toggable and disabled by default.

The problem with live regions is that they need to be used carefully, and people tend not to do that. If we would braille them by default, it could be a huge distraction for the braille user, even for valid live region usage. Imagine that PuTTY or the windows command console would output everything inside a live region and the braille display is flashed for every single update to the region.

**Comment by leonardder** [comment] 2017-11-21 07:17
cc @dkager. Also, I'm sure @bramd has a valuable opinion about this.

**Comment by jcsteh** [comment] 2017-11-21 09:57
Yes, my reason for not brailling these was exactly that cases like the
Windows Command Console, PuTTY, etc. are totally valid use cases for lie
regions, and this would be hugely disruptive for braille. In cases where
there are frequent updates, it'd be impossible to review text because
messages would continually interrupt. (In contrast, polite live regions do
not interrupt speech. With braille, we can't do this because we have no way
of knowing when the user is finished working with the line currently on the
display.) This would be bad even for chat systems, which is a very common
use case for live regions.

**Comment by leonardder** [comment] 2017-11-21 14:22
Do the IA2 attributes expose whether a live region is polite or assertive? I think there are valid reasons to say that assertive live regions should be brailled by default. Still, given the behavior of the google docs live region, that seems to be an assertive one, and we really don't want to have everything brailled by default what that live region spits out.

Anyhow, a toggle for this would be great, but we must agree about the scope of such a toggle. There are also the UIA live regions in Windows 10, for example.

**Comment by jcsteh** [comment] 2017-11-21 20:39
The IA2 attributes do expose this, yes, and there's a UIA equivalent. Note that the IA2 live regions code currently doesn't communicate this to NVDA itself, but that needs to be fixed for multiple reasons.

**Comment by MarioBatusic** [comment] 2020-06-04 04:01
This is not a feature request but an issue. There are deaf-blind people and also us working in a team without using speach output, only braille diesplays.
#### Current status
This bug occurs still in Firefox 76.0.1 and in Google Chrome 83.0.4103.97.

**Comment by zersiax** [comment] 2021-03-28 17:21
Not sure if this is still being looked into at all, but I would say allowing this as a toggle, for live region information as well as, say, role=alert, should probably be considered. The gains for people not using speech for whatever reason would be quite substantial off the top of my head, but there's more use cases:

- Monitor things happening in Zoom and other applications through braille alone, allowing speech to be toggled off to not interrupt zoom meetings
- If subtitles use this mechanism to output to screenreaders, I have seen this in the wild on at least a few places, one could read them in braille while listening to the content without speech talking over it.

While it's true that having this be a default thing is probably not a good idea due to the reasons already mentioned in this thread, having it be a toggle for these use cases would be quite useful.

**Comment by feerrenrut** [comment] 2021-03-31 06:11
Yep, I think putting this behind a toggle is a good way to start experimenting with the UX for this. Happy to accept a PR if someone wants to work on this.

**Comment by ericdq** [comment] 2022-11-16 21:35
hello, I am a deaf blind user, fortunately I still have a hearing loss.
It would be very useful for me a switch or that by default is integrated in the braille output as it is done by the voice output.
It occurs to me that to make the messages disappear you could add the functionality that already exists to mute the voice when pressing the control key, that same press resets the dwell time of the alert, even if the option to permanently display the alert is selected.
I sincerely hope this can be fixed in future versions.

**Comment by stes-acc** [comment] 2023-06-17 08:13
It is all about the "how NOT to distract but inform" and not the "cant because users are distracted."

I could imagine of an additional symbol, a vibration or a defined dot animation on the braille display when live messages rush in that informs the user in an unobstrusive way, an internal buffer in braille driver to keep the message and to toggle to it as result of a designated braille hardware key press, keeping the other text in annother buffer and being able to switch back to that any time.

The problem is you may need first industry-wide spec for this, otherwise we experience different implementations.

**Closed** 2023-07-06 02:16 UTC
Labels: component/braille, audience/hearing-impaired, component/braille-ux
