### ISSUE TITLE
nvda returns to navegation mode when the list of address suggestions appears in gmail.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8112] opened 2018-03-22 14:04 UTC
### Steps to reproduce:
In nvda disable the option
Autofocus mode when focus changes
Open a new message in gmail using default view mode.
enter the first letter of the desired e-mail in the To field.
Now try typing the second letter.

### Expected behavior:
The next characters after the first should be entered normally.

### Actual behavior:
The next characters are not typed and nvda informs not supported in this document if the letter you pressed is not used by nvda.
Stop when the nvda exits the focus mode and goes to the navigation mode.
Also note that this occurs because the list of suggested addresses appear on the page.
This happens soon when trying to type the email, if when nvda returns to the navigation mode press nvda + space to force the nvda go to the focus mode the behavior is normalized and the other characters are typed normally.

### System configuration:
NVDA version:
next 14952

NVDA Installed or portable:
instaled
Other information:
This also occurs in google gsuite's corporate email.

Windows version:
windows 7

Name and version of other software in use when reproducing the issue:
chrome 65 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment] 2019-04-03 22:47
@fernando-jose-silva Could you please test with NVDA 2019.1 and Chrome 73? Can you still see this issue? I cannot reproduce it.

**Comment by fernando-jose-silva** [comment] 2019-04-04 01:18
Strange, I took the test now and I was able to replicate the problem again.
Open a new message in gmail.
In the field, press enter.
type a letter in case I typed s.
Now automatically the nvda went out of focus mode and went to Browse mode.
Hope the nvda continued in focus mode.
The automatic switching between focus mode and nvda Browse is disabled.
nvda alfa 16976
chrome 73
thank you.

**Comment by fernando-jose-silva** [comment] 2019-04-04 01:19
log:
[gmail.txt](https://github.com/nvaccess/nvda/files/3041307/gmail.txt)

**Comment by Adriani90** [comment] 2019-05-06 17:32
Closing as duplicate of #8211. The errors in the logs suggest quite the same.

**Closed by Adriani90** 2019-05-06 17:32 UTC
Labels: duplicate
