### ISSUE TITLE
NVDA menu disapears if a Nuance TTS is installed

### ISSUE THREAD

**Issue by nozem79** [nvaccess/nvda#11916] opened 2020-12-07 19:41 UTC
The menu disapears if I have a Nuance TTS being used, the only way to get the manu again I have to remove/rename nvda.ini ..

**Comment by Adriani90** [comment] 2020-12-07 21:58
Cc: @michaelDCurran

**Comment by nozem79** [comment] 2020-12-08 08:48
if needed I can send the voice I'm using, to replicate the issue.

**Comment by nozem79** [comment] 2021-01-21 08:05
I checked it with another Nuance voice from another source & the issue is also there.
That's too bad, Nuance voices are really the best ;-)

**Comment by ruifontes** [comment] 2021-01-21 16:27
Excuse me, but please justify your statement...


Many users are using Vocalizer voices from Tiflotecnia without any 
problem opening the NVDA menu!

So, please, if you have any prblem with our Vocalizer voices, contact us 
through our support e-mail, tiflotecnia@tiflotecnia.com



Rui Fontes

Tiflotecnia, Lda.



Às 08:06 de 21/01/2021, nozem79 escreveu:

**Comment by nozem79** [comment] 2021-01-22 07:48
Well, I used to voices from Claro & Harposoftware, both have the same issue, I did not install or used Tiflotecnia voices.

**Comment by nozem79** [comment] 2021-01-22 07:50
Your voices are only for NVDA, the 'normal' install way of Nuance vocies are more general.

**Comment by CyrilleB79** [comment] 2021-01-22 08:40
@nozem79, unfortunately you did not use the [bug report](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=bug_report.md) in this issue.
Could you provide the missing information in order to get a better chance to have this issue considered and worked on? Especially:
* steps to reproduce the issue
* NVDA version
* Test on earlier versions and result
* Tested without add-ons?
Thanks.

**Comment by nozem79** [comment] 2021-01-22 08:54
Just did :-)

**Comment by nozem79** [comment] 2021-01-27 18:50
The issue is that when a Nuance voice like Claroread or Harposoftware Nuance voices are being used, the options menu disapears, the only way to get it back is to delete the nvda.ini file from \roaming\nvda\ .
After that the 'regular' voices will be used again and the menu is usable again.

    I repreduces this on three diffet laptops - Windows 10 (1809 - 20H2)
    I found this issue with NVDA 2020.3 (I saw this issue earlier in older versions)
    There where no add-ons installed with all tests

I dot not use the shortcuts, , nut now I used a Nuance voice again & my menu is 'losed' again, does also not work with a shotcut (so I lose my settings again) 

For Tiflotecnia: The drivers do not work for NVDA newer than 2019, so those TTS's do not work at all.

**Comment by ruifontes** [comment] 2021-01-27 19:14
Our Vocalizer is already compatible with NVDA 2020.3.

Driver at:

https://www.tiflotecnia.net/Instal/vocalizer_expressive_driver-3.1.2.nvda-addon



Best regards,


Rui Fontes

Tiflotecnia, Lda.


Às 18:50 de 27/01/2021, nozem79 escreveu:

**Comment by CyrilleB79** [comment] 2021-01-27 20:10
@nozem79  wrote:
> The issue is that when a Nuance voice like Claroread or Harposoftware Nuance voices are being used, the options menu disapears, the only way to get it back is to delete the nvda.ini file from \roaming\nvda\ .
> After that the 'regular' voices will be used again and the menu is usable again.

Which option menu are you speaking of? I cannot see any item called "Option" in NVDA menu. Are you speaking of NVDA menu itself?

**Comment by nozem79** [comment] 2021-01-27 21:39
Yes, the NVDA menu indeed, the only way to get it back is to delete nvda.ini (or put a backup of the ini file back)

**Comment by CyrilleB79** [comment] 2021-01-27 23:00
Could you perform the following steps:
* Press NVDA+Q, select the item to restart in debug mode
* When NVDA has restarted, change your synthesizer to Nuance
* press NVDA+N; according to your description, you should not have NVDA menu at this time
* press NVDA+F1 to open the log
* Press control+S and save your log somewhere
* Attach your log file to this issue.
Thanks.

**Comment by CyrilleB79** [comment] 2022-11-28 16:31
@nozem79 are you still experimenting the issue?
If yes, could you provide the log? And describe more precisely the steps you are executing as asked in https://github.com/nvaccess/nvda/issues/11916#issuecomment-768634533?

**Comment by nozem79** [comment] 2022-11-29 08:48
Hi, after the latest update I cannot reproduce the issue :-) (I'm a bit slow, I use other software, so no NVDA anymore)

**Comment by CyrilleB79** [comment] 2022-11-29 09:47
Thanks for the update.

Just for curiosity (and to keep a trace), which update solved the issue? NVDA update or Nuance TTS update?

Anyway, since the issue seems to be resolved and since you do not experiment the problem anymore, I'd suggest you to close this issue. In the future, if you or someone else face the same issue, we can always reopen this issue or open a new one with more up-to-date information.
Thanks.

**Closed** 2022-11-29 21:31 UTC

**Comment by nozem79** [comment] 2022-11-30 14:33
Hi, It was fixed with NVDA 2022.3.2 (maybe before, rightnow I use Claroread & the accessaillity from MacOS)
