### ISSUE TITLE
many addons have been disabled after updating to snapshot Version: alpha-22782,7e6561a0 U

### ISSUE THREAD

**Issue by shadyar** [nvaccess/nvda#12426] opened 2021-05-17 21:00 UTC
### Steps to reproduce:
  After updating
  ### Actual behavior:
  addon(s) do not work as well as their settings have been omitted from NVDA preferences.
  ### Expected behavior:
  I can use addon like instantTranslate-4.4.1 or quickDictionary-2.1.2-dev
  ### System configuration
  #### NVDA installed/portable/running from source:
  NVDA installed
  #### NVDA version:
  alpha-22782,7e6561a0 U
  #### Windows version:
  Windows 10 64-bit the last version. (up to date)
  #### Name and version of other software in use when reproducing the issue:
  
  #### Other information about your system:
  Laptop 8GB of RAM, processor: coreI7 64-bit
  ### Other questions
  #### Does the issue still occur after restarting your computer?
  yes it does.
  #### Have you tried any other versions of NVDA? If so, please report their behaviors.
  earlier snapshot versions before around May 14th 2021 worked well.
  #### If add-ons are disabled, is your problem still occurring?
  N/A
  #### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
  N/A

**Comment by zstanecic** [comment] 2021-05-17 22:15
This is the api compatibility breaking release. Please contact add-on authors to make these compatible.

 

From: shadyar ***@***.***> 
Sent: Monday, May 17, 2021 11:01 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] many addons have been disabled after updating to snapshot Version: alpha-22782,7e6561a0 U (#12426)

 


Steps to reproduce:


After updating


Actual behavior:


addon(s) do not work as well as their settings have been omitted from NVDA preferences.


Expected behavior:


I can use addon like instantTranslate-4.4.1 or quickDictionary-2.1.2-dev


System configuration


NVDA installed/portable/running from source:


NVDA installed


NVDA version:


alpha-22782,7e6561a0 U


Windows version:


Windows 10 64-bit the last version. (up to date)


Name and version of other software in use when reproducing the issue:


Other information about your system:


Laptop 8GB of RAM, processor: coreI7 64-bit


Other questions


Does the issue still occur after restarting your computer?


yes it does.


Have you tried any other versions of NVDA? If so, please report their behaviors.


earlier snapshot versions before around May 14th 2021 worked well.


If add-ons are disabled, is your problem still occurring?


N/A


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


N/A

**Comment by shadyar** [comment] 2021-05-18 04:59
Not only do those  two addons but also a large number of addons, have been disabled. I mentioned to those as few samples.

**Comment by josephsl** [comment] 2021-05-18 08:57
Hi,

The add-ons community is aware of add-ons that will break in upcoming NVDA 2021.1 (see the above note as to why), and the good news is that folks are preparing their add-ons accordingly. Once NvDA 2021.1 beta 1 is released, a message will be sent throughout the add-ons community, asking add-on developers to prepare add-on releases with 2021.1 support.

As for my add-ons, rest assured that I am keeping an eye on NVDA 2021.1 development, and do plan to release compatible versions of my add-ons shortly after beta 1 is released.

Thanks.

**Comment by CyrilleB79** [comment] 2021-05-18 09:16
Note also that the fact that many add-ons have become incompatible with last alpha is due to changes in the `speech` module that is widely used across add-ons.
In any case, it's up to add-on authors to fix these compatibility issues as explained above.
So please, if everything is clarified for you, you can close this issue. Thanks.

**Comment by feerrenrut** [comment] 2021-05-19 08:54
Alpha versions of NVDA may be unstable. It is recommended to have a backup release available when using the alpha. 

Thanks for pointing out that many addon's are broken, this is expected. Add-ons will have to be updated in order to work with the 2021.1 release of NVDA.

I'm going to close this issue.

**Closed by feerrenrut** 2021-05-19 08:54 UTC
