### ISSUE TITLE
table commands do not working in firefox with multiprocess enabled

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7558] opened 2017-09-02 12:26 UTC
NVDA has a problem in a tables, with firefox when multiprocess function was enabled, 
the problem, which is described below, does not exist, when multiprocess is disabled.

### Steps to reproduce:

1. enable multiprocess in firefox - possibly you would enforce it
2. restart the firefox
3. go to page with table such as gmail in basic html view
4. press t to go to the table
5. press ctrl+alt+downArrow

### Expected behavior:

table commands should work, as expected and documented in UserGuide so the focus must be moved to next row when I pressed ctrl+alt+downArrow

### Actual behavior:

NVDA says "edge of the table" when I pressed ctrl+alt+down

### System configuration:
NVDA version:
last next (14373...)
NVDA Installed or portable:
installed
Other information:

tested with x64 firefox, because it seems in a 32-bit firefox I cannot enforce a multiprocess

Windows version:
w10 (1703) with latest updates

Name and version of other software in use when reproducing the issue:
firefox x64 55.0.3

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
not yet.

**Comment by zahra21** [comment] 2017-09-12 16:31
hi.
i tried to fource multiprocess in firefox 32bit.

but anything did not work for me!

sometimes firefox became unresponsive, also brows mode and using any arrow keys did not work!

i could only hear the title of page using nvda tab.

**Comment by Adriani90** [comment] 2018-11-20 07:52
@gregjozk is this issue still reproducible with last Firefox and last NVDA Alpha?
cc: @jcsteh

**Comment by jcsteh** [comment] 2018-11-20 11:03
I'm closing this, as there have been massive changes to Firefox since this was reported. I cannot reproduce any issues regarding table navigation, nor are we aware of any current reports of such issues.

**Closed by jcsteh** 2018-11-20 11:03 UTC
Labels: Firefox
