### ISSUE TITLE
The capital letter change prompt should also be effective when selecting text

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12996] opened 2021-10-27 08:21 UTC
### Steps to reproduce:
1. Make the following settings in the voice settings panel:
- Capital pitch change percentage 30
- Say cap before capitals: checked
- Beep for capitals: checked
2. Press Win + R to type notepad to open the Notepad;
3. Type a word containing capital letters, such as "WiFi";
4. Press Ctrl + Home to go back to the beginning of the document;
5. Use the right arrow to navigate what you just typed: You will hear the pitch change as well as beep and voice prompts;
6. Press Ctrl + Home to go back to the beginning of the document;
7. Press and hold Shift and then press the right arrow to select the content you just typed.
### Actual behavior:
Only "selected" is reported when performing step (7).
### Expected behavior:
When the report "selected", the capital should also be reported, such as in step (5). 
windows's Narrator has this feature.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.2
#### Windows version:
Windows 10 21H1 (x64) build 19043.1288
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All versions of NVDA do not seem to have this feature
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment] 2022-02-09 01:32
@feerrenrut 
@seanbudd 
Hello, What do you think for this?

**Comment by CyrilleB79** [comment] 2023-11-22 10:28
Closing as duplicate of #4874.

**Closed by CyrilleB79** 2023-11-22 10:28 UTC
Labels: p4
