### ISSUE TITLE
ocr dont work in latest alpha

### ISSUE THREAD

**Issue by mjonsson1986** [nvaccess/nvda#15148] opened 2023-07-15 17:10 UTC
when you try to do ocr the error log says

ERROR - vision.visionHandler._getProvidersFromFileSystem (19:08:56.997) - MainThread (15564):
Error while importing vision enhancement provider module NVDAHighlighter
Traceback (most recent call last):
  File "vision\visionHandler.pyc", line 58, in _getProvidersFromFileSystem
  File "vision\visionHandler.pyc", line 36, in _getProviderClass
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 242, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - vision.visionHandler._getProvidersFromFileSystem (19:08:57.012) - MainThread (15564):
Error while importing vision enhancement provider module screenCurtain
Traceback (most recent call last):
  File "vision\visionHandler.pyc", line 58, in _getProvidersFromFileSystem
  File "vision\visionHandler.pyc", line 36, in _getProviderClass
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\screenCurtain.pyc", line 218, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - queueHandler.flushQueue (19:08:57.032) - MainThread (15564):
Error in func VisionHandler.postGuiInit
Traceback (most recent call last):
  File "queueHandler.pyc", line 64, in flushQueue
  File "vision\visionHandler.pyc", line 96, in postGuiInit
  File "vision\visionHandler.pyc", line 119, in _updateAllProvidersList
  File "vision\visionHandler.pyc", line 103, in _getBuiltInProviderIds
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 242, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
ERROR - scriptHandler.executeScript (19:09:10.693) - MainThread (15564):
error executing script: <bound method GlobalCommands.script_recognizeWithUwpOcr of <globalCommands.GlobalCommands object at 0x042DEA10>> with gesture 'NVDA+r'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "globalCommands.pyc", line 4066, in script_recognizeWithUwpOcr
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "visionEnhancementProviders\screenCurtain.pyc", line 218, in <module>
AttributeError: module 'gui' has no attribute 'AutoSettingsMixin'
it worked fine before this alpha version

**Comment by seanbudd** [comment] 2023-07-16 23:48
Closing as duplicate of #15142

**Closed by seanbudd** 2023-07-16 23:48 UTC
