### ISSUE TITLE
Display a confirmation dialogue on activating the commands "Reset configuration to factory defaults" and "Revert to saved configuration"

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#16373] opened 2024-04-08 14:09 UTC
### Is your feature request related to a problem? Please describe.
Currently, after executing the "Reset configuration to factory defaults" command, it is carried out with no confirmation dialogue. This can be a problem if it was done accidentally, e.g. by pressing the wrong key while in the NVDA menu. This could be even more of an issue if someone quits NvA with the option "Save configuration when exiting NVDA" enabled, and has probably forgot or is unaware of it. They could then  inadvertently overwrite their settings they have spent years customising.
Slightly less of an issue is that the "Revert to saved configuration" command also has no confirmation dialogue 
### Describe the solution you'd like
For both commands, Display a dialogue asking the user if they're sure they want to proceed with yes and no buttons. Also, have no shortcut keys assigned to them by default.
### Describe alternatives you've considered
None.
### Additional context
I have heard of a user who activated "Reset configuration to factory defaults" by accident but luckilly realised and was able to use the revert option.

**Comment by XLTechie** [comment] 2024-04-08 14:48
> For both commands, Display a dialogue asking the user if they're sure they want to proceed with yes and no buttons. Also, have no shortcut keys assigned to
> them by default.

To the yes and no buttons?
Or to the reset functions themselves?

**Comment by XLTechie** [comment] 2024-04-08 15:01
So, @kara-louise, I've heard this request plenty of times before. Let me ask you 
something, concentrating on the Revert to saved settings option for a moment.

If a user does something that causes there to be no speech--lowers the NVDA 
volume to zero, goes into an unfamiliar speech mode, disables keyboard feedback, 
etc.
And they want to get out of this situation: what should they do?

If they press the shortcut keys to revert, they will hear no feedback, so can't 
hear the confirmation dialog. If you meant that there should be no shortcut 
keys, are you saying that they should have memorized the NVDA menu enough to 
reach this rarely used function without feedback, and then navigate the question 
dialog with no feedback?

**Comment by kara-louise** [comment] 2024-04-08 15:28
> To the yes and no buttons? Or to the reset functions themselves?
I meant the reset functions.

**Comment by kara-louise** [comment] 2024-04-08 15:29
regarding your second comment @XLTechie I didn't think of that issue. You're right, that  would be a problem.

**Comment by kara-louise** [comment] 2024-04-08 15:34
> dialog for reset to factory defaults is covered in #6648.

@Adriani90 I searched for Reset configuration to factory defaults before creating this issue but didn't see the one you mentioned. Any tips for searching for issues on here would be greatly appreciated since I seem to be creating a lot of duplicates recently.

**Comment by Adriani90** [comment] 2024-04-08 15:48
I use the in:title operator along with some of the strings I would add to the title.For example Is:Issue is:open in:title factoryled quite fast to that issue.Sometimes you have to perform searches multiple times with different combinations of key words.E.g.in:title revert settingsGives good results, but in:title settingsis too vague.I wrote a post in the nvda users mailing list some time ago about issues on Github but I cannot find it right now.Von meinem iPhone gesendetAm 08.04.2024 um 17:34 schrieb kara-louise ***@***.***>:﻿

dialog for reset to factory defaults is covered in #6648.

@Adriani90 I searched for Reset configuration to factory defaults before creating this issue but didn't see the one you mentioned. Any tips for searching for issues on here would be greatly appreciated since I seem to be creating a lot of duplicates recently.

**Comment by Adriani90** [comment] 2024-04-08 15:56
Sometimes you get more results and you have to read through some of them to be sure whether it is a duplicate or not.To scroll through titles faster you can use the vertical navigation, you must assign a key gesture for it. I assigned nvda+alt+ctrl+down and up arrow cause it is quite similar to table navigation. It‘s too bad that this is not assigned by default. Many users will be cut off from this great feature unless they discover the entry in the input gestures dialog or they read carefully the user guide.Von meinem iPhone gesendetAm 08.04.2024 um 17:34 schrieb kara-louise ***@***.***>:﻿

dialog for reset to factory defaults is covered in #6648.

@Adriani90 I searched for Reset configuration to factory defaults before creating this issue but didn't see the one you mentioned. Any tips for searching for issues on here would be greatly appreciated since I seem to be creating a lot of duplicates recently.

**Comment by kara-louise** [comment] 2024-04-08 16:06
Thanks for those tips @Adriani90.

**Comment by kara-louise** [comment] 2024-04-08 16:07
> regarding your second comment @XLTechie I didn't think of that issue. You're right, that would be a problem.
Or, have a command that just resets the volume.

**Comment by XLTechie** [comment] 2024-04-08 16:26
>       Or, have a command that just resets the volume.

The problem is, that is only one of lots of things that can go wrong which a 
revert can fix.

It's impossible for NVDA to know which one is wrong that you are revertingto 
solve--maybe you wanted to switch to speech mode off, or change your language to 
Hindy, and these aren't accidents.

**Comment by gerald-hartig** [comment] 2024-04-08 22:35
Closing as this is the desired behaviour.

**Closed by gerald-hartig** 2024-04-08 22:35 UTC
