### ISSUE TITLE
Suggestion, identify and inform the user that the link can only be opened with the use of the mouse.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7027] opened 2017-03-29 15:29 UTC
When analyzing the accessibility of the site:

Http://3remetodista.org.br/

I found some links that could only be opened by hovering the mouse over the navigation object with shift + nvda + m, and then clicking the left mouse button.
If you press enter on the link nothing happens.
I think this is a problem on the site, and I've already communicated the developers.
However I believe this problem is common in other sites.
For this I would suggest if it is technically possible for nvda to be able to identify that the link can only be opened with the mouse and pass this information to the user.
The justification is that the user of nvda can press enter on the link and when nothing happens believe that he can not open the link and give up doing the operation, being able to carry out the activity by clicking with the mouse on the link .
To reproduce:
Enter the site:
Http://3remetodista.org.br/

Navigate with the arrows below until the link:

EXP. MISSIONÁRIA

Press enter, note that nothing happens.

Now pressing shift + nvda + m and then nvda + [ (Left click) note that navigating with the arrows below shows a new set of options.

**Comment by jcsteh** [comment] 2017-03-29 22:31
There's no way we can detect this. However, we might be able to handle cases like this by changing the way we activate things in browse mode. Closing as a duplicate of #4448, as it's the same underlying issue.

**Closed by jcsteh** 2017-03-29 22:31 UTC
