### ISSUE TITLE
Vuetify Select Reads Blank

### ISSUE THREAD

**Issue by rkrasnan** [nvaccess/nvda#10685] opened 2020-01-14 15:52 UTC
### Steps to reproduce:
Using NVDA 2019.2.1
Tab to a v-select
Press space to open the menu.
Press down to go to the first option.

### Actual behavior:
NVDA reads "blank" on each option in the dropdown

### Expected behavior:
NVDA should read the item in the dropdown,
eg. "2017", "2018"

#### NVDA version: 
2019.2.1

#### Windows version:
Windows 7 Professional

#### Name and version of other software in use when reproducing the issue:
Vuetify Version: 2.1.9
Vue Version: 2.6.10
Browsers: Google Chrome, Mozilla Firefox
OS: Windows

#### Reproduction Link
https://codepen.io/rkrasnan/pen/bGGQWXZ

### Other questions
I originally open an issue within Vuetify but I think it might be a NVDA issue. 
https://github.com/vuetifyjs/vuetify/issues/9680

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment] 2020-01-14 18:17
I can also reproduce this with the codepen example in Firefox 72.0.1 and NVDA 2019.3 Beta 1.
cc: @MarcoZehe

**Comment by MarcoZehe** [comment] 2020-01-15 08:20
This is author error. The issue is in whatever Vue does with that list component. There are two divs with the ID list-4, which is invalid HTML. There are also several other ID duplicates I've seen in the DOM. As a result, the aria-owns on that input button doesn't know which one of the items to take, and there is a strict rule that an ID has to be unique within a document. So, this example is invalid and not a browser or NVDA problem. Take it up with the Vue component developers to clean up their IDs and adhere to coding rules that IDs have to be unique and *not* duplicated.

**Comment by Adriani90** [comment] 2020-01-15 08:52
Closing as imvalid. Thanks Marco!

**Closed by Adriani90** 2020-01-15 08:52 UTC
Labels: invalid

**Comment by rkrasnan** [comment] 2020-01-15 15:50
Thank you very much with your help diagnosing this issue.
