### ISSUE TITLE
Announce dot at end of sentence when reading word by word

### ISSUE THREAD

**Issue by OnFireToCode** [nvaccess/nvda#6278] opened 2016-08-18 12:43 UTC
When I read word by word using NVDA, I get only the words spoken, but when I reach the end of sentence, it also reports only word I pass, but does not inform that it was the end of the sentence like Jaws does, it would be great to know that I reached the end of the sentence, but I am chosen only some symbols to be spoken and I wish functionality to let me choose to hear the dot in the end and at the same time do not hear dot after each sentence when NVDA just reads some line, paragraph and ETC, only when I read word by word, thanks.

**Comment by ehollig** [comment] 2017-07-25 15:41
If I understand this correctly, you would like NVDA to report the symbol at the end of the sentence when reading by line or by paragraph like it does when reading a sentence word by word.
This is possible by changing the Punctuation/Symbol Level by pressing NVDA+P. It sounds like you would want to change this to "All", so that all punctuation will be read as words while reading by line or by paragraph.

**Comment by leonardder** [comment] 2017-07-26 06:31
ehollig: Hmm, but setting punctuation level to all means that the dot is always spoken, and it seems @OnFireToCode only wants this for word by word navigation. That would either require a new symbol level for words (e.g. like we have for characters), and than you would need to have multi selection possibilities for the symbol level.

**Comment by jcsteh** [comment] 2017-08-06 23:36
Duplicate of #1468.

**Closed by jcsteh** 2017-08-06 23:36 UTC
