### ISSUE TITLE
NVDA freezes when in the Outlook 2010 Message List

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5708] opened 2016-01-24 14:26 UTC
When I delete a message or two from one of my folders in Outlook 2010 with the latest Master of NVDA, there is a freeze. The only way to get responsive feedback is to Alt Tab away and back to Outlook.

**Comment by jcsteh** [comment] 2016-01-24 22:57
Does this occur with NVDA 2015.4? If unsure, please test.

Also, please provide a log file with log level set to input/output as per [this article](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps).

**Comment by fernando-jose-silva** [comment] 2016-01-26 01:19
dear me something similar happens sometimes when walking with arrows above or below the message list, or delete them with delete, NVDA to read the message list,
To reproduce the error just browse through a list of messages in an Outlook folder, going through various messages and sometimes deleting some or moving folders messages.
Input: kb (laptop): delete
IO - speech.speak (22:01:20):
Speaking [u'cursor Edit]
IO - speech.speak (22:01:21):
Speaking [u'cursor Normal]
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (22:01:23):
oleacc.AccessibleObjectFromEvent with window 852 246, -4 objectID and childID 0: [Error -2147024809] Incorrect Parameter
IO - inputCore.InputManager.executeGesture (22:01:24):
Input: kb (laptop): tab
this also occurs when you move a folder of e-mail, when browsing through folders in dispute menu.
To reproduce the error, select a message in an Outlook message box, press the contest menu (right), walk with the arrows Assima to move option, press arrow right, it is expected that NVDA read folder where to move the email, what happens is that NVDA does not read the name of the selected folder.
Input: kb (laptop): rightArrow
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (22:00:31):
oleacc.AccessibleObjectFromEvent with window 133266, 1560 objectID and childID 0: [Error -2147467259] Unspecified error
IO - speech.speak (22:00:31):
Speaking [u'Mover list ']
IO - speech.speak (22:00:31):
Speaking [u'menu ']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (22:00:31):
oleacc.AccessibleObjectFromEvent with window 133266, 1561 objectID and childID 0: [Error -2147467259] Unspecified error
IO - inputCore.InputManager.executeGesture (22:00:33):
Input: kb (laptop): enter

**Comment by fernando-jose-silva** [comment] 2016-01-26 11:40
[outlook.txt](https://github.com/nvaccess/nvda/files/104820/outlook.txt)
Dear, I collected a blog where the error occurred in the outlook.
 To reproduce the error again was browsing the message list in Outlook inbox, deleted a message and NVDA stopped reading the message list.

**Comment by PratikP1** [comment] 2016-05-26 19:23
Similar behavior occurs in Outlook 2016. NVDA freezes (or speech freezes) when arrowing through the message list. Sometimes the speech will come back. Other times, one has to move to another folder and return to the previous folder to get speech back. Note that speech is not completely gone. Rather, the message list does not speak.

**Comment by derekriemer** [comment] 2016-05-26 20:56
I've seen this but can't quite pinpoint it.


On 5/26/2016 1:24 PM, PratikP1 wrote:
>
> Similar behavior occurs in Outlook 2016. NVDA freezes (or speech 
> freezes) when arrowing through the message list. Sometimes the speech 
> will come back. Other times, one has to move to another folder and 
> return to the previous folder to get speech back. Note that speech is 
> not completely gone. Rather, the message list does not speak.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5708#issuecomment-221969034>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by Adriani90** [comment] 2019-02-12 13:13
@PratikP1, @fernando-jose-silva, @JamaicanUser is this issue still reproducible in last NVDA alpha or in NVDA 2018.4.1? I am on NVDA 2017.4 on Windows 8.1 and MS Outlook 2010. I couldn't reproduce this issue ever during last two years. I didn't test in Outlook 2016 with last NVDA yet.

**Comment by fernando-jose-silva** [comment] 2019-02-12 19:50
I did not have this problem any more.
Thank you very much.
I now use ffice 2019 and windows 10 1809

**Comment by Adriani90** [comment] 2019-02-12 22:55
Closing as works for me. If the issue comes up again we can reopen this.

**Closed by Adriani90** 2019-02-12 22:55 UTC
Labels: Microsoft Office support, worksforme
