### ISSUE TITLE
impossible to start nvda_snapshot_threshold_py3_staging-17851,779ca15b.exe

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9831] opened 2019-06-27 12:33 UTC
### Steps to reproduce:
I would like to apologize if the call does not apply.
I am not a programmer, I work with computers and I am interested in testing the software.
I saw that on the nvda snapshot page there was a new branch
threshold_py3_staging
and wanted to test.
I downloaded the file and tried to run, but I get an error.
only one error sound is played, nor is a message displayed.
below is the error log.
this verdict of nvda does not start.
### Actual behavior:
pressing enter on the installation file causes an error sound to sound and not a message appears on the screen.
The temporary copy of nvda does not start and can not be installed or run as a temporary copy.
### Expected behavior:
nvda is installed and can be tested.
#### NVDA installed/portable/running from source:
installation file
nvda_snapshot_threshold_py3_staging-17851,779ca15b.exe
#### NVDA version:
installation file
nvda_snapshot_threshold_py3_staging-17851,779ca15b.exe
#### Windows version:
10 17763.557
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
log:
[nvda.log](https://github.com/nvaccess/nvda/files/3334708/nvda.log)

**Comment by leonardder** [comment] 2019-06-27 13:01
@josephsl: Would you be able to have a look?

**Comment by josephsl** [comment] 2019-06-27 13:38
Hi, looks like something expects a module to be located somewhere other than the path we normally use. Thanks.

**Comment by josephsl** [comment] 2019-06-27 14:00
Hi, web searches indicate that Python 3 (at least the one that ships with staging branch) insists on looking at somewhere when loading DLL’s. I cannot reproduce this problem after following steps given by the poster, so looks like this is unique to his. Also note that I’m using Version 1903 build 18362 as opposed to the poster who is running Version 1809. Thanks.

**Comment by leonardder** [comment] 2019-06-27 14:02
I wonder whether this could be reproduced from a vm or sandbox.

**Comment by josephsl** [comment] 2019-06-27 14:05
Hi, I’ll report back once I run this inside Windows Sandbox. Thanks.

**Comment by leonardder** [comment] 2019-06-27 14:08
> web searches indicate that Python 3 (at least the one that ships with staging branch) insists on looking at somewhere when loading DLL’s.

Could you please provide the source of this information?

**Comment by leonardder** [comment] 2019-06-27 14:16
Looks like this needs a hook in py2exe. I will write a patch for it. cc @albertosottile

**Comment by josephsl** [comment] 2019-06-27 14:23
Hi, one of these is: https://github.com/msys2/MINGW-packages/issues/3343

**Comment by nishimotz** [comment] 2019-06-27 14:41
I think AppVeyor VM is adding the location of _ssl.pyd to the PATH, so the CI doesn't fail.
The following batch file works for me.
Python 3.7.3 (32bit) should be installed.

```
set PATH=C:\Users\nishimotz\AppData\Local\Programs\Python\Python37-32\DLLs;%PATH%
nvda.exe
```

**Comment by albertosottile** [comment] 2019-06-27 14:57
If the problem is just `_ssl.pyd` you can add `_ssl` in your `'includes'` dictionary.

**Comment by leonardder** [comment] 2019-06-27 15:08
@albertosottile The problem is actually that _ssl relies on extra dll's that aren't copied by py2exe.

**Comment by Brian1Gaff** [comment] 2019-06-27 17:31
and for those interested, an attempt to run it on windows 7 fails, but of 
course its trying to load add ons from the path of the installed normal 
version so there is a lot of  rubbish at the start of this log.

INFO - __main__ (18:18:01.541):
Starting NVDA
INFO - external:core.main (18:18:01.620):
Config dir: C:\Users\Brian\AppData\Roaming\nvda
INFO - external:config.ConfigManager._loadConfig (18:18:01.620):
Loading config: C:\Users\Brian\AppData\Roaming\nvda\nvda.ini
INFO - external:config.ConfigManager._loadConfig (18:18:01.629):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{'schemaVersion': '2', 'upgrade': {}, 'update': {'autoCheck': 'True', 
'startupNotification': 'True', 'allowUsageStats': 'True', 
'askedAllowUsageStats': 'True'}, 'general': {'showWelcomeDialogAtStartup': 
'False', 'language': 'Windows', 'saveConfigurationOnExit': 'True', 
'askToExit': 'True', 'playStartAndExitSounds': 'True', 'loggingLevel': 
'DEBUG'}, 'speech': {'synth': 'espeak', 'outputDevice': 'Speakers (4- 
BEHRINGER USB WDM ', 'symbolLevel': '100', 'espeak': {'voice': 'en', 
'variant': 'quincy', 'rate': '40', 'pitch': '40', 'inflection': '75', 
'volume': '95'}, 'sapi5': {'voice': 
'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech\\Voices\\Tokens\\ScanSoftDaniel_Full_22kHz', 
'volume': '100', 'rate': '70', 'pitch': '49'}, 'mssp': {'voice': 
'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech 
Server\\v11.0\\Voices\\Tokens\\TTS_MS_en-GB_Hazel_11.0', 'volume': '90', 
'rate': '45'}, 'silence': {}, 'sapi4': {'voice': 
'{BF5EAD40-9F65-11CF-8FC8-0020AF14F271}', 'rate': '100', 'pitch': '26', 
'volume': '54'}, 'speechPlayerInEspeak': {'voice': 'en', 'variant': 
'quincy', 'rate': '40', 'pitch': '40', 'inflection': '75', 'volume': '99'}, 
'pico': {'voice': 'en-gb', 'volume': '77', 'rate': '55', 'pitch': '40'}, 
'dectalk': {'voice': 'Frank', 'rate': '38', 'pitch': '19', 'inflection': 
'40'}}, 'braille': {'messageTimeout': '4', 'noBraille': {'port': ''}}, 
'presentation': {'reportTooltips': 'True', 
'guessObjectPositionInformationWhenUnavailable': 'True', 
'reportObjectDescriptions': 'True', 'progressBarUpdates': 
{'progressBarOutputMode': 'both'}}, 'virtualBuffers': 
{'autoPassThroughOnCaretMove': 'True'}, 'documentFormatting': 
{'reportRevisions': 'False', 'reportSpellingErrors': 'False', 
'reportLineIndentation': 'False', 'reportBlockQuotes': 'False', 
'autoLanguageSwitching': 'True', 'detectFormatAfterCursor': 'False', 
'reportFontName': 'False', 'reportFontSize': 'False', 'reportAlignment': 
'True', 'reportStyle': 'False', 'reportFontAttributes': 'False', 
'reportEmphasis': 'False', 'reportLineIndentationWithTones': 'True', 
'reportParagraphIndentation': 'False', 'reportLineSpacing': 'False'}, 
'keyboard': {'speakTypedCharacters': 'True', 'useCapsLockAsNVDAModifierKey': 
'False', 'keyboardLayout': 'desktop', 'speakTypedWords': 'False'}, 
'wintenApps': {'updateCheckTime': '1529135589'}, 'speechViewer': {'x': '68', 
'y': '44', 'width': '500', 'height': '500', 'displays': ['(1920, 1080)'], 
'autoPositionWindow': 'False'}, 'audioThemes': {'speakRole': 'True'}, 
'mouse': {'enableMouseTracking': 'True'}, 'development': 
{'enableScratchpadDir': 'False'}, 'clipContentsDesigner': {'confirmToCopy': 
'True', 'confirmToCut': 'True'}}
DEBUG - external:core.main (18:18:01.641):
setting language to Windows
INFO - external:core.main (18:18:01.642):
NVDA version threshold_py3_staging-17851,779ca15b
INFO - external:core.main (18:18:01.642):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - external:core.main (18:18:01.642):
Using Python version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC 
v.1916 32 bit (Intel)]
INFO - external:core.main (18:18:01.642):
Using comtypes version 1.1.7
INFO - external:core.main (18:18:01.642):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - external:core.main (18:18:01.650):
Initializing add-ons system
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.651):
Listing add-ons from C:\Users\Brian\AppData\Roaming\nvda\addons
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.651):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\addonUpdater
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.652):
Found add-on addonUpdater - 19.07. Requires API: (2019, 1, 0). Last-tested 
API: (2019, 3, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.652):
Add-on addonUpdater is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.652):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\applicationDictionary
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.653):
Found add-on applicationDictionary - 1.2-dev. Requires API: (0, 0, 0). 
Last-tested API: (0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.653):
Add-on applicationDictionary is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.653):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\AudioThemes3D
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.654):
Found add-on AudioThemes3D - 5.1. Requires API: (0, 0, 0). Last-tested API: 
(0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.654):
Add-on AudioThemes3D is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.654):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\dropbox
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.654):
Found add-on dropbox - 4.3. Requires API: (0, 0, 0). Last-tested API: (0, 0, 
0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.654):
Add-on dropbox is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.655):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\extendedWinamp
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.655):
Found add-on extendedWinamp - 1.1. Requires API: (0, 0, 0). Last-tested API: 
(0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.655):
Add-on extendedWinamp is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.655):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\fakeClipboardAnouncement
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.656):
Found add-on fakeClipboardAnouncement - 1.0. Requires API: (0, 0, 0). 
Last-tested API: (0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.656):
Add-on fakeClipboardAnouncement is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.656):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\focusHighlight
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.657):
Found add-on focusHighlight - 6.1. Requires API: (2014, 1, 0). Last-tested 
API: (2019, 4, 0)
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.657):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\goldenCursor
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.658):
Found add-on goldenCursor - 3.6. Requires API: (2017, 3, 0). Last-tested 
API: (2019, 2, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.658):
Add-on goldenCursor is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.658):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\goldwave
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.658):
Found add-on goldwave - 19.04. Requires API: (2017, 3, 0). Last-tested API: 
(2019, 2, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.658):
Add-on goldwave is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.659):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\IndentNav
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.659):
Found add-on IndentNav - 1.6. Requires API: (2018, 1, 0). Last-tested API: 
(2019, 1, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.659):
Add-on IndentNav is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.659):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\Mozilla
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.660):
Found add-on Mozilla - 1.7. Requires API: (2018, 1, 0). Last-tested API: 
(2019, 1, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.660):
Add-on Mozilla is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.660):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\OpenLinkWith
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.661):
Found add-on OpenLinkWith - 1.0. Requires API: (0, 0, 0). Last-tested API: 
(0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.661):
Add-on OpenLinkWith is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.661):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\pico
ERROR - external:addonHandler._getAvailableAddonsFromPath (18:18:01.662):
Error loading Addon from path: 
C:\Users\Brian\AppData\Roaming\nvda\addons\pico
Traceback (most recent call last):
  File "C:\projects\nvda\source\addonHandler\__init__.py", line 196, in 
_getAvailableAddonsFromPath
  File "C:\projects\nvda\include\configobj\src\configobj\__init__.py", line 
502, in __getitem__
KeyError: 'name'
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.667):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\resourceMonitor
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.668):
Found add-on resourceMonitor - 19.07. Requires API: (2017, 4, 0). 
Last-tested API: (2019, 3, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.668):
Add-on resourceMonitor is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.668):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\speechPlayerInEspeak
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.669):
Found add-on speechPlayerInEspeak - 0.4.1. Requires API: (0, 0, 0). 
Last-tested API: (0, 0, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.669):
Add-on speechPlayerInEspeak is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.669):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\systrayList
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.670):
Found add-on systrayList - 3.5. Requires API: (2017, 3, 0). Last-tested API: 
(2019, 2, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.670):
Add-on systrayList is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.670):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\textnav
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.671):
Found add-on textnav - 1.2. Requires API: (2018, 1, 0). Last-tested API: 
(2019, 1, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.671):
Add-on textnav is considered incompatible
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.671):
Loading add-on from 
C:\Users\Brian\AppData\Roaming\nvda\addons\toolbarsExplorer
DEBUG - external:addonHandler._getAvailableAddonsFromPath (18:18:01.671):
Found add-on toolbarsExplorer - 1.1. Requires API: (2017, 3, 0). Last-tested 
API: (2019, 1, 0)
DEBUGWARNING - external:addonHandler._getAvailableAddonsFromPath 
(18:18:01.671):
Add-on toolbarsExplorer is considered incompatible
CRITICAL - __main__ (18:18:01.745):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 221, in <module>
  File "C:\projects\nvda\source\core.py", line 245, in main
  File "C:\projects\nvda\source\appModuleHandler.py", line 27, in <module>
  File "C:\projects\nvda\source\NVDAHelper.py", line 19, in <module>
  File "C:\projects\nvda\source\eventHandler.py", line 9, in <module>
  File "C:\projects\nvda\source\api.py", line 12, in <module>
  File "C:\projects\nvda\source\review.py", line 10, in <module>
  File "C:\projects\nvda\source\NVDAObjects\__init__.py", line 16, in 
<module>
  File "C:\projects\nvda\source\displayModel.py", line 16, in <module>
  File "C:\projects\nvda\source\mouseHandler.py", line 8, in <module>
  File "C:\projects\nvda\source\gui\__init__.py", line 28, in <module>
  File "C:\projects\nvda\source\gui\settingsDialogs.py", line 39, in 
<module>
  File "C:\projects\nvda\source\updateCheck.py", line 33, in <module>
  File "C:\Python37\lib\ssl.py", line 98, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: The specified module could not be found.) 
'C:\\Users\\Brian\\AppData\\Local\\Temp\\nsj4FA9.tmp\\app\\_ssl.pyd'

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by dingpengyu** [comment] 2019-06-28 08:39
> ### Steps to reproduce:
> I would like to apologize if the call does not apply.
> I am not a programmer, I work with computers and I am interested in testing the software.
> I saw that on the nvda snapshot page there was a new branch
> threshold_py3_staging
> and wanted to test.
> I downloaded the file and tried to run, but I get an error.
> only one error sound is played, nor is a message displayed.
> below is the error log.
> this verdict of nvda does not start.
> 
> ### Actual behavior:
> pressing enter on the installation file causes an error sound to sound and not a message appears on the screen.
> The temporary copy of nvda does not start and can not be installed or run as a temporary copy.
> 
> ### Expected behavior:
> nvda is installed and can be tested.
> 
> ### System configuration
> #### NVDA installed/portable/running from source:
> installation file
> nvda_snapshot_threshold_py3_staging-17851,779ca15b.exe
> 
> #### NVDA version:
> installation file
> nvda_snapshot_threshold_py3_staging-17851,779ca15b.exe
> 
> #### Windows version:
> 10 17763.557
> 
> #### Name and version of other software in use when reproducing the issue:
> #### Other information about your system:
> ### Other questions
> #### Does the issue still occur after restarting your PC?
> yes
> 
> #### Have you tried any other versions of NVDA? If so, please report their behaviors.
> no
> log:
> [nvda.log](https://github.com/nvaccess/nvda/files/3334708/nvda.log)

I used nvda_snapshot_threshold_py3_staging-17866 in the Simplified Chinese windows10-1903, the same problem occurred during the 0b9f3efb.exe test.
thank

**Comment by leonardder** [comment] 2019-06-28 10:35
This can be fixed when https://github.com/albertosottile/py2exe/pull/12 and https://github.com/albertosottile/py2exe/pull/13 are merged, in which case we can update our py2exe binary copy.

**Comment by Adriani90** [comment] 2019-07-03 14:08
@leonardder I guess this issue can also be closed now. Right?

**Comment by leonardder** [comment] 2019-07-03 14:15
Yes.

**Closed** 2019-07-03 19:25 UTC
Labels: blocked, worksforme
