### ISSUE TITLE
Visual Studio 2015 Community menu hotkey don't read from NVDA

### ISSUE THREAD

**Issue by sharkboyto** [nvaccess/nvda#5880] opened 2016-04-12 09:52 UTC
In Visual Studio 2015 Community the hotkey in the top menu bar don't read from NVDA.
1. press alt to go in the menu
2. NVDA read the hotkey to open this menu
3. press arrow down to select another menu item
4. NVDA read the menu item and the underline letter to press but don't read the hotkey for example ctrl+C for copy for example

with other applications the problem there aren't and NVDA work fine.

**Comment by jcsteh** [comment] 2016-04-12 10:28
I'm pretty certain this is something that will need to be fixed in 
Visual Studio.

First, are you sure this actually gets displayed visually? Just because 
it does in other apps doesn't mean it is here.

Second, does this work with Narrator? If it doesn't, it's something 
Microsoft will need to fix.

**Comment by sharkboyto** [comment] 2016-04-12 13:24
hi,
1. Yes, the shortcut key is displayed correctly.
2. Yes, the software Narrator works fine, all shortcut are properly 
announced.

Thanks.

Alessandro

Il 12/04/2016 12:28, James Teh ha scritto:

**Comment by Neurrone** [comment] 2016-05-01 14:38
Yes, this bug has been reported, along with a list of other accessibility problems at https://connect.microsoft.com/VisualStudio/feedback/details/1592131/accessibility-bug-list

**Comment by sharkboyto** [comment] 2016-05-04 15:56
Ok, thank you for yoour time.
I'm waiting for the solution from Microsoft Team.

Alessandro

Il 01/05/2016 16:39, Neurrone ha scritto:

**Comment by ehollig** [comment] 2017-08-19 17:05
Duplicate of #6021

**Closed by ehollig** 2017-08-19 17:05 UTC
Labels: duplicate
