### ISSUE TITLE
edge: information not announced after activating 'More actions' control.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#15153] opened 2023-07-17 10:34 UTC
### Steps to reproduce:

1. Launch Edge Application.
2. Navigate to 'Extensions' button using tab key and invoke it using enter key.
3. Navigate to 'More Options' button using arrow keys and invoke it using enter key.
4. Observe the NVDA behavior i.e., announcing all the options in the more options pop-up.

### Actual behavior:
NVDA remains silent, when user open any pop-up on top of another pop-up. For example, when user open 'More Options' button of 'Extension', menu item pop-up will appear, but NVDA remains silent.

### Expected behavior:
When user open any pop-up on top of another pop-up, NVDA should not remain silent. It should announce the opened pop-up information.

### NVDA logs, crash dumps and other attachments:

https://github.com/nvaccess/nvda/assets/93735775/bc7a9a2e-4cc7-427d-8e59-fa42552092a2

**Comment by Brian1Gaff** [comment] 2023-07-17 11:24
It would be interesting to know if a system restart makes this read again, 
at least for a while.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "msftedad" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Monday, July 17, 2023 11:34 AM
Subject: [nvaccess/nvda] Screen reader is not announcing any information 
after activating 'More actions' control. (Issue #15153)

**Comment by seanbudd** [comment] 2023-07-18 00:25
This sounds like a duplicate of #14916 or is otherwise related

**Comment by msftedad** [comment] 2023-07-18 05:01
Hi Brian 
I have checked and updated it, even after restarting the system issue getting repro.
@seanbudd yes, this issue is somehow similar to #14916 as in both scenario NVDA focus is not going to the options available after invoking more option button.

**Comment by msftedad** [comment] 2024-02-08 12:30
Hi team, Any update on this issue?

**Closed** 2024-04-22 09:23 UTC
Labels: close/worksforme, p3, app/edge/anaheim, triaged
