### ISSUE TITLE
Additional text read when navigating through table headers

### ISSUE THREAD

**Issue by clayplumridge** [nvaccess/nvda#10256] opened 2019-09-20 18:19 UTC
NOTE: This issue appears to occur only when the table itself contains links. Using the dropdown you can view other samples using the same components and note that this issue does not reproduce on all of them.

### Steps to reproduce:
1. Navigate to https://developer.microsoft.com/en-us/azure-devops/components/table#table-with-links
2. Tab through the page until you reach the "Hide code" button.
3. Press the down arrow key to navigate into the table header (Name column header should be selected)
4. Press the down arrow key to attempt to navigate to the next table header

### Actual behavior:
NVDA produces the following output and does not change the focused element:
space
blank

### Expected behavior:
NVDA navigates to the next header and reads it out.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA 2019.2

#### Windows version:
Windows 10 1903 18362.356

#### Name and version of other software in use when reproducing the issue:
Chrome 76

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
One version from 2018, I don't remember which. It didn't have the additional text.

### Full NVDA Output navigating through the headers in the table
table clickable with 5 rows and 4 columns 
row 1  Name   column 1
no indent
Name
space
blank
Continent   column 2
no indent
Continent
space
blank
Server   column 3
no indent
Server
space
blank

**Comment by Adriani90** [comment] 2019-09-22 11:19
It seems something is different in this layout when compared in different browsers. In Firefox everything works correctly. In Chrome 77 I can reproduce this issue. Moreover, when I press down arrow and NVDA reports blank, at that moment table navigation commands (ctrl+alt+arrow keys) do not work at all. When I press down arrow again and focus a header, table navigation commands work correctly.


cc: @feerrenrut, @leonardder

**Comment by clayplumridge** [comment] 2019-09-23 14:04
I believe this was working on NVDA 2018.3? May have been 2018.2. Not sure if there's any changelog that can help pinpoint between then and now.

**Comment by Adriani90** [comment] 2020-05-27 22:01
I can access the links by pressing arrow keys in focus mode now in Chrome 83 with NVDA 2020.1 and Firefox also. But I cannot access the headers. This is occuring mostly because the headers are only text and are not having an action or atribute on them like button, link etc. Text even with role clickable cannot be focused in focus mode. So this is actually working as expected sofar as far as I can understand.
This table implementation is not standard  and does not follow a logical table navigation. The headers can be accessed in browse mode anyway.
This being said, I am closing this issue as works for me.

**Closed by Adriani90** 2020-05-27 22:01 UTC
Labels: close/worksforme
