### ISSUE TITLE
HTML element list ignores some nav elements

### ISSUE THREAD

**Issue by martinlex** [nvaccess/nvda#14420] opened 2022-12-02 23:27 UTC
### Description:
If there are multiple nav elements, the element list (nvda + F7) ignores some nav elements.

### Steps to reproduce:
Put two navs in header and two navs in main. Make sure they have an accessible name, I use aria-label.
Here is the code:
https://codepen.io/martinlex/pen/yLEQYaK?editors=1000
Here is a page to test it:
https://cdpn.io/pen/debug/yLEQYaK?authentication_hash=PNkvYyaGbLVA

### Actual behavior:
The element list (under landmarks) does not show all nav elements. Top nav and breadcrumbs nav are not showing.
In the Chrome accessibility tree shows all navs. ANDI a11y extension also shows all landmarks.
I have tested in Chrome, Firefox and Edge, with same result.
However - navigating page landmarks with nvda + d is working, it will take you to all four nav elements.

### Expected behavior:
The element list should present all nav elements.

### NVDA logs, crash dumps and other attachments:
This image shows that the NVDA landmark element dialog does not expose all nav elements.
![image](https://user-images.githubusercontent.com/10650928/205405331-6b51b8be-6083-4afa-aada-2fe6249d01ca.png)

This image shows that all nav elements are revealed in the accessibility tree provided by firefox dev tools.
![image](https://user-images.githubusercontent.com/10650928/205405421-47fffcc5-d45c-43e1-9d16-3ded6a39bbfb.png)

#### NVDA version:
2022.3.1

#### Windows version:
Windows 11 Pro

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by feerrenrut** [comment] 2022-12-06 02:00
English screenshot in Firefox:
![image](https://user-images.githubusercontent.com/3491346/205789882-476cd971-5d99-40f6-8d33-3393518e061c.png)

Text from Speechviewer (Firefox)
```
banner  1 of 2  level 0
down arrow
main  expanded  2 of 2  level 0
down arrow
level 1  Main nav; navigation  1 of 3
down arrow
main  expanded  2 of 3  level 1
down arrow
level 2  Other pages; navigation  1 of 1
down arrow
level 1  content info  3 of 3
```

Same behavior in Edge (Chromium)

**Comment by Adriani90** [comment] 2023-02-13 20:11
cc: @JulienCochuyt

**Comment by Adriani90** [comment] 2024-12-08 22:35
This is invalid.
1. NVDA ignores blank landmarks
2. and merges nested landmarks to one single landmark where the parent landmark doesn't have any content before the child landmark.
This avoids useless verbosity. d navigates the landmarks, but the elements list displays only the parent landmark if two nested landmarks are merged.
This is by design.
Following example is correct and would show all the landmarks also in the elements list:

```
data:text/html,<html><header><nav aria-label="Top nav"><p>"content 1</nav><nav aria-label="Main nav"><p>content 2</p></nav></header><body><main><p>content 3</p><nav aria-label="Breadcrumbs"><p>content 4</p></nav><h1>Test</h1><p>Content</p><nav aria-label="Other pages"><p>content 5</p></nav></main><footer><h2>"Yo"</h2></footer></body></html>
```

I am closing as won't fix.

**Closed by Adriani90** 2024-12-08 22:35 UTC
Labels: close/wontfix, p3, app/chrome, app/firefox, app/edge/anaheim, triaged, needs-technical-investigation
