### ISSUE TITLE
no reliable braille output in LibreOffice Calc

### ISSUE THREAD

**Issue by DavidBitSource** [nvaccess/nvda#12249] opened 2021-03-30 09:33 UTC
### Steps to reproduce:
* LibreOffice Calc
* Enter data into Calc (not the first column).

### Actual behavior:
Just the TTS gives you feedback, the braille display doesn't change. This mostly occurs when the TTS announces "text frame".
### Expected behavior:
Proper braille ouput in real time, according to the screen and according with the TTS output.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
7 64 bit
#### Name and version of other software in use when reproducing the issue:
Libreoffice Calc 7.0.4.2
#### Does the issue still occur after restarting your computer?
yes
#### If add-ons are disabled, is your problem still occurring?
yes

**Comment by DrSooom** [comment] 2021-04-05 19:09
Also reproducible with LibreOffice 7.1.1.2 and NVDA 2019.2.1 on Win7x64. LibreOffice 7.1.2.2 wasn't tested.

**Comment by mwhapples** [comment] 2022-04-07 15:03
A very quick test for me seems to show this as working. However this is on a more up-to-date system, Windows11, NVDA 2021.3.5 and LibreOffice 7.3.2.2. Do you get this issue with newer versions of NVDA and LibreOffice. Also does it happen always or only sometimes?

**Comment by seanbudd** [comment] 2022-06-16 05:56
Could you update the issue with clear steps to reproduce.

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by michaelDCurran** [comment] 2024-10-02 00:03
I am unable to reproduce this in LibreOffice Calc 24.8.2.1. Windows 11. Every time I edit a cell with f2, the editable content is shown on the display.
Closing. Please reopen if this is experienced again with most recent or future stable builds of LibreOffice.

**Closed by michaelDCurran** 2024-10-02 00:03 UTC
Labels: component/braille, app/libreoffice, needs-triage
