### ISSUE TITLE
Excel: NVDA doesn't report cell under focus after choosing an item from a dropdown list

### ISSUE THREAD

**Issue by abdel792** [nvaccess/nvda#13426] opened 2022-03-03 18:31 UTC
In Excel 2016 and higher, NVDA refuses to report the cell under focus after choosing an element from a drop-down list.

### Steps to reproduce:

Open an Excel workbook, including a drop-down list.

Here is an [example](https://github.com/nvaccess/nvda/files/8180201/example.xlsx) with the days of the week.

Open the drop-down list, and choose an item.

Press Enter, or Control + enter if you prefer to stay on the active cell.

Press tab, to move to another cell.

### Actual behavior:

NVDA is silent, no information about the cell under focus.

### Expected behavior:

NVDA should report the cell under focus.

#### NVDA installed/portable/running from source:

NVDA installed

#### NVDA version:

2021.3.3

#### Windows version:

Windows 10, Version 21H1, Build 19043.1526

#### Name and version of other software in use when reproducing the issue:

Not applicable

#### Other information about your system:

ASUS Desktop, 64bits. processor Intel(R) Core(TM) i3-5005U. 8 GB RAM

#### Does the issue still occur after restarting your computer?

Yes

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by britechguy** [comment] 2022-03-03 19:32
I can replicate.

NVDA 2021.3.3, Excel 2016, Windows 10 Version 21H2 Build 19044.1526

HP 15-ba011cy, AMD A12-9600P, 12 GB RAM

**Comment by CyrilleB79** [comment] 2022-03-03 20:54
Yes, confirmed also on my side on Excel 2016 ('16.0.14827.20198')

Pressing NVDA+Tab shows that NVDA seems to believe that the focus is still on a list item, whereas the list is closed.
It is also highlighted visually by the focus highlight which remain at the location of the last selected list item before the validation, even if you move the selected cell with arrows.

Note: To be able to open the list, you need to remove the protect mode that is automatically set on Excel files when downloading from internet.

**Comment by Qchristensen** [comment] 2022-03-04 03:12
While a valid issue, this is a duplicate of #10401 so I will close it.  Please do follow that issue for updates.

Note that the workaround for this, especially if using a newer version of Excel, is to turn on "Use UI Automation to access Microsoft Excel":

1) Press NVDA+control+g to open the settings dialog.
2) Press control+shift+tab to move to the last category, "Advanced"
3) Press spacebar to accept the warning.
4) Press tab until the focus is on "Use UI Automation to access Microsoft Excel".
5) Press spacebar to check this checkbox.
6) Press enter to activate the OK button.

Note that UIA may not work as well (overall) in older versions of Excel, so be aware that some things may read differently (better, or worse).  Set that option as best works for you overall.

**Closed by Qchristensen** 2022-03-04 03:12 UTC
