### ISSUE TITLE
NVDA is too verbose when switching keyboard language on windows 11 with Windows+space or windows+shift+space

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#13931] opened 2022-07-20 20:39 UTC
### Steps to reproduce:
1. press NVDA+windows+space
2. You will notice that NVDA is too verbose when this shortcut is used to switch keyboard layout on Windows 11
### Actual behavior:

>windows+space
>Control Centre  window
>Keyboard layout  window
>Language Switching List  grouping
>list
>English (United Kingdom) United Kingdom  1 of 5

### Expected behavior:

> windows+space
> English (United Kingdom) United Kingdom  1 of 
> 5

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.2
#### Windows version:
windows11
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Same behaviour on other versions.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by josephsl** [comment] 2022-07-20 20:48
Hi, which Windows 11 version are you using (build number please)? Thanks.

**Comment by seanbudd** [comment] 2022-07-21 05:50
When implementing this some context e.g. "Keyboard layout window"/"Language Switching List grouping" should probably still be announced.

**Comment by fatihyuksek1** [comment] 2022-07-21 09:47
Build OS: 22000.795 Отправлено из приложения "Почта" для Windows От: Joseph LeeОтправлено: 20 июля 2022 г. в 23:48Кому: nvaccess/nvdaКопия: Fatih Yüksek; AuthorТема: Re: [nvaccess/nvda] NVDA is too verbose when switching keyboard language on windows 11 with Windows+space or windows+shift+space (Issue #13931) Hi, which Windows 11 version are you using (build number please)? Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Adriani90** [comment] 2023-09-16 19:33
This is not reproducible in the last Windows 11 22 H2 update with NvDA 2023.2. The list grouping of switching languages is reported as expected as well.
I am closing as works for me. Please comment if you still have this issue in Windows 11 22 H2 last update and we can reopen.

**Closed by Adriani90** 2023-09-16 19:33 UTC
Labels: close/worksforme, p5, platform/Windows11, triaged
