### ISSUE TITLE
Click fired at wrong element when focused on div with tabindex="0"

### ISSUE THREAD

**Issue by RichCaloggero** [nvaccess/nvda#11415] opened 2020-07-23 21:44 UTC
## Steps to reproduce

1. goto https://richcaloggero.github.io/test/click-test.html
2. press tab once after page has loaded
   - NVDA should say "outer focused"
3. press Enter
   - NVDA says "innermost clicked"

### Actual behavior:

NVDA reports correct focus, but sends click to the wrong element when Enter key is pressed on div with `tabindex="0"`.

### Expected behavior:

When NVDA is running, and enter is pressed on a focusable element, NVDA synthesizes a click and fires it at the currently focused element.

For more explanation see https://github.com/RichCaloggero/test/blob/master/click-test.md

**Comment by codeofdusk** [comment] 2020-07-24 01:13
Cc @jcsteh.

**Comment by jcsteh** [comment] 2020-07-24 05:13
In browse mode, pressing enter clicks the deepest element under the browse mode cursor. Since there's nothing in the outer div which precedes the inner div, they effectively occupy the same browse mode cursor position.

Note that visually, you'd get the same behaviour for nested divs. You can't click on the outer one if it occupies the same dimensions as the inner one.

**Comment by feerrenrut** [comment] 2020-07-24 07:57
I can confirm this matches the visual / mouse driven behavior. Clicking on "....some content..." will briefly show X focused, then innermost clicked. Where X is the selection in the combo.

I'm going to close this issue>

**Closed by feerrenrut** 2020-07-24 07:57 UTC
Labels: close/invalid
