### ISSUE TITLE
problems of the latest alpha versions of nvda with the mail app for windows 10

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#12254] opened 2021-03-31 12:50 UTC
Hello. The latest alpha versions of nvda do not read the list of emails in the mail app for Windows 10. Try to log into the mail app and get on the email list. nvda will play the sound of the error. expected nvda should read the items in the list. there are also problems with the windows update center and with many switches in windows 10 settings. I think all these problems are related. because it started about two weeks ago. I tried older versions of nvda such problems are not.
[nvda.log](https://github.com/nvaccess/nvda/files/6236636/nvda.log)

**Comment by lukaszgo1** [comment] 2021-04-09 08:59
@Nikita34196 Is this still reproducible for you with latest Alpha?

**Comment by Nikita34196** [comment] 2021-04-09 09:34
@lukaszgo1 Hello. The problem has been fixed in the email app. but the problem with the windows settings has not been fixed. Enter the settings. nvda automatically has to report the point at which the cursor is installed. in fact, nvda doesn't report anything until I start moving arrows. also nvda does not tell the progress of downloading windows updates. i tried nvda 2020.4 there are no such problems.

**Comment by lukaszgo1** [comment] 2021-04-13 09:35
Relevant part of the log:
```
ERROR - eventHandler.executeEvent (15:43:33.573) - MainThread (10564):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x07330BC8> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 246, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "C:\Users\ntara\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 105, in next
  File "NVDAObjects\behaviors.pyc", line 187, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1142, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1137, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1005, in reportFocus
  File "speech\__init__.pyc", line 449, in speakObject
  File "speech\__init__.pyc", line 518, in getObjectSpeech
  File "speech\types.pyc", line 50, in _flattenNestedSequences
  File "speech\types.pyc", line 50, in <genexpr>
  File "speech\__init__.pyc", line 1089, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 738, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 539, in _getTextWithFieldsForUIARange
  File "UIAUtils.pyc", line 178, in getChildrenWithCacheFromUIATextRange
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: [WinError -529697949] Windows Error 0xe06d7363
ERROR - scriptHandler.executeScript (15:43:35.169) - MainThread (10564):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x07330BC8>> with gesture 'стрелка вниз'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "editableText.pyc", line 224, in script_caret_moveByLine
  File "editableText.pyc", line 163, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 177, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 149, in _caretScriptPostMovedHelper
  File "speech\__init__.pyc", line 1049, in speakTextInfo
  File "speech\types.pyc", line 42, in __iter__
  File "speech\__init__.pyc", line 1089, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 738, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 539, in _getTextWithFieldsForUIARange
  File "UIAUtils.pyc", line 178, in getChildrenWithCacheFromUIATextRange
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: [WinError -529697949] Windows Error 0xe06d7363
ERROR - scriptHandler.executeScript (15:43:35.828) - MainThread (10564):
error executing script: <bound method EditableText.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionUIA object at 0x07330BC8>> with gesture 'стрелка вверх'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "editableText.pyc", line 224, in script_caret_moveByLine
  File "editableText.pyc", line 163, in _caretMovementScriptHelper
  File "NVDAObjects\behaviors.pyc", line 177, in _caretScriptPostMovedHelper
  File "editableText.pyc", line 149, in _caretScriptPostMovedHelper
  File "speech\__init__.pyc", line 1049, in speakTextInfo
  File "speech\types.pyc", line 42, in __iter__
  File "speech\__init__.pyc", line 1089, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 738, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 539, in _getTextWithFieldsForUIARange
  File "UIAUtils.pyc", line 178, in getChildrenWithCacheFromUIATextRange
  File "comtypesMonkeyPatches.pyc", line 27, in __call__
OSError: [WinError -529697949] Windows Error 0xe06d7363
```


@josephsl Since you're on Insiders same as Original Poster is this issue reproducible for you in Windows Settings?

**Comment by josephsl** [comment] 2021-04-13 11:18
Hi, I’ve seen this after opening Edge in Insider Preview build 21354, specifically when address omnibar is focused. Thanks.

**Comment by lukaszgo1** [comment] 2021-04-15 12:54
@Nikita34196  Could you please test with [this try build](https://ci.appveyor.com/api/buildjobs/9j0yrsjmphluhd9n/artifacts/output%2Fnvda_snapshot_try-py37-22369%2C439dc27a.exe)?

**Comment by Nikita34196** [comment] 2021-04-15 13:42
@lukaszgo1 hi. I've tested it now. unfortunately, the problem remained.
[nvda.log](https://github.com/nvaccess/nvda/files/6318432/nvda.log)

**Comment by Nikita34196** [comment] 2021-04-15 14:12
I was testing older versions now. problem starts after alpha-21871,16b83338

**Comment by lukaszgo1** [comment] 2021-04-15 14:24
Could you please try with the build that I've linked above but start it from the command line passing `--disable-addons` to the executable?

**Comment by Nikita34196** [comment] 2021-04-15 14:51
@lukaszgo1 if you disable all add-ons, the problem is fixed. only thing. when nvda starts there is an error sound. here is log
[nvda.log](https://github.com/nvaccess/nvda/files/6318907/nvda.log)

**Comment by lukaszgo1** [comment] 2021-04-15 17:10
@Nikita34196 You don't need to worry about the error from the last log. it is caused by the fact that your default speech synthesizer is an add-on and therefore cannot be loaded when add-ons are disabled. 
Could you please repeat the testing with the current Alpha and add-ons disabled
Given that this problem cannot be reproduced when add-ons are disabled I suggest to close this issue, try to disable add-ons one by one and when you find a guilty one report the problem to its author.

**Comment by Nikita34196** [comment] 2021-04-15 17:20
if you disable the add-on, the last alpha works smoothly. thank you.

**Comment by lukaszgo1** [comment] 2021-04-21 09:54
@Nikita34196 Could you please close this issue?

**Closed** 2021-04-21 10:49 UTC
