### ISSUE TITLE
Skype for Business 2016: Content of Chat Messages Not Automatically Read

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7511] opened 2017-08-21 16:50 UTC
When running the latest NVDA Next snapshot as of this issue, I've noticed that the content of chat messages is not automatically read. From taking a look at the latest couple of merges, it looks as if these should now automatically be read. Is this the case?

**Comment by ehollig** [comment] 2017-09-02 03:57
This is a duplicate of #5333 and should have been fixed in #7281 in NVDA 2017.3. If this is not the case, CC @michaelDCurran

**Closed by ehollig** 2017-09-02 03:57 UTC

**Comment by elliott94** [comment] 2017-09-04 19:56
@michaelDCurran - Am I right in thinking that NVDA will only read the initial message that gets sent with this pull?
