### ISSUE TITLE
accessible problem nvda and microsoft office publisher

### ISSUE THREAD

**Issue by ollcayy** [nvaccess/nvda#11200] opened 2020-05-25 20:46 UTC
Publisher use is impossible with NVDA. Reads standard office menus in NVDA Publisher; however, it does not focus and read the document content. Is it possible to try to get data over UIA or any other solution?

**Comment by Adriani90** [comment] 2020-05-25 20:52
Closing as duplicate of #4653. Please comment on that issue with your specific problems, please also include the tasks you are trying to use publisher for. Thanks.

**Closed by Adriani90** 2020-05-25 20:52 UTC
Labels: close/duplicate

**Comment by Brian1Gaff** [comment] 2020-05-26 10:14
Does Narrator work on it?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by ollcayy** [comment] 2020-05-26 15:10
No, The situation is the same with nvda, jaws and narrator. A solution has not yet come from the Microsoft accessibility team.

 

Olcay Aşcı

 <https://certification.nvaccess.org/> NVDA Uzmanlık Sertifikası (NVDA Certified Expert)

Front-end Developer (Arayüz geliştirici)  <https://www.vodafone.com.tr/index.php> Vodafone TR Dijital Varlıklar Müdürlüğü

 <http://eniyideneyim.com/> En İyi Deneyim projesi yöneticisi ve sahibi

Takip edin:

 <https://twitter.com/eniyideneyim> Twitter'de en iyi deneyim  <https://twitter.com/olcayashchi> Twitter'da Olcay Aşcı

 <https://www.linkedin.com/in/olcay-a%C5%9F%C3%A7%C4%B1-b0a619124/> LinkedIn Olcay Aşcı  <https://www.facebook.com/profile.php?id=100000061230801> FaceBook Olcay Aşcı
