### ISSUE TITLE
Outlook 2016: Autocomplete Suggestions not automatically announced

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10953] opened 2020-04-07 17:33 UTC
### Steps to reproduce:

1. Open a new message, and begin typing an email address that's already present in Outlook's Autocomplete list; an easy way to ensure that this is the case is to send at least one email to the address, at which time it should then automatically be cached by Outlook for future use

2. When the first several letters of the email address have been typed into the "To..." edit box, hit the enter key

### Actual behavior:

NVDA should then output the entirety of the email address, confirming that it's been automatically prefilled

### Expected behavior:

When using Outlook 2010, upon typing the first several letters of an email address, NVDA would automatically announce the first address in Outlook's autocomplete list - this was really useful, and saved hitting enter only to find out that the wrong address had been chosen. It'd be really useful if this functionality could also be added to Outlook 2016

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

7 X64

#### Name and version of other software in use when reproducing the issue:

Office 2016 (X86)

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

**Comment by josephsl** [comment] 2020-04-07 17:40
Hi, it already does for me. I’m curious to know if this is a regression in either Outlook or NVDA. Thanks.

**Comment by lukaszgo1** [comment] 2020-04-07 17:54
Duplicate of #8502 @josephsl I believe you're using  Office 365 not 2016 which makes a difference in this case.

**Comment by josephsl** [comment] 2020-04-07 18:05
Hi, ah, that explains why. Thanks.

**Comment by josephsl** [comment] 2020-04-07 18:06
Closing as a duplicate. Please comment on issue #8502. Thanks.

**Closed by josephsl** 2020-04-07 18:06 UTC
