### ISSUE TITLE
move the cursor from navigation mode to the mouse cursor

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10697] opened 2020-01-17 19:59 UTC
### Steps to reproduce:
open a website in any browser.
Now place your mouse cursor over text on the website.
Now navigate with the arrow keys.
### Actual behavior:
the browse mode
when walking with the arrows you are in a totally different place from the mouse.
### Expected behavior:
nvda can provide a shortcut key to move the cursor from the browse mode to the mouse cursor.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
all
#### Windows version:
all
#### Name and version of other software in use when reproducing the issue:
browser
### Other questions
as I believe that the English language for me is a barrier to explain what I want, I will try to tell you what need came to me.
An nvda user is studying english.
During her studies she makes use of a website.
When she needs to read a part of the site she can't find, a sighted user places the mouse over the text she needs to read.
The user walks with the arrow keys on the keyboard but the focus of the keyboard is in a totally different place than the mouse.
The nvda is in browse mode, which is better for her as she is totally blind.

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes

**Comment by Adriani90** [comment] 2020-01-17 21:07
Actualy this is already possible. I must have a look if this is properly documented but here are the steps:
1. In NVDA settings under "review cursor" set the review cursor to follow all other cursors (system focus, system carret and mouse cursor)
2. Open a website and move the mouse somewhere while being in browse mode
3. Press nvda+shift+n to move the navigator (incl. the review cursor) to the mouse
4. Press nvda+shift+two times backspace to move the virtual cursor (incl. system focus) to the mouse.


cc: @feerrenrut maybe you know more exactly why there is no way to tell system focus to follow the mouse directly? I think windows does not allow such a feature. right?
However, since we now can split the system focus from the virtual cursor (nvda+8) it might be worthy to implement a key stroke to move the virtual cursor directly to the mouse without considering system focus.
Maybe system focus is splited, then the virtual cursor should follow review cursor and vice versa. Then we could press just nvda+shift+n and the navigator together with the virtual cursor would move to the mouse.
cc: @leonardder

**Comment by Adriani90** [comment] 2020-01-17 21:10
As of now the review cursor follows the virtual cursor and the system focus but the other way round is not possible.

**Comment by fernando-jose-silva** [comment] 2020-01-18 14:49
Thank you very much for your feedback.
I did what you reported:
When pressing nvda + shift + backspace twice the nvda repeats until what is on the mouse, more when pressing the arrows the browse cursor is still in a totally different place.
by pressing nvda + arrows below, the nvda reads only a portion of the sentence, but does not read the entire site from this point on, and simply walking with the arrows below would be more transparent for the user.

**Comment by Adriani90** [comment] 2020-01-18 15:28
you have to make sure that „read all content after page load“ is disabled in browse mode settings in nvda.
For read all the keystroke in laptop layout is nvda+a, not nvda+down arrow. This is documented properly.

Von meinem iPhone gesendet

**Comment by fernando-jose-silva** [comment] 2020-01-18 15:51
read the page automatically is disabled I know that nvda + a on the laptop keyboard layout read the entire page, and I know it is documented, even so it doesn't work as I said before.
I tried to press nvda plus the arrow below since reading everything doesn't work as expected.

**Comment by DrSooom** [comment] 2020-01-18 16:31
Maybe related: Issue #3004 and #4896

**Comment by Adriani90** [comment] 2020-01-18 17:52
Is this with disabled addons?

Von meinem iPhone gesendet

**Comment by fernando-jose-silva** [comment] 2020-01-18 19:13
Yes

Enviado do meu iPhone

**Comment by Adriani90** [comment] 2020-01-18 20:14
Ok I have recorded an audio on how I do it and it works. This is in Firefox. Note that it works in other browsers too but it is quite unreliable. The best result you can get is in Firefox.
Having said that, I will upload the audio here and then I am closing this issue as duplicate of #4896.
[moving virtual cursor to the Mouse.zip](https://github.com/nvaccess/nvda/files/4081705/moving.virtual.cursor.to.the.Mouse.zip)

**Closed** 2020-01-18 20:14 UTC
Labels: duplicate
