### ISSUE TITLE
Remote support add-on does not appear in the tools menu

### ISSUE THREAD

**Issue by jcoffin1** [nvaccess/nvda#8084] opened 2018-03-14 16:38 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. When remote support add-on is enabled, the tools menu in the NVDA menu does not display the remote support option in tools. 

1. if you have the remote add-on installed, and enabled go to NVDA menu, arrow to tools, open tools menu, and remote support should be an option, but it's not there.

**Comment by josephsl** [comment] 2018-03-14 16:50
Hi, are you perhaps running the latest next branch snapshot? If so, I raised an issue on Remote add-on regarding this matter. The ultimate culprit is a missing attribute for wx.Menu in wxPython 4. CC @TSpivey, @CToth.

**Comment by jcoffin1** [comment] 2018-03-14 18:46
Yes I am. Using the latest next snapshot.
On March 14, 2018 10:50:42 AM Joseph Lee <notifications@github.com> wrote:>

**Comment by leonardder** [comment] 2018-03-14 20:15
Strictly spoken, this is not a bug in NVDA itself, it should be solved in NVDA Remote. Therefore I'm temped to close this in favour of nvdaremote/nvdaremote#170 and nvdaremote/nvdaremote#171.

**Comment by DrSooom** [comment] 2019-02-12 18:06
Isn't this fixed in NVDA 2018.4.1 and NVDA Remote Access 2.2?

**Comment by ctoth** [comment] 2019-02-12 21:04
Yes, this should be closed.

**Comment by Adriani90** [comment] 2019-02-12 22:54
Closing as works for me.

**Closed by Adriani90** 2019-02-12 22:54 UTC
Labels: needsExternalFix, worksforme
