### ISSUE TITLE
NVDA No Longer Reads the Save Dialog In NOTEPAD

### ISSUE THREAD

**Issue by netblue44** [nvaccess/nvda#5546] opened 2015-11-26 19:08 UTC
Hi,
When saving a document in Notepad, with the shortcut key, NVDA reads nothing until you press tab or tab away from the window and back. Only then does NVDA, reads the options in the save dialog.
This use to work fine in NVDA2015.3 and prior. However in all versions of NVDA post 2015.3 the problem persist.
This is the log

INFO - **main** (13:07:05):
Starting NVDA
INFO - core.main (13:07:05):
Config dir: C:\Users\USUARIO\AppData\Roaming\nvda
INFO - core.main (13:07:05):
NVDA version next-12845,937f433
INFO - core.main (13:07:05):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (13:07:05):
Using Python version 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
INFO - core.main (13:07:05):
Using comtypes version 0.6.2
INFO - external:synthDrivers.eloquence.SynthDriver.**init** (13:07:05):
Using Eloquence version 6.1.0.0
INFO - synthDriverHandler.setSynth (13:07:05):
Loaded synthDriver eloquence
INFO - core.main (13:07:05):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (13:07:05):
Using liblouis version 2.6.4
INFO - braille.BrailleHandler.setDisplayByName (13:07:05):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (13:07:05):
Braille input initialized
WARNING - core.main (13:07:05):
Java Access Bridge not available
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (13:07:05):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (13:07:05):
No user gesture map
DEBUGWARNING - touchHandler.initialize (13:07:05):
Touch only supported on Windows 8 and higher
INFO - core.main (13:07:05):
NVDA initialized
IO - speech.speak (13:07:06):
Speaking [u'Taskbar']
IO - speech.speak (13:07:07):
Speaking [u'Men\xfa Inicio']
IO - speech.speak (13:07:07):
Speaking [u'Cuadro de b\xfasqueda  edit   Buscar programas y archivos']
IO - speech.speak (13:07:07):
Speaking [u'blank']
IO - inputCore.InputManager.executeGesture (13:07:07):
Input: kb(laptop):upArrow
IO - speech.speak (13:07:07):
Speaking [u'blank']
IO - speech.speak (13:07:07):
Speaking [u'Todos los programas  subMenu  Use la tecla Tabulador para desplazarse entre secciones, incluidos el primer y el segundo panel y los botones de encendido. Use las teclas de flecha arriba y abajo para pasar de un elemento al otro en la lista.  T']
IO - inputCore.InputManager.executeGesture (13:07:07):
Input: kb(laptop):enter
IO - speech.speak (13:07:07):
Speaking [u'Atr\xe1s']
IO - inputCore.InputManager.executeGesture (13:07:08):
Input: kb(laptop):upArrow
IO - speech.speak (13:07:08):
Speaking [u'Todos los programas  tree view']
IO - speech.speak (13:07:08):
Speaking [u'level 1  WinRAR  collapsed  36 of 36']
IO - inputCore.InputManager.executeGesture (13:07:08):
Input: kb(laptop):upArrow
IO - speech.speak (13:07:08):
Speaking [u'VMware  collapsed  35 of 36  level 1']
IO - inputCore.InputManager.executeGesture (13:07:09):
Input: kb(laptop):a
IO - speech.speak (13:07:09):
Speaking [u'Acrobat Reader DC  1 of 36  level 1']
IO - inputCore.InputManager.executeGesture (13:07:11):
Input: kb(laptop):a
IO - speech.speak (13:07:11):
Speaking [u'Accesorios  collapsed  16 of 36  level 1']
IO - inputCore.InputManager.executeGesture (13:07:11):
Input: kb(laptop):rightArrow
IO - speech.speak (13:07:12):
Speaking [u'expanded']
IO - speech.speak (13:07:12):
Speaking [u'21 items']
IO - inputCore.InputManager.executeGesture (13:07:12):
Input: kb(laptop):downArrow
IO - speech.speak (13:07:12):
Speaking [u'level 2  Bloc de notas  1 of 21']
IO - inputCore.InputManager.executeGesture (13:07:13):
Input: kb(laptop):enter
IO - speech.speak (13:07:13):
Speaking [u'Taskbar']
IO - speech.speak (13:07:13):
Speaking [u'Sin t\xedtulo: Bloc de notas']
IO - speech.speak (13:07:13):
Speaking [u'edit  multi line']
IO - speech.speak (13:07:13):
Speaking [u'blank']
IO - inputCore.InputManager.executeGesture (13:07:14):
Input: kb(laptop):upArrow
IO - speech.speak (13:07:14):
Speaking [u'blank']
IO - inputCore.InputManager.executeGesture (13:07:14):
Input: kb(laptop):upArrow
IO - speech.speak (13:07:14):
Speaking [u'blank']
IO - inputCore.InputManager.executeGesture (13:07:14):
Input: kb(laptop):f
IO - inputCore.InputManager.executeGesture (13:07:15):
Input: kb(laptop):enter
IO - speech.speakTypedCharacters (13:07:15):
typed word: f
IO - speech.speak (13:07:15):
Speaking [u'f']
IO - inputCore.InputManager.executeGesture (13:07:15):
Input: kb(laptop):f
IO - inputCore.InputManager.executeGesture (13:07:15):
Input: kb(laptop):enter
IO - speech.speakTypedCharacters (13:07:15):
typed word: f
IO - speech.speak (13:07:15):
Speaking [u'f']
IO - inputCore.InputManager.executeGesture (13:07:17):
Input: kb(laptop):control+g
IO - inputCore.InputManager.executeGesture (13:07:24):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:07:24):
Developer info for navigator object:
name: None
role: ROLE_EDITABLETEXT
states: STATE_MULTILINE, STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObject object at 0x05EE4510>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleEditWindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (185, 227, 988, 447)
value: u'f\r\nf\r\n'
appModule: <'appModuleHandler' (appName u'notepad', process ID 3908) at address 5ea7250>
appModule.productName: u'Sistema operativo Microsoft\xae Windows\xae'
appModule.productVersion: u'6.1.7600.16385'
TextInfo: <class 'NVDAObjects.window.edit.EditTextInfo'>
windowHandle: 328624
windowClassName: u'Edit'
windowControlID: 15
windowStyle: 1345323268
windowThreadID: 3740
windowText: u'f\r\nf\r\n'
displayText: u'ff'
IAccessibleObject: <POINTER(IAccessible) ptr=0x556b60 at 5eac9e0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=328624, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: None
IAccessible accValue: u'f\r\nf\r\n'

**Comment by jcsteh** [comment] 2015-11-26 20:38
I can't reproduce this. For me, this dialog reads as it always did. Can 
anyone else?

I also can't see anything wrong in your log; NVDA isn't reporting a 
freeze that might have caused it to drop some information, etc. 
Therefore, if I can't reproduce this, that's unfortunately going to make 
this very difficult to debug.

I can't think of any changes in 2015.4 that should have caused this to 
change. Have you tested this again with 2015.3 recently? I'm wondering 
whether this might have changed due to a recent Windows Update or similar.

**Comment by josephsl** [comment] 2015-11-26 22:18
Hi, is Control+G Save command? If so, it appears to me either you are pressing the wrong command or the dialog isn’t appearing. Like Jamie, I cannot reproduce this also. Thanks.

**Comment by netblue44** [comment] 2015-11-26 22:25
Yes in spanish versions of Windows the shortcut is control+g and yes the diolog does open but nvda does not read nor anounce it until you tab away from it or press the tab key.

**Comment by ruifontes** [comment] 2015-11-26 23:36
The same happens in Portugal.
And not only on NotePad.

Rui



-----Mensagem Original-----

**Comment by jcsteh** [comment] 2015-11-26 23:41
@ruifontes: And this works fine for you still with NVDA 2015.3?

I don't see how this could be language specific, but it's starting to look that way...

**Comment by ruifontes** [comment] 2015-11-26 23:46
No, it happens like that some versions ago...
I can't remember when it started...

Rui

-----Mensagem Original-----

**Comment by dkager** [comment] 2015-11-27 10:58
I can reproduce this with latest master when right-clicking a link (to a PDF) in Firefox and choosing to save the file. I'll do some version comparisons tonight and also test this in Notepad.
My system locale is en-US, though I did change some format options. This is on Windows 7.

**Comment by dkager** [comment] 2015-11-27 12:34
I can reproduce this in Notepad too, but not consistently. Most of the time it works as expected. Tested by writing a few words, then repeatedly pressing Ctrl+S and Escape.

**Comment by marrie** [comment] 2015-11-28 17:48
I cannot reproduce this.  I was able to read the zsave as dialogue just fine using the latest snap

 I've attached the log of what happens, I think I did it right. 
[nvda log 11-28-2015.pdf](https://github.com/nvaccess/nvda/files/46383/nvda.log.11-28-2015.pdf)

**Comment by leonardder** [comment] 2018-03-23 20:41
I removed a duplicate comment.

@netblue44: Could you provide a status update? I can't reproduce this using Notepad in de Windows 10 fall creators update.

**Comment by Brian1Gaff** [comment] 2018-03-24 10:49
Just in case this is relevant. There has always been a certain flakyness 
about save dialogues in nvda. If you tab to  some parts then speech stops 
unless you switch away and   back again as if its lost its way. I see it a 
lot in Windows 7 dialogues on office, Goldwave and others apparently 
randomly always a change away and back seems to restore the  system. Not 
tried extracting a log though.

Its a bit like when a browser does not see the page in nvda till you open 
and close a menu.
 Brian

**Comment by ehollig** [comment] 2018-10-25 23:52
I am going to close this as we have not heard from @netblue44 and others on if this issue still exists. I am not able to reproduce this in notepad either as @leonardder and @jcsteh have expressed.

**Closed by ehollig** 2018-10-25 23:52 UTC
