### ISSUE TITLE
NVDA won't read clipboard over a certain limit

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#10546] opened 2019-11-26 00:18 UTC
NVDA says "the clipboard contains a large portion of text" when pressing NVDA-C to read aloud the clipboard's contents if it contains what I gather is more than 1000 characters. I don't understand the purpose of this limitation. I suggest either removing it entirely or allowing the user to adjust the threshold at which it will no longer read the clipboard's contents.

**Comment by josephsl** [comment] 2019-11-26 01:23
Hi, surprise: you are not the only one requesting this change (I think there is an issue noted on GitHub that asks the same thing i.e. duplicate). Thanks.

**Comment by Luke-Robinett** [comment] 2019-11-26 16:24
OK, sounds good. Sorry for the duplicate. There are only tens of thousands of issues posted so I can be forgiven for missing it. :)

**Comment by josephsl** [comment] 2019-11-26 17:00
Hi, don’t worry about making duplicates – even I myself (a long time contributor) forget that what I think is new is actually a duplicate. Thanks (duplicate of #5573).

**Closed** 2019-11-26 17:02 UTC
