### ISSUE TITLE
Title displaying on Braille Display not Updating to Current Folder Selection in File Explorer

### ISSUE THREAD

**Issue by travisroth** [nvaccess/nvda#7225] opened 2017-05-30 13:10 UTC
Steps to reproduce:
1. Open File Explorer.
2. In the folder tree, browse to a different folder and press Enter to select it. 
3. Observe on Braille display that the new title of the window which shows the selected folder is not updated. The Braille display shows the old title.
Note: I am using File Explorer with Display Current Path set to off. I am not certain if this is significant.
Expected: 
The Braille display should display the current title when it is displaying the tile of the window, in this case selected folder. (This is also needed to confirm the new folder was selected/opened.)

NVDA 2017.2
OS: Windows 10 Creators Update

**Comment by leonardder** [comment] 2018-03-24 15:55
@travisroth: Can you still reproduce this? There have been some changes to braille since your report.

**Comment by travisroth** [comment] 2018-03-26 19:33
Using NVDA 2018.1 the issue is still present in File Explorer, Windows 10 Pro.

**Comment by Adriani90** [comment] 2020-05-05 20:04
@travisroth how is this now in NVDA 2020.1 RC1 and Windows 10 1909 Update? Do you have the braille display tethered to review cursor or to system focus?

**Comment by travisroth** [comment] 2020-05-15 15:43
Using NVDA 2020.1 and Windows 10 Pro and Braille tethering automatic this appears to be working. 

Selecting a new folder in the folder tree in File Explorer then pressing NVDA+t is showing the correct tile on the braille display.

**Comment by Adriani90** [comment] 2020-05-15 16:17
Thanks for the reply. I am closing this issue as works for me. Please comment on this if the issue appears again and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-15 16:17 UTC
Labels: close/worksforme, component/braille
