### ISSUE TITLE
Expanded/collapsed state fails to read

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#6401] opened 2016-09-22 23:20 UTC
STR:
1. Open Firefox and browse to http://heydonworks.com/practical_aria_examples/#progressive-collapsibles
2. In browse mode, press enter on First title in block of content

I should hear expanded, but I hear nothing. Same for collapsed.

**Comment by jcsteh** [comment] 2016-09-23 00:39
Firefox is regenerating the accessible for that button when it expands/collapses. So, instead of firing a stateChange, it fires focus on a "new" accessible. See Mozilla bugs [https://bugzilla.mozilla.org/show_bug.cgi?id=659886](659886) and [1285862](https://bugzilla.mozilla.org/show_bug.cgi?id=1285862).

If it were a stateChange, NVDA would report it. Instead, NVDA suppresses reporting the focus event because it's at the same position in the document (and not doing this would result in a lot of duplication when moving around).

**Comment by jcsteh** [comment] 2017-06-06 23:51
Actually, this is a duplicate of #5247 as far as NVDA is concerned (even if the CSS which triggers this behaviour is different).

**Closed by jcsteh** 2017-06-06 23:51 UTC
Labels: needsExternalFix
