### ISSUE TITLE
Skype: Call Skype option cannot be activated directly

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#5986] opened 2016-05-22 05:38 UTC
Steps to reproduce
1 Open a contact’s chat window in Skype.
2 Tab over to the Call button and press it.
3 Now, a sort of menu appears with two options:
Call Skype (default focus)
Call mobile (phone number)
4 Your focus, as NVDA reports, since is already on Call Skype, and assuming that is what you require anyways, try to activate it using Space or Enter.
Actual Result: Nothing happens.
Expected Result: The call should have been made.

Note: When you arrow up to the Call mobile option, or then arrow back to Call Skype, both can be activated normally, but it is only the first time that the default focus does not activate Call Skype for unknown reasons.

Test Environment
Windows 8.1 Pro 64 bit
Skype™   Version 7.23.0.105 (downloaded from Skype’s official website and not the built in system app)

**Comment by Adriani90** [comment] 2019-01-12 15:17
I cannot reproduce this in Skype UWP and the design changed totally in Skype 8. @bhavyashah, @k-kolev1985 are you able to test if this is still an issue in Skype 8?

**Comment by Adriani90** [comment] 2019-02-24 19:05
I am closing this issue since it is not reproducible in Skype 8 either. @bhavyashah please comment on it if you don't agree and we can reopen it. Thanks.

**Closed by Adriani90** 2019-02-24 19:05 UTC
Labels: p3
