### ISSUE TITLE
NVDA do not announce the state of check box selection

### ISSUE THREAD

**Issue by WiproCRMAccessibility** [nvaccess/nvda#9191] opened 2019-01-23 09:31 UTC
Open attached HTML. Start NVDA and then follow these steps.
1) Navigate to item and click/press Space, The aria-selected flag is updating. But NVDA is not reading that as selected/non-selected.

[ariaSelected.zip](https://github.com/nvaccess/nvda/files/2786547/ariaSelected.zip)

**Comment by cabeln** [comment] 2019-09-03 11:15
The observation was made on Edge browser.

**Comment by Adriani90** [comment] 2020-04-20 20:04
This works as expected in Edge Cromium 81. Since this will be distributed broadly through the Windows Update 20 H1, I will close this issue as works for me.

**Closed by Adriani90** 2020-04-20 20:04 UTC
Labels: app/edge, close/worksforme

**Comment by Adriani90** [comment] 2020-04-30 20:29
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
