### ISSUE TITLE
Chrome, NVDA not reading any alt= for http://www.ebay.com/rpp/graduation

### ISSUE THREAD

**Issue by time4testing** [nvaccess/nvda#5965] opened 2016-05-19 04:20 UTC
NVDA is not able to read any of the alt="  " text when they actually were coded http://www.ebay.com/rpp/graduation.  I say that because all screens for ebay it was not always coded properly.  I noticed that it doesn't read the text for social media icons when the text appears over the icon.  This is for google chrome, I haven't tried using any other browser yet to see if the same thing happens.  On the www.ebay.com, the entire first page doesn't get read at all, even when text appears underneath the picture, nothing is getting read out loud at all for images or any text either.  All the text in the bottom frame of the screen, not sure if font or font size makes a difference.

**Comment by Adriani90** [comment] 2019-02-24 19:33
@time4testing are you still available to reproduce this issue? The design of the ebay website has changed significantly and the site is actually very accessible now. Can you confirm?

**Comment by Adriani90** [comment] 2019-12-14 17:42
I cannot reproduce this issue and we calso lost contact to the initial author. Closing as works for me.

**Closed by Adriani90** 2019-12-14 17:42 UTC
Labels: p3, worksforme
