### ISSUE TITLE
No support for Access bridge in Java 10 and above

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#9384] opened 2019-03-18 15:08 UTC
### Steps to reproduce:

1. Install JDK V11 x64. oracle has stopped producing x86 versions since V10.
2. Enable the Java access bridge from control panel
3. Restart NVDA. The log indicates that "java access bridge is not available".
4. Attempt to use software such as [Ghidra](https://www.nsa.gov/resources/everyone/ghidra/), which requires V11.

### Actual behavior:

Access bridge not found, nothing is read. My understanding is that if there is no corresponding x86 version of java, NVDA won't work with access bridge support.

### Expected behavior:

Access bridge works with NVDA, so there is some hope for such applications to be usable.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-16922,11a5fd57

#### Windows version:
1803

#### Name and version of other software in use when reproducing the issue:
JDK 11.0.2, Ghidra 9

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by jcsteh** [comment] 2019-11-19 10:45
Duplicate of #7724.

**Closed by jcsteh** 2019-11-19 10:45 UTC
