### ISSUE TITLE
add a way to copy rendered web content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5028] opened 2015-04-09 20:14 UTC
**Reported by Sukil on 2015-04-09 20:14**
Currently, the selection and copying in webpages copies the text in the virtual buffer of NVDA. Maybe some other command or a toggle could be added to copy the actual rendered HTML, as if NVDA was not running.
Thanks.

**Comment by leonardder** [comment] 2017-08-12 09:29
Closing as duplicate of #5354, which has already been triaged.

**Closed by leonardder** 2017-08-12 09:29 UTC
Labels: enhancement
