### ISSUE TITLE
NVDA and support of Citrix

### ISSUE THREAD

**Issue by andersbp** [nvaccess/nvda#11217] opened 2020-05-29 10:48 UTC
I am confused about if NVDA alreaddy support connection and run from Citrix-servers, where clients connect to Citrix and run NVDA from there server with speechs and braille or not?

Thanks in advance for your answer, and have a nice day.

Regards,
Anders

**Comment by leonardder** [comment] 2020-05-29 17:16
This is possible with the UnicornDVC software from Access4U. See https://www.nvaccess.org/product/unicorndvc/

cc @engineeringmario 

Having said that, this issue is a duplicate of #3564. Closing as such.

**Closed by leonardder** 2020-05-29 17:16 UTC
