### ISSUE TITLE
When in browse mode, pressing e doesn't move the user to the next edit field if that edit field is read only.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5551] opened 2015-11-29 03:01 UTC
When in browse mode, the user cannot move to the next read-only edit field with e or f.

## reproduce:

1. Go to <www.github.com/nvaccess/nvda>.
2. Press e to go through edit fields.
3. Note how NVDA reports no more edit fields when it is hasn't passed over the edit field for the clone url.
5. Pressing e should move the user to the edit field with the clone url in it.

**Comment by Laughingthunder** [comment] 2015-11-29 04:23
What URL are we supposed to go to? It seems to be missing from the 
original report.

**Comment by derekriemer** [comment] 2015-11-29 05:27
Darn. Github's <> renders html but normal markdown allows links between &lt; and &gt; to render as links. So markdown wizzards: from now on, just paste urls in normally and github will take care of them.

It was github.com/nvaccess/nvda

**Comment by Laughingthunder** [comment] 2015-11-29 05:33
Oh! I see. Thanks for clarifying.

**Comment by derekriemer** [comment] 2015-12-02 09:46
I just wanted to make sure that because of the url issue this didn't 
somehow fly under the radar.

On 11/28/2015 10:33 PM, Laughingthunder wrote:
> Oh! I see. Thanks for clarifying.
>
> On 11/28/2015 11:27 PM, derekriemer wrote:
> > Darn. Github's <> renders html but normal markdown allows links between
> > < and > to render as links. So markdown wizzards: from now on, just
> > paste urls in normally and github will take care of them.
> >
> > It was github.com/nvaccess/nvda
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5551#issuecomment-160372898>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5551#issuecomment-160373152>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment] 2016-04-24 15:08
Hi guys, 
Is this issue recognized?

**Comment by leonardder** [comment] 2016-04-25 07:10
I'd also like this to be fixed.

**Comment by derekriemer** [comment] 2016-05-17 06:37
Hi,
Did this get missed?

**Comment by Brian1Gaff** [comment] 2016-05-17 07:58
Should it do so if you cannot alter it?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by parhamdoustdar** [comment] 2016-05-17 08:12
The definition for the `e` key is "edit field". It doesn't say anything 
about it being alterable, so I'm guessing the answer is yes, it should 
move you to it even though you can't change the contents.

**Comment by ruifontes** [comment] 2016-05-17 17:12
I agree!
Some fields of read-only text are important...

Rui


-----Mensagem Original----- 
De: Parham Doustdar
Data: terça-feira, 17 de maio de 2016 09:12
Para: nvaccess/nvda
Assunto: Re: [nvaccess/nvda] When in browse mode, pressing e doesn't move 
the user to the next edit field if that edit field is read only. (#5551)

The definition for the `e` key is "edit field". It doesn't say anything
about it being alterable, so I'm guessing the answer is yes, it should
move you to it even though you can't change the contents.


On 5/17/2016 12:28 PM, Brian1Gaff wrote:
> Should it do so if you cannot alter it?
> Brian
>
> bglists@blueyonder.co.uk
> Sent via blueyonder.
> Please address personal email to:-
> briang1@blueyonder.co.uk, putting 'Brian Gaff'
> in the display name field.
> ----- Original Message -----
> From: "derekriemer" <notifications@github.com>
> To: "nvaccess/nvda" <nvda@noreply.github.com>
> Sent: Tuesday, May 17, 2016 7:37 AM
> Subject: Re: [nvaccess/nvda] When in browse mode, pressing e doesn't move
> the user to the next edit field if that edit field is read only. (#5551)
>
>
> > Hi,
> > Did this get missed?
> >
> > ---
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/nvaccess/nvda/issues/5551#issuecomment-219631790
>
> -
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nvaccess/nvda/issues/5551#issuecomment-219646041>
>



-

**Comment by derekriemer** [comment] 2016-05-17 17:23
>Should it do so if you cannot alter it?
Yes.

**Comment by bhavyashah** [comment] 2016-05-17 18:17
Hi,
I also find an HTML control which is read as a section that is
editable by NVDA. I believe that perhaps too should be within the
scope of an element navigable by the 'e' key.
Thanks.

On 5/17/16, derekriemer <notifications@github.com> wrote:
>  >Should it do so if you cannot alter it?
> Yes.
>
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5551#issuecomment-219790656


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by leonardder** [comment] 2016-07-05 14:24
Formally, this seems to be a duplicate of #4164. It seems that most people here agree on including read only edit boxes into quick navigation with E.

**Comment by jcsteh** [comment] 2016-07-06 01:18
Duplicate of #4164.

**Closed by jcsteh** 2016-07-06 01:18 UTC
Labels: duplicate
