### ISSUE TITLE
Thunderbird reading extra information when opening an email

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16146] opened 2024-02-08 05:59 UTC
### Steps to reproduce:

Open Thunderbird
Navigate to an email
Press ENTER to open it.

### Actual behavior:

I send a message to myself with the subject "This is a test".  After ENTER is pressed, NVDA reads:

Home - Mozilla Thunderbird
This is a test - Mozilla Thunderbird
unknown
This is a test - Mozilla Thunderbird
This is a test  grouping
This is a test
This is a test

It then starts reading the contents of the message.

The title bar isn't visible, but pressing NVDA+t while the message is open reads "This is a test - Mozilla Thunderbird".  The "This is a text grouping" line, I'm guessing comes from Mozilla opening messages in tabs by default.  There is a tab header with "This is a test" (the subject of the message).

### Expected behavior:

Most users would expect the subject to be read once.  Even appreciating that the title and grouping also contain the subject, I would argue we could maybe read the window title (probably can't avoid that) but ideally cut out the rest - 5 times is definitely overkill.

The Mozilla enhancements add-on may help with this?  I didn't try it, (would be good to hear from someone who uses it) but we may also be able to improve how NVDA works in Thunderbird as well.

#### NVDA version:

NVDA 2024.1 Beta 7 installed

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.3007 

#### Name and version of other software in use when reproducing the issue:

Mozilla Thunderbird, Version: 115.7.0 

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Reported by a user running NVDA 2023.3.3

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

**Comment by XLTechie** [comment] 2024-02-08 06:53
cc @emitche

**Comment by emitche** [comment] 2024-02-12 14:24
Thanks, I won't be working at MZLA after today, so I won't be able to help with Thunderbird at this time.

**Comment by Adriani90** [comment] 2024-02-20 21:18
Closing as duplicate of #1776.

**Closed by Adriani90** 2024-02-20 21:18 UTC
Labels: close/duplicate, p4, bug/double-speaking, app/thunderbird, triaged
