### ISSUE TITLE
Aria-sort doesn't work in edge

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6978] opened 2017-03-15 15:28 UTC
Visit https://dequeuniversity.com/library/aria/tables/sf-sortable-grid
Move to the table.
Now, read the column headers, and click one.
In Narrator, aria-sort is properly indicated (But not in scan mode). In NVDA, this information is omitted.

**Comment by derekriemer** [comment] 2017-03-15 15:29
CC @michaelDCurran

**Comment by jcsteh** [comment] 2017-03-15 23:33
aria-sort is only exposed in UIA via the AriaProperties property.

**Comment by Adriani90** [comment] 2020-04-19 12:41
This works as expected with NVDA Version: alpha-20015,56a62097, Firefox 75, Crome 81and Edge Cromium 81. Closing as works for me.

**Closed by Adriani90** 2020-04-19 12:41 UTC
Labels: app/edge, close/worksforme, p3

**Comment by Adriani90** [comment] 2020-04-30 21:33
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
