### ISSUE TITLE
Lots of intermittent errors while using Microsoft Edge with NVDA

### ISSUE THREAD

**Issue by akash07k** [nvaccess/nvda#12189] opened 2021-03-17 17:35 UTC
### Steps to reproduce:
1. Install edge beta/dev/caneri
2. Install NVDA latest snapshot
3. Turn on NVDA
4. Open edge
5. Navigate casually and observe
### Actual behavior:
Whenever we navigate the web or open the edge or go to the address bar, we get tons of errors and error sounds
### Expected behavior:
No errors should be thrown
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Latest alpha snapshot
#### Windows version:
Win 10 21332
#### Name and version of other software in use when reproducing the issue:
Edge
#### Other information about your system:
I'm attaching the logs which I got while browsing the web, opening edge and going to address bar.
#### Does the issue still occur after restarting your computer?
yes, always
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes
[edge.txt](https://github.com/nvaccess/nvda/files/6158389/edge.txt)
[Log1.txt](https://github.com/nvaccess/nvda/files/6158450/Log1.txt)
[Log2.txt](https://github.com/nvaccess/nvda/files/6158453/Log2.txt)

**Comment by akash07k** [comment] 2021-05-28 07:29
Yes, It still reproduces

**Comment by leonardder** [comment] 2021-05-28 08:53
Could you test the try build for #12475?

**Comment by akash07k** [comment] 2021-05-28 09:16
Sure, please give me some time.

**Comment by akash07k** [comment] 2021-05-28 15:18
Hi, I can't find the link to download the try build, can you please
let me know that where do I find that?

**Comment by CyrilleB79** [comment] 2021-05-28 20:49
Here it is:
[nvda_snapshot_pr12475-22946,37f5649f.exe](https://ci.appveyor.com/api/buildjobs/xohn2wgijbs21s34/artifacts/output%2Fnvda_snapshot_pr12475-22946%2C37f5649f.exe)

**Comment by akash07k** [comment] 2021-05-29 18:47
Yes, the issue is fixed with this try build.
thanks a lot for your work

**Comment by akash07k** [comment] 2021-06-02 12:52
In my opinion this should be merged into master.

**Comment by CyrilleB79** [comment] 2021-06-02 13:25
Yes, it has been merged (cf. #12475)

If the issue is resolved in [latest master build](https://ci.appveyor.com/api/buildjobs/g5ipj1gdomewcdjn/artifacts/output/nvda_snapshot_alpha-22975,c9bb993e.exe), you can close this issue. Thanks.

**Comment by akash07k** [comment] 2021-06-02 16:02
Sure, I'm closing it and going to download latest master
> Yes, it has been merged (cf. #12475)
> 
> If the issue is resolved in [latest master build](https://ci.appveyor.com/api/buildjobs/g5ipj1gdomewcdjn/artifacts/output/nvda_snapshot_alpha-22975,c9bb993e.exe), you can close this issue. Thanks.

**Comment by leonardder** [comment] 2021-06-02 16:05
I don't think it's yet merged into master. We need another merge from beta into master

**Comment by akash07k** [comment] 2021-06-02 16:38
Yes, I checked, it is not merged

**Closed** 2021-06-03 03:23 UTC
