### ISSUE TITLE
After installing NVDA version alpha-21895 and restarting, the speech synthesizer gives an error.

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#12158] opened 2021-03-12 01:54 UTC
### Steps to reproduce:
First from [here](https://ci.appveyor.com/api/buildjobs/9o1gdgmukmhqm49t/artifacts/output%2Fnvda_snapshot_alpha-21895%2C52bf1ed6.exe) Download the installation package and run steps 
Then restart NVDA to get the error
### Actual behavior:
NVDA will play an error tone
### Expected behavior:
NVDA starts normally
#### NVDA installed/portable/running from source:
install version
and
Portable 
#### NVDA version:
NVDA version alpha-21895,52bf1ed6
#### Windows version:
Microsoft Windows [version 10.0.19042.867]
#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
none
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
#### If add-ons are disabled, is your problem still occurring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not in the scope of this tool
log:
[nvda.log](https://github.com/nvaccess/nvda/files/6127093/nvda.log)

**Comment by josephsl** [comment] 2021-03-12 01:57
Hi, since speech.*Command attributes were marked as deprecated in the past, this is normal behavior (at least based on compatibility policy). Ideally speech synth makers should provide workarounds (I’ll alert the add-ons community). Thanks.

**Comment by Brian1Gaff** [comment] 2021-03-12 08:07
The latest alpha does not run sapi 4 but 5 and speech platform work, but 
sometimes trigger error tones when they load.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by fernando-jose-silva** [comment] 2021-03-15 18:58
The rh voice synthesizer and the Brazilian Portuguese leticia voice are also not working correctly after upgrading to the last alpha.
The voice cuts out several lines while browsing windows.
Can someone from nv acces assist in communicating with rh voice maintainers to provide a correction.
Thank you very much.

**Comment by lukaszgo1** [comment] 2021-04-09 09:11
@dingpengyu From your log it looks like the errors are caused by synnth driver add-on, but in the pr description you've stated that this can be reproduced with add-ons disabled. Assuming that this is still reproducible could you please try one more time with add-ons disabled and report back.

**Comment by dingpengyu** [comment] 2021-04-09 09:20
> @dingpengyu From your log it looks like the errors are caused by synnth driver add-on, but in the pr description you've stated that this can be reproduced with add-ons disabled. Assuming that this is still reproducible could you please try one more time with add-ons disabled and report back.

The error will not occur after stopping the plugin altogether.

**Comment by lukaszgo1** [comment] 2021-04-09 09:23
Since this is caused by add-ons please close this issue here, investigate which add-on is causing the problem and report it to its author.

**Closed** 2021-04-12 04:46 UTC
