### ISSUE TITLE
Inconsistent escape key behavior in addon store dialog and addon updates available dialog

### ISSUE THREAD

**Issue by cyrmax** [nvaccess/nvda#16964] opened 2024-08-05 21:02 UTC
### Steps to reproduce:
1. Open NVDA add-on store;
2. Install any add-on on the available add-ons tab or update one of add-ons on the updatable tab;
3. Close the add-on store window with escape key (important to close the window not with close button but with escape key);
4. Notice that your add-ons are being installed or updated after closing the window and finally NVDA suggests to restart;
5. Install some outdated add-on version and restart NVDA to receive an "add-on updates available" window;
6. Press update all, wait until add-on status changes to "downloaded pending install" and close the window with escape key.

### Actual behavior:
The dialog closes without installing any add-on; add-ons stay not changed.

### Expected behavior:
Behavior of escape key in add-on store window and add-on updates window should be the same and either in both cases apply add-on changes or in both cases discard and ignore them.
The behavior should be consistent.

### NVDA logs, crash dumps and other attachments:
N/a

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
NVDA 2024.3 beta 4

#### Windows version:
Windows 11 24H2 (AMD64) build 26100.1301

#### Name and version of other software in use when reproducing the issue:
N/a

#### Other information about your system:
N/a

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tried

#### If NVDA add-ons are disabled, is your problem still occurring?
N/a, because if all add-ons are disabled the update window does not appear.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2024-08-06 01:35
Hi - I cannot reproduce this issue. In my testing NVDA correctly applies the install on the escape key, i.e. the expected behaviour.

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2024-08-15 01:43
Closing as works for me until further information is provided

**Closed by seanbudd** 2024-08-15 01:43 UTC
Labels: close/worksforme, bug/regression, p3, blocked/needs-info, triaged, feature/addon-store
