### ISSUE TITLE
Nvda reverses word order

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7262] opened 2017-06-07 13:42 UTC
Good morning everyone.
I'm using nvda and windows in the Portuguese language of Brazil.

### To Reproduce
- Create in windows explorer a folder with the name of abril
- when arriving in this folder with the arrow keys

### Actual behaviour
nvda first reads the folder number inside the list in the example that I will sitar next this folder is the number 2 inside From the folder list, and then reads the folder name that in the case is Abril.

### Expected behaviour
When correct would be that the nvda reads the name of the folder and then the number of her order inside the list of folders.
My guess is that nvda is processing the name of the folder as a date, since in Portuguese the word Abril is the name of the 4th month of the year, plus it is also the name of a company.

There is another situation where I found an inverted words.

### To Reproduce
- Change the language of windows and nvda to portuguese brazil.
- Also use a synthesizer in Brazilian Portuguese.
- Open a folder in windows explorer and create a folder.
- Open this created folder and inside it create two folders, one with the name of 1 and the other with the name of Abril.
- Walk with the arrows to the Abril folder.

### Actual behaviour
NVDA reports:
2 de Abril de 2.

### Expected behaviour
NVDA reports:
Abril 2 de 2

Another situation where this occurs.

### To reproduce
- Open the word.
- Paste in a line of the word the data: `A59103 Tifvil9981 *`
- Now press arrow.

### Actual behaviour
Notice that the nvda first reads the word:
Tifvil9981 *

### Expected behaviour
When the first word that should be read was:
A59103

The word example is not hypothetical, it is a list of users and passwords.

### version Information
- NVDA Master 14090 (reproduced with other verifications of nvda.
- Windows 7 64bits (I also played on windows 10.
- I used the second test in word 2013, but I also reproduced in word 2016.

**Comment by ruifontes** [comment] 2017-06-07 14:44
Hello!

The problem is the comma insertion to split chunks of text sent to the 
synthesizer and Vocalizer having as standard to date read the US format, 
Abril, 2 de 2...

Rui


-----Mensagem Original----- 
De: fernando-jose-silva
Data: 7 de junho de 2017 14:42
Para: nvaccess/nvda
Cc: Subscribed
Assunto: [nvaccess/nvda] Nvda reverses word order (#7262)



Good morning everyone.
I'm using nvda and windows in the Portuguese language of Brazil.
It happens that when creating in windows explorer a folder with the name of 
abril when arriving in this folder with the arrow keys, nvda first reads the 
folder number inside the list in the example that I will sitar next this 
folder is the number 2 inside From the folder list, and then reads the 
folder name that in the case is Abril.
When correct would be that the nvda reads the name of the folder and then 
the number of her order inside the list of folders.
My guess is that nvda is processing the name of the folder as a date, since 
in Portuguese the word Abril is the name of the 4th month of the year, plus 
it is also the name of a company.
There is another situation where I found an inverted words.
Here's how to play the two situations.
Change the language of windows and nvda to portuguese brazil.
Also use a synthesizer in Brazilian Portuguese.
Open a folder in windows explorer and create a folder.
Open this created folder and inside it create two folders, one with the name 
of 1 and the other with the name of Abril.
Walk with the arrows to the Abril folder and see that the nvda says:
2 de Abril de 2.
When the correct one would pronounce Abril 2 de 2
Another situation where this occurs.
Open the word.
Paste in a line of the word the data:
A59103 Tifvil9981 *
Now press arrow.
Notice that the nvda first reads the word:
Tifvil9981 *
When the first word that should be read was:
A59103
The word example is not hypothetical, it is a list of users and passwords.
View of nvda
Master 14090 (reproduced with other verifications of nvda.
Windows 7 64bits (I also played on windows 10.
I used the second test in word 2013, but I also reproduced in word 2016.

**Comment by jcsteh** [comment] 2017-06-07 23:39
We don't use a comma. We use two spaces, which wouldn't normally be used to separate dates. I don't think there's anything we can do about this; Vocalizer simply shouldn't be interpreting this as a date given the double space.

Does this happen with eSpeak?

**Comment by fernando-jose-silva** [comment] 2017-06-08 20:13
Yes, I tested with eSpeak and the problem also occurred.
Sorry, but in new test, the problem is occurring on windows 7, on windows 10 15063.332 the problem did not happen, I remember that, unless I'm making a good mess, I remember that in previous versions of windows 10 this also happened.

**Comment by fernando-jose-silva** [comment] 2017-06-12 13:36
Strange, I still have the same problems, and the rooms to reproduce are these same.
I even re-everything and the problem continues, I disabled the add-ons.
I ran the tests on two machines, with windows 7 and 10.
Just reviewing this call I can already reproduce the problem.
In the log does not show, in the log it informs as if the output is correct.
Let's see if anyone else can help.
If I can help in any way, I am at your disposal, and thank you very much for checking.

**Comment by ruifontes** [comment] 2017-06-12 17:38
As far as I know, it only happens with portuguese or brazilian Vocalizer 
voices.

Rui

-----Mensagem Original----- 
De: Reef Turner
Data: 12 de junho de 2017 10:18
Para: nvaccess/nvda
Cc: ruifontes ; Comment
Assunto: Re: [nvaccess/nvda] Nvda reverses word order (#7262)



I tested this on my system, but could not reproduce either problem (in word, 
or with folder names).

First I took these steps:

By going to Control Panel -> Clock, Language and Region -> Change date, time 
or number formats set my formats to Portuguese (Brazil)
Set NVDA language to Portuguese (Brazil) also

The steps I took for the folder names issue:

Open Windows explorer in an empty temporary directory.
Create one folder called "1"
Create one folder called "Abril"
Use the arrow keys to select the first folder, then the second.

NVDA reports:
Abril 2 de 2

The steps I took for the issue in Word:

Open Word 2013
Create a new blank document
Paste in A59103 Tifvil9981 *
Press down arrow to read the whole line.

NVDA reports:
A59103 Tifvil9981 *

Using NVDA version next-14098,66f26bb2 with espeak-ng
Windows 10 Version 1607

Please let me know if there is some error in my steps to reproduce, or if 
anyone else can reproduce this?

**Comment by feerrenrut** [comment] 2017-06-13 02:06
Yes I should have mentioned I was using espeak. I will update my previous comment to mention that. However @fernando-jose-silva mentioned that the problem also occurs in espeak. @fernando-jose-silva when you re-tested this did you do so with espeak? How about Microsoft speech?

**Comment by fernando-jose-silva** [comment] 2017-06-13 03:30
Had reproduced the problem with espeak and nvspeak in espeak

Enviado do meu iPhone

**Comment by feerrenrut** [comment] 2017-06-13 03:55
@fernando-jose-silva would you mind testing with espeak again and send us the nvda log in debug mode? There must be something different in my settings or set up, the log will give us some more information about your setup, and allow us to mimic the actions you take. I just tried this again with the same build (master-14090,3c71fb34) as you were using (in case recent changes to espeak in next were affecting the behaviour). I was not able to reproduce with this build either.

Note: I also set my region and the NVDA language to Portuguese(Brazil) .

**Comment by fernando-jose-silva** [comment] 2017-06-13 18:22
Hello everyone.
I repeated the tests.
I'm running nvda next 14106 on windows 7 64bits.

In word 2013 I was able to reproduce the problem as I had informed using espeak, I attached a log as debugging.
As far as explorer, I could not reproduce the problem again executing the espeak, just executing the vocalizer exprecive 1.1 voice Luciana.
I also attached a log.
What changed from when I opened the call until today was the verdict of the nvda.
Thank you.
[logexplorer.txt](https://github.com/nvaccess/nvda/files/1072466/logexplorer.txt)
[logword.txt](https://github.com/nvaccess/nvda/files/1072465/logword.txt)

**Comment by Adriani90** [comment] 2019-02-04 14:32
I had a similar issue in Excel. @fernando-jose-silva if you still reproduce this issue, can you please look into your speech dictionary? Vocalizer voices automatically added some entries in my dictionary which caused this issue. Could you delete the entrie in the dictionary and see if the issue still occurs? Thanks.

**Comment by fernando-jose-silva** [comment] 2019-02-04 22:12
The problem in explorer is caused by your nuances.
Now the problem in word I still continue with it, I tried using the one-core voice pt-br Maria.
To test:
Set your nvda and windows to use the voice one core pt-br Maria.
Open a blank document in word:
type it
a50596 Fersil2915!
Now press arrow to read the line
I heard the typing:
Fersil2915! a50596
I could not find a dictionary for the voice vocalizer on my nvda.
Thank you very much.

**Comment by Adriani90** [comment] 2019-04-17 22:17
Unfortunately I cannot reproduce this issue in NVDA 2019.1.1. @fernando-jose-silva could you please test if you reproduce this issue on other machines as well? It might be something specific on your machine. Also please try to reproduce this issue with all addons disabled.

**Comment by fernando-jose-silva** [comment] 2019-04-18 12:26
I was able to reproduce only my second page, open a document in word, and paste the line:
A59103 Tifvil9981*
Now press an arrow and notice that the nvda changed the order of the codes, it read first:
Tifvil9981*
and then read:
A59103
most in the written line is in the order:
A59103
and then:
Tifvil9981*
Tested with speack ptbr and amirican.
Also tested with voices windows onecore ptbr.
Windows and word are in ptbr.
Also reproduced in chrome 73 when editing this text.
Finally the strangest thing is that in the log the codes are shown as if they have been read in the correct order.
Tested with disabled add-ons.
These codes were not random, the code:
A59103
is the network user of a user and the code:
Tifvil9981*
is your password, already revoked so they will not be exposed.
Thank you very much.

**Comment by fernando-jose-silva** [comment] 2019-04-18 12:29
I do not know why chrome insists on separating the * at the end of the code
Tifvil9981
with a space plus this space does not exist as this is a password.

**Comment by fernando-jose-silva** [comment] 2019-04-18 13:10
Perfect also solved after deleting entries in the dictionary as recommended by
@Adriani90 
As a suggestion in the nvda log when an expression was modified by an entry in the dictionary this could be reported, it would facilitate the resolution of this problem.

**Comment by Adriani90** [comment] 2019-04-18 21:45
Thanks very much Fernando for reporting back and for your suggestion. I will forward this directly to NV Access for further steps. Very appreciated.
Closing as works for me.

**Closed by Adriani90** 2019-04-18 21:45 UTC
Labels: worksforme
