### ISSUE TITLE
NVDA does't read new element after focusing from element with display="none" 

### ISSUE THREAD

**Issue by AnaBelochka** [nvaccess/nvda#11184] opened 2020-05-21 10:48 UTC
### Steps to reproduce:

https://jsfiddle.net/sup6Lm3f/4/ 
1. Focus into result window
2. Press tab to "Not Reading" button
3. Press SPACE or ENTER keys
4. NVDA does't read aria-label or text
5. Press tab to "Reading" button
6. Press SPACE or ENTER keys
7. NVDA reads aria-label or text

### Actual behavior:
NVDA does't read new element after focusing from element with display="none" 

### Expected behavior:
NVDA reads new element after focusing from element with display="none" 

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.1

#### Windows version:

Windows 10 Enterprise 64 bit 1909 version, OS build: 18363.720
Windows 10 Enterprise 64 bit 1903 version, OS build: 18362.836

#### Name and version of other software in use when reproducing the issue:

Mozila Firefox 76.0.1 version
Mozila Firefox 75.0 version

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Tried on other older version, but don't remeber version numbers. Behavior was the same.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment] 2020-05-23 07:55
Cc: @jcsteh

**Comment by Adriani90** [comment] 2020-05-23 10:03
I try to clarify a bit the steps to reproduce here:
1. Open the link in the description
2. In browse mode, press b until oyu land on "first button" which is the first focus
3. Press enter on it (the button will be hidden and no label is read)
4. Press tab, shift+tab and tab again, don't leave the div

Actual behavior:
Step 3: NVDA does not report the label (first focus). However I am somehow confused because there is also the label "11111" which is reported only in focus mode but not in browse mode when pressing enter on "first button".
Step 4. NVDA reports "second button" when pressing tab once, but does not report anything when pressing shift+tab and tab again in browse mode, although the focus lands on "second button" which is visible and reported correctly when pressing nvda+tab. In focus mode however it seems to work.
Expected behavior in browse mode:
Step 3, NVDA should report "first focus"
Step 4: NVDA should report "second button" when pressing tab after shift+tab.

In Chrome 83 this seems to work correctly.

**Comment by jcsteh** [comment] 2020-05-24 22:54
This is another instance of #6606. This would have been fixed by #8869, but that was reverted due to problems.

**Comment by Adriani90** [comment] 2023-09-12 22:15
Is this fixed now by #14611?

**Comment by Adriani90** [comment] 2024-11-19 18:22
I seems indeed this was fixed by #14611. Closing as works for me in NVDA 2024.4.1 and Firefox 132. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-11-19 18:22 UTC
Labels: close/worksforme
