### ISSUE TITLE
When I activate the open tab in Microsoft  word and Excel 2013 and navigate to recent items, I am told no recent items are present

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5296] opened 2015-08-19 14:57 UTC
**Reported by pranavlal on 2015-08-19 14:57**
When I navigate to the open tab in word and or excel 2013 and then move down to recent files, I am initially told that no such documents are present. 

programs: word and excel 20133
os=windows 7

**Comment by Qchristensen** [comment] 2016-10-21 01:41
Just to confirm:

a) I can reproduce this in Office 2016 as well
b) you need to have "Don't show the backstage when opening or saving files" NOT checked in the Save category of options  (I have negative options that require a double negative to explain like that)
and
c) this happens when there are recent items (it happens when there aren't recent items, but of course in that instance, it's not a bug!).  NVDA reads:

"Recent Documents  grouping
You haven't opened any documents recently.
Pick a place to browse for a document.
Today  grouping
firstdocument.docx"

(where "firstdocument.docx" is whatever the most recent document you had open was.  Ditto for Excel except replace document with workbook as needed).

**Comment by jcsteh** [comment] 2016-10-21 01:52
Looks like Word is exposing this incorrect message as help text via UI Automation. We should file a bug with Microsoft.

P3 because it's misinformation, but the fact that a file name is then read suggests that there are recent files after all.

**Comment by Adriani90** [comment] 2019-02-01 23:06
Did anyone fill a bug to Microsoft for this?
I can still reproduce it.
cc: @jcsteh, @Qchristensen

**Comment by Qchristensen** [comment] 2022-09-01 02:52
Apologies @Adriani90 - not sure why I never responded back in 2019.  In any case, I can confirm I had reported it to Microsoft back in 2019, and I have also reported it again to them today.

This issue is still present and reproduceable using Office 365 (64-bit) Version: 16.0.15427.20190 on Windows 11 (64-bit) Version: 21H2 (2009), Build: 22000.856.

I can also repro with Excel. It doesn't happen using Narrator

**Comment by Qchristensen** [comment] 2022-09-07 22:32
Update from Microsoft:

"This does appear to be an Office bug. When you navigate to the Recent tab, there is some helptext associated with the group of tabs that is exposed via the LegacyIAccessible.Help property.
...
If NVDA were to consume UIA only in this experience, this could be mitigated."

**Comment by Adriani90** [comment] 2024-10-03 23:16
@Qchristensen I cannot reproduce this issue in Microsoft Word or Excel MSO (Version 2409 Build 16.0.18025.20030) 64 Bit
with NvDA 2024.4 Beta on Windows 11 23 H2.
So it seems Microsoft fixed this, because I am not using UIA fully, but the setting is set to "only when necessary" in MS Word and it is disabled in MS Excel.

So it seems this is probably reproducible only on Office 2016.
cc: @CyrilleB79 could you please test in Office 2016?

**Comment by CyrilleB79** [comment] 2024-10-04 06:27
Still present on Microsoft® Word 2016 (16.0.5452.1001) MSO (16.0.5465.1000) 32 bits. I may test on a newer Office 2016 version tonight.

**Comment by CyrilleB79** [comment] 2024-10-04 21:54
On a newer Word 2016 version, namely Microsoft® Word 2016 MSO (Version 2409 Build 16.0.18025.20030) 32 bits, the issue is not present anymore.

My opinion is that, given the low priority (or rather severity in this case) and given the issue has been fixed in newer product versions by Microsoft, it's not worth fixing this in NVDA.

**Comment by Adriani90** [comment] 2024-10-05 01:03
Closing as fixed in Microsoft, and companies which still use Office 2016 will have to update to this new build due to security reasons.

**Closed by Adriani90** 2024-10-05 01:03 UTC
Labels: bug, close/worksforme, blocked/needs-external-fix, app/microsoft-office, p4, triaged
