### ISSUE TITLE
Audio settings with stereo headset (or speakers) - Send NVDA sounds on one side and the rest of Windows sounds on the other side

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12985] opened 2021-10-25 11:48 UTC
I have had this feature request in mind since many years. But I finally open this ticket thanks to another person [asking it](https://groups.io/g/nvda-fr/topic/son_de_nvda_seulement_d_un/86573343?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,86573343,previd=1635155623389494153,nextid=1631705229306738732&previd=1635155623389494153&nextid=1631705229306738732) on a French mailing list.

### Is your feature request related to a problem? Please describe.

When participating to audio-conferences on the computer, it's often confusing to have NVDA's vocal feedback mixed up with the audio stream of the conference.

### Describe the solution you'd like

NVDA audio stream is produced by synthesizer output but also beeps (progress bars, indent reporting) as well as other sounds such as focus/browse mode and spelling mistakes detection.
With a stereo headset or stereo speakers, it would be handy to have an option allowing to split the audio stream in two parts:
* NVDA audio stream on one side, (e.g. left ear)
* the rest of the computer's audio stream on the other side (e.g. right ear). That includes Windows sounds and sounds of the applications, which may include:
  * the audio stream of an aundio conference (Skype, Zoom, Teams either withe desktop application or in the browser)
  * the audio stream of audio or video editing/processing software (e.g. mp3DirectCut)

### Describe alternatives you've considered

* Maybe there is one or more applications that may already do this job; if yes, it would be good to reference it here.
* In this issue, we may also consider the opportunity to add this feature in an add-on.

But IMO it would be valuable to have this feature integrated in NVDA or in an add-on rather that an external application. It would allow many people to discover this feature even if they do not express the need clearly.
Also it would be a plus to have this feature available in a portable version of NVDA; I do not know if it is technically doable however.

### Additional context

Jaws 2022 will provide this feature (and that's what convinced me that this feature could be embedded in a screen reader). Below is a quote of its release notes ([What's new](https://support.freedomscientific.com/Downloads/PublicBeta)):

> Sound Splitter
> Earlier in JAWS and Fusion 2021, we introduced a way for users to lower the volume of JAWS speech independently of system audio to help make it easier to hear audio from other applications. Version 2022 takes this a step further by now allowing those using stereo headsets or speakers to route all JAWS or Fusion speech to one ear while routing audio from all other applications to the other ear. This helps make it easier to continue getting work done with JAWS while following along during a Zoom or Teams meeting, a Skype call, or a YouTube video.
> To split audio:
> 1. Press INSERT+SPACEBAR followed by V to activate the Volume layer.
> 2. Press B for Balance, and then do one of the following:
> ◦ Press LEFT ARROW to route JAWS Speech to the left and audio from all other applications to the right.
> ◦ Press RIGHT ARROW to route JAWS speech to the right and audio from all other applications to the left.
> ◦ Press UP ARROW to restore both JAWS speech and application audio to both channels.
> Note: Before attempting to split your audio, make sure your headset or speakers are properly oriented. For instance, if you route JAWS speech to the left and instead hear it in your right ear, your headset is most likely reversed.
> Once you split your JAWS speech and application audio, it remains in effect until you restart JAWS, or use the command to restore the audio balance.

I do not advocate for copying all features of Jaws in NVDA. But I think in this case that having this feature integrated in NVDA is a real plus.

**Comment by mltony** [comment] 2021-11-01 01:21
I've actually had this in my plans to implement this in one of my add-ons when time permits.
It appears this can be done via wasapi, there is IChannelAudioVolume interface that allows to control sound produced by other programs separately for left and right channels. But that would require calling some com interfaces, wihch I don't have much experience with. Another risk here is that I fear it might not work with Skype, since Skype might be using some fancy audio interfaces. And I would think that Skype and other VC apps must be the primary use case for this feature. Anyway, this requires some trial and error and some hacking. I'll update this thread if I manage to make it to work.

**Comment by mltony** [comment] 2021-11-13 22:18
Implemented in Tony's enhancements add-on. Sound splitting can be toggled by pressing NVDA+Alt+S.
https://github.com/mltony/nvda-tonys-enhancements/releases/download/v1.11/tonysEnhancements-1.11.nvda-addon

**Comment by nidza07** [comment] 2021-11-14 00:53
Thanks so much @mltony for this.
Might be better to move to your repo and create a separate issue, but there is currently one  case you are not handling.
If you enable sound split, and then quit NVDA, the rest of the audio remains on one side instead of being restored.
Now, if you start NVDA, NVDA goes to center obviously since sound split is no longer enabled, but the rest remains on one side.
Hope that is clear enough and that you can fix this in a future build.
Thanks once again for taking this up.

**Comment by cary-rowen** [comment] 2021-11-14 01:16
Thanks to tony’s efforts, it seems that the sound can only be fixed to the right at the moment,Can the left and right sides be realized?
In addition, when I enabled sound splitting, the other side was not completely muted.

**Comment by nidza07** [comment] 2021-11-14 01:17
@cary-rowen yes, if you go to NVDA's settings, under the Tony's enhancements panel, check the checkbox named Switch left and right during sound split. This will revert it, meaning that NVDA will be on the left and everything else on the right.

**Comment by cary-rowen** [comment] 2021-11-14 01:24
Wow! Thank you for your reminder, it might be better if addon allow the shortcut keys to switch between the left, right and disabled modes.

**Comment by mltony** [comment] 2021-11-16 18:35
In the next version I will make it restore sound before quitting NVDA.

**Comment by josephsl** [comment] 2022-05-02 06:58
Hi,

Partly resolved with add-ons from Tony and yours truly.

Thanks.

**Comment by cary-rowen** [comment] 2022-05-02 07:58
Hi, @josephsl 
Will it be a big challenge to bring 'sound spliter' into the NVDA core? Regarding the psutil module, is there any reason for NVAccess to reject it?
Also, I have to say that the sound separation in the 'NVDA Extensions Global Plugin' is more useful, It allows me to concentrate on the movie and subtitles, could you further enrich the functionality of the 'Sound Splitter'?

Thanks

**Comment by josephsl** [comment] 2022-05-02 08:17
Hi, I have no plans to work further on Sound Splitter, nor plan to bring this to NVDA Core as I’m about to accelerate my transition away from NVDA Core contributions. Thanks.

**Comment by mltony** [comment] 2022-05-02 17:10
Then what was the point of forking from Tony's enhancements? Initially 
you said that you'd fork specifically to prepare for merging into NVDA 
core PR.

**Comment by josephsl** [comment] 2022-05-02 17:39
Hi, indeed, the original intention was to test the feasibility of merging into Core if possible. But I realized that we can run into dependency issues (psutil, for instance), something we can work around by reminding ourselves to update dependencies annually if possible; a better solution is changing audio volume levels without use of additional dependencies. The bigger reason for not continuing with this work was due to life priorities – I’ve been letting go of add-ons to reduce workload. But the fundamentals of bringing sound splitting functionality to NVDA Core is present in our add-ons: app volume manipulation, nvwave changes, handling profile switches directly from nvwave module, and incorporating add-on settings to appropriate settings panel (likely speech panel). Thanks for your concerns (I’m sorry for bringing this news).

**Comment by Adriani90** [comment] 2023-05-04 21:00
@CyrilleB79 is this somehow a duplicate of #13818? I think there is more technical discussion going on, I wonder if we can close this one in favor of #13818.

**Comment by CyrilleB79** [comment] 2023-05-04 21:13
> @CyrilleB79 is this somehow a duplicate of #13818? I think there is more technical discussion going on, I wonder if we can close this one in favor of #13818.

I agree that the implementation of both issues may be based on the same functions. But the use cases are different.
The use case of the current issue is to have Sound Splitter add-on feature integrated in core. On the other side, #13818 seems a more general use case, with the possibility to mix among various channels. IMO it may be worth to keep both tickets open: NVAccess may accept/implement this one in core and want to keep #13818 in an add-on.

**Comment by CyrilleB79** [comment] 2023-05-20 13:41
There are already three add-ons that provide this feature: Sound Splitter (cc @XLTechie), Tony's Enhancements (cc @cary-rowen, @mltony) and NVDAExtensionGlobalPlugin (cc @paulber19).

WASAPI is now integrated in alpha and is activated by default. Unfortunately, from what I know, the authors or contributors of these add-ons have not yet found a compatible way to implement the sound splitting feature. If no solution is found, there is the risk that many user disable the WASAPI checkbox. In addition, unfortunately, we do not have a FeatureFlag on this feature to manage it more precisely.

Would this be the opportunity to include sound split it in NVDA? Is this something hard to do or not? If not and since you have worked recently on WASAPI, @jcsteh would you be interested in implementing it?

@seanbudd and @michaelDCurran what do
you think, especially regarding the risk that many users disable the checkbox to be able to use their sound splitting add-ons? Should you reconsider WASAPI enabled by default in 2023.2 and implement a feature flag for it?

**Comment by jcsteh** [comment] 2023-05-21 10:23
I'm not willing to implement the feature in its entirety, as that means figuring out the right user experience and interface and I just don't have the time to go back and forth on that. However, I might be able to make it possible for add-ons to do this easily. I could provide a setChannelVolume method on WavePlayer instances or something like that. I'd also need to know what extensionPoints would be required for an add-on to implement this without monkey patching. For example, I'm guessing we'd need actions for when a stream is opened, when it is stopped, etc.

Alternatively, I could implement the backend parts of this (setChannelVolume or similar) and someone else could implement the UX/UI for channel splitting, working with others to figure out the best UX/UI.

**Comment by cary-rowen** [comment] 2023-05-23 03:44
> Alternatively, I could implement the backend parts of this (setChannelVolume or similar) and someone else could implement the UX/UI for channel splitting, working with others to figure out the best UX/UI.

I think that would be nice too, that's enough, someone will be willing to put in the effort on the UI/UX side.

**Comment by CyrilleB79** [comment] 2023-05-23 06:41
> I'm not willing to implement the feature in its entirety, as that means figuring out the right user experience and interface and I just don't have the time to go back and forth on that. However, I might be able to make it possible for add-ons to do this easily. I could provide a setChannelVolume method on WavePlayer instances or something like that. I'd also need to know what extensionPoints would be required for an add-on to implement this without monkey patching. For example, I'm guessing we'd need actions for when a stream is opened, when it is stopped, etc.
> 
> Alternatively, I could implement the backend parts of this (setChannelVolume or similar) and someone else could implement the UX/UI for channel splitting, working with others to figure out the best UX/UI.

@jcsteh thanks for this proposal. Such contribution would be very helpful. Add-on authors or anyone wanting to implement it in core will be able to provide a GUI without any problem.

To help you, maybe add-on authors (@cary-rowen, @XLTechie and @paulber19) can indicate the functions and extension points taht they would need in the API. That is indicate the private functions they use in their add-on and the functions that they are monkey patching.

**Comment by XLTechie** [comment] 2023-05-23 08:50
@jcsteh Thank you for your consideration. We already have UI for this behavior, extant in at least three add-ons; though one of them, Sound Splitter, is an updated version of what was already being done in one of the others. @josephsl did that work, but I recently started maintaining it.

Based on my grasp of what's going on in the code used, we would definitely need channel based volume control as you mentioned, and probably the session notification Actions you talked about. I haven't looked into how WASAPI differs in the way it handles audio, so I don't know what else we would need, but that sounds like the minimum (and maybe also the maximum).

Below, I have pasted the most important code that is used to patch stable NVDA to accomplish this, minus the obvious parts that you can infer. The full sourcecode is [available here](https://github.com/opensourcesys/soundSplitter/blob/main/addon/globalPlugins/soundSplitter/__init__.py).

<details><summary>Code Excerpts:</summary>

```python
import ctypes
import types
import os
import core
import nvwave

winmm = ctypes.windll.winmm
originalWaveOpen = None

def noWASAPI_preWaveOpen(selfself, *args, **kwargs):
	global originalWaveOpen
	result = originalWaveOpen(selfself, *args, **kwargs)
	# All we care about is splitting sounds, so set volume to 100 percent always.
	volume = 100
	volume2 = int(0xFFFF * (volume / 100))
if not config.conf["soundSplitter"]["soundSplit"]:
		volume2 = volume2 | (volume2 << 16)
	else:
		if config.conf["soundSplitter"]["soundSplitLeft"]:
			pass
		else:
			volume2 = (volume2 << 16)
	winmm.waveOutSetVolume(selfself._waveout, volume2)
	return result

if not isUsingWASAPI():
	preWaveOpen = noWASAPI_preWaveOpen

def setAppsVolume(volumes=None, exit=False):
	from . pycaw.pycaw import AudioUtilities, IChannelAudioVolume
	if volumes is not None:
		leftVolume, rightVolume = volumes
	else:
		volume = 100
		# By default, if enabled, NVDA is on the right, left only is on the left
		if config.conf["soundSplitter"]["soundSplit"]:
			# If this option is set, NVDA is on the left, and right sounds are on the right
			if config.conf["soundSplitter"]["soundSplitLeft"]:
				leftVolume = 0
				rightVolume = volume
			else:
				leftVolume = volume
				rightVolume = 0
		else:
			leftVolume = rightVolume = volume
	leftVolume /= 100.0
	rightVolume /= 100.0
	audioSessions = AudioUtilities.GetAllSessions()
	for s in audioSessions:
		if (
			not exit
			and s.Process is not None
			and s.ProcessId == os.getpid()  # FixMe should this be here? (Luke)
		):
			continue
		channelVolume = s._ctl.QueryInterface(IChannelAudioVolume)
		if channelVolume.GetChannelCount() == 2:
			channelVolume.SetChannelVolume(0, leftVolume, None)
			channelVolume.SetChannelVolume(1, rightVolume, None)

soundSplitterMonitorCounter = 0

def soundSplitterMonitorThread(localSoundSplitterMonitorCounter):
	global soundSplitterMonitorCounter
	while localSoundSplitterMonitorCounter == soundSplitterMonitorCounter:
		if (
			not config.conf["soundSplitter"]["soundSplit"]
			or isUsingWASAPI()
		):
			return
		setAppsVolume()
		yield 1000

def updateSoundSplitterMonitorThread(exit=False):
	global soundSplitterMonitorCounter
	soundSplitterMonitorCounter += 1
	if exit:
		setAppsVolume((100, 100), exit=True)
		return
	ss = config.conf["soundSplitter"]["soundSplit"]
	if ss:
		executeAsynchronously(soundSplitterMonitorThread(soundSplitterMonitorCounter))
	else:
		setAppsVolume()

def executeAsynchronously(gen):
	"""This function executes a generator in such a manner, that allows updates
	from the operating system to be processed during execution.
	Specifically, every time the generator yields a positive number,,
	the rest of the generator function will be executed from within wx.CallLater().
	If the generator yields a value of 0, then the rest of the generator
	will be executed from within wx.CallAfter().
	This allows clear and simple expression of the logic inside the generator body,
	while still allowing NVDA to process update events from the operating system.
	Essentially the generator will be paused every time it calls yield, then the updates will be
	processed by NVDA and then the remainder of generator function will continue executing.
	"""
	if not isinstance(gen, types.GeneratorType):
		raise Exception("A generator is required")
	try:
		value = gen.__next__()
	except StopIteration:
		return
	# FixMe: The below line may require a rewrite as multiple Flake8/lint errors are raised.
	l = lambda gen=gen: executeAsynchronously(gen)  # NOQA
	core.callLater(value, executeAsynchronously, gen)

updateSoundSplitterMonitorThread()

class GlobalPlugin(globalPluginHandler.GlobalPlugin):

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		global originalWaveOpen
		if not isUsingWASAPI():
			originalWaveOpen = nvwave.WavePlayer.open
			nvwave.WavePlayer.open = preWaveOpen

	def terminate(self):
		global originalWaveOpen
		updateSoundSplitterMonitorThread(exit=True)
		if not isUsingWASAPI():
			nvwave.WavePlayer.open = originalWaveOpen
		super().terminate()  # Probably unnecessary but maybe needed in the future
```
</details>

**Comment by jcsteh** [comment] 2023-05-23 11:22
It looks like you already have everything you need in the setAppsVolume function. NVDA's main output (usually just speech) and sounds are now in separate sessions. You can get the session GUIDs using nvwave.defaultSession.guid and nvwave.soundsSession.guid. You could adjust the channels for those sessions as needed.

That said, it'd obviously be better if this wasn't done with monkey patching in future.

**Comment by jcsteh** [comment] 2023-05-23 11:26
Now I'm realising you don't even want to separate NVDA speech from NVDA sounds. But I don't understand why you have the monkey patching winmm path when you have setAppsVolume which can already adjust all channel volumes, including NVDA. Can you explain?

**Comment by XLTechie** [comment] 2023-05-24 01:43
@josephsl can you explain, as you were the one who (re)wrote this code?

I am a bit perplexed about why some of this is being done. I know what's being 
done, but not why it has to be.

And I haven't had time since taking over to take the code back down to bedrock, 
and figure out what breaks when it's done in a more straight forward way. The 
code documentation is somewhat lacking.

**Comment by josephsl** [comment] 2023-05-24 02:29
Hi, the code was originally written by Tony Malykh as part of his Tony’s Enhancements add-on and I simplified it somewhat. I know that it patches parts of nvwave to provide channel splitting functionality by manipulating app volume. Thanks.

**Comment by mltony** [comment] 2023-05-24 22:01
So the question is why do we need monkey patching in sound splitter, right?
It's been a while since I wrote that code and I see it's been modified since then. I see only a single place where it monkey patches nvwave.WavePlayer.open function. So this is needed to adjust volume of NVDA output - it appears to require _waveout object and we need to adjust volume for every _waveout object in NVDA.
As to why we cannot use pycaw and Com interface magic to adjust NVDA volume the ansewr is simple: it doesn't appear to work. IIRC via that API I could successfully change volume of all the other apps, but not NVDA itself.

**Comment by XLTechie** [comment] 2024-01-16 10:47
The current Sound Splitter add-on (which I have been slow to update for WASAPI), 
has the ability to use the keysstroke to cycle between off, left, or right.

I suggest, for the audio settings panel interface, a combo box with the 
following options:

* Off

* NVDA on the right

* NVDA on the left

* Selected by keyboard

As an end result, the toggle/cycle key will either switch between off and left, 
off and right, or off, left, right, as it does now in the add-on.

Alternatively, this could be done with checkboxes:

* Enable NVDA on the right

* Enable NVDA on the left

If both are checked, then the shortcut works to cycle through all three options. 
Otherwise it is a toggle between off and the selected option.

Note: I don't care about these names, they are only for example to make clear 
what I am suggesting.

I thought of doing something like this in the add-on when I updated it, but 
depending on when this feature appears, I likely won't bother.

**Comment by mltony** [comment] 2024-01-16 22:51
@michaelDCurran, @seanbudd, since  guys closed my other issue, I would like to align with you here on the following two issues before I can start implementing this:
> 1. Sound Splitting can be achieved using wasapi by adjusting the volume of all running applications and setting left volume to zero, while setting NVDA right volume to zero (or vice versa). So I will need to call wasapi COM objects. I would need to implement interfaces in Python for these objects. I am not very familiar with Python interoperability with COM, and I haven't found a way to automatically generate Python stubs for COM interfaces, so I propose to copy relevant interfaces from PyCaw library. The library is published under a permissive MIT license and based on Google v. Oracle case a couple of years ago - APIs are not copyrightable. An alternative solution could be including PyCaw library as a dependency, but I personally think this would be an overkill.
> 2. In order for sound split to work properly, we would need to monitor audio sessions and if new audio sessions appear, we'd need to adjust their volume. I propose to create a new thread for that. The thread would be checking all audio sessions every second and adjust volume of new ones.
So do I have green light on copying Com APIs from PyCaw library and to create a new thread within NVDA - that thread would only be active as long as sound split is active?

**Comment by michaelDCurran** [comment] 2024-01-17 02:05
Yes, we would accept the comtypes COM interface definitions from pyCaw. As long as the file clearly stated where it came from.
A thread also sounds fine to me, but obviously more review can occur once a pr is opened or drafted.

**Comment by XLTechie** [comment] 2024-01-17 10:12
@mltony Have you looked at how NVDA Global Extension add-on is doing this for 
WASAPI? I believe @CyrilleB79 suggested I use the same method in Sound Splitter, 
and perhaps there is an approach there you can utilize some part of.

**Comment by CyrilleB79** [comment] 2024-01-17 21:45
> @XLTechie, what exactly are you talking about? I looked at global extension a while ago and the guy just copied relevant code from Tony's Enhancements. So yeah, I'm familiar with that approach because I wrote it in the first place.

In the meantime, NVDA Global Extensions' sound splitting capability works both with wASAPI. If I am not mistaken, Sound Splitter and Tony's Enhancements instead have only sound splitting working when WASAPI is disabled.
Hence the suggestion to look at NVDA Global Extensions add-on.

Cc @paulber19 in case you have some advice to give.

**Comment by paulber19** [comment] 2024-01-18 08:50
All I can specify is that today, the "NVDAExtensionGlobalPlugin" add-on 
no longer includes a single line of code from the "TonyEnhancements" 
add-on and that only the pycaw library is used to control the volume of 
NVDA channels and applications.
The add-on works with Wasapi enabled or not.

**Closed** 2024-03-06 04:38 UTC
Labels: p5, triaged
