### ISSUE TITLE
NVDA trapped in navigation mode when refreshing page with jQuery UI datepicker

### ISSUE THREAD

**Issue by sesopenko** [nvaccess/nvda#6939] opened 2017-03-06 18:22 UTC
When a user selects a date using a jQuery UI datepicker, focuses the text box containing the date, then refreshes the page, the focus jumps to the text box (expected) but the screen reader is trapped in a navigation mode.

Steps to reproduce:

1.  Browse to a page with just a jQuery UI datepicker attached to a text field
2.  Select a date using the datepicker
3.  Move focus to the text box (ie:  tab or click)
4.  Refresh the browser
5.  press backspace to delete the last digit of the year
6.  Press 1

Expected results:  year portion of date is 2011
Actual results: "No next heading at level 1" is spoken by the screen reader and the number pressed isn't entered into the input box.

OS:  Windows 10 (10.0.14393 Build 14393)
Browser:  IE11 (11.576.14393.0)
NVDA 2016.4

**Comment by ehollig** [comment] 2017-09-15 01:07
@sesopenko, is this still an issue? If so, is this issue specific to Internet Explorer or can you reproduce it in other browsers as well? If you could provide an example of the date picker as well, it would assist others in testing and verifying the issue.

**Comment by Adriani90** [comment] 2019-04-08 15:21
@sesopenko this is actually not an issue in NVDA. Every page is loaded in browse mode by default and it changes automatically to focus mode when moving the virtual cursor with arrow keys or tab over an edit field etc. Now in NVDA 2019.1, in browse mode settings you can enable focus mode by default. This will cause browse mode not to be activated anymore after loading  a page.
@leonardder solved this in #8846. 
Thus, closing as works for me.

**Closed** 2019-04-08 15:21 UTC
Labels: worksforme
