### ISSUE TITLE
NVDA Does Not Always Refresh the Screen With Dynamic Content in Chrome

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#10801] opened 2020-02-19 19:55 UTC
### Steps to reproduce:

1. With Chrome running, visit:
https://lenovo.com/
2. Click on "Laptops"

### Actual behavior:

Nothing happens

### Expected behavior:

NVDA act as if a new page has loaded.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3

#### Windows version:

10 64 bit

#### Name and version of other software in use when reproducing the issue:

Chrome Version 80.0.3987.106 (Official Build) (64-bit)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

This only started happening after I updated to NVDA 2019.3 from 2019.2.1. NVDA 2019.2.1 worked just fine.
I have not tested on 2019.2.1 since I updated.

### Other Comments

To get the page to load I need to press NVDA F5, then something will happen and when I hit up and down arrow keys, I hear "blank". If I then hit tab, I will hear the content of the new page.

**Comment by Novalis7747** [comment] 2020-02-21 12:37
confirmed with 2019.3.1 and latest Chrome. This also applies for other sites as well.

**Comment by Timtam** [comment] 2020-02-24 13:23
Can confirm that this behaviour started somewhere close to the 2019.3 release. I'm always running the latest alpha and I remember that it started happening close to Chrome releasing V 80, so I was under the impression that this update is the culprit here. This bug however is rather annoying on dynamically generated websites by forcing you to always press F5 to show the new website, which also resets you to the top of the page in several cases, requiring you to search where you stopped reading.

**Comment by Qchristensen** [comment] 2020-02-25 00:45
From some testing myself (news.com.au seems a "good" site to test this on - it either happens when going from the main site to an article, or when going from an article back to the main site).

This also happens with NVDA 2019.2.1, which seems to confirm it is a change in Chrome rather than NVDA.  It can be tricky as Chrome updates in the background without input from the user, and when something happens around the time NVDA releases an update, it can be easy to think it's something with NVDA.

Comments on the NVDA email group suggest this issue affects Jaws as well.

**Comment by Novalis7747** [comment] 2020-02-25 08:09
Confirmed. Same under 2019.2.1. I tested portable beta google chrome Version 81.0.4044.26 (Official Build) (32-bit) and the problem is gone for all sites I noticed it before.

**Comment by Qchristensen** [comment] 2020-02-25 23:33
Going on @Novalis7747 comment both confirming that this is an issue in Chrome, and further that it appears to be fixed in Chrome 81, is it worth closing this issue?

Looking at https://www.chromestatus.com/features/schedule Chrome 81 is due for Stable release on March 17

**Comment by Adriani90** [comment] 2020-02-26 20:48
Closing as fixed in Chrome 81 Beta. Thanks for reporting.
@Qchristensen yes this should be ok, this is consistent with what we are also doing with Firefox issues.

**Closed by Adriani90** 2020-02-26 20:48 UTC
