### ISSUE TITLE
nvda when with the option to use uia in word does not report comments

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10768] opened 2020-02-07 15:43 UTC
### Steps to reproduce:
in the advanced options of nvda check the option to use the uia in word.
Open a document in word with a comment.
Press nvda + alt + c to read the comment.
### Actual behavior:
the nvda is mute.
### Expected behavior:
nvda should read the comment.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
alfa 19633
#### Windows version:
10 1909 18363.628
#### Name and version of other software in use when reproducing the issue:
Aplicação: WINWORD.EXE, Microsoft Office 16.0.12325.20344

#### Other information about your system:
everything works well if you uncheck the option to use uia in word.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by zstanecic** [comment] 2020-02-07 15:48
Hi,

This is a dupe of some issue and

Someone is working on pr

**Comment by DrSooom** [comment] 2020-02-08 08:59
Duplicate of issue #9285.

**Comment by Adriani90** [comment] 2020-02-09 21:49
closing as duplicate

**Closed by Adriani90** 2020-02-09 21:49 UTC
Labels: duplicate
