### ISSUE TITLE
Reads href after clicking on anchor tag in Firefox 

### ISSUE THREAD

**Issue by DzmitryAlifer** [nvaccess/nvda#6573] opened 2016-11-17 08:30 UTC
I have this item on a page `<a role="option" href="[looong url]">My Item</a>`

After clicking on this item in Firefox in **regular mode** NVDA reads:
> document busy
> [looong url from browser's address bar]
> application
> My Item 

When I click on the item again it doesn't read the url (desired behavior):
> document busy
> blank
> application
> My Item 

In the meantime when I do the same thing in Firefox in **private mode** it reads every time as expected:
> document busy
> blank
> application
> My Item 

Is that an expected difference in FF behavior for regular and private modes?

**Comment by feerrenrut** [comment] 2016-11-17 13:04
@jcsteh What are your thoughts here?

**Comment by jcsteh** [comment] 2016-11-18 00:37
I can't reproduce this with the following steps:

1. Open this URL: `data:text/html,<a href="http://google.com/blah" role="option">Go</a>`
2. Click "Go".

I never hear a URL get announced. It'd be good if you could provide a test case which reproduces this.

**Comment by feerrenrut** [comment] 2016-11-18 06:35
To be clear @jcsteh. There is not any expected differences between private and non-private browsing in Firefox?

I seem to be able to reproduce this with FireFox 49.0.2 using the following steps to reproduce:

1. Open this URL: `data:text/html,<a href="http://google.com" role="option">Go</a>`
2. Click "Go".

_Notice that the link is now a page that exists._ 

Then (copied from speech viewer) I get:

```
document
Mozilla Firefox
http://192.168.185.20:8080/CustomerInfo/Customer?mdn=6288219260693&user-agent=Samsung&url=http%3A%2F%2Fgoogle.com%2F&lac=2205&ci=57604895&mode=444  busy
http://192.168.185.20:8080/CustomerInfo/Customer?mdn=6288219260693&user-agent=Samsung&url=http%3A%2F
%2Fgoogle.com%2F&lac=2205&ci=57604895&mode=444
Google  busy
link
Screen-reader users, click here to turn off Google Instant.
```

I'm not sure where that URL is coming from.
Interestingly once I have done this once the URL part is not reported again. If I clear my recent history it does happen again. My guess is that there is a permanent redirect on `http://google.com`. Since I'm in Indonesia, I get redirected to `https://www.google.co.id`

Running this again, with network monitoring on within Firefox developer tools, I do get a response status code of 302.

This URL is not reported in private mode.

If I change the "go" link to point to `https://www.google.com` I also do not get the URL reported.

After updating to FireFox 50.0 I no longer see this behaviour.

I assume that this happened during the redirect because firefox triggers two page load events. One for the redirect (indeed I was seeing a number show on the screen for a fraction of a second, too quick to read) and then the resulting page. If the first page load does not have a page title, the URL is used instead?

**Comment by jcsteh** [comment] 2016-11-18 06:48
I'm not aware of any differences between private and normal browsing that
should cause this, no.

@DzmitryAlifer, what version of Firefox were you testing this with?

**Comment by DzmitryAlifer** [comment] 2016-11-18 07:45
@jcsteh I've updated Firefox from 49.0.2 to 50.0 and I'm still able to reproduce it.

**Comment by feerrenrut** [comment] 2016-11-18 08:02
@DzmitryAlifer could you give us an example which reproduces it for you in Firefox 50.0?

**Comment by DzmitryAlifer** [comment] 2016-11-18 08:44
@feerrenrut here is the full example of one of the items
```
<a  ng-if="::!menuItemVM.config.isNested" 
      ng-href="attendance#/dataView?pageId=502" id="502_link" 
      title="Attendance" 
      ng-click="menuItemVM.selectMenuLink()" 
      class="selected" 
      tabindex="0" 
      ng-class="{'selected': menuItemVM.config.isSelected}" 
      role="option" 
      aria-setsize="2" 
      aria-posinset="2" 
      aria-labelledby="502_text" 
      aria-selected="true"  
      ng-attr-target="{{::menuItemVM.target}}" 
      automation-id="attendanceMenuLink" 
      href="attendance#/dataView?pageId=502">
           <span id="502_text" ng-if="::menuItemVM.config.text">Attendance</span>
</a>
```

**Comment by DzmitryAlifer** [comment] 2016-11-24 07:34
Hello guys! Do you have any updates regarding this issue?

**Comment by feerrenrut** [comment] 2016-11-25 09:54
Sorry @DzmitryAlifer I am not able to reproduce this issue using your example. I have to set a valid `href` URL, and remove all the angular specific stuff (eg `ng-if`) because I do not have an angular project set up. This leaves me with the following which does not reproduce the issue for me:

`data:text/html,<a  id="502_link"        title="Attendance"                class="selected"        tabindex="0"         role="option"        aria-setsize="2"        aria-posinset="2"        aria-labelledby="502_text"        aria-selected="true"          automation-id="attendanceMenuLink"        href="https://www.google.com">            <span id="502_text" >Attendance</span> </a>`

If you could provide a test case that reproduces this issue that can be pasted into the address bar without relying on external dependencies that would really help us out when looking at this issue. This issue is likely caused by something in firefox, for us to look into this and perhaps raise a bug with them we really need a solid repo case.

Something in the form `data:text/html,<body>Your example here</body>`

**Comment by ehollig** [comment] 2017-11-21 00:59
I am not able to reproduce this issue with the example provided in https://github.com/nvaccess/nvda/issues/6573#issuecomment-262920009. @DzmitryAlifer, is this still an issue with Firefox, and if so, could you provide a working example without the angular specific stuff and a valid href URL?

**Comment by Adriani90** [comment] 2019-03-18 22:02
@DzmitryAlifer are you still having this issue in Firefox 65.0.2 with NVDA 2019.1 RC^1?

**Comment by Adriani90** [comment] 2019-03-25 20:31
It seems the initial author is unfortunately not available anymore. We didn't get a response since three years. I am closing this issue. If we get the requested information from the author, we can reopen the issue. Thanks.

**Closed by Adriani90** 2019-03-25 20:31 UTC
Labels: blocked
