### ISSUE TITLE
sometimes when arrowing   around nvda won’t speak what’s under my curser

### ISSUE THREAD

**Issue by marrie** [nvaccess/nvda#11976] opened 2020-12-27 19:59 UTC
### Steps to reproduce:

1. Launch NVDA. This can be at start

2. Use NvDA as normal
3. When it wants to happen you can be using left right, or shift left and shift right to select. control left right has even done this behavior.

What happens is this. The curser will move but nvda won't speak. I've tried this with add ins   Dissabled, but since  a restart fixes it I can no longer reproduce after said restart. of system, or any time.
###Actual behavior:

Even though the curser is moving, the arrow keys won't read. I know this as I've been able to make edits and I can tell when theta re made as sometimes, not always, nvda will speak the selection.

### Expected behavior:

NVDA should not be doing this. I remember it did n't used to do this in I believe 2018.x. this has been happening for a few years now since about 19.x

###System configuration
#### NVDA installed/portable/running from source:
 Install not running from source.
#### NVDA version:
2020.3
#### Windows version:
2004-h
#### Name and version of other software in use when reproducing the issue:
n/a, this happens in any text editor, browser, email client.  This is a random bug.
#### Does the issue still occur after restarting your computer?
yes.
#### If addons are disabled, is your problem still occuring?
yes and no. No because a restart with or with out add ins disabled will fix the issue.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes. that was the first step I did.

**Comment by Brian1Gaff** [comment] 2020-12-28 11:22
I have noticed this too, but I put it down to some other windows process 
momentarily slugging the response. In your case does it eventually catch up 
or remain as a problem for ever till you restart nvda?

The short term catch up and occasional clicking in Espeak seem to be some 
kind of processor spike, but the loss altogether of an edit area is 
obviously something else. Strangely, sometimes  if it happens in a text 
editor. the opening of say, wordpad will fix it, at others not. This is in 
windows 7. I have also fixed this with a registry replacement reboot, which 
has cured it for some days. It is indeed strange and quirky, and no the only 
fault you got in earlier versions was occasional non reading of context 
menus, which seems fixed in the more recent versions of nvda..



bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by marrie** [comment] 2020-12-28 16:16
My machine has 32 gigs of ram, an i5 processor and I don't recall what 
display. My shadow machine for which this happens is an AMD  from this 
year, or at least the latest with 12 gigs of ram. This sometimes happens 
to me when I first start windows, sometimes not, sometimes at random 
when I'm on a web page,, never when I'm on a desktop. I've seen my arrow 
keys "freeze" when I'm in jarte, notepad, thunderbird, etc. I did upload 
a log to someone before but they did say it didn't help much as there 
didn't appear to be anything  wrong. They were also able to reproduce 
though.

**Comment by ridleymon** [comment] 2020-12-29 15:18
Every since I updated to 2020.3 my colleagues and I are experiencing no announcements when on browse mode using the arrows on plain text.  When on input field the reader gets stuck and won't move past the input field when pressing the down arrow.  Tab works fine.  The colleagues that didn't update are not experiencing these issues.

**Comment by marrie** [comment] 2020-12-30 17:48
the issue cropped up today, I'll attach the log, not that it will help.
[nvda-old.log](https://github.com/nvaccess/nvda/files/5755141/nvda-old.log)

**Comment by bhavyashah** [comment] 2021-01-16 01:23
I can confirm that I have recently been routinely facing a bugg in NVDA wherein NVDA stays silent when I make selection. Sometimes, it does occur in case of navigation too, but is much more frequently in case of selections. One instance where NVDA is quite consistent in failing to report Shift+left/right arrow selections is the message edit box on web.whatsapp.com.

**Comment by Adriani90** [comment] 2023-03-28 22:23
@marrie are you still having this issue in NVDA 2023.1?

**Closed** 2023-06-10 07:57 UTC
