### ISSUE TITLE
Reporting Of Marked (Highlighted) Text Should be Disabled By Default

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#11640] opened 2020-09-19 21:37 UTC
### Is your feature request related to a problem? Please describe.
I would not consider it to be a problem in the sense of that something is broken, however, I would consider it to be a change to address something that could be an annoyance to some.

Starting in NVDA 2020.3 beta 1, NVDA is able to report the marked state of text in web browsers, such as if text is emphasized or marked as strong, and this creates a lot of extra verbosity, especially on sites hosted by Microsoft, such as:
http://aka.ms/WindowsReleaseHealth (the Windows Release Health Dashboard in the "Issue Details" section), as well as their knowledge base articles for the optional non-security updates, such as the most recent one for Windows 10 version 1909:
https://support.microsoft.com/help/4577062
Under the heading "How To Get This Update", a ton of extra verbosity is present by default because NVDA says "Go to Strong settings not strong greater strong update and security not strong greater strong windows update not strong... and so forth.
Previously, this reporting was controlled by "Report Emphasis" being turned on. In NVDA 2015.4 when that feature was first introduced, it too was on by default, and in 2016.1 was disabled by default.

### Describe the solution you'd like

The solution I'd like to see is to still have this option available if people want to hear highlighted or marked text, but I don't think it should be on by default due to the extra verbosity it causes.

### Describe alternatives you've considered
I haven't thought about any alternatives since the option is either on or off (there's not really a middle ground).

### Additional context
I think it's nice to have this feature as stated previously, but much like the case with "Report Emphasis", I have a feeling that a lot of people won't like to hear all the extra verbosity generated by having this option on by default. I consider this option to be more of a proofing tool.

Thank you very much for your time and I look forward to any input you may have.

Sincerely,

Brandon Tyson

**Comment by fisher729** [comment] 2020-09-20 07:16
Hi.

I agree with the above. Personally, I think both options should be merged (emphasis and marked content), but for now, I think both should be disabled by default.

**Comment by dingpengyu** [comment] 2020-09-20 12:27
cc @feerrenrut 
and
@michaelDCurran

**Comment by CyrilleB79** [comment] 2020-11-04 14:33
I cannot reproduce. Did the pages change? 
Or is anybody else able to reproduce?

**Comment by btman16** [comment] 2020-11-04 18:19
Hello,

Last time I checked the pages, NVDA continued to report”Strong” and “Not Strong” when reading the Microsoft KB updates.

Is this on a fresh install of 2020.3?

Thanks,

Brandon

**Comment by CyrilleB79** [comment] 2020-11-05 11:07
@michaelDCurran wrote in #11436 initial description (known issues):

> Marked text is now reported by default in web browsers, where as previously, at least in Internet Explorer, you needed to turn on report emphasis. I would argue that marking (highlighting) is extremely important semantically, and should be reported by default, as this is used in many education scenarios including online exams. However, having it under report emphasis along with em and strong would cause many users to want to keep the option off, as those two other tags are used way too much (and sometimes inappropriately) on web pages.

It seems so that the intent was not to report strong formatting when checking the marked checkbox. strong formatting was intended to be controlled by the 'Emphasis' checkbox.
But the implementation seems to have a bug. Actually, the 'Emphasis' checkbox now does not control anything more! I am preparing a PR to fix it.

So when this is fixed, I suggest to keep 'Emphasis' disabled and 'Marked' enabled by default in Document formatting settings, following @michaelDCurran's clear arguments.

@btman16, would you reconsider your request if strong formatting is finally controlled by 'Emphasis' checkbox (disabled by default)?

**Comment by CyrilleB79** [comment] 2020-11-05 11:36
@btman16, one additional question: with which browser did you encounter this excessive verbosity? According to the code, it seems to me that only IE reported emphasis (emphasised or strong). Do you confirm this fact?
That would explain why I coud not reproduce this excessive verbosity, usually working on Firefox or Chrome.
Thanks.

**Comment by btman16** [comment] 2020-11-05 21:01
Hi,

1. Yes, I was in IE. I will check Firefox.

2. Yes, if "Strong" and "emphasized" can be again controlled with the emphasis checkbox, I would totally re-consider.

Thanks for following up,

Brandon

**Closed** 2020-11-06 01:21 UTC
