### ISSUE TITLE
Add a toggle to always report clipboard text

### ISSUE THREAD

**Issue by LarrySilvermintz** [nvaccess/nvda#11320] opened 2020-06-30 13:46 UTC
Situation:  When long text string is in clipboard, The Report clipboard function speaks the number of characters instead of the string itself.  Many people only want to hear the clipboard contents, without learning the size of that string.  Hearing the actual text regardless of size will make clipboard contents accessible.  This is especially useful to learn what was cut/copied, and to confirm what is in the clipboard before pasting it.  
Request:  Please provide this always read clipboard ability.

Steps to reproduce problem:  Place long text string into clipboard and activate Report clipboard function.

Solution:  Provide a setting, with two  choices:  either 
alternative (1) Report clipboard length for large text 
or else 
alternative (2) Always read the full clipboard without reporting length regardless of clipboard size.

Of course,  In all cases reading the clipboard contents can be curtailed using the "Stop speech" function.

**Comment by Adriani90** [comment] 2020-06-30 19:59
Tis does not work unfortunately without downsides. A big amount of text in the clipboard would impact performance directly if the text has to be chunked at once by the synthesizer. We had this discussion also previously in another issue. Actually, if you have a very long text in the clipboard, usually you don't want to listen to it since you know it already from the selection that you did before. If you are not sure, then you can just paste the text in an edit field and read it then with the usual reading commands. Currently NVDA supports reading of clipboard text up to 1023 characters, extending this number would impact some synthesizers directly in terms of performance.
Otherwise you can use the addon clipboard content designer:
https://addons.nvda-project.org/addons/clipContentsDesigner.en.html

I am closing this issue for now.

**Comment by JulienCochuyt** [comment] 2020-06-30 20:00
Sending potentially enormous chunks of text for speech used to lead to freeze or instability with many synthesizer.
@feerrenrut, is it still the case as of Speech Refactor?

An alternative approach, when the content exceeds a reasonable limit, might be an announce like:
"NNNN characters in clipboard, From <first few words> to <first last words>."

**Comment by Adriani90** [comment] 2020-06-30 20:02
Oops, ok let's reopen the discussion again. I was not considering the speech refactor although I don't know if this would be viable.

**Comment by JulienCochuyt** [comment] 2020-06-30 20:12
@Adriani90 wrote:
> Oops, ok let's reopen the discussion again. I was not considering the speech refactor although I don't know if this would be viable.

I'm not sure either. Of course, this request is an old standby, but let's first ensure if conditions have changed, as many users seem to praise for it...

**Comment by LarrySilvermintz** [comment] 2020-06-30 20:17
Thank you for your immediate reply.  For perspective, in Zoomtext  Say
clipboard" always works totally fine with my sinthesizer voice and is a
finction I really depended on.  Please, Is there some possible way to add it
as an option or some way to at least raise the limit value?

 

 

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by LarrySilvermintz** [comment] 2020-06-30 20:20
Please, At least to read the beginning of the clipboard instead of reporting
length.  Some indicator could be given such as saying "plus more" or "more
not spoken".

 

 

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by LarrySilvermintz** [comment] 2020-06-30 20:43
Thank you!

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by XLTechie** [comment] 2020-06-30 23:04
I would prefer to see a Press once for length, press twice for speak contents 
approach.

**Comment by LarrySilvermintz** [comment] 2020-06-30 23:28
Other way around, please, Predominant need is to hear just the content.  And
thank you for considering this feature!

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by XLTechie** [comment] 2020-06-30 23:31
If more users really want this, it could be useful to discuss how it might be 
done effectively and efficiently.

I agree with @Adriani90 that the text limit is there for a good reason.
There's nothing wrong with the current text limit imo. What is wrong is deciding 
that if there is more text than that, the user must only want to hear the number 
of characters.

  I was recently talking a very slow typist (not to mention very 
advanced in years) through some operations.

We had to perform a substantial copy action.

The clipboard already contained a large chunk of text before that copy, and it 
was unclear whether the copy would have worked in that element.

Rather than just hearing the number of characters (useless), even hearing the 
first 10 words would have told whether the copy was successful

Instead, I had to talk the user through opening a notepad session, paste in the 
huge text, and going to the top of it, to find out, then close and go on with 
the activity in question.

If it was me, doing it myself, it would have taken all of 10 seconds, and not 
been worth more than an annoyed thought. But trying to talk this person through 
it took at least a minute.

**Comment by feerrenrut** [comment] 2020-07-01 07:28
I think there is enough information on this issue to understand the core issues users face with this implementation.
I believe it was originally done this way to work around limitations with synthesizers, and accommodate the most common use case. I think it might be time to revisit this approach and see if it can be improved. Note there is also the new windows clipboard feature in Windows 10 `windows key+v` which may play into this.

**Comment by JulienCochuyt** [comment] 2020-07-01 07:41
@feerrenrut, do you know if Speech Refactor gives us more ability to send big amounts of text to the speech synthesizer?

**Comment by feerrenrut** [comment] 2020-07-01 07:55
I don't think that aspect has been specifically addressed, it may have been as a side effect. I think it will need some experimentation.

I think if we wanted to read a lot of text off the clipboard, something like the say-all for the clipboard would be a good idea. Taking the full content at once could result in a massive memory use. 

I like the idea of announcing the size and the first sentence as a starting point for fixing this. Then experiment with something like say-all for the clipboard triggered by a double tap. I think it is important to warn the user in this way, otherwise they have no idea how long it will take to speak the full clipboard contents.

**Comment by LarrySilvermintz** [comment] 2020-07-01 12:21
Thank you again, To reiterate, it is rare that the user ever wants to learn
the number of characters.  If the duration of the speaking is too long, the
user can simply curtail speech with the quiet command.

Therefore, once again, the simplest for the user is the setting that
functions start reading regardless of length and continue until curtailed by
user.

 

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by feerrenrut** [comment] 2020-07-02 17:01
Thanks for the input @LarrySilvermintz, however the number of characters is still considered useful to some. Not to learn the exact size, but as a very fast way to determine if a copy operation went wrong, copying much more than expected. For most users, the majority of copy operations are small snippets, several words or perhaps sentence or two. Quickly knowing that the copy was larger than this is the intent. The limit is currently 1024 characters, which I agree is too small. The number also gives an indication of how long it will take to hear the full contents. Though I think we should streamline the message by rounding down to the nearest 1000: "Clipboard contains more than 2000 characters"

**Comment by Adriani90** [comment] 2020-07-02 18:14
The solution propopsed by @XLTechie with one press = number of characters if the content is too long and second press = reporting the content completely, is already proposed in #5889. In fact, this issue is a duplicate of #5573. Note that there is also a somehow related discussion on #10709 but that alternative will not work consistently in applications due to inconsistent information about pasted text exposed to accessibility APIs.
Overall, I am closing this issue in favor of #5573 which contains also some different statements. Maybe it makes sense to continue discussions there.

**Closed by Adriani90** 2020-07-02 18:14 UTC
Labels: close/duplicate

**Comment by Adriani90** [comment] 2020-07-02 18:16
Regarding optional implementation (i.e. a toggle checkbox etc) this can also be discussed there after a consensus has been found wether it is possible to implement without downsides for users or not.

**Comment by Adriani90** [comment] 2020-07-02 18:17
Oops sorry the issue #5889 was about spelling, I was too fast on that..

**Comment by LarrySilvermintz** [comment] 2020-07-02 20:59
Then we are requesting a pull-down or radio button to choose the 

* simple and most logical function of just always reading only full
clipboard contents.  

* then any other choices y'all choose to have.  

 

Summary, the main option is, as specified, the simplest nost logical
behavior.  Just read what is asked, here it is the clipboard's full
contents, until curtailed or interrupted by the user.

 

 

Respectfully!

Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by LarrySilvermintz** [comment] 2020-09-10 20:39
Greetings.  Any chance that a toggle to always report full clipboard will be
implemented any time soon?  I'd be glad to contribute if that would help.

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____
