### ISSUE TITLE
Firefox: Table navigation stops working intermitently

### ISSUE THREAD

**Issue by blindpk** [nvaccess/nvda#16142] opened 2024-02-07 15:26 UTC
### Steps to reproduce:
Navigate in Firefox for a while, then try to navigate in a table with the Ctrl+Alt+arrow key commands. The time before the bug is appears is not consistent. The bug disappears if I restart NVDA or Firefox as far as I can tell.

### Actual behavior:

NVDA does note navigate in the table and the error sound plays.

### Expected behavior:

NVDA navigates as usual.

### NVDA logs, crash dumps and other attachments:
NVDA log attached.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30972,9717b815

#### Windows version:
Windows 11, latest updates

#### Name and version of other software in use when reproducing the issue:
Firefox 122

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The issue has been present for a few days and through several alpha versions

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[nvda.log](https://github.com/nvaccess/nvda/files/14195800/nvda.log)

**Comment by Adriani90** [comment] 2024-02-07 21:24
Please provide an example website where you can reproduce this issue. Is it also reproducible in Chrome or Edge?

**Comment by Adriani90** [comment] 2024-02-07 21:25
I cannot reproduce this issue with NVDA last alpha. Did you reproduce this with all addons disabled?

**Comment by Brian1Gaff** [comment] 2024-02-08 10:06
Is this only with the new 2024 version of nvda, or can you get it on the last release version as well? Are there some tables that will work, no matter what. Obviously a test site is helpful.
 The reason I ask is that occasionally, with certain sites, and older versions of everything, tables are quirky and I've been putting it down to dodgy coding of the web sites. 
Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: blindpk 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Wednesday, February 07, 2024 3:26 PM
  Subject: [nvaccess/nvda] Firefox: Table navigation stops working intermitently (Issue #16142)



  Steps to reproduce:
  Navigate in Firefox for a while, then try to navigate in a table with the Ctrl+Alt+arrow key commands. The time before the bug is appears is not consistent. The bug disappears if I restart NVDA or Firefox as far as I can tell.

  Actual behavior:
  NVDA does note navigate in the table and the error sound plays.

  Expected behavior:
  NVDA navigates as usual.

  NVDA logs, crash dumps and other attachments:
  NVDA log attached.

  System configuration
  NVDA installed/portable/running from source:
  Installed

  NVDA version:
  alpha-30972,9717b815

  Windows version:
  Windows 11, latest updates

  Name and version of other software in use when reproducing the issue:
  Firefox 122

  Other information about your system:
  Other questions
  Does the issue still occur after restarting your computer?
  Yes

  Have you tried any other versions of NVDA? If so, please report their behaviors.
  The issue has been present for a few days and through several alpha versions

  If NVDA add-ons are disabled, is your problem still occurring?
  Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
  Yes
  nvda.log

**Comment by blindpk** [comment] 2024-02-08 15:02
I haven't been able to test much today, but so far the bug has not appeared at all today. To answer the questions, I have not tested thoroughly in other browsers, but I did a little testing in Brave when the bug was present and in Brave table navigation worked as it should. I have not tested without add-ons but I will do if the bug appears again. The same for older versions of NVDA. When the bug was present I tried many sites to see if it was site-specific, but I couldn't find any pattern for when it started. I'll write again if I find out more, but if the bug doesn't come back in a few days I'll close the issue.

**Comment by blindpk** [comment] 2024-02-09 11:34
The bug appeared later yesterday so now I've tested without addons. First I tested with all addons turned off and the bug did not appear, then I started with activating addons that *should* not have anything to do with browsing, Calibre, FileZilla, VLC and TesseractOCR, and everything worked fine but a few minutes agonow the bug appeared again, although it took a while. I attach the log of this session as well. Still no pattern of which website that causes it, as it is different each time.
[nvda2.log](https://github.com/nvaccess/nvda/files/14221084/nvda2.log)

**Comment by Neurrone** [comment] 2024-02-17 06:55
Is this a duplicate of #15862?

**Comment by blindpk** [comment] 2024-02-17 20:51
Reading up on that issue it seems like it, sorry for not finding that before reporting. The bug has not been as frequent during the last couple of days, but it still pops up sometimes. One site where it has happened multiple times is musicbrainz.org, when searching for an artist that give many results or looking up an artist with many albums, so in that case it seems to be triggered by large or complex tables, but it still doesn't happen all the time.

**Comment by Adriani90** [comment] 2024-02-18 17:42
Closing as duplicate of #15862.

**Closed by Adriani90** 2024-02-18 17:42 UTC
Labels: close/duplicate, p4, app/firefox, triaged
