### ISSUE TITLE
Regression in the ck editor which breaks rich text support

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6387] opened 2016-09-18 23:31 UTC
1. Open a page with ck editor.
2. When you hear application, press enter to access the editor.
3. Type some text, E.G. "Once upon a time, I went to Hawaii."
4. Select Hawaii, and press alt+f10. This brings up the ck editor toolbar.
5. pressing tab here brings you eventually to the link toolbar and button. Press the button to generate a link. Enter a URL, E.G. a link to Hawaii on Wikipedia.
6. Now that the editor again has focus, go to the end of the line. Try to read the current line in multiple ways. It reports Everything before "Hawaii" just fine. 
7. Press return and type "I saw a beautiful waterfall."
8. Try to read that text. Notice how NVDA only says up to, but not including the link start, and ignores everything else.
9. Save the page, In drupal, you do this by hitting save after exiting the application ck editor is in. 
10. Reload the page and try to edit the document in the same way. Notice how all the text reads as expected.
11. Go after the text

**Comment by leonardder** [comment] 2017-11-01 17:01
@derekriemer: Is this still reproducible? If so, could you explain why you think this is caused by NVDA and not by a bug in CK Editor, for example?

**Comment by derekriemer** [comment] 2017-11-02 00:08
Can't test. I don't have access to a drupal install now.

**Comment by Adriani90** [comment] 2019-03-08 23:14
@khsbory could you please test if this issue is still reproducible? Thanks!

**Comment by Adriani90** [comment] 2023-08-24 09:16
@derekriemer have you got by chance to test this and see if it is working? Especially in the last alpha of NVDA? I think there was some work on rich edit areas which might have impacted this positively.

**Comment by leonardder** [comment] 2023-08-24 14:03
CK Editor is a web editor, it has nothing to do with the rich edit changes made recently.

I'm going to close this as abandoned. Last report is from years ago and CK Editor is very likely to have received many, many updates since then.

**Closed by leonardder** 2023-08-24 14:03 UTC
