### ISSUE TITLE
nvda only reads out the first letter

### ISSUE THREAD

**Issue by JunyiXiao** [nvaccess/nvda#10239] opened 2019-09-17 19:33 UTC
### Steps to reproduce:
1. open any webpage in chrome
2. open developer tools
3. In Element tool Style Pane, tab into individual property name like this
![image](https://user-images.githubusercontent.com/47334233/65072992-ce160b00-d946-11e9-811d-e90dbd466005.png)

### Actual behavior:
NVDA reads "tree view, edit, selected b"

### Expected behavior:
reads out the whole property name, i.e. "selected background"

#### Name and version of other software in use when reproducing the issue:
Chrome

**Comment by Adriani90** [comment] 2019-09-19 20:51
Hello, if you go to nvda settings, and then to browse mode settings, you can adjust the number of characters per line. Could you please try different numbers? Does that make a difference when reproducing this issue?

**Comment by Adriani90** [comment] 2019-09-19 20:51
Hello, if you go to nvda settings, and then to browse mode settings, you can adjust the number of characters per line. Could you please try different numbers? Does that make a difference when reproducing this issue?

**Comment by JunyiXiao** [comment] 2019-09-19 21:27
Nope, it doesn't make a differences. The same problem still repros.

**Comment by Adriani90** [comment] 2020-05-27 19:56
@JunyiXiao This is not reproducible with NVDA 2020.1 in Chrome 83. Can you confirm?

**Comment by Adriani90** [comment] 2023-08-29 18:20
We didn't get any updates from the initial author since many years, I am closing this as works for me since I cannot reproduce it in Chrome 116 with NVDA 2023.2 RC.
Please comment on this if you are still having this issue and we can reopen.

**Closed by Adriani90** 2023-08-29 18:20 UTC
Labels: close/worksforme
