### ISSUE TITLE
Not include emojis in punctuation traitment

### ISSUE THREAD

**Issue by Oreonan2** [nvaccess/nvda#9700] opened 2019-06-09 13:09 UTC
Hello,
I think it is not good to include emojis in the punctuation traitment.
In my opinion, emojis are not punctuation but are just characters.
More, emojis are very usefull in communication now.
So, I think emoji should be considered as text and not as punctuation and I think the punctuation level should not affect the announcement of emojis.
What we think about this idea ?
Thanks.
PS: sory for my bad english

**Comment by DrSooom** [comment] 2019-06-10 03:07
Duplicate of issue #8826 and #9210.

**Comment by Adriani90** [comment] 2019-06-10 17:23
Closing as duplicate. Let's continue the discussion on #8826.

**Comment by Adriani90** [comment] 2019-06-10 17:24
@DrSooom thank you very much for your comment.

**Closed by Adriani90** 2019-06-10 17:23 UTC
Labels: duplicate

**Comment by Oreonan2** [comment] 2019-09-09 04:22
I think that approving the #9707 pull request, which has been waiting for a long time, would close that. This would also make some users happy and finally allow some contributors to feel useful :)
