### ISSUE TITLE
Add table navigation commands when editing tables in MS Power Point

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8002] opened 2018-02-15 15:17 UTC
Hello,

NVDA does not provide the usual table Navigation commands when editing a table in MS Power Point. Would it be possible to implement such a Feature?

Many thanks.

**Comment by leonardder** [comment] 2018-02-15 15:25
Are the tables detected as such when editing them?

**Comment by leonardder** [comment] 2018-02-15 15:30
Actually, closing as duplicate of #5350

**Closed by leonardder** 2018-02-15 15:30 UTC
