### ISSUE TITLE
getPossiblePorts error with Seika Notetaker driver

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#13121] opened 2021-12-02 09:24 UTC
### Steps to reproduce:
1. ctrl+nvda+a follow the usual steps to select the braille display.
2. Click the change button, Select Seika Notetaker in the combo box and press Enter;
3. Click the change button again;

### Actual behavior:
Perform step 2, the dialog box is closed, the device can display Braille, and an error sound is heard.
<details><summary>Log snippet
</summary><pre><code>
ERROR - unhandled exception (17:11:04.027) - MainThread (11824):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 3437, in onDisplayNameChanged
  File "gui\settingsDialogs.pyc", line 3419, in updatePossiblePorts
  File "braille.pyc", line 2429, in getPossiblePorts
ValueError: need more than 1 value to unpack
Perform step 3, the braille display selection dialog box is not opened, and the following log is generated:
ERROR - unhandled exception (17:19:19.400) - MainThread (6204):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 3328, in onChangeDisplay
  File "gui\settingsDialogs.pyc", line 194, in __init__
  File "gui\settingsDialogs.pyc", line 3380, in makeSettings
  File "gui\settingsDialogs.pyc", line 3411, in updateBrailleDisplayLists
  File "gui\settingsDialogs.pyc", line 3419, in updatePossiblePorts
  File "braille.pyc", line 2429, in getPossiblePorts
ValueError: need more than 1 value to unpack
</code></pre></details>

### Expected behavior:
Perform step 2 and there should be no errors.
Perform step 3 should be able to open the dialog box without errors.

#### NVDA installed/portable/running from source:
installed and portable

#### NVDA version:
2021.3rc1

#### Windows version:
Windows 10 21H2 (x64) build 19044.1387

#### Name and version of other software in use when reproducing the issue:
None

#### Other information about your system:
None

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA2021.2 has the same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2021-12-03 02:09
Hi @cary-rowen,

Could you do the following:
* Set the log level to DEBUG via the general settings panel
* enable `hwIo` logging in the advanced setting panel
* [collect the full log](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#log-files)

Feel free to email this to info@nvacces.org if you have any privacy concerns

**Comment by seanbudd** [comment] 2021-12-03 02:16
Just a correction the email is info@nvaccess.org

**Comment by cary-rowen** [comment] 2021-12-03 05:07
Hello @seanbudd 

I have sent an email to info@nvaccess.org, which contains a complete log. Besides, I am not very worried about privacy issues. I will also share a complete log here for others to review.

[log.txt](https://github.com/nvaccess/nvda/files/7646953/log.txt)

**Comment by cary-rowen** [comment] 2021-12-06 04:59
@seanbudd 
Hello,
Do you have any findings about this? Do I need to provide further useful information?

**Comment by cary-rowen** [comment] 2021-12-07 00:19
Hello,

I have a new discovery. Using Seika_Notetaker_addon will not reproduce this problem. I attached Addon below.
[Seika_Notetaker_addon_for_Mini16,24_Seika-V6,V7_SDPlusV3.3.nvda-addon.zip](https://github.com/nvaccess/nvda/files/7664353/Seika_Notetaker_addon_for_Mini16.24_Seika-V6.V7_SDPlusV3.3.nvda-addon.zip)

@moyanming Do you have any thoughts on this?

**Comment by moyanming** [comment] 2021-12-07 14:03
> Hello,
> 
> I have a new discovery. Using Seika_Notetaker_addon will not reproduce this problem. I attached Addon below. [Seika_Notetaker_addon_for_Mini16,24_Seika-V6,V7_SDPlusV3.3.nvda-addon.zip](https://github.com/nvaccess/nvda/files/7664353/Seika_Notetaker_addon_for_Mini16.24_Seika-V6.V7_SDPlusV3.3.nvda-addon.zip)
> 
> @moyanming Do you have any thoughts on this?

Hi, @cary-rowen 
I can reproduce your issue, NVDA 2021.3RC1,
I have selected the "Seika Notetakter" as a Braille display and works fine now. If I reopen the Braille settings dialog and click on the "Change..." button, there is no response, but the NVDA and Seika Notetaker is working fine now. Here is the log after exit NVDA
[can't click change button when exit nvda.log](https://github.com/nvaccess/nvda/files/7668791/can.t.click.change.button.when.exit.nvda.log)

But I found that there have another different log file when running NVDA when the issue reproduce
[can't click change button when nvda runing.log](https://github.com/nvaccess/nvda/files/7668819/can.t.click.change.button.when.nvda.runing.log)


![click Change button have no response](https://user-images.githubusercontent.com/13234209/145042637-09816ed8-3d0d-442e-a131-94c2c00fed56.jpg)

**Comment by seanbudd** [comment] 2021-12-08 00:41
Hi @cary-rowen - we are fairly confident as to what the problem is, based on the log you provided.

**Comment by feerrenrut** [comment] 2021-12-10 09:57
Hi @cary-rowen and @moyanming could you please test [this build](https://ci.appveyor.com/api/buildjobs/h89xxrp7yoee8air/artifacts/output%2Fnvda_snapshot_pr13156-24338%2C9b0d2467.exe) for me and let me know?

**Comment by moyanming** [comment] 2021-12-10 12:09
> Hi @cary-rowen and @moyanming could you please test [this build](https://ci.appveyor.com/api/buildjobs/h89xxrp7yoee8air/artifacts/output%2Fnvda_snapshot_pr13156-24338%2C9b0d2467.exe) for me and let me know?

Hi, @feerrenrut 
Thanks for your great job. I have tested [this build](https://ci.appveyor.com/api/buildjobs/h89xxrp7yoee8air/artifacts/output%2Fnvda_snapshot_pr13156-24338%2C9b0d2467.exe), Seika Notetaker with USB connection works fine now, the "Change..." button can be used too.
BTW, the accidentally disconnected USB cable of the Seika Notetaker issue is still not fixed and I have a report log file in #13143.
I have found that the Bluetooth COM Port selection has been added to this build, but the Bluetooth COM Port can't work and I have a report log file in #13142.

**Comment by cary-rowen** [comment] 2021-12-10 17:15
@feerrenrut
    My test results are the same as @moyanming's. The USB cable works normally, but Bluetooth cannot be used. However, through the Seika Notetaker Addon, both Bluetooth and USB cables work normally.
    BTW: If you select "Auto" in the port selection combo box, the connection will not succeed, even if the device has been connected to the computer via USB cable.

**Comment by feerrenrut** [comment] 2021-12-13 05:36
@moyanming and @cary-rowen from your comment it isn't clear if you are saying this change is an improvement (but there are still other problems), or if you are saying that this changes fixes some things but makes others worse. I don't want to hold back the point release on this, so you'll have to be very clear. Otherwise this change will go to the alpha builds to give more time for testing.

**Comment by moyanming** [comment] 2021-12-13 08:19
Hi, @feerrenrut 
I mean this issue #13121 which is the "Change..." button can't open dialog has been fixed.
Since the "Auto" added with "USB", "Bluetooth serial port", this "Auto" may be having issues according to @cary-rowen said.

There are have other issues, #13142 and #13143 already exist for a long time.

**Comment by feerrenrut** [comment] 2021-12-15 13:47
@cary-rowen and @moyanming  could you please test the following [try-build](https://ci.appveyor.com/api/buildjobs/ftl26sbf7vmwv6ml/artifacts/output%2Fnvda_snapshot_try-fixSeikaNtk-24357%2C83ca1974.exe).

**Comment by cary-rowen** [comment] 2021-12-16 01:07
@feerrenrut 
Hello, I use a USB cable to connect Seika Notetaker and everything works as expected, but when I use a Bluetooth connection, it fails to connect. The following is my error log. HWIO has been turned on.
However, the issue has been resolved. For Bluetooth issues, do we need to reopen an issue and bring the repaired issue to 2021.3.1?
[Log.txt](https://github.com/nvaccess/nvda/files/7723808/Log.txt)

**Comment by feerrenrut** [comment] 2021-12-16 10:42
Thanks for the update @cary-rowen. We can talk about Bluetooth on https://github.com/nvaccess/nvda/issues/13142

I'll look to include [these updates to the Seika Notetaker driver](https://github.com/nvaccess/nvda/pull/13156) in the point release.

**Comment by feerrenrut** [comment] 2021-12-16 12:13
@cary-rowen Could you please test [this try-build](https://ci.appveyor.com/api/buildjobs/1apjdpe359v2vrhd/artifacts/output%2Fnvda_snapshot_try-fixSeikaNtk-24362%2C7b768256.exe)

**Comment by feerrenrut** [comment] 2021-12-17 15:02
build of RC to test merged changes: https://ci.appveyor.com/api/buildjobs/pl56jgcjg2ym6xap/artifacts/output%2Fnvda_snapshot_rc-24378%2Ccaf14822.exe

**Comment by cary-rowen** [comment] 2021-12-19 12:52
Hello
@feerrenrut 
1. Use a USB cable to connect, and select Seika Notetaker in the dialog, then Seika Notetaker can display the content normally;
2. Selecting "Seika Notetaker" again in the dialog box will cause an error, causing Seika Notetaker to fail to display any content;
3. I have to repeat step (1) to make Seika Notetaker work normally.
[log.txt](https://github.com/nvaccess/nvda/files/7740816/log.txt)
@moyanming 
can you test this latest TryBuild?

**Comment by feerrenrut** [comment] 2022-01-10 05:33
As per https://github.com/nvaccess/nvda/pull/13156#issuecomment-993315287 this was resolved with f6d47c53a7672cb219451057a571d6af0d5cd809 via PR #13156

**Closed by feerrenrut** 2022-01-10 05:33 UTC
