### ISSUE TITLE
Suggestion: Warning that there is loaded a profile when you change settings.

### ISSUE THREAD

**Issue by javidominguez** [nvaccess/nvda#7530] opened 2017-08-27 07:10 UTC
When there is a profile loaded, if i change a setting, that only applies for current profile. It's right, but this can produce a bit of confusion When I want to change a setting globally. Sometimes I don't remember that there is loaded a profile. I'm aware of the error when I switch to another application.
I think it would be good to inform which profile to affect changes, for example, modifying the name of the menu "Preferences" by "Preferences (profile name)" when there is a profile loaded. Also, adding "(profile name" to the title of dialogs of settings.

**Comment by fisher729** [comment] 2017-08-29 06:14
Hi @javidominguez.
I believe #577 will tackle this issue you are having. A note, however, let's say you change your settings with keyboard shortcuts. It would not be intuitive for NVDA to identify the profile currently being edited. But, as said before. Have a look at the ticket, and possibly close if necessary.

**Comment by leonardder** [comment] 2017-08-29 13:56
To be specific, #3644 addresses the same issue and also proposes a suggestion, which will be implemented as part of #577. I"m closing this as duplicate of #3644.

**Closed by leonardder** 2017-08-29 13:56 UTC
Labels: Configuration profiles
