### ISSUE TITLE
2023.3 Beta 1: Version Numbering Scheme Is too Strict to Run Certain Add-Ons, For Example, RHVoice

### ISSUE THREAD

**Issue by ChrisDuffley** [nvaccess/nvda#15452] opened 2023-09-14 22:31 UTC
### Steps to reproduce:
* Download RHVoice from https://rhvoice.org/download/RHVoice-1.12.0.nvda-addon
* Install this add-on as normally done. When NVDA restarts, a prompt will appear, detecting that there are no voice add-ons installed and offers to go to the Languages page. Say Yes/Alt+Y (or download one directly, example voice is below).
* Download a voice, for this example, as this is affecting my use particularly, we'll use [BDL](https://rhvoice.org/download/RHVoice-voice-English-Bdl-4.1.2009.10.nvda-addon).
* Try to install the add-on, and it'll refuse and make the error sound. Accompanied by this, not surprisingly, an error is thrown (see the Logs/Dumps/etc heading for it)
### Actual behavior:
An error tone plays and is thrown in the log.

### Expected behavior:
Despite this odd versioning scheme, and anything like this being odd to NVDA, external add-ons regardless of what scheme is used should still install.

### NVDA logs, crash dumps and other attachments:
[RHVoice-NVDA-Error.txt](https://github.com/nvaccess/nvda/files/12614018/RHVoice-NVDA-Error.txt)
#### NVDA installed/portable/running from source:
Installed, but don't think it would matter.
#### NVDA version:
2023.3beta1
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3448

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The first time I've seen this be a problem is this beta version. All is normal on previous versions as far as I can remember.
#### If NVDA add-ons are disabled, is your problem still occurring?
No, as this is of course an add-on version validity issue.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

Cc: @Olga-Yakovleva, @zstanecic, @seanbudd

**Comment by seanbudd** [comment] 2023-09-14 23:44
Closing as fixed and duplicate of #15440

**Closed** 2023-09-14 23:44 UTC

**Comment by Brian1Gaff** [comment] 2023-09-15 07:35
Are you saying here, then that its an add on issue?
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by CyrilleB79** [comment] 2023-09-15 14:20
> Are you saying here, then that its an add on issue?

No he just says that it was an NVDA issue and that it's already fixed.

Additional information: fixed in beta branch, thus in future 2023.3beta2

> […](#)
> -- ***@***.*** Sent via blueyonder.(Virgin media) Please address personal E-mail to:- ***@***.***, putting 'Brian Gaff' in the display name field.
