### ISSUE TITLE
NVDA and browse mode Elements List error with Firefox

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#8105] opened 2018-03-21 10:11 UTC
In Browse mode with Mozilla Firefox, I get the following error constantly.
ERROR - unhandled exception (05:00:58.789):
Traceback (most recent call last):
  File "wx\_core.pyo", line 16766, in <lambda>
  File "browseMode.pyo", line 426, in run
  File "browseMode.pyo", line 827, in __init__
  File "browseMode.pyo", line 885, in initElementType
  File "browseMode.pyo", line 901, in filter
  File "virtualBuffers\__init__.pyo", line 121, in label
  File "browseMode.pyo", line 219, in _getLabelForProperties
  File "virtualBuffers\__init__.pyo", line 118, in propertyGetter
  File "virtualBuffers\__init__.pyo", line 149, in _getControlFieldAttribs
LookupError
This error is brought upon when I press NVDA+F7 to get the elements list. While this error occurs, I can't escape out of the list, nor can I activate links, nor move to links. Interestingly, if I Alt+Tab away and go back to the browser, the Elements list is gone. This, if I can recall, started happening when the dialog accepted new element types and added the ability to navigate by quickly typing in the name of the link.
Using Firefox 59, NVDA 2018.1 but noticeable in 2017.4 and Windows 10 1709.

**Comment by leonardder** [comment] 2018-03-21 15:29
Thanks for bringing this up again. Closing as duplicate of #7853.

**Closed by leonardder** 2018-03-21 15:29 UTC
