### ISSUE TITLE
In excel office 2016/365, editing of an existing cell is not accessible

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#9137] opened 2019-01-09 16:15 UTC
### Steps to reproduce:
1. open Microsoft excel by creating a new workbook
2. write something in any cell, for example, a1
note that for the first time, the editing works
when you finish, press enter and try to edit the cell data by pressing f2

### Actual behavior:
NVDA says unknown, and you cannot do anything with the arrow keys, nor navigate through the cell
### Expected behavior:
NVDA should speak the content you are editing and you should spell the editing content.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2018.4 and latest alpha
#### Windows version:
windows 10, 1809, 17763
#### Name and version of other software in use when reproducing the issue:
Microsoft® Excel® Office 365 MSO (16.0.11126.20102) (64-bit) 
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
2018.4 / latest stable

**Comment by lukaszgo1** [comment] 2019-01-09 16:47
Duplicate of #8146. This really should get some more attention.

**Closed** 2019-01-09 17:01 UTC
