### ISSUE TITLE
NVDA is announcing incorrect role for the list items of the dropdown and also not announcing checked-unchecked status and which item got selected.

### ISSUE THREAD

**Issue by preetimorajkar** [nvaccess/nvda#14572] opened 2023-01-19 12:56 UTC
### Steps to reproduce:
1.Open the HTML file shared in edge browser.
2.Run the NVDA tool for screen reading
3.Mouse hover on the multiselect drop down.
4.NVDA is announcing incorrect role for the list items of the dropdown and also not announcing checked-unchecked status and which item got selected.

### Actual behavior:
Below is the speech text from NVDA when one of the option is selected/checked from multiselect drodown:

Device Type  button  collapsed  
expanded
list  with 5 items  Option 1  check box  not checked    link  
Option 2  check box  not checked    link  
Option 3  check box  not checked    link  

### Expected behavior:

Option 1  check box checked 
Option 2  check box checked 
Option 3  check box checked 

#### NVDA version:
nvda_2022.4.exe

#### Window
[HTMLPage1.zip](https://github.com/nvaccess/nvda/files/10456859/HTMLPage1.zip)
[HTMLPage1.zip](https://github.com/nvaccess/nvda/files/10456861/HTMLPage1.zip)
s version:
Windows 10 Enterprise
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by seanbudd** [comment] 2023-02-14 02:32
Closing as we cannot reproduce this with the sample given

**Comment by seanbudd** [comment] 2023-02-14 02:33
What version of edge are you using?

**Closed by seanbudd** 2023-02-14 02:32 UTC

**Comment by preetimorajkar** [comment] 2023-02-14 05:17
Hello,

We are using Edge with Version 110.0.1587.41 (Official build) (64-bit) and chrome with version Version 110.0.5481.77 (Official Build) (64-bit)


Thanks and Regards,
Preeti

**Comment by seanbudd** [comment] 2023-02-15 00:06
We were unable to reproduce the issue you describe at all.  Would you be please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Could you confirm that in the issue template, you copy and pasted the actual speech from speech viewer.
