### ISSUE TITLE
Instead of using English as system language when the system language isn't supported, NVDA should use the second language in the languages list of windows

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#14279] opened 2022-10-22 18:43 UTC
### Describe the solution you'd like
NVDA should use the second language in the list of preferred languages of Windows rather than switching to English when the os is set to a langauge that's not supported by NVDA

**Comment by Brian1Gaff** [comment] 2022-10-23 11:38
I think you need to fill in the template fully, and justify under what 
conditions you consider this  a good idea and why?

As English is one of the most widely spoken languages in the world, then I'm 
guessing that somehow you would like it to ask your language and make some 
intelligent guess as to what might work for you if that is not supported?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Fatih Yüksek" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, October 22, 2022 7:44 PM
Subject: [nvaccess/nvda] Instead of using English as system language when 
the system language isn't supported, NVDA should use the second language in 
the languagees list of windows (Issue #14279)

**Comment by seanbudd** [comment] 2022-10-23 22:50
Related: #12707

**Comment by seanbudd** [comment] 2022-10-25 01:51
Closing as a duplicate of #12707.
It would be good to have a more thorough algorithm to determine the resolution order of preferred Windows languages (given more than 2), rather than just defaulting to the second one.

**Closed by seanbudd** 2022-10-25 01:51 UTC
