### ISSUE TITLE
Say all profile gets triggered even when there is no text to read

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#10899] opened 2020-03-25 19:15 UTC
### Steps to reproduce:
1. Make a say all profile
2. Go to the desktop by pressing windows+m
3. Press the say all command
### Actual behavior:
[nvda-old.log](https://github.com/nvaccess/nvda/files/4383029/nvda-old.log)
Say all profile gets triggered, with no way of disabling other than quitting NVDA.
### Expected behavior:
Say all profile doesn't get triggered, since there is no text to speak
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.3.1
#### Windows version:
10 1903
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, previous versions behaved similarly, but I didn't investigate that much
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by CyrilleB79** [comment] 2020-03-26 12:19
Maybe linked with #9947?

**Comment by feerrenrut** [comment] 2020-03-30 14:02
Can you expand on the problem this causes? Would it be adequate to ensure that the say all profile is disabled once it is determined that there is no speech?

**Comment by burakyuksek** [comment] 2020-03-30 18:10
Hello,
So my configuration with the current synthesizer I'm using is rate 85 pitch 60. I cannot understand long text with those settings so I made a say all profile which sets the pitch and rate to 65. Being stuck with this profile means being stuck with those settings until next restart, or if I try changing the settings the say all profile is edited instead of default profile.
I think disabling say all profile would be enough.

**Comment by ruifontes** [comment] 2020-03-30 18:24
It have already happened to me...

Now, I can't reproduce...

I think I have cleaned something wrong in the profiles files...


Regards,


Rui


Às 19:10 de 30/03/2020, burakyuksek escreveu:

**Comment by gregjozk** [comment] 2020-04-03 03:34
Hello,

to me it happens everywhere there is no text to read like taskbar, buttons etc. and when it happens, it does not automatically switch to default profile.
my work around to restore default behaveour in this case:
- open configuuration profile
- go to default profile
- disable all triggers
- press enter to close a configuration profiles dialog
- reopen a configuration profiles dialog
- reenable all triggers (clear checkbox there)
- close the dialog

thanks.

**Comment by lukaszgo1** [comment] 2020-07-31 09:21
How it is now with the latest Alpha?

**Comment by Adriani90** [comment] 2020-08-02 14:39
This is still reproducible in last NVDA alpha, following error is appearing:

```
IO - inputCore.InputManager.executeGesture (16:31:52.864) - winInputHook (14656):
Input: kb(laptop):NVDA+a
DEBUG - config.ConfigManager._triggerProfileEnter (16:31:52.881) - MainThread (13592):
Activating triggered profile Sayall
DEBUG - synthDriverHandler.SynthDriver.loadSettings (16:31:52.890) - MainThread (13592):
Loaded changed settings for SynthDriver ibmeci
DEBUGWARNING - sayAllHandler.readText (16:31:52.894) - MainThread (13592):
Unable to make reader
Traceback (most recent call last):
  File "sayAllHandler.pyc", line 116, in __init__
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 470, in __init__
  File "textInfos\offsets.pyc", line 249, in _getCaretOffset
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sayAllHandler.pyc", line 80, in readText
  File "sayAllHandler.pyc", line 118, in __init__
NotImplementedError: Unable to make TextInfo: 
ERROR - stderr (16:31:52.895) - MainThread (13592):
Exception ignored in:
ERROR - stderr (16:31:52.950) - MainThread (13592):
<function _TextReader.__del__ at 0x038A1978>
ERROR - stderr (16:31:53.027) - MainThread (13592):
Traceback (most recent call last):
ERROR - stderr (16:31:53.096) - MainThread (13592):
  File "sayAllHandler.pyc", line 252, in __del__
ERROR - stderr (16:31:53.148) - MainThread (13592):
  File "sayAllHandler.pyc", line 245, in stop
ERROR - stderr (16:31:53.202) - MainThread (13592):
AttributeError
ERROR - stderr (16:31:53.255) - MainThread (13592):
:
ERROR - stderr (16:31:53.321) - MainThread (13592):
'_TextReader' object has no attribute 'reader'
```

**Comment by Adriani90** [comment] 2020-08-02 14:40
I am on alpha-20656,87eee7f4
after #10723 has been merged.

**Closed** 2020-08-03 23:46 UTC
Labels: bug, component/speech
