### ISSUE TITLE
The plugin menu has disappeared from the tools menu in NVDA 18.3V

### ISSUE THREAD

**Issue by mythral0** [nvaccess/nvda#8762] opened 2018-09-18 23:40 UTC
### Steps to reproduce:
1. Install NVDA 18.3
2. Install plugin e.g. NVDA Remote V2.1
3. After installation has completed, the plugin menue is not displayed.

### Actual behavior:
The plugin menus are not found in the tools menu

### Expected behavior:
If a plugin is loaded and enabled, the user could navigate to the menu from NVDA/Tools menue.
#### NVDA Installed/portable/running from source:
installed

#### NVDA version:
18.3.

#### Windows version:
10Pro

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA?
NVDA V18.21 works fine.

**Comment by leonardder** [comment] 2018-09-19 06:39
Duplicate of #8084

Cc @ctoth @tspivey

**Closed** 2018-09-19 06:39 UTC
