### ISSUE TITLE
No braille feedback in Windows Calculator

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#12268] opened 2021-04-04 16:08 UTC
### Steps to reproduce:
1. Open Windows Calculator.
2. Type 2
3. Type +
4. Type 3
5. Type = (or Enter)

Note that the new appmodule listens for the Enter key, but not the equals (=) key. However, both work to display the result. Speech reports the result when you press Enter, but braille provides no feedback regardless of what key you press.

### Actual behavior:
The braille display continues to show "Display is 0".
There are two problems with this:
1. As you type (without using speech) you cannot verify what you just entered.
2. Once the result appears, you cannot read it unless you temporarily move the focus away from the display and back again.

### Expected behavior:
The braille display shows each number, operator and result as you type.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.4

#### Windows version:
Version	10.0.19042 Build 19042

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, it worked in NVDA 2019.3.

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by josephsl** [comment] 2021-04-04 18:19
Hi, resolved in Windows 10 App Essentials 21.04 – at least braille will announce results. Letting braille announce expressions as you type will require some time to tweak UIA notification event. I’ll submit a pull request that will resolve results announcement and add Delete to Calculator commands within the next 24 hours. Thanks for reminding me about this.

 

From: Davy Kager ***@***.***> 
Sent: Sunday, April 4, 2021 9:09 AM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] No braille feedback in Windows Calculator (#12268)

 


Steps to reproduce:


1.	Open Windows Calculator.
2.	Type 2
3.	Type +
4.	Type 3
5.	Type = (or Enter)

Note that the new appmodule listens for the Enter key, but not the equals (=) key. However, both work to display the result. Speech reports the result when you press Enter, but braille provides no feedback regardless of what key you press.


Actual behavior:


The braille display continues to show "Display is 0".
There are two problems with this:

1.	As you type (without using speech) you cannot verify what you just entered.
2.	Once the result appears, you cannot read it unless you temporarily move the focus away from the display and back again.


Expected behavior:


The braille display shows each number, operator and result as you type.


System configuration


NVDA installed/portable/running from source:


Installed


NVDA version:


2020.4


Windows version:


Version 10.0.19042 Build 19042


Name and version of other software in use when reproducing the issue:


Other information about your system:


Other questions


Does the issue still occur after restarting your computer?


Yes


Have you tried any other versions of NVDA? If so, please report their behaviors.


Yes, it worked in NVDA 2019.3.


If add-ons are disabled, is your problem still occurring?


Yes


Did you try to run the COM registry fixing tool in NVDA menu / tools?


Yes

**Comment by josephsl** [comment] 2021-05-25 20:52
Hi,

It looks like the accompanying pull request might be one of the last ones from me for now...

To Sean: smoke tests cannot be performed in the upcoming pull request because Calculator is a modern app not included in AppVeyor VM (the VM uses Windows Server 2016 or 2019, which do not come with apps such as Calculator).

Thanks.

**Closed** 2021-05-31 07:55 UTC

**Comment by dreinn** [comment] 2021-09-02 08:09
Don't work for me.
I'm trying it with NVDA 2021.2beta1, no Windows essential installed.
On my windows10 work pc version 10.0.19043, if I open the calculator, on the display i read "screen is 0".
I write:
2

The "2" sign is displayed for 1 second, then it returns to "screen is 0".
I add "+3" then enter.

for a second it appears "screen is 5", then again "screen is 0".

**Comment by CyrilleB79** [comment] 2021-09-02 11:07
Same feedback for me.

Actually, I guess this behaviour was intended when developing the feature; @josephsl can you confirm this since you have used `ui.message`?
IMO the unique way to have this feature usable is to set up a profile for Windows Calculator and configuring braille messages to be displayed indefinitely.
But it is quite confusing for the users who do not know that they should change this option.
If nothing better could be done, at least this should be documented in the user guide.

**Comment by ruifontes** [comment] 2021-09-02 11:58
I am using the last Alpha, 23661,c45f5f76, and it works as expected...

**Comment by josephsl** [comment] 2021-09-02 14:42
Hi, this is intentional – I suppressed additional braille output to avoid repetitions caused by UIA notification event, although I did just notice that braille output isn’t working properly with Windows App Essentials enabled. As for documenting the proposed workaround, I imagine this isn’t limited to Calculator. Besides it is a bit risky as Windows 11 version of Calculator changes the user interface again and breaks workarounds in place for existing Calculator app. Thanks.

**Comment by dkager** [comment] 2021-09-02 19:17
Could an alternative solution for the original problem, i.e. redundant speech output, perhaps be to ship a preset configuration profile for the Calculator app with NVDA? This profile would disable character echo. Then you can leave braille (and UIA, for that matter) alone.

**Comment by josephsl** [comment] 2021-09-02 19:32
Hi, it doesn’t solve the problem where braille does not reflect what is actually shown on screen as notification event handler uses flash messages (the alternative to that is displaying flash messages indefinitely). I’m personally against including app-specific configuration profiles for apps by default as it should be up to users to decide what to do about specific situations (that’s one of the selling points of using custom commands to switch between profiles). Thanks.

**Comment by bdorer** [comment] 2021-09-05 10:54
Hi, I vote for such profiles because users expect nvda to show braille output until something other happens. Users don't care how you provide data.

**Comment by CyrilleB79** [comment] 2021-09-05 19:33
I think including a profile directly in NVDA release can be very confusing for the user experience of some. Users expect to have only default profile when they install NVDA and some are even not conscious at all to have a unique (default) profile active. Thus you can expect questions such as: "Why NVDA does not remember the voice rate if I change it while in Calculator?"

The problem is actually this one:
> users expect nvda to show braille output until something other happens.

I have mentioned profiles just as a work-around. But this cannot be the solution for this problem.
