### ISSUE TITLE
Add tutor help hints capability to NVDA

### ISSUE THREAD

**Issue by dfarough** [nvaccess/nvda#5963] opened 2016-05-18 18:44 UTC
It would help new users to get some sort of tutor help or hint when this information is available in a control.  It would be good to make this feature adjustable in the NVDA preferences functionality.

**Comment by jcsteh** [comment] 2016-05-18 23:54
Duplicate of #3232. Note that there is an add-on called Control Usage Assistant which does some of this.

**Closed by jcsteh** 2016-05-18 23:54 UTC
Labels: duplicate
