### ISSUE TITLE
NVDA freezes and does not recover in Windows Terminal

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#15507] opened 2023-09-24 16:06 UTC
I've seen this happen twice so far.

### Steps to reproduce:

Use Windows Terminal to do something on the command line.

### Actual behavior:

NVDA freezes and plays error sounds continually. It does not recover, and the only way to proceed is to go to the desktop and manually restart NVDA.

### Expected behavior:

NVDA should not freeze

### NVDA logs, crash dumps and other attachments:
[nvda freeze.txt](https://github.com/nvaccess/nvda/files/12709065/nvda.freeze.txt)

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29111,b341bf97 (2024.1.0.29111)
#### Windows version:
Windows 11 22H2

#### Name and version of other software in use when reproducing the issue:
Windows Terminal 1.17.11461.0

#### Other information about your system:
Under advanced settings, Windows console support is set to "Automatic (prefer UIA)", diff algorithm is automatic, prefer Diff Match Patch.

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Unknown, I will try to reproduce this more.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2023-09-24 23:07
Just to confirm, this is an intermittent issue that's rare to reproduce?

It would be good to confirm it with add-ons disabled as well

**Comment by codeofdusk** [comment] 2023-09-26 22:02
What happens with "speak new text in Windows Terminal" set to notifications?

**Comment by mo29cg** [comment] 2023-09-29 08:38
Same here, it constantly freezes like onece in an hour.
I also didn't check if it happens without any ad-ons.

**Comment by mo29cg** [comment] 2023-10-10 02:19
@codeofdusk If "speak new text in Windows Terminal" was set to "UIA notifications", it doesn't freeze anymore.
I guess there is some bug in speaking diffs then.

**Comment by mo29cg** [comment] 2023-10-12 04:01
If "speak new text in Windows Terminal" was set to "UIA notifications",
it often stop speaking characters typed to the console.
This side effect is very annoying.

**Comment by VovaMobile** [comment] 2023-10-28 09:17
Hello, dear community!
These problems occur not only in the Terminal. NVDA can suddenly freeze anywhere and under any conditions.
The problems started with version 2023.2. They are reproduced in both Windows 10 and Windows 11. I have collected logs and comments from users in the Ukrainian NVDA community and publish them here because these problems occur very often.
Below are a few completely different examples with the same result.
#### NVDA crashed and did not recover after Microsoft Edge was closed ####
The problem occurred on a Windows 10 22H2 (10.0.19045) AMD64 workstation (NVDA version 2023.3rc2).
I accidentally opened a file in Microsoft Edge when I should have opened it in Chrome. As soon as Edge opened, I closed it with the tab-close command (ctrl+w) and NVDA stopped working and did not recover on its own.
Error text:
[error1.txt](https://github.com/nvaccess/nvda/files/13195026/error1.txt)


There were smaller freezes before this one, but NVDA recovered on its own.
Full log:
[nvda-old.log](https://github.com/nvaccess/nvda/files/13195028/nvda-old.log)



#### NVDA completely froze when the user switched to the desktop ####

This happened on a Windows 11 22H2 (10.0.22621) AMD64 workstation (NVDA version 2023.3rc2).
Error text:
[error2.txt](https://github.com/nvaccess/nvda/files/13195029/error2.txt)


#### Nvda crashed in Microsoft Eams ####
Another user reported that NVDA 2023.3RC2 ran stably on a Windows 11 22H2 (10.0.22621) AMD64 workstation for almost five hours and then crashed when he was working in Microsoft Teams.
Here is a snippet of his log:
[error3.txt](https://github.com/nvaccess/nvda/files/13195031/error3.txt)


#### Resume ####
Addons like Newfon or browserNav often appear in the logs, but freezes also occur for people who don't use any of these addons.
Freezes after which NVDA does not recover can occur when closing a window, exiting to the desktop, or moving the carriage in the Terminal.

**Comment by Ishtef** [comment] 2023-10-28 09:45
I fully confirm the problem described by VovaMobile. It seems to me that it has acquired such dimensions that it is unacceptable to ignore it any longer.

**Comment by Adriani90** [comment] 2023-10-28 10:30
Some things to check:
* Which versions of MS Edge are used? Is thiw occuring also when updating to MS Edge 118?
* Are the freezes occuring with every type of synthesizer? Or only with aprticular ones such as onecore or IBM TTS?

I cannot reproduce any of these freezes without addons when using eSpeak or one core on Windows 11 with NVDA 2023.3 RC2.

Did the people try to clean their user configuration and reinstall NVDA?

**Comment by VovaMobile** [comment] 2023-10-28 10:37
Some of these users reinstalled NVDA, but the freezes continued.
I don't remember which version of Edge I was running, since this is a work computer and the main browser there is Chrome. But that's not the main thing. As you can see, the problem with freezing occurs in the Terminal and other programs.
I don't know which synthesizer the author of this issue uses, but all the users I mentioned in my comment use either the Newfon synthesizer or the RHVoice synthesizer.

**Comment by Adriani90** [comment] 2023-10-29 21:42
Can they reproduce these freezes also when using WASAPI for audio output is disabled in NVDA advanced settings?
I am trying to understand whether this is related to the synthesizers and their sequences sent to the screenreader or not.

**Comment by seanbudd** [comment] 2023-10-29 22:58
Please create new issues @VovaMobile , rather than hijacking an existing issue to discuss a separate set of issues

**Comment by jcsteh** [comment] 2023-11-15 02:11
This is fixed by #15753. You'll still see one error in the log, as I don't quite know how to fix that yet, but it won't cause a freeze and it is harmless.

**Closed by jcsteh** 2023-11-15 02:11 UTC
Labels: bug/freeze, p3, app/windows-terminal, triaged
