### ISSUE TITLE
NVDA 2023.3beta3: Audio output device selection inconsistency.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15548] opened 2023-09-28 09:11 UTC
### Actual behavior:

Start NVDA with a blank configuration.
- modify the speech rate by activating the rate boost and using "nvda+control+direction arrows".
1- type "NVDA+n", select "preferences", then "Settings".
2- in the "Speech" category, press "change".
3- in the "Choose synthesizer" dialog, the selected synthesizer is "Windows OneCore" and the audio output device is  "Microsoft sound mapper".
4- without touching the synthesizer, modify the audio output device and validate with “OK”
- First problem: the speech rate has been reset to 9, the rate boost has not changed.
5- by "shift+tab", return to the list of categories,
6- select the "Audio" category and press tab.
7- check that the audio output device is the one set previously.
8- return to the "Speech" category and press the "Change" button again.
9- without touching the synthesizer, select the "Microsoft sound mapper" as the audio output device and validate with "OK".
10- go back to the "Audio" category and check the audio output device.
it is not the "Microsoft sound mapper" but the first device configured.
11- return to the "Choose synthesizer" dialog, recheck that the audio output device is indeed the "Microsoft sound mapper", and still validate with "OK".
12 -press the “Apply” button.
14- return to the “Choose synthesizer” dialog and check the audio output device.
This is not the "Microsoft sound mapper", but the one configured in the "Audio" category.

### Expected behavior:

The audio output device must be the same in the "Audio" category and in the "Choose Synthesizer" dialog.
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
2023.3beta3
#### Windows version:
Windows 10 22H2 (10.0.19045) workstation x86

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by XLTechie** [comment] 2023-09-28 09:16
***@***.***, @codeofdusk

**Comment by CyrilleB79** [comment] 2023-09-28 10:43
Confirmed on my side.
(Windows 10 22H2 (AMD64) build 19045.3448)

**Comment by CyrilleB79** [comment] 2023-09-28 10:58
Notes:
* The issue of speech rate & boot reset already exists in older versions of NVDA (e.g. 2021.1). Only the consistency issues reported at point 10 and 14 are to be considered for NVDA 2023.3 release.
* I have encountered a similar consistency issue modifying audio ducking instead of audio output device in synth dialog (NVDA+control+S) and audio settings; but I have not found the way to reproduce again. More tests need to be performed.

**Comment by leonardder** [comment] 2023-09-29 18:57
I wonder whether we should take this as a known issue for 2023.3, or just yet stick with removing the entries from the synth selection dialog again.

**Comment by CyrilleB79** [comment] 2023-10-02 07:03
Cc @seanbudd, just to ensure you are aware of this issue and since you were hoping to issue last beta very soon.

**Comment by Brian1Gaff** [comment] 2023-10-02 10:38
Does this only affect one core voices, as using Espeak I could not get it to go wrong. I use a usb interface and  it seems to be fixed when I select it.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment] 2023-10-02 22:47
This is fixed in 2024.1, we are accepting this as a temporary issue with 2023.1

**Comment by CyrilleB79** [comment] 2023-12-20 21:43
Closing now that NVDA 2024.1beta1 has been released.
The audio output device is not present anymore in the Choose synthesizer dialog.

**Closed by CyrilleB79** 2023-12-20 21:43 UTC
Labels: p4, triaged
