### ISSUE TITLE
Chrome now reads the entire selection when extending selections

### ISSUE THREAD

**Issue by ahicks92** [nvaccess/nvda#12106] opened 2021-02-26 22:26 UTC
### Steps to reproduce:

1. Open Chrome to something with an edit field.
2. Type some text, a full sentence or so.
3. Start selecting the text by word.
4. Observe that the entire selection is read for every word added.

This appears to not be 100% reliable.  I've seen this a few times across a few different sites.  When it happens it's consistent until NVDA restart or page load.  As far as I know the text fields are normal non-rich text fields.

### Actual behavior:

If you have "this is a test" and "this is a" is selected, extending the selection to include test" will read "this is a test"

### Expected behavior:

It should just read "test".

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:
2020.4

#### Windows version:
Windows 10, 64-bit.

#### Name and version of other software in use when reproducing the issue:

Chrome: Version 88.0.4324.190 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?

Yes.
#### If addons are disabled, is your problem still occuring?
can't make it happen reliably enough to tell for sure.  Only add-on I'm running is [Notepad++](https://github.com/derekriemer/nvda-notepadPlusPlus).

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Shouldn't be relevant.

**Comment by brunoprietog** [comment] 2021-03-17 00:42
I confirm that

**Comment by ahicks92** [comment] 2021-03-17 14:32
Yeah.  I haven't come back because it's infrequent, but this definitely still happens.  Hoping to get a more reliable repro at some point: when I opened the issue it was happening reliably in that moment.

**Comment by nidza07** [comment] 2021-03-17 15:26
I can also reproduce this.

**Comment by Adriani90** [comment] 2023-09-14 22:07
Do you have a minimal test case for this or an example website where this occurs? 
I cannot reproduce this issue with NVDA 2023.2 and Chrome 117.

**Comment by ahicks92** [comment] 2023-09-15 15:37
I haven't seen this in a very long time.  We may want to close until it comes back, if it does.

**Comment by Adriani90** [comment] 2023-09-15 15:44
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2023-09-15 15:44 UTC
Labels: close/worksforme
