### ISSUE TITLE
MS Excel 2016 - tabbing or arrow-navigation across cells causes previous cell contents to be spoken

### ISSUE THREAD

**Issue by manish10** [nvaccess/nvda#8751] opened 2018-09-14 05:16 UTC
### Steps to reproduce:
In Microsoft Excel 2016, for any spreadsheet:
1. put some values in adjacent cells
2. move around the cells with arrow keys.
3. The value of the cell loosing focus is announced in place of the one gaining focus. This happens frequently but not every time.
 
### Actual behavior:
The contents of the previous cell with focus (the cell that is loosing focus) are spoken instead of the cell that is gaining focus.
### Expected behavior:
The cell gaining focus should be spoken.
### System configuration:
windows 10 64 bit, ms excel 2016
#### NVDA Installed/portable/running from source:
installed.
#### NVDA version:
2018.2.1
#### Windows version:
windows 10 64 bit
#### Name and version of other software in use when reproducing the issue:
ms excel 2016
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by PratikP1** [comment] 2018-09-14 14:28
I am unable to duplicate this with Excel 2016 and the latest NVDA alpha. I am also not able to duplicate it with the RC build of 2018-3.

**Comment by manish10** [comment] 2018-09-14 18:14
I see this with every excel file I open. Not sure what I can do to help replicate this.

 

I will try the 2018.3 rc build to see if this goes away.

**Comment by manish10** [comment] 2018-11-26 19:12
Additional information: The issue occurs in forms mode, which seems to be the default with my settings in NVDA (I have auto forms mode disabled everywhere). If I press "nvda + space" to move to browse mode, the problem goes away.
Also, this is the same problem as #8889  -- this one occurs in the teams app in forms mode. The behavior is exactly the same.

**Comment by ehollig** [comment] 2019-03-27 17:42
@manish10 is this still an issue with Excel 2016? I am not able to reproduce when I am in focus mode and using Excel 2016  and arrow around to different cells in a spreadsheet.

**Comment by manish10** [comment] 2019-03-30 00:29
This seems to be fixed with the 2019.1 release of NVDA. I no longer face
this issue on tseveral excel sheets I worked on today.In general NVDA feels
much more responsive in excel now.

Regards,
Manish
http://iaccessible.net <http://iaccessible.blogspot.com>

**Comment by Adriani90** [comment] 2019-03-30 16:30
Closing as works for me. Thank you for reporting back!

**Closed by Adriani90** 2019-03-30 16:30 UTC
Labels: Microsoft Office support, worksforme
