### ISSUE TITLE
NVDA stopps automaticaly restart after updating

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#8444] opened 2018-06-26 07:16 UTC
If you update NVDA, after update the start automaticaly checkbox is turned off.
I have tested it only with next branch, although it is sayd, that in stable version the problem occurs as well.
Both PC are a windows 10 X64 architecture.
I could not review on windows 7, 8, 8.1, because there are not such pc's in my house.
These are all installed NVDAs, in windows 10.
The main language of the two pc, what has problem with next and stable.

**Comment by leonardder** [comment] 2018-06-26 07:42
Could you please file your issue according to the issue template? Please provide the exact steps to reproduce your issue, as well as what you expect and what happens instead.

**Comment by josephsl** [comment] 2018-06-26 07:49
Hi, if I’m not mistaken, this is a duplicate of an issue filed in the past. Thanks.

**Comment by Brian1Gaff** [comment] 2018-06-26 08:36
Yes this does sound like it. I thought the auto restart off was a choice 
made deliberately every time though by design?
 At least for portable versions.
I always tend to leave it that way as a delay helps my well known issue of 
non restarting  to be fixed.

Brian

**Comment by ehollig** [comment] 2018-06-26 17:05
I could be wrong, but I think this is a duplicate of #6929. Please file your issue according to the template next time.

**Closed by ehollig** 2018-06-26 17:05 UTC
