### ISSUE TITLE
Cyclic switch between viewing modes of review cursor

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#5601] opened 2015-12-11 23:10 UTC
I propose to make a cyclic switch between viewing modes review cursor.
For example if set the view object and the user to switch the view mode by pressing NVDA+numpad1, it must be set to view screen.
Conversely, if set the view screen, pressing NVDA+numpad7 should set mode the view object.
I don't always remember what mode of viewing cursor set now and often try to switch the wrong keys. The appearance of cyclic choice I think many would have facilitated the choice of mode.
If the idea is accepted, i can make the appropriate pull requeste. Thank you.

**Comment by jcsteh** [comment] 2015-12-13 23:23
The problem is that this breaks backwards compatibility; i.e. existing users are used to two commands which stop when they hit the last mode in that direction. Introducing a new command consumes an extra key and keys are somewhat in short supply. The only other option is to introduce a command which is unbound by default. Would that be acceptable to you? Of course, you can bind this easily using the Input Gestures dialog.

@MichaelDCurran may have other thoughts, though I suspect his thinking will be similar to mine.

**Comment by kvark128** [comment] 2015-12-14 01:23
Yes, the binding gesture can make the user. But maybe it is better to make not one, but two commands for both directions?

**Comment by derekriemer** [comment] 2015-12-14 01:37
I propose getting rid of the two keystrokes and switching to only one 
toggle modes key. This will both not be super hard for existing users to 
switch to, and will decrease the cognitive load on new NVDA users while 
learning. We could do a phased deprecation; the user would hear a 
message saying that this keystroke will stop working in the next nvda 
version and pop up a dialog (or tell the user to use the other keystroke).

On 12/13/2015 4:23 PM, James Teh wrote:
>
> The problem is that this breaks backwards compatibility; i.e. existing 
> users are used to two commands which stop when they hit the last mode 
> in that direction. Introducing a new command consumes an extra key and 
> keys are somewhat in short supply. The only other option is to 
> introduce a command which is unbound by default. Would that be 
> acceptable to you? Of course, you can bind this easily using the Input 
> Gestures dialog.
>
> @MichaelDCurran <https://github.com/MichaelDCurran> may have other 
> thoughts, though I suspect his thinking will be similar to mine.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5601#issuecomment-164310037>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.drupalgardens.com>
Non-proffessional website. <http://derekriemer.pythonanywhere.com/personal>
Awesome little hand built weather app that rocks! 
<http://derekriemer.pythonanywhere.com/weather>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by bhavyashah** [comment] 2017-07-23 05:18
This ticket is a duplicate of both #3958 and #3392, both of which are open as well. Could two of these three tickets duplicating each other be closed and further discussion be concentrated in just one? @leonardder 
Additionally, are we for the implementation of this feature, or do we still have concerns? @jcsteh @ehollig @Qchristensen @kvark128 @derekriemer

**Comment by derekriemer** [comment] 2017-07-31 10:33
closing as duplicate and in favor of #3958

**Closed by derekriemer** 2017-07-31 10:33 UTC
