### ISSUE TITLE
SSH in Windows Terminal: Errors when many text flows in

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#12735] opened 2021-08-14 06:54 UTC
### Steps to reproduce:
1. Open an SSH session in Windows Terminal
2. Trigger a process that generates a flow of output, e.g. a system update on Arch Linux using Pacman

### Actual behavior:
Errors in the log:

```Log
ERROR - eventHandler.executeEvent (08:49:34.487) - MainThread (6948):
error executing event: caret on <NVDAObjects.Dynamic_WinTerminalUIAEditableTextWithAutoSelectDetectionUIA object at 0x07D59750> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 195, in event_caret
  File "NVDAObjects\__init__.pyc", line 1213, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 312, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 792, in collapse
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 27, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (08:49:35.473) - MainThread (6948):
error executing event: caret on <NVDAObjects.Dynamic_WinTerminalUIAEditableTextWithAutoSelectDetectionUIA object at 0x07D59750> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 195, in event_caret
  File "NVDAObjects\__init__.pyc", line 1213, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 312, in __init__
  File "NVDAObjects\UIA\__init__.pyc", line 792, in collapse
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 27, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### Expected behavior:
No Errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-23579,07f7bf1c

#### Windows version:
Windows 11 21H2 (build 22000.132)

#### Name and version of other software in use when reproducing the issue:
Windows Terminal 1.9.1942.0

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by leonardder** [comment] 2021-08-14 06:54
Cc @codeofdusk

**Comment by codeofdusk** [comment] 2021-08-14 06:56
Does Terminal continue to function even though it's generating errors?

CC @carlos-zamora.

**Comment by leonardder** [comment] 2021-08-14 06:57
Yes, it still functions.

**Comment by Neurrone** [comment] 2021-08-14 07:21
This looks like an exact duplicate of #12723.

**Closed** 2021-08-14 07:34 UTC
