### ISSUE TITLE
While installing NVDA, NVDA beeps always like the installation is at 50% and the progress bar shows at %0

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11332] opened 2020-07-03 15:28 UTC
### Steps to reproduce:
1. Start installing NVDA to the hard drive, or create a portable copy
2. You will hear that while the installation is in progress, the progress bar sound does not increase in pitch as the installation  gets closer to completion. Instead, the progress sound is at always 50%.
### Actual behavior:
The progress bar sound does not increase in pitch to reflect the progress level. It stays at 50% all the time.
### Expected behavior:
The progress sound while installing NVDA gets higher in pitch as the installation gets closer to completion
#### NVDA installed/portable/running from source:
temporary copy
#### NVDA version:
2020.1
#### Windows version:
windows 10, build 1909
#### Name and version of other software in use when reproducing the issue:
NVDA setup/installer
#### Other information about your system:
64-bit arcitecture
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
In every version of NVDA, the behavior is the same
#### If addons are disabled, is your problem still occuring?
no
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by josephsl** [comment] 2020-07-03 16:28
Hi, ah, this is indeterminate progress bar. @MichaelDCurran, is there a reason for coding it that way? Also, I geta feeling that this is a duplicate. Thanks.

**Comment by leonardder** [comment] 2020-07-04 11:05
Duplicate of #2313

**Closed by leonardder** 2020-07-04 11:05 UTC
