### ISSUE TITLE
Excel 365: Focus issues when adding notes to cells

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#11153] opened 2020-05-12 06:35 UTC
# Steps to reproduce:
1. Open excel 365
2. Focus a cell
3. Press shift+f10 or the applications key
4. Choose add note

### Actual behavior:
NVDA returns nothing when invoking "add note" or it reports the name of the sheet. Focus seems to be lost entirely. It is not possible to read the contents of the note that's currently being added, nor the contents of the sheet when escaping out of the notes edit field.

### Expected behavior:
NVDA should provide access to the note edit box and focus should track reliably when exiting the note edit box.

#### NVDA installed/portable/running from source:
INstalled

#### NVDA version:
NVDA alpha-20175,9967903a

#### Windows version:
Windows 10 2004, build 19041.208

#### Name and version of other software in use when reproducing the issue:
Excel 365 (16.0.12730.20250)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, most recent alpha versions.

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by CyrilleB79** [comment] 2020-05-12 06:50
According to Microsoft on the page [The difference between threaded comments and notes](https://support.microsoft.com/en-us/office/the-difference-between-threaded-comments-and-notes-75a51eec-4092-42ab-abf8-7669077b7be3):

> Notes are for making notes or annotations about the data, and work like comments used to work in earlier versions of Excel.

So the notes are just the comments from Excel's previous versions.

Do notes behave differently than comments on previous versions of Excel? On previous versions, comments box were not accessible but could be edited without vocal feedback of the actions in comment box. Excel's shortcut to add a comment (Shift+F2) is overridden by NVDA to present to the user an accessible NVDA-made dialog box where he can write/edit the cell's comment.

**Comment by leonardder** [comment] 2020-05-12 07:29
Thanks for this helpful information.

Shift+f2 still works correctly, so that solves my issue here. However, it now applies to notes, not to new style comments. May be we need to update this in the user guide. Would that be something you'd like to do @CyrilleB79?

**Comment by CyrilleB79** [comment] 2020-05-12 09:37
Well, I would prefer if you or somemone else update yourself the user guide, since I have not even Office 365 and thus cannot make tests.

Also Cc @Adriani90 who has just updated this part of the user guide in #11067 and commented in #10867.

**Comment by Adriani90** [comment] 2020-05-12 21:33
Yes indeed, the difference between notes were called comments in earlier versions. New style comments allow for answering to comment, keeping a comment treat i.e. on a single cell. I will have to adjust the coresponding paragraph in the user guide. The new style comment dialog is accessible, while the notes dialog is not. On the other hand, adding new style comments on a cell, NVDA does not report that there is a new style comment on the cell.
For notes, there is already issue #9194 in place. For new style comments there is issue #9195. I am closing this issue as duplicate of #9194.

**Closed by Adriani90** 2020-05-12 21:33 UTC
Labels: app/microsoft-office, close/duplicate
