### ISSUE TITLE
adding direct USB support for BAUM VarioPro  braille display

### ISSUE THREAD

**Issue by pavel46** [nvaccess/nvda#6117] opened 2016-06-28 09:44 UTC
BAUM has a braille display VarioPro 64 and VarioPro 80. unfortunately, currently this braille display is only supported Via BRLTTY. so i'm asking to add a direct USB support for this braille display by the existing direct driver for the BAUM  braille displays. this display is usually connected to the computer via USB sirial port.
for those 2 models of VarioPro i found following information:
VID 0403 hex 
PID FE76 hex 
VarioPro 80 
VID 0403 hex 
PId FE77 hex 
VarioPro 64

**Comment by jcsteh** [comment] 2016-06-30 06:01
Duplicate of #5162.

**Closed by jcsteh** 2016-06-30 06:01 UTC
Labels: duplicate
