### ISSUE TITLE
Remapping single key navigation does not apply under Edge

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#9142] opened 2019-01-11 09:06 UTC
If I reassing some single key navigation keys, my changes are taken in count under Firefox, Chrome and IE, but not under Edge and all Windows applications that seem to use Edge (Twitter etc).

**Comment by DrSooom** [comment] 2019-01-11 22:48
@MichelSuch: Please provide us more information by completely filling out the bug report draft. Thanks.

**Comment by lukaszgo1** [comment] 2019-03-06 18:30
Duplicate of #6108.

**Comment by Adriani90** [comment] 2019-03-07 21:35
Closing as duplicate. @lukaszgo1 great pick! :-) Thanks for your assistance!

**Closed by Adriani90** 2019-03-07 21:35 UTC
Labels: duplicate
