### ISSUE TITLE
Add single letter navigation key for clickable elements

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#12074] opened 2021-02-15 05:03 UTC
### Is your feature request related to a problem? Please describe.
Today, the presence of elements and controls that NVDA reports as "clickable" is increasingly substantial on the Internet. NVDA does currently have single letter navigation keys like 'k' for links and 'b' for buttons, but nothing of the like for clickable elements. Given comparable levels of prevalence on the web, the need for a key that helps users jump to the next and previous clickable element is felt for similar reasons: skimming through a page, jumping to different portions of a webpage quickly, navigating to only those parts of a page that can be pressed to reveal additional content or go to related pages.

### Describe the solution you'd like
I am neutral on which alphabetic or punctuation key gets assigned to clickable elements. It seems like j, p, y and z are the only unassigned alphabets. There is a whole host of punctuations that are unassigned.
Alternatively, it may be worth considering which existing elements for which quick navigation keys are present are relatively uncommon and jumping to them is not particularly helpful. In my strictly personal opinion, frames (m), objects (o), and block quotes (q) come to mind. If there is some consensus on these, we could remap one of these letters to clickable elements.

### Describe alternatives you've considered
Perhaps clickable elements could be integrated within an existing single letter navigation key. As an arbitrary example, we could change b to jump across both buttons and clickable elements.
Future work in this front could even include having clickable elements as an option in the Filter By grouping of NVDA's Elements List dialog. I acknowledge that that is an unrelated request; hence I characterize it as a future extension.

**Comment by fisher729** [comment] 2021-02-15 05:35
Hi.

This is a duplicate of #124. As it is a long requested feature that hasn't got any love for over 11 years, I'm not sure if this will be taken up any time soon. Hopefully someone with knowledge of python can actually do up a pull request for this.

In my opinion, the key should be unassigned, similar to those for articles and groupings. However, you are on to something where frames is concerned. They are no longer being prominently used as they were 10 years or so, and perhaps it can be assigned to that letter as well, clickable eleMents.

**Comment by Brian1Gaff** [comment] 2021-02-15 09:39
I think it needs another look now because it seems clickable items are a 
massive problem these days. For some reason they are popular now whereas 
they were not some five years ago.
 Weird.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by fisher729** [comment] 2021-02-15 11:35
I wouldn't hasten to  call them a problem at all, however they are
used in the incorrect manner on many occasions.

**Comment by XLTechie** [comment] 2021-02-15 21:13
They are most definitely a problem, because given their popularity, the 
inability to jump right to them, or have them be included when moving by tab or 
other "visit every selectible option" method, is inconceivable.

Granted they are often misused, or overloaded with other elements such as 
buttons or links, but equally as often they are on their own.

That there is no feature to jump to them is absurd.

I do think it should be assigned by default to some key or other (my preference 
is j/J), but even having them reachable by tab would be a step in the right 
direction.

**Comment by cary-rowen** [comment] 2021-02-16 03:07
This is really important, I also hope to assign a separate letter for this

**Comment by Adriani90** [comment] 2021-02-16 10:40
Closing as duplicate of #124, let's continue discussions there.

**Closed by Adriani90** 2021-02-16 10:40 UTC
Labels: close/duplicate
