### ISSUE TITLE
No entry for the Ctrl key in "Emulated system keyboard keys".

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#7772] opened 2017-11-17 20:42 UTC
I want to see how to emulate the Ctrl key using a Braille display, thus taking advantage of this feature in NVDA:

(Quoted lines from the "What's New" document that comes with NVDA)
"•Braille display gestures that emulate system keyboard key modifiers (such as control and alt) can now be combined with other emulated system keyboard keys without explicit definition. (#6213)
◦
(Quote finished)

From the NVDA Preferences submenu, open the "Input Gestures" dialog and scroll to "Emulated system keyboard keys" tree and open it using the RightArrow key.

With a FreedomScientific Focus40 Blue Braille display connected, I can't find any entry for the Ctrl key.

Info:

NVDA version next-14617,ef52ddc4

Windows10 Fall Creators Update (Using Windows version 10.0.16299 workstation)

**Comment by leonardder** [comment] 2017-11-18 12:15
Closing as duplicate of #6060.

**Closed by leonardder** 2017-11-18 12:15 UTC
