### ISSUE TITLE
Focussing LibreOffice when a footer text has focus gives a stacktrace

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4695] opened 2014-12-15 00:32 UTC
**Reported by bramd on 2014-12-15 00:32**
Tested in LibreOffice 4.3.4.1.
Steps to reproduce:
1. Create a new LibreOffice document and add some text in the footer (menu Format, Add footer, Default style).
2. Go to another application.
3. When the focus returns to LibreOffice, the following stacktrace occurs:

```
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 171, in doPreGainFocus
  File "compoundDocuments.pyc", line 405, in event_treeInterceptor_gainFocus
  File "braille.pyc", line 1414, in handleGainFocus
  File "braille.pyc", line 1418, in _doNewObject
  File "braille.pyc", line 1211, in getFocusRegions
  File "braille.pyc", line 815, in update
  File "compoundDocuments.pyc", line 388, in makeTextInfo
  File "compoundDocuments.pyc", line 206, in __init__
AttributeError: 'NoneType' object has no attribute 'makeTextInfo'
```

**Comment by Adriani90** [comment] 2019-01-11 19:47
@bramd are you still able to reproduce this issue?
cc: @Qchristensen

**Comment by bramd** [comment] 2019-01-12 22:19
@Adriani90 Not exactly, but there are still issues editing footers.

After inserting a footer and editing it, I get the following:

```
ERROR - eventHandler.executeEvent (23:17:42.940):
error executing event: caret on <NVDAObjects.Dynamic_SymphonyParagraphSymphonyTextEditableTextWithAutoSelectDetectionIAccessible object at 0x0640EA30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "compoundDocuments.pyc", line 456, in event_caret
  File "documentBase.pyc", line 24, in makeTextInfo
  File "compoundDocuments.pyc", line 210, in __init__
  File "documentBase.pyc", line 24, in makeTextInfo
  File "textInfos\offsets.pyc", line 405, in __init__
  File "NVDAObjects\IAccessible\__init__.pyc", line 180, in _getCaretOffset
RuntimeError: Retrieving caret offset failed
```

Caret movement isn't detected and braille doesn't update.

**Comment by Qchristensen** [comment] 2019-01-21 03:51
I don't get any error when alt+tabbing, however I did get an error in the log when typing into the footer to begin with:

IO - inputCore.InputManager.executeGesture (14:42:32.163):
Input: kb(desktop):t
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:42:32.173):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (14:42:32.174):
error executing event: caret on <baseObject.Dynamic_SymphonyParagraphSymphonyTextEditableTextWithAutoSelectDetectionIAccessible object at 0x0587E7D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "compoundDocuments.pyo", line 444, in event_caret
  File "documentBase.pyo", line 24, in makeTextInfo
  File "compoundDocuments.pyo", line 209, in __init__
  File "documentBase.pyo", line 24, in makeTextInfo
  File "textInfos\offsets.pyo", line 298, in __init__
  File "NVDAObjects\IAccessible\__init__.pyo", line 167, in _getCaretOffset
RuntimeError: no active caret in this object

I haven't currently got a Braille display connected, but NVDA reads everything as it should in the footer (letters as I arrow, words or the whole thing with say all / read current line etc).

In OpenOffice, I don't get an error like that, but when typing I get the following warning (this was when pressing space after a word, I had NVDA set to echo typed words but not characters) which may be related to why this only happened at the end of words):

Input: kb(desktop):space
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (14:48:38.042):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speakTypedCharacters (14:48:38.045):
typed word: The
IO - speech.speak (14:48:38.045):
Speaking [LangChangeCommand ('en_GB'), u'The']

**Comment by Adriani90** [comment] 2024-10-01 18:48
I cannot reproduce the particular issue when typing and navigating within a footer with Libreoffice 25.2 and NVDA 2024.4 Beta, but I don't know how to jump between header, footer and main document, there is no keyboard command for that.
@michaelweghorn do you have any hints? I guess the header and footer should be navigable via pressing f6 multiple times, at least this would be ideal.


I only get following error when switching the window with alt´t+tab between different open Libreoffice documents, especially when pressing and releasing the alt´t+tab keys very fast. No matter whether there is a footer or not.

```
IO - inputCore.InputManager.executeGesture (20:43:22.887) - winInputHook (32036):
Input: kb(laptop):alt+tab
ERROR - eventHandler.executeEvent (20:43:23.031) - MainThread (14972):
error executing event: gainFocus on <NVDAObjects.Dynamic_SymphonyParagraphSymphonyTextEditableTextWithAutoSelectDetectionIAccessible object at 0x00BBEB50> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 348, in executeEvent
  File "eventHandler.pyc", line 382, in doPreGainFocus
  File "api.pyc", line 189, in setFocusObject
  File "api.pyc", line 348, in setNavigatorObject
  File "review.pyc", line 138, in setCurrentMode
  File "review.pyc", line 57, in getDocumentPosition
  File "documentBase.pyc", line 76, in makeTextInfo
  File "compoundDocuments.pyc", line 287, in __init__
  File "documentBase.pyc", line 76, in makeTextInfo
  File "textInfos\offsets.pyc", line 505, in __init__
  File "textInfos\offsets.pyc", line 267, in _getCaretOffset
NotImplementedError
```

**Comment by michaelweghorn** [comment] 2024-10-02 06:03
> (...) but I don't know how to jump between header, footer and main document, there is no keyboard command for that. @michaelweghorn do you have any hints? I guess the header and footer should be navigable via pressing f6 multiple times, at least this would be ideal.

At least with an English UI, Ctrl+PgDown moves focus to the footer, Ctrl+PgUp to the header, and Esc gets you back into the main document. Keyboard shortcuts can be customized in "Tools" -> "Customize".

**Comment by Adriani90** [comment] 2024-10-02 09:35
@michaelweghorn thanks so much, yeah I have to find a way to jump back from the main document into the footer or header. So far I am getting there only by using the mouse but it is very tricky at least for me. :-)

**Comment by michaelweghorn** [comment] 2024-10-02 11:27
> @michaelweghorn thanks so much, yeah I have to find a way to jump back from the main document into the footer or header. So far I am getting there only by using the mouse but it is very tricky at least for me. :-)

@Adriani90 To double-check: With "so far" do you mean before trying what I wrote in my last comment and it works now with these? Or is there still some issue when trying the keyboard shortcuts I mentioned for switching?

**Comment by Adriani90** [comment] 2024-10-03 22:50
Ah ok I tested now again and the key strokes work just great, thanks very much.
After restarting my computer it seems the error that I posted above is also not reproducible anymore.
I am closing this issue as works for me. if anyone is still having this issue, please comment and we can reopen.
If needed, please make sure you test with Libreoffice 24.8 or newer.

**Closed by Adriani90** 2024-10-03 22:50 UTC
Labels: bug, close/worksforme, app/libreoffice
