### ISSUE TITLE
NVDA won't focus new menu in Google Drive under Firefox if user is in browse mode

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#11133] opened 2020-05-08 15:39 UTC
### Steps to reproduce:

1. Load drive.google.com in Mozilla Firefox, 75 worked here.
2. press c, once the list of files appears. Note how NVDA kicks the user out of browse mode. Observe where focus is located.
3. Press escape. Force focus mode, and press c again.

### Actual behavior:

focus lands on the button, not on the menu that appears.

### Expected behavior:

Focus should move to the menu that appears on screen. It does this in other browsers, and occasionally in focus mode, or without NVDA running.

#### NVDA installed/portable/running from source:

NA, but installed

#### NVDA version:

Version: alpha-20145,cdd37c72
Reproduces on 20.1 and 19.3

#### Windows version:

(10) 1903

#### Name and version of other software in use when reproducing the issue:

Firefox, any version seems to work.

**Comment by Adriani90** [comment] 2020-05-08 18:03
cc: @jcsteh

**Comment by jcsteh** [comment] 2020-05-11 01:00
I'm confused by these STR:

>     2. press c, once the list of files appears. Note how NVDA kicks the user out of browse mode.

if the user was in browse mode, pressing c wouldn't have worked; it would have tried to navigate to a combo box. So, were you actually in focus mode? Or did you pass key through?

>     3. Press escape. Force focus mode, and press c again.

You mention you were in focus mode when you pressed c, but then:

> Focus should move to the menu that appears on screen. It does this in other browsers, and occasionally in focus mode,

It seems to me that both of these cases were in focus mode, not browse mode?

For what it's worth, I normally can't reproduce this. However, if the button isn't focused, the focus event for the button sometimes arrives after the menuStart event for the menu.

It's hard to verify with complex JS, but I'd say this is a bug in Drive. It's most likely focusing the button after it displays the menu. This won't be an issue in Chromium because it seems to reorder events so that focus events are always delivered first, regardless of actual event ordering. This is definitely not something that is guaranteed by any spec, though.

Here's a simple test case which shows a menu and then focuses a button when you press c. In Firefox, the menuStart event is delivered first, then the focus event.

`data:text/html,<body onkeydown="if (event.key == 'c') { menu.hidden = false; button.focus(); }"><button id="button">Open menu</button><div id="menu" role="menu" hidden><div role="menuitem">test</div></div>`

Interestingly, NVDA seems to reorder these events sometimes, so it sometimes works the way you'd want.

Even if Firefox reordered events so that focus always came first, this wouldn't always be desirable. For example, consider this test case which opens a menu and focuses the first item:

`data:text/html,<body onkeydown="if (event.key == 'c') { menu.hidden = false; item.focus(); }"><div id="menu" role="menu" hidden><div id="item" tabindex="-1" role="menuitem">test</div></div>`

In Chromium, the focus event for the item is always delivered before the menuStart event for the menu. But that technically means the menuStart supersedes the item focus.

**Comment by Adriani90** [comment] 2020-05-17 17:44
@jcsteh I think I can reproduce this:
My approach: Be in focus mode when pressing c first time. Have NVDA switch automatically to focus mode on system focus and carret, then it will be automatically in focus mode when opening Google drive.

Then NVDA changes to browse mode after pressing c, but instead of moving the virtual cursor to the bottom of the page where the menu is, the virtual cursor is on the menu button, not on the menu itself. Is it maybe that NVDA does not sync exactly focus and virtual cursor?
However, I am not sure how the system focus moves here. @Qchristensen could you please help visualizing this abit?


I also noticed when pressing enter in browse mode on the menu button, the menu is only expanded for a second or so and colapses again automatically afterwards. So this might be a problem in browse mode and the virtual buffer. i saw this behavior in GMail on some menu buttons as well.

The question is here actually, why does NVDA move automatically to browse mode when pressing c for the first time at all?
The focus issue is an additional problem, but they might be related to each other.

**Comment by jcsteh** [comment] 2020-05-17 22:13
> Then NVDA changes to browse mode after pressing c, but instead of moving the virtual cursor to the bottom of the page where the menu is, the virtual cursor is on the menu button, not on the menu itself. Is it maybe that NVDA does not sync exactly focus and virtual cursor?

I explained this in https://github.com/nvaccess/nvda/issues/11133#issuecomment-626419560. The focus event for the button gets fired after the menuStart event for the menu, resulting in the focus event overriding the menuStart event.

> The question is here actually, why does NVDA move automatically to browse mode when pressing c for the first time at all?

NVDA is supposed to switch to browse mode for a button. However, it's not supposed to do this for quick navigation, so I don't know why that part is breaking.

**Comment by Adriani90** [comment] 2024-03-18 22:45
This works as expected now with NVDA 2024.1 Beta 13 and firefox 123 only if automatically change to focus mode on focus changes is enabled in NVDA browse mode settings.
If this is disabled, the virtual document does not move the virtual cursor to the menu in browse mode as explained by Jamie above but this needs an external fix to redirect the focus properly and reordering events seems not really ideal. I am closing this one as works for me since there is the work around in focus mode.

**Closed by Adriani90** 2024-03-18 22:45 UTC
Labels: close/worksforme
