### ISSUE TITLE
Read special characters as normal text

### ISSUE THREAD

**Issue by HiEv** [nvaccess/nvda#16110] opened 2024-01-30 07:18 UTC
### Is your feature request related to a problem? Please describe:
There are special characters which are sometimes used to provide alternative typefaces, such as in social media, but they aren't read or translated by NVDA, they're simply skipped.  There are sites like the following to help generate text using these characters:
[https://yaytext.com/bold-italic/](https://yaytext.com/bold-italic/)

### Describe the solution you'd like:
The ability in NVDA to automatically detect and translate those characters so that they could be read.

### Additional context:
I know some Python, so I would be willing to assist with this effort if you could direct me to where this would need to be implemented.

**Comment by hwf1324** [comment] 2024-01-30 07:58
Hi, if I understand you correctly, maybe you can refer to: https://www.nvaccess.org/files/nvda/documentation/developerGuide.html#toc7

**Comment by hwf1324** [comment] 2024-01-30 08:12
This is a duplicate of #11570

**Comment by CyrilleB79** [comment] 2024-01-30 09:36
Closing as duplicate of #11570.

**Closed by CyrilleB79** 2024-01-30 09:36 UTC

**Comment by josephsl** [comment] 2024-01-30 14:38
Hi,

In addition, may I ask that folks provide expected and actual speech/braille output so we can better understand what's up? Thanks.
