### ISSUE TITLE
Input composition: When entering Korean characters, "selected" is announced each time characters are entered

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6008] opened 2016-05-27 06:33 UTC
Hi,

A Korean user writes:

When entering Korean characters in places such as Notepad and when focused on desktop icons, NVDA announces "selected" each time Korean characters are entered.

STR:
1. With Korean IME installed, open Notepad.
2. Switch to Korean/native input and type something like "r" (without quotes.

Expected: NVDA announces just the Korean character.
Actual: the word "selected" is announced along with Korean characters.

The user wishes this be looked into as soon as possible, as this extraneous announcement could be a point of confusion for NVDA users in Korea and other Asian countries.

Technical: @MichaelDCurran and @Nishimotz, settings in input composition dialog doesn't help - specifically, unchecking Report changes to the composition string" checkbox doesn't help, as it suppresses IME change announcement as a result of entering CJK characters. I'm thnking that it might be something to do with IME input getting selected. Is there a way to either suppress announcement of "selected" for specific languages such as Korean or provide a setting to announce just the characters? Thanks.

**Comment by nishimotz** [comment] 2016-05-27 14:01
As far as I have seen with Windows 10 Microsoft Korean IME and the notepad or the wordpad, the Korean character is selected visually as well.
Sometimes the selected Korean character is replaced by another Korean character, as the result of following input.
I don't think the announcement of "selected" is extraneous.

Technically, I am not sure how to determine whether the text selection is caused by Korean IME or other reasons.
Or, should we do something at tsf.cpp related to TF_DISPLAYATTRIBUTE?

**Comment by Adriani90** [comment] 2019-02-24 17:36
@josephsl, @nishimotz is this issue still reproducible in last NVDA Alpha on Windows 10 or 8.1 or 7?

**Comment by dnz3d4c** [comment] 2019-02-24 21:42
Yes, you can reproduce this issue.

> 
> 
> @josephsl, @nishimotz is this issue still reproducible in last NVDA Alpha on Windows 10 or 8.1 or 7?

**Comment by josephsl** [comment] 2024-07-15 03:28
Hi,

2024 update: I don't hear "selected" when I type Korean text in Windows 11 Notepad with modern Korean IME. Perhaps it might be the difference between modern and traditional IME used up to Windows 10.

Thanks.

**Comment by Adriani90** [comment] 2024-09-06 10:05
As indicated by @nishimotz the cahracter is selected visually, so in fact NVDA does not do anything wrong in that case. Also it seems it is not reproducible anymore in Notepad modern. If someone is still affected by this issue, please comment and we can reopen. I am closing this for now as works for me.

**Closed by Adriani90** 2024-09-06 10:05 UTC
Labels: close/worksforme, Asian character input
