### ISSUE TITLE
Symbol freezes NVDA when Read

### ISSUE THREAD

**Issue by ehollig** [nvaccess/nvda#7740] opened 2017-11-08 19:58 UTC
I noticed this when testing #5152
### Steps to reproduce:
1. Open Voice Settings
2. Ensure ESpeak is the synthesizer and change the voice to Tamil
3. Go to the Punctuation/symbol pronunciation dialog. (NVDA+N, P, P)
4. Press down arrow to the symbol ":"
5. Notice that NVDA freezes and must be restarted to continue.

### Expected behavior:
NVDA should read the line without freezing.

### Actual behavior:
NVDA freezes and a restart of NVDA is required to continue.

### System configuration:
NVDA version: Master-14590,5efe71c8
NVDA Installed or portable: Installed
Windows version: Windows 10,1703

### Other questions:
Does the issue still occur after restarting your PC? Yes
Have you tried any other versions of NVDA? Yes
next-14601,e62a168e, same issue
2017.3 portable, no issue

### Additional Information ###
I think I may have pinpointed the symbol causing the issue (ள்):
IO - speech.speak
Speaking [u'\u0bb3\u0bcd\r\n']

**Comment by Brian1Gaff** [comment] 2017-11-08 20:27
You sure have this message freezes nvda when it gets down past the bit about 
the symbol, so its an espeak character that mutes the sound as it seems to 
think its still speaking but is in fact completely silent in English for me 
after that and I have to reboot the  nvda master. version I'm running.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Brian1Gaff** [comment] 2017-11-08 20:39
IO - speech.speak (20:22:18.033):
Speaking [LangChangeCommand ('en_GB'), u'heading  level 3', u'Additional 
Information']
IO - inputCore.InputManager.executeGesture (20:22:18.555):
Input: kb(desktop):downArrow
IO - speech.speak (20:22:18.573):
Speaking [LangChangeCommand ('en_GB'), u'I think I may have pinpointed the 
symbol causing the issue (\u0bb3\u0bcd):', u'\n'

The rest of this log was totally silent even though espeak thought it was 
speaking, note that at the end after my blind reboot it failed to get past 
espeak being shut down, and presumably then had to terminate it in a rather 
poor manner!
 If this is a legal character and it seems it is in an email to the list 
then Espeak needs to be sorted before the release as this was in the latest 
master. This might explain several other hangs which I'd never thought of as 
being related to the speech engine itself.

 PS I dare not edit the text below as it will lock up again if I do. rest of 
log.]
IO - inputCore.InputManager.executeGesture (20:22:25.229):
Input: kb(desktop):alt+space
IO - speech.speak (20:22:25.275):
Speaking [LangChangeCommand ('en_GB'), u'Restore  unavailable  r  1 of 7']
IO - inputCore.InputManager.executeGesture (20:22:27.579):
Input: kb(desktop):escape
IO - speech.speak (20:22:27.612):
Speaking [LangChangeCommand ('en_GB'), u'System  subMenu  Space']
IO - inputCore.InputManager.executeGesture (20:22:32.532):
Input: kb(desktop):escape
IO - speech.speak (20:22:32.653):
Speaking [LangChangeCommand ('en_GB'), u'[nvaccess/nvda] Symbol freezes NVDA 
when Read (#7740) - Unicode (UTF-8)']
IO - speech.speak (20:22:32.654):
Speaking [LangChangeCommand ('en_GB'), u'document']
IO - speech.speak (20:22:32.655):
Speaking [LangChangeCommand ('en_GB'), u'I think I may have pinpointed the 
symbol causing the issue (\u0bb3\u0bcd):', u'\n']
IO - inputCore.InputManager.executeGesture (20:22:37.740):
Input: kb(desktop):control+alt+r
IO - speech.speak (20:22:37.785):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (20:22:37.842):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (20:22:37.845):
Speaking [LangChangeCommand ('en_GB'), u'80 space', u'blank']
INFO - core.main (20:22:37.951):
Exiting
DEBUG - core._terminate (20:22:37.951):
Terminating updateCheck
DEBUG - core._terminate (20:22:37.951):
Terminating watchdog
DEBUG - core._terminate (20:22:37.953):
Terminating global plugin handler
DEBUG - external:globalPlugins.focusHighlight.GlobalPlugin.terminate 
(20:22:38.453):
focusHighlight terminated
DEBUG - core._terminate (20:22:38.453):
Terminating gui
DEBUG - fileUtils.FaultTolerantFile (20:22:38.459):
C:\Users\Brian\AppData\Roaming\nvda\nvda.inil_n0gs.tmp
INFO - config.ConfigManager.save (20:22:38.476):
Base configuration saved
DEBUG - core.main (20:22:38.476):
calling lose focus on object with focus
DEBUG - core._terminate (20:22:38.476):
Terminating treeInterceptorHandler
DEBUG - treeInterceptorHandler.killTreeInterceptor (20:22:38.476):
Killed treeInterceptor: <virtualBuffers.MSHTML.MSHTML object at 0x0592AAD0>
DEBUG - core._terminate (20:22:38.477):
Terminating IAccessible support
DEBUG - core._terminate (20:22:38.477):
Terminating UIA support
DEBUGWARNING - _UIAHandler.UIAHandler.terminate (20:22:38.677):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (20:22:38.677):
Terminating winConsole support
DEBUG - core._terminate (20:22:38.677):
Terminating Java Access Bridge support
DEBUG - core._terminate (20:22:38.677):
Terminating app module handler
DEBUG - core._terminate (20:22:38.677):
Terminating NVDAHelper
DEBUG - core._terminate (20:22:38.680):
Terminating touchHandler
DEBUG - core._terminate (20:22:38.680):
Terminating keyboard handler
DEBUG - core._terminate (20:22:38.680):
Terminating mouseHandler
DEBUG - core._terminate (20:22:38.680):
Terminating inputCore
DEBUG - core._terminate (20:22:38.680):
Terminating brailleInput
DEBUG - core._terminate (20:22:38.680):
Terminating braille
DEBUG - core._terminate (20:22:38.680):
Terminating speech

And that os your lot.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2017-11-08 20:51
Agreed, no issue on last release portable. The character is pronounced and 
nvda carries on OK, When was the current version of Espeak Merged into 
Master last?

I'm using windows 7 64 and latest master but at the moment a portable 
version of 2017.3, as I said, it says the symbol. So the language of the 
synth is not the issue just the character, which might I guess appear on a 
web page with English still selected, in which case nvda gets stuck, ir 
rather espeak does as nvda carries on reading to a silent espeak.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment] 2017-11-08 21:02
I apologize. I did not realize this would lock up English ESpeak as well.

**Comment by Brian1Gaff** [comment] 2017-11-09 09:53
No its good to find as it needs fixing I think. Quite urgently. Since its 
not in the last stable release somebody needs to look at this. maybe its a 
problem with Unicode or perhaps a variable not defined issue due to all the 
messaging about after the xp bits were taken out. That was why I asked when 
the last version of espeak was merged into master.
 Anyone care to let me know I'm happy to run through a few versions to see 
where it goes wrong. Just put a file together with the character in it and 
we can test it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Brian1Gaff** [comment] 2017-11-09 15:20
So why is it that on this  it hangs, but on a cut and pasted character it
says tamil and the character OK. Is there some subtle difference between it
in this message and what I tried by cutting and pasting it? Could there be
more than one character  together that causes the problem

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment] 2017-11-09 22:45
CC @feerrenrut. Could this possibly be due to updating ESpeak? Although, it appears testing the Master branch before that, it still occurs.

**Comment by Brian1Gaff** [comment] 2017-11-10 09:32
Not for me it does not.
I just tried it with before and after runs of the archives back on the 1st 
of this month.



I'm using windows 7. I also note that it is in fact two chars  together.
This is the version merged in snap
nvda_snapshot_master-14578,d63f4ed4.exe
nvda_snapshot_master-14578,d63f4ed4.exe

The one prior is unaffected.
 Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by feerrenrut** [comment] 2017-11-13 07:20
I have confirmed that this issue is not present in d232c913, if the later of d63f4ed4 is the first in which this problem happens, then there are 3 commits it could have been due to:
- Update espeak (PR #7583) 9e8c05fbdba102bef7ce334e21a439ec8be82bb2
- Update changes file for PR #7583 0ff1224ad84762ae75242047af2b76de779d58f7
- Move voice dict files (PR #7666) d63f4ed4710631e773aca13246bf52049fa7c605 

Updating espeak is the most suspicious. This change includes a Tamil specific change: the introduction of emoji handling. Removing this emoji file from the build of NVDA and the freeze seems to go away for both English and Tamil when speaking the character described in this issue.

**Comment by Brian1Gaff** [comment] 2017-11-13 09:33
Yes as I said. the dictionary change only affects orphaning off files with 
the old name construct so should not affect normal performance at all.
 I agree.
 maybe its not being trapped correctly somewhere or something really daft. 
is there any way to stress test espeak with every known code to see if there 
are any other gotchas waiting out there?

One other issue how is it that the characters are not seen in the log 
produced during this  problem?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by feerrenrut** [comment] 2017-11-13 09:37
This approach means that emoji will not be supported for Tamil. Please try the following build to confirm that the problem is resolved and leave a comment here. https://ci.appveyor.com/api/buildjobs/ux1v4wj356282hqg/artifacts/output%2Fnvda_snapshot_try-i7740-fixEspeakFreezeWithTamilEmoji-14614%2C6f53b534.exe

**Comment by derekriemer** [comment] 2017-11-13 10:02
This fixes the unrelated tamil freeze I saw when opening voice settings after setting the language. Not sure if it fixes the original issue.

**Comment by feerrenrut** [comment] 2017-11-13 10:25
Thanks Derek, is there an open issue for the voice settings problem? I couldn't find it. If so, could you comment it on the PR #7751

**Comment by ehollig** [comment] 2017-11-13 14:43
@feerrenrut, this try build fixes the issue for reading the symbol both in English and Tamil.
Interestingly though, in NVDA master-14609,14811579 when I read the symbol, it appears as if there is one character when reading character by character. When using this try build, it appears that there is two characters.
I think the issue @derekriemer is referring to is, NVDA froze when he was checking the Punctuation/symbol level in the voice settings dialog when the voice was set to Tamil. A different issue, but related to this issue, as I believe ESpeak is freezing whenever it encounters a ":" in the Tamil language.
Again, this is fixed with the try build though.

**Comment by Brian1Gaff** [comment] 2017-11-13 15:04
Yes i tried to make this point earlier. I was very surprised that it was 
triggered in the UK English version of Espeak, I guess because it is capable 
of switching its language.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by derekriemer** [comment] 2017-11-13 23:58
no, if I checked a box in any setting dialog with tamil, it would freeze.

**Closed** 2017-11-14 09:42 UTC
Labels: freeze, p1, Speech
