### ISSUE TITLE
Making an add-on compatible by changing the manifest after marked as incompatible brings the add-on in stuck incompatible state.

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#15401] opened 2023-09-08 05:55 UTC
Note, while this is really an edge case, i thought I'd yet report.

### Steps to reproduce:
1. Update to NVDA alpha-29119
2. During the update, add-ons will be marked as incompatible.
3. Change the manifest for an installed add-on to make it compatible again by changing the last tested version.

### Actual behavior:
In the add-ons manager, the add-on is marked as disabled incompatible, yet it is not possible to enable the add-on. Only Remove, Help and Homepage are available. Note that this is an external add-on that wasn't installed from the store. There is no incompatible reason mentioned in the `other details` edit box.

### Expected behavior:
Either:

1. The add-on is enabled again since it is now compatible and the previous state was enabled.
2. The add-on is still marked as incompatible, but you can yet enable it.

### NVDA logs, crash dumps and other attachments:
No errors whatsoever.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29119

#### Windows version:
Windows 11 22H2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by Brian1Gaff** [comment] 2023-09-08 07:39
Ah, so the issue is that it was downloaded manually then, not the add on itself? I thought it was me going mad.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment] 2023-09-11 06:29
I think we should only consider this an issue if it applies to add-ons which prior to 2023.2, had an edited manifest. If your starting state is the add-on store, and you manually edit an add-ons manifest, you are doing this at your own risk and outside of the support of the add-on store

**Comment by seanbudd** [comment] 2023-09-11 23:43
Closing this as won't fix

**Closed by seanbudd** 2023-09-11 23:43 UTC
