### ISSUE TITLE
NVDA isn't able to detect skype message window I think

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4964] opened 2015-03-08 12:15 UTC
**Reported by bdorer on 2015-03-08 12:15**
A german user reports NVDA isn't able to announce the first, second message, etc. I'll attach his log.
**Blocked by #4972**

**Comment by Adriani90** [comment] 2019-01-12 15:47
@bdorer, @k-kolev1985, @jcsteh can you reproduce this in last skype version?

**Comment by Adriani90** [comment] 2019-01-28 21:40
@k-kolev1985 I am trying to reproduce this issue but cannot. If this is not an issue in Skype 8, I would suggest to close it because the interface changed significantly.

**Comment by leonardder** [comment] 2019-01-29 07:42
Closing this, since Skype has been entirely rewritten.

**Comment by leonardder** [comment] 2019-01-29 07:42
Closing this, since Skype has been entirely rewritten.

**Closed by leonardder** 2019-01-29 07:42 UTC
Labels: App specific: Skype for Desktop, bug
