### ISSUE TITLE
Current profile name in settings title

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#7926] opened 2018-01-21 20:57 UTC
Discussing with a basic NVDA user, I noticed that it's not so clear the relationship between per-application profile creation and modifying preference.
So, I think: why not provide an immediate indicator of current profile in settings dialog title?
It's useful also for advanced users, for an immediate validation...

**Comment by leonardder** [comment] 2018-01-22 04:53
Closing as duplicate of #3644

**Closed by leonardder** 2018-01-22 04:53 UTC
Labels: NVDA GUI, feature
