### ISSUE TITLE
Add a warning about Firefox 57 and later to start screen of nvda

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7710] opened 2017-10-29 08:51 UTC
Since we now are aware that this version of Firefox has serious slow down issues and the eventual aim is to no longer support screenreaders in the traditional way that most screenreaders expect for security reasons. I feel that the next version of nvda should carry a warning about the use of later versions of Firefox until the access issues have been sorted out. This should apply to updates and new installations etc.
 I don't think an average user would be aware of the problems and it may well put people off using nvda if Firefox is sluggish or not working at all. Not everyone uses windows 10 and has access to Edge or will want to use it.

 Brian

**Comment by dkager** [comment] 2017-10-29 11:39
I feel putting this on the welcome screen is a bit of a strong reaction, though I can definitely see why you would want this at the top of the release notes.

**Comment by Brian1Gaff** [comment] 2017-10-29 17:27
One has to imagine you are a first installer though. I find that human kind, 
me included seldom reads stuff, we tend to go in and play, and hence they 
would need to definitely  look at your notes , but may not realise they are 
even there.
 This is going to spread like wildfire as Jaws already has an article and 
Dolphin are having issues as well, so I tend to feel, that although it may 
seem  drastic, something needs to be done given that the opportunity is in 
our laps with a new version soon to appear. Seems like fate to me.
 Of course I realise it will need translation which is why I brought it up 
now.

Even if it says just Note  If you use Firefox,  please use  versions prior 
to 57, due to  changes in the browser affecting accessibility.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment] 2017-10-31 19:35
There is now an official statement in the last NVDA in process. Personally, I don't think the welcome screen should be used for warning people about the use of FF57.

**Comment by Brian1Gaff** [comment] 2017-11-01 16:20
Why not?

 New users might not be able to just go to the web site. maybe we should 
consider what many other bits of software do, ie display the read me first 
file or a web page before you are allowed in. the latter of course might be 
a catch 22 if the machine already has the offending version of Firefox on 
it!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by derekriemer** [comment] 2017-11-01 23:23
Going for no in the welcome screen. 
"Welcome to NVDA, hey this software doesn't work!" is not a good message to send.

**Comment by Brian1Gaff** [comment] 2017-11-02 09:24
I don't think that was what was being suggested actually!
 I do feel here that as there is a lot of stuff about improvements on 
Firefox in whats new, maybe that needs a little star to say firefox 55 or 
earlier ( 56 having the fucus bug if the sidebar is open)
  Maybe then if Whats new is flagged folk might be able to see the issue.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by bramd** [comment] 2017-11-04 14:00
From a user experience point of view, I think a clear warning is a good idea. Many less technical users might just update NVDA and are not that interested in the what's new documentation. It also will have a low priority in most translation teams that don't have many resources, so might not even be available in their own language.

I didn't try Firefox 57 and I'm not sure how bad the experience will be. However, if the official NVAccess statement is to avoid this version, I think we should communicate that as clearly as possible to all users. I know we already have a string freeze for NVDA 2017.4, however may be adding an Firefox appmodule that does a version check and gives a warning on first use might be a good idea? We could even include a link/reference to nvaccess.org for more information.

**Comment by dkager** [comment] 2017-11-04 14:34
I'd rather see a one-time, app-specific warning.

**Comment by Brian1Gaff** [comment] 2017-11-05 09:16
I'd agree. I was expecting when I downloaded 57 off the shelf, at present in 
beta of course, for this checkbox to be off and that firefox would work, 
albeit very sluggishly. However I downloaded it from my windows 7 machine 
directly as an update from 55 beta and even after a complete system restart, 
only the menus worked no sign of focus or brows mode, just lots of unknowns 
.
 If the beta has this checkbox on for some reason how can one get it to be 
off when half the interface won't work?
 However it might just be that the beta is broken, and the release might be 
better, but we need to know this, as I decided on the mess I ended up with 
to downdate again and switch off updates.

 I guess there could well be a work around to fix this, but its dicey this 
close to a release to say, it will work although,  slowly when My experience 
of it shows otherwise.

Just saying, ie, I'm just a user, but to me it seems that with the warning 
on the blog and my experience it  is debatable what a user might encounter, 
especially a new user. Maybe its different for Windows 7 than 10?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Brian1Gaff** [comment] 2017-11-05 09:25
if I was doing things in this situation, I think I'd want to put a short 
delay on the release of nvda, and actually see what the release of Firefox 
57 did in reality, on all supported operating systems, then if needed add a 
warning on the start page which most people bypass after installation, but 
that then still leaves those who update and do not read any lists or bloggs 
suddenly getting whatever they get and scratching their heads.
 I do notice that some software nowadays seems to have a part of their 
update or installers that does give a message to the user, like I saw on a 
recent K-lite update, note this is the last version which will install on 
windows xp  for example.

The odd thing about that one is that it is not read by default by a 
screenreader! grin.

I wonder is there any way a screenreader installed as admin could turn off 
that checkbox directly.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by craigbrett17** [comment] 2017-11-15 21:11
I wouldn't want it coming up in the welcome screen myself. Speaking as someone who's just failed to prevent the update and had to try jumping to the beta to see if it will get resolved even sooner. 

That being said, this hit me at work today unexpectedly. They've got some nerve gloating about its speed! It's like Kim Kardashian gloating about her prospects for a doctorate. 

I'd suggest a better approach might be for the Firefox module to check the version of Firefox (if possible) and warn users of 57 with a popup or similar when they launch it that there are known incompatibility issues, and to try Edge (if on Win10+) or Chrome. Chrome is also not a great experience with NVDA, but the problem is less sluggishness, and more just general Chromium doesn't like accessible tech as much as it should.

**Comment by Brian1Gaff** [comment] 2017-11-16 10:04
Also of course some of us have failed miserably to get the new firefox to 
even read page content despite all the checkboxes being set as they should 
be. also any sounds you had set up in ff will be gone forever along with 
many other add ons.

I use windows 7, and thus far now I've moved to the esr release no prompt to 
update has occurred. I say prompt as I learned a long time ago not to let ff 
just update automatically as it can create a mess.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ehollig** [comment] 2017-11-17 15:44
I am leaning toward a wontfix here, as there already is an official statement in the last NVDA in process.

**Comment by dkager** [comment] 2017-11-17 15:45
I concur.

**Comment by ehollig** [comment] 2017-11-17 15:47
Closing as wontfix

**Closed by ehollig** 2017-11-17 15:47 UTC

**Comment by derekriemer** [comment] 2017-11-17 15:57
I concur.

**Comment by Brian1Gaff** [comment] 2017-11-17 18:02
Well , I'm still not convinced from my own experience of it.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by craigbrett17** [comment] 2017-11-19 19:08
I do not concur
