### ISSUE TITLE
Microsoft Edge: search suggestions not announced in address bar

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5368] opened 2015-09-18 05:11 UTC
**Reported by nvdakor on 2015-09-18 05:11**
Hi,
This could be a variation on #5049:
When a user types addresses or search terms into Microsoft  Edge's address/search bar, suggestions such as URL's are not announced.
STR:
1. Open Microsoft Edge.
2. Press Alt+D to go to address/search bar.
3. Type something.
Expected: NVDA announces search suggestions, and in case of URL's, the rest of the URL is announced.
Actual: No announcement.

Setup:
- NVDA version: 2015.3, next.12528.
- OS: Windows 10 RTM (10240)

Technical: Microsoft Edge's address bar gives the following developer info:

```
name: u'Search or enter web address'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: 1
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x04F4F410>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (319, 277, 334, 32)
value: u''
appModule: <'appModuleHandler' (appName u'microsoftedge', process ID 4140) at address 515f9b0>
appModule.productName: u'Microsoft Edge'
appModule.productVersion: u'11.00.10240.16463'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 919940
windowClassName: u'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: 1409286144
windowThreadID: 4388
windowText: u'Microsoft Edge'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x63d8220 at 51c1d00>
UIA automationID: addressEditBox
UIA frameworkID: XAML
UIA runtimeID: (42, 919940, 2, 6)
UIA providerDescription: [Main(parent link):Unidentified Provider (unmanaged:Windows.UI.Xaml.dll)](pid:4140,hwnd:0x0)
UIA className: RichEditBox
```

Probing this control with Accevent (part of Windows 10 SDK) shows that selection selected event is fired when search suggestions (including URL's) are returned, which suggests the solution could involve adding a new Edge overlay class to handle this control (using the routine employed in ticket 5049 for Start search suggestions).
Thanks.

**Comment by Adriani90** [comment] 2019-02-02 00:12
This is still reproducible with NVDA Alpha 16691,10590C87. @josephsl are you planning to raise a pull request with the coresponding part of your windows 10 app essentials addon?

**Comment by josephsl** [comment] 2019-02-02 00:48
Hi, not anytime soon.

**Comment by Adriani90** [comment] 2020-04-25 00:26
Closing as works for me, this works as expected in Edge Chromium 81.

**Closed by Adriani90** 2020-04-25 00:26 UTC
Labels: app/edge, enhancement, p3
