### ISSUE TITLE
Log error messages

### ISSUE THREAD

**Issue by DalisonCPU** [nvaccess/nvda#10724] opened 2020-01-27 22:41 UTC
### Actual behavior:
NVDA works normally, but whenever a window is opened the error sound is played.
### Expected behavior:
That the error sound is not reproduced
#### NVDA installed/portable/running from source:
Instaled version
#### NVDA version:
NVDA 2019.3beta2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Windows Explorer and Google Chrome
#### Other information about your system:
This error occurs whenever a window is opened. The log with the information will be at the bottom.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
In the 2019 beta1 version this error did not happen.

LOG:
```
INFO - __main__ (19:15:36.735) - MainThread (3560):
Starting NVDA version 2019.3beta2
INFO - core.main (19:15:37.137) - MainThread (3560):
Config dir: C:\Users\flávio\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (19:15:37.137) - MainThread (3560):
Loading config: C:\Users\flávio\AppData\Roaming\nvda\nvda.ini
INFO - core.main (19:15:37.211) - MainThread (3560):
Using Windows version 10.0.18363 workstation
INFO - core.main (19:15:37.211) - MainThread (3560):
Using Python version 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)]
INFO - core.main (19:15:37.211) - MainThread (3560):
Using comtypes version 1.1.7
INFO - core.main (19:15:37.211) - MainThread (3560):
Using configobj version 5.1.0 with validate version 1.0.1
ERROR - RPC process 4088 (nvda.exe) (19:15:37.416) - Dummy-1 (8580):
Thread 3560, build\x86\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for IAccessible2Proxy.dll

ERROR - RPC process 4088 (nvda.exe) (19:15:37.453) - Dummy-1 (8580):
Thread 3560, build\x86\remote\ia2Support.cpp, installIA2Support, 59:
Error registering IAccessible2 proxy

ERROR - RPC process 4088 (nvda.exe) (19:15:37.491) - Dummy-1 (8580):
Thread 3560, build\x86\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for ISimpleDOM.dll

ERROR - RPC process 4088 (nvda.exe) (19:15:37.531) - Dummy-1 (8580):
Thread 3560, build\x86\remote\ia2Support.cpp, installIA2Support, 63:
Error registering ISimpleDOM proxy

INFO - synthDrivers.espeak.SynthDriver.__init__ (19:15:37.759) - MainThread (3560):
Using eSpeak NG version b'1.49.3 dev'
INFO - synthDriverHandler.setSynth (19:15:39.002) - MainThread (3560):
Loaded synthDriver espeak
INFO - core.main (19:15:39.002) - MainThread (3560):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (19:15:39.003) - MainThread (3560):
Braille input initialized
INFO - braille.initialize (19:15:39.004) - MainThread (3560):
Using liblouis version 3.10.0
INFO - braille.initialize (19:15:39.006) - MainThread (3560):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (19:15:39.010) - MainThread (3560):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (19:15:39.136) - MainThread (3560):
Java Access Bridge support initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (19:15:39.146) - _UIAHandler.UIAHandler.MTAThread (8296):
UIAutomation: IUIAutomation6
INFO - core.main (19:15:43.721) - MainThread (3560):
NVDA initialized
ERROR - RPC process 8664 (notepad.exe) (19:15:53.291) - Dummy-1 (8580):
Thread 6232, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for IAccessible2Proxy.dll

ERROR - RPC process 8664 (notepad.exe) (19:15:53.329) - Dummy-1 (8580):
Thread 6232, build\x86_64\remote\ia2Support.cpp, installIA2Support, 59:
Error registering IAccessible2 proxy

ERROR - RPC process 8664 (notepad.exe) (19:15:53.367) - Dummy-1 (8580):
Thread 6232, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for ISimpleDOM.dll

ERROR - RPC process 8664 (notepad.exe) (19:15:53.403) - Dummy-1 (8580):
Thread 6232, build\x86_64\remote\ia2Support.cpp, installIA2Support, 63:
Error registering ISimpleDOM proxy

ERROR - RPC process 2908 (TeamTalk5Classic.exe) (19:16:03.667) - Dummy-1 (8580):
Thread 5896, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for IAccessible2Proxy.dll

ERROR - RPC process 2908 (TeamTalk5Classic.exe) (19:16:03.705) - Dummy-1 (8580):
Thread 5896, build\x86_64\remote\ia2Support.cpp, installIA2Support, 59:
Error registering IAccessible2 proxy

ERROR - RPC process 2908 (TeamTalk5Classic.exe) (19:16:03.742) - Dummy-1 (8580):
Thread 5896, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for ISimpleDOM.dll

ERROR - RPC process 2908 (TeamTalk5Classic.exe) (19:16:03.783) - Dummy-1 (8580):
Thread 5896, build\x86_64\remote\ia2Support.cpp, installIA2Support, 63:
Error registering ISimpleDOM proxy

ERROR - RPC process 10344 (chrome.exe) (19:17:05.976) - Dummy-3 (8888):
Thread 6748, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for IAccessible2Proxy.dll

ERROR - RPC process 10344 (chrome.exe) (19:17:06.018) - Dummy-3 (8888):
Thread 6748, build\x86_64\remote\ia2Support.cpp, installIA2Support, 59:
Error registering IAccessible2 proxy

ERROR - RPC process 10344 (chrome.exe) (19:17:06.053) - Dummy-3 (8888):
Thread 6748, build\x86_64\remote\COMProxyRegistration.cpp, registerCOMProxy, 63:
LoadLibrary failed for ISimpleDOM.dll

ERROR - RPC process 10344 (chrome.exe) (19:17:06.088) - Dummy-3 (8888):
Thread 6748, build\x86_64\remote\ia2Support.cpp, installIA2Support, 63:
Error registering ISimpleDOM proxy
```

**Comment by Adriani90** [comment] 2020-01-27 23:08
Could you please run the com registration fixing tool in nvda menu / tools? Is the issue still occuring after that?

**Comment by DalisonCPU** [comment] 2020-01-28 01:59
Yes, I used this tool function but it didn't work.
-----Mensagem original-----
De: Adriani90
Enviada em: Segunda, 27 de Janeiro de 2020 15:08
Para: nvaccess/nvda
Cc: DalisonCPU; Author
Assunto: Re: [nvaccess/nvda] Log error messages (#10724)

Could you please run the com registration fixing tool in nvda menu / tools? Is the issue still occuring after that?

**Comment by Brian1Gaff** [comment] 2020-01-28 08:22
Did you reboot the machine after running the tool?
 One other question, have you changed or updated any other software since 
the beta 1 worked, IE if you run beta 1 now does it still work?
 If for example something  like Avast or avg is on the machine I have found 
some very odd issues with loading bits of nvda. No idea as to why myself, 
but often a complete removal and running the registration tool fixes 
whatever daft thing was going on.
 it could be a red herring but it would be best to find out if the old 
version still runs in case its an unrelated issue in windows.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Adriani90** [comment] 2020-01-28 11:12
cc: @michaelDCurran it seems the registration fixing tool fails here. According to the log the DLLs are not registered completely. It seems to affect Google Chrome, Teamtalk 5 and Notepad.
@DalisonCPU have you tested with all addons disabled and also using different synthesizers?

**Comment by feerrenrut** [comment] 2020-01-29 16:30
@DalisonCPU Can you attach the NVDA log after running the com registration fixing tool please? Perhaps we can see why it fails.

**Comment by Adriani90** [comment] 2020-01-30 21:36
@DalisonCPU could you please tell us if this is still reproducible in NVDA 2019.3 Beta 3 after restarting your PC? Please also disable the addons when reproducing this issue. Thanks.

**Comment by DalisonCPU** [comment] 2020-01-30 22:55
In beta 3 this error no longer occurs.
Thank you.
-----Mensagem original-----
De: Adriani90
Enviada em: Quinta, 30 de Janeiro de 2020 13:36
Para: nvaccess/nvda
Cc: DalisonCPU; Mention
Assunto: Re: [nvaccess/nvda] Log error messages (#10724)

@DalisonCPU could you please tell us if this is still reproducible in NVDA 2019.3 Beta 3 after restarting your PC? Please also disable the addons when reproducing this issue. Thanks.

**Comment by Adriani90** [comment] 2020-01-30 23:12
Thanks. Closing as works for me.

**Closed by Adriani90** 2020-01-30 23:12 UTC
Labels: worksforme
