### ISSUE TITLE
Question: MathML/MathPlayer support overview

### ISSUE THREAD

**Issue by pkra** [nvaccess/nvda#5555] opened 2015-11-29 12:24 UTC
Not sure if that fits on the tracker; please let me know if this is better posted elsewhere. 

Is there a good resource on what combinations of Windows+Browser (versions) are supported by NVDA+MathPlayer? For example, I can't get any browser to work on Windows 8.1 (neither IE11 in enterprise mode (or not), nor current Firefox or Chrome); but searching around I find discussions indicating that this is supported. (Here's a plain MathML sample I was using http://s.codepen.io/pkra/debug/JYgRPV)

**Comment by jcsteh** [comment] 2015-11-30 02:49
It should work with any reasonably recent version of Firefox and IE 8 
and later. (I haven't tested IE 6 and 7.) It definitely doesn't work in 
Chrome, as Chrome doesn't expose what we need.

Can you be more specific about exactly what happens when you say "can't 
get any browser to work"? I do know that several users have experienced 
problems with MathPlayer installs which cause it to completely fail when 
NVDA tries to access math. I've never been able to reproduce this 
myself, but completely reinstalling MathPlayer should help if this is 
the issue. If you do try this, it'd be great if you can grab your 
MathPlayer install log from it's directory in Program Files first, as 
that might be useful to Design Science to track this down.

**Comment by pkra** [comment] 2015-11-30 10:01
Thanks for the response, James. For background, I am currently testing MathJax's AssistiveMML extension (that's the one embedding hidden MathML) for the changes you suggested (use role=presentation etc). This is the sample I use for the updated AssitiveMML extension http://s.codepen.io/pkra/debug/NGojag. Whenever I encounter issues, I test this plain MathML sample: http://s.codepen.io/pkra/debug/JYgRPV. See also https://github.com/mathjax/MathJax-docs/issues/111 for our ongoing documentation work.

> Can you be more specific about exactly what happens when you say "can't
> get any browser to work"?

Just for completeness: NVDA was working fine generally but MathML produced silence. When I explored (using up/down arrow keys to move through lines), NVDA read the text paragraphs in the MathML sample but the line with MathML produced silence.

> completely reinstalling MathPlayer should help if this is the issue.

Great! Reinstalling helped (in my case, both Windows 8.1 and  Windows 10 needed a reinstallation).

On Windows 8.1, the plain MathML sample now works in Firefox and even IE11 -- although I had to disable Enterprise mode on IE11 despite [DesignScience saying it is required](http://www.dessci.com/en/products/mathplayer/download.htm). I'm happy to share the MathPlayer installation log if you want it but I guess I should have kept the previous one which had the problem. Let me know if you still want it.

On Windows 10, I got Firefox to work. Edge does not work (NVDA reads "x 2" for the line with MathML) but IIRC NVDA does not yet support Edge.

Even better, the approach of using role=presentation on the AssistiveMML extension works; I sometimes had trouble navigating but that's almost certainly just me still learning to use NVDA. 

For what it's worth, 

* On WinXP I could not install MathPlayer (its installer failed repeatedly), so I didn't test anything there.
* I could not get Chrome to read MathML on Windows 7, 8.1, or 10; just silence. Is Chrome supported?
* On Win7, I had no issues with IE9, IE10, Firefox.

Thanks again for your all your help in this.

I'm still interested in getting some better documentation together. Obviously, we'll have our results in our documentation but maybe a larger group can do better together.

**Comment by jcsteh** [comment] 2015-11-30 11:04
@NSoiffer: See below regarding the MathPlayer bits.

> Great! Reinstalling helped (in my case, both Windows 8.1 and Windows 10 needed a reinstallation).

Hmmm. I've heard of quite a few users having this problem. It's a shame you didn't manage to get the install log. I wish we could track that problem down.

> On Windows 8.1, the plain MathML sample now works in Firefox and even IE11 -- although I had to disable Enterprise mode on IE11 despite DesignScience saying it is required.

The whole situation with MathPlayer and IE is really confusing. You need enterprise mode if you want the MathPlayer browser plug-in to work, but that's for visual rendering. NVDA doesn't use the browser plug-in at all; it uses the MathPlayer library separately. IMO, Design Science should have distributed the MathPlayer a11y library as an entirely separate product, but apparently, someone there doesn't agree.

That said, NVDA should ideally work *regardless* of the IE plug-in, so I'm concerned that having it enabled broke this. I'm pretty sure i tested this for earlier versions of IE. What happens in that case? Just silence again?

> Edge does not work (NVDA reads "x 2" for the line with MathML) but IIRC NVDA does not yet support Edge.

NVDA does have preliminary support for Edge. Full support is pending necessary changes b Microsoft. Note that there is no way at all (even a hacky/insane way) for ATs to access MathML in Edge. You'd need to take that one up with Microsoft. We (and other AT vendors) have already made it fairly clear to them that this is important, but there's been no movement on that yet AFAIK.

> On WinXP I could not install MathPlayer (its installer failed repeatedly), so I didn't test anything there.

MathPlayer doesn't support aXP, only Vista and above. When I last checked, this wasn't documented and I requested that this be fixed, but I'm not sure whether that got done or not. 

> I could not get Chrome to read MathML on Windows 7, 8.1, or 10; just silence. Is Chrome supported?

Quoting my [original reply](https://github.com/nvaccess/nvda/issues/5555#issuecomment-160503827):

> It definitely doesn't work in Chrome, as Chrome doesn't expose what we need.

**Comment by pkra** [comment] 2015-11-30 11:17
Thanks, James.

> That said, NVDA should ideally work regardless of the IE plug-in, so I'm concerned that having it enabled broke this. I'm pretty sure i tested this for earlier versions of IE. What happens in that case? Just silence again?

I did not try to activate the IE plugin. Will try to find the time to try that.

> NVDA does have preliminary support for Edge. Full support is pending necessary changes b Microsoft. Note that there is no way at all (even a hacky/insane way) for ATs to access MathML in Edge. You'd need to take that one up with Microsoft. We (and other AT vendors) have already made it fairly clear to them that this is important, but there's been no movement on that yet AFAIK.

Right; sorry for making it sound like it was NVDA's fault. If there are issue threads on the Microsoft side that you want us to add comments to, could you share some links?

> MathPlayer doesn't support aXP, only Vista and above. 

Thanks for confirming.

> Quoting my original reply:
> It definitely doesn't work in Chrome, as Chrome doesn't expose what we need.

Oh, bugger. Sorry for missing that!

**Comment by jcsteh** [comment] 2015-11-30 12:01
> I did not try to activate the IE plugin. Will try to find the time to try that.

Oh. So you're saying it didn't work in IE 11 enterprise mode even with the plug-in deactivated? (I thought the installer just installed and activated it automatically.)

> Right; sorry for making it sound like it was NVDA's fault.

I didn't interpret it that way. Edge is still a huge hole for accessibility as far as we're concerned. Just wanted to make the situation clear.

> If there are issue threads on the Microsoft side that you want us to add comments to, could you share some links?

As is fairly typical with Microsoft, there's nothing public we can link to. If only there was...

**Comment by pkra** [comment] 2015-11-30 14:55
> Oh. So you're saying it didn't work in IE 11 enterprise mode even with the plug-in deactivated? 

Yes, the plain MathML sample had not worked in IE11 enterprise mode with the IE plugin deactivated. 

Trying again now in Enterprise mode, the plain MathML sample is not voiced (see more below) while the MathJax/AssistiveMML sample works. FYI, the MathML voicing in the MathJax sample is preceded by "embedded object".

But by now I'm convinced that this will magically change the next time I start the VM ;-)

> (I thought the installer just installed and activated it automatically.)

I'm not sure. IE 11 lists two "Add-ons": "MathPlayer" and "MathPlayer BrowserHelperObject"; I don't recall the others but will check when I get the chance. After installation of MathPlayer, opening IE usually shows a popup, asking if I want to activate the  "MathPlayer BrowserHelperObject" which I always decline given other issues (see below). But the "MathPlayer" plugin seems to be activated automatically.

I activated the BrowserHelperObject as promised earlier. Using Enterprise Mode with the plain MathML sample, this gets MathPlayers' visual rendering working and NVDA also voices the MathML (after twice voicing "embedded object"). The MathJax sample continues to work. Fun fact: switching MathJax to NativeMML output crashes IE11 end as does mouse clicking on MathPlayer's rendering in the plain MathML sample.

With the Helper Addon and not using Enterprise mode, the plain MathML sample is voiced as "x 2" and the MathJax sample is voiced correctly.

(I do come away with the feeling that I should screencapture every single testing to avoid the feeling "I was sure it did / didn't work before". Oh well, automated tests remain a fantasy.)

**Comment by pkra** [comment] 2015-11-30 20:47
In case it's helpful, I think I've tested all necessary configurations and it seems I could get everything to work that could be made to work. I've collected that at (for MathJax but tests were also with plain MathML) https://github.com/mathjax/MathJax-docs/issues/111.

**Comment by pkra** [comment] 2015-11-30 20:48
Thanks again for your assistance (and patience!), @jcsteh.

**Comment by NSoiffer** [comment] 2015-12-07 07:35
Sorry for coming late to the discussion. Based on the useful table that
Peter posted at mathjax/MathJax-docs#111
<https://github.com/mathjax/MathJax-docs/issues/111>, there are two
MathPlayer issues:

1.  The installer sometimes fails to install
2.  MJ and MathPlayer for IE are not playing well together

I had hoped to come out with another beta for MathPlayer 4 almost a month
ago, but when I gave it out to some people, I found that MS had done major
damage to the technology MathPlayer uses for IE on Windows 10.
IE11+MathPlayer on Win 7 was working great in enterprise mode -- on Win 10,
it randomly draws/doesn't draw despite MathPlayer doing identical things
when it draws and when it doesn't draw. Also, they messed up scrolling.
I've spent the last month trying to verify that MathPlayer really isn't at
fault and also trying workarounds likes forcing extra draws, expanding the
bounding box it can draw into, etc. No luck. I given up and will try to put
out a release this week.

The new release should cut down on the failures for the install. I think it
fixes the problem with MJ and MP not playing well together also. I'd like
to give up on the visual rendering because IE is a black hole for time, but
we still have people who depend on it.

If there is some action that I need to take that I missed, please let me
know.

     Neil

**Comment by jcsteh** [comment] 2017-05-18 00:58
I've just submitted PR #7184 to get MathML supported in Chrome (59 and later).

I'm closing this issue because it was more of a series of questions rather than a bug and because I believe all of those questions have been addressed in some way or another. Please reopen if you disagree.

**Closed by jcsteh** 2017-05-18 00:58 UTC
