### ISSUE TITLE
NVDA sometimes clicks the wrong element when in Firefox browse mode

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#5903] opened 2016-04-27 16:00 UTC
The title of this issue is somewhat vague, this is because I haven't been able to accurately reproduce this yet.
It does crop up often enough to be annoying though, so I'll try to write up what I've found so far.
This happens on latest Windows 10 Insider Build, with latest NVDA Next. Flow:
- You are on a webpage and try to click something using Enter. Not sure, but the problem seems to happen more often when the item you are clicking on isn't marked up as a link or button (e.g. clickable div, clickable heading etc)
- expected result is that the selected item is activated.
- Observed result is that either nothing will get clicked, or you get catapulted to another place within the same window or sometimes even other windows. When you try to route mouse to NVDA on such an element, you will either get an error, nothing will be announced or the wrong item will be routed to.

I have found that using the windows+arrows and control+windows+arrows keys on Windows 10, the keys that govern where a window resides on the screen, can sometimes help in fixing these issues at least partially. But at that point you're just randomly moving windows around and hope it works.
I'm not sure if this is a Windows, Firefox or NVDA bug. Is this a duplicate?

**Comment by derekriemer** [comment] 2016-04-27 18:17
Do you have focus highlight installed?


On 4/27/2016 10:00 AM, Florian Beijers wrote:
>
> The title of this issue is somewhat vague, this is because I haven't 
> been able to accurately reproduce this yet.
> It does crop up often enough to be annoying though, so I'll try to 
> write up what I've found so far.
> This happens on latest Windows 10 Insider Build, with latest NVDA 
> Next. Flow:
>
>   * You are on a webpage and try to click something using Enter. Not
>     sure, but the problem seems to happen more often when the item you
>     are clicking on isn't marked up as a link or button (e.g.
>     clickable div, clickable heading etc)
>   * expected result is that the selected item is activated.
>   * Observed result is that either nothing will get clicked, or you
>     get catapulted to another place within the same window or
>     sometimes even other windows. When you try to route mouse to NVDA
>     on such an element, you will either get an error, nothing will be
>     announced or the wrong item will be routed to.
>
> I have found that using the windows+arrows and control+windows+arrows 
> keys on Windows 10, the keys that govern where a window resides on the 
> screen, can sometimes help in fixing these issues at least partially. 
> But at that point you're just randomly moving windows around and hope 
> it works.
> I'm not sure if this is a Windows, Firefox or NVDA bug. Is this a 
> duplicate?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5903>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by zersiax** [comment] 2016-04-27 18:19
nope

**Comment by derekriemer** [comment] 2016-04-27 21:11
Okay. This may very well have to do with DPI aware. CC @jcsteh


On 4/27/2016 12:19 PM, Florian Beijers wrote:
>
> nope
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5903#issuecomment-215180302>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment] 2016-04-27 23:23
Firefox is DPI aware, so DPI awareness isn't the issue. More likely, the 
element was off-scree or Firefox reported the wrong location.

When this occurs, if you press NVDA+numpad5 (laptop: NVDA+shift+o) to 
read the current object while the cursor is over the problematic object, 
what does NVDA report? The developer info (NVDA+f1) might also be 
interesting.

**Comment by jcsteh** [comment] 2016-04-28 04:54
Oh... also, is it possible you zoomed the page with Firefox (whether intentional or not)? You can reset zoom by pressing control+0. Firefox certainly used to report incorrect locations when zoomed and I suspect that's still the case.

**Comment by zersiax** [comment] 2016-04-28 08:55
Took me a while to reproduce it, but:
- I went to a website that exhibits the behavior. the nvda=Shift+o
reports 'TextFrame", while the control under the cursor should
actually be a link.
- Developer info reports the following:
Developer info for navigator object:
name: None
role: ROLE_TEXTFRAME
states:
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x03288810>
Python class mro: (<class 'NVDAObjects.IAccessible.mozilla.Mozilla'>,
<class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class
'NVDAObjects.IAccessible.IAccessible'>, <class
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class
'baseObject.ScriptableObject'>, <class
'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (285, 338, 310, 56)
value: None
appModule: <'firefox' (appName u'firefox', process ID 4548) at address 52bc0b0>
appModule.productName: u'Firefox'
appModule.productVersion: u'45.0.2'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 262652L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 2564
windowText: u'\u2265 Marktplaats - De plek om nieuwe en tweedehands
spullen te kopen en verkopen - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x7e115c4 at 55bb210>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=262652, objectID=-4,
childID=-495079584
IAccessible accName: None
IAccessible accRole: u'span'
IAccessible accState:  (0)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 262652
IAccessible2 uniqueID: -495079584
IAccessible2 role: IA2_ROLE_TEXT_FRAME
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_OPAQUE (5120)
IAccessible2 attributes:
u'margin-left:0px;text-align:center;text-indent:0px;formatting:block;margin-right:0px;tag:span;margin-top:0px;margin-bottom:0px;display:block;'

**Comment by jcsteh** [comment] 2016-04-28 09:22
The text frame isn't in itself a problem; it just means there's 
something with significant formatting inside the link. Assuming the 
author hasn't done something weird like float the content of the link 
outside of the link, that should work fine. Are you able to reproduce 
this on a public page you can disclose?

**Comment by zersiax** [comment] 2016-04-28 09:25
Not reliably. This sample came from the following website:
http://www.marktplaats.nl/

You will want to click the "Plaats Advertentie" link, for me this
would do nothing at all. Sometimes I can get around this by going into
focus mode and pressing Enter on it from there, this works if the
element in question is actually in the tab order. With clickable divs
this is obviously not the case.

**Comment by zersiax** [comment] 2016-05-16 14:22
Anything new known about this one? It's becoming a real nuisance.
Sometimes going to Focus mode fixes it but especially in browse mode
the problem is really bad for me

**Comment by bhavyashah** [comment] 2017-07-29 13:36
@zersiax  Given that this ticket is several Firefox versions old and Windows 10 has also evolved significantly, could you please retest and let us know whether this issue still exists with more recent software?

**Comment by zersiax** [comment] 2017-08-23 12:26
This happens sometimes still, but quite rarely. And when it happens it usually has to do with scrolling content being manipulated with JS, or with divs that have been marked up to be clickable. I am assuming that is likely caused by these elements being off-screen / unreachable due to some other mechanic. I'd say we can close this one for now.

**Comment by leonardder** [comment] 2017-08-23 12:35
@zersiax: Since you are the initial author, let's close this on your request. You can always request a reopen if you so desire.

**Closed by leonardder** 2017-08-23 12:35 UTC
Labels: p3
