### ISSUE TITLE
speech cuts off at random

### ISSUE THREAD

**Issue by mdyer1** [nvaccess/nvda#14700] opened 2023-03-06 22:45 UTC
### Steps to reproduce:

Insure that NVDA 2022.4  or 2023.1 RC is running.
Try navigating around and perform tasks such as brows the web, check email etc. 
 ### Actual behavior:

NVDA at random will stop speaking until another action such as ault+tab from 1 window then back. 

NVDA at random will stop speaking until another action such as ault+tab from 1 window then back is pressed.  
### Expected behavior:

NVDA should not cut off while speaking such as while reading a message, briwsing a web page or typing in a document.

### NVDA logs, crash dumps and other attachments:
DEBUG - __main__ (17:02:56.791) - MainThread (9156):
Provided arguments: ['--debug-logging']
INFO - __main__ (17:02:56.792) - MainThread (9156):
Starting NVDA version 2023.1rc1
DEBUG - __main__ (17:02:56.792) - MainThread (9156):
Debug level logging enabled
DEBUG - core.main (17:02:56.895) - MainThread (9156):
Core starting
DEBUG - config.getInstalledUserConfigPath (17:02:56.895) - MainThread (9156):
Installed user config is not in local app data
INFO - core.main (17:02:56.899) - MainThread (9156):
Config dir: C:\Users\User\AppData\Roaming\nvda
DEBUG - core.main (17:02:56.900) - MainThread (9156):
loading config
INFO - config.ConfigManager._loadConfig (17:02:56.907) - MainThread (9156):
Loading config: C:\Users\User\AppData\Roaming\nvda\nvda.ini
DEBUG - config.profileUpgrader.upgrade (17:02:56.913) - MainThread (9156):
Current config schema version: 10, latest: 10
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.917) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.917) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.918) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.919) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.920) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: ParagraphNavigationFlag, behaviorOfDefault: APPLICATION
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.920) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: ParagraphNavigationFlag, behaviorOfDefault: APPLICATION
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.921) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:56.921) - MainThread (9156):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
DEBUG - fileUtils.FaultTolerantFile (17:02:56.923) - MainThread (9156):
C:\Users\User\AppData\Roaming\nvda\nvda.iniguwmer61.tmp
INFO - config.ConfigManager._loadConfig (17:02:56.928) - MainThread (9156):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{'schemaVersion': '10', 'general': {'language': 'Windows', 'saveConfigurationOnExit': 'True', 'askToExit': 'True', 'playStartAndExitSounds': 'True', 'loggingLevel': 'INFO', 'showWelcomeDialogAtStartup': 'False'}, 'upgrade': {}, 'update': {'autoCheck': 'True', 'startupNotification': 'True', 'allowUsageStats': 'True', 'askedAllowUsageStats': 'True'}, 'development': {'enableScratchpadDir': 'False'}, 'speech': {'synth': 'oneCore', 'outputDevice': 'Microsoft Sound Mapper', 'autoLanguageSwitching': 'False', 'autoDialectSwitching': 'True', 'oneCore': {'voice': 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM', 'volume': '100', 'rate': '100', 'rateBoost': 'False'}, 'espeak': {'voice': 'en-us', 'variant': 'max', 'rate': '60', 'pitch': '40', 'inflection': '100', 'volume': '100'}}, 'braille': {'noBraille': {}}, 'vision': {'NVDAHighlighter': {'highlightFocus': 'False', 'highlightNavigator': 'False', 'highlightBrowseMode': 'False'}, 'screenCurtain': {}}, 'mouse': {'reportMouseShapeChanges': 'True', 'enableMouseTracking': 'True'}, 'presentation': {'progressBarUpdates': {'reportBackgroundProgressBars': 'True', 'progressBarOutputMode': 'both'}}, 'virtualBuffers': {'autoSayAllOnPageLoad': 'False', 'useScreenLayout': 'True'}, 'documentFormatting': {'includeLayoutTables': 'False', 'reportArticles': 'True'}, 'uwpOcr': {'language': 'en-US'}, 'UIA': {'allowInMSWord': '3', 'eventRegistration': 'selective'}, 'keyboard': {'keyboardLayout': 'laptop', 'NVDAModifierKeys': '7'}}
DEBUG - core.main (17:02:56.994) - MainThread (9156):
setting language to Windows
DEBUGWARNING - languageHandler._createGettextTranslation (17:02:56.994) - MainThread (9156):
couldn't set the translation service locale to en_US
DEBUG - languageHandler.setLocale (17:02:56.994) - MainThread (9156):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (17:02:56.999) - MainThread (9156):
set python locale to English_United States.1252
INFO - core.main (17:02:57.000) - MainThread (9156):
Windows version: Windows 11 22H2 (10.0.22621) workstation AMD64
INFO - core.main (17:02:57.000) - MainThread (9156):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (17:02:57.000) - MainThread (9156):
Using comtypes version 1.1.11
INFO - core.main (17:02:57.000) - MainThread (9156):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (17:02:57.000) - MainThread (9156):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.007) - MainThread (9156):
Listing add-ons from C:\Users\User\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.008) - MainThread (9156):
Loading add-on from C:\Users\User\AppData\Roaming\nvda\addons\addonUpdater
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.010) - MainThread (9156):
Found add-on addonUpdater - 23.03.4. Requires API: (2022, 4, 0). Last-tested API: (2023, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.010) - MainThread (9156):
Disabling add-on addonUpdater
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.010) - MainThread (9156):
Loading add-on from C:\Users\User\AppData\Roaming\nvda\addons\Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.012) - MainThread (9156):
Found add-on Mozilla - 1.18. Requires API: (2018, 1, 0). Last-tested API: (2023, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.012) - MainThread (9156):
Disabling add-on Mozilla
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.013) - MainThread (9156):
Loading add-on from C:\Users\User\AppData\Roaming\nvda\addons\sayProductNameAndVersion
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.015) - MainThread (9156):
Found add-on sayProductNameAndVersion - 2022.04. Requires API: (2017, 3, 0). Last-tested API: (2022, 1, 0)
DEBUGWARNING - addonHandler._getAvailableAddonsFromPath (17:02:57.015) - MainThread (9156):
Add-on sayProductNameAndVersion is considered incompatible
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.015) - MainThread (9156):
Loading add-on from C:\Users\User\AppData\Roaming\nvda\addons\wintenApps
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.017) - MainThread (9156):
Found add-on wintenApps - 23.03. Requires API: (2022, 4, 0). Last-tested API: (2023, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (17:02:57.018) - MainThread (9156):
Disabling add-on wintenApps
DEBUG - core.main (17:02:57.699) - MainThread (9156):
Initializing appModule Handler
DEBUG - core.main (17:02:57.700) - MainThread (9156):
Initializing NVDAHelper
DEBUG - NVDAHelper._RemoteLoader.__init__ (17:02:57.716) - MainThread (9156):
Starting C:\Program Files (x86)\NVDA\lib64\2023.1rc1\nvdaHelperRemoteLoader.exe
DEBUG - core.main (17:02:57.723) - MainThread (9156):
initializing background i/o
DEBUG - core.main (17:02:57.724) - MainThread (9156):
Initializing tones
DEBUG - core.main (17:02:57.736) - MainThread (9156):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (17:02:57.737) - MainThread (9156):
Loading speech dictionary 'C:\Users\User\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (17:02:57.737) - MainThread (9156):
file 'C:\Users\User\AppData\Roaming\nvda\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (17:02:57.737) - MainThread (9156):
Loading speech dictionary 'C:\Program Files (x86)\NVDA\builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (17:02:57.759) - MainThread (9156):
3 loaded records.
DEBUG - core.main (17:02:57.760) - MainThread (9156):
Initializing speech
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (17:02:57.764) - MainThread (9156):
registering pre_configSave action: <class 'synthDrivers.oneCore.OneCoreSynthDriver'>
INFO - NVDAHelperLocal (17:02:57.765) - MainThread (9156):
Thread 9156, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_initialize, 215:
ocSpeech_initialize

INFO - NVDAHelperLocal (17:02:57.765) - MainThread (9156):
Thread 9156, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::activate, 89:
Activating

INFO - NVDAHelperLocal (17:02:57.894) - MainThread (9156):
Thread 9156, build\x86\localWin10\oneCoreSpeech.cpp, preventEndUtteranceSilence_, 443:
AppendedSilence supported

DEBUG - speechDictHandler.SpeechDict.load (17:02:57.905) - MainThread (9156):
Loading speech dictionary 'C:\Users\User\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft David.dic'...
DEBUG - speechDictHandler.SpeechDict.load (17:02:57.905) - MainThread (9156):
file 'C:\Users\User\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft David.dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (17:02:57.905) - MainThread (9156):
Loaded settings for SynthDriver oneCore
INFO - synthDriverHandler.setSynth (17:02:57.905) - MainThread (9156):
Loaded synthDriver oneCore
DEBUG - speech.sayAll.initialize (17:02:57.905) - MainThread (9156):
Initializing sayAllHandler
DEBUG - core.main (17:02:57.911) - MainThread (9156):
Initializing MathPlayer
WARNING - mathPres.initialize (17:02:57.918) - MainThread (9156):
MathPlayer 4 not available
INFO - core.main (17:02:57.918) - MainThread (9156):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
DEBUG - core.main (17:02:57.921) - MainThread (9156):
Initializing braille input
INFO - brailleInput.initialize (17:02:57.921) - MainThread (9156):
Braille input initialized
DEBUG - core.main (17:02:57.921) - MainThread (9156):
Initializing braille
INFO - braille.initialize (17:02:57.921) - MainThread (9156):
Using liblouis version 3.24.0
INFO - braille.initialize (17:02:57.921) - MainThread (9156):
Using pySerial version 3.5
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (17:02:57.924) - MainThread (9156):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (17:02:57.931) - MainThread (9156):
loading braille noBraille
INFO - braille.BrailleHandler.setDisplayByName (17:02:57.932) - MainThread (9156):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - core.main (17:02:57.933) - MainThread (9156):
Initializing vision
DEBUG - core.main (17:02:57.933) - MainThread (9156):
Initializing displayModel
DEBUG - core.main (17:02:57.933) - MainThread (9156):
Initializing GUI
DEBUG - windowUtils._rawWindowProc (17:02:57.972) - MainThread (9156):
CustomWindow rawWindowProc called for unknown window 198462
DEBUG - windowUtils._rawWindowProc (17:02:57.972) - MainThread (9156):
CustomWindow rawWindowProc called for unknown window 198462
DEBUG - windowUtils._rawWindowProc (17:02:57.972) - MainThread (9156):
CustomWindow rawWindowProc called for unknown window 198462
DEBUG - windowUtils._rawWindowProc (17:02:57.972) - MainThread (9156):
CustomWindow rawWindowProc called for unknown window 198462
DEBUG - languageHandler.setLocale (17:02:57.994) - MainThread (9156):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (17:02:57.994) - MainThread (9156):
set python locale to English_United States.1252
DEBUG - core.main (17:02:57.994) - MainThread (9156):
Initializing garbageHandler
DEBUG - core.main (17:02:58.004) - MainThread (9156):
initializing Java Access Bridge support
INFO - core.main (17:02:58.188) - MainThread (9156):
Java Access Bridge support initialized
DEBUG - core.main (17:02:58.192) - MainThread (9156):
Initializing legacy winConsole support
DEBUG - core.main (17:02:58.288) - MainThread (9156):
Initializing UIA support
INFO - UIAHandler.UIAHandler.MTAThreadFunc (17:02:58.304) - UIAHandler.UIAHandler.MTAThread (2216):
UIAutomation: IUIAutomation6
INFO - NVDAHelperLocal (17:02:58.487) - UIAHandler.UIAHandler.MTAThread (2216):
Thread 2216, build\x86\UIARemote\UIARemote.cpp, initialize, 145:
Registered C:\Program Files (x86)\NVDA\lib\2023.1rc1\Microsoft.UI.UIAutomation.dll.manifest

INFO - NVDAHelperLocal (17:02:58.512) - UIAHandler.UIAHandler.MTAThread (2216):
Thread 2216, build\x86\UIARemote\UIARemote.cpp, initialize, 150:
Microsoft.UI.UIAutomation is available

DEBUG - core.main (17:02:58.512) - MainThread (9156):
Initializing IAccessible support
DEBUG - core.main (17:02:58.513) - MainThread (9156):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (17:02:58.513) - MainThread (9156):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (17:02:58.514) - MainThread (9156):
No user gesture map
DEBUG - core.main (17:02:58.514) - MainThread (9156):
Initializing keyboard handler
DEBUG - core.main (17:02:58.514) - MainThread (9156):
initializing mouse handler
DEBUG - core.main (17:02:58.555) - MainThread (9156):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (17:02:58.556) - MainThread (9156):
No touch devices found
DEBUG - core.main (17:02:58.556) - MainThread (9156):
Initializing global plugin handler
DEBUG - core.main (17:02:58.557) - MainThread (9156):
Initializing core pump
DEBUG - core.main (17:02:58.558) - MainThread (9156):
Initializing watchdog
DEBUG - core.main (17:02:58.559) - MainThread (9156):
initializing updateCheck
INFO - core.main (17:02:58.564) - MainThread (9156):
NVDA initialized
DEBUG - core.main (17:02:58.564) - MainThread (9156):
entering wx application main loop
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (17:02:58.572) - MainThread (9156):
registering pre_configSave action: <class 'visionEnhancementProviders.NVDAHighlighter.NVDAHighlighterSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (17:02:58.578) - MainThread (9156):
loading vision NVDAHighlighter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (17:02:58.578) - MainThread (9156):
Loaded settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (17:02:58.588) - MainThread (9156):
registering pre_configSave action: <class 'visionEnhancementProviders.screenCurtain.ScreenCurtainSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (17:02:58.596) - MainThread (9156):
loading vision screenCurtain
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (17:02:58.596) - MainThread (9156):
Loaded settings for ScreenCurtainSettings
DEBUG - core._doPostNvdaStartupAction (17:02:58.608) - MainThread (9156):
Notify of postNvdaStartup action
IO - speech.speech.speak (17:02:58.638) - MainThread (9156):
Speaking ['Inbox - ilovecountrymusic483@gmail.com - Outlook', CancellableSpeech (still valid)]
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (17:02:58.639) - MainThread (9156):
No CLDR data for locale en_US
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (17:02:58.639) - MainThread (9156):
No symbol data for locale en_US
IO - speech.speech.speak (17:02:58.824) - MainThread (9156):
Speaking ['Table View', 'table', CancellableSpeech (still valid)]
DEBUGWARNING - RPC process 10516 (nvda_slave.exe) (17:02:58.983) - Dummy-1 (10096):
languageHandler._createGettextTranslation:
couldn't set the translation service locale to en_US
DEBUG - RPC process 10516 (nvda_slave.exe) (17:02:58.989) - Dummy-1 (10096):
languageHandler.setLocale:
Win32 locale string from locale code is English_United States.1252
DEBUG - RPC process 10516 (nvda_slave.exe) (17:02:59.000) - Dummy-1 (10096):
languageHandler._setPythonLocale:
set python locale to English_United States.1252
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (17:02:59.140) - watchdog (14900):
Potential freeze, waiting up to 10 seconds.
DEBUG - config.featureFlag._validateConfig_featureFlag (17:02:59.160) - UIAHandler.UIAHandler.MTAThread (2216):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
IO - speech.speech.speak (17:02:59.196) - MainThread (9156):
Speaking ['level 2', 'unread From Jennifer;  Gene Warner, Subject Re: [victor] Blue tooth on the Victor treck., Received Mon 3/6/2023 7:16 AM, Size 29 KB,', 'row 3', 'column 1', 'through 10', '2 of 646', CancellableSpeech (still valid)]
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (17:02:59.656) - watchdog (14900):
Recovered from potential freeze after 1.0151764 seconds.
IO - inputCore.InputManager.executeGesture (17:03:03.035) - winInputHook (13200):
Input: kb(laptop):delete
IO - speech.speech.speak (17:03:03.179) - MainThread (9156):
Speaking ['level 1', 'unread From Jennifer;  will walsh, Subject [victor] Blue tooth on the Victor treck., Received Mon 3/6/2023 7:14 AM, Size 21 KB,', 'row 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:09.928) - winInputHook (13200):
Input: kb(laptop):home
IO - inputCore.InputManager.executeGesture (17:03:11.413) - winInputHook (13200):
Input: kb(laptop):delete
IO - speech.speech.speak (17:03:11.583) - MainThread (9156):
Speaking ['unread From Leonard de Ruijter, Subject [nvaccess/nvda] Eurobraille bnote and bbook automatic detection (PR #14690), Received Mon 3/6/2023 7:17 AM, Size 8 KB,', 'level 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:24.211) - winInputHook (13200):
Input: kb(laptop):delete
IO - speech.speech.speak (17:03:24.368) - MainThread (9156):
Speaking ['unread From cketti, Subject [thundernest/k-9] K9 is failing to build over at F-droid  (Issue #6718), Received Mon 3/6/2023 7:19 AM, Size 7 KB,', 'level 1', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:03:29.209) - MainThread (9156):
Speaking ['Federated Timeline: 4 new items.']
IO - inputCore.InputManager.executeGesture (17:03:33.660) - winInputHook (13200):
Input: kb(laptop):delete
IO - speech.speech.speak (17:03:33.868) - MainThread (9156):
Speaking ['unread From Luna Jernberg, Subject 2023-03-06 @ 16:00 UTC - Fedora QA Meeting, Received Mon 3/6/2023 7:21 AM, Size 10 KB,', 'level 1', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (17:03:35.498) - MainThread (9156):
IUIAutomationElement.buildUpdatedCache failed given IDs of {30019, 30086, 30022, 30025, 30155, 30138, 30036, 30070, 30103, 30008, 30009, 30010, 30046, 30079}
DEBUGWARNING - eventHandler.executeEvent (17:03:35.499) - MainThread (9156):
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x014B7690> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 110, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1337, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1278, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1129, in reportFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1640, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 988, in _getUIACacheablePropertyValue
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (17:03:44.017) - winInputHook (13200):
Input: kb(laptop):NVDA+n
IO - speech.speech.speak (17:03:44.128) - MainThread (9156):
Speaking ['NVDA', 'menu', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:46.716) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:46.726) - MainThread (9156):
Speaking ['Exit', 'x', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:47.639) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:47.664) - MainThread (9156):
Speaking ['Preferences', 'subMenu', 'p', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:48.246) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:48.277) - MainThread (9156):
Speaking ['Exit', 'x', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:48.899) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:48.937) - MainThread (9156):
Speaking ['Donate', 'd', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:49.415) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:49.446) - MainThread (9156):
Speaking ['Save configuration', 's', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:49.866) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:49.897) - MainThread (9156):
Speaking ['Reset configuration to factory defaults', 'r', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:50.495) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:50.527) - MainThread (9156):
Speaking ['Save configuration', 's', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:50.720) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:50.757) - MainThread (9156):
Speaking ['Donate', 'd', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:50.900) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:50.927) - MainThread (9156):
Speaking ['Exit', 'x', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:51.080) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:51.118) - MainThread (9156):
Speaking ['Preferences', 'subMenu', 'p', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:51.283) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:51.317) - MainThread (9156):
Speaking ['Tools', 'subMenu', 't', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:51.575) - winInputHook (13200):
Input: kb(laptop):downArrow
IO - speech.speech.speak (17:03:51.598) - MainThread (9156):
Speaking ['Help', 'subMenu', 'h', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:52.229) - winInputHook (13200):
Input: kb(laptop):upArrow
IO - speech.speech.speak (17:03:52.247) - MainThread (9156):
Speaking ['Tools', 'subMenu', 't', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:52.656) - winInputHook (13200):
Input: kb(laptop):rightArrow
IO - speech.speech.speak (17:03:52.690) - MainThread (9156):
Speaking ['View log', 'v', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (17:03:53.825) - winInputHook (13200):
Input: kb(laptop):enter
DEBUG - gui.contextHelp.bindHelpEvent (17:03:53.834) - MainThread (9156):
Did context help binding for LogViewer

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2022.4 and 2023.1 RC.
#### Windows version:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:
Outlook 365, thunderbird 102.8 sttable and thunderbird bata 110.0b4.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Older versions of NVDA did not have this problem.
#### If NVDA add-ons are disabled, is your problem still occurring?
YesI thought I read of someone else having this problem, but not sure.
[nvda log.txt](https://github.com/nvaccess/nvda/files/10903657/nvda.log.txt)

**Comment by Adriani90** [comment] 2023-03-06 23:25
@mdyer1 did you run the com registration fixing tool in the NVDA menu under tools? Does the issue occur after that?
I cannot reproduce with NVDA last alpha version.


Next time, please fill out the issue template and upload the log file instead of posting the whole text out here. It is better for investigation.

Here is the relevant error:

error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x014B7690> with extra args of {}
Traceback (most recent call last):
File "eventHandler.pyc", line 300, in executeEvent
File "eventHandler.pyc", line 101, in init
File "eventHandler.pyc", line 110, in next
File "NVDAObjects\UIA_init.pyc", line 1337, in event_gainFocus
File "NVDAObjects_init.pyc", line 1278, in event_gainFocus
File "NVDAObjects_init.pyc", line 1129, in reportFocus
File "speech\speech.pyc", line 628, in speakObject
File "speech\speech.pyc", line 668, in getObjectSpeech
File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
File "baseObject.pyc", line 62, in get
File "baseObject.pyc", line 168, in getPropertyViaCache
File "NVDAObjects\UIA_init.pyc", line 1640, in get_states
File "NVDAObjects\UIA_init.pyc", line 988, in _getUIACacheablePropertyValue
File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in call
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

**Comment by seanbudd** [comment] 2023-03-07 01:10
This may be a duplicate of #14039

**Comment by mdyer1** [comment] 2023-03-07 01:10
Yes After posting the github issue, I ran it with the same resault.  I did manage to find the attacgh button.  Thanks for that info.  Perhaps with that error someone might be able to track it down.  

 

Matthew

**Comment by fisher729** [comment] 2023-03-11 19:33
Hi..Have you tried it with the new 2023.1rc1? I had this issue before I upgraded, but no longer do.

**Comment by Adriani90** [comment] 2023-12-20 23:53
We cannot reproduce this issue as it stands, and I think it is solved anyway after WASAPI has been introduced.
I am closing this issue but feel free to comment if you are still having it with NVDA 2024.1 Beta.

**Closed by Adriani90** 2023-12-20 23:53 UTC
Labels: close/worksforme
