### ISSUE TITLE
NVDA doesn't recognise list item in StartAllBack application

### ISSUE THREAD

**Issue by narayan-b-raikar** [nvaccess/nvda#13771] opened 2022-06-05 17:00 UTC
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? Yes.

>
NVDA doesn't recognise list item in Start all back application. Start all
> back is a popular application for windows 10-11. After updating the latest
> virsion, It doesn't speak the list item in the startmenu. I have collected
> the log. I am ataching the log info with this Issue text. hoping that Your team can solve this  problem in next updates. Thank you.
[Nvda Log about start all back application.txt](https://github.com/nvaccess/nvda/files/8840380/Nvda.Log.about.start.all.back.application.txt)

**Comment by cary-rowen** [comment] 2022-06-05 23:54
Please follow #13761 about this issue

**Comment by seanbudd** [comment] 2022-06-06 00:07
Closing as duplicate of #13659

**Closed by seanbudd** 2022-06-06 00:07 UTC

**Comment by narayan-b-raikar** [comment] 2022-06-06 12:38
Thank you for informing me. Sorry for Bad posting. I Haven't more knoledge regarding usage of github.

**Comment by narayan-b-raikar** [comment] 2022-06-21 12:57
Thank you for resolving the problem which has been previously mentianed regarding Start all Back. Really this is verry valuable effert of your team for us. Now another problem has occured in BarahaPad application, which is popular indian language editor. This is the only one application for Indian Blind users for editing Indian Languages.
The problem is: While navigating the next or previous paragraph using Ctrl+DownErro-Ctrl+UpErro, The paragraphs will be anounced verry lately. In previous version of NVDA We Had not seen such problem. Hope that your team definately solve this bug. I am attaching the extra Log info of this BarahaPad Application.

Best regards.
[NVDA LOG Info.txt](https://github.com/nvaccess/nvda/files/8949043/NVDA.LOG.Info.txt)

**Comment by lukaszgo1** [comment] 2022-06-21 13:11
@narayan-b-raikar  Please  do not hijack an unrelated issue, and open a second report for the problem you're experiencing.
