### ISSUE TITLE
NVDA is not reading the aria label on <Li> elements

### ISSUE THREAD

**Issue by WiproCRMAccessibility** [nvaccess/nvda#9390] opened 2019-03-21 09:21 UTC
Steps to reproduce:
1. Open the attached file in Chrome and turn on NVDA, and navigate to "Coffee" by tabbing.
Note : This aria label is been read by Narrator (on EDGE).

Actual behavior:
NVDA is not reading or announcing the aria label (i.e My coffee) , it just says bullet.

Expected behavior:
1. NVDA should read the aria label which is present on the <Li> element.

System configuration:
NVDA version:
2018.2.1
Windows version:
Version 1809 (OS Build 17763.379)
[ListItemAriaLabel-NVDA issue.zip](https://github.com/nvaccess/nvda/files/2991409/ListItemAriaLabel-NVDA.issue.zip)

**Comment by Adriani90** [comment] 2019-03-21 20:37
Could you please test with nvda 2019.1 rc1 and Chrome 73? Is the issue still occuring?

**Comment by ehollig** [comment] 2019-03-27 18:10
Is it invalid to provide an aria-label on a noninteractive element? If so, this was reverted in #8899

**Comment by Adriani90** [comment] 2020-04-19 15:00
This works as expected in NVDA Version: alpha-20015,56a62097, Google Chrome and Edge Chromium 81 as well as Firefox 75. NVDA reports the aria label in focus mode, or when pressing nvda+tab or nvda+shift+o in browse mode. NVDA did never report aria label in browse mode when pressing arrow keys, and this is expected behavior.
Closing as works for me.

**Closed by Adriani90** 2020-04-19 15:00 UTC
Labels: close/worksforme
