### ISSUE TITLE
nvda is not voiced switching of keyboard layout in microsoft edge.

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7636] opened 2017-10-01 06:23 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the resulthi. open the microsoft edge.

hi. open the microsoft edge.

hi. open the microsoft edge.

get in the address bar by using shortcut CTRL+O the sludge in the edit field on any website. for example www.google.com

try switching the language is alt+shift. expected nvda should speak the language that switched the layout.

in fact. nvda is silent and sometimes freezes for a few seconds.windows10 1709 16299
nvda next-14463,7dca66c4 nvda installed.

**Comment by derekriemer** [comment] 2017-10-01 06:51
I suspect this might be due to injection being blocked in edge, although I don't have two languages here to test with, becaust I don't need them.

**Comment by josephsl** [comment] 2017-10-01 06:54
Hi,

I can confirm this, and I think @DerekRiemer might have the right idea. CC @michaelDCurran

**Comment by gdata1** [comment] 2017-10-01 07:10
if so I think you need to solve it with microsoft. the last time edge was convenient and accessible with nvda.

**Comment by josephsl** [comment] 2017-10-01 07:11
Hi, this problem may involve a fix from MS, a fix from NVDA, both, or none. After working with Windows 10 for the past three years, I came to conclusion that certain problems require collaborative solutions, including Edge issues. Thanks.

**Comment by Adriani90** [comment] 2019-12-15 19:41
I cannot reproduce this problem in NVDA 2019.3 Beta 1 and Windows 10 1909 Update.
I tested as follows:
1. Open edge
2. Press ctrl+o
3. Type www.google.com
4. Press alt + shift
Actual behavior:
NVDA reports the keyboard language
Expected behavior:
See above.

Condition: it works if you press alt, hold it down, and press shift multiple times to switch between languages. If you wait for half a second between shift presses, you will hear the language. After you have the language needed, release finally the alt key. NVDA will report the focus of the address bar.
This seems to work correctly.

@josephsl, @gdata1 can you confirm?

**Comment by k-kolev1985** [comment] 2019-12-15 20:32
@Adriani90 I can confirm that it works as you've described it. But the announcement of the input language switch in this case I think is just by accident. When the input language switching is done as you've described it (by pressing and holding ALT, pressing and releasing SHIFT while not releasing ALT until the switching is announced by NVDA), for some strange reason, the pop-up menu for input method switching (usually invoked with Windows+Space) appears. The focus lands in that pop-up menu and NVDA announces what is selected in it. The menu displays the available input methods/languages. Each time SHIFT is pressed while holding ALT, the input method switches and the selection in the pop-up menu changes, which makes NVDA read that selection.

**NOTE:** When not holding ALT after pressing and releasing SHIFT, the pop-up menu for the input method switching does not appear on the screen. And if I remember correctly previously it did not even if ALT was held. Maybe this is an intentional change in v1909 of Windows 10 (?).

**Comment by gdata1** [comment] 2019-12-15 20:55
@Adriani90 I can attest to that. and works in windows 10 2004 building 19041.

**Comment by Adriani90** [comment] 2019-12-15 21:44
Thank you very much for the swift replies.
It makes sense that NVDA reads the language only when the popup is appearing, this is probably also what sighted people get. I think also this came with 1909 update. But I am not sure though.
For now I will close this as works for me. Please comment on it if it occurs again and we can reopen it.
Thanks.

**Closed by Adriani90** 2019-12-15 21:44 UTC
Labels: Edge, worksforme
