### ISSUE TITLE
NVDA constantly saying "Editing" in Excel 2013 when you enter a value in the first cell

### ISSUE THREAD

**Issue by andersbp** [nvaccess/nvda#6910] opened 2017-02-23 15:30 UTC
Hi everyone

When I in Excel 2013 enter text, use just a random cell in random spreadsheets, NVDA constantly saying "edit item" - but only when I enter the first value.

Can the constantly "editing" is be removed, so NVDA only say the value that you enter in a first cell, or is this an error in NVDA?
If yes, I will be glad for a correction.

Thanks in advance.

Regards,
Anders

**Comment by ehollig** [comment] 2017-08-21 02:40
For someone who is doing a lot of editing in Excel, I can see how this would be a lot of information that is being spoken. I believe there is reasoning for why NVDA announces the information it does though. In a Microsoft Excel document, in cell A1, if I type something, NVDA says:
Edit Item
edit
an edit control
Maybe this could be shortened to just editing? CC @feerrenrut @michaelDCurran

**Comment by michaelDCurran** [comment] 2017-08-21 02:42
This is a Microsoft bug, which has been reported to them.   In short, the name is "edit item", the role is edit, and the description is "An edit control". Both name and description are not necessary here.

**Comment by Adriani90** [comment] 2019-02-04 14:45
@andersbp, @pranavlal could you please test if this issue is still reproducible in Excel 2013 with NVDA 2018.4.1 or with last alpha? Thanks.

**Comment by pranavlal** [comment] 2019-02-05 14:44
I am unable to duplicate this.

-----Original Message-----

**Comment by Adriani90** [comment] 2019-02-05 15:06
Thank you. Closing as works for me. @andersbp please comment on this issue if you don't agree and we can reopen it.

**Closed** 2019-02-05 15:06 UTC
Labels: Microsoft Office support, needsExternalFix, worksforme
