### ISSUE TITLE
Lots of errors are being logged, when focus some windows like explorer

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#15750] opened 2023-11-06 09:20 UTC
### Steps to reproduce:
It is a bit hard to reproduce, like openning some window, and after closing it and returning to explorer lots of errors are being logged and nvda freezes for a while
### Actual behavior:
NVDA is logging errors and freezes
### Expected behavior:
No freezes should appear
### NVDA logs, crash dumps and other attachments:
ERROR - comtypes._comobject.call_without_this (13:06:16.780) - Dummy-1 (23184):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 154, in call_without_this
  File "UIAHandler\__init__.pyc", line 714, in IUIAutomationEventHandler_HandleAutomationEvent
  File "comtypes\__init__.pyc", line 278, in __getattr__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3 and latest alpha
#### Windows version:
Windows 10 22h2 with latest updates
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not except described above
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment] 2023-11-06 15:18
This occurs for me as if its some kind of timing thing, where some other item is still focussed when it tries to do something else. Windows 10. Win 7 you get some errors but not a freeze, well not so far, of course I'm using the latest stable not the alpha.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: Beqa Gozalishvili 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Monday, November 06, 2023 9:20 AM
  Subject: [nvaccess/nvda] Lots of errors are being logged, when focus some windows like explorer (Issue #15750)



  Steps to reproduce:
  It is a bit hard to reproduce, like openning some window, and after closing it and returning to explorer lots of errors are being logged and nvda freezes for a while

  Actual behavior:
  NVDA is logging errors and freezes

  Expected behavior:
  No freezes should appear

  NVDA logs, crash dumps and other attachments:
  ERROR - comtypes.comobject.call_without_this (13:06:16.780) - Dummy-1 (23184):
  Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
  Traceback (most recent call last):
  File "comtypes_comobject.pyc", line 154, in call_without_this
  File "UIAHandler_init.pyc", line 714, in IUIAutomationEventHandler_HandleAutomationEvent
  File "comtypes_init_.pyc", line 278, in getattr
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in call
  _ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

  System configuration
  NVDA installed/portable/running from source:
  Installed

  NVDA version:
  2023.3 and latest alpha

  Windows version:
  Windows 10 22h2 with latest updates

  Name and version of other software in use when reproducing the issue:
  Other information about your system:
  Other questions
  Does the issue still occur after restarting your computer?
  Yes

  Have you tried any other versions of NVDA? If so, please report their behaviors.
  Not except described above

  If NVDA add-ons are disabled, is your problem still occurring?
  Yes

  Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
  Yes

**Comment by Adriani90** [comment] 2023-11-06 20:03
This seems specific to Windows 10, in Windows 11 23 H2 or 22 H2 I cannot reproduce the errors.

cc: @josephsl

**Comment by mzanm** [comment] 2023-11-06 20:46
I'm getting the exact same error when I close Edge. Windows 11 22 h 2. Very consistently for me.

**Comment by Adriani90** [comment] 2024-02-22 15:44
@beqabeqa473, @mzanm are you still seeing these errors in NVDA last alpha?

**Comment by beqabeqa473** [comment] 2024-02-22 17:35
I didn't see such problems after i migrated to windows 11.

On 2/22/24, Adriani90 ***@***.***> wrote:
> @beqabeqa473, @mzanm are you still seeing these errors in NVDA last alpha?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15750#issuecomment-1959723618
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment] 2024-02-26 18:18
I cannot reproduce this either on Windows 10 last update.
I am closing this for now as works for me. Please comment if you are still having this issue and we can reopen.

**Closed by Adriani90** 2024-02-26 18:18 UTC
Labels: close/worksforme, p4, triaged
