### ISSUE TITLE
Control Placement Of Spoken Element Types

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#17154] opened 2024-09-10 15:30 UTC
### Is your feature request related to a problem? Please describe.
It depends upon user preference at the end of the day, and yet when pressed for time, it is the current cause of many delays and long hours spent hearing information that isn't always needed to make the change you desire to. Conventionally, the problem is related at the client side level to optional user input and output limitations. If it is left unchecked, then over time, as control types become more descriptive, this could lead to a chain effect that would cause changes to be unnecessarily delayed in other ways that a user may not want. Obviously this behavior is unintentional, and so this is why altering transactional information by customizing the level of when it is spoken first will fix this concern for the foreseeable future. So if implemented, adding controlled placement of element types would significantly reduce navigational  issues which would otherwise be prone to a higher output of user errors. As such, this preference group would also add a more convenient way for people to execute changes made to programs by dealing with this blindness specific oversight in a more efficient manner where time constraints occur.
### Describe the solution you'd like
A category in NVDA settings that is labeled speech controls. Here, all of the available interactive states of conditional fields, dependency groups, selective positions, and other element controls would be spoken either before, after or customizable context is relayed to its corresponding text. The goal is to reduce the inability for long emphasis in dialog controls such as ones Microsoft is prone to using in Windows 11 Settings, that would allow users to know what action they can take before the announcement of what they're doing is spoken ideally.
### Describe alternatives you've considered
A way to define context before application control sets are read out. Or, some other way of speech gestures that can be controlled similar to input gestures, but instead would be more hard coded in case of API changes over time as output states evolve.
### Additional context
Currently there is no way for NVDA to announce the states of elements when interacting with control groups. This can be problematic, when navigating long item lists where you're having to selectively select or not select items in a list in file explorer. Or when reviewing settings when installing a program, some users may not hear the state of a checkbox until after a long item description particularly in windows installers is read out. It therefore makes sense to control whether item states like selected, not selected, checked, unchecked, and so on are spoken before or after control group and dialog text. Additionally, other information especially for different language contexts such as button, list, link, and other identifiers are spoken in relation to such dependent states. As well as contextual information for reading positions, like where one of three, or selected 5 of 16 is spoken. These speech controls would make a great addition to NVDA users which would more effectively help identify what a user is doing, particularly on laggy computers or when someone may be pressed for time when working with larger data sets.

**Comment by SaschaCowley** [comment] 2024-09-11 00:28
Duplicate of #7232

**Closed by SaschaCowley** 2024-09-11 00:28 UTC
