### ISSUE TITLE
Section in role=document div

### ISSUE THREAD

**Issue by afiorenza** [nvaccess/nvda#6664] opened 2016-12-21 13:44 UTC
Hi, i found some weird behavior when i have a `section` tag inside a div with `role=document`

Here is the markup: 
```
<div role="dialog" tabindex="0" class="container">
  <div role="document">
    <h1 id="title">Dialog title</h1>
    <section aria-labelledby="title">
      <input type="text">
      <input type="text">
      <input type="text">
      <button>cancel</button>
      <button>ok</button>
    </section>
  </div>
</div>
```

The issue is that only the first time i tab from the last input to cancel button, instead of read:
```
edit  has auto complete
blank
cancel
button
```

it reads:
```
edit  has auto complete
blank
Dialog title region 
cancel
button
```

I can't understand why it reads `Dialog title region` in the middle of the input and the button.

Here is a fiddle recreating it: [https://jsfiddle.net/nvfxo7ud/1/](https://jsfiddle.net/nvfxo7ud/1/)

Thanks, regards.

**Comment by henkabma** [comment] 2016-12-22 00:20
Hi,


I don't know if this is related or completely separate.


this site: https://kunstencadeau.org/ makes heavy use of sections. When 
navigating using next/previous heading, NVDA has a habit of reading 
information from the previous section. Other screen readers have no 
issue with it and the site just received a 3-star rating for accessibility.


HTML code looks like this:

                         <section class="col-sm-4 product">
                 <a 
href="https://kunstencadeau.org/product/70-Steigerhouten%20Groeimeter">
                     <div class="block-background">
                         <div class="text-holder">
                             <h3>Steigerhouten Groeimeter</h3>
                             <p></p><p>De groeimeter is verkrijgbaar met 
de tekstkleuren: wit, zwart,blauw,roze,grijs,groen.</p><p></p>
                         </div>
                                                 <img 
src="./CliÃ«ntenwebwinkel _ Koninklijke Visio_files/79.JPG" alt="" 
width="320">
                         <div class="button-holder">
                             <span class="price-stroke">â‚¬ 15.00</span>
                             <button class="btn btn-navigate 
btn-product-list" tabindex="-1" type="button">
                                 Details bekijken<i 
class="icon-middlearrowright" aria-hidden="true"></i></button>
                         </div>
                     </div>
                 </a>
             </section>
                         <section class="col-sm-4 product">
                 <a 
href="https://kunstencadeau.org/product/12-Steigerhouten%20dienblad">
                     <div class="block-background">
                         <div class="text-holder">
                             <h3>Steigerhouten dienblad</h3>
                             <p></p><p>Dienblad met opdruk 'smakelijk' 
(behandeld)</p>
<p>Afmetingen: 50 cm (lengte) x 19,5 (breedte)
                         </p></div>
                                                 <img 
src="./CliÃ«ntenwebwinkel _ Koninklijke Visio_files/12.jpeg" alt="" 
width="320">
                         <div class="button-holder">
                             <span class="price-stroke">â‚¬ 9.50</span>
                             <button class="btn btn-navigate 
btn-product-list" tabindex="-1" type="button">
                                 Details bekijken<i 
class="icon-middlearrowright" aria-hidden="true"></i></button>
                         </div>
                     </div>
                 </a>
             </section>




When I move to the "steigerhouten dienblad" using H or shift+H, NVDA 
tells the heading level, followed by "steigerhouten dienblad", followed 
by info about the "groeimeter".

With kind regards,

Henk.

Op 21-12-2016 om 14:44 schreef Agustin Fiorenza:

**Comment by jcsteh** [comment] 2016-12-22 00:21
Hmm. This is interesting.

The labelled section maps to an ARIA region. In browse mode, we report ARIA regions. You'll see this if you switch to browse mode and cursor down from the heading.

The reason this happens when tabbing to the button is that tabbing to a button switches to browse mode. However, because we were in focus mode before that point, browse mode never reported the region and so it gets reported then.

I'm not entirely sure how we'd fix this. One idea is to keep the browse mode speech cache updated even when we're in focus mode, but that seems like a pretty expensive thing to do.

**Comment by jcsteh** [comment] 2016-12-22 00:22
P3 because it's annoying but not severe and probably costly to fix.

**Comment by jcsteh** [comment] 2016-12-22 00:38
@henkabma, I can't reproduce your issue, but in any case, I'm pretty sure it is unrelated. Please file a separate issue for that and include browsers tested, etc. Thanks.

**Comment by afiorenza** [comment] 2016-12-22 12:35
@jcsteh But it is a NVDA defect? or is there anything we could do in my side? Thanks

**Comment by jcsteh** [comment] 2016-12-23 00:39
Yes, it's an NVDA defect. Sorry for any lack of clarity.

**Comment by Adriani90** [comment] 2019-03-25 21:58
@afiorenza are you still able to reproduce this issue with NVDA 2019.1 RC1?
I cannot reproduce it.

Thanks!

**Comment by Adriani90** [comment] 2020-04-25 15:21
This works as expected in Firefox 75 with NVDA Version: alpha-20045,a335297e. Closing as works for me.

**Closed by Adriani90** 2020-04-25 15:21 UTC
Labels: close/worksforme, p3
