### ISSUE TITLE
Excel 2016: Autocomplete suggestions of formular is not spoken

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#7103] opened 2017-04-25 21:19 UTC
Using Excel 2016, NVDA Next 13998 ( from April 25).
When in a cell after having typed "=", start typing a formular e.g "=ab". Autocomplete suggestions start to appear but are not spoken by NVDA.

The checkbox in Excel's settings under the second tab "formular" is checked in autocomplete formular (excuse my bad translation from Danish). I am using the Danish Excel 2016.

As far as I can tell, the field is interpreted as not having autocomplete. I pasted the result of NVDA+f1 below.
  

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (23:18:15):
Developer info for navigator object:
name: u'Rediger element'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x050228B0>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'et redigeringselement'
location: (447, 646, 135, 37)
value: None
appModule: <'appModuleHandler' (appName u'excel', process ID 3580) at address 5022710>
appModule.productName: u'Microsoft Office 2016'
appModule.productVersion: u'16.0.7870.2031'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 197704
windowClassName: u'EXCEL6'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 6436
windowText: u''
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x6974440 at 52b3bc0>
UIA automationID: 
UIA frameworkID: Win32
UIA runtimeID: (42, 197704)
UIA providerDescription: [pid:3972,providerId:0x30448 Main:Nested [pid:3580,providerId:0x30448 Main(parent link):Unidentified Provider (unmanaged:EXCEL.EXE)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: EXCEL6

**Comment by DGartmann** [comment] 2017-05-15 15:35
This issue is still present in Next 14047 I received today.

**Comment by josephsl** [comment] 2017-05-15 17:41
Hi, foundations laid via pull request for #6241. Although the referenced issue talks about UIA, it is applicable to other situations such as the one described on this issue. Thanks.

**Comment by ehollig** [comment] 2017-08-21 01:16
Duplicate of #6786

**Closed by ehollig** 2017-08-21 01:16 UTC
