### ISSUE TITLE
Java Access Bridge not working with 2019.3 and Windows 7

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#10842] opened 2020-03-04 15:59 UTC
Issue of a Spanish-speaking user.

### Steps to reproduce:

Open Control Panel and press J to locate "Java, link, Java Control Panel". Activate it.

### Actual behavior:

The focus gets lost and the object navigator is on the link. Java Control Panel is focusable but the user is unable to read anything.
[nvda.log](https://github.com/nvaccess/nvda/files/4288223/nvda.log)
this has been reported to happen on two different machines, and after reinstalling both NVDA and JRE.
I and another Spanish-speaking users have been unable to reproduce this with Windows 10, although it may be a version specific issue.

### Expected behavior:

NVDA reads all the content of the window, since Java Access Bridge is now bundled with the application and it enables JAB in the VM on startup.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

Windows 7 (6.1.7601 service pack 1) 32 bits

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, JAB works as expected with NVDA 2019.2.1 in the same machine.

**Comment by lukaszgo1** [comment] 2020-03-04 17:04
I cannot reproduce this on Windows 7 x64. What version and what architecture of Java is installed exactly?

**Comment by ivnc** [comment] 2020-03-04 19:30
The user has reproduced the issue with JRE 6, 7 and 8 on 32 bit, thus 
JRE architecture is the same. In case of Java 6, he has manually 
activated JAB

(copying the corresponding file).


Regards.

**Comment by Adriani90** [comment] 2020-03-08 22:02
cc: @michaelDCurran

**Comment by ivnc** [comment] 2021-04-02 18:51
Hello.

A user has reported that this issue is also reproducible with Windows 10 32 bits. Since the original reporter also has a 32-bit system, in their case Windows 7 with SP1, this is probably a problem related only to 32-bit machines.
This second report was solved by downloading JDK from AdoptOpenJDK and manually copying the file windowsaccessbridge-32.dll into system32 folder.

Regards.

**Comment by ivnc** [comment] 2023-05-08 08:42
Hi, according to further comments submitted to us by the reporter, the problem is that NVDA doesn't locate the file C:\Windows\system32\WindowsAccessBridge.dll and looks for C:\Windows\syswow64\WindowsAccessBridge-32.dll instead, even on a 32-bits machine.

**Comment by seanbudd** [comment] 2024-02-22 22:49
Can this be reproduced on Windows 8.1, Windows 10 or Windows 11 on 32bit machines? Windows 7 is no longer supported. I am closing this for now, but can re-open if this is reproducible on 8.1/10/11

**Comment by ivnc** [comment] 2024-02-22 23:00
As I commented, in 2021 we had an user with a similar issue on Windows 10 32-bit, specifically Win 10 version 1909. Would you like me to ask him for more information? My original comment was:
> Hello.
> 
> A user has reported that this issue is also reproducible with Windows 10 32 bits. Since the original reporter also has a 32-bit system, in their case Windows 7 with SP1, this is probably a problem related only to 32-bit machines. This second report was solved by downloading JDK from AdoptOpenJDK and manually copying the file windowsaccessbridge-32.dll into system32 folder.
> 
> Regards.

**Comment by seanbudd** [comment] 2024-02-22 23:03
Thanks -  I missed that sentence

**Comment by mwhapples** [comment] 2024-02-23 09:09
@seanbudd if a windows version no longer being supported is valid as a reason to close, can I ask what the policy would be regarding Java versions? My thought here being that as Java17 seems to be the last LTS Java release supporting 32-bit then once Java17 is no longer supported then as far as NVDA goes would this then be an issue. Unlike Windows though, (java may be more tricky to determine when it is "supported", mainly because you have builds and support from various organisations and some of those offer both free and paid for support which may also have different end dates. My concern is that this could remain as a lingering issue for ever more, or at least until there is no longer a 32-bit Windows which is supported. To see what I mean about the variety of Java support dates, see this wikipedia article https://en.wikipedia.org/wiki/Java_version_history

**Comment by seanbudd** [comment] 2024-03-12 23:52
@mwhapples we will be forced to move to 64bit in the next few years.
I think any issues with extremely ancient versions of Java we can close. I'd suggest a conservative cut off around Java SE 10/11

**Comment by seanbudd** [comment] 2024-03-12 23:52
@mwhapples we will be forced to move to 64bit in the next few years.
I think any issues with extremely ancient versions of Java we can close. I'd suggest a conservative cut off around Java SE 10/11

**Comment by FelipeZanabria** [comment] 2024-05-12 00:38
I am not a programmer, but looking at the JABHandler code before 2019.3, I realized that the legacy mode is missing to define the JOBJECT64 class.
We also need to locate the windowsAccessBridge.dll dll, and load it in the same way as the one that is already in NVDA, depending on the architecture (x86 or x64).
If the operating system is 32-bit, define:
class JOBJECT64(c_int):
Otherwise use c_int64 instead.
I have downloaded the latest JABHandler.py from the source code, modified it to work, and also downloaded windowsAccessbridge.dll from the open jdk jre, and it worked on my system.

**Comment by Adriani90** [comment] 2024-11-16 11:07
End of support for Windows 10 will end in Oktober 2025, and Windows 10 is the last Windows to support only 32bit (x86) operations as per my understanding.
On another note, Open JDK  11 is end of life as of Oktober 31, 2024 but has paid support until 2027. and Open JDK 8 is on LTS until 2026.
https://access.redhat.com/articles/1299013

Oracle Java SE on the other hand look a bit different, Java SE 8 and 11 are on LTS until 2030 and 2032 respectively.

Nonetheless, the recommendation is to update to JDK or Java SE 2021 or newer when building applications.

My conclusion is that we should still try to solve this issue because it might be still relevant, especially for people in developing countries who still rely on older systems.

**Comment by gerald-hartig** [comment] 2024-11-17 22:03
We're starting the groundwork for our own migration of NVDA to 64 bit. As a result, bugs affecting 32 bit only environments will not be prioritised unless they have a large impact on a significant number of users. The last 32-bit only CPU was released in 2006. We can reopen this if there is demand from the community.

**Closed by gerald-hartig** 2024-11-17 22:03 UTC
Labels: bug, bug/regression, p3
