### ISSUE TITLE
NVDA  replacement dictionary problem

### ISSUE THREAD

**Issue by laosamayor2010** [nvaccess/nvda#14384] opened 2022-11-19 00:25 UTC
### [Apologies.]
Apologies I'm not a programmer I read the template, but I didn't understand how to do the markdown format

### [INTRODUCTION.]
   When NVDA reads text, it sometimes talks a lot and describes everything in detail, which can be very annoying. So I copy the phrase, use the default dictionary, and replace it with a single word.

### [EXAMPLE OF AN ENTRY IN MY DICTIONARY.]
    Pattern: "Cuadro de búsqueda  edición  en blanco"
    Replace: "Blanco"

### [BEGINNING OF PROBLEM.]
After a few months when I started using this application, I had hundreds of dictionary entries, and the navigation was nice, because NVDA only spoke few words that I had entered. After updating the app to new versions, he started speaking long sentences again, and became annoying again. What happened is that those phrases that I entered in the dictionary were no longer replaced by the words that I entered.

#### Clarification.
To make sure the sentences are correct, I open the speech viewer (NVDA+F4), copy, and paste into the default dictionary. So there is no typing error.

### [SPEECH VIEWER.]
With the speech viewer open, when you tap the Windows logo key, NVDA says:
   "Cuadro de búsqueda, two spaces, edición, two spaces, en blanco"
The line is apparently divided into 3 sections.
   Section 1: Cuadro de búsqueda
   Section 2: edición
   Section 3: en blanco

"Cuadro de búsqueda--edición--en blanco"
              

### [MINE GUESS.]
What I write below is my assumption. I raise it in order to explain what I think would be happening.

I suppose that the 2 spaces in a row, means that it is a jump from one section to another of the same object. All 3 sections are on the same line, probably because they belong to the same object. I'm assuming that each time it's passed to a different object, it's written to a new line.

In previous versions, NVDA considered the whole line, as a single thing, and looked for a match in the dictionary, if it found it, it did the replacement, spoke, and then moved on to the next object that was on another line.
Now, that long sentence made up of 3 sections, it analyzes it, section by section, and looks for a match in the dictionary, and if there is not a match, it speaks the text as it is, then it goes to the next section of the same line and returns to find a match in the dictionary, and so on.

   Before it analyzed the complete set that included all the sections of the same line, and searched for a match, now it analyzes section by section, therefore, the dictionary entry: "Cuadro de búsqueda--edición--en blanco" is no longer useful, because it is It deals with a sentence, which is on the same line, and is the set formed by 3 sections.

   
### [EXAMPLES: Some dictionary entries stopped working.]

"Panel de control--agrupación--expandido"
"Apagar--botón divisor--subMenú"
 "separador--no disponible"
"edición--multilínea--en blanco"
"Sintetizador--cuadro combinado"
"Instalando controlador de dispositivo--globo de ayuda"

 -- Double minus: Shows the double space, which is the separator between the sections

#### Clarification.
All phrases entered in my dictionary, which have two spaces, meaning the object has multiple sections, are no longer replaced.

### [EXAMPLES: Some dictionary entries, which still work.]

"Menú Inicio"
"Buscar archivos y carpetas"
"Encabezado de redes"
"Microsoft Word"
"bloc de notas"
"tiene auto completado"

#### Clarification.
All my dictionary entries, where the phrases have only one section, still work.

### [OVER 100 INPUTS STOPPED WORKING.]
    These phrases are just an example, I have over 100 dictionary entries of similar long phrases that were previously replaced by a single word, and they stopped working. It is a leap backwards, because I lost the comfort of keeping quiet about so much verbiage.

### [SOLUTION.]

   I would like long phrases entered in the dictionary to be replaced again. Sentences that are made up of several sections work again, to silence so many words
I ask developers to fix this in future releases.

### [ADDITIONAL INFORMATION.]
NVDA(Installed) Version: 2022.2.2
NVDA No plugins installed

Windows 10 Home (Español)- 10.0.19043 Build 19043
 x64
HP ENVY Laptop 17-ae1xx
SKU 1KT19UA#ABA
Core i7-8550U CPU @ 1.80GHz, 1992 Mhz, 4 Main Processors, 8 Logical Processors
RAM 16GB

### [GREETINGS AND THANKS.]
Thanks to the programmers and everyone who is involved in the development of NVDA. My name is Alan, I have retinitis pigmentosa, this screen reader is essential to use the computer. Thanks for your help.

**Comment by michaelDCurran** [comment] 2022-11-22 02:01
What was the last version of NVDA where this definitely worked?
Are you able to provide an NVDA log set to debug  for both a version of NVDA where it worked, and a version where it does not?
A part from setting your log level to debug in NVDA's general settings, please also turn on both the Speech and Speech manager options in the debug logging list in NVDA's Advanced settings.

**Comment by laosamayor2010** [comment] 2022-11-23 15:54
### Clarification 
The double minus sign represents the double space. When there is a double space, the replace fails.

### NVDA 2019.2
I ran NVDA 2019.2 portable

I pressed the Windows key and it spoke:
Inicio--ventana
Buscar--ventana
Cuadro de búsqueda--edición
en blanco

I added to the default dictionary
Pattern:Cuadro de búsqueda--edición
Replace:

I pressed the Windows key again and this time it didn't say:Cuadro de búsqueda--edición
Well!

### NVDA 2020.4
I ran NVDA 2020.4 portable

I pressed the Windows key and it said:
Inicio--ventana
Buscar--ventana
Cuadro de búsqueda--edición
en blanco

I added to the default dictionary
Pattern:Cuadro de búsqueda--edición
Replace:

I pressed windows key again and it said:Cuadro de búsqueda--edición
The replacement did not take effect.
Bad

### Other NVDA versions:
  NVDA 2017 (Work ok)
  NVDA 2019.2 (Work ok)
  NVDA 2020.4 (Not)
  NVDA 2022.2.2 (Not)
  NVDA 2022.3.1 (Not)

### Two Log files



[nvda 2020.4 Reg..txt](https://github.com/nvaccess/nvda/files/10076795/nvda.2020.4.Reg.txt)
[nvda 2019.2 Reg. Well!.txt](https://github.com/nvaccess/nvda/files/10076796/nvda.2019.2.Reg.Well.txt)

**Comment by CyrilleB79** [comment] 2022-11-23 17:20
The new behaviour came with NVDA 2019.3 speech refactor.

The problem is that you want to handle with the dictionary two things that are now spoken separately because they have nothing to do with each other. E.g in "start  window", you have the type of graphical object (window) and the name of this object (start).

I think that the dictionary is not intended to mute over-verbose reporting of NVDA. Its primary aim is to fix TTS pronunciation of words.

Trying to mute more complex expressions worked just by chance in NVDA 2019.2.1 and before.

You'd better to open an issue describing the problem of having too much verbosity. Actually, maybe there is already such issue.

**Comment by XLTechie** [comment] 2023-01-16 09:06
Duplicate of #11289

**Closed** 2023-01-16 09:28 UTC
Labels: p3, blocked/needs-info
