### ISSUE TITLE
Outlook 2016 Calendar date picker does not read out the dates

### ISSUE THREAD

**Issue by wallaceid** [nvaccess/nvda#6375] opened 2016-09-13 22:51 UTC
The calendar invite date picker does not read out dates. To get there, start a new meeting in Outlook 2016 Calendar and tab to after the date, then press Space to activate. This issue only applies to Office 365.

**Comment by AlexandreMooc** [comment] 2016-10-06 17:29
Can confirm in Outlook 2016 and NVDA 2016.2.1. Dates and the "Today" button are not being read.

**Comment by sucharugupta** [comment] 2016-10-14 11:28
I also experience the same with NVDA. While with JAWS, can navigate to dates but only sequentially and there no mechanism to navigate to different month or year.

**Comment by Adriani90** [comment] 2019-03-08 23:37
@wallaceid, @AlexandreMooc, @sucharugupta are you still having this issue? I cannot reproduce it with NVDA 2019.1 Beta 1 and Outlook 2016 / 365.

**Comment by Adriani90** [comment] 2019-03-11 19:58
It seems the author is not responding. I cannot reproduce this issue. I close it as works for me. Please comment on it if you still have the issue and we can reopen it. Thanks!

**Closed by Adriani90** 2019-03-11 19:58 UTC
Labels: Microsoft Office support, worksforme
