### ISSUE TITLE
List count in the action center is not valid when quick actions are collapsed

### ISSUE THREAD

**Issue by parhamdoustdar** [nvaccess/nvda#6263] opened 2016-08-13 14:31 UTC
Windows version 1607, NVDA version master-13505,f5ade272

Steps to reproduce:

Go to the action center and, if the button reads, "Collapse quick actions", press space on it once to collapse quick actions.  Then, press tab.

Expected results: there are only 4 items , so NVDA should say "1 of 4".

Actual result: NVDA reports the total number of items to be 10, which is valid only when the quick actions is expanded.

**Comment by leonardder** [comment] 2018-02-10 14:14
@parhamdoustdar: Is this still the case? Could you please make sure that you have "Guess object position information when unavailable" disabled in the object presentation settings?

This is most likely a needs external fix.

**Comment by Adriani90** [comment] 2019-03-08 18:10
I can still reproduce this issue in Windows 10 1809 update with NVDA 2019.1 Beta 1. cc: @josephsl

**Comment by Adriani90** [comment] 2020-05-03 10:25
This works correctly in Windows 10 1909 Update with NVDA alpha 20097,6a573cd9. Closing as works for me.

**Closed by Adriani90** 2020-05-03 10:25 UTC
Labels: close/worksforme
