### ISSUE TITLE
Nvda is not reading auto filter options in excel 2013

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7421] opened 2017-07-19 20:44 UTC
When opening a spreadsheet in excel 2013 and pressing alt+downArrow
, and soon after walking with arrows below nvda is not reading the auto filter options displayed by excel.
For the tests:
Create a spreadsheet in excel I believe that with at least two lines.
In the first line press alt+downArrow.
Excel displays the list with auto filter options.
By pressing down arrow the nvda informs only list.
The expected one is that the nvda read the auto filter options.
Nvda master 14195
Windows 7 64bits.
Excel 2013 32 bits.
I ran tests with the plugins disabled and the result was the same.
Follow the log:

IO - inputCore.InputManager.executeGesture (17:40:43.710):
Input: kb(laptop):downArrow
IO - tones.beep (17:40:43.740):
Beep at pitch 418.733333333, for 40 ms, left volume 40, right volume 44
DEBUG - external:globalPlugins.focusHighlight.GlobalPlugin.event_gainFocus (17:40:43.779):
(app excel) (wc EXCEL7) (rect pos 233 425 size 1198 409) (dpi ac 0 win 96 sys 96 scale 1.00) (mon pos 0 0 size 1600 900) (posInMon 233 425) (primary 1) (dpiMon 96 96) (cMon 1) (role célula state  roletext célula) (name Adriano)
IO - speech.speak (17:40:43.839):
Speaking [u'Adriano  B2']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 389 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 390 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 391 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 392 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 393 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (17:40:43.849):
oleacc.AccessibleObjectFromEvent with window 2820106, objectID 394 and childID 0: [Error -2147467259] Erro não especificado
IO - inputCore.InputManager.executeGesture (17:40:44.789):
Input: kb(laptop):alt+downArrow
IO - tones.beep (17:40:44.829):
Beep at pitch 510.4, for 40 ms, left volume 69, right volume 15
DEBUG - external:globalPlugins.focusHighlight.GlobalPlugin.event_gainFocus (17:40:44.839):
(app excel) (wc EXCEL:) (rect pos 215 484 size 172 41) (dpi ac 0 win 96 sys 96 scale 1.00) (mon pos 0 0 size 1600 900) (posInMon 215 484) (primary 1) (dpiMon 96 96) (cMon 1) (role lista state  roletext aplicativo)
IO - speech.speak (17:40:44.859):
Speaking [u'lista']
IO - inputCore.InputManager.executeGesture (17:40:45.890):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (17:40:47.900):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (17:40:48.019):
Developer info for navigator object:
name: u''
role: ROLE_LIST
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.window.excel.ExcelDropdown object at 0x0B0C9B90>
Python class mro: (<class 'NVDAObjects.window.excel.ExcelDropdown'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (215, 484, 172, 41)
value: ''
appModule: <'excel' (appName u'excel', process ID 1388) at address afd6550>
appModule.productName: u'Microsoft Office 2013'
appModule.productVersion: u'15.0.4945.1000'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 3867582
windowClassName: u'EXCEL:'
windowControlID: 0
windowStyle: -1778384896
windowThreadID: 4988
windowText: u''
displayText: u''

**Comment by jcsteh** [comment] 2017-07-19 21:56
Duplicate of #6459.

**Closed by jcsteh** 2017-07-19 21:56 UTC
