### ISSUE TITLE
Add-on store: Display the readme document of the add-on

### ISSUE THREAD

**Issue by hwf1324** [nvaccess/nvda#15579] opened 2023-10-04 09:11 UTC
The add-on details currently displayed by the add-on store are sometimes sorely lacking for a quick look at what an add-on does to determine if it's needed.

### Is your feature request related to a problem? Please describe.

When I want to find out what add-ons are suitable for me in the add-on store, can I only rely on the name and short description of the add-on to determine if I need it?
If the short description of the add-on does not specify what functionality it provides, I cannot immediately determine its purpose
Especially those add-ons that have a wide range of different functions
Or an add-on similar to xxx enhance.

### Describe the solution you'd like

Add a control to display the readme

**Comment by XLTechie** [comment] 2023-10-04 09:26
This might be better achieved, by requiring that add-ons provide a homepage.

Also, by allowing hashmarks (#) in homepage URLs, so the GitHub #readme feature 
can work.
(/user/repo#readme will take the page directly to the readme, but the store 
currently filters these out of URLs)

**Comment by hwf1324** [comment] 2023-10-04 09:32
Opening a browser window is a disruptive action when it comes to quickly checking the functionality of add-ons

Moreover, the current GUI has a large blank space available to display information

**Comment by CyrilleB79** [comment] 2023-10-04 10:39
Today, the readme document of installed add-ons is accessible through the Action menu, Help item. It opens a browser with the readme.
Your request is that this information be embedded directly in the add-on store GUI and do not open an external browser. Your request applies to installed add-ons. Is all this correct?

What about available (and not installed add-ons)?

@XLTechie there is already an action to open the home page in the action menu. Your request to allow "#" in URLs deserves a separate issue IMO.

**Comment by hwf1324** [comment] 2023-10-04 10:51
> Your request is that this information be embedded directly in the add-on store GUI and do not open an external browser. Your request applies to installed add-ons. Is all this correct?

Yes, but I believe this feature is more important for those who browse the functionality information of a large number of add-ons that are not installed in the add-on store

> What about available (and not installed add-ons)?

Initiate a network request to retrieve the corresponding data

But is it necessary to check the old readme for already installed add-ons here?

**Comment by CyrilleB79** [comment] 2023-10-04 11:25
Well this request is still a bit general.

Could you complete the "Is your feature request related to a problem? Please describe." paragraph? Present there a real life use case (or more) explaining what you are trying to achieve and what the issue is.

**Comment by hwf1324** [comment] 2023-10-04 11:51
Can you please provide additional information for the paragraph "Is your feature request related to a problem? Please describe."? Include a real-life scenario (or multiple scenarios) that illustrate what you are attempting to accomplish and what the problem entails.

@CyrilleB79, I have edited it

**Comment by josephsl** [comment] 2023-10-04 12:11
Hi, try selecting “help” from add-on context menu (from add-on store) and see if that makes a difference (this requires add-ons themselves to come with readme files). Thanks.

**Comment by lukaszgo1** [comment] 2023-10-04 14:41
The fact that readme for a given add-on cannot be read before installing it from the store comes up from time to time on various community mailing lists. The main problem which is mentioned is that users perceive it to be a regression compared to the, now legacy, add-ons website. When using the web page to install add-ons you could essentially read the documentation for the add-on and decide if it is of interest or not. While it is obviously possible to open the add-on web page from the context menu it is way more tedious than it used to be. My initial thought would be to just add additional metadata field to the json spec which would contain HTML content of the add-on readme. While this would be certainly a major project it would allow us to fully deprecate the add-ons  website, providing the same informations in the store.

**Comment by XLTechie** [comment] 2023-10-05 00:52
> Opening a browser window is a disruptive action when it comes to quickly checking the functionality of add-ons

And, I will just note that closing said browser window/tab, usually doesn't 
re-focus the store interface.

That's one of the reasons I proposed using ui.browseableMessage to display 
readmes and such, though that proposal was rejected.

**Comment by nvdaes** [comment] 2023-10-07 20:07
In a talk organized by @jmdaweb, people has mentioned that, in the old add-ons manager, the Help button maybe easier to use. What about using shift+f1 to open the Homepage for available add-ons, which usually includes the readme (not translated), and to  open the translated documentation for installed add-ons?

**Comment by seanbudd** [comment] 2023-10-09 22:52
Closing as duplicate of #13454

There is already an action to open the homepage before installing an add-on.

**Comment by XLTechie** [comment] 2023-10-10 00:03
@seanbudd, #13454 is about the Add-on Manager. This seems more applicable to the 
case of the store, since the controls in that issue no longer exist.

**Comment by CyrilleB79** [comment] 2023-10-10 07:06
@seanbudd, #13454 was about the add-on manager. There is an associated PR, #14615, on which I still have to work. But the issue and the PR are about the add-ons from the add-on manager, which translates to external add-ons in the new add-on store.

Instead, even if a bit confuse, the current issue seems to be about having the documentation directly visible (without any button) in the add-on store. This is a quite different request.

**Comment by lukaszgo1** [comment] 2023-10-10 09:53
While this seemed obvious to me, perhaps it is still worth mentioning explicitly that being able to open add-ons homepage from the context menu is of any use for non-english speaking people if, and only if, the url leads to the community add-ons website. If it leads for example to GitHub readme displayed by default is in English, and reading the documentation in another language requires browsing add-on files, that is not something doable for most users. The  older community website allowed to select a language in which the documentation was displayed, an, I believe though haven't tested this explicitly, even used the browser language by default.

**Comment by XLTechie** [comment] 2023-10-10 10:08
@lukaszgo1 while I had not considered that point, and I thank you for 
introducing it, it does lead us to the expectation that the community site will 
be discontinued at some point perhaps not very far away.

Further, only a (shrinking) subset of store add-ons are represented on that 
site.

Does the help menuitem open the language specific readme?
(It doesn't appear to looking at the code, but I only looked very briefly)

**Comment by lukaszgo1** [comment] 2023-10-10 10:22
Yes, the 'help' menu item opens the readme for the installed add-on in NVDA's language, as long as there is a translated readme of course. As to the add-ons website being deprecated I strongly believe this should not be done until this issue is addressed in some form, so that users can read the add-on documentation in their native language before installing it.

**Comment by seanbudd** [comment] 2023-10-16 23:05
The original issue describes the purpose of the homepage button, which already exists.

So the only work remaining here is being able to read a thorough and translated description of the add-on i.e. the add-ons help page.

I closed this as a duplicate of #13454 for this reason.

I'm not sure what other work is remaining here given the existence of the homepage button.

**Closed by seanbudd** 2023-10-16 23:05 UTC
