### ISSUE TITLE
Outlook 2010: No Feedback Given when attempting to save Excel Attachment

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5576] opened 2015-12-04 17:47 UTC
STR:
1. From within Outlook, open an email that contains an Excel-based attachment
2. Shift-Tab to the list of attachments, and use the right cursor to navigate to the filename of the Excel workbook

Expected: As is currently the case for many other attachment types, NVDA should output the filename of the focused item and when pressing Enter, the user should be given the option of whether to either open or save the file.

Actual: Whilst the filename is output, pressing Enter does not allow the user to choose the required action for the file in question; it is necessary to use Object Navigation to either right-click or double-click on the file to carry out the required task. It is my guess that the Excel-based preview that Outlook offers may be the cause of this, but if this is the case NVDA doesn't output any information after the attachment has initially been focused.

**Comment by leonardder** [comment] 2017-07-17 11:19
The preview pane is indeed the cause of this issue, I've seen this with SuperNova in Outlook 2010. Given the fact that you can disable this pane, I'm leaning towards a won't fix, since there is a suitable workaround. Having said that, I wonder whether Outlook 2016 suffers from the same issue.

**Comment by leonardder** [comment] 2018-02-20 14:45
Still leaning towards a close. I assume we could be able to move the focus out of the preview handler window, but this is really something MS should allow us to do. May be we should add a paragraph to the user guide that advises to disable office preview handlers?

**Comment by Adriani90** [comment] 2019-02-06 16:38
Yes, this is an issue caused by the preview pane. However, in Outlook 2010 at least pressing enter on an Attachment opens it without giving you any Options to save or so. You can press the application key and then you can save the attachment. So I am closing this because there is a Workaround for it. Discussions on preview pane is more apropriate in issue #4351.

**Comment by Adriani90** [comment] 2019-02-06 16:40
In fact, I would prefer Support for preview pane implemented in NVDA rather than simply moving the Focus out of it. This would improve Efficiency especially because you would not have to Change the window when editing an E-Mail based on an Excel sheet or so.

**Closed** 2019-02-06 16:40 UTC
Labels: Microsoft Office support
