### ISSUE TITLE
NVDA narrates text in PowerPoint Slides twice

### ISSUE THREAD

**Issue by TetaFred** [nvaccess/nvda#10772] opened 2020-02-10 05:33 UTC
Steps to reproduce:

1.  Turn on NVDA
2. Open PowerPoint 
3. Turn to PowerPoint Slide Show
4. Listen to NVDA narrate text on the slides

Actual behavior:
NVDA narrates all text on the slides twice

Expected behavior:
NVDA should only narrate text on the slides once

System configuration

NVDA installed/portable/running from source:
Installed

NVDA version:
2019.2.1

Windows version:
Windows 10 Version 10.0.18363 Build 18363

Name and version of other software in use when reproducing the issue:
PowerPoint Version 2001 Build 12430.20184

Other information about your system:
Running Windows 10

Other questions

Does the issue still occur after restarting your PC?
Issue repros even after restarting the computer

Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by DrSooom** [comment] 2020-02-11 14:28
Unsure if this issue here is a duplicate of issue #9379. @TetaFred: Please check this out and correct the typo in the PowerPoint version. Thanks.

**Comment by TetaFred** [comment] 2020-02-11 17:30
Hi Daniel,
Thant’s correct and I’m closing out 10772<https://github.com/nvaccess/nvda/issues/10772> as a duplicate.
Thanks

Fred

**Comment by TetaFred** [comment] 2020-02-11 17:31
Duplicate of 9379

**Closed** 2020-02-11 17:31 UTC
