### ISSUE TITLE
can not connect Outlook to Gmail  with NVDA running

### ISSUE THREAD

**Issue by TJOlsen87** [nvaccess/nvda#15139] opened 2023-07-14 03:59 UTC
### Steps to reproduce:
open the new account dialogue
### Expected behavior:

when I use Jaws or Narrator I am able to get the password prompt

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
23h2 most recet
#### Windows version:
11  23h2
#### Name and version of other software in use when reproducing the issue:
microsoft outlook 365
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022h2 2023h1
#### If NVDA add-ons are disabled, is your problem still occurring?
yes

**Comment by CyrilleB79** [comment] 2023-07-17 07:56
Hi @TJOlsen87 

Could you please edit your first comment and fill correctly all the requested fields from the template?
* Versions of NVDA and Windows are not valid
* Version of microsoft outlook: we need the precise version; 365 is not a version number for MS Outlook but the name of a product.
* You did not report the behaviour with other NVDA versions
* No empty fields please

Also, could you test if the issue is fixed with [last alpha version](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-28694,c4ca763b.exe)? You can test it using it as a portable version or directly from the launcher.

**Comment by seanbudd** [comment] 2023-07-20 00:45
Please re-open a new issue with the template properly filled.

**Closed by seanbudd** 2023-07-20 00:45 UTC
