### ISSUE TITLE
Select all is not properly announced when cursor is to the right of last character

### ISSUE THREAD

**Issue by tmthywynn8** [nvaccess/nvda#7195] opened 2017-05-23 10:25 UTC
Problem: When selecting all text with CTRL+A when the cursor/caret is at the end of a document/edit box, NVDA stays silent. Is this related to #7131?

Steps to reproduce:
1. Open Notepad.
2. Type"This is a test." without the quotes.
3. Press CTRL+A then backspace.
    - Expected: NVDA should say "This is a test. selected," followed by "selection removed."
    - Actual: NVDA stays completely silent.
4. Type "test." without the quotes.
5. Press CTRL+A, then CTRL+X.
    - Expected: NVDA should say "test. selected," followed by "selection removed."
    - Actual: NVDA just says "selection removed," providing feedback for only CTRL+X.

Note: Select all is not announced at all in the Run dialog (Windows+R) regardless of cursor location , but that's probably a separate issue?

**Comment by jcsteh** [comment] 2017-05-25 01:15
Duplicate of #1898. NVDA uses caret movement events to detect selection changes for Win32 Edit controls, but if the caret doesn't move (as is the case here), no caret event is fired, so NVDA doesn't get notified about the changed selection.

**Closed by jcsteh** 2017-05-25 01:15 UTC
