### ISSUE TITLE
nvda reads toast notifications repeatedly

### ISSUE THREAD

**Issue by mreiser** [nvaccess/nvda#7204] opened 2017-05-25 00:49 UTC
### Steps to reproduce:
1.  Using Microsoft mail, send your self a test message.  

2.  Wait for the notification.  
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.
NVDA should only speak the notification once.  
### Actual behavior:
> Tell us what happens instead.
NVDA repeatedly reads the notification.  
### System configuration:
NVDA version:
> Example: next-14027,c80e529f
2017.2 rc1
NVDA Installed or portable:
installed
Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066
windows 10 version 1703 build 16199.100
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
> Please list them and the result
version 2017.1 with the same result

**Comment by josephsl** [comment] 2017-05-25 00:59
Hi, a duplicate of an issue posted a few days ago (I think), which I, @DerekRiemer and others are actively tracking. Thanks.

**Comment by jcsteh** [comment] 2017-05-25 01:03
Duplicate of #7128.

**Closed by jcsteh** 2017-05-25 01:03 UTC
