### ISSUE TITLE
Capitalization pitch change doesn't work with sapi 4

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#12356] opened 2021-04-30 16:45 UTC
### Steps to reproduce:
1. Select sapi 4 as your Synthesizer.
2. Make sure that the capitalization pitch change setting is set to have an effect on the pitch, for example at the default value 30.
3. Cursor over a capital letter or type one, assuming that speaking typed characters is turned on
### Actual behavior:
NVDA doesn't rise the pitch when reading the letter
### Expected behavior:
NVDA should rise the pitch
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.4
#### Windows version:
Windows 10 prerelease (10.0.19043) workstation
#### Name and version of other software in use when reproducing the issue:
Sapi 4 voices, such as via voice or Infovox Desktop 2.2
#### Other information about your system:
I tried it with the afore mentioned voices but it didn't work. I normally use infovox and thought it might be an exclusive issue with that synthesizer, but it isn't.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I did try 2019.2.1, because I thought maybe this issue could come from Python 3. It doesn't though.
#### If add-ons are disabled, is your problem still occurring?
I don't think it's linked with that, so didn't try it.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
I don't see how that tool could be responsible for this kind of issue.

**Comment by XLTechie** [comment] 2021-04-30 18:42
I believe this is a duplicate of #10896 and #10926.

**Closed** 2021-04-30 18:59 UTC

**Comment by XLTechie** [comment] 2021-04-30 19:10
> you are right! Sorry! Shouldn't it have notified me when creating the issue? It didn't, so I thought it was ok.

Not really. You have to do your own searching for existing issues.

That old feature I think it had, of suggesting issues with similar titles, 
seems no longer to exist. At least, it never happens for me any more.

**Comment by cary-rowen** [comment] 2021-05-01 04:38
I think this is still a duplicate of #12311. But PR#12354 seems to fix it, can you test it with the latest Alpha version?

**Comment by hozosch** [comment] 2021-05-01 09:46
It's true, the latest alpha partially fixes the problem, and yes, 2019.2.1 has the same partial fix as the Alpha versions. In both versions, the problem still persists with Infovox Desktop 2.2 though.

**Comment by feerrenrut** [comment] 2021-05-03 02:07
If this is specific to infovox, it might be worth having a separate issue. There may be something non-standard about infovox that needs a workaround.

**Comment by hozosch** [comment] 2023-10-30 14:37
Well, in the latest alpha versions, this is clearly fixed. Infovox respects it as well now. wasn't there a pull request for rewriting capital pitch change for sapi4?

**Comment by cary-rowen** [comment] 2023-10-31 01:11
cc @seanbudd 
You may be able to close this issue.
