### ISSUE TITLE
Improve support for Eclipse

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#5667] opened 2016-01-10 20:18 UTC
Hi,

I made some modifications to the AppModule for the Eclipse IDE.

It's to allow using the autocompletion feature without leaving the focus from the code editor.

[eclipse_appModule_patch.txt](https://github.com/nvaccess/nvda/files/85156/eclipse_appModule_patch.txt)

It's a patch file.

Cheers.

**Comment by dkager** [comment] 2016-01-13 10:23
> +class autocompletionItem(IAccessible):

Following code semantics, the class should probably be called AutocompletionItem (with capital A).

> +		# Fixme: I don't know if it is the correct way to do this.
> +		ui.message(self.name)

With default configuration this will show the message in braille for only a few seconds. If I remember correctly Eclipse doesn't pop up a proper context menu for these suggestions, so this solution may be the next best thing. Still, if it is actually a list that stays on screen for the programmer to ponder over it'd be nice if NVDA could interpret it as such. Would it not be possible to auto-focus this thing when it appears? Just some uneducated guesses...

**Comment by francipvb** [comment] 2016-01-13 11:17
Hello,

El 13/01/2016 a las 07:23 a.m., Davy Kager escribió:
>     +class autocompletionItem(IAccessible):
>
> Following code semantics, the class should probably be called
> AutocompletionItem (with capital A).

Yes, I did read the code semantics after posting it.

>       * # Fixme: I don't know if it is the correct way to do this.
>       * ui.message(self.name)
>
> With default configuration this will show the message in braille for
> only a few seconds. If I remember correctly Eclipse doesn't pop up a
> proper context menu for these suggestions, so this solution may be the
> next best thing. Still, if it is actually a list that stays on screen
> for the programmer to ponder over it'd be nice if NVDA could interpret
> it as such. Would it not be possible to auto-focus this thing when it
> appears? Just some uneducated guesses...

Anyway, I noticed some problems dealing with it in this way. For 
example, if you are at a longer line, you need to wait the synthesizer 
finish reading it before start reading the selected suggestion.

Additionally, this script actually doesn't support the XML 
Autocompleter, for example.

I think that it can be better sending a fake gainFocus event or stopping 
the speech before it can be read.

I'll test these alternatives and then I'll post a pull request.

P.D: Sorry, my English is too bad.

Cheers,
-- 
¡Cuando tus fuerzas terminan, las de Dios comienzan!

**Comment by francipvb** [comment] 2016-01-14 17:30
Hello,

I believe that it's solved. Please test it and reopen this isswe if you have problems.

Cheers,

**Comment by josephsl** [comment] 2016-01-14 17:55
Hi,
Please don't close an issue just because you think it is closed (this patch requires further user testing).
An issue should be closed if:
1. This is a duplicate of an existing issue.
2. A setting change has fixed na issue.
3. Officially included in a release version of NVDA (inclusion into master means it is definitely included in the next version).
If ther's a way to reopen this...
Thanks.

**Comment by feerrenrut** [comment] 2017-11-01 05:41
The change associated with issue has been reverted. Re-opening this issue. The change caused an error to be raised in some circumstances please see https://github.com/nvaccess/nvda/pull/5680#issuecomment-340877036 for further details.

**Comment by Adriani90** [comment] 2019-02-12 13:45
are there any further alternatives planed to solve this issue? @feerrenrut mybe we can get some further suggestions from @albzan who created an eclipse addon? @albzan are you planning to raise any pull requests with improvements?

**Comment by francipvb** [comment] 2019-02-18 12:24
Hello,

I'm tweaking this a little...

Sorry for the *huge* delay.

**Comment by francipvb** [comment] 2019-02-19 22:38
Hello,

Please check #9297.

cheers,

**Comment by albzan** [comment] 2019-02-23 21:42
> are there any further alternatives planed to solve this issue? @feerrenrut mybe we can get some further suggestions from @albzan who created an eclipse addon? @albzan are you planning to raise any pull requests with improvements?

Yep, I'm open for contributions and, too, if someone want to help improve it and submit to the addon community site.
For the automatic announcement of the dialog, I think it should be annoying because it will be repeated for each letter you enter. I've developed a version where when the pop-up comes up the addon makes a sound.
What do you think of this implementation?

**Closed** 2019-05-13 14:54 UTC
Labels: App specific
