### ISSUE TITLE
Add a feature in NVDA, which should work as "flexible web" of JAWS for windows.

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#6372] opened 2016-09-13 06:26 UTC
Hi NVDA developer. Here i'am with a request to add  another very useful feature for browsing the internet, specially for those who are the daily readers of different types of contents on the internet such as newspaper, articles, online books, and lot more! 
Some words about flexible web:
Frequently, we encounter Web pages that contain a lot of excess content which can make it difficult to locate the actual content we want, or interupts the flow when reading. For instance, many sites contain Google ad frames. These can be troublesome for screen reader users as they disrupt the reading order of surrounding content.
Flexible Web enables you to take more control of Web pages by allowing you to quickly find the content you are looking for, as well as hide content that interrupts the reading experience. We can hide sections of content, such as Google ad frames or other types of unnecessary content, for a smoother reading experience.
Application:
So, this is flexible web, but i think currently there is nothing available like this in NVDA. That's why i've created this issue ticket, so the developer should add it in the list of upcoming feature list. It will be a major addition to strong-growing freeware screen reader called NVDA! I would also like to request you to involve the add-on developers to make an add-on for the same, if it is more suitable as comparing to adding it as core product functionality. Thanks a lot for any anticipation

**Comment by dreinn** [comment] 2016-09-13 06:59
Hello,
I always have many difficulties  to understand why a screen reader 
should have similar features.
If you use firefox, or google chrome, and for example install adblock, 
or adblock plus, or use F123Access, you will have your web page 
absolutely free of banner and frame and social network.
On my opinion this is not a screen reader feature.
Also, Firefox have a reading mode that you can find on the view menu. If 
you activate it when the article is loaded, you will have only the text, 
like reading mode on iphone or OSX.
I know that Jaws has many features, but some of these doesn't allow 
users to learn new browser capabilites.
This is only my opinion.








Il 13/09/2016 08:26, abdullah5490 ha scritto:

**Comment by josephsl** [comment] 2016-09-13 07:17
Hi,

This is a much more informative duplicate of #5073. Thanks.

**Closed by josephsl** 2016-09-13 07:17 UTC

**Comment by Brian1Gaff** [comment] 2016-09-13 07:42
Yes reinventing the wheel seems a bit daft, however, I do often have issues 
when trying to read content where it seems every other word is a link, I'm 
not sure how one might process this if you just want to hear the text or cut 
and paste it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment] 2016-09-13 08:48
Just disable reporting of links for a while in these situations. There is an unbound gesture for that.

**Comment by abdullah5490** [comment] 2016-09-13 16:51
First, mister @josephsl i don't know how to find a specific issue before posting to avoid duplicates. So sorry if it bothers you! And what does the "close" means? You've closed this issue, what does it means? Secondly mister @dreinn i am not talking about hiding the ads only. I know that there are multiple solution for this. But i'm asking for hiding whatever contents on a webpage those are unwanted for a regular user. For  instant if you are using facebook, there is a lot of area on each page that you won't needed while regular serfing. It may include links your pages, suggested pages, apps, advertisements, people you may know etc. So you can hide them all at once with flexible web, and continue to brows the interested contents that matters to you. Hope its clear

**Comment by josephsl** [comment] 2016-09-13 17:08
Hi,

hmmm, interesting questions, things that I believe should be addressed before we continue:

Closing issues: for this one, I closed it as this is a duplicate.

Ignoring unwanted web content: this is relative and unsound. This is a relative one in that what one may consider unwanted is something that someone would mark as important, which may appear to support Flexible Web. However, this goes against very nature of web technology, advocacy and competency:

* Nature of web technology: web is a continuously changing field of text, multimedia, markup and protocols. Even if told to ignore specific content, they'll come back in one form or another later.
* Competency: ignoring unwanted web content isn't the ultimate answer to life on the web. Rather, I believe the real answer is learning to navigate the web more effectively using commands such as moving past a group of links, finding text and so on.
* Advocacy: I believe adding features isn't the effective route to advocacy for improved web accessibility and efficiency. Rather, the best route is letting webmasters know what's going on and work towards collaborative solution.

Thanks.

**Comment by abdullah5490** [comment] 2016-09-13 18:28
No mister @josephsl actually you are not getting me. The flexible web is aimed to provide an option to hide a specific type of contents, or a specific area of a web page according to user's desires. It does not work to hide any content automatically. But we can use it to hide any region, block quotes, frame, or group of headings, an advertising frame, or anything you want, by setting up a rule for the current page. We can apply that rule only to the currently active page, or to every pages under the same domain such as facebook.com or nvaccess.org. And we can also configure a specific rule to be applied automatically when that specific page load each time in the browser. Moreover, we can also use the flexible web technology to avoid skipping navigation, like we can set up our virtual curser to be directly jump to a specific area of page, and start navigating from there below. If it is still not cleared, then please take a time to look at the feature details in JAWS documentation. May be you'll find a clue to understand what i'am saying here! Ultimately, it is a great feature for writers and readers, specially students.
