### ISSUE TITLE
Add an issue template for feature requests

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#8494] opened 2018-07-10 09:20 UTC
### Steps to reproduce:
1. Create a new issue at
https://github.com/nvaccess/nvda
2. Try to suggest a new feature.
### Actual behavior:

A template designed for reporting bugs is shown.

### Expected behavior:

A template designed for requesting a new feature should be shown.
Fields like example/s of use cases, suggestions about design and others could be included.
An example of this can be found at:
https://github.com/nvdaes/emoticons/
More info:
https://help.github.com/articles/creating-issue-templates-for-your-repository/

**Comment by DrSooom** [comment] 2018-07-10 13:43
Well, a feature request is similar to an issue. ;) Several things like the actual and the expected behaviour as well as OS and software metadatas might helpful as well. As far as I see based on your linked help article there isn't a way to create multiple templates for an issue.

Solution: The title of an feature request should start with the prefix "[Request]". This little info can be added to the command section at the top of the issue template. The devs can than labelled this issue as a feature request later on and delete this temporary prefix in the issue title as well.

**Comment by nvdaes** [comment] 2018-07-10 14:14
DrSooom commented 26 minutes ago 

> As far as I see based on your linked help article there isn't a way to create multiple templates for an issue.

It's possible to create several templates for an issue, one for bugs and other one for feature requests.
I think this could make easier requesting features, with fields better adapted for this.
Please see my example at:
https://github.com/nvdaes/emoticons/

And try to create an issue on this repo.
Thanks

**Comment by nvdaes** [comment] 2018-07-10 14:38
Thanks @leonardder.
I suggest the following fields:


### Feature description ###

Example: Include the ability of skipping elements when in browse mode when pressing NVDA+f7.

### Suggestions about design

Example: Add a checkbox labelled Skip frames and show elements outside them. 

### Use cases

Example: Skip announces.

**Comment by DrSooom** [comment] 2018-07-10 14:45
@leonardder: I fully agree with you. I also didn't know this and I just checked it out now and I think it really might be helpful.

But I have one more question: Is it possible not only to create different issue template, is it also possible to label feature request on created this type of issue automatically by default? I couldn't figure this out during my testing.

**Comment by josephsl** [comment] 2018-07-10 14:48
Hi, I think it’s not implemented by GitHub, but I could be wrong (there is a related feature for pull requests where reviews will be assigned automatically based on which file was edited). Thanks.

**Comment by DrSooom** [comment] 2018-07-10 15:02
The template for the feature request should be similar to the current one – no examples in the template itself, but in a separate wiki article.

I would prefer the following headlines:
* Feature description
* Benefits against the actual behaviour
* Concerned OS, software or NVDA module (e.g. Firefox, Braille, gestures.ini)
* List of changes (e.g. in the GUI, translations, nvda.ini, documentations)

**Comment by josephsl** [comment] 2018-07-10 15:08
Hi, because it could become confused with pull request, I’d rather not put changes to be made in ‘new feature” issue template. At a minimum, I think the rationale, feature description, new behavior/change, and design should be present, with additional headings as needed. Thanks.

**Comment by nvdaes** [comment] 2018-07-10 15:38
I think that this should make easy for users to request features, so imo, though bug reporting requires very precisse information for reproducing and debugging, this should be more flexible:
1. Users should be able to describe the requested feature, and in the Wiki article we can suggest to be sure that this is not included in NVDA or recommend to search issues with the same topic to avoid duplicates.
2. Use cases should be provided to avoid requesting features not useful.
3. Design could be provided, but this shouldn't be very strict, since it's possible that users don't know how this should be implemented. This can be decided with several comments.
Thanks

**Comment by Adriani90** [comment] 2018-07-10 16:43
I think such feature requests can be marked as feature by issue trackers and developers can start to discuss with the users about certain use cases.

**Comment by nvdaes** [comment] 2018-07-10 20:13
Adriani90commented 3 hours ago

> I think such feature requests can be marked as feature by issue trackers and developers can start to discuss with the users about certain use cases.

I agree. But I think that a field asking for use cases will be useful in the template.
I'm not quite sure about feature description. The title may explain the request in some cases, but a description may be needed to provide more details, and it's more probable that developers change the title than a description, so I think that description field will be included.
Also, a possible field will be the scope of the feature, for instance: NVDA portable/inhstalled/website. A set of checkboxes in the template may be useful for this.

**Comment by feerrenrut** [comment] 2018-12-02 13:32
I have just created a PR for this, please take a look at #9000

**Closed** 2018-12-05 11:51 UTC
