### ISSUE TITLE
Input labels are not announced when virtual focus enters an input while reading line by line

### ISSUE THREAD

**Issue by mfairchild365** [nvaccess/nvda#10812] opened 2020-02-22 18:30 UTC
### Steps to reproduce:

1. navigate to https://codepen.io/mfairchild365/full/zYGodew
2. read the entire page by using the 'down' arrow (line by line)

### Actual behavior:

observe that when the virtual focus is placed on an input, the input's name is not announced. However, it will be announced if the label is on the same line.

### Expected behavior:

I'm not sure what the expected behavior is. This could be a bug, or it might be considered a feature. It is worth noting that JAWS, Narrator, Orca, and VO all read the input's name while reading line by line or item by item.

#### NVDA installed/portable/running from source:

installed

#### NVDA version:
2019.3.1

#### Windows version:

1909

**Comment by Brian1Gaff** [comment] 2020-02-23 09:14
Is this not the same as one just raised a few days ago, which pridictably, I 
cannot find. IE text in the edit area is read but the label is not making it 
hard in forms to work out what its asking for?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by mfairchild365** [comment] 2020-02-23 20:58
It sounds like the same issue, but I also didn't see one created by you. I did some more research, and JAWS only announces the name because it switches to forms mode automatically when entering an input. If you turn off that option, you get the same results as NVDA.

I also [found an old issue about this](https://github.com/nvaccess/nvda/issues/4773).  It appears that it was an intentional decision to not announce the name since the name should already be in the reading order. In other words, the reason for not announcing the name is to reduce duplication. However, I'd like to point out that there are situations where the label for the input may not be in the reading order right before the input. For example, the author might decide to put the label after the input, or they might decide to place it somewhere else on the page. These situations are fairly rare, but perhaps worth considering.

**Comment by Brian1Gaff** [comment] 2020-02-24 08:50
It was not created by me, it was somebody else.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2020-02-25 20:03
@mfairchild365 if you enable "preserve screen layout" in NVDA' settings under cathegory "browse mode", the input label "in line after" will also be reported, but after the edit field and the content has been reported. So you have to wait a big, NVDA will report "edit - in line after. This is because the label is after the field. In my view from an user perspective it doesn't make sense at all to put labels after the field, this is not what someone would do when creating a form on printed paper either and is really good web design. But this might be only my opinion.

Regarding NVDA's behavior, this is actually expected behavior here. Moreover, NVDA announces all the labels properly when pressing e to navigate between edit fields in browse mode. And it also announces the labels when navigating by tab, both in browse mode and focus mode.
When preserve screen layout is disabled, NVDA will try to virtualize every element on a single line (i.e. label and edit field will be virtualized on separate lines although they are on the same line visually). This is also the same behavior in jaws.
To avoid double information here and because the user has plenty of alternatives to get the label, I would close this for now as works for me.
If you have any other arguments, please comment further on this issue and we can reopen it.

**Closed by Adriani90** 2020-02-25 20:03 UTC
Labels: worksforme

**Comment by mfairchild365** [comment] 2020-02-25 20:09
I agree and thank you for sharing those details. Much appreciated.
