### ISSUE TITLE
Firefox: Inconsistent Reading of Content when navigating via word using Object Navigation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5477] opened 2015-11-10 21:10 UTC
STR:
1. Paste the following URL into an empty Firefox Address Bar:

    ```https://github.com/nvaccess/nvda/issues/5476```

2. At the start of the link, read its contents by navigating via word using Object Navigation. You should notice that output is as expected, and that NVDA breaks the URL up as necessary
3. When at the end of the URL, begin to navigate the URL in reverse, but still by word using Object Navigation

Expected: NVDA to navigate the user back through the URL using the same breaks in the text

Actual: Double occurrences of the "/" character are encountered; I have know idea where NVDA is fetching these from! Either way, I don't think that these should be repeated twice

**Comment by leonardder** [comment] 2017-07-15 13:55
I can still reproduce.

@JCSTeh: Seems something went wrong in assigning labels to this.

**Comment by jcsteh** [comment] 2017-07-17 02:04
Yeah, can't quite remember what happened there, but the final result (just needsExternalFix) is correct. However, it'd help if I explained why. :)

This occurs because in order to get the previous word, we ask for the word at the previous character. In the problematic case, the character is the slash. When we ask for the word, Firefox just returns the slash. When we then ask for the word before the slash, Firefox returns the word including the slash. Firefox shouldn't return the slash as its own word.

Probably related to https://bugzilla.mozilla.org/show_bug.cgi?id=872397.

**Comment by Adriani90** [comment] 2019-02-02 13:19
This is still reproducible in NVDA Alpha 16691,10950C87 and Firefox 65.

**Comment by jcsteh** [comment] 2021-11-05 00:37
This was fixed in Firefox 83.

**Closed by jcsteh** 2021-11-05 00:37 UTC
Labels: blocked/needs-external-fix, p3
