### ISSUE TITLE
UIA Focus Event bugs in Win10

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6574] opened 2016-11-18 05:18 UTC
@jcsteh
This came about after some discussion on twitter - @jcsteh suggested moving this discussion to someplace more suitable.

I suspect there is a bug in the way that win10's UIA implementation raises focus events - screen readers do not move focus properly. This can easily be seen when you try opening a file that has no file extension, triggering the open with dialog. In both jaws and NVDA, the dialog coming up is not announced. 

Inspecting the accessibility tree, the focus is being placed on a pane, this pane is the parent of the controls we actually need focus to land on. 

I suspect this is also related to a bug in visual studio, where pressing ctrl+shift+b to build a solution does not properly place focus, or ctrl+alt+l to move to the solution explorer tree view.

**Comment by josephsl** [comment] 2016-11-18 05:26
Hi, is there a pattern (such as similarly labeled UIA automation ID’s or class names) we can use to hunt these down and come up with a solution? Thanks. CC @MichaelDCurran

**Comment by Neurrone** [comment] 2016-11-18 05:48
I didn't notice anything at first glance, other than the fact that the focus keeps on landing on the parent of the object that we actually need focus to be on. The class names and such are very long WPF names, which look to be autogenerated, and the control ID is also set to 0. 

The ideal fix is to get Microsoft on this.

**Comment by Adriani90** [comment] 2019-03-18 21:38
@josephsl, @Neurrone are there any improvements made from UIA side regarding this behavior? I cannot reproduce this issue very often now but I might be wrong.

**Comment by Adriani90** [comment] 2019-03-18 21:38
cc: @FelixGruetzmacher

**Comment by Adriani90** [comment] 2020-01-18 20:28
this is highly related to #8389.

**Comment by Adriani90** [comment] 2024-04-12 12:13
This is not reproducible in Windows 11, and I cannot reproduce it either in Windows 10 last update.
I am closing this issue as works for me. If you are still having it, please comment and we can reopen.

**Closed by Adriani90** 2024-04-12 12:13 UTC
Labels: close/worksforme
