### ISSUE TITLE
Add a silent uninstaller

### ISSUE THREAD

**Issue by Nael-Sayegh** [nvaccess/nvda#16892] opened 2024-07-22 18:25 UTC
### Is your feature request related to a problem? Please describe.
NVDA offers a silent installer that can be used by specifying a configuration, which is very convenient for deployments on remote computers, such as with WAPT.
However, it does not provide a silent uninstaller, which poses a problem if you want to uninstall it remotely when the user doesn't need it, as WAPT would. .Or it is not documented

### Describe the solution you'd like
It would be practical to have a silent uninstall key available or to provide an argument to the uninstall.exe file to specify that it should be silent and remove the user's configuration.

### Describe alternatives you've considered
None

**Comment by Nael-Sayegh** [comment] 2024-07-22 18:26
Does this function already exist @SaschaCowley ?

**Comment by SaschaCowley** [comment] 2024-07-22 23:28
@Nael-Sayegh Not as far as I know.

**Comment by wmhn1872265132** [comment] 2024-07-23 00:45
NVDA can be uninstalled silently through uninstall.exe /S, but please note:
1. The configuration files in %appdata%\NVDA need to be deleted manually;
2. Since the uninstaller runs under ordinary user rights by default, it needs to be executed in a command line with administrator rights to uninstall correctly.

**Comment by SaschaCowley** [comment] 2024-07-23 00:50
@wmhn1872265132 Is this documented anywhere?

**Comment by wmhn1872265132** [comment] 2024-07-23 00:53
This is a function provided by NSIS. NVDA has not found any documentation describing this function.

**Comment by SaschaCowley** [comment] 2024-07-23 01:05
Thanks, @wmhn1872265132.

**Comment by gerald-hartig** [comment] 2024-07-24 03:14
This is a duplicate of https://github.com/nvaccess/nvda/issues/16150, however it could be better documented. @Qchristensen

**Comment by Qchristensen** [comment] 2024-07-24 03:59
Per [@wmhn1872265132's Comment above](https://github.com/nvaccess/nvda/issues/16892#issuecomment-2244047838), it sounds like this already works using the /S switch as an administrator, except for the %appdata%\NVDA folder.  There are several issues which reference this:

#6869 notes how add-ons are left after uninstall.
#9596 requests an option to prompt whether to use or remove old configurations on install.  I created that one out of the need that some users were uninstalling / reinstalling NVDA to fix an issue with a non-working configuration (they'd set the speed too fast, NVDA volume to silent, etc and thought reinstalling might fix it).

So, two or possibly three actions for this:

Can anyone confirm, are these (config & add-ons not being removed) the issues referred to about running uninstall with /S as a regular user rather than administrator, or are there more?

1) If the routine needs to run as administrator, can we prompt for admin access when running it?

2) Document in https://www.nvaccess.org/files/nvda/documentation/userGuide.html#CommandLineOptions the silent uninstall switch.

3) Should we consider an uninstall option (and associated command-line switch) to force deletion of add-ons and configuration files.  This may resolve #9596, but in any case, is also likely the behaviour expected by corporate users.

**Comment by wmhn1872265132** [comment] 2024-07-25 00:31
It should be pointed out that NVDA's uninstaller does not support clearing user configuration files, so whether it is uninstalled through the command line or through the GUI, the configuration cannot be deleted.

**Comment by Nael-Sayegh** [comment] 2024-08-05 07:54
@Qchristensen I think the default user directory should either be removed upon uninstallation, as this is the behavior expected by many users, or, as proposed, an option should be added to choose to remove it, which should also be possible via CMD.
I believe that uninstallation via CMD should be indicated in the documentation, as it would make the work easier for IT services for the deployment of NVDA.
One thing I haven't tested yet: is it possible to install NVDA via CMD by specifying a configuration to load for the user?

**Comment by SaschaCowley** [comment] 2024-08-05 23:08
> I think the default user directory should either be removed upon uninstallation, as this is the behavior expected by many users, or, as proposed, an option should be added to choose to remove it, which should also be possible via CMD.

I would vote for the latter. Many programs leave their user config present upon uninstallation to make things like repair installs easier. Nevertheless, a complete uninstall that removes all (reasonable) traces of NVDA should be an option.

> I believe that uninstallation via CMD should be indicated in the documentation, as it would make the work easier for IT services for the deployment of NVDA.

Absolutely agreed.  @coderabbitai please open an issue to document command line uninstallation of NVDA in the user guide.

> One thing I haven't tested yet: is it possible to install NVDA via CMD by specifying a configuration to load for the user?

I don't know, but I doubt it. One thing that might work as a work around is to create a portable copy, configure as desired, then install from portable keeping the config. I think this is possible from the GUI, but I'm not sure about from the CLI.

**Comment by Nael-Sayegh** [comment] 2024-08-06 08:15
@SaschaCowley It is true that many programs leave their configuration behind, and NVDA would do well to follow this way of functioning.
Adding an option to delete it seems like a good alternative.
I think your solution of installing a portable copy could work, thanks to the --copy-portable-config argument which seems to copy the portable configuration of NVDA to the new installation.
What do you think?

**Comment by SaschaCowley** [comment] 2024-08-07 00:34
Yes, I believe that's currently the only option to install with a custom config (short of making your own build that does what so).

**Comment by Nael-Sayegh** [comment] 2024-08-11 15:42
@SaschaCowley Yes, I think we can close this ticket since @coderabbitai has created another issue to document the uninstallation function.

**Comment by SaschaCowley** [comment] 2024-08-12 00:37
Closed as this is currently possible. Documentation recommended, see https://github.com/nvaccess/nvda/issues/16966 for progress.

**Closed by SaschaCowley** 2024-08-12 00:37 UTC
Labels: p5, triaged
