### ISSUE TITLE
Microsoft edge: NVDA is logging errors when pressing backspace in addressbar

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#15751] opened 2023-11-06 09:50 UTC
### Steps to reproduce:
Enter some url in addressbar and delete it with backspace
### Actual behavior:
NVDA is logging an error
### Expected behavior:
No error should occur
### NVDA logs, crash dumps and other attachments:
ERROR - eventHandler.executeEvent (13:45:40.940) - MainThread (44572):
error executing event: caret on <NVDAObjects.Dynamic_ChromiumUIAEditableTextWithAutoSelectDetectionUIA object at 0x05C2CBF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\behaviors.pyc", line 306, in event_caret
  File "editableText.pyc", line 398, in detectPossibleSelectionChange
  File "editableText.pyc", line 405, in _updateSelectionAnchor
  File "NVDAObjects\UIA\__init__.pyc", line 942, in compareEndPoints
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2146233079, None, (None, None, None, 0, None))

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3 and latest alpha
#### Windows version:
Windows 10 22h2 with latest updates
#### Name and version of other software in use when reproducing the issue:
Microsoft edge 119.0.2151.44 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2023-11-06 20:01
Closing as duplicate of #15563.

**Closed by Adriani90** 2023-11-06 20:01 UTC
Labels: close/duplicate
