### ISSUE TITLE
report subscripts and superscripts #10919: exclude reporting on elements in browsers such as buttons etc.

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#11078] opened 2020-05-01 07:55 UTC
### Steps to reproduce:
1. Open NVDA and enable reporting of subscripts and superscripts in NVDA's document formating settings
2. Open a browser i.e. Firefox
3. While navigating on websites with arrow keys or quick commands in browse mode, notice what NVDA reports (i.e. on some buttons in the comment area of this issue)

### Actual behavior:
NVDA reports very often "base line"

### Expected behavior:
NVDA should report "base line" only in mathematical content or if this is part of a text block. Not on elements such as buttons etc.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-20086,f436d4d7

#### Windows version:
Windows 10 1909 Update

#### Name and version of other software in use when reproducing the issue:
All commonly used browsers, newest versions.

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, the version before merging #10919 but this had not have separate reporting for subscripts and superscripts.

#### If addons are disabled, is your problem still occuring?
yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
n/a

**Comment by feerrenrut** [comment] 2020-05-01 08:32
Other than in MathML or other explicitly defined math, it could be difficult to determine "math content". I think a reasonable path forward is to only announce base line if the last text announced was superscript or subscript. Examples could help to clarify your issue description: 

**Given:**
This is a regular sentence with <sup>some superscript note</sup> followed by more text

**Expected:**
Speech: "This is a regular sentence with superscript some superscript note baseline followed by more text"

**Comment by feerrenrut** [comment] 2020-05-01 08:38
Interestingly, I can't get NVDA to recognise that "some superscript note" is actually formatted as superscript. It was written like this in the comment, and visually appears as superscript. Pressing `NVDA+F` on this text announces it as baseline.
```
This is a regular sentence with <sup>some superscript note</sup> followed by more text
```

**Comment by ultrasound1372** [comment] 2020-07-15 22:24
Glad I'm not the first to report the issue just referenced, but check there for a good example and breakdown of the behavior. Discussion should continue here though.

**Comment by CyrilleB79** [comment] 2020-12-03 00:12
@Adriani90 and @ultrasound1372, would #11897 allow to close this issue?
The issue with spurious reporting of "baseline" should be fixed but the implemented solution is not to exclude some web elements for reporting.

**Comment by CyrilleB79** [comment] 2020-12-03 20:47
Here is a link to download the [test build](https://ci.appveyor.com/api/buildjobs/mqle2nn7wkpcclu4/artifacts/output%2Fnvda_snapshot_pr11897-21450%2C1f912784.exe).

**Comment by CyrilleB79** [comment] 2021-02-04 08:48
@ultrasound1372 and @Adriani90 could you try the test build and indicate if it meets your needs? Would #11897 solve the root cause of this issue?

Note however that it may not solve the issue raised by @feerrenrut  regarding `<sup>` tags in GitHub comments described in https://github.com/nvaccess/nvda/issues/11078#issuecomment-622302159

**Comment by CyrilleB79** [comment] 2021-03-25 10:52
Ping @Adriani90, @ultrasound1372
Please provide feedback.

**Comment by ultrasound1372** [comment] 2021-03-25 20:56
@CyrilleB79 appears to work for the use case I presented in my issue.

**Comment by CyrilleB79** [comment] 2021-03-25 22:58
> @CyrilleB79 appears to work for the use case I presented in my issue.

Yes @ultrasound1372, I have made a PR that may solve this issue.
And that's why I was asking you to test the [test build](https://ci.appveyor.com/api/buildjobs/mqle2nn7wkpcclu4/artifacts/output%2Fnvda_snapshot_pr11897-21450%2C1f912784.exe) to know if the issue is fixed in this build.
Thanks.

**Comment by ultrasound1372** [comment] 2021-03-26 14:39
Yes, I was saying I tested the test build and it fixes the issue I reported.

**Comment by CyrilleB79** [comment] 2021-10-01 21:25
@Adriani90 it is a last attempt to ask you to test [this updated build](https://ci.appveyor.com/api/buildjobs/95ixodw9gx7g755i/artifacts/output%2Fnvda_snapshot_pr11897-23840%2Cffbb45e7.exe) of PR #11897.
Let me know if you consider that it resolves this issue, even if the fimplemented solution is not what you suggest in this issue.

**Comment by Adriani90** [comment] 2021-10-04 07:49
This is still reproducible in NVDA alpha-23852,df92ef66.
Especially in browse mode. I have updated the description accordingly.
Also when you move to the address bar with f6 and press ctrl+left arrow, NVDA reports "base line".

I can reproduce this issue now only in Firefox, version 92 currently.

cc: @jcsteh

**Comment by CyrilleB79** [comment] 2021-10-04 08:04
@Adriani90 my question was not to test last alpha but the build of PR #11897 (cf. my previous message). Could you give a try and see if it resolves this problem for you?

**Comment by Adriani90** [comment] 2021-10-04 08:35
Oops I was missing that one.
Testing with Version: pr11897-23840,ffbb45e7, the problem does not occur anymore. Thank you so much for your work!

Sory for the confusion, and that it took so long. I am quite busy these times and don't find much time to contribute to NVDA.

**Comment by CyrilleB79** [comment] 2021-10-04 08:44
No problem, do not worry. The PR has not been delayed because of you but because of me anyway. Thank you for your feedback.

**Closed** 2022-02-15 12:02 UTC
