### ISSUE TITLE
Two COM errors in Chrome when navigating a Gmail conversation

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#11515] opened 2020-08-21 07:48 UTC
### Steps to reproduce:

1. In Chrome, open a Gmail conversation and start arrowing down.
2. When hitting the heading for the first participant, a H3, the first error is generated.
3. When down arrowing onto the sender/recipient short details, the second error is logged.

### Actual behavior:

First error that is logged:
```
ERROR - eventHandler.executeEvent (07:40:22.088) - MainThread (3428):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x03B044B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "browseMode.pyc", line 1573, in event_gainFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1103, in _get_rowNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

Second error that gets logged:
```
ERROR - eventHandler.executeEvent (07:40:54.197) - MainThread (3428):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0EF454B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 217, in executeEvent
  File "eventHandler.pyc", line 96, in __init__
  File "eventHandler.pyc", line 105, in next
  File "browseMode.pyc", line 1573, in event_gainFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 517, in getObjectSpeech
  File "speech\__init__.pyc", line 381, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1141, in _get_columnNumber
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

### Expected behavior:

No errors.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

version alpha-20763,1ef4dfb0

#### Windows version:

10.0.2004.20041.

#### Name and version of other software in use when reproducing the issue:

Chrome version 84 stable.

#### Other information about your system:

Braille in use, no extensions like BrailleExtender present.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, 2020.2, happens there, too.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes, no change.

Does not happen in Firefox.

**Comment by feerrenrut** [comment] 2020-08-24 11:35
Potentially related to: https://github.com/nvaccess/nvda/issues/10925

**Comment by Adriani90** [comment] 2020-08-25 08:09
cc: @ObjectInSpace

**Comment by Adriani90** [comment] 2024-03-29 20:01
I acnnot reproduce with NVDA 2024.1 RC1 and Crhome 125 Canary. Closing as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-03-29 20:01 UTC
Labels: close/worksforme, app/chrome
