### ISSUE TITLE
NVDA reading the hidden HTML in IE11 browser

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5233] opened 2015-07-18 18:20 UTC
**Reported by Madhava on 2015-07-18 18:20**

'''Issue:''' NVDA reading the hidden HTML in IE 11 browser when mouseover in the area and is working fine in other browsers.

NVDA version: 2015.2
OS: Windows 7/8.1

Expected result: Ideally, when certain part of UI is hidden from the user. Should not read by Screen reader.

Any help on confirming whether this is known limitation, would be appreciated.

**Comment by ehollig** [comment] 2017-07-13 02:57
This sounds very similar to #5320

**Comment by jcsteh** [comment] 2017-07-13 03:04
Closing as duplicate of #5320, as it has a better summary and has been prioritised.

**Closed by jcsteh** 2017-07-13 03:04 UTC
Labels: bug
