### ISSUE TITLE
Wrong reading of a braille unicode Character

### ISSUE THREAD

**Issue by levilibegas** [nvaccess/nvda#15363] opened 2023-09-04 08:52 UTC
Hello, I am experimenting an issue while reading two braille unicode charadcters. the 0x2438 which contains dots 456 is wrongly read. Instead of its dots it is read as dots 123 which is the unicode braille character 0x2807. I have just seen this behaviour and I am using the last Snapshots. I am not are if it would happen before. I do not know if this has something to do with liblouis tables or rather to nvda. Thanks a lot.

**Comment by seanbudd** [comment] 2023-09-04 08:54
This is a duplicate of #15282 and will be fixed in 2023.3

**Closed by seanbudd** 2023-09-04 08:54 UTC
