### ISSUE TITLE
Firefox 56 no longer displays the page when launched

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7509] opened 2017-08-21 12:26 UTC
Firefox from 55 to 56, when it launches, it seems to be in a weird place called bookmarks panel or similar. One then has to tab several times to get to the page and hence browse mode. Sadly you are no longer taken to the edit field if its a search engine, and then you need to explore to find if its up or down from where its dunped you.
I am using the latest master branch, but some people on the user group are telling me that the old stable version works as expected on this new version. All I can tell you is that this looks to me like a firefox issue, as going back to 54, the latest download I have puts things back as they were for me in the latest master branch snap.

Perhaps some investigation is needed, and I'd really like to know what this weird panel is as all toolbars are turned off in the menus of firefox.
 I am running on windows 7 64, but its a 32 bit version of Firefox I'm running here.
 Brian

**Comment by fisher729** [comment] 2017-08-21 15:24
Hi.
On first observation, Firefox 56 is not the latest stable version. Does this mean that any issue relating to a Firefox bug can be fixed before major release? Secondly, the bookmarks panel is present in Firefox 55.0.2 if, say, I press Control+I. Could you press this shortcut to see if the page loads normally? If yes, this issue may be due to an accidental press. Thirdly, could you send steps to reproduce the bug? Which version of Windows? As a side note, the panel is accessible by using Tab or pressing Control+I to close.

**Comment by Brian1Gaff** [comment] 2017-08-22 08:12
I simply updated from 55 to 56. I did not press any key. it did it on 
opening the  program every time. I know about the i and b shortcuts here and 
avoid them, plus nothing in the menus or set up was changed.
 I am using Windows 7 pro 64, and in this case the latest master snap or the 
rc of the new version.
 I was not sure about where the cause lay since if you look at the user list 
there are people there using 55 saying that firefox  cannot be used in the 
latest RC of the new version and as yet nobody seems to have a reason for 
this since the current version works for them. I suggest you pop over there 
and have a read in case its related, given the  nearness of the new version.
 I hope if as you say the beta is fixable and it turns out to be that that 
somebody with more skill on the mozilla site than I can file a bug report.
 The most worrying part is not the wrong window in focus at launch but the 
arbitrary placement of the cursor or focus when you tab to the window. No 
not tried the i shortcut directly, as most people will not be expecting to 
have to do this.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment] 2017-08-29 14:07
As far as I know, Firefox 56 is a beta version currently.

**Comment by ehollig** [comment] 2017-11-03 18:41
@Brian1Gaff, is this still reproducible? I am currently using Firefox 56 and do not experience described behavior.

**Comment by Brian1Gaff** [comment] 2017-11-04 09:42
Yes the bugzilla feed i looked at from this said won't fix and fixed in 57, 
which obviously is rather pointless at present as 57 does not work at all 
with nvda now apart from the menu bar.The advice as I have seen it is to use 
way back to version 52, though 55 will still work if you close the bookmarks 
sidebar wotsit in 56 you can make it work sort of, at least for me anyway.

What a mess!
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by feerrenrut** [comment] 2017-11-06 11:24
Could you please link to the Bugzilla feed so that we could get more information?
Could you also try starting Firefox in a "New Private Window" and report back on what happens?

At the moment there is not enough information here to reproduce the problem. This makes it very hard to progress the issue, and uses up a lot of time while trying to "guess" what might be causing it for you. 

While trying to reproduce it with Firefox 56 on Windows 10 with NVDA next-14588,6a175cf6
1. With NVDA already running.
1. Start Firefox by pressing windows, typing firefox, and pressing enter
1. the following is announced:
```
Mozilla Firefox Start Page  document
Search query  edit  collapsed
blank
Focus mode
```
Press `NVDA+t`: NVDA announces `Mozilla Firefox Start Page - Mozilla Firefox`
Press `NVDA+Tab`: NVDA announces:
```
Search query  edit  collapsed  focused
blank
```

While trying to reproduce this with Firefox 56 on Windows 7 SP1 with NVDA- `next-14588,6a175cf6`
1. With NVDA already running.
1. Start Firefox by double clicking the desktop shortcut
1. the following is announced
```
Mozilla Firefox Start Page  document
Search query  edit  collapsed  focused
```

Do you have any other NVDA Windows open when this happens (eg the speech viewer, the update notification)?
Do you have any other Windows open more generally?
Have you tried this with all addons disabled?

**Comment by Brian1Gaff** [comment] 2017-11-06 18:14
https://bugzilla.mozilla.org/show_bug.cgi?id=1394207



I think the advice was to close it in options.
     They do not intend to fix it... grin, I now understand why with 57, 
which I tried over the weekend, Oh dear.
 Brian
bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by ehollig** [comment] 2017-11-07 02:45
Closing, as it sounds this issue will be fixed in Firefox 57

**Closed by ehollig** 2017-11-07 02:45 UTC
Labels: Firefox, needsExternalFix

**Comment by Brian1Gaff** [comment] 2017-11-07 15:20
Yes a bit bitter sweet under the circumstances though, sadly.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----
