### ISSUE TITLE
Nvda does not le the name of some groups in the start menu of windows 10

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8120] opened 2018-03-24 15:54 UTC
### Steps to reproduce:
open the windows start menu.
Navigate with the arrows below.
Note that there are some groups, with the initials of the letters of the existing programs in the start menu.
Curiously the nvda le the name of some of these groups as an example:
a
B
c
d
However do not name some of these groups as an example
o

P

### Expected behavior:
nvda should read the name of all groups.

### Actual behavior:
nvda does not name some groups, tested with several voice synthesizers, and with disabled add-ons.
Language in Portuguese Brazil

### System configuration:
NVDA version:
next 14952
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 10 16299.309
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by josephsl** [comment] 2018-03-24 15:57
Hi, I cannot reproduce this – groupings for O and P are announced. That doesn’t mean the issue can be closed so soon. Thanks.

**Comment by leonardder** [comment] 2018-03-24 15:58
Could you reproduce this with Narrator?

**Comment by josephsl** [comment] 2018-03-26 21:15
Hi, regarding Object Location Tones, which version is this? Thanks.

**Comment by fernando-jose-silva** [comment] 2018-03-26 22:21
is version 17.12a
Thank you.
I tested a new copy of nvda without any add-ons and the problem persisted.

**Comment by ehollig** [comment] 2019-04-10 01:03
@feerrenrut are all of the groups visible in the start menu? If not, this would explain why NVDA is skipping some groups

**Comment by feerrenrut** [comment] 2019-04-10 14:26
@ehollig They are visible only if you have items that start with that letter. @fernando-jose-silva Do you have any items in the start menu that begin with a letter that is a missing group. Also @fernando-jose-silva I notice in your log that there are several errors touching on add-ons. Could you repeat the test with all addons disabled?
To do this, ensure that NVDA is configured to "Show exit options when exiting NVDA" (in general settings), then press `NVDA+q` and select "restart with addons disabled"

**Comment by fernando-jose-silva** [comment] 2019-04-10 14:49
Many thanks, I no longer have this problem, everything has changed:
another machine
windows 17763.437
nvda alfa 17004

**Comment by feerrenrut** [comment] 2019-04-10 14:58
In this case, I propose we close this issue. If anyone can still reproduce it, then we will open it again.

**Closed by feerrenrut** 2019-04-10 14:58 UTC
