### ISSUE TITLE
Google Chrome 117 Crashes When the New Custom Field Dialog of Object Manager in Salesforce Closes While NVDA is Running

### ISSUE THREAD

**Issue by sasikrishna** [nvaccess/nvda#15603] opened 2023-10-11 08:31 UTC
### Issue Summary:
When closing Salesforce dialogs, such as the New Custom Field dialog of Object Manager, while Google Chrome 117 is being used with the NVDA 2023.2 screen reader running, the browser completely closes. This issue is being reported in other scenarios, such as accessing reports on Experience Cloud sites, but this is the only issue we have been able to reproduce thus far.

### Steps to reproduce:
1. Sign up for Salesforce Developer Edition org - https://developer.salesforce.com/signup

2. Log in to Salesforce org using the latest version of the Google Chrome 117 browser.

3. Select Setup.

4. Select Object Manager.

5. Select Account.

6. Select Fields & Relationships.

7. Make sure the NVDA 2023.2 screen reader is running and speech is being heard.

8. Tab to and press enter on New Custom Field.

9. Tab to and press enter on the Cancel button. Observe that Google Chrome closes immediately.

### Actual behavior:
Google Chrome completely closes when Cancel is pressed in the New Custom Field dialog.

### Expected behavior:
Google Chrome should not close. As the issue has been triggered by a Chrome update, we should probably log a 3rd-party bug against Chrome.

#### NVDA version: 
2023.2

#### Name and version of other software in use when reproducing the issue: 
Google Chrome 117 & Salesforce 

#### Does the issue still occur after restarting your computer?
Yes

**Comment by Adriani90** [comment] 2023-10-11 08:34
Is this also reproducible in Google Chrome 118?

**Comment by seanbudd** [comment] 2023-10-11 09:51
Can you also test with chrome canary 119 - it fixes known crash

**Comment by Adriani90** [comment] 2023-10-15 18:39
This seems fixed in Chrome and Edge 118. I am closing as works for me. If you are still having this issue please provide the information requested and comment on it and we can reopen.

**Closed by Adriani90** 2023-10-15 18:39 UTC
Labels: close/worksforme
