### ISSUE TITLE
Automatic reading of window title when navigating shortcuts in windows toolbars

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9455] opened 2019-04-04 17:11 UTC
### Steps to reproduce:
Press
windows + alt + numbers from 1 to 9.
Each time you walk through an item windows displays the shortcuts on the items in the taskbar.
For example on my machine in the current section.
windows + alt + 1 shows the shortcuts to microsoft hedge.
now press windows + alt + 2 on my machine windows now displayed shortcuts to outlook.
When we press windows + alt + numbers and navigate with the arrows it is not possible to find out which program the displayed shortcuts correspond to, except by deduction.
More if you read the title of the window with nvda + t or nvda read correctly which application matches the shortcuts.
My suggestion is if for each item displayed when walking with windows + alt + numbers, nvda announces the title of the window automatically, so the user would know faster without needing to press another keystroke to which application the shortcuts is related.

### Actual behavior:
when pressing windows + alt + numbers the nvda read taskbar.
### Expected behavior:
when pressing windows + alt + numbers the nvda could inform the title of the window + taskbar.
for example:
microsoft hedge taskbar
outlook taskbar.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 17004
#### Windows version:
10 17763.379
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2019-04-04 21:26
@fernando-jose-silva I am testing with NVDA Version: alpha-16982,01118965 and the title is recognized automatically. Did you enable object descriptions in NVDA's object presentation settings?

**Comment by Adriani90** [comment] 2019-04-04 21:28
I know from other issues that you use the addon global plugin extensions from @paulber007. Unfortunately it seem this addon produces some conglicts in last versions of NVDA. So please, if you don't mind, try to reproduce your problems after disabling that addon.

**Comment by fernando-jose-silva** [comment] 2019-04-05 00:37
Thank you very much.
The machine with problems is my machine.
To my surprise and happiness on my personal machine everything works fine.
There is some configuration of windows or nvda conflicting.
You can close the call, I'll investigate on my account because it's not a general problem of nvda.

**Comment by paulber007** [comment] 2019-04-05 06:10
Hello,
being the author of the addon cited, I am very interested to know the 
possible inconveniences produced by the addon.
Can you tell me describe them to you in private.
Thank you.

Paul.

**Comment by Adriani90** [comment] 2019-04-05 11:38
Hey Paul, thanks very much for commenting! As of now we are not sure where all conflicts occure and if this is something only caused by this addon. But some users Report different conflicts in MS Word for example, where expanding Combo boxes in browse mode with alt+down arrow etc. is not working properly. Table Navigation and and paragraph Navigation in MS Word are also affected when using the addon. I.e. it seems in certain cases that People cannot move out of a table with ctrl+down arrow wehn using the addon.
Thus, for providing objective testing results, People should generally disable addons. I named your addon only because I got some reports from users which could solve their issues in MS Word after disabling the addon. I will write you an email with some sumarized Feedback from users as soon as I have a more broad Picture about different conflicts and wether they are really causesd by global plugin extensions or not.

Maybe issue #8783 is also of interest for you, see i.e. the last log file.

**Comment by paulber19** [comment] 2019-04-05 14:15
Thank you Adriani for your response.
It is a shame, because to this day, I have not been aware of the issues 
that you me entionnez.
This means that there are not so frequent as this, and the addon is not 
necessarily likely to be the cause of any malfunction of NVDA.
I'm going to try to reproduce the case you have described to detect 
potential problems with the addon and waits for the other cases.
However, it would be better to avoid focus on such or such an addon as 
the problem is not clearly identified.
In the log, we also find:
Could not execute function event_becomeNavigatorObject defined in 
globalPlugins.objloc module; kwargs: {'isFocus': True}
So the error is reported to the globalPlugin objloc .
Best regards.
Paul.

**Comment by Adriani90** [comment] 2019-04-05 14:55
Hey Paul, I am sorry I did not intend to offend you or the addon. But for me it is easier to conclude if something is caused by an addon if I advice an user to disable a certain addon. Given the fact that I got those reports from users and that I saw the related functions of the addon impacting input in the issue referenced above, I concluded that it might cause a conflict and that's why NVDA does not speak. But let's discuss on that issue further. It is not a negative thing if someone focuses on one addon. it is just an attempt to find what could cause an issue.

As of now, I am closing this one as works for me since Fernando reported that it seems to be a problem with his personal machine.

**Closed by Adriani90** 2019-04-05 14:55 UTC
Labels: worksforme
