### ISSUE TITLE
NVDARC1 doesn't respond with microsoft word

### ISSUE THREAD

**Issue by fatmamehanna** [nvaccess/nvda#6030] opened 2016-06-02 08:26 UTC
hi all,
sorry for the delay of this issue, but this issue happened when the arabic community started to use nvda rc12016.2 with microsoft word.
steps to reproduce:
1 open a word file consists of several pages.
try to modify somethings in it.
results:
NVDA stopped to respond when you want to close the program and you will be forced to close word from the task manager and all the info you wrote would be lost.
this problem happen with office2010/2013 with windows 10 in most cases.
here is a log file to show the problem.

[error when opening microsoft word.txt](https://github.com/nvaccess/nvda/files/295170/error.when.opening.microsoft.word.txt)
thanks.

**Comment by mohdshara** [comment] 2016-06-02 16:57
Hi.

according to the comments on this post, on an Arabic Community website, the issue is solved with 2016.2 final. 
https://www.blindtec.net/node/2646

I have also tested this myself with windows 10 64 bit and office 2013 and I can't reproduce it. Can you please retest with the final version and see if this is solved for you?

**Comment by fatmamehanna** [comment] 2016-06-02 20:42
yes, it has been solved.
thanks.

**Comment by jcsteh** [comment] 2016-06-02 23:44
It's worth noting that there's no code difference between 2016.2rc1 and 2016.2 final. Are these users perhaps running Windows 10 Insider builds? Our feeling (but we aren't certain) is that this might be caused by a recent Insider build.

**Comment by fatmamehanna** [comment] 2016-06-03 20:34
hi,
the users say that this problem also happens with windows 8.1 and also with microsoft outlook 2010

**Comment by mohdshara** [comment] 2016-06-04 07:21
Hi.

those users were talking about RC still. they say it's fixed with 2016.2 final. 

on a different thought, might this have been caused by a windows update which was later fixed or pulled out?

@fatmamehanna I suggest that you close this since you and I can't reproduce.

**Comment by mohammad-suliman** [comment] 2016-06-04 22:54
Hello,, not reproducible also with win 7 and ms word 2010 so far

**Comment by jcsteh** [comment] 2016-06-23 19:53
Duplicate of #5954 (fixed in NVDA 2016.2.1).

**Closed by jcsteh** 2016-06-23 19:53 UTC
Labels: duplicate
