### ISSUE TITLE
Braille cursor routing is unreliable in textareas in Chrom/Edge

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#13545] opened 2022-03-27 19:48 UTC
### Steps to reproduce:
1. Open the following data URL in Edge or Chrome:

`data:text/html,<textarea>foobarfoobarfoobarbazasdfasdfasdf%0Aasdfasdfasdf</textarea>`

2. Go to the end of the textarea, press enter to create a new line and type a few characters
3. Use braille cursor routing to move the cursor somewhere in the new line of text

Please note, this issues is also being discussed in the comments of #12010
### Actual behavior:
The cursor is placed on the requested position, but on the first line of the textarea instead of the last line. Please note that cursor routing works fine in the lines that were already in the textarea on page load.
### Expected behavior:
Cursor should land on the requested position in the last line.
#### NVDA installed/portable/running from source:
Tested installed, portable and running from source
#### NVDA version:
alpha-25094,307c8902
#### Windows version:
Windows 11 21H2
#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 99.0.1150.52 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes

* 2019.3.1: Bug is present
* 2018.2.1: bug is present, but braille is somewhat unreliable in modern Chrome/Edge textareas in this version

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by bramd** [comment] 2022-03-27 19:52
CC @MarcoZehe

**Comment by MarcoZehe** [comment] 2022-03-27 20:03
Definitely confirmed. And not seeing the problem with JAWS 2022.

**Comment by leonardder** [comment] 2022-03-28 08:45
Interesting enough, I can also reproduce this when UIA is enabled for Edge. Also note that braille is really unreliable in that case as well.

**Comment by cary-rowen** [comment] 2022-03-28 12:24
cc @michaelDCurran @seanbudd 

Yes, sometimes using cursor routing in ms word will open the system menu incorrectly, this needs to be fixed.

Thanks

**Comment by SaschaCowley** [comment] 2024-07-18 01:20
I am unable to reproduce this. @bramd, @MarcoZehe, @LeonarddeR, @cary-rowen, are you still experiencing this issue?

**Comment by SaschaCowley** [comment] 2024-07-18 01:21
(Possibly fixed via #12208)

**Comment by LeonarddeR** [comment] 2024-08-02 10:23
I can also no longer reproduce this. Closing as works for me.

**Closed by LeonarddeR** 2024-08-02 10:23 UTC
Labels: component/braille, p3, app/chrome, app/edge/anaheim, triaged
