### ISSUE TITLE
NVDA is almost unresponsive in ABBYY programs (tested in Abbyy FineReader 11 and 12)

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#5693] opened 2016-01-20 19:16 UTC
Steps to reproduce a problem:
- start NVDA
- open FineReader
- Try to scan some pages (2 or 3 is enough)
- try to recognise them

This might be NVDA's bug, because FineReader works correctly with other screen readers.

Anyway, thanks for good job.

regards, Jožef

**Comment by leonardder** [comment] 2016-01-20 19:20
I can confirm that NVDA is quite sluggish in navigating the finereader menu bar.

**Comment by jcsteh** [comment] 2016-01-20 22:51
I'm not sure I understand the issue. When Finereader is recognising a 
page, it is obviously quite busy and only really displays a progress 
dialog. Because it is busy, the UI isn't overly responsive. Please be 
more specific about exactly what works better in other screen readers.

**Comment by gregjozk** [comment] 2016-01-21 03:53
Hi,

I know, that during proces of recognising FR is busy. It is not a problem. Problem exist, when proces of scanning is finished or when pdf or other image files are loaded into document. At that situation NVDA becomes slow and it means, that you cannot read toolbars and menubar, so you cannot perform advanced operations on images because NVDA does not give information where is focus or focus loses. And it means that proces of recognising cannot be started via menubar.

When reading of document is finished, I cannot save or send results because I cannot click an approppriate choice. NVDA can read first 4 or 5 items, then it stops.

If you can reproduce a problem, than I think that it will be clear what I'm talking about.

specifications:
- win7 32-bit
- NVDA next branch

I hope that I provided enough information to clear situation.

**Comment by ruifontes** [comment] 2016-01-21 12:39
I am using Windows 10, Fine Reader 11, last Next version of NVDA, and in 
Fine Reader NVDA is a litle slow, but possible of working...
I have tried opening a PDF document with 186 pages... and my machine is only 
a Quad Core 2.1GHz already in turbo boost...

Rui


-----Mensagem Original----- 
De: gregjozk
Data: quinta-feira, 21 de janeiro de 2016 03:53
Para: nvaccess/nvda
Assunto: Re: [nvda] NVDA is almost unresponsive in ABBYY programs (tested in 
Abbyy FineReader 11 and 12) (#5693)



Hi,

I know, that during proces of recognising FR is busy. It is not a problem. 
Problem exist, when proces of scanning is finished or when pdf or other 
image files are loaded into document. At that situation NVDA becomes slow 
and it means, that you cannot read toolbars and menubar, so you cannot 
perform advanced operations on images because NVDA does not give information 
where is focus or focus loses. And it means that proces of recognising 
cannot be started via menubar.

When reading of document is finished, I cannot save or send results because 
I cannot click an approppriate choice. NVDA can read first 4 or 5 items, 
then it stops.

If you can reproduce a problem, than I think that it will be clear what I'm 
talking about.

specifications:

win7 32-bit
NVDA next branch

I hope that I provided enough information to clear situation.

-

**Comment by fernando-jose-silva** [comment] 2016-01-21 13:29
Good morning, I would just also report to deal with this problem, after scanning a document in fine reader 12 on windows 10, it is impossible to navigate the menus, NVDA is extremely slow.

**Comment by jcsteh** [comment] 2016-01-21 22:18
Unfortunately, I only own FineReader 8, so I have no way of testing 
this. A log file with level set to debug might help, but please give 
some indication of what keys and messages to look for where the lag 
starts to occur. Preferably, the interfaces should be set to English so 
we can see what is going on.

**Comment by fernando-jose-silva** [comment] 2016-01-22 18:22
Good afternoon dear.
 Reproduce the problem in ABBYY FineReader.
 1 open the reader
 2 press alt and down to the option open PDF and image files.
 3 Choose the file and wait for the end of the reader for document processing.
 4 hit enter on completed processing message.
 5 now the first mistake, NVDA reports just fine reader, pressing any keys like alt or arrows is not told anything.
 6 To continue testing and display the main problem, switch to another software windows with alt + tabe and return to the reader window with alt + tabe again.
 7 now take place the main problem, press alt and walk with arrows below.
 It is expected that the reader read the menus and what happens is that NVDA does not read anything.
 Thanks to disposal.
[reader nvda.log.txt](https://github.com/nvaccess/nvda/files/101227/reader.nvda.log.txt)

**Comment by dreinn** [comment] 2016-02-03 08:45
I answer here just to give you a little solution, but this is only a sort of trick.
When you have finished the process of scanning and recognizing, NVDA goes into a "unknown window". You can't use keyboard on this situation.
But, press windows-d for going on desktop, then press alt-tab.
For some strange reason, now NVDA reads the window of Finereader!
At least you can press alt and activate menu.
Obviously, you can't read recognized text, that window is inaccessible also with Jaws.
Hope it helps.

**Comment by fernando-jose-silva** [comment] 2016-02-03 12:50
Thank you so much.

After returning to the reader window with alt + tabe , and press alt to navigate the menus with the arrow keys, in my case NVDA is extremely slow.

 

De: dreinn [mailto:notifications@github.com] 
Enviada em: quarta-feira, 3 de fevereiro de 2016 06:46
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>
Assunto: Re: [nvda] NVDA is almost unresponsive in ABBYY programs (tested in Abbyy FineReader 11 and 12) (#5693)

 

I answer here just to give you a little solution, but this is only a sort of trick.
When you have finished the process of scanning and recognizing, NVDA goes into a "unknown window". You can't use keyboard on this situation.
But, press windows-d for going on desktop, then press alt-tab.
For some strange reason, now NVDA reads the window of Finereader!
At least you can press alt and activate menu.
Obviously, you can't read recognized text, that window is inaccessible also with Jaws.
Hope it helps.

**Comment by gregjozk** [comment] 2016-02-05 03:11
attached a log.

at first look I see that there is problem with IAccessible2 if I have read a log correctly. 
[nvda.zip](https://github.com/nvaccess/nvda/files/118577/nvda.zip)

**Comment by cannona** [comment] 2016-03-01 21:24
There is a free demo version of ABBYY Finereader available, which should be sufficient to reproduce the problem, if necessary.

https://www.abbyy.com/finereader/professional/trial/

**Comment by vortex1024** [comment] 2017-06-15 17:36
I'm attaching a log at debug level. It's not too big, the issue should be easy to find.
The slow response is not the worst issue. The thing is that NVDA doesn't read submenus. Jaws and even 
narrator do read them, and don't have slow response either.
[nvda.log.txt](https://github.com/nvaccess/nvda/files/1078455/nvda.log.txt)

**Comment by jcsteh** [comment] 2017-08-07 22:16
Thoughts based on these logs:

1. It seems that watchdog is cancelling too early; i.e. `_shouldRecoverAfterMinTimeout` is returning True when it shouldn't. I'm not sure why this is, but that is probably why certain things don't get read at all; the calls get cancelled by watchdog before the information can be retrieved. That doesn't explain why it's so slow, though.
2. A lot of these freezes seem to occur in QueryService. That suggests the app is doing something pretty broken, but it'd explain why Narrator isn't affected; it uses UIA and wouldn't be making any QueryService calls. JAWS possibly only does QueryService for very specific window classes. We can probably QueryService for MSHTML only for specific window classes, but we can't really do this for IAccessible2 or windowless RichEdit, as we really want those to work everywhere. Maybe we can have some window classes which are blacklisted, though?

For those experiencing this, it'd be interesting if you could try with watchdog disabled. Note that this may result in significant freezes and NVDA maynot be able to recover, so please be aware that you mayhave to force restart NVDA if this breaks. To do this:

1. Open the NVDA Python Console by pressing NVDA+control+z.
2. Paste the following command, then press enter: `import watchdog; watchdog.terminate()`

Does this make things better or worse? At a guess, I'd say the sub-menus will now read, but things might be sluggish.

**Comment by jcsteh** [comment] 2017-08-07 22:17
While I don't believe this is our bug, Abbyy Finereader is probably an important app used by quite a few screen reader users, so p2 to at least investigate further.

**Comment by fernando-jose-silva** [comment] 2017-08-07 23:57
Perfect, it worked.

Follow the new log.

Please now how do i to nvda voutar the default settings after typing in the piton what you asked for.

It was the first time I entered the python console.

Thank you very much.

 

IO - inputCore.InputManager.executeGesture (20:55:20.486):

Input: kb(laptop):downArrow

IO - speech.speak (20:55:21.367):

Speaking [u'Digitalizar p\xe1ginas...\tCtrl+K  D  3 de 20']

IO - inputCore.InputManager.executeGesture (20:55:25.894):

Input: kb(laptop):NVDA+f1

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (20:55:26.844):

Developer info for navigator object:

name: u'Digitalizar p\xe1ginas...\tCtrl+K'

role: ROLE_MENUITEM

states: STATE_FOCUSED

isFocusable: False

hasFocus: True

Python object: <NVDAObjects.IAccessible.MenuItem object at 0x0AB80710>

Python class mro: (<class 'NVDAObjects.IAccessible.MenuItem'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)

description: None

location: None

value: None

appModule: <'appModuleHandler' (appName u'finereader', process ID 13188) at address ae74df0>

appModule.productName: u'ABBYY FineReader'

appModule.productVersion: u'12.0.101.483'

TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>

windowHandle: 592568

windowClassName: u'AWL:2EE50000:8b:10003:0:0:0'

windowControlID: 0

windowStyle: 1442840576

windowThreadID: 16476

windowText: u'MenuWindow'

displayText: exception: 'NoneType' object is not iterable

IAccessibleObject: <POINTER(IAccessible) ptr=0x9af2260 at 5832530>

IAccessibleChildID: 3

IAccessible event parameters: windowHandle=592568, objectID=-4, childID=3

IAccessible accName: u'Digitalizar p\xe1ginas...\tCtrl+K'

IAccessible accRole: ROLE_SYSTEM_MENUITEM

IAccessible accState: STATE_SYSTEM_HOTTRACKED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_VALID (132)

IAccessible accDescription: None

IAccessible accValue: None

 

 

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: segunda-feira, 7 de agosto de 2017 19:17
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [nvaccess/nvda] NVDA is almost unresponsive in ABBYY programs (tested in Abbyy FineReader 11 and 12) (#5693)

 

Thoughts based on these logs:

1.	It seems that watchdog is cancelling too early; i.e. _shouldRecoverAfterMinTimeout is returning True when it shouldn't. I'm not sure why this is, but that is probably why certain things don't get read at all; the calls get cancelled by watchdog before the information can be retrieved. That doesn't explain why it's so slow, though.
2.	A lot of these freezes seem to occur in QueryService. That suggests the app is doing something pretty broken, but it'd explain why Narrator isn't affected; it uses UIA and wouldn't be making any QueryService calls. JAWS possibly only does QueryService for very specific window classes. We can probably QueryService for MSHTML only for specific window classes, but we can't really do this for IAccessible2 or windowless RichEdit, as we really want those to work everywhere. Maybe we can have some window classes which are blacklisted, though?

For those experiencing this, it'd be interesting if you could try with watchdog disabled. Note that this may result in significant freezes and NVDA maynot be able to recover, so please be aware that you mayhave to force restart NVDA if this breaks. To do this:

1.	Open the NVDA Python Console by pressing NVDA+control+z.
2.	Paste the following command, then press enter: import watchdog; watchdog.terminate()

Does this make things better or worse? At a guess, I'd say the sub-menus will now read, but things might be sluggish.

**Comment by jcsteh** [comment] 2017-08-08 00:09
From what I can see, there's still a second or so of lag before it reports each menu item. Is that correct? Do you experience the same lag with Narrator?

There's no way to make this the default, nor would this be a good idea. If a window stops responding, NVDA will simply stop responding altogether; it won't recover when you switch to another application or the like. I just wanted to check whether my diagnosis was at least partially correct.

**Comment by fernando-jose-silva** [comment] 2017-08-08 00:29
Thank you very much, I did the tests with the narrator, and he did not present the time of 1 second to navigate.

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: segunda-feira, 7 de agosto de 2017 21:09
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Comment <comment@noreply.github.com>
Assunto: Re: [nvaccess/nvda] NVDA is almost unresponsive in ABBYY programs (tested in Abbyy FineReader 11 and 12) (#5693)

 

From what I can see, there's still a second or so of lag before it reports each menu item. Is that correct? Do you experience the same lag with Narrator?

There's no way to make this the default, nor would this be a good idea. If a window stops responding, NVDA will simply stop responding altogether; it won't recover when you switch to another application or the like. I just wanted to check whether my diagnosis was at least partially correct.

**Comment by vortex1024** [comment] 2017-08-08 22:40
Correct, NVDA still has that 1 second delay with the watchdog disabled, while narrator doesn't. Thanks much for looking into this. Let us know how we can help further.

**Comment by tspivey** [comment] 2017-08-09 00:21
@fernando-jose-silva
You can re-enable the watchdog by restarting NVDA.

**Comment by fernando-jose-silva** [comment] 2017-08-09 21:42
thank you so much

**Comment by bhavyashah** [comment] 2017-09-04 05:41
Just to clarify, is the reported sluggishness specific to ABBYY Fine Reader 11/12 (as it seems from the ticket title), or have we been successful in reproducing the same with ABBYY Fine Reader version 14, the latest stable release of this program as well?

**Comment by gregjozk** [comment] 2017-09-04 05:53
Hi,

in Finereader 14 as I saw the GUI was completely redesigned but I
don't tested the performance during a scan process, so I cannot say if
this is true for FR 14.

2017-09-04 7:41 GMT+02.00, bhavyashah <notifications@github.com>:

**Comment by bhavyashah** [comment] 2017-09-04 07:52
@gregjozk  Please do test this with ABBYY Fine Reader 14 as and when time permits, particularly since you say that the GUI has been redesigned, which means that there is a substantial chance that this sluggishness might have been resolved in the same.

**Comment by lukaszgo1** [comment] 2018-12-17 14:30
Any updates on this? I can confirm that the problem is still present on Windows 7 with ABBYY FineReader 12 pro. FineReader is widely used OCR software ad least in Poland, and this problem makes working with NVDA in it not optimal to say it politely. I can also confirm, that disabling watchdog makes submenus accessible, but there is still a lag which isn't present with JAWS. cc @leonardder As you was able to reproduce the issue.

**Comment by Adriani90** [comment] 2018-12-17 14:54
This is also reproducible in Finereader 14 on Windows 8.1 and Windows 10. But as far as I can see only the menu bar is sluggish. That means when pressing alt to Access the menu bar and use arrow key to navigate through the menus, NVDA becomes very very slow. In all other cases NVDA is very responsive.

**Comment by zstanecic** [comment] 2018-12-17 15:05
Abbyy finereader has 64 bit support. 

Is it a fraction of a second or what?

**Comment by leonardder** [comment] 2018-12-17 15:05
As this is not reproducible with other screen readers, we might just write an appModule that enforces UIA within the menu bar by treating them as good UIA windows. Sounds like a good for new dev.

**Comment by lukaszgo1** [comment] 2018-12-17 15:35
@leonardder Are you certain, that Menu bar can be accessed using UIA on Windows 7? I've created an appModule, but when accessing menu the error sound is played, and the following is written in the log:
ERROR - core.CorePump.run (16:29:55.342):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 486, in run
  File "IAccessibleHandler.pyc", line 900, in pumpAll
  File "IAccessibleHandler.pyc", line 671, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 687, in processFocusNVDAEvent
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 666, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1090, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 756, in _prefetchUIACacheForPropertyIDs
AttributeError: 'Dynamic_testMenuItemIAccessible' object has no attribute 'UIAElement'

So either I've done something wrong which is very possible,  or Windows 7 is to old for this.

**Comment by josephsl** [comment] 2018-12-17 15:37
Hi, MSAA objects do not expose UIA element property at all (unless bridged). In order to look at IA element object, one needs to subclass NVDAObjects.UIA.UIA. Thanks.

**Comment by lukaszgo1** [comment] 2018-12-17 15:41
@josephsl wrote:
> 
> Hi, MSAA objects do not expose UIA element property at all (unless bridged). In order to look at IA element object, one needs to subclass NVDAObjects.UIA.UIA.

Any examples of something like that in the code?

**Comment by josephsl** [comment] 2018-12-17 15:42
Hi, so many of them – NVDAObjects/UIA/__init__.py, Microsoft Edge content process (appModules/microsoftedgecp.py), Windows 10 App Essentials and others. Thanks.

**Comment by leonardder** [comment] 2018-12-17 15:46
I'd do something like this:

1. Find the window class name of the menu bar and its descendants, it might be the same for the menu as a whole.
2. Create a simple app module that defines `isGoodUIAWindow(self, hwnd)`. It should return True `if winUser.getClassName(hwnd) == theClass`, otherwise, it should return False.

No subclassing of NVDAObjects.UIA.UIA should be necessary at all.

**Comment by leonardder** [comment] 2018-12-17 18:46
I fired up a copy of version 11 which I still had sitting around. Using UIA for the menu bar or for the whole application did improve slightly, but it is still not very fast.
[finereader.zip](https://github.com/nvaccess/nvda/files/2687432/finereader.zip)

**Comment by jcsteh** [comment] 2018-12-18 01:06
> I fired up a copy of version 11 which I still had sitting around. Using UIA for the menu bar or for the whole application did improve slightly, but it is still not very fast.

@leonardder, how does the speed with NVDA + UIA compare to Narrator? I really don't understand why it should be faster with Narrator than it is with NVDA + UIA, since in that case, NVDA isn't making any QueryService calls.

@lukaszgo1 It'd be good to see a log with UIA where sub-menus won't read so we can see the new point where things freeze. In addition, I'd like to see the dev info (NVDA+f1) for a menu item which is slow but does read.

**Comment by leonardder** [comment] 2018-12-18 07:00
> @leonardder, how does the speed with NVDA + UIA compare to Narrator? I really don't understand why it should be faster with Narrator than it is with NVDA + UIA, since in that case, NVDA isn't making any QueryService calls.

Normally, NVDA is faster than Narrator, for example when I'm arrowing on the desktop. With NVDA+UIA, speed is almost equal, i.e. where NVDA is noticeably slower, Narrator doesn't seem to be slower than normal.
Note however that FineReader 11, although slower, is still usable. I've seen version 12 as well though, and that was noticeably slower than 11.

**Comment by Adriani90** [comment] 2018-12-18 07:46
here is a part of log file while navigating through the menu:

```
IO - inputCore.InputManager.executeGesture (08:43:29.566):
Input: kb(laptop):rightArrow
DEBUGWARNING - watchdog._watcher (08:43:30.269):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 203, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 444, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "eventHandler.pyo", line 61, in _queueEventCallback
  File "eventHandler.pyo", line 138, in executeEvent
  File "eventHandler.pyo", line 151, in doPreGainFocus
  File "api.pyo", line 107, in setFocusObject
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 495, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 918, in _get_parent
  File "NVDAObjects\__init__.pyo", line 71, in __call__
  File "NVDAObjects\IAccessible\__init__.pyo", line 608, in __init__
  File "comtypes\__init__.pyo", line 1078, in QueryInterface

IO - speech.speak (08:43:30.457):
Speaking [LangChangeCommand (u'de'), u'Senden an  Men\xfc']
IO - inputCore.InputManager.executeGesture (08:43:30.723):
Input: kb(laptop):downArrow
IO - speech.speak (08:43:30.848):
Speaking [LangChangeCommand (u'de'), u'PDF-Editor...  1 von 8']
IO - speech.speak (08:43:31.286):
Speaking [LangChangeCommand (u'de'), u'Microsoft Word  3 von 8']
IO - inputCore.InputManager.executeGesture (08:43:31.911):
Input: kb(laptop):rightArrow
DEBUGWARNING - watchdog._watcher (08:43:32.660):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 203, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 444, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "eventHandler.pyo", line 61, in _queueEventCallback
  File "eventHandler.pyo", line 138, in executeEvent
  File "eventHandler.pyo", line 151, in doPreGainFocus
  File "api.pyo", line 107, in setFocusObject
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 495, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 922, in _get_parent
  File "NVDAObjects\__init__.pyo", line 61, in __call__
  File "NVDAObjects\__init__.pyo", line 196, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 102, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 321, in isUIAWindow
  File "_UIAHandler.pyo", line 315, in _isUIAWindowHelper

IO - speech.speak (08:43:32.691):
Speaking [LangChangeCommand (u'de'), u'Unbenanntes Projekt [1] - ABBYY FineReader 14 OCR-Editor']
IO - inputCore.InputManager.executeGesture (08:43:32.973):
Input: kb(laptop):upArrow
IO - speech.speak (08:43:33.035):
Speaking [LangChangeCommand (u'de'), u'Bearbeiten  Untermen\xfc  2 von 7']
IO - inputCore.InputManager.executeGesture (08:43:33.457):
Input: kb(laptop):upArrow
IO - speech.speak (08:43:33.878):
Speaking [LangChangeCommand (u'de'), u'Symbol einf\xfcgen...  Nicht verf\xfcgbar  28 von 28']
IO - inputCore.InputManager.executeGesture (08:43:34.051):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (08:43:34.332):
Input: kb(laptop):upArrow
DEBUGWARNING - watchdog._watcher (08:43:34.378):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 203, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 897, in pumpAll
  File "IAccessibleHandler.pyo", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 684, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 637, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 916, in _get_parent
  File "IAccessibleHandler.pyo", line 433, in accParent
  File "IAccessibleHandler.pyo", line 327, in normalizeIAccessible
  File "comtypes\__init__.pyo", line 1111, in QueryService

DEBUGWARNING - core.CorePump.Notify (08:43:34.457):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 897, in pumpAll
  File "IAccessibleHandler.pyo", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 684, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 637, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 918, in _get_parent
  File "NVDAObjects\__init__.pyo", line 71, in __call__
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (08:43:34.582):
Input: kb(laptop):upArrow
DEBUGWARNING - watchdog._watcher (08:43:34.957):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 203, in <module>
  File "core.pyo", line 473, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 897, in pumpAll
  File "IAccessibleHandler.pyo", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 684, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 637, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 916, in _get_parent
  File "IAccessibleHandler.pyo", line 431, in accParent
  File "comtypes\client\__init__.pyo", line 44, in wrap_outparam
  File "comtypesMonkeyPatches.pyo", line 54, in newCpbDel
  File "comtypes\__init__.pyo", line 841, in __del__
  File "comtypes\__init__.pyo", line 1092, in Release

DEBUGWARNING - core.CorePump.Notify (08:43:35.019):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyo", line 443, in Notify
  File "IAccessibleHandler.pyo", line 897, in pumpAll
  File "IAccessibleHandler.pyo", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 684, in processFocusNVDAEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 637, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 918, in _get_parent
  File "NVDAObjects\__init__.pyo", line 71, in __call__
  File "watchdog.pyo", line 202, in _COMError_init
CallCancelled
IO - speech.speak (08:43:35.410):
Speaking [LangChangeCommand (u'de'), u'Seitenbilder bearbeiten...\tStrg+I  23 von 28']
IO - inputCore.InputManager.executeGesture (08:43:36.035):
Input: kb(laptop):upArrow
IO - speech.speak (08:43:36.410):
Speaking [LangChangeCommand (u'de'), u'Seite aufteilen...  22 von 28']
IO - inputCore.InputManager.executeGesture (08:43:37.628):
Input: kb(laptop):NVDA+f1
```

**Comment by Adriani90** [comment] 2018-12-18 07:46
And here is the developer info for a menu item which is being read but NVDA is very slow:

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (08:43:37.908):
Developer info for navigator object:
name: u'Seite aufteilen...'
role: ROLE_MENUITEM
states: STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.IAccessible.MenuItem object at 0x05450E90>
Python class mro: (<class 'NVDAObjects.IAccessible.MenuItem'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (48, 548, 302, 30)
value: None
appModule: <'appModuleHandler' (appName u'finereaderocr', process ID 3536) at address 554ffb0>
appModule.productName: u'ABBYY FineReader'
appModule.productVersion: u'14.0.101.624'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 264632
windowClassName: u'AWL:562E0000:8b:10007:0:0:0'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 1916
windowText: u'MenuWindow'
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x813ab08 at 5542bc0>
IAccessibleChildID: 22
IAccessible event parameters: windowHandle=264632, objectID=-4, childID=22
IAccessible accName: u'Seite aufteilen...'
IAccessible accRole: ROLE_SYSTEM_MENUITEM
IAccessible accState: STATE_SYSTEM_HOTTRACKED, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_VALID (132)
IAccessible accDescription: None
IAccessible accValue: None
```

**Comment by Adriani90** [comment] 2018-12-18 07:47
This is from ABBYY Finereader 14 and Windows 8.1. The same is Happening on Windows 10.

**Comment by lukaszgo1** [comment] 2018-12-18 17:09
@jcsteh wrote"
> @lukaszgo1 It'd be good to see a log with UIA where sub-menus won't read so we can see the new point where things freeze. In addition, I'd like to see the dev info (NVDA+f1) for a menu item which is slow but does read.


By Sub menus are no longer reported I meant, that if the certain menu item has sub menu and isGoodUIAWindow is set to true the fact that sub menu exists isn't reported.

**Comment by lukaszgo1** [comment] 2019-09-16 17:22
Someone asked  about it on NVDA Users list today. Is there any chance of a fix for this? I don't know how it is in English speaking countries but here in Poland it is almost only commonly used OCR solution.

**Comment by Adriani90** [comment] 2020-01-13 16:40
This seems to be also the case in ABBYY finereader 15.

**Comment by Adriani90** [comment] 2023-03-27 23:08
This has greatly improved now with NVDA last Alpha and ABBYY Finereader 16. no noticeable difference to software that works very fluently. I am closing this one for now but feel free to comment in case you still have serious performance issues with ABBYY Finereader 16 and NVDA.

**Closed by Adriani90** 2023-03-27 23:08 UTC
Labels: app-specific, p2
