### ISSUE TITLE
Moving an object over an image with no alt-text breaks in powerpoint

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6644] opened 2016-12-15 05:00 UTC
1. open powerpoint. create a slide, put test in the title.
2. take a screen shot by pressing print screen.
3. paste it into powerpoint on the slide you are on.
4. Go to the title, and move it. 

* Expected:
    "behind left of unlabelled Image by 926 points, behind top of unlabelled image by 151 points, behind right of unlabelled image by 926 points, behind bottom of unlabelled image by 529 points, 28.8 points from top slide edge, 407 points from bottom slide edge"
* Actual:
    Something like 
    "behind left of None by 926 points, behind top of None by 151 points, behind right of None by 926 points, behind bottom of None by 529 points, 28.8 points from top slide edge, 407 points from bottom slide edge"

Now. 

1.tab to and right click the image. 
2. select formatting, go to size and properties.
   (Press f6 after the right click to get there, ms doesn't focus that).
3. expand alt text if it isn't already.
4. Type screen shot in the title.
5. Move the title again.

This time you get 

behind left of Screen shbehind left of Screen shot by 926 points, behind top of Screen shot by 153 points, behind right of Screen shot by 926 points, behind bottom of Screen shot by 527 points, 30.6 points from top slide edge, 405 points from bottom slide edge
@michaelDCurran

**Comment by derekriemer** [comment] 2016-12-15 05:01
There was a issue with me pasting that from speech viewer there, but I think you get the point.

**Comment by Adriani90** [comment] 2019-03-25 22:06
@derekriemer I think this is still reproducible. Right?

**Comment by Adriani90** [comment] 2024-10-05 13:59
This is not reproducible with NvDA 2024.4 Beta and Office 365 build 2409, and also not in 2016 with the same build.
I am closing as works for me, NVDA reports "behind other item by x points" no matter whether the screenshot has alt text or not. Other item is the category this shape belongs to in MS Office.

If you have other findings or are still having this issue, please comment and we can reopen

**Closed by Adriani90** 2024-10-05 13:59 UTC
Labels: close/worksforme, p4
