### ISSUE TITLE
provide a shortcut key to read the network status

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10882] opened 2020-03-18 11:52 UTC
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
My suggestion is inspired because there is a feature from another screen reader that I found interesting and useful.
I would like a shortcut key to be made available for nvda to report network status.
As there are few shortcut keys available, the shortcut key could be unassigned.
I know that it is possible to obtain this information in the task bar, but the intention would be to facilitate the reading of this information, as is already done in the reading of the hours and battery status.

**Comment by lukaszgo1** [comment] 2020-03-18 12:18
Duplicate of #1279

**Comment by feerrenrut** [comment] 2020-03-18 12:50
Closing as a duplicate of #1279

**Closed by feerrenrut** 2020-03-18 12:50 UTC
Labels: close/duplicate
