### ISSUE TITLE
Automatic Braille table change

### ISSUE THREAD

**Issue by AppleUser03** [nvaccess/nvda#13880] opened 2022-07-08 11:47 UTC
JAWS 2022 introduced a new feature that changes the Braille table depending on which language i'm reading. For example, if I have the Braille table set to Italian and I'm reading a webpage in French, it automatically sets the French Braille table. This is very helpful because lets me read in a different language with the specific Braille patterns. Is it possible to have this feature also in NVDA?

**Comment by CyrilleB79** [comment] 2022-07-09 14:33
Hi @AppleUser03 

Would this issue be a duplicate of #2044?
If yes, please close it and add further comments there. Thanks.

**Comment by seanbudd** [comment] 2022-07-11 00:15
Welcome @AppleUser03 ,

We are unable to process this issue as it stands.

- Please fill out the issue template fully. https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=feature_request.md

Kind Regards,
NV Access Software Developers

**Closed by seanbudd** 2022-07-11 00:15 UTC
