### ISSUE TITLE
In case of no item in folder, windows explorer.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5759] opened 2016-02-18 10:49 UTC
Hello, I'm Hyongsop Kim in Korea.
Once I enter inside folder and if there is no item in windows explorer, nvda says nothing.
I think that nvda should say 'no item' or something, otherwise, users are confused about the focus.
Also if just one file is there and user doesn't know how many files are there, once user press arrow keys, nvda says nothing.
in that case, it might be confusing whether there is a file or not.
Of course, as user enters a folder, nvda says the file name with not selected, sometimes user doesn't recognize this information.
Please consider this issue.

Thank you.

**Comment by leonardder** [comment] 2017-07-17 13:57
Hmm, I can see the benefits of this. In the case of Explorer, there's a dynamic UIA list item object, but when you try to retrieve children for its parent, it returns nothing as expected. Also, these empty list don't seem to trigger a Focus event.

@MichaelDCurran @JCSTeh, thoughts? May be we should generalize this to other containers as well?

**Comment by jcsteh** [comment] 2017-07-18 00:13
The fact that Explorer doesn't fire a focus event on the list when opening an empty folder is a bug in Explorer. Most lists do. (Interestingly, it doesn't fire a UIA focus event, but it does fire an MSAA focus event. We use UIA for this control, so that doesn't help us.) I'm not sure whether we can work around this. @MichaelDCurran, do we have a channel to report this to Microsoft? Note that it affects Narrator as well.

Reporting "no items" or similar for an empty list is related, but separate. That does apply to all lists.

I suggest we track the Explorer specific issue here; the expected result would be reporting "list" or similar when entering an empty folder. The "no items" help message should be filed as a separate issue if desired.

See also #3152.

**Comment by jcsteh** [comment] 2017-07-18 00:14
P2 because this is potentially very confusing. However, it's likely that all we can do is file a bug with Microsoft, a fix for which probably won't get backported before Windows 10.

**Comment by Adriani90** [comment] 2019-02-12 14:52
In Windows 10 this is still an issue.

**Comment by jcsteh** [comment] 2019-02-12 21:54
@michaelDCurran, while I'm sure we've mentioned this to Microsoft in the past, was an actual bug report ever filed? It'd be nice to get this silly bug some attention.

**Comment by fernando-jose-silva** [comment] 2021-10-11 16:03
I would like to join the choir so that this problem is solved, this would help a lot new users, I am a computer instructor for people with visual impairments.

**Comment by josephsl** [comment] 2023-01-21 23:26
Hi,

Turs out the solution is quite simple (or maybe not):

1. Listen to name change event coming from an IAccessible object with the window class name of "ShellTabWindowClass".
2. Do a UIA tree traversal to locate items list.
3. Check the last child of the items list, and if this is a static text with a specific UIA class name or Automation Id, announce the label, which happens ts say "this folder is empty".

This solution works even with selective UIA event registration on, although this will result in double speaking in some cases (or may not speak at all under some circumstances; tests pending). This is an NVDA side solution - the ultiamte solution should come from Microsoft.

Thanks,

**Comment by josephsl** [comment] 2023-04-16 01:43
Hi,

Update: it was reported on NVDA users list that with the solution applied, NVDA will say "working on it" when opening File Explorer (Windows+E).

A potential fix was released a while ago in the form of an add-on, which was then incorporated into Widows App Essentials not long ago and subsequently edited to use the solution proposed above. So far, the solution works with occasional double speaking in some cases. If I do write a PR, it'll bring the proposed solution above to NVDA, but I can wait if NV Access believes Microsoft will do something about it.

Thanks.

**Comment by josephsl** [comment] 2023-04-18 06:37
Hi,

Another update: turns out the solution I had in mind has a critical flaw:

1. Find a program that does not raise focus event sometimes such as Outlook.
2. Copy the title of the app in question to the clipboard.
3. Open File Explorer, navigate to a folder (say, Documents), then create a new (empty) folder giving it the same name as the just copied app title.
4. Open the new folder.
5. Switch between the first app and File Explorer/empty folder.

Expected: NVDA will announce "this folder is empty" when switching to File Explorer.
Actual: no differences in announcement when switching between aps, more so in Windows 10 and Windows 11 21H2 and earlier. One must use Control+NVDA+F1 (app module name) to obtain where one is located.

The proposed solution relies on name change/UIA element selected event, used when opening folders and/or switching between tabs in File Explorer, the latter introduced in Windows 11 22H2. Therefore, I'm withdrawing the proposed solution and the pull request plan (along with removing it from Windows App Essentials add-on in May).

Thanks.

**Comment by josephsl** [comment] 2024-02-15 02:35
Hi,

Ten months later: FINALLY RESOLVED! This is fixed at least in Windows Insider build 26052, so it should make its way via Windows 11 24H2 (2024 Update, I assume that's goin to be the marketing name). The fix was confirmed with both NVDA and Narrator. I vote to close this issue as "resolved externally" once Windows 11 24H2 official build does include this fix (things can change between the time this post is written and 24H2 RTM).

Thanks.

**Comment by josephsl** [comment] 2024-04-22 17:18
Hi,

April 2024 update: all indications point to build 26100 as 24H2 RTM (a higher build is being tested by Insiders in canary channel). Closing as fixed externaly.

Thanks.

**Closed by josephsl** 2024-04-22 17:18 UTC
Labels: p3, feature/windows-explorer, triaged
