### ISSUE TITLE
Firefox: Unable to press Show Options button on a Github ticket

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#11352] opened 2020-07-07 18:20 UTC
### Steps to reproduce:
1 View this ticket on github.com.
2 Navigate to the Show Options button.
3 Try to activate it using Spacebar or Enter.

### Actual behavior:
Nothing happens, i.e. the button does not get pressed. The log snippet when trying to press Spacebar is pasted below. Note that the exact same is shown even on pressing Enter.
"Input: kb(laptop):shift+b
IO - speech.speak (23:48:15.018) - MainThread (7676):
Speaking ['clickable', 'Show options', 'Show options', 'graphic', 'button', 'collapsed', 'subMenu']
IO - inputCore.executeGesture (23:48:16.580) - winInputHook (3584):
Input: kb(laptop):space
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (23:48:16.612) - MainThread (7676):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (23:48:16.612) - MainThread (7676):
Clicking with mouse"

### Expected behavior:
The button should have gotten clicked/presed/activated.

### Notes
* I suspect this ticket is likely a variation of an existing ticket or at least related in some way. Please point out any similar tickets and I will try to contribute to conversation there.
* Firefox, according to the System submenu, has the Maximize option as unavailable, which is to say that Firefox is maximized when experiencing this bug.
* I tried routing the mouse to the navigator object and emulating the left mouse click as well, and that did not help.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.2 Beta 2
#### Windows version:
8.1
#### Name and version of other software in use when reproducing the issue:
Firefox 78.0.1
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by DrSooom** [comment] 2020-07-07 23:43
Press ALT+ArrowDown on this button.

**Comment by CyrilleB79** [comment] 2020-07-08 07:49
I have also experimented this issue on Github in Firefox. Windows 10 1809, Firefox 78.0.1 (64 bits). This happens only sometimes but I have not succeeded in understanding in which condition it happens. Sometimes reloading the webpage (F5) or alt+tabbing forth and back solves the issue.
When the issue occurs, alt+downArrow does not work either.

**Comment by XLTechie** [comment] 2020-07-08 08:59
I can confirm this periodic issue, and that when it happens, no method of 
activating the dropdown button will work.

Sometimes it will resolve after multiple attempts, or after activating another 
element.

**Comment by MarcoZehe** [comment] 2020-07-08 12:05
This is very strange, it sometimes works, and sometimes doesn't, for me. It is likely that this is related somehow to #11185. CC @jcsteh

**Comment by zahra21** [comment] 2020-07-08 12:15
hello.
i tested this issue with firefox 52 and nvda 2017.3 (the last versions that until now, support windows xp.
when i pressed enter button on show options, the menu expanded and i have only copy link button.
but, since several months ago, i had similar issue and for this reason, i wanted to write a comment and ask, do you have this problem?
or is it because github no longer support firefox 52, i observe this issue?
and, maybe my issue is related to yours.
when i write a comment,
previously, before not supporting firefox 52 by github,
i could edit my comment.
but since several months ago, i cant edit my comments on github.
and, i cant open issues which are resolved for specific version of nvda.
for example:
https://github.com/nvaccess/nvda/milestone/52
i cant open and read closed issues!

**Comment by XLTechie** [comment] 2020-07-08 16:56
Often, it will happen for me after I've already used it once or twice.

For example: post an issue, then edit it, then edit it again. By the third edit,
it would have started happening for me.

**Comment by lukaszgo1** [comment] 2022-01-20 11:32
cc @jcsteh  Would you be able to take a look at this? In Chromium based browsers this button can be always activated successfully.

**Comment by jcsteh** [comment] 2022-01-21 03:10
NVDA always walks to the deepest node for browse mode activation. IN this case, that's a graphic. The graphic doesn't have a click event listener, so Firefox doesn't expose a click action on it, causing NVDA to fall back to simulating a mouse click itself. I guess if anything is obscuring the button, that will break.

In contrast, Chrome exposes a "click ancestor" action on all descendants of click event listeners. So, NVDA almost always uses actions rather than simulating clicks itself.

https://bugzilla.mozilla.org/show_bug.cgi?id=1395181 is probably the best way to deal with this.

**Comment by lukaszgo1** [comment] 2022-01-21 11:29
Given the low priority (P5) of the Firefox bug perhaps the more reasonable course of action would be to fix this on the GitHub's side. Is there anything which can be changed on the GitHub page to improve the situation?

**Comment by jcsteh** [comment] 2022-04-24 05:16
This has been fixed in Firefox 101 (currently Nightly).

**Closed by jcsteh** 2022-04-24 05:16 UTC

**Comment by lukaszgo1** [comment] 2022-04-28 08:00
Hi @jcsteh  Many thanks for your work on This! Unfortunately there are still several cases where I cannot activate controls with NVDA. I'm running Nightly 101.0a1 (2022-04-27) (64-bit).
- Open https://crash-stats.mozilla.org/report/index/dc83730d-38be-436d-a0cf-663920220428 move to the Bugzilla tab and try to select it with Enter.
- open https://github.com/nvaccess/nvda/pull/13366/commits move to one of the commits and try to activate the 'Copy the full SHA' button.
- Open https://cjo.up.krakow.pl/o-nas/struktura/, move to the heading named 'Struktura', and try to activate tab called 'Zespół III'.

If these are unrelated just let me know and I will create a separate issues for these.

**Comment by jcsteh** [comment] 2022-04-28 10:38
>     * Open https://crash-stats.mozilla.org/report/index/dc83730d-38be-436d-a0cf-663920220428 move to the Bugzilla tab and try to select it with Enter.

This is a bug in the tab component used on the site. It exposes tab controls with aria-labelledby (which overrides the content), but the tab doesn't handle clicks. Rather, clicks are handled by a link inside the tab... but because the content is overridden with aria-labelledby, screen readers don't render the link. I can't activate these in Chromium browsers either. (You can switch to focus mode and press enter, though.) I should probably file a bug for us to hack around the tab component, but I don't think we can fix this in Firefox at this stage.

>     * open https://github.com/nvaccess/nvda/pull/13366/commits move to one of the commits and try to activate the 'Copy the full SHA' button.

Similar website bug as above. This time, they have a button inside the button. The outer button has aria-label, thus overriding the content. Only the inner button accepts clicks.

>     * Open https://cjo.up.krakow.pl/o-nas/struktura/, move to the heading named 'Struktura', and try to activate tab called 'Zespół III'.

Same bug as the first one, probably even the same tab component.

These bugs courtesy of incorrect usage of ARIA. <sigh>

**Comment by jcsteh** [comment] 2022-05-17 13:35
Unfortunately, we ran into a late problem with this and had to delay it until Firefox 102.
