### ISSUE TITLE
Quick Navigation Key for Jumping to Menu Items.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4948] opened 2015-02-25 12:30 UTC
**Reported by ateu on 2015-02-25 12:30**
As well as it's possible to jump to next and previous list item, It would be nice if the same quick navigation key take us to next and previous menu item.
I think this is an important feature, as this control is really common in today's web pages.

**Comment by ehollig** [comment] 2017-08-04 17:16
@jcsteh what do you think of this issue? It may be useful for menus that use ARIA.

**Comment by leonardder** [comment] 2018-03-23 21:58
Closing as older duplicate of #7695, as the latter also covers menus.

**Closed by leonardder** 2018-03-23 21:58 UTC
Labels: Browse mode, enhancement
