### ISSUE TITLE
browse mode is very slow for walmart website

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#6829] opened 2017-02-01 13:51 UTC
Browse mode is very very slow with NVDA 2016.4 especially on the walmart website. When I load up and use jaws 18 the website is very fast and snappy. Please redo browse mode in NVDA so it is very fast and snappy like jaws is. I would rather not switch to jaws if I can help it. but the walmart website especially adding stuff to the cart just makes NVDA slow to a crawl to the point the purchase process from walmart website is not useable and i have to load up jaws. thanks.

**Comment by leonardder** [comment] 2017-12-16 14:53
@joshknnd1982: Please provide additional details:

* What browser were/are you using?
* Can you reproduce this with multiple browsers?

**Comment by Adriani90** [comment] 2019-04-01 16:11
@joshknnd1982 could you please provide an update to this issue? Is this still occuring? Are you using Internet Explorer? Or which browser?

**Comment by Adriani90** [comment] 2019-04-01 18:25
Thanks for reporting back. Closing as works for me.

**Closed by Adriani90** 2019-04-01 18:25 UTC
Labels: worksforme
