### ISSUE TITLE
twitter frame contents on nvaccess.org is not in the buffer with firefox 77

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#11223] opened 2020-06-03 08:20 UTC
### Steps to reproduce:
With firefox v77, open nvaccess.org and scroll down to the heading at number 3 "nvaccess on twitter". try to navigate down. you will notice that the frame that includes latest tweets is not there.
### Actual behavior:
nvda doesn't recognize the frame
### Expected behavior:
NVDA should read out the contents of the frame
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.1
#### Windows version:
windows 1010 2004
#### Name and version of other software in use when reproducing the issue:
Mozilla firefox v77
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, that doesn't change the behavior

**Comment by Adriani90** [comment] 2020-06-03 15:41
cc: @feerrenrut, @Qchristensen

**Comment by Adriani90** [comment] 2020-06-04 18:50
This is not reproducible in NVDA alpha-20256,f2cbfec8. The contents are read properly in Firefox 77. Closing as works for me.

**Closed by Adriani90** 2020-06-04 18:50 UTC
Labels: close/worksforme
