### ISSUE TITLE
source/comInterfaces contains some files which should be ignored

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#7070] opened 2017-04-13 06:11 UTC
When working with current master, scons -c removes files below:

```
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    source/comInterfaces/UIAutomationClient.py
        deleted:    source/comInterfaces/_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py
```

Usually such files should be ignored by .gitignore.

**Comment by jcsteh** [comment] 2017-04-13 06:22
Scons shouldn't be cleaning these. They were once generated by scons, but
now, they're checked into Git.

If you checkout these files again and rebuild, does scons -c delete them
again? It's possible scons is just confused because it previously generated
those files and you haven't done a clean build since then.

If that doesn't work, try removing the .sconsign.dblite file and
rebuilding. That will ensure you're not using any cached scons data.

CC @MichaelDCurran.

**Comment by nishimotz** [comment] 2017-04-13 06:58
I understand they are intentionally added files.
However, working with fresh clone, scons -c still removes these two files.

**Comment by leonardder** [comment] 2018-03-23 21:11
I can confirm this with latest master.

What is actually supposed to be the functionality of scons -c? If I do scons -c and than git clean -dfx, many files still seem to remain, where you might expect that scons -c cleans up the entire repo, including submodules.

**Comment by Adriani90** [comment] 2019-04-12 21:26
cc: @michaelDCurran

**Closed** 2023-12-04 05:15 UTC
