### ISSUE TITLE
Suggestion, reading the end information of the updates during the login window.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6566] opened 2016-11-15 10:25 UTC
Soon after installing the windows updates, soon after restarting the computer after having installed windows updates, before windows lets you enter the user password is displayed a screen with the "please wait, preparing windows, do not power off your Computer, installing updates, (x%) ".
Nvda currently reads this screen only if you press incert + b.
My first suggestion would be for nvda to read this screen automatically, and also tell me the percentage of the update.
Soon after windows has finished installing the updates the login screen is displayed, however nvda does not automatically inform that it is already possible to enter the password. The only way to find out that updates have been completed and that you can type the password is by pressing incert + b to have the screen read, or press any key to enter the password.
My suggestion was for nvda to inform itself authomatically that the installation of updates has been completed and that we can enter the password.

**Comment by josephsl** [comment] 2016-11-15 13:55
Hi,

Which version of Windows is this? If it's Windows 10, it is a bit tricky to implement.

Technical: UIA live region changed event is fired for status messages. However, there are times when the info repeats (likely because two different controls fire this event). Also, we need to make sure this doesn't break for those using earlier versions of Windows.

Thanks.

**Comment by fernando-jose-silva** [comment] 2016-11-15 15:19
10.0.14393

Thanks

 

 

De: Joseph Lee [mailto:notifications@github.com] 
Enviada em: terça-feira, 15 de novembro de 2016 11:55
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Suggestion, reading the end information of the updates during the login window. (#6566)

 

Hi,

Which version of Windows is this? If it's Windows 10, it is a bit tricky to implement.

Technical: UIA live region changed event is fired for status messages. However, there are times when the info repeats (likely because two different controls fire this event). Also, we need to make sure this doesn't break for those using earlier versions of Windows.

Thanks.

**Comment by josephsl** [comment] 2016-11-15 15:31
Hi, thanks. CC @MichaelDCurran, @JCSTeh, I’m happy to donate live region changed event code from my add-on to the Core.

**Comment by feerrenrut** [comment] 2016-11-16 04:28
This sounds like it could save quite a bit of frustration. However it does not stop or limit what a user is able to do. Considering the is a starting point for the implementation, I'll assign it a priority 3.

**Comment by Adriani90** [comment] 2019-03-25 20:33
cc: @josephsl

**Comment by Adriani90** [comment] 2020-05-02 19:32
@fernando-jose-silva are you still seeing this issue? I cannot reproduce it with NVDA 2020.1 RC1. If I set NVDA to start with Windows and on logon screens, NVDA reports "please wait, updates x" etc. Can you confirm?

**Comment by fernando-jose-silva** [comment] 2020-05-02 22:18
Nvda reports the percentage of the update, however after reaching 100% nvda does not inform you to enter the user's password, and does not read the login window.
The user can only assume that he can press any key to enter the password because the update has reached 100%, but it is a deduction, since nvda does not automatically announce the login screen.
Sometimes windows informs 100% the update is complete, but the user needs to wait a few seconds or depending on the machine for minutes for the keyboard to respond and allow the user to enter the password.
It would be good if the nvda announces itself 100% updating completed.
And then the login screen is announced, and it usually announces the date and time.

**Comment by Adriani90** [comment] 2024-11-16 00:18
@fernando-jose-silva that part of the issue you describe in your last comment is already covered in #10583.
I am closing this one as duplicate of the newer issue.

**Closed by Adriani90** 2024-11-16 00:18 UTC
Labels: close/duplicate, p4
