### ISSUE TITLE
optgroup role and label not conveyed

### ISSUE THREAD

**Issue by mfairchild365** [nvaccess/nvda#10034] opened 2019-08-03 21:27 UTC
### Steps to reproduce:

1. With NVDA running and set to default settings, go to https://a11ysupport.io/tests/html/html/select.html
2. navigate through the options (while collapsed and expanded)
3. notice that no information about the optgroups are provided

### Actual behavior:

notice that no information about the optgroups are provided

### Expected behavior:

Information should be conveyed, such as [the grouping role](details-id-101) and label. Boundary information may also be helpful.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1

#### Windows version:
windows 10 build 1903

#### Name and version of other software in use when reproducing the issue:
Chrome 75, Firefox 68

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by leonardder** [comment] 2019-10-25 11:28
Closing as duplicate of #9485

**Closed** 2019-10-25 11:28 UTC
