### ISSUE TITLE
NVDA Freezing in WSL / WT terminal

### ISSUE THREAD

**Issue by Arfs6** [nvaccess/nvda#14849] opened 2023-04-20 09:25 UTC
### Steps to reproduce:
Open WSL using Windows terminal.
Open neovim text editor.
Use ctrl - right arrow to navigate
It happens once in a while.
### Actual behavior:
NVDA freezes and I had to restart it. It wasn't responding to anything.
### Expected behavior:
Cursor  moves to the next word in the text editor (neovim)
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/11284416/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.1 (2023.1.0.27913)

#### Windows version:
22H2 (OS Build 19045.2364)
#### Name and version of other software in use when reproducing the issue:
Windows Sub system for Linux (WSL)
Version: 1.1.6.0                                                                                                                                        
Windows Terminal(wt)
Version: 1.17.1023
Neovim (Nvim)
Version: 0.6.1
#### Other information about your system:
It happens once in a while. I have enabled debug logging just incase it happens next time to attach the full logs.
I read the logs and there seem to be an uncaught Exception.
I have seen a couple of issues about NVDA freezing but non on a release version. That was why i decided to open the issue.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Unknown
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Unknown

**Comment by Adriani90** [comment] 2023-04-20 12:15
Is this also rpeorducible in the last NVDA version?

You can download and test with the last alpha at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Arfs6** [comment] 2023-04-22 15:14
i have tried it today. There wasn't any complete freeze but a log of hooks. I have enabled the debug logging. Here is the log file: 
[nvda.log](https://github.com/nvaccess/nvda/files/11301610/nvda.log)
About 130, 00 lines :) Hope it will be helpful
I'll surely send the log file if it freezes.

**Comment by Adriani90** [comment] 2023-04-22 16:56
There are many hooks due to event being canceled to avoid double speaking. Otherwise I don't see any significant errors or performance issues from this log file. I am closing this issue as works for me, since it has probably been fixed in the last alpha verison of NVDA.

If you are still seeing any freezes or performance issues, please comment on this with an updated log file and steps to reproduce and we can reopen. Or open a new issue with updated steps to reproduce.

**Closed by Adriani90** 2023-04-22 16:56 UTC
Labels: close/worksforme
