### ISSUE TITLE
Outlook 2010/2016: Unread Status of Messages not announced when Selecting with the Keyboard

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11014] opened 2020-04-15 17:31 UTC
### Steps to reproduce:

Note: This may also be reproduceable in newer versions of Outlook; 2010 and 2016 are the only versions that I've had available to test with, so I've listed these as a starting point.

1. Open a folder that contains at least 3/4 unread email messages; you'll notice that as you move up/down, NVDA automatically announces either "read" or "unread" to indicate their status

2. Place focus on the top message in the list, and use shift + down to select the message and move to the next message in the list - ensuring that the message that is about to get focused is unread

### Actual behavior:

NVDA simply announces the information pertaining to the next message in the list; unread status isn't announced

### Expected behavior:

As long as the next message in the list is unread, NVDA should announce "unread" as the message is focused and highlighted - as it does when moving through the list with the up/down arrows

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

7 X64

#### Name and version of other software in use when reproducing the issue:

Office 2016 X86

#### Does the issue still occur after restarting your computer?

Yes

#### If addons are disabled, is your problem still occuring?

Yes

**Comment by DrSooom** [comment] 2020-04-16 12:36
I noticed this incorrect behavior just a few days (or weeks) ago with Microsoft® Outlook® 2010 (14.0.7245.5000) SP2 MSO (14.0.7237.5000) and NVDA 2019.2.1 on Win7x64. So thanks for opening this issue.

**Comment by Adriani90** [comment] 2020-04-16 20:21
Closing as duplicate of #6819

**Closed by Adriani90** 2020-04-16 20:21 UTC
Labels: close/duplicate
