### ISSUE TITLE
SPA, navigation and focus management

### ISSUE THREAD

**Issue by alebourblanc** [nvaccess/nvda#6504] opened 2016-10-25 13:56 UTC
Hi,

I work on a web application with Angular 2 and I have a major issue with NVDA on Firefox.
Single page application and accessibility are not very compliant but as soon as we play a little with it we can find some solutions.

My issue is about the navigation, each time we navigate to the next or the back page ,on our webapp, NVDA does not understand that the focus has changed and he must start to read automatically the content of the new page.

To repair this issue I try to use the focus management, I add a div around all the html code of my page and I give him the focus as soon as the page is read, with angular2 it is in the ngAfterViewInit method.

It works fine for the first page of my webapp (my first page or any other page after a F5), it's like NVDA does not detect the focus has changed even if the div (as described above) is correctly focused.

By the way, it's working fine with JAWS and Voice Over.

Thanks and regards,
Alex

**Comment by jcsteh** [comment] 2016-10-25 23:02
Please provide a test case and steps to reproduce the problem. Thanks.

**Comment by alebourblanc** [comment] 2016-10-27 15:37
Hi,

I think this test case could help you. Indeed, at the page load NVDA will read the list of the top heroes on the first page of the web application but when you want to navigate in the other pages it will read nothing automatically.

Steps to reproduce:
    - Go on http://plnkr.co/edit/xTXgZBkH0dTD7yO7QEqS?p=preview
    - Launch the plunkr
    - Go on the different pages and see what is reading by NVDA

Expected behavior
     NVDA sould read automatically the content of each page of the web application

Issue description
     NVDA is reading only the first page of the web application

Thanks and regards,
Alex

**Comment by alebourblanc** [comment] 2016-11-03 12:01
Hi,

Can you please have a look on my previous message ?

Thanks,
Alex

**Comment by nicolasigot** [comment] 2016-11-07 17:51
Hello @jcsteh , 
Can you please review with scenario provided? You should not be blocked anymore. This issue is serious as we are trying to implement website on which accessibility is mandatory and we need to have it working with Angular 2 and NVDA. 
We can provide you any support that would help.
Thanks a lot and Regards,
Nicolas

**Comment by monkier** [comment] 2016-11-21 19:53
I have a similar situation with Angular 1. The virtual cursor is in the correct position if I set focus to the `<header>` or the `<main>` but not a wrapper div with `tabindex="-1"`.

If I set it to a wrapper div, the virtual cursor appears to be in the middle of the virtual buffer, i.e., when I press down arrow when the view has loaded, it will be in the middle of a newly loaded form or on other views it will be after the `h1`.

**Comment by BrennanRoberts** [comment] 2018-01-12 20:19
I think this may be a simpler test case: 
http://codepen.io/sarbbottam/full/yJeQLa/ 

From [this ticket](https://github.com/ember-a11y/ember-a11y/issues/6):
> When one activates the link foo, bar, baz, load bar and load baz, the outlet container is updated accordingly and focused.

> When the link foo, bar, baz is activated, NVDA reads out the content of the outlet container. However, when the link load bar, load baz is clicked, NVDA does not read out the content of the outlet container, though the outlet container is focused.

**Comment by BrennanRoberts** [comment] 2018-01-12 20:27
This may be related to or a dup of #6606. The cause of that ticket:
> At present, NVDA ignores focus on an ancestor in this case because the browse mode cursor is already "within" the focused element. The reason for this is that NVDA itself moves the focus when you move the browse mode cursor, but we don't want this focus change to cause spurious reading and to snap the browse mode cursor to the start of the element (which is normally the expected behaviour for focus). There's no reliable way of determining whether a focus change was caused by NVDA itself or by the web page, so we assume focus on an element which already contains the browse mode cursor was caused by NVDA.

**Comment by jcsteh** [comment] 2018-01-15 01:40
Yes, I'd agree this is a duplicate of #6606. Closing this one in favour of #6606, since it contains more technical detail.

**Closed by jcsteh** 2018-01-15 01:40 UTC
