### ISSUE TITLE
Focus problems in RS5 version of Skype UWP, and the Settings app with NVDA master builds with UIA event coalescence

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#8580] opened 2018-07-31 05:32 UTC
### Steps to reproduce:

1. Run NVDA latest Master build with Windows RS5 Insider builds and the version of Skype that comes with it (the UWP version, not the Electron app).
2. Alt-tab into and out of it, tab around the UI, and do day to day tasks in Windows that require you to go in and out of Skype occasionally.

### Actual behavior:

Several problems might occur:

1. When alt-tabbing into Skype, or when first starting it, actual focus might not be announced.
2. When pressing Tab, focus changes might not be announced.
3. Skype might crash so you have to relaunch it.
4. Focus almost never stays where you last left it when alt-tabbing out of Skype and returning to it later. It always starts at the "My info" button, which is the first focusable item in the UI.

### Expected behavior:

Focus should always be announced, focus location should be remembered, and Skype should not crash as frequently.

#### NVDA Installed/portable/running from source:

installed.

#### NVDA version:

NVDA Master, version alpha-15726,870669e3.

#### Windows version:

Version 1803 (Build 17723.1000)

#### Name and version of other software in use when reproducing the issue:

Skype Version 8.26.0.48
Application version 14.26.48.0

#### Other information about your system:

Microsoft Surface Laptop.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

Yes, and it does not happen with NVDA 2018.2.1. All problems are gone if I use the current stable release version.

CC @josephsl @michaelDCurran at Joe's explicit request.

**Comment by josephsl** [comment] 2018-07-31 05:36
Hi, yes, after some email exchanges, I’m thinking it may have to do with event coalescing or something in recent NVDA alpha snapshots. Note that this affects RS5/19H1 (19H1 = 18204)/Skype 14 Preview. And no, this does not apply to #7126. Thanks.

**Comment by MarcoZehe** [comment] 2018-08-01 06:47
I am also seeing this more in the Settings app of RS5 builds. Focus either gets stuck (or so it seems) in the search field, or it doesn't speak at all, except "Settings window" when alt-tabbing into or opening it.

**Comment by michaelDCurran** [comment] 2018-08-01 06:51
I am also experiencing this on Windows build 17728 a lot. But not so 
much on 17723. I don't believe this is directly related to NVDA now 
using UIA event coalescing.

**Comment by Adriani90** [comment] 2019-04-22 20:56
@MarcoZehe are you still having this issue? I am using NVDA 2019.1.1 on Windows 10 1809 Update and Skype UWP 8.42 and I cannot reproduce this issue. I could reproduce it however on Windows 10 1803 Update.

**Comment by MarcoZehe** [comment] 2019-04-23 03:36
Nope, no longer reproducible for me in 1809 or 1903 builds, except for some very rare occasion in the Settings app. But Skype seems fine now.

**Comment by Adriani90** [comment] 2019-04-23 08:59
Thank you Marko for reporting back. Closing as works for me.

**Closed by Adriani90** 2019-04-23 08:59 UTC
Labels: worksforme
