### ISSUE TITLE
Chrome: text in some edit fields appears to be missing

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#8781] opened 2018-09-25 15:03 UTC
### Steps to reproduce:

1. Open Chrome to a page that has a textarea element, and put a LOT of text in the field.
2. At some point, try reviewing the text. For me, NVDA reports "blank for any text after some unknown cutoff point.

### Actual behavior:

NVDA reports "blank" where the text should be. It reads normally, then cuts off partway along. I suspect a character maximum is being reached.

### Expected behavior:

NVDA should read the text as normal.

#### NVDA Installed/portable/running from source:

installed

#### NVDA version:

2018.3.1

#### Windows version:

Windows 10, v1803

#### Name and version of other software in use when reproducing the issue:

Chrome 69.0.3497.100

#### Other information about your system:

None relevant, to my knowledge

#### Does the issue still occur after restarting your PC?

unknown

#### Have you tried any other versions of NVDA?

no

**Comment by Adriani90** [comment] 2019-12-20 21:12
@mehgcap how is the behavior in NVDA 2019.3 Beta 1 and Chrome 79?

**Comment by isidorn** [comment] 2020-01-31 10:06
I can reproduce this also in VS Code that is built on top of Chrome.
I have latest NVDA

**Comment by isidorn** [comment] 2020-02-19 11:41
fyi @leonardder since this issue seems rather important
Is this maybe the root cause https://bugs.chromium.org/p/chromium/issues/detail?id=1001591&q=nvda%20does%20not%20read&can=2

**Comment by isidorn** [comment] 2021-03-02 15:41
I can not reproduce this anymore with latest Chrome.
As far as I am concerned this can be closed

**Comment by Adriani90** [comment] 2021-03-03 08:19
Closing as works for me. Thanks for keeping us updated.

**Closed by Adriani90** 2021-03-03 08:19 UTC
Labels: close/worksforme
