### ISSUE TITLE
NVDA Screen reader is reading unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.

### ISSUE THREAD

**Issue by eDADMSFTChristopher** [nvaccess/nvda#10998] opened 2020-04-13 17:44 UTC
User Experience:
Screen reader dependent users won't be able to navigate pane properly or screen reader users confused to navigate pane through screen reader, if Screen reader is reading unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.

Repro Steps:
1. Open https://login.microsoftonline.com/common/oauth2/authorize?client_id=8360d653-4205-4a3c-add2-cc8806f96c15&response_type=code
2. Enter valid user name and password provided by customer.​
3. Navigate all the controls of "Permissions requested" page.
4. Verify the issue.

Actual Result:
In normal mode screen reader is reading unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.
At first time NVDA is reading 'Sign in to your account document table table wingtiptoysonline.net menu button sub menu'.

Expected Result:
Screen reader should not read unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.

Note:
Same type of issue doesn't exists through Narrator + Edge.

Repro Steps:
1. Open https://login.microsoftonline.com/common/oauth2/authorize?client_id=8360d653-4205-4a3c-add2-cc8806f96c15&response_type=code
2. Enter valid user name and password provided by customer.​
3. Navigate all the controls of "Permissions requested" page.
4. Verify the issue.

Actual Result:
In normal mode screen reader is reading unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.
At first time NVDA is reading 'Sign in to your account document table table wingtiptoysonline.net menu button sub menu'.

Expected Result:
Screen reader should not read unwanted table information on 'wingtiptoysonline.net' button under Permissions requested pane.

Win10   version 2004(OS Build 19562.1000)   
Chrome   browser (Version 80.0.3987.163)
NVDA 2019.3.1
--

**Comment by DrSooom** [comment] 2020-04-15 09:30
@eDADMSFTChristopher: Can you please report the behaviors with Firefox (75.0.x) and Edge (the latest) in combination with NVDA 2019.3.1 as well? Thanks.

**Comment by Adriani90** [comment] 2020-04-17 17:57
@eDADMSFTChristopher in order for us to investigate exactly what the issue is, could you please create a minimal test case out of that control / table and post it here?
Without user name and password it will be impossible for us to reproduce.
Thanks for your assistance.

**Comment by DrSooom** [comment] 2020-04-18 12:45
@Adriani90: I guess your own Microsoft/Skype account is enough here. But please shorten the two URLs in the issue description to `https://login.microsoftonline.com/` as they contain sensitive data. Thanks.

**Comment by Adriani90** [comment] 2020-04-18 23:26
Thanks Daniel for the suggestion, however, I think we still need a minimal test case here. Not all developers do have a Microsoft account.

**Comment by Adriani90** [comment] 2020-05-17 11:26
@eDADMSFTChristopher I logged into this website and saw that someone needs administrator permission to access the app. I guess it is easy to reproduce for an administrator but not for everyone. Given this restriction we will not be able to investigate here. If this is confidential, please contact NV Access directly and discuss with them this issue or provide here a minimal test case.
I am closing this issue for now until we get a reliable test case which can be reproduced by everyone. After that we can reopen. Thanks.

**Closed by Adriani90** 2020-05-17 11:26 UTC
