### ISSUE TITLE
Unavailable error message from Screen reader for ANY Button click at the moment.

### ISSUE THREAD

**Issue by prajwalmanju** [nvaccess/nvda#13832] opened 2022-06-22 08:58 UTC
### Steps to reproduce:
1) Enable NVDA Screen Reader
2) Focus on the any adaptive card button.
3) Click on enter while focusing on any button and observe the screen reader input.

### Actual behavior:
While triggering any button screen reader reading with error message "unavailable".

### Expected behavior:
While triggering any button screen reader should not read with error message "unavailable".

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes I tried with NVDA 2021.1 version as well same issue in both the versions.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment] 2022-06-22 09:05
Please provide a minimal reproducible HTML example using CodePen or similar tool. Without a MWE this issue cannot be progressed.

**Comment by prajwalmanju** [comment] 2022-06-22 09:08
we are using JSON to create the card, is it fine if we share JSON example along with screen recording of the repro ?

**Comment by seanbudd** [comment] 2022-06-22 10:37
@prajwalmanju - we need an HTML sample, it would not be clear what the issue is with just JSON data.
Screen recordings are generally not accessible to our vision impaired contributors.

**Comment by prajwalmanju** [comment] 2022-06-22 11:38
Hello Team,

We are not facing this issue in other screen readers, we are facing the issue while using NVDA screen reader.

Please find the attachment for HTML sample.
[HTML sample1.txt](https://github.com/nvaccess/nvda/files/8957162/HTML.sample1.txt)

Thanks!

**Comment by prajwalmanju** [comment] 2022-06-27 01:47
Hello Team,

Greetings of the day!

A gentle follow up to check if there is any update on this issue ?

I have attached the requested HTML sample via previous chat, please let me know if you need any additional details.

Thanks!

**Comment by prajwalmanju** [comment] 2022-06-29 17:44
Hello Team,

Greetings of the day!

A gentle follow up to check if there is any update on this issue ?

Thanks!

**Comment by seanbudd** [comment] 2022-06-29 22:48
@prajwalmanju - thank you for providing the required information to investigate. There are over 2000 open issues. When we get a chance to investigate further, we will let you know on this issue.

**Comment by Manasa-acuvate** [comment] 2022-07-06 14:01
Hello Team,
I will be a new SPOC and replacement of @prajwalmanju.

As per comment I see that we are waiting for an update from your end.
May I know if you got a chance to investigate further? If, yes please may I know the latest update?

Thank-you!

**Comment by seanbudd** [comment] 2022-07-07 01:35
@Manasa-acuvate - There are over 2000 open issues. When we get a chance to investigate further, we will let you know on this issue.
Please stop spamming the issue.

**Comment by seanbudd** [comment] 2022-07-07 02:17
@Manasa-acuvate - if this is critical for your organisation, please contact info@nvaccess.org to organise formal support.

**Comment by Adriani90** [comment] 2023-03-02 23:14
I am closing this as duplicate and in favor of #14292. The minimal test case in that issue is easier to read and understand I think.

**Closed by Adriani90** 2023-03-02 23:14 UTC
Labels: close/duplicate
