### ISSUE TITLE
NVDA prevents the deletion of Windows Schedule Tasks and crashes MMC in Windows 10 64 bit

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#8485] opened 2018-07-07 04:04 UTC
Steps to reproduce:
Type taskschd.msc in the run dialogue (Windows key+R and press Enter.
Select the Task Scheduler Library Tree view
Tab to the list of available scheduled tasks, select one or multiple items, E.G. Google Update, Adobe Updator, etc. and try deleting the selected scheduled task while NVDA is running.
Actual behavior:
After selecting Yes in the delete prompt, the task won't be deleted, and also MMC.exe (the program which handles Task Scheduler and other Microsoft Management Console Snap-ins) crashes, and becomes unresponsive.
Expected behavior:
The selected task should be deleted, and the user should be able to further explore the list of available scheduled tasks.
System configuration:
Intel Core i7-6700K CPU, 16GB RAM, 512GB NVMe SSD. The issue is not system specific.
NVDA Installed/portable/running from source:
Installed.
NVDA version:
2018.2.1
Windows version:
Windows 10 64 bit , version 1803 (build 17134.137)
Name and version of other software in use when reproducing the issue:
Microsoft Management Console 3.0
Task Scheduler Snap-ins 1.0
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
Yes. This issue also applies to previous NVDA releases.

**Comment by derekriemer** [comment] 2018-07-07 05:54
I can't reproduce this on the 1803 I'm running. Is this random, or is it reliably crashing mmc?

**Comment by armick** [comment] 2018-07-07 06:22
Are you probably running Windows 10 32 bit?
Also, I am not experiencing the crash on every MMC snap-in. For example Device Manager works fine.
I am having the crash every time I use Task Scheduler. Note, however, it seams it's not happening on 32 bit version of Windows 10.

**Comment by amirsol81** [comment] 2018-07-07 07:03
Hi. I can reliably duplicate the exact same issues on my Windows 10 Pro 64-Bit machine: Windows 10 64 bit , version 1803 (build 17134.137).

**Comment by Brian1Gaff** [comment] 2018-07-07 08:13
As a matter of interest, should this command work in windows 7?
 It normally throws an error, but I thought it was my lack of understanding.

taskschd.msc

**Comment by Brian1Gaff** [comment] 2018-07-07 08:43
Further to this. I do not even get that far running the task scheduler in 
windows 7 from the start search box.

I invoked it from the start search box in Windows 7 64 bit
Task Scheduler
And this happened, may be repeated as things were just a little sluggish!

Unhandled Exception in Managed Code Snap-in Unhandled Exception in Managed 
Code Snap-inFX:{c7b8fb06-bfe1-4c2e-9217-7a69a95bbac4}
FX:{c7b8fb06-bfe1-4c2e-9217-7a69a95bbac4}

Exception has been thrown by the target of an invocation.
Exception type: System.Reflection.TargetInvocationException
Exception stack trace:    at 
Microsoft.ManagementConsole.Executive.MmcThreadMessageWindow.OnThreadException(Exception 
e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, 
String text, String caption, Int32 type)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String 
text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, 
MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean 
showHelp)
   at System.Windows.Forms.MessageBox.Show(IWin32Window owner, String text, 
String caption, MessageBoxButtons buttons, MessageBoxIcon icon, 
MessageBoxDefaultButton defaultButton, MessageBoxOptions options)
   at 
Microsoft.ManagementConsole.Advanced.MessageBoxParameters.ShowDialog(IWin32Window 
parent)
   at 
Microsoft.ManagementConsole.Internal.ConsoleDialogHost.ShowDialog(WaitCursor 
waitCursor, ShowDialogCallback callback)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.MMCConsole.ShowDialog(MessageBoxParams 
messageParams)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.DisplayError.ShowMessageBox(Boolean 
parentIsModal, String message, String caption, MessageBoxButtons buttons, 
MessageBoxIcon icon, MessageBoxDefaultButton defaultButton)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.DisplayError.UserError(String 
errorString)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.UITaskBase.ShowServiceIsDownMessage(Exception 
e, Boolean restartService)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.UITaskFolder.GetUITaskList(Object 
sender, DoWorkEventArgs eWorker, Boolean loadTaskDefinitions, Boolean 
includeHiddenTasks)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.EnumerateTasksAndAddToList()
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.RefreshData(Boolean 
firstRefresh)
   at 
Microsoft.TaskScheduler.SnapIn.TaskSchedFolderFormViewControl.RefreshData(Boolean 
firstTime)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.InitializeTaskDetailControl()
   at 
Microsoft.TaskScheduler.SnapIn.TaskSchedFolderFormViewControl.Microsoft.ManagementConsole.IFormViewControl.Initialize(FormView 
snapinFormView)
   at Microsoft.ManagementConsole.FormView.InternalInitialize()
   at 
Microsoft.ManagementConsole.View.HandleInitializationRequest(IRequestStatus 
requestStatus)
   at Microsoft.ManagementConsole.View.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.ViewMessageClient.ProcessRequest(Request 
request)
   at 
Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request 
request)
   at 
Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient 
messageClient, RequestInfo requestInfo)
   at 
Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   at 
Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback 
callback)



Unhandled Exception in Managed Code Snap-in Unhandled Exception in Managed 
Code Snap-inFX:{c7b8fb06-bfe1-4c2e-9217-7a69a95bbac4}
FX:{c7b8fb06-bfe1-4c2e-9217-7a69a95bbac4}

Exception has been thrown by the target of an invocation.
Exception type: System.Reflection.TargetInvocationException
Exception stack trace:    at 
Microsoft.ManagementConsole.Executive.MmcThreadMessageWindow.OnThreadException(Exception 
e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, 
IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.SafeNativeMethods.MessageBox(HandleRef hWnd, 
String text, String caption, Int32 type)
   at System.Windows.Forms.MessageBox.ShowCore(IWin32Window owner, String 
text, String caption, MessageBoxButtons buttons, MessageBoxIcon icon, 
MessageBoxDefaultButton defaultButton, MessageBoxOptions options, Boolean 
showHelp)
   at System.Windows.Forms.MessageBox.Show(IWin32Window owner, String text, 
String caption, MessageBoxButtons buttons, MessageBoxIcon icon, 
MessageBoxDefaultButton defaultButton, MessageBoxOptions options)
   at 
Microsoft.ManagementConsole.Advanced.MessageBoxParameters.ShowDialog(IWin32Window 
parent)
   at 
Microsoft.ManagementConsole.Internal.ConsoleDialogHost.ShowDialog(WaitCursor 
waitCursor, ShowDialogCallback callback)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.MMCConsole.ShowDialog(MessageBoxParams 
messageParams)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.DisplayError.ShowMessageBox(Boolean 
parentIsModal, String message, String caption, MessageBoxButtons buttons, 
MessageBoxIcon icon, MessageBoxDefaultButton defaultButton)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.DisplayError.UserError(String 
errorString)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.UITaskBase.ShowServiceIsDownMessage(Exception 
e, Boolean restartService)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.UITaskFolder.GetUITaskList(Object 
sender, DoWorkEventArgs eWorker, Boolean loadTaskDefinitions, Boolean 
includeHiddenTasks)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.EnumerateTasksAndAddToList()
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.RefreshData(Boolean 
firstRefresh)
   at 
Microsoft.TaskScheduler.SnapIn.TaskSchedFolderFormViewControl.RefreshData(Boolean 
firstTime)
   at 
Microsoft.Windows.ManagementUI.CombinedControls.TaskDetailControl.InitializeTaskDetailControl()
   at 
Microsoft.TaskScheduler.SnapIn.TaskSchedFolderFormViewControl.Microsoft.ManagementConsole.IFormViewControl.Initialize(FormView 
snapinFormView)
   at Microsoft.ManagementConsole.FormView.InternalInitialize()
   at 
Microsoft.ManagementConsole.View.HandleInitializationRequest(IRequestStatus 
requestStatus)
   at Microsoft.ManagementConsole.View.ProcessRequest(Request request)
   at Microsoft.ManagementConsole.ViewMessageClient.ProcessRequest(Request 
request)
   at 
Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request 
request)
   at 
Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient 
messageClient, RequestInfo requestInfo)
   at 
Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   at 
Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback 
callback)

end

**Comment by Brian1Gaff** [comment] 2018-07-07 09:46
Hi again. When I boot in the Jaws demo, terminat nvda, then run the  utility again from the tart menu, it performs Ok, but says, that the image could have been tampered with or currupted. I then terminate jaws reboot a portable nvda and I can get at the tasks with no issues. So it only gives the error if nvda is already running when it is started, in this case its Windows 7.
 I have no idea about the tampering bit as a warning at all.
 Brian

**Comment by armick** [comment] 2018-07-07 17:29
1. I am not experiencing this issue when running JAWS on any Windows version/architecture
2. This happens only on Windows 10 64 bit when NVDA is running. I can delete tasks on Windows 7 64 bit.

**Comment by Brian1Gaff** [comment] 2018-07-07 23:12
Yes that is right it is only nvda running before the launch of the task 
manager that crashes it.
It does it earlier in 7, however.

Not sure what it all means though. I'll let the clever folk here work it all 
out!

**Comment by Adriani90** [comment] 2019-05-08 16:04
Closing in favor of #9222 because this is the same issue and the behavior is exactly the same. In that issue more details are proviced incl. log errors etc.

**Closed by Adriani90** 2019-05-08 16:04 UTC
Labels: duplicate
