### ISSUE TITLE
Chrome occasionally fails to recognize radio buttons in browse mode

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#7363] opened 2017-07-07 05:13 UTC
### Steps to reproduce:
1. Open Chrome
2. Visit the following link: https://google.qualtrics.com/jfe/form/SV_ewWXIoEVLBcyp7f?referral_code=0&reserved=0&pType=0&productTag=0&campaignType=0&campaignDate=0&labelTag=0&appTag=0&l=0
3. Choose the next button to get to the country selection screen.
4. use browse mode to choose your country from among the list of countries.

### Expected behavior:
NVDA should identify each country as a radio button as the user navigates with arrow keys.

### Actual behavior:
NVDA only lists the country when arrowing. If object navigation is used, the radio buttons are identified. This problem does not occur while in focus mode. NVDA also sees the radio buttons if you tab rather than use arrow keys. The problem is also not limited to this page. I have noticed it on other sites. This is an example.

### System configuration:
NVDA version:
NVDA version next-14162,fa7fdc3f

NVDA Installed or portable:
installed

Windows version:
Windows 10 Pro Insider 1703 build 16232

Name and version of other software in use when reproducing the issue:
Chrome Canary Version 61.0.3150.0 (

**Comment by derekriemer** [comment] 2017-07-08 10:12
d

**Comment by PratikP1** [comment] 2017-07-08 10:22
@derekriemer Your comment appears to have been cut off.

**Comment by derekriemer** [comment] 2017-07-09 06:24
whoops. um, try again.

This is strange. down arrow skips it in browse mode. if you tab into them, they focus fine.
I thought this meant the radio buttons were aria-hidden="true" but it seems not. This seems like it could potentially affect a large number of users.

**Comment by PratikP1** [comment] 2017-07-09 13:56
@derekreimer wrote:
> This is strange. down arrow skips it in browse mode. if you tab into them, they focus fine. I thought this meant the radio buttons were aria-hidden="true" but it seems not. 

I noticed the tabbing behavior and updated my comment. I also tested (but failed to note) the ARIA-hidden possibility. But, if that had been the case, none of the text should have appeared. The code didn't indicate it either.

**Comment by jcsteh** [comment] 2017-07-09 22:51
Duplicate of #6781. That issue relates to check boxes, but the cause is the same. For some reason, Chrome exposes these with a width and height of 0, which means they are effectively invisible and NVDA therefore doesn't render them. In contrast, Firefox exposes these with a width and height of 16 x 16.

**Closed by jcsteh** 2017-07-09 22:51 UTC
