### ISSUE TITLE
Can't determine unread message status in Thunderbird

### ISSUE THREAD

**Issue by jscholes** [nvaccess/nvda#8902] opened 2018-11-01 10:18 UTC
### Steps to reproduce:
1. Move to the message list in a folder in Thunderbird.
2. Arrow up and down between unread messages.
### Actual behavior:
NVDA doesn't distinguish between read and unread messages as it used to.
### Expected behavior:
NVDA speaks the word "unread" between the subject line and the sender of the message.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
alpha-16209,b02ed2de
#### Windows version:
Windows 7 Professional Service Pack 1, 64-bit (6.1.7601)
#### Name and version of other software in use when reproducing the issue:
Mozilla Thunderbird 64.0b1 (32-bit)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by jscholes** [comment] 2018-11-01 10:31
Confirmed that unread message status is still reported with 60.0 (32-bit).  However #8903 still applies irrespective of Thunderbird version used.

**Comment by Adriani90** [comment] 2023-08-14 19:28
This is not reproducible in Thunderbird 102 or newer with NVDA 2023.2 Beta 3. i am closing as works for me. Please comment on this issue if you are still having it and we can reopen.

**Closed by Adriani90** 2023-08-14 19:28 UTC
Labels: close/worksforme, MozillaWork, blocked/needs-external-fix
