### ISSUE TITLE
Activating elements in firefox occasionally doesn't work, announces battery status from system tray instead

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11185] opened 2020-05-21 13:55 UTC
CC: @MarcoZehe @jcsteh 

### Steps to reproduce:

1. Its hard to replicate this reliably because it only happens sometimes. The last time I saw this happening was trying to react to a facebook video via the toggle button, but have also seen this in other types in controls like links and buttons.

### Actual behavior:

The battery status icon is read out from the system tray

### Expected behavior:

The element being activated is properly clicked, and you hear the result.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-20220,1c4519a6

#### Windows version:
Windows 10 2004 10.0.19041.264

#### Name and version of other software in use when reproducing the issue:
Firefox 77.0 b8, but I've seen this for months and just thought to report it. Also in earlier versions of Firefox

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, multiple alpha builds - this has been going on for as long as I can remember

#### If addons are disabled, is your problem still occuring?
Unknown

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by MarcoZehe** [comment] 2020-05-21 18:23
I have seen this before, this often happens if the screen orientation or resolution changes while NVDA is running, for example after a new display driver update has been installed, or sometimes when returning from standby. It helps to restart NVDA then. Sometimes if this happens, the whole screen coordinate system for mouse click simulation is totally off.

**Comment by Neurrone** [comment] 2020-05-22 16:45
Nothing of that sort was going on though.

**Comment by Adriani90** [comment] 2020-05-23 10:07
I cannot reproduce on a Dell machine with Intel graphic card and Firefox 76. is the window maximized when you interact with the elements?
Is this occuring when the setting "automatically move focus to focusable elements" is enabled or disabled? The setting state can be changed with nvda+8.

**Comment by Adriani90** [comment] 2020-05-23 10:08
I am on the same alpha currently.

**Comment by Neurrone** [comment] 2020-05-23 12:05
"automatically move focus to focusable elements" is on, I'll try to see if it happens with it off the next time it happens. I doubt this is going to help though.

The window is maximized.

**Comment by Qchristensen** [comment] 2020-06-05 00:06
I found a specific page I can replicate this on reliably:

The Texas State University homepage: https://www.txstate.edu/ contains a video which when you try to pause it, in Firefox, minimises the whole window and moves focus to the taskbar or next Window.

It's a bit of a hike to get to, but press 2 six times to jump to the sixth heading level 2, then tab three times to get to the "Play Wherever you are Bobcats, we're with you video" link, then when the player opens and the video starts, tab to the play / pause button and ENTER to (attempt to) pause the video.

It might be something with the embedded Vimeo player.  Interestingly, playing videos, including this one, directly on the Vimeo site itself works, including the play / pause button -  although that button isn't the easiest to find there, but it works once you do.

I'm using Firefox 77.0.1 64-bit

CC: @jcsteh

**Comment by bhavyashah** [comment] 2020-06-20 15:15
NVDA doesn't announce the battery status for me, but I too, on facebook.com, have experienced times when pressing something, usually a Messenger chat, with either the Spacebar or the Enter key, does not work. In these cases, I press F11 as well as check the System submenu to maximize Firefox (version 77.0.1). However, this does not help. Sometimes, setting the mouse cursor and then left clicking it with the keyboard helps, but often it doesn't. I think I have been experiencing this less with NVDA version 2020.2 Beta 1, but that might be because I have barely used facebook.com after updating.

**Comment by XLTechie** [comment] 2020-06-20 23:27
I've been getting a variant of this in 2020.1 and 2020.2beta1, where pressing 
enter on something in Firefox will give me either Cortana's entry field, or 
something in the notification area.

Maximizing is the solution to this. But really the maximized state of the 
browser window shouldn't be connected to where the screen reader goes when you 
select a button or link.

Unfortunately, this has only happened so far while I'm in a hurry, and using 
protected websites such as banks or the IRS.gov site.

As soon as I can get a shareable log, I will post one.

**Comment by Neurrone** [comment] 2020-06-21 06:28
It happens for me even when the window is maximized. It is odd that whether its maximized or not would affect how controls are activated.

**Comment by MarcoZehe** [comment] 2020-06-21 06:48
When NVDA activates something, it performs a click action on the deepest child of the element under the virtual cursor. So for a link, it is the link text or image that's embedded. There are some things that seem to throw off the screen coordinates that NVDA uses to perform that click. An updated video driver can be such a thing, without NVDA having been restarted in the interim. The coordinate systems then get out of sync somehow. Or if something overlaps the browser window that NVDA isn't aware of.

This has historic reasons: Too many web sites override the click or mouse down/up handlers even on buttons and do other things than the keyboard. That's why at some point, NVDA stopped just calling the press action on buttons or the jump action on links when the Enter or Space key are pressed in browse mode, and performs a mouse click on the deepest child instead.

**Comment by Adriani90** [comment] 2020-06-21 19:31
cc: @jcsteh, @leonardder

**Comment by Adriani90** [comment] 2020-12-08 21:07
@MarcoZehe 
> if something overlaps the browser window that NVDA isn't aware of.

yeah this is the most common case where this issue can be reproduced (i.e. when a CCleaner update window appear on the foreground and NVDA does not report it.

**Comment by bhavyashah** [comment] 2021-12-17 09:15
I second https://github.com/nvaccess/nvda/issues/11185#issuecomment-741032783. In my case, when I connect my Smartphone to my laptop via USB, a Dropbox Camera Upload window occupies a part of the screen. Activating controls in different applications begins to frequently fail, throwing me back to the Camera Upload window instead. I have had this experience with obtrusie Wordweb and CCleaner windows as well.

**Comment by jcsteh** [comment] 2022-04-24 05:17
This should be fixed in Firefox 101 (currently in Nightly builds).

**Closed by jcsteh** 2022-04-24 05:17 UTC

**Comment by jcsteh** [comment] 2022-05-17 13:35
Unfortunately, we ran into a late problem with this and had to delay it until Firefox 102.
