### ISSUE TITLE
MS Edge: Navigation in YouTube is very hard to perform

### ISSUE THREAD

**Issue by florianionascu7** [nvaccess/nvda#8309] opened 2018-05-20 17:52 UTC
### Steps to reproduce:
1. Open Microsoft Edge and play any YouTube video, or directly open YouTube itself.
2. Move with the arrows through the site, and you'll see that NVDA tells you what happens with a big delay.
### System configuration:
NVDA version:
2018.1.1
NVDA is Installed, I'm not running the portable copy.
Windows version:
April 2018 Update.
### Other related questions
Does the bug still occurs after restarting your PC?
Yes, it does.
Have you tried other MVDA versions?
Yes, and the same behavior. I tried NVDA 2017.3 with Windows 10 Creators Update I guess. It happened in the last autumn.

**Comment by derekriemer** [comment] 2018-05-21 05:06
I can maybe reproduce this. can you give an example of the amount of time you experience for slowness?

**Comment by florianionascu7** [comment] 2018-05-21 06:03
Hello! An example is the delaying of 12 or 13 seconds.

**Comment by gdata1** [comment] 2018-05-22 06:30
Hello. I have already created a request, but decided to write here.. When viewing the results on yutube using edge Nvda says empty if you go through the headings with the H key. When playing video I have a delay of 1 second approximately.

**Comment by florianionascu7** [comment] 2018-05-22 08:41
Our delay diference is quite big.

**Comment by derekriemer** [comment] 2018-05-23 19:16
I get delays of maybe a second also, but nothing like you report. Is there anything unique about your setup?

**Comment by florianionascu7** [comment] 2018-06-01 20:21
There's not

**Comment by Adriani90** [comment] 2020-04-22 17:08
Closing as works for me, this is working well in Edge Chromium 81. Edge Chromium will be distributed to most users through Windows 10 20 H1 update.

**Closed by Adriani90** 2020-04-22 17:08 UTC
Labels: app/edge, close/worksforme

**Comment by Adriani90** [comment] 2020-04-30 21:02
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
