### ISSUE TITLE
NVDA 2018.4 beta 1 not reading .chm file

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#8976] opened 2018-11-24 09:26 UTC
Using NVDA 2018.4 beta 1 on Windows 10 and trying to open the AutoHotKey help file.  Contents momentarily appears on the screen but NVDA says nothing.  There is then that nasty clang-clang sound and I am returned to where I started.  The problem does not occur with earlier NVDA versions, including nvda_snapshot_alpha-16247,fbae6b0b.  Also no problem when using Narrator.  A copy of the log file is attached.
[nvda-log.txt](https://github.com/nvaccess/nvda/files/2612149/nvda-log.txt)
Andrew

**Comment by leonardder** [comment] 2018-11-24 11:56
Please provide exact steps to reproduce this issue.

**Comment by andrew-l-d** [comment] 2018-11-24 23:52
In brief, trying to open the autohotkey.chm file.  Steps are:
1. Press Windows key.
2. Up arrow once.
3. Press a (for apps starting with a)
4. Arrow down until reaching the AutoHotKey folder.
5. Press Enter.
6. Arrow down to AutoHotKey help file.
7.  Press Enter.
8.  Wait a few seconds and get thrown back to previous position.
Alternatively navigate to c:\program files\autohotkey, arrow to the autohotkey.chm file and press Enter.  Results are the same.
Andrew

**Comment by andrew-l-d** [comment] 2018-12-11 09:59
The issue persists with 2018.4 rc1.  The last line of the log file is:
WindowsError: [Error 1726] The remote procedure call failed
As well as the autohotkey.chm file, the problem occurs with some, but by no means all, such files.
Andrew

**Comment by leonardder** [comment] 2018-12-11 10:00
Could you somehow upload this chm file to here?

**Comment by Adriani90** [comment] 2018-12-11 10:37
I have done following:
1. Opened c:\programme (x86)
2. Went to the search field and typed .chm
3. Tested with 12 .chm files from different applications (VB Jaws, Active X etc.).

Result: I didn't get any errors in Windows 10 1809 Update with NVDA 2018.4 RC1.
@andrew-l-d, looking at your log file content it could be something wrong in your app data related to current profile. Could you change the current profile in NVDA and see if the issue still occurs? Does it occur when you open the file as administrator?
In worst case I would say remove NVDA, delete the NVDA folder in %app data% / roaming and install NVDA again.

**Comment by Andre9642** [comment] 2018-12-11 10:37
Have you tried with a portable version of NVDA 2018.4? Is it the same?
Have you tried with all add-ons disabled?
Maybe a log in debug level might help....

**Comment by andrew-l-d** [comment] 2018-12-11 21:57
Adrian, as I mentioned previously, the problem occurs with some, but not all, .chm files.  I suggest you test with the file I uploaded.
Meanwhile, I installed 2018.4 RC1 as a portable version in an empty folder and the problem occurred.  I deleted it and installed 2018.3 as a portable and the file loaded.  In both cases, no add-ons were installed.  The problem did not occur with alpha builds and started with the betas.  Interestingly, the problem does not occur with try-i8994-16338,745f390d, which was used to test page position announcement in Word.
Andrew

**Comment by lukaszgo1** [comment] 2018-12-11 22:18
I am able to reproduce it on Windows 7 x64 with the file to which @andrew-l-d linked. Due to fact, that it is reproducible only with the betas/rcs and not with the alpha version i believe, tat we maybe experiencing something similar to #8767 i.e differences between optimized vs non optimized builds. cc @michaelDCurran

**Comment by michaelDCurran** [comment] 2018-12-12 04:53
I believe I have found the bug.
I have made the fix and created an optimized try build for testing:
https://ci.appveyor.com/api/buildjobs/esdyr121mgd8my2i/artifacts/output%2Fnvda_try-release-i8976-16420%2Cad535b47.exe
For me, the chm file opens correctly while running this build, where as it did not with the betas and rc.
This try build has been compiled the same way as a release would.
Please download and test this build and confirm that the issue is fixed for you.
My plan is to get this into the next rc, which again I will ask here for you to try that build also to confirm before we release 2018.4.

**Comment by andrew-l-d** [comment] 2018-12-12 09:33
Michael, the try build works fine with that pesky .chm file.  I will also check RC2 when available.
Andrew

**Comment by lukaszgo1** [comment] 2018-12-12 12:11
This try build fixes it for me.

**Comment by leonardder** [comment] 2018-12-13 06:02
Fixed in #9052.

**Closed by leonardder** 2018-12-13 06:02 UTC

**Comment by michaelDCurran** [comment] 2018-12-13 23:20
2018.4rc2 with chm fix: https://www.nvaccess.org/files/nvda/releases/2018.4rc2/nvda_2018.4rc2.exe

**Comment by andrew-l-d** [comment] 2018-12-14 00:13
Definitely fixed
Andrew

**Comment by lukaszgo1** [comment] 2018-12-14 12:53
I can also confirm, that it is fixed in RC2.
