### ISSUE TITLE
Error raised when using MS word

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6996] opened 2017-03-21 08:03 UTC
When using NVDA (version next-13911,3c8e30bd) with Microsoft Word 2013 with [this document](https://github.com/nvaccess/nvda/files/857386/Word.total.width.error.zip) an error is raised when moving by line. 

```
ERROR - RPC process 12312 (WINWORD.EXE) (15:58:26):
Thread 6400, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 962:
pageWidth does not equal the calculated page width. Some margin or offset me be missed, this may mean that some column numbers reported were incorrect. pageWidth: 624 colStartPos: 465.85
```

This document was created by removing their content from a document submitted by a user. Note that when the "page setup" dialog is accessed on the "margins" tab the "gutter position" value is blank, valid options are 'left' and 'top'. This seems like the document is not valid. However we might be able to handle this more gracefully.

Word seems to assume the value of 'left' is used in this case.

**Comment by feerrenrut** [comment] 2017-03-23 01:53
Further information:
The error sound reported by the user can not be heard in stable versions of NVDA. We could potentially improve the column detection code. I'm not sure what value is being returned when we ask for the gutter position in this document. We could however assume the value of 'left' when the value is not one of 'top' or 'left'. MS word does this after all.

**Comment by Adriani90** [comment] 2019-04-09 20:12
@feerrenrut I cannot reproduce this issue in NVDA alpha-17029,4d2e7f2b. i tested both in Word 2010 and Word 2016 / 365. Is it still reproducible in Word 2013 though?

**Comment by feerrenrut** [comment] 2019-04-09 21:14
No, I can't reproduce the log error ( using nvda version `alpha-17029,4d2e7f2b` and Word 2013)

Looking more closely, the code that produced this warning was commented out in the interests of performance. See [PR #9217 file nvdaHelper/remote/winword.cpp at line 1005](https://github.com/nvaccess/nvda/pull/9217/files#diff-90846759642698297f744ca06fdb37edR1005 )

I don't recommend we close this off. The erroneous result is likely still occurring, it is now just less obvious.

**Comment by Adriani90** [comment] 2023-03-07 11:05
I am closing this one until we get other reports from users / developers that this occurs again.

**Closed by Adriani90** 2023-03-07 11:05 UTC
Labels: close/worksforme, app/microsoft-office, p3
