### ISSUE TITLE
Braille input not working with Braille Me display using BRLTTY

### ISSUE THREAD

**Issue by xtstoll** [nvaccess/nvda#11518] opened 2020-08-22 23:15 UTC
### Steps to reproduce:
1. Install BRLTTY (https://brltty.app/download.html)
2. Connect a Braille Me display to your PC with NVDA on
3. Configure NVDA to use the BRLTTY option in Settings > Braille
4. Open Notepad
5. Try to type "hello" on the braille display

### Actual behavior:
Nothing is typed. Only arrows keys work to navigate, not other keys (dot keys, spacebar and Enter).

### Expected behavior:
The word "hello" should appear on screen and on the braille display.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.2

#### Windows version:
Windows 10.0.17763

#### Name and version of other software in use when reproducing the issue:
BRLTTY (brltty-win-6.1-0-libusb-1.0.exe)
Braille Me (firmware M02.38S0106H9.20)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by leonardder** [comment] 2020-08-25 17:13
Thanks for your report. This is a known issue, but it looks like noone got around to look into this further.

Closing as duplicate of #6483

**Closed by leonardder** 2020-08-25 17:13 UTC
