### ISSUE TITLE
NVDA browse mode and tabindex -1 attribute in div container

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#11820] opened 2020-11-09 04:16 UTC
Hello.
My name is Hyongsop Kim from Korea and NVDA user.
If div container with some text and buttons or links are existed and div has tabindex-1 attribute, NVDA browse mode with tab key focus is inconsistency.
To reproduce this issue:
1. Go to [sample page](https://khsbory.github.io/video%20player%20with%20aria-live%20script.html).
For testing purpose, I added tabindex -1 attribute in main tag.
2. Please tab key to go to play button.
3. Press down arrow key and you can find text.
4. Press tab key again.
You can find that focus will go to play button.
Expected behavior is NVDA focus should go to big button, not play button.
Because play button is above the text.
The reason is NVDA browse mode recognize not correctly tabindex -1 attribute.
You can watch [demonstration video](https://1drv.ms/v/s!Aj9xs5XCa0zwmK8MD5XthIgDN_FJhg?e=PLwPHE).
I took the video with this demo.
Thank you.

**Comment by Adriani90** [comment] 2020-11-11 19:38
In which browsers did you reproduce this?

**Comment by khsbory** [comment] 2020-11-12 00:26
I tested with chrome and firefox.
I experienced same issues with two browsers.
Thank you.

**Comment by JulienCochuyt** [comment] 2020-11-23 12:17
This occurs only if "Automatically set system focus to focusable elements" is checked.
When looking up the `focusableNVDAObjectAtStart`, NVDA only considers looking up the parent tree.
Thus, when moving down from the "Play" button, the focus lands on the region.
IMHO, when moving up from the "Big" button, we do want focus to land on the region, but when moving down from the "Play" button, focus should remain there until a new focusable object is encountered.

**Comment by Adriani90** [comment] 2020-11-30 12:06
cc: @jcsteh

**Comment by jcsteh** [comment] 2020-11-30 23:48
Effectively the same underlying issue as described in https://github.com/nvaccess/nvda/issues/5251#issuecomment-458758479.

That said, I'd argue this is fixed for most users, since auto focus focusable elements is now disabled by default (#11190).

**Comment by Adriani90** [comment] 2020-12-02 22:21
Thanks Jamie for this comment. This makes sense to me. I am going to close this issue for now, but feel free to comment if there is a clear justification why this should be further investigated when automatic set focus to focusable elements is enabled.

**Closed by Adriani90** 2020-12-02 22:21 UTC
Labels: close/worksforme
