### ISSUE TITLE
NVDA with the mail app in windows10

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#8085] opened 2018-03-14 18:34 UTC
We seem to have an issue with the mail app in windows10, when you open the mail app to read a message, you open the message and read it, then when you hit alt f 4 to close it, NVDA crashes, then you need to restart it.### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by BEdenhofer** [comment] 2018-05-20 04:56
I reported this issue with the mail app in windows10, back in march, and no ones responded to this thread, whatsoever. I'd like to ask you developers to respond to me on this issue.

**Comment by ehollig** [comment] 2018-11-08 03:46
Duplicate of #7911

**Closed by ehollig** 2018-11-08 03:46 UTC
