### ISSUE TITLE
when displaying the Updatable add-ons tab in the add-ons store save the previously chosen value in the Channel combo box:

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#14977] opened 2023-06-06 17:01 UTC
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
open nvda addon store
now open the tab
Updateable add-ons
in the combo box
Channel:
choose some non-default value as an example:
all
Now close the window by tabing to the close button and pressing enter.
Now open the addon store again and open the tab again
Updateable add-ons
put focus on combo box
Channel:
see that the default value is set in the case:
stable
I would like nvda to have the value chosen by me previously in the all case.
### Additional context
if my request is not what the majority expected make this configurable.

**Comment by seanbudd** [comment] 2023-06-08 01:26
This is intended behaviour and the alternative described here would potentially be misleading. Closing as won't fix

**Closed by seanbudd** 2023-06-08 01:26 UTC
Labels: feature/addon-store
