### ISSUE TITLE
nvda2017.3 fails to read emails with tables in outlook 2013 2013 under windows 7

### ISSUE THREAD

**Issue by mcsedmak** [nvaccess/nvda#7705] opened 2017-10-26 21:33 UTC
### Steps to reproduce:
1. Open outlook 2013 in windows 7 while running nvda2017.3
2. In the list of emails, select an html email with a table including links and press return to open the email for viewing
3. Attempt to navigate by using "k" to jump to the next link

I have not narrowed this down to happen with all emails that include tables.  However almost every email sent from the Jira bug system appears to have the magic setup to confuse nvda

### Expected behavior:
Read the text of the link
### Actual behavior:
No sound output, appears not to read the contents.  
But if I move a single character at a time I can verify that the focus did move to the link

I see the following error in the logfile viewer:

ERROR - scriptHandler.executeScript (15:11:06.188):
error executing script: <bound method MailViewerTreeInterceptor.script_nextLink of <appModules.outlook.MailViewerTreeInterceptor object at 0x06085AD0>> with gesture u'k'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "browseMode.pyo", line 359, in <lambda>
  File "browseMode.pyo", line 341, in _quickNavScript
  File "browseMode.pyo", line 184, in report
  File "speech.pyo", line 835, in speakTextInfo
  File "browseMode.pyo", line 1001, in getControlFieldSpeech
  File "textInfos\__init__.pyo", line 434, in getControlFieldSpeech
  File "speech.pyo", line 1173, in getControlFieldSpeech
  File "NVDAObjects\window\winword.pyo", line 728, in get
  File "NVDAObjects\window\winword.pyo", line 1232, in fetchAssociatedHeaderCellText
  File "NVDAObjects\window\winword.pyo", line 1169, in getHeaderCellTrackerForTable
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 149, in __getattr__
  File "comtypes\automation.pyo", line 664, in _invoke
COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))

### System configuration:
NVDA version:
nvda2017.3

NVDA Installed or portable:
installed
Other information:
Email has tables, links and graphics

Windows version:
windows 7  enterprise 64 bit sp1

Name and version of other software in use when reproducing the issue:
outlook 2013

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
2017.2 had the same result

**Comment by dineshkaushal** [comment] 2017-10-26 23:41
Possible duplicate of #7196

**Comment by ehollig** [comment] 2017-10-27 13:36
Closing as duplicate of #6827

**Closed by ehollig** 2017-10-27 13:36 UTC
