### ISSUE TITLE
Chromium & Chromium Based Browsers: tables are not rendered in '<details>' tag

### ISSUE THREAD

**Issue by Andre9642** [nvaccess/nvda#11007] opened 2020-04-14 19:41 UTC
### Steps to reproduce:
1. Open this URL in Chrome, Edge and Firefox:
  `data:text/html,<details><summary>Product price list</summary><table><tr><th>Product</th><th>Price</th></tr><tr><td>HK205</td><td>140$</td></tr><tr><td>TLE215</td><td>80$</td></tr><tr><td>NWE714</td><td>94$</td></tr></table></details>`
2. Expand the — Product price list — section.

### Actual behavior:
In Chromium, Google Chrome and Edge Chromium the table is not rendered. No problem in Firefox.

### Expected behavior:
It should work no matter the browser 

#### NVDA installed/portable/running from source:
Any

#### NVDA version:
alpha-19972,72ee0b9a

#### Windows version:
Windows 10 Insider (64-bit) build 19603.1000

#### Name and version of other software in use when reproducing the issue:
- Microsoft Edge 81.0.416.53
- Chrome 80.0.3987.163

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by ObjectInSpace** [comment] 2020-06-01 17:38
Unable to reproduce. After expanding the list, the table is rendered and NVDA navigation commands traverse the content. Going to guess this was fixed for M83.

**Comment by Adriani90** [comment] 2020-06-01 18:28
Confirming this works properly in NVDA alpha 20220,1c4519a6, Chrome 83 and also Edge Chromium 83.
Closing as works for me and thank you for the update on this.

**Closed by Adriani90** 2020-06-01 18:28 UTC
Labels: app/chrome, app/edge/anaheim, close/worksforme

**Comment by Andre9642** [comment] 2020-06-01 22:48
Indeed, it's now fixed :)
