### ISSUE TITLE
Speech Viewer: NVDA Window remains Focused after Dismissed

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5666] opened 2016-01-09 11:44 UTC
STR:
1. Open the Speech Viewer, and then close it again. I should mention at this point the action of closing the Viewer was from the Tools menu; I haven't yet tested whether the following behaviour can also be duplicated if the same action is performed via a gesture.

Expected: Focus should automatically be returned to the window that previously had focus when the Viewer was dismissed.

Actual: The window that is usually hidden (entitled "NVDA") automatically gains focus, and the user must first Alt-Tab to regain focus on the window that previously had focus.

I should point out the obvious here - I realise that in the big scheme of things this is hardly a big issue, but the Viewer is a great help when showing sighted users what information is output by NVDA, and whilst only resulting in several seconds of delay it'd be great if I could simply close it without then having to manually navigate back to my work.

**Comment by jcsteh** [comment] 2016-01-11 00:03
I've certainly seen this, but I actually have no idea why it occurs. :(

**Comment by jcsteh** [comment] 2016-09-08 02:26
I think this might have been fixed by #5050. I'm not quite sure which part.

**Comment by bhavyashah** [comment] 2017-08-29 17:25
I can confirm that this issue seems to be fixed as noted by @jcsteh in https://github.com/nvaccess/nvda/issues/5666#issuecomment-245476312. Time to close? @ehollig

**Comment by ehollig** [comment] 2017-08-29 17:33
Yes, it does appear this issue has been fixed, from what I can see. I opened the speech viewer using the tools menu, moved to a few windows that were open, and closed speech viewer in the tools menu. The speech viewer did not remain open. @elliott94, if this is still an issue for you, we can reopen this issue. Closing as worksforme

**Closed by ehollig** 2017-08-29 17:33 UTC
Labels: bug, goodForNewDev, NVDA GUI
