### ISSUE TITLE
some aria-label 's are read character-by-character instead of with words

### ISSUE THREAD

**Issue by akarelas** [nvaccess/nvda#8206] opened 2018-04-25 20:13 UTC
### Steps to reproduce:
1. Open Firefox
2. Browse to http://s3.karjala.org/strange.html
3. Have NVDA read the entire page to you.
4. Notice how the first time (of the two in the page) that Αλέξανδρος is read, the word's individual letters are read, one-by-one, instead of the word.

### Expected behavior:
If you look at the tiny source code of the page, it is obvious that the word Αλέξανδρος should be read twice in the exact same way, ie as a word.

### Actual behavior:
The first time Αλέξανδρος is read, it is read as a list of letters, read out one after the other, rather than as a word.

### System configuration:
NVDA version: 2018.1.1

NVDA Installed or portable:
Installed

Other information:
Running in a VM with VMware, as my computer is really a Linux machine.

Windows version:
Windows 10 Home Version 1709 Build 16299.125

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by derekriemer** [comment] 2018-04-26 13:31
Which speech synthesiser and language are you using? I'm asking because on ESpeak in English US, I cannot get it to read either as words. I'm happy to change my voice to test this,, I just need to know which setup can reproduce it.
Thanks.

**Comment by akarelas** [comment] 2018-04-26 23:44
@derekriemer I am using "eSpeak NG" in Synthesizer, and in General Settings I have "Language" (at the top) set to: "English, en". Then in the "Voice settings" dialog, I have Voice: "English (America)".

If I set Voice to "Greek", my problem gets solved, and all greek words are read as greek. But I was hoping to not have to change manually each time I want to visit a page in a different language. Is it necessary to do so manually each time?

Also, I wonder what's different between our two setups, and why I'm getting greek words (the visble ones) where you're getting spelling-out for those same words. Do you think it would be wise to export the NVDA settings to a file, and exchange that between us? Maybe I have NG and you have the simple eSpeak?

@PratikP1 I tried your setup (by setting Synthesizer to OneCore), and that doesn't have english voices (unless I'm mistaken), and I get spelling-out every greek word in my page with this synthesizer. Is it possible to get greek voices for OneCore? Is that what you did, and why it's working for you?

**Comment by PratikP1** [comment] 2018-04-27 03:50
Have you set up the lang attributes correctly on the page? Take a look at language inheritance patterns.

**Comment by akarelas** [comment] 2018-04-30 21:32
@PratikP1 All I did for lang attributes was set lang="el" (ie greek) on the <html> element. Shouldn't that be enough? I googled "language inheritance patterns" and "lang inheritance patterns" but didn't find anything interesting. Could you point me to a resource please?

**Comment by Adriani90** [comment] 2019-05-06 17:51
In most languages the greek name seems to be pronounced correctly. Only with following languages NVDA pronounces the word letter by letter:
English (all variants), bosnian, africans, serbian, macedonian, lituanian, vietnamese and kroatian. All other languages work correctly. i think this is an issue in eSpeak and should be reported on this repository for eSpeak:

https://github.com/espeak-ng/espeak-ng
@akarelas I would close this one and we can track the issue in the iSpeak repository. Would you mind creating a new issue there with this remarks?
Thanks for reporting.

**Closed by Adriani90** 2019-05-06 17:51 UTC

**Comment by akarelas** [comment] 2019-05-06 18:38
Ok, I'll make a note to do that this weekend.
