### ISSUE TITLE
In GitHub text areas, NVDA gets confused if you don't choose one of the items from a GitHub suggested completion list

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#13441] opened 2022-03-08 09:26 UTC
#### STR A:

1. Go into a GitHub comment field.
2. Attempt to cite an issue number with five digits. I noticed this most recently when mentioning issue 12729.
3. After typing the fourth digit, use the arrow keys to move through the five provided suggestions in the textarea, which has now become a combobox.
4. After the fifth suggestion, when you have not found 12729, go down one more time.

#### STR B:

1 and 2 are the same. At step 3: Finish typing all five digits, then press space as if you wanted to keep typing more text in your comment.

#### STR C:

1 and 2 are the same At step 3, type the last digit, a space, then start backspacing to clear the issue citation attempt.

#### STR A:

NVDA will fall off the end of the list.
The list apparently remains, and NVDA now seems not to understand how to work with the field, whatever the field may now be.
You can't re-enter the list of suggestions, you can't enter more text in the field, and so on. NVDA can't really read anything in the field now, unless you use browse mode.

That is a problem, if it's only a four digit issue number you were trying to enter (ran into that one a couple days ago); but is also a problem because you now can't type the "9" that is missing from the end of the issue number.

Sometimes, you can press tab while in focus mode, which will either leave you in a functional comment field, or will take you to the "Browse" button, shift+tabbing from which *might* get you to a functional edit field.

The only way I've found to definitely resolve this, is to switch the editor to preview mode, then back to write mode, at which point the javascript which had been holding the field hostage, resets, and it is a comprehensible field to NVDA again.

This also happens with other kinds of GitHub suggestion lists; it is just most easy to demonstrate with issue citations.

#### STR B:

If you enter the full issue number, then try to press space, GitHub will start suggesting other issues unrelated to what you entered (another list of five).
If you press enter after entering all five digits, it will enter the desired number, but also insert a newline.
And if you press tab then shift+tab, you will get the proper issue number.

#### STR C:

If you try to backspace over an entered issue number, and an optional space you have pressed after it, you will have to backspace blind, because what is spoken is either the fact that you're in a comment or some unrelated random issue number and title for the first one, or back to the proper suggestion list once you're in the number you entered.

And, if you backspace past the hash mark, even through the space before it, and start typing again, sometimes you will get a new (?) suggestion list.
To get out of this one, I eventually had to just press enter on an issue number I didn't want, then select and delete it (since it can't be deleted character by character without another suggestion list appearing), even if you delete it all.

### Expected behavior:

The old behavior was much more sane with these. As I recall, if you finished typing a number you could either hit enter or space to select a suggestion or keep what you wrote, respectively. If you backspaced, you heard the suggestions relevant to what was left of your number, and getting out of suggestion lists was not so tricky.

If you backspaced through the hash mark, the suggestion list went away and remained away.

I'm not really sure what should happen here, just that it's not this. NVDA should have some sane way of either re-entering the suggestion list, or of continuing to allow editing of the text field (if you want to enter another digit, or type more stuff after your only four digit issue number).
Or should have some ability to jut close the suggestion list (can the sighted do that?).

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-24825,4c3a67b2

#### Windows version:
21H2 (OS Build 19044.1526)

#### Name and version of other software in use when reproducing the issue:
Firefox97.0.2 (64 bit)

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Have noticed in a few other alphas, but not sure which ones.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### Other info:

In Brave (Chromium), some of the same problems happen. But there I have error sounds, and after the first time it gets unusual, subsequent appearances of the suggestion list result in this in the log:

error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x00E0CE90> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "browseMode.pyc", line 1334, in event_caret
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 249, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1608, in event_caret
  File "NVDAObjects\__init__.pyc", line 1200, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 120, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 232, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (04:14:19.499) - MainThread (24472):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1760, in _get_IA2States
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (04:14:19.499) - MainThread (24472):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speech.speak (04:14:19.509) - MainThread (24472):
Speaking ['list', CancellableSpeech (still valid)]
IO - speech.speech.speak (04:14:19.509) - MainThread (24472):
Speaking ['#12894 Manual attempts to update NVDA, or NVDA Add-Ons, is throwing error messages', '1 of 5', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getFormatFieldAndOffsets (04:14:19.540) - MainThread (24472):
could not get attributes
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 258, in _getFormatFieldAndOffsets
  File "comtypes\__init__.pyc", line 851, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))

**Comment by Adriani90** [comment] 2023-04-14 08:09
@XLTechie I don't understand exactly the heuristics behind this suggestions list, if I have a number with five digits Github shows propper issues with five digits, ho ever when pressing backspace Github sometimes shows issues with four digits, but pressing down arrow Github shows issues with five digits again. I think this part of the issue is rather related to Github than to NVDA.
When you press multiple times space bar while hearing suggestions, Github seems not to add the space characters to the edit field, but to cycle through the suggestions or to propose new suggestions. This part of the issue is also related to Githubs features in the suggestion list, not to NVDA.
The backspace issue you describe even when you delet the hash sign and type again, Github seems to add a new suggestion list but this is based on Github internal heuristics and I don't think this is related to NVDA either.

Update with Firefox 111 and NVDA 2023.1: when pressing enter after hearing a suggestion, the list goes away and the propper suggestion is added to the comment edit field together with a space character, not a new line.
Also NVDA does not fall off the end of the list anymore, when you press down arrow and there is just one suggestion, NVDA switches between edit field and the suggestion list until you select the suggestion. If there are more than one suggestions, NVDA starts at the top of the list when pressing down arrow at the end of the list.

Note that you can easily close the suggestion list with escape and only the number you entered remains in the edit field.


I think NVDA is doing everything right here, it's just the implementation and the design of the features in the suggestions list that gives you this user experience.

Are you fine if we close this issue?

You can report any unsatisfactory features with that list behavior also to Github accessibility directly at:
https://github.com/orgs/community/discussions/categories/accessibility
or try to contact their accessibility team directly.

**Comment by Adriani90** [comment] 2024-12-04 23:47
I am closing this issue as can't fix, NVDA cannot do anythin about this behavior so it needs an external fix. If you provide a link to the bug reoprt on Githubs bug tracker, we can reopen this and track the external bug report here as well.

**Closed by Adriani90** 2024-12-04 23:47 UTC
Labels: close/cantfix, blocked/needs-external-fix, needs-triage
