### ISSUE TITLE
NVDA doesn't announce the number of items in a description list correctly

### ISSUE THREAD

**Issue by sraghav1989** [nvaccess/nvda#17226] opened 2024-09-27 13:44 UTC
We are using description list to present key-values of information. It is counting the number of elements incorrectly .

Code sample:
code pen link: https://codepen.io/Shailendra-Raghav/pen/zYgBLMV

we suspected that it could be because of some styling but styles should not impact component count.
If we remove all CSS classes, it counts correctly..

### Steps to reproduce:
if we use description list to show key values in column format, this behavior should be reproducible in that case.
Attached the code pen link.

### Actual behavior:
NVDA is reading out 3 list of items instead of 6.

**Speech is as below:**

list  with 3 items

### Expected behavior:
Reader should read out 9 items instead of 4 as there are total 9 elements (dl + dd elements)

### NVDA logs, crash dumps and other attachments:

Not Applicable as crash didn't happen.

### System configuration
Machine : Windows 10

#### NVDA installed/portable/running from source:

NVDA installed on machines.

#### NVDA version:
NVDA 2024.1 (2024.1.0.31547) Released. 

#### Windows version:
Edition: Windows 10 Enterprise
Version: 22H2
OS Build: 19045.4894
Experience:  Windows Feature Experience Pack 1000.19060.1000.0

#### Name and version of other software in use when reproducing the issue:
it's simply chrome browser and NVDA on windows machines.
Chrome version:  Version 129.0.6668.71 (Official Build) (64-bit)

#### Other information about your system:
Browser: Chrome

#### Does the issue still occur after restarting your computer?
- Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
- No
#### If NVDA add-ons are disabled, is your problem still occurring?
- Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
- didn't try it

**Comment by Adriani90** [comment] 2024-09-27 13:53
Please write down the text from the screenshots or create a new issue with propper readable plain text. Here are a lot of blind developers who are not able to read the screenshots.

Also we need a minimal test case to test with, e.g. a codepen minimal test case. Otherwise it is not possible to investigate further.

**Comment by sraghav1989** [comment] 2024-09-27 14:00
Sure, i will update the issue description with texts and will reduce information to focus on particular usecase.

**Comment by Adriani90** [comment] 2024-09-30 09:59
@sraghav1989 can you please provide a minimal test case in Codepen?
See https://codepen.io/ where you can create such a test case.

**Comment by sraghav1989** [comment] 2024-09-30 10:42
@Adriani90 , sure we can try to put the code snippet there on codepen and will share the link.

**Comment by seanbudd** [comment] 2024-10-01 00:03
Duplicate of #3858

**Comment by sraghav1989** [comment] 2024-10-06 19:01
Anyhow it's marked as duplicate but still share the code link for reference :  https://codepen.io/Shailendra-Raghav/pen/zYgBLMV

**Comment by Adriani90** [comment] 2024-10-20 18:43
This is not reproducible in NVDA 2024.4 RC with Firefox 131 and Chrome canary 132. NVDA reads "list of 6 items" which are:
* Member1
* STMFVE CLAMFIVE1
* Member2
* STMFVE CLAMFIVE2
* Member3
* STMFVE CLAMFIVE3.

So the behavior is as expected. If you are still having this issue, please provide a propper minimal test case where we can reproduce this and we can reopen.

**Closed by Adriani90** 2024-10-20 18:43 UTC
Labels: close/worksforme, blocked/needs-info, needs-triage
