### ISSUE TITLE
Javascript alert content not read in Chrome

### ISSUE THREAD

**Issue by kpeterson85** [nvaccess/nvda#11395] opened 2020-07-17 21:13 UTC
### Steps to reproduce:
1. Visit https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert
2. Click the "Try it" button"
3. A javascript alert containing the text "Hello! I am an alert box!" is activated

### Actual behavior:
It is announced that a dialog has occurred but the content of the dialog is not read, only the "Ok" button text is read.

Speech Viewer Log from Chrome 84 beta
An embedded page on this page says  dialog
OK  button  1 of 1

### Expected behavior:
The dialog should be announced and the content of the dialog should be read

Speech Viewer Log from Firefox 78.0.2 for comparison
dialog  Hello! I am an alert box!
OK  button

Speech Viewer Log from Chrome 75 for comparison
An embedded page on this page says  dialog  row 1  column 1
OK  button  row 1  column 1
alert  Hello! I am an alert box!  row 1  column 1

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Chrome 84 beta
Chrome 75
Firefox 78.0.2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Brian1Gaff** [comment] 2020-07-18 07:54
That page is  a mess in Waterfox, I just hear all the html code and hitting 
the button goes into edit mode with nothing spoken.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by zersiax** [comment] 2020-07-22 11:13
Confirmed. You can use object nav to navigate to the text, but it would be more ideal if this text is read automatically.

**Comment by addamsviz** [comment] 2020-07-24 16:15
Confirmed this is an issue.  We have a number of clients that are pointing out that our alert messages are not being read.  Hopefully this can be fixed. We are having to tell clients that this is out of our hands because it is a native browser alert that we cannot control.

**Comment by Adriani90** [comment] 2020-07-24 21:39
cc: @aleventhal, @ObjectInSpace is there any bug in Chromium related to this? Or does this need to be fixed in NVDA?

maybe @derekriemer has also some thoughts for a possible solution.

**Comment by kpeterson85** [comment] 2020-10-01 12:24
I've confirmed we still experience this in Chrome beta 86.0.4240.68 and NVDA 2020.2

**Comment by aleventhal** [comment] 2020-10-01 17:04
+Jacobo Aragunde Pérez <jaragunde@igalia.com> I think you're working on
this one, correct?

Aaron

**Comment by jaragunde** [comment] 2020-10-02 06:38
Yes, it's in my queue; it's https://crbug.com/779501. I'll bump its priority.

**Comment by kpeterson85** [comment] 2021-01-06 13:32
I've confirmed we still experience this in Chrome beta 88.0.4324.50 and NVDA 2020.3

I saw in the crbug link that on 12/4/2020 the issue received the label ReleaseBlock-Stable M-89. Does that mean a Chrome fix is planned for Chrome 89?

**Comment by jaragunde** [comment] 2021-01-11 13:40
One clarification; the linked issue [779501](https://crbug.com/779501) was about dialogs not being announced *at all*, which is not happening any more. I've opened a new issue as https://crbug.com/1164927.

**Comment by ABuffEr** [comment] 2021-02-12 12:17
Hi,
I get same issue in Firefox 85.0.2 and NVDA version alpha-21746,dcf3a325, only Ok button is spoken, even if alert text is reachable via object navigation.
So, it' not seems browser dependent.

**Comment by Adriani90** [comment] 2021-02-12 14:19
cc: @jcsteh

**Comment by jcsteh** [comment] 2021-02-14 22:18
Can't reproduce in Firefox. When I press the Try it button, NVDA says:

The page at https://www.w3schools.com says: dialog
Hello! I am an alert box!
OK button

**Comment by jcsteh** [comment] 2021-02-14 22:19
Note that if you have disabled report object descriptions in NVDA's Object presentation settings, the alert message won't be read even in Firefox, since dialog messages are the "description" of a dialog.

**Comment by ABuffEr** [comment] 2021-02-15 09:19
> Note that if you have disabled report object descriptions in NVDA's Object presentation settings, the alert message won't be read even in Firefox, since dialog messages are the "description" of a dialog.

Thanks! It was exactly my problem, sorry for wrong reporting :)

**Comment by kpeterson85** [comment] 2021-04-22 13:23
@jaragunde Thank you for the update. I see there has been ongoing comments with the most recent issue you opened (https://crbug.com/1164927). Are you able to provide some details on the status of it and when a fix might be released?

**Comment by jaragunde** [comment] 2021-04-23 13:42
There was a box with role "alert" inside the dialog, confusing ATs; removing it seems to have fixed the problem. The fix is included in the Chrome 90 release.

**Comment by Adriani90** [comment] 2023-03-05 21:39
This seems fixed since Google Chrome 102. It works as expected with NVDA alpha-27795,9ea9af61 (2023.2.0.27795)
 and Chrome 110. closing as works for me.

**Closed by Adriani90** 2023-03-05 21:39 UTC
Labels: close/worksforme
