### ISSUE TITLE
No external synth drivers work in latest alpha version

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#12400] opened 2021-05-11 17:07 UTC
### Steps to reproduce:

1. Install the latest alpha.
2. Install a synth driver that is not part of the built-in ones, like the Vocalizer for NVDA add-on from Tiflotechnia, either the 3.0 or 2.1 version.
3. Try to switch to it.

### Actual behavior:

The synth driver won't load. In the logs, I see:

```
ERROR - globalPluginHandler.initialize (18:56:25.621) - MainThread (11084):
Error initializing global plugin <class 'globalPlugins.vocalizer_globalPlugin.GlobalPlugin'>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 33, in initialize
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer-driver\globalPlugins\vocalizer_globalPlugin\__init__.py", line 99, in __init__
    with VocalizerOpened():
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer-driver\globalPlugins\vocalizer_globalPlugin\utils.py", line 15, in __enter__
    if speech.getSynth().name != vocalizer.SynthDriver.name:
AttributeError: module 'speech' has no attribute 'getSynth'
INFO - core.main (18:56:26.029) - MainThread (11084):
NVDA initialized
ERROR - synthDriverHandler.getSynthList (18:57:04.631) - MainThread (11084):
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 402, in getSynthList
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer-driver\synthDrivers\vocalizer\__init__.py", line 55, in check
    synth = speech.getSynth()
AttributeError: module 'speech' has no attribute 'getSynth'
ERROR - synthDriverHandler.getSynthList (18:57:04.665) - MainThread (11084):
Error while importing SynthDriver eloquence
Traceback (most recent call last):
  File "synthDriverHandler.pyc", line 397, in getSynthList
  File "synthDriverHandler.pyc", line 386, in _getSynthDriver
  File "importlib\__init__.pyc", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\marco\AppData\Roaming\nvda\addons\codefactory-py3\synthDrivers\eloquence.py", line 25, in <module>
    class SynthDriver(tts.genericSynthDriver):
  File "C:\Users\marco\AppData\Roaming\nvda\addons\codefactory-py3\synthDrivers\eloquence.py", line 39, in SynthDriver
    speech.IndexCommand,
AttributeError: module 'speech' has no attribute 'IndexCommand'

```

### Expected behavior:

Synth drivers should still load.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:
NVDA version alpha-22683,a794a4ee

#### Windows version:
10.0 20H2
#### Name and version of other software in use when reproducing the issue:
NVDA Vocalizer synth add-on.
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Earlier alphas before #12251 .
#### If add-ons are disabled, is your problem still occurring?
No, because it is a breaking change with add-ons that is causing the problem.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by MarcoZehe** [comment] 2021-05-11 17:14
To be exact, the last working alpha is alpha-22646,a2a6e23f.

**Comment by feerrenrut** [comment] 2021-05-12 03:17
This was caused by a change in API. Devs see: PR #12251 
It is great to have people testing alpha and reporting issues, but please be aware alpha is not intended to be 100% stable, this is especially true for the compatibility breaking releases (the 20xx.1 releases). 

Our recommendation is to use the stable release in production environments, or at the very least have it available as a fallback.
If there are no objections, I'll close this issue.

Thanks for reporting @MarcoZehe

**Closed by feerrenrut** 2021-05-12 03:17 UTC
