### ISSUE TITLE
 Internet Explorer 11 64 bit on windows 7

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#6450] opened 2016-10-11 15:56 UTC
Issue
 Internet Explorer 11 64 bit on windows 7
 the option in the browse dialogue, Automatic focus mode for caret movement
seems to be stuck on unchecked even though you can check and uncheck it. Ie it remains set as if it is not checked.
 It does not, for example, allow one to cursor over an edit box without getting stuck in it, which would equate to this being unchecked.
 The function is fine in firefox.

Tested on nvda 2016.3 and recent snapshots from the master branch.
 Note the Next branch at the time of writing also gives an error when going in and out of the edit or focus mode under the above conditions, but once again, Firefox is OK in this regard.

Here is the log from next.
 INFO - **main** (16:03:45):
Starting NVDA
INFO - core.main (16:03:46):
Config dir: C:\Users\Brian\AppData\Roaming\nvda
DEBUG - core.main (16:03:46):
setting language to Windows
INFO - core.main (16:03:46):
NVDA version next-13627,769531bb
INFO - core.main (16:03:46):
Using Windows version 6.1.7601 service pack 1 workstation
INFO - core.main (16:03:46):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (16:03:46):
Using comtypes version 0.6.2
DEBUG - core.main (16:03:46):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Listing add-ons from C:\Users\Brian\AppData\Roaming\nvda\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\easyTableNavigator
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on easyTableNavigator
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Disabling add-on easyTableNavigator
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on extendedWinamp
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on fakeClipboardAnouncement
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\goldenCursor
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on goldenCursor
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on goldwave
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on objPad
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on resourceMonitor
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Loading add-on from C:\Users\Brian\AppData\Roaming\nvda\addons\speechPlayerInEspeak
DEBUG - addonHandler._getAvailableAddonsFromPath (16:03:46):
Found add-on speechPlayerInEspeak
DEBUG - core.main (16:03:46):
Initializing appModule Handler
DEBUG - addonHandler.Addon.addToPackagePath (16:03:46):
Addon extendedWinamp added to appModules package path
DEBUG - addonHandler.Addon.addToPackagePath (16:03:46):
Addon goldwave added to appModules package path
DEBUG - core.main (16:03:46):
Initializing NVDAHelper
DEBUG - core.main (16:03:46):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
Loading speech dictionary 'C:\Users\Brian\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
file 'C:\Users\Brian\AppData\Roaming\nvda\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
3 loaded records.
DEBUG - core.main (16:03:46):
Initializing speech
DEBUG - addonHandler.Addon.addToPackagePath (16:03:46):
Addon speechPlayerInEspeak added to synthDrivers package path
INFO - synthDrivers.espeak.SynthDriver.__init__ (16:03:46):
Using eSpeak version 1.48.15  16.Apr.15
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
Loading speech dictionary 'C:\Users\Brian\AppData\Roaming\nvda\speechDicts\espeak-english.dic'...
DEBUG - speechDictHandler.SpeechDict.load (16:03:46):
file 'C:\Users\Brian\AppData\Roaming\nvda\speechDicts\espeak-english.dic' not found.
INFO - synthDriverHandler.setSynth (16:03:46):
Loaded synthDriver espeak
INFO - core.main (16:03:46):
Using wx version 3.0.2.0 msw (classic)
DEBUG - core.main (16:03:46):
Initializing braille
INFO - braille.initialize (16:03:46):
Using liblouis version 3.0.0
INFO - braille.BrailleHandler.setDisplayByName (16:03:46):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (16:03:46):
Initializing braille input
INFO - brailleInput.initialize (16:03:46):
Braille input initialized
DEBUG - core.main (16:03:46):
Initializing displayModel
DEBUG - core.main (16:03:46):
Initializing GUI
DEBUG - core.main (16:03:46):
initializing Java Access Bridge support
WARNING - core.main (16:03:46):
Java Access Bridge not available
DEBUG - core.main (16:03:46):
Initializing winConsole support
DEBUG - core.main (16:03:46):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (16:03:46):
UIAutomation: IUIAutomation
DEBUG - core.main (16:03:47):
Initializing IAccessible support
DEBUG - core.main (16:03:47):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (16:03:47):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (16:03:47):
No user gesture map
DEBUG - core.main (16:03:47):
Initializing keyboard handler
DEBUG - core.main (16:03:47):
initializing mouse handler
DEBUG - core.main (16:03:47):
Initializing touchHandler
DEBUGWARNING - touchHandler.initialize (16:03:47):
Touch only supported on Windows 8 and higher
DEBUG - core.main (16:03:47):
Initializing global plugin handler
DEBUG - addonHandler.Addon.addToPackagePath (16:03:47):
Addon fakeClipboardAnouncement added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (16:03:47):
Addon goldenCursor added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (16:03:47):
Addon objPad added to globalPlugins package path
DEBUG - addonHandler.Addon.addToPackagePath (16:03:47):
Addon resourceMonitor added to globalPlugins package path
DEBUG - core.main (16:03:47):
Initializing core pump
DEBUG - core.main (16:03:47):
Initializing watchdog
DEBUG - core.main (16:03:47):
initializing updateCheck
INFO - core.main (16:03:47):
NVDA initialized
DEBUG - core.main (16:03:47):
entering wx application main loop
IO - speech.speak (16:03:47):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - inputCore.InputManager.executeGesture (16:03:49):
Input: kb(desktop):alt+tab
IO - speech.speak (16:03:49):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Web Search - Internet Explorer  icon  1 of 9']
IO - speech.speak (16:03:50):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Web Search - Internet Explorer']
DEBUG - treeInterceptorHandler.update (16:03:51):
Adding new treeInterceptor to runningTable: <virtualBuffers.MSHTML.MSHTML object at 0x05741330>
IO - speech.speak (16:03:51):
Speaking [LangChangeCommand ('en_GB'), u'table']
IO - speech.speak (16:03:51):
Speaking [LangChangeCommand ('en_GB'), u'row 1  column 1']
IO - speech.speak (16:03:51):
Speaking [LangChangeCommand ('en_GB'), u'heading']
IO - speech.speak (16:03:51):
Speaking [LangChangeCommand ('en_GB'), u'StartPage', u'graphic', u'link', u'heading  level 1']
IO - speech.speak (16:03:51):
Speaking [LangChangeCommand ('en_GB'), u'StartPage Web Search']
DEBUG - queueHandler.registerGeneratorObject (16:03:51):
Adding generator 1
IO - speech.speak (16:03:51):
Speaking [IndexCommand(1), LangChangeCommand ('en_GB'), u'heading  level 1', u'link', u'graphic', u'StartPage']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(2), LangChangeCommand ('en_GB'), u'link', u'the world\u2019s ', u'most private', u' search engine']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(3), LangChangeCommand ('en_GB'), u'edit']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(4), LangChangeCommand ('en_GB'), u'button', u'GO']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(5), LangChangeCommand ('en_GB'), u'enhanced by ']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(6), LangChangeCommand ('en_GB'), u'link', u'Add to ', u'IE', u'link', u' Set as Home ']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(7), LangChangeCommand ('en_GB'), u'How we protect you ']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(8), LangChangeCommand ('en_GB'), u'heading  level 2', u'Congratulations!']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(9), LangChangeCommand ('en_GB'), u'The first thing you will find here is your search privacy.']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(10), LangChangeCommand ('en_GB'), u'link', u'www.startpage.com section-feat\u2026']
IO - speech.speak (16:03:51):
Speaking [IndexCommand(11), LangChangeCommand ('en_GB'), u'list with 3 items', u'heading  level 3', u'Search, Find & Surf! Privacy friendly.']
IO - inputCore.InputManager.executeGesture (16:03:54):
Input: kb(desktop):downArrow
IO - speech.speak (16:03:54):
Speaking [LangChangeCommand ('en_GB'), u'link', u'the world\u2019s ', u'most private', u' search engine']
IO - inputCore.InputManager.executeGesture (16:03:57):
Input: kb(desktop):downArrow
IO - speech.speak (16:03:57):
Speaking [LangChangeCommand ('en_GB'), u'edit', u'space']
IO - speech.speak (16:03:57):
Speaking [LangChangeCommand ('en_GB'), u'edit']
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:57):
Fetching parents starting from enclosingElement
ERROR - eventHandler.executeEvent (16:03:57):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05773E70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "browseMode.pyc", line 1340, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects__init__.pyc", line 892, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 369, in speakObject
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 445, in getTextWithFields
  File "NVDAObjects\UIA__init__.pyc", line 330, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (16:03:59):
Input: kb(desktop):downArrow
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:59):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:59):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:59):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:03:59):
Fetching parents starting from enclosingElement
ERROR - scriptHandler.executeScript (16:03:59):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05773E70>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 445, in getTextWithFields
  File "NVDAObjects\UIA__init__.pyc", line 330, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (16:04:03):
Input: kb(desktop):tab
IO - speech.speak (16:04:03):
Speaking [LangChangeCommand ('en_GB'), u'GO', u'button']
IO - inputCore.InputManager.executeGesture (16:04:08):
Input: kb(desktop):upArrow
IO - speech.speak (16:04:08):
Speaking [LangChangeCommand ('en_GB'), u'edit']
IO - speech.speak (16:04:08):
Speaking [LangChangeCommand ('en_GB'), u'edit']
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:08):
Fetching parents starting from enclosingElement
ERROR - eventHandler.executeEvent (16:04:08):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05761DF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "browseMode.pyc", line 1340, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects__init__.pyc", line 892, in event_gainFocus
  File "NVDAObjects__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 369, in speakObject
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 445, in getTextWithFields
  File "NVDAObjects\UIA__init__.pyc", line 330, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (16:04:10):
Input: kb(desktop):upArrow
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:10):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:10):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:10):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:10):
Fetching parents starting from enclosingElement
ERROR - scriptHandler.executeScript (16:04:10):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05761DF0>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 445, in getTextWithFields
  File "NVDAObjects\UIA__init__.pyc", line 330, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (16:04:11):
Input: kb(desktop):downArrow
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:11):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:11):
rootElement: edit
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:11):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (16:04:11):
Fetching parents starting from enclosingElement
ERROR - scriptHandler.executeScript (16:04:11):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionMSHTMLIAccessible object at 0x05761DF0>> with gesture u'down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\UIA__init__.pyc", line 445, in getTextWithFields
  File "NVDAObjects\UIA__init__.pyc", line 330, in _getTextWithFieldsForUIARange
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (16:04:14):
Input: kb(desktop):control+alt+r
DEBUGWARNING - RPC process 4252 (conhost.exe) (16:04:14):
Thread 3532, build\x86_64\remote\ia2Support.cpp, installIA2Support, 86:
Error registering class object, code -2147221008

IO - speech.speak (16:04:14):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (16:04:14):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (16:04:14):
Speaking [LangChangeCommand ('en_GB'), u'80 space', u'blank']
INFO - core.main (16:04:14):
Exiting
DEBUG - core._terminate (16:04:14):
Terminating updateCheck
DEBUG - core._terminate (16:04:14):
Terminating watchdog
DEBUG - core._terminate (16:04:14):
Terminating global plugin handler
DEBUG - core._terminate (16:04:14):
Terminating gui
INFO - config.ConfigManager.save (16:04:14):
Base configuration saved
DEBUG - core.main (16:04:14):
calling lose focus on object with focus
DEBUG - core._terminate (16:04:14):
Terminating treeInterceptorHandler
DEBUG - treeInterceptorHandler.killTreeInterceptor (16:04:14):
Killed treeInterceptor: <virtualBuffers.MSHTML.MSHTML object at 0x05741330>
DEBUG - core._terminate (16:04:14):
Terminating IAccessible support
DEBUG - core._terminate (16:04:14):
Terminating UIA support
DEBUG - core._terminate (16:04:14):
Terminating winConsole support
DEBUG - core._terminate (16:04:14):
Terminating Java Access Bridge support
DEBUG - core._terminate (16:04:14):
Terminating app module handler
DEBUG - core._terminate (16:04:14):
Terminating NVDAHelper
DEBUG - core._terminate (16:04:14):
Terminating touchHandler
DEBUG - core._terminate (16:04:14):
Terminating keyboard handler
DEBUG - core._terminate (16:04:14):
Terminating mouseHandler
DEBUG - core._terminate (16:04:14):
Terminating inputCore
DEBUG - core._terminate (16:04:14):
Terminating brailleInput
DEBUG - core._terminate (16:04:14):
Terminating braille
DEBUG - core._terminate (16:04:14):
Terminating speech
DEBUG - core._terminate (16:04:14):
Terminating addonHandler
DEBUG - core.main (16:04:15):
core done
INFO - __main__ (16:04:15):
NVDA exit

I see no add on causing problems in this log.

**Comment by jcsteh** [comment] 2016-10-12 02:44
I suspect this might be a regression introduced by #6271. I shall investigate.

**Comment by Brian1Gaff** [comment] 2016-10-12 06:11
I have a feeling there are in fact two different causes one for the 
regression of that checkbox and the other for the errors seen in next but 
not in master.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2016-10-12 08:45
Further tests prove that this same thing is happening on the 32 bit version 
of Internet Explorer as well.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2016-10-12 14:51
For the record it does not have this problem in the venerable old IE8 in xp.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment] 2016-11-02 03:46
There are two issues here:

1. Automatic focus mode for caret movement not working:
 * This is actually a regression introduced in NVDA 2015.4 by #4174 (a87940f0) where we switched to UI Automation for editable text fields in IE.
 * The option partially works in that it does correctly switch to focus mode when the caret moves inside an edit field. (If this was disabled, it would stay in browse mode.) The problem is that it doesn't switch back to browse mode when you hit the edge of the field.
 * The problem is that we don't detect when a cursor movement command hits the edge of the field. This would probably be fixed by #5991, but that breaks backspace in some UIA controls.
 * Our understanding is that this option isn't used by many users.
 * Prioritising as p3 because this is not a commonly used option and it isn't a regression from the last two versions.
2. Exception in next (E_FAIL somewhere in `_getTextWithFieldsForUIARange`):
 * @MichaelDCurran is investigating this. I suspect a regression introduced by #6271, but I'm not sure.

**Comment by Brian1Gaff** [comment] 2016-11-03 08:34
Well, I find the  mode very useful on unknown pages, to get a feel for the 
layout without keeping getting stuck and having to exit the field or worse, 
move some combo box without meaning to. This is my default way of working 
now, but as most of the time I use Firefox and that works as expected, I 
find IE is only used on some sites where it often easier to get at say, 
audio files real addresses with that browser than it is with the current 
Firefox versions.
 It is certainly odd.
 I'm not too worried about the error as this is only seen in next at 
present.
 I posted in the dev list which version of nvda had the last working 
version of the move focus with caret movement. I think it was 2015.2 and .3 
broke it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment] 2016-11-03 10:05
With that option disabled, you shouldn't get thrown into focus mode unless you press enter or move the focus with tab, etc. There are some rare occasions where this happens, but that's not intentional. If you're seeing that behaviour constantly, that's very concerning, though it should be addressed separately. See #2039.

**Comment by Brian1Gaff** [comment] 2016-11-06 13:56
No with it disabled in IE it works as you say, but of course then in 
firefox, you get stuck in an auto edit area, and need to esc out to browse 
mode.
 I suppose an application specifice choice change might be good to fix this.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment] 2016-11-06 22:00
With that option disabled in Firefox, I don't get switched to focus mode
automatically unless I press tab to focus or the page focuses a field when
it loads (e.g. Google). This is the expected behaviour. There are some rare
circumstances where it will throw you into focus mode when it shouldn't,
but they should be very rare. It sounds like you're seeing this behaviour
always? If so, please do comment on #2039; that is very concerning.

**Comment by Brian1Gaff** [comment] 2016-11-07 08:45
Hmm, I'll have to sit down and work out a logical test of all the variations 
here so I can see what is really going on.
 At present all I can say is that in my old xp both browsers behave as I 
would have expected on the various settings, but 7 and 10 do not.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by bhavyashah** [comment] 2017-08-04 10:47
@Brian1Gaff In https://github.com/nvaccess/nvda/issues/6450#issuecomment-258776888, you said that you would conduct more diagnostic tests. Could you please update us about the results of those and the current standing of the issue(s) reported in this ticket?

**Comment by Adriani90** [comment] 2018-07-28 07:53
I cannot reproduce this issue with NVDA2018.2.1 on Windows 10 and IE11.
Can anyone still see this issue?

**Comment by Brian1Gaff** [comment] 2019-01-19 08:04
Not that I can see. IE 11 is not being used by me, but a quick check seems 
to suggest things are working normally. Anyone else got any comments?
 It was back in 2016 after all.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment] 2019-01-19 19:56
Closing as works for me. If the issue comes up again, please feel free to comment on it and we will reopen it.

**Closed by Adriani90** 2019-01-19 19:56 UTC
Labels: p3, regression, worksforme
