### ISSUE TITLE
Use windowUtils.CustomWindow class foor dll based braille display drivers

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6719] opened 2017-01-11 06:29 UTC
Although a trivial change, I think it would make DLL based braille display drivers more readable if we use windowUtils.CustomWindow to handle received messages from dll's. This would apply to the following drivers:

* Hims
* syncBraille
* freedomScientific

**Comment by jcsteh** [comment] 2017-01-11 22:36
It would, but the change is fairly significant and could thus cause unexpected regressions. The change would need to be made and tested extensively by people with access to those displays. We can't justify allocating resources to this if it's just this alone, as it has no actual benefit to the user. That said, if someone is working on one of these drivers, it'd probably make sense to make the change.

I'm closing this, since we wouldn't be working on this as a stand-alone chunk of work.

**Closed by jcsteh** 2017-01-11 22:36 UTC
