### ISSUE TITLE
Include editable section HTML elements in ‘e’ edit field single letter navigation key

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7168] opened 2017-05-12 03:42 UTC
Often, in complex online editors and blogging sites, there is an element that NVDA reads as ‘section editable’ in which text can be entered and edited. These seem to be usually more advanced edit fields because they can convert URLs to their hyperlinked title, handle HTML tags, etc.
As an example of said control, if you have an account on quora.com, type something in the initial Ask and Search Quora edit box, and then arrow down until you land on ‘section editable’ and observe that it performs the basic functions of an edit field fundamentally. Also, experimentally observe that pressing ‘e’ on the webpage does not jump to the aforesaid editable section. There is a similar editable but excluded control when I edit or add a blog post on Wordpress too.
Ideally, since this is an editable control, pressing ‘e’ should jump to editable sections as well.

**Comment by jcsteh** [comment] 2017-05-12 06:01
Duplicate of #5534.

**Closed by jcsteh** 2017-05-12 06:01 UTC
