### ISSUE TITLE
Provide ability to jump between list items at the same level

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11069] opened 2020-04-29 15:06 UTC
### Is your feature request related to a problem? Please describe.

In places such as Reddit and hackernews, it would be extremely convenient if there was a version of the i key which did not take into account child list items. This would rapidly allow for jumping to the next list item while skipping child lists.

### Describe the solution you'd like

Provide some method of moving between list items at the same level (i.e, only siblings)

### Describe alternatives you've considered

There's a browser nav add-on which does alleviate this in some circumstances but it is based off the offsets of elements though.

**Comment by feerrenrut** [comment] 2020-04-29 15:22
To generalize this feature, a command could be added to jump to the next item matching the current item. So if you are on a level 2 list item, jumps to the next level 2 list item. If on a level 2 heading, to the next level 2 heading. Though it raises the question of what to do with multiple matches, EG a link and a level 2 list item. Perhaps it should only apply to hierarchical items EG: unordered list items, ordered list items, heading levels. Are there others I'm not thinking of?

I agree that this should only move between siblings. If the list ends or, the heading levels change, the user should be informed. There is lots of UX detail in this proposal that needs to be worked out, I'd like to see that expanded on so we can agree where this is headed before this is worked on.

UX questions:
- What do you call this command?
- How does it announce reaching the limits (first/last). Consider both speech and braille.
- Should any indication be given about what is skipped? 

Implementation note: lists are likely to be much easier than headings. I would expect headings to be handled in a followup PR.

**Comment by DrSooom** [comment] 2020-04-29 16:43
Duplicate of issue #8193.

**Comment by feerrenrut** [comment] 2020-04-30 14:04
Ah thanks @DrSooom I'm not familiar with #8193. Are my questions and considerations already answered there or do I need to copy over the relevant parts. Either way I will close this issue.

**Closed by feerrenrut** 2020-04-30 14:04 UTC
Labels: feature, feature/browse-mode, ux

**Comment by Adriani90** [comment] 2020-04-30 14:56
At least for headings there is already something in place. Pressing 2 on the keyboard in browse mode will jump between headings level 2, 3 for level 3 etc. maybe shift+numbers in browse mode should jump between list levels. I.e. shift+2 for list item level 2.

**Comment by DrSooom** [comment] 2020-04-30 15:32
@Adriani90: Shift+1 to Shift+6 already invert the order (bottom to top instead of top to bottom). Please continue the discussion in issue #8193. Thanks.

@feerrenrut: I'll take a look on this soon.
