### ISSUE TITLE
NVDA is incorrectly announcing switch as "checkbox".

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13647] opened 2022-04-28 00:00 UTC
### Steps to reproduce:
1. Turn on NVDA.
2. Open URL: https://codepen.io/testaccount01/pen/oNprxEd.
3. Navigate to switch control in the preview pane.
4. Observe that NVDA is announcing the switch control as "checkbox".

### Actual behavior:
NVDA is incorrectly announcing "checkbox" for a switch control defined with role="switch".

### Expected behavior:
NVDA should provide correct information as "switch" for the input control defined with role="switch" instead of checkbox.

### Note:
JAWS and Narrator is correctly announcing the control as "switch" with state "Off" and "Pressed on" (JAWS)/ "On" (Narrator).

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version 2021.3.5

#### Windows version:
OS: Windows 11 Version 21H2 Build 22000.613

#### Does the issue still occur after restarting your computer?
Yes

**Comment by OzancanKaratas** [comment] 2022-04-28 00:29
I cannot reproduce this issue. Please disable your add-ons and try again.

The check box is reported as expected.

**Comment by mazen428** [comment] 2022-04-28 04:23
That's the issue though, it should be reported as a switch not a checkbox

**Comment by CyrilleB79** [comment] 2022-04-28 09:43
Hi
I did not go in the details, but #11310 and #12306 seem to be related.
If this issue is a duplicate of one of these two issues, please close it.

**Comment by alexarnaud** [comment] 2022-05-02 15:26
@CyrilleB79 You're right, we've 3 times the same issue.

I don't know who has the permission to close duplicate but I think we should close 2 of them to keep only one.

**Comment by CyrilleB79** [comment] 2022-05-03 07:00
> @CyrilleB79 You're right, we've 3 times the same issue.
> 
> I don't know who has the permission to close duplicate but I think we should close 2 of them to keep only one.

Cc @seanbudd, @feerrenrut 
According to @alexarnaud's confirmation, #11310 and #12306 are duplicates of this issue. Could you take care of closing two of them? Thanks.

**Comment by feerrenrut** [comment] 2022-05-04 03:17
Closing as a duplicate of #11310 which as more discussion.

**Closed by feerrenrut** 2022-05-04 03:17 UTC
