### ISSUE TITLE
NVDA in Firefox can't change options in this HTML list, but Narrator can

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#15604] opened 2023-10-11 09:44 UTC
### Steps to reproduce:

1. In Firefox, open the following URL: [https://powerdmarc.com/dkim-record-generator/](https://powerdmarc.com/dkim-record-generator/)
2. Attempt to adjust the "Key length" combobox/list.

### Actual behavior:

No method I could think of, from Alt+space followed by navigation on the expanded list, to space followed by navigation, to switching into focus mode and using object navigation, could change from the default option of 2048.
I even used object nav to open the field, and then tried mouse routing to select its options, which also fails.

[Speech Logger capture of attempts in Firefox](https://github.com/nvaccess/nvda/files/12867287/speech-log-ff-dkim.txt)

Here is another attempt, using just enter/alt+downArrow, and tab, like what works with Narrator. In this one, even though the 1024 option can be reached, none of the others can, and choosing it doesn't work.
[Attempting what works with Narrator](https://github.com/nvaccess/nvda/files/12867729/brokenComboBox2.txt)

### Expected behavior:

I would expect, as with Narrator, that the list's options become available and able to be selected.

In Narrator, just press enter on the combo, tab to the desired option, and press enter on it. In this case, I wanted 1024.

If you try the same thing in NVDA (not demonstrated in my log), it can work, but half the time the option selected is not the one you pressed enter on, and another percentage of the time there is no effect (see above for the latter).

I was slightly more successful in Brave (Chromium) initially, using a combination of browse commands and object nav in focus mode, but I could not come up with a successful STR there for either success or failure, it was so unreliable.

Obviously there is a coding issue with the page here, though Narrator doesn't seem to mind.

#### NVDA

Installed, version 2023.3beta3.

#### Windows version:

11 Home 22H2

#### Name and version of other software in use when reproducing the issue:

Firefox 118.0.1
Brave Browser 117.1.58.137

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by jcsteh** [comment] 2023-10-11 10:18
Note that this only works with Narrator in scan mode (akin to NVDA browse mode). NVDA browse mode is different, though, in that it doesn't render list box options. There are good reasons for this - it can clutter things a lot - but in this case, rendering them in scan mode is an advantage.

Unfortunately, NVDA+enter doesn't even work on these items because they contain text content, so NVDA assumes you want to activate the character at the review cursor rather than the entire object. That would probably be fixed by #15159.

This obviously isn't a solution, but just so you know, if you get to the right object with object navigation, you can use the Python console and do nav.doAction() to select it.

**Comment by burmancomp** [comment] 2023-10-11 11:37
It seems to be possible but complex to select desired alternative.

On key length combo box:

- enter
- down arrow
- tab

NVDA should speak now something like 1024... Then with object navigation, navigate to parent object. In this level there should be 3 text frames which corresponds to alternatives 1024, 2048 and 4096. Going inside any of them, there should be object saying corresponding key length, then inside it there should be text frame again, and inside it there should be keylength again.

Now pressing nvda+enter should change key length.

**Comment by seanbudd** [comment] 2024-04-29 02:09
Closing this issue as it appears to be an authoring issue with the web page.
To be able to process this issue, we need a minimum HTML sample that appears to have valid authoring.

**Closed by seanbudd** 2024-04-29 02:09 UTC
Labels: p2, app/firefox, triaged, blocked/needs-technical-investigation

**Comment by Adriani90** [comment] 2024-04-29 05:39
Hmm interesting that Narator can handle that list properly. According to my tests this is also an issue with Jaws, behaves even worse than NVDA in this case.
This issue is also reproducible in Chrome.
So yeah, it seems definitely something with bad authoring here.
