### ISSUE TITLE
NVDA cannot change or do anything with One Drive while syncing

### ISSUE THREAD

**Issue by KevanGP** [nvaccess/nvda#12522] opened 2021-06-06 16:12 UTC
NVDA does not work properly with One Drive when syncing, cannot do anything because the recent files list keeps changing and NVDA keeps jumping to it whenever I tab to settings, before I can activate the settings button.

**Comment by KevGP** [comment] 2021-06-06 16:17
One solution is to turn off my computer's Internet access when I want to change One Drive settings, close One Drive, or do anything else. But that's hardly a proper solution. It works but it's tedious.

**Comment by XLTechie** [comment] 2021-06-07 01:28
What if you turn off "report dynamic content changes" (nvda+5)?

**Comment by Adriani90** [comment] 2024-11-24 23:19
This is not reproducible in NVDA 2024.4.1 and last Onedrive version Build 24.211.1020.0001 (64-Bit).
Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-11-24 23:19 UTC
Labels: close/worksforme
