### ISSUE TITLE
Sapi4 icon won't go away from the synth menu

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4799] opened 2015-01-14 04:54 UTC
**Reported by mikebayus on 2015-01-14 04:54**
I installed the free trial of Text Speaker from Desk Share version 3.2 and I discovered that it installed the runtime for at&t natural voices.  I didn't like Text Speaker, so I uninstalled it, and uninstalled the at&t runtime package, but I found that I had a Sapi4 icon in my NVDA synth menu.  it wasn't there yesterday, but today it is.  How do I make it go away?  I tried populating the list of voices with LH Truevoice, and found that I could load them.  But when I uninstalled them, I still had the Sapi4 icon, and when I pressed O.K, I got the expected error message: "can not load synthesizer.  I ran Regedit, but could find nothing in the regestry that sayd anything about NVDA Sapi4.  How do I make it go away.

**Comment by leonardder** [comment] 2017-07-15 08:14
Seems like the sapi4 runtime didn't get cleaned up correctly. This is not a bug in NVDA, unless we should change the check method on the SynthDriver class. But since SAPI4 is very old anyway and it is not a live disrupting issue, closing as won't fix.

**Closed by leonardder** 2017-07-15 08:14 UTC
Labels: bug, Speech synth drivers
