### ISSUE TITLE
Nvda freezes for longer time when focusing large xml files in android studio

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#13120] opened 2021-12-02 09:00 UTC
### Steps to reproduce:
* Open Android studio with some project
* Focus some xml file which is large enough, mine is 2214 lines long.

### Actual behavior:
NVDA stops speaking and seems frozen for approximately 10 seconds. It is possible to work and edit the file after this time. NVDA log contains a lot of messages of this kind:

```
ERROR - unhandled exception (09:21:26.340) - MainThread (7624):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "JABHandler.pyc", line 691, in internal_event_stateChange
  File "JABHandler.pyc", line 335, in internalQueueFunction
  File "queue.pyc", line 190, in put_nowait
  File "queue.pyc", line 136, in put
queue.Full
ERROR - unhandled exception (09:21:26.341) - MainThread (7624):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "JABHandler.pyc", line 720, in internal_event_caretChange
  File "JABHandler.pyc", line 335, in internalQueueFunction
  File "queue.pyc", line 190, in put_nowait
  File "queue.pyc", line 136, in put
queue.Full
ERROR - unhandled exception (09:21:26.342) - MainThread (7624):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "JABHandler.pyc", line 720, in internal_event_caretChange
  File "JABHandler.pyc", line 335, in internalQueueFunction
  File "queue.pyc", line 190, in put_nowait
  File "queue.pyc", line 136, in put
queue.Full
```

### Expected behavior:
NVDA should work and let us to edit xml file immediately when is the file focused.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.2, tested also with older versions

#### Windows version:
Windows 10 21H1 (10.0.19043) workstation

#### Name and version of other software in use when reproducing the issue:
Android Studio Arctic Fox | 2020.3.1 Patch 3 

#### Other information about your system:
Thinkpad p14s gen2 (i7-1165G7 @ 2.80GHz, 16GB RAM)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same in previous version

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[log.txt](https://github.com/nvaccess/nvda/files/7640521/log.txt)

**Comment by PeterLecky** [comment] 2022-06-17 11:35
Hello,
This problem still exists, also with nvda 2022.2 beta.
Can I somehow help to track it?

**Comment by feerrenrut** [comment] 2022-07-07 06:47
There was some work done recently in this area, see #13039, it might be worth testing the latest NVDA alpha: https://www.nvaccess.org/files/nvda/snapshots/

**Comment by mwhapples** [comment] 2022-08-04 08:05
Having a quick think about this one I get the following thoughts and questions. The log entries posted makes it look like NVDA is getting flooded with events which fills up its event queue. Whether all these events are needed or relevant or whether NVDA should be discarding some of them may be a suitable approach to explore. I doubt any of the recent Java improvements would help with this if the cause is as I suspect.

**Comment by mwhapples** [comment] 2022-08-04 08:10
@PeterLecky could you provide a sample android project which causes this. Also when you say an XML file, is this any specific type of XML, in particular an Android view XML. I use IntelliJ frequently with NVDA and have not noticed such an issue, but I use it for desktop Java applications. So my thought is whether something like the preview for android XML views is firing all these events and not the XML text editor itself.

**Comment by PeterLecky** [comment] 2022-08-11 11:30
Hello,
Thank you for your time with this.
I actually found that the problem lies somewhere in configuration of my project. I created a new project and copied my large xml resource file to it and it works fine, no lagging, no messages in the log. Actually exploring quite large workspace.xml which is that file which probably causes this. Tried to copy it to my new project and problems arised also in it. So, i probably enabled somewhat somewhere in that forest of different settings in android studio which causes that flood of accessibility events. Will try to check it with someone sighted, may be that we will find that i enabled some nice visual feature which i do not need and have. ;)
Thanks again.
It still seems that something needs to be fixed somewhere, because that bunch of accessibility events is probably not okay in any case. I will write in case of some new info.

**Comment by mwhapples** [comment] 2022-08-11 11:39
> Hello, Thank you for your time with this. I actually found that the problem lies somewhere in configuration of my project. I created a new project and copied my large xml resource file to it and it works fine, no lagging, no messages in the log. Actually exploring quite large workspace.xml which is that file which probably causes this. Tried to copy it to my new project and problems arised also in it. So, i probably enabled somewhat somewhere in that forest of different settings in android studio which causes that flood of accessibility events. Will try to check it with someone sighted, may be that we will find that i enabled some nice visual feature which i do not need and have. ;) Thanks again. It still seems that something needs to be fixed somewhere, because that bunch of accessibility events is probably not okay in any case. I will write in case of some new info.

If you do find more out as to what causes the issue then do create a new issue for it. I agree with you there does seem to be some issue relating to that flood of accessibility events and if we can do something to prevent NVDA being the bottleneck then that would be good.

**Comment by seanbudd** [comment] 2022-08-12 01:23
Closing this issue as can't be reproduced.
If this can be reproduced, it will be re-opened

**Closed by seanbudd** 2022-08-12 01:23 UTC
Labels: bug/app-freeze, p1, component/java-access-bridge

**Comment by PeterLecky** [comment] 2022-10-11 07:14
This unfortunately didn't fix the problem. Tested with 
nvda_snapshot_alpha-25756,ba743746
Peter

**Comment by PeterLecky** [comment] 2022-10-11 07:56
Can I somehow log or may be see in nvda console that acc events and see 
more information about them? I tried to change logging level of nvda but 
nvda log does not contain more info about them.
Thank you

**Comment by seanbudd** [comment] 2022-10-11 23:47
@PeterLecky without steps to reproduce we still cannot re-open this issue.
You can enable more detailed logging via Preferences, Advanced, Debug logging.
I'm not sure if the `events` category will add helpful information, but it may be worth checking.

**Comment by PeterLecky** [comment] 2023-08-04 15:44
Hello,
I definitely found the problem. It seems that the problem happens when is the file structure tool visible. So
1. open some xml file
2. press alt+f1 and activate "file structure"
3. Nvda now starts to receive a lot of accessibility events and behavs as i described in the description above.
4. Wait few seconds until pc starts to be responsive and switch to other file and return back to large xml. Pc will freeze again and there will be again a lot of mentioned messages in NVDA log. 
5. Press f12 to switch to file structure, close it and problem will disappear.
