### ISSUE TITLE
edge chromium

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#9475] opened 2019-04-09 20:55 UTC
Hello. I installed the preview version of Microsoft Edge.
When I get into the edit box the browser does not respond. This happens with the Nvda enabled.
windows 10 18865
edge Version 75.0.124.0 (Official build) canary (64-bit)
nvda alpha-17029,4d2e7f2b

**Comment by Adriani90** [comment] 2019-04-09 21:16
Do you have a log file when the issue occurs? Could you please upload it to this issue?

**Comment by gdata1** [comment] 2019-04-09 21:22
Hello. Can download.

**Comment by gdata1** [comment] 2019-04-09 21:25
INFO - __main__ (00:23:07.595):
Starting NVDA
INFO - core.main (00:23:07.674):
Config dir: C:\Users\nikit\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (00:23:07.674):
Loading config: C:\Users\nikit\AppData\Roaming\nvda\nvda.ini
INFO - core.main (00:23:07.815):
NVDA version alpha-17029,4d2e7f2b
INFO - core.main (00:23:07.816):
Using Windows version 10.0.18865 workstation
INFO - core.main (00:23:07.816):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (00:23:07.816):
Using comtypes version 1.1.3
INFO - core.main (00:23:07.816):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - external:synthDrivers.RHVoice.SynthDriver.__init__ (00:23:07.993):
Using RHVoice version 0.7.1
INFO - synthDriverHandler.setSynth (00:23:08.005):
Loaded synthDriver RHVoice
INFO - core.main (00:23:08.005):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
INFO - brailleInput.initialize (00:23:08.005):
Braille input initialized
INFO - braille.initialize (00:23:08.005):
Using liblouis version 3.8.0
INFO - braille.BrailleHandler.setDisplayByName (00:23:08.005):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (00:23:08.045):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (00:23:08.055):
UIAutomation: IUIAutomation6
INFO - core.main (00:23:08.279):
NVDA initialized

**Comment by gdata1** [comment] 2019-04-09 21:26
Again. The problem only occurs when the Nvda is turned on.

**Comment by DrSooom** [comment] 2019-04-10 07:55
@gdata1: Please set the log level to "Debug" and upload the logfile here. Please don't post the content of a logfile as a comment. Thanks.

**Comment by gdata1** [comment] 2019-04-10 10:02
[nvda.log](https://github.com/nvaccess/nvda/files/3063176/nvda.log)

**Comment by DrSooom** [comment] 2019-04-10 12:46
Could you please disable the RHVoice add-on (or just change the TTS to eSpeak) and repeat the steps starting with launching Edge via the Windows Desktop? RHVoice produces quite a lot of errors. Thanks.

**Comment by gdata1** [comment] 2019-04-10 14:02
[nvda.log](https://github.com/nvaccess/nvda/files/3064164/nvda.log)
No. The problem is not gone.

**Comment by DrSooom** [comment] 2019-04-10 14:50
Okay, this logfile is a little bit easier to read – and with a disabled audio ducking feature it would be even better. So, see line 392, 463, 618 and especially beginning from line 679.
CC: @jcsteh and @michaelDCurran

**Comment by Adriani90** [comment] 2019-04-10 16:38
I think this is not related to the synthesizer. It is rather related to the offset of 0 which seems to be too big for buffer, here are the important parts of the log:

```
DEBUGWARNING - RPC process 8000 (msedge.exe) (16:59:11.211):
Thread 8976, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 1050:
Offset of 0 too big for buffer, returning false
```

```
IO - inputCore.InputManager.executeGesture (16:59:14.249):
Input: kb(laptop):control+shift+o
DEBUG - audioDucking.AudioDucker.disable (16:59:14.272):
Ignoring duplicate disable
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (16:59:14.434):
could not get IAccessible2::uniqueID to use as IA2UniqueID
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 611, in __init__
COMError: (-2147467259, '\xcd\xe5\xee\xef\xee\xe7\xed\xe0\xed\xed\xe0\xff \xee\xf8\xe8\xe1\xea\xe0', (None, None, None, 0, None))
```


```
IO - inputCore.InputManager.executeGesture (16:59:19.223):
Input: kb(laptop):downArrow
DEBUG - audioDucking.AudioDucker.enable (16:59:19.417):
ignoring duplicate enable
IO - inputCore.InputManager.executeGesture (16:59:19.677):
Input: kb(laptop):downArrow
DEBUG - audioDucking.AudioDucker.disable (16:59:19.757):
disabling
DEBUG - audioDucking._unensureDucked (16:59:19.757):
Queuing _unensureDucked
IO - inputCore.InputManager.executeGesture (16:59:20.278):
Input: kb(laptop):upArrow
DEBUGWARNING - watchdog._watcher (16:59:28.588):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\nikit\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1475, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 179, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 414, in speakObject
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 470, in expand
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 354, in _findUnitEndpoints
  File "NVDAObjects\IAccessible\__init__.pyc", line 161, in expand
  File "textInfos\offsets.pyc", line 458, in expand
  File "textInfos\offsets.pyc", line 437, in _getUnitOffsets
  File "NVDAObjects\IAccessible\__init__.pyc", line 272, in _getLineOffsets
  File "comtypes\__init__.pyc", line 857, in __call__

DEBUGWARNING - eventHandler.executeEvent (16:59:28.773):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x04F9D6F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\nikit\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 426, in event_gainFocus
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1475, in event_gainFocus
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
IO - inputCore.InputManager.executeGesture (16:59:29.907):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (16:59:31.132):
Input: kb(laptop):alt+tab
DEBUGWARNING - watchdog._watcher (16:59:38.987):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1202, in event_caret
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 183, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1438, in event_caret
  File "NVDAObjects\__init__.pyc", line 1007, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 94, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 202, in _findContentDescendant

DEBUGWARNING - eventHandler.executeEvent (16:59:39.058):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x04F9D6F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1202, in event_caret
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 183, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1438, in event_caret
  File "NVDAObjects\__init__.pyc", line 1007, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "watchdog.pyc", line 202, in _COMError_init
CallCancelled
DEBUGWARNING - RPC process 2000 (HxOutlook.exe) (16:59:40.917):
Thread 12468, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 121:
disabling IA2 support

DEBUGWARNING - watchdog._watcher (16:59:49.283):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1202, in event_caret
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 183, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1438, in event_caret
  File "NVDAObjects\__init__.pyc", line 1007, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 94, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 202, in _findContentDescendant
```

**Comment by Adriani90** [comment] 2019-04-10 16:38
I might be wrong, but it seems the freeze occurs after leaving the edit field with escape aand a link has been accessed with enter afterwards.

@gdata1 can you confirm?

Could you please do following?

1. Change NVDA language to englisch
2. Restart NVDA with disabled addons
3. Open Edge Canary and try to reproduce the issue
4. Open the log file and save it
5. Upload the file to this issue.

**Comment by PratikP1** [comment] 2019-04-10 17:10
Just to add a little more to this. Not sure if it will help. I'm able to work with edit fields without a problem with Edge Chromium 64 bit. Latest NVDA alpha and Windows 10 18362. I'm attaching the log with the results. These are only a few examples. I've been using the browser since Monday.

[NVDA log for Edge Chromium.log](https://github.com/nvaccess/nvda/files/3064982/NVDA.log.for.Edge.Chromium.log)

**Comment by DrSooom** [comment] 2019-04-10 17:11
@Adriani90: I knew that the RHVoice might not be the reason for this issue, but I just wanted to clean up the logfile a little bit. Just take a look at the first one and you see what I mean.

@gdata1: Therefore in addition to @Adriani90 mentioned steps, please disable audio ducking too. Thanks.

**Comment by gdata1** [comment] 2019-04-10 17:42
[nvda.log](https://github.com/nvaccess/nvda/files/3065086/nvda.log)
The problem does not disappear. I did all the steps

**Comment by gdata1** [comment] 2019-04-10 19:55
After disabling add-ons the problem does not disappear
[nvda.log](https://github.com/nvaccess/nvda/files/3065593/nvda.log)

**Comment by gdata1** [comment] 2019-04-12 13:17
Here is an example of the pages on which this happens most often.
https://vk.com/feed
https://www.youtube.com/feed/subscriptions

**Comment by leonardder** [comment] 2019-09-18 05:47
@gdata1 Does this issue still persist on the beta channel of Edge Chroimum?

**Comment by gdata1** [comment] 2019-09-18 08:29
@leonardder now this problem is very rare. She's been gone for the last week. I've tried all the edge chromium versions

**Comment by leonardder** [comment] 2019-11-28 09:53
I'm closing this. We can always reopen if this is still the case in stable versions ofr Edge Chromium.

**Closed by leonardder** 2019-11-28 09:53 UTC
