### ISSUE TITLE
NVDA reports inputs of `type="number"` in Firefox as unlabeled in the 'forms' elements list

### ISSUE THREAD

**Issue by 36degrees** [nvaccess/nvda#9675] opened 2019-06-05 12:35 UTC
### Steps to reproduce:

In Firefox, with an HTML document containing the following markup, open the elements list using NVDA + F7 and select the 'Form fields' type.

```html
<input type="text" id="text-field">
<label for="text-field">Text field</label>

<br><br>

<input type="number" id="number-field">
<label for="number-field">Number field</label>
```

([View in Codepen](https://codepen.io/36degrees/pen/joJovN))

### Actual behavior:

The elements list does not include the text from the label associated with the number field; instead reporting it as 'unlabeled':

- Text field; edit; has autocomplete
- Unlabeled; edit

<img width="1136" alt="Screen Shot 2019-06-05 at 13 23 01" src="https://user-images.githubusercontent.com/121939/58956489-560c4680-8796-11e9-9a78-9f4487e568b5.png">

Note that the label text _is_ read correctly when the form input is focused.

### Expected behavior:

The elements list should include both fields with the text from the associated label:

- Text field; edit; has autocomplete
- Number field; edit

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.1.1

#### Windows version:

Windows 10; Version 1607; Build 14393. (VirtualBox VM)

#### Name and version of other software in use when reproducing the issue:

Firefox 67.0.1

#### Other information about your system:

N/A

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

N/A

**Comment by bramd** [comment] 2019-06-07 17:46
I can reproduce this. It's not just a bug in the elements list, but also when the field has focus. In NVDA's object navigation I see the field as a spin button which has an edit field and two buttons inside. Those buttons are unlabeled, but decrease/increase the value.

When tabbing to the field NVDA reads the label correctly, since it reads the label of the parent control (the spin button) as well. However, when pressing nvda+tab it just reports the unlabeled edit field.

**Comment by bramd** [comment] 2019-06-07 18:22
CC @jcsteh

**Comment by gijsk** [comment] 2020-02-28 11:29
Can someone test if this is fixed with Firefox 74 ( https://beta.mozilla.org/ ) ? The implementation of `input type=number` is changing, cf. https://bugzilla.mozilla.org/show_bug.cgi?id=981248 .

**Comment by jcsteh** [comment] 2020-02-29 21:47
This is definitely fixed as part of https://bugzilla.mozilla.org/show_bug.cgi?id=981248 .

**Closed by jcsteh** 2020-02-29 21:47 UTC
