### ISSUE TITLE
A particular web page: Table navigation reports "not in the table cell"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5366] opened 2015-09-15 02:37 UTC
**Reported by surfer0627 on 2015-09-15 02:37**
Hi,
Here is a test page:
https://www.apple.com/voiceover/info/guide/_1131.html
STR:
1. Press h and hear "General commands"
2. Press down arrow until hear "cell Turn VoiceOver on or off"
3. Press Ctrl+alt+right arrow and hear "not in the table cell"
4. Press ,(comma) and hear "out of table"
Is this a web design issue or a NVDA issue.
Thanks.

notes: Jaws table navigation could work on this page.

**Comment by surfer0627** [comment] 2017-03-21 03:54
Hi,
Here is another table navigation test case:
http://webcall.ntpc.gov.tw/PhoneBook2.html
1. Press pageDown three times.
2. Press ctrl+alt+leftArrow
NVDA report: row16
3. Press , to move past end of container
NVDA report: not in a container

**Comment by feerrenrut** [comment] 2017-03-28 10:17
I think I can reproduce the described behaviour in Chrome with the STR from the original description of the issue (with the Apple web page).

However, I think I might be misunderstanding something here. @surfer0627 Can you please outline the expected behaviour? Were you using Internet Explorer in both cases?

For those that were not aware (or need a reminder):  Comma moves past the end of the container (list, table, etc.) where the caret is positioned. From the [nvda user guide](https://www.nvaccess.org/files/nvda/documentation/userGuide.html#toc41)

**Comment by surfer0627** [comment] 2017-03-29 00:55
> Can you please outline the expected behaviour? Were you using Internet Explorer in both cases?

Yes, I use Internet Explorer in  both cases.
In case1 (Apple web page), table navigation commands and , are unavailable.
In case2, single navigation command (t ,) are not working.

**Comment by ehollig** [comment] 2018-08-08 02:10
I can reproduce this issue for both cases in Internet Explorer 11. Both example tables are working as expected using Firefox, Chrome and Edge. I am interested to hear if @feerrenrut is still able to reproduce the one issue in Chrome. As this issue is specific to Internet Explorer, I am unsure if it will be fixed.

**Comment by feerrenrut** [comment] 2018-08-13 08:32
@ehollig I am not able to reproduce this on Chrome `68.0.3440.106 `

**Comment by Adriani90** [comment] 2019-02-02 00:36
It seems IE interprets this like a layout table. If you enable layout tables in browse mode settings, the table navigation, as well as (t and ,) are working correctly in IE11. @feerrenrut I think there was a quite similar issue months ago. This is issue #7913. Is your explanation from that issue maybe also related to this one? In that case I think we could close this one as well.

**Comment by Adriani90** [comment] 2023-03-09 00:50
I am closing this one since it was most probably a web authoring issue as explained in #7913. IE support ended in 2022 and for the IE mode in Edge for backwards compatibility I don't expect significant accessibility updates comming soon.

**Closed by Adriani90** 2023-03-09 00:50 UTC
Labels: bug, app/internet-explorer
