### ISSUE TITLE
Plain text being identified incorrectly as clickable

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#6069] opened 2016-06-15 02:40 UTC
Using Chrome Canary on the standard GMail web site:
open a message and activate browse mode to review the content.
Notice that following the header info that pressing down arrow to read the first line or two of text will cause NVDA to speak "clickable" when in fact it is only plain text being read.

**Comment by mjanusauskas** [comment] 2016-06-16 15:58
Another example of this can be seen on this page - specifically the items in the unordered lists:
http://9to5mac.com/2016/06/13/ios-10-features-developers/

**Comment by bhavyashah** [comment] 2017-07-29 08:15
@mjanusauskas  Can you still reproduce this issue using the latest stable release of Chrome on the page http://9to5mac.com/2016/06/13/ios-10-features-developers/, because I cannot.
Please re-investigate and check whether this ticket is relevant to Project Webfix. @jcsteh @feerrenrut

**Comment by mjanusauskas** [comment] 2017-08-18 15:24
Yes I can still reproduce it.

**Comment by ehollig** [comment] 2017-08-19 23:05
I am able to replicate this in Chrome. Firefox and Internet Explorer do not report clickable though

**Comment by sunitakarle23** [comment] 2018-12-18 06:02
While navigating back using up arrow to the plain text in NVDA the text read as clickable on Firefox

Below is the markup. 
<div class="flight-cancel-text-col grid__col-sm-11 grid__col-xs-11">
<span class="flight-cancel-text"> Book without worry! </span>
  You can cancel your flight online within 24 hours of booking. Program fees may apply.
<div>

Please let me know how can we handle this.           
             
Thanks.

**Comment by Adriani90** [comment] 2019-02-24 19:44
@mjanusauskas, @sunitakarle23 are you still able to reproduce this issue with NVDA 2018.4.1 or with last NVDA Alpha?

In Firefox I cannot reproduce this issue, but in Google chrome, after the first list, NVDA reads only "clicckable" for more than 6 lines or so. In Firefox, there is some text which is not recognized in Google Chrome. In my opinion this could be bad implementation from web developer. But I am not sure.
In any case, in the list NVDA does not report clickable at all.

cc: @jcsteh your ghoughts on this are very appreciated. Thanks!

**Comment by Adriani90** [comment] 2020-05-02 18:19
I am closing this issue, it seems it is not reproducible anymore. Please comment on it if you are still having it and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-02 18:19 UTC
Labels: app/chrome, close/worksforme, p3

**Comment by ernistkg** [comment] 2021-03-18 18:47
Still reproducible
