### ISSUE TITLE
Inconsistent Focus Moving by Headings with Dynamic Web Page and Firefox 59

### ISSUE THREAD

**Issue by jage9** [nvaccess/nvda#7799] opened 2017-11-26 21:57 UTC
### Steps to reproduce:
1. Open Firefox Nightly (59 as of the time of this bug).
2. Go to 
https://www.hotels.com/search.do?resolved-location=CITY%3A1538574%3AUNKNOWN%3AUNKNOWN&destination-id=1538574&q-destination=Detroit,%20Michigan,%20United%20States%20of%20America&q-check-in=2017-12-04&q-check-out=2017-12-08&q-rooms=1&q-room-0-adults=2&q-room-0-children=0
3. Go to the list of hotels and start moving quickly between them by pressing H. As you do this, more hotels are loaded, roughly 5-10 at a time.

### Expected behavior:
Pressing H will move to the next heading on the page.

### Actual behavior:
When moving by heading, focus sometimes gets lost, and results are repeated. Seems to happen the most when moving quickly.

### System configuration:
NVDA version: NVDA Next 14660 installed

Other information:

Windows version: Windows 10 1703

### Other questions:

Does the issue still occur after restarting your PC? yes

Have you tried any other versions of NVDA?
This is a Regression. Worked using Firefox 56 and NVDA 2017.3. In Firefox 52.5 ESR, sometimes the same behavior is seen while other times the page buffer just doesn't refresh at all.

**Comment by PratikP1** [comment] 2017-11-27 15:09
For comparison purposes, I tested this with Firefox 56, Edge, and Chrome Canary.

The reported problem also occurs in Firefox 56. The main difference between Firefox 56 and 59 is the speed with which we can move from heading to heading. Edge and Chrome do not exhibit the same issue and the navigation is pretty smooth and speedy.

**Comment by feerrenrut** [comment] 2017-11-28 04:11
When I tried to reproduce this with Firefox 57.0, the results I observed were consistent with my expectations based on the loading of the hotel results. For instance, when more hotels are being loaded and 'h' is pressed, the next header is an advert saying "choose one of the following...". Then pressing `shift+h` the last hotel heading I visited is given focus.

**Comment by jage9** [comment] 2017-11-28 04:16
If you move by heading deliberately and more slowly, this will generally 
happen. The focus issues seem to happen when moving faster. I wonder how 
slowly the additional results load visually. Perhaps this is part of 
what's happening.

**Comment by PratikP1** [comment] 2017-11-28 06:00
I suspect the visual results are pretty fast considering my testing in Chrome and Edge. There were no delays at all. As a screen reader user, I couldn’t even tell that the results were being dynamically updated.

**Comment by fernando-jose-silva** [comment] 2017-11-28 18:00
I did the tests and with me there is also a very great slowness.
On a machine with firefox 56 it is slow.
More on a machine with firefox 57 is extremely very slow, however the problem of slowness in firefox 57 is not only in this site, but in many others, the experience in firefox 57 for me is very challenging, the slowness is very great.

**Comment by feerrenrut** [comment] 2017-11-28 22:37
When I tested this (Firefox 57) the results visually loaded slowly, 2-3 seconds for each new block of results.

**Comment by jage9** [comment] 2018-12-07 07:41
While it is possible to press H to move past the list of hotels, the behavior described in this issue no longer seems to exist, at least on this site.
This is with FF 63. Can this one be closed as fixed at some point?

**Comment by Adriani90** [comment] 2018-12-07 08:49
@jage9      you can Close this issue by yourself since you have created it. The vlose button is near to the comment button.

**Comment by jage9** [comment] 2018-12-07 18:45
Thanks, will do. Just wanted to make sure no one else was still 
experiencing this.

**Closed** 2018-12-07 18:45 UTC
Labels: Firefox

**Comment by Adriani90** [comment] 2018-12-07 19:47
I have also tested in Firefox 63.0.3 with NVDA 2018.4 Beta 4 and the cursor seems to stay stable even when navigating quickly. You can navigate much wuicker than hotels are loaded and you can pass the list without the cursor getting stuck on the list.

**Comment by Adriani90** [comment] 2018-12-07 19:48
However I have noticed a slow delay when many hotels are loaded. But I think that issue is out of scope for this one.
