### ISSUE TITLE
Additional Browse Mode Targets

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#15046] opened 2023-06-22 16:17 UTC
### Is your feature request related to a problem? Please describe.
It is not related to broken functionality but it could make web navigation much easier on many sites/web apps.

### Describe the solution you'd like
As an NVDA user, I'd like the ability to easily navigate by region, menu and tab group, so that I have more methods of getting around dense and complex web applications and pages.
I often hear NVDA announce these types of elements - region, menu and tab - but there are no corresponding single-character browse mode shortcuts for moving between these elements. It would be consistent with other web content announced by NVDA, such as links, form controls and headings, for which there are browse mode shortcuts.

### Describe alternatives you've considered
There are currently no methods of moving by these element types, to my knowledge. For now, users must use the cursor keys or the existing browse mode shortcuts which sometimes don't  allow you to quickly get to the elements I've mentioned above.

### Additional context
I'm a software developer and often work in applications such as Azure Cloud where pages contain dense amounts of controls, options, settings and tabs, and often time such pages contain regions, tab groups and menus as announced by NVDA. I could be more efficient at my job if I could more easily traverse these dense pages, and additional browse mode shortcuts would enable this.

**Comment by seanbudd** [comment] 2023-06-28 00:18
Do you have any suggestions on single characters for these?

**Comment by amirsol81** [comment] 2023-07-02 06:18
@seanbudd @Luke-Robinett While NVDA doesn't natively support these, most of them can be added via the useful BrowserNav add-on, and I also support including them in NVDA core. The keys BrowserNav uses for these are:
Y, and SHIFT+Y: Jump to next/previous tab.
Z, and SHIFT+Z: Jump to next/previous menu.
There are also others like Jump to next format change = Grave Accent, Jump to next tree view = 0, etc.

**Comment by ruifontes** [comment] 2023-07-02 12:54
I will avoid the use of grave accent, backslash and so on, since wich keyboard have those keys in different places...

**Comment by Adriani90** [comment] 2023-12-29 18:56
For menu and menu items there is #7695. Quick navigation by tabs has been introduced in #15332 being part of NVDA 2023.3 and you can assign an input gesture for it in the input gesture dialog.

Given this is a duplicate of #7695, I am closing as such.

**Closed by Adriani90** 2023-12-29 18:56 UTC
Labels: close/duplicate, feature/browse-mode, p4, triaged
