### ISSUE TITLE
NVDA Crash In PowerPoint 2013

### ISSUE THREAD

**Issue by netblue44** [nvaccess/nvda#5515] opened 2015-11-19 14:31 UTC
Hi,
when closing PowerPoint 2013 without saving any chainges to the document, NVDA crashes and summtimes causes PowerPoint it self to crash. This problem has existed since NVDA2014.3. I have not been able to GET a log of this problem because after each crash I have to restart NVDA.
I am using Windows 7 Ultemate 64 bits.

**Comment by jcsteh** [comment] 2015-11-20 02:48
You already filed this. :) Duplicate of #4479.

**Closed by jcsteh** 2015-11-20 02:48 UTC
Labels: duplicate
