### ISSUE TITLE
Feature request: Natural voices support for windows 11

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#15587] opened 2023-10-05 21:15 UTC
### Is your feature request related to a problem? Please describe.
Starting with Win11 Build 22631.1835 Narrator officially supports Natural voices
### Describe the solution you'd like
I hope to be able to support natural speech if NVDA support is not too difficult.
### Describe alternatives you've considered
none
### Additional context
[Microsoft documentation](https://support.microsoft.com/en-us/windows/appendix-a-supported-languages-and-voices-4486e345-7730-53da-fcfe-55cc64300f01#WindowsVersion=Windows_11)

**Comment by GeorgeWu3** [comment] 2023-10-05 22:25
I agree it will be nice.

**Comment by dpy013** [comment] 2023-10-05 23:00
The main reason is that Natural voices has great voice quality.

**Comment by seanbudd** [comment] 2023-10-05 23:28
Closing as duplicate of #13288

**Closed by seanbudd** 2023-10-05 23:28 UTC
