### ISSUE TITLE
NVDA repeats File Name thrice in Save As dialogs

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4670] opened 2014-12-05 12:06 UTC
**Reported by bhavyashah on 2014-12-05 12:06**
Hi,
Steps to reproduce
Open MS Word 2007.
Type something (probably optional).
Hit F12, and listen.
Expected: NVDA would read the field gaining focus once, and behave normally.
Actual: NVDA says file name thrice or multiple times.

**Comment by ehollig** [comment] 2017-07-28 18:55
I can confirm this on Windows 10 with Office 2016 as  well as any other save as dialogs like in Notepad. This is slightly annoying, but it does not break functionality.

**Comment by Brian1Gaff** [comment] 2017-07-29 09:40
Somebody needs to change the title of this as yes, it does often affect 
other similar dialogues and also in other versions of Windows. I'm 
suspicious that multiple events or  some refreshing of content is causing 
this one.
 Its very hard to call when its going to happen.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment] 2020-05-02 14:21
This is not reproducible anymore with NVDA Version: alpha-20097,6a573cd9. Tested in MS Word 2007, 2010 and 365 as well as in Notepad. Closing as works for me.

**Closed by Adriani90** 2020-05-02 14:21 UTC
Labels: bug, close/worksforme
