### ISSUE TITLE
We don't leave focus mode if a search is performed on google

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6938] opened 2017-03-06 16:41 UTC
1. Search google for "blah blah blah blah blah" via actually visiting google.com and typing in the edit box. Do not use the address bar.
2. Now, press enter.
3. observe that even though the page loaded, we don't go into browse mode.

**Comment by PratikP1** [comment] 2017-03-06 16:44
This is a problem with Google applying autofocus to the search field even after search results are delivered.

**Comment by Brian1Gaff** [comment] 2017-03-07 07:27
Which is one reason I set up the checks to automatically come out when I 
cursor out of an edit field. It very much depends on the type of field 
otherwise.
 I suspect his might be something to do with that google instant rt 
thingamajig.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment] 2019-04-08 14:58
@derekriemer, @PratikP1, @Brian1Gaff are you still seeing this issue? I cannot reproduce it in NVDA 2019.1.

**Comment by Brian1Gaff** [comment] 2019-04-08 15:03
I certainly do not see it in the latest nvda, but since this was reported I 
think Google have also changed their search page.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment] 2019-04-08 15:44
Closing as works for me. If it is still occuring, please comment on it and we can reopen it. Thanks!

**Closed** 2019-04-08 15:44 UTC
Labels: GoogleWork, bug, p3, worksforme
