### ISSUE TITLE
NVDA reads treeview role and level for VS Code autocomplete suggestions

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#10777] opened 2020-02-11 11:43 UTC
### Steps to reproduce:
1. Open Visual Studio Code insiders.
2. Create a file with a supported extension, e.g. index.js.
3. type "co ". NVDA will report  "level 1 console" or "console level 1". Pressing the up and down arrow keys at this point will read out the suggestions, followed by "level 1".
4. At times, this is a bit harder to reproduce, NVDA will report "treeview item" or similar.

### Actual behavior:
NVDA seems to think a treeview is being used. This is false, according to this tweet from one of the developers for VS Code , @isidorn:

"Autocomplete (same as extensions view) uses a listView, not a treeView. We set aria-posinset, aria-setsize. We do not use aria-level."

### Expected behavior:
There should be no mention of level in these announcements, nor of treeview items.

#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.2. This behavior is absent in this version, seeming to mark this as a regression.

**Comment by isidorn** [comment] 2020-02-11 11:51
I find it quite strange that NVDA reads these items as tree items even though VSCode does not set the `aria-level` attribute.
We do set the role to be `treeitem` and this is probably the cause, but it is just a list, since there is no `aria-level`.
I am also open to changing the role on the VS Code side, however I am not aware of a role that represents list.

Gist: NVDA should not read level when `aria-level` is not set.

**Comment by francipvb** [comment] 2020-02-11 13:28
The problem is reproducible in stable, too.

**Comment by leonardder** [comment] 2020-02-17 09:57
NVDA just announces what it gets from the IA2 implementation of chromium.



> I am also open to changing the role on the VS Code side, however I am not aware of a role that represents list.

Just the list role. You can use list for the list and listitem for the listitem. Could be that these have been added in the aria 1.1 spec, not sure. See https://www.w3.org/WAI/PF/aria/roles#listitem

**Comment by isidorn** [comment] 2020-02-18 10:48
@leonardder Ok, this makes sense. Created https://github.com/microsoft/vscode/issues/90876 on the vscode side so we try to tackle this.

**Comment by isidorn** [comment] 2020-03-04 15:21
This is fixed on the vscode side thus I suggest we close this.

**Comment by leonardder** [comment] 2020-03-04 15:28
Thanks @isidorn

**Closed by leonardder** 2020-03-04 15:28 UTC
Labels: App specific, needsExternalFix

**Comment by leonardder** [comment] 2020-03-16 15:20
Related to https://github.com/microsoft/vscode/issues/92719, which has been fixed also.
