### ISSUE TITLE
nvda stops reading any information on microsoft teams

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11211] opened 2020-05-26 22:07 UTC
### Steps to reproduce:
on nvda disable the autofocus mode option when the focus changes
open microsoft teams
switch to navigation mode and join a team, then join a channel.
Now switch to the focus mode.
in the list of tabs select the files tab.
now in focus mode choose a file and press the right button.
I chose a microsoft word file.
when pressing the right button choose the open menu, then choose open in word.
The file will be opened in the local microsoft word, installed on the machine.
Make changes to the file, close the file.
The focus should return to teams.
The nvda will now not read anything when walking with the arrows or with a tab.
For nvda to return to work it is necessary to close teams, to close means to end the teams process in the task manager and re open teams.
This has already occurred on other teams screens, but by making the palaces so I was able to easily reproduce the problem.
### Actual behavior:
nvda not reading anything in teams
### Expected behavior:

nvda continues to work with teams after closing word.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 20220 
#### Windows version:
10 190041.264
#### Name and version of other software in use when reproducing the issue:
teams Teams.exe, Microsoft Teams 1.3.00.12058
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no
[teams.txt](https://github.com/nvaccess/nvda/files/4685209/teams.txt)

**Comment by lukaszgo1** [comment] 2020-05-26 22:12
What happens if after closing MS Word you minimize Teams window with Windows _ down arrow and then maximize with Windows _ up Arrow? If it causes NVDA to interact with Teams again it is a known problem which needs to be fixed in Teams unfortunately.

**Comment by fernando-jose-silva** [comment] 2020-05-27 14:20
unfortunately it didn't solve it, I minimized the window and maximized it and continued without reading anything.
The log is with several add-ons however running nvda without add-ons the answer is the same.
Thank you.
follow new log
[teams1.txt](https://github.com/nvaccess/nvda/files/4689326/teams1.txt)

**Comment by Adriani90** [comment] 2020-06-01 10:17
Could you try to run the COM registration fixing tool please?

**Comment by Adriani90** [comment] 2020-06-01 10:25
I cannot reproduce this issue with NVDA last alpha.

**Comment by fernando-jose-silva** [comment] 2020-06-01 14:10
thank you very much, I ran the registry correction tool with, but the problem persists.
New log follows.
[teams 1-6-2020.txt](https://github.com/nvaccess/nvda/files/4711691/teams.1-6-2020.txt)

**Comment by codeofdusk** [comment] 2020-06-01 20:11
I can reproduce this issue under NVDA 2020.1.

**Comment by leonardder** [comment] 2020-06-08 10:36
I got the following from Microsoft:

> A fix for this issue was made available this week as an automatic update to Teams.  You should have the fix now.

> The build you should have with the fix is:

> 1.3.00.13565 or newer.

**Closed by leonardder** 2020-06-08 10:36 UTC
Labels: blocked/needs-external-fix

**Comment by fernando-jose-silva** [comment] 2020-06-08 15:25
I installed teams on another machine, the version installed was the one indicated by microsoft.
I continue with the problem, please investigate furthe
[teams8-6-2020.txt](https://github.com/nvaccess/nvda/files/4746902/teams8-6-2020.txt)
r.
The behavior of the nvda is extremely uncomfortable.
