### ISSUE TITLE
NVDA should support unicode Emoticons in both Braille and speech

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5135] opened 2015-06-02 21:51 UTC
**Reported by winman3000 on 2015-06-02 21:51**
More and more People are using Smartphones and they sent Unicode Emoticons. NVDA cannot announce These emotecons and cannot Show it correctly on the Braille Display either.

**Comment by leonardder** [comment] 2018-09-01 12:13
Closing as older duplicate of #6523. Note that #6523 deals with speech in particular, but I guess braille is also quite important.

**Closed by leonardder** 2018-09-01 12:13 UTC
Labels: Braille, Speech, enhancement
