### ISSUE TITLE
Default Tab Sequence Should Speak Links, Not Links + Section Headings

### ISSUE THREAD

**Issue by v-garset** [nvaccess/nvda#11234] opened 2020-06-05 19:41 UTC
### Steps to reproduce:

1. Open NVDA application
2. Open web browser
3. Navigate to https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_between
4. Press Tab repeatedly until you reach any heading with a nested link
5. NVDA reads "§  link    heading    level 3" on section 3 headings with nested links
6. NVDA reads "§  link    heading    level 4" on section 4 headings with nested links
7. Exit NVDA
8. Open Windows Narrator
9. Navigate to https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_between
10. Press Tab repeatedly until you reach any heading with a nested link
11. Windows Narrator reads "link section sign" with section 3 headings with nested links
12. Windows Narrator reads "link section sign" with section 4 headings with nested links
13. Try same behavior on https://wiki.developer.mozilla.org/en-US/docs/Learn/Accessibility/WAI-ARIA_basics
14. NVDA reads "Section link heading level 2"
15. Windows narrator reads "link section"
16. Try same behavior on https://docs.microsoft.com/en-us/windows/apps/accessibility#main
17. NVDA reads "Build accessibility into your applications to empower people of all abilities  link    heading    level 2"
18. Windows narrator reads "link Build accessibility into your applications to empower people of all abilities"

### Actual behavior:

The default tab sequence reads links + section headings when links are nested within section headings.

### Expected behavior:

The default tab sequence _should_ read only links when links are nested within section headings, _not_ links + section headings.

According to the W3 spec at https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_general_between, "In HTML, the default tab sequence of a web page includes only links and HTML form elements".
 When using the default tab sequence on [the WCAG spec](https://www.w3.org/TR/WCAG21/) itself, links plus section headings are read aloud.

Windows Narrator only reads links, NVDA reads links + section headings. 

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.1

#### Windows version:
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.19041 Build 19041

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge | 83.0.478.44 (Official build) (64-bit)
Google Chrome | 83.0.4103.61 (Official Build) (64-bit)
Firefox 77.0.1 (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment] 2020-06-06 00:18
Unless I am not wrong, this WCAG explanation of tab sequence is not entirely correct. In fact, a tab sequence does not contain only links and form elements. For example in tables, NVDA would also report the cell coordinates which is expected behavior for any screen reader. This is also the case for headings. If an user would not hear the heading in the tab sequence, he or she would not have an idea about the page structure. Headings are very important also for sighted people to understand how a text is structured, so reporting them also in the tab sequence helps for example low vision people who are using focus mode by default to navigate a web page. The same happens for groupings or lists. So in my view, Narator does not behave as expected here. I would say this is rather an issue in Narator and not in NVDA.
@jcsteh please correct me if I am wrong.

**Comment by leonardder** [comment] 2020-06-06 07:17
The problem described here is that NVDA reads the parent heading of a link when a heading contains a link. This is probably because the heading is a ancestor of a link and the heading is considered a presentable focus ancestor, see the `isPresentableFocusAncestor` property on the object.

I think this is on purpose and shouldn't be changed, but other people might have other thoughts.

**Comment by Adriani90** [comment] 2020-06-08 18:39
I am closing this issue for now since it seems this is expected behavior here. If someone has other comments on it, please add them to this issue and we can reopen the discussion. Thanks.

**Closed by Adriani90** 2020-06-08 18:39 UTC
