### ISSUE TITLE
Implement generic braille input hotkeys

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#7677] opened 2017-10-21 07:36 UTC
Currently, every braille driver that implements braille input is mapping certain keys to braille keyboard gestures.

I would like to see generic mappings for common keys on a braille keyboard. This would increase consistancy for users of multiple displays/braille keyboards.

To do:

1. Determine the keys we want braille shortcuts for
2. Research common mappings for such keys in other screenreaders, NVDA's existing braille drivers and probably other devices such as notetakers
3. Implement such mappings for all braille keyboards and remove existing mappings from braille display drivers

**Comment by munawarb** [comment] 2017-10-21 11:06
I’m glad this issue was posted :). I think also we should have the ability to map Braille inputs to actual keys on the keyboard, such as me being able to specify that space with S will press the WINDOWS key.

**Comment by leonardder** [comment] 2017-10-21 11:11
This is actually a duplicate of #2945, so let's continue the discussion there.

**Closed by leonardder** 2017-10-21 11:11 UTC
Labels: Braille

**Comment by josephsl** [comment] 2017-10-21 16:04
Hi, isn’t this a duplicate of another issue that asks for a similar thing? Thanks.
