### ISSUE TITLE
list box focus and currently selected items are not queryable

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5647] opened 2016-01-04 01:16 UTC
It is not possible using nvda (or other screen readers for that matter) to check to see what items in a list box are currently selected. For example, if you have windows explorer set up in list view, and select things at random with ctrl-space, and later wish to know what you selected you can't easily see what is selected. Exasperating this problem is the fact that NVDA speaks the whole item before stating if it is unselected. (i.e. "support assistance work record log.xlsx not selected") a friend of mine who is a confident computer issue asked me if there was a way to query this information using NVDA recently. I couldn't think of a way to. To make things worse, it seems that some (lots actually) of listboxes on the web don't properly convey there selection state when passively browsing the list, and list boxes on the web don't properly convey which item is actually focused to the user of NVDA in many cases, simply reporting list box.

**Comment by jcsteh** [comment] 2016-01-04 03:48
Duplicate of #1839.

**Closed by jcsteh** 2016-01-04 03:48 UTC
Labels: duplicate
