### ISSUE TITLE
Word Crashed on Opening Document Properties

### ISSUE THREAD

**Issue by tfri** [nvaccess/nvda#7449] opened 2017-07-27 16:50 UTC
### Steps to reproduce:
Opened NVDA, set to no speech with Speech Viewer open
Opened Word Document in Word 2013
Opened Document Properties window.

### Expected behavior:
Nothing

### Actual behavior:
Word crashed.
I tried again after exiting NVDA and it worked normally. Once I had the Properties window open, I could start NVDA with no issues.

### System configuration:
NVDA version:
2017.2

NVDA Installed
Other information:

Windows version:
> Example: Windows 10 Version 1703 Build 15063.483

Name and version of other software in use when reproducing the issue:
Word 2013
### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
No

**Comment by bhavyashah** [comment] 2017-07-29 07:33
@tfri  Could you please answer the following questions:
* Are both parts of Step 1, i.e. opening Speech Viewer as well as setting NVDA to No Speech compulsorily required for the replication of the described behaviour?
* For the benefit of other testers (including me), could you elaborate on the steps you took to open the Document Properties window in MS Word?

**Comment by tfri** [comment] 2017-07-31 12:59
1. Yes, both parts of Step 1 were done.
2. To open the Document Properties, Click File. Con the right where the properties are displayed, click the triangle beside the word Properties. Choose Show Document Panel.

**Comment by Adriani90** [comment] 2019-02-04 14:24
@tfri are you still having this issue?

**Comment by Adriani90** [comment] 2019-04-24 13:27
@tfri I cannot reproduce this issue in NVDA 2019.1.1. Are you still available to test if you are having it still? It seems to be a very specific issue and for us very hard to reproduce. We rely on tests and updates from your side to track if it is solved or not. Otherwise the issue will rpbably be closed sooner or later without any result unfortunately.

**Comment by Adriani90** [comment] 2019-04-24 13:28
@feerrenrut, in case the author is not available anymore, couls you please try to test if this is occuring on your side using Office 2013? Tanks.

**Comment by tfri** [comment] 2019-04-24 13:31
It’s been so long that I’m not sure I remember exactly what the original issue was. I’ll see what I can figure out. I may have also upgraded my version of Office since then.

Do what I do: hold tight and pretend it’s a plan.
---The Eleventh Doctor; The Doctor, the Widow and the Wardrobe

Tammy Frietsch
Technology Coordinator
Yoakum ISD
315 E. Gonzales St.
P.O. Box 737
Yoakum, TX 77995
361.293.6960

**Comment by feerrenrut** [comment] 2019-04-26 14:42
I tried to reproduce this with Word 2013 and NVDA 2019.1.1 and could not. I am going to close the issue, if anyone is able to reproduce please comment or re-open it.

**Closed by feerrenrut** 2019-04-26 14:42 UTC
Labels: appCrash
