### ISSUE TITLE
reading cell line in google docs

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7941] opened 2018-01-23 20:14 UTC
### Steps to reproduce:
Open a new document in google docs, an empty text document.
Insert a table with 2 rows and 2 columns.
Now type text in all cells of the table, in this example I'll type:
line 1 column 1 test 1
line 1 column 2 test 2
line 2 column 1 test 3
row 2 column 2 test 4
Now focus on row 1 column 1
Press tab to read row 2 column 1
now press down arrow.

### Expected behavior:
The nvda should read the text in column 2 line 2 in case test 4

### Actual behavior:
The nvda informs the text of line 1 column 2 in case test 2 followed by the word unmarked.
and does not read the text in column 2 row 2 in case test 4.

### System configuration:
NVDA version:
> Example: next-14799

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 7

Name and version of other software in use when reproducing the issue:
firefox 57
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

log:

Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:34.362):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (18:12:34.382):
Speaking [u'Tabela introduzida com 2 colunas por 2 linhas Linha 1 Coluna 1 teste 1  ']
IO - inputCore.InputManager.executeGesture (18:12:39.516):
Input: kb(laptop):tab
IO - speech._speakSpellingGen (18:12:39.575):
Speaking character u'tab'
DEBUG - queueHandler.registerGeneratorObject (18:12:39.575):
Adding generator 4586
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:39.605):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:39.615):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:39.615):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:39.625):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUG - queueHandler.pumpAll (18:12:39.625):
generator 4586 finished
IO - speech.speak (18:12:39.625):
Speaking [u'teste 2 Selecionado  ']
IO - inputCore.InputManager.executeGesture (18:12:43.364):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:43.404):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:43.404):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:43.414):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:43.414):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (18:12:43.414):
Speaking [u'teste 2 Desmarcado  ']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (18:12:43.434):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (18:12:47.075):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (18:12:48.467):
Developer info for navigator object:
name: None
role: ROLE_GROUPING
states: STATE_FOCUSABLE, STATE_INVISIBLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_GroupboxMozillaIAccessible object at 0x08E256D0>
Python class mro: (<class 'NVDAObjects.Dynamic_GroupboxMozillaIAccessible'>, <class 'NVDAObjects.IAccessible.Groupbox'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (323, -9922, 609, 0)
value: None
appModule: <'firefox' (appName u'firefox', process ID 6796) at address 91721d0>
appModule.productName: u'Firefox'
appModule.productVersion: u'57.0.4'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 984420L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 382664704
windowThreadID: 3920
windowText: u'fernando - Documentos Google - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xb1f3c44 at 91622b0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=984420, objectID=-4, childID=-33564627
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_GROUPING
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 984420
IAccessible2 uniqueID: -33564627
IAccessible2 role: ROLE_SYSTEM_GROUPING
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_ACTIVE (1025)
IAccessible2 attributes: u'margin-left:0px;text-align:start;text-indent:0px;id:docs-texteventtarget-descendant;tag:div;xml-roles:group;margin-top:0px;margin-bottom:0px;margin-right:0px;display:block;hidden:true;formatting:block;'

**Comment by PratikP1** [comment] 2018-01-24 04:54
I can confirm this behavior. Tabbing to a cell selects its contents. When using the down arrow key, the selection is removed and the cursor moves to the next row. However NVDA only announces the selection change. The contents of the cell in which the cursor has landed is not spoken.

**Comment by Adriani90** [comment] 2019-05-01 12:00
In Firefox 66.0.3 this is still reproducible. Moreover, it seems the focus jumps through the table when using ctrl+alt+arrow keys and land on unexpected cells. Sometime NVDA reports that the text is selected although it is not selected with shift+arrow keys. Something seems to be broken with regard to carret movement.
cc: @jcsteh

**Comment by Adriani90** [comment] 2023-04-21 10:35
This is not reproducible in NVDA 2023.1 or last alpha in Google Docx and Firefox 112. In fact, If you are in the first column and press down arrow, NVDA reads the whole row from left to right. When you are in the second column, NVDA reports only the correct cell content when you press down arrow.

Note that you have to enable both screen reader and braille support in Google docs accessibility settings.

Actually I really like the behavior in Firefox to read the whole row when you press down arrow while focusing the first column. @jcsteh is this something NVDA could consider for all kind of tables in focus mode in every application apart from application like Excel or Libre Calc? This would improve efficient reading alot.

This could apply only when focusing first column while the behavior remains unchanged when focusing other columns. Maybe making it configurable for people that wouldn't like the feature.

**Comment by Adriani90** [comment] 2023-05-05 19:50
I am closing this issue as works for me.

**Closed by Adriani90** 2023-05-05 19:50 UTC
Labels: close/worksforme
