### ISSUE TITLE
LibreOffice Writer:  report text alignment (left, center, right, justify)

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#6913] opened 2017-02-24 03:35 UTC
This is a feature request that NVDA report text alignment, while pressing NVDA+f in LibreOffice Writer.
Steps to reproduce:
1. Open Writer.
2. Type the word "All things right and beautiful"
3. Press shift+home to select words.
4. Press ctrl+r
5. Press NVDA+f
NVDA report:
Liberation Serif
12.000pt
black on white
baseline

**expected**: NVDA also report "align right"

**Comment by feerrenrut** [comment] 2017-02-24 13:37
Is there any other alternative means to get the alignment?

One consideration is how this should work when the selection contains text with several alignments. In Microsoft Word 2013 it seems that the first alignment is reported, the others are ignored.
Use case:
who: Any NVDA user working with the latest stable version of LibreOffice
what: Report alignment of selected text when `NVDA+f` is pressed. If there is no text selected, report the alignment of the text under the caret.
why: So that the formatting information reported by NVDA is more complete. This saves the user time.

**Comment by zahra21** [comment] 2018-01-16 13:33
i confirm this issue using any version of libreoffice which i tested!
did you find a solution for this?
God bless you all.

**Comment by ehollig** [comment] 2018-04-08 22:16
Related to, or possible duplicate of #2204

**Comment by michaelweghorn** [comment] 2021-10-14 06:35
There's also a bug report about this in LibreOffice's Bugzilla: https://bugs.documentfoundation.org/show_bug.cgi?id=135922

**Comment by michaelweghorn** [comment] 2023-10-27 20:26
This has been implemented in the meanwhile, will work with LibreOffice 24.2 and NVDA 2024.1, s. https://bugs.documentfoundation.org/show_bug.cgi?id=135922 and https://github.com/nvaccess/nvda/pull/15649

I think this issue can therefore be closed.

**Comment by Adriani90** [comment] 2023-10-27 23:35
@michaelweghorn note that NVDA 2024.1 has not been issued yet, so I guess you mean the last alpha version of NVDA right?

**Comment by Adriani90** [comment] 2023-10-27 23:39
Anyway, this works in the master of LO 24.2 as you mentioned, thank you very much for this. I am closing as works for me.

**Closed by Adriani90** 2023-10-27 23:39 UTC
Labels: close/worksforme, p4, app/libreoffice

**Comment by michaelweghorn** [comment] 2023-10-28 03:44
> @michaelweghorn note that NVDA 2024.1 has not been issued yet, so I guess you mean the last alpha version of NVDA right?

Yes, I meant that this requires the current development versions (git master) of both, LibreOffice and NVDA which contain the changes mentioned in my previous comment.
