### ISSUE TITLE
Add-on store: present updatable add-ons or add-on update notification at NVDA startup

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#15035] opened 2023-06-20 02:12 UTC
Hi,

This one may require some thought:

### Rationale
One of the highlights of add-on store client (NVDA 2023.2) is ability to update add-ons. However, in order to check for add-on updates, one must visit the ad-on store. There might be times when the user might be busy working on something and would like to be notified about add-on updates without leaving the task they are working on.

### Is your feature request related to a problem? Please describe.
Add-ons such as Add-on Updater offer ability to be notified about add-on updates, mostly at NVDA startup.

### Describe the solution you'd like
Add a mechanism and a setting to present an interface or a notification about add-on updates at NVDA startup. The most ideal approach is a toast notification that informs users about add-on updates (Windows 10 and later) and directs users to visit the add-on store to review updates.

### Describe alternatives you've considered
Let users check for add-on updates manually.

### Additional context
While toasts are usable with Windows 8 and later, enhancements such as actionable toasts came with Windows 10. Currently wxPython 4.1.1 does allow presenting a notification message but does not support actionable toasts (things might be different with wxPython 4.2.1 and later). In addition, if this aproach is successful (incuding actionable toasts), this may serve as a foundation to let NVDA present a notification message when updates to itself become available.

Thanks.

**Comment by nvdaes** [comment] 2023-06-20 02:20
Í absolute agree with this request.

**Comment by seanbudd** [comment] 2023-06-20 02:23
This may be a duplicate of: https://github.com/nvaccess/nvda/issues/3208

NV Access is working on a development plan for this, but it is unlikely to be included in 2023.2.

Some background suggestions I have.

I want to use a pip module, schedule, which works as a cron job scheduler in python
https://pypi.org/project/schedule/
I think we are going to want a system where update notifications are staggered to prevent a conflict of notifications.

For example, during NVDA initialization we schedule 2 cron jobs:
- every 24 hours, 5min after starting NVDA, run NVDA update check
- every 6 hours, 10min after starting NVDA, refresh the add-on store cache
- every 24 hours, 15min after starting NVDA, run add-on update check

This gives us the room for more scheduled jobs, and allows add-ons to schedule jobs around core functions.

As a general API, I think we need a wrapper to prevent conflicts and allow add-ons to smart schedule a regular job.

**Comment by seanbudd** [comment] 2023-06-20 02:24
using windows toasts like suggested for all of these update might be good too

**Comment by josephsl** [comment] 2023-06-20 02:30
Hi, I think more towards an enhancement on top of #3208 for which add-on store is part of the solution. Thanks.

**Comment by XLTechie** [comment] 2023-06-20 03:02
@seanbudd wrote:
> using windows toasts like suggested for all of these scheduled jobs might be good too

While generally I think that's fine, I have noticed while doing end user support 
over the years, that a shocking number of users don't pay attention to those, 
type through them, don't know how to interact with them (or that they even can), 
or don't understand why they have to keep hearing them.

I don't offer that as a good reason not to do it that way, just as a factor to 
consider.

**Comment by seanbudd** [comment] 2023-06-20 23:47
Rather than Windows toasts, as these are often ignored or snoozed, a regular message dialog is more appropriate.

We could consider adding it to the NVDA menu as well, e.g. "Add-on updates available" which opens the add-on store to the updates page.

**Comment by nvdaes** [comment] 2023-06-21 02:58
I think that this should be configurable, ie., a settings panel should allow to choose if the notifications will be presented via toast or with a conventional dialog. The experience provided by addonUpdater add-on may be considered here, and for me toast provide a better experience.

**Comment by josephsl** [comment] 2023-09-05 12:53
Hi,

September 2023 update: I and Luke are willing to keep Add-on Updater going until this issue receives a pull request, hopefully as part of 2024.1 or 2024.2.

Thanks.

**Comment by seanbudd** [comment] 2023-12-07 22:48
This is not scheduled work @CyrilleB79

**Closed** 2024-06-12 01:37 UTC
Labels: p5, triaged, merge-early, feature/addon-store
