### ISSUE TITLE
Application not responding after landmark navigation

### ISSUE THREAD

**Issue by zarubond** [nvaccess/nvda#8813] opened 2018-10-01 13:53 UTC
Related to  #6410

### Steps to reproduce:
1. Install latest Skype
2. Go to conversation with many messages and start going through them by pressing "d" key
3. After some time NVDA will announce "no new landmark" and the Skype app become unresponsive (Not Responding) for ever (sometimes you also have to switch to other application and back)

### Actual behavior:
Hangs application and crashes the NVDA

### Expected behavior:
Not hang the application

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.3.2

#### Windows version:
Win 10 and Win 7

#### Name and version of other software in use when reproducing the issue:
Electron based Skype 8.31

Log from NVDA
INFO - __main__ (15:51:31.700):
Starting NVDA
INFO - core.main (15:51:32.973):
Config dir: C:\Users\xxx\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (15:51:32.973):
Loading config: C:\Users\onzruba\AppData\Roaming\nvda\nvda.ini
INFO - core.main (15:51:33.062):
NVDA version 2018.3.2
INFO - core.main (15:51:33.062):
Using Windows version 10.0.17134 workstation
INFO - core.main (15:51:33.062):
Using Python version 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
INFO - core.main (15:51:33.062):
Using comtypes version 1.1.3
INFO - synthDriverHandler.setSynth (15:51:33.339):
Loaded synthDriver oneCore
INFO - core.main (15:51:33.339):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
INFO - brailleInput.initialize (15:51:33.342):
Braille input initialized
INFO - braille.initialize (15:51:33.342):
Using liblouis version 3.6.0
INFO - braille.BrailleHandler.setDisplayByName (15:51:33.342):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (15:51:33.487):
UIAutomation: IUIAutomation5
INFO - core.main (15:51:34.407):
NVDA initialized
WARNING - watchdog._watcher (15:52:38.687):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:52:53.694):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:53:08.711):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:53:23.752):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:53:38.786):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:53:53.805):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:54:08.816):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:54:23.861):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:54:38.911):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:54:53.959):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:55:08.967):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:55:23.983):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:55:39.030):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:55:54.046):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:56:09.071):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:56:24.114):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

WARNING - watchdog._watcher (15:56:39.153):
Core frozen in stack:
  File "nvda.pyw", line 214, in <module>
  File "core.pyo", line 508, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 963, in Notify
  File "core.pyo", line 480, in run
  File "mouseHandler.pyo", line 220, in pumpAll
  File "mouseHandler.pyo", line 176, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyo", line 262, in objectFromPoint
  File "NVDAObjects\__init__.pyo", line 202, in findBestAPIClass
  File "NVDAObjects\__init__.pyo", line 197, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 103, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 357, in isUIAWindow
  File "_UIAHandler.pyo", line 345, in _isUIAWindowHelper

ERROR - eventHandler.executeEvent (15:57:03.270):
error executing event: mouseMove on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x058DF950> with extra args of {'y': 73, 'x': 1087}
Traceback (most recent call last):
  File "eventHandler.pyo", line 152, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 930, in event_mouseMove
  File "NVDAObjects\IAccessible\__init__.pyo", line 146, in expand
AttributeError: 'NoneType' object has no attribute 'rindex'

**Comment by ironcross32** [comment] 2018-10-22 18:39
This also happens to me, and on another machine as well, but this time, it was on YuTube, so there may be a deeper issue with landmark navigation.

**Comment by ironcross32** [comment] 2018-10-24 02:16
This happened again on a fresh install of win 10 for unrelated issue, and it crashed so bad it crashed explorer and I had to sign out to get access again. I don't know which side is at fault here, or some strange interaction between the two, but this has the potential to be bad.

**Comment by Adriani90** [comment] 2019-04-22 20:33
@k-kolev1985 could you please test if this is reproducible for you? I am using Skype electron for desktop 8.43.0.56 and I cannot reproduce it in NVDA 2019.1.1.

**Comment by k-kolev1985** [comment] 2019-04-23 06:15
No, i can't reproduce it either with Skype 8.44 and latest NVDA alpha snapshot.

**Comment by Adriani90** [comment] 2019-04-23 09:02
closing as works for me.

**Closed by Adriani90** 2019-04-23 09:02 UTC
Labels: worksforme
