### ISSUE TITLE
Outlook 2013- some messages are not at all read with say all or with arrows.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4910] opened 2015-02-12 08:31 UTC
**Reported by sumandogra on 2015-02-12 08:31**
Outlook 2013
Some messages such as msgs from linkedin  are not read at all with say all or arrows.  Only the table dimensions are announced.  Please see the attachment which is a saved outlook message which is not read with NVDA.  
 Linkedin messages that have invitations, updates are examples of such messages that are not read by NVDA.

**Comment by ehollig** [comment] 2017-08-17 14:19
Maybe I am missing it, but I do not see tables in the attached message. Could someone else try this? I am using Outlook 2016.

**Comment by Adriani90** [comment] 2019-01-20 02:42
But comming back to the original issue, I cannot reproduce the initial issue. The message is properly read by NVDA when using arrow keys or say all command.
@sumandogra are you still able to reproduce it? I tested in Outlook 2010 and Outlook 365.

**Comment by Qchristensen** [comment] 2019-01-21 05:33
FIrstly, just for anyone interested, you can view the source HTML for an open email message in Outlook with Alt+h, a, o, a.

There is what looks like a layout table, I think just to show the text as black on a white background, with a grey border either side.

In Outlook 365, I can reproduce being able to move as if in a (2 column by 1 row?) table as per Adriani's comment, and I can't navigate to previous or next table.

I can read the whole message fine as well though.  So based on that, I would view this as an oddity, but not overly problematic.  Does anyone have an example of an email which presents like this and where it does cause reading problems?

**Comment by Adriani90** [comment] 2019-01-24 20:42
I am closing it as works for me now and we can reopen it, if someone reports it again. Thanks Quentin for your valuable input.

**Closed by Adriani90** 2019-01-24 20:42 UTC
Labels: bug, worksforme
