### ISSUE TITLE
error sounds when navigating through web page in chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5702] opened 2016-01-22 18:58 UTC
when surfing the so-
[nvda erro chrome.log.txt](https://github.com/nvaccess/nvda/files/101274/nvda.erro.chrome.log.txt)
called NVDA page with the arrows below making use of chrome, error sounds are heard.
 Attached a log file with the errors reported.

**Comment by fernando-jose-silva** [comment] 2016-01-29 21:26
Good night dear, did not realize the problems most in chrome 48.
 Thank you so much.

**Comment by jcsteh** [comment] 2016-03-30 06:51
Duplicate of #5256, which has been fixed resultant to a fix in Chrome.

**Closed by jcsteh** 2016-03-30 06:51 UTC
Labels: duplicate, GoogleWork
