### ISSUE TITLE
Chrome: NVDA is slow when navigating the messages list on Outlook Office 365

### ISSUE THREAD

**Issue by mohammad-suliman** [nvaccess/nvda#10489] opened 2019-11-13 22:52 UTC
### Steps to reproduce:
* Run NVDA and Google Chrome latest versions on windows 7.
* Go to:
 https://outlook.office.com/mail/inbox
* Navigate to the messages list using tab or Ctrl + F6 if required.
* Try to navigate the messages list quickly using up and down arrows.
### Actual behavior:
In many cases, it takes for NVDA more than 2 seconds to report the message under the focus.
### Expected behavior:
NVDA should report the message under the focus immediately as soon as it receives the focus.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Windows 7 Professional 64-bit service pack 1
#### Name and version of other software in use when reproducing the issue:
Google Crome latest: version 78.0.3904.97 64-bit
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by mohammad-suliman** [comment] 2019-11-14 13:18
Further observations shows that the lag happens when the focus moves from read an unread messages. To clarify: let's assume we have 5 messages in the messages list, the first one is read, the second is unread, the third is read and so on... If i move the focus with down arrow from the first to the second, then here we will have a big lag. If the first and second and third is all read or unread, then moving the focus from the first to the second to the third and vies versa won't produce any lag at all.
Also, do I need also to report the bug on the Chromium project? Please let me know if it will be helpful to do that.
Wanted to say also that the bug makes using Outlook on Office 365 not convenient at all with Google Chrome.

**Comment by Adriani90** [comment] 2020-05-17 18:11
Oh yeah that's really slow in Chrome. See this log:

```
IO - inputCore.InputManager.executeGesture (20:09:54.074) - winInputHook (9540):
Input: kb(laptop):upArrow
IO - inputCore.logTimeSinceInput (20:09:56.568) - MainThread (2344):
2.494 sec since input
IO - speech.speak (20:09:56.569) - MainThread (2344):
Speaking ['Ungelesen MTP Content Da ist er! GS Newsflash April 2020 Fr, 10:57 Was war im April in MTP Deutschland los? Besondere Zeiten erfordern Kreativität und Einfallsreichtum. Was unsere Geschäftsstellen aus der aktuellen Situation machen, das könnt ihr unten nachlesen. Viel Spaß beim Stöpern! Danke an alle Kommis, die ei', '1 von 698']
IO - speech.manager.SpeechManager._pushNextSpeech (20:09:56.576) - MainThread (2344):
Sending to synth: ['Ungelesen MTP Content Da ist er! GS Newsflash April 2020 Fr, 10:57 Was war im April in MTP Deutschland los? Besondere Zeiten erfordern Kreativität und Einfallsreichtum. Was unsere Geschäftsstellen aus der aktuellen Situation machen, das könnt ihr unten nachlesen. Viel Spaß beim Stöpern! Danke an alle Kommis, die ei  ', '1 von 698  ', IndexCommand(1743)]
IO - inputCore.InputManager.executeGesture (20:09:58.642) - winInputHook (9540):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (20:10:03.345) - winInputHook (9540):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (20:10:06.538) - MainThread (2344):
3.194 sec since input
IO - speech.speak (20:10:06.539) - MainThread (2344):
Speaking ['Microsoft Azure Starten Sie mit Ihrer kostenlosen Testversion von Microsoft Dynamics 365 Do, 23:40 Melden Sie sich an, um mit der kostenlosen Testversion zu starten. Entdecken Sie, wie Dynamics 365 Ihr Unternehmen vereinen kann Vielen Dank für Ihre Registrierung für eine kostenlose Testversion von Dynamics 365. Name: Adriani Botez Benutzer-', '2 von 698']
IO - speech.manager.SpeechManager._pushNextSpeech (20:10:06.544) - MainThread (2344):
Sending to synth: ['Microsoft Azure Starten Sie mit Ihrer kostenlosen Testversion von Microsoft Dynamics 365 Do, 23:40 Melden Sie sich an, um mit der kostenlosen Testversion zu starten. Entdecken Sie, wie Dynamics 365 Ihr Unternehmen vereinen kann Vielen Dank für Ihre Registrierung für eine kostenlose Testversion von Dynamics 365. Name: Adriani Botez Benutzer  ', '2 von 698  ', IndexCommand(1744)]
IO - inputCore.InputManager.executeGesture (20:10:07.126) - winInputHook (9540):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (20:10:11.597) - MainThread (2344):
4.471 sec since input
```

**Comment by Adriani90** [comment] 2020-05-17 18:15
In Firefox is much faster, between 0.7 and 1.3 seconds:

```
IO - inputCore.InputManager.executeGesture (20:13:24.552) - winInputHook (9540):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (20:13:25.244) - MainThread (2344):
0.692 sec since input
IO - speech.speak (20:13:25.244) - MainThread (2344):
Speaking ['Ungelesen Caroline Engelhardt in Microsoft Teams Caroline hat „MTP“ erwähnt. Mo, 11.05 Allgemein, Veranstaltungen Auch heute möchten wir euch wieder herzlich zu unserem Plenum um 20:00 Uhr einladen.... \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c', '5 von 74']
IO - speech.manager.SpeechManager._pushNextSpeech (20:13:25.249) - MainThread (2344):
Sending to synth: ['Ungelesen Caroline Engelhardt in Microsoft Teams Caroline hat  MTP  erwähnt. Mo, 11.05 Allgemein, Veranstaltungen Auch heute möchten wir euch wieder herzlich zu unserem Plenum um 20:00 Uhr einladen 4 Punkt  \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c \u200c  ', '5 von 74  ', IndexCommand(2033)]
IO - inputCore.InputManager.executeGesture (20:13:28.933) - winInputHook (9540):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (20:13:29.944) - MainThread (2344):
1.011 sec since input
```

cc: @feerrenrut, @aleventhal

I tested in Chrome 81 and NVDA alpha-20220,1c4519a6

**Comment by Adriani90** [comment] 2020-06-16 21:21
cc: @ObjectInSpace

**Comment by ObjectInSpace** [comment] 2020-06-18 22:00
FWIW, I saw what appears to be identical behavior in JAWS. I did not experience significant lag, however I also have a computer with a core i5 and 8 GBs of RAM, so that's not surprising. I did notice however that the lag was increased when moving from a read message to an unread one and vice versa, so I would not be surprised to see more lag on lower end hardware. Filed https://crbug.com/1096752. Thanks for the report!

**Comment by mohammad-suliman** [comment] 2021-03-19 15:47
Thanks for your comments. I no longer can reproduce the issue, but here are things worth mentioning:
* I have upgraded my laptop to a one with much better specs
* I use office 365 rarely nowadays
* The issue is still open on the Chromium side

**Comment by feerrenrut** [comment] 2021-03-26 04:42
I've labelled this as requiring an external fix. It seems unlikely there is anything we can do about this from NVDA's side.

**Comment by seanbudd** [comment] 2022-05-09 01:15
It appears the chrome issue is still open with the last updates in mid 2020.

**Comment by Adriani90** [comment] 2024-01-14 18:46
I cannot reproduce this on Outlook website, the message list works pretty well with NVDA 2024.1 Beta. I am closing as works for me. If anyone else has this problem, please comment and we can reopen. I will also close the Chromium issue and we can report again to Chromium if it occurs again.

**Closed by Adriani90** 2024-01-14 18:46 UTC
Labels: close/worksforme, blocked/needs-external-fix, app/chrome, triaged
