### ISSUE TITLE
impossible to spell an email in sender list in thunderbird

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13939] opened 2022-07-22 16:16 UTC
### Steps to reproduce:
1. open an email you received in thunderbird
1. Walk with `tab` to the list
1. press an arrow below to focus on the email address of the person who sent you the email.
1 with laptop keyboard layout try spelling the the address with `nvda + left` and right arrows.

### Actual behavior:
nvda pronounces:

>character 65532

or it will be muted depending on the synthesizer used as voice portuguese brazil maria windows one core

log [tunderbird.txt](https://github.com/nvaccess/nvda/files/9169248/tunderbird.txt)

### Expected behavior:
I hope it is possible to spell out the email address of the person who sent me the email.

This also occurs in the list of email addresses for achieved also with tab.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-25937,0f9c0daf

#### Windows version:
22622.436
#### Name and version of other software in use when reproducing the issue:
thunderbird.exe, Thunderbird 103.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment] 2022-07-23 10:34
A few clients seem to do funny things here. I noticed even as far back as 
Outlook Express that the email address, although heard either says recipient 
or some  character not known.
 I thought it might have been deliberate. Looking at the header though you 
can normally find it between () marks
Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "fernando-jose-silva" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, July 22, 2022 5:16 PM
Subject: [nvaccess/nvda] impossible to spell an email in sender list in 
thunderbird (Issue #13939)

**Comment by seanbudd** [comment] 2022-07-28 06:01
Can you set your symbol pronunciation level to all and test this?|

Does other commands to spell objects work (laptop mode)?
- `NVDA+tab` twice to spell current focus
- `NVDA+l` twice to spell the current line
- `NVDA+control+.` twice to spell the current review text

**Comment by fernando-jose-silva** [comment] 2022-07-28 12:25
thank you very much for the feedback.
setting the score level for all does not change the problem posed
spelling object in focus nvda + tab 2 times works correctly
spelling current line with nvda + l twice doesn't work even with punctuation set to all repeat twice character 65532
Or if you are using the synthesizer windows one core Maria brasil portuguese is muted.
nvda + ctrl + . twice repeat
character 65532
Or if you are using the synthesizer windows one core Maria brasil portuguese is muted.

**Comment by Adriani90** [comment] 2023-08-14 19:57
This is a duplicate of #15161, I am closing this one in favour of the new one which contains a bit more technical discussion.

**Closed by Adriani90** 2023-08-14 19:57 UTC
Labels: close/duplicate
