### ISSUE TITLE
Browse mode with focus focusable elements disabled: When entering focus mode NVDA repeats the focused control

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#11304] opened 2020-06-26 22:01 UTC
### Steps to reproduce:
With the recent NVDA Alpha in which focus focusable elements in browse mode is disabled by default:
1. In Firefox open https://github.com/nvaccess/nvda/issues/new?template=bug_report.md
2. Navigate with e key to the "commend body" edit field.
3. Press enter to activate focus mode.

### Actual behavior:
NVDA repeats "commend body < edit multiline" which we already know as we navigated to this field.
### Expected behavior:
No repetition
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA version alpha-20400,675c4c54
#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 79
#### Other information about your system:
Does not occur with "automatically set focus to focusable elements" set to on. This is not intermittent but can be reproduced more often than not.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not relevant

**Comment by lukaszgo1** [comment] 2020-06-26 22:03
cc @jcsteh @codeofdusk @feerrenrut

**Comment by lukaszgo1** [comment] 2020-06-27 10:32
@Adriani90  @leonardder Could one of you add a regression label to this one please?

**Comment by Adriani90** [comment] 2020-06-27 23:43
@lukaszgo1 I am not sure this is a bug actually. It is related to #11206. When you have disabled automatically set focus to focusable elements and you enter focus mode, the system focus will be automatically moved to the current position of the virtual cursor. This had to be done because otherwise the tabindex on websites would not have been honored when testing for accessibility.

What happens here is that NVDA reports the focused element when the system focus moves to it and that's why NVDA repeats it.
@jcsteh is it possible to remove reporting of the element when forcing focus mode? Because actually the user knows the element from browse mode already so it does not expect it to be reported again.
So I think NVDA needs to be silent here when the system focus is forced to move, but I think this is tricky to implement because the movement by tab and shift+tab should not be touched when fixing this issue.

**Comment by jcsteh** [comment] 2020-06-28 22:34
The reporting happens because of the focus event which gets fired after we
switch to focus mode. Fixing this would be tricky, since the focus event
happens asynchronously after we move the focus. To make things more
interesting, there are also cases where you set focus to one thing (e.g. a
list) and another thing gets focus (e.g. a list item in the list).

**Comment by Adriani90** [comment] 2020-07-17 20:22
Actually the reannouncement of the focus is helpful in my opinion. Because I know that the system focus has been draged successfully to the virtual cursor. But yeah, I can imag9nie that for a novice user this might be confusing.
@lukaszgo1 which priority would you see for this from an user perspective? Is it very annoying?

**Comment by Adriani90** [comment] 2024-03-24 11:28
We don't have any complaints from users so far related to this behavior, and indeed when the focus is not synchronized properly when pressing nvda+space bar, NVDA is silent. So repeating the element that gets the system focus after sync is a good validation that sync has succeeded and is still helpful. This can be considered intended behavior. I am closing as won't fix.

**Closed by Adriani90** 2024-03-24 11:28 UTC
Labels: close/wontfix
