### ISSUE TITLE
NVDA is reading the day name incorrectly inside the date picker

### ISSUE THREAD

**Issue by Sandhya-aluri** [nvaccess/nvda#9501] opened 2019-04-18 11:10 UTC
### Steps to reproduce: https://codepen.io/sandhya-aluri/pen/RdJVbx
<img width="809" alt="nvda" src="https://user-images.githubusercontent.com/48669559/56357027-185c5a00-61f8-11e9-8689-03da6ec5df00.png">

**Comment by Brian1Gaff** [comment] 2019-04-18 13:53
Hi maybe  I am misunderstanding here, but using 2019.1.1 on that page and 
opening one of the items with days in it I can hear the days correctly 
spoken in Waterfox. What is your browser?


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Sandhya-aluri** [comment] 2019-04-22 07:14
chrome

**Comment by yuryk53** [comment] 2019-06-06 12:59
The bug is reproduced with office-ui-fabric-react fiddle: https://codepen.io/yuryk53/pen/arrRLz . You could also check https://developer.microsoft.com/en-us/fabric#/controls/web/calendar with Chrome and NVDA.
The bug is reproduced only in Chrome (current version: 75.0.3770.80) with NVDA. In Firefox & Edge works correctly. The HTML markup generated by <Calendar /> component complies with WCAG. Chrome and Narrator work perfectly. So, an NVDA issue

**Comment by Adriani90** [comment] 2020-04-19 14:47
@yuryk53, @Sandhya-aluri how is this now with last Chrome 81 and last NVDA alpha? Or with NVDA 2019.3.1?

**Comment by Adriani90** [comment] 2020-05-16 21:22
Tested in Chrome 81 and Firefox 76 with NVDA alpha-20220,1c4519a6. Everything works as expected now. Closing as works for me.

**Closed by Adriani90** 2020-05-16 21:22 UTC
Labels: close/worksforme
