### ISSUE TITLE
Read-Only Edit Fields: Present in Browse Mode

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6199] opened 2016-07-21 20:18 UTC
When browsing a web page, there may be occasions when a user can encounter a read-only edit field. At the current time, when using NVDA to either navigate to the next/previous edit box or form control these are skipped. Whilst this may make sense due to the fact that these are read-only and can't directly be edited, I've used several pages where directly interacting with a separate control can change the value presented within the edit field which then has to manually be navigated to.

Does anybody (other than me!) see the possible advantage of including these fields in the next/previous form controls/edit box commands?

**Comment by derekriemer** [comment] 2016-07-22 00:03
Duplicate of https://github.com/nvaccess/nvda/pull/6158, https://github.com/nvaccess/nvda/issues/5551

**Closed** 2016-07-22 01:12 UTC

**Comment by leonardder** [comment] 2016-07-22 07:36
Also duplicate of #4164. This is work in progress.
