### ISSUE TITLE
IE 11 reads twice

### ISSUE THREAD

**Issue by chrishanpeiris** [nvaccess/nvda#6198] opened 2016-07-21 09:26 UTC
A link inside a list item read twice in Internet Explorer 11 by the NVDA reader. 

It says "Link 1 visited Link 1"

Structure as follows 

```
<ul> 
  <li> 
   <input type="checkbox" id="heading" checked="true"> 
   <label for="heading" id="lbl" tabindex="0" role="treeitem"> </label>
    <a> 
       <span>Link 1</span> 
   </a> 
</li> 
</ul>
```

How to stop reading it twice ?

**Comment by chrishanpeiris** [comment] 2016-07-21 09:56
Check the below sample in IE 11 with NVDA


<div class="sm-menu-wrapper" id="sm-menu">
    <div class="tw" id="ws">
        <li>
            <a href=sm.html" class="sm"> <span aria-hidden="true" class="gf" title="tt"></span>Main</a></li>
        
        <ul class="mi" role="tree">
            <li class="open"><input type="checkbox" id="hf" checked="true" style="display:none" /> 
            <label for="hf" id="lbl" tabindex="0" role="treeitem"> </label>

                <a href="tt.html" id="pro" tabindex="0"><span>Subitem</span></a>

                <ul class="chd ex">
                    <li id='pp'><input id="sh4" class="ssf" type="checkbox" checked="checked" style="display:none" />
                        <label for="sh4" tabindex="0 " class="sbi" role="treeitem"></label> <a href="gm.html" class="expand-heading">
                            <span data-chkBox='heading'>Sub expand</span></a>

                        <ul class="si">
                            <li role="treeitem"><a href="sm4.html"><span data-chkBox='heading' aria-hidden="true">tree 1</span></a></li>
                            <li role="treeitem"><a href="kl.html"><span data-chkBox='heading' aria-hidden="true">tree 1</span></a></li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

**Comment by chrishanpeiris** [comment] 2016-07-21 09:59
https://jsfiddle.net/chrishanmx/y27xq86e/1/?utm_source=website&utm_medium=embed&utm_campaign=y27xq86e

**Comment by derekriemer** [comment] 2016-07-22 00:17
You are using a ordered list, and expressly putting numbers in. "The <ol> tag defines an ordered list. An ordered list can be numerical or alphabetical.
Use the <li> tag to define list items."
[On W3Schools.](http://www.w3schools.com/tags/tag_ol.asp) Ordered lists order themselves without you having to number anything yourself.
This means that a list as follows
```html
<ol>
<li> 1. Tons.
<li>2. Even more.
<li>3. more, more, more.
</ol>
```
 renders as:
1. 1. Tons
2. 2. Even more.
3. 3. More, more, more!

This can be further illustrated with this example.
```html
<ul start="5">
<li>1 fish
<li>2 Fish
<li> 3 Fish,
<li> 4.
</ul>
```
5. 1 Fish
6. 2 Fish
7. 3 Fish
8. 4

Therefore, this won't double if you leave the numbers out of the ordered list.
Also, having your label with a tabindex of 0 is not recommended, because that means that users of NVDA or other software if they navigate with the tab key will focus the label, which is undesirable.
HTH,
Derek

**Comment by chrishanpeiris** [comment] 2016-07-22 04:15
Thanks Derek for your quick response..

I used un-ordered list to create a menu like this http://codepen.io/allusis/pen/doPLxG

So I want to insert anchor tags in between them and provide access to the menu using tabs..

Any ideas how to do that approach without reading it twice ?

Regards
Chrishan

**Comment by bhavyashah** [comment] 2017-08-25 07:34
This is a friendly reminder for @derekriemer and a gentle request for other web accessibility experts to kindly respond to @chrishanpeiris's https://github.com/nvaccess/nvda/issues/6198#issuecomment-234450734. Also, if the original issue was a result of incorrect web authoring, please let us know if this ticket can be closed as worksforme.

**Comment by derekriemer** [comment] 2017-08-28 19:15
I'm not exactly sure what you intend here.

**Comment by derekriemer** [comment] 2017-08-28 19:16
can you give steps to reproduce the bug you are experiencing?

**Comment by Adriani90** [comment] 2019-03-06 19:36
@chrishanpeiris I cannot reproduce this in NVDA 2019.1 Beta 1. Are you still able to reproduce it?

**Comment by chrishanpeiris** [comment] 2019-03-07 00:41
Sorry I haven't use it after that project.

**Comment by Adriani90** [comment] 2019-03-07 21:28
Closing as works for me. If the issue comes up again, fell free to comment on this one and we can reopen it. or you can open a new one. Thanks for reporting.

**Closed** 2019-03-07 21:29 UTC
Labels: question, worksforme
