### ISSUE TITLE
error while scrolling the tortoisesvn log list when running svn update

### ISSUE THREAD

**Issue by dave090679** [nvaccess/nvda#7874] opened 2017-12-22 10:41 UTC
[nvda_tortoisesvn.zip](https://github.com/nvaccess/nvda/files/1582242/nvda_tortoisesvn.zip)
### Steps to reproduce:
1. open the windows explorer and select a  folder which contains an svn repository
2. run "svn update" from the context menu, the svn update will proced and the progress (log) will be displayed in a list view.
3. navigate in the list view
4. while navigating in the list view, an error sound is played.

### Expected behavior:
the list items should be displayed an spoken whenever you navigate through the list vies.

### Actual behavior:
an error sound is played (and the list items are NOT spoken or displayed whenever you press the arrow keys to navigate in the list view.

### System configuration:
NVDA version:
master-14754,633fd91c

NVDA Installed or portable:
installed

Windows version:
Windows 10 Version 1709 Build 16299.125

Name and version of other software in use when reproducing the issue:
* TortoiseSVN 1.9.7, Build 27907 - 64 Bit
* Subversion 1.9.7, -release

### Other questions:

Does the issue still occur after restarting your PC?
yes

**Comment by feerrenrut** [comment] 2017-12-28 00:47
Thanks for the log. The exact error and trace is:
```
error executing event: gainFocus on <NVDAObjects.IAccessible.sysListView32.ListItem object at 0x0563D110> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 950, in event_gainFocus
  File "NVDAObjects\behaviors.pyc", line 471, in reportFocus
  File "NVDAObjects\__init__.pyc", line 838, in reportFocus
  File "speech.pyc", line 379, in speakObject
  File "speech.pyc", line 273, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 389, in _get_name
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 336, in _getColumnContent
  File "NVDAObjects\IAccessible\sysListView32.pyc", line 328, in _getColumnContentRaw
  File "winKernel.pyc", line 124, in readProcessMemory
ArgumentError: argument 2: <type 'exceptions.OverflowError'>: long int too long to convert
```
And the [exact line in the commit being used](https://github.com/nvaccess/nvda/blob/633fd91cd1e599cf63c8ef2e5411a3a68007e302/source/NVDAObjects/IAccessible/sysListView32.py#L328) (NVDA version master-14754,633fd91c). The call to winKernel just forwards the args on to [readProcessMemory](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680553(v=vs.85).aspx).

This looks like it could be related to the recently introduced support for more than 256 characters in list views for various twitter clients (#7829)

**Comment by derekriemer** [comment] 2017-12-29 03:30
@feerrenrut I have seen This issue for at least 3 years, I don't think it is a regression. it probably affects the translators though quite a bit.

**Comment by leonardder** [comment] 2018-04-13 11:46
This looks like a duplicate of #2693.

**Comment by leonardder** [comment] 2018-04-13 11:52
Coming back to this, I believe this issue is related to running x64 processes, while #2693 has more tod with access rights.

I'm closing this regardless in favour of #8175, which contains a more thorough technical background.

**Closed by leonardder** 2018-04-13 11:52 UTC
Labels: bug, p2
