### ISSUE TITLE
Browse Mode Inadvertently Switched Off When Navigating Rapidly.

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#8701] opened 2018-09-01 09:26 UTC
When I press the up and down arrow keys rapidly to move through lines of an HTML document, Browse Mode toggles off, sometimes causing interaction with a control when no interaction was intended.

This is despite having "Automatic focus mode for caret movement" turned off in NVDA settings -> Browse Mode.

### Steps to reproduce:
- Open a web page.
- Proceed to press up and down arrow with a one second delay between presses. Also try pressing CTRL+up / down.
- Observe that NVDA behaves as expected, moving up and down a web page.
- Now press the navigation keys mentioned above rapidly, allowing for no more than a half second delay. The recommended approach here is to hold a navigation key down, allowing the system to speedily navigate through the document. Make sure to pass over a control during this navigation.

### Actual behavior:
NVDA will toggle off Browse Mode, and you will find yourself either moving through options in a combo box or navigating in Focus Mode in an edit field. This is bad for controls that have JavaScript actions tied to them, because now you've inadvertently caused some action to occur.

### Expected behavior:
NVDA should stay in Browse Mode unless explicitly instructed to  come out of Browse Mode by the user, or the user's settings dictate to leave Browse Mode.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1

#### Windows version:
Version	10.0.17134 Build 17134

#### Name and version of other software in use when reproducing the issue:
Firefox 60.0.1 (64-bit)

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes, all 2018 builds.

**Comment by Adriani90** [comment] 2019-05-07 18:15
@munawarb this is not an issue, this is intended behavior. Controls gaining focus after loading a page (i.e. edit fields, etc.) get focused and focus mode is fired. There were users who actually wanted this behavior and filled issues in the past for it.
Also other controls fire focus mode when you focus them, this is intended (i.e. very helpful in several web tools for webinars etc.). If you want focus mode only for edit fields, then you can just enabled focus changes for carret movement in NVDA setings / browse mode.
I am closing this as works for me.
Please comment on it if you have other arguments on this and we can reopen the discussion.
For java applicatoins, the automatic switch to focus mode can be disabled and there should not be a risk that users perporm unwanted actions.

**Closed by Adriani90** 2019-05-07 18:15 UTC
Labels: worksforme
