### ISSUE TITLE
Impossible to Save Log Entries in Latest Next Snapshot

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#8385] opened 2018-06-11 03:33 UTC
### Steps to reproduce:
1. Open the NVDA log viewer.
2. Try to save with control+s or the save as item in the log menu.

### Expected behavior:
A dialog appears asking where the log should be saved.

### Actual behavior:
The operation fails and the following traceback is displayed.
ERROR - unhandled exception (23:30:52.717):
Traceback (most recent call last):
  File "gui\logViewer.pyc", line 71, in onSaveAsCommand
AttributeError: 'module' object has no attribute 'SAVE'

### System configuration:
NVDA version:
next-15211,8a5d09f0

NVDA Installed or portable:
Installed.

Windows version:
Windows 10 version 1803, build 17134.81.

### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No.

**Comment by Mohamed00** [comment] 2018-06-11 04:44
This isn't happening in master.

**Comment by josephsl** [comment] 2018-06-11 04:52
Hi, confirmed – another reason why we need a lot of feedback regarding #7104. I’ll provide a fix very soon.

Cheers,

Joseph

**Comment by zstanecic** [comment] 2018-06-11 05:01
hi joseph, i can confirm the same,

latest next, windows 10 1803

ERROR - unhandled exception (06:59:58.387):
Traceback (most recent call last):
   File "gui\logViewer.pyc", line 71, in onSaveAsCommand
AttributeError: 'module' object has no attribute 'SAVE'


W dniu 11.06.2018 o 06:52, Joseph Lee pisze:

**Comment by Brian1Gaff** [comment] 2018-06-11 08:52
Actually it does save but it seems whenever a menu is cancelled or opened 
there is a pause during which errors occur but the program seems to work ok 
for me albeit on windows 7
IO - inputCore.InputManager.executeGesture (09:35:25.605):
Input: kb(desktop):escape
DEBUGWARNING - Python warning (09:35:25.608):
C:\nvda extra\library.zip\IAccessibleHandler.py:556: RuntimeWarning: 
tp_compare didn't return -1 or -2 for exception
ERROR - IAccessibleHandler.winEventCallback (09:35:25.608):
winEventCallback
Traceback (most recent call last):
  File "IAccessibleHandler.pyc", line 556, in winEventCallback
wxAssertionError: C++ assertion "m_menuDepth > 0" failed at 
..\..\src\msw\toplevel.cpp(1545) in 
wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?
IO - speech.speak (09:35:25.717):
Speaking [LangChangeCommand ('en_GB'), u'NVDA Log Viewer']
IO - speech.speak (09:35:25.839):
Speaking [LangChangeCommand ('en_GB'), u'edit  read only  multi line']
IO - speech.speak (09:35:25.839):
Speaking [LangChangeCommand ('en_GB'), u'INFO - __main__ (09:33:04.953):\r']
IO - inputCore.InputManager.executeGesture (09:35:29.460):
Input: kb(desktop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (09:35:29.497):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (09:35:29.499):
Speaking [LangChangeCommand ('en_GB'), u'Starting NVDA\r']
IO - speech.speak (09:35:32.236):
Speaking [LangChangeCommand ('en_GB'), u'Log  subMenu  Alt+l']
IO - inputCore.InputManager.executeGesture (09:35:33.869):
Input: kb(desktop):downArrow
IO - speech.speak (09:35:33.898):
Speaking [LangChangeCommand ('en_GB'), u'Refresh\tF5  r  1 of 4']
IO - inputCore.InputManager.executeGesture (09:35:34.733):
Input: kb(desktop):downArrow
IO - speech.speak (09:35:34.770):
Speaking [LangChangeCommand ('en_GB'), u'Save as...\tCtrl+S  a  2 of 4']
IO - inputCore.InputManager.executeGesture (09:35:36.549):
Input: kb(desktop):enter
ERROR - IAccessibleHandler.winEventCallback (09:35:36.552):
winEventCallback
Traceback (most recent call last):
  File "IAccessibleHandler.pyc", line 556, in winEventCallback
wxAssertionError: C++ assertion "m_menuDepth > 0" failed at 
..\..\src\msw\toplevel.cpp(1545) in 
wxTopLevelWindowMSW::DoSendMenuOpenCloseEvent(): No open menus?
IO - speech.speak (09:35:36.950):
Speaking [LangChangeCommand ('en_GB'), u'Save As  dialog']
IO - speech.speak (09:35:36.951):
Speaking [LangChangeCommand ('en_GB'), u'File name:  combo box  collapsed']
IO - speech.speak (09:35:36.957):
Speaking [LangChangeCommand ('en_GB'), u'edit  ALT+n']
IO - speech.speak (09:35:36.957):
Speaking [LangChangeCommand ('en_GB'), u'selected nvda.log']


I changed this and successfully saved it.
 Looks like something is expecting to know if a menu is open or closed but 
does not, whether this matters I guess depends on what you doing.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2018-06-11 09:00
As you will note my error is different in windows 7 but it will save, so any 
fix needs to be sure its not breaking it for other versions of windows.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Mohamed00** [comment] 2018-06-25 17:54
Since this is fixed now, should I close it?

**Comment by josephsl** [comment] 2018-06-25 17:58
Hi, not just yet. I’m sure it’ll be closed once wxPy4 support comes to master branch. Thanks.

**Comment by leonardder** [comment] 2018-06-25 18:08
Hmm, as this is already fixed in next, I agree with @Mohamed00  and see no reason to keep it open.

**Comment by josephsl** [comment] 2018-06-25 18:12
Hi,

I see. Closing as requested.

**Closed by josephsl** 2018-06-25 18:12 UTC
