### ISSUE TITLE
freezing:

### ISSUE THREAD

**Issue by wildcat11** [nvaccess/nvda#5897] opened 2016-04-24 05:11 UTC
When I looked at the nvda.log file it told me that warning trying to recover from freez.

**Comment by josephsl** [comment] 2016-04-24 05:14
Hi, Er, what were you doing? How can we reproduce this? Could you be more specific? Thanks.

**Comment by wildcat11** [comment] 2016-04-24 05:17
[nvdalog.txt](https://github.com/nvaccess/nvda/files/233283/nvdalog.txt)

**Comment by wildcat11** [comment] 2016-04-24 05:21
I was in file explorer in windows 10, and pressed enter to open the documents folder and nvda exited and restarted.

**Comment by derekriemer** [comment] 2016-04-24 13:44
Did it play a ping sound before abruptly restarting? If so, then was it 
unlike the exit sound (windows error sound to be exact)? If it did, 
please attach a crash dump.
https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps

On 4/23/2016 11:21 PM, wildcat11 wrote:
>
> I was in file explorer in windows 10, and pressed enter to open the 
> documents folder and nvda exited and restarted.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5897#issuecomment-213891734>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by wildcat11** [comment] 2016-04-24 22:59
How do I attach a crash dump?
Kenny Peyattt jr.

**Comment by derekriemer** [comment] 2016-04-25 04:48
In the link I provided, please read the part about crash dumps.


On 4/24/2016 4:59 PM, wildcat11 wrote:
> How do I attach a crash dump?
> Kenny Peyattt jr.
>
> On 4/24/2016 9:44 AM, derekriemer wrote:
> > Did it play a ping sound before abruptly restarting? If so, then was it
> > unlike the exit sound (windows error sound to be exact)? If it did,
> > please attach a crash dump.
> > https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps
> >
> > On 4/23/2016 11:21 PM, wildcat11 wrote:
> > >
> > > I was in file explorer in windows 10, and pressed enter to open the
> > > documents folder and nvda exited and restarted.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/nvaccess/nvda/issues/5897#issuecomment-213891734>
> > >
> >
> > --
> > ------------------------------------------------------------------------
> >
> >
> > Derek Riemer
> >
> > * Department of computer science, third year undergraduate student.
> > * Proud user of the NVDA screen reader.
> > * Open source enthusiast.
> > * Member of Bridge Cu
> > * Avid skiier.
> >
> > Websites:
> > Honors portfolio <http://derekriemer.com>
> > Awesome little hand built weather app!
> > <http://django.derekriemer.com/weather/>
> >
> > email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
> > Phone: (303) 906-2194
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nvaccess/nvda/issues/5897#issuecomment-213958926>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5897#issuecomment-214058676>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by ehollig** [comment] 2017-08-16 20:15
@wildcat11, is this still an issue for you or was this a one time thing. If you still are experiencing this issue, please attach a crash dump as suggested by @derekriemer in https://github.com/nvaccess/nvda/issues/5897#issuecomment-213958926

**Comment by Adriani90** [comment] 2018-06-13 20:07
@wildcat11 can you still reproduce this issue?

**Comment by Adriani90** [comment] 2019-02-19 20:42
Ok the author seems not to be available anymore. I am closing this. I couldn't reproduce it ever. @wildcat11 if you are still available, please comment if you still have this issue and we can reopen it. Thanks.

**Closed by Adriani90** 2019-02-19 20:42 UTC
