### ISSUE TITLE
[Preview-MAS Violation]:During scan mode column heading are narrated twice.

### ISSUE THREAD

**Issue by NavyaGoberu** [nvaccess/nvda#9621] opened 2019-05-27 08:46 UTC
User Experience:
User who rely on screen reader if when focus on the column header screen reader is narrating twice user will confuse.

Test Environment:
OS: Windows 10
Browser: Chrome
URL: https://int.onerf.microsoft.com/en-us/enterprise/tablev2?preview=inprogress&variationChoices=*:default

Repro Steps:
Step 1: Open the above URL using any browser.
Step 2: Navigate to section “OneGDCWeb-TableV2-yxfw15b” and press down key to read the table column header.
Step 3 : Verify while pressing down key column header information is narrate twice or not? 

Actual:
While pressing down key when when focus on the column header screen reader is narrating twice of the column header.
Expected:
Screen reader should be narrate the column header information single time.

MAS Reference:
MAS 4.1.2
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={248054a6-5e68-4771-9e1e-242fb5025730}

**Comment by DrSooom** [comment] 2019-05-27 21:50
@NavyaGoberu: Please specify the Win10, the Google Chrome and the NVDA version in the issue description. Thanks.

**Comment by Adriani90** [comment] 2019-08-23 08:39
Duplicate of #10066

**Closed by Adriani90** 2019-08-23 08:39 UTC
Labels: duplicate
