### ISSUE TITLE
NVDA responds slowly in Elements list dialog in Word 2019

### ISSUE THREAD

**Issue by manhcuong0312** [nvaccess/nvda#11947] opened 2020-12-17 09:32 UTC
### Steps to reproduce:
- Run NVDA.
- Open a word document.
- Turn on Browse mode.
- NVDA+F7 to open elements list dialog.
- Tab or Shift+Tab to the type grouping.
- Up / down arrow to choose from the radio buttons.
### Actual behavior:
NVDA displayed the dialog after a few seconds. Sometimes more than five seconds. It was very slow at the type grouping when arrow keys to choose from the radio buttons.
### Expected behavior:
NVDA should open the dialog more quickly, especially at the group of radio buttons.
#### NVDA installed/portable/running from source:
NVDA install, and portable
#### NVDA version:
2020.3 install, and 2020.4beta1 portable
#### Windows version:
Windows 10 pro 64 bit, v20h2
#### Name and version of other software in use when reproducing the issue:
Microsoft Office Word 2019 Professional
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Just those versions, and NVDA 2020.4beta1 responded a little faster.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by bhavyashah** [comment] 2021-02-15 11:40
@manhcuong0312  Is your experience unique to Word 2019, or do you face something similar in Elements Listin other places as well, say on the web? Also, could you give us a count of how many headings, links, etc. were present in this document? I believe the lag is proportional to their quantity. I am genuinely surprised by how remarkably slow NVDA's Elements List dialog is when switching element type as well as when using the Filter By edit box. Is there some equivalent functionality that users of other screen readers can possibly test to get a sense of the speed (or lack thereof) in other software? One suggestion that I might make to developers is to gradually populate the search results of Filter By or the list of instances of a newly selected element type rather than compelling the user to wait until they are all loaded. This would be analogous to how Start Menu and File Explorer searches work. I would like to be respectful of the scope of this ticket, so I would appreciate a nudge in the right direction if my suggestion would be suitable for another issue.

**Comment by manhcuong0312** [comment] 2021-02-28 07:24
Hi @bhavyashah  
I just experience this with MS Word 2019, even using NVDA 2020.4. I've tested using a word document with 53 pages, and 148 element. Also tested using this issue page, and NVDA worked well on this one.

**Comment by cary-rowen** [comment] 2021-02-28 15:57
I also encountered the problem of slow response in the element dialog box, which greatly affects work efficiency.

**Comment by Adriani90** [comment] 2023-09-07 23:17
Closing as duplicate of #6297. Although this issue does not explicitely speak about anotations, the freeze in the elements list is related to a high number of elements and solving that one will very probably solve this as well.

**Closed by Adriani90** 2023-09-07 23:17 UTC
Labels: close/duplicate
