### ISSUE TITLE
In Chrome, NVDA reads the first line of a read-only multi-line text area on down arrow

### ISSUE THREAD

**Issue by segedyjr** [nvaccess/nvda#11149] opened 2020-05-11 13:51 UTC
In Chrome, when focus lands on a readonly textarea element, NVDA stays in forms mode, and pressing the down arrow repeatedly reads the first line of the text area.

### Steps to reproduce:
1. Open Chrome
2. Navigate to https://jsfiddle.net/on5r693q/
3. Tab to the text area
4. Press the down arrow twice

### Actual behavior:
When focus moves to the textarea, NVDA speaks the first line of the textarea. Upon pressing the down arrow key, NVDA again speaks the first line of the text area.
### Expected behavior:
When focus moves to the textarea, NVDA speaks the first line of the textarea. Upon pressing the down arrow key, NVDA speaks the second line of the text area.

**Comment by DrSooom** [comment] 2020-05-12 01:47
Related: Issue #11098

**Comment by Adriani90** [comment] 2020-05-12 16:56
Closing as duplicate of #11098

**Closed by Adriani90** 2020-05-12 16:56 UTC
Labels: close/duplicate
