### ISSUE TITLE
Browse Mode for Windows 10 Store Apps

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5660] opened 2016-01-07 12:49 UTC
In Windows 8 and 8.1, NVDA provided Browse mode capabilities for the Modern? Metro? Windows Apps that were shipped with Windows. This proved to be quite effective. In Windows 10, this functionality is no longer present, thus leaving the user to only tab around the apps. The problem with tabbing is that certain text controls will not be reported in the tab order, leaving the user to only use Object Navigation. Could browse mode be made available?

**Comment by jcsteh** [comment] 2016-01-14 06:25
While many Store apps shipped with Windows 8/8.1 were HTML based (and thus used a web browser engine), a lot of the apps shipped with Windows 10 seem to be XAML based. In short, XAML is a framework which does not use a web browser engine and so we can't do browse mode for it at this stage.

**Comment by josephsl** [comment] 2019-08-16 17:50
Hi,

Actually, this is relevant now that we have progressive web apps (PWA's) hosted inside wwahost.exe. Therefore, reopening.

Thanks.

**Comment by josephsl** [comment] 2019-08-16 17:51
Hi,

I have reopened this issue in hopes that we can get more updated comments and to make sure this is taken care of (technically, PWA's are rendered using EdgeHTML at the moment, which qualifies them as proper webapps; note that we still need to classify them as proper apps; see #9117 for details).

Thanks.

**Comment by leonardder** [comment] 2020-05-02 16:06
I'm tempted to close this again. The issue is too broad. Many windows store apps are electron apps or even win32 apps nowadays. What do you think @josephsl?

**Comment by josephsl** [comment] 2020-05-02 18:47
Hi, some are progressive web apps (PWA’s) where a combination of browse and focus modes are desirable. Besides that, one way to force browse mode (or rather, turn off browse mode forcefully) is telling an app module to enable/disable browse mode for an app. Since it is really up to app developers to specify which frameworks they are going to use, I think it would be best to leave it up to them (closing as requested). Thanks.

**Closed** 2020-05-02 18:47 UTC
