### ISSUE TITLE
Regarding browse mode off suddenly

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5869] opened 2016-04-08 08:13 UTC
Hello, I'm Hyongsop Kim in Korea.

In browse mode with ie or ff, once I move arrow keys to navigate web page too fast, browse mode is suddenly turned off in edit box.
Of course once I move slowly, it doesn't be turned off, but if I navigate so fast and there are some edit boxes, browse mode is off in edit box, of course it is not turned off first edit box always.
The spot is different every time.
Please check this issue.

Thank you.

**Comment by Brian1Gaff** [comment] 2016-04-08 09:19
How have you got the  options checked for automatically going into focus 
mode etc?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by khsbory** [comment] 2016-04-08 09:22
No, I didn't check automatic browse mode off if focus to edit box.
 
Thank you. 
 
  
김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 대리	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark

  
-----Original Message-----

**Comment by jcsteh** [comment] 2016-04-08 09:57
Duplicate of #2039.

**Closed by jcsteh** 2016-04-08 09:57 UTC
Labels: duplicate
