### ISSUE TITLE
not reading tool tip for PDF signature field 

### ISSUE THREAD

**Issue by privatmamtora** [nvaccess/nvda#5664] opened 2016-01-07 18:53 UTC
When on a signature field it only says "Signature field is unsigned".

I have multiple signatures in document and I am using the tooltip to tell whom the signature field is for.
Sometimes with other instructions.

Would this be a NVDA issue?

**Comment by jcsteh** [comment] 2016-01-10 23:04
Can you please provide a simple test case? Thanks.

**Comment by privatmamtora** [comment] 2016-01-10 23:55
Created a document from scratch.
[Test Sig.pdf](https://github.com/nvaccess/nvda/files/85234/Test.Sig.pdf)

It seems that if you allow it to read whole document (when opened), it does read the signature's tooltip.
(Mostly unlikely since user will/might stop in-between, if document is long)

But, it doesn't speak the tooltip if you TAB to the signature field.

**Comment by bhavyashah** [comment] 2018-08-19 01:33
@privatmamtora Could you please retest this issue with more recent versions of NVDA and Adobe Acrobat DC and kindly provide a status update for this ticket?

**Comment by Adriani90** [comment] 2019-02-12 13:54
@privatmamtora testing with NVDA 2017.4 on Windows 8.1 and last version of Adobe reader, I cannot reproduce this issue. The tooltipp is reported both when navigating with arrow keys and when changing to focus mode and navigating by tab. Could you please test in NVDA 2018.4.1 if the issue still occurs? Thanks.

**Comment by Adriani90** [comment] 2019-02-18 22:37
Testing with NVDA alpha-16768,a6f7fb40 and las Adobe reader version, I cannot reproduce this issue. Closing as works for me. Feel free to comment on it if you still have this issue and we can reopen it.

**Closed by Adriani90** 2019-02-18 22:37 UTC
Labels: AdobeWork, worksforme

**Comment by AllenWrenches** [comment] 2020-09-29 15:59
I'm having the exact same issue as described in this issue. 

NVDA version 2020.2
Adobe Reader version 2020.12.20043

**Comment by JulienCochuyt** [comment] 2021-05-06 18:14
@Adriani90, would you please be able to re-test this in order to qualify a potential regression?
