### ISSUE TITLE
Try to switch to next in youtube,a com error is triggered.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#6133] opened 2016-07-03 07:36 UTC
Hi:
Step to reproduce:
1. Open the address:https://www.youtube.com/watch?v=6kgJBzCXr4Y
2.  Try to navagate to the next button.
Error log is below:
ERROR - scriptHandler.executeScript (15:27:54):
error executing script: <bound method MSHTML.script_nextLink of <virtualBuffers.MSHTML.MSHTML object at 0x05A7CDF0>> with gesture u'k'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "browseMode.pyc", line 317, in <lambda>
  File "browseMode.pyc", line 308, in _quickNavScript
  File "browseMode.pyc", line 190, in moveTo
  File "browseMode.pyc", line 1104, in _set_selection
  File "browseMode.pyc", line 1119, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 916, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))

**Comment by Brian1Gaff** [comment] 2016-07-03 13:12
Firefox cannot see a next button.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by bhavyashah** [comment] 2017-07-21 08:31
I cannot reproduce the described behaviour with Firefox 54 stable with the given YouTube video. Just to be clear, by 'next button', I take it that you mean pressing the single-letter navigation key 'b' to jump to the next button. Otherwise, the YouTube interface control is the Next link and not any button, the option that allows you to move to the next video in YouTube. I @vgjh2005 I would appreciate a clarification about the meaning of 'next button', and an update as to whether or not you still encounter this problem.

**Comment by vgjh2005** [comment] 2017-07-25 13:09
Hi:
I guess this bug is about specific language( example simplified Chinese etc). Because when press arror keys to navigate the play area, many com error are catchd. 
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 366, in Notify
  File "IAccessibleHandler.pyc", line 875, in pumpAll
  File "IAccessibleHandler.pyc", line 668, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 684, in processFocusNVDAEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 635, in _get_shouldAllowIAccessibleFocusEvent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 793, in _get_states
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:06:02.091):
error executing script: <bound method MSHTML.script_moveByLine_back of <virtualBuffers.MSHTML.MSHTML object at 0x04EF07B0>> with gesture u'\u4e0a\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 205, in script_moveByLine_back
  File "cursorManager.pyc", line 139, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1159, in _set_selection
  File "browseMode.pyc", line 1174, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:06:02.868):
error executing script: <bound method MSHTML.script_moveByLine_back of <virtualBuffers.MSHTML.MSHTML object at 0x04EF07B0>> with gesture u'\u4e0a\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 205, in script_moveByLine_back
  File "cursorManager.pyc", line 139, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1159, in _set_selection
  File "browseMode.pyc", line 1174, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:06:06.144):
error executing script: <bound method MSHTML.script_moveByLine_forward of <virtualBuffers.MSHTML.MSHTML object at 0x04EF07B0>> with gesture u'\u4e0b\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 209, in script_moveByLine_forward
  File "cursorManager.pyc", line 139, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1159, in _set_selection
  File "browseMode.pyc", line 1174, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (21:06:06.486):
error executing script: <bound method MSHTML.script_moveByLine_forward of <virtualBuffers.MSHTML.MSHTML object at 0x04EF07B0>> with gesture u'\u4e0b\u5149\u6807'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 209, in script_moveByLine_forward
  File "cursorManager.pyc", line 139, in _caretMovementScriptHelper
  File "browseMode.pyc", line 1159, in _set_selection
  File "browseMode.pyc", line 1174, in _shouldSetFocusToObj
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 944, in _get_isFocusable
  File "comtypes\client\lazybind.pyc", line 207, in __call__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2147352319, None, (None, None, None, 0, None))

**Comment by Adriani90** [comment] 2019-03-06 19:57
@vgjh2005 is this still an issue in NVDA 2019.1 Beta 1?

**Comment by Adriani90** [comment] 2019-07-16 12:17
We do not have updates on this issue since a very long time and I cannot reproduce it. I also changed the NVDA language to chinese simplified etc. It might be an issue related to the synthesizer but it seems we lost contact to the initial author and we cannot assess this. I am closing this issue as works for me. Feel free to comment on it if you can reproduce it and we reopen the discussion.

**Closed by Adriani90** 2019-07-16 12:17 UTC
Labels: worksforme
