### ISSUE TITLE
Steam Availability with Nvda

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#8196] opened 2018-04-22 11:16 UTC
Hello. I understand that not many people use steam, but I would like to offer to improve its availability with NVDA.Now it is possible to use steam only with the help of OCR but personally I do not always activate menu items.
I use OCR on Windows 10 1803.

**Comment by gdata1** [comment] 2019-05-08 15:03
Unfortunately, steam developers do not want to be contacted on this issue. I tried a few more people.

**Comment by Adriani90** [comment] 2023-05-05 23:02
The steam developers are now more open to accessibility topics, in fact the last version of the steam client is not perfect but by far much better than before. To use the settings panel and other inaccessible areas you must enable the big picture mode. But yeah, for that you have to use OCR first.

**Comment by Adriani90** [comment] 2023-08-24 12:49
Given there is now a native steam mode which makes steam accessible, I am closing this as works for me.
For certain issues with the app, contact the developer first and otherwise post new issues with NVDA for single actions with detailed steps to reproduce here on Github.

**Closed by Adriani90** 2023-08-24 12:49 UTC
Labels: close/worksforme
