### ISSUE TITLE
Hot Key Conflict in Excel Elements List

### ISSUE THREAD

**Issue by mohithbp** [nvaccess/nvda#5543] opened 2015-11-26 08:36 UTC
The hot key "Alt+F" is the same for Formulae radio button and the Filter edit box.
Whenever the hot key is pressed the focus is going to the "filter" edit box. One has to navigate all the way to the list of radio buttons and navigate with the arrow keys to select the radio button.
This results in lack of efficiency in the work environment.

Please change the hot key of one of the controls.
Thought: Alt+L for formulae or Alt+T for Filter.

**Comment by nvdaes** [comment] 2015-11-26 11:01
This is a duplicate of #5527

**Closed** 2015-11-26 11:55 UTC
Labels: duplicate
