### ISSUE TITLE
Support quick navigation by article in browse mode

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#9227] opened 2019-02-02 10:29 UTC
### Is your feature request related to a problem? Please describe.

I propose that NVDA implement a quick navigation key for browse mode that allows to skip back and forward by articles. So far, this is done via the Enhanced ARIA add-on, which simply expands the landmark navigation to include articles. However, with many articles, the rest of the landmarks get drowned out easily, so it makes sense to use a separate keystroke specifically for articles.

### Describe the solution you'd like

* Introduce a new keystroke in quick nav scripts to jump back and forward between article elements on a page. Alternatively, repurpose the keystroke previously used to navigate among Flash objects. Flash is dead, so it makes sense to repurpose this keystroke. Mozilla announced that Flash will be gone in Firefox 69, and object navigation, with the last of the NPAPI plugins gone, is then obsolete.
* When navigating with the virtual cursor, announce when the user enters a new article similar to what is being done for other landmarks.

### Describe alternatives you've considered

Using the Enhanced ARIA add-on, which works on and off depending on the new NVDA add-on compatibility feature, making this unreliable, but the need for this kind of navigation is definitely there. Also, see above, using the same landmark navigation also for articles drowns other landmarks.

### Additional context

Many websites like the new Twitter, AKA [Mobile Twitter](https://mobile.twitter.com), or [Threema Web](https://web.threema.ch), or the [Mastodon](https://mastodon.social) or [Pinafore](https://pinafore.social) Mastodon clients use articles to separate one message or tweet from one another. In addition, the [Feed design pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#feed) in WAI-ARIA 1.1 encourages to group entities by elements with the article role to separate them and make them navigable.

**Comment by leonardder** [comment] 2019-02-02 11:56
This looks like a duplicate of #7835.

[**@MarcoZehe**](https://github.com/MarcoZehe) commented on [2 Feb 2019, 11:29 CET](https://github.com/nvaccess/nvda/issues/9227#issue-405970630 "2019-02-02T10:29:21Z - Replied by Github Reply Comments"):
> Alternatively, repurpose the keystroke previously used to navigate among Flash objects. Flash is dead, so it makes sense to repurpose this keystroke. Mozilla announced that Flash will be gone in Firefox 69, and object navigation, with the last of the NPAPI plugins gone, is then obsolete.

Note that object navigation (with o) also navigates to audio and video tags, and I believe even embedded applications.

I think we really need to make a decision on how to go forward with quick navigation keys. There are several open requests for new quick navigation keys, including splitting annotations into multiple other quick navigation scripts.

**Comment by bramd** [comment] 2019-02-02 18:53
I'm totally for a way to navigate to (and announce) articles. However, @leonardder has a valid point about the number of quicknav keys that are around and new ones requested. Some kind of ring with the lesser used options might be helpful so we free up keys for new usage?

**Comment by Andre9642** [comment] 2019-02-02 19:16
I'd also like to see this in NVDA Core. 
There are still some free keys: j, p, y and z. Why not one of them?

**Comment by bdorer** [comment] 2019-02-02 19:20
What about leaving this and others unasigned and allow people to asign 
keys in input manager?

Am 02.02.2019 um 19:53 schrieb Bram Duvigneau:

**Comment by Dan503** [comment] 2019-05-04 03:56
As a quick solution to many of the problems around the `<article>` element, I'd suggest simply treating `<article>` the exact same way as how `<section>` is treated except announce it as "article" rather than "region".

At the moment NVDA treats `<article>` the same way that it treats `<div>` which is a major accessibility issue. This should be fixed as soon as possible.

Refinements around what creates the best UX around the `<article>` element are less of a priority and can be handled in later updates.

**Comment by josephsl** [comment] 2019-05-04 04:14
Hi,

May we get an evidence or two (links to example websites, specs, etc.) supporting this idea please? That way we can ask people to review that while others are working on Python 3 transition and other work.

CC @JCSTeh if he has anything for us to think about.

Thanks.

**Comment by Dan503** [comment] 2019-05-04 04:28
Hi @josephsl,

`<article>` is one of the four "sectioning content" elements `<article>`, `<aside>`, `<nav>`, `<section>`
https://www.w3.org/TR/html5/dom.html#sectioning-content

These elements are all very similar to one another.

- They are all aria land marks that people should be able to navigate to when navigating via landmarks.
- They all affect the document outline algorithm (If it was ever implemented).
- They can all be labeled using either `aria-label`, `aria-labelledby`, or a `<h#>` element.

Also see these links:
- https://www.w3.org/TR/html5/sections.html#headings-and-sections
- https://www.w3.org/TR/html5/sections.html#the-article-element

**Comment by MarcoZehe** [comment] 2019-10-24 10:42
Also, the feed design pattern in the WAI-ARIA 1.1 spec calls for article, or elements that have role="article" set, to be separate items users shold be able to navigate to.

Discourse, when displaying a topic, has each post in an article, which is not denoted in any way otherwise, but if NVDA supported navigating to these by default, would browsing a topic and its comments easily.

I already mentioned Twitter, which by now is the new PWA everywhere, and Mastodon, plus the Pinafore alternative client for it. Facebook uses articles to separate posts, and each comment after a post. Many WordPress themes use articles on their main page to separate the different article teasers. However, there, headings are usually also present, so the matter becomes a little less pressing here.

As you can see, there are many examples that call for article to be treated like something that can be navigated to via quick navigation. I'd settle for implementing the script without a gesture, so I can then assign my own gesture to it, but at least having it would be awesome.

**Comment by Dan503** [comment] 2019-10-24 12:01
> They are all aria landmarks that people should be able to navigate to when navigating via landmarks.

I was actually wrong about that. `<article>` elements are not landmarks.

**Comment by leonardder** [comment] 2019-10-24 17:58
I started working on support for article. The first part of that is making articles actually report as such, and that's now done. The second part will be adding the ability to add quicknav scripts without default assignments.

**Comment by JulienCochuyt** [comment] 2019-10-29 07:27
@leonarder, This is indeed a long awaited feature, thanks a lot for your work on PR #10424.

I understand that unbound gestures are an effective way to have features implemented despite the difficulty to settle on consuming a gesture. Nevertheless, (almost) unlocalized gestures have proven to be quite a strength of NVDA. Not binding a gesture that might interest quite a lot of people leads to unnecessary difficulties for lesser experienced users.

As others already pointed out, there is a strong need for quick navigation to more elements than we have available keys: eg. articles, tabs, font attributes, temporary jump-back marker, …
Not blocking PR #10424 at all, I really think we should go on defining our way to address these needs in a way that does not ask new users to define their own gestures.

A few alternatives:
 - consider binding j, p, y and/or z
 - quick nav ring à-la VoiceOver: Can handle many cases, but not as efficient as direct keys and requires a way to quickly toggle what is in the ring and in which order.
 - reconsidering older/potentially-seldom-used keys: What is the percentage of use for a, n, q, s, u and v?
 - (OT?) consider context awareness: We could consider limiting "i" to the current list or a heading level to the current higher header level (ie. only quick nav to the next h2 within the current h1). UX could go something like "no next/previous X in current Y, press again to search outside"

**Comment by lukaszgo1** [comment] 2019-10-29 13:57
@JulienCochuyt wrote:


> I understand that unbound gestures are an effective way to have features implemented despite the difficulty to settle on consuming a gesture. Nevertheless, (almost) unlocalized gestures have proven to be quite a strength of NVDA. Not binding a gesture that might interest quite a lot of people leads to unnecessary difficulties for lesser experienced users.

I would go a step further and say that for most users an unbound by default gesture may not exists at all.

> 
> As others already pointed out, there is a strong need for quick navigation to more elements than we have available keys: eg. articles, tabs, font attributes, temporary jump-back marker, …
> Not blocking PR #10424 at all, I really think we should go on defining our way to address these needs in a way that does not ask new users to define their own gestures.

Some commends about your proposals below, however what I think would help here would be to make different keybindings for browsers and for MS Word. In this particular case the letter 'a' would be free in browse mode (I do not think there is any use for annotations in web browsers). Also navigation to different font attributes would be mostly useful in MS Word, so it would solve also this problem.




> 
>     * reconsidering older/potentially-seldom-used keys: What is the percentage of use for a, n, q, s, u and v?

May I ask how you've chosen these particular keys? I am personally using these a lot (with an exception of 'a' as mentioned above).

> 
>     * (OT?) consider context awareness: We could consider limiting "i" to the current list or a heading level to the current higher header level (ie. only quick nav to the next h2 within the current h1). UX could go something like "no next/previous X in current Y, press again to search outside"




JAWS developers used this approach a few years ago. From user perspective this was very confusing. The final argument against this is the fact that Vispero changed this behavior to make it like NVDA. It looks like it had its problems.

**Comment by JulienCochuyt** [comment] 2019-10-29 14:57
> @JulienCochuyt wrote:
> 
> > I understand that unbound gestures are an effective way to have features implemented despite the difficulty to settle on consuming a gesture. Nevertheless, (almost) unlocalized gestures have proven to be quite a strength of NVDA. Not binding a gesture that might interest quite a lot of people leads to unnecessary difficulties for lesser experienced users.
> 
@lukaszgo1 wrote:
> I would go a step further and say that for most users an unbound by default gesture may not exists at all.

I quite agree with your view here.

> Some commends about your proposals below, however what I think would help here would be to make different keybindings for browsers and for MS Word. In this particular case the letter 'a' would be free in browse mode (I do not think there is any use for annotations in web browsers). Also navigation to different font attributes would be mostly useful in MS Word, so it would solve also this problem.

Good point for "a" that could serve another purpose where annotations do not exist.
I don't think we should further diverge, though, in order to preserve the new user learning curve.

> > ```
> > * reconsidering older/potentially-seldom-used keys: What is the percentage of use for a, n, q, s, u and v?
> > ```
> May I ask how you've chosen these particular keys? I am personally using these a lot (with an exception of 'a' as mentioned above).

These are just my personal lesser/un- used. Thanks for providing a first counter example to my bad intuition.

For the (OT?) context awareness question, I've just found out #8193 which might be a better place to further debate.

**Comment by lukaszgo1** [comment] 2019-10-29 18:30
@JulienCochuyt wrote:

> Good point for "a" that could serve another purpose where annotations do not exist.
> I don't think we should further diverge, though, in order to preserve the new user learning curve.

We have two options here:
We can make commands different for MS Word  and for web browsers potentially making new users slightly confused but improving the situation with not enough quick nav keys or leave it as is and look for another solution. Making a few new users confused is in my view small price to pay. Additionally for people migrating from both JAWS and WE it is obvious that Word and browsers do not share the same quick nav keys.


> 
> For the (OT?) context awareness question, I've just found out #8193 which might be a better place to further debate.


I agree as it would not improve the situation of not enough quick navigation keys.

**Closed** 2019-10-29 22:27 UTC

**Comment by Anubarak** [comment] 2021-05-31 07:50
Not sure if I should write here or create another issue that might be closed instantly but I'm not sure if it's really fixed or if I do something wrong.
My NVDA reader does not read articles the same way it reads sections.
Just a simple JS Fiddle https://jsfiddle.net/7kumjzhg/
Works for `section` but not for `article`

**Comment by Dan503** [comment] 2021-05-31 07:54
@Anubarak I went looking in the settings and article support seems to be turned off by default. I don't know why it is disabled by default.

Try turning article support on.

**Comment by XLTechie** [comment] 2021-05-31 07:57
Have you assigned a key to article navigation under Browse Mode in Input 
Gestures?

**Comment by Anubarak** [comment] 2021-05-31 08:24
@Dan503 @XLTechie Doh. Thank you very much for your quick response. That was indeed the case - I didn't know that.
It works now

**Comment by Dan503** [comment] 2021-05-31 08:37
There is a question around why it is disabled by default though and requires the user to set up custom key bindings.

It doesn't make sense not having that turned on by default. 😕
