### ISSUE TITLE
Quicknav Keys not working in Outlook 2016

### ISSUE THREAD

**Issue by taymun26** [nvaccess/nvda#7471] opened 2017-08-02 21:27 UTC
Steps to reproduce:

1. Open Outlook 2016
2. In the mail list, open any mail which contains a link or table, etc.
3. Press "u" letter in case there is a link.
Expected: NVDA should jump to the next linkk.
In this case NVDA does not do anything.

Tested with current Next snapshot.

**Comment by taymun26** [comment] 2017-08-02 21:37
=== Further details 

OS: Windows 7
NVDA version: > Snapshot 14200 (tested with different versions)

Restarting Outlook or Windows did not help.

**Comment by PratikP1** [comment] 2017-08-03 08:23
taymun26 wrote: 
> 3. Press "u" letter in case there is a link.
Navigating by using letter u is not supported in Outlook. You should use letter "k" instead to move from link to link. "U" is used to navigate from unvisited link to unvisited link. In the steps above, if you substitute "k," it works. I am unable to replicate the behavior you outlined.

**Comment by dkager** [comment] 2017-08-06 16:16
@taymun26 Could you confirm whether pressing "k" works?
I can't reproduce on Windows 10.

**Comment by fisher729** [comment] 2017-08-07 01:07
@taymun26, do you hear '"not supported in this document" when you press this letter? That's the behaviour in Word, and since this is also an Office application, the same should apply for Outlook, where it doesn't work. Could others test?

**Comment by ehollig** [comment] 2017-10-01 01:10
Closing as worksforme because of the description provided in https://github.com/nvaccess/nvda/issues/7471#issuecomment-319902521. When I press "U" or "V" in an Outlook 2016 message, NVDA announces, "Not supported in this document."

**Closed by ehollig** 2017-10-01 01:10 UTC
