### ISSUE TITLE
Microsoft Outlook raises AttributeError of NVDA when cancelling message composition

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#6196] opened 2016-07-21 07:24 UTC
Actually, the error does not occur always, however, it occurs when the cancelation is repeatedly performed several times.

Setup
- Windows 10 (32bit English) + Office 365 Outlook (English)
- NVDA next-13436 (portable without add-ons)

Steps
- launch Outlook, Alt+H N (New Email) to open "Untitled - Message (HTML)" window
- press Tab several times to go to composition window
- type something
- press Esc to show "Want to save your changes?" dialog of Outlook
- press Esc again. the dialog closes and return to "Untitled" window.
- press Esc twice again. after several trials, the error raises as follows.

The original issue is reported in Japan, from a person who uses Windows 7 and Outlook 2007 in Japanese environment.

```
INFO - __main__ (16:07:58):
Starting NVDA
INFO - core.main (16:07:59):
Config dir: C:\nvda\userConfig
INFO - core.main (16:07:59):
NVDA version next-13436,180dc743
INFO - core.main (16:07:59):
Using Windows version 10.0.14393 workstation
INFO - core.main (16:07:59):
Using Python version 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
INFO - core.main (16:07:59):
Using comtypes version 0.6.2
INFO - synthDrivers.espeak.SynthDriver.__init__ (16:08:00):
Using eSpeak version 1.48.15  16.Apr.15
INFO - synthDriverHandler.setSynth (16:08:01):
Loaded synthDriver espeak
INFO - core.main (16:08:01):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (16:08:01):
Using liblouis version 3.0.0.alpha1
INFO - braille.BrailleHandler.setDisplayByName (16:08:01):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (16:08:01):
Braille input initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (16:08:01):
UIAutomation: IUIAutomation3
INFO - core.main (16:08:02):
NVDA initialized
INFO - updateCheck.AutoUpdateChecker._started (16:08:02):
Performing automatic update check
INFO - config.ConfigManager.save (16:08:04):
Base configuration saved
ERROR - eventHandler.executeEvent (16:08:46):
error executing event: gainFocus on <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x04D2A970> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 892, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 804, in reportFocus
  File "speech.pyc", line 370, in speakObject
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\window\winword.pyc", line 528, in __init__
AttributeError: 'NoneType' object has no attribute 'range'
ERROR - eventHandler.executeEvent (16:08:46):
error executing event: caret on <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x04D2A970> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\IAccessible\__init__.pyc", line 1280, in event_caret
  File "NVDAObjects\window\winword.pyc", line 1035, in event_caret
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\window\winword.pyc", line 523, in __init__
AttributeError: 'NoneType' object has no attribute 'range'
```

**Comment by Adriani90** [comment] 2019-03-06 19:39
@nishimotz there were several improvements made regarding to similar issues. Are you still able to reproduce the issue in NVDA 2019.1 Beta 1?

**Comment by nishimotz** [comment] 2019-03-09 02:31
I have not tested with beta, however, not reproduced the issue with the setup as follows:

* NVDA alpha 16885 (tested with both Word UI Automation is turned on and off)
* Windows 10 version 1809 64bit Japanese
* Office 365 Outlook version 1902

**Comment by Adriani90** [comment] 2019-03-09 10:14
@nishimotz thank you very much. Closing as works for me.

**Closed by Adriani90** 2019-03-09 10:14 UTC
Labels: p3, worksforme
