### ISSUE TITLE
Espeak randomly announces characters in strange languages in daisy books from bookshare

### ISSUE THREAD

**Issue by mreiser** [nvaccess/nvda#7983] opened 2018-02-09 23:12 UTC
### Steps to reproduce:
1. Download the following book from bookshare.  
All in 1 Network plus by Mike Meyers.  
1. Open it in an app that can read daisy books such as qread.  
1. In qread, press `control+T` and navigate to chapter 2. 
1. Start reading. 
EspeakNG will act like it is switching to a different dialect or language while reading the book, making it almost unintelligible at times.  I'll copy and paste some lines to give examples. 
   * Describe how models such as the OSI seven-layer model and the TCP/IP model help technicians understand and troubleshoot networks
   * Explain the major functions of networks with the OSI seven-layer model
   * Describe the major functions of networks with the TCP/IP model

### Expected behavior:
Espeak should read normally.  

### Actual behavior:
Espeak acts like it is switching languages.  I'm not sure if this is nvda specific or an espeak issue so thought I'd report here first.  

### System configuration:
NVDA version: 2017.4
NVDA Installed or portable: Installed
Other information:

Windows version:
Windows 10 version 1709 build number 16299.192
Name and version of other software in use when reproducing the issue:
qread version 3.1
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by Brian1Gaff** [comment] 2018-02-10 10:24
A while back I got this exact effect on some web pages for no apparent 
reason. I have to say that I do not get it in the espeak as in the   speech 
player in Espeak add on, so I have reluctantly decided its yet another bug 
in espeak NG.
 Brian
You might try this on your problem However if its happening in all sorts of 
synths then its a new issue.
 Brian

**Comment by Adriani90** [comment] 2020-05-07 19:34
@mreiser can you still reproduce this with NVDA 2020.1?

**Comment by Adriani90** [comment] 2020-05-29 22:12
No updates on this issue since years. This issue is a general issue and is further discussed in #2990. I am closing this one in favor of #2990.

**Closed by Adriani90** 2020-05-29 22:12 UTC
