### ISSUE TITLE
support for preserving formatting on copied pages in the hedge

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8333] opened 2018-05-25 16:54 UTC
### Steps to reproduce:
I have an old desire for nvda to allow copying the formatting of web pages.
This would be very valuable to me mainly in my work.
Today I read in the release notes of windows 10 incider build 17677 that the narrator will support the pages copied in the hedge preserve their formatting.
I'm not part of the windows incident, so I can not test this functionality.
However I would like to ask you if you can look at this functionality and support it at nvda in the future windows, at least for the hedge.

### Expected behavior:
Using nvda in future builds of windows in hedge, when copying a text into a webpage, especially tables allow you to copy the formatting of the web page so that when they are pasted into other places like word, preserve the original formatting of the page web.
My wish is especially to be able to copy tables directly from the browser, and paste them into word and have the preserved row and column formatting.

### Actual behavior:
When copying text from a web page and pasting it into a text editor, the formatting is completely lost.

### System configuration:
NVDA version:
all

NVDA Installed or portable:
instaled and portable

Other information:
> Example: Running in a VM

Windows version:
next 17677

Name and version of other software in use when reproducing the issue:
hedge

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by leonardder** [comment] 2018-05-28 06:54
Closing as duplicate of #5354. However, note that specifically for Edge, this is probably easier to implement than for virtual buffers (firefox, Chrome, IE).

**Closed by leonardder** 2018-05-28 06:54 UTC

**Comment by Brian1Gaff** [comment] 2018-05-28 08:13
I seem to recall while reading in the add ons for firefox that some kind of 
cut and paste and even direct page editing was available as one or more of 
them. Not really that interested, so did not look any deeper.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
