### ISSUE TITLE
Nvda can not open a button with submenu in chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6976] opened 2017-03-15 14:37 UTC
When browsing the page:
Http://www.freedomscientific.com/Downloads/JAWS
There is a button with submenu to choose the language of the software that you want to download.
The problem is that when trying to open this button with enter, space, I could not open the button.
To open the button you need to focus on the button, press nvda + space to switch to focus mode, and navigate through the options with the arrows.
My nvda setup is with the switch to autofocus mode disabled.
I'm with nvda next 13926, chrome 57, and windows 10 build 14393.
In firefox 52 this submenu button is shown as a combo box and you can interact with it normally.
Follow the log:

Speaking [u'Select your preferred language:']
IO - inputCore.InputManager.executeGesture (11:25:46):
Input: kb(laptop):downArrow
IO - tones.beep (11:25:46):
Beep at pitch 226.446492062, for 80 ms, left volume 50, right volume 50
IO - speech.speak (11:25:46):
Speaking [u'bot\xe3o de menu  recolhido  submenu']
IO - inputCore.InputManager.executeGesture (11:25:48):
Input: kb(laptop):enter
IO - inputCore.InputManager.executeGesture (11:25:51):
Input: kb(laptop):space
IO - inputCore.InputManager.executeGesture (11:25:54):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (11:25:54):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0543B830>
Python class mro: (<class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (484, 531, 171, 31)
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 7092) at address a706ed0>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'57.0.2987.98'
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
windowHandle: 722438L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 211850880
windowStyle: 1445986304
windowThreadID: 4028
windowText: u'Chrome Legacy Window'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0xb78f3ec at a61acb0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=722438, objectID=-4, childID=-1184
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 windowHandle: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 uniqueID: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 role: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 states: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 attributes: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by jcsteh** [comment] 2017-03-15 23:40
Confirmed. The issue is that the list actually gets focus as soon as you get to the button; activating the button does nothing because it's already activated.

I'll discuss this with Google. Aside from anything else, this new implementation seems very odd to me.

P2 because this makes a basic control somewhat difficult to use in Chrome.

**Comment by jcsteh** [comment] 2017-04-05 02:31
Minimal test case: `data:text/html,<select><option>a</option><option>b</option></select>`
This should report as a combo box, not a menu button.

This appears to be working in latest Chrome Canary: Version 59.0.3062.0 (Official Build) canary (64-bit)
It doesn't work in Chrome stable: Version 57.0.2987.133
So, this appears to be fixed for Chrome 59.

Closing.

**Closed by jcsteh** 2017-04-05 02:31 UTC
Labels: GoogleWork, needsExternalFix, p2
