### ISSUE TITLE
Change Mouse Hover.

### ISSUE THREAD

**Issue by LarrySilvermintz** [nvaccess/nvda#11748] opened 2020-10-10 22:10 UTC
Overview:  For partially-sighted users, speaking the entire line the mouse is hovering over is a critically important feature.  NVDA needs to fix how it speaks (echoes) hovered lines.

### Steps to reproduce:
1. With Firefox visit https://en.wikipedia.org/wiki/NonVisual_Desktop_Access
1. Ensure that _mouse tracking_ is turned on.
1. Set _Text unit resolution:_ to _paragraph_ (mouse tracking panel in NVDA settings) 
1. Hover mouse over first paragraph, which has the text: `"NonVisual Desktop Access (NVDA) is a free, open-source, portable screen reader[1] for Microsoft Windows.[2] The project was started by Michael Curran in 2006"`
1. **Note** that only the text `"NonVisual Desktop Access (NVDA) is a free,"` is read, NVDA stops at the start of the first link.
1. Try to position the mouse so that NVDA reads the whole paragraph (try positioning the mouse after the first link).
1. **Note:** when it does, the text from links is skipped. 

### Actual Behavior:
In focus mode, when hovering the mouse pointer over a line of text, NVDA only speaks a segment of the line, delimited by the edges of a link.  Specifically, if pointer moves down to the beginning of the next line of text, NVDA only reads from the beginning of that line up to the start of the first link, then if the pointer is moved over the link, only that link is spoken, and then one must continue moving the mouse to hear successive line segments.

### Expected behavior: 
Speak the entire line beneath the mouse pointer, just like ZoomText and Supernova. 

### Context: 
NVDA works as an overall excellent companion to a screen-magnifier such as that which ships with Windows.  But it must be able to do line echo in order to really be practical.  

### Environment:
Windows-10 Pro x64 Versio 10.0.19041 Build 19041
Windows Magnifier
Either Firefox 81 or MS Edge browser
NVDA 2020.2
Sample website:  Wikipedia.  
Wikipedia popups disabled through their account Preferences (found at the top right of Wikipedia pages).
Sample page to reproduce behavior:  https://en.wikipedia.org/wiki/NonVisual_Desktop_Access

**Comment by leonardder** [comment] 2020-10-12 05:48
Related to #9515, #9235 and #3590

**Comment by Brian1Gaff** [comment] 2020-10-12 08:23
Am I being a bit thick here, but surely you must be able to know you are 
over a link?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by LarrySilvermintz** [comment] 2020-10-12 16:18
Hello Brian and thank you for your quick response! 

In a word, YES, you are missing the point.

Being legally blind (impairment level of full-screen mode magnification
minimum of 8x, 20x or more, only a small part of a line is visible, and
instead of scanning with our eyes, the technique we use: slowly hover down
the lines, while listening (as requested here) to the full-line's spoken
content.  Since hovering across all the way is both slow and laborious, We
only scan occasional lines cross-wise to see desired details or to select a
desired link embedded within the text.

I also hover all around the page, to get it's overall structure, and
visually navigate the page.

 

Correction to original report:  The behavior is inconsistent, sometimes the
text segment delimited by links is read, sometimes only the text up to the
beginning of a link is read, and sometimes the full line is read except that
the text for links is absolutely and silently omitted!

 

CRITICAL problem with current behavior!  There is no way to hear and thus to
know if there is more text on a line without manually scanning across it.
Also, if you are hovering somewhere in the middle of a line, you currently
have know idea where in the middle is the segment you just heard; in stark
contrast the requested change to NVDA:  hovering up/down to a line and
hearing its full contents spoken you can quickly figure-out the relative
position of the visible portion within what you just heard.   Lacking trust
kills dead the whole point of having a trustworthy reader to free us from
having to hover all the way across a line to learn if there is something we
are missing.

 

 

If you please just try it, I think you will get-it.

 

Please let us know what it will take to get this implemented.

 

Thanks!

Larry Silvermintz

  _____

**Comment by feerrenrut** [comment] 2020-10-14 19:45
I can reproduce this issue, I can understand the problem. Note, I have updated the issue description to clarify.

**Comment by LarrySilvermintz** [comment] 2020-10-14 20:03
THANK YOU!  Hope you can fix it soon. 

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by Adriani90** [comment] 2024-07-25 12:32
@jcsteh will this also be fixed by #16912?

**Comment by jcsteh** [comment] 2024-07-25 12:35
No.

**Closed** 2024-07-25 12:38 UTC
Labels: bug, feature/mouse-tracking, audience/low-vision

**Comment by iubito** [comment] 2024-08-21 10:34
Still not fixed in 2024.3, the last update freshly installed.
We don't know what is the right issue, because everybody seem tou encounter this problem, create an issue, and there all duplicates of duplicates.
Note that the voice stop also when the line contains a bold, italic, type-scripted word.

The description of this issue is very clear with a nice example. Wikipedia, with a lot of links, is a nightmare to read by mouse tracking.
Note, that it happen when tracking mode is both line or paragraph.
Firefox, Chrome or chromium-based browsers (Brave), Windows 10.
