### ISSUE TITLE
NVDA does not identify graphic content inside radio buttons/checkboxes

### ISSUE THREAD

**Issue by RD-Brown** [nvaccess/nvda#8007] opened 2018-02-16 21:00 UTC
### Steps to reproduce:
1.	In Chrome, go to 
http://jsbin.com/liyidanuqa/3/edit?html,css,output
2.	From the top of the page, press G twice.  (Note that “Welcome to JS Bin,” is the only graphic found.)
3.	From the top of the page, press X until the “A. blue box” checkbox is reached.  (Note that none of the choices are identified as graphics.)

### Expected behavior:
NVDA should identify the content as a graphic by prefacing the alt text with "Graphic."

### Actual behavior:
Only the alt text is read.

### System configuration:
NVDA version: 2017.4

NVDA Installed or portable: Installed.

Other information:
Windows version: Windows 7

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA? No

**Comment by Adriani90** [comment] 2019-05-02 21:02
This is still reproducible in NVDA 2019.1.1 and Chrome 74. However, I do not see a negative effect on user experience since the alt text is read.
I am not sure if this is an NVDA issue. i saw several other websites which showed the same issue. it might also be a problem in Chrome regarding the way Chrome exposes the grafic atribute to screen readers. Is this also hapenning with other screen readers like Narator or Jaws?

**Comment by RD-Brown** [comment] 2019-05-03 14:29
Yes, the same behavior also exists when testing with JAWS.

**Comment by Adriani90** [comment] 2019-05-03 16:32
cc: @feerrenrut do you think this is a NVDA bug? If not, I guess at least for consistency reasons we could report this to Chrome. Or maybe there is already a bug report  for this but I cannot find one.

**Comment by Adriani90** [comment] 2019-12-20 17:25
Actually, I tend to close this issue since the user can press down arrow and hear that the label is embeded into a grafic. It is not important for this case to report "grafic" when pressing x. Note the same behavior can be observed in Firefox.
I will close this for now but feel free to comment on it if you have other arguments. We can reopen this issue afterwards. Thanks.

**Closed by Adriani90** 2019-12-20 17:25 UTC
