### ISSUE TITLE
Com error when  password field in outlooks credentials dialog gains focus

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#7299] opened 2017-06-18 12:54 UTC
### Steps to reproduce:
1. Outlook (for some reason) will periodically ask me to renter my credentials (username/password) for my gmail accounts. A way of forcing this dialog to come out is to clear any stored passwords, and initiate a check for new mail, which should cause it to prompt you for it.
2. Tab to the password field.

### Expected behavior:
NVDA should not error.

### Actual behavior:
NVDA makes an error sound, and this is the error log:

```
ERROR - eventHandler.executeEvent (20:47:17.760):
error executing event: gainFocus on <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x05514370> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\Dickson\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 365, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\Dickson\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 296, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\behaviors.pyc", line 167, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 907, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 819, in reportFocus
  File "speech.pyc", line 367, in speakObject
  File "speech.pyc", line 689, in speakTextInfo
  File "NVDAObjects\window\edit.pyc", line 677, in getTextWithFields
  File "NVDAObjects\window\edit.pyc", line 623, in _getTextAtRange
  File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
```

### System configuration:
NVDA version:
master-14116,135061dc

NVDA Installed or portable:
Installed

Windows version:
Windows 10 Version 1611 Build Version 10.0.14393

Name and version of other software in use when reproducing the issue:
Outlook 2016 (though I remember this happening in 2013 as well)

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
Has been happening for a long time, so yes

**Comment by jcsteh** [comment] 2017-06-18 22:37
Is this the same as #6871?

Aside from the error sounds, are there any other user visible symptoms? For example, #6871 notes that nothing is read when cursoring around that field.
Do you get repeated error sounds if you cursor around the field?

**Comment by Neurrone** [comment] 2017-06-21 14:59
Yup, cursoring around the field causes the errors as well. Sorry for the duplicate.

**Comment by jcsteh** [comment] 2017-06-25 23:12
Closing as duplicate of #6871.

**Closed by jcsteh** 2017-06-25 23:12 UTC
