### ISSUE TITLE
Increase the depth of the HTML structure that NVDA can read

### ISSUE THREAD

**Issue by jstreitsss** [nvaccess/nvda#15851] opened 2023-11-28 18:15 UTC
### Is your feature request related to a problem? Please describe.
Yes, if we have a deep html structure of content the reader stops reading before it reaches the end.  If the structure is not as deep is is able to read the entire content.  It appears there is a limit on how deep the screen reader is able to traverse.  We are using a hidden div as a description to an image and it works great except when the content is multiple levels deep.
### Describe the solution you'd like
I would like to be able to adjust/increase the max level it is able to traverse.
### Describe alternatives you've considered
We have looked at the PDFs that we are reading the tagged data from to see how they are created if we can eliminate the depth but the users are using a third party to create the pdf with tagged content and it is automatically setting the structure based on the structure of the document.

**Comment by Adriani90** [comment] 2023-11-28 22:01
We need a codepen or a minimal example that demonstrates this in order to investigate.
Also did you try to apply opacity:0 class to see if this works? In which browsers did you test? Does it reproduce in Cjhrome and also in Firefox browser?

**Comment by jstreitsss** [comment] 2023-11-28 22:02
Ok I will add that.  Yes tested on both Chrome and Firefox.  I will add a few samples

**Comment by bramd** [comment] 2023-11-30 17:58
@jstreitsss Also consider checking the accessibility tree in the browser to see if your structure is properly communicated to screen readers. You can do this in the Devtools/Inspector accessibility tab in Chrome and Firefox.

**Comment by Adriani90** [comment] 2023-12-01 14:03
I am closing this for now since we cannot investigate without a minimal example. Please provide the info and we can reopen then.

**Closed by Adriani90** 2023-12-01 14:03 UTC
Labels: blocked/needs-info

**Comment by jstreitsss** [comment] 2023-12-01 14:34
Sorry I have been traveling this week.  I will work on getting some samples uploaded later today.

Thanks

Jason Streit
Simply Secure Sign
Phone: (866) 546-1880
Direct: (210) 846-6158

***@***.******@***.***>
http://www.simplysecuresign.com
