### ISSUE TITLE
Its not clear which key is NVDA key on Thinkpad laptops

### ISSUE THREAD

**Issue by mertdeg2** [nvaccess/nvda#7995] opened 2018-02-13 00:22 UTC
### Steps to reproduce:
1. Buy Thinkpad laptop
2. Install NVDA on it
3. Try to press NVDA+ n to turn it on/off. 

### Expected behavior:
Its clear which key is the NVDA key for this configuration

### Actual behavior:
I have tried bunch of keys, but couldn't find which one is NVDA key. NVDA program has "Welcome to NVDA" message, but it doesn't say anywhere which key is the NVDA key

Windows version:
Windows 10

**Comment by josephsl** [comment] 2018-02-13 01:03
Hi, what ThinkPad model did you get? The NVDA key is the insert key. Thanks.

**Comment by ehollig** [comment] 2018-02-13 03:29
Hello @mertdeg2. When the welcome dialog comes up, check the box that allows capslock to be used as an NVDA modifier key. Then press capslock+1 to go into input help mode. This mode will allow you to explore the keys on your keyboard that you are unsure of their function. See if you have an insert key. If so, this key can be used as the NVDA key as well.

**Comment by mertdeg2** [comment] 2018-02-13 16:47
@josephsl I have Lenovo ThinkPad X1 Carbon

@ehollig It doesn't have caps lock key either.

(From top to bottom) Left column of the keyboard has: ESC, TAB, (HOME/END as one button), shift, ctrl
(From left to right) Bottom row of the keyboard has: CTRL, Windows key, Alt, space, alt, comma, ctrl, arrow left, arrow down, arrow right

**Comment by josephsl** [comment] 2018-02-13 16:51
Hi, I bet it doesn’t have an insert key, right? In this case, it might be best to use an external keyboard with this laptop. Thanks.

**Comment by mertdeg2** [comment] 2018-02-13 16:54
Nope it doesn't have the insert key, would it be too hard to make the NVDA key configurable?

**Comment by josephsl** [comment] 2018-02-13 16:56
Hi, depends. The thing is, it can conflict with app-specific commands (for example, if Control+Shift is assigned to NVDA key, if you press Control+Shift+N from File Explorer, it’ll open NVDA menu instead of creating a new folder). Thanks.

**Comment by mertdeg2** [comment] 2018-02-13 17:00
Ah, got you. Yeah it would be annoying if it conflicts with other commands. Maybe the NVDA application can let the user configure the NVDA key? Not sure what would be the technical challenges in achieving this

**Comment by josephsl** [comment] 2018-02-13 17:04
Hi, in a way, it does by abstracting either the regular insert, numpad insert, or caps lock as NVDA key. There could be challenges – you don’t want to find yourself “pressing” shift key twice if Control+Shift keys are mapped to NVDA key. CC @LeonardDer, @MichaelDCurran, @JCSTeh

**Comment by ehollig** [comment] 2018-02-18 04:03
This discussion sounds as if it is requesting a User-definable NVDA key, as discussed in #225. I am going to close this as a duplicate of that issue. Feel free to reopen if I am mistaken.

**Comment by feerrenrut** [comment] 2022-01-19 10:11
Given that #225 was made more specific, it does not cover this use case.

Looking at this issue, it seems like the details of this were never discovered. I'll re-open, however if we have lost contact with @mertdeg2 and we can't progress this further I suggest closing the issue.

The keys that can currently be used as the NVDA key:
- caps lock
- numpad insert
- insert

This issue suggests that the insert key could not be found, however the Caps Lock key was not mentioned, can this be used instead?
Telling us the name of the laptop model will help us to identify the location of the insert key for you.

**Comment by ehollig** [comment] 2022-01-21 03:48
@feerrenrut did you see https://github.com/nvaccess/nvda/issues/7995#issuecomment-365327461
> @josephsl I have Lenovo ThinkPad X1 Carbon
> 
> @ehollig It doesn't have caps lock key either. Maybe this article is related: https://www.networkworld.com/article/2173257/computers/lenovo-drops-caps-lock-key-in-redesign-of-slim-thinkpad-x1-carbon.html
> 
> (From top to bottom) Left column of the keyboard has: ESC, TAB, (HOME/END as one button), shift, ctrl (From left to right) Bottom row of the keyboard has: CTRL, Windows key, Alt, space, alt, comma, ctrl, arrow left, arrow down, arrow right

Based on this description, and from the information provided in the linked article, this type of computer does not have a capslock key.

**Comment by josephsl** [comment] 2022-01-21 04:03
Hi,

The article in question was from 2014, and as someone pointed out in this post:
https://news.ycombinator.com/item?id=15066671

I have ThinkPad X1 Yoga generation 6 which is equivalent to ThinkPad X1 Carbon generation 9 apart from Yoga being a convertible, and I can tell everyone that ThinkPads did return to the standard layout - Caps Lock key is present and so is the Insert key. If X1 Carbon generation 10 dropped Caps Lock key, the tech press would have talked about it last week, but since I didn't hear anything from Lenovo nor tech presses, we can assume that the layout remains the same. Therefore, I'm in favor of actually closing this issue as this is device-specific, although the idea and feasibility of a customizable NVDA key should be researched by someone (I guess someone outside of NV Access).

Thanks.

**Comment by feerrenrut** [comment] 2022-01-21 08:28
Thanks @ehollig, since this wasn't from the original reporter I disregarded. There likely are machines out there without caps-lock / insert / numpad insert. My first concern would be helping them confirm this is the case, and any way they can work around it (EG use an external keyboard). Then we'd need to be able to confirm with them what an appropriate replacement might be.

Given the age of this issue, I think we can close it. I'm happy to re-open if there is more to discuss.

**Closed by feerrenrut** 2022-01-21 08:28 UTC
Labels: close/duplicate
