### ISSUE TITLE
Start menu sometimes doesn't speak

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4967] opened 2015-03-09 04:10 UTC
**Reported by tspivey on 2015-03-09 04:10**
Sometimes, when activating the start menu, there's no feedback.
STR:
1. Press the windows key.
Expected:
I hear "Start apps list of programs in this view"
Actual:
I hear nothing

Unfortunately, this happens rarely for me, so I'm not sure how to track it down. Restarting NVDA fixed it last time.

**Comment by ehollig** [comment] 2017-08-31 02:00
I am not able to reproduce this using the steps provided in https://github.com/nvaccess/nvda/issues/4967#issuecomment-155334939 and Windows 10. It would be interesting to know if this can still be reproduced in Windows 7 or 8.1, in hopes this has been fixed. If not, should an appropriate issue be created with Microsoft?

**Comment by bhavyashah** [comment] 2017-08-31 03:34
I cannot reproduce issue reported in https://github.com/nvaccess/nvda/issues/4967#issuecomment-155334939 using NVDA 2017.3 on Windows 8.1, although this might well be because I have a Start menu modified by Classic Shell.

**Comment by derekriemer** [comment] 2017-08-31 06:08
@tspivey 
I actually believe this was either fixed by ms in win10, or is not relevant no more.

**Comment by ehollig** [comment] 2017-10-13 19:45
I just tried this on my Windows 8.1 virtual machine and NVDA 2017.3 and did not get the behavior described above. Either this has been fixed by Microsoft, or this will not be fixed by Microsoft, as a lot of development is with Windows 10. Closing as this sounds not to be an NVDA issue, as Narrator experienced this issue as stated in https://github.com/nvaccess/nvda/issues/4967#issuecomment-155334942

**Closed by ehollig** 2017-10-13 19:45 UTC
Labels: bug, needsExternalFix
