### ISSUE TITLE
NVDA expanding areas on chrome without pressing enter

### ISSUE THREAD

**Issue by frastlin** [nvaccess/nvda#14729] opened 2023-03-18 23:48 UTC
### Steps to reproduce:

Using Chrome Version 111.0.5563.65 (Official Build) (64-bit)

1. Visit [Google.com](https://google.com)
2. Search for "Pizza"
3. Press "h" until you hear "Domino’s® Pizza - Online Ordering" (or some other add or result, it doesn't matter).
4. Press the down arrow until you hear: "Why this ad?" (or if on a normal result, "About this result")
5. Observe the dialog opening without you pressing enter on it.

Note this behavior is recent, in the last couple weeks, and I don't know if it is a Chrome bug or something else.

### Actual behavior:

The dialog opens without you pressing enter (the speech message is different depending on what dialog you open, but it will inevitably open the dialog for the button you are over without you pressing enter).

### Expected behavior:

NVDA should read the title of the button and nothing else. e.g. "button About this result"

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

Version: 2022.4 (2022.4.0.27401)

#### Windows version:

Windows 11 Pro Version 10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:

Chrome Version 111.0.5563.65 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by Brian1Gaff** [comment] 2023-03-19 13:36
I'm pretty certain this has come up before. I personally feel its a bug in 
the Chrome Browser code. Does it work ok still in Firefox?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Brandon" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Saturday, March 18, 2023 11:53 PM
Subject: [nvaccess/nvda] NVDA expanding areas on chrome without pressing 
enter (Issue #14729)


### Steps to reproduce:

Using Chrome Version 111.0.5563.65 (Official Build) (64-bit)

1. Visit [Google.com](https://google.com)
2. Search for "Pizza"
3. Press "h" until you hear "Domino’s® Pizza - Online Ordering" (or some 
other add or result, it doesn't matter).
4. Press the down arrow until you hear: "Why this ad?" (or if on a normal 
result, "About this result")
5. Observe the dialog opening without you pressing enter on it.

Note this behavior is recent, in the last couple weeks, and I don't know if 
it is a Chrome bug or something else.

### Actual behavior:

The dialog opens without you pressing enter (the speech message is different 
depending on what dialog you open, but it will inevitably open the dialog 
for the button you are over without you pressing enter).

### Expected behavior:


NVDA should read the title of the button and nothing else. e.g. "button 
About this result"

### System configuration
#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

Version: 2022.4 (2022.4.0.27401)

#### Windows version:

Windows 11 Pro Version 10.0.22621 Build 22621

#### Name and version of other software in use when reproducing the issue:

Chrome Version 111.0.5563.65 (Official Build) (64-bit)

### Other questions
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their 
behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing 
Tool in NVDA's tools menu?


-- 
Reply to this email directly or view it on GitHub:
https://github.com/nvaccess/nvda/issues/14729

**Comment by frastlin** [comment] 2023-03-19 15:39
Hello,
No, only on Chrome and Edge.
Thank you,

Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by Adriani90** [comment] 2023-03-19 19:44
@frastlin did you enable "automatically set system focus to focusable elements" in NVDA's borwse mode settings or with nvda+8? If yes, Please disable this setting and try to reproduce your issue again. Is this still occuring?

**Comment by frastlin** [comment] 2023-03-19 19:56
Hello,
NVDA+8 seemed to work!
Thank you,

Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by Adriani90** [comment] 2023-03-19 20:05
Closing as works for me.

**Closed by Adriani90** 2023-03-19 20:05 UTC
Labels: close/worksforme

**Comment by frastlin** [comment] 2023-03-19 20:33
Hello,
When this option is off, hitting enter on Google Calendar events will focus
on something that is not the calendar event, and pop you into focus mode.
When you press NVDA+space to go back into brows mode, you are on the date
in the calendar table.
When focus system focusable elements is on, you are jumped into a dialog
where you can edit or delete the event. I am not sure how to access this
dialog with the focus system focusable elements off.
Thanks,

Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by Adriani90** [comment] 2023-03-19 20:50
The first behavior you described is the expected behavior. When you press enter on google calendar with focus focusable elements off, nvda‘s focus jumps to the list or grid with the dates. Then you have to choose a date and press enter on it to open the date editing dialog.Note it is not recommended to enable automatically move system focus to focusable elements since the synchronization of system focus and NVDA‘s virtual focus does not work properly. That‘s why this setting is turned off by default.You can manually move the system focus to NVDA‘s virtual cursor by switching  from browse mode to focus mode with nvda+space. Then you can switch  back to browse mode and so on.Von meinem iPhone gesendetAm 19.03.2023 um 21:33 schrieb Brandon ***@***.***>:﻿
Hello,
When this option is off, hitting enter on Google Calendar events will focus
on something that is not the calendar event, and pop you into focus mode.
When you press NVDA+space to go back into brows mode, you are on the date
in the calendar table.
When focus system focusable elements is on, you are jumped into a dialog
where you can edit or delete the event. I am not sure how to access this
dialog with the focus system focusable elements off.
Thanks,

Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by frastlin** [comment] 2023-03-19 22:28
Hello,
1. Open google Calendar
2. Enter focus mode
3. Press "6" and navigate through the dates until you find one with events
you are interested in.
4. Hit enter and a dialog with events will show.
5. Down arrow and hit enter on one of the buttons to view the event.

At this point, when automatically set focus to focusable elements is off,
NVDA enters focus mode and arrow keys do nothing.
If  automatically set focus to focusable elements is on, you will stay in
brows mode, and enter an event dialog with the options to edit,, delete,
and view the event information.
Thanks,

Brandon Keith Biggs <http://brandonkeithbiggs.com/>

**Comment by brunoprietog** [comment] 2023-03-30 20:39
It also happens to me a few weeks ago. Disabling that option with NVDA+8 does not help me at all, as for me it is very useful that feature when using Object Location Tones. Also, even if you turn it off, in Google Calendar, navigating to events opens the create button without pressing it. This also happens in Google search, in Gmail browsing emails opens automatically, in Google oauth 2 screen links are pressed automatically, in Google Meet browsing to upcoming meetings buttons also presses automatically, in Jira dialogs also open without pressing the buttons, in many sites. In my opinion this should not be closed, it is being too obnoxious and every time I enter these sites I have to disable the option, and when I leave there re-enable it. Sometimes I have discovered sites where it happens and they are pressed without my consent.
