### ISSUE TITLE
Cannot access context menu when browsing downloads in Edge with control+j

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14922] opened 2023-05-12 00:48 UTC
### Steps to reproduce:

1. Open Edge to a blank page, or any page.
2. Press control+j to open downloads.
3. Use the arrows to move to any download.
4. Press the applications key to open the context menu
5. Press the down arrow to move through the options.

### Actual behavior:

The focus moves through the items in the context menu, however NVDA does not read anything.  There is nothing written to the log.

### Expected behavior:

NVDA should read the context menu.

#### NVDA version:

2023.1 installed

#### Windows version:

Windows 11 (64-bit) Version: 22H2, Build: 22621.1702 

#### Name and version of other software in use when reproducing the issue:

Microsoft Edge, Version: 113.0.1774.35 

#### Other information about your system:

I did find a workaround for anyone hitting this, is to open the downloads page rather than the "menu":
1) Press alt+d to open the address bar.
2) Type the following
edge://downloads
3) Press enter

The user who reported this also noted that the context meu (after pressing control+j ) reads fine with both Narrator and Jaws.

**Comment by Qchristensen** [comment] 2023-05-12 05:55
Update from Microsoft: "Everything seems normal to me. There is a focus being fired to each new menu item. I see that NVDA isn’t speaking but not sure why."

**Comment by Adriani90** [comment] 2023-05-12 06:35
@Qchristensen would it be ok to add your points in #14916? This is actually a duplicate of that one.

**Comment by Adriani90** [comment] 2023-05-12 06:38
I am closing this one as duplicate and we can continue discussions there.

**Closed by Adriani90** 2023-05-12 06:38 UTC
Labels: close/duplicate

**Comment by Qchristensen** [comment] 2023-05-12 07:23
Thanks @Adriani90!
