### ISSUE TITLE
NVDA inserts a space after code elements in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4835] opened 2015-01-20 15:45 UTC
**Reported by parham on 2015-01-20 15:45**
I'm not sure if this is a regression (I have unconsciously noticed it, but I don't know if I always have or if it's something new). When you have an HTML code like this:

```
<p>The default flavor is <code>dev</code>.</p>
```

NVDA inserts a space after 'dev' even though there is no space in there in the HTML source of the page. This snippet is from this github page: https://github.com/docker/docker-registry/tree/0.9.1

**Comment by ehollig** [comment] 2017-08-15 01:24
I am not able to reproduce this using Firefox 54 and going to the stated Github page and viewing the source. Closing as invalid

**Closed by ehollig** 2017-08-15 01:24 UTC
Labels: Browse mode, bug
