### ISSUE TITLE
errors after restarting nvda

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8184] opened 2018-04-16 15:02 UTC
### Steps to reproduce:
Open microsoft word.
While inside the word, restart nvda with the addons disabled.
When nvda restart type some characters in word.

### Expected behavior:
The characters you enter must be read by nvda, assuming the option to speak typed characters is enabled in the keyboard options.

### Actual behavior:
The characters you type are not advertised by nvda, even though the option to speak typed characters is enabled.
Removing the focus from the word window and resuming focus on word causes everything to work properly again.
In the log appear strange information.
I do not know if soon to restart nvda and without removing focus from word if the problems are limited to not reading the typed characters or if there are other errors.

### System configuration:
NVDA version:
next 15029

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 7 64bits

Name and version of other software in use when reproducing the issue:
word e outlook 2015
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no:
log:
INFO - core.main (11:50:37.895):
NVDA initialized
DEBUG - core.main (11:50:37.895):
entering wx application main loop
IO - speech.speak (11:50:38.043):
Speaking [u'Documento1 - Word']
IO - speech.speak (11:50:38.069):
Speaking [u'Documento1']
IO - speech.speak (11:50:38.076):
Speaking [u'Documento1  documento']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (11:50:38.079):
Potential unimplemented child class: <NVDAObjects.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x05BDC8F0>
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.079):
_getTextWithFieldsForUIARange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.081):
rootElement: documento
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.082):
full text: 
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.082):
Fetching parents starting from enclosingElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.085):
parentElement: editar
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.086):
parentElement: página
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.091):
Hit root
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.092):
Done fetching parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.092):
Generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.092):
parentElement: editar
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.095):
parentElement: página
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.096):
Done generating controlFields for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.096):
Yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.096):
Done yielding control starts for parents
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.096):
Yielding balanced fields for textRange
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.098):
no children
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.098):
Yielding text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (11:50:38.098):
_getTextWithFields_text start
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (11:50:38.098):
Walking by unit 1
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (11:50:38.098):
With further units of: [2, 0]
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFields_text (11:50:38.101):
Done _getTextWithFields_text
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.101):
Yielding controlEnd for parentElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.101):
Yielding controlEnd for parentElement
DEBUG - NVDAObjects.UIA.UIATextInfo._getTextWithFieldsForUIARange (11:50:38.101):
_getTextWithFieldsForUIARange end
IO - speech.speak (11:50:38.104):
Speaking [u'edi\xe7\xe3o  somente leitura']
IO - inputCore.InputManager.executeGesture (11:50:44.378):
Input: kb(laptop):shift+m
IO - inputCore.InputManager.executeGesture (11:50:45.562):
Input: kb(laptop):e
IO - inputCore.InputManager.executeGesture (11:50:46.026):
Input: kb(laptop):u
IO - inputCore.InputManager.executeGesture (11:50:48.507):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - displayModel.DisplayModelTextInfo._get__storyFieldsAndRects (11:50:48.532):
AppModule does not have a binding handle
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.535):
Couldn't add property ID 30112 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.535):
Couldn't add property ID 30118 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.535):
Couldn't add property ID 30127 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.535):
Couldn't add property ID 30128 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.535):
Couldn't add property ID 30132 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.536):
Couldn't add property ID 30136 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.536):
Couldn't add property ID 30137 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.536):
Couldn't add property ID 30141 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.536):
Couldn't add property ID 30149 to cache request, most likely unsupported on this version of Windows
DEBUG - NVDAObjects.UIA.UIA._prefetchUIACacheForPropertyIDs (11:50:48.536):
Couldn't add property ID 30151 to cache request, most likely unsupported on this version of Windows
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (11:50:48.608):
Developer info for navigator object:
name: u'Documento1'
role: ROLE_DOCUMENT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x05BDC8F0>
Python class mro: (<class 'NVDAObjects.Dynamic_WordDocumentEditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject'>, <class 'NVDAObjects.UIA.wordDocument.WordDocument'>, <class 'UIABrowseMode.UIADocumentWithTableNavigation'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'NVDAObjects.UIA.wordDocument.WordDocumentNode'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.winword.WordDocument'>, <class 'NVDAObjects.window.Window'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: (0, 143, 1583, 695)
value: None
appModule: <'appModuleHandler' (appName u'winword', process ID 6212) at address 5b24b30>
appModule.productName: u'Microsoft Office 2013'
appModule.productVersion: u'15.0.5015.1000'
TextInfo: <class 'NVDAObjects.UIA.wordDocument.WordDocumentTextInfo'>
windowHandle: 985324
windowClassName: u'_WwG'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 1116
windowText: u'Documento do Microsoft Word'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x4458088 at 5c03080>
UIA automationID: 
UIA frameworkID: Win32
UIA runtimeID: (42, 985324)
UIA providerDescription: [pid:564,hwnd:0xF08EC Main:Nested [pid:6212,hwnd:0xF08EC Main(parent link):Unidentified Provider (unmanaged:wwlib.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: _WwG
UIA patterns available: LegacyIAccessiblePattern, ScrollPattern, TextPattern

**Comment by Adriani90** [comment] 2019-02-04 14:01
@fernando-jose-silva it Looks like you have enabled UIA for Microsoft. Can you reproduce this issue in last NVDA Alpha Version with UIA disabled?

**Comment by Adriani90** [comment] 2019-02-04 19:03
Testing on Windows 10 with NVDA Alpha 16691,10950C87 and Word 365, I cannot reproduce this issue with UIA enabled or disabled.

**Comment by fernando-jose-silva** [comment] 2019-02-04 21:21
I can no longer reproduce the problem, thank you very much.

**Comment by Adriani90** [comment] 2019-02-04 21:42
Closing as works for me.

**Closed by Adriani90** 2019-02-04 21:42 UTC
Labels: worksforme
