### ISSUE TITLE
Web site search box use upper and lower the cursor can not find, but the TAB you will find it

### ISSUE THREAD

**Issue by c469591** [nvaccess/nvda#13624] opened 2022-04-22 00:00 UTC
Steps to reproduce:
Press CTRL + home after open the web page, and then down

### Actual behaviors:

Can't see the edit box, can only use TAB to find to the edit box

### Expected behaviors:

Look to the edit box

### The System configuration

Windows 10 21 h2
intel10700

#### As the installed/portable/running from the source:

 version as install

#### Given the version:

Version: 2021.3.5

#### Windows version:

21 the h2

#### The Name and version of other software in the use of the when reproducing the issue:

Brave the latest version
Firefox the latest version

#### Other information about your system:

My website using Hugo meme theme erection,
https://lamb.tw

### Other questions

I'm from Taiwan, so use traditional Chinese, I use the browser is brave,
My site:
https://lamb.tw
This is my blog, use the erection of the MEME theme of Hugo,
To describe problems:
After open my website, press CTRL + home to top of the page, and then press TAB, can enter an edit box, this is my web site search function, you can enter keywords for the article,
But if I press CTRL + home on a web page, press the direction key, will pass in the edit box, just like there was no edit box,
That is to say, I want to move the focus to the edit box, I can only press the TAB, even I press e will prompt no edit box on the web,
But oddly, I use Windows 10 built-in screen readers to operate the web, according to the upper and lower the cursor moves, you can find the edit box,
More detailed said, as I use and press CTRL + home, will like this - > in downwards see
My blog name
Classification of the article
And when I use Windows 10 screen reader, will see to it like this
My blog name
The picture
Used to enter search text edit box
Classification of the article
Therefore, I suggest that testing friend can use as first, press CTRL + home to jump to the top, press the cursor, whether trying to find an edit box,
Then press CTRL + win + enter to open the screen reader, doing the same operation, test whether the edit box can be found,
If you want to more clearly understand the layout of the website content, can install additional components in translation, but I think does not affect the testing,
I think nvda on the web page will need to improve, because Windows 10 screen readers can find the edit box and pictures, and given can only use TAB to find that
The same problem may also be used in other Hugo meme theme of the website, so I think this problem need to be pay attention to,
Thank you very much!

#### Does the issue still occur after restarting your computer?

yes

#### Have you tried any other versions of NVDA? If so, do the report their behaviors.

There is no

#### If given the add - ons are disabled, is your problem, the occurring?

yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA 's tools menu?

yes

**Comment by XLTechie** [comment] 2022-04-22 01:41
Please fill out the issue template, instead of posting below it and ignoring 
its questions.

I think I understand what you are asking, but more information would be helpful.

Also, the link to your website doesn't seem clickable.

**Comment by c469591** [comment] 2022-04-22 03:16
My site is
https://lamb.tw

**Comment by cary-rowen** [comment] 2022-04-22 03:39
Hi, please fill out the issue template, otherwise the issue may be closed

**Comment by Brian1Gaff** [comment] 2022-04-22 07:44
I think it may be a little difficult for them as the site is in Chinese, so 
all I see is Chinese letter etc. However a cursor down once then an enter 
puts me into focus mode for a field, with  words already present in it, one 
assumes to make it obvious what should be entered there.

 There do seem to be a lot of text mode items on the page. I suppose this 
site is not going to offer a native English version which we could  look at.
 If not maybe you can get a translator to explain more fully the site layout 
in the email to the list and fill out the template as to what you expected, 
and what actually happens, please include the browser used as well.
 My guess is that there is a simple authoring issue to fix on the site.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by c469591** [comment] 2022-04-22 10:52
I'm sorry, I didn't express is clear enough,
I'm from Taiwan, so use traditional Chinese, I use the browser is brave,
My site:
https://lamb.tw
This is my blog, use the erection of the MEME theme of Hugo,
To describe problems:
After open my website, press CTRL + home to top of the page, and then press TAB, can enter an edit box, this is my web site search function, you can enter keywords for the article,
But if I press CTRL + home on a web page, press the direction key, will pass in the edit box, just like there was no edit box,
That is to say, I want to move the focus to the edit box, I can only press the TAB, even I press e will prompt no edit box on the web,
But oddly, I use Windows 10 built-in screen readers to operate the web, according to the upper and lower the cursor moves, you can find the edit box,
More detailed said, as I use and press CTRL + home, will like this - > in downwards see
My blog name
Classification of the article
And when I use Windows 10 screen reader, will see to it like this
My blog name
The picture
Used to enter search text edit box
Classification of the article
Therefore, I suggest that testing friend can use as first, press CTRL + home to jump to the top, press the cursor, whether trying to find an edit box,
Then press CTRL + win + enter to open the screen reader, doing the same operation, test whether the edit box can be found,
If you want to more clearly understand the layout of the website content, can install additional components in translation, but I think does not affect the testing,
I think nvda on the web page will need to improve, because Windows 10 screen readers can find the edit box and pictures, and given can only use TAB to find that
The same problem may also be used in other Hugo meme theme of the website, so I think this problem need to be pay attention to,
Thank you very much!

**Comment by c469591** [comment] 2022-04-22 11:09
Steps to reproduce:
Press CTRL + home after open the web page, and then down
Actual behaviors:
Can't see the edit box, can only use TAB to find to the edit box
Expected behaviors:
Look to the edit box
The System configuration
Windows 10 21 h2
intel10700
As the installed/portable/running from the source:
 version as install
Given the version:
Version: 2021.3.5
Windows version:
21 the h2
The Name and version of other software in the use of the when reproducing the issue:
Brave the latest version
Firefox the latest version
Other information about your system:
My website using Hugo meme theme erection,
https://lamb.tw
Other questions
Does the issue still occur after restarting your computer?
yes
Have you tried any other versions of NVDA? If so, do the report their behaviors.
There is no
If given the add - ons are disabled, is your problem, the occurring?
yes
Does the issue still occur after you run the COM Registration Fixing Tool in NVDA 's tools menu?
yes

**Comment by cary-rowen** [comment] 2022-04-22 11:45
You can edit the content of your first speech, which is markdown syntax, you just need to add the corresponding content under each heading. As you said last time.

**Comment by seanbudd** [comment] 2022-04-27 06:08
It's quite difficult to understand the issue raised here. Without the template clearly filled out, this issue cannot be progressed. 
If you need assistance following web accessibility standards, please consider another forum.
If NVDA is not compliant with the standards, or you suspect it is not behaving properly, please make that clear in the issue.

**Comment by c469591** [comment] 2022-04-28 23:55
hi各位，不好意思造成大家的不便，
我已經修改了我的第一條訊息，
謝謝!

**Comment by seanbudd** [comment] 2022-04-29 00:00
Thanks @c469591

**Comment by cary-rowen** [comment] 2023-03-20 23:29
To be honest, I have never been able to reproduce this using FireFox. I just tested this again with FireFox 111.0, still can't reproduce.

**Comment by Adriani90** [comment] 2023-03-21 13:58
Thanks for the update. I am closing as works for me.

**Closed by Adriani90** 2023-03-21 13:58 UTC
Labels: close/worksforme
