### ISSUE TITLE
Add automatic language detection based on the alphabet used, just like in the vocalizer expressive addon

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#14193] opened 2022-09-28 18:11 UTC
### Is your feature request related to a problem? Please describe.
The problem is I'm using my computer in Russian with e-speak, and when I come across a text that is in Turkish, Russian e-speak reads the Turkish text as it is English.
### Describe the solution you'd like
Add automatic language swtiching based on unicode characters like in  the vocalizer expressive addon for NVDA, so we can set which language and voice we want for alphabets like latin, Cyrillic, Arabic etc.

**Comment by seanbudd** [comment] 2022-09-29 02:46
This appears to be a duplicate of #2990

**Comment by seanbudd** [comment] 2022-10-04 00:14
Closing as duplicate

**Closed by seanbudd** 2022-10-04 00:14 UTC
