### ISSUE TITLE
The options with disabled attribute are skipped by NVDA screen reader

### ISSUE THREAD

**Issue by shirsha** [nvaccess/nvda#14374] opened 2022-11-14 22:48 UTC
### Steps to reproduce:

- Start NVDA on Chrome

- Go to the W3 school and select [disabled attribute example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_option_disabled)

- Expand the Choose a car list

- Navigate through the list

### Actual behavior:

- Observe that screen reader narrates there are 4 items in the list, but skips over the disabled item when navigating using up/down arrow key

### Expected behavior:

_ Screen reader user is able to access all the options in the list.  When they navigate to the disabled option, it should narrate the option followed "disabled"

**Comment by seanbudd** [comment] 2022-11-14 23:59
Closing as duplicate of #14190

**Closed by seanbudd** 2022-11-14 23:59 UTC
