### ISSUE TITLE
nvda is not reading the list of messages in an email app box 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12229] opened 2021-03-25 20:49 UTC
### Steps to reproduce:
open the email app on windows 10
navigate with the arrows above and below the message list 
### Actual behavior:
just a speechless error sound 
### Expected behavior:
nvda read the email in focus 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-22132,d90b24e7

#### Windows version:
10 19043.899
#### Name and version of other software in use when reproducing the issue:
HxOutlook.exe, microsoft.windowscommunicationsapps 16005.13426.20688.0

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
ys
#### If add-ons are disabled, is your problem still occurring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes
log
[email3.txt](https://github.com/nvaccess/nvda/files/6207783/email3.txt)

**Comment by Nikita34196** [comment] 2021-03-26 10:15
Hello. I have this problem, too. I use the latest alfa version. when you move the arrows in the list of emails, nvda loses the sound of the error and that's it. Mail app for windows 10
[nvda.log](https://github.com/nvaccess/nvda/files/6210973/nvda.log)

**Comment by lukaszgo1** [comment] 2021-04-09 09:03
@fernando-jose-silva Is this till reproducible for you with latest Alpha?

**Comment by fernando-jose-silva** [comment] 2021-04-09 10:27
no thanks, problem solved when using the last alpha.
If I am not mistaken corrected in alpha 22260.

**Comment by lukaszgo1** [comment] 2021-04-09 10:33
@fernando-jose-silva Thanks for the update! Since this is fixed could you please close this issue??

**Closed** 2021-04-09 10:41 UTC
