### ISSUE TITLE
Feature Request: move caret to current word being read

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10819] opened 2020-02-26 17:12 UTC
Win10 1909 / Version: 2019.2.1 / portable

Hello, this request is that when reading text with a caret, NVDA moves the cursor to the  ccurrent word being read.

Text files in Notepad are an example. On Say All the cursor (generally) moves to the beginning of each line., but then stays there as the line is read out. I would want the cursor to follow along with the current word being read.

I use Say ALL to check spelling, and it would then be easy to ctrl+left to go back to the misspelt word I had just heard.

As it stands I have to work out where the caret is in relation to the target word as it will be at a different point.

Text files in Wordpad are another example where the caret moves to each line, but doesn't then follow within the line.

Thank you, hope this is possible! Or if it was already meant to sync caret to read word then let me report this as a bug..

EDIT 
"#### Does the issue still occur after restarting your PC?"

Yes, I have never seen the caret follow the current word being read in Notepad. I don't really use any other text editors. Although I notice that it also doesn't follow the current word in this page's reply edit box. Just the current line.

**Comment by josephsl** [comment] 2020-02-26 17:17
Hi, if I recall correctly, there should be a pull request that might resolve this problem. Also, what Adriani meant by template is filling out the actual feature request template found at: https://github.com/nvaccess/nvda/issues/new?template=feature_request.md. Also, as a general note, I think it would be great if we don’t forcefully close issues just because the original poster didn’t follow the template correctly. Thanks.

**Comment by TechHorseG** [comment] 2020-02-26 18:42
I followed the general template as I was unclear as to whether this was a bug or not.

I thought it was a feature request but then the response to the original thread made it sound as if it was already meant to work that way, and hence this is a bug?

I did answer all the questions the general template asked, but if I have missed something that the bug or feature request template would have asked, sorry about that!

I've just had a look at both and the only question I did not address was in the bug template, so I will do that now.

"#### Does the issue still occur after restarting your PC?"

Yes, I have never seen the caret follow the current word in Notepad. I don't really use any other text editors. Although I notice that it also doesn't follow the current word in this reply edit box. Just the current line.

**Comment by DrSooom** [comment] 2020-02-26 19:04
See also: Issue #3287 and #9179 and PR #9937.

**Comment by Adriani90** [comment] 2020-02-26 20:15
Thanks Daniel for the referenced pr and issues. Since this request is covered already in those issues, I will close this as duplicate.
@josephsl I normally do not close issues as long as the description is clear enough to reproduce the problem.
And in case of the template, it is in favor of the users to fill it in order to work out a viable solution as suitable as possible without raising indefinite discussion on small things. Quality is mostly more important than quantity. Thus, just two lines of description is not enough to understand problems completely. I trust you agree on this.

**Closed by Adriani90** 2020-02-26 20:15 UTC
Labels: duplicate
