### ISSUE TITLE
Very strange problem using Firefox and the Qwant search engine

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#6898] opened 2017-02-18 14:27 UTC
Hi,

Here is what happens:
I use Firefox 51.0.1 64 bits, latest NVDA's next, Windows 10 64 bits.
When I try to use the Qwant search engine, NVDA command keys get completely messed up.
To reproduice:
go to Qwant
http://www.qwant.com
enter a search query in the search edit field
press enter.
In the search result page, try to navigate with the "h" key to find next heading.
Then, try to get back to the previous heading with shift+h.
Now, you will see that all NVDA commands are messed, even if you switch to another application, all you have to do is restart NVDA.
This problem must be recent since this search engine is my default one and I did not notice the problem until now.
But sorry, I could not exactly say when it appeared.

**Comment by PratikP1** [comment] 2017-02-18 15:05
I tested with NVDA next-13893,02d87678 with Firefox 51 on Windows 10 64 bit. I can’t replicate the problem you described in the same manner as you have. But, the attached log does provide some potential explanations.

·         One potential explanation is that NVDA puts the user back into the search field after the results are shown with focus mode switched on, resulting in the user being confused and trying to use browse mode keyboard commands. If this is the case, then nothing much could be done about this since the site developer chose to autofocus.

·         There appear to be some debug warnings and script execution errors in the log on this site as well. They could contribute to the problem.

·         The log also points out a problem that I’ve seen on other sites: NVDA fails to switch back to browse mode with NVDA+space bar  keyboard command. If this is a contributing factor, I’m happy to file a separate bug.




IO - speech.speak (09:37:49):
Speaking [LangChangeCommand ('en'), u'qwant.com']
IO - inputCore.InputManager.executeGesture (09:37:50):
Input: kb(laptop):enter
IO - speech.speak (09:37:50):
Speaking [LangChangeCommand ('en'), u'(1) Techmeme  document  busy']
IO - speech.speak (09:37:50):
Speaking [LangChangeCommand ('en'), u'link', u'Bill Gates supports taxing the use of robots, to slow the spread of automation and to finance other ']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (09:37:52):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
IO - speech.speak (09:37:52):
Speaking [LangChangeCommand ('en'), u'Qwant - The search engine that respects your privacy  document']
IO - speech.speak (09:37:52):
Speaking [LangChangeCommand ('en'), u'Qwant - The search engine that respects your privacy  document']
IO - speech.speak (09:37:52):
Speaking [LangChangeCommand ('en'), u'edit']
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getCaretOffset (09:37:52):
IAccessibleText::caretOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 151, in _getCaretOffset
COMError: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
ERROR - queueHandler.flushQueue (09:37:52):
Error in func _loadBufferDone from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 396, in _loadBufferDone
  File "browseMode.pyc", line 1063, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1336, in event_gainFocus
  File "browseMode.pyc", line 1063, in <lambda>
  File "NVDAObjects\behaviors.pyc", line 167, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 893, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 805, in reportFocus
  File "speech.pyc", line 370, in speakObject
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 340, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 289, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
IO - speech.speak (09:37:53):
Speaking [LangChangeCommand ('en'), u'What are you looking for?  edit']
IO - speech.speak (09:37:53):
Speaking [LangChangeCommand ('en'), u'blank']
IO - inputCore.InputManager.executeGesture (09:37:57):
Input: kb(laptop):p
IO - inputCore.InputManager.executeGesture (09:37:57):
Input: kb(laptop):o
IO - inputCore.InputManager.executeGesture (09:37:57):
Input: kb(laptop):i
IO - inputCore.InputManager.executeGesture (09:37:57):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):t
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):space
IO - speech.speakTypedCharacters (09:37:58):
typed word: point
IO - speech.speak (09:37:58):
Speaking [LangChangeCommand ('en'), u'point']
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):a
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):d
IO - inputCore.InputManager.executeGesture (09:37:58):
Input: kb(laptop):space
IO - speech.speakTypedCharacters (09:37:58):
typed word: and
IO - speech.speak (09:37:58):
Speaking [LangChangeCommand ('en'), u'and']
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):f
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):i
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):g
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):u
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):r
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):e
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):space
IO - speech.speakTypedCharacters (09:37:59):
typed word: figure
IO - speech.speak (09:37:59):
Speaking [LangChangeCommand ('en'), u'figure']
IO - inputCore.InputManager.executeGesture (09:37:59):
Input: kb(laptop):c
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):h
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):a
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):r
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):t
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):i
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):g
IO - inputCore.InputManager.executeGesture (09:38:00):
Input: kb(laptop):space
IO - speech.speakTypedCharacters (09:38:00):
typed word: charting
IO - speech.speak (09:38:00):
Speaking [LangChangeCommand ('en'), u'charting']
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):w
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):i
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):t
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):h
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):space
IO - speech.speakTypedCharacters (09:38:01):
typed word: with
IO - speech.speak (09:38:01):
Speaking [LangChangeCommand ('en'), u'with']
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):a
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):n
IO - inputCore.InputManager.executeGesture (09:38:01):
Input: kb(laptop):a
IO - inputCore.InputManager.executeGesture (09:38:02):
Input: kb(laptop):l
IO - inputCore.InputManager.executeGesture (09:38:02):
Input: kb(laptop):y
IO - inputCore.InputManager.executeGesture (09:38:02):
Input: kb(laptop):s
IO - inputCore.InputManager.executeGesture (09:38:02):
Input: kb(laptop):i
IO - inputCore.InputManager.executeGesture (09:38:02):
Input: kb(laptop):s
IO - inputCore.InputManager.executeGesture (09:38:03):
Input: kb(laptop):enter
ERROR - scriptHandler.executeScript (09:38:03):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x050B4770>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 128, in script_caret_newLine
  File "speech.pyc", line 721, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 340, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 289, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
DEBUGWARNING - NVDAObjects.NVDAObject._reportErrorInPreviousWord (09:38:03):
Error fetching last character of previous word
Traceback (most recent call last):
  File "NVDAObjects\__init__.pyc", line 817, in _reportErrorInPreviousWord
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 340, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 289, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (09:38:03):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
IO - speech.speakTypedCharacters (09:38:03):
typed word: analysis
IO - speech.speak (09:38:03):
Speaking [LangChangeCommand ('en'), u'analysis']
IO - speech.speak (09:38:03):
Speaking [LangChangeCommand ('en'), u'point and figure charting with analysis - Qwant Search  document']
IO - inputCore.InputManager.executeGesture (09:38:15):
Input: kb(laptop):NVDA+space
IO - inputCore.InputManager.executeGesture (09:38:16):
Input: kb(laptop):h
IO - speech.speak (09:38:16):
Speaking [LangChangeCommand ('en'), u'no next heading']
IO - inputCore.InputManager.executeGesture (09:38:17):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (09:38:17):
Input: kb(laptop):tab
IO - speech.speak (09:38:17):
Speaking [LangChangeCommand ('en'), u'What are you looking for?  edit']
IO - speech.speak (09:38:17):
Speaking [LangChangeCommand ('en'), u'point and figure charting with analysis']
IO - speech.speak (09:38:17):
Speaking [LangChangeCommand ('en'), u'IMAGES', u'link']
IO - inputCore.InputManager.executeGesture (09:38:19):
Input: kb(laptop):NVDA+space
IO - inputCore.InputManager.executeGesture (09:38:19):
Input: kb(laptop):h
IO - inputCore.InputManager.executeGesture (09:38:19):
Input: kb(laptop):h
IO - speech.speak (09:38:19):
Speaking [LangChangeCommand ('en'), u'What are you looking for?  edit']
IO - speech.speak (09:38:19):
Speaking [LangChangeCommand ('en'), u'point and figure charting with analysish']
IO - inputCore.InputManager.executeGesture (09:38:22):
Input: kb(laptop):h
IO - inputCore.InputManager.executeGesture (09:38:23):
Input: kb(laptop):backspace
IO - speech._speakSpellingGen (09:38:23):
Speaking character u'h'
IO - inputCore.InputManager.executeGesture (09:38:24):
Input: kb(laptop):NVDA+space
IO - inputCore.InputManager.executeGesture (09:38:25):
Input: kb(laptop):h
IO - speech.speak (09:38:25):
Speaking [LangChangeCommand ('en'), u'Web', u'link', u'heading  level 2']
IO - speech.speak (09:38:25):
Speaking [LangChangeCommand ('en'), u'Web', u'link', u'heading  level 2']
IO - inputCore.InputManager.executeGesture (09:38:25):
Input: kb(laptop):h
IO - speech.speak (09:38:25):
Speaking [LangChangeCommand ('en'), u'Point and figure chart - Wikipedia', u'link', u'heading  level 3']
IO - speech.speak (09:38:26):
Speaking [LangChangeCommand ('en'), u'Point and figure chart - Wikipedia', u'link', u'heading  level 3']
IO - inputCore.InputManager.executeGesture (09:38:28):
Input: kb(laptop):h
IO - speech.speak (09:38:28):
Speaking [LangChangeCommand ('en'), u'Point & Figure Charting [ChartSchool] - StockCharts.com', u'visited  link', u'heading  level 3']
IO - speech.speak (09:38:28):
Speaking [LangChangeCommand ('en'), u'Point & Figure Charting [ChartSchool] - StockCharts.com', u'visited  link', u'heading  level 3']
IO - inputCore.InputManager.executeGesture (09:38:38):

**Comment by MichelSuch** [comment] 2017-02-18 15:18
After some navigation on the result page, many strange things happen to 
NVDA.

For example, pressing the alt key switches keyboard layout, the NVDA key 
does not work anymore as expected.

Never seen such a thing!


                     Michel SUCH

michel.such@free.fr
Skype : michel.such
Twitter : @SuchMichel

**Comment by PratikP1** [comment] 2017-02-18 15:20
Can you provide a log? I’m not seeing this at all.

**Comment by MichelSuch** [comment] 2017-02-18 15:44
Here is a log, I set it on input/output logging level.
[nvda-log.zip](https://github.com/nvaccess/nvda/files/785136/nvda-log.zip)

**Comment by ehollig** [comment] 2018-04-18 20:27
@MichelSuch, is this still an issue? I do not believe I can replicate using NVDA next-15040,26daa5cb

**Comment by ehollig** [comment] 2018-09-06 00:03
Closing, as I am unable to reproduce this issue.
Steps I took to reproduce:
1. Go to http://www.qwant.com
2. Enter "anything" into the search field
3. Press enter and then tab
4. Press H to move to the next heading and shift+H to go to the previous heading.
Everything seems to work well for me.

**Closed by ehollig** 2018-09-06 00:03 UTC
