### ISSUE TITLE
Excel: Navigate to last or first cell containing data in a row/column while in browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5404] opened 2015-10-08 04:37 UTC
**Reported by siddhartha_iitd on 2015-10-08 04:37**
In MS Excel if Cells are Protected and Selection Disabled, there should be a way to read any given row/column, to know the last data containing cell in a row/column, especially if the data is sparsely filled. Moreover, there should be a way to directly navigate to first/last data containing cell of any row/column.

This is already implemented as a solution to #4952. It's available in branch in_t4952_nvdaobj at https://bitbucket.org/manish_agrawal/nvda

**Comment by jcsteh** [comment] 2016-05-24 04:03
@DineshKaushal: As discussed on the call today, it'd be great if we can get an updated summary of what is needed here. The inability to move to locked cells no longer applies, since browse mode now allows this. Note the following:

1. A quick look at the code suggests we might need to add control+home/control+end to handle locked cells in browse mode.
2. We also need a use case and expected behaviour for row/column reading commands; e.g. why it's more efficient than just cursoring through the sheet, whether empty cells should be skipped, whether coordinates should be read, whether regions should be respected, etc.

**Comment by ehollig** [comment] 2017-11-25 02:15
This sounds similar to the feature requested in #1911

**Comment by feerrenrut** [comment] 2017-11-29 06:38
There is also #901 which covers reading Rows and Columns and is specific to excel. 

The difference between this and #1911, if I'm not mistaken, is that it also aims to cover navigating to the the last cell with data in a row or column (in browse mode).

Outstanding questions pertinent to reading rows / columns in excel:
> why it's more efficient than just cursoring through the sheet

 #1911 gives some insight into this. The action of cursoring takes focus away from the content.
The user has to:
- consider if you have reached the last call with data in the row / column
- press the arrow key

> whether empty cells should be skipped

This is still a good question. I would imagine they should be skipped for the following reason.
- Skipping makes it easier to understand the cells that are empty
  - Faster, because you do not have to wait for each cell coordinate to be announced.
  - Requires less memory, the users does not have to count and remember the number of cells skipped. 

The option "cell coordinates" in the document formatting dialog plays into this.
Consider the following use cases:
- A user who wants to know about empty cells.
  - Essentially cares about cell boundaries.
  - Turns on reporting of cell coordinates.
  - They do not need to hear "hello A1, A2, A3, world A4" to know that two blank cells were skipped. This could be achieved with "hello A1, world A4"
  - [warning, scope creep ahead] If this were not enough we could add an announcement: "hello A1, two cells skipped, world A4" I would suggest this be considered out of scope for this issue. It should be request, justified, and validated as a new issue. 
- A user who does not want to know about the empty cells, but cares about the cell boundaries of cells with data.
  - This is someone who wants to ensure they dont get confused about which data comes from which cell. EG "red car blue" vs  "red A1, car blue A2"
  - Turns on reporting of cell coordinates.
- A user who does not care about any cell boundaries, the data has enough context to understand which cell it is in.
  - Turns off reporting of cell coordinates, if they find it distracting.

> whether coordinates should be read

This should be based on the, "cell coordinates" option in document formatting.

> whether regions should be respected

Not sure about this one, opinions / explanations welcome.

**Comment by feerrenrut** [comment] 2017-11-29 06:42
Given there is #901, which discusses reading the row/column in excel, I will move the relevant parts of the previous comment there, and morph this issue to be specific to navigating to the final data filled cell in a row or column while in browse mode.

**Comment by Adriani90** [comment] 2017-12-01 13:09
I am working as an analyst in finance and I am dealing with big financial models almost every day. If the sheets are well organized you can easily navigate by data regions and from first to last row or column of a data region by holding down the ctrl key and pressing the arrow keys. With ctrl + page down you can go to the last data cell of a sheet and then press ctrl+ up to go to the begining of the last data region. I don't really see the issue here.

However, try doing following:
1. In an empty sheet write Hello in e10
2. Write Hey in e20
3. protect the sheet and be sure that users are not allowed to sellect protected cells.
4. Be sure that users are allowed to sellect unprotected cells


Result: In focus mode you will not be able to navigate through the table at all which is ok. But in browse mode everything works fine.

To reproduce this more clearly, go to e10, right click on it and go to formating cells dialog. Go to "protect" and uncheck the checkbox for protecting that cell. Do the same for e20. Now if you protect the whole sheet again and make sure the users are not allowed to sellect protected cells but only unprotected cells, following will happen:
- NVDA will jump only between e10 and e20 everytime you press an arrow key.

In many sheets, diferent cells are protected individually, so that it will not be possible for NVDA to structure the data in focus mode in such a way that you can navigate to the protected cells. But browse mode works very fine so I think there is no problem about that.

**Comment by feerrenrut** [comment] 2017-12-04 01:24
Thanks @Adriani90, I wasn't aware of those shortcuts, could you mention the version of Excel you used to test this please?
I can confirm this works well in browse mode for Excel 2013. 

I'm not sure what behaviour the following was supposed to trigger:
> A quick look at the code suggests we might need to add control+home/control+end to handle locked cells in browse mode

I assumed it was the behaviour we currently get from `ctrl+left` / `ctrl+right` while in browse mode.

**Comment by Adriani90** [comment] 2017-12-04 05:57
Hi, I used Excel 2010 and excel 2016.



Von meinem iPhone gesendet

**Comment by feerrenrut** [comment] 2017-12-04 07:12
I think testing of this in Excel 2010, 2013, and 2016 is good enough coverage to close this issue. So if I'm missing the point (perhaps some other behaviour is expected from `ctrl+home` / `ctrl+end`) or someone else gets different results please comment here.

**Closed by feerrenrut** 2017-12-04 07:12 UTC
Labels: bug
