### ISSUE TITLE
In microsoft win 10 mail, Nvda raises a com error

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#8015] opened 2018-02-19 09:16 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. open win 10 mail app
> 2. switch to whatever account you have set up
> 3. Open any message in your inbox
> 4. Notice an error sound when enter is pressed.
> 5. in the log, the following error is present: ERROR - queueHandler.pumpAll (10:08:15.861):
error in generator 435
Traceback (most recent call last):
  File "queueHandler.pyc", line 72, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 752, in speakTextInfo
  File "treeInterceptorHandler.pyc", line 212, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 158, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 620, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 592, in _getTextWithFieldsForUIARange
COMError: (-2146233079, None, (None, None, None, 0, None))

### Expected behavior:
> Nvda should load the field error-free.

### Actual behavior:
> it loads slowly, but with error.

### System configuration:
NVDA version: latest master snapshot
> Example: next-14027,c80e529f

NVDA Installed or portable: installed

Other information:
> Example: Running in a VM

Windows version:
> windows 10 ver 1709 16299.latest build

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Brian1Gaff** [comment] 2018-02-19 10:08
So is it a next or a master snap?
 What is it doing looking at the word  data when in the email program?
 
Brian

**Comment by zstanecic** [comment] 2018-02-19 10:27
Hi brian,
Read my issue carefully.

1. I said, that it is the master snap latest one
2. It happens directly when the message is loading, and it is the random error, hard to reproduce. 
Maybe you will not be able to reproduce it.


Wysłane z aplikacji Poczta dla Windows 10

Od: Brian Gaff
Wysłano: poniedziałek, 19 lutego 2018 11:09
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] In microsoft win 10 mail, Nvda raises a com error(#8015)

So is it a next or a master snap?
What is it doing looking at the word data when in the email program?

Brian

**Comment by leonardder** [comment] 2018-02-21 20:00
Could you please also test this with 2017.4? Many major changes have been made to UIA support in Word, which also covers Windows 10 mail I believe.

**Comment by zstanecic** [comment] 2018-02-22 07:55
Well,
It’s irrelevant, because in 2017.4 i don’t see this error


Wysłane z aplikacji Poczta dla Windows 10

Od: Leonard de Ruijter
Wysłano: środa, 21 lutego 2018 21:00
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] In microsoft win 10 mail, Nvda raises a com error(#8015)

Could you please also test this with 2017.4? Many major changes have been made to UIA support in Word, which also covers Windows 10 mail I believe.

**Comment by leonardder** [comment] 2018-02-22 13:04
[**@zstanecic**](https://github.com/zstanecic) commented on [22 feb. 2018 08:55 CET](https://github.com/nvaccess/nvda/issues/8015#issuecomment-367596025 "2018-02-22T07:55:13Z - Replied by Github Reply Comments"):
> It’s irrelevant, because in 2017.4 i don’t see this error

What do you consider irrelevant here? I actually belief that it would be quite relevant if this issue did not occur in 2017.4 and does occur in master snapshots. Note that release versions do not play the error sound though. Are you sure the log does not show this error?

**Comment by zstanecic** [comment] 2018-02-22 13:06
Yes, i have checked it


Wysłane z aplikacji Poczta dla Windows 10

Od: Leonard de Ruijter
Wysłano: czwartek, 22 lutego 2018 14:05
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] In microsoft win 10 mail, Nvda raises a com error(#8015)

@zstanecic commented on 22 feb. 2018 08:55 CET:
It’s irrelevant, because in 2017.4 i don’t see this error
What do you consider irrelevant here? I actually belief that it would be quite relevant if this issue did not occur in 2017.4 and does occur in master snapshots. Note that release versions do not play the error sound though. Are you sure the log does not show this error?

**Comment by leonardder** [comment] 2018-02-22 13:12
@michaeldcurran: could you please prioritise and investigate this?

**Comment by zstanecic** [comment] 2018-02-22 13:18
Well, i will say that it is a high priority, because it’s going into 2018,1


Wysłane z aplikacji Poczta dla Windows 10

Od: Leonard de Ruijter
Wysłano: czwartek, 22 lutego 2018 14:16
Do: nvaccess/nvda
DW: zstanecic; Mention
Temat: Re: [nvaccess/nvda] In microsoft win 10 mail, Nvda raises a com error(#8015)

@michaelDCurran: could you please prioritise and investigate this?

**Comment by Brian1Gaff** [comment] 2018-02-22 15:06
Does it in fact stop it functioning?

**Comment by ehollig** [comment] 2018-11-08 03:44
@michaelDCurran, could you please prioritize and investigate this as requested in https://github.com/nvaccess/nvda/issues/8015#issuecomment-367676348? As there are several issues around Windows 10 mail, I think it should get some more attention

**Comment by Adriani90** [comment] 2019-05-02 20:30
I cannot reproduce this in Windows 10 1809 Update and NVDA 2019.1.1 with Windows Mail app. Closing as works for me. If you are still having this problem, please comment on it and we can reopen the discussion.

**Closed by Adriani90** 2019-05-02 20:30 UTC
Labels: regression, worksforme
