### ISSUE TITLE
Setting the inflection and pitch sliders to 50% in e-speak-ng causes them to go back to 51%

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11832] opened 2020-11-12 20:20 UTC
### Steps to reproduce:
1. Set the synthesizer to e-speak-ng
2. Set the inflection and pitch to 50%
3. Save the configuration
4. They will revert back to 51%
### Actual behavior:
The inflection and pitch sliders will be 51% after setting them to 50% and saving the configuration
### Expected behavior:
They should be at 50% instead of 51%
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
windows 10 build 1909
#### Does the issue still occur after restarting your computer?
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by bhavyashah** [comment] 2021-01-16 02:16
I can confirm this rather odd issue using NVDA 2020.4 Beta 4. As it stands, this issue is very low-impact and is therefore, I think, unlikely to receive much attention. @fatihyuksek1 By any chance, have you investigated this issue further and found variations of it to occur at other percentages, for other voice settins, and with other speech synthesizers? An expanded understanding of the prevalence of this issue would be in the interest of this ticket.

**Comment by fatihyuksek1** [comment] 2021-01-17 10:08
I tested and found that this bug affects only e-speak ng. It didn’t affect neither SAPI nor windows one core voices Windows 10 için Posta ile gönderildi Kimden: bhavyashahGönderilme: 16 Ocak 2021 Cumartesi 05:16Kime: nvaccess/nvdaBilgi: fatihyuksek1; MentionKonu: Re: [nvaccess/nvda] Setting the inflection and pitch sliders to 50% in e-speak-ng causes them to go back to 51% (#11832) I can confirm this rather odd issue using NVDA 2020.4 Beta 4. As it stands, this issue is very low-impact and is therefore, I think, unlikely to receive much attention. @fatihyuksek1 By any chance, have you investigated this issue further and found variations of it to occur at other percentages, for other voice settins, and with other speech synthesizers? An expanded understanding of the prevalence of this issue would be in the interest of this ticket.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ehollig** [comment] 2022-11-10 20:26
Would this be an espeak issue? This one is odd indeed.

**Comment by seanbudd** [comment] 2022-11-11 00:00
@ehollig  This is a duplicate of #9811, closing for the same reason as that issue.

**Closed by seanbudd** 2022-11-11 00:00 UTC
