### ISSUE TITLE
Incorrect focus after selecting a file in Chrome

### ISSUE THREAD

**Issue by gabrielhhaber** [nvaccess/nvda#14125] opened 2022-09-11 17:11 UTC
### Steps to reproduce:
1. Open an HTML page that has a form, with a button to select a certain file, like the one linked here.
[HTML example form with select file button](HTTP://intervox.nce.ufrj.br/~heineck/select_file.html)
2. Go to the file selection button with the down arrow, using browse mode. Select any file from your computer and click the open button to confirm, or even press the escape key, it does not affect the result.
3. Note that after returning to the Chrome window, NVDA will only read the title of the window, but the focus will not automatically return to the document. Thus, it is necessary to press the tab key to be able to navigate the page, and it will not be possible to navigate with the up and down arrows.
### Actual behavior:

NVDA focus does not return to document after selecting file.
### Expected behavior:

NVDA should allow page navigation normally after selection, with the up and down arrows.
### NVDA logs, crash dumps and other attachments:
I am linking a simple HTML page with an example form.
#### NVDA installed/portable/running from source:
NVDA installed.
#### NVDA version:
NVDA 2022.2.2 (latest version)
#### Windows version:
Windows 10 v21H2
#### Name and version of other software in use when reproducing the issue:
Google Chrome v105.0.5195.102 (latest version)
#### Other information about your system:
Apparently, this issue only occurs on Google Chrome, but not on other Chromium-based browsers such as Microsoft Edge. Also, if the page automatically sets focus to another element after selecting the file, the problem does not occur, only if the focus is not explicitly set to another element. NVDA speaks the name of the button that was focused before the file selection, but then it just reads the window title and the focus freezes.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I haven't tried it with other versions of NVDA.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Adriani90** [comment] 2023-11-01 10:58
Closing as duplicate of #7099.

**Closed by Adriani90** 2023-11-01 10:58 UTC
Labels: close/duplicate, GoogleWork, p3, app/chrome, app/edge/anaheim, triaged
