### ISSUE TITLE
Table role "presentation" is not identify by NVDA screen reader

### ISSUE THREAD

**Issue by Muthu3982** [nvaccess/nvda#13227] opened 2022-01-10 22:27 UTC
### Steps to reproduce:
We have a table inside the UL -> LI (each LI has a table) and we don't want the screen reader to announce the table when it focused, hence we added role="presentation" for the table, but still when the first row of the first table is focused NVDA announce as table... where as for the other tables (present inside the second LI) NVDA is not announcing as table.
### Actual behavior:
NVDA still identify as table even after role presentation.

### Expected behavior:
NVDA should not identify as table when role presentation is added.

#### Does the issue still occur after restarting your computer? 
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, NVDA 2021

**Comment by ehollig** [comment] 2022-09-22 16:01
Hello @Muthu3982, could you provide a minimal example of the page you are describing as an attachment?

**Comment by seanbudd** [comment] 2022-09-26 00:28
Welcome @Muthu3982 ,

We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need a code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).
- The NVDA versions listed are out of date, and were out of date when this issue was posted. Please confirm this is still an issue with NVDA 2022.2+

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment] 2023-04-20 13:49
I you have nested tables, you have to add role="presentation to every <table> tag.

For instance using following example reproduces your issue but this is not respecting aria spec:

```
<ul>
<li>
<table role='presentation'>
<tbody>
<tr>
<td><strong>Example</strong></td>
<td><strong>Navigation</strong></td>
</tr>
</tbody>
<table>
<tbody>
<tr>
<td><strong>hello world</strong></td>
<td><strong>sunny day</strong></td>
</tr>
</tbody>
</table>
</table>
</li>
</ul>
```
In this case, the second table is nested but does not have a role ="presentation", so NVDA still recognizes it as table even though the first parent table has this role.

See also following link for more information:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role

In fact, all the elements inside of TH and TD are exposed to the screen reader even if the table has a role="presentation".

Since we miss a test case from the initial author, I am closing this issue as invalid.

**Closed by Adriani90** 2023-04-20 13:49 UTC
Labels: close/invalid, blocked/needs-info, blocked/needs-sample
