### ISSUE TITLE
NVDA announces most of the WPF dialog contents on opening "Options" dialog when they obtain focus

### ISSUE THREAD

**Issue by jeremymeng** [nvaccess/nvda#8243] opened 2018-05-07 17:16 UTC
### Steps to reproduce:

1. Open Visual Studio 2017 (a free community edition is available at https://www.visualstudio.com/downloads/)
2. Invoke **Tools | Options** menu item
3. Type "Live Unit Testing" in the search text box
4. Click on the "General" node
5. Type TAB key

![image](https://user-images.githubusercontent.com/7583839/39714498-23ed7b80-51df-11e8-8bfc-cf2666a2aed2.png)

### Expected behavior:

NVDA should only announce the checkbox that has focus.

In this case **General grouping | Pause Live Unit Testing during build and debug check box not checked**

### Actual behavior:

NVDA announces most of the controls on the right pane. Below is what is showing in the Speech Viewer:

![image](https://user-images.githubusercontent.com/7583839/39714459-fd079f46-51de-11e8-882a-77b5ee4cd9fb.png)

Note that the Visual Studio Option dialog hosts both Win32 and WPF option pages
on the right pane. NVDA has this behavior for other WPF option panes as well.

Another example is **Text Editor | C# | Advanced** option pane. NVDA doesn't
announce the whole contents of an option page when it is implemented using Win32
controls. Most of the Visual Studio Option dialog panes are in Win32.

### System configuration:
NVDA version: > 2018.1.1

NVDA Installed or portable:

Portable

Other information:

Windows version: Windows 10

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Yes

Have you tried any other versions of NVDA?

No

**Comment by jeremymeng** [comment] 2018-05-07 17:16
Is it by-design?

**Comment by Adriani90** [comment] 2019-05-07 17:39
cc: @francipvb maybe you can answer this as VB user and NVDA developer. Thank you very much.

**Comment by francipvb** [comment] 2019-05-07 18:09
Hello,

No, I don't think so.

Still occurs with latest alpha.

Cheers,

**Comment by Adriani90** [comment] 2024-01-30 22:51
Closing as duplicate of the newer #15342. Note the comments there for more details.

**Closed by Adriani90** 2024-01-30 22:51 UTC
Labels: close/duplicate
