### ISSUE TITLE
The Braille navigation doesn't work in Thunderbird when meeting an empty line

### ISSUE THREAD

**Issue by vincent-lg** [nvaccess/nvda#8127] opened 2018-03-27 12:36 UTC
### Steps to reproduce:

1. Open Mozilla Thunderbird.
2. Scroll to a message and open it with Enter.
3. Use the Braille navigation keys to read the email.

### Expected behavior:

Obviously, navigation keys in Thunderbird (particularly when reading an email) should still work as it already does in so many editors.  Empty lines should appear on the Braille display and the move shouldn't be cancelled.

### Actual behavior:

If the next line is empty, the move will be cancelled when pressing whatever Braille forward navigation key you happen to have.  One has to scroll using a different strategy to skip empty lines.

### System configuration:
NVDA version: 2018.1

NVDA Installed or portable: installed.

Other information: obviously, test with Braille support.

Windows version: 10.

Name and version of other software in use when reproducing the issue: Thunderbird 52 (and many past releases).

### Other questions:

Does the issue still occur after restarting your PC? Indeed.

Have you tried any other versions of NVDA? As far as I know, this behavior was there on every Thunderbird and NVDA releases since I began using NVDA itself, maybe in 2011.

**Comment by Adriani90** [comment] 2019-12-05 23:05
@vincent-lg can you still reproduce this issue in thunderbird 68.3.0 and NVDA 2019.2.1?

**Comment by Adriani90** [comment] 2020-05-07 20:15
@hozosch, @novalis7747, @bdorer  could anyone of you please try to reproduce this issue? I don't have a braille display at hand unfortunately. Thanks.

**Comment by Andre9642** [comment] 2020-05-08 05:49
I confirm the issue, but in another context.

STR:

1. Open Mozilla Thunderbird.
2. Create a new message.
3. Move the focus on the message body field.
4. Paste the following text (for example):
    > a
    > b<br />
    > c<br />
    > d<br />
    > .
5. Put the cursor on the first line.
6. Use the Braille navigation keys to read the message.

Result: we can scroll until the second line only.

**Comment by hozosch** [comment] 2020-05-08 08:47
Same here. I can only confirm it in the context given by @Andre9642.

**Comment by Adriani90** [comment] 2020-05-08 12:13
Personally, i think this is a quite severe issue at least for people using only braille display for the navigation.
cc: @bramd, @leonardder

**Comment by Adriani90** [comment] 2023-08-14 19:59
@aaclause, @hozosch can you also reproduce this issue in Thunderbird 115.1 with NVDA 2023.2 Beta 3?

**Comment by hozosch** [comment] 2023-08-14 20:13
I'm sorry, I currently don't have a braille display to test, and I'm not sure when I will get my hands on it again. I will write if I do have a way to test.

**Comment by Adriani90** [comment] 2023-08-15 21:05
Thanks for testing, I am closing this issue as works for me. @vincent-lg in case you are still having this issue, please comment on it and we can reopen.

**Closed by Adriani90** 2023-08-15 21:05 UTC
Labels: close/worksforme, component/braille
