### ISSUE TITLE
Problem with gui.nvdaControls.CustomCheckListBox

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#8916] opened 2018-11-04 10:13 UTC
### Steps to reproduce:
1. Press NVDA+control+k to open the Keyboard category of the NVDA settings dialog.
2. Press OK button to close the dialog.
3. Press NVDA+q to NVDA exit.
4. Press control+alt+n to start NVDA.

### Actual behavior:
NVDA starts for a very long time, after which everything freezes. It becomes impossible to use the system.

### Expected behavior:
NVDA should start and work normally.

### System configuration:
Windows 7 32bit SP1 with all updates.

#### NVDA Installed/portable/running from source:
Installed and portable

#### NVDA version:
alpha-16220,87eb36f8

#### Does the issue still occur after restarting your PC?
Yes, the issue is always reproduced.

**Comment by lukaszgo1** [comment] 2018-11-04 20:17
I can reproduce it on Windows 7 Professional x64 all of the time. It is almost impossible to get a log from this crash, because the rest of the system also crashes with NVDA. I believe that it is a good candidate for a P1. @michaelDCurran @feerrenrut

**Comment by lukaszgo1** [comment] 2018-12-06 15:57
Should this one be fixed when #8006 was merged?

**Comment by lukaszgo1** [comment] 2019-01-31 14:16
This list is now used in advanced settings and the same problem can be observed there. The only way to restore computer to its working condition after restart of NVDA is a complete reboot of the system. Can this be given attention it deserves? Solving it before 2019.1 is released would be nice.

**Comment by leonardder** [comment] 2019-01-31 14:36
I can not reproduce this myself, but will try to provide a fix.

**Comment by Adriani90** [comment] 2019-01-31 18:01
I can definitely reproduce it in Windows 10 1809 update with NVDA 2018.4.1. I think we could find some notices maybe in the event viewer. I was looking for indicators there but couldn't really find something which convinces me yet.

**Comment by leonardder** [comment] 2019-01-31 18:21
Could you please test [this](https://ci.appveyor.com/api/buildjobs/aln7s4yp2g3j3l5y/artifacts/output%2Fnvda_snapshot_try-accPropServerFix-16681%2C996dce6e.exe) try build?

**Comment by lukaszgo1** [comment] 2019-01-31 18:50
I've tested with the STR given in the initial commend, and the bug is gone. I cannot test with the logging options list in the advanced settings, because it isn't included in this build.

**Comment by kvark128** [comment] 2019-01-31 20:46
I confirm that the bug has been fixed in this build.

**Closed** 2019-02-01 13:02 UTC
Labels: freeze, p2
