### ISSUE TITLE
ALVA: Merge double "alt key"-lines into one in the documentation

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8509] opened 2018-07-17 17:53 UTC
### Steps to reproduce:

1. Open the NVDA User Guide (userGuide.html).
2. Go to "14.3. Optelec ALVA 6 series/protocol converter".

And

1. Open the NVDA Commands Quick Reference (keyCommands.html).
2. Go to "Optelec ALVA 6 series/protocol converter".
### Actual behavior:
The line "alt key" in both tables exists twice.
### Expected behavior:
Merge "sp2" and "alt" to "sp2, alt" and delete the second "alt key"-line in both tables.
#### NVDA version:
NVDA alpha-15554,66186bfb

**Comment by josephsl** [comment] 2018-07-17 17:58
Hi, looks like the pull request for fixing this wasn’t merged yesterday. CC @MichaelDCurran, @LeonardDer

**Comment by lukaszgo1** [comment] 2018-07-17 18:59
It was initially reported in #8073 and fixed in #8465. I think this issue should be closed as duplicate of #8073

**Comment by DrSooom** [comment] 2018-07-17 22:17
@lukaszgo1: Will those changes in the file "user_docs/en/userGuide.t2t" will also have effects on the file "keyCommands.html" as well? If so, PR #8465 will close this bug here (#8509) as well.

**Comment by leonardder** [comment] 2018-07-18 04:07
Closing as duplicate of #8073.

**Closed by leonardder** 2018-07-18 04:07 UTC

**Comment by DrSooom** [comment] 2018-07-18 23:23
@leonardder: Could you please label this bug here as "duplicate" too – for the issue overview on GitHub. Thanks.
