### ISSUE TITLE
Excel 2010: Focus not automatically regained when applying Filter

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5413] opened 2015-10-12 17:21 UTC
**Reported by elliott94 on 2015-10-12 17:21**
Str:
1. Open a new workbook, and enter the following in cells A1-4:

Name

Dave

James

John
1. Enter the following in cells B1-4:

Location

Canada

United Kingdom

United States
1. Add a filter to the active workbook by choosing "Filter" from the Data tab of the ribbon
2. Navigating back to A1, press Alt+the down cursor; this should open the drop-down menu from where a filter can then be set
3. From the list of values that can be filtered in the A column, select any of the names as entered above and either click on the OK button or simply press Enter after checking the relevant checkbox

Expected: Upon closing, the user should automatically be returned to the active worksheet, at which point they can examine the resulting data that has just been filtered.

Actual: It is first necessary to Alt-Tab out of, and then back into the window before anything is read.

**Comment by Adriani90** [comment] 2023-02-08 22:16
@elliott94 can you still reproduce this in nvda 2022.4? I cannot reproduce this in MS Excel 365.

**Comment by seanbudd** [comment] 2023-02-12 19:32
@Adriani90 

Closing this as fixed + abandoned. If this is not the case, please open a new issue.

**Closed by seanbudd** 2023-02-12 19:32 UTC
Labels: bug, app/microsoft-office
