### ISSUE TITLE
Notepad++ and Braille: scrolling problem

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#7483] opened 2017-08-09 06:46 UTC
### Steps to reproduce:
With the latest next version, you can nomore scroll forward and backward with a braille terminal using Notepad++.
Other problem: you can't enter contracted braille from the terminal, the text seems to appear and disappear instantly.

**Comment by leonardder** [comment] 2017-08-09 07:30
Closed as duplicate of #7419

**Closed** 2017-08-09 07:29 UTC
