### ISSUE TITLE
Punctuation is announced separatedelly from a HTML element

### ISSUE THREAD

**Issue by nsousa2007** [nvaccess/nvda#6888] opened 2017-02-15 15:27 UTC
There are different behaviours, but normally, when a HTML element, e.g. Link, is followed by a period, the period is announced in the line after the link when using arrows up/ down.
The same happens with atributes like "abbr"; "alt" in images-links with text name; "span text" inserted in Links "through" hidden CSS classes..

**Comment by PratikP1** [comment] 2017-02-15 17:01
Can you provide examples of the behavior you’re describing? In the case of links, the code makes a difference. If, for instance, the punctuation is wrapped in the anchor tag, NVDA does not treat it separately. If the punctuation is outside the tag, then it is treated as it should. I suspect your remaining cases  are similar in nature. It’s the content creator’s job to markup the document correct. NVDA should not second guess.

**Comment by nsousa2007** [comment] 2017-02-16 14:55
Hi,

Punctuation should be writen outside the Link. NVDA should do the right pause instead of reading the period when navigating with up/ down arrows. It is what I wanted to say. I'm sorry. It happens in other programs like Skype too.
Below examples for Links, span and abbr elements. Pay attention to the diference in reading behaviour between the two abbr implementations.
http://codepen.io/nsousa/pen/OWGbdg

Regards,
NS

**Comment by jcsteh** [comment] 2017-02-22 06:29
This occurs because links are separated from other content so it is clear that the other content is not part of the link. For example, if you had the letters "ab" together, but a was a link and b wasn't part of the link, we would say "link a b" rather than "link ab". Saying "link ab" is misleading because it suggests that the b is part of the link. It might be good to special case specific symbols here, but that is not easy to do without breaking other cases.

This is a duplicate of #1475, so closing.

**Closed by jcsteh** 2017-02-22 06:29 UTC

**Comment by nsousa2007** [comment] 2017-02-22 09:23
Hi,

Your example fits to "Link+text". But it should not happen for punctuation and for other examples I've attached.
So far I understood, the 1475 opened treating the issue of punctuation, but went further with control fields + text.
Unfortunatelly I don't know to code enough yet!
I'd like to leave this issue open, since it has other examples when it occurs..

Regards,
NS
