### ISSUE TITLE
NVDA crashes Microsoft Word

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#9375] opened 2019-03-14 12:58 UTC
Ever since installing the 2019.1beta1 copy of NVDA, I have experienced a crash in Microsoft Word, that I feel can be tied down to navigating in tables. I would sometimes be arrowing up and down in the document to move by column, and then NVDA would become silent for two seconds. Then, Microsoft Word would close, leaving me at my previously opened window. Sometimes it reopens automatically, while other times, it would require me to try and reopen the program. When it does open, it shows that the file is either recovered, or a version last saved by the user is opened with that being shown in the title. Here is my log to confirm this. I'm using Windows 10 1809 and Microsoft Word (Office) 16.0.4732.100. I have disabled all add-ons.

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:06.795):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:07.609):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 43 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:07.680):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:07.960):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:08.015):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 60 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:08.089):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 61 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:08.150):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 78 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:08.220):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:08.275):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 79 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:08.464):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:08.589):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 96 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:08.769):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:09.079):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 139 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:09.079):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 140 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:09.194):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (07:46:10.003):
oleacc.AccessibleObjectFromEvent with window 919046, objectID 158 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:10.032):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:10.665):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:10.977):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:11.292):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - RPC process 5316 (WINWORD.EXE) (07:46:11.562):
Thread 2520, build\x86_64\remote\winword.cpp, collectRevisionOffsets, 366:
range.revisions failed

DEBUGWARNING - watchdog._watcher (07:46:17.342):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 233, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 490, in run
  File "queueHandler.pyo", line 86, in pumpAll
  File "queueHandler.pyo", line 53, in flushQueue
  File "scriptHandler.pyo", line 145, in _queueScriptCallback
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1377, in script_tab
  File "speech.pyo", line 781, in speakTextInfo
  File "NVDAObjects\window\winword.pyo", line 711, in getTextWithFields

DEBUGWARNING - NVDAObjects.window.winword.WordDocumentTextInfo.getTextWithFields (07:46:23.157):
winword_getTextInRange failed with 1726
DEBUGWARNING - scriptHandler.executeScript (07:46:23.178):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.IAccessible.winword.WordDocument object at 0x04CC9B10>> with gesture u'shift+tab'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1377, in script_tab
  File "speech.pyo", line 781, in speakTextInfo
  File "NVDAObjects\window\winword.pyo", line 714, in getTextWithFields
  File "baseObject.pyo", line 31, in __get__
  File "NVDAObjects\window\winword.pyo", line 942, in _get_text
  File "comtypesMonkeyPatches.pyo", line 37, in new__getattr__
  File "comtypes\client\dynamic.pyo", line 110, in __getattr__
  File "comtypes\automation.pyo", line 708, in GetIDsOfNames
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUGWARNING - scriptHandler.executeScript (07:46:23.178):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.IAccessible.winword.WordDocument object at 0x04CC9B10>> with gesture u'shift+tab'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1370, in script_tab
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (07:46:23.240):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - scriptHandler.executeScript (07:46:23.296):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.IAccessible.winword.WordDocument object at 0x04CC9B10>> with gesture u'tab'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1370, in script_tab
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUGWARNING - scriptHandler.executeScript (07:46:23.303):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.IAccessible.winword.WordDocument object at 0x04CC9B10>> with gesture u'tab'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1370, in script_tab
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUGWARNING - scriptHandler.executeScript (07:46:23.305):
error executing script: <bound method WordDocument.script_tab of <NVDAObjects.IAccessible.winword.WordDocument object at 0x04CC9B10>> with gesture u'tab'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "NVDAObjects\window\winword.pyo", line 1370, in script_tab
  File "comtypesMonkeyPatches.pyo", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyo", line 168, in __getattr__
  File "comtypes\automation.pyo", line 729, in _invoke
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))

**Comment by DrSooom** [comment] 2019-03-14 21:00
@fisher729: Is the option "Use UI automation to access Microsoft Word document controls when available" in the Advanced NVDA Settings enabled? I guess it is. Please disable this, restart NVDA and Microsoft Word and compare the situation. Note that this is just a workaround, it wouldn't fix the UIA issue.

**Comment by Adriani90** [comment] 2019-03-14 21:02
cc: @michaelDCurran

**Comment by fisher729** [comment] 2019-03-15 11:30
Hi Daniel,

No, this option has not been checked, nor has anything in this
settings category. Off topic for this ticket, but why is the Advanced
category being reported in the Settings dialog as profile specific?

**Comment by MAWoods** [comment] 2019-06-14 03:00
Having issues with Word 2016 crashing using NVDA latest version. Is this a memory issue? Should I be using another program instead of Word? Has anyone had this experience with Word 2019?

**Comment by DrSooom** [comment] 2019-06-14 04:24
@MAWoods: If it's critical, you can install [LibreOffice 6.2](https://www.libreoffice.org/download/download/) or just use its [portable version](https://www.libreoffice.org/download/portable-versions/) as a workaround.

**Comment by MAWoods** [comment] 2019-06-14 05:04
Thank you for this. So, you don't think it's a memory issue?

**Comment by DrSooom** [comment] 2019-06-14 05:32
NVDA uses another AppModule for LibreOffice than for Microsoft Word. Therefore using LibreOffice Writer could help here.

**Comment by Adriani90** [comment] 2019-06-14 19:11
@leonardder do you have any idea why the rpc server is unavailable here? I am abit confused also by following part of the log above:
```
range.revisions failed
```


Could this be a side effect of the PR which improved performance in Word without UIA?

**Comment by leonardder** [comment] 2019-09-18 17:43
@Adriani90 The RPC failed is probably because Word crashes and NVDA is unable to communicate with a non-existent Word.

@fisher729: Can this still be reproduced on Alpha versions of NVDA?

**Comment by Adriani90** [comment] 2020-01-19 19:51
@fisher729 do you have this issue in NVDA 2019.3 Beta 2?

**Comment by Adriani90** [comment] 2020-06-25 19:06
@fisher729 could you please test with NVDA 2020.2 Beta 2 if this issue is still occuring?

**Comment by fisher729** [comment] 2020-06-25 21:21
Hi.

It no longer crashes for me. The ticket can therefore be closed.

**Comment by Adriani90** [comment] 2020-06-26 14:15
Thanks for reporting. Closing as works for me.

**Closed by Adriani90** 2020-06-26 14:15 UTC
Labels: app/microsoft-office, bug/app-crash, close/worksforme
