### ISSUE TITLE
Delayed descriptions for characters on cursor movement and Chinese characters

### ISSUE THREAD

**Issue by LittleStar-VIP** [nvaccess/nvda#13966] opened 2022-07-30 09:22 UTC
First of all I would like to say, I am not sure if this is a bug, please correct me if I am wrong.

### Steps to reproduce:
1. enabled the function Delayed descriptions for characters on cursor movement of the latest nvda beta, 2023.1 beta1, 
2. open a notepad and type some Chinese words, e.g. 香港
3. I try switching to Chinese Taiwan and Chinese Hong Kong locale to test this function
4. under each of the locale I use  arrow keys to move the edit cursor to check the character descriptions
5. the character description reported by nvda beta is the same for both of the characters in Chinese Taiwan and Chinese Hong Kong locale (where using the enhance phonetic addon switching locale will generate different character description)
6. Under both locale, nvda beta only reported the first available character description of both of the characters here (where using the enhance phonetic addon switching locale will report all of the available character descriptions)

Specifically using the character 港 as an example.
Using the nvda beta here, the character description for 港 is "香港" under hk and tw locale
but using the enhance phonetic reading addon, the character description under hk locale is "港	香港	港澳	港口	海港	商港	軍港	漁港	港區	港務局	轉運港	駐港領事館" and under tw locale is "港	港口	港灣	香港	海港	避風港	高雄港	(左半三點水，右半巷口的巷)"

### Expected behavior:
1. as Chinese locale has different character description under different locale, the character description being reported should be based on the current locale of the nvda
2. I am not sure if it is an intended function of the pull request to only report the first available character description instead of reporting all the available character description of a character, but I would really appreciate the nvda core to retain the function of enhance phonetic reading to report all available character description 

#### NVDA installed/portable/running from source:
portable

#### NVDA version:
nvda 2022.3 beta 1
#### Windows version:
windows 10 home ed 21h2
#### Does the issue still occur after restarting your computer?
not tried
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not tried
#### If NVDA add-ons are disabled, is your problem still occurring?
this is a nvda portable version without any addon
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not tried

**Comment by seanbudd** [comment] 2022-08-03 03:41
Can you confirm what the results are with NVDA 2022.2?

**Comment by LittleStar-VIP** [comment] 2022-08-03 04:01
I am currently using nvda 2022.2 and both the numpad 2 and the delay character description addon  here generated correctcharacter description based on the current active locale.
charact

**Comment by seanbudd** [comment] 2022-08-04 06:16
Closing as duplicate of #13969

**Closed by seanbudd** 2022-08-04 06:16 UTC

**Comment by CyrilleB79** [comment] 2022-08-04 06:58
This issue is not exactly a duplicate of #13969  since #13969 does not deal with multiple character descriptions which does not exist in western languages.

Instead in this issue's description, the following points refer to multiple descriptions:
> 6. Under both locale, nvda beta only reported the first available character description of both of the characters here (where using the enhance phonetic addon switching locale will report all of the available character descriptions)
and
> 2. I am not sure if it is an intended function of the pull request to only report the first available character description instead of reporting all the available character description of a character, but I would really appreciate the nvda core to retain the function of enhance phonetic reading to report all available character description

Nevertheless, #13972 as it is implemented today is probably fixing this issue as well.
