### ISSUE TITLE
Table navigation does not work for tables with `display: block` in Chrome

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10927] opened 2020-04-01 11:27 UTC
CC @feerrenrut

Originally reported in #10915 

### Steps to reproduce:

1. Go to this page in Chrome: `data:text/html,<table style="display: block;"><tr><th>a</th><td>b</td></tr></table>`

### Actual behavior:
The table is not recognized as such, and table navigation doesn't work

Note:
Looking at the a11y tools in Chrome 80.0.3987.149 (Official Build), this table has a `LayoutTable` role.
This happens because the table has CSS `display: block`, it also happens with `display: inline-block`. 

### Expected behavior:
This table is recognized as such and table navigation works

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-19847,e27e9071
#### Windows version:
Windows 10 1909
#### Name and version of other software in use when reproducing the issue:
Chrome 80.0.3987.162
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Irrelevant
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Irrelevant

**Comment by ObjectInSpace** [comment] 2020-06-01 17:35
Unable to reproduce. When I load this, NVDA announces the table and table navigation works correctly as expected.

**Comment by Adriani90** [comment] 2020-06-01 18:22
Thanks for the update @ObjectInSpace I confirm this works correctly in Chrome 83 with NVDA alpha-20220,1c4519a6. Closing as works for me.

**Closed by Adriani90** 2020-06-01 18:22 UTC
Labels: app/chrome, close/worksforme
