### ISSUE TITLE
Python3. Eliminate the long silence in the one core voices

### ISSUE THREAD

**Issue by comunicationVoices** [nvaccess/nvda#10621] opened 2019-12-14 05:03 UTC
Hello, in the version of NVDA 2019.3beta1, the long silences in windows one core remain as the versions below 2019.1. Silences happen when the text has a period, or two points, etc. I would like you to solve this error. Thank you for reading!

**Comment by josephsl** [comment] 2019-12-14 05:05
Hi, just to clarify: you are saying that this is not happening with 2019.2.1, correct? If so, it is a definite regression. Thanks.

**Comment by Adriani90** [comment] 2019-12-19 12:30
@comunicationVoices could you please answer to the question above? Is this not reproducible with NVDA 2019.2.1?

**Comment by comunicationVoices** [comment] 2019-12-23 18:21
Hi. This error only occurs with 2019.3, in the beta version for python 3. I
just clarify this, regards.

**Comment by feerrenrut** [comment] 2020-01-29 16:13
Closing as a duplicate of #10721 which has the template filled out.

**Closed by feerrenrut** 2020-01-29 16:13 UTC
