### ISSUE TITLE
run nvda from a system account

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#5908] opened 2016-04-28 12:19 UTC
hello all.

i am using a windows server with nvda remote, and when rdp session is disconnecting, i am loosing speech. it seems, nvda is suspending.
how to run nvda from a system account or something else to not loose speech?

**Comment by jcsteh** [comment] 2016-04-28 23:25
I've seen this, but I'm not sure if there's anything that can be done to work around it. When you detach from a Windows remote desktop session, the whole session gets suspended; this seems to be very intentional:

> The RDP client disconnects from an RD Session Host server, but the user session remains in a suspended mode for possible later use.

(https://msdn.microsoft.com/en-us/library/hh872166.aspx)

The question is what "suspended" actually means from a technical point of view; I can't find any documentation on that. Running as another account is very unlikely to help, though, and in fact will probably mean you can't access the UI of any of your applications.

I'm closing this because whether we like it or not, suspending the session is intended behaviour according to Microsoft and users of other remote software are going to hit the same issue.

**Closed by jcsteh** 2016-04-28 23:25 UTC
Labels: cantfix

**Comment by beqabeqa473** [comment] 2016-04-29 03:59
i've managed to run nvda without connecting with rdp.

i've copied userconfig to systemconfig with nvdaremote addon, rebooted a machine, it asked me to press alt+ctrl+del, then i entered my password and logged in to my account.
after that, nvda works without suspension.
