### ISSUE TITLE
NVDA & Magnifier Keyboard Shortcut Conflict

### ISSUE THREAD

**Issue by mush42** [nvaccess/nvda#7902] opened 2018-01-07 12:54 UTC
Hello,

NVDA's browse mode table navigation commands conflict with the built in magnifier commands. I discovered this when I moved to a new computer without a mouse.

The Magnifier commands for moving the magnifying area around the screen is: Ctrl + Alt + arrows (right, left, up, down). Which, apparently, are the same commands used by NVDA in browse mode to navigate table cells.

Outside the browse mode, those commands work perfectly. However in browse mode, it is a bit of a problem, they are taken over completely by NVDA, even after unassigning them using the "Input Gestures" dialog.

**Comment by feerrenrut** [comment] 2018-01-08 06:29
I tried this myself with a [HTML table](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_table_intro) while using Chrome. I can confirm that in browse mode the shortcuts are intercepted by NVDA and can no longer be used to move the magnifier.  

When I tried removing the gestures, the magnifier could be controlled with the keyboard shortcuts while NVDA was in browse mode.

**Comment by josephsl** [comment] 2018-01-08 06:32
Hi, what if you switch to focus mode? Thanks.

**Comment by feerrenrut** [comment] 2018-01-08 06:37
I believe I had the same experience as the reporter who said 
> Outside the browse mode, those commands work perfectly. However in browse mode, it is a bit of a problem

In focus mode the shortcuts can be used to control the magnifier tool even without removing the gestures.

**Comment by JulienCochuyt** [comment] 2019-06-26 10:22
This is an old ticket, but I just wanted to get sure you knew there is no need to remove a shortcut to bypass its setting: Pressing NVDA+F2 allows the next keyboard shortcut to be ignored by NVDA.
The "next keyboard shortcut" is considered done only when all keys are released.
Then, first pressing NVDA+F2, then holding control+alt while pressing multiple times the arrow keys allows to move the magnified area, even in browse mode.

**Comment by Adriani90** [comment] 2019-06-30 00:30
this is also not an issue now that #8846 is merged. In browse mode settings, you can disable browse mode by default. I am closing this as works for me.

**Closed by Adriani90** 2019-06-30 00:30 UTC
Labels: worksforme

**Comment by JulienCochuyt** [comment] 2019-06-30 11:52
@Adriani90, I totally agree this can be closed as being a non-issue, since NVDA+F2 or remapping the gestures are two ways to support controlling the Magnifier panning while NVDA is in browse mode.
Nevertheless, apologies for nitpicking, I disagree that disabling browse mode by default is more than a workaround. I think we should keep in mind this great new feature is not meant to fit every cases, and that users of magnification software should still be allowed to take advantage of browse mode in all situations other users do.

Anyways, thanks for closing.
