### ISSUE TITLE
Add support for seika notetaker braille display

### ISSUE THREAD

**Issue by larry801** [nvaccess/nvda#9478] opened 2019-04-10 10:13 UTC
### Is your feature request related to a problem? Please describe.
No
### Describe the solution you'd like
Add driver for seika notetaker from patch file provided by manufacturer into nvda core
### Describe alternatives you've considered
None

**Comment by JulienCochuyt** [comment] 2019-05-23 09:18
(Cross-posting to issue #5755, I guess we could close one of the duplicates)

Accessolutions repackaged the Seika notetakers driver patch for NVDA version 3.2 as an add-on compatible with 2019.1.1
Repository: https://github.com/accessolutions/seikamini-nvda
Packaged release: https://github.com/accessolutions/seikamini-nvda/releases/download/3.2.2019.1.1/seikamini-3.2.2019.1.1.nvda-addon

We are working with Nippon Telesoft and Tsinghua Univ. on the license agreements and code clean-up to help prepare it for candidate integration in NVDA.

**Comment by leonardder** [comment] 2019-05-23 09:52
duplicate of #5755

**Closed by leonardder** 2019-05-23 09:52 UTC
