### ISSUE TITLE
Freezing nvda with firefox running

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#11628] opened 2020-09-17 18:22 UTC
# Steps to reproduce:

i was not able to identify, when this happens.
last time i've got this was when i was writing something in notepad and firefox was running but minimized to background
`taskkill /f /im firefox.exe` recovered nvda

### Actual behavior:
NVDA is freezing
### Expected behavior:
NVDA should not freeze
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-20966,0baf0ceb
#### Windows version:
Windows 10 2004
#### Name and version of other software in use when reproducing the issue:
firefox 80
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the same
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

Here is a log when i've got this freeze
```
ERROR - watchdog._watcher (22:06:20.294) - watchdog (8808):
Core frozen in stack!
INFO - watchdog._watcher (22:06:20.307) - watchdog (8808):
Listing stacks for Python threads:
Python stack for thread 16356 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 426, in idle
  File "nvwave.pyc", line 436, in _idleUnbuffered
  File "nvwave.pyc", line 386, in sync
  File "winKernel.pyc", line 225, in waitForSingleObject

Python stack for thread 8492 (Dummy-1):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 498, in IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent
  File "_UIAHandler.pyc", line 758, in isNativeUIAElement
  File "_UIAHandler.pyc", line 737, in getNearestWindowHandle
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

Python stack for thread 13656 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 190, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 3632 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x045FC4E0>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 8808 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 142, in _watcher
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 11924 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 8128 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 310, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 11124 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2187, in func

Python stack for thread 3492 (MainThread):
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 550, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1062, in Notify
  File "core.pyc", line 519, in run
  File "IAccessibleHandler\__init__.pyc", line 1099, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 691, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 636, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 79, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 607, in __init__
  File "IAccessibleHandler\__init__.pyc", line 1124, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1158, in QueryInterface
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

ERROR - watchdog._watcher (22:07:21.473) - watchdog (8808):
Core frozen in stack!
INFO - watchdog._watcher (22:07:22.032) - watchdog (8808):
Listing stacks for Python threads:
Python stack for thread 4476 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 426, in idle
  File "nvwave.pyc", line 436, in _idleUnbuffered
  File "nvwave.pyc", line 386, in sync
  File "winKernel.pyc", line 225, in waitForSingleObject

Python stack for thread 13656 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 190, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 3632 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x045FC4E0>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 8808 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 142, in _watcher
  File "watchdog.pyc", line 63, in getFormattedStacksForAllThreads

Python stack for thread 11924 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 8128 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 310, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 11124 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2187, in func

Python stack for thread 3492 (MainThread):
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 550, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1062, in Notify
  File "core.pyc", line 519, in run
  File "IAccessibleHandler\__init__.pyc", line 1099, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 691, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 636, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 79, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 607, in __init__
  File "IAccessibleHandler\__init__.pyc", line 1124, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1158, in QueryInterface
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

```

**Comment by feerrenrut** [comment] 2020-09-18 11:31
Related to #9359

**Comment by beqabeqa473** [comment] 2023-05-10 08:59
Hello.

It is not related with caching.

I am still have this lag and had it in nightly with caching enabled.

On 5/10/23, Adriani90 ***@***.***> wrote:
> Closed #11628 as completed.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11628#event-9208917697
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment] 2023-05-10 09:36
Thanks for the quick update, I am reopning this particular one.

**Comment by jcsteh** [comment] 2023-05-10 10:22
@beqabeqa473, are you absolutely certain the cache is enabled? That is, if you go to about:config in the address bar and search for accessibility.cache.enabled, does it say true?

Are you still able to reproduce this in latest NVDA alpha? At the very least, this should prevent freezing when an app stops responding, so even if Firefox freezes, NVDA shouldn't freeze now.

**Comment by beqabeqa473** [comment] 2023-05-10 10:24
Yes, cache is enabled, and yes, even worr was done to prevenn tnvda
freeze, with firefox i can still experience a freeze.

On 5/10/23, James Teh ***@***.***> wrote:
> @beqabeqa473, are you absolutely certain the cache is enabled? That is, if
> you go to about:config in the address bar and search for
> accessibility.cache.enabled, does it say true?
>
> Are you still able to reproduce this in latest NVDA alpha? At the very
> least, this should prevent freezing when an app stops responding, so even if
> Firefox freezes, NVDA shouldn't freeze now.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11628#issuecomment-1541880306
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by jcsteh** [comment] 2023-05-10 10:31
Okay. In that case, I think it'd be useful to see a new log with latest alpha, as the anti-freeze patch should mean we no longer freeze in the same spot we did before.

**Comment by Adriani90** [comment] 2023-12-14 21:21
@beqabeqa473 a further attempt. Are you still having this issue with NVDA 2023.3 or last alpha and Firefox 120? I could never reproduce this freeze. in the last 6 months of using Firefox.
Could you please run the COM registration fixing tool and see if the issue still happens?

**Comment by Adriani90** [comment] 2024-03-18 22:48
I am closing this issue as works for me, I could not see any freeze related to NVDA while using Firefox in the last year, using NVDA 2024.1 Beta 13 and Firefox 123 I cannot reproduce. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-03-18 22:48 UTC
Labels: close/worksforme, bug/app-freeze, app/firefox
