### ISSUE TITLE
Removing NVDA Service also removed win32api, which cause problems for some add-ons

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7642] opened 2017-10-03 15:49 UTC
When I installed as a portable version, but left the old user config file so the add ons etc would be loaded I got this error on running either the installer or the finished portable version.
ERROR - globalPluginHandler.listPlugins (12:03:44.404):
Error importing global plugin goldenCursor
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 22, in listPlugins
  File "C:\Users\Brian\AppData\Roaming\nvda\addons\goldenCursor\globalPlugins\goldenCursor.py", line 24, in <module>
ImportError: No module named win32api

Seems to be rather a vital omission??

**Comment by Brian1Gaff** [comment] 2017-10-06 09:34
[latest next with just golden cursor as add on clean install, only minor configs to give the result uncluttered by other stuff.log](https://github.com/nvaccess/nvda/files/1362233/latest.next.with.just.golden.cursor.as.add.on.clean.install.only.minor.configs.to.give.the.result.uncluttered.by.other.stuff.log)

**Comment by Brian1Gaff** [comment] 2017-10-06 09:39
Added the complete log for a clean install into a portable version showing the error in the add on. the version of the snap is the first one to create this error. Note if you are updating a previous portable version the chances are due to old files still in the folder the error will not appear in the running portable version, which is probably why this loss of a function was missed during creation of this snap.
Brian

**Comment by fisher729** [comment] 2017-10-16 17:25
I think this issue should be closed, as it doesn't affect NVDA itself, but external components. I think a PSA is in order on some forum, though. Just my thoughts.

**Comment by josephsl** [comment] 2017-10-16 17:35
Hi, thanks for reminding me about a PSA for this. I’ll make a note to remind the add-ons community regarding this in November, and will revisit win32api in January when I plan to remove that dependency completely from the source code. Thanks.

**Comment by leonardder** [comment] 2017-10-16 19:04
I think there should at least be a transision period for new add-ons to be updated. 2018.1 is ok for that, but I belief at least 2017.4 should still contain this dependency.

**Comment by derekriemer** [comment] 2017-10-17 17:54
Is this even a big module? I ask because this and win32con are extremely useful for addons, and removing this might hinder some addon development quite a lot. I would rather not see ten different versions of win32api in 10 different addons if we can stop it.

**Comment by Brian1Gaff** [comment] 2017-10-17 18:50
I do agree with this, but wonder if it is actually going to go away in the 
near future if the new version of Python is used.
 The person who fixed golden cursor presumably put it in the main folder of 
the add on.



Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Brian1Gaff** [comment] 2017-10-17 18:52
PPS...What should have happened is that just parts of the service now not 
needed for XP or Vista were removed instead.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.

**Comment by Adriani90** [comment] 2018-07-28 07:35
As I am understanding this issue correctly, it was reproduced in Windows XP or Vista. Can you reproduce it in Windows 7 or higher? I am using Golden Cursor and am not able to reproduce it on Windows 8.1 or Windows 10.
cc: @josephsl

**Comment by leonardder** [comment] 2018-07-30 18:01
win32api is manually included nowadays, so I'm going to close this. Removing it again is a different issue IMO.

**Closed by leonardder** 2018-07-30 18:01 UTC
