### ISSUE TITLE
Outlook 2013: Problems reading the CC field when it contains more than 2 addresses

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5168] opened 2015-06-20 09:53 UTC
**Reported by Brendon22 on 2015-06-20 09:53**
In Office 2013. In Outlook 2013 and when you creat a new email message and you have more than two people in the CC field, and you move back to the CC edit field to get NVDA to read the CC field to you. NVDA will only allow me to read the first persons name and not all of the people  in that CC field and will not allow me  to review what is in  this CC  field with my  up and down errow keys?

Could this be made possible?

**Comment by ehollig** [comment] 2017-07-28 23:22
This appears to workforme in Outlook 2016. Can anyone test using Outlook 2013 to see if the experience is different?
Also, can anyone change the title of this issue? It is currently too verbose.

**Comment by Adriani90** [comment] 2019-02-01 22:40
@pranavlal could you test if this issue is reproducible in Outlook 2013? Thank you very much in advance.

**Comment by pranavlal** [comment] 2019-02-01 23:20
I certainly could. Please give me until Monday.

-----Original Message-----

**Comment by pranavlal** [comment] 2019-02-02 00:09
One thought, when you tab back into the "cc" field, what about using left and right arrows? They work for me in outlook 2013. I have outlook 2013 on my work machine hence the request to give me until Monday. I usually hit ctrl+home in the "cc" field to get to the top of the field and the review the addresses with right and left  arrows.

**Comment by Adriani90** [comment] 2019-02-04 12:32
Since left and right arrows work in cc and bcc fields in MS Outlook 2013, I am closing this as works for me. @Brendon22 feel free to comment on this issue if you don't agree. Then we can reopen it.

**Closed by Adriani90** 2019-02-04 12:32 UTC
Labels: bug, worksforme
