### ISSUE TITLE
Punctuation / symbol level: most: Some symbols on the right is not voiced (Turkish)

### ISSUE THREAD

**Issue by SeanTolstoyevski** [nvaccess/nvda#12556] opened 2021-06-17 02:40 UTC
If you are reading a sentence in quotes **("SENTENCES WORDS")**, NVDA will ignore the quotation mark on the right.
The problem is that if there is any symbol next to the quotation mark on the right, NVDA will consider the quotation mark on the right. For example "hello."
Now if we remove the fullstop  from the example, we will only hear quote once.

## A note:
I don't know if this problem is caused by Espeak. NVDA may be sending the wrong data for Turkish to Espeak.
Repeat the same steps for English and everything seems correct.
Since I don't know how to analyze this process more deeply, I wanted to create an issue. I will close this issue with your referrals and recreate it in Espeak-NG repo.
I don't know how to repeat these steps for Espeak. I can ask these questions, but I can also listen to your thoughts and suggestions.

And if this problem is in NVDA codebase I want to submit a pr. Could you please tell me which files I can analyze?
I want to make a small improvement. I love the open source world and NVDA is a great project.

Thanks for reading the note.

### Steps to reproduce:

1. Change Punctuation/symbol level: most
2. Change Synthesizer: EspeakNG
3. Change synthesizer language: Turkish
4. Typing
"Merhaba dostum" dedi.
Or coding example:
`functionCallProduce("a string")`

5. Scroll through the text with the up and down arrows.

### Actual behavior:

In both examples, you will hear the quotation mark only 1.

So:
tırnak Merhaba dostum dedi.

Or:
functionCallProduce açparantez tırnak a string kapaparantez

### Expected behavior:
The following output should be voiced:
tırnak Merhaba dostum tırnak dedi.

Code example:
functionCallProduce açparantez tırnak a string tırnak kapaparantez

#### NVDA installed/portable/running from source:
Tested installed, portable

#### NVDA version:
2020.4

#### Windows version:
Windows 10, 64 bit
#### Does the issue still occur after restarting your computer?
	Yes
#### If add-ons are disabled, is your problem still occurring?
	yes

**Comment by seanbudd** [comment] 2021-06-17 03:04
Hi Sean,

Thanks for the thorough investigation. I believe this is a duplicate of #11779, which should be fixed by #11856. Your enthusiasm for fixing this is highly appreciated, feel free to have a review of that PR and issue. 

Cheers

**Comment by SeanTolstoyevski** [comment] 2021-06-18 09:57
Hi @seanbudd ,

I downloaded the build as you said in pr and tested it with the same configuration.
It doesn't fix what i'm talking about.

**Comment by Surveyor123** [comment] 2021-06-18 11:52
I've just Updated symbols.dic and  Committed. Will be fixed in NVDA2021.1. Thanks

**Comment by CyrilleB79** [comment] 2021-06-18 12:36
@SeanTolstoyevski and @Surveyor123, have you been able to check with the new symbol file that the issue is fixed?

If it is confirmed that this issue aws due to symbol file, this issue should be closed. Thanks.

**Comment by Surveyor123** [comment] 2021-06-18 12:47
Exactly, have tested and after editing the problematic line I can confirm it was because of local symbols file. Please close the issue.

Kimden: Cyrille ***@***.***>
Gönderilme: 18 Haziran 2021 Cuma 15:36
Kime: ***@***.***>
Bilgi: ***@***.***>; ***@***.***>
Konu: Re: [nvaccess/nvda] Punctuation / symbol level: most: Some symbols on the right is not voiced (Turkish) (#12556)


@SeanTolstoyevski<https://github.com/SeanTolstoyevski> and @Surveyor123<https://github.com/Surveyor123>, have you been able to check with the new symbol file that the issue is fixed?

If it is confirmed that this issue aws due to symbol file, this issue should be closed. Thanks.

**Comment by SeanTolstoyevski** [comment] 2021-06-18 13:39
Can you share a build with the latest commits active?
As the owner of the issue, I want to confirm this.

**Comment by CyrilleB79** [comment] 2021-06-18 20:01
As explained, translation/localization are not made in this Git repository but in another SVN repository. That's why you were asked to close this issue and to contact translators to make the modifications.

The modifications are not yet in this repo and there is no automatic build containing them. You will be able to see them when a new beta (if any) is released or in NVDA 2021.1rc1 build.

If you want to test manually without expecting these builds:
1. Create a portable version of NVDA 2021.1beta3 (if you do not have already)
2. Download [symbols.dic.txt](https://github.com/nvaccess/nvda/files/6679067/symbols.dic.txt) and rename it without the txt extension. That's the last version of the symbol file modified by @Surveyor123 
3. Go to YourPortableNVDAFolder\locale\tr
4. Paste there the file you have downloaded and renamed. You will need to accept to overwrite the existing file.
5. Start your portable copy of NVDA and test

**Closed** 2021-06-18 20:22 UTC
