### ISSUE TITLE
Aria-live "polite" not reading at all.

### ISSUE THREAD

**Issue by ChilupuriAnilReddy** [nvaccess/nvda#13994] opened 2022-08-08 05:46 UTC
### Steps to reproduce:
Go to https://codepen.io/careddy/pen/XWEYjdy Click Create Button

### Actual behavior:
Newly added element is never announced

### Expected behavior:
Should read iframe aria-label details when user is idle

#### NVDA installed/portable/running from source:
https://www.nvaccess.org/download/

#### NVDA version:
2022.2

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Firefox: 91.12.0esr (64-bit)
Chrome: 104.0.5112.91(64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by seanbudd** [comment] 2022-08-10 08:57
Closing as duplicate of #12464

**Closed by seanbudd** 2022-08-10 08:57 UTC
