### ISSUE TITLE
Chrome Sign In page inaccessible

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#5512] opened 2015-11-19 05:36 UTC
STR:
1. Open google chrome. I'm placed on the address bar.
2. Type google.com and press enter.

I hear nothing, however the title bar changes so I know the page has loaded. Tabbing says nothing, except when I select and unselect one item several tabs away.

It seems the only way to fix this is to alt+tab out, alt+tab back in again, and load another page.

Chrome version 46.0.2490.86 m on windows 8.1 X64, NVDA master.

**Comment by ObjectInSpace** [comment] 2015-11-19 06:04
Have you tried using insert+f5 to refresh the virtual buffer? I often 
find this fixes Chrome page loading issues.

**Comment by jcsteh** [comment] 2015-11-19 06:04
This doesn't seem to happen in Google Chrome Canary, which means it should be fixed in Chrome 47 when it comes out later this month. If you're willing, I'd be interested to know whether you can reproduce this with Chrome Canary.

**Comment by tspivey** [comment] 2015-11-19 06:25
I tried Canary, with the following results:

* Opening Chrome brings me to chrome://chrome-signin/?source=0, where
NVDA says unknown and I can't read the page content.
* I can press control l and go to google.com, and now it reads. So one
fewer alt+tab step.
* Going back to that page says embedded object instead of unknown, and I
can only read it with object navigation.

**Comment by jcsteh** [comment] 2015-11-19 06:30
> * Going back to that page says embedded object instead of unknown
Going back how? And to which page: the first chrome:// url or google.com?

**Comment by tspivey** [comment] 2015-11-19 06:31
Going back to chrome://chrome-signin/?source=0, by pressing control-l,
pasting that and pressing enter.

**Comment by jcsteh** [comment] 2015-11-19 06:36
Eek, yeah, that's definitely weird. They seem to be rendering the 
document inside an object tag, but we don't render objects in browse 
mode because they're usually non-browser things like Flash. I'll need to 
discuss that with Google.

**Comment by jamessetaro** [comment] 2016-02-23 22:46
Where did this one end up? Is there a corresponding chromium issue? How do most people use chrome with this kind of issue?

**Comment by jcsteh** [comment] 2016-02-23 22:56
I don't seem to get that sign-in page when I start Chrome, but even so, it needs to be fixed. I haven't filed a bug yet.

**Comment by jcsteh** [comment] 2016-02-24 02:38
I don't seem to get that sign-in page when I start Chrome, but even so, it needs to be fixed.

Filed [Chromium issue 589325](https://bugs.chromium.org/p/chromium/issues/detail?id=589325).

**Comment by jcsteh** [comment] 2016-08-24 06:30
Chromium issue 589325 is now fixed and I've verified that it works as expected.

**Closed by jcsteh** 2016-08-24 06:30 UTC
Labels: bug, GoogleWork, needsExternalFix
