### ISSUE TITLE
Windows 7: NVDA Loses Focus on Items when Alt-Tabbing Back to Windows Explorer Lists

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6881] opened 2017-02-12 17:33 UTC
Since upgrading to the latest snapshot, I've noticed that NVDA appears to be losing focus on Windows Explorer items which did not previously occur. This happens when navigating back to a focused list, at which point rather than reading the title of the active folder NVDA will simply output "icon". When activating the "read current line" command, NVDA says "blank". This only happens when Alt Tab are used together to immediately jump to the active Windows Explorer task; cycling through open windows and then releasing Alt does not produce the same result. My only guess so far is that this could possibly be related to the fix applied in #6671; has anybody else noticed this? I unfortunately don't have any Windows 10 devices that I can test.

**Comment by Brian1Gaff** [comment] 2017-02-13 09:22
Yes I thought it was me though, hitting the wrong keys. Is this in Next 
branch?
I don't see it in Master or not thus far.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment] 2017-02-13 10:52
@elliott94, is this in master or next? If next, can you please try latest
master (temporary/portable should be fine)?

Possible causes if master: #6691, #6789
Possible causes if next: both of the above plus #6834

**Comment by elliott94** [comment] 2017-02-19 11:29
Apologies for the delay.

I'm currently running Next - sorry for not previously mentioning this. Running the latest Master build does not produce the same problem - navigation is as it was before the update.

**Comment by jcsteh** [comment] 2017-02-20 06:57
Can you please try [this first build](https://ci.appveyor.com/api/buildjobs/df4rs8t8807x2lsr/artifacts/output/nvda_snapshot_next-13868,260192cf.exe) and [this second build](https://ci.appveyor.com/api/buildjobs/4qh4kpd0n62g1wnq/artifacts/output/nvda_snapshot_next-13867,d3230777.exe) and report whether the issue exists in either (or both) of these?

**Comment by elliott94** [comment] 2017-02-20 18:27
Sure - hopefully getting closer! :)

The first build produces the exact same result - however, after Alt-Tabbing around 50 times the second build appears not to include the problem. Navigation is as it should be when using this one.

**Comment by jcsteh** [comment] 2017-02-21 01:02
We weren't able to reproduce this ourselves. Do you have Aero disabled by any chance?

**Comment by jcsteh** [comment] 2017-02-21 01:12
We weren't able to reproduce this ourselves. Do you have Aero disabled by any chance?You said:

> This only happens when Alt Tab are used together to immediately jump to the active Windows Explorer task

I'm confused by the word "active" here. Do you mean you're cycling through all windows and getting back to the window you're already in? Or do you mean, for example, you open Explorer, open Notepad, then quickly press alt+tab to switch back to Explorer?

**Comment by Brian1Gaff** [comment] 2017-02-21 08:51
The only time I've seen this sort of thing is if the explorer file list is 
the one you get when you use open in a piece of software other than the 
explorer itself, ie the one you would get opening  a folder from computer 
icon.
 Also in such cases the sorting order is often reversed so my guess is that 
sometimes programs, say like Goldwave, might be using an old system of 
looking at files that gets nvda confused.
 From what I read though this is not what he is talking about.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by elliott94** [comment] 2017-02-22 17:49
I have Aero enabled - I've been able to test this on two machines with the same result.

The latter occurs - if I have Notepad enabled and I Alt-Tab to the active Explorer window, this is when "icon" is announced. It doesn't always happen though - on a slower machine, however, it seems to occur more frequently.

**Comment by jcsteh** [comment] 2017-02-23 02:01
Do you have more than one Windows keyboard layout/language installed?

**Comment by elliott94** [comment] 2017-02-23 17:08
Unfortunately not - I've just confirmed this by checking in Region and Language. Is there any info that I could grab to show this (developer info, etc)?

**Comment by jcsteh** [comment] 2017-03-18 00:53
It turns out that #6834 is no longer necessary, so I've reverted it. I don't really understand why that would cause this issue, but your feedback about the two builds I asked you to test (https://github.com/nvaccess/nvda/issues/6881#issuecomment-281150620) suggests that #6834 was the cause. As such, I'm closing this as fixed. If the problem persists in current "next" snapshots, please reopen.

**Closed by jcsteh** 2017-03-18 00:53 UTC
