### ISSUE TITLE
Focus problem while managing conversations on Skype for desktop

### ISSUE THREAD

**Issue by salihkn** [nvaccess/nvda#7234] opened 2017-05-31 08:45 UTC
### Steps to reproduce:
> 1. Open Skype
> 2. Go to conversations list by pressing Alt+2
> 3. Navigate within the conversation list.
> 4. Press delete to delete one of the conversations from the conversations list

### Expected behavior:
> Pressing delete on a conversation deletes it from the list, and the focus moves to the most recent conversation so NVDA should speak it's name.

### Actual behavior:

> NVDA speaks the second recent conversation within the conversations list, but the focus is on the very first recent after checking by pressing NVDA+Tab.

### System configuration:
NVDA version:
> 2017.2

NVDA Installed or portable: Installed

Other information:

Windows version:
> Windows 10 Version 1703

Name and version of other software in use when reproducing the issue: Skype for desktop 7.36

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA?
> NVDA 2017.1. The result is the same.

**Comment by Adriani90** [comment] 2019-04-17 22:36
I am closing this because it is related to an old skype version and it is not reproducible in Skype 8.

**Closed by Adriani90** 2019-04-17 22:36 UTC
Labels: App specific: Skype for Desktop
