### ISSUE TITLE
nvda give errors when trying to add languages in the settings app in win 10

### ISSUE THREAD

**Issue by mjonsson1986** [nvaccess/nvda#12550] opened 2021-06-15 07:09 UTC
### Steps to reproduce:
go to windows 10 settings app
time and language
and language
and try to add a language

### Actual behavior:
nvda seems to hang or something
### Expected behavior:
nvda should not hang
#### NVDA installed/portable/running from source:
installed nvda
#### NVDA version:
latest snapshot
#### Windows version:
latest windows insider preview
#### Does the issue still occur after restarting your computer?
yes

**Comment by lukaszgo1** [comment] 2021-06-15 07:20
@mjonsson1986  You were supposed to follow the issue template when reporting the issue. If you would do that one of the questions asked was 'If add-ons are disabled, is your problem still occurring?' and the answer is No since this is caused by @josephsl win 10 App Essentials. This should be closed as invalid and reported against @josephsl  repository.

**Comment by XLTechie** [comment] 2021-06-15 18:50
Try this with add-ons disabled.

Next time, please fill out the complete bug report.

CC @josephsl

**Comment by josephsl** [comment] 2021-06-15 18:53
Hi, or better yet, with add-ons enabled and disabled, please attach a debug log so we can analyze what’s going on. Thanks.

**Comment by josephsl** [comment] 2021-06-15 19:15
Hi,

Ah, it is indeed with my add-on.

Technical: through Windows 10 App Essentials add-on, NVDA can react to UIA layout invalidated event, used in auto-suggest accessibility. However, the edit field for searching display languages is not properly recognized as a search field, hence raising attribute error.

Note that this issue does not occur with Windows 10 App Essentials latest stable release (21.06). Therefore I'm going to close this issue as this has to do with dev versions of an add-on.

Thanks.

**Closed by josephsl** 2021-06-15 19:15 UTC
