### ISSUE TITLE
can not open the google apps menu in browse mode

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8500] opened 2018-07-12 12:59 UTC
### Steps to reproduce:
using Microsoft hedge.
open the google page
walk with the arrow below until the button gathered google apps.
Press enter.
### Actual behavior:
nothing happens.
### Expected behavior:
the google apps button is expanded and by walking with the arrows below you can read and open the submenus with enter.
When walking with ctrl + right and left arrows you can not read the word button collapsed google apps.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
alfa 15495
#### Windows version:
10 17.134.165
#### Name and version of other software in use when reproducing the issue:
microsoft hedge
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2020-05-09 11:09
This works as expected with NVDA 2020.1 and Edge Chromium 81. Closing as works for me and adding edge spartan label since it might be reproducible in the old Edge. However, Edge Chromium will be distributed to most users via Windows 10 2004 update.

**Closed by Adriani90** 2020-05-09 11:09 UTC
Labels: app/edge, app/edge/spartan, close/worksforme
