### ISSUE TITLE
What's New (changes.html): Add Release Date for Old and Future NVDA Releases

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10013] opened 2019-08-01 17:05 UTC
When looking at changelogs for software (and NVDA being a really good example), I find it really useful and interesting to see the release date for a particular version of a piece of software that gets released; for NVDA, it's particularly amazing to see how many features have been added over the years.

For the "What's New" file, could we consider adding this for older NVDA releases, and including this piece of information into future revisions to the file? I'm more than happy to go through and collect these for older releases if somebody would be happy to push a commit for me.

**Comment by DrSooom** [comment] 2019-08-01 18:06
@elliott94: Do you want to change files in older NVDA versions and re-release them? Personally I'm against this because it is much easier to upload the localized "changes.html" files onto the NV Access website as well. The English "changes.html" files are already there, e.g. [here](https://www.nvaccess.org/files/nvda/releases/2019.1.1/nvda_2019.1.1_changes.html).

@Qchristensen: I already suggested [here](https://github.com/nvaccess/nvda/issues/8884#issuecomment-433474183) in the past to add a .htaccess file with the following content in the folder for https://www.nvaccess.org/files/nvda/releases/
> Options +Indexes

**Comment by XLTechie** [comment] 2019-08-01 18:10
For what it's worth, I have also been known to find such dates useful for 
certain projects. It can be a quick way to track down when certain changes 
happened, if you don't know enough about the internals of the feature or bug to 
find it through git or whatever.

Only in future versions of the file, of course.

**Comment by elliott94** [comment] 2019-08-01 18:43
No - my suggestion is to include this in future revisions, but also to include a release date for previously-released builds. To make this have as little impact on translation as possible, I think we have two options:

1. Put the release date in brackets after the version number - for example: 2019.1 (2019-01-01)

2. As above, but put the word "released" before the date - for example: 2019.1 (released 2019-01-01)

This way, translations need only include the word "released" to translate the string.

**Comment by DrSooom** [comment] 2019-08-01 18:44
If you want to add the release date of a stable version directly after the NVDA version, then that is something which the devs should keep an eye on it, as the framework for creating this file could get be changed due to Python 3. Furthermore the file "changes.html" already contains all changes from version 0.5 to 2019.1.1.

**Comment by DrSooom** [comment] 2019-08-01 18:58
Yes, the date format YYYY-MM-DD should be used. Sadly it sounds a little bit strange depending on the language, if we add "released" as well). [This here](https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.t2t) is the original file, which has to be changed.

**Comment by XLTechie** [comment] 2019-08-01 19:13
I'm not sure what value the word "released" would serve in that context: there's 
nothing else the parenthetical date could represent.

**Comment by elliott94** [comment] 2019-08-01 20:08
> 
> 
> Yes, the date format YYYY-MM-DD should be used. Sadly it sounds a little bit strange depending on the language, if we add "released" as well. [This here](https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.t2t) is the original file, which has to be changed.

Thank you for this. :)



> 
> I'm not sure what value the word "released" would serve in that context: there's nothing else the parenthetical date could represent.

You're right.

If I go ahead and collect this info, would somebody be willing to push this - or do people not think that it's worthwhile?

**Comment by Andre9642** [comment] 2019-08-01 20:30
```
$ git for-each-ref --sort=taggerdate --format "- %(tag): %(taggerdate:short)" refs/tags|grep -vE "(rc|beta)"|grep release|tac|sed 's/release-//g'
- 2019.1.1: 2019-04-10
- 2019.1: 2019-03-26
- 2018.4.1: 2019-01-14
- 2018.4: 2018-12-17
- 2018.3.2: 2018-09-26
- 2018.3.1: 2018-09-20
- 2018.3: 2018-09-18
- 2018.2.1: 2018-07-07
- 2018.2: 2018-06-13
- 2018.1.1: 2018-03-28
- 2018.1: 2018-03-08
- 2017.4: 2017-12-06
- 2017.3: 2017-08-24
- 2017.2: 2017-05-29
- 2017.1: 2017-02-22
- 2016.4: 2016-12-16
- 2016.3: 2016-09-06
- 2016.2.1: 2016-06-10
- 2016.2: 2016-06-02
- 2016.1: 2016-02-22
- 2015.4: 2015-11-23
- 2015.3: 2015-08-25
- 2015.2: 2015-06-15
- 2015.1: 2015-02-23
- 2014.4: 2014-11-27
- 2014.3: 2014-09-04
- 2014.2: 2014-05-22
- 2014.1: 2014-03-13
- 2013.3: 2013-12-04
- 2013.2: 2013-08-29
- 2013.1.1: 2013-06-24
- 2013.1: 2013-05-18
```

**Comment by Andre9642** [comment] 2019-08-01 20:49
And we can retrieve the rest of release & date with `git log --tags --simplify-by-decoration --pretty="format:%D %ai"|grep -i release|grep -vE "(beta|rc)"`:

- 2012.3.1: 2012-12-13
- 2012.3: 2012-11-08
- 2012.2.1: 2012-06-13
- 2012.2: 2012-06-08
- 2012.1: 2012-03-21
- 2011.3: 2011-11-25
- 2011.2: 2011-08-05
- 2011.1.1: 2011-04-07
- 2011.1: 2011-03-07
- 2010.2: 2010-10-28
- 2010.1: 2010-03-29
- 2009.1: 2009-11-24
- 0.6p3.2: 2009-03-13
- 0.6p3.1: 2009-02-20
- 0.6p3: 2009-02-14
- 0.6p2: 2008-08-07
- 0.6p1: 2008-03-11
- 0.5.next: 2008-01-13
- 0.5: 2007-05-25

**Comment by elliott94** [comment] 2019-08-02 20:51
@Andre9642 Thank you - that makes things much easier and saves lots of manual searching! :)

Would somebody mind pushing this if we think as a majority that this would be useful info to have?

**Comment by feerrenrut** [comment] 2019-08-05 11:34
I'd like to push back on this slightly, what makes this information useful? What does this tell you that our current version scheme does not tell you?

**Comment by elliott94** [comment] 2019-08-05 11:39
> 
> 
> I'd like to push back on this slightly, what makes this information useful? What does this tell you that our current version scheme does not tell you?

Absolutely nothing. :)

My main suggestion for adding this for both previous and future releases was for historical purposes - on a personal note, when looking back at changelogs for old releases of software, it's simply a useful reference point. It makes perfect sense if you'd prefer to not add this info due to maintaining - I just thought it would be a nice thing to add to see how far NVDA has come throughout the years, and for people who may not be as familiar with the project a release date may provide clarity on that.

**Comment by Adriani90** [comment] 2019-08-16 18:27
@elliott94 here is already a website where you can see all the release dates for NVDA:
https://www.filehorse.com/download-nvda/old-versions/

In my opinion, someone interested in this information could ask for it on the NVDA users mail list. I don't see a necessity to have this included in the change log but if you would like to do this work, I am happy to show you how to raise a pull request for this.
But note that every time when a release is out someone must maintain the dates in the change log. Or maybe this is possible with an automatic script to extract the release date from Github and place it in the change log automatically?

**Comment by DrSooom** [comment] 2019-08-17 10:52
Linking to a Third-Party-Website is no solution – because you can't trust it – and it isn't also the point here.

> In my opinion, someone interested in this information could ask for it on the NVDA users mail list.

Why? Why the mailing list? Why does someone have to offer his e-mail address first and then have to wait for an answer? Sorry, that's non-sense, because the timestamps are visible in the Installers, if you open them with 7-Zip. But I don't know how many non-advanced users know this.

> But note that every time when a release is out someone must maintain the dates in the change log.

I already thought about that. But I have to correct you – only the latest release date is affected. Furthermore I have to note that txt2tags could be replaced with another solution for creating these kinds of files due to Python 3. Therefore I suggest to write "2019Q4" for the upcoming NVDA 2019.3. All previous release dates are firm, thus they can be added as static data. Sadly I haven't the time to do that right now, but it's really easy to extent that single t2t file.

**Comment by lukaszgo1** [comment] 2019-08-17 10:53
The question is why add it in the first place? There is no benefit and an extra work for someone.

**Comment by DrSooom** [comment] 2019-08-17 11:01
As there are just a handful releases a year, I wouldn't see that such critical.

**Comment by Adriani90** [comment] 2019-08-17 15:19
> Linking to a Third-Party-Website is no solution – because you can't trust it – and it isn't also the point here.

The scope of this issue was that this information should be accessible anywhere and a suggestion was to include it in the changelog. The website I have linked here is trustworthy although it is a third party website.

> I already thought about that. But I have to correct you – only the latest release date is affected.

Why that? There were lots of deviations from the planed cycle in the past, even with more than four versions a year.

> Furthermore I have to note that txt2tags could be replaced with another solution for creating these kinds of files due to Python 3.

This was investigated very thoroughly on another issue. The problem is that txt2tags is very powerful in its ability of understanding and dealing with bash scripts. And our whole translation system works based on such scripts. It is not as easy as to just change the markdown.

> I suggest to write "2019Q4" for the upcoming NVDA 2019.3.

And what if 2019.4 comes out in december?

**Comment by Adriani90** [comment] 2019-08-17 15:23
> All previous release dates are firm, thus they can be added as static data.

Well, in my opinion, if implemented, at least this should be rather done by an automatic script to avoid missing maintenance in the future. Because if noone maintains it afterwards, after some years someone will open a new issue complaining that there are inconsistencies in the changelog.

**Comment by DrSooom** [comment] 2019-08-18 07:30
To be fully correct, the latest two dates have to be changed manually directly after a release – changing the release date of the recently released version from "2019Qx" to "2019-MM-DD" and adding the quarter "2019Qx" to the upcoming release. But I agree that adding the release dates automatically might be a better solution. The foolish point here is that the localized changelog files are part of the Installer/software.

>> I suggest to write "2019Q4" for the upcoming NVDA 2019.3.
> And what if 2019.4 comes out in december?

2019Q4 means October, November and December. I can't see a problem here. But the quarter date value solution is only for manual editing.

See: https://de.wikipedia.org/wiki/Quartal#Quartale_und_ihre_Monate or https://en.wikipedia.org/wiki/Calendar_year#Quarters

**Comment by Adriani90** [comment] 2019-08-18 08:22
However, NVDA is in a structured versioning cycle which has already been changed some months ago and has been promoted on al possible official channels. I would not change it again because this will cause inconsistencies and people would raise again many questions on what's behind it etc.

**Comment by Adriani90** [comment] 2019-08-18 08:23
Thus, even when editing it manually, I would still preserve the current numbering and add a date behind it (2019.3+date, 2019.4+date etc.).

**Comment by DrSooom** [comment] 2019-08-18 08:47
Sorry, I have no idea what you wanted to explain me. I only think that this year due to the Python 3 migration, releasing a 2019.4 version couldn't be the case. Well, we will see how long it will take to release 2019.3.

**Comment by feerrenrut** [comment] 2019-10-03 11:17
I don't release dates belong in the changes file.

From the [comment from @elliott94](https://github.com/nvaccess/nvda/issues/10013#issuecomment-518199586) 
> when looking back at changelogs for old releases of software, it's simply a useful reference point.

I think enough granularity can be achieved by the current version string. It already tells you the year, and which release within that year. This is enough to order the releases, and have an approximate idea of when they happened. For more accuracy there are other sources. Adding timestamps the changes file is just more maintenance, another thing to remember at release time, and clutters the change log.

Being pedantic about it, there is also a question of which timestamp actually constitutes the time of a release, there are several possible different timestamps:
- When the tag is created
- When the build for that tag is finished
- When the binary actually lands on the server
- When NV Access makes the announcement of the release.

These times are likely to be all within 24 hours, but not necessarily the same day depending on your timezone. They are all already publicly available in official locations. Most useful in my opinion are:
- The announcement of a release timestamp [for each release post.](https://www.nvaccess.org/category/news/releases/)
- The creation time of the release tag,[ listed on github](https://github.com/nvaccess/nvda/releases)

I'm going to close this issue, since I think it has served it's purpose.

**Closed by feerrenrut** 2019-10-03 11:17 UTC
