### ISSUE TITLE
nvda not read several items in the menu insert in word

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8447] opened 2018-06-27 00:19 UTC
### Steps to reproduce:
open the word.
press alt to open the menu bar.
press right arrow until the insert tab.
press enter on the insert tab
Walk tabbed by guide.
Note that several items nvda is mute.
as an example, nvda does not advertise the box to insert a new table.
### Actual behavior:
when navigating with tab and nvda is muted in several items that gain focus
### Expected behavior:
nvda should advertise all items that gain focus with tabe.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
next 15363
#### Windows version:
10 17.134.112
#### Name and version of other software in use when reproducing the issue:
word 16.0.9330.2124
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by fernando-jose-silva** [comment] 2018-06-27 00:42
IO - inputCore.InputManager.executeGesture (21:41:58.914):
Input: kb(laptop):tab
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:41:58.944):
oleacc.AccessibleObjectFromEvent with window 1051068, objectID 14 and childID 0: [Error -2147467259] Erro não especificado
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (21:41:58.944):
oleacc.AccessibleObjectFromEvent with window 1051068, objectID 13 and childID 0: [Error -2147467259] Erro não especificado
IO - inputCore.InputManager.executeGesture (21:42:01.604):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - watchdog._watcher (21:42:02.654):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 489, in main
  File "wx\core.pyc", line 2096, in MainLoop
  File "gui\__init__.pyc", line 959, in Notify
  File "core.pyc", line 461, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "scriptHandler.pyc", line 145, in _queueScriptCallback
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 1438, in script_navigatorObject_devInfo
  File "logging\__init__.pyc", line 1174, in info
  File "logHandler.pyc", line 140, in _log

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (21:42:02.723):
Developer info for navigator object:
name: u'Quebra de P\xe1gina'
role: ROLE_BUTTON
states: STATE_FOCUSABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.IAccessible.Button object at 0x0E7E2410>
Python class mro: (<class 'NVDAObjects.IAccessible.Button'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: RectLTWH(left=4, top=137, width=151, height=27)
value: None
appModule: <'winword' (appName u'winword', process ID 2480) at address e7bae70>
appModule.productName: u'Microsoft Office 2016'
appModule.productVersion: u'16.0.9330.2124'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 1051068
windowClassName: u'NetUIHWND'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 6112
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0xba908d0 at e7bce90>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1051068, objectID=100729460, childID=0
IAccessible accName: u'Quebra de P\xe1gina'
IAccessible accRole: ROLE_SYSTEM_PUSHBUTTON
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by Adriani90** [comment] 2018-06-27 18:58
I cannot reproduce this with last next and MS Word (16.0.10228.20080)

1. I opened Word
2. I pressed alt
3. I pressed right arrow until I heared "insert"
4. I pressed tab multiple times

Everything is read properly, also the table group.

The only thing is that NVDA reports everytime the label of the settings group and after that it reports the element of that group.

**Comment by fernando-jose-silva** [comment] 2018-06-27 22:17
I updated the office and now I am in the version
16.0.10228.20080
and I continue with the problem.
If it makes a difference, I have office 64bit.

**Comment by Adriani90** [comment] 2019-05-08 16:26
@fernando-jose-silva could you please test with all addons disabled? Is the issue still occuring?

**Comment by fernando-jose-silva** [comment] 2019-05-08 22:29
I managed to solve the problem, I used microsoft software to erase all the word settings and start the software from the beginning.
That is to say it was some configuration in the word that caused it, which configuration I do not know.

**Comment by fernando-jose-silva** [comment] 2019-05-08 22:38
I managed to solve the problem, I used microsoft software to erase all the word settings and start the software from the beginning.
That is to say it was some configuration in the word that caused it, which configuration I do not know.

**Comment by ehollig** [comment] 2019-05-09 03:04
Closing. Thank you for replying @fernando-jose-silva

**Closed by ehollig** 2019-05-09 03:04 UTC
