### ISSUE TITLE
microsoft edge freezing on undead-assault.com with nvda

### ISSUE THREAD

**Issue by mayson199514** [nvaccess/nvda#11375] opened 2020-07-14 12:01 UTC
Microsoft edge based on chromium keeps freezing with nvda when going to undead-assault.com's download page to download the game.
[nvda.log](https://github.com/nvaccess/nvda/files/4924462/nvda.log)

### windows os version, windows 10 version 20h2 beta build 19042.338

**Comment by Brian1Gaff** [comment] 2020-07-14 15:51
Have you got a link that will work to the page?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by mayson199514** [comment] 2020-07-14 20:32
Hello, I should have clarified, this is with the new Microsoft edge based of Chromium. and now hear is the link to the direct page: http://undead-assault.com/download

**Comment by mayson199514** [comment] 2020-07-14 20:36
Okay so I just tried it out chromium edge does not freeze Nvda if you go directly to it, but if you navigate to it from the home page by hitting that menu button to expand the menu, then navigate to the download link, that is will crash nvda.

**Comment by JulienCochuyt** [comment] 2020-07-15 06:00
@mayson199514, could you please try to post a log of the crash?
The file can usually be found at `%TEMP%\nvda.log`
The most informative log for us can be obtained by setting debug log level, disabling all add-ons, restarting NVDA, and then go straight ahead to reproducing the issue with as few steps as possible.

By the way, please note the "Bug report" issue template you chose not to fill also provides us with useful information in nailing down the exact circumstances of your issue. Please take the time to answer these questions:

> Please thoroughly read NVDA's wiki article on how to fill in this template, including how to provide the required files.
Issues may be closed if the required information is not present.
https://github.com/nvaccess/nvda/wiki/Github-issue-template-explanation-and-examples


### Steps to reproduce:

### Actual behavior:

### Expected behavior:

### System configuration
#### NVDA installed/portable/running from source:

#### NVDA version:

#### Windows version:

#### Name and version of other software in use when reproducing the issue:

#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your computer?

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

#### If addons are disabled, is your problem still occuring?

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

**Comment by mayson199514** [comment] 2020-07-15 13:19
Hello I just redead the issue and attached the log file. let me know if this is ok!

**Comment by mayson199514** [comment] 2020-07-15 18:24
Hopefully the issue looks propper now.

**Comment by Adriani90** [comment] 2020-07-15 19:11
I can reprotuce this issue with the last alpha and the newest Edge Chromium stable version. Here is the most important part of the log:

```
IO - speech.speak (21:07:37.954) - MainThread (8108):
Speaking ['Menü-Eintrag', 'besucht', 'Link', 'Download']
IO - inputCore.InputManager.executeGesture (21:07:39.073) - winInputHook (708):
Input: kb(laptop):enter
IO - inputCore.logTimeSinceInput (21:07:39.135) - MainThread (8108):
0.062 sec since input
IO - speech.speak (21:07:39.136) - MainThread (8108):
Speaking ['Seite wird geladen…']
DEBUG - treeInterceptorHandler.killTreeInterceptor (21:07:39.473) - MainThread (8108):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x00AAEC10>
IO - inputCore.InputManager.executeGesture (21:07:42.582) - winInputHook (708):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:07:44.682) - winInputHook (708):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:07:46.082) - winInputHook (708):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (21:07:46.332) - winInputHook (708):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (21:07:46.492) - winInputHook (708):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (21:07:46.742) - winInputHook (708):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (21:07:47.592) - winInputHook (708):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (21:07:48.222) - winInputHook (708):
Input: kb(laptop):ö
DEBUGWARNING - watchdog._watcher (21:07:49.752) - watchdog (508):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1049, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 64, in _queueEventCallback
  File "eventHandler.pyc", line 214, in executeEvent
  File "eventHandler.pyc", line 94, in __init__
  File "eventHandler.pyc", line 102, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\UIA\__init__.pyc", line 1053, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1105, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 991, in reportFocus
  File "speech\__init__.pyc", line 478, in speakObject
  File "speech\__init__.pyc", line 548, in getObjectSpeech
  File "speech\types.pyc", line 50, in _flattenNestedSequences
  File "speech\types.pyc", line 50, in <genexpr>
  File "speech\__init__.pyc", line 1127, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 96 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 594, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 418, in _getControlFieldForObject
  File "baseObject.pyc", line 41, in __get__
  File "baseObject.pyc", line 144, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1247, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 811, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
```

**Comment by Adriani90** [comment] 2020-07-15 19:13
@mayson199514 could you please test this with NVDA 2020.1 stable version? Is the issue still occuring there?

**Comment by mayson199514** [comment] 2020-07-15 19:25
Hello, just tested it with stable, and issue still happens their as well.

**Comment by mayson199514** [comment] 2020-07-17 11:23
I think this ticket can be closed, it looks lke the problem was fixed on microsofts end! I tried the site again with both stable nvda and the alpha, and the latest update to microsoft edge, version 84 no longer freezes on that site.

**Comment by Adriani90** [comment] 2020-07-17 19:40
Yes, It seems it has been fixed in MS Edge 84. Closing as works for me.

**Closed by Adriani90** 2020-07-17 19:40 UTC
Labels: close/worksforme
