### ISSUE TITLE
Announcement of content of role=status

### ISSUE THREAD

**Issue by ehollig** [nvaccess/nvda#10010] opened 2019-07-31 22:20 UTC
### Steps to reproduce:
I think this may have to do with how NVDA handles role=status
1. Open the attached index file [located here](https://github.com/nvaccess/nvda/files/3454115/NVDAIssue.zip).
2. Press enter on the button.
3. Observe that information is presented to NVDA but is not automatically announced.

### Actual behavior:
After the button is pressed, the message of "This is a new fake sentence" is announced after 3 seconds.

### Expected behavior:
The message, "Loading another sentence " should be announced and then the message, "This is a new fake sentence".

#### NVDA version and NVDA installed/portable/running from source:
NVDA 2019.2 RC 1

#### Windows version:
Windows 10 version 1809

#### Name and version of other software in use when reproducing the issue:
Firefox and Chrome, latest versions

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment] 2019-07-31 22:37
Is the button itself not already sugerating that a new sentence will be loaded once it is pressed? I mean the infornation „loading a new sentence„ is obsolete if I already know the acion of the button. I might be wrong, but in my view it is like if you have a button with the label „cancel“ and nvda says „canceling“ when it is pressed although the usetr already knows from the label which action will happen after pressing it.

**Comment by XLTechie** [comment] 2019-08-08 02:48
I completely disagree that this is irrelevant/redundant/obsolete information 
that doesn't need to be spoken.

The point, to me, is that if a sighted user can see the redundant information, 
then we should be able to hear it/read it in braille.

It shouldn't matter whether it is redundant. That is a user experience issue of 
the site in question, not something NVDA should interfere with for our 
supposed convenience. Because who knows when the situation will not be as in the 
example, and the redundant information won't be redundant?

Plus, in your cancel, then canceling example: that information is not actually 
redundant, and the information is not obsolete. It tells me that something is 
happening. That something is in the act of being canceled, and I don't need to 
press the button again, because it worked. It also tells me that I should be 
expecting a cancellation result in the very near future. If I don't get such a 
result, I know that something went wrong in the process behind the button, but 
that the button itself did actually work.

**Comment by Adriani90** [comment] 2019-08-08 07:20
If a sighted Person can see it, then I agree with you. However, if it is just a matter of some mili seconds, even most sighted Persons would not notice it. If the Action takes longer (i.e. more than 5 seconds) then I agree with you.

**Comment by XLTechie** [comment] 2019-08-09 02:09
Adriani90 wrote:

> If a sighted Person can see it, then I agree with you. However, if it is just a matter of some mili seconds, even most sighted Persons would not notice it.
> If the Action takes longer (i.e. more than 5 seconds) then I agree with you.

Can we know that ahead of time? I don't think it is common to do that for 
fractions of a second intentionally.

**Comment by ehollig** [comment] 2019-08-14 03:32
@Adriani90 the information provided in the example is just test data. The content could be whatever you would like. This issue is around how NVDA handles the announcement of new content with role=status, and the lack of an announcement of a screen reader only class that has display:none changed to display:block with javascript

**Comment by kangka29** [comment] 2020-03-12 10:09
are we expecting any fix to this issue?

**Comment by feerrenrut** [comment] 2020-03-12 10:49
I just had a look at the sample, and while `role=status` is not something I am very familiar with, the sample seems to be at fault. The `div` with `role=status` is initially hidden, compare that to the other live region which has a wrapper. I don't think that the status div should come in and out of existence, only it's content is reported. Instead, changing the HTML for the example to the following and it works (I guess as intended?):

```
  <div id="spinnerWrapper" role="status">
    <div id="spinner" class="spinner" style="display:none;">
      <span class="sr-only">Loading another sentence</span>
      <svg class="svg spinner-animation" aria-hidden="true" role="img"></svg>
    </div>
  </div>
```

Background on `role=status`:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_status_role
- https://www.w3.org/TR/wai-aria-1.1/#status

**Comment by leonardder** [comment] 2020-03-12 10:49
I'm not sure whether this is a bug. The status role implies a live region, and NVDA only announces stuff that's added to the region, not what's in it already. That is, the contents of the region isn't announced when display: none is removed. If you change the role to alert, you will notice that announcement works. Alternatively, you need to push the status message to the region after changing the state of the region to being displayed.

**Comment by kangka29** [comment] 2020-03-12 11:11
@feerrenrut @leonardder - I have a similar use case where the issue is reproduced, please refer to the below link:

https://developer.microsoft.com/en-us/fabric#/controls/web/messagebar

Repro steps:
1) Visit the above link.
2) Select any one of the radio buttons in the 'Usage' section.

A box will appear whose container is having role=status.

Expected result:
NVDA should read contents of the box.

Actual result:
NVDA doesn't read the contents.

Kindly let me know if the expectation is correct or some changes should be made to the HTML structure.

**Comment by feerrenrut** [comment] 2020-03-12 11:46
@kangka29 This looks like a sample from Microsoft? I'd prefer a minimal example that highlights what you believe is a bug in NVDA. 

I just tested this page with Firefox and NVDA 2019.3 and the status was read. Please open a new issue with your specific details (browser, NVDA versions you have tested). A minimal sample is highly appreciated, and will likely result in your issue being looked at sooner.

I'm going to close this issue for now. @ehollig please comment if I have missed something here and I will re-open the issue.

**Closed by feerrenrut** 2020-03-12 11:46 UTC
Labels: ARIA

**Comment by kangka29** [comment] 2020-03-12 12:20
@feerrenrut 
**NVDA version** - 2019.3.1
**Browsers** - 
Microsoft Edge 44.18362.449.0
Edge Version 81.0.416.28 (Official build) beta (64-bit)

The issue that I was facing is specific to the above example.

I will get back to you with more details and a new issue if required.
