### ISSUE TITLE
Support reading news on windows 10 news app

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5700] opened 2016-01-22 18:39 UTC
Good afternoon dear.
 I would suggest NVDA there is some way to read news on windows 10 news app.
 What happens that is possible within the windows of the news app choose the news, but after choosing the news to be read and open it to enter, you can not read the News Open.
 I could hardly read the news moving the mouse to the NVDA read the cursor stado editing, and positioning the focus to shift + NVDA + n, and press NVDA + a.
 It would be very interesting that after opening the news with enter, it was possible to read the news opened with a command, or that it was possible to focus on the news and read it quickly.

**Comment by leonardder** [comment] 2017-07-17 17:37
@JosephSL, do you know the current state of the news app? Thanks.

**Comment by josephsl** [comment] 2017-07-17 17:43
Hi, at least one can use object navigation to read articles. Thanks.

**Comment by fernando-jose-silva** [comment] 2017-07-17 21:17
Sorry, I tried to navigate objects to read the articles and I could not read the news.
I opened the news app on windows 10 15063.483, pressed tabe to the list of news, chose the arrows to read, pressed enter, then pressed nvda + page down until the object exploration, and tried to navigate objects with Nvda + shift + left and right arrows, and the nvda only repeated the open news link.

**Comment by Adriani90** [comment] 2019-02-12 13:19
@fernando-jose-silva are there any improvements in this regard? Could you test with last versions of the ap and NVDA? Thanks.

**Comment by fernando-jose-silva** [comment] 2019-02-12 19:46
I now using a machine with nvda 2018.4.1 and windows 10 1803 I was able to read the news, but in a little intuitive way in my opinion.
When opening the news it is necessary to make navigation by objects to read block by block of news.
If possible some more intuitive way to read the news would help users with less practice.
Thank you very much.

**Comment by Adriani90** [comment] 2019-02-12 22:57
I guess object navigation will remain the navigation method in Windows 10 apps, especially because Microsoft also introduced scan mode in Narator to make this easier for users. Maybe object navigation will be improved accordingly. I let this issue open for further suggestions.

**Comment by Adriani90** [comment] 2023-05-04 23:34
@fernando-jose-silva I have noticed significant improvements when using the news app now in Windows 10 or 11. Can you still reproduce this issue with NVDA last alpha? Or how is the behavior now for you?

**Comment by fernando-jose-silva** [comment] 2023-05-05 02:25
Perfect, now I can use the app without feeling it.
I think we can close the question.

**Comment by Adriani90** [comment] 2023-05-05 06:53
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2023-05-05 06:53 UTC
Labels: close/worksforme, p4
