### ISSUE TITLE
Regression in announcing required attribute for a select dropdown

### ISSUE THREAD

**Issue by narayanpai** [nvaccess/nvda#14876] opened 2023-04-26 21:31 UTC
### Steps to reproduce:
Go to any page with a select/dropdown which has been marked as required using html5 `required` attribute.

```html
<select required="true">
  <option value="1">Option 1</option>
  <option value="2">Option 2</option>
</select>
```

### Actual behavior:
NVDA not announcing the select input as required based upon `required` html attribute on latest version of NVDA 2023.1

### Expected behavior:
NVDA needs to announce it select/dropdown as required input. It works fine in NVDA 2022.2

#### NVDA version:
2023.1

#### Windows version:
OS: Windows 11 Pro, Version 22H2(OS build: 22621.1265), MAC-13.2.1

**Comment by CyrilleB79** [comment] 2023-04-27 06:28
Hello @narayanpai 

With Chrome 112, I cannot reproduce: I can hear "combo box  collapsed  required    Option 1" when reading the line in browse mode (NVDA+upArrow) and "combo box  Option 1  collapsed  required" when focusing the combobox in focus mode (shift+tab / tab).

Please fill all the fields of the template so that we can understand better your situation. More specifically, the following fields would be useful:
* Name and version of other software in use when reproducing the issue: (for your browser)
* Does the issue still occur after restarting your computer?
* Have you tried any other versions of NVDA? If so, please report their behaviors. (since you speak of regression)
* If NVDA add-ons are disabled, is your problem still occurring?

**Comment by Adriani90** [comment] 2024-01-31 13:26
The issue description template is not filled completely and it seems this issue is not reproducible. i am closing as works for me. if you are still having this issue, please provide the requested info above and we can reopen.

**Closed by Adriani90** 2024-01-31 13:26 UTC
Labels: close/worksforme, blocked/needs-info, needs-triage
