### ISSUE TITLE
MS Teams: [Meeting]: Unable to navigate to the preview screens in the share panel using up/down keys

### ISSUE THREAD

**Issue by HarishTerala** [nvaccess/nvda#10506] opened 2019-11-19 10:59 UTC
### Steps to reproduce:
1. Open MS Teams.
2. Join a scheduled meeting and enable browse mode.
3. Open share panel and press Tab key to navigate to preview screen under "Windows" section.
4. Press down arrow key on 1st preview screen in "Windows" section and verify the NVDA behavior.

### Actual behavior:
User is not able to navigate to list items in the "Windows" section using arrow keys.

### Expected behavior:
User should be able to navigate to list items in the "Windows" section using arrow keys.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
Win10 1903

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by ehollig** [comment] 2019-11-19 17:13
Have you tried navigating the list in focus mode? Some things in MS Teams do not work properly in browse mode

**Comment by HarishTerala** [comment] 2019-11-20 03:59
@ehollig - In focus mode NVDA is working fine, but the issue is in browse mode.

**Comment by Adriani90** [comment] 2023-03-04 23:45
@HarishTerala I think the list you are talking about is a list box, and not a HTML list like an unordered list or so. NVDA renders list boxes like in browsers. To choose a list item, you have to switch to focus mode. In browse mode you will see only the selected item.

This is expected behavioir.

I am closing this issue as works for me.

**Closed by Adriani90** 2023-03-04 23:45 UTC
Labels: close/worksforme
