### ISSUE TITLE
NVDA does not speak email contact autocompletion options in outlook 2016 and NVDA 2018.1

### ISSUE THREAD

**Issue by mcsedmak** [nvaccess/nvda#8244] opened 2018-05-07 19:19 UTC
### Steps to reproduce:
Open 2016 MSO (16.0.9226.2114) 32-bit
Hit control-n to create a new email
start typing in the To: field the name or address of someone that should auto-complete 
Press the down arrow to attempt to cycle through the list of autocompletion suggestions

### Expected behavior:
You should be able to down arrow through the list of autocompletion suggestions.

### Actual behavior:
No output from NVDA
### System configuration:

NVDA version:
2018.1

NVDA Installed or portable:
installed

Other information:

Windows version:
Windows 7 SP1 Win7x64_08-08-14

Name and version of other software in use when reproducing the issue:
Microsoft Outlook 2016 MSO (16.0.9226.2114) 32-bit

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by leonardder** [comment] 2018-05-08 15:07
cc @bramd

**Comment by Novalis7747** [comment] 2018-05-10 13:08
confirmed, this applies to the TO, CC and BCC field, same with NVDA 2017.4

**Comment by Novalis7747** [comment] 2018-06-20 16:44
I looked in the code and fixed it for Outlook 2016 at least:
class AutoCompleteListItem(IAccessible):

	def event_stateChange(self):
		states=self.states
		focus=api.getFocusObject()
		if (focus.role==controlTypes.ROLE_EDITABLETEXT or focus.role==controlTypes.ROLE_BUTTON) and controlTypes.STATE_SELECTED in states and controlTypes.STATE_INVISIBLE not in states and controlTypes.STATE_UNAVAILABLE not in states and controlTypes.STATE_OFFSCREEN not in states:
			address = self.name
			if address:
				speech.cancelSpeech()
				ui.message(self.name)


Basicly I just filtered out the saying of blank when arrowing down in the suggestions. before a blank fired and after that the cancel speach. That's why we never heard the email suggestions. Now it works

**Comment by ehollig** [comment] 2018-06-20 17:38
@Novalis7747, do you plan on opening a PR for this change?

**Comment by josephsl** [comment] 2018-06-20 18:31
Hi,

The fix does not fix the problem. When I apply suggested edits, I hear suggestions announced multiple times. Ideally, whenever users enter email addresses, auto-complete should kick in, and it doesn't work in recent Office 365 builds, which is just as important as hearing blanks when moving through suggestions.

Thanks.

**Comment by Adriani90** [comment] 2018-06-20 18:40
I think this is related to the accessibility API. The same problem is when opening start menu in Windows 10. When typing something, suggestions are announced multiple times. However, for me as an user is more important to hear the suggestion rather than blank.

**Comment by Adriani90** [comment] 2018-06-20 18:41
notice that in Outlook 2010 forexample it works perfectly.

**Comment by josephsl** [comment] 2018-06-20 18:42
Hi, ah yes, regarding Windows 10 Start menu problem, I believe we have an issue regarding this problem. I’ll dig into this today. Thanks.

**Comment by Adriani90** [comment] 2018-06-20 18:45
You're welcome. Maybe it is the same problem in Outlook 365.

**Comment by Adriani90** [comment] 2018-06-20 18:48
@josephsl, note that suggestions are only bein announced multiple times, when there are more results begining with the same letter or the same word. If there is a clear result for a suggestion, then the suggestion is not being announced multiple times.

**Comment by Adriani90** [comment] 2018-06-20 18:52
I don't really know if this is a bug. Ideally NVDA should announce the first suggestion and then should report how many additional suggestions have been found. (for example network seetings, three additional suggestions).

**Comment by josephsl** [comment] 2018-06-20 18:52
Hi,

Regarding Start menu problem, this will happen if you type things really fast.

Suppressing multiple suggestion announcements actually has a bad side effect: if you type part of something, and it happens that you type a letter that completes the search term and the top suggestion remains the same, NVDA won't announce the fact that suggestion remains the same. To me, this is the desired behavior: the top suggestion is the same, so folks can just press Enter, whereas if it is suppressed, folks won't know what they'll meet next.

As far as this issue goes, there might be a reason why speech.cancelSpeech will be called. I advise holding off on PR for this until we get a definitive word that speech.cancelSpeech should be called no more in Outlook's auto-complete suggestions item. Without this check, and if this PR is approved and incubated, other users may raise a complaint regarding broken functionality in other parts of Outlook.

Thanks.

**Comment by Adriani90** [comment] 2018-06-20 18:54
I agree.

**Comment by josephsl** [comment] 2018-06-20 18:55
Hi, it does announce how many items are suggested if report object position info is turned on, both in Core and my add-on. Thanks.

**Comment by Adriani90** [comment] 2018-06-20 18:59
oh sorry. My speech rate was to high and I didn't notice it. Ok forget my last comment. *lol*

**Comment by Novalis7747** [comment] 2018-06-20 19:02
I tested that in Office 365 on 3 machines and for me I don't hear any sugestion, just blank. But when looking in debug log of NVDA I can see that the suggestion was sent. The cancel speech killed it. With my modification I can hear the suggestions, and yes some are spoken twice, but at least I can hear them now.

**Comment by josephsl** [comment] 2018-06-20 19:22
Hi,

Solution found: queue ui.message function instead if and only if we're dealing with a different auto-complete item (evidenced by name being different).

I'd be happy to mentor you on how to provide an official pull request and review it if requested.

Thanks.

**Comment by Adriani90** [comment] 2019-05-08 19:35
Closing as duplicate of #8502 which also covers this issue.

**Closed by Adriani90** 2019-05-08 19:35 UTC
Labels: Microsoft Office support, duplicate
