### ISSUE TITLE
NVDA not identifying extension name & other elements on chrome://extensions/shortcuts page

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#8348] opened 2018-05-30 19:12 UTC
### Steps to reproduce:

1. Open an instance of the Chrome browser with some extensions installed

2. Open a new tab and enter _chrome://extensions/shortcuts_ in the address box then hit enter

3. Begin tabbing through the page.  Once you have tabbed past the search box and toggle for developer mode you land in the first edit box (of a sort) for the first extension you have installed and NVDA announces "Edit - Include either Control or Alt, type a shortcut. Blank"  This is the case whether the shortcut is actually blank or not.  Existing shortcuts defined are not read.

4. In order to know what you are actually trying to define you would need to have heard the name of the extension itself, which does appear and is announced if you mouse over the text for it, as well as the field that precedes the shortcut which can read, for example, "Activate the extension."  Other things ahead of the shortcut define edit box are dependent on the extension itself and what actions one can trigger.

5. Once one tabs out of that edit box one traverses to a button which is marked with an X which is intended to allow one to undefine an existing shortcut.  This is always announced only as "Button."

6. Tabbing one more time takes you to the dropdown for "In Chrome" or "Global" that is announced, but if you SHIFT+TAB 2 times back in to the edit box, have never activated that X-delete button, and even if you did define something or there was a default value with CTRL or ALT plus a letter, the announcement is always, "Invalid entry."  This cannot be the case as one would not have been left out of the edit box until correcting or eliminating an invalid entry.

7. There are occasions when SHIFT+TAB is used when the X button is skipped over entirely.  It is always skipped when using TAB to move forward, but this makes sense because one can delete or edit an entry in progress without using it and one generally wants to move to the edit box for the next available shortcut.

8.  There is never an announcement of the extension involved even as you transition from extension to extension on this screen.

### System configuration:
Windows 10 Home, 64-bit, Version 1803, Build 17134.81
NVDA version:
2018.1.1  Installed

Chrome Version:  Version 66.0.3359.181

**Comment by josephsl** [comment] 2018-05-30 19:15
CC @DerekRiemer

**Comment by derekriemer** [comment] 2018-06-04 05:52
@feerrenrut do you have a meeting with Chrome to address this, or should a chrome issue be created?

**Comment by Adriani90** [comment] 2019-12-20 18:08
This is still reproducible with NVDA 2019.3 Beta 1 and Chrome 79.

**Comment by Adriani90** [comment] 2023-04-23 00:03
This works as expected now with NVDA Version: alpha-28130,aOf16eOb (2023.2.0.28130) and Chrome 112.

Closing as works for me.

**Closed by Adriani90** 2023-04-23 00:03 UTC
Labels: close/worksforme
