### ISSUE TITLE
Incorrect output in the store after pressing CTRL+TAB for the first time

### ISSUE THREAD

**Issue by RainerBrell** [nvaccess/nvda#15817] opened 2023-11-23 13:13 UTC
### Steps to reproduce:

- Open the NVDA menu with NVDA+n
- Open Tools and then Store
- Press Control+Tab

### Actual behavior:

On a German system:

Braille-output: "RK panel"
Speechoutput: "Registerkarte panel"

### Expected behavior:

On a German system:

Braille-output: "Updates (G) Registerkarte"
Speechoutput: "Registerkarte Updates ausgewählt"

### NVDA logs, crash dumps and other attachments:

Are not needed.

#### NVDA installed/portable/running from source:

Installed Versionen of 2023.3 or NVDA 2023.2 or portable Version: alpha-30026,9894c9dd (2024.1.0.30026)

#### Windows version:

Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64

#### Other information about your system:

I work with a germanwindows.

This problem only occurs after pressing Control+Tab for the first time.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, see above.

#### If NVDA add-ons are disabled, is your problem still occurring?

Unfortunately yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Unfortunately yes.

**Comment by CyrilleB79** [comment] 2023-11-23 13:28
Welcome @RainerBrell.

This issue has already been reported in #15670. Please comment there if needed.

Closing the current issue as duplicate of #15670.

**Closed by CyrilleB79** 2023-11-23 13:28 UTC

**Comment by RainerBrell** [comment] 2023-11-23 13:53
Thanks for the merge.
The problem I observed can certainly be reproduced well and behaves a little differently than the original problem.> -----Original Message-----

**Comment by CyrilleB79** [comment] 2024-01-09 08:47
Sorry, this issue is actually a duplicate of #14986, not #15670, as I wrote in my previous comment.
