### ISSUE TITLE
Outlook (365): Current view not reported in Change view ribbon item.

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9068] opened 2018-12-14 04:24 UTC
### Steps to reproduce:

1. Open Outlook to the Inbox.
2. Press alt+v, then c, then v to open the Change View item.
3. Press TAB to move through the views available.

### Actual behaviour:

The currently active view is visually highlighted, however NVDA gives no indication of this.
Using object navigation Next or Previously object to move to the view which is active, report current object (NVDA+numpad 5 / NVDA+shift+o).  NVDA reports "focused" for the object you have tabbed to.  NVDA reports "selected" for both the view which is currently selected and the object which is focused.

### Expected behaviour:

When tabbing through views, NVDA should report "selected" for the view which is currently in use.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:
2018.4rc1
#### Windows version:
18272.1000 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11029.20079 

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
alpha 16440,2d8f08a1

Each section of Outlook (mail, calendar, contacts, tasks, etc.) has a "change view" option available from the view ribbon, and all behave in the same way with regard to the selected view.

**Comment by Adriani90** [comment] 2024-06-03 20:15
This is not reproducible with NVDA 2024.2 Beta and Outlook 365 
In my case NVDA reports "hide messages for deletion", "group messages for deletion not selected", "imap messages not selected", "preview not selected".
So NVDA reports the proper not selected state when something is not selected and is silent when something is selected.
I move with left and arrow keys which is the correct way to focus the proper controls in this outlook ribbon area.

I am closing as works for me. If you are still reproducing this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-06-03 20:15 UTC
Labels: close/worksforme
