### ISSUE TITLE
PathControlHelper should label the edit control

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6522] opened 2016-10-29 20:28 UTC
Take code like this.

``` python
class CrashSettings(gui.SettingsDialog):
    #Translators: Title of the settings dialog.
    title = _("pick the directory  for  crashes")

    def makeSettings(self, settingsSizer):
        self.folderName = config.conf["crashSaver"]["dir"]
        self.crashDirectory = guiHelper.PathSelectionHelper(self, "Browse", "Choose your crash selection Directory")
        self.crashDirectory.pathControl.Value = self.folderName


    def onOk(self, evt):
        if os.path.exists(self.crashDirectory.pathControl.Value):
            config.conf["crashSaver"]["dir"] = self.crashDirectory.pathControl.Value
        else:
            gui.messageBox(_("That folder doesn't exist. Enter a valid folder name."))
            return
        super(CrashSettings, self).onOk(evt)
```

from the redesign of crash hero to use gui helper.
The resulting edit field in the crash directory doesn't have a label (Just says edit).

**Comment by feerrenrut** [comment] 2016-11-01 02:11
This was by design. From memory, the only current use of `PathSelectionHelper` (in NVDA) is in the "create portable copy" dialog, where no label is required due to the group box having a label. Actually, in that particular case the group box could potentially be removed and replaced with a label but that's another issue. I think there are cases where a grouping (and no label) would be better. For instance when a dialog contains a path and several options related to it, as well as several options not so related to the path.

Following the current pattern for adding labels I would suggest extending the `addLabeledControl` method to know about `PathSelectionHelpers` (if it doesn't already?)

P3 since there is a work around, eg using a group box, as done in the "create portable copy" dialog or by manually adding a label to the sizer.

**Comment by josephsl** [comment] 2024-07-15 15:04
Hi,

Eight years later...

This is not solved, and as @cyrilleb79 and others noted in #6525, this affects portable copy creation interface. For now I vote to close this unless someone thinks this issue should be reopened.

Thanks.

**Closed by josephsl** 2024-07-15 15:04 UTC
Labels: p4
