### ISSUE TITLE
Windows 10 Mail: COM error when moving focus to another control after closing the app

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8484] opened 2018-07-07 00:27 UTC
Hi,

Reported by a user on NVDA users mailing list:

### Steps to reproduce:
1. Open Windows 10 Mail app (hxoutlook.exe).
2. Read some messages.
3. While reading a message, close Mail.
4. Try moving focus to another control or an app.

### Actual behavior:
COM error is thrown.

### Expected behavior:
No errors.

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1

#### Windows version:
Windows 10 Version 1803

#### Name and version of other software in use when reproducing the issue:
Mail and Calendar (version unknown)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Unsure

#### Have you tried any other versions of NVDA?
No

### Relevant log fragment

DEBUGWARNING - eventHandler.executeEvent (00:55:41.697):
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x050BA050> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyo", line 147, in executeEvent
  File "eventHandler.pyo", line 160, in doPreGainFocus
  File "api.pyo", line 118, in setFocusObject
  File "treeInterceptorHandler.pyo", line 48, in cleanup
  File "baseObject.pyo", line 21, in __get__
  File "appModules\hxmail.pyo", line 15, in _get_isAlive
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 115, in _getPropertyViaCache
  File "appModules\hxmail.pyo", line 24, in _get_shouldCreateTreeInterceptor
COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))

Thanks.

**Comment by Adriani90** [comment] 2019-05-08 16:06
@josephsl I am not able to reproduce this in NVDA 2019.1.1. Is this specific maybe to a synthesizer?

**Comment by josephsl** [comment] 2019-05-08 16:19
Hi, caused by outdated app module, now resolved with another PR from me in 2019.1. Thanks.

**Comment by Adriani90** [comment] 2019-05-08 16:22
Closing as works for me.

**Closed by Adriani90** 2019-05-08 16:22 UTC
Labels: worksforme

**Comment by josephsl** [comment] 2019-05-08 16:29
Hi, I advise closing this as “fixed” rather than as “works for me” to present what happened with this more accurately. Thanks.

**Comment by Adriani90** [comment] 2019-05-08 16:33
I guess this only occurs if Github closes it automatically when merging the pull request where the issue is referenced. I cannot find a label for "fixed".

**Comment by josephsl** [comment] 2019-05-08 16:35
Hi, yep, that’s something pull request authors may wish to keep in mind… Thanks.
