### ISSUE TITLE
Localized donation webpage

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12573] opened 2021-06-23 07:02 UTC
### Is your feature request related to a problem? Please describe.
Some people on the French NVDA user mailing list, especially people that do not speak English, regularly complain that donation is not easy for two main reasons:
* When choosing the "Donation" item in their localized NVDA menu, they are redirected to an English webpage
* They are also reluctant to make a donation in Australian dollars. I do not know if it is because they do not know the exchange rate or because they will have unknown extra bank charge for the currency conversion.
In such cases, sometimes they just give up their donation. In other cases, they can make their donation with the help of other people, e.g. on the list.
In any case, it clearly demotivates people who would like to make a donation.
It seems to me however that the language issue is the main one with respect to the currency issue.

### Describe the solution you'd like

Have the language page translated by translators.
Note that this is the only page that is not localized and that is directly accessible from NVDA's interface. On the contrary, the add-on page is localized.

### Describe alternatives you've considered

If the donation page cannot be translated on the website, make it minimalist. And move all the description of the donation motivations (why it is important, etc.) and the donation process in NVDA's interface and/or in the User Guide.

**Comment by CyrilleB79** [comment] 2021-06-23 07:18
Another information: in the French community, there is a French donation page for NVAccess on nvda-fr.org website.
nvda-fr.org is historically the website that provide localized information regarding NVDA such as NVDA releases download links, some add-ons, including add-ons not reviewed by the NVDA add-on community but very commonly used in the French community, etc. This website is maintained by many persons active in the French NVDA community.

The French donation page is here:
https://www.nvda-fr.org/donate.php

It was suggested on the French user list to have this French page opened when clicking the "Make a donation" menu item instead of the English one.

Cc @Oreonan , @MichelSuch

**Comment by aaclause** [comment] 2021-06-23 07:46
Duplicate of #4307 and #6392

**Comment by CyrilleB79** [comment] 2021-06-23 09:01
Thanks @aaclause, it's actually a duplicate of these issues. I did not find them because they are both closed.
But the problem remains.
The reason why #6392 was closed is not clear to me: @Adriani90 wrote in https://github.com/nvaccess/nvda/issues/6392#issuecomment-471108662:
> I am closing this one because NV Access is well aware of this. @mohdshara please feel free to discuss this directly with NV Access by email or fone. Thank you for reporting.

IMO, "NVAccess is aware of this" is not a good reason to close an issue.

Should this issue be closed as duplicate of #6392, I would recommend to reopen #6392.

**Comment by lukaszgo1** [comment] 2021-09-22 17:12
While I understand the desire to have this web page localized this issue does not address any of the problems raised in the older issues closed as a duplicate. The main one seems to be how to make sure that the translated content is an adequate translation the only way which may work would be to for each update of this web page request a translation from sworn translator  but then the costs would be on NV Access. Also I'm not sure opening a localized web page from NVDA menu is much better - who is going to ensure that the transferred money is going to end up in NV Access's hands. Imagine a situation in which someone adds their supposedly localized donation web page and then takes all the money to  their own account a scandal would be gigantic.

**Comment by CyrilleB79** [comment] 2021-09-22 20:17
I agree that the current issue does not address the issues that were listed in #6392.
The current issue does not bring any new argument that has not been expressed in #6392 and I would be happy to close it in favor of #6392.

I am just mentioning that #6392 was closed with the reason "NVAccess is aware of the problem" but that's not a valid reason. I will comment there to ask reopening it.

**Comment by Adriani90** [comment] 2021-09-23 07:47
closing in favor of #6392

**Comment by CyrilleB79** [comment] 2021-09-23 07:47
Closed as duplicate in favor of #6392 where the whole discussion takes place.
Thanks @Adriani90 for having reopened it.

**Closed by Adriani90** 2021-09-23 07:47 UTC
