### ISSUE TITLE
Standard notepad. The text reads through the line

### ISSUE THREAD

**Issue by Janna39** [nvaccess/nvda#14813] opened 2023-04-08 16:49 UTC
### Steps to reproduce:
Font size -> 16.
Window size -> Is not important.
Language -> Tested in English and Russian.

1. Open Notepad.
	1.1. Press Win + R
	1.2. Enter the command "notepad"
	1.3. Press Enter
2. Copy this text and paste it into notepad (you can take any other text)
```sh
Concerned by the high cost of commercial screen readers, In April 2006, Michael Curran began writing a Python-based screen reader with Microsoft SAPI as its speech engine. It provided support for Microsoft Windows 2000 onwards, and provided screen reading capabilities such as basic support for some third-party software and web browsing. Towards the end of 2006, Curran named his project Nonvisual Desktop Access (NVDA) and released version 0.5 the following year.
```
3. Find a pattern where the text in one line is longer than the text in the line below.
	Example: ![picture 1](https://user-images.githubusercontent.com/99340499/230732388-08412bfd-5a8f-4c41-a5a5-ac571108b129.PNG)

4. The longer line will be the first. The shorter line will be the second.
5. We set the cursor on the first line so that it stands further than the last character in the second line.
	Example: ![picture 2](https://user-images.githubusercontent.com/99340499/230732403-f3d5577b-1335-49d5-bbd4-0985a8d89cda.PNG)

6. Click once on the down arrow.

### Actual behavior:
It is not the second line that is voiced, but the third.

#### NVDA installed/portable/running from source:
> installed

#### NVDA version:
> 2023.1 (2023.1.0.27913)

#### Windows version:
> Windows 10 Pro version 1909 (OS assembly 18363.1500)

#### Does the issue still occur after restarting your computer?
> Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The problem was observed in versions:
> [2023.1](https://github.com/nvaccess/nvda/releases/tag/release-2023.1)
> [2022.3.1](https://github.com/nvaccess/nvda/releases/tag/release-2022.3.1)

**Comment by josephsl** [comment] 2023-04-08 17:05
HI, have you tested it with say, Windows 10 Version 22H2 (build 19045)? Windows 10 Version 1909 (build 18363) is unsupported by Microsoft since May 2022. Thanks.

**Comment by Adriani90** [comment] 2023-04-08 23:37
I cannot reproduce this on Windows 11 22 H2 at least.

**Comment by seanbudd** [comment] 2023-04-11 01:48
This appears to be fixed in newer versions of Windows

**Closed by seanbudd** 2023-04-11 01:48 UTC

**Comment by Janna39** [comment] 2023-04-22 12:02
> HI, have you tested it with say, Windows 10 Version 22H2 (build 19045)? Windows 10 Version 1909 (build 18363) is unsupported by Microsoft since May 2022. Thanks.

No, I haven't tested it on later versions

**Comment by Janna39** [comment] 2023-04-22 12:02
> This appears to be fixed in newer versions of Windows

ok thanks, I'll try another version
