### ISSUE TITLE
Unrecoverable error with cancel speech and text transformations

### ISSUE THREAD

**Issue by ABuffEr** [nvaccess/nvda#11780] opened 2020-10-22 09:37 UTC
### Steps to reproduce:
1. Go to www.facebook.com
2. find a post or comment field, and activate it;
3. write:
"test :)"
without quotes;
4. add a space (":)" will turn into a emoticon representation);
5. try to delete with backspace.
### Actual behavior:
NVDA enters in an endless loop of these two errors:
***
ERROR - speech.manager.SpeechManager._getUtteranceIndex (10:52:30.066) - MainThread (9108):
Expected last item to be an indexCommand.
ERROR - speech.manager.SpeechManager._checkForCancellations (10:52:30.164) - MainThread (9108):
no utterance index, cant save cancellable commands
***
### Expected behavior:
NVDA continues to work without problems.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA version alpha-21250,cb156d20
#### Windows version:
Windows 10 1909
#### Name and version of other software in use when reproducing the issue:
Firefox 81.0.2
#### Other information about your system:
In NVDA advanced settings, "Attempt to cancel speech for expired focus events" is set to yes. Setting to no, the problem disappears.

**Comment by Andre9642** [comment] 2020-10-24 15:32
Duplicate of #11752?

**Comment by ABuffEr** [comment] 2020-10-25 09:59
Yes, it seems same issue, sorry. Should I close this as duplicate?

**Comment by michaelDCurran** [comment] 2020-10-27 01:25
Closing as duplicate

**Closed by michaelDCurran** 2020-10-27 01:25 UTC
