### ISSUE TITLE
edge When switching layouts on the Web pages of nvda does not report on what language it was switching

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#6989] opened 2017-03-19 06:58 UTC
hello When switching layouts on the Web pages of nvda does not report on what language it was switching. 1. Open the Microsoft edge.
2. Open the site for example www.google.com and click in the editor.
3. try switching the keyboard layout.
expected. NVDA should report on what language it was. the actual. NVDA is not reported. windows 10 15061 nvda next-13933,231f5b92

**Comment by jcsteh** [comment] 2017-03-19 23:48
Possibly a duplicate of (or at least related to) #6855.

CC @MichaelDCurran.

**Comment by gdata1** [comment] 2017-08-25 10:06
Hello. Could you send feedback to Microsoft on this issue?

**Comment by leonardder** [comment] 2018-03-06 14:22
I can confirm this and can reproduce this with both JAWS and NVDA.

**Comment by gdata1** [comment] 2018-04-12 11:47
I can also reproduce it with the narrator.
I think this is a problem on the Microsoft side but it has to be solved.

**Comment by Adriani90** [comment] 2020-04-24 23:32
This works as expected on Windows 10 1909 Update and Edge Chromium 81. Closing as works for me since Edge Chromium will be distributed to most users via Winows 10 20 H1 update.

**Closed by Adriani90** 2020-04-24 23:32 UTC
Labels: app/edge, blocked/needs-external-fix, close/worksforme
