### ISSUE TITLE
NVDA can't navigate spreadsheets in Excel 2007

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#7255] opened 2017-06-05 13:02 UTC
In NVDA 2017.2, I can't navigate spreadsheets opened in Excel 2007. Previous versions of NVDA had no trouble with this task.

When I open a spreadsheet, I land on the top left cell, as normal. However, pressing any arrow key results in NVDA speaking that first cell's content, no matter which arrow I press or how many times I press it. Here's the log for the object:

```
Developer info for navigator object:
name: u'SKU'
role: ROLE_TABLECELL
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.window.excel.ExcelCell object at 0x05064610>
Python class mro: (<class 'NVDAObjects.window.excel.ExcelCell'>, <class 'NVDAObjects.window.excel.ExcelBase'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (-2, 500, 1084, 520)
value: ''
appModule: <'appModuleHandler' (appName u'excel', process ID 18172) at address 4ec4e90>
appModule.productName: u'2007 Microsoft Office system'
appModule.productVersion: u'12.0.6766.5000'
TextInfo: <class 'NVDAObjects.window.excel.ExcelCellTextInfo'>
windowHandle: 3606352
windowClassName: u'EXCEL7'
windowControlID: 0
windowStyle: 1456406528
windowThreadID: 7388
windowText: u'All Products.csv'
```

**Comment by jcsteh** [comment] 2017-06-05 23:45
@MichaelDCurran, is this a duplicate of #7243?

**Comment by michaelDCurran** [comment] 2017-06-06 00:02
@jcsteh: Looks like this is a duplicate, yes.

**Closed** 2017-06-06 00:11 UTC
