### ISSUE TITLE
Problems with the new yutube design in Microsoft Edge

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7728] opened 2017-11-05 11:17 UTC
Hello. 1. Open Edge.
2 Go to Www.yutube.com
3 move through the headings.
Expected. Nvda reads the name video.
Fact. Nvda says it's empty.
windows.  windows 10 1709
nvda. next-14588,6a175cf6

**Comment by ehollig** [comment] 2017-11-05 21:39
Duplicate of #7611

**Closed by ehollig** 2017-11-05 21:39 UTC

**Comment by Brian1Gaff** [comment] 2017-11-06 18:27
I guess nobody has actually put the word video into a dictionary entry with 
a null replacement have they?
Not that I can test here, but just wondered!

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message
