### ISSUE TITLE
non reading, if a program run as an other user (runas on windows)

### ISSUE THREAD

**Issue by wip3** [nvaccess/nvda#7959] opened 2018-02-04 17:17 UTC
### Steps to reproduce:
Professionally, I am the system administrator. At work we register with our standard user. But we have no permissions with this user. For example, to do something in ActiveDirectory, we need to start the Microsoft MMC console (dsa.msc) as a different user.
As soon as I run dsa.msc as a different user, NVDA does not read anything in this window. I also have to start NVDA as this user, so that the contents of the dsa.msc are read to me. However, if I start NVDA as a different user, I will not read anything else that is done with the default user.
>
> Example:
>
1. create a user names StandardUser
2. create a second user names user-A
3. Logon on your Windows with the User StandardUser
4. run the dsa.msc as the user "user-A" (on powershell with the command: runas /user:User-A "dsa.msc"
5. navigate the dsa.msc-Window. 

### Expected behavior:
> NVDA can not read the content

### System configuration:
NVDA version: 2017-4
> Windows: Windows 8.1 Pro

NVDA Installed or portable: installed

Name and version of other software in use when reproducing the issue: dsa.msc for example

### Other questions:

Does the issue still occur after restarting your PC? yes

Have you tried any other versions of NVDA?
> 2015-3
> 2016-1

**Comment by leonardder** [comment] 2018-02-05 04:58
Closing as duplicate of #7669, which has the same underlying issue. Having said that, thanks a lot for your thorough description of the issue.

**Closed by leonardder** 2018-02-05 04:58 UTC
