### ISSUE TITLE
New feature: Speech on demand

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#15798] opened 2023-11-17 13:14 UTC
### Is your feature request related to a problem? Please describe.

When I am in a meeting or have any other type of audio feedback (e.g. listening to music or video), I prefer to have a very minimalist audio feedback. I do not want to be bothered by character or word echo when typing, by all sort of notifications, by object speaking when navigating through controls, by text reading when moving around with arrow keys, etc. However, I still want to be able to have specific information reported when I ask for them, e.g. ask title of window, time, read current line, read current object, etc.

### Describe the solution you'd like
In the NVDA+S speech modes loop, add a new "on demand" speech mode. This speech mode should mute all speech except for scripts that are only dedicated to report something, e.g.: report window title, report current object, report current line, report selection, report time, report current nav object, etc.

The behaviour of braille should not change.

### Describe alternatives you've considered
1. I can somewhat reduce the verbosity in a dedicated profile, e.g. disable notifications and suggestions, disable typing echo, etc. But some actions will stil echo some speech, e.g. navigation.
2. I can temporarily enable speech wih NVDA+S, call the requested command, e.g. say time, and disable speech again. But in a meeting, it's more tedious and more verbose.

### Additional context
Jaws has such feature (JawsKey+Space, then S). It may be a source of inspiration to see which scripts are vocalized or muted.

**Comment by Adriani90** [comment] 2023-11-17 13:31
This is a duplicate of #481 and describes a potential approach. Since there is more discussion on this, please post this details in that issue.
Closing as duplicate.

**Closed by Adriani90** 2023-11-17 13:31 UTC
Labels: close/duplicate

**Comment by XLTechie** [comment] 2023-11-17 13:45
+1, for sure.
