### ISSUE TITLE
Characters are not being interpreted correctly

### ISSUE THREAD

**Issue by DalisonCPU** [nvaccess/nvda#11502] opened 2020-08-17 03:42 UTC
### Steps to reproduce:
you just need to hear a text that must be spoken by the reader, using the portuguese BR language.
### Actual behavior:
when we put the ª sign, for example, it announces female ordinal, instead of interpreting its previous character, the same as it was in the previous version.
### Expected behavior:
The reader must interpret the previous character before the character, for example 2ª, the reader must pronounce primeira, and for º sign primeiro.
#### NVDA installed/portable/running from source:
nvda installed
#### NVDA version:
2020.2
#### Windows version:
Microsoft Windows 10 Pro
#### Name and version of other software in use when reproducing the issue:
notepad etc
#### Other information about your system:
there is no way to send log, because it happens everywhere and there is no error
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
With the previous version of NVDA the signal is interpreted correctly.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by lukaszgo1** [comment] 2020-08-17 09:43
Regression caused by #11110. @DalisonCPU Is this happening with other symbols besides "ª" and "º"?

**Comment by lukaszgo1** [comment] 2020-08-17 10:41
It seems these symbols are used in ordinal numbers also for Spanish. @jmdaweb Is it  problematic for Spanish speaking users?

**Comment by Adriani90** [comment] 2020-08-17 12:54
Yes, the translator actually just translated them because of the change introduced by the regression PR. I will solve this, but the translators themselves must be aware that in some languages there are masculine ordinal and female ordinal signs (i.e. in latin languages such as romanian, spanish, portuguese etc. They have to translate this correctly.

**Comment by Adriani90** [comment] 2020-08-17 12:56
So if possible, please write this also into the translations mailing list so that translators are aware of it. I am closing this for now since both symbols are actually already there, they just need to be translated correctly.

**Closed by Adriani90** 2020-08-17 12:56 UTC

**Comment by ivnc** [comment] 2020-08-17 17:57
Hi.

Just to note that, unless that symbols are removed from locale/en/symbols.dic, reading would probably not return back to normal. The intention of the reporter is that numbers are read as "first", "second", "third" when written 1º, 2º, 3º... In Spanish this symbols is already correctly translated, as "ordinal masculino" (and "ordinal femenino" for ª) but NVDA says "uno ordinal masculino" ("one masculine ordinal") instead of "primero" ("first"). If I delete the symbol it defaults to English definition and says !1 ordinal" or, even stranger, "one superscript a" in case of 1ª.
The workaround I've found is to delete the symbol also from the english file by hand. But this is only a workaround, never a solution.
Without these symbols in NVDA, I think the work is done by synthesizers, which come with rules to speak ordinals correctly.
IMO, possible solutions would be to remove the two symbols from NVDA, either by deleting their two lines from the english symbols.dic or by don't defaulting to English if no translation for the symbol is available, or designing a logic that speaks ordinals as expected for affected languages.

Regards.

**Comment by Adriani90** [comment] 2020-08-17 19:32
Thanks for this info, after thinking more about it I think it is not possible in this case to solve this in the NVDA core and it should be let to the synthesizers themselves to solve these issues on a language specific basis. Otherwise it will be really complicated to consider all languages in the core. This being said, I would say the best idea is to remove both symbols from the dictionary.

**Comment by Adriani90** [comment] 2020-08-17 21:03
Another approach would be to create a checkbox in the interpunctuation dialog which lets you decide if the symbol should be pronounced with the patern from symbols.dic or from the sythesizer's own patern.

**Comment by DalisonCPU** [comment] 2020-08-17 21:11
how can I do this?
-----Mensagem original-----
De: Adriani90 <notifications@github.com>
Para: nvaccess/nvda <nvda@noreply.github.com>
Data: Segunda, 17 de Agosto de 2020 14:03
Assunto: Re: [nvaccess/nvda] Characters are not being interpreted correctly(#11502)

Another approach would be to create a checkbox in the interpunctuation dialog which lets you decide if the symbol should be pronounced with the patern from symbols.dic or from the sythesizer's own patern.

**Comment by Christianlm** [comment] 2020-09-01 09:15
A simple solution could be preserve the behaviour of synthesizer:

"""

º	ordinal	char	norep

ª	superscript a	char	norep
"""

same thing for Spanish "abrir interrogación" and "abrir exclamación ":

"""

¿	inverted question	all	norep

¡	inverted exclamation	all	norep
"""

Thanks.
