### ISSUE TITLE
NVDA randomly triggers an error when entering focus mode in firefox

### ISSUE THREAD

**Issue by kara-louise** [nvaccess/nvda#6943] opened 2017-03-07 22:10 UTC
Occasionally, when pressing enter on an edit field on a webpage, NVDA generates the following error message:
ERROR - scriptHandler.executeScript (17:46:51):
error executing script: <bound method Gecko_ia2.script_activatePosition of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x053A5C10>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "browseMode.pyc", line 417, in script_activatePosition
  File "browseMode.pyc", line 1123, in _activatePosition
  File "browseMode.pyc", line 408, in _activatePosition
  File "treeInterceptorHandler.pyc", line 118, in _set_passThrough
  File "review.pyc", line 117, in setCurrentMode
  File "review.pyc", line 25, in getObjectPosition
  File "NVDAObjects\__init__.pyc", line 960, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 201, in _findContentDescendant
COMError: (-2147417842, 'The application called an interface that was marshalled for a different thread.', (None, None, None, 0, None))
Running NVDA version next-13899,af44c1d4 and firefox version 51.0.1 64 bit. the error occurs in the 32 bit version also.
Using Windows 10 build 14393.693.
I can't be more specific as it happens seemingly at random on various websites.

**Comment by jcsteh** [comment] 2017-03-07 23:10
Do you have the focus highlight add-on installed by any chance? If not,
what add-ons do you have installed?

**Comment by kara-louise** [comment] 2017-03-07 23:23
Ah, yes I do have that add on running. I guess it's due for an update then.
Thanks for clearing that up.

**Comment by jcsteh** [comment] 2017-03-07 23:58
I'm not sure if this bug has been fixed in the Focus Highlight add-on. I only know it's an issue that certainly did exist previously. I'm closing this, as this is not a bug in NVDA itself.

@nishimotz, Focus Highlight seems to cause objects to be created in a thread other than the main thread which causes COM marshalling problems. @MichaelDCurran might be able to tell you more, as I know he discovered this a while ago.

**Closed by jcsteh** 2017-03-07 23:58 UTC
