### ISSUE TITLE
NVDA reads folder and file names twice in a row in Windows explorer

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4979] opened 2015-03-17 22:12 UTC
**Reported by toonhead on 2015-03-17 22:12**
When arrowing through folder names and files in windows explorer, NVDA announces them twice in a row i.e. the folder called Stuff would be read out as, stuff stuff.  NVDA also announces drive letters twice as well i.e.  Local Disc C Local Disc c, my book f, my book f, etc.    I have gone into Windows explorer and have disabled the preview pain, details pain  and navigation pain.  Also, under the view menu, list is checked.  This happens 100 percent of the time, but it's got to be machine-specific because no one else I know can reproduce this.  I have tried completely uninstalling, and re-installing NVDA, making sure to remove the NVDA folder from %appdata% so that no older  setings will still be present.  Even after a clean install, it still does this. I have 2 other screenreaders on my system and none of the other ones exhibit this type of behavior.  That's certainly not to say they're better, alls I'm saying is that NVDA is the only one doing this.  Any suggestions would be helpful.  Please keep in mind that I am not a programmer,so if I'm required to do anything, please provide instructions if possible..I'd love to get this fixed!

**Comment by Brian1Gaff** [comment] 2018-07-28 09:42
Seems to me its been years since the author added to this. As current nveda does not run on XP/Vista, maybe the issue was fixed when  the Windows 7 and up version  went live. Need really to hear from the author, assuming the same computer is still in use etc.
 
I seem to recall that if nvda thought it was running on XP it disabled UIA since the windows update to add this to XP was really buggy and kept freezing windows when a screenreader attempted to look at some edit fields.
 Brian

**Comment by leonardder** [comment] 2018-07-28 11:13
I can only reproduce this when I forcefully disable UI Automation. As we haven't received additional reports like this, I'm closing this as works for me. if the problem is still reproducible somehow, please open a new issue and follow the issue template.

**Closed by leonardder** 2018-07-28 11:13 UTC
Labels: bug
