### ISSUE TITLE
Allow filtering by keystroke in the input gestures dialogue

### ISSUE THREAD

**Issue by tangela19** [nvaccess/nvda#11901] opened 2020-12-03 23:57 UTC
### Additional context
Rather than searching by action, it would be nice if we could also filter by keystroke, such as alt+down arrow, to see all actions bound to that keystroke. This would be helpful in re-assigning keystrokes that map to duplicate actions.

**Comment by Adriani90** [comment] 2023-09-13 20:26
Closing as duplicate of #10302.

**Closed by Adriani90** 2023-09-13 20:26 UTC
Labels: close/duplicate
