### ISSUE TITLE
Messy code problem in ESpeak is occured again in 2018.1 rc1 in Chinese.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#8033] opened 2018-02-24 06:18 UTC
Hi:
Messy code fixed in next branch is occured in 2018.1 rc1. For example, 复选框 is read as 复4选3框1. Please fix it. Thanks!

**Comment by vgjh2005** [comment] 2018-02-24 10:44
Please update espeak ng to 1.49.3 to fix this problem. Thanks!

**Comment by leonardder** [comment] 2018-02-24 12:03
@vgjh2005: Did this problem occur in 2017.4?

cc @feerrenrut

**Comment by vgjh2005** [comment] 2018-02-24 16:13
yes

**Comment by Adriani90** [comment] 2019-05-02 20:18
I am not sure if this is a NVDA bug. Is it not rather related to eSpeak and should be reported there? @vgjh2005 are you still having this problem in NVDA 2019.1.1?

**Comment by feerrenrut** [comment] 2019-05-03 13:24
The included version of Espeak is now `919f3240cbbb8060da550f0f9641e69b2975d9f4` which is an in development version of `1.49.3`. There are several other related issues that have been closed, so I think it is safe to close this one. @vgjh2005 if the problem is still ongoing in 2019.1.1 please let us know so we can look into it further.

**Closed by feerrenrut** 2019-05-03 13:24 UTC
