### ISSUE TITLE
Internet Explorer: Deleted content not Retained when Announce Typed Words is Enabled

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5583] opened 2015-12-05 12:05 UTC
When deleting content from text fields from within Internet Explorer, unlike Firefox NVDA does not currently take into account content that may have been deleted. For example, if a user types "test" into an edit field, deletes the last "t" and re-enters it, if NVDA's "Announce typed Words" setting is enabled, the "t" character will be spoken twice when the user starts the next word.

**Comment by JamaicanUser** [comment] 2015-12-07 00:16
I think I reported a similar issue a long while back. Strange enough, the devs haven't replied to it

**Comment by jcsteh** [comment] 2015-12-07 02:21
Duplicate of #4958.

**Closed by jcsteh** 2015-12-07 02:21 UTC
Labels: duplicate
