### ISSUE TITLE
Excel: announce autofilter status when opening

### ISSUE THREAD

**Issue by sumandogra** [nvaccess/nvda#6429] opened 2016-10-06 05:55 UTC
the following is a use case as given by a bank employee-
Use case 1 - No information is provided regarding auto filter status
As a bank employee I am handling ATM monitoring role, I daily receive excel sheets with data such as up / down ATMs, shifted / permanently moved ATMs, daily hits, etc. for analysing and monitoring from various sources internal departments as well as from vendors.   With JAWS screen reader when I open a worksheet it tells me whether the sheet is filtered or not?.  JAWS keystroke Insert + F1 gives me sheet summary with comment as “has auto filter” so this helps me a lot in further data analysis and to work on filtered data. 
However with NVDA there is no such spoken feedback about sheet has filtered data or not.  Each time for every worksheet manually I need to first go to the header row, then by pressing alt + down arrow see whether header row has drop down or not.  If it has I assume that it is a filtered data.  There is no summary option or auto detection by NVDA for filtered sheet.  This is very inconvenient for screen reader user.  I may miss this vital status of the sheet if I do not perform checking headers status operation.  Absence of this key feature which is present in the paid screen readers is hampering my usage of NVDA in the banking work environment.

**Comment by Adriani90** [comment] 2018-02-15 18:02
Is there any chance to start working on this during the year? It would be a very useful feature.

**Comment by Novalis7747** [comment] 2019-05-24 09:24
this is really a very important feature I miss since years in NVDA and Excel. The announcement of an autofilter row is essential for me to do my daily work. I'm kinda bored of switching to another screen reader when working with Excel. If you need an example I can upload one. Any chance to get this in NVDA in 2019?

**Comment by nvdaes** [comment] 2020-09-29 17:41
Hello: this feature has been also requested by Gabriel López, a member of the NVDA's spanish mailing list created by me.
We'll be very grateful if this could be implemented. Here is [topic in Spanish](https://nvdaes.groups.io/g/lista/topic/77148095).

Thanks.

**Comment by ainekc** [comment] 2020-12-06 20:04
Also when you press alt+shift+l for filtering and then you press alt+down, when it has worked correctly NVDA only says "unknown"

**Comment by pranavlal** [comment] 2021-06-25 00:01
Like others who have commented on this issue, I need this data. I am handling budgetry work for my team and have to track invoices. There is a lot of filtering involved and not knowing that a row has an auto filter or not renders NVDA useless for this activity. The sheet is very broad and it is crucial to filter columns and values.

**Comment by Qchristensen** [comment] 2021-06-28 00:13
This is definitely something which is still being requested.  Looking it up, is this a duplicate of #6065 ?  If so, can we move conversation there and close this issue as a duplicate?  Or is there a nuance to this ("when opening" as opposed to at all maybe?) which differentiates it from #6065?

**Comment by pranavlal** [comment] 2021-06-28 00:40
Hi,

<snip is this a duplicate of #6065 ? If so, can we move conversation there and close this issue as a duplicate?

PL] Yes.

 

Pranav

**Comment by seanbudd** [comment] 2021-06-28 03:55
Thanks @pranavlal, closing as duplicate of #6065

**Closed by seanbudd** 2021-06-28 03:55 UTC
Labels: app/microsoft-office, enhancement, p4
