### ISSUE TITLE
Shortcuts to announce comments and translator notes aren't working for Poedit 1.7 and 1.8beta

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5093] opened 2015-05-17 13:59 UTC
**Reported by bdorer on 2015-05-17 13:59**
The last known version this is working is v1.6.10.
In v1.7 the developer created a sidebar showing the translator notes and so on.
This is a partial Reggression of #3485.

**Comment by leonardder** [comment] 2017-07-22 09:10
Closing as duplicate of #4371. Even though this issue is broader in scope (it also talks about comments) the underlying issue is probably the same. Also note that Poedit 2 is currently the stable version, and many things have changed which make the current app module unusable.

**Closed by leonardder** 2017-07-22 09:10 UTC
Labels: App specific, enhancement
