### ISSUE TITLE
Notepad is locking when opening using nvda

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8379] opened 2018-06-08 18:54 UTC
### Steps to reproduce:
I have a problem using nvda.
When I open the notepad using nvda the notepad hangs.
This occurs only when you open Notepad before you restart the computer.
Some times after a long period of time without opening the notepad the problem happens again.
I used another screen reader for a while to see if the problem occurred, but no, it is only with the use of nvda.
To reproduce the problem with the most chances of it occurring, you can do the following:
Restart the computer.
Open firefox and do a google search.
Close firefox and open Notepad.

### Expected behavior:
Firefox should open without errors

### Actual behavior:
Often the notepad hangs.
Please try to reproduce this problem more than two times until it occurs.

### System configuration:
NVDA version:
next 15211
NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 10 17134.81
Name and version of other software in use when reproducing the issue:
notepad
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
yes
log:
[notepad.txt](https://github.com/nvaccess/nvda/files/2085669/notepad.txt)

**Comment by dkager** [comment] 2018-06-15 13:18
I cannot reproduce this with 2018.2.
Do you have any addons installed? If so, does the problem occur after you restart NVDA with addons disabled?

**Comment by ehollig** [comment] 2018-06-15 17:43
Closing, as this sounds to be an issue with an addon that @fernando-jose-silva has installed, and not NVDA itself.

**Closed by ehollig** 2018-06-15 17:43 UTC

**Comment by Adriani90** [comment] 2018-06-15 17:58
Which addons are activated in your NVDA?
