### ISSUE TITLE
aria-hidden elements in table headers can be read as spaces in Chrome

### ISSUE THREAD

**Issue by glin** [nvaccess/nvda#11181] opened 2020-05-21 06:03 UTC
When there's an element with the `aria-hidden="true"` attribute in a table header cell, NVDA can read that element as a space or "blank" if the element's text content is changed. This only seems to happen if the aria-hidden element is next to a block element (e.g., div) in the header, but not an inline element or text node.

For example, if you change the text of both aria-hidden elements in this table (using something like `document.querySelector('[aria-hidden="true"]').textContent = 'a'`), the first header will be read as "C1, space" and the second header will be read as "C2".

```html
<table>
  <tr>
    <th>
      <span aria-hidden="true">hidden</span>
      <div>C1</div>
    </th>
    <th><span aria-hidden="true">hidden</span><span>C2</span></th>
  </tr>
</table>
```

I think this issue only happens in table headers, but I haven't tested this extensively in other contexts. I also originally hit this in a table of divs with `role="table"`.

I've reproduced this issue in Chrome and Edge (Legacy), but not Firefox or IE 11. In Firefox and IE 11, the table headers are read as "C1" and "C2" without any spaces.

Also, the Edge behavior is slightly different. If you navigate character-by-character in Edge, NVDA will read the space before the header, like "space, line feed, C1".

### Steps to reproduce:
1. Open Chrome
2. Browse to https://codepen.io/glin1/pen/dyYaPow
3. Click the "Change text of hidden elements in headers" button
4. Navigate through the table headers.

### Actual behavior:
The first column header is read as "C1, space". The second column header is read as "C2" as expected.

### Expected behavior:
The first column header is read as "C1". The second column header is read as "C2".

#### NVDA installed/portable/running from source:
Installed 

#### NVDA version:
2020.1, but also reproduced with 2019.1

#### Windows version:
Windows 10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:
Google Chrome 83.0.4103.61 (Official Build) (64-bit)

Also reproduced in Microsoft Edge 44.18362.449.0

**Comment by Adriani90** [comment] 2020-07-17 20:46
I think this needs to be fixed in Chrome, since elements with aria hidden should not be exposed or replaced by something else.
cc: @ObjectInSpace

**Comment by ObjectInSpace** [comment] 2020-07-20 17:21
Filed crbug/1107482. FYI, I wasn't able to get this to reproduce in JAWS> Given that and hat it reproduces in other browsers as well, my sense is this is an NVDA issue.

**Comment by Adriani90** [comment] 2020-07-20 18:12
cc: @JulienCochuyt maybe you have some suggestions for this?

**Comment by Adriani90** [comment] 2024-11-18 23:21
The issue is not reproducible anymore in Chrome canary 133 or Edge stable 131 with NVDA 2024.4.1. Closing as works for me. The chromium bug is also closed.

**Closed by Adriani90** 2024-11-18 23:21 UTC
Labels: close/worksforme

**Comment by glin** [comment] 2024-11-18 23:38
I forgot to comment here earlier, but yes, I was also no longer able to repro as of NVDA 2024.3 and Chrome 128.0.6613.120. Great to see this fixed!
