### ISSUE TITLE
Cannot set column & row headers in Word using UIA

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13006] opened 2021-10-29 01:40 UTC
### Steps to reproduce:

Using NVDA 2021.3 Beta 1 (also 2021.2):

1. Set NVDA to use UI Automation to access Microsoft Word controls (in advanced settings)
2. Create a blank document in Word
3. insert a table (ALT+N, T, then 2x2 or greater)
4. Try to set column or row headers (NVDA+shift+c or NVDA+shift+r)

### Actual behavior:

NVDA reports "C" (and a "C" is typed into the current cell in the table).
Log fragment:

IO - inputCore.InputManager.executeGesture (12:34:31.394) - winInputHook (29728):
Input: kb(desktop):shift+NVDA+c
IO - speech.speech.speak (12:34:31.407) - MainThread (27980):
Speaking [PitchCommand(offset=30), CharacterModeCommand(True), LangChangeCommand ('en_US'), 'C', PitchCommand(), EndUtteranceCommand()]

(No error generated)

### Expected behavior:

NVDA should set the current cell as the start of column (or row) headers.

#### NVDA version:

NVDA 2021.3 beta 1 installed

#### Windows version:
Windows 10 (64-bit) Version: 2009, Build: 19043 
#### Name and version of other software in use when reproducing the issue:
Office 365 (64-bit) Version: 16.0.14430.20304 
#### Other information about your system:

NVDA is set to use UI Automation in Word.  With this setting disabled, setting column and row headers works as expected.  Also if column and row headers have previously been set in a table, and NVDA is set to use UIA, NVDA does read the headings while navigating around the table.

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.

NVDA 2021.2 using UIA, won't set headers or read existing headers.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment] 2021-11-25 00:37
Hi, can't this problem be fixed in 2021.3?

**Comment by cary-rowen** [comment] 2022-02-15 09:30
Hopefully this issue will be resolved soon, the performance boost brought by UIA has greatly improved ms Word access.

**Comment by cary-rowen** [comment] 2022-03-07 01:32
cc @michaelDCurran @feerrenrut @Qchristensen 

Seen in #13437 has been added to the 2022.1 milestone, please don't forget this issue.😊

Grateful

**Comment by seanbudd** [comment] 2022-03-07 08:08
This issue uses `Office 365 (64-bit) Version: 16.0.14430.20304`, UIA by default is only for Word 16.0.15000  and newer. Can this be reproduced with `16.0.15000`?

**Comment by josephsl** [comment] 2022-03-07 08:19
Hi,

Looks like we need to wait until late March or April to find out as 16.0.15000 or later is internally marked as version 2203 (Office Insider beta channel at the moment). In other words, the people who will know the answer wil be Microsoft Office 365 engineers and Insiders.

Thanks.

**Comment by cary-rowen** [comment] 2022-03-07 08:34
Hi,
Yes, probably as Joseph said, we cannot verify this at the moment.
I reproduced the issue with the current latest version Microsoft 365MSO  (2202 Build 16.0.14931.20116) 

Thanks.

**Comment by josephsl** [comment] 2022-03-07 08:44
Hi, for folks wishing to verify that this is gone, you must sign up as an Office Insider (I’m (again) willing to become a canary for this experiment). Thanks.

**Comment by LittleStar-VIP** [comment] 2022-05-18 11:18
Not sure if any user has reported the problem or not,
I just found that enabling the UIA support for excel in nvda advance setting, will also make nvda unable to set column and row headers using the respective hotkeys.

**Comment by cary-rowen** [comment] 2022-10-15 13:42
Hi,
@feerrenrut  @josephsl  and everyone who is following this issue,
Is there any progress on this issue?
Thanks

**Comment by michaelDCurran** [comment] 2022-10-17 01:35
It will be impossible for NVDA to support setting row and column headers on a Word document or Excel spreadsheet when using UI automation, as there is no way that NvDA can create bookmarks or set name ranges on the documents via UIA.
For Excel spreadsheets, the recommendation for users is to create proper tables in Excel spreadsheets, enabling the header row and special first column options on the table.
Similarly for Word documents, setting the Header row and first column formatting options on the table.
For existing tables, perhaps Microsoft may consider looking at the custom screen reader bookmarks / named ranges shared between NVDA and Jaws, and expose column and row headers via the UI Automation tableItem pattern.
For new tables, where first row / column is not enough, I guess NVDA could store the user's set row/column header choice in the NVDA user config for each document, but as pointed out above, it can no longer be saved inside the document itself.

**Comment by LittleStar-VIP** [comment] 2022-10-17 03:23
@michaelDCurran 

Based on my testing, although we could still set row or column headers when UIA is enabled, those header info are not spoken by NVDA if UIA is enabled.
I have to turn off UIA support in order to listen to those headers.

**Comment by CyrilleB79** [comment] 2022-10-17 08:02
Would it be possible to use object model (if available) for this feature even if Excel uses UIA for all the other features.

More generally, for Excel but also for Word, would it be possible to have the following choices:
1. use UIA only: probably for devs to test UIA or maybe  for security reasons
2. prefer UIA: use UIA generally but use object model when UIA not available or feature not implemented or implementable with UIA
3. when suitable (i.e. 2. or 4. according to Excel or Word / Windows version)
4. prefer object model: use object model generally but use UIA when object model not available or feature not implemented (or implementable) in UIA.
5. object model only: probably for dev only to test object model
6. Default: today, 4. for Excel and 3. for Word

It would probably be a lot of work to reorganize the code for this purpose. Just a thought...

**Comment by lukaszgo1** [comment] 2022-10-17 20:28
> Would it be possible to use object model (if available) for this feature even if Excel uses UIA for all the other features.


Just for reference - that is what JAWS does.

**Comment by LittleStar-VIP** [comment] 2022-10-17 23:54
This is my current work around,
I create a separate profile for word and excel which uia is disabled, whenever i have to listen to and set table headers, I have to switch to that profile, and it is something very inproductive.

**Comment by Qchristensen** [comment] 2023-10-11 05:45
Looking at this currently, with:
- NVDA 2023.3 Beta 4
- Windows 11 (64-bit) Version: 22H2, Build: 22621.2428 
-  Office 365 (64-bit) Version: 16.0.16827.20130 

What I found was:
- You cannot set headers in tables in Word with NVDA
- The first row and first column are treated as the headers automatically (NVDA will report either the top row, left column, both or neither, as per the "Headers" setting in NVDA's document formatting settings).

Given:
- This seems like it would work in the vast majority of tables which use either the first row and / or left column as the header.
- There was some work needed on Microsoft's side to make our traditional headers work with UIA.  If they were to do this work, it would only be for Office 365 and newer.

Therefore, are we happy to close this issue?

**Comment by seanbudd** [comment] 2023-10-11 22:37
Mick agreed, to close this we must update the user guide

**Closed** 2023-10-16 02:42 UTC
Labels: blocked/needs-external-fix, app/microsoft-office, component/UIA-ms-office
