### ISSUE TITLE
NVDA and PowerPoint animations

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#11140] opened 2020-05-09 21:42 UTC
### Is your feature request related to a problem? Please describe.
While not a bug per se, my suggestion will help NVDA users when presenting a PowerPoint deck.

### Describe the solution you'd like
In PowerPoint, it's possible to assign animations to an object on a slide. For example, say we have a bulleted list. An animation can be applied to this list such that each bullet point appears one after the other, either as the user presses a key or a timing is set up. NVDA doesn't recognize these animated presentations of the bullet points and instead reads them all at once when the slide first appears.
As a blind user designing a PowerPoint presentation, I want to hear each animated item spoken aloud as it appears on the screen, allowing me to test my presentation and understand how sighted people will see the bullet points appearing. I also may want to add a narration to my deck and read these points as they visually appear on the screen.
My suggestion is to have NVDA read the items as they become visible rather than treating them just like a static bulleted list and reading them all at once.

### Describe alternatives you've considered
I an not aware of alternatives to this suggestion but I welcome them if anyone knows of any.

### Additional context
I believe this should be clear but let me know if anything needs clarification.

**Comment by Adriani90** [comment] 2020-05-09 23:53
Closing as duplicate of #7877 which contains a very detailed discussion on this feature.

**Closed by Adriani90** 2020-05-09 23:53 UTC
Labels: close/duplicate
