### ISSUE TITLE
NVDA+Chrome: Office Fabric Dropdown - Disabled Dropdown reads both unavailable and clickable

### ISSUE THREAD

**Issue by xugao** [nvaccess/nvda#10691] opened 2020-01-16 18:36 UTC
### Steps to reproduce:
Note: Only reproing in Chrome
1. Open url: https://fabricweb.z5.web.core.windows.net/oufr/7.82.2/#/examples/dropdown
2. Navigate to the basic dropdown section using down arrow key and navigate to the disabled combo-box "Disabled example with defaultSelectedKey" the "broccoli" is announced being clickable while it is disabled.

### Actual behavior:
Disabled dropdown is read as unavailable and clickable
### Expected behavior:
Disabled dropdown is read as unavailable only

#### NVDA version:
Latest
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
office-ui-fabric-react v7.82.2 (latest)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by fsteffi** [comment] 2020-02-08 11:53
@xugao any update on this issue?

**Comment by v-metiwa** [comment] 2020-02-20 04:54
@xugao :- any update on this?

**Comment by xugao** [comment] 2020-02-21 17:42
@fsteffi @v-metiwa , this issue is NVDA (not Fabric) specific. There is not much I can do here but waiting for NVDA team to resolve

**Comment by Adriani90** [comment] 2020-05-29 23:21
I think this is rather an issue in Chrome or Chromium. The browser should not expose clickable property if the element is disabled.

cc: @aleventhal, @ObjectInSpace

**Comment by ObjectInSpace** [comment] 2020-06-01 16:41
Filed https://crbug.com/1088492 for this. Thanks!

**Comment by feerrenrut** [comment] 2020-06-11 16:35
> There is not much I can do here but waiting for NVDA team to resolve

@xugao You could provide a minimal test case. This would be really helpful for finding the cause of the problem (and proving that is not actually just an authoring error).

Looking at this element with the Firefox and Chrome dev tools, it does indeed have event handler's set for `click` and `onclick`. 

Given that this does not affect Firefox, it's quite likely a Chrome issue.

**Comment by fsteffi** [comment] 2021-07-30 08:12
@xugao  has the issue been fixed

**Comment by Adriani90** [comment] 2023-04-13 22:28
This is fixed as also stated in the Chromium bug. Tested now with NvDA 2023.1, in Edge and Crhome 112 as well as Firefox 111 the "clickable" status is not reported on the list which is disabled. I am closing as works for me.

**Closed by Adriani90** 2023-04-13 22:28 UTC
Labels: bug, close/worksforme, p3, app/chrome, issue-tracking/crbug
