### ISSUE TITLE
Make translated add-on documentation available to users before installation of the add-on

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#17364] opened 2024-11-04 16:00 UTC
### Is your feature request related to a problem? Please describe.

Before the Add-on Store, NVDA menu offered a link to the add-on community website. Through this website, the user could search for a specific add-on and read its documentation in his/her native language before installation, provided the website and the documentation of the targeted add-on had actually been translated in this language.

Now, the user can browse the available add-ons in the Add-on Store, in available add-ons tab. To read the documentation related to a specific add-on, the user can select "Homepage" in the context (action) menu of the add-on. Unfortunately, the URL of this homepage is hard-coded by the add-on. Most of the times, this page is the GitHub's repo main page, containing the readme in the main language of the add-on, which, most of the time, is English.

### Describe the solution you'd like
Allow the user to read the add-on's documentation in his/her native language if it has been translated in this language; fallback to English, or main language of the add-on if not available. Note: some multi-lingual add-ons have Spanish as their main (base) language.

There are probably various possible solutions:
* Allow the "url" field to be translated in the `manifest.ini` file.
* or store all the translated help files (`docFileName` in the manifest) on Add-on Store server and provide the "Help" item also for Available add-ons tab.
* or maybe other possibilities?

### Describe alternatives you've considered

* Let the add-on author detect the language of the user as on other international websites which automatically detect the country of the user.

### Additional context
N/A

**Comment by CyrilleB79** [comment] 2024-11-04 16:02
Cc:
* @RPTools-org; we just discussed it by e-mail.
* @nvdaes: you are likely to be interested by such requests.

**Comment by nvdaes** [comment] 2024-11-06 08:43
Pragmatically, I think we may extract the add-on without putting it in the addons folder, just in a temporary folder, and make the documentation path available.
I think that using URLs may be less stable, unless documentation is stored separately in the store, but a temporary folder may be a solution which involves less work from NV Access.

**Comment by XLTechie** [comment] 2024-11-06 08:57
@nvdaes while that might work most of the time, some add-ons are rather large. 
Downloading them just to get the documentation, could be quite the expense.

I'd rather see NV Access keep the documentation during store on-boarding for each version, and make it available at a specific URL in the addon-datastore repo under either the master or a custom branch.

Like blob/master/docs/language_code/addon/readme.md

**Comment by nvdaes** [comment] 2024-11-06 13:30
@XLTechie , if the documentation is stored by NV Access, this maybe done when the store web frontend is created. This frontend is mentioned in the [roadmap](https://www.nvaccess.org/post/nvda-roadmap). In this case, an important think may be checking if GitHub normal branches are appropriate regarding language switching for screen readers.
I used GitHub pages for some projects since, at least time ago, using just markdown files didn't accept to use HTML langs.

**Comment by seanbudd** [comment] 2024-11-08 03:15
We could store markdown files but we would really want something translatable and that creates a scaling problem for hosting. I think it might be good  to download add-ons client side for now

**Comment by XLTechie** [comment] 2024-11-08 07:27
@seanbudd can you elaborate on the scaling problem?

Regarding storage, if you add up the size of the doc directory of all current add-ons served by the store, , I'd be surprised if it reaches over 150 MB, being generous.

Since it would be GitHub serving the actual data, I wouldn't expect a scaling issue on the request side. So where is the scaling problem?

**Comment by seanbudd** [comment] 2024-11-08 08:33
@XLTechie - we store every version of every add-on, not just every add-on.

It's `numAddons * numAddonVersions * numLanguages * sizeDocs`

**Comment by seanbudd** [comment] 2024-11-12 23:11
Duplicate of #13454

**Closed by seanbudd** 2024-11-12 23:11 UTC
