### ISSUE TITLE
Nvda utters unavailable after copying files

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6842] opened 2017-02-04 12:53 UTC
Soon after finishing copying several files using windows explorer, nvda announces unavailable and does not inform the item focused on windows explorer.
To do the tests.
Using `windows 10 build 14393 64 bits`, for this tests I used the `nvda master 13865`, this acarn with previous versions of nvda.
Open the Start menu and the "This computer" item.
Enter a folder and paste `ctrl + v` a large amount of files, in this case paste a folder of a portable nvda that has about 3gb for the amount of you that was saved in it.
Shortly after the copying of the files, nvda says "unavailable, 100%" is muted.
The expected one would be that nvda will report "100% and the item with focus on the list of files and folders of windows explorer".
This error does not occur with the copy of all the files, it is an intemitente error, today it has already occurred with the copy of the nvda executable and of this folder of files, but it did not happen with the copy of files of complements of nvda and files .doc .
Follow the log:

```
IO - speech.speak (10:32:51):
Speaking [u'indispon\xedvel']
IO - speech.speak (10:32:51):
Speaking [u'100 porcento']
IO - inputCore.InputManager.executeGesture (10:33:17):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:33:17):
Developer info for navigator object:
name: ''
role: ROLE_CHECKBOX
states: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
isFocusable: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
hasFocus: False
Python object: <NVDAObjects.UIA.UIA object at 0x0AD039D0>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: None
value: None
appModule: <'explorer' (appName u'explorer', process ID 47340) at address 5364090>
appModule.productName: u'Sistema operacional Microsoft\xae Windows\xae'
appModule.productVersion: u'10.0.14393.0'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 786686
windowClassName: u'DirectUIHWND'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 49868
windowText: u''
displayText: exception: 'NoneType' object is not iterable
UIAElement: <POINTER(IUIAutomationElement) ptr=0x7967018 at ac9ee90>
UIA automationID: Exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
UIA frameworkID: DirectUI
UIA runtimeID: (47340, 287165744, 0)
UIA providerDescription: [pid:47340,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:DUI70.dll)]
UIA className: Exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
```

**Comment by feerrenrut** [comment] 2017-02-08 12:41
Potentially a quick fix. Should be investigated to understand the cause if we can. Settings a P2

**Comment by feerrenrut** [comment] 2017-02-13 16:08
I think this is timing dependant. My guess is that the file copy dialog is being destroyed before we get a chance to query information from it. This does not happen every time. For me, it actually seems to be easier to reproduce when deleting the files. I'm not sure what we can do to resolve this issue.

This is a result of the "stateChange" event.

**Comment by feerrenrut** [comment] 2017-02-13 16:10
Logging the dev info on the object that causes the "unavailable" text to be shown lets us know that it is the "pause button":

```
name: u'Pause the operation'
role: ROLE_CHECKBOX
states: STATE_FOCUSABLE, STATE_UNAVAILABLE, STATE_FOCUSED, STATE_READONLY, STATE_CHECKABLE
```

The "unavailable" text is spoken due to `STATE_UNAVAILABLE` being present on the object.

**Comment by fernando-jose-silva** [comment] 2017-02-13 16:43
thank you

Enviado do meu iPhone

> Em 13 de fev de 2017, às 14:08, Reef Turner <notifications@github.com> escreveu:
> 
> I think this is timing dependant. My guess is that the file copy dialog is being destroyed before we get a chance to query information from it. This does not happen every time. For me, it actually seems to be easier to reproduce when deleting the files. I'm not sure what we can do to resolve this issue.
> 
> This is a result of the "stateChange" event.
> 
> —

**Comment by jcsteh** [comment] 2017-02-14 03:27
The thing that worries me more here is the issue of focus not being returned to the file list. If focus landed in the file list correctly, it's possible you wouldn't even hear unavailable, since that state change might get fired after the focus moved to the file list anyway.

@feerrenrut, were you able to reproduce the focus issue? For example, if you press NVDA+tab after hearing "unavailable", does NVDA report the currently focused file? If not, we need to work out whether a UIA focus event is being fired. If it is fired, we need to work out why we're ignoring it. If not, we need to file a bug with Microsoft.

**Comment by feerrenrut** [comment] 2017-02-23 15:52
Using NVDA Version: `next-13881,c025b508`
When copying files I got the following output from NVDA:

```
36% complete
Copying 1,223 items from New folder to New folder (2) - 36% complete  grouping
Pause the operation  check box  read only  not checked  Pause the operation
unavailable
New folder (2)  window
Items View  list
brailleDisplayDrivers  1 of 55
```

When I press `NVDA+tab` I get:
```
brailleDisplayDrivers  list item  focused  selected  1 of 55
```

When deleting files:
```
New folder (2)  window
Items View  list
brailleDisplayDrivers  1 of 55
22% complete
49% complete
Recycling 1,223 items from New folder (2) - 49% complete  grouping
Pause the operation  check box  read only  not checked  Pause the operation
unavailable
```

and `NVDA+tab` results in "blank". This makes some sense, there are no files left at that point.

When all but one file is deleted:
```
56% complete
Recycling 1,222 items from New folder (2) - 84% complete  grouping
Pause the operation  check box  read only  not checked  Pause the operation
unavailable
New folder (2)  window
Items View  list
wxmsw30u_html_vc90.dll  not selected  1 of 1
```

**Comment by bramd** [comment] 2018-07-19 11:41
I think NVDA should report a list of 0 items in an empty folder. When using tab to go through an Explorer window with an empty folder, it gives no output at all when landing on the list. When I press nvda+tab, it is silent, only when pressing it twice (for spelling) it says blank. I have seen similar issues before when working with files after copying/deleting/fetching something from OneDrive, which all display similar status/progress dialogs. Also, sometimes the focus doesn't land correctly on the file list after opening a file from explorer and closing the program that was opened, hard to give a specific STR here. For what it's worth, Narrator has the same issue when viewing an empty folder, STR for this:

1. Open Narrator
2. Open explorer in an existing folder with some items
3. Press ctrl+shift+n to create a new folder and press enter to accept the "new folder" name
4. Press enter to open the folder

Expected: the folder name and "list, 0 items" or similar
Actual: nothing

**Comment by feerrenrut** [comment] 2018-08-06 08:09
The number of items for a folder is listed in the status bar (if you have the status bar enabled). However, NVDA doesn't seem to be able to report the status bar on my machine.

**Comment by ruifontes** [comment] 2018-08-06 10:58
Hello!

Try copying this file:
https://www.dropbox.com/s/xodl99wntr63wvv/explorer.py?dl=0
to:
%appdata%\nvda\appmodules
and restart NVDA.

Rui Fontes



Às 09:09 de 06/08/2018, Reef Turner escreveu:

**Comment by feerrenrut** [comment] 2018-08-07 06:36
@ruifontes This does allow the status bar to be reported. Would you mind creating a pull request for this?

**Comment by ruifontes** [comment] 2018-08-07 12:01
I can try to do my first PR... Smile!
For wich issue #?
For Alpha version?

**Comment by ruifontes** [comment] 2018-08-07 13:51
Should I use this:
Issue #6769 Can't read status bar in File Explorer (Windows 10)

**Comment by ruifontes** [comment] 2018-08-07 14:00
Reef, I am not yet ready to make a PR...

If you want, please, make one for me...

Issue #6769 Can't read status bar in File Explorer (Windows 10)

Regards,



Às 07:36 de 07/08/2018, Reef Turner escreveu:

**Comment by feerrenrut** [comment] 2018-08-08 01:13
Yes #6769 would be fine. I'm going to hide this conversation (collapse the messages) since they are not relevant to the initial discussion.

**Comment by Adriani90** [comment] 2020-05-29 22:18
@fernando-jose-silva are you still having this issue in NVDA 2020.1 on Windows 10 1909 Update?

**Comment by fernando-jose-silva** [comment] 2020-05-29 23:11
yes there is still this problem
windows 10 2004 20041.264 64bit
follows log the problem is reproduced with addons disabled
[copy.txt](https://github.com/nvaccess/nvda/files/4704729/copy.txt)

**Comment by Adriani90** [comment] 2023-01-30 09:43
@fernando-jose-silva could you please test again with the last version of Nvda? Is this issue still reproducible for you?

**Comment by fernando-jose-silva** [comment] 2023-01-30 20:55
I don't have this problem anymore, thanks.Enviado do meu iPhoneEm 30 de jan. de 2023, à(s) 06:43, Adriani90 ***@***.***> escreveu:﻿
@fernando-jose-silva could you please test again with the last version of Nvda? Is this issue still reproducible for you?

**Comment by Adriani90** [comment] 2023-01-31 10:25
Closing as works for me.

**Closed by Adriani90** 2023-01-31 10:25 UTC
Labels: close/worksforme, p2, quick fix
