### ISSUE TITLE
Different content and layouts in web pages on different systems, often missing information

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#10647] opened 2019-12-21 15:00 UTC
### Steps to reproduce:

I often find web pages which present differing content and layouts depending whether I access them on my Windows computer at home or at my workplace computer. The main differencnes between the two are that I run Windows 10 at home, and Windows 7 at my workplace. in addition, my home computer is a laptop, while my workplace computer is a Desktop.

In my workplace, there are also some restrictions such as in case of pages trying to redirect to other pages, etc.

I can't say now whether there are differences in things like the screen resolution, assuming it matters.

One example of such a page is Assembla - www.assembla.com/. In my workplace, I was able to find the "Sign in" link to do my login, but here at home, there is no Sign in option, even using NVDA's find functionality or the review cursor. The only way I managed to login here was directly changing the page address by adding "login" at the end.

### Actual behavior:

Page layout differs in a significant way.

### Expected behavior:

At least, information shouldn't be missing.

#### NVDA installed/portable/running from source:

Installed at home, portable at workplace.

#### NVDA version:

2019.2.1 in both computers.

#### Windows version:

Windows 10 here, Windows 7 there.

#### Name and version of other software in use when reproducing the issue:

Firefox 71 in both computers.

#### Does the issue still occur after restarting your PC?

Yes.

**Comment by Adriani90** [comment] 2019-12-21 22:53
is screen layout disabled in Nvda‘s browse mode settings on all machines? I cannot reproduce this issue on several machines with different screen sizes. The information exposed through the accessibility APIs to the screen reader does not depend on screen resolution as far as I know.

**Comment by Cleversn** [comment] 2019-12-22 00:50
Hi, yes, screen layout is disabled in all machines. I recall other pages reproducing this problem, but they require private login information to display. In any case, I'll stay watchful to try finding more public pages.

**Comment by Brian1Gaff** [comment] 2019-12-22 10:07
What happens if you do a page refresh just a few seconds after the page has 
displayed? I have found this often helps. It looks like part of the data on 
a page is sent later and either nvda is not looking for it or the browser 
ignores it. Not sure. However vital buttons and edit areas can just be 
completely missing. Oddly the only browser that has always worked is IE11,
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2019-12-22 10:14
https://kingston.talking-news.info/

Try the above site, when you  go to the player  9 times out of ten the main 
controls are not there, ie play and wind and the counter, and pause etc, do 
a refresh, and there they are.
This affects firefox and waterfox and not ie.

 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Cleversn** [comment] 2019-12-22 14:16
Hi, thanks for the hint on refreshing the page and/or the virtual buffer. I don't often recall to try that. Incidentally, I'm trying now to log out from my account at Assembla, but there seems not to be any link or button to do that.

**Comment by Adriani90** [comment] 2019-12-22 23:30
To be honnest I think this is not an NVDA issue. It might be an issue related to your grafic card, to your windows system but also as you said, relatd to restrictions about page redirecting. Did you already compared the link in the address bar of your browser on the different machines? Are the links exactly the same?
I am using NVDA on thre machines with different windows versions and also on more Windows 10 machines, I cannot reproduce this issue.

**Comment by Brian1Gaff** [comment] 2019-12-23 21:04
Well assuming refresh does not show one it might be a site issue. I have 
found many web sites where you log in but seemingly not out again.
 I suppose it detects you are gone.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2019-12-23 21:05
Did you try my example? Several people get the same as me, and refresh 
always sorts it.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2020-05-28 19:57
@Cleversn how is this now with NVDA 2020.1 and Firefox 76?

**Comment by Adriani90** [comment] 2020-05-28 19:59
Are you having screen curain enabled at the machine where you cannot find the login link?

**Comment by Cleversn** [comment] 2020-05-28 22:22
Hi Adriani, I've experienced this problem at other web sites since i opened this issue, and I believe to have identified more precisely what is happening. For some reason, when a given web site offers more than one layout (e.g. a normal layout and a mobile layout), then for some reason, Google Chrome and the new Microsoft Edge display the normal layout, while Firefox is displaying the mobile layout, even though the page a ddress is for the normal layout. Oddly enough, when the web site is m.facebook.com, then it is the oposite: Firefox displays the mobile page as it should, but MS Edge displays the normal layout, even though the address is the mobile.

I'm afraid I'm gonna need to set up a permanent extension for Firefox to pretend to be Chrome or Edge at some sites...

**Comment by Adriani90** [comment] 2020-05-29 21:32
@Cleversn in this case I think there is nothing NVDA can do about it. This might be caused by the AMP or the rendering platform used by the website. So unfortunately it is not possible to solve this in NVDA, but rather the website developer should improve this ideally. So if you see something like this, I am quite sure that the website looks different also visually, not only for the screen reader. In this case please contact the owners of the website if there are real accessibility issues.
I am closing this for now.

**Closed by Adriani90** 2020-05-29 21:32 UTC
