### ISSUE TITLE
Why do radio buttons trigger focus mode, but checkboxes don't?

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#7578] opened 2017-09-08 19:17 UTC
I wonder why do radio buttons trigger focus mode, but checkboxes don't?

Here's a demo with radio buttons. When tabbing to the first radiobutton, the legend's title (Gender) is announced by NVDA (as focus mode is triggered):

https://codepen.io/accessibility-developer-guide/full/WEqVdR/

Here's a demo with checkboxes. When tabbing to the first checkbox, the legend's title (Hobbies) isn't announced by NVDA (as browse mode remains active):

https://codepen.io/accessibility-developer-guide/full/aygeqR/

This feels like unpredictable behaviour to me. Are there any other form elements that don't trigger focus mode upon tabbing?

**Comment by AKJ** [comment] 2017-09-19 19:13
I presume this is intended behavior, as checkboxes are a simple toggle while radio buttons can be navigated between in focus mode with up / down arrows. I know I like not being taken into focus mode for checkboxes; it feels unnecessary since it does not expose any new method for interacting with the checkbox.

Anyone disagree with this assessment?

**Comment by jmuheim** [comment] 2017-09-21 07:13
The problem is, that when you attach descriptive text to form fields using `aria-describedby`, it's only announced in focus mode (as far as I remember). So when a user is tabbing through form controls, information attached to radio buttons may be missed, which is unfortunate, as for all other form controls, this technique works reliably.

**Comment by derekriemer** [comment] 2017-09-21 23:17
@feerrenrut Is descriptions in browse mode on the roadmap?

**Comment by feerrenrut** [comment] 2017-10-02 02:33
This is not currently on the road map, I agree that the consistency could be improved by having descriptions read from browse mode.

**Comment by jmuheim** [comment] 2017-10-02 08:45
Powermapper claims that NVDA reads `aria-describedby` in browse mode since 2012 already!

https://www.powermapper.com/tests/screen-readers/labelling/a-aria-describedby/

So you say this claim is wrong?

**Comment by jmuheim** [comment] 2018-04-30 16:16
Is there any news on that?

**Comment by Qchristensen** [comment] 2019-09-23 22:41
Not adding anything, but this looks like the same issue as #10095.  I'm going to close this one as the other issue as more detail, but I'll copy @jmuheim's original comments / links across as another useful demo of the issue.

**Closed by Qchristensen** 2019-09-23 22:41 UTC
Labels: Browse mode, feature
