### ISSUE TITLE
Suggestion about words with all caps

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#10822] opened 2020-02-26 21:59 UTC
### Is your feature request related to a problem? Please describe.
I sometimes encounter words with all caps. As a student of translation studies, I want to capitalize my work too so I can fit it to the source. I don't know where I encounter them.
### Describe the solution you'd like
Addition of an option which causes the synthesizer to raise pitch while reading the word whenever it encounters a written word, just like it does when we navigate over capital letters. The options of beeping and say cap should also be implemented.

**Comment by Qchristensen** [comment] 2020-05-21 05:12
Closing this as a duplicate of #3286.  The issue itself is still valid, but please continue conversation of it in issue #3286.

**Closed by Qchristensen** 2020-05-21 05:12 UTC
