### ISSUE TITLE
Reversed reading order of control types and label/text in browse mode with or without quick keys as well as Productivity degrading announcement of "out of link", "out of list" etc.

### ISSUE THREAD

**Issue by akash07k** [nvaccess/nvda#11102] opened 2020-05-04 07:51 UTC
### Steps to reproduce:
1. start NVDA,
2. Open any of the browser and browse/open any webpage.
3. Try navigating to headings, links, buttons etc using quick keys and observe the behaviour.
4. Now try navigating/reading the webpage without quick keys using arrow keys in browse mode and observe the behaviour with headings, links, buttons etc.

### Actual behavior:
When we navigate in browse mode using quick keys, NVDA announces nearely every element's text first and then it's control type/role which is excellent. For example:
If I'm on any page and there are headings:
"Introduction", "Testing", "About".
Links such as: "Download", "Contact Us".
Buttons: "Search", "Submit" etc.
Now when I navigate to the headings by using quick key: "H", NVDA announces it like:
"Introduction heading level 2", "Testing heading level 2", "About heading level 2".
If I use "L" for links it announces like: "Download link", "Contact us link". 
For buttons: "Search Button", "Submit Button" etc.
Now when we navigate in browse mode via arrow keys without using any quick key, the order gets reversed.
It announces the control type first and then the label/text of the control which is very annoying and degrades the productivity level.
For example: "Heading level 2 introduction", "Heading level 2 Testing", "Heading level 2 about", 
"Link Download", "Link Contact Us", 
"Button search", "Button submit" etc.
It becomes very time consuming to here the control type/role of every control/element first and then it's label/text.
It degrades and badly impacts the web browsing experience with NVDA.
Moreover, it's very annoying to hear: "Out of list", "Out of link" etc while browsing.
Also, if we turn on the article announcement from the "document format settings", still NVDA announces the "article" before every article even though browsing it via quick key.

### Expected behavior:
When user navigates via arrow keys, he/she wants to get the information as quickly as possible. But if he/she hears the control type first then he/she requires to wait for hearing the actual information regarding the control role/text.
If possible, a toggle should be added in NVDA so that user can toggle this behaviour as per his/her liking.
Article reporting should also be fixed for the better experience.
Announcements such as: "Out of link", "Out of list" etc should also be turned off or a toggle should be provided for them.

#### NVDA installed/portable/running from source:
Tried with both: (Installed and portable)
#### Windows version:
Windows 10 Build 19041.208
#### Name and version of other software in use when reproducing the issue:
Chrome 81 stable and latest caneri, Brave  latest and caneri, Firefox.
#### Other information about your system:
Tried with latest RS fast insider releases of windows but same issue is there.

#### Does the issue still occur after restarting your computer?
Yes, always
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, tried with all the versions till alpha snapshots and same behaviour repros on every version
#### If addons are disabled, is your problem still occuring?
Yes, always
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by leonardder** [comment] 2020-05-04 07:58
I think it is safe to treat this as a duplicate of #7232. The description of this issue also seem to describe multiple issues, not just one single issue. Could you open a new issue for:

> Also, if we turn on the article announcement from the "document format settings", still NVDA announces the "article" before every article even though browsing it via quick key.

Along with steps to reproduce?

**Closed by leonardder** 2020-05-04 07:58 UTC

**Comment by akash07k** [comment] 2020-05-04 08:34
> I think it is safe to treat this as a duplicate of #7232. The description of this issue also seem to describe multiple issues, not just one single issue. Could you open a new issue for:
> 
> > Also, if we turn on the article announcement from the "document format settings", still NVDA announces the "article" before every article even though browsing it via quick key.
> 
> Along with steps to reproduce?
https://github.com/nvaccess/nvda/issues/11103
Also, can we please reopen this issue so that it gets visibility and can be taken into consideration?

Hi @leonardder I've logged the issue and below is the link:

**Comment by leonardder** [comment] 2020-05-04 09:31
> Also, can we please reopen this issue so that it gets visibility and can be taken into consideration?

If a duplicate, we always close the duplicates so only one stays open for the backlog not to get too messy. We'll continue in #7232.

**Comment by akash07k** [comment] 2020-05-04 11:53
Ok bro
