### ISSUE TITLE
Outlook 2016 errors while reading emails with tables

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#7417] opened 2017-07-19 05:00 UTC
### Steps to reproduce:

1. Read a moderately complex email that contains tables such as linked in's invites. I'm not sure what the best way would be to post a sample email that can be imported into outlook.
2. Do a say all. It stops reading once it encounters this error:

```python
ERROR - queueHandler.pumpAll (12:50:10.961):
error in generator 325
Traceback (most recent call last):
  File "queueHandler.pyc", line 72, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 835, in speakTextInfo
  File "browseMode.pyc", line 1001, in getControlFieldSpeech
  File "textInfos\__init__.pyc", line 434, in getControlFieldSpeech
  File "speech.pyc", line 1173, in getControlFieldSpeech
  File "NVDAObjects\window\winword.pyc", line 727, in get
  File "NVDAObjects\window\winword.pyc", line 1231, in fetchAssociatedHeaderCellText
  File "NVDAObjects\window\winword.pyc", line 1168, in getHeaderCellTrackerForTable
  File "comtypesMonkeyPatches.pyc", line 35, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 149, in __getattr__
  File "comtypes\automation.pyc", line 664, in _invoke
COMError: (-2146822463, None, (u'Object has been deleted.', u'Microsoft Word', u'wdmain11.chm', 25305, None))
```

3. The same error appears as well when moving using the arrow keys, just with a slightly different call stack.

### Expected behavior:
The email should read normally without stopping on errors.

### Actual behavior:
It stops reading in say all when encountering this error. When using arrow navigation, it errors when encountering the triggering line, and is unable to read it.

### System configuration:
NVDA version:
master-14204,86f50927

NVDA Installed or portable:
Installed

Windows version:
Windows 10 version 1611

Name and version of other software in use when reproducing the issue:
Outlook 2016 

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
Not yet, but this only started happening recently, (like a month ago?) so its either an outlook or NVDA change.

**Comment by Neurrone** [comment] 2017-08-20 18:05
Bump, seeing a lot of these recently.

**Comment by PratikP1** [comment] 2017-08-20 19:41
Possible duplicate of #6827 and #7196. Also possibly related to #5450 5776.

**Comment by ehollig** [comment] 2017-08-20 20:22
Duplicate of #7196

**Closed by ehollig** 2017-08-20 20:22 UTC
