### ISSUE TITLE
HIMS Smart Beetle Scroll Buttons Say "malformed"

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#7837] opened 2017-12-07 21:11 UTC
I still get the issue of scroll buttons on the Smart Beetle not working as expected in NVDA 2017.4, so tried to assign them to the scroll commands by using the "Input gestures" dialog. Here are the results.

### Steps to reproduce:

* Connect the Smart Beetle over Bluetooth.
* Open the "Input gestures" dialog.
* Open the "Braille" branch and navigate to the "Scrolls the braille display back" entry.
* Press the "Add" button.
* Press one of the scroll buttons on the Smart Beetle.

### Expected behavior:

NVDA should register the scroll button.

### Actual behavior:

NVDA assigns "malformed:br(hims)" when the scroll button is pressed. Interestingly, this lets me scroll, but since both the scroll back and scroll forward buttons both register "malformed:br(hims)", I can only scroll in one direction. I have to assign different dot combinations to the scroll commands to get the Smart Beetle to actually scroll. When I do this (for example, assigning dots 2-3-space to scroll backwards,) pressing dots 2-3-space does scroll the display backward. So the gesture is working, it is only that the scroll buttons are not being recognized.

### System configuration:

NVDA version: 2017.4

NVDA Installed or portable: Installed

Other information:

Windows version: 10, Fall Creator's Update

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Yes

Using 2017.3, I also could not scroll the display.

**Comment by leonardder** [comment] 2017-12-08 04:53
The idea behind the malformed indicator is that you should actually not register them, since the gesture identifier that is produced by pressing the key is malformed (i.e. the key is not mapped to a key name inside the driver). Note that the previous behavior in version 2017.3 was much less user friendly. These malformed gestures for the Beetle will be fixed as part of #7712, which is now incubating in next.
This is essentially still a duplicate of #6086 and #7679, so I"m closing this.

**Closed by leonardder** 2017-12-08 04:53 UTC
Labels: Braille
