### ISSUE TITLE
Outlook 2016 hangs and restarts when changing folders

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#7556] opened 2017-09-01 21:07 UTC
### Steps to reproduce:

In Outlook 2016, when in e.g the Inbox, press Ctrl+y to bring up the list of folders and arrow down to another folder and press Enter.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:

Sometimes, Outlook gives the message "No default IMEI available" and restarts. Sometimes Windows gives the possibility to exit the application or wait.

### System configuration:
NVDA version: Next 14373, my Braille display is not connected. 

NVDA Installed or portable:
Installed

Other information:

Windows version:
Windows 10 64 bit.

Name and version of other software in use when reproducing the issue:

Outlook 2016.

Hope the below log fragment is of any use:

```
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
ERROR - RPC process 4960 (nvda_slave.exe) (22:26:36.411):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
ERROR - RPC process 5044 (nvda_slave.exe) (22:27:17.721):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
ERROR - RPC process 8552 (nvda_slave.exe) (22:28:34.237):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
INFO - inputCore.InputManager._handleInputHelp (22:33:06.362):
Input help: gesture kb(laptop):NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:06.490):
Input help: gesture kb(laptop):NVDA+z
INFO - inputCore.InputManager._handleInputHelp (22:33:10.176):
Input help: gesture kb(laptop):leftShift
INFO - inputCore.InputManager._handleInputHelp (22:33:10.176):
Input help: gesture kb(laptop):shift+NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:10.266):
Input help: gesture kb(laptop):shift+NVDA+x
INFO - inputCore.InputManager._handleInputHelp (22:33:12.072):
Input help: gesture kb(laptop):leftShift
INFO - inputCore.InputManager._handleInputHelp (22:33:12.091):
Input help: gesture kb(laptop):shift+NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:12.141):
Input help: gesture kb(laptop):shift+NVDA+z, bound to script toggleCurrentAppSleepMode on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (22:33:14.539):
Input help: gesture kb(laptop):leftControl
INFO - inputCore.InputManager._handleInputHelp (22:33:14.542):
Input help: gesture kb(laptop):control+NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:14.631):
Input help: gesture kb(laptop):control+NVDA+z, bound to script activatePythonConsole on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (22:33:21.150):
Input help: gesture kb(laptop):NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:21.250):
Input help: gesture kb(laptop):NVDA+f1, bound to script navigatorObject_devInfo on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (22:33:27.289):
Input help: gesture kb(laptop):leftShift
INFO - inputCore.InputManager._handleInputHelp (22:33:27.305):
Input help: gesture kb(laptop):shift+NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:27.377):
Input help: gesture kb(laptop):shift+NVDA+f1
INFO - inputCore.InputManager._handleInputHelp (22:33:30.364):
Input help: gesture kb(laptop):leftControl
INFO - inputCore.InputManager._handleInputHelp (22:33:30.364):
Input help: gesture kb(laptop):control+NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:30.473):
Input help: gesture kb(laptop):control+NVDA+f1, bound to script reportAppModuleInfo on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (22:33:35.693):
Input help: gesture kb(laptop):NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:36.079):
Input help: gesture kb(laptop):NVDA+2, bound to script toggleSpeakTypedCharacters on globalCommands.GlobalCommands
INFO - inputCore.InputManager._handleInputHelp (22:33:38.223):
Input help: gesture kb(laptop):NVDA
INFO - inputCore.InputManager._handleInputHelp (22:33:38.411):
Input help: gesture kb(laptop):NVDA+1, bound to script toggleInputHelp on globalCommands.GlobalCommands
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:38:46.038):
Developer info for navigator object:
name: u'Default IME'
role: ROLE_UNKNOWN
states: STATE_FOCUSABLE, STATE_UNAVAILABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at 0x055CE670>
Python class mro: (<class 'NVDAObjects.IAccessible.ContentGenericClient'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 0, 0)
value: u''
appModule: <'appModuleHandler' (appName u'dwwin', process ID 5804) at address 5472a10>
appModule.productName: u'Microsoft\xae Windows\xae Operativsystem'
appModule.productVersion: u'10.0.15063.0'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 2230310
windowClassName: u'IME'
windowControlID: 0
windowStyle: -1677721600
windowThreadID: 12852
windowText: u'Default IME'
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x6ff6010 at 529dbc0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=2230310, objectID=-4, childID=0
IAccessible accName: u'Default IME'
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_UNAVAILABLE, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048581)
IAccessible accDescription: None
IAccessible accValue: None
INFO - config.ConfigManager._loadConfig (22:39:16.049):
Loading config: C:\Users\Daniel Gartmann\AppData\Roaming\nvda\profiles\Dansk.ini
WARNING - stdout (22:39:16.105):
hooked waveOutOpen
WARNING - stdout (22:39:16.107):
hooked waveOutClose
INFO - synthDriverHandler.setSynth (22:39:16.174):
Loaded synthDriver sapi5
ERROR - braille.BrailleHandler.setDisplayByName (22:39:21.431):
Error initializing display driver
Traceback (most recent call last):
  File "braille.pyc", line 1504, in setDisplayByName
  File "brailleDisplayDrivers\freedomScientific.pyc", line 179, in __init__
RuntimeError: No display found
INFO - braille.BrailleHandler.setDisplayByName (22:39:21.497):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - synthDriverHandler.setSynth (22:42:31.572):
Loaded synthDriver eloquence
ERROR - braille.BrailleHandler.setDisplayByName (22:42:36.838):
Error initializing display driver
Traceback (most recent call last):
  File "braille.pyc", line 1504, in setDisplayByName
  File "brailleDisplayDrivers\freedomScientific.pyc", line 179, in __init__
RuntimeError: No display found
INFO - braille.BrailleHandler.setDisplayByName (22:42:36.900):
Loaded braille display driver noBraille, current display has 0 cells.
ERROR - RPC process 1312 (nvda_slave.exe) (22:48:36.023):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
ERROR - RPC process 3240 (nvda_slave.exe) (22:53:04.104):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221021] Handlingen er ikke tilgængelig
```

**Comment by fernando-jose-silva** [comment] 2017-09-02 00:57
I also have this problem, the same verifications of nvda and office.

**Comment by Brian1Gaff** [comment] 2017-09-02 12:00
This looks like the problem has already happened, and also it looks like 
nvda restarted and yet kept the same log. Most odd.

I note the number of times you tried to get nvda/F1 to work here.


You might try setting up this batch file in the route and calling it from a 
hotkey shortcut on the desktop.

@echo off
cd "%temp%"
start /WAIT nvda.exe -q

start notepad.exe nvda.log
rem, this line just kicks its heels for a bit to make sure the log is loaded 
into notepad before rebooting nvda.
ping -n 5 127.0.0.1>nul
start nvda.exe

exit


Do this when the hang happens as fast as possible. it may take a while to 
restart nvda if it has to forcibly terminate it.
 I hope this works on Windows 10, it does on windows 7, as a similar issue 
occurs on some software there as well, but is pesky and not easy to get it 
to do it to order.



set loging level to debug first of course.
 I think you may then see a crash screen in the rebooted nvda for whatever 
it was that fell over.
 Not convinced by the braille display errors as I think nvda was well 
confused. also a sad lack of any spoken messages in the log, what synth was 
in use at the time. set  to Espeak first, just in case.

That would be my few thoughts.

 Brian



bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by leonardder** [comment] 2017-09-02 18:18
cc @dkager

**Comment by dkager** [comment] 2017-09-02 19:14
Confirmed. Further:
- Also happens with NVDA 2017.3.
- Has happened with the last few Office 365 updates. I suspect something in Outlook changed, rather than in NVDA, but that's an uneducated guess.
- Can't reproduce with Outlook 2013.
- When I enable troubleshooting logs in the Outlook options (Advanced tab, near the bottom) the problem goes away. This makes me wonder if it is a timing issue, e.g. Outlook is a bit slower with logs enabled.

**Comment by ehollig** [comment] 2017-09-05 22:47
As reported by @comanna in #7559:
### Steps to reproduce:
1. Open Outlook
2. At the Inbox, press control-y for the folder list
3. select any folder by typing the first letter e.g. "s" for "sent items"
4. Outlook should open the desired sub-folder immediately.
### Expected behavior:
The desired folder should open
### Actual behavior:
Outlook hangs and eventually (after about 10 seconds) reports that the folder is "Not responding"
Two possible outcomes have been experienced:
1. Outlook reverts to teh Inboxand all seems as normal
2. After a further 10 seconds Outlook reports that a problem has occured and Outlook needs to close
### System configuration:
NVDA 2017.3 installed on Windows 10Version 1703 (OS Build 15063.540)
### Name and version of other software in use when reproducing the issue:
MS Office 2016 latest update (31st August 2017)
### Other questions:
Does the issue still occur after restarting your PC?
The issue is not dependant on the PC restarting. It is intermittent and can persist for many hours and then not appear for a day.
The impact of the crash is to close the folder opening function that is triggered by control-y. The alternative method of using control-shift-tab remains functional and allows each folder to be opened normally. The strange anomaly is that frequently but not every time, control-shift-i will trigger the timeout crash after the use of control-shift-tab.
### Have you tried any other versions of NVDA?
The same results were experience for teh past year with version 2017.1, 2017.2 and now with 2017.3
### The user experience:
https://nvda.groups.io/g/nvda/topic/5928737#24997
### NVDA log:
[NVDA log.txt](https://github.com/nvaccess/nvda/files/1279191/NVDA.log.txt)

**Comment by Qchristensen** [comment] 2017-09-12 01:35
I can reproduce this as well, on Windows 10 fast insider build 16281 and Office 2016 version 1707, version 8326.2096 and NVDA 2017.3.  For me, having the enable troubleshooting logs enabled in Outlook didn't resolve it.

In the interim, it is possible to change folders seemingly more reliably by pressing control+shift+tab to move from the list of messages in the current folder, to the folder list, then using the arrow keys to select a folder and press enter to activate and go into that folder.

**Comment by comanna** [comment] 2017-09-13 11:51
Duplicate of #7556
The NVDA log file that I saved does show an error after control+y is pressed.  It is listed in the attached files. I have also attached a second NVDA log file to show the log when countrol+shift+tab is pressed with no error generated which might give a contrasting pattern that might be useful.

Cearbhall
[nvda ctrl-y-log.txt](https://github.com/nvaccess/nvda/files/1299270/nvda.ctrl-y-log.txt)
[nvda-ctrl-shift-tab-log.txt](https://github.com/nvaccess/nvda/files/1299269/nvda-ctrl-shift-tab-log.txt)
comanna

**Comment by Qchristensen** [comment] 2017-09-14 00:49
@comanna you mentioned duplicate of #7556, but this is issue 7556 - did you mean to link a different issue?

Also, two small updates from my testing and another user report:
- I still haven't reproduced the crash by changing folders with control+shift+tab then arrows, so that seems to work ok.
- Changing folders, particularly changing to different folder types (eg to calendar and back or different accounts) by clicking on the folder with the mouse also causes an identical looking crash.

**Comment by comanna** [comment] 2017-09-14 09:53
Quentin,

 

No, I was making it clear that the details given in my comment come from my own issue which was assigned 7559. I accepted that 7559 be closed because it actually refers to the same situation reported here at 7556. I added my material because I notice that my steps are a bit different from those originally reported in 7556. 

 

I have occasionally triggered the same issue when using control+shift+I to return to the Inbox after I have moved to a sub folder using control+shift+tab. However, it happens very rarely. I will try to trap it next time it happens.

 

All the best,

 

Cearbhall

 

m +353 (0)833323487 Ph: _353 (0)1-2864623 e: cearbhall.omeadhra@blbc.ie

**Comment by dkager** [comment] 2017-09-14 19:08
A crash that looks the same also occurs when switching between folder types with hotkeys, e.g. Ctrl+2 to go from Mail to Calendar. This makes the issue quite serious IMO. While there are work-arounds, they aren't quite as fast.

**Comment by Brian1Gaff** [comment] 2017-09-15 09:41
I don't think this is new, as a friend has random crashes of Outlook 2003 in 
win ten which was working before. it might of course also be an issue with 
newer versions of win 10 and nvda causing some undesired effects.
 Brian


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by michaelDCurran** [comment] 2017-09-15 10:57
Looks like this may be a recent change in Outlook 2016. This can be reproduced with versions of NVDA all the way back to 2015.1
I have reported this crash to Microsoft including steps to reproduce and a dump file.

**Comment by Qchristensen** [comment] 2017-09-18 23:34
Renamed the issue as it is not specific to next builds - as noted, it happens with even older versions of NVDA, and also changing folders seem to be the most consistent way to trigger this bug.  Otherwise, I don't have an update on the issue itself.

**Comment by dkager** [comment] 2017-10-01 10:40
I can no longer reproduce this with Outlook 16.0.8431.2046. @Qchristensen could you give it a try?

**Comment by derekriemer** [comment] 2017-10-01 23:55
Sina can. Are you running insiders? maybe it needs to perkalate back in to stable builds of office.

**Comment by Qchristensen** [comment] 2017-10-02 00:14
I'm still running stable Office, so the issue is still present for me. Actually, I just checked my build number and I'm running Version 1708, build 8431.2079 which would appear to be newer than @dkager 

I did find the first time I opened Outlook this morning, I could change folders using any method for about 30 seconds and was about to agree that the issue appeared to be resolved, and then it hung, and now it seems to be hanging regularly again.

**Comment by derekriemer** [comment] 2017-10-02 00:36
That's exactly what Sina's reporting.

**Comment by dkager** [comment] 2017-10-02 05:02
> Are you running insiders?

No. Also, when I try to update Office, it says there are no updates.
Could be that if I let it sit for a while, it will revert to hanging again. Let's see!

**Comment by stickbear2015** [comment] 2017-10-02 05:55
As an interesting note to this, I switched to JAWS, and attempted to reproduce this interesting bug, and running through the entire list of steps, had no issues.
Returning to NVDA, running through each of the STR's in this ticket, outlook crashed in either one, or both of the ways previously described.
I can reproduce this under windows 10 insider, running latest outlook insider build, and windows 10 creator with latest stable outlook build.
I don't know how much help that'll be but their it is.

**Comment by comanna** [comment] 2017-10-02 07:32
I confirm that the same is happening here. I recently installed Office 365 online, which is Office 2016 delivered with a rolling-over licence so is still Office 2016 as usual.

 

I find that the reported behaviour is even more frequent in this installation of Office when NVDA 2017.3 is running. The control+shift+tab is still functioning correctly.

 

There is another Outlook issue which I will detail in a separate thread.

 

 

 

All the best,

 

Cearbhall

 

m +353 (0)833323487 Ph: _353 (0)1-2864623 e: cearbhall.omeadhra@blbc.ie

**Comment by dkager** [comment] 2017-10-06 09:13
I can once more reproduce this, and Outlook's build number didn't change.

**Comment by feerrenrut** [comment] 2017-10-17 02:12
The MS Office team has identified and fixed the bug, this will not be seen publicly until Dec.

**Comment by michaelDCurran** [comment] 2017-10-20 23:09
the internal Microsoft bug ID is: 1900286

**Comment by feerrenrut** [comment] 2018-01-15 01:10
The fix from Microsoft for this issue should have arrived by now. Expected in December. I will close this issue. If this is still affecting anyone, please leave a comment so we can investigate further.

**Closed by feerrenrut** 2018-01-15 01:10 UTC
Labels: appCrash, blocked, needsExternalFix, p1

**Comment by PratikP1** [comment] 2018-01-15 15:59
This bug should not be closed yet. The  crashes still occur.

**Comment by dkager** [comment] 2018-01-15 16:16
I can't reproduce the crash anymore.

**Comment by PratikP1** [comment] 2018-01-15 16:20
I’m afraid I was able to reproduce this three times this morning with Outlook 16.0.8431.2110. While I’m not in the Office Insider program, I am receiving early releases through the Enterprise E3 plan. It’s somewhere between Insider and general availability.

**Comment by michaelDCurran** [comment] 2018-01-15 19:29
If I understand Microsoft correctly, the fix should be seen in build 
16.0.8704.1000 or higher.

**Comment by dkager** [comment] 2018-01-15 19:33
I have build 16.0.8730.2175, 32-bit.

**Comment by Ednunp** [comment] 2018-02-19 14:39
Hi. I'm still seeing this issue as well. I'm so glad I came across it, I thought I was going mad. What's interesting for me at least is that I reproduced it with Narator as well. Currently using the control shift tab method of navigating but it's slower to move around for sure.
