### ISSUE TITLE
Dialog pronunciation is broken in Mozilla Firefox when CSS 'position' property is changed from 'fixed' to 'absolute' for the dialog element

### ISSUE THREAD

**Issue by Petroniusly** [nvaccess/nvda#9406] opened 2019-03-25 16:59 UTC
### Steps to reproduce:
Step 1: Start NVDA.
Step 2: Open provided below link using Firefox browser
Step 3: Click 'open First Modal' button.
Note, the 'dialog-label  dialog' was stopped and continue from current focused element label ('close-modal-button-label')
Link to the code example: https://codepen.io/Petroniusly/pen/PLLXJa
Link to the folder with attached files (code example, screenshot, NVDA logs): https://www.dropbox.com/sh/zywtxqjuxczqbyf/AABEXT3QidAcQLSjzsKZ1GKUa?dl=0

### Actual behavior:
NVDA start reading the dialog content data when focus is moved into it. But when position type for the dialog element is changed from 'fixed' to 'absolute':
- the text pronunciation is stopped;
- the same speech text is loaded;
- the text pronunciation is starting the pronunciation reloaded text but the first row with dialog label is skipped 

### Expected behavior:
NVDA read the dialog content once.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.4.1

#### Windows version:
1709 (OS Build 16299.967)

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 60.6.1esr - is reproduced repeatedly
Chrome 72.0.3626.121 - is not reproducible

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by DrSooom** [comment] 2019-03-25 19:36
CC: @jcsteh and @MarcoZehe

**Comment by jcsteh** [comment] 2019-03-26 00:38
Caused by https://bugzilla.mozilla.org/show_bug.cgi?id=659886
This is being worked on at the moment, but the fix is quite complicated and is likely to be several months of work.

Workaround (if feasible) is to set position absolute *before* focusing the dialog.

**Comment by Adriani90** [comment] 2020-01-11 23:20
@jcsteh the firefox bug seems fixed now. Is this issue still valid?

**Comment by jcsteh** [comment] 2020-01-12 23:55
Fixed.

**Closed by jcsteh** 2020-01-12 23:55 UTC
Labels: Firefox, needsExternalFix
