### ISSUE TITLE
allow unlabeled buttons to be labeled

### ISSUE THREAD

**Issue by Dennisl123** [nvaccess/nvda#6808] opened 2017-01-25 22:39 UTC
Hi, Please allow unlabeled buttons on websites and flash players to be labeled.  Thank you.

**Comment by leonardder** [comment] 2017-07-17 19:02
Closing as duplicate of #5874, which has associated pull requests.

**Closed by leonardder** 2017-07-17 19:02 UTC

**Comment by Dennisl123** [comment] 2017-08-20 05:47
Why was this ticket closed?

**Comment by ehollig** [comment] 2017-08-20 16:14
@Dennisl123, this issue was marked as a duplicate, as #5874, already has code contributed to this issue.

**Comment by Dennisl123** [comment] 2017-08-20 16:39
Will this be in a release soon?

**Comment by ruifontes** [comment] 2017-08-20 18:01
Hello!

For me, it seems abandoned code... last comment about code is one year 
old...

And the broad of this ticket is only for HTML objects, and not GUI 
objects...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 20 de agosto de 2017 17:14
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] allow unlabeled buttons to be labeled (#6808)



@Dennisl123, this issue was marked as a duplicate, as #5874, already has 
code contributed to this issue.
