### ISSUE TITLE
nvda displays the contents of a .pdf file in large lines

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9882] opened 2019-07-05 21:18 UTC
### Steps to reproduce:
open the attached .pdf document.
Note that when reading with arrow below the nvda read the information in large lines.
### Actual behavior:
large lines are displayed with a large amount of text, making it difficult to understand.
### Expected behavior:
I read this same document using jaws 2019 and the reader divided each information into one line making it much easier to read.
Can nvda do the same?
#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 17928
#### Windows version:
10 18362.175

#### Name and version of other software in use when reproducing the issue:
adobe reader Continuous Release | Versão 2019.012.20035
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

**Comment by fernando-jose-silva** [comment] 2019-07-05 21:19
[04072019_115511.246.pdf](https://github.com/nvaccess/nvda/files/3364025/04072019_115511.246.pdf)

**Comment by DrSooom** [comment] 2019-07-06 00:34
Duplicate of issue #7275. Related issue: #9370.

**Comment by Adriani90** [comment] 2019-07-10 16:56
Closing as duplicate.

**Closed by Adriani90** 2019-07-10 16:56 UTC
Labels: duplicate
