### ISSUE TITLE
NVDA silent after accepting auto-complete in Android Studio

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#10737] opened 2020-01-30 18:38 UTC
I'm not the original reporter, but I can reproduce this issue locally.

### Steps to reproduce:
With NVDA running and using Android studio:
- Start typing some code
- Select an item from auto-complete (Pressing `tab` to accept the item)
- Press up or down arrow.

### Actual behavior:
After accepting an item from the auto-complete list NVDA no longer speaks.
Press Alt+tab to refocus the application, NVDA speaks again.

### Expected behavior:
After accepting an item from the auto-complete list, NVDA continues to speak.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
NVDA 2019.3beta3

#### Windows version:
Windows 10. 1903

#### Name and version of other software in use when reproducing the issue:
Android Studio 3.5.3
Build #AI-191.8026.42.35.6010548, built on November 15, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

**Comment by akash07k** [comment] 2020-02-05 11:22
I can also reproduce this issue on my machine. Any fix so far?

**Comment by Adriani90** [comment] 2024-03-01 21:20
Closing as works for me, thanks for updating and testing. If anyone still has this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-03-01 21:20 UTC
Labels: close/worksforme, component/java-access-bridge
