### ISSUE TITLE
Vertical Sliders are reversed to NVDA

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#13752] opened 2022-05-30 12:20 UTC
### Steps to reproduce:
Run the following WXPython example, and try to adjust the slider with the 4 arrow keys.
```python
import wx

class MainWindow(wx.Frame):
	def __init__(self):
		super().__init__(None, title="Test")
		panel = wx.Panel(self)
		slider = wx.Slider(panel, style=wx.SL_VERTICAL)
		panel.Layout()
		self.Show()

if __name__ == "__main__":
	app = wx.App()
	wnd = MainWindow()
	app.MainLoop()
```
### Actual behavior:
UP arrow decreases the slider, down arrow increases it. Left and right arrows seem to work fine, though.
### Expected behavior:
Up arrow should increase the slider, and down arrow should decrease it, same as every other slider.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.1
#### Windows version:
Windows 10 21H1 (64-bit) build 19043.1706
#### Name and version of other software in use when reproducing the issue:
N/A (happens anywhere there's a vertical slider).
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.3.5 also had this issue.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/a, but yes

**Comment by lukaszgo1** [comment] 2022-05-30 13:15
What makes you believe this is caused by NVDA? Have you tried  these steps with Narrator or JAWS?

**Comment by CyrilleB79** [comment] 2022-05-30 15:47
The behavior is not linked to NVDA. Narrator behaves the same way.

Note that visually, the slider's cursor goes up when you press up arrow and down when you press down arrow so this is correct.

What is confusing is that the 0% is at the top of the slider and the 100% at the bottom.

This issue (if any) should be discussed with wx guys.

**Comment by CyrilleB79** [comment] 2022-06-01 08:51
I have tested with Jaws 2020. I confirm that the slider's value is increased when pressing upArrow on the contrary to NVDA. But with Jaws, the left/right arrow is also the opposit, i.e. pressing left arrow increases the slider's value what is less expected.

For this slider object when the thumb is at the bottom:
* NVDA object's properties indicate:
  `IAccessible accValue: '100'`
  This is coherent with the value 100% indicated by NVDA and Narrator for this object.
* Using script utility mode with Jaws, I can see that MSAA returns 100, while Jaws indicates a value of 0% for this object.

Thus you have two options:
1. You consider that Jaws' reported value is the good one. Then you should ask Microsoft why they report 0 via MSAA and Narrator.
2. You consider that Microsoft's reported value is the good one. Then you should close this issue and ask Freedom Scientific why they do not follow MSAA value.

Regarding ZDSR, I do not know it at all.

**Comment by seanbudd** [comment] 2022-06-02 06:22
Agreed with @CyrilleB79, we are following the spec here. Please follow steps 1 or 2.

**Closed by seanbudd** 2022-06-02 06:22 UTC

**Comment by feerrenrut** [comment] 2022-06-02 06:31
Different issue, but perhaps related to #13230
