### ISSUE TITLE
working in browsers is broken after restart of NVDA

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7523] opened 2017-08-25 16:33 UTC
Hi,

I know, possibly there is already simular issue, however I'm going to file this:

### Steps to reproduce:

1. go to browser (tested in Firefox)
2. restart NVDA (with shortcut defined on a desktop or in a InputGesture)

### Expected behavior:

NVDA is going to work in browsers as before restart especially when update process is finnished.

### Actual behavior:

Browse mode is not working, focus mode is broken either.

As I observed, it works correctly when NVDA has been started, when other programs were in foreground (e.g. wordpad) or all windows were minimised, when the process of updating has started or NVDA was needed to be restarted for other reason.

### System configuration:
NVDA version:
next from yesterday and today is 14342 ...

NVDA Installed or portable:
installed
Other information:

latest stable firefox (32-bit)

Windows version:
w10x64 15063

### Other questions:

Does the issue still occur after restarting your PC?

no, restarting firefox solves an issue.

Have you tried any other versions of NVDA?

Yes, this problem has been actual since one of next snapshot in development phase of 2017.3 or 2017.2 was released. I thought, that some days ago it was fixed, but it seems, that I missed something.

Thanks.

**Comment by leonardder** [comment] 2017-08-26 08:57
Closing as duplicate of #7269

**Closed by leonardder** 2017-08-26 08:57 UTC

**Comment by Brian1Gaff** [comment] 2017-08-26 21:45
Normally in Windows 7, when you do restart nvda, firefox is not in focus 
when it comes up, so the problem never is seen.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
