### ISSUE TITLE
Crash of the latest alpha NVDA builds on a system with Russian locale

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#12160] opened 2021-03-13 11:34 UTC
### Steps to reproduce:
Download and run the installation package of the latest NVDA alpha builds.
### Actual behavior:
The sound of the temporary copy of NVDA starting is played, after which it crash
### Expected behavior:
The temporary copy of NVDA should start correctly when the launcher starts
#### NVDA installed/portable/running from source:
Occurs when the installation package is started
#### NVDA version:
alpha-21882,528d5708 and higher
#### Windows version:
Windows 10 version 1809
#### Other information about your system:
The problem is reproduced if the Russian language of the interface is selected in the system parameters. If change the language to English and log in again, the problem disappears and NVDA start correctly.
NVDA log is interrupted on the wxPython version, probably the crash occurs when creating an instance of wx.App.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Problem appeared in new NVDA builds with Python 3.8 and WXPython 4.1.1
#### If add-ons are disabled, is your problem still occurring?
Yes
[nvda-old.log](https://github.com/nvaccess/nvda/files/6134690/nvda-old.log)

**Comment by kvark128** [comment] 2021-03-15 06:48
The same problem occurs when running NVDA from source code with Python 3.8.8.
[nvda.log](https://github.com/nvaccess/nvda/files/6139295/nvda.log)

**Comment by josephsl** [comment] 2021-03-15 07:00
Hi, likely caused by C locale problem, hopefully should be fixed with wxPython 4.1.2 (under development; I and several wxPython users and Robin had a conversation about this issue a while back). Thanks.

**Comment by kvark128** [comment] 2021-03-18 07:22
How soon is wxPython expected to update to version 4.1.2? Due to this issue, I can't test my addons for compatibility with the new NVDA versions.

**Comment by josephsl** [comment] 2021-03-18 07:42
Hi, maybe a few weeks to months, as it depends on what Robin says. Thanks.

**Comment by lukaszgo1** [comment] 2021-03-18 11:00
@josephsl Is the problem with the C Locale that you've mentioned fixed in the development version of WX Python already?

**Comment by seanbudd** [comment] 2021-03-24 03:47
I can't reproduce this on `alpha-21882,528d5708` nor using the latest alpha `alpha-22086,0316158b`. I'm running Windows 10 and using the main Russian locale for my windows VM. Are you using a different Russian dialect?

**Comment by kvark128** [comment] 2021-03-25 17:59
I use the ru_RU locale. Here is my research in the Python 3.8.8 console:
>>> import wx, locale
>>> locale.getdefaultlocale()
('ru_RU', 'cp1251')
>>> locale.getlocale()
('Russian_Russia', '1251')
>>> app = wx.App()
>>> locale.getlocale()
('ru_RU', 'UTF-8')
Creating an instance of wx.App for some reason changes the encoding of the current locale, which probably later causes a failure when trying to write to the NVDA log. NVDA crashes with the exit code 0xc0000374.
I commented out call the locale.setlocale function in the InitLocale method of wx.App, after which NVDA from the source code now starts without errors.

**Comment by seanbudd** [comment] 2021-03-25 23:26
Thanks @kvark128 

Sounds like #12214 should fix this

**Comment by kvark128** [comment] 2021-03-26 13:07
wxPython version 4.0.3 does not change the current locale, but I can do it manually in the Python console of NVDA 2020.4 and the same crash will occur:
```
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "ru_RU")
'ru_RU'
>>> log.info("test")
```
When trying to write to the log, NVDA immediately crashes.

**Comment by kvark128** [comment] 2021-03-29 20:55
It looks like the cause of the problem is UCRT, as described in this issue:
https://bugs.python.org/issue36792
These commands in the Python console of NVDA 2020.4 I have also causes heap corruption and crash:
import locale, time
locale.setlocale(locale.LC_ALL, 'ru_RU')
time.localtime(time.time())

**Comment by seanbudd** [comment] 2021-03-30 01:51
Hi @kvark128, I've tried to build a workaround for this which reverts to previous behaviour around setting the python locale to match the Windows one rather than the translation service - do you mind testing this build using the "User Default" system language like before? https://ci.appveyor.com/api/buildjobs/ymaxrabvfmfmxk1m/artifacts/output%2Fnvda_snapshot_try-fix-ru-locale-22193%2C2e816544.exe

Sorry for all the difficulties - it's just strangely impossible to reproduce this on my Russian Windows VM.

**Comment by kvark128** [comment] 2021-03-30 15:27
As a workaround, this problem is solved by the following code, which must be inserted before initializing the NVDA log:
```
try:
	lang, enc = locale.getdefaultlocale()
	locale.setlocale(locale.LC_ALL, lang)
except:
	pass
```
It is important that this code is executed before attempts to write to the log, otherwise the crash will occur again. It looks like errors when working with memory somewhere inside UCRT.

**Comment by CyrilleB79** [comment] 2021-03-31 06:31
I am also facing this issue on two computers running Windows 10 1809 French UI.
Strangely, this issue has only appeared a few days ago. And I am not able to run Py3.8 build that I were previously able to run on the same machines. Probably due to an update?




@kvark128 you write:
> As a workaround, this problem is solved by the following code, which must be inserted before initializing the NVDA log:
> 
> ```
> try:
> 	lang, enc = locale.getdefaultlocale()
> 	locale.setlocale(locale.LC_ALL, lang)
> except:
> 	pass
> ```
> 
> It is important that this code is executed before attempts to write to the log, otherwise the crash will occur again. It looks like errors when working with memory somewhere inside UCRT.

Could you please explain where exactly you paste this code? Thanks.

**Comment by kvark128** [comment] 2021-03-31 12:30
> Could you please explain where exactly you paste this code? Thanks.

This should be inserted into the nvda.pyw file, before calling logHandler.initialize(). NVDA should be run from the source code.

**Comment by lukaszgo1** [comment] 2021-04-06 17:10
@CyrilleB79  @kvark128 Could you please test [this build](https://ci.appveyor.com/api/buildjobs/ala1b23m47rpp25a/artifacts/output%2Fnvda_snapshot_pr12250-22254%2Cfd7e1bf8.exe) and if you are able to run from sources branch I12160 of my fork just to make sure that there are no differences between binary and source copies.

**Comment by kvark128** [comment] 2021-04-06 19:41
Yes, I confirm that this build starts and working correctly. Code from branch I12160 also does not cause a crash. Many thanks.

**Comment by CyrilleB79** [comment] 2021-04-06 20:18
> @CyrilleB79 @kvark128 Could you please test [this build](https://ci.appveyor.com/api/buildjobs/ala1b23m47rpp25a/artifacts/output%2Fnvda_snapshot_pr12250-22254%2Cfd7e1bf8.exe) and if you are able to run from sources branch I12160 of my fork just to make sure that there are no differences between binary and source copies.

I have tested the snapshot you reference in your comment above (nvda_snapshot_pr12250-22254,fd7e1bf8.exe) as well as the head of your PR's branch (commit b2eaf4fdc1f556725c728418059c4590fc15b0c1) from source.
Both are starting and working correctly.

Good job! Thanks to you @lukaszgo1  and to @kvark128.

**Closed** 2021-04-09 00:22 UTC
Labels: bug/crash

**Comment by lukaszgo1** [comment] 2021-08-19 20:14
@CyrilleB79  @kvark128  While #12250 fixed this particular crash the underlying cause still was not fixed. I believe I've understood the problem and fixed the root cause in #12753. Would you be able to test [this try build](https://ci.appveyor.com/api/buildjobs/3lkyc46av7tajt2s/artifacts/output%2Fnvda_snapshot_pr12753-23607%2C12afb0c9.exe) and branch correctWinLocales of my fork on machines which were causing you troubles? Also if you're able to start from sources I'd appreciate if you could let me know if unit tests from this branch can pass as it was a real pain to make them work reliably across the range of Windows versions NVDA supports.

**Comment by CyrilleB79** [comment] 2021-08-24 21:59
Hello
Unfortunately I read this message just too late. Both machines where the issue occurred now run Windows 10 20H2. One was completely reinstalled in May 2021 and the second one has just been migrated from Windows 10 1809 to 20H2 earlier today...
I may however perform the tests if you feel it is worth. Not sure however if I can try the unit tests since I do not have Visual Studio on these machines.

I have also just tested the try build on a third machine running Windows 10 2004 (64-bit) build 19041.388 and all is running well. I may try from source and run the unit tests on this machine if you feel it is worth. But this third machine did not exhibit the crash described in this issue at the time.

For information, all the three machines run a French Windows.

**Comment by lukaszgo1** [comment] 2021-08-25 09:10
> I may however perform the tests if you feel it is worth. Not sure however if I can try the unit tests since I do not have Visual Studio on these machines.

If you would be able to execute Unit tests that would be appreciated - they should not require VS to be installed.
