### ISSUE TITLE
issue with app kindle for pc.

### ISSUE THREAD

**Issue by Lucas028** [nvaccess/nvda#14501] opened 2023-01-03 03:22 UTC
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Actual behavior:
The continuous reading is pausing.
### Expected behavior:
When pressind NVDA key + down, it should read the whole book in app kindle.
#### NVDA installed/portable/running from source:
2022.4
#### NVDA version:
NVDA 2022.4
#### Windows version:
Windows 11.
#### Name and version of other software in use when reproducing the issue:
Amazon Kindle for PC.
#### Other information about your system:
Windows 11, 64 bit.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, all other versions work well.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by ivnc** [comment] 2023-01-03 21:59
Probably duplicate of #14390.

**Comment by seanbudd** [comment] 2023-01-03 23:12
Closing as duplicate

**Closed by seanbudd** 2023-01-03 23:12 UTC
