### ISSUE TITLE
No Feedback when Changing Virtual Desktops in Windows 10

### ISSUE THREAD

**Issue by jage9** [nvaccess/nvda#6264] opened 2016-08-14 20:40 UTC
Windows 10 offers virtual desktops, allowing a user to switch between desktop windows. When hotkeys are pressed which change the current virtual desktop, or other events cause the virtual desktop to change, the new desktop should be announced. These hotkeys include
Control+Win+Right: move to next virtual desktop
Control+Win+Left: move to previous virtual desktop
Control+Win+D: Create a new virtual desktop
Control+Win+F4: Close the current virtual desktop

Windows+Tab can also be used to switch virtual desktops, and there are likely non-keyboard ways to do this as well.

**Comment by jcsteh** [comment] 2016-08-17 00:09
Duplicate of #5641.

**Closed by jcsteh** 2016-08-17 00:09 UTC
Labels: duplicate
