### ISSUE TITLE
MSWord 2007 - Did not modify the document when spelling errors are checked, even though the Save As dialog box is displayed

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4745] opened 2014-12-23 04:24 UTC
**Reported by advck1123 on 2014-12-23 04:24**
str
1. Press NVDA+Control+D Document Formatting setting dialog then 'report spelling errors' item is checked and NVDA+N -> Save configuration.
2. Open MSWord attach file.
3. Press ALT+F4

Save dialog is displayed.
I'am using MSWord 2007 for Korean version and WINDOWS7 64bit system.
Please fix this issue.
Thanks.

**Comment by bhavyashah** [comment] 2017-08-19 08:53
I don't follow. If the reporting of spelling errors in NVDA is checked, how does that affect a Save dialog in Word? Unless anyone can make more sense of this ticket independently, since the original author of this ticket can no longer be contacted, I suggest closing. @ehollig

**Comment by ehollig** [comment] 2017-08-19 21:57
I do not quite follow either.
### Testing performed

1. Restart NVDA
2. Ensure Spelling errors is checked in the Document Formatting dialog.
3. Open the attached document.
4. Arrow around the document, ensuring not to make modifications.
5. Press Alt+F4
### Expected and Actual Behaviour
Word closes without a save dialog.

Although, this could also be a Duplicate of #949. Closing

**Closed by ehollig** 2017-08-19 21:57 UTC
Labels: bug, Microsoft Office support

**Comment by Brian1Gaff** [comment] 2017-08-20 08:42
Two things here.
 This is not confined to 2007, as I've seen it back in 2003. I seem to 
recall there are several scenarios
1. Even without modification to the file, word thinks its different to the 
loaded file and prompts to save the changes.
 This is a very long running issue, and I don't think anyone has managed to 
figure out why some files do it and others do not. This implies that nvda 
being there affects the changes detection of Word.
 The other issue is that you can do all you have said, and change spelling 
errors when the spellcheck is run after the file is typed. and some 
substitutions do not get fixed or worse are added as well as the faulty 
version in the file. Once again its apparently random. I did wonder if 
perhaps there is some kind of pop up sometimes that we are not seeing that 
asks if you want to have both, but is this really likely?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
