### ISSUE TITLE
Can't open .pdf files with windows 11

### ISSUE THREAD

**Issue by Nathanja94** [nvaccess/nvda#13114] opened 2021-12-01 14:15 UTC
### Steps to reproduce:

Select a .pdf file
Press enter.

### Actual behavior:

[nvda.log](https://github.com/nvaccess/nvda/files/7634368/nvda.log)

### Expected behavior:

The .pdf file opens.

#### NVDA version:

2021.2 2021.3betea2 and 2021.3rc1

#### Windows version:

Windows 11 pro version 21H2

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I got the same reaction with all three mentioned version.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by cary-rowen** [comment] 2021-12-01 14:20
What software did you try to open, I didn't see it.

**Comment by lukaszgo1** [comment] 2021-12-01 15:12
Duplicate of #12920

**Closed** 2021-12-01 17:23 UTC
