### ISSUE TITLE
Focus switches to tabindex="-1" parent element on in-page link navigation

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#10059] opened 2019-08-08 16:34 UTC
### Steps to reproduce:

1. Open Firefox
2. Navigate to https://output.jsbin.com/yibacazuda
3. Tab navigate to "Link to target div"
4. Activate the link
5. Press Tab again

### Actual behavior:
Focus switches to "Link at top of main". This is because NVDA has switched focus to the parent element with tabindex="-1" after activating the link. This does not reproduce if NVDA is not running.

### Expected behavior:
Focus switches to "Link in target div".

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by ndarilek** [comment] 2021-12-22 19:04
I think this may be related. I'm finding that NVDA focuses elements with `tabindex="-1"` generally even though the specs don't indicate this.

See the attached HTML document with three `<h1/>` elements. The center `<h1/>` specifies `tabindex="-1"`. Under NVDA, I can open this document, press Ctrl-Home, and tab to the second heading even though I shouldn't be able to. Under Narrator this doesn't happen.

Thanks.

Update: GitHub won't let me attach the HTML I used to test for some reason. Here it is inline:

```html
<!DOCTYPE html>
<html>

<body>
    <h1>First non-focusable header</h1>
    <h1 tabindex="-1">Second non-focusable header</h1>
    <h1>Third non-focusable header</h1>
</body>

</html>
```

**Comment by Adriani90** [comment] 2024-06-28 21:45
@ndarilek this is not really related, tabindext=-1 elements are focusable only in browse mode when pressing tab key. @jcsteh what is the reason NVDA focuses tabindex=-1 elements in the virtual document on tab press?

**Comment by Adriani90** [comment] 2024-06-28 21:47
By the way, the issue description is referencing to Firefox, but in Firefox 127 with NVDA 2024.2 this issue is not reproducible anymore.
However, it is still reproducible in Chromium. I think we have to open an issue with Chromium for this.

**Comment by jcsteh** [comment] 2024-06-29 00:01
> what is the reason NVDA focuses tabindex=-1 elements in the virtual document on tab press?

See my explanation in https://github.com/nvaccess/nvda/issues/8906#issuecomment-2136345496.

**Comment by Adriani90** [comment] 2024-11-11 13:48
Closing as duplicate of #8906.

**Closed by Adriani90** 2024-11-11 13:48 UTC
Labels: close/duplicate
