### ISSUE TITLE
NVDA is way too verbose when autocomplete list on GitHub appears

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#11305] opened 2020-06-26 22:12 UTC
### Steps to reproduce:
With focus focusable elements disabled:
1. Open https://github.com/nvaccess/nvda/issues/new?template=bug_report.md
2,, Move to the commend body edit field.
3. Switch to focus mode, type @ and start typing "jcsteh"

### Actual behavior:
After one or more letters is being typed NVDA repeats entire focus ancestry before announcing the autocomplete item which gains focus.
For example:
"New Issue · nvaccess/nvda - Firefox Nightly
unknown
New Issue · nvaccess/nvda - Firefox Nightly
New Issue · nvaccess/nvda - Firefox Nightly
New Issue · nvaccess/nvda  document
main landmark
list
"

### Expected behavior:
No repetition of the focus ancestry similar to what happens with focus focusable elements enabled.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA version alpha-20400,675c4c54
#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 79
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring? 
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Not relevant

**Comment by Adriani90** [comment] 2020-06-26 23:22
Does it make a difference if you enable attempt to cancel speech in nvda‘s advanced settings?

**Comment by leonardder** [comment] 2020-06-27 09:06
@jcsteh Any idea what could clarify this?

**Comment by leonardder** [comment] 2020-06-27 09:07
I marked this regression, as focus focusable elements is now the default.

**Comment by Adriani90** [comment] 2020-06-27 10:15
This seems also reproducible with attempt to cancel speech activated. I thought it might make a difference but it does not.

**Comment by lukaszgo1** [comment] 2020-06-27 10:42
While having focus focusable elements disabled makes this happen more frequently I've succeeded in reproducing this even with this option enabled once or twice.

**Comment by Neurrone** [comment] 2020-06-30 13:28
I'm also able to observe this when playing around with the `<select>` example on [MDN's page for the <select> element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)

Here's some speech output where I am in the select element and choose a new option.

```
Choose a pet:  combo box  Hamster  collapsed
combo box  expanded
Hamster  list
Hamster  4 of 7
Parrot  5 of 7
<select> - HTML: Hypertext Markup Language | MDN  document
main landmark
article
MDN Web Docs Interactive Example  frame
MDN Web Docs Interactive Example  document
Choose a pet:  combo box  Parrot  collapsed
```

Notice the extra 5 lines of focus ancestry that gets announced

It also only seems to be happening for me in Firefox, so maybe this could be a Firefox issue.

**Comment by jcsteh** [comment] 2020-07-01 00:58
> With focus focusable elements disabled:

This isn't related to focus focusable elements disabled, so it isn't a regression. I can also reproduce it with that enabled.

>     1. Open https://github.com/nvaccess/nvda/issues/new?template=bug_report.md
>        2,, Move to the commend body edit field.
> 
>     2. Switch to focus mode, type @ and start typing "jcsteh"
> 
> 
> ### Actual behavior:
> 
> After one or more letters is being typed NVDA repeats entire focus ancestry before announcing the autocomplete item which gains focus.

I'd guess the reason this happens is that GitHub focuses an autocomplete item, but then rebuilds the autocomplete list so that the item it just focused dies. It then focuses the new item once the list is rebuilt. Unfortunately, the old (dead) focus event is still queued, so NVDA processes it and gets back an invalid object, which screws up the focus ancestry. The invalid object is why you hear "unknown".

The correct fix is for GitHub not to do this. Realistically, this probably isn't going to happen.

The workaround on the NVDA side would be to ignore focus events on invalid objects. That's trickier than it sounds. Because of the way MSAA is designed, it's difficult to be certain that the object is invalid. Also, we don't always want to ignore invalid focus, since sometimes, it at least tells the user that focus got lost somewhere. It's better to hear "unknown" than to think focus is still somewhere it isn't.

I guess NVDA could set some kind of timeout if it detects invalid focus and only report it if there isn't another focus event within the timeout. That's getting pretty complicated, though.

**Comment by jcsteh** [comment] 2020-07-01 01:00
> I'm also able to observe this when playing around with the `<select>` example on [MDN's page for the `<select>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select).

I can't reproduce this. I'd suggest you file a new issue for this, including the exact steps to reproduce and version information. Please CC me. Thanks.

**Comment by leonardder** [comment] 2020-07-03 06:50
I removed the regression label and updated the issue title based on https://github.com/nvaccess/nvda/issues/11305#issuecomment-652124886

**Comment by Adriani90** [comment] 2023-04-01 23:12
This is not reproducible anymore with Firefox 111 and NVDA Version: alpha-27981,51aacac6 (2023.2.0.27981). Closing as works for me. Please comment if you are still having it and we can reopen.

**Closed by Adriani90** 2023-04-01 23:12 UTC
Labels: close/worksforme, feature/browse-mode
