### ISSUE TITLE
[Word] RTT flags not announced 

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#8291] opened 2018-05-16 06:37 UTC
###Steps to reproduce:
1.	create a cloud document and share by creating an anonymous link
2.	Paste the link into an incognito web browser
3.	once the document loads, start typing in the content
4.	back in Win32 Word, move your cursor such that NVDA reads the line where the RTT flag is present (where the user in the web browser is typing)

### Expected behavior:
I should hear "Author" or the author's name or something indicating another user is present in the document there

### Actual behavior:
When I come across an RTT flag while reading text, I do not hear presence.
Note: sometimes I hear "inserted" and "end inserted" so in some cases it may be announcing the wrong thing but at the right time

### System configuration:
NVDA version: 2018.1.1
App Name: Word
NVDA Installed or portable: Installed
**Other information:**
Windows version:
> Example: Windows 10 Version 1803 Build 17134.48
Name and version of other software in use when reproducing the issue:

### Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No
> Please list them and the result

**Comment by Adriani90** [comment] 2020-05-08 19:26
Closing as duplicate of #2150.

**Closed by Adriani90** 2020-05-08 19:26 UTC
Labels: close/duplicate
