### ISSUE TITLE
NVDA not using aria-valuemax

### ISSUE THREAD

**Issue by thbt** [nvaccess/nvda#6906] opened 2017-02-22 10:28 UTC
NVDA only seems to read the aria-valuenow attribute, and ignore the aria-valuemax value. For example, if I have a progress-bar with `aria-valuenow=150` and `aria-valuemax=200`, it will read `150`, and if I have a progress-bar with `aria-valuenow=150` and `aria-valuemax=150`, it will also read `150`, the end user have no indication of the current progress.

**Comment by feerrenrut** [comment] 2017-02-22 15:25
Could you provide a test case for this (self contained and zipped html file) or example on jsfiddle or a similar service?

**Comment by thbt** [comment] 2017-02-22 16:38
Sure thing : [JSFiddle](https://jsfiddle.net/yc9sjp8b)

**Comment by feerrenrut** [comment] 2017-02-23 16:24
Thanks.
Using Version: next-13881,c025b508 I can reproduce this. 

The [JSFiddle](https://jsfiddle.net/yc9sjp8b) reads:
- "progress bar 25"
- "progress bar 50"
- "progress bar 150"
- "progress bar 150"

When viewed as a percentage, these would be 25%, 50%, 75%, 100%. Perhaps instead NVDA could output:
- "progress bar 25 of 100 25%"
- "progress bar 50 of 100 50%"
- "progress bar 150 of 200 75%"
- "progress bar 150 of 150 100%"

@jcsteh what do you think? Perhaps this could be addressed with the aria project?

**Comment by feerrenrut** [comment] 2017-02-23 16:27
[Aria documentation](https://www.w3.org/TR/wai-aria/complete#aria-valuemax) This does not seem to be new in aria 1.1

**Comment by jcsteh** [comment] 2017-03-07 01:27
- The need for max has been mentioned, but not min. If min is 100, now is 200 and max is 300, "200 of 300" is incorrect. Arguably, it's even worse, since now you're misleading the user (as opposed to assuming the min and max can be determined some other way).
- Constantly hearing "200 minimum 100 maximum 300" is going to be extremely annoying for the user, especially for progress bars.
- For sliders:
 * I think the min and max should be reported when the slider gets focus, not when the value changes. So, you might hear "slider minimum 100 maximum 300 value 200". This eliminates extraneous verbosity.
 * If valuetext is present, only valuetext should be reported, none of the others.
- For progress bars:
 * We should certainly normalise the values for progress bar beeps.
 * We should consider always normalising to a percentage even for speech. There's no opportunity to report the minimum and maximum just once for a progress bar like there is for sliders (since progress bars don't get focus). Continually reporting them is just not an option; the verbosity would be insane.

**Comment by Dan503** [comment] 2018-07-24 07:16
Another use case: 

- `role="progressbar"`
- Step 1 of 5
- Updates step progress dynamically as the user fills in questions
- `aria-valuemin="1"`
- `aria-valuemax="5"`
- `aria-valuenow="1"`

If `aria-valuenow` hits a value of `5` NVDA currently treats it like the user is only 5% through the form. In reality NVDA should treat it like they are 100% through the form.

**Comment by Adriani90** [comment] 2024-11-28 21:41
The same applies probably also for spin buttons and other elements with mina nd max values.

I am closing in favor of #16678 which contains technical information on how to start implementing this.

**Closed by Adriani90** 2024-11-28 21:41 UTC
Labels: close/duplicate, ARIA, p4
