### ISSUE TITLE
Impossible to use the search field in google chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6988] opened 2017-03-17 20:52 UTC
Good afternoon.
I believe the following call has to do with the so-called # 6976.
When you try to use the search field on the site:
Https://blogs.windows.com/windowsexperience/#7OmwzMWtRTdKuYdD.97
The nvda pronounce clickable in the place where we could insert the text to look for, and I could not of even one form to insert the text to look for.
Using the nvda next 13931 and the chrome 57.
Using firefox the search field is displayed and you can search.
Follow the log:

IO - inputCore.InputManager.executeGesture (17:51:17):
Input: kb(laptop):downArrow
IO - tones.beep (17:51:17):
Beep at pitch 220, for 80 ms, left volume 50, right volume 50
IO - speech.speak (17:51:17):
Speaking [u'bot\xe3o', u'Submit']
IO - inputCore.InputManager.executeGesture (17:51:19):
Input: kb(laptop):upArrow
IO - tones.beep (17:51:19):
Beep at pitch 226.446492062, for 80 ms, left volume 50, right volume 50
IO - speech.speak (17:51:19):
Speaking [u'clic\xe1vel']
IO - inputCore.InputManager.executeGesture (17:51:21):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (17:51:22):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x0986ADD0>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (1052, 176, 15, 16)
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 2132) at address 92e0150>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'57.0.2987.98'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 525346
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 219824896
windowStyle: 1445986304
windowThreadID: 7792
windowText: u'Chrome Legacy Window'
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x111250d0 at 9170440>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=525346, objectID=-4, childID=-447
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by derekriemer** [comment] 2017-04-25 10:09
Hi: can you still reproduce this? In canary, I seem to be unable to reproduce this, so maybe Google fixed it.

**Comment by fernando-jose-silva** [comment] 2017-04-25 15:53
I did more tests.
On a machine with windows 10 15063 64bit and chrome 58 64bit I did not have the problem.
Now on a machine with windows 7 64bit and chrome 58 64bit I had the same problem described.
On both machines I now have the nvda master 13996.
On the machine with windows 10 I have another problem in the search field. The first time I open the windows experience page as long as I am typing the search, nvda exits the focus mode and goes to the browsing mode. This does not only occur in the search field on this page, but also in other text editing fields . If I return to focus mode the problem does not return to happen until I open another page with a text edit field or close the chrome.
I also tested the add-ons deactivated and the problem continued.

I'll put another log when this problem automatically exits from focus mode occurs.

Input: kb(laptop):space
IO - speech.speakTypedCharacters (12:40:08):
typed word: problemas
IO - speech.speak (12:40:08):
Speaking [u'problemas']
IO - speech._speakSpellingGen (12:40:08):
Speaking character u'espa\xe7o'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2WindowHandle (12:40:08):
IAccessible2::windowHandle failed: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (12:40:08):
Resorting to WindowFromPoint on accLocation
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible.__init__ (12:40:08):
accLocation failed: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.__call__ (12:40:08):
Invalid NVDAObject: Can't get a window handle from IAccessible
Stack trace:
  File "nvda.pyw", line 195, in <module>
  File "core.pyc", line 391, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 362, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 61, in _queueEventCallback
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 207, in event_valueChange
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\ReportLastProgressBarValue\globalPlugins\ReportLastProgressBarValue.py", line 27, in event_valueChange
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\ferna\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 650, in event_valueChange
  File "eventHandler.pyc", line 97, in next
  File "eventHandler.pyc", line 117, in gen
  File "NVDAObjects\__init__.pyc", line 343, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 19, in getTreeInterceptor
  File "NVDAObjects\IAccessible\chromium.pyc", line 33, in __contains__
  File "browseMode.pyc", line 1443, in _isNVDAObjectInApplication
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 475, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 913, in _get_parent
  File "NVDAObjects\__init__.pyc", line 71, in __call__
IO - speech.speak (12:40:08):
Speaking [u'Google Tradutor  documento']
IO - speech.speak (12:40:08):
Speaking [u'edi\xe7\xe3o  multilinha', u'problemas ']
IO - speech.speak (12:40:08):
Speaking [u'Google Tradutor  documento']
IO - speech.speak (12:40:08):
Speaking [u'problemas ']
IO - inputCore.InputManager.executeGesture (12:40:17):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (12:40:17):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x0A7791D0>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 7760) at address 4f002b0>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'58.0.3029.81'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 198978L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 228045752
windowStyle: 1445986304
windowThreadID: 11388
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible2) ptr=0x9a9a57c at a7fb3f0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=198978, objectID=-4, childID=-865
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 windowHandle: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 uniqueID: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 role: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 states: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible2 attributes: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by bhavyashah** [comment] 2017-07-22 18:02
On a Windows 8.1 64 bit system, I was unable to reproduce this bug in Chrome 59 stable with NVDA version 2017.2 installed. The edit field appeared alright.

**Comment by fernando-jose-silva** [comment] 2017-07-22 19:42
Unfortunately I still have this problem on windows 7. If I can help I'm at ease.

Enviado do meu iPhone

> Em 22 de jul de 2017, às 15:02, bhavyashah <notifications@github.com> escreveu:
> 
> On a Windows 8.1 64 bit system, I was unable to reproduce this bug in Chrome 59 stable with NVDA version 2017.2 installed. The edit field appeared alright.
>

**Comment by bhavyashah** [comment] 2017-07-29 09:45
Could you please assist in troubleshooting this (possibly-related-to-Project-Webfix) issue? @jcsteh @feerrenrut @leonardder

**Comment by fernando-jose-silva** [comment] 2017-07-29 14:53
Unfortunately I'm not a programmer, I'm a nvda user, I can contribute with tests.
Thank you so much for the great work.

**Comment by feerrenrut** [comment] 2017-07-31 08:20
@fernando-jose-silva , In your most recent log I noticed that you have some addons enabled. Could you please disable these addons, and try this again. This can be done by selecting the "restart with addons disabled" option when quiting NVDA. Please report back on the result of this.

**Comment by fernando-jose-silva** [comment] 2017-07-31 12:41
Thank you very much.

I ran the tests again, and to my surprise I did not have the problem anymore, the search field was located by walking with the arrow keys and pressing the letter e.

I do not know for sure what has changed from the previous week to today.

Actually nvda usually every Friday, and I am currently with the nvda master 14241.

The chrome is with automatic updates on, but I do not know if it updated from the previous week to today.

Finally windows is also with automatic updates turned on, but as it is a corporate machine do not know what was updated this week.

In the end, a strange problem that was solved.

Thank you very much for your interest in investigating.

 

De: Reef Turner [mailto:notifications@github.com] 
Enviada em: segunda-feira, 31 de julho de 2017 05:20
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Impossible to use the search field in google chrome (#6988)

 

@fernando-jose-silva <https://github.com/fernando-jose-silva>  , In your most recent log I noticed that you have some addons enabled. Could you please disable these addons, and try this again. This can be done by selecting the "restart with addons disabled" option when quiting NVDA. Please report back on the result of this.

**Comment by jcsteh** [comment] 2017-07-31 23:37
Thanks for the update! Closing.

**Closed by jcsteh** 2017-07-31 23:37 UTC
