### ISSUE TITLE
The screen reader does not announce the link as a link. 

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#14623] opened 2023-02-10 11:46 UTC
<html>
<body>
<p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><b style="box-sizing: border-box;">PWD Impact: </b></p><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;">Users who rely on the screen reader get confused as the screen reader does not announce the links as a link. </p><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><b style="box-sizing: border-box;">Test Environment:​ </b></p><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;">OS: Windows 11 (OS Build 22000.258) </p><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><b style="box-sizing: border-box;">Browser:</b><span> </span>Microsoft Edge-Version 95.0.1020.40 (Official build) (64-bit)</p><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><b style="box-sizing: border-box;">Tool used:<span> </span></b>NVDA</span></span><br style="box-sizing: border-box;"></div><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><b style="box-sizing: border-box;">URL:</b> <a href="https://msit.powerbi.com/groups/me/apps/c9b0d557-3804-4d7c-a877-168552a900bc/reports/99c8fac6-34e6-42a8-8a06-2300b3e9be1e/ReportSection3a874e85123a53682590?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">https://msit.powerbi.com/groups/me/apps/c9b0d557-3804-4d7c-a877-168552a900bc/reports/99c8fac6-34e6-42a8-8a06-2300b3e9be1e/ReportSection3a874e85123a53682590?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47</a></p><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0cm 0cm 8pt; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><br style="box-sizing: border-box;"></p><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;">

Description | Details
-- | --
Bug ID and Bug URL | Bug 9267621:https://microsoftit.visualstudio.com/OneITVSO/_workitems/edit/9267621
Title | [Screen readers - ServiceMaturityModel] - The screen reader does not announce the link as a link.
Severity | Severity-3
Application/Product Impacted | URL: https://msit.powerbi.com/groups/me/apps/c9b0d557-3804-4d7c-a877-168552a900bc/reports/99c8fac6-34e6-42a8-8a06-2300b3e9be1e/ReportSection3a874e85123a53682590?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47
Description | Whenever focus lands on the links by screen reader, Screen Reader is not announcing the link as links.
Does eDAD and external parties have access to the environment/test app to repro? | Do reach out to us if there are any access issues.
Environment (OS, Application, Versions) | OS: Windows 11 (OS Build 22000.258) Browser: Microsoft Edge-Version 95.0.1020.40 (Official build) (64-bit),
AT (include version number) | NVDA
Repro Steps | Step 1: Open the above URL on Edge Browser Step 2: Navigate to Entity Details page. Step 3: In the entity details page, navigate Assessment Details table. Step 4: Verify whether the screen reader announces the links as a link.
Screenshots/Videos | PFA video < 1.3.1-The screen reader does not announce the link as a link>PFA <1.3.1-The screen reader does not announce the link as a link.png>
Actual Results | The screen reader does not announce the link as a link.
Expected Results | The screen reader is expected to read out the content present on the page appropriately.

<br style="box-sizing: border-box;"></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><b style="box-sizing: border-box;"><span style="box-sizing: border-box;">Repro steps</span></b><br style="box-sizing: border-box;"></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><p style="box-sizing: border-box; font-size: 12pt; font-family: &quot;Times New Roman&quot;, serif; margin: 0cm; background: white;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 11pt; font-family: Calibri, sans-serif;"></span></span></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><b style="box-sizing: border-box;">Step 1:<span> </span></b>Open the above URL on Edge Browser<b style="box-sizing: border-box;"> </b></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><span style="box-sizing: border-box; font-weight: bold;">Step 2:<span> </span></span>Navigate to Entity Details page.<b style="box-sizing: border-box;"> </b></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><span style="box-sizing: border-box; font-weight: bold;">Step 3:<span> </span></span>In the entity details page, navigate Assessment Details table.<b style="box-sizing: border-box;"> </b></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><span style="box-sizing: border-box; font-weight: bold;">Step 4:<span> </span></span>Verify whether the screen reader announces the links as a link.</p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><b style="box-sizing: border-box;"><b style="box-sizing: border-box;"><span style="box-sizing: border-box;">Actual Result:</span></b></b></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><b style="box-sizing: border-box;"></b></p><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;"><span style="box-sizing: border-box;">The screen reader does not announce the link as a link. </span></p><b style="box-sizing: border-box;"><b style="box-sizing: border-box;"><span style="box-sizing: border-box;">Expected Result:</span></b></b></span></span></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><p style="box-sizing: border-box; margin: 0cm 0cm 8pt;">The screen reader is expected to read out the content present on the page appropriately. <span style="box-sizing: border-box;"></span></p><b style="box-sizing: border-box;"><b style="box-sizing: border-box;"><span style="box-sizing: border-box;">MAS References:</span></b></b></span></span></span></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><b style="box-sizing: border-box;"><a href="https://microsoft.sharepoint.com/:w:/s/accessibility/EXdDUZzldv5MgwDaMHnTzcMBcT8opKGncYjU-gCJ4uqQdg?e=9nuVmt" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">https://microsoft.sharepoint.com/:w:/s/accessibility/EXdDUZzldv5MgwDaMHnTzcMBcT8opKGncYjU-gCJ4uqQdg?e=9nuVmt</a><br style="box-sizing: border-box;"></b></span></span></span></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><b style="box-sizing: border-box;"><b style="box-sizing: border-box;"><span style="box-sizing: border-box;">WCAG Reference:</span></b> </b></span></span></span></div><div style="box-sizing: border-box; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px 0cm 10.6667px; line-height: 15.6933px; font-size: 11pt; font-family: Calibri, sans-serif;"><span style="box-sizing: border-box;"><span style="box-sizing: border-box;"><b style="box-sizing: border-box;"><a href="https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships" style="box-sizing: border-box; color: var(--communication-foreground,rgba(0, 90, 158, 1)); text-decoration: underline; cursor: pointer;">https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships</a> </b></span></span></div>
</body>
</html>
<img width="1542" alt="1 3 1-The screen reader does not announce the link as a link" src="https://user-images.githubusercontent.com/93735775/218084646-95294d33-a194-4456-a126-478e30a8d90c.png">

https://user-images.githubusercontent.com/93735775/218084667-ed390d90-f6f5-42e6-9533-6e6916263ccc.mp4

**Comment by josephsl** [comment] 2023-02-10 12:22
Hi,

A few things to help us diagnose this a bit further:

* What was the NVDA version tested?
* Does this happen if using a newer Windows 11 21H2/22H2 build.UBR?
* Is this still reproducible if using Edge 109?

Please answer all three questions before continuing.

Thanks.

**Comment by zersiax** [comment] 2023-02-10 12:42
@msftedad  Nobody is going to be able to reproduce this issue given the URL you provided requires you to be a tenant of the Microsoft Azure domain, from a quick look.
So you are going to have to provide a non-authenticated example if people want to repro this one.
My guess would be, if the links aren't announced as links, they may very well not be links. They might be div elements that have been augmented to act like links, which is a coding issue that needs to be fixed on the side of the dev team responsible for this page. However, i can't verify that because I can't reach the requested URL page with my Microsoft account.

**Comment by seanbudd** [comment] 2023-02-12 19:20
We are unable to process this issue as it stands.

- Please fill out the NVDA issue template.
- Many developers, contributors and community members here are vision impaired. Screenshots are not accessible. Provide an alternative description, and capture any relevant information from images.

**Closed by seanbudd** 2023-02-12 19:20 UTC
