### ISSUE TITLE
Can only read first line of text messages in new Google Voice web interface

### ISSUE THREAD

**Issue by 4RJames** [nvaccess/nvda#6837] opened 2017-02-03 21:21 UTC
Using NVDA with Firefox
Since the Google Voice web interface was updated
Can only read first line of text messages
Used to be able to read entire text message
Please note: Have always used mouse over to read the text messages

**Comment by ehollig** [comment] 2017-07-13 19:12
In Google Voice, I can confirm that you can read the list of entire text messages by mouseover. However, text messages can only be read in focus mode with tab and shift+tab, not browse mode. I am not exactly sure why this is, but the original poster requested to read text messages via mouseover.

**Comment by leonardder** [comment] 2017-07-22 17:01
Closing, since there's a works for me for the initially reported issue.

**Closed by leonardder** 2017-07-22 17:01 UTC
