### ISSUE TITLE
NVDA causes a crash in Word Preview Touch

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4891] opened 2015-02-06 09:49 UTC
**Reported by MarcoZehe on 2015-02-06 09:49**
When opening a document in Word Preview for the touch interface in Windows 10, and touching the document area, NVDA causes Word to crash. Doing the same with narrator does not cause Word to crash.

Unfortunately, I had no luck getting a crash dump out of the Word crash. While the Python console gave me the patch for where the file would be created, when the actual crash happened, no file was created.

I am attaching the debug level log file that I saved after the crash happened, and the test document I was playing with.

**Comment by bhavyashah** [comment] 2017-09-06 06:24
@MarcoZehe  Can you still reproduce the reported crash? CC @josephsl (Touch Screen and Windows 10 expert), @michaelDCurran and @Qchristensen (Microsoft Office experts) and others

**Comment by Qchristensen** [comment] 2017-09-07 12:42
Every time I see a new Office issue it seems to be from a new (to me) version :)  When I Googled Word Preview Touch, all I could find were references to initial beta versions.

The best I could find was this article: http://www.redmondpie.com/download-microsoft-office-2016-touch-preview-apps-for-windows-10-video/

Which links to "Buy Word Mobile" https://www.microsoft.com/en-us/store/p/word-mobile/9wzdncrfjb9s which takes you to the Windows Store from where I could download a UWP Microsoft Word app.

While it didn't seem the most responsive to touch, trying it (immediately upon opening a document, as per the original issue) didn't crash either Word or NVDA.

I'd be interested to see if Marco can confirm if this is the right app (possibly updated since this issue was filed)? And if the problem still exists?

**Comment by Brian1Gaff** [comment] 2017-09-07 15:41
Not heard of this version. What is the point of a touch based word? I 
thought the way things were going everyone will be dictating to their 
machines before long, the prospect of this tends to make me wince.

I've not seen any downloads of a future version so maybe some people ar 
getting insider builds of it somewhere.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Qchristensen** [comment] 2017-09-10 11:55
Brian, As far as I can tell, this "touch" release was an earlier version of what is now the UWP version of Word available on the Windows Store.  Particularly since, as I noted, following the one link I did find to the touch version, redirected me to the UWP app anyway.  The "touch" part was presumably what they were concentrating on in developing that as touch screen devices were starting to become more common.  These UWP apps you can download from the Windows store can be run on your desktop as well as a touch screen tablet version of Windows.  Being designed for touch and a potentially smaller screen, they often tend to be a little simpler in terms of window layout and sometimes with fewer features as well (I haven't played in depth with it to know for sure, that was a general comment).

Anyway, I did ask Marco (outside Github) and got a reply saying this could be closed now.   Given that, and that when I tried the closest available version to the one originally reported and could not reproduce the crash, I'm going to close this issue as worksforme

**Closed by Qchristensen** 2017-09-10 11:55 UTC
Labels: appCrash, bug, Microsoft Office support
