### ISSUE TITLE
When using Firefoxx pressing shift-enter to oepn a link in a new window does not always refresh the browse mode buffer when the window opens

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5035] opened 2015-04-13 09:38 UTC
**Reported by dgoldfield on 2015-04-13 09:38**
On some pages, when I press shift-enter to open a link in a new Firefox window, NVDA acts as though I'm still on the original page even though I am on the new page in the new window. Once I press the alt key twice to move focus away from and then back to the window NVDA acknowledges the new window.

**Comment by bhavyashah** [comment] 2017-09-06 10:34
I am unable to replicate the reported issue using Firefox 55.0.3 stable and NVDA 2017.3, neither have I heard any recent reports describing such behaviour. Since we cannot contact the original author of this ticket and request a status update, and it is possible that a Firefox update may have resolved this problem, unless anyone can still confirm this issue, I suggest closing as worksforme. @ehollig

**Comment by ruifontes** [comment] 2017-09-06 10:41
Hi!
Still happens randomly.
Firefox 55.0.3, last NVDA Next and Windows 10 Creator up-to-date.
I will grab a new log, if necessary.

**Comment by Adriani90** [comment] 2019-01-23 22:11
@ruifontes are you still able to reproduce it? I cannot reproduce it in Firefox 64.0.2.

**Comment by Adriani90** [comment] 2019-01-27 17:58
I am closing this as works for me. @bhavyashah, @ruifontes please comment on it if you still have this issue. We will reopen it if you can reproduce it.

**Closed** 2019-01-27 17:59 UTC
Labels: Browse mode, bug, worksforme
