### ISSUE TITLE
Add feature to set delay time for character description 

### ISSUE THREAD

**Issue by manhcuong0312** [nvaccess/nvda#14454] opened 2022-12-18 16:50 UTC
### Is your feature request related to a problem? Please describe.
This is not a problem. Just a feature requested in a Vietnamese group on Facebook, and I help him to create issue here.
### Describe the solution you'd like
Add a control after the Delayed descriptions for characters on cursor movement option using an edit spinbox so user can choose time to delay before saying character description, or enter manualy.
### Describe alternatives you've considered
add a combo box, an provide some options other than 1 second delay.

**Comment by seanbudd** [comment] 2022-12-19 00:36
I believe this is a duplicate of #13967, feel free to add discussion there if you think anything is missed

**Closed by seanbudd** 2022-12-19 00:36 UTC
