### ISSUE TITLE
The Start NVDA after sign in checkbox doesn't actually do anything in the welcome dialog

### ISSUE THREAD

**Issue by TheQuinbox** [nvaccess/nvda#14590] opened 2023-01-27 01:00 UTC
### Steps to reproduce:

1. Make sure NVDA is not set to start up after login.
2. Open the welcome dialog.
3. Check the start NVDA after sign in checkbox.
4. Log out and back in.

### Actual behavior:

NVDA doesn't start up.

### Expected behavior:

This checkbox should function the same as the one in general settings.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2022.4
#### Windows version:
Windows 11 21H2
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.3 also seems to do it.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not related, but yes

**Comment by XLTechie** [comment] 2023-01-27 01:16
You say NVDA doesn't start up, but is the box still checked in the welcome 
dialog?

You also didn't provide a debug level log of what happens when you check the 
box, through NVDA shutdown.

I am unable to replicate this in alpha.

If I check the box in welcome, then look in general, it is still checked there.

If I check the box in welcome, then restart NVDA, the box is still checked.

If I check the box in welcome, then restart the machine, the box is still 
checked and NVDA starts.

Note that I have settings not set to save automatically, but even so it works.

**Comment by CyrilleB79** [comment] 2024-01-30 11:12
I cannot reproduce on my side.

@TheQuinbox, is the issue still reproducible with NVDA 2023.3.3 or 2024.1beta6?
If yes, could you please provide two logs at debug level:
1. the log of NVDA session when you open and configure this parameter in the welcome dialog
2. the log of the NVDA session that you start manually after you have logged out and in again.

Please during the second session, check the state of the start NVDA after sign in checkbox both in welcome dialog and general settings and report it here as advised by @XLTechie.

Thanks.

**Comment by CyrilleB79** [comment] 2024-07-30 14:37
@TheQuinbox could you answer the questions from @XLTechie and myself?

**Comment by seanbudd** [comment] 2024-07-30 23:11
Closing until more information has been provided

**Closed** 2024-07-30 23:11 UTC
Labels: blocked/needs-info, needs-triage
