### ISSUE TITLE
Option to restrict object navigation.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5146] opened 2015-06-08 22:54 UTC
**Reported by kara_louise on 2015-06-08 22:54**
This option if enabled would restrict Object Nav to the current window or application, similar to the command in JAWS.
This could have the potential to benefit new and experienced users alike. If you accidentally move out of an application window into another level of the hierarchy, it can be confusing/time consuming to find your place again.  The top level is the worst I've found.
Restricting Object Nav would ensure that you couldn't move outside the current application/window to prevent this from happening. There would be a gesture to quickly toggle between window, application or unrestricted.
I don't know enough about how NVDA works to ascertain if this would be possible to implement, but I thought I'd throw it out there anyway for consideration, and I couldn't find  another ticket requesting this feature.

**Comment by bhavyashah** [comment] 2017-09-05 14:22
I agree with the third pointer in @josephsl's https://github.com/nvaccess/nvda/issues/5146#issuecomment-155339970. Apart from that, I think the original author was definitely referring to NVDA's object navigation because of the mention of words and phrases like 'the top level', 'hierarchy', 'object navigation', etc. I would like to kindly request comments, thoughts and inputs from others on this feature request so that we can finalize the scope and UX of this ticket.

**Comment by leonardder** [comment] 2018-06-21 13:53
Closing as duplicate of #7759, which has, though newer, much more discussion.

**Closed by leonardder** 2018-06-21 13:53 UTC
Labels: enhancement
