### ISSUE TITLE
NVDA role=alert support for FF and IE

### ISSUE THREAD

**Issue by elenastoyanovaa** [nvaccess/nvda#8797] opened 2018-09-28 07:25 UTC
Hello,

NVDA does not read a div with a role alert in both FF and IE. It works only in Chrome. Tested with JAWS, and there the issue is not present.

You can test it in the following example: https://jsfiddle.net/elenastoyanovaaa/7pk03rxc/1/
If you remove the aria-label, the issue still persist.

**Comment by ehollig** [comment] 2018-09-28 16:33
Duplicate of #2442

**Closed by ehollig** 2018-09-28 16:33 UTC
