### ISSUE TITLE
A noticeable delay while arrowing through 1 Password's list view with NVDA

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#10511] opened 2019-11-19 21:55 UTC
### Steps to reproduce:
1. Open 1 Password
2. Select your vault and tab to the list of items in your vault. (Choose category as necessary.)
3. Tab to the list of items in the vault.
4. Use your up and down arrow keys to navigate through the list items.

Note that the behavior occurs with or without add-ons running.

### Actual behavior:
Navigation is slow. There is a noticeable delay after pressing the up/down arrow keys and NVDA announcing the items. (See log snippet.) This behavior only occurs with NVDA. I have not observed the slowness with JAWS or Narrator.

### Expected behavior:
Considerable delay should not occur when traversing through the list.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
NVDA version alpha-19210,ff3722e9

#### Windows version:
Windows 10 1903 build 19025.10

#### Name and version of other software in use when reproducing the issue:
1 Password Windows desktop version latest public release and latest beta release.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Two previously released versions of NVDA

### Log

IO - inputCore.InputManager.executeGesture (16:20:20.395) - winInputHook (18240):
Input: kb(laptop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (16:20:20.412) - MainThread (6308):
Cancelling
IO - speech.speak (16:20:20.449) - MainThread (6308):
Speaking [LangChangeCommand ('en_US'), 'Fidelity - PratikP12']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:20.458) - MainThread (6308):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (16:20:20.986) - Dummy-1 (15208):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:20.987) - Dummy-1 (15208):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:21.038) - Dummy-1 (15208):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (16:20:21.361) - winInputHook (18240):
Input: kb(laptop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (16:20:21.381) - MainThread (6308):
Cancelling
IO - speech.speak (16:20:22.764) - MainThread (6308):
Speaking [LangChangeCommand ('en_US'), 'Fidelity Cash account']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:22.777) - MainThread (6308):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (16:20:23.224) - Dummy-1 (15208):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:23.224) - Dummy-1 (15208):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:23.286) - Dummy-1 (15208):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (16:20:23.601) - winInputHook (18240):
Input: kb(laptop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (16:20:23.606) - MainThread (6308):
Cancelling
IO - speech.speak (16:20:24.651) - MainThread (6308):
Speaking [LangChangeCommand ('en_US'), 'Fidelity Debit - Pratik Patel']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:24.661) - MainThread (6308):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (16:20:25.197) - Dummy-1 (15208):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:25.197) - Dummy-1 (15208):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:25.249) - Dummy-1 (15208):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (16:20:25.514) - winInputHook (18240):
Input: kb(laptop):downArrow
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (16:20:25.524) - MainThread (6308):
Cancelling
IO - speech.speak (16:20:26.605) - MainThread (6308):
Speaking [LangChangeCommand ('en_US'), 'fiverr.com']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:26.619) - MainThread (6308):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (16:20:26.948) - Dummy-1 (15208):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:26.948) - Dummy-1 (15208):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (16:20:27.000) - Dummy-1 (15208):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (16:20:27.385) - winInputHook (18240):
Input: kb(laptop):downArrow

**Comment by Adriani90** [comment] 2019-11-19 22:04
Closing as duplicate of #10508.

**Closed by Adriani90** 2019-11-19 22:04 UTC
Labels: duplicate
