### ISSUE TITLE
Additional list numbers read when navigating a list in Word with UIA

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9613] opened 2019-05-23 06:50 UTC
### Steps to reproduce:

1. Turn NVDA's UIA in Word option on.  Open Word 365 to a blank document.
2. Type: 1. The first
3. Press enter and for list item 2 type "the second".
4. Press UP ARROW.
5. Press LEFT ARROW
6. Press RIGHT ARROW four times.

### Actual behavior:

A) At Step 4, NVDA reads "1. The first 2"
B) At Step 5 (left arrow), NVDA reads "T".
C) At step 6, NVDA reads "2", then "2. T", then "2. T", then "h"

### Expected behavior:
A) NVDA should read "1. The first" (without reading 2)
B) This step is correct.
C) NVDA should read "linefeed", "2", "T", "h"

#### NVDA version:
NVDA 2019.1.1 installed
nvda_snapshot_alpha-17311,0d29265e

#### Windows version:
Windows 10 18362.1 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11601.20184 

#### Does the issue still occur after restarting your PC?
Yes

**Comment by leonardder** [comment] 2019-10-28 07:13
This has been an issue for a while now. While UIA is still not the default implementation, this is a major show stopper from using it, therefore assigning it p2, at least to investigate what the problem is.

@michaelDCurran Any ideas where to start looking?

**Comment by zstanecic** [comment] 2019-10-28 07:17
HI,

The same is with the UIA and comments.

Has somebody reviewed the PR related to comments?

When it comes to these nasty spurious list reporting, I can reproduce it even in word 2019 and outlook 2019.

**Closed** 2019-11-06 06:55 UTC
Labels: Microsoft Office support, p2
