### ISSUE TITLE
NVDA is extra verbose when reading dialog contents if focus is given above first text element

### ISSUE THREAD

**Issue by disimmon** [nvaccess/nvda#9695] opened 2019-06-07 23:04 UTC
### Steps to reproduce: 
Open Edge Latest or Chrome latest and go to https://jsfiddle.net/cfs1Ljz5/

Navigate to the `Open Dialog (Error)` button and activate it to reveal the dialog and programmatically move focus to the modals close button.

The dialog has a `role="dialog"` and accessible name indicated by an aria-labelledby pointing to the h2 within the dialog. 

### Actual behavior:
When showing the modal NVDA reads out: "Test: Dialog, close button, **Test**, buton: close, heading level 2: test". The second read out of "Test" is redundant and confusing.

### Expected behavior:
When showing the modal NVDA should read out: "Test: Dialog, close button, buton: close, heading level 2: test". The heading should only be read 2 times.

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2019.1.1

#### Windows version: 
Version	10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:
tested with Chrome (latest), Edge 44.18362.1.0

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by DrSooom** [comment] 2019-06-09 06:34
The latest Google Chrome version is 75.0.3770.80 (released on June 4, 2019).

**Comment by Adriani90** [comment] 2020-04-19 14:18
This is only reproducible if read whole page after load is enabled in browse mode settings.
cc: @feerrenrut

**Comment by Adriani90** [comment] 2020-05-12 15:27
Closing as duplicate of #8971.

**Closed by Adriani90** 2020-05-12 15:27 UTC
Labels: close/duplicate
