### ISSUE TITLE
NVDA should support HTML5 input type=range

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5423] opened 2015-10-16 20:29 UTC
**Reported by spanchang02 on 2015-10-16 20:29**
NVDA announces HTML5 input type=range form controls as an editable slider but does not permit selection of  a value within the specified range using arrow key navigation in Google Chrome 45 or later on Windows 7 or Windows 8.1.

**Comment by ehollig** [comment] 2017-07-13 13:52
Confirmed with Chrome 59. Is this a Chrome issue?

**Comment by leonardder** [comment] 2017-07-13 14:09
Quick approach to have such a slider is to paste the following on a Chrome or Firefox address bar:
```
data:text/html, <label for="slider">Slider</label><input id="slider" type="range"/>
```

In Chrome Canary 61.0.3156.0 browse mode, this reports as slider, without the value. However, when you change the value in focus mode, the change is reported accurately. In Firefox 54.0.1, the slider is fully accessible. Same for IE11 and Edge in the Windows 10 creators update.
@ehollig: Could you test with Chrome 59?

The thing I'm more concerned about is that range elements aren't considered to be form fields according to quick navigation, and they really should be treated that way. That is at least something that should be fixed.

**Comment by ehollig** [comment] 2017-07-13 14:17
In Chrome 59 browse mode, this reports as slider, without the value. When you change the value in focus mode using the arrow keys, nothing is reported.

**Comment by leonardder** [comment] 2017-07-13 14:29
So it seems it has been fixed in Canary, at least for the focus mode part. @JCSTeh, the finding that for Firefox, the value of the slider is exposed in browse mode just fine, suggests that there's still work to do for Google at some point. Is that correct?

**Comment by leonardder** [comment] 2017-07-13 14:34
As for quick navigation, it is quite easy to add this for form fields. I'd argue that the behaviour of sliders is somewhat similar to combo boxes in how you select a value from a non-visual perspective (with the keyboard).

**Comment by jcsteh** [comment] 2017-07-14 00:55
[**@leonardder**](https://github.com/leonardder) commented on [14 Jul 2017, 00:29 GMT+10](https://github.com/nvaccess/nvda/issues/5423#issuecomment-315094856 "2017-07-13T14:29:25Z - Replied by Github Reply Comments"):
> So it seems it has been fixed in Canary, at least for the focus mode part.

Right. We were tracking this in #6323.

> @JCSTeh, the finding that for Firefox, the value of the slider is exposed in browse mode just fine, suggests that there's still work to do for Google at some point. Is that correct?

Technical: Chrome is exposing the text interface on these sliders and exposing the label as the text. I'd argue they shouldn't expose the text interface. Having said that, we could fix this easily enough in the gecko_ia2 vbuf backend by ignoring the text interface, just as we do for combo boxes. See around line 558 of nvdaHelper/vbufBackends/gecko_ia2/gecko_ia2.cpp.

P2 because this breaks functionality expected for these controls.

**Comment by jcsteh** [comment] 2017-07-14 00:56
[**@leonardder**](https://github.com/leonardder) commented on [14 Jul 2017, 00:34 GMT+10](https://github.com/nvaccess/nvda/issues/5423#issuecomment-315096393 "2017-07-13T14:34:32Z - Replied by Github Reply Comments"):
> As for quick navigation, it is quite easy to add this for form fields. I'd argue that the behaviour of sliders is somewhat similar to combo boxes in how you select a value from a non-visual perspective (with the keyboard).

Agreed. I'd be happy to see form field quick nav move to sliders.

**Comment by leonardder** [comment] 2017-07-14 04:10
To be sure, also for combo boxes, or only form fields? It sounded like 
you only prefer the latter.

I'm happy to do this, however I wonder whether we should consider doing 
more quick nav related work in one pr. It is likely that multiple prs 
will lead to merge conflicts after every single merge, which causes some 
unnecessary extra work.

**Comment by jcsteh** [comment] 2017-07-18 02:17
[**@leonardder**](https://github.com/leonardder) commented on [14 Jul 2017, 16:10 GMT+12](https://github.com/nvaccess/nvda/issues/5423#issuecomment-315265053 "2017-07-14T04:10:58Z - Replied by Github Reply Comments"):
> To be sure, also for combo boxes, or only form fields?

I follow your argument with combo boxes, but even though the keyboard pattern is similar in some ways, I still don't feel this quite fits. @MichaelDCurran, @QChristensen, do you think it makes sense for the combo box quick nav command to jump to sliders?


> I'm happy to do this, however I wonder whether we should consider doing 
> more quick nav related work in one pr. It is likely that multiple prs 
> will lead to merge conflicts after every single merge, which causes some 
> unnecessary extra work.

That's true, but I'm not sure if you have other issues in mind at this point.

**Comment by michaelDCurran** [comment] 2017-07-18 04:17
I don't think c should jump to sliders.

**Comment by leonardder** [comment] 2017-07-18 04:18
[**@jcsteh**](https://github.com/jcsteh) commented on [18 jul. 2017 04:17 CEST](https://github.com/nvaccess/nvda/issues/5423#issuecomment-315938758 "2017-07-18T02:17:52Z - Replied by Github Reply Comments"):
> That's true, but I'm not sure if you have other issues in mind at this point.

Yes, I could add it to #7290. Also #7390 pops into mind regarding the spinbutton role for button navigation.

I'm also thinking about filing a request to have toggle buttons added to check box navigation instead. Though a bit controversial, toggle buttons are more like check boxes than regular buttons.

**Comment by Qchristensen** [comment] 2017-07-18 05:11
I think combo boxes and sliders are similar in the same way that unordered (bulleted) list items and ordered (numbered) list items - the interaction with them is often similar, but the meaning is different.  Sliders progress from a starting point to an ending point and each point in between is a measurable and consistent distance.  A common use is volume from 0 - 10, in increments of 1, or progress through a video / music from 0:00 to the length of the song, in increments of 1 second, or maybe 1%.  A combo box has a list of items which may have no (measurable) order or distance between them.  For instance a list of colours, or species of trees).  Following on from that, I would be happy to use the same single letter navigation key for sliders and spin boxes, since spin boxes are a logical set of numbers.  The only tricky bit is possibly the manipulation of the item itself can be different.  That and picking a logical letter (since S is already taken).

**Comment by ehollig** [comment] 2018-10-09 23:06
Coming back to this, it appears the example @leonardder provided in https://github.com/nvaccess/nvda/issues/5423#issuecomment-315089098, the slider reports it's value in browse and focus modes in Firefox, and only reports it's value in focus mode for Chrome 69,

**Comment by Adriani90** [comment] 2019-01-23 21:54
still the same in Chrome 71.

**Comment by Adriani90** [comment] 2019-12-14 18:26
Why not using "o" for embeded objects for these sliders? Their meaning are more related to such objects (i.e. web players etc.).

**Comment by ObjectInSpace** [comment] 2020-05-20 02:16
NVDA reads the slider in browse mode as well as focus mode for Chrome 83.0.4103.61.

**Comment by Adriani90** [comment] 2020-05-20 21:04
Confirmed it works correctly in Chrome 83. Closing as works for me.

Regarding the quick navigation key to sliders and spins, this could be discussed on a separate issue.

**Closed by Adriani90** 2020-05-20 21:04 UTC
Labels: GoogleWork, app/chrome, bug, close/worksforme, feature/browse-mode, p2
