### ISSUE TITLE
Broken table navigation in the list of messages in Thunderbird

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10400] opened 2019-10-19 10:16 UTC
### Steps to reproduce:
1. Launch Mozilla Thunderbird v60 or newer.
2. Go to a folder containing a few messages.
3. Move the focus/go to the list of messages.
4. Select a message from the list.
5. Use the NVDA table navigation commands to move between columns. 

### Actual behavior:
NVDA fails to navigate between the columns and reports "end of table".

### Expected behavior:
NVDA should navigate between the columns in the list. and report their content.

### System configuration
- Operating system: Windows 10 Pro version 1903 (build 18362.418), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-18937,5bd8872b, in bulgarian.
- Mozilla Thunderbird version: 68.1.2, 32-bit, in bulgarian.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I have - v2019.2.1. It behaves as expected, so this must be something related to code in the alpha builds of NVDA.
[nvda-old.log](https://github.com/nvaccess/nvda/files/3746516/nvda-old.log)

**Comment by lukaszgo1** [comment] 2019-10-19 15:25
I cannot reproduce this with latest Alpha as a portable copy using English version of Thunderbird Nightly on Windows 7.

**Comment by DrSooom** [comment] 2019-10-20 05:41
See issue #8396 (incl. [this comment](https://github.com/nvaccess/nvda/issues/8396#issuecomment-397854296)) and PR #9185. CC: @mltony

**Comment by k-kolev1985** [comment] 2019-10-20 06:47
@DrSooom Good point.
@lukaszgo1 Do you use the message list in Thunderbird in threaded view by any chance? Because I don't. Maybe that is the difference.

**Comment by lukaszgo1** [comment] 2019-10-20 09:58
I've tried with both threaded and unthreaded view and I still cannot reproduce this. Can anyone else try to reproduce this?

**Comment by bdorer** [comment] 2019-10-20 10:10
I'm not able to reproduce with Thunderbird 60.9.0 64bit and NVDA 
2019.2.1 and latest alpha.

Am 19.10.2019 um 12:16 schrieb Kostadin Kolev:

**Comment by k-kolev1985** [comment] 2019-11-25 14:26
I've solved the mystery! 😊

In my NVDA configuration, in "Document formatting" section, in the "Table information" grouping, the first check box ("Tables") was unchecked. When I checked it, NVDA started recognizing the list of messages in Thunderbird 68 as a table as it did before v60. But I haven't changed before that option if I remember correctly - it was always unchecked for me in my NVDA configuration. But updating from v50x of Thunderbird to v60x did brake the behavior of NVDA in the messages list with that NVDA option unchecked.

**Comment by Adriani90** [comment] 2020-05-03 10:43
This works as expected now in Thunderbird 68.7 with NVDA alpha 20097,6a573cd9 even if reporting of tables is disabled in the document formatting settings. Closing as works for me. However, please comment on this if you still have the issue with this setup adn we can reopen. Thanks.

**Closed by Adriani90** 2020-05-03 10:43 UTC
Labels: close/worksforme
