### ISSUE TITLE
NVDA is not reading the floating objects in word document(Any picture/Shape/video/smartArt/Chart- with Text wrapping other than "Inline with text" ) in down navigation or paragraph reading

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#9395] opened 2019-03-22 08:33 UTC
### Steps to reproduce:
1. Open a word document with multiple different objects(picture/Shape/SmartArt/icon etc)
2. Switch to canvas area and place the cursor at the beginning of the document. 
3. Select all these objects one by one and change it's text wrapping from "Inline" to any other "Square/Through/Tight/Behind text" etc (You can do it by selecting the picture and navigating to related Format Tab-->Then to "Wrap Text" button and chose from the menu)
4. Now try to read the document using up down arrow
5. Observe NVDA is not reading the floating objects. 
6. Now again try reading with Insert+Down Arrow
7. Observe NVDA is not reading  the floating objects. 

### Actual behavior:
While continuous reading of whole document and in line navigation NVDA is not reading the floating objects. 

### Expected behavior:
NVDA should read all the objects while in line navigation or continuous reading of the document. 

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes, Same everywhere

**Comment by Adriani90** [comment] 2020-05-16 18:40
Closing as duplicate of #5599.

**Closed by Adriani90** 2020-05-16 18:40 UTC
Labels: app/microsoft-office, close/duplicate
