### ISSUE TITLE
NVDA freezes in Microsoft Edge dev

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#10869] opened 2020-03-11 08:49 UTC
### Steps to reproduce:
1. Use Microsoft Edge dev for web browsing
1. From time to time, the crash as described in "Actual behavior" occurs. It seems mostly related to the opening/closing of model dialogs on the web, but I don't have a concrete test case yet

### Actual behavior:

NVDA freezes and crashes, I have to restart it.

The logged stacktrace is as follows:

```
DEBUGWARNING - watchdog._watcher (09:34:23.206) - watchdog (10356):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 501, in speakObject
  File "speech\__init__.pyc", line 952, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 704, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  [Previous line repeated 33 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 666, in _getTextWithFieldsForUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

WARNING - watchdog._watcher (09:34:38.254) - watchdog (10356):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 501, in speakObject
  File "speech\__init__.pyc", line 952, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 704, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  [Previous line repeated 34 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 678, in _getTextWithFieldsForUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

```

### Expected behavior:

NVDA does not crash.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-19538,b21a299b

#### Windows version:
Windows 10 insiders release, 2004 (OS Build 19577.1000)

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Version 82.0.439.1 (Official build) dev (64-bit)

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Observed this behavior in recent alpha versions
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment] 2020-04-18 23:36
Might be related to #10895.

**Comment by Adriani90** [comment] 2020-05-30 00:52
@bramd can you also reproduce this in Edge Chromium 83?

**Comment by bhavyashah** [comment] 2020-07-08 23:05
@bramd  This is a friendly reminder to respond to https://github.com/nvaccess/nvda/issues/10869#issuecomment-636249887. Also, in case you use other web browsers, particularly Firefox, could you please check if similar freezes occur from time to time there too?

**Comment by Adriani90** [comment] 2020-07-17 21:26
This has been fixed in Edge Chromium 84. Please comment on it if it still occurs for you. I am closing this as works for me.

**Closed by Adriani90** 2020-07-17 21:26 UTC
Labels: app/edge, bug/freeze, close/worksforme
