### ISSUE TITLE
openning file menu constantly while using ctrl+alt+arrow keys in a table

### ISSUE THREAD

**Issue by NedAT** [nvaccess/nvda#7729] opened 2017-11-05 22:45 UTC
1. Open a web page in IE11 in Windows 7.
2. Start navigating a table using ctrl+alt+arrow keys.
3. Release the keys.

Focus should stay in the current table cell waiting for the next command.

The browser's File menu opens instead.
Have to hit "escape"  to go back to the contents.

NVDA version: 2017.3, installed.

Windows version: 7 Pro, x64, Version	6.1.7601 Service Pack 1 Build 7601

Name and version of other software in use when reproducing the issue: IE11 

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA?  Same problems in previous versions.

**Comment by ehollig** [comment] 2017-11-05 23:13
Is it possible you are not releasing the alt key at the same time as the control key? CC @Brian1Gaff to test this on Windows 7

**Comment by NedAT** [comment] 2017-11-06 04:17
Well, I thought of such a possibility, but the mentioned issue was not present on the other screen reader I got rid of.

I also tried to eliminate "key repeat" through windows, but it didn't work.

What is the probability of adding that feature (turning key repeat on/off) in NVDA?

**Comment by feerrenrut** [comment] 2017-11-06 09:04
Does this happen every time you do this?
Does this happen in other applications (other than IE 11)?
To rule out that this is a problem with the keyboard, could you please try another keyboard?

**Comment by NedAT** [comment] 2017-11-06 14:59
Does this happen every time you do this?

-         Almost every time. I did experiment and found out that if I release the Alt key before ctrl, File menu pops up.

-         - If ctrl is released first, however, then everything is fine.

-         
Does this happen in other applications (other than IE 11)?

-         NO. I tried with Firefox, it works like a charm.

-          

I am using a wireless keyboard, as well as the original one on Dell Vostro 3750; no difference in behavior.

**Comment by Brian1Gaff** [comment] 2017-11-06 18:24
Isn't right alt in fact cntrol/alt?
 If anyone has a table to test it I'll give it a try. I have nothing 
relevent here at the moment and so am in a bit of a difficult possition to 
test it.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by k-kolev1985** [comment] 2017-11-06 18:53
Apparently it is keyboard dependent. I can reproduce it with my Logitech K270 keyboard, no matter if connected to my desktop PC or my ASUS T100TA. But if I use the keyboard of the ASUS T100TA itself, I cannot reproduce the issue.

The Logitech K270 is a wireless keyboard. Can please anyone who can reproduce the issue share the brand and model of the keyboard and type of connection being used for the keyboard? That may be the core of the issue.

**Comment by NedAT** [comment] 2017-11-06 18:57
No, it’s left ctrl & left alt.

 

Here is the relevant output from the NVDA log (set on i/o level):

. . .

IO - inputCore.InputManager.executeGesture (11:49:35.246):

Input: kb(desktop):alt+control+downArrow

IO - speech.speak (11:49:35.256):

Speaking [u'link', u'AccessWorld']

IO - inputCore.InputManager.executeGesture (11:49:35.506):

Input: kb(desktop):alt+control+downArrow

IO - speech.speak (11:49:35.526):

Speaking [u'link', u'AFB CareerConnect']

IO - speech.speak (11:49:35.937):

Speaking [u'File  subMenu  Alt + F']

IO - inputCore.InputManager.executeGesture (11:49:39.147):

Input: kb(desktop):NVDA+f1

. . .

 

So, before the File menu was opened, there is no log entry of the alt key being pressed at all.

**Comment by k-kolev1985** [comment] 2017-11-06 19:01
Actually, I spoke too soon. I was able to reproduce the issue even with the keyboard of the ASUS T100TA, though not so frequently as with the Logitech K270. Maybe the speed with which the keyboard sends key presses has something to do with it? I've noticed (at least in the passed) that different keyboards have different speeds of sending key presses, even if the repetition delay in the keyboard options is set at the same value in both cases.

**Comment by NedAT** [comment] 2017-11-06 19:10
Well, my wireless keyboard is Logitech as well, but the same thing happens when I use the regular one on the laptop.

 

I did try to turn off key repeat in Windows unsuccessfully. The option “Ignore all key repeats”  is checked, but keys are still being repeated; not as quickly as before though.

**Comment by feerrenrut** [comment] 2017-11-07 02:42
I don't think alt is affected by the windows key repeat feature.

I am using the built in keyboard on my laptop, with IE 11.

Without NVDA running, the file menu is shown if I press `ctrl+alt`. If I press `ctrl+alt+down arrow` the file menu does not appear.
I tried all combinations of releasing the keys `ctrl+alt+down arrow` the order made no difference.

The behaviour did not change with NVDA running.

I suspect a connectivity issue with the keyboard. Could you please try with a USB wired keyboard?

**Comment by ehollig** [comment] 2017-11-07 03:15
I was able to reproduce this on my laptop, using both the internal keyboard and wireless external keyboard. I pressed left control + left alt + an errow key several times at various speeds, releasing the keys at different times. Here is what I found:

- The issue only occurs in Internet Explorer. Does not occur in Google Chrome or Firefox
- The issue can be reproduced by just pressing left control + left alt
- Focus moves to the file menu when the alt key is released first
- I was able to reproduce this issue using Narrator and JAWS 2018, which makes me think it's an IE issue, or an issue with the way IE handles input of keys

**Comment by feerrenrut** [comment] 2017-11-07 03:24
Ok, that does make it sound like an IE issue. 

Note: I think that it is the correct behaviour to show the file menu when only `ctrl+alt` are pressed.

Testing this some more, I can only reproduce this (with `ctrl+alt+down arrow`) if the `alt` key is pressed first., and the `ctrl` key is released last.
So, using the following sequence:
`alt pressed`, `ctrl pressed`, `down arrow pressed`, `down arrow released`, `alt released`, `ctrl released`

**Comment by NedAT** [comment] 2017-11-07 07:47
OK good people,

 

I think the same: it’s an IE11 issue.

 

The way to avoid it is to release ctrl before releasing alt key.

Or, even better, get rid of old habits and switch to another browser altogether!

 

The only reason I opened it is I didn’t have this problem until I  switched to NVDA 24/7, and it was becoming annoying.

 

I am not sure who can close the thread, but it’s time to do so.

 

Many thanks yall for your help!

**Comment by feerrenrut** [comment] 2017-11-07 08:08
Closing as "cantfix"

**Closed by feerrenrut** 2017-11-07 08:08 UTC
Labels: cantfix

**Comment by nunahosting** [comment] 2017-11-07 17:01
I have to second this. I think it is an IE bug as when I test with jaws or narrator I get the same results.
