### ISSUE TITLE
Change behaviour of focusing and reading bullets in Word with UI auomation enabled

### ISSUE THREAD

**Issue by ainekc** [nvaccess/nvda#11908] opened 2020-12-06 19:56 UTC
### Steps to reproduce:
Turn on enabling UI automation in word from NVDA settings > advanced
Make a new Word file and make a short list of bullet points, min. 2
Try scrolling by paragraph ctrl+up or ctrl+down 
### Actual behavior:
NVDA focuses first on the bullet symbol and then on the listem item itself, but it effectively reads out the bullet twice, once per press of ctrl+up or ctrl+down. 
### Expected behavior:
NVDA focuses on the entire bullet point+item and reads it only once? i.e. new press of ctrl+up or ctrl+down really means next list item every time
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
[Window Title]
About NVDA

[Content]
NonVisual Desktop Access (NVDA)
alpha-21456,f99644e9
#### Windows version:
10.0.18363 Build 18363
#### Name and version of other software in use when reproducing the issue:
Microsoft Word for Office 365 16.0.12527.21296 and earlier
#### Other information about your system:
?
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This has been the case since whenever the UI automation setting was introduced. It doesn't happen with that setting off.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment] 2024-11-22 18:59
This is fixed now in NVDA. You can change the paragraph handling in NVDA settings / document navigaiton, e.g. to "one caraige return" or so and then the paragraph handling is done within NVDA. With this setting, the problem is fixed. Closing as works for me.

**Closed by Adriani90** 2024-11-22 18:59 UTC
Labels: close/worksforme, app/microsoft-office, component/UIA-ms-office
