### ISSUE TITLE
Placeholders are represented as normal value in Chromium based Edge dev

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#11009] opened 2020-04-15 07:44 UTC
### Steps to reproduce:
1. Open Edge based on Chromium
1. Go to this URL: `data:text/html,<label for="test">Test:</label><input id="test" type="text" placeholder="Type something">`

### Actual behavior:
* The placeholder text is represented as a normal value in braille and speech.
* When entering focus mode and pressing left/right arrows, NVDA announces the first letter of the placeholder, blank is expected
* In braille the placeholder is visible with the cursor at the beginning of the text, the cursor is expected after the placeholder text.

### Expected behavior:
* The placeholder is treated as it is in other browsers and does not look like a normal value in the input

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-19919,d1c49e80
#### Windows version:
Version 2004 (OS Build 19603.1000)

#### Name and version of other software in use when reproducing the issue:
Edge dev Version 83.0.478.5 (Official build)

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment] 2020-04-18 23:23
Could you please try with NVDA Version: alpha-20015,56a62097?
I cannot reproduce it with this version on Edge cromium 81. However, the behavior might be different in the development version of Edge 83.

For the future, I suggest not to create issues based on development versions of third party software other than NVDA. In my view we should report issues against NVDA only based on stable versions of software. Otherwise we end in an endless loop of issues which might have to be closed as soon as the stable version of that software is released.
As far as I know Edge cromium 81 is the last stable version.

**Comment by bramd** [comment] 2020-04-19 20:58
@Adriani90 I think it might be worthwhile to log issues against dev/beta versions of third party software, especially things like browsers which are used so often. It can help identify potential issues in the next version of this software and works as a central place to keep information about this issue for other users who may encounter it.

I retested this in Edge stable and beta with latest NVDA alpha. In stable and beta this still works fine, so it is a change/regression in Edge dev. I'll report this to the MS Edge team and get back here if I know more.

**Comment by Adriani90** [comment] 2023-04-14 11:04
@bramd thank you for your input. It seems your effort was successful,
This works as expected now with NVDA 2023.1 and Edge 112.

Closing as works for me.

**Closed by Adriani90** 2023-04-14 11:04 UTC
Labels: close/worksforme, app/edge/anaheim
