### ISSUE TITLE
Button with aria-label not getting read after getting focus inside a div

### ISSUE THREAD

**Issue by jndiaz** [nvaccess/nvda#6627] opened 2016-12-07 21:04 UTC
I have a button with aria-label inside a div. I'm following this steps: 

1. Focus the div using javascript
2. Press tab

Expected behavior: 
Button's aria-label get read

Current behavior:
Button's aria-label doesn't get read. 

I've done a fiddle reproducing the exact same HMTL structure i have. It also have an example with an anchor, and one with just a div with a button inside. In all three examples the button's aria-label doesn't get read. 

https://jsfiddle.net/xp2hg02s/14/

I'd like to know if this is an expected behavior from NVDA, or maybe i'm doing something wrong on my structure. 

Many thanks!

**Comment by feerrenrut** [comment] 2016-12-08 08:19
In Chrome Version `54.0.2840.99` with a recent next build of NVDA (Version: `next-13749,4be7ee9e`)

I get the following output after triggering the `Give focus to button` button (in the fiddle you linked to)

> Give focus to button
> button
> Click here to close
> button
> This is input 1
> This is input 1  edit
>  
> This is input 2
> This is input 2  edit
>  
> This is input 3
> This is input 3  edit

Then nothing when I press `Tab`

I get essentially the same behaviour in FireFox version `50.0.2`.

@jcsteh Could I get your thoughts on this?

**Comment by jndiaz** [comment] 2016-12-12 12:38
Thanks, that's exactly what i'm getting. 

I forgot to mention that I tested this in FireFox version `50.0.2` and using NVDA `2016.3`.

**Comment by feerrenrut** [comment] 2016-12-15 09:24
I think we should look into this more closely to understand what is going on here. Assigning this a priority 2.

**Comment by jndiaz** [comment] 2016-12-19 13:01
Guys, any update on this? Thanks.

**Comment by Adriani90** [comment] 2019-03-25 20:42
@jndiaz this should be solved in NVDA 2019.1 RC1. Could you please test if you can still reproduce this issue? At least I am not able to reproduce it in Chrome 73 and Firefox 66.0.1.

**Comment by Y-V-H** [comment] 2019-06-05 15:23
Hello everyone,
I can reproduce this issue.
Behavior like @feerrenrut described.
I use FF 67.0.1 and NVDA 2019.1.1
Has somebody any update on this?
![image](https://user-images.githubusercontent.com/11545672/58968628-055d1380-87bf-11e9-8f47-78523a7668de.png)

**Comment by Adriani90** [comment] 2019-12-15 14:37
@feerrenrut this seems till reproducible in Firefox 71 and Chrome 79 with NVDA 2019.3 Beta 1. Since this has a P2 assigned, is there any update on this topic? Or should we assign another priority to it?
cc: @jcsteh.

**Comment by Adriani90** [comment] 2019-12-15 14:42
This seems like a duplicate of #6606. However, one has P2, the other has P3 assigned.

**Comment by JulienCochuyt** [comment] 2020-07-16 06:37
To my understanding, this issue is not specific to aria-label, nor is it to buttons.
NVDA remains silent when tabbing from the div to its first focusable child if they are at the same offset of the virtual buffer.
It does not announce the aria-label, but neither does it announce role, title or value.
In the third example provided, the simplest, adding text inside the div before the button demonstrates this behavior: The control is now announced as offsets are distincts.

**Comment by Adriani90** [comment] 2023-04-11 22:35
I am not sure I understand correctly this issue, but this might be related or even duplicate of #12045. In the second part with edit fields, NVDA reports "x" on the button with the aria-label ="click here to close". It might have to do with the <a></a> tag.

**Comment by Adriani90** [comment] 2023-04-11 22:39
I am closing this as the button is now reported as expected, only the aria-label in the <a></a> tag is not but this is covered by #12024.

**Closed by Adriani90** 2023-04-11 22:39 UTC
Labels: close/worksforme, p2
