### ISSUE TITLE
Outlook 2010: Contents of Recipient List not automatically updated during Cursor Movement when invoked from Send To Context Menu

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6723] opened 2017-01-12 18:07 UTC
STR:

1. From within Outlook, open a new message and activate the "Too..." button. By default, this will focus the cursor on an edit box that will allow a user to search the chosen list of contacts; type something in here, and select the "Go" button.

2. The focus will now be moved to the list of results. Notice that when either the down/up cursors are used that NVDA will output the next/previous result in this list.

3. Close the just-opened message, and from within Windows Explorer navigate to any file, Open the context menu, select "Send To", and then "Mail Ricipient". This will open a pre-populated message with the chosen filename as the subject, and will have already attached the chosen file.

4. Once again, select the "Too..." button and enter a name into the provided text box. Hit "Go"; a similar list will now appear.

Expected: As before, NVDA should output the names of contacts as the cursor keys are used

Actual: No output is given; interestingly, performing a read active line correctly outputs the focused contact

I can provide dev info for both dialogs if that'd be useful.

**Comment by ehollig** [comment] 2017-08-16 16:59
@elliott94, is this still the case for you? Seems to work okay for me using Outlook 2016 and the steps you provided above.

**Comment by elliott94** [comment] 2017-08-17 13:40
Unfortunately this is still the case for Outlook 2010; I don't have access to any newer versions that I can test with.

**Comment by Adriani90** [comment] 2024-06-25 12:59
This is not reproducible with NVDA 2024.2 on Outlook 2016 or 365. Support for Office 2010 has ended many years ago. I am closing this issue as works for me. if you are still having this issue with newer MS Office versions, please comment and we can reopen.

**Closed by Adriani90** 2024-06-25 12:59 UTC
Labels: close/worksforme, app/microsoft-office
