### ISSUE TITLE
Virtual buffer not updating as content refreshes in Firefox

### ISSUE THREAD

**Issue by Cleversn** [nvaccess/nvda#10481] opened 2019-11-12 01:35 UTC
Note: I can't recall a web page written in English where this problem occurs, but the following page written in Brazilian Portuguese should be easy enough to follow, since the relevant lines start with numbers. In any case, the problem certainly occurs in other pages as well.

### Steps to reproduce:

1.  Go to http://www.portaldoempreendedor.gov.br/duvidas-frequentes

2. Use the key NVDA+control+f to search for "1-", which should be a link.

3. Now you may verify with the down arrow that the line below starts with the number 2. Then press up arrow to come back to the line startting with 1. If you press numpad insert+num pad 6 now, you notice that this is the last object in this level. Now press numpad insert+numpad 8, then numpad insert+numpad 6, and notice how you land in that same line that starts with the number 2.

4. Now use insert+up arrow to confirm that the system focus is at the line starting in 1, then press Enter on it.

5. Verify with the down arrow that the following line is still the same that starts with 2.
6. Use up arrow to come back to the line that starts in 1. Now if you press numpad insert+numpad 6, you notice that there is a brand new list containing lines starting in numbers like 1.1, 1.2, etc.

### Actual behavior:

Lines starting in 1.1, 1.2, etc. are not displayed in the virtual buffer. This is certainly a regression, but I can't say when the problem started, nor if it started after upgrading Firefox or NVDA.

### Expected behavior:

Such lines must appear there between the 1 line and the 2 line. The same must happen for each of the other cases, i.e. 2.1, 2.2, etc.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

2019.2.1

#### Windows version:

Windows 10 Pro 1903

#### Name and version of other software in use when reproducing the issue:

Firefox 70.0.1 64 bits

#### Does the issue still occur after restarting your PC?

Yes.

**Comment by francipvb** [comment] 2019-11-14 19:36
Hello,

I saw this too. This may be caused by latest fFirefox update, not NVDA.

Cheers,

**Comment by Cleversn** [comment] 2019-11-14 19:42
Thanks for confirming. Today I tested on Internet Explorer, and in fact, the problem doesn't occur there.

**Comment by Adriani90** [comment] 2019-11-18 21:32
cc: @MarcoZehe

**Comment by ehollig** [comment] 2019-11-19 17:24
This does not occur in Chrome either. CC @jcsteh

**Comment by jcsteh** [comment] 2019-11-19 23:04
Confirmed. Occurs in Firefox 70, but is fixed in Firefox 71, currently in beta. Sorry for the breakage.

**Closed by jcsteh** 2019-11-19 23:04 UTC
Labels: Firefox
