### ISSUE TITLE
The incompatible add-ons dialog can lead users to believe that add-ons enabled by overriding compatibility will be disabled again.

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15414] opened 2023-09-10 02:49 UTC
### Steps to reproduce:
1. Upgrade to NVDA-alpha-29119 (not the latest Alpha version), then override compatibility and enable some add-ons.
2. Try upgrading from alpha-29119 to a newer version, such as alpha-29134.
3. Before upgrading alpha-29134, you will see an incompatibility dialog. View incompatible add-ons in the dialog.

### Actual behavior:
Those add-ons whose compatibility was overridden and enabled in step (1) will appear in the list.
This situation may lead users to believe that these add-ons will be disabled after installing alpha-29134.
### Expected behavior:
Add-ons that are enabled by overriding compatibility should not appear in this list, as they will not be disabled after installing a new version of NVDA.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha Version
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3393
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment] 2023-09-10 20:59
I think that it is expected that upgrading to a API-breaking release disable again add-ons that were previously enabled overriding compa issue. Is it what you are experimenting here?

Is it documented in the User Guide? If not, maybe it should be. Probably it should be in the change log at least.

Maybe it should also be documented in the UI in the same dialog that informs that some add-ons will be incompatible.

Let's hear NV Access opinion on this.

**Comment by cary-rowen** [comment] 2023-09-10 21:19
Hi @CyrilleB79 

According to my tests:
When upgrading from one API-breaking version to another API-breaking version, NVDA claims that add-ons enabled by overriding compatibility will be disabled, but in fact they are not, and those add-ons remain enabled.

**Comment by CyrilleB79** [comment] 2023-09-11 04:57
@cary-rowen you write:
> Expected behavior:
> Add-ons that are enabled by overriding compatibility should not appear in this list, as they will not be disabled after installing a new version of NVDA.

I think that the expected behaviour should be instead:
Add-ons that are enabled by overriding compatibility should be disabled again since the choice to override incompatibility was done in consideration of the previous API.


Add-ons that are enabled by overriding compatibility should not appear in this list, as they will not be disabled after installing a new version of NVDA.

**Comment by leonardder** [comment] 2023-09-11 05:52
I think the expected behavior should depend on the source and target API version difference. If you update from one API breaking Alpha to the nextt Alha, the API version should still be equal and therefore no add-ons should be disabled. If you are upgrading from 2024.1 to 2025.1 and you have an add-on force enabled that has a max version of 2023.1, the add-on should be disabled again.

**Comment by cary-rowen** [comment] 2023-09-11 07:03
I agree with @leonardder that users upgrading to the same breaking API version should not disable add-ons that have been enabled by overriding compatibility.

**Closed** 2023-09-20 02:14 UTC
Labels: p3, triaged, feature/addon-store
