### ISSUE TITLE
NVDA stops speaking in web application when using Polish Core Synthesiser

### ISSUE THREAD

**Issue by donalfitzpatrick** [nvaccess/nvda#10632] opened 2019-12-17 18:43 UTC
###Note

I am posting this issue on behalf of a colleague from Poland who is not on Github.  My apologies if the language is somewhat garbled, I am happy to liaise with him to clarify.

### Description of issue

During loading of Web page in the Firefox web browser speaking was stoped. The synthesizer in use was Windows Core voice Adam Polish.
NVDA.

###  log error message after error:

ERROR - unhandled exception (20:19:00.882):
Traceback (most recent call last):
 File "_ctypes/callbacks.c", line 315, in 'calling callback function'
 File "synthDrivers\oneCore.pyo", line 347, in _callback
ValueError: invalid literal for int() with base 10: 'Y'

### Steps to reproduce:
1. Switch nvda to Windows Core speech synthesizer.
2. open firefox and enter the webpage address: http://www.euromath.eu:9090/euromath
3. repeat step 2. Error occurs inconsistently, about twice in every 10.

### Actual behavior:
 NVDA stops speaking

### Expected behavior:
 Synthesizer should read content of the page

#### NVDA installed/portable/running from source:
  Installed
#### NVDA version:
 2019.2.1
#### Windows version:
version	10.0.17134 Compilation 17134
#### Name and version of other software in use when reproducing the issue:
 Mozilla Firefox 68.0.1 (64 bit)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
 Yes, portable version 2019.2.1 but error also was occur in erlier versions from 2018.3
 I have noticed that speaking is stoppd when in the web page that I am opening there is sign of   unicode code \Xfeff
When I try to navigate across the web page in form edit mode and meet this sign, speaking is stop. But I do not thing that it is only one reason of this error.

Sometimes the error occurs also when using english voices (Windows Core synthesizer) and after making any edit operations on the web page.

**Comment by DrSooom** [comment] 2019-12-17 21:14
Quote from [my comment in issue #10634](https://github.com/nvaccess/nvda/issues/10634#issuecomment-566743084):
> U+FEFF is displayed in Firefox if an UTF-8 with BOM encoded html/php file is included. This isn't the case if you include UTF-8 without BOM encoded html/php files. Eliminating this Unicode character has to be done in my opinion by the web browsers – but always as an option. This is NOT a Liblouis or braille issue. These Unicode characters are also sent to the TTS.
> 
> See also: https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding

**Comment by Adriani90** [comment] 2019-12-19 12:15
cc: @MarcoZehe

**Comment by Adriani90** [comment] 2020-05-23 11:05
@donalfitzpatrick are you still having this issue with NVDA 2020.1 and Firefox 76?
Please run the COM registration fixing tool in NVDA menu / tools and report if you are still having this problem after that.
Thanks.

**Comment by CyrilleB79** [comment] 2022-07-19 14:24
@donalfitzpatrick do you still experience this issue?
I cannot reach the webpage. Are you still able to load it? Or would you have another sample where the issue occurs?

If this is not a problem for you anymore, please close this issue and indicate the reason, e.g. issue fixed or unable to reproduce the issue (due to unavailable webpage for example).
Thanks.

**Comment by seanbudd** [comment] 2022-07-19 23:40
Closing as stale

**Closed by seanbudd** 2022-07-19 23:40 UTC
