### ISSUE TITLE
Please say color value for labelled input type=color

### ISSUE THREAD

**Issue by carmacleod** [nvaccess/nvda#8132] opened 2018-03-28 17:44 UTC
We have a settings page with a bunch of color choices in a list.
Each of the color choices has a label element and a corresponding input type=color.
Here is a sample of the markup (for one color choice):
```
<li>
   <label for="editorThemeRulerColor">Ruler color</label>
   <input id="editorThemeRulerColor" class="colorpicker-input" type="color" value="#767676">
</li>
```

If I delete the label, then NVDA speaks the color value as something like 50% red, 50% green, 50% blue.
This is totally fine.
However when I put the label element back, and correctly hook it up to its corresponding input with the for attribute, then NVDA does not announce the color value any more - only the contents of the label.

What I really want is for NVDA to announce the label text, followed by the color value.

**Comment by leonardder** [comment] 2018-03-29 13:06
Could you please provide information on what browsers you tested with?

**Comment by carmacleod** [comment] 2018-04-05 18:38
Interesting. I only tried it in Chrome on Windows before.
I've just now tried it in FF and IE on Windows, and Safari on Mac.

IE and Safari render a color input the same way as a text input, which is a very different experience from a color-swatch button that opens a color picker dialog. The screen reader reads the hex color value out as "number sign, F, F, 0, 0, 0, 0", for example, which is ok.

Firefox does have a button-and-dialog color input, just like Chrome. However, the screen reader experience in Firefox is even worse than Chrome. All you hear for a color input is "Button". If there's a label, the label is spoken, but not the value (same as what I reported for Chrome).

I guess my point is that when any type of input has a label and a value, both should be spoken. That's what would happen for a checkbox input, for example; screen readers say the checkbox label and then "checked" or "not checked". So I think it should be the same for color inputs... say the label, and then the color. The color doesn't have to be a word, like "red". It is perfectly fine to say the percentage of red and green and blue, or the hex value, etc.

In case it's helpful, here's a [color input test page](https://carmacleod.github.io/playground/color-input.html).

**Comment by Adriani90** [comment] 2024-05-14 22:28
Testing with NVDA 2024.1 in Firefox 125.0.3 and Chrome Canary 126, I cannot reproduce this issue. NVDA reports the color values in both cases.
Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-05-14 22:28 UTC
Labels: close/worksforme
