### ISSUE TITLE
Launcher: Ease of Access Center appears after Installation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#7776] opened 2017-11-18 14:05 UTC
When performing an install of NVDA via the Launcher package, I've noticed that EoA appears to be executed at the end of installation. This happens for both Windows 7 and 10, and in 7 means that Narrator automatically starts speaking which can potentially cause confusion. Is this something that can be stopped?

**Comment by Brian1Gaff** [comment] 2017-11-18 17:14
I've not encountered Narrator starting up unwantedly. How can this occur?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by ehollig** [comment] 2017-11-18 23:56
If this is an issue, and someone can reproduce it, this is a duplicate of #5873

**Closed by ehollig** 2017-11-18 23:56 UTC
