### ISSUE TITLE
Excel 2013 crash when quitting NVDA

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#7761] opened 2017-11-15 09:59 UTC
### Steps to reproduce:
I tried the following with Excel 2013:
1. type into a cell ( not press enter or otherwise leave the cell)
1. open the context menu and select formatting
1. press tab and hear Font
1. press the up and down arrows to select different fonts.
1. quit NVDA with `NVDA+q`

### Expected behavior:
Excel should not crash

### Actual behavior:
Excel crashes

### System configuration:
NVDA version: `next-14617,ef52ddc4`

NVDA Installed or portable:
Installed

Windows version:
Windows 10 Version 1703

Name and version of other software in use when reproducing the issue:
Microsoft Office Excel 2013

I could not find a crash dump for this, and there was no errors in the NVDA log.

**Comment by Adriani90** [comment] 2017-11-15 10:30
I think this is not a NVDA issue. I have encountered similar behaviors with past versions of MS Office. Did you try to reinstall it?

**Comment by Brian1Gaff** [comment] 2017-11-15 16:42
Also I notice many office  executables though closed according to how 
windows looks if you look in the running programs and processes you can 
refresh all you like and it remains. Of particular annoyance are runtimes of 
access databases, which can actually delay windows shut down for quite a 
while with the usual  little thing about close wait for it to do something 
etc, but no matter what you do it just takes its own sweet time. The issue 
is its not going to do it every time, so it has to be a Microsoft issue I 
feel.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Adriani90** [comment] 2019-02-04 14:21
@feerrenrut do you still have this issue?

**Comment by Adriani90** [comment] 2019-05-01 08:18
I am closing this one for now, I was testing with different office packages and could not reproduce it. If it is still an issue, please feel free to comment and reopen it. Thanks!

**Closed by Adriani90** 2019-05-01 08:18 UTC
Labels: Microsoft Office support, appCrash
