### ISSUE TITLE
New null context handle error in speech manager

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#11541] opened 2020-09-01 10:38 UTC
### Steps to reproduce:

Sometimes, when a web page is loaded in Firefox (not sure about Chrome), the following error is logged:

```
ERROR - speech.manager.SpeechManager._handleIndex (12:31:15.124) - MainThread (25656):
Error running speech callback
Traceback (most recent call last):
  File "speech\manager.pyc", line 669, in _handleIndex
  File "speech\commands.pyc", line 326, in run
  File "sayAllHandler.pyc", line 164, in _onLineReached
  File "sayAllHandler.pyc", line 213, in lineReached
  File "documentBase.pyc", line 24, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 207, in __init__
  File "textInfos\offsets.pyc", line 477, in __init__
  File "virtualBuffers\__init__.pyc", line 225, in _getStoryLength
OSError: [WinError 1775] Ein NULL-Kontexthandle wurde während eines Remoteprozeduraufrufs vom Client an den Host übergeben
```

This is intermittent.

### Actual behavior:

Error as seen above.

### Expected behavior:

No error.

#### NVDA installed/portable/running from source:

installed.

#### NVDA version:

version alpha-20793,9a4074bc

#### Windows version:

10.0 20H2.

#### Name and version of other software in use when reproducing the issue:

Firefox Nightly 82.

#### Other information about your system:

Dell Laptop, XPS15-9560 from 2017. Focus 40 Blue 5th Generation Braille Display. Using the Vocalizer 5.5 Tiflotecnia speech synthesizer.

#### Does the issue still occur after restarting your computer?

Yes, happened intermittently for a few days at least, also after restarts.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No.

CC @feerrenrut @jcsteh

**Comment by jcsteh** [comment] 2020-09-01 10:40
Duplicate of #11351.

**Closed by jcsteh** 2020-09-01 10:40 UTC
