### ISSUE TITLE
Description List (DL) DT P tags read as items

### ISSUE THREAD

**Issue by alanfluff** [nvaccess/nvda#10859] opened 2020-03-09 12:44 UTC
**Aside:** I am almost certain this is already listed as an issue, I just failed to find it (sorry if that was due to poor searching on my part).

### Steps to reproduce:
This markup
```
<dl>
	<dt>1.01.01</dt>
	<dd>
		<p>I can see 1 cat</p>
		<p>I can see 2 cats</p>
		<p>I can see 3 cats</p>
	</dd>
	<dt>1.01.01</dt>
	<dd>
		<p>I can see 1 dog</p>
		<p>I can see 2 dogs</p>
		<p>I can see 3 dogs</p>
	</dd>
</dl>
```
### Actual behavior:
...is announced as a "list" (good) with (8) items (not good).

### Expected behavior:
That it be announced as *'a list with two items'*, or better still, *'a Description List with two items'*.

### System configuration
NVDA installed as `.exe`.

#### NVDA version:
2019.2.1

#### Windows version:
7 Enterprise.

#### Name and version of other software in use when reproducing the issue:
Chrome 80.0.3987.122

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
n/a

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by leonardder** [comment] 2020-03-09 14:41
Duplicate of #3858

**Closed by leonardder** 2020-03-09 14:41 UTC
