### ISSUE TITLE
Braille driver for BraillePen 12

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4801] opened 2015-01-14 11:23 UTC
**Reported by Karol on 2015-01-14 11:23**
Braille driver for BraillePen 12 display. It requires the BP12TI.dll library.

**Comment by jcsteh** [comment] 2015-11-26 02:06
Closing as duplicate of #5538, since there's not really any design discussion to have and the pull request is the better place to do code review.

**Closed by jcsteh** 2015-11-26 02:06 UTC
Labels: Braille, duplicate, enhancement
