### ISSUE TITLE
create a screen curtain addon for NVDA

### ISSUE THREAD

**Issue by Fatihyuksek** [nvaccess/nvda#8334] opened 2018-05-27 13:00 UTC
Please create an addon that turns the screen off. It could be useful for users that want privacy and cannot project their screens to a projector

**Comment by josephsl** [comment] 2018-05-27 16:26
Hi, yes, this was requested before. CC @Eholig

**Comment by leonardder** [comment] 2018-05-28 06:48
Closing as duplicate of #7857.

**Closed by leonardder** 2018-05-28 06:48 UTC
