### ISSUE TITLE
A11y_CombineStatusandDataUsagesettingspages_Status_NetworkStatus_ScreenReader:The screenreader sequence of navigation on the page is incorrect.

### ISSUE THREAD

**Issue by fsteffi** [nvaccess/nvda#10206] opened 2019-09-12 07:39 UTC
**Environment Details:​​**
Application name: Combine Status and Data Usage settings pages
Screen reader: Nvda2019.2

**Repro Steps:​​**
1. Go to "Windows search bar" and search for "settings".
2. Click on "Network and internet"​
3. Navigate to "status tab"​
4. Check for network status​
5. Launch screen reader as nvda
6. Navigate using insert+4 to the header "Status"

**Actual:​**
On navigating on the page using insert+4 the header "Status" is not announced instead announced " no previous", it directly moves to "network status". This issue is not observed in narrator.

**Expected:​**
On navigating on the page using insert+4 the header "Status" along with the announcement as a header and its level should be announced and then to "network status". 

**User Impact:​**
Screen reader users will not get/receive the information present on the screen , they will not know what the information is related to it.

**Attachment Reference:**
![23438557_A11y_CombineStatusandDataUsagesettingspages_Status_NetworkStatus_ScreenReader](https://user-images.githubusercontent.com/24580570/64761570-0047f700-d55a-11e9-9441-111bc7dc5c71.png)

**Comment by Adriani90** [comment] 2020-05-25 21:41
The heading level announcement is already covered in #10207. The other part of this issue works correctly. With insert+numlock 4 on network status, then insert+numlock 2 to enter the object jerarchie and then insert+numlock 6 to navigate its siblings like network name and status etc. This is expected behavior.
Closing as works for me.

**Closed by Adriani90** 2020-05-25 21:41 UTC
Labels: close/worksforme
