### ISSUE TITLE
Feature suggestion - option to report misspelt words in Braille as well as speech

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6171] opened 2016-07-13 00:09 UTC
NVDA currently reports spelling errors (eg in Microsoft Word) in speech but there is no Braille indication.  Apparently, some screen readers use dots 7 and 8 (suggested by Jordy on NVDA users mailing list).

See conversation at: https://nvda.groups.io/g/nvda/thread/proposal_for_a_new_braille/2197966?p=,,,20,0,0,0::Relevance,,Proposal+for+a+new+braille+feature,20,2,0,2197966

**Comment by josephsl** [comment] 2016-07-13 00:27
Hi,

Duplicate of #3022. Speech has been taken care of, but it might be a bit tricky for braille. Thanks.

**Closed by josephsl** 2016-07-13 00:27 UTC
