### ISSUE TITLE
Punctuation/Symbol Pronunciation Dialog: Allow Filtering for Characters

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9128] opened 2019-01-06 18:01 UTC
Since the addition of the Unicode data for Emoji and similar characters, my list of symbols has now substantially grown which has made me realise how useful an option to filter the dialog would be - this would make it much easier to remove symbols that are not required and/or needed. As an example, typing "Face" into the search box would display all Emoji and other characters with "Face" as their name.

**Comment by Brian1Gaff** [comment] 2019-01-07 07:38
While in this thread, nobody has explained why some currency symbols have 
been made so only all punctuation speaks them. Among these are pound dollar 
and euro to name but a few, however it seems rupee is still some.
 I have changed all these to some which makes documents being read sound 
more like they really should do. Was there any  reason for this in the last 
version of nvda, or does it need fixing?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment] 2019-01-07 08:10
Duplicate of #5761, pr #8790

**Closed by leonardder** 2019-01-07 08:10 UTC
