### ISSUE TITLE
jump to slider and jump to video area on websites

### ISSUE THREAD

**Issue by joshknnd1982** [nvaccess/nvda#17194] opened 2024-09-19 12:56 UTC
I would like two features that do the following: first, make a keyboard gesture such as the left-bracket-key. second, when you press this key, and when browse mode is active, and you are on a website that has a slider, such as a volume or fast-forward or rewind video slider, NVDA will jump you directly between the different slider controls on the website so you can then turn browse mode off, and interact with the slider. 
second: add a keyboard command and feature that, when in browse mode, and browse mode is active, and you are on a website with a video, you add an input gesture such as right-bracket-key, and when you press the assigned gesture, NVDA will jump you directly into the video area of the website so you can get to the video controls faster.

**Comment by Adriani90** [comment] 2024-09-19 22:52
The slider issue is a duplicate of #17005.
For moving to video area, you can already assign hotkeys for toggle buttons and progress bars in input gesture dialog in NVDA. All video areas I found so far in Internet have either a toggle button for sharing or other options,  or a progress bar for playback time. So these hotkeys will definitely help.
If you are still having other arguments, please open a new issue for the video area.
I am closing this in favor of #17005..

**Closed by Adriani90** 2024-09-19 22:52 UTC
Labels: close/duplicate
