### ISSUE TITLE
Windows 7 - Explorer: Metadata Editor Crashes entire Machine when NVDA is Running

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10149] opened 2019-08-26 20:34 UTC
### Steps to reproduce:

1. With NVDA running, open a new Explorer window and place focus on any media file recognised by Explorer (tested with both MP3 and WMA)

2. With focus present on the test file, use the Tab key several times until you land on the first edit field within Explorer's built-in metadata editor; NVDA will read something along the lines of "Artist multiline" when the correct field has focus

3. Leave focus on this edit field for around 10 seconds, and then try to move focus away by either tabbing or alt-tabbing away from the window

At this point, you'll notice that Explorer, as well as the entire system, has crashed - a forced restart is the only way to continue using it.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.2

#### Windows version:

Windows 7 X64

#### Does the issue still occur after restarting your PC?

Yes

**Comment by lukaszgo1** [comment] 2019-08-26 20:38
Duplicate of #5337

**Comment by Brian1Gaff** [comment] 2019-08-27 08:12
Is this related to the one caused when the mouse is used? I can test this 
one in the try version, and will do so in a few minutes.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2019-08-27 08:14
I do not find a metadata editor this way in windows 7, have you  missed out 
a step?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment] 2019-08-27 11:54
@elliott94: Maximize the Windows Explorer window with WIN+ArrowUp. As an alternative install [Mp3tag (Freeware)](https://www.mp3tag.de/en/download.html) for editing ID3-Tags.

**Comment by Brian1Gaff** [comment] 2019-08-27 15:29
I've been playing with the normal editor and cannot duplicate it no matter 
what I do in fact.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2019-08-27 18:59
closing as duplicate of #5337

**Closed by Adriani90** 2019-08-27 18:59 UTC

**Comment by lukaszgo1** [comment] 2019-08-27 21:39
@elliott94 COuld you  pleaase try with this build: https://ci.appveyor.com/api/buildjobs/4ipq2w2jj8lw8v6a/artifacts/output%2Fnvda_snapshot_pr10153-18469%2Cac76081c.exe . I've tested on my machine, but having additional confirmation is always good.

**Comment by elliott94** [comment] 2019-08-28 11:33
Seems to have fixed it for me. :) Would you mind if I asked the changes that you've made to stop this from happening?

**Comment by DrSooom** [comment] 2019-08-28 16:52
@elliott94: See https://github.com/nvaccess/nvda/pull/10153/files
