### ISSUE TITLE
Always keeping the audio device open causes stuttering on certain soundcards.

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#11926] opened 2020-12-10 17:17 UTC
### Steps to reproduce:
On certain soundcards, such as the ones that ship with modern HPs, NVDA constantly keeping the audio device open can (seemingly randomly and with no log output), start crackling/stuttering until you restart it.
### Actual behavior:
My soundcard making a crackling noise when NVDA speaks/beeps.
### Expected behavior:
No stuttering/crackling when NVDA is talking/beeping.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2020.2
#### Windows version:
Windows 10 2004 (64-bit) build 19041.685
#### Name and version of other software in use when reproducing the issue:
Other software doesn't appear to effect it.
#### Other information about your system:
Intel I7 7th gen, Quad-core, 4.2 GHZ, 16 GB ram.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

As this appears to be a soundcard problem, I would recommend possibly making a checkbox in advanced (or somewhere else) that allows you to turn off the constantly keeping the audio device open.

**Comment by lukaszgo1** [comment] 2020-12-10 17:49
@TyGillespie NVDA keeps sound card open only since NVDA 2020.3, however you've mentioned testing with 2020.2, so the cause is probably different. Why you believe that these crackling noises are caused by the sound card being kept open? Could you test with NVDA 2020.3 or preferably latest Alpha?

**Comment by TyGillespie** [comment] 2020-12-10 17:53
Sure thing. I'll do that, and report back with my result. :
)

**Comment by TyGillespie** [comment] 2020-12-10 18:01
Woah... updating to 2020.3 made it worse. By a lot. It used to only happen every once in a while, but just enough to be annoying, and now it's about every 5 minutes, and it's worse. Going back to 2020.2 gets it back to how it was. Every once in a while and not as stuttering.

**Comment by josephsl** [comment] 2020-12-10 18:03
Hi, how about with latest alpha build (21485)? Thanks.

**Comment by TyGillespie** [comment] 2020-12-10 18:25
Hi.
I tried updating to:
Version: alpha-21485,d3ba21a3
And it still seems to happen.

**Comment by TyGillespie** [comment] 2020-12-10 18:28
Hi.
This appears to have no difference. I am on the latest snapshot.

**Comment by Adriani90** [comment] 2020-12-10 20:52
Just to understand the impact, could you please install the addon bluetooth audio and report the results? You can find the adon on www.addons.nvda-project.org or on @mltony github page.

**Comment by Brian1Gaff** [comment] 2020-12-10 21:50
Some sound cards are quite frankly crap, or shall we suggest the drivers or 
something else in the hardware is.  Do you find making recordings and 
playing them back hads crackling as well? Most with the problem say this is 
also an issue to my knowledge. What happens if you use an external sound 
card?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by TyGillespie** [comment] 2020-12-11 14:41
It does only appear to be the inbuilt soundcard. My Yeti, for example, does not do it.

**Comment by Adriani90** [comment] 2023-05-04 21:06
@trypolis464 could you please test with the last NVDA alpha if this issue is still occuring?
You can download the last alpha for testing purposes at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by TheQuinbox** [comment] 2023-05-07 01:13
Can confirm that it does not.

**Comment by Adriani90** [comment] 2023-05-07 07:49
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2023-05-07 07:49 UTC
Labels: close/worksforme
