### ISSUE TITLE
Intermittent lag under Windows 10 build 1803

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#8783] opened 2018-09-26 01:04 UTC
### Steps to reproduce:
Perform tasks
### Actual behavior:
Ever since the upgrade to 1803, NVDA intermittently lags for a second or two.
This happens anywhere, but it's most noticeable in something I don't expect to lag (e.g. ssh into my other machine on the LAN).

When this happens, NVDA stops responding, but I can still do other things such as start/stop music.
After a second or so, it comes back.
### Expected behavior:
NVDA doesn't lag
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
Version: try-unregisterUIAProxyWinEvents-16059,e53d3adf
This also happened with 2018.2.1 and snapshots
#### Windows version:
Version 1803 (OS Build 17134.286)
#### Does the issue still occur after restarting your PC?
Yes, though it might take a while (days) to start.
#### Have you tried any other versions of NVDA?
Alpha snapshots

**Comment by Neurrone** [comment] 2018-09-26 12:31
@tspivey I've recently started experiencing what you described starting from a few weeks ago, but haven't been able to pin it down. 

I've experienced this issue previously, but that was caused by Symantec Endpoint Protection, which I've since uninstalled. It was fine until recently.

**Comment by Rob-Hudson** [comment] 2018-09-27 08:17
I experience this also, under the same configuration. Restarting NVDA resolves this--for a time, anyway. There used to be an issue where NVDA would become slow while Chrome-based browsers or firefox was active with several tabs, but this is different. NVDA just falls silent for about 2 to 3 seconds, like it has to think about something. This lag does not appear to be application based, because it can pop up in absolutely any task.

**Comment by Ghorthalon** [comment] 2018-09-27 08:42
This happens to me too. interestingly I've noticed that braille seems to be less affected by this. If I navigate, most of the time the display still updates fine, just the rest is stuck. It also seems to occur more and more frequently.

**Comment by Neurrone** [comment] 2018-09-27 15:06
I'm going to try running NVDA with debug logging enabled, in hopes of getting useful output when it happens. When running without debug logging, it doesn't show anything, such as a warning about a core freeze.

**Comment by leonardder** [comment] 2018-10-06 11:12
@tspivey: how about Windows 10 version 1809?

**Comment by tspivey** [comment] 2018-10-08 10:32
I still get the lag. Maybe not as often, I can't tell yet.

**Comment by josephsl** [comment] 2018-10-12 18:30
Hi, is this even with NVDA 2018.3.2? If so, that’s concerning. Thanks.

**Comment by Rob-Hudson** [comment] 2018-10-12 18:32
Yes it is.

**Comment by PratikP1** [comment] 2018-10-12 18:39
A debug log would be quite useful here. I've been testing 1803 as an insider and 1809 as well. I have not seen this behavior. It would be nice to crush if it's on NVDA's end. I not, it might be Windows. I'd like to get Microsoft more information if we can dig it up.

**Comment by tspivey** [comment] 2018-10-27 10:36
Things I've tried so far:

* Restarting NVDA or rebooting - this might get rid of it for a while (possibly days), but it comes back.
* Disabling Handle keys from other applications - nothing changes.
* Turning on filter keys (and using an external key click application) to give me a key click when a key is accepted - this is the  most interesting, the click stops when NVDA is unresponsive, and all the keys fire when speech returns.
During this process, my music is still playing in Foobar, and I'm able to stop it using global hotkeys, so the keyboard is working.
* Calling keyboardHandler.terminate() to disable NVDA's keyboard hook, no change.

The debug log doesn't seem very useful, I sat in notepad typing this is a test of notepad a few times. Here're the most recent things I typed, and I stopped right after the keys all started to fire.
[debug.txt](https://github.com/nvaccess/nvda/files/2521676/debug.txt)

**Comment by ryok141** [comment] 2018-11-21 03:30
I'm also having this issue. I'm running windows 10 1803 here. It usually starts after I put my computer on standby then turn it on again. Restarting NVDA doesn't help much. No matter what I'm doing whether I'm browsing etc, NVDA will freeze for 3 seconds or so.
Ways that I tried to get around this issue.

- Restarting NVDA: didn't help at all.
Disabling add-ons: didn't help either.

**Comment by josephsl** [comment] 2018-11-21 03:52
Hi, can you try with NVDA 2018.4 beta 1 and see if it improves things a bit? Thanks.

**Comment by fernando-jose-silva** [comment] 2018-11-21 13:57
I am using the last nvda alpha 16298 and windows 10 1809 17763.134 and I experience delays in nvda.
Some times I open the menu to start typing settings, press enter to open settings and nvda announces settings, press tab to navigate and nvda is muted.
After a long time approximately 15 seconds or more the nvda makes the sound that the search box of the start was closed and starts to read the settings screen.
It appears that nvda takes a long time to receive notification that the search box at startup has been closed and that another window is already open.
This occurs when you open other parts by the search in the start as control panel.
Other times I'm browsing explorer and nvda does not advertise the folders open and closed, after a long time or about 30 seconds nvda starts reading the files and files with focus on explorer.
Again it seems that the nvda takes a long time to identify the focus.
For many times this does not happen and everything works fine, I did not notice these errors in periods of intentional use of processing, although it may be occurring in some background process and I do not know.

**Comment by leonardder** [comment] 2019-02-13 16:07
It would be good to have an update with regard to whether this also occurs with 2018.4.1 as well as latest alpha.

**Comment by Adriani90** [comment] 2019-04-03 22:33
@tspivey, @fernando-jose-silva, @ryok141, @Rob-Hudson could anyone of you give a short update with NVDA 2019.1 and last Windows 10 update? Did you encounter the issue in the last several weeks?

**Comment by fernando-jose-silva** [comment] 2019-04-04 02:08
I have found the problem in the last few weeks, but now it occurs much more sporadically, say, 2 times a week.

**Comment by fernando-jose-silva** [comment] 2019-04-04 16:42
I just got a log of a delay in nvda's response.
I opened windows explorer.
I started navigating the folders with the arrow keys.
As soon as I opened windows explorer the nvda was mute.
While navigating with the arrows the nvda also remained mute for about 12 seconds.
Until you started reading the items with focus.
The arrows moved around the screen even with nvda without speech because I was already a 10 intens below in the list of folders and files.
log:
[windows.txt](https://github.com/nvaccess/nvda/files/3044567/windows.txt)

**Comment by Adriani90** [comment] 2019-04-04 21:38
@fernando-jose-silva, as stated in other issues already, please try to reproduce this issue after disabling global plugin extensions addon. This one seems to be related to commandkeyselectiveannouncement and remanence which is probably enabled in global plugin extensions. Thanks.

**Comment by fernando-jose-silva** [comment] 2019-04-05 01:37
I disabled the add-ons in question, if I understood correctly which add-ons are:
Do you have the name of the generally problematic add-ons?
In any case if we can wait for some time until I see if the problem returns, maybe a couple of weeks.

**Comment by Adriani90** [comment] 2019-04-05 07:48
Fernando this is hard to say which addons might cause conflicts. We can just make assumptions based on experience from other People. We must test things case by case and then decide if an addon was the Problem or not. Here is quite clrear that in the log golobal plugin extensions influences your Input and this could have some implications on the Cursor movement. That's why I think the addon causes a conflict here.

**Comment by Adriani90** [comment] 2019-04-05 14:58
@paulber007 this is 
the issue in question. As it is hard to reproduce, we are depending on tests carried by Fernando. Thus, first of all we need to find out if it is really caused by an addon.

**Comment by fernando-jose-silva** [comment] 2019-04-05 15:10
follows the log of 1 more of these locks.
If you recommend disabling any more test addon, you can talk.
[w3.txt](https://github.com/nvaccess/nvda/files/3048529/w3.txt)

**Comment by fernando-jose-silva** [comment] 2019-04-11 19:15
I am attaching yet another nvda locking log on windows.
in the case of suggestions to disable addons I am at disposal.
[w4.txt](https://github.com/nvaccess/nvda/files/3070221/w4.txt)

**Comment by Adriani90** [comment] 2019-04-11 19:37
Ok Fernando in your last log file, were all addons disabled? Could you please try to reproduce the issue with all addons disabled?
Before doing that, please run the com registration fixing tool in NVDA menu > tools > run com registration fixing tool.

To be honnest, something seems to influence your input when accessing the file explorer but I cannon really track what it is. Unfortunately I cannot reproduce this issue myself.

**Comment by Adriani90** [comment] 2019-04-11 19:39
Do you have audiothemes 3d enabled? This could also be a potential cause but as I said, we must try different things.

**Comment by fernando-jose-silva** [comment] 2019-04-12 02:09
Thank you very much for the great help.
My last log the addons are enabled.
I am addicted to the addons testing the nvda without them for long it will be torture.
At this point I will leave it to others to point out problems, or they may close for now.
If I ever get the clear pauses to reproduce the problem without much test time I will report again.

**Comment by fernando-jose-silva** [comment] 2019-05-16 13:02
Due to the project
threshold
I was obliged not to use a complement.
But this helped in this call.
See in the log below that nvda keeps locking in windows 10 1809.
Thank you.
[1809.txt](https://github.com/nvaccess/nvda/files/3187143/1809.txt)

**Comment by Adriani90** [comment] 2019-05-16 19:11
@fernando-jose-silva I don't exactly understand your conclusion. The log file does not show any errors or any frozen core in stack. Is NVDA sluggish also when using Threshold?

**Comment by fernando-jose-silva** [comment] 2019-05-16 19:34
yes, my conclusion is that even with the plugins disabled the problem continues.
Yes I am using nvda threshold 17249
Finally I do not know why the log shows nothing.
by pressing down arrow in the list in explorer the nvda read only the date of modification of the file but did not read the name of the file or folder.

**Comment by Adriani90** [comment] 2019-05-16 19:45
This could be caused if you are on another column. If you press left arrow, do you land on the file name? Which view is set on your windows explorer? You can check that by doing following:

1.	Open windows explorer with windows+e
2.	Press alt
3.	Navigate with right arrow to “view”
4.	Press tab until you hear “view button submenu”
5.	Open that with space bar
6.	Try different view options.

 

 

Von: fernando-jose-silva <notifications@github.com> 
Gesendet: Donnerstag, 16. Mai 2019 21:35
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Intermittent lag under Windows 10 build 1803 (#8783)

 

yes, my conclusion is that even with the plugins disabled the problem continues.
Yes I am using nvda threshold 17249
Finally I do not know why the log shows nothing.
by pressing down arrow in the list in explorer the nvda read only the date of modification of the file but did not read the name of the file or folder.

**Comment by fernando-jose-silva** [comment] 2019-05-16 20:09
the list view is set to details.
No, I'm in the very first column, where there is the file name.
What nvda is reading is the windows screen tip, the help balloons, in my nvda the option to read the tooltips is active.

**Comment by Adriani90** [comment] 2020-03-06 15:29
@fernando-jose-silva how is this now in NVDA 2019.3.1 and Windows 10 last update? Do you see any changes? Or are you still having this issue?

**Comment by fernando-jose-silva** [comment] 2020-03-06 18:12
Thank you very much, I no longer have this problem on nvda alfa 19755 and windows 10 build 19041.

**Comment by leonardder** [comment] 2020-03-06 18:17
ANd you @tspivey?

**Comment by Adriani90** [comment] 2020-12-08 21:31
It seems this is solved, I cannot reprouce it and other users do not reproduce as well. I am closing this issue as works for me but feel free to comment if you are still having it and we can reopen.

**Closed by Adriani90** 2020-12-08 21:31 UTC
Labels: close/worksforme
