### ISSUE TITLE
Nasty Core Freeze When Exiting PowerPoint 2013 64-bit on Windows 7 SP1

### ISSUE THREAD

**Issue by Laughingthunder** [nvaccess/nvda#6331] opened 2016-09-04 21:12 UTC
I am experiencing a rather strange complete NVDA core freeze when I open PowerPoint, then immediately exit it by using the keyboard shortcut "ALT+F, X." I can consistently reproduce this. Here's how I cause the crash on my system, an HP Pavilion dv7-4285DX Notebook PC (early 2011 model), running Windows 7 Pro SP1 (64-bit).

1. Starting on the desktop of my standard (non-administrator) user account, I press Windows+R to open the run dialog.
2. In the run dialog, I enter "powerpnt" without the quotes to launch Microsoft PowerPoint via its' executable name.
3. I press escape to dismiss the PowerPoint start screen.
4. After NVDA announces the blank slideshow, I press ALT+F, then X to exit PowerPoint via the exit option in the file menu.

At this point, NVDA crashes in the worst way possible, with no apparent warning. Speech output is gone, NVDA keyboard shortcuts are unresponsive, and the nvda.exe process seems to end suddenly, although I can't verify this because NVDA is, well, gone.
After the crash, I attempt to immediately restart NVDA with CTRL+ALT+N, but nothing happens. Fortunately, I do have a small amount of remaining vision, and am able to notice what seems to be an out-of-focus dialog with some sort of error relating to NVDA. I can't read the message, but I did manage to get a screenshot of it. I ran OCR on the image later after recovering NVDA, and it seems as though NVDA tries to write some sort of log to the C:\Program Files (x86\nvda directory for some unknown reason, and the error is displayed because NVDA can't write to that location, since it's not elevated. The only way I can get NVDA to start again is to simply launch it after dismissing the strange dialog. I can only speculate as to the cause of this strange crash, but I can tell you for sure that I've noticed it occurring in previous versions of NVDA on this PC, but I'm unsure as to when it started. I managed to get a debug log of the time leading up to the crash, but the crash itself is so hard, that it seems to take the logging facility with it as well, since the log just ends after a message regarding the core frozen in stack, along with references to some NVDA-related files.
![nvda_strange_error](https://cloud.githubusercontent.com/assets/15803737/18233893/1f9b77c2-72ba-11e6-823e-64c94a7f9869.png)
[NVDA_Strange_PowerPoint_Crash_Debug_Log.txt](https://github.com/nvaccess/nvda/files/454113/NVDA_Strange_PowerPoint_Crash_Debug_Log.txt)

**Comment by jcsteh** [comment] 2016-09-04 22:18
I believe this is a duplicate of #4479. Unfortunately, I wasn't able to reproduce this then and I still can't reproduce it now. I wonder whether this is perhaps specific to Windows 7. We'll need to test this. In any case, we'll address this in #4479.

**Closed by jcsteh** 2016-09-04 22:18 UTC
Labels: duplicate
