### ISSUE TITLE
Windows 10 App Essentials is not updated...

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7993] opened 2018-02-12 15:32 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the resultHello problem manifested in the latest version of NVDA. Here's the log.

INFO - __main__ (18:29:37.068):
Starting NVDA
INFO - core.main (18:29:37.226):
Config dir: C:\Users\nikit\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (18:29:37.226):
Loading config: C:\Users\nikit\AppData\Roaming\nvda\nvda.ini
INFO - core.main (18:29:37.318):
NVDA version next-14852,875fa991
INFO - core.main (18:29:37.318):
Using Windows version 10.0.17093 workstation
INFO - core.main (18:29:37.318):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (18:29:37.318):
Using comtypes version 1.1.3
INFO - external:synthDrivers.RHVoice.SynthDriver.__init__ (18:29:37.528):
Using RHVoice version 0.5
INFO - synthDriverHandler.setSynth (18:29:37.532):
Loaded synthDriver RHVoice
INFO - core.main (18:29:37.532):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (18:29:37.533):
Braille input initialized
INFO - braille.initialize (18:29:37.535):
Using liblouis version 3.3.0
INFO - braille.BrailleHandler.setDisplayByName (18:29:37.535):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (18:29:37.565):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (18:29:37.569):
UIAutomation: IUIAutomation3
INFO - core.main (18:29:38.066):
NVDA initialized
ERROR - unhandled exception (18:29:54.740):
Traceback (most recent call last):
  File "wx\_core.pyc", line 16766, in <lambda>
  File "C:\Users\nikit\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\w10config.py", line 126, in getUpdateResponse
  File "C:\Users\nikit\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\w10config.py", line 221, in __init__
TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by josephsl** [comment] 2018-02-12 15:37
Hi, caused by introduction of update postponing feature in next snapshots, fixed via an emergency patch. Thanks.

**Closed** 2018-02-12 15:37 UTC
