### ISSUE TITLE
Having "display: none;" on a dynamic element blocks NVDA from reading menu options

### ISSUE THREAD

**Issue by johntlee** [nvaccess/nvda#13116] opened 2021-12-01 18:42 UTC
### Steps to reproduce:
1. Turn on NVDA.
2. Go to https://jsfiddle.net/37h1z8cL/.
3. Tab to the web contents at the end.
4. Tab to the select menu labeled "Without timeout"
5. Use arrow keys to change the selected menu option.

### Actual behavior:
NVDA does not consistently read out the selected option.

### Expected behavior:
NVDA reads out the selected option every time. Note that if you tab to the select menu labeled "With timeout", the selected option is read every time.

The bug only occurs if there is a custom element (the custom element does not have to be defined) that has a style attribute with "display: none" on it, and it sits inside a parent element whose visibility gets toggled. Removing the style attribute or replacing the display property with any other CSS property gets NVDA to consistently read out the selected option, as does replacing the custom element tag with an actual HTML tag (eg. "div"). Adding a timeout to toggling the visibility also fixes the issue.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2020.3

#### Windows version:
10

#### Name and version of other software in use when reproducing the issue:
Chrome Canary 98.0.4736.0

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by feerrenrut** [comment] 2021-12-02 02:41
I suspect what is happening is that NVDA is receiving an event from the browser to notify that something has changed. We try not to report stale information. Since the `select` is at the same level in the dom as the `div` for `content`, it may be that the parent (common to both `select` and `div id=content`) is the subject of the event.
As for the asymmetry for hiding vs showing, more investigation would be required. It may be due to different events received from the browser.

You can put your content in a nested `div` to workaround this:
``` html
<div>
  <div id="content">
  My content
  
    <my-element style="display: none;"></my-element>
  </div>
</div>
```

**Comment by johntlee** [comment] 2022-10-25 23:17
This seems to also happen if a sibling has an available <slot> in its shadow DOM, regardless of whether or not it's actually filled with content. See example here: https://jsfiddle.net/vqx3ym7c/. In this example, NVDA does not announce the new aria-pressed state as you toggle on/off the button because its sibling with a <slot> in its shadow DOM is being hidden/shown as you press the button. Removing the slot fixes the issue. Putting the sibling in its own div so that it's not a direct sibling also fixes the issue.

**Comment by Adriani90** [comment] 2024-11-28 21:17
Hmm, in browse mode this works, but in focus mode the button cannot be triggered at all.
Is this a web authoring error?
It happens both in Firefox and Chrome.
cc: @jcsteh, @SaschaCowley not sure whether this can be closed.

**Comment by Adriani90** [comment] 2024-11-29 01:28
Oh sorry forgot to mention, I meant the minimal example posted in https://github.com/nvaccess/nvda/issues/13116#issuecomment-1291238010

**Comment by SaschaCowley** [comment] 2024-12-02 01:33
Indeed, this is due to bad authoring. In browse mode, NVDA simulates a mouse click when activating elements. Since @johntlee has only bound a click event listener, only click events activate the "button". I'm not exactly sure what the problem is here. @johntlee is this still a problem you're experiencing? It seems like everything is working as expected.

**Comment by seanbudd** [comment] 2024-12-02 01:53
Closing this as won't fix, until further information is provided

**Closed by seanbudd** 2024-12-02 01:53 UTC
