### ISSUE TITLE
VMWare 10: Simple review exclues elements from web installation page

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4831] opened 2015-01-19 16:46 UTC
**Reported by vgjh2005 on 2015-01-19 16:46**
Hi:
In some especial application interface, there include breathtaking amont of no use architectures of controls. We must through them by pressing nvda+2. I make a test: browsing the software waste my lots of time. For example adobe audition. There are more window and pain etc and they aren't useful.
I thinks:
Make search deeply to find useful controls that is hidden in conplex architecture. I find if the useful control is included in more than two level, and the control will be ignore completely. Get them from unuseful architectures.
If this is finished, and not easy browse mode can be removed. It will improve our speed of control computer. 
All screen reader zdeveloped in China， They are only two level:
the first level is container control( listbox, listview, tab control, treeview etc);
The second level is container's item( list item, menu item, tab item etc).
Certainly, I don't want NVDA is also the same, I only hope to let you understand why I want them. I just want to filter unuseful architecture. If you want to test the software, welcome to tell me. There is ENG language pack. Thanks!

**Comment by leonardder** [comment] 2017-08-12 12:05
VMware 10 isn't the most recent version of this software any more.

@vgjh2005: Could you provide steps to reproduce? Do you still think this issue should be open?

**Comment by vgjh2005** [comment] 2017-08-13 20:41
Hi:
It is not just a bug in VM 10. I just use this software to be the example.
However, adobe audition can be the examination. Thanks

2017-08-12 20:05 GMT+08:00, Leonard de Ruijter <notifications@github.com>:

**Comment by Adriani90** [comment] 2019-05-05 18:21
Since this seems to be an issue with the object navigation in general, I am closing this in favor of #7759 and other issues which cover object navigation. I think more probably there will be changes to the object navigation as such in the future rather than covering such specific software like VM Ware or Adobe audition. Object navigation needs a refactoring itself. Covering all applications which have difficulties with object navigation will be utopic. Even Microsoft office suffers from lots of issues when using object navigation.

**Closed by Adriani90** 2019-05-05 18:21 UTC
Labels: enhancement
