### ISSUE TITLE
Error with quick Nav by heading - UIA with Edge

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#12039] opened 2021-02-05 09:35 UTC
Hello. 1. Include nvda's "Use UIA with Microsoft Edge and other Chromium based browsers" in nvda settings.
2. Open Microsoft edge and go for example to https://vk.com/
3. Start moving through the headlines with H
4. nvda plays the sound of the error and the movement does not occur.
5. Expected. nvda should move through the headlines on the page.
6. version nvda alpha-21723,1392aa3a Microsoft edge 88.0.705.62 and 90.0.788.0

**Comment by Nikita34196** [comment] 2021-02-05 09:41
[nvda.log](https://github.com/nvaccess/nvda/files/5931472/nvda.log)

**Comment by feerrenrut** [comment] 2021-02-08 02:44
Error seems to be:
```
ERROR - scriptHandler.executeScript (12:38:09.762) - MainThread (8752):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x08FBB6F0>> with gesture 'h'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "browseMode.pyc", line 461, in <lambda>
  File "browseMode.pyc", line 419, in _quickNavScript
  File "NVDAObjects\UIA\web.pyc", line 476, in HeadingControlQuicknavIterator
  File "NVDAObjects\UIA\web.pyc", line 438, in level
  File "UIAUtils.pyc", line 99, in getUIATextAttributeValueFromRange
UIAUtils.UIAMixedAttributeError
```

**Comment by Nikita34196** [comment] 2021-02-12 10:14
@feerrenrut there is also an error in nvda when Microsoft edge is opened in Use UIA settings with Microsoft Edge and others 
Chromium based browsers when available: Only when necessary and included.
[nvda.log](https://github.com/nvaccess/nvda/files/5970990/nvda.log)

**Comment by Adriani90** [comment] 2023-04-04 12:38
I get this error:
```
IO - inputCore.InputManager.executeGesture (14:36:14.739) - winInputHook (1940):
Input: kb(laptop):h
ERROR - scriptHandler.executeScript (14:36:14.810) - MainThread (2620):
error executing script: <bound method BrowseModeTreeInterceptor.addQuickNav.<locals>.<lambda> of <NVDAObjects.UIA.chromium.ChromiumUIATreeInterceptor object at 0x06B8EDD0>> with gesture 'h'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 257, in executeScript
  File "browseMode.pyc", line 484, in <lambda>
  File "browseMode.pyc", line 442, in _quickNavScript
  File "NVDAObjects\UIA\web.pyc", line 482, in HeadingControlQuicknavIterator
  File "UIAHandler\browseMode.pyc", line 361, in UIAControlQuicknavIterator
  File "UIAHandler\browseMode.pyc", line 65, in __init__
ValueError: Could not get text range for UIA element
```

cc: @seanbudd, @michaelDCurran

**Comment by Adriani90** [comment] 2024-04-21 20:12
This is not reproducible anymore with NVDA 2024.1 and Edge 124 or Chrome canary 125 when UIA is enabled. Closing as works for me. Please reopecomment with an updated test case if you are still having this issue and we can reopen.

**Closed by Adriani90** 2024-04-21 20:12 UTC
Labels: bug, close/worksforme, app/edge/anaheim, api/uia
