### ISSUE TITLE
NVDA is not able to read the DBeaver grid

### ISSUE THREAD

**Issue by jeanbrazcosta** [nvaccess/nvda#8426] opened 2018-06-20 12:54 UTC
Could you please check why NVDA can not read the DBeaver grid?

I can configure the program, make select but at the time of reading the result while being on the grid NVDA does not pronounce anything.

Attached follows the log I made after connecting to a database.

NVDA version 2018.2.1

link site DBeaver 
https://dbeaver.io/
[nvda.log](https://github.com/nvaccess/nvda/files/2119361/nvda.log)

**Comment by Adriani90** [comment] 2019-05-08 15:41
@jeanbrazcosta there is an app module now in NVDA. Can you still reproduce this issue in NVDA 2019.1.1?

**Comment by jeanbrazcosta** [comment] 2019-05-16 00:40
The problem has been resolved.

Thanks.

**Comment by molaachir** [comment] 2019-08-23 18:30
@Adriani90 I still seem to have this problem. Is there anything I need to configure in order to get this working correctly?

**Comment by jeanbrazcosta** [comment] 2019-10-30 23:50
Unfortunately, I did test it with the latest version, as it was not used on the client to the database, but I was not able to view the grid.

**Comment by Adriani90** [comment] 2024-05-20 21:24
@jeanbrazcosta, @molaachir, @marlon-sousa are you still having this issue with NVDA 2024.2 Beta 2 and dbeaver 24.0.5?

**Comment by marlon-sousa** [comment] 2024-05-21 11:30
Hello,

I can try to test it latter.

However:

* With NVDA 2024.1 and dbeaver 24.0.2 I can access the grid, because dbeaver folks have apparently fixed stuff, not NVDA.
* However, the auto complete is broken, See #16416 ... Whether  #16417 is being packaged into 2024.2 I really don't know, but this issue and pr have niothing to do with grid accessibility, they fix another group of problems specially for Windows 11 users.

**Comment by jeanbrazcosta** [comment] 2024-05-22 01:03
I agree with @marlon-sousa for me the only problem is self completion

**Comment by seanbudd** [comment] 2024-05-22 01:45
Closing this issue as the original issue has been fixed. Autocomplete should be fixed on alpha and 2024.3

**Closed by seanbudd** 2024-05-22 01:45 UTC

**Comment by marlon-sousa** [comment] 2024-05-22 09:47
@jeanbrazcosta  so that you are aware, the same patch fixing NVDA was submitted to [nvda-eclipse addon](https://github.com/albzan/eclipse-nvda). The [associated pr](https://github.com/albzan/eclipse-nvda/pull/15) was merged, although I don't know whether this is already included in a new version.

Putting this here because a broken auto complete is a very heavy limitation for those who need to use dbeaver specially professionally and 2024.3 will naturally take its schedule to go.
