### ISSUE TITLE
<sup> tag incorrect speech

### ISSUE THREAD

**Issue by Alexandre-Cousin-Maplr** [nvaccess/nvda#15890] opened 2023-12-07 20:39 UTC
### Steps to reproduce:
Use this html:
```html
<p>
  English<br />
  1st or 1<sup>st</sup>
</p>
<p>
  Français<br />
  1er ou 1<sup>er</sup>
</p>
```

### Actual behavior:
The `<sup>` html tag is incorrectly readed by nvda
Examples:
> 1st

is corretly readed "first"

> 1<sup>st</sup>

is readed "one s t" or "one street" depending on context

Speech viewer log
```
1st
1  st
```
Braille viewer log
```
1st
```
(for both)

I have the same issues for french speech:
> 1er

is readed "premier"

> 1<sup>er</sup>

is readed "un e r"

Speech viewer log
```
1er
1  er
```
Braille viewer log
```
1er
```
(for both)

### Expected behavior:
In both case, read "first" (or "premier" in french etc)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/sup#ordinal_numbers

### NVDA logs, crash dumps and other attachments:
N/A

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
2023.3 (2023.3.0.29780)

#### Windows version:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎01-‎16
OS build	22621.2715
Experience	Windows Feature Experience Pack 1000.22677.1000.0

#### Name and version of other software in use when reproducing the issue:
Brave: Version 1.60.125 Chromium: 119.0.6045.199 (Official Build) (64-bit)
Firefox: 120.0.1 (64-bit)
(latest version for both)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons installed

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment] 2023-12-08 10:30
This one is a tricky one.

According to the various use cases presented on the MDN page, the expected result is not the same:

For ordinal numbers ("1st") or superior lettering (French "Mlle"), you probably expect the `<sup>` tag to be ignored and its content to be joined to the previous/next words so that "1st" or "Mlle" is only one word, not "1 st" or "M lle". And enabling superscript/subscript in reporting in document formatting settings would be indesirable.

For exposants:
2<sup>2</sup>+3<sup>2</sup>=13
You would not expect the content of `<sup>` to be joined to the surrounding text. Else you would get:
22+32=13
You'd better have a space:
2 2+3 2=13
Even if it remains incorrect, you are more likely to understand that you are missing some formatting information. And you would then enable superscript/subscript in document formatting settings to get the desired result.

The problem with the MDN specification of `<sup>` tag is that
* in the case of ordinal numbers or superior lettering, the superscript presentation is only here due to typographical conventions, but does not convey any semantic: removing this superscript formatting does not change the meaning of the text.
* in the case of mathematical exponant, it conveys meaning.

Unfortunately, I have no universal solution to fix this.

**Comment by Alexandre-Cousin-Maplr** [comment] 2023-12-08 15:44
Can't we differentiate "superscript numbers" and "superscript letters"?

in case of letters, it's "ignored"

but in case of numbers, it will be treated as exponent ?

I'm thinking about explain in other words.
What is the main purpose of "superscript"? probably exponent. I guess it will always be a number.
What happens if it's not a number ? superscript makes no sens and it'll be ignored.

Is that a solution?

**Comment by CyrilleB79** [comment] 2023-12-08 16:39
It's not so simple. Mathematical expressions can also use letters as variables, e.g.:
a<sup>n</sup>=a×a×...×a (n times)

Note: And also superscript number can be used in other context than mathematics, e.g. notes in Wikipedia. In this last case however, we still expect the superscript text to be separated from the surrounding text.

**Comment by Alexandre-Cousin-Maplr** [comment] 2023-12-08 17:48
Nice catch!

But actually, `<sup>` does nothing other than separate the content from previous word/character, that's right?
Why adding this "separation"?

**Comment by CyrilleB79** [comment] 2023-12-08 22:22
> But actually, `<sup>` does nothing other than separate the content from previous word/character, that's right? Why adding this "separation"?

Visually, the text between <`sup>` and `</sup>` is smaller and raised up, i.e. "superscripted". If you check the "Superscripts and subscripts" checkbox in Document settings, the format change will be reported to you when reading it with NVDA.
If there was no space between each component of a webpage, some words would be merged when you would expect a space between them.

**Comment by seanbudd** [comment] 2023-12-12 23:32
This is intended behaviour for the reasons @CyrilleB79 outlined.
"1 st" should be handled better by the synthesizer

**Closed by seanbudd** 2023-12-12 23:32 UTC

**Comment by CyrilleB79** [comment] 2023-12-13 09:27
> This is intended behaviour for the reasons @CyrilleB79 outlined. "1 st" should be handled better by the synthesizer

I disagree with this conclusion. The root cause of the issue is that it cannot be clarified if the semantic of `<sup>` is to make its content a separate word or not; since this cannot be determined, a space is added around its content (by the browser API or by NVDA).
The role of the synthesizer is to speak correctly "1st" without space, not "1 st" with space. If the synth (or NVDA dictionary) implements handling of "1 st" with space, it would be a workaround at best; and I do not know if it is easy to do without causing other side issues.

**Comment by Alexandre-Cousin-Maplr** [comment] 2023-12-18 20:59
Will this issue be reopened?

**Comment by CyrilleB79** [comment] 2023-12-18 21:23
@Alexandre-Cousin-Maplr, just to clarify my position:

I do not know how we may fix this because there is no way to know if spaces should be inserted around the content of `<sup>` tag since the specification does not makes the difference between presentation and semantic with this tag.

The synth can probably handle this, but it would be a workaround: it's basically not its responsibility to fix this.

@seanbudd your opinion? Should it be reopened and why?

**Comment by Masarczyk-Wienfluss** [comment] 2024-06-14 13:08
Just my two cents here: I discovered that if a <sup> tag is a part of a <a> Tag, the superscripted part is treated as a separate link which produces double link speech. Perhaps this is intended behaviour but I just checked it with JAWS and it did not happen there.
