### ISSUE TITLE
Tor Browser 8.0 no longer works with NVDA

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8772] opened 2018-09-22 16:53 UTC
### Steps to reproduce:

1. Install the latest Tor Browser version, 8.o at time of writing. All prior versions were fine.
2. Launch it and attempt to use it.

### Actual behavior:

NVDA reads nothing, not even menus.

### Expected behavior:

Works as well as it does with Firefox.

#### NVDA Installed/portable/running from source:

Installed

#### NVDA version:

2018.3

#### Windows version:

Windows 10 1803

#### Name and version of other software in use when reproducing the issue:

Tor Browser 8.0

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

No

**Comment by Brian1Gaff** [comment] 2018-09-22 17:44
I'm almost certain this is because they have  used a very basic version of 
the Quantum engine without any of the accessibility bits that current 
firefox has. Is it the 64 bit version, by the way? I do have the older 
version and suspended updates as I was warned about this possibility. I hope 
I'm wrong but only time will tell.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Mohamed00** [comment] 2018-09-22 18:12
Known issue on TOR's part I believe, accessibility services are 
apparently broken in 8.0, and NVDA relies on that.

**Comment by Neurrone** [comment] 2018-09-23 03:14
@Mohamed00 do you have a link to the issue on Tor's side tracking this?

**Comment by Mohamed00** [comment] 2018-09-23 05:44
Yes, here it is. https://trac.torproject.org/projects/tor/ticket/27503

**Comment by derekriemer** [comment] 2018-09-24 05:14
Now that we know the cause, I'm going to close this and mark can't fix. Please follow the relevant tor bug for status updates. The good news is they seem to care about fixing this.

**Closed by derekriemer** 2018-09-24 05:14 UTC

**Comment by Brian1Gaff** [comment] 2018-09-24 15:16
That is good news, as this browser can get around some problems certain 
countries impose on internet users which are more than just inconvenient.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by Neurrone** [comment] 2019-09-07 05:57
I'm happy to report this is now fixed in the latest version of TorBrowser, v8.5.5.
