### ISSUE TITLE
Can not find the search field on a webpage

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7340] opened 2017-06-29 20:17 UTC
When visiting the page:
Https://blogs.windows.com/windowsexperience/

There is an edit field on the page, but when you press the letter e to go to the search field, nvda informs you that there are no editing fields on the page.
When navigating with the arrows you can not find the field either.
I'm using windows 7 64bit and chrome 59 64bit.
I could not reproduce the problem on this same machine with firefox, and on a machine with windows 10 and the same chrome version.
The nvda in use is the next 14139.
I'll post a log to see if it helps.

IO - inputCore.InputManager.executeGesture (17:13:57.983):
Input: kb(laptop):b
IO - speech.speak (17:13:58.006):
Speaking [u'Primary Navigation marca navigation ', u'Search marca search clic\xe1vel', u'clic\xe1vel', u'Submit', u'bot\xe3o']
IO - tones.beep (17:13:58.114):
Beep at pitch 745.066666667, for 40 ms, left volume 30, right volume 54
DEBUG - external:globalPlugins.focusHighlight.GlobalPlugin.event_gainFocus (17:13:58.119):
(app chrome) (wc Chrome_RenderWidgetHostHWND) (rect pos 1024 184 size 1 1) (dpi ac 0 win 96 sys 96 scale 1.00) (mon pos 0 0 size 1600 900) (posInMon 1024 184) (primary 1) (dpiMon 96 96) (cMon 1) (role botão state focável,com foco roletext janela) (name Submit)
IO - inputCore.InputManager.executeGesture (17:14:09.595):
Input: kb(laptop):shift+e
IO - speech.speak (17:14:09.618):
Speaking [u'sem campo de edi\xe7\xe3o anterior']
IO - inputCore.InputManager.executeGesture (17:14:11.203):
Input: kb(laptop):e
IO - speech.speak (17:14:11.217):
Speaking [u'sem campo de edi\xe7\xe3o seguinte']
IO - inputCore.InputManager.executeGesture (17:14:13.355):
Input: kb(laptop):upArrow
IO - tones.beep (17:14:13.378):
Beep at pitch 226.446492062, for 80 ms, left volume 50, right volume 50
IO - speech.speak (17:14:13.391):
Speaking [u'clic\xe1vel']
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (17:14:13.401):
IARole: i
IO - inputCore.InputManager.executeGesture (17:14:17.427):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (17:14:17.529):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x0B577B90>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 7292) at address 5b8a450>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'59.0.3071.115'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 3278764
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 463111872
windowStyle: 1445986304
windowThreadID: 7692
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0xc557388 at b571120>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=3278764, objectID=-4, childID=-321586
IAccessible accName: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147417842, 'O aplicativo chamou uma interface marshalled para um outro thread.', (None, None, None, 0, None))

**Comment by jcsteh** [comment] 2017-06-30 00:03
I can't reproduce this, either with Chrome 59 or Chrome Canary. Can you
please try with all Chrome extensions and NVDA add-ons disabled?

**Comment by fernando-jose-silva** [comment] 2017-06-30 19:57
Many thanks for the feedback.
I ran the tests with the chrome and nvda add-ins uninstalled and the result was the same.
Just reinforcing this occurs in a machine with windows 7 64 bits and chrome 64bits.
I uninstalled the chrome and reinstalled, erasing the google folders, and in the case of nvda I ran a blank copy with no settings.
Another mystery of computer science.

**Comment by ehollig** [comment] 2017-08-03 19:35
CC @derekriemer can you try this on Windows 7 with Chrome? I am getting the same results as @jcsteh on Windows 10.

**Comment by derekriemer** [comment] 2017-08-04 04:02
1. I opened chrome (Not canary). 
2. I went to https://blogs.windows.com/windowsexperience/
3. I pressed e. Result: Speaking [LangChangeCommand ('en_US'), u'banner landmark ', u'search landmark ', u'combo box  editable  has auto complete']

**Comment by ehollig** [comment] 2017-08-04 14:57
Thanks for the update. Worksforme. Closing
@fernando-jose-silva, if this is still happening, please try with all addons and Chrome plugins disabled and upload a new log with logging level set to debug.

**Closed by ehollig** 2017-08-04 14:57 UTC
