### ISSUE TITLE
inform the user of the end points of a slider 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12368] opened 2021-05-05 21:30 UTC
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
when using the narrator i discovered a function that i found interesting, that could be used by nvda
in the narrator place the reader for maximum details.
I would like the nvda on the keyboard to stay focused on a slider, it will inform you what is the maximum and minimum value of this control, in addition to the information of the value currently, for example:
speed, minimum value 0, maximum value 100 current value 50
This would be useful for controls that do not have usual values as a minimum value -20 maximum value 15

**Comment by Adriani90** [comment] 2024-11-28 20:44
Closing as Duplicate of #13209. It is the same underlying problem.

**Closed by Adriani90** 2024-11-28 20:44 UTC
Labels: close/duplicate
