### ISSUE TITLE
Outlook 2010: Closing Brackets Not Announced if Navigating by Word

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9681] opened 2019-06-06 14:33 UTC
Tested with NVDA snapshot alpha-17509,0f7c1419 on both Windows 7 and 10 X64.

STR:

1. Open a new message from within Outlook, and in the body type the following:

This is a (test) with NVDA

2. Navigate to the top of the just-typed text, and begin to read by word with CTRL + right

You'll notice that NVDA reads the presence of the left bracket, but doesn't make any announcement that the right bracket exists when navigating over it.

**Comment by DrSooom** [comment] 2019-06-09 04:37
@elliott94:
1. Which synthesizer are you using?
2. And please report the current used symbol level and the configuration for the two brackets in the Punctuation/Symbol Pronunciation Dialog as well.
3. And please report each cursor positions after pressing CTRL+ArrowRight. In Microsoft Word 2010 (quick test with NVDA 2018.1) the cursor jumps as follows: a ( t ) w

**Comment by elliott94** [comment] 2019-06-10 19:26
Apologies - I forgot to mention this.

This is with eSpeak and my Symbol Level set to "Some". No changes have been made to my symbols file.

Thanks.

**Comment by DrSooom** [comment] 2019-06-11 06:24
Okay, I can reproduce this with eSpeak NG, which is built in NVDA 2018.1. It has to do with the space after the bracket. If there is a space after a bracket, the bracket isn't spoken by eSpeak NG, but by other synthesizers. A deeper test for all kind of brackets `()[]{}<>«»` is pending. That should be done during fixing this issue. Maybe the whole thing can be easily fixed by deleting the last character (only if it's U+0020 or U+00A0) in the line, which is sent to the TTS during word navigation.

Therefore the issue title should be now updated too. Thanks.

**Comment by Adriani90** [comment] 2020-06-25 18:57
Fixed by #11167. Testing with NVDA Version: alpha-20400,675c4c54. Closing as works for me.

**Closed by Adriani90** 2020-06-25 18:57 UTC
Labels: close/worksforme
