### ISSUE TITLE
NVDA announces pages opened in a new tab via a hyperlink as "document unknown"

### ISSUE THREAD

**Issue by iamrafan** [nvaccess/nvda#9533] opened 2019-05-03 00:04 UTC
### Steps to reproduce:

1. Open https://codepen.io/iamrafan/pen/GLVxXN?editors=1000#0 in chrome
2. Turn on NVDA 
3. Navigate to Link-1 and activate it
4. Observe that the page opened is announced as "document unknown"

### Actual behavior:
New document opened as announced as "document unknown heading  level 1 . . ."

![image](https://user-images.githubusercontent.com/22068434/57113514-c63c2e00-6cf9-11e9-992f-53f8c3bbc821.png)

#### NVDA installed/portable/running from source: 
installed

#### NVDA version: 
2019.1.1

#### Windows version: 
Windows 10 Enterprise Version 1803 OS build: 17134.345

#### Name and version of other software in use when reproducing the issue:
Chrome: Version 74.0.3729.131 
#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Brian1Gaff** [comment] 2019-05-03 07:54
At the risk of being a little dim here, is this not a very strange thing to 
do? When that page opens  it is in most browsers in an edit box. If nvda is 
not running, then run all sorts of  conditions could be true.
 It might not create the buffer, it might be in either  edit or browse mode. 
I've often noticed that a page can say unknown if its unsure of the focus or 
where its supposed to be.
 How many people turn on the screenreader while in a web site?
 Just saying.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by iamrafan** [comment] 2019-10-22 00:18
@leonardder can you please let me know if there is an update on this issue?

**Comment by Adriani90** [comment] 2020-05-17 13:16
This issue does not occur in NVDA 20201 and Chrome 81. Moreover, I get a 404 error when the new tab opens after clicking on link 1.
I am closing as works for me. If this issue still occurs for you with NVDA 2020.1 and Chrome 81, please post here an updated example to reproduce with and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-17 13:16 UTC
Labels: close/worksforme
