### ISSUE TITLE
Alternative text for SVG icon is announced twice

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4782] opened 2015-01-08 05:39 UTC
**Reported by kloots on 2015-01-08 05:39**
Adding a role of "img" to the SVG element does result in the value of the <title> being recognized in NVDA, but the title is announced twice.

Sample markup:

```
<svg role="img">
  <title>Green rectangle</title>
  <rect width="75" height="50" rx="20" ry="20" fill="#90ee90" stroke="#228b22" stroke-fill="1" />
</svg>
```

**Comment by ehollig** [comment] 2017-09-10 03:40
It appears that this issue is specific to Internet Explorer. Tested the attached document in Firefox, Chrome, and Edge, and did not experience double speaking of the title attribute.
[test 4782.zip](https://github.com/nvaccess/nvda/files/1290239/test.4782.zip)

**Comment by Adriani90** [comment] 2019-01-11 20:50
@ehollig are you still able to reproduce it?

**Comment by ehollig** [comment] 2019-01-20 22:46
Yes, still able to reproduce in IE 11 and now Firefox 64. CC @jcsteh

**Comment by Adriani90** [comment] 2024-10-03 22:44
This is not reproducible anymore with NVDA 2024.4 Beta, Firefox 130 or Chromium Canary 131.
I am closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-10-03 22:44 UTC
Labels: bug, close/worksforme, feature/browse-mode, app/firefox, app/internet-explorer, bug/double-speaking
