### ISSUE TITLE
MS Edge: while reading pdf file, NVDA table navigation commands are not supported

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#14920] opened 2023-05-11 08:11 UTC
while reading pdf file in MS Edge, NVDA table navigation commands are not supported.

This case occurs in MS Edge,. It works as expected in foxit reader.

### Steps to reproduce:

1. Open [this file](https://github.com/nvaccess/nvda/files/11449879/testing.table.navigation.keyCommands.pdf).
1. Press t to move to next table.

#### Actual behavior:
No next table.

#### Expected behavior:
table  with 10 rows and 5 columns  row 1  column 1  Name

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
2023.1

#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2846

#### Name and version of other software in use when reproducing the issue:
* Microsoft Edge version 112.0.1722.58
* Foxit PDF Reader version 11.2.1.53537

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

**Comment by Adriani90** [comment] 2023-05-11 12:02
Closing as duplicate of #11920 which talks about Chrome but the issue is understood globally in every browser, also all Chromium browsers, which displays pdf files.

**Closed by Adriani90** 2023-05-11 12:02 UTC
Labels: close/duplicate

**Comment by XLTechie** [comment] 2023-05-12 02:16
@Adriani90 if you're going to pseudo-merge issues like this, can you please edit 
the title of the "receiving" issue, so it reflects that it applies to more than 
what is listed?

E.g. in this case, change "Chrome" to "Chrome and Edge", or "all Chromium 
browsers", in the title of #11920.

That will help, at the least, with searching and quickly going through titles, 
especially for people who don't understand certain relationships (such as a 
problem with Chrome likely also effecting Edge, to use this issue again as an 
example).

**Comment by Adriani90** [comment] 2023-05-12 06:30
@XLTechie unfrotunately I don't have the permission for changing issue titles, I will cc relevant people who can do that in the issue.
