### ISSUE TITLE
Capital pitch change doesn't work with sapi4 synthesizers

### ISSUE THREAD

**Issue by ondrosik** [nvaccess/nvda#10926] opened 2020-03-31 16:45 UTC
On recent versions of NVDA, it is not possible to use this setting. The pitch of voice doesn't change when using sapi4 synthesyzers during spelling while typing or reading by character. I tested with Wintalker voice 1.6, but many users report to me that it doesn't work also with voice called Hlas. Both are still popular in Czech and Slovak republic. Say "cap" or beep works fine. Here is the log where I read word "ahoj" with lovercase letters, and then "AHOJ" with uppercase letters:

```
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:20.886) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:20.886) - MainThread (11660):
Speaking [CharacterModeCommand(True), 'h', EndUtteranceCommand()]
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:20.906) - MainThread (11660):
Unknown index 6, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:21.106) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:21.116) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:21.126) - MainThread (11660):
Speaking [CharacterModeCommand(True), 'o', EndUtteranceCommand()]
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:21.136) - MainThread (11660):
Unknown index 8, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:21.356) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:21.376) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:21.386) - MainThread (11660):
Speaking [CharacterModeCommand(True), 'j', EndUtteranceCommand()]
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:21.401) - MainThread (11660):
Unknown index 10, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:21.596) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:21.636) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:21.636) - MainThread (11660):
Speaking [PitchCommand(offset=70), CharacterModeCommand(True), 'A', PitchCommand(), EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:21.636) - MainThread (11660):
Unsupported speech command: PitchCommand(offset=70)
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:21.636) - MainThread (11660):
Unsupported speech command: PitchCommand()
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:21.656) - MainThread (11660):
Unknown index 12, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:21.836) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:21.866) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:21.866) - MainThread (11660):
Speaking [PitchCommand(offset=70), CharacterModeCommand(True), 'H', PitchCommand(), EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:21.866) - MainThread (11660):
Unsupported speech command: PitchCommand(offset=70)
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:21.866) - MainThread (11660):
Unsupported speech command: PitchCommand()
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:21.876) - MainThread (11660):
Unknown index 14, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:22.076) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:22.086) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:22.096) - MainThread (11660):
Speaking [PitchCommand(offset=70), CharacterModeCommand(True), 'O', PitchCommand(), EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:22.096) - MainThread (11660):
Unsupported speech command: PitchCommand(offset=70)
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:22.096) - MainThread (11660):
Unsupported speech command: PitchCommand()
DEBUG - speech.manager.SpeechManager._handleIndex (18:27:22.106) - MainThread (11660):
Unknown index 16, speech probably cancelled from main thread.
IO - inputCore.InputManager.executeGesture (18:27:22.306) - winInputHook (11904):
Input: kb(laptop):rightArrow
DEBUG - editableText.EditableText._hasCaretMoved (18:27:22.337) - MainThread (11660):
Caret move detected using event. Elapsed: 0 ms
IO - speech.speak (18:27:22.337) - MainThread (11660):
Speaking [PitchCommand(offset=70), CharacterModeCommand(True), 'J', PitchCommand(), EndUtteranceCommand()]
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:22.337) - MainThread (11660):
Unsupported speech command: PitchCommand(offset=70)
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (18:27:22.337) - MainThread (11660):
Unsupported speech command: PitchCommand()
```

**Comment by DrSooom** [comment] 2020-03-31 23:44
Duplicate of issue #10896.

**Comment by feerrenrut** [comment] 2020-04-01 11:21
Closing as duplicate of #10896

**Closed by feerrenrut** 2020-04-01 11:21 UTC

**Comment by cary-rowen** [comment] 2021-05-01 04:44
#12354   seems to solve this issue, can you test it with the latest alpha version
