### ISSUE TITLE
NVDA reads Thunderbird Status Bar, intruding on anything else you're doing.

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#10975] opened 2020-04-09 23:44 UTC
# Steps to reproduce:
Open Thunderbird when there are still messages to be downloaded.
Navigate to inbox and begin reading any message
NVDA will intrude on this with all sorts of information that seems to be based on ongoing changes in the status bar.  This did not occur in the past.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?  Not for this, but just ran it 2 days ago for something else.

Please see also this Bugzilla bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1628891
and this NVDA issue, specifically the comment of yesterday and addition of tags subsequent to that comment:  https://github.com/nvaccess/nvda/issues/10460

**Comment by josephsl** [comment] 2020-04-10 06:31
Hi,

According to @LeonardDer (via Twitter), this is caused by ARIA role status placed on Thunderbird's status bar. Unless this is something NVDA needs to fix, I'm going to close this as "needs external fix" unless justification can be made.

Thanks.

**Comment by leonardder** [comment] 2020-04-10 06:38
Relevant line in dev info of the status bar:

IAccessible2 attributes: 'margin-left:0px;text-align:start;text-indent:0px;live:polite;id:status-bar;container-live:polite;tag:hbox;class:statusbar chromeclass-status;xml-roles:status;container-live-role:status;margin-top:0px;margin-bottom:0px;margin-right:0px;display:-moz-box;'

We had a similar discussion in https://github.com/microsoft/vscode/issues/94677#issuecomment-611421551

Quoting @MarcoZehe from there:

> role="status" has an implicit aria-live="polite" attached to it. To keep the semantic that this is the status bar, but not make it chatty, you could do role="status" aria-live="off".

**Comment by smeveriss** [comment] 2020-04-10 10:37
Hmmm.
A mozilla non thunderbird user mentioned the same thing about the tag over on the thunderbird bugziller issue sighting this issue.
Yeah, chatty is the word.
The status bar is a nice idea but its a bit chatty.
similarly the remote content and junk filter alerts and other alerts can be a bit chatty at times.
Saying that I like bits of the bar, being told I have no messages, being told that there are x many messages in the box and that there are when you check so many messages to get is fine.
read and unread status then it gets a bit overloaded.

**Comment by alexarnaud** [comment] 2020-04-10 14:41
This will be soon fixed in Thunderbird as discussed in bugzilla.

We lack NVDA testers in Thunderbird Daily, we only have Linux orca users like me. Feel free to install Thunderbird Daily and helps us to test accessibility of it. The Thunderbird team does a amazing job of working and solving accessibility issues.

**Comment by josephsl** [comment] 2020-04-10 17:51
Hi,

Closing as "needs external fix". Thanks.

**Comment by ruifontes** [comment] 2020-04-11 14:46
If this problem already occurs on two separate programs, from different 
companies, it will not be better be NVDA taking care of that for all 
programs?


Rui Fontes


Às 07:38 de 10/04/2020, Leonard de Ruijter escreveu:

**Comment by leonardder** [comment] 2020-04-16 06:14
@alexarnaud DO you have a reference to the bugzilla ticket mentioning this bug?

**Comment by leonardder** [comment] 2020-04-16 10:36
Thanks!

I'm going to reopen this issue:

1. it is causing confusion for many people, so it is easier to find when it is open rather than closed
2. There's still some debate going on about whether NVDA should handle these erroneous cases itself.

**Comment by smeveriss** [comment] 2020-04-16 10:53
Hi lenard.
Well since the issue is fixed in thunderbird bugzilla when is this fix going to make it into compiled versions.
I know the milestone has been set on mozilla bugzilla for 77.0 but noticed a patch exists for esr.
So any idea when the next esr will be coming.
Since this bug is now solved in source, I do wander that for us users effected if maybe a hotfix can be compiled just for this bug until the next esr goes out.

**Comment by leonardder** [comment] 2020-04-16 11:04
> I know the milestone has been set on mozilla bugzilla for 77.0 but noticed a patch exists for esr.

IN that case, it will land in the next ESR, probably.

> So any idea when the next esr will be coming.

Likely in 4 till 6 weeks.

> Since this bug is now solved in source, I do wander that for us users effected if maybe a hotfix can be compiled just for this bug until the next esr goes out.

You mean a hotfix in NVDA? I'm afraid that's way too much afford. There's more to see to convince the Thunderbird devs to incorporate this in a minor release and release an 68.7.1, for example.

**Comment by alexarnaud** [comment] 2020-04-16 12:05
OK, let's me discuss with the TB team for that.

**Comment by Adriani90** [comment] 2020-05-06 22:12
Fixed in Thunderbird 68.8. Closing as works for me.

**Closed by Adriani90** 2020-05-06 22:12 UTC
Labels: blocked/needs-external-fix, close/worksforme
