### ISSUE TITLE
NVDA/Firefox not reading out "embedded object" for Flash object when Flash plugin is not installed

### ISSUE THREAD

**Issue by ps-nd** [nvaccess/nvda#6448] opened 2016-10-11 05:00 UTC
My page has an embedded Flash object (see code below).  I am testing it with NVDA in browse mode.

NVDA version: 2016.3
Firefox version: 49.0.1

I initially added the **alt** attribute on the `<embed>` element but it did not get read out in any browser.  Instead, I added the **aria-label** attribute on the `<object>`.

For Chrome/IE11 this was enough - NVDA previously read out only

> embedded object

but now reads out

> embedded object
> Chart Report

and that is what I want.

This also happens in Firefox but only if the Flash plugin is installed.  Without the Flash plugin (which is the default situation nowadays) Firefox just reads out

> button
> A plugin is needed to display this content.

Could this be a bug in NVDA or Firefox?  Does anyone have advice on how to make Firefox read out the object in the way I am expecting?

The only workaround I have found so far is rather crude - I added `<span>Chart Report</span>` inside the object and set this span's position off-screen using CSS.  Then in browse mode NVDA would read out the contents of the span when it is navigated to using the down (or up) arrow key in browse mode.

`<object id="StackedBar2D"`
`classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"`
`aria-label="Chart Report"`
`codebase="//download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"`
`width="640" height="320">`
`<param name="movie"`
`value="/my_path/my_file.swf?XMLLoadingText=Reading+data...&amp;PBarLoadingText=Loading+chart...&amp;ChartNoDataText=No+data">`
`<param name="FlashVars"`
`value="&amp;dataURL=%2Fmy_path%2FgetMyData%3Ftype%3DmyType%26year%3D2016&amp;chartWidth=640&amp;chartHeight=320">`
`<param name="quality" value="high">`
`<param name="wmode" value="transparent">`
`<embed wmode="transparent"`
`src="/my_path/my_file.swf"`
`pluginspage="//get.adobe.com/flashplayer/"`
`name="StackedBar2D"`
`alt="Chart Report"`
`flashvars="XMLLoadingText=Reading+data...&amp;PBarLoadingText=Loading+chart...&amp;ChartNoDataText=No+data&amp;dataURL=%2Fmy_path%2FgetMyData%3Ftype%3DmyType%26year%3D2016&amp;chartWidth=640&amp;chartHeight=320"`
`quality="high" type="application/x-shockwave-flash"`
`width="640" height="320">`
`</object>`

**Comment by Brian1Gaff** [comment] 2016-10-11 08:12
I think its an intentional  firefox way of doing things. What is the point 
in it just saying embedded object if it cannot be used without a plug in?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by jcsteh** [comment] 2016-10-12 03:09
Is a sighted user able to see the alt text or label when Flash is not installed?

Triage note: We weren't able to get a Flash test case to work when trying to reproduce this briefly. We do have an swf we can use, but it was refusing to load for some reason.

**Comment by ps-nd** [comment] 2016-10-12 03:42
Thanks for the quick replies!

@Brian1Gaff 
My intention is to let a visually impaired user know what type of element is supposed to be there, to aid them in deciding whether to install the relevant plugin or not.  If the object is a video with sound, they may want to install Flash so that they can listen, but if it's just a bar chart (which is the case here) then they probably wouldn't.

@jcsteh 
When Flash is not installed, a sighted user sees the usual grey box stating "A plugin is needed to display this content." - the alt text and label are not shown.

**Comment by jcsteh** [comment] 2016-10-12 03:57
I'd argue, then, that the experience is equivalent for screen reader and sighted users. I understand you want to mitigate the need for a screen reader user to install Flash if it's just a chart, but sighted users don't get that information either.

As noted above, I don't have a working test case yet. However, I suspect this occurs because Firefox actually replaces the embedded object with its own content on the page. We don't read aria-label for anonymous divs, spans, etc. because that would cause duplication and/or spurious reading in some cases.

Triage note: P4 because while this might be nice to have, a screen reader user isn't missing anything here that other users can access.

**Comment by ps-nd** [comment] 2016-10-12 04:22
Your argument makes sense, so for now I'll leave Firefox to its default behaviour. I suspect any screen reader user familiar with Firefox would already know how to recognise instances of missing plugins, and the context should help them to figure out what is meant to be displayed.

**Comment by Brian1Gaff** [comment] 2016-10-12 06:14
The embedded object in fire fox has been flaky for some time. On the bbc 
site I had to refresh the page several times to get it to be seen in the 
media player landmarked part of the page.

Its as if firefox simply does not always load it. It definitely needs a 
sighted person to look at this one.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment] 2019-03-09 11:34
@jcsteh since flash support is being dropped soon in most browsers, what should happen with this issue? I suggest for closing anyway, because there are logic arguments why it should stay as it is now.

**Comment by jcsteh** [comment] 2019-03-25 00:33
Agreed. Even aside from the arguments already made, Flash is not going to get any additional work from anyone, whether that be Adobe, browsers or assistive technology. Closing wontfix.

**Closed by jcsteh** 2019-03-25 00:33 UTC
Labels: blocked, p4
