### ISSUE TITLE
NVDA freezes causing keyboard commands to stop working properly

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#6651] opened 2016-12-19 07:30 UTC
This started happening about a week ago. A few mins after NVDA starts up, it freezes periodically when I type or do something. A few seconds later, it echos all the keys that I typed. After this happens, NVDA keyboard commands no longer work properly. E.g, pressing NVDA+N causes NVDA to announce n or capital n instead of opening the menu. I'm on win10 1607, master snapshot branch

**Comment by Brian1Gaff** [comment] 2016-12-19 09:11
Are you sure this is not windows doing this? I've noticed on slower machines 
that this weird behaviour occurs while its looking at or downloading updates 
from Microsoft. However not seen the  effect where keyboard commands fail 
unless Explorer crashes, which often stops shortcuts from working on all 
versions of Windows.
 Another strange thing in 7 and 10 is that when typing into the save as 
dialogue on some programs, you will lose the feedback speech, and then after 
a few seconds the characters are read back and the command executed.
 Never seen this in XP.



Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Neurrone** [comment] 2016-12-19 09:43
NVDA was working just fine for me for several months, so its probably not my machine being too slow. It always works again when I restart NVDA, and I've never noticed this happening with jaws.

**Comment by Neurrone** [comment] 2016-12-19 09:46
Is there any debug mode setting or something I can turn on to see if I can get more info about this problem when it occurs?

**Comment by Neurrone** [comment] 2016-12-20 15:27
From debug log:
IO - inputCore.InputManager.executeGesture (23:13:16):
Input: kb(laptop):alt+tab
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (23:13:16):
IARole: page
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (23:13:16):
IARole: page
IO - speech.speak (23:13:16):
Speaking [LangChangeCommand ('en'), u'Untitled - Notepad  row 1  column 2']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (23:13:17):
oleacc.AccessibleObjectFromEvent with window 3276886, objectID 1894 and childID 0: [Error -2147024809] The parameter is incorrect
DEBUG - NVDAObjects.IAccessible.IAccessible._get_role (23:13:17):


I think MSAA is breaking somehow, I noticed this happening when installing MathPlayer on a different installation of windows. I remember there being some discussion about other people having their screen readers working strangely due to something breaking MSAA.

**Comment by jcsteh** [comment] 2016-12-21 01:30
This is a duplicate of #2003. To cut a long story short, Windows has a very short timeout for keyboard hooks, after which it removes the hook that took too long without warning the app in any way. If this has only started happening recently, that suggests something changed either in NVDA or on your system that is causing the hook thread to take too long. There are a few things to try:

1. Can you test with NVDA 2016.3 to see if it happens with that?
2. Did you install any NVDA add-ons recently? If so, try with them disabled.
3. Is your log level set lower than debugWarning? If so, see if the problem persists at level debugWarning. It's possible that disk writes are taking longer for some reason on your system, which would mean the hook is blocking too long while it tries to log key presses.

I'm closing this as a duplicate, but feel free to comment with your findings here.

**Closed by jcsteh** 2016-12-21 01:30 UTC

**Comment by Neurrone** [comment] 2016-12-22 05:29
It still happens with NVDA 2016.3 with only the eloquence and indentone addon, with the default logging level. I've tried restarting after reregistering all dlls and sfc /scannow didn't find any problems. So its probably a system change.

I find that jaws displays symptoms of MSAA corruption when I start it after shutting down NVDA whenever this happens. So I'm not sure if this is just coincidental or whether these 2 issues are somehow related.

Which process does the keyboard hook run in? Maybe I can try explicitly excluding NVDA and all its processes from antivirus scans. Another possible cause is me updating from jaws 17 to 18, if it leaves something running in the background after its been shut down.

I've also filed an issue in the win10 feedback hub titled "notify applications when their keyboard hooks time out" as a potential long-term solution.

**Comment by jcsteh** [comment] 2016-12-22 05:34
The keyboard hook runs in nvda.exe (NVDA's main process).

Obviously, it'd be good to try to mitigate this. We've tossed around ideas
like having two hooks so that one hook could trigger if the other one died,
but the problem is that we can't reproduce this ourselves, and trying to
debug new code like this via someone else is a massive time sink.

**Comment by Neurrone** [comment] 2016-12-22 05:55
Understood. Based on [this documentation](https://msdn.microsoft.com/en-us/library/ms644985.aspx), it looks like the hook timeout notification was deliberately removed from windows 7 and up. So a last resort before a reinstall is increasing this timeout.

**Comment by Neurrone** [comment] 2016-12-22 05:57
I guess NVDA is already running the hook on its own thread?

**Comment by jcsteh** [comment] 2016-12-22 06:45
Yes, it's running on its own thread. The Python GIL can cause problems
here, though, because it needs to access some Python data structures to
know whether to pass the key through or trap it.

**Comment by Neurrone** [comment] 2016-12-22 06:48
Nods, otherwise it could be implemented in c++. Will continue to post findings here.

**Comment by Neurrone** [comment] 2016-12-24 10:24
I'm fairly sure I've found the cause of these issues. It hasn't happened after I uninstalled symantec endpoint protection 14 (i suspect later versions of 12 cause this too). Disabling it from the system tray doesn't work, I'm not sure what its doing. Hope that helps anyone with similar issues.
