### ISSUE TITLE
Windows 10 OCR refreshable

### ISSUE THREAD

**Issue by Flash109** [nvaccess/nvda#12745] opened 2021-08-17 18:19 UTC
### Is your feature request related to a problem? Please describe.
When I am e.g. in a Game, where I must read very much text, what I can only do with Windows 10 OCR, because the text is not presented in Windows conform way, it gets annoying after a while to use OCR, read the text and then, after I triger an event by klicking the Mouse or using the controller, pressing escape and doing it all over again.
### Describe the solution you'd like
It would be nice, if there could be a refreshing, like it is used with websites, maybe NVDA+F5.
### Describe alternatives you've considered
Maye using the NVDA navigator for moving through the OCR results without converting it into a html document.

**Comment by cary-rowen** [comment] 2021-08-17 22:54
Can this add-on solve your problem?
https://github.com/larry801/auto_ocr

**Comment by seanbudd** [comment] 2021-08-18 00:31
I agree that is in an important feature that should be implemented when we can.

This issue is a duplicate of #2797 should be fixed by #11270, if work is continued on that pull request.
Please continue the discussion in those places.

**Closed by seanbudd** 2021-08-18 00:31 UTC
