### ISSUE TITLE
Espeak changing speech rate when navigating math content

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5095] opened 2015-05-18 17:19 UTC
**Reported by ondrosik on 2015-05-18 17:19**
I am using master 1079, MathPlayer 4 beta, firefox 30.
steps to reproduce
1) set your voice to espeak, tempo 100, rateboost off. Set your synth settings ring to tempo for quick workarround
2) open this website
https://www.dessci.com/en/products/mathplayer/tech/mathml3-elemmath-sample.xht
3) navigate the heading level 2 "Addition, Subtraction, and Multiplication Problems" and try to interact with the first math content 496+28.
4) Zoom by down arrow until it sais zoomed in all of the way.
5) press left and right arrow.
Now the rate should increase rapidly and it stays so fast also when alttab to other window. You can restart NVDA or simply slover the tempo in synthesyzer ring to fix this.
I see some rate related commands in the log:
"Input: kb(laptop):downArrow
IO - speech.speak (19:08:49):
Speaking [in all of the way ', BreakCommand(time=160), u'4 ', BreakCommand(time=40), RateCommand(multiplier=1.15), u'in the hundreds column ', RateCommand(multiplier=1), BreakCommand(time=36)](u'zoomed)
IO - inputCore.InputManager.executeGesture (19:08:50):
Input: kb(laptop):leftArrow
IO - speech.speak (19:08:50):
Speaking [previous digit ', BreakCommand(time=36)](u'No)
IO - inputCore.InputManager.executeGesture (19:08:50):
Input: kb(laptop):leftArrow
IO - speech.speak (19:08:50):
Speaking [previous digit ', BreakCommand(time=36)](u'No)
IO - inputCore.InputManager.executeGesture (19:08:51):
Input: kb(laptop):rightArrow
IO - speech.speak (19:08:51):
Speaking [', BreakCommand(time=40), RateCommand(multiplier=1.15), u'in the tens column ', RateCommand(multiplier=1), BreakCommand(time=36)](u'9)
IO - inputCore.InputManager.executeGesture (19:08:51):
Input: kb(laptop):leftArrow
IO - speech.speak (19:08:51):
Speaking [', BreakCommand(time=40), RateCommand(multiplier=1.15), u'in the hundreds column ', RateCommand(multiplier=1), BreakCommand(time=36)](u'4)"

this doesn't happen with vocalizer voices and also didn't happen when you set eSpeak rate under 80.

**Comment by bhavyashah** [comment] 2017-08-03 07:39
@jcsteh Does this problem occur with ESpeak-NG as well? Also, on a slightly related note, I often experience this bug wherein ESpeak-NG suddenly jumps its pitch while reading Math content to a point where it is either too nasal or too deep, for no apparent reason. The only way to restore the original pitch, apart from restarting NVDA of course, is to just press NVDA+Ctrl+V to open Voice Settings, without actually needing to do anything in the dialog. Any thoughts on this?

**Comment by Adriani90** [comment] 2019-01-28 22:31
@ondrosik can you still reproduce this issue?

**Comment by Adriani90** [comment] 2019-01-29 18:13
I have tested with NVDA 2018.4.1 in Firefox 64.0.2. eSpeak, tempo 100, rateboost off. The rate is not changing when reading math content. I cannot reproduce this issue. I will close this as works for me. Please comment on it if you can reproduce it. We will reopen it then.

**Closed by Adriani90** 2019-01-29 18:13 UTC
Labels: bug
