### ISSUE TITLE
Feature request：Add hotkey script to assign audio output device

### ISSUE THREAD

**Issue by lijianwei2019** [nvaccess/nvda#11355] opened 2020-07-08 12:43 UTC
### Is your feature request related to a problem? Please describe.

In a multi-sound card device environment, it is occasionally necessary to switch audio output devices frequently. The original operation logic is very inconvenient at this time. Affect the user experience.

### Describe the solution you'd like

The audio output device can be quickly switched by hotkey.

### Describe alternatives you've considered

Add allocates a hotkey script for an audio output device.

**Comment by XLTechie** [comment] 2020-07-08 16:54
There has been discussion on mailing lists and in other places, about the 
desirability of having an assignable hotkey to cycle through available output 
devices.

Windows 10 has a habit of reassigning the default sound device. If NVDA was set 
to use it, sound can be lost.
Other circumstances can also exist where NVDA is suddenly on a sound device 
where it wasn't expected, and that device may not even be hooked up to a set of 
speakers/headphones/whatever if it was intended for input use only.

**Comment by Adriani90** [comment] 2020-07-08 21:24
Closing as duplicate of #8801.

**Closed by Adriani90** 2020-07-08 21:24 UTC
Labels: close/duplicate
