### ISSUE TITLE
Character Reading Broken in Latest Alpha

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#10805] opened 2020-02-20 01:04 UTC
### Steps to reproduce:
1. Read character by character using the left and right arrows.
### Actual behavior:
Nothing is spoken.
### Expected behavior:
The current character is spoken.
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
Alpha-19724,2c4caa62.
#### Windows version:
Windows 10, Version	10.0.19564 Build 19564.
#### Name and version of other software in use when reproducing the issue:
N/a.
#### Other information about your system:
N/a.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, 2019.3.1 works normally.

**Comment by Brian1Gaff** [comment] 2020-02-20 08:36
Maybe I'm not understand you, but in what situation are characters not being 
read.I've not seen this in my latest Alpha snap.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Living4God1991** [comment] 2020-02-20 09:13
I'm seeing this. When you move character by character with the arrow keys or review commands the characters are not read.

**Comment by lukaszgo1** [comment] 2020-02-20 10:56
@Mohamed00 @Living4God1991 What synthesizer are you using? Do you have speech viewer enabled? If you do this is a duplicate of #10741

**Comment by Living4God1991** [comment] 2020-02-20 11:19
No I don't have Speech Viewer enabled. I'm using eSpeak NG.

Email Signature

Lanie Molinar

Disability Rights Advocate and Software Engineering Student at Brigham 
Young University-Idaho <https://byui.edu>

Connect with me on LinkedIn <https://linkedin.com/in/laniegmolinar/>

Phone: 832-284-2426

Certified expert with general use of NVDA (Non Visual Desktop Access and 
use of it with Microsoft Word. Learn more here 
<https://certification.nvaccess.org/>.

NVDA Certified Expert logo"NVDA Certified Expert (with Microsoft Word)" 
logo

Do you have multiple disabilities or know someone who does? Please check 
out and share my blog on life with multiple disabilities 
<https://lifewithmultipledisabilities.home.blog>. Click the "Available 
Groups" link to find support and advocacy groups for people with 
multiple disabilities.

**Comment by lukaszgo1** [comment] 2020-02-20 13:43
have you tried with all add-ons disabled? For reference I cannot reproduce this with latest portable Alpha.

**Comment by Living4God1991** [comment] 2020-02-20 13:49
I just did and it does seem to be an add-on issue because characters are 
read when all add-ons are disabled. Now I just need to figure out which 
add-on is causing the problem.

Email Signature

Lanie Molinar

Disability Rights Advocate and Software Engineering Student at Brigham 
Young University-Idaho <https://byui.edu>

Connect with me on LinkedIn <https://linkedin.com/in/laniegmolinar/>

Phone: 832-284-2426

Certified expert with general use of NVDA (Non Visual Desktop Access and 
use of it with Microsoft Word. Learn more here 
<https://certification.nvaccess.org/>.

NVDA Certified Expert logo"NVDA Certified Expert (with Microsoft Word)" 
logo

Do you have multiple disabilities or know someone who does? Please check 
out and share my blog on life with multiple disabilities 
<https://lifewithmultipledisabilities.home.blog>. Click the "Available 
Groups" link to find support and advocacy groups for people with 
multiple disabilities.

**Comment by Living4God1991** [comment] 2020-02-20 13:58
Interestingly, restarting with all add-ons disabled fixes the issue but disabling them manually and then restarting does not.

**Comment by Mohamed00** [comment] 2020-02-20 14:25
Not using speech viewer here as well. I have tried disabling all addons but it has no effect, characters are still not read no matter what synthesizer I use.

**Comment by leonardder** [comment] 2020-02-21 11:20
Have you enabled the scratchpad directory and have any code in the scratchpad?

**Comment by amirsol81** [comment] 2020-02-21 12:00
An alpha release of the SpeechHistory add-on, which is an older variant adopted for Python 3, seems to be behind this issue, and it affects all NVDA releases based on Python 3. It affects movement with Left/Right arrows though, interestingly, character selection with SHIFT+Left and Right isn't affected.

**Comment by Mohamed00** [comment] 2020-02-21 12:47
I do have that version, but it seems that the issue persists even if I remove it. Developer scratchpad is not enabled.

**Comment by Mohamed00** [comment] 2020-02-21 13:08
Hmm, I tried resetting completely to factory defaults, deleting the entire NVDA folder and restarting, and also manually going into my old nvda.ini and clearing out a lot of configurations for various things I don't use. I'm not sure what exactly the issue was, but doing that seems to have fixed it, though the Speech History issue remains. Is this safe to close and consider resolved?

**Comment by Mohamed00** [comment] 2020-02-21 13:13
Never mind, found the issue that wasn't specific to speech history. It appears that enabling the speech category in debug logging under advanced settings somehow breaks character reading.

**Comment by Living4God1991** [comment] 2020-02-21 14:04
Just responding to let you all know I figured out what was causing my 
problem. I was using a version of the Speech History add-on that had 
been posted to the add-ons list with some changes to make it work with 
NVDA 2019.3 That add-on was causing the problem. Once I figured that out 
and removed it things started working normally.

Email Signature

Lanie Molinar

Disability Rights Advocate and Software Engineering Student at Brigham 
Young University-Idaho <https://byui.edu>

Connect with me on LinkedIn <https://linkedin.com/in/laniegmolinar/>

Phone: 832-284-2426

Certified expert with general use of NVDA (Non Visual Desktop Access and 
use of it with Microsoft Word. Learn more here 
<https://certification.nvaccess.org/>.

NVDA Certified Expert logo"NVDA Certified Expert (with Microsoft Word)" 
logo

Do you have multiple disabilities or know someone who does? Please check 
out and share my blog on life with multiple disabilities 
<https://lifewithmultipledisabilities.home.blog>. Click the "Available 
Groups" link to find support and advocacy groups for people with 
multiple disabilities.

**Comment by fernando-jose-silva** [comment] 2020-02-21 16:13
I continue to have this problem.
When I enable the speech viewer and try to read character by character, nvda does not read the characters.
I restarted nvda with add-ons disabled and the problem continued.
log:
[caractreres.txt](https://github.com/nvaccess/nvda/files/4236948/caractreres.txt)

**Comment by DrSooom** [comment] 2020-02-21 18:20
See also: Issue #10133

**Comment by Adriani90** [comment] 2020-02-25 20:22
I can confirm this issue is reproducible if "speech" is enabled in the debug logging under advanced settings.
cc: @michaelDCurran, @jcsteh

**Comment by feerrenrut** [comment] 2020-03-09 15:57
Closing as a duplicate of #10741 which has more info

**Closed by feerrenrut** 2020-03-09 15:57 UTC
