### ISSUE TITLE
Script Error pop-up window displayed when clicking "Caps" key

### ISSUE THREAD

**Issue by nelmerse** [nvaccess/nvda#5982] opened 2016-05-20 17:55 UTC
When user tries to create an account, she enters password and hits "caps" key to re-enter password. This returns a scrip error pop-up window. Please refer to attached screenshot for details.
![screen shot 2016-05-20 at 1 16 52 pm](https://cloud.githubusercontent.com/assets/3044119/15436980/72cc80fc-1e92-11e6-989d-153f42ccda1c.png)

**Comment by jcsteh** [comment] 2016-05-20 22:23
Please provide further information, including the browser used and an 
example website or test case where this issue can be reproduced. Also, 
please note that the lead developers (and most other developers) are 
blind, so we cannot read screen shots. You will need to provide any 
information in screen shots as text. Thanks.

**Comment by nelmerse** [comment] 2016-05-23 13:10
- Browsers used: FF45. FF46, Chrome 50, IE10, and IE11. 
- Test case: create an account. 
- Website: amazon.com
- Go to amazon.com and enter your name, email, password, and password again.
- If user clicks "Caps" key in password and/or password again, Script Error pop-up windows is displayed.

**Comment by nelmerse** [comment] 2016-05-25 01:01
Any update on this? Thanks!

**Comment by jcsteh** [comment] 2016-05-25 02:12
I can't reproduce this in either Firefox or Chrome. I can reproduce it 
in IE, but you noted you're seeing it in all three browsers. Please confirm.

**Comment by jcsteh** [comment] 2016-05-25 02:23
Duplicate of #3362.

**Closed by jcsteh** 2016-05-25 02:23 UTC
Labels: duplicate

**Comment by nelmerse** [comment] 2016-05-25 15:20
Correction: this is happening in IE only.
