### ISSUE TITLE
Outlook 2016 crashes when certain messages are opened

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#9032] opened 2018-12-08 16:21 UTC
MS Outlook 2016 crashes when opening certain messages. This only occurs with NVDA. The behavior has not been observed when Narrator is running. It does not occur frequently but does enough times that it causes interruptions in productivity. I have only observed the crashes when opening HTML messages. While this does not mean that crashes are only related to HTML messages, it's a strong indication. I have pasted the relevant debug log at the end of the issue report below.

### Steps to reproduce:
1. Open Outlook
2. Open message

### Actual behavior:
Outlook crashes after the message is opened.

### Expected behavior:
Outlook should not crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-16382,a2545511

#### Windows version:
Insider 10.0.18290 

#### Name and version of other software in use when reproducing the issue:
Outlook 2016 
#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
NVDA 18-3 and other alpha/betas

### NVDA debug log

IO - speech.speak (09:34:46.720):
Speaking [LangChangeCommand (u'en_US'), u"unread From Uber, Subject Pratik, you're invited to join Uber Rewards, Received Fri 12/7/2018 12:38 PM, Size 105 KB,  row 9  column 1  through 9  8 of 47880  level 1"]
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:46.730):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:46.730):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:48.411):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:48.411):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (09:34:49.582):
Cancelling
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:49.592):
Queue empty, done processing
IO - inputCore.InputManager.executeGesture (09:34:50.016):
Input: kb(laptop):enter
IO - speech.speak (09:34:51.065):
Speaking [LangChangeCommand (u'en_US'), u"Pratik, you're invited to join Uber Rewards - Message (HTML) "]
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:51.085):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:51.131):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:51.131):
Calling idle on audio player
IO - speech.speak (09:34:51.236):
Speaking [LangChangeCommand (u'en_US'), u'dialog']
DEBUG - treeInterceptorHandler.update (09:34:51.540):
Adding new treeInterceptor to runningTable: <appModules.outlook.MailViewerTreeInterceptor object at 0x079EA850>
IO - speech.speak (09:34:51.565):
Speaking [LangChangeCommand (u'en_US'), u'Message  multi line']
DEBUG - queueHandler.registerGeneratorObject (09:34:51.565):
Adding generator 258
INFO - external:globalPlugins.dictation.flushCurrentEntry (09:34:51.565):
text u'\n'
IO - speech.speak (09:34:51.565):
Speaking [LangChangeCommand (u'en_US'), 'new line']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:52.391):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:52.401):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:52.401):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:52.657):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:52.657):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver._callback (09:34:53.015):
Done pushing audio
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:53.015):
Calling idle on audio player
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (09:34:53.200):
Queue empty, done processing
DEBUGWARNING - watchdog._watcher (09:34:56.102):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 217, in <module>
  File "core.pyc", line 516, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 985, in Notify
  File "core.pyc", line 487, in run
  File "queueHandler.pyc", line 75, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 774, in speakTextInfo
  File "treeInterceptorHandler.pyc", line 212, in getTextWithFields
  File "NVDAObjects\window\winword.pyc", line 710, in getTextWithFields

DEBUGWARNING - NVDAObjects.window.winword.WordDocumentTextInfo.getTextWithFields (09:34:56.193):
winword_getTextInRange failed with 1726
DEBUGWARNING - queueHandler.pumpAll (09:34:56.263):
error in generator 258
Traceback (most recent call last):
  File "queueHandler.pyc", line 75, in pumpAll
  File "sayAllHandler.pyc", line 128, in readTextHelper_generator
  File "speech.pyc", line 774, in speakTextInfo
  File "treeInterceptorHandler.pyc", line 212, in getTextWithFields
  File "NVDAObjects\window\winword.pyc", line 713, in getTextWithFields
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\window\winword.pyc", line 940, in _get_text
  File "comtypesMonkeyPatches.pyc", line 37, in new__getattr__
  File "comtypes\client\dynamic.pyc", line 110, in __getattr__
  File "comtypes\automation.pyc", line 708, in GetIDsOfNames
COMError: (-2147023174, 'The RPC server is unavailable.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (09:34:56.328):
application outlook closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (09:34:56.388):
Killed treeInterceptor: <appModules.outlook.MailViewerTreeInterceptor object at 0x079EA850>
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (09:34:56.394):
Cancelling

**Comment by TylerK93** [comment] 2019-11-19 23:42
I have a similar problem, and it just started today. Here's what shows up in my NVDA log when I set the logging level to DebugWarning:

ERROR - RPC process 17940 (nvda_slave.exe) (17:35:12.058):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 93, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1247, in GetActiveObject
  File "_ctypes/callproc.c", line 946, in GetResult
WindowsError: [Error -2147221021] Operation unavailable
DEBUGWARNING - watchdog._watcher (17:35:13.194):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 490, in run
  File "queueHandler.pyo", line 86, in pumpAll
  File "queueHandler.pyo", line 53, in flushQueue
  File "eventHandler.pyo", line 62, in _queueEventCallback
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 1030, in event_gainFocus
  File "NVDAObjects\behaviors.pyo", line 481, in reportFocus
  File "NVDAObjects\__init__.pyo", line 918, in reportFocus
  File "speech.pyo", line 416, in speakObject
  File "speech.pyo", line 289, in speakObjectProperties
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "appModules\outlook.pyo", line 446, in _get_name
  File "baseObject.pyo", line 31, in __get__
  File "appModules\outlook.pyo", line 123, in _get_nativeOm
  File "appModules\outlook.pyo", line 112, in _registerCOMWithFocusJuggle

I am using Office 365, and my Outlook version reports as "Microsoft Outlook for Office 365 MSO (16.0.12228.20202) 64-bit."

**Comment by PratikP1** [comment] 2019-11-19 23:47
Ditto. This started for me again. I had the first crash this morning followed by another crash a few hours ago. I didn’t have the time to trace it.

**Comment by Adriani90** [comment] 2020-01-19 19:54
Could you please attach a non confidential message here which allows us to reproduce this crash?

**Comment by PratikP1** [comment] 2020-01-20 16:51
Regrettably, I do not have examples of non-confidential emails to share. Crashes were with confidential messages. 

I will say, however, that this issue stopped after a few days since my last response. I would be comfortable with this issue being closed at this time, to be opened again should it become necessary.

**Comment by Adriani90** [comment] 2020-01-20 20:40
Thanks for reporting back. Closing as works for me. Please comment on it if you still see this issue. Thanks!

**Closed by Adriani90** 2020-01-20 20:40 UTC
Labels: worksforme
