### ISSUE TITLE
NVDA lose the settings a few times to start the windows

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5709] opened 2016-01-24 15:28 UTC
A few times to start the windows 10 NVDA lose the settings, this occurs with low frequency, but already happened a few times.
 Sometimes there is no error message, other times it is informed that the configuration file contains errors.

**Comment by jcsteh** [comment] 2016-01-24 22:55
Duplicate of #3165.

**Closed by jcsteh** 2016-01-24 22:55 UTC
Labels: duplicate

**Comment by fernando-jose-silva** [comment] 2016-01-25 16:39
thank you

 

 

De: James Teh [mailto:notifications@github.com] 
Enviada em: domingo, 24 de janeiro de 2016 20:56
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>
Assunto: Re: [nvda] NVDA lose the settings a few times to start the windows (#5709)

 

Duplicate of #3165 <https://github.com/nvaccess/nvda/issues/3165> .
