### ISSUE TITLE
Installing an add-on from Explorer when the add-on store is open pops twice asking dialog

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15427] opened 2023-09-11 17:30 UTC
### Steps to reproduce:
1. Start NVDA and open the add-on store
2. Keep the add-on store window open, then go to Explorer and install an NVDA add-on package.
3. NVDA pops up a dialog and asks:"Restart NVDA', 'dialog', 'Changes were made to add-ons. You must restart NVDA for these changes to take effect. Would you like to restart now?"
4. Press 'Y', Another dialog box from the add-on store appears on the screen.
5. Continue press 'Y'.
### Actual behavior:
Stap4: NVDA does not restart but remains silent.
Stap5: NVDA restart.
### Expected behavior:
Perform step 4 NVDA should restart.
### NVDA logs, crash dumps and other attachments:
[nvda.txt](https://github.com/nvaccess/nvda/files/12578885/nvda.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA-alpha-29160
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3393
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment] 2023-09-11 20:27
Duplicate of #14525: a bug already present with the old add-on manager, but still present with the add-on store.

**Closed by CyrilleB79** 2023-09-11 20:27 UTC
