### ISSUE TITLE
NVDA keeps saying "file ///C/.../myfile.ods" in LibreOffice Calc

### ISSUE THREAD

**Issue by urdle** [nvaccess/nvda#15264] opened 2023-08-06 13:49 UTC
### Steps to reproduce:
Use libreoffice Calc with any saved file, place the cursor on any cell.
LibreOffice Calc 7.5
NVDA 2023.1
Windows 10 and 11 (tried on 2 computers)
Language : French

### Actual behavior:
NVDA says "file slash slash slash C slash ......... myfile.ods" whenever the mouse is hovering cells (and many other blank spaces in calc)

### Expected behavior:
Just like on Excel, NVDA says what's written in the cell and the position

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
NVDA 2023.1

#### Windows version:
Windows 10 and 11 (tried on 2 computers)

#### Name and version of other software in use when reproducing the issue:
LibreOffice Calc 7.5.5.2

#### Other information about your system:
Tried fresh install, both LibreOffice and NVDA, and default settings

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-on installed

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by XLTechie** [comment] 2023-08-07 06:13
cc @michaelweghorn

**Comment by michaelweghorn** [comment] 2023-08-08 17:08
This is caused by incorrect handling in LibreOffice, so I've created a bug report there:
https://bugs.documentfoundation.org/show_bug.cgi?id=156679

I'm working on a fix, will post an update here once that's done.

@urdle wrote:
> Just like on Excel, NVDA says what's written in the cell and the position

For me, NVDA just says the text in the cell, no position. Is there any extra option in NVDA to enable that?

**Comment by Adriani90** [comment] 2023-08-08 21:51
yes usually you can enable reporting of table cell coordinates in NVDA document formating settings.

**Comment by michaelweghorn** [comment] 2023-08-09 05:56
The 2 LibreOffice fixes are merged now:
https://git.libreoffice.org/core/commit/39302875c27d4cf4246bb7520ed90abcf0af777a
https://git.libreoffice.org/core/commit/d1d07992a89ba503f1d457a8f79926063f4d3f9c

So that will work from LibreOffice 24.2 on. If anybody wants to test it, there are daily builds available at https://dev-builds.libreoffice.org/daily/master/current.html - but you need to wait for the next one to become available because the current one doesn't yet include the fixes.

There's a difference in behavior with Excel, quoting from my commit message:

> With this change in place, NVDA now announces the
> text when hovering over the text and mouse tracking
> is enabled in NVDA (which is the case by default).
> Other than with Microsoft Excel, the text is only
> announced when the mouse is actually over the text,
> not over free space in the cell, which might be
> because Excel uses UIA and the UIA equivalent,
> `ITextProvider::RangeFromPoint` [2] shall also return
> the index of the closest character when the point
> itself is not over the actual bounds of any
> character.



> yes usually you can enable reporting of table cell coordinates in NVDA document formating settings.

That is enabled for me and cell position/coordinates are announced when I move focus between cells using the arrow keys. But they're not announced in either Excel (Office Professional Plus 2021) or LibreOffice, but I think that's unrelated to the issue discussed here.

**Comment by seanbudd** [comment] 2023-08-09 06:38
Going to close this as solved as the fixes have landed

**Closed by seanbudd** 2023-08-09 06:38 UTC
Labels: blocked/needs-external-fix, feature/mouse-tracking, p2, app/libreoffice, audience/low-vision, triaged

**Comment by urdle** [comment] 2023-08-21 08:00
> For me, NVDA just says the text in the cell, no position. Is there any extra option in NVDA to enable that?

My bad, i'm sorry, you're right, it only tells the position (row, column) when I navigate through the cells with the keyboard.

Thank you again for helping getting it fixed !
