### ISSUE TITLE
Add ability to change update channel for developers

### ISSUE THREAD

**Issue by OzancanKaratas** [nvaccess/nvda#17172] opened 2024-09-14 09:56 UTC
### Is your feature request related to a problem? Please describe.
The Update Channel Selector add-on allows developers to change update channel. For example, a developer can switch to standard channel from alpha channel to test other versions of NVDA. This is a more flexible way to find a answer for question “Have you tried any other versions of NVDA?”.
### Describe the solution you'd like
Logic of the Update Channel Selector add-on can be integrated into NVDA core.
### Describe alternatives you've considered
This feature should work well with #17151.
### Additional context
None

Thanks @nvdaes, @jmdaweb and all members of community working for this project. I hope they will join this discussion.

**Comment by nvdaes** [comment] 2024-09-14 10:12
To avoid confusions, I have a fork of the updateChannel add-on, but I've just performed some review time ago. I'm clarifying this since I'm mentioned in the first place, but I'm not maintaining this project and I'm not reflected as a contributor of this add-on since I didn't participate in its development beyond some add-on review.
Kind regards

**Comment by Adriani90** [comment] 2024-09-15 20:54
Closing as duplicate of #10679

**Closed by Adriani90** 2024-09-15 20:54 UTC
Labels: close/duplicate
