### ISSUE TITLE
Error when starting while holding down control

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#9337] opened 2019-03-01 21:54 UTC
### Steps to reproduce:
Start NVDA while holding down control
### Actual behavior:
```
ERROR - keyboardHandler.internal_keyDownEvent (13:46:57.943):
internal_keyDownEvent
Traceback (most recent call last):
  File "keyboardHandler.pyc", line 178, in internal_keyDownEvent
  File "inputCore.pyc", line 421, in executeGesture
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "inputCore.pyc", line 145, in _get_script
  File "scriptHandler.pyc", line 87, in findScript
RuntimeError: Set changed size during iteration
```
### Expected behavior:
No error
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-16874,8573a05b
#### Windows version:
Version 1809 (OS Build 17763.316)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by josephsl** [comment] 2019-03-04 04:27
Hi,

Confirmed - I was wondering how I can produce this problem, and we finally found a way to do that.

Note that this also occurs if one holds down Alt key while restarting NVDA.

Thanks.

**Comment by leonardder** [comment] 2019-03-04 18:46
This error is slightly trivial. I don't know whether it is worth it to fix it by iterating over a copy of the global plugins set, for example.

**Comment by Adriani90** [comment] 2020-05-16 17:55
This does not occur anymore in NVDA alpha-20220,1c4519a6 and Windows 10 1909 Update. Closing as works for me.

**Closed by Adriani90** 2020-05-16 17:55 UTC
Labels: close/worksforme
