### ISSUE TITLE
Disable logging by default in release builds.

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#12087] opened 2021-02-20 21:02 UTC
### Is your feature request related to a problem? Please describe.
Not really. It would be nice, but it's not a huge deal.
### Describe the solution you'd like
For the default log level to be set to none in release builds.
### Describe alternatives you've considered
I really haven't. The main one would be to add the -l switch every time you start NVDA, and set that to disabled.
### Additional context
Info really isn't enough for a bugfix, and it doesn't seem necessary to have it enabled on a lot of machines of users that run stable builds, who likely have no idea what the log is for.

**Comment by feerrenrut** [comment] 2021-02-22 05:19
Perhaps you could explain why you think it would be nice. What problem does logging cause?

Logging can often help to get an idea about the cause of a problem after it has occurred. Having logging be default makes it easier to provide support if something goes wrong.

**Comment by trypolis464** [comment] 2021-02-22 13:02
True. And it doesn't necessarily cause a problem, but I have never found info to be enough for a bug report, and it's more than likely that people on stable builds won't use the log, at least from what I've seen.

**Comment by cary-rowen** [comment] 2021-02-22 13:07
I also think that the stable version can turn off the log by default. People who need the log may also know how to turn it on? Conversely, logs may not be of much use to users of the stable version.

**Comment by lukaszgo1** [comment] 2021-02-22 13:14
The question here is not how useful the log at info level is but rather what improvements disabling it would   bring to users of stable versions. Unless there are any I vote to close this issue.

**Comment by feerrenrut** [comment] 2021-02-23 10:16
The default log level can often be useful for reports of errors, crashes or freezes. By default we want to make these most serious issues easy to report.

I'll close this for now. I'll consider re-opening if justification for the suggestion can be provided.

**Closed by feerrenrut** 2021-02-23 10:16 UTC
