### ISSUE TITLE
Provide an option to prevent the audio device from going to sleep

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10829] opened 2020-03-01 09:01 UTC
### Is your feature request related to a problem? Please describe.

Laptops are notorious for having audio output devices turn off after some period of silence to save power. The same happens when pairing with bluetooth speakers / headphones. This causes the following problems:

* Increased latency, due to the audio device waking up before speech is heard. This is a really terrible experience for end users
* The start of the speech utterance being cut off

### Describe the solution you'd like

Build the functionality directly into NVDA to prevent the audio output device from going to sleep when NVDA is running, e.g by playing silence.

### Describe alternatives you've considered

This has been implemented in the Bluetooth Audio add-on and the Silencio program. However, this requires users to explicitly install these programs. Less technical users may not understand what's going on, and attribute this to an unfixable problem with NVDA or their laptop. 

Having this built-in and documented in the user guide would be extremely helpful, since this is a widespread plague.

**Comment by Neurrone** [comment] 2020-03-01 09:06
I'm wondering if its better for this to just be something that NVDA just does by default, with an option to turn it off e.g, to save power.

**Comment by Brian1Gaff** [comment] 2020-03-01 10:17
I believe that this problem is solved by a program which runs independently 
of any screenreader. I don't recall the name off the top of my head but its 
something like silencio or something. The program sends silence to the audio 
channels when run. It is needed by many people not just the blind, since the 
drivers supplied by relate are bugged and cannot be set to be always on. One 
might have expected Microsoft to get this fixed as so many people now have 
this issue, even when playing music etc. I suppose it does save some power, 
but is totally pointless when a machine is running from the  mains power 
unit.

I don't have a machine up to date enough to need this, thankfully!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2020-03-01 10:49
I was trying to find the software, but I did find this page, which seems to 
be able to do a heck of a lot more, but cannot check as I don't have any 
sound issues.
https://veg.by/en/projects/soundkeeper/

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by JulienCochuyt** [comment] 2020-05-03 12:22
+1 for integrating this feature in NVDA as an optional behavior.
It would certainly increase the experience of the less tech-aware users.
Note however that I could find some wireless audio devices for which the strategy adopted by the Bluetooth Audio add-on is not enough to prevent the device from going to sleep. These might require some kind of "modulated-pseudo-silence" (if this wording makes any sense).

**Comment by leonardder** [comment] 2020-05-04 19:17
I believe this is going to be fixed by #11024

**Comment by Adriani90** [comment] 2020-05-04 20:33
Actually, I am closing this as duplicate of #5172. This behavior could be the default, an optional setting for this is in my view not needed, this is usually done automatically by other screenreaders like jaws for example. But the exact implementation of this can be discussed further in #11024.

**Closed by Adriani90** 2020-05-04 20:33 UTC
Labels: close/duplicate

**Comment by ondrosik** [comment] 2020-09-15 06:29
Just for reference, the program is called Sillenzio, available at
http://www.stefankiss.sk/programy/silenzio/Silenzio_1.0_setup.exe
The problem is now solved but you can still use it if you prefer to not close the audio stream at all. Similar functionality can be done via Bluetooth audio addon
https://addons.nvda-project.org/addons/BluetoothAudio.en.html
