### ISSUE TITLE
inform the name of the menus when walking through them even if they are already open

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13806] opened 2022-06-16 16:52 UTC
### Steps to reproduce:
This has been around for a long time and applies to any software that has navigation menus.

To demonstrate the menus in Thunderbird and give context:
- open a message
- press `alt`
  - NVDA announces, "file"
- Press `right arrow` multiple times, NVDA announces
  -  "edit"
  - "display"
  - "go"

Then to demonstrate the actual problem:
- press `alt`
  - NVDA announces, "file"
- Press `down arrow`, NVDA announces "new"
- Press `right arrow`, NVDA announces "new menu"
- Press `right arrow`, NVDA announces "undo"
   - This is a menu item of the "edit" menu, but nvda doesn't announce "edit", focus is no longer in the "file" menu.

### Actual behavior:
NVDA announces menu item in a new menu without announcing the menu name.
>  NVDA announces "undo"

### Expected behavior:
Announce the menu name and right after the menu item name, when the user opens a new menu while previously inside another menu. E.G.
> edit menu, undo menu item.

This would support novice users who are still figuring out how to navigate windows.
If this causes inconvenience to experienced users, I suggest that you can enable and disable this type of ad.

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
nvda.exe, NVDA alpha-25587,fb1ce94d

#### Windows version:
22.621.160
#### Name and version of other software in use when reproducing the issue:
several
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, the problem occurs
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment] 2022-06-17 08:47
Maybe when this occurs a snazzy little sound could indicate you have in fact 
fallen off the previous menu and moved to another?
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "fernando-jose-silva" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Thursday, June 16, 2022 5:52 PM
Subject: [nvaccess/nvda] inform the name of the menus when walking through 
them even if they are already open (Issue #13806)

**Comment by XLTechie** [comment] 2022-06-17 18:08
> Maybe when this occurs a snazzy little sound could indicate you have in fact
> fallen off the previous menu and moved to another?

That is only part of the problem. The other part is that you don't know which 
menu you're in now, unless you have memorized the layout of the menubar.

**Comment by XLTechie** [comment] 2022-10-11 07:37
I whole heartedly support this feature request.

It is not even limited to novice users.  Experienced users, using an unfamiliar 
program with lots of menus, or one that has frequent menu reorganizations 
between versions, will also face this issue.  Audacity is an example in these 
categories.

I do not support making this selectable. It is too small of a change IMHO, to 
warrant an option; and for those who don't like it it is a very microscopic 
inconvenience I think.

**Comment by Adriani90** [comment] 2024-01-16 21:34
actually this is a duplicate of #4278. So closing. Note this has been introduced earlier but had drawbacks due to many applications not naming their menus correctly. This has been reverted in https://github.com/nvaccess/nvda/commit/dda6017c4dfb77eddd3554ef2a35a0b3bd4c3018

So if this is implemented again, then I think it makes sense to do it on an app module level. So let's continue the discussion on #4278 maybe you can implement it for thunderbird and firefox only. This works as expected in Libre Office for example.

**Closed by Adriani90** 2024-01-16 21:34 UTC
Labels: close/duplicate, p5, triaged
