### ISSUE TITLE
Microsoft office online applications trigger error on carrot movement

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#5834] opened 2016-03-26 22:56 UTC
I have just seen this behavior in Word online. When arrowing through an open document, the following error is thrown every time:
ERROR - scriptHandler.executeScript (23:45:57):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x04FE1950>> with gesture u'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 675, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 303, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 252, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'
IO - speech.speak (23:45:57):

After this happens, the accessibility hint for the editable section is repeated, I think this is an ARIA alert but haven't checked to make sure.
Seems like focus is lost for a very short while and then regained, is this a problem with Office online, NVDA or Firefox?
This is on Windows 10 latest insider build, latest Next snapshot of NVDA.

**Comment by josephsl** [comment] 2016-03-26 22:58
Hi, have you observed this problem when using other browsers? Thanks.

**Comment by zersiax** [comment] 2016-03-26 23:03
Just tested in IE. The problem is not reproduceable there, but NVDA becomes very sluggish to the point of near-unresponsiveness in that browser.

**Comment by josephsl** [comment] 2016-03-26 23:06
Hi, I see. How about Chrome, and is this sluggishness observed when using another screen reqader? Thanks.

**Comment by zersiax** [comment] 2016-03-26 23:15
Surprisingly, Chrome is actually the best one of the bunch so far. It does repeat 'praagraph editable"  before ever line in the document, which is annoying, but no exceptions and no sluggishness. I will try with JAWS 14 in Firefox and see how that goes, just a minute.

**Comment by ehollig** [comment] 2017-08-01 22:11
Any update on this issue? If you could provide an updated test case, along with the tested browser so that I and others can replicate this issue. @zersiax

**Comment by Adriani90** [comment] 2019-02-18 23:23
@zersiax could you please test last NVDA alpha and see if the issue is still reproducible? Thanks.

**Comment by Adriani90** [comment] 2019-12-14 18:06
I am testing with NVDA 2019.3 Beta 1 on Firefox 71. I cannot reproduce this issue. Carret movement works as expected and no errors are raised. Closing as works for me.

**Closed by Adriani90** 2019-12-14 18:06 UTC
Labels: worksforme
