### ISSUE TITLE
NVDA Incorrectly Starts Reading Dates 1 Character At A Time When Keyboard Navigating a react-datepicker component

### ISSUE THREAD

**Issue by cayusebryce** [nvaccess/nvda#12644] opened 2021-07-13 16:17 UTC
### Steps to reproduce:
1. Open a web page that uses a date picker created with the react-datepicker component.  Several working examples can be found a the react-datepicker website: https://reactdatepicker.com/
2. Tab to the input element to open the date picker calendar.
3. Attempt to navigate per day (left or right arrows), per week (up or down arrows), per month (home or end keys) or by year (page up or page down keys).

### Actual behavior:
Almost always, when trying to navigate the dates of the calendar with a keyboard, a user can move the focus at most one day before NVDA captures the keyboard input.  If using the arrow keys, NVDA will start to read the currently selected date one character at a time.

### Expected behavior:
Navigation to the next calendar item would occur as outlined in step 3 above.

### System configuration
Windows 10 Pro
Chrome 90/Firefox 88

#### NVDA version:
2021.1

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
react-datepicker 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu? yes

**********
This issue was discovered by our QA team while testing some accessibility work our company is currently conducting. FWIQ, the date picker functionality works as expected with other screen reader/OS/browser combos, and if NVDA is turned off on Windows, the date picker functions properly again.

**Comment by feerrenrut** [comment] 2021-07-14 03:48
I think what you are saying is that when navigating NVDA automatically transitions out of focus (forms / application) mode and into browse mode. In focus mode key presses are passed through to the underlying application, in browse mode they are used for quick navigation. Do you hear a "boop" or "click" noise, these indicate browse mode and focus mode respectively? The audio indication (earcon) can be replaced with speech "focus mode", "browse mode" via "Audio indication of focus and browse modes  check box " in the "browse mode" settings panel.

I tried a few of the samples on that issue and can not reproduce this issue with Edge (Chromium) `Version 91.0.864.64 (Official build)`

Screen readers rely on the browser to provide accessibility information. Different screen readers use different aspects of the API's or entirely different API's. Without careful consideration of these variables, trying to isolate the cause of the bug by comparing different screen readers can be quite misleading.

Please isolate a minimal example and provide specific steps to demonstrate the issue. Being specific about what NVDA reports during the steps helps us to verify that we are following correctly.

**Comment by Adriani90** [comment] 2023-04-14 08:55
This works as expected with NVDA last alpha and Firefox 111 as well as Chrome and Edge 112.

I am closing as works for me. Please comment if you are still having this issue and we can reopen.

**Closed by Adriani90** 2023-04-14 08:55 UTC
Labels: close/worksforme
