### ISSUE TITLE
When MathML is on a Button, the Button becomes Difficult to Activate

### ISSUE THREAD

**Issue by SuzanneTaylor** [nvaccess/nvda#11215] opened 2020-05-27 21:59 UTC
### Steps to reproduce:

1. In Firefox  with NVDA running, go to the examples here: http://www.manateeroad.com/BugReports/MathMLonButtons.html
2. Navigate to either of the two example buttons
3. Notice that the MathML reads well and can be navigated! This is awesome!
4. Press Space or Enter, as though to activate the button.
5. Notice that Space and Enter don't activate the button.

### Actual behavior:
You can't activate the button with Space or Enter. Or even Escape, followed by Space or Enter. The only way to activate the button is with Control Space or Enter, or by leaving the button and returning in forms mode, at which time the button will not appear to be labeled.

### Expected behavior:
Space or Enter should activate the button. If that is not possible, at least Escape or Insert Space should allow this without having to leave the button first.

**Comment by Adriani90** [comment] 2020-06-01 10:01
This is expected behavior. see Math ML documentation of shortcuts at
https://docs.wiris.com/en/mathplayer/navigation_commands
This is also documented in NVDA's user guide at chapter 7.1.

Pressing enter reports you the current operation you are in (i.e. in the numerator of a fraction) along with the operation inside it. This is very useful for example in nested fractions.
Spacebar report you the current cell you are in or the current operator or number you are focusing. So enter or space bar are already part of Math ML navigation.
If you have a special use case where you can justify that the behavior of enter or space should be changed in Math ML, you should create an issue with the Math ML developers.
But since ctrl+enter actiavtes the button, I don't see a need for change here.
I am closing this issue because there is nothing NVDA can do in this case.

**Closed by Adriani90** 2020-06-01 10:01 UTC

**Comment by SuzanneTaylor** [comment] 2020-06-03 15:09
Thanks Adriani90 - Is use of ctrl+enter for this purpose documented anywhere? I just want to be sure that if a lot of content is set up depending on this, it will keep working in the future.

**Comment by Adriani90** [comment] 2020-06-03 15:35
Hello,

 

this does not seem to be documented properly. I will submit a pull request to NVDA and will include this in the user guide.

 

Thanks for reporting.

 

 

Von: Suzanne Taylor <notifications@github.com> 
Gesendet: Mittwoch, 3. Juni 2020 17:10
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] When MathML is on a Button, the Button becomes Difficult to Activate (#11215)

 

Thanks Adriani90 - Is use of ctrl+enter for this purpose documented anywhere? I just want to be sure that if a lot of content is set up depending on this, it will keep working in the future.

**Comment by SuzanneTaylor** [comment] 2020-06-03 16:16
thanks so much!
