### ISSUE TITLE
Microsoft Lync 2010: Deleted Characters not taken into account when feedback set to read Typed Words

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#5556] opened 2015-11-29 14:01 UTC
When typing text into an IM window from within Lync 2010, if characters are deleted, the correct word typed and then a space left between words NVDA currently outputs the wrong text that has been entered. This appears to occur because NVDA doesn't recognise that characters have been deleted and simply announces everything that has been typed since a space was last left within the text.

Ultimately, if at all possible it'd be beneficial if the behaviour of Office applications could be mirrored within Lync, i.e. NVDA takes into account deleted characters as is done with Word.

**Comment by leonardder** [comment] 2017-07-17 10:24
@Elliott94: Is this still reproducible? If so, could you provide exact steps to reproduce (e.g. what do you type, what does NVDA say, etc.)?

**Comment by elliott94** [comment] 2017-07-17 19:02
Unfortunately, I no longer have access to a functional Lync installation and since Skype for Business is now the preferred option, I'm happy for this to be closed unless anybody else can provide feedbac.

**Comment by derekriemer** [comment] 2017-08-01 02:13
Are you happy for this to be closed?

**Comment by bhavyashah** [comment] 2017-08-01 02:38
@elliott94 said 'I'm happy for this to be closed unless anybody else can provide feedbac.' in https://github.com/nvaccess/nvda/issues/5556#issuecomment-315850082. Since no additional feedback has been received in the past two weeks with regards to this issue, I suppose we can safely close this ticket. @derekriemer @feerrenrut

**Closed** 2017-08-01 02:55 UTC
