### ISSUE TITLE
Suggest an option to change the time to automatically read character descriptions for the Delayed descriptions for characters on cursor movement feature

### ISSUE THREAD

**Issue by nhunam24** [nvaccess/nvda#14809] opened 2023-04-08 09:12 UTC
Hello. I have a suggestion to NVDA that add an option to be able to change the automatic character description interval for the Delayed descriptions for characters on cursor movement feature. I recommend this feature not because of a bug, but I find the default reading time not suitable for me, as well as I want to help a friend on a Vietnamese Facebook group, so I would like to suggest this feature to developers in the next NVDA versions. Thank!

**Comment by XLTechie** [comment] 2023-04-08 10:59
In mailing list discussions, I have observed dissatisfaction with the default 
timing as well, with some people clinging to the add-on because the built in 
version takes too long to announce.

Personally, I also find it too long.

If I recall correctly, NV Access was against making this independently 
configurable while the feature was being created.
Is that still the case @seanbudd?

**Comment by Adriani90** [comment] 2023-04-08 23:13
Closing as duplicate of #13967. Please add relevant input in that issue.

**Closed by Adriani90** 2023-04-08 23:13 UTC
Labels: close/duplicate
