### ISSUE TITLE
'Can not edit cells in excel.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7015] opened 2017-03-24 13:54 UTC
After upgrading to nvda 13946 when trying to edit a cell in excel 2013, an error sound is heard, just as trying to navigate the characters with right and left arrows while editing the cell will hear an error sound and the character is not informed.
Follow the log:

IO - speech.speak (10:47:08):
Speaking [u'Editar Item  edi\xe7\xe3o  um controle de edi\xe7\xe3o']
ERROR - eventHandler.executeEvent (10:47:08):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0BA04150> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 416, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\enhancedTouchGestures\globalPlugins\enhancedTouchGestures.py", line 94, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator.py", line 82, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 410, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 199, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\Favorite folders\globalPlugins\FavoriteFolders\__init__.py", line 161, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\AudioThemes3D\globalPlugins\audioThemes\__init__.py", line 125, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 900, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 812, in reportFocus
  File "speech.pyc", line 368, in speakObject
  File "speech.pyc", line 719, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 581, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 443, in _getTextWithFieldsForUIARange
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 84, in _get__controlFieldUIACacheRequest
COMError: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:47:13):
Input: kb(laptop):control+home
ERROR - scriptHandler.executeScript (10:47:13):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIA.script_caret_moveByLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0BA04150>> with gesture u'control+roume'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 719, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 581, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 443, in _getTextWithFieldsForUIARange
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 84, in _get__controlFieldUIACacheRequest
COMError: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:47:15):
Input: kb(laptop):rightArrow
ERROR - scriptHandler.executeScript (10:47:15):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIA.script_caret_moveByCharacter of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0BA04150>> with gesture u'direita'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 147, in script_caret_moveByCharacter
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 719, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 581, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 443, in _getTextWithFieldsForUIARange
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 84, in _get__controlFieldUIACacheRequest
COMError: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (10:47:17):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (10:47:17):
Developer info for navigator object:
name: u'Editar Item'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x0BA04150>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'um controle de edi\xe7\xe3o'
location: (90, 449, 94, 19)
value: None
appModule: <'excel' (appName u'excel', process ID 2084) at address b90e890>
appModule.productName: u'Microsoft Office 2013'
appModule.productVersion: u'15.0.4885.1000'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 133126
windowClassName: u'EXCEL6'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 3712
windowText: u''
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x440a948 at 5eb2d00>
UIA automationID: 
UIA frameworkID: Win32
UIA runtimeID: (42, 133126)
UIA providerDescription: [pid:5428,hwnd:0x20806 Main:Nested [pid:2084,hwnd:0x20806 Main(parent link):Unidentified Provider (unmanaged:EXCEL.EXE)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:UIAutomationCore.dll)]
UIA className: EXCEL6

**Comment by fernando-jose-silva** [comment] 2017-03-25 14:39
The problem occurs with a machine with windows 7 64 bit, office 2013 32bit.
I tested it now with a machine with windows 10 14393 64 bit and office 2016 32 bit and everything works fine.

**Comment by feerrenrut** [comment] 2017-03-27 09:59
I was not able to reproduce this in Excel with Office 2013 on Windows 10 with NVDA Version: `next-13949,b9c7808e`. To try to reproduce this I opened Excel and used the left and right arrows to move through the cells.

From the log, I noticed that there are several plugins enabled.
Could you please see if you are able to reproduce this with the plugins disabled?
Does this happen with a blank excel document? If not could you please attach the document that you were using.

For the maximum chance of reproducing this issue and being able to fix it, could you please attach your NVDA configuration?

**Comment by fernando-jose-silva** [comment] 2017-03-27 12:32
Thank you very much.
The problem occurred on the nvda next 13946, but as part of the fixes made in the nvda next 13949 the problems were fixed.
The problem occurred only in windows 7 and when the cell was edited, and we would navigate the cell characters with right and left arrows.

**Comment by jcsteh** [comment] 2017-03-27 12:54
Regression caused by (and subsequently fixed in) #6994. Closing.

**Closed by jcsteh** 2017-03-27 12:54 UTC
