### ISSUE TITLE
Problem activating some links with ENTER where SHIFT+ENTER works

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11244] opened 2020-06-10 06:54 UTC
### Steps to reproduce:

I've had reports of this on various pages, but I'll use https://yandex.ru/ which is a large website, popular in Russia.  The main page starts in a search edit, similar to Google.

1) Go to https://yandex.ru/
2) Type a search query.
3) Press ENTER
4) Press H or 2 to move to the first search result, reported as a heading level 2, but not a link.
5) Press ENTER.
6) Press SHIFT+ENTER

### Actual behavior:

At Step 5, nothing happens when you press ENTER.  At Step 6, the "link" is opened in a new window.

Without NVDA running, the link opens with ENTER at step 5 (well, if you tabbed to it, since you can't jump to heading without NVDA).

### Expected behavior:

The link should open at step 5.

#### NVDA version:

NVDA 2020.1 installed.

#### Windows version:

Windows 10 (64-bit) Version: 1903 build 18362.388

#### Name and version of other software in use when reproducing the issue:

Firefox Version: 
77.0.1 
 
Chrome Version: 
83.0.4103.97 

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I tried NVDA 2019.1 and it behaved the same.

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No difference

**Comment by DrSooom** [comment] 2020-06-11 03:17
Similar to or a duplicate of issue #9058.

**Closed** 2020-09-20 23:27 UTC
