### ISSUE TITLE
NVDA does not moves braille caret in libreoffice

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#8153] opened 2018-04-09 12:08 UTC
If you try to read in braille with Libreoffice,
the braille caret only moves itself for 2 or 1 lines, and no next.
I use the handy tech driver inserted into nvda, with a braille top 1.2 braille display on com2 port.
[braille.log](https://github.com/nvaccess/nvda/files/1889775/braille.log)
[braille.txt](https://github.com/nvaccess/nvda/files/1889776/braille.txt)
I attached the logs in txt and log also

**Comment by Adriani90** [comment] 2019-05-06 17:13
@lallerke1 are you still having this issue in Libre office 6.2.2?

**Comment by Adriani90** [comment] 2019-06-01 23:46
@FelixGruetzmacher, @nvdaes, @buevest, @gregjozk are you able to reproduce this issue? Unfortunately I do not have a braille display at hand so I cannot test this. Thanks.

**Comment by bdorer** [comment] 2019-12-02 22:58
I'm not able to reproduce this with latest LibreOffice.

**Comment by FelixGruetzmacher** [comment] 2019-12-03 08:17
Don't have LibreOffice on any of my machines right now, sorry.

Am Mo., 2. Dez. 2019 um 23:58 Uhr schrieb Bernd Dorer <
notifications@github.com>:

**Comment by Adriani90** [comment] 2020-02-04 22:06
We do not have updates from the initial author and most users do not seem to reproduce it. Closing as works for me.
Please comment on it if you still see this issue and we can reopen it. Thanks.

**Closed by Adriani90** 2020-02-04 22:06 UTC
Labels: Braille, libreoffice, worksforme
