### ISSUE TITLE
nvda does not advertise list numbering when spelling character by character

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9248] opened 2019-02-07 10:54 UTC
### Steps to reproduce:
open the word
type it
1- item 1
press enter
enter item 2
press enter enter item 3

now you can go to the line where there is item 1
press home
press left arrow
can do the same for item 2 and 3

### Actual behavior:
note that as you type in the first line 1- word creates a list.
when walking character by character when passing the focus where to the marker of the list with the numeral the nvda repeats the first letter of the written word

### Expected behavior:
When walking character by character would expect that when the focus goes through the list marker that word creates the nvda announce the number of the item in the list

#### NVDA installed/portable/running from source:
install
#### NVDA version:
2018.4.1
#### Windows version:
10 16299
#### Name and version of other software in use when reproducing the issue:
word 16.0.4266.1001

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2019-02-07 13:39
This is solved when using UIA in MS Word 2016.
 But this Problem is present in other MS Office Versions too.

**Comment by Adriani90** [comment] 2019-02-07 14:37
Closing as duplicate of #2649.

**Closed** 2019-02-07 14:38 UTC
Labels: duplicate
