### ISSUE TITLE
Copying and pasting issue in MS Word 2013 and NVDA 2018.3.2

### ISSUE THREAD

**Issue by DeamonDavid** [nvaccess/nvda#9012] opened 2018-12-03 14:00 UTC
### Steps to reproduce:
Open a MS Word document with some text.
Try to select and copy a portion of the text, and paste it another place in the document.
### Actual behavior:
Some of the copied text are missing when pasting it.
### Expected behavior:
All text copied should be included when pasting it.
#### NVDA version:
18.3.2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Microsoft Word 2013
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No. But when doing the same with AAWS running, this works as expected.

**Comment by Brian1Gaff** [comment] 2018-12-03 15:40
Just a thought, but do you have the zoom level high enough as if the pasted 
text say covers a boundary between page 1 and page 2 it looks like its not 
pasted, but what in fact has happened is that you have jumped to view page 
three as words weird logic puts page 1 and 2 alongside each other, moving 
the zoon to 200 makes it only display one page per page and page 2 moves 
underneath page 1 again.
 I hate this messing about myself. If only Word or for nvda had an  auto one 
page per page option.


Of course this is just a guess.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by DeamonDavid** [comment] 2018-12-04 07:56
Hmm... Not sure actually... How can I see if the zoom is set to anything else than just normal?
In anye case, if this is the thing, I'd hope for a fix, as this is quite disturbing things.

As said, when doing this using JAWS, it works properly when doing the same steps.

**Comment by Adriani90** [comment] 2019-02-04 13:49
@DeamonDavid could you please create a test document and upload it to this issue so we can reproduce this Problem? Is the text in a table or a text field?

**Comment by Adriani90** [comment] 2020-05-11 00:23
No further updates on this issue since more than one and a half years, closing as abandoned. Please comment on it if you are still having this issue and we can reopen.
I cannot reproduce with NVDA 2020.1.

**Closed by Adriani90** 2020-05-11 00:23 UTC
