### ISSUE TITLE
BrailleNote: Support for BrailleNote Touch via USB HID/new protocol

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#6524] opened 2016-10-31 16:33 UTC
Hi,

I haven't forgotten about my work on supporting Apex's scroll wheel and others...

According to a HumanWare staff, BrailleNote Touch firmware 2.0 includes a braille display mode to allow it to act as a braille display, with the Touch using USB HID and a new protocol (no more need for a custom USB serial driver). I plan to ask HumanWare AU to let @jcsteh have a demo unit so he can investigate this further.

Thanks.

**Comment by jcsteh** [comment] 2016-10-31 22:21
I've been in contact with HumanWare about this already.

* The protocol is based on the Brailliant B HID protocol, so it'll need to be supported by that driver rather than the BrailleNote driver.
* I believe the protocol has been updated slightly. I do have the documentation, but haven't taken a look yet.
* I have local contacts for HumanWare, so I should be able to get hold of a unit if I need one.

Thanks!

P3 because we want to support as many braille displays as possible, but this is new enough that it's also not urgent.

**Comment by NicklasMCHD** [comment] 2017-08-31 07:27
Hi.
Are there any plans as to when the Braillenote Touch is going to be supported.
I've tested the support with NVDA version 2017.3, tried to connect it with every type of Humanware display in "braille settings" but it didn't work.

**Comment by josephsl** [comment] 2017-08-31 12:19
Hi, last time I talked to Greg Stilson from HumanWare, a Touch should emulate newer Brailliant models. Thanks.

**Comment by NicklasMCHD** [comment] 2017-08-31 12:54
Hi.
I can confirm that, that isn't the case.
When I connect my bnt with the provided usb cable, install the usb serial drivers from humanware's website and go and try to set it up with nvda it just gives the following message:
Could not load the papenmeier display.

**Comment by ruifontes** [comment] 2017-08-31 13:47
Sorry, but you realy have selected Papenmeyer Braille displays?
Brailliant is a Humanware model...

Rui Fontes


-----Mensagem Original----- 
De: Nicklas Tegner
Data: 31 de agosto de 2017 13:54
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] BrailleNote: Support for BrailleNote Touch via 
USB HID/new protocol (#6524)



Hi.
I can confirm that, that isn't the case.
When I connect my bnt with the provided usb cable, install the usb serial 
drivers from humanware's website and go and try to set it up with nvda it 
just gives the following message:
Could not load the papenmeier display.

**Comment by jcsteh** [comment] 2017-09-01 01:11
I have a branch (brailliantBtHid) which updates the Brailliant B driver to support the BN Touch, among other things. Unfortunately, despite using the correct protocol, etc., it apparently doesn't work, even though it works just fine with the Brailliant via USB (and is the same protocol). I suspect some weirdness with either the HumanWare firmware or some Windows driver. In any case, we're going to need to debug this with a display. I won't have time to do this before I leave, so @MichaelDCurran will work with HumanWare to take care of this when he is able (though that may take some time given the transition at NV Access).

@NicklasMCHD, I'm not sure what serial driver you're referring to, but as far as HumanWare have told me, the BN Touch does not use USB serial. Instead, it uses USB HID, which does not need a driver installed.

**Comment by devinprater** [comment] 2018-02-17 03:35
Has anyone tried this driver from Humanware? See http://support.humanware.com/index.php?Action=Page.Link&PageLink=11541&To=http%3A%2F%2Fwww.humanware.ca%2Fweb%2FHumanWare%2FBrailleDrivers%2FBrailleTerminalTools2_1_0_6.exe
This is supposed to work with JAWS, but I suspect that it may give a sort of bridge for NVDA to cross, so that NVDA can use the braille note touch as well.

**Comment by michaelDCurran** [comment] 2018-02-21 06:34
Humanware have finally managed to get me a BrailleNote Touch so I can continue work on the driver. I now have it and am getting used to its layout and settings before I start looking into debugging / fixing the USB HID driver in the next few days. Bluetooth is working okay for me.

**Comment by leonardder** [comment] 2018-02-21 07:06
@michaelDCurran: Are you going to base this on @jcsteh's (brailliantBtHid branch (i.e. does it also implement Bluetooth HID)?

**Comment by jcsteh** [comment] 2018-02-21 07:36
I'd recommend basing any further work on that branch, as it includes other changes necessary to support these newer HumanWare displays as well.

**Comment by michaelDCurran** [comment] 2018-02-21 07:56
I haven't properly looked into this yet, but I'm not quite sure what you 
mean about bluetooth HID... Current versions of NVDA seem to work fine 
with this device via Bluetooth and I did not need to install any 
drivers. Is it Bluetooth serial by default and I'm just lucky Windows 10 
supports this Bluetooth device? Or is it already Bluetooth HID. I have 
not yet seen any settings on the Device to change what kind of Bluetooth 
it is. I only see a choice of Bluetooth or USB.
I'll start looking at Jamie's branch tomorrow.

**Comment by jcsteh** [comment] 2018-02-21 08:01
Only the Brailliant uses Bluetooth HID and only in OpenBraille mode. Other displays use USB HID and Bluetooth serial.

**Comment by michaelDCurran** [comment] 2018-02-21 08:01
Ah. After resetting the device, Brailliant driver in NVDA no longer 
shows up. There must be settings somewhere on the device then.

**Comment by jcsteh** [comment] 2018-02-21 08:07
I believe the BrailleNote can emulate the Bluetooth name of the Brailliant in order to support older screen readers. However, it's still Bluetooth serial regardless, even in native mode.

**Comment by michaelDCurran** [comment] 2018-02-21 11:04
Now using Jamie's branch Bluetooth is working well. I am guessing that when I received the device it was  still on an older version where the bluetooth name had Brailliant in it. It now just says BrailleNote Touch after I reset / updated the device.
However, as Jamie points out, USB is problematic. The device initializes okay, but all display writes do nothing.  If I comment out ever calling write in display, Braille input still works perfectly, and I can restart NVDA many times and the device initializes and braille input continues to work fine.
If however, I leave the display write in there, not only do the dots not appear, but closing/restarting NVDA seems to block on dev.close (I think), and it also seems to freeze up the BrailleNote Touch, requiring a hard power off. 
I tried splitting the reading and writing into two separate HID instances (writh a little rewriting of hwIo.HID of course) but that did not help at all... exactly the same simptums.
I wonder if there are any other commands  (other than displaying cells) I could write to the device to see if this is an issue with writing, or that specific command?

**Comment by jcsteh** [comment] 2018-02-21 11:07
What happens if you disable reading? My hypothesis is that the device
doesn't like us waiting on a read for some reason while we're also writing.
This doesn't make sense, since reading is actually just retrieving from a
circular buffer that Windows maintains as it receives HID input reports,
but maybe there's some weird interaction I'm not understanding.

**Comment by leonardder** [comment] 2018-02-21 11:32
[**@michaelDCurran**](https://github.com/michaelDCurran) commented on [21 feb. 2018 12:04 CET](https://github.com/nvaccess/nvda/issues/6524#issuecomment-367291594 "2018-02-21T11:04:15Z - Replied by Github Reply Comments"):
> I tried splitting the reading and writing into two separate HID instances (writh a little rewriting of hwIo.HID of course) but that did not help at all... exactly the same simptums.

May be instead of using two hwIo.Hid instances, you need to use different endpoints for I/O. I belief I pointed that out as an idea to @jcsteh before he left. See the Hims driver as an example, however that uses Bulk instead of HID.

**Closed** 2018-03-13 21:28 UTC
Labels: p3
