### ISSUE TITLE
Microsoft Excel: Repeat command not working if enabled "Report table row/column headers"

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#5695] opened 2016-01-21 12:43 UTC
Microsoft Excel has function to repeat previously used command.
The keyboard shortcut is F4 key.

The F4 key is not working if NVDA is working and "Report table row/column headers" option of format setting is turned on.

Setup:
- NVDA 2015.4 (portable) with no add-ons
- Windows 8.1 (32bit) English language installed and selected as primary language
- Office 2013 with English language pack

Step to reproduce:
- open new worksheet in Excel and type "123" to A1 and A2 respectively
- move to A1 using arrow keys
- press Ctrl+B to make it bold. nothing reported for this action, however, it can be verified by NVDA+F.
- move to A2 using down arrow key
- press F4

Expected:
- cell A2 is changed to bold font.

Actual result:
- if NVDA is running and "Report table row/column headers" is enabled, A2 is not changed to bold. instead of this, selected region is expanded to A1..A2.

**Comment by jcsteh** [comment] 2016-01-21 22:14
Any idea, @MichaelDCurran?

**Comment by michaelDCurran** [comment] 2016-01-22 00:58
I cannot reproduce this. However, logically I'm guessing that because we call a property such as currentRegion when supporting row and column headers, Excel treats this as a command.
You say Office 2013 with English language pack. Does this mean that technically your MS Office install is actually a Japanese version? If so it may be specific to that version.
I wonder if anyone else can reproduce this.

**Comment by surfer0627** [comment] 2016-01-22 06:12
This case also occurred in Excel2010 (Chinese traditional).
The F4 key is not working if NVDA "Report table row/column headers" option of format setting is turned on.

**Comment by ruifontes** [comment] 2016-01-22 16:35
Here, with Windows 10, Excel 2013 and last NVDA Next, it is working.

Rui


-----Mensagem Original----- 
De: surfer0627
Data: sexta-feira, 22 de janeiro de 2016 06:12
Para: nvaccess/nvda
Assunto: Re: [nvda] Microsoft Excel: Repeat command not working if enabled 
"Report table row/column headers" (#5695)



This case also occurred in Excel2010 (Chinese traditional).
The F4 key is not working if NVDA "Report table row/column headers" option 
of format setting is turned on.

-

**Comment by derekriemer** [comment] 2016-01-22 16:43
With a US english version of Excel this works as expected.

On 1/22/2016 9:35 AM, ruifontes wrote:
> Here, with Windows 10, Excel 2013 and last NVDA Next, it is working.
>
> Rui
>
>
> -----Mensagem Original-----
> De: surfer0627
> Data: sexta-feira, 22 de janeiro de 2016 06:12
> Para: nvaccess/nvda
> Assunto: Re: [nvda] Microsoft Excel: Repeat command not working if 
> enabled
> "Report table row/column headers" (#5695)
>
>
>
> This case also occurred in Excel2010 (Chinese traditional).
> The F4 key is not working if NVDA "Report table row/column headers" 
> option
> of format setting is turned on.
>
> -
> Reply to this email directly or view it on GitHub.
>
>
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5695#issuecomment-173970783>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by michaelDCurran** [comment] 2016-01-24 23:12
@nishimotz or @surfer0627: does this happen with NVDA current next snapshots? There is a fix for #5396 in Next which may indirectly fix this issue, though I am not sure.

**Comment by surfer0627** [comment] 2016-01-25 01:47
@michaelDCurran: 
In the test, this issue has been fixed in [next-13184,6199741](http://www.nvaccess.org/files/nvda/snapshots/).

**Comment by jcsteh** [comment] 2016-01-27 23:27
This depends on #5396.

**Comment by surfer0627** [comment] 2016-06-17 08:32
Yes, as Jamie removed this from the 2016.2, because this issue occurs again in next-13286 (Mon Apr 11) and later.

**Comment by ehollig** [comment] 2017-10-01 23:07
Is this related to #7044? CC @Qchristensen

**Comment by Qchristensen** [comment] 2017-10-02 03:48
I'm using Office version 1708, build 8431.2079.  Downloaded from Microsoft in Australia and using the Australian dictionary.

I can reproduce the original issue - with NVDA running AND table row / column headers being reported, pressing F4 does not repeat the last action.

What F4 does in this situation, seems to be the same as control+shift+* - that is, it selects the current region - the block of cells surrounded by blank cells.  Pressing F4 multiple does flashes the cursor "waiting" for a moment, keeps the same cells selected and does nothing more.

If I uncheck row / column headers in NVDA's document formatting options, pressing F4 repeats the last action.

Although the same key, this is different to #7044.  When you are editing a cell and have a cell reference selected, pressing F4 cycles through all combinations of absolute and relative references.  That works fine, it's just that the change isn't announced.  So, in fact, there is a shared issue between the two, but it's just that when the cell contents is changed, NVDA isn't reporting it, but that's a different issue to F4 not working as expected which is what this issue is.

**Comment by Adriani90** [comment] 2019-02-18 22:22
@nishimotz, @qchristensen are you still able to reproduce it with last NVDA alpha?

**Comment by nishimotz** [comment] 2019-02-19 07:22
Reproduced original issue with the setup as follows

* NVDA 2018.4.1
* Office 365 Excel (Version 1901) + English experience
* Windows 10 (64bit) Version 1809 + English experience

**Comment by nishimotz** [comment] 2019-02-19 07:37
Confirmed that latest alpha resolves the issue:

* NVDA alpha-16789,73db4aa5
* Office 365 Excel (Version 1901) + English experience
* Windows 10 (64bit) Version 1809 + English experience

procedure:

* same as the beginning of this issue

result:

* cell A2 is changed to the bold font as expected

**Comment by Adriani90** [comment] 2019-02-19 19:18
cc: @michaelDCurran I guess your MS Excel speedup PR solved this issue. If you can confirm, then I suggest closing this issue as works for me now. cc: @Qchristensen

**Comment by Qchristensen** [comment] 2019-02-19 23:58
I can confirm this now works as expected for me in Office 365 Version 16.0.11231.20164 with NVDA alpha-16793,31692c6c.

**Comment by Adriani90** [comment] 2019-02-23 21:52
Closing as works for me.

**Closed by Adriani90** 2019-02-23 21:52 UTC
Labels: Microsoft Office support, worksforme
