### ISSUE TITLE
Continuous reading suspends pc on windows 11 using kindle

### ISSUE THREAD

**Issue by ericdq** [nvaccess/nvda#13809] opened 2022-06-17 10:41 UTC
When I am reading in Windows 11 with continuous reading on Kindle desktop, when the time configured in the system is reached, the pc is suspended.
I don't know if the same thing happens in other applications.

**Comment by seanbudd** [comment] 2022-06-30 06:47
Welcome @ericdq ,

We are unable to process this issue as it stands.
Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment] 2024-05-16 18:39
Closing since the template is not filled. Please fill the template with all details of this issue, reproduce it with NVDA 2024.1 and Kindle 2.3.5.

**Closed by Adriani90** 2024-05-16 18:39 UTC
Labels: needs-triage
