### ISSUE TITLE
Scons devDocs Does Not Generate Documentation

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#6751] opened 2017-01-18 06:52 UTC
When I type scons devDocs after executing scons source, I get an empty output directory. I've attached the scons output here.

[scons_output.txt](https://github.com/nvaccess/nvda/files/713175/scons_output.txt)

**Comment by bhavyashah** [comment] 2017-08-25 07:22
Possibly related to #5373

**Comment by leonardder** [comment] 2018-02-17 12:06
@munawarb: can you still reproduce this?

**Comment by munawarb** [comment] 2018-02-18 02:52
@leonardder Sorry, since then I've switched systems and don't have the tools to build NVDA on here. I can fetch them again if you'd like me to test it, just to close out this issue, but that'll have to be in a month or two from now since I'm traveling for business at the moment and am short on free time. So, I'll follow up with you as soon as I can.

**Comment by leonardder** [comment] 2018-02-21 20:15
I will test this on my corporate system later this week.

**Comment by ehollig** [comment] 2018-10-26 00:33
@leonardder can you provide any updates?

**Comment by Adriani90** [comment] 2019-03-30 19:43
@leonardder is this still an issue?

**Comment by feerrenrut** [comment] 2020-05-02 16:46
devDocs builds for me. I can't see any error in the log file. I assume that it was being skipped, perhaps scons decided it was already built. Since there hasn't been updates in a long time I'll close this issue.

**Closed by feerrenrut** 2020-05-02 16:46 UTC
Labels: component/documentation
