### ISSUE TITLE
NVDA 2019.1.1 crashes after searching with NVDA+Ctrl+F

### ISSUE THREAD

**Issue by FrankEliott** [nvaccess/nvda#10092] opened 2019-08-14 11:01 UTC
### Steps to reproduce:
Press NVDA+Ctrl+F to open the find dialog. Enter any expression and search the website for it. The function works fine for the first time. Then press NVDA+Ctrl+F again and NVDA crashes. NVDA stops talking and also doesn't accept any keystroke. 

### Actual behavior:
NVDA crashes

### Expected behavior:
NVDA doesn't crash and opens the search dialog that the user can search again.

#### NVDA installed/portable/running from source:
NVDA 2019.1.1. installed locally.

#### NVDA version:
NVDA 2019.1.1

#### Windows version:
Windows 10 Professional (1903)

#### Does the issue still occur after restarting your PC?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
 I also tried 2019.2.rc2 (no installation).

**Comment by Brian1Gaff** [comment] 2019-08-14 11:59
Nvda plus control plus does nothing in Firefox or waterfox for me. Should 
it?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by DrSooom** [comment] 2019-08-14 12:38
@FrankEliott: Please list all web browser incl. versions, where this issue occurs. Furthermore please upload the file "nvda_old.log" from "C:\Users\[Username]\AppData\Local\Temp\ after such a crash. And finally please tell us the behavior with NVDA 2019.2 RC2 Portable (incl. used web browsers). Thanks.

**Comment by Adriani90** [comment] 2019-08-14 12:50
cc: @josephsl, @feerrenrut

**Comment by FrankEliott** [comment] 2019-08-14 18:02
> Nvda plus control plus does nothing in Firefox or waterfox for me. Should it? Brian bglists@blueyonder.co.uk Sent via blueyonder. Please address personal E-mail to:- briang1@blueyonder.co.uk, putting 'Brian Gaff' in the display name field. Newsgroup monitored: alt.comp.blind-users ----- Original Message ----- From: "FrankEliott" <notifications@github.com> To: "nvaccess/nvda" <nvda@noreply.github.com> Cc: "Subscribed" <subscribed@noreply.github.com> Sent: Wednesday, August 14, 2019 12:01 PM Subject: [nvaccess/nvda] NVDA 2019.1.1 crashes after searching with NVDA+Ctrl+F (#10092)
> […](#)
> ### Steps to reproduce: Press NVDA+Ctrl+F to open the find dialog. Enter any expression and search the website for it. The function works fine for the first time. Then press NVDA+Ctrl+F again and NVDA crashes. NVDA stops talking and also doesn't accept any keystroke. ### Actual behavior: NVDA crashes ### Expected behavior: NVDA doesn't crash and opens the search dialog that the user can search again. ### System configuration #### NVDA installed/portable/running from source: NVDA 2019.1.1. installed locally. #### NVDA version: NVDA 2019.1.1 #### Windows version: Windows 10 Professional (1903) #### Name and version of other software in use when reproducing the issue: #### Other information about your system: ### Other questions #### Does the issue still occur after restarting your PC? yes #### Have you tried any other versions of NVDA? If so, please report their behaviors. I also tried 2019.2.rc2 (no installation). -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #10092

NVDA Control F all together.

**Comment by FrankEliott** [comment] 2019-08-14 18:18
> cc: @josephsl, @feerrenrut

Yandex 19.7.2.422
Edge Microsoft Edge 44.18362.267.0

I tried 2019.2.rc2 with the same behavior

[nvda.log](https://github.com/nvaccess/nvda/files/3502695/nvda.log)

**Comment by josephsl** [comment] 2019-08-14 18:35
Hi, I’m thinking NVDA wants to locate a specific object when it goes around in circles trying to do that, as tracebacks point to GetClassName wrapper in winUser. Is this the case with all websites or with a specific content? Thanks.

**Comment by Brian1Gaff** [comment] 2019-08-14 19:41
Yes exactly, nothing happens.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by zahra21** [comment] 2020-03-04 09:10
Does it occur only in 2019 versions of nvda?
i cant reproduce in 2017 versions of nvda except 2017.4 which does not support windows xp!

**Comment by FrankEliott** [comment] 2020-03-04 10:23
Hello Zahara,

I’m sorry but currently I’m using a Mac.
Kind regards

Frank Becker
frank@beckerwelt.de

**Comment by feerrenrut** [comment] 2020-03-09 17:23
Can anybody reproduce this issue? I'm going to close it for now considering both NVDA and Edge have changed significantly since this was reported. Please comment to re-open.

**Closed by feerrenrut** 2020-03-09 17:23 UTC
