### ISSUE TITLE
In an Excel workbook, if multiple cells are selected, NVDA does not correctly report the currently focused with TAB/Shift+TAB cell

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10540] opened 2019-11-25 09:22 UTC
In an Excel workbook, the user can select multiple cells and move the focus between the selected cells with TAB and Shift+TAB. In such scenario, Narrator correctly reports the currently focused cell from the selected cells, when pressing TAB or Shift+TAB. NVDA however does not - NVDA each time the focus changes reports the whole selection (range of selected cells).

### Steps to reproduce:
1. Launch NVDA.
2. Open a workbook in Excel. The workbook has to have at least a few adjacent cells filled with some data.
3. Select a few filled adjacent cells with Shift+Arrow keys.
4. Use TAB and Shift+TAB to move the system focus between the selected cells.
5. Observe what NVDA reports after each focus change.

### Actual behavior:
NVDA reports the range of selected cells, as if the "report selection" command was executed.

### Expected behavior:
NVDA should report the focused cell and its content, like it does when moving between cells with arrow keys when there are no selected cells. Narrator behaves like this (as expected), so it is technically possible and the observed bug is probably not due to Excel itself.

### System configuration
Test environment:
- Operating system: Windows 10 Pro version 1909 (build 18363.476), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19266,67bf1df6, in bulgarian.
- Microsoft Excel version: Microsoft Excel for Office 365, 32-bit, MSO (16.0.12130.20232), click to launch, in bulgarian (information taken from the "About Excel" dialog).
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes - v2019.2.1 - the behavior is the same.

**Comment by CyrilleB79** [comment] 2020-04-18 22:00
Could it be a duplicate of #6959?

Note that in an Excel cell selection, you can move the focus the following way:
* Enter/Shift+Enter moves the focus in column and go to the next/previous column when the column end is reached.
* Tab/Shift+Tab moves the focus in line and go to the next/previous line when the line end is reached.

**Comment by Qchristensen** [comment] 2020-05-22 07:27
I'm going to close this as a duplicate of #6959 - the issue is definitely still valid and still reproducible, just easier to keep all conversation in one place.

**Closed by Qchristensen** 2020-05-22 07:27 UTC
