### ISSUE TITLE
Unigram UWP jumps to the last message when pressing the down arrow

### ISSUE THREAD

**Issue by SpanishCrusader** [nvaccess/nvda#13873] opened 2022-07-06 16:19 UTC
Hello guys.
I'm having a very wird problem with NVDA and Unigram.

When I open a chat, and try to navigate through the messages using the up & down arrow, every time I presss the down arrow instead of moving to the below message NVDA jumps directly to the last one.

An example could be something like this:

Message 1: Hello.
Message 2: Hello there.
Message 3: I'm eating blue strawberries.
Message 4: I don't like those.

Now let's say that the current possition is at the message 2, ("Hello there"). If I press the down arrow to hear the next message I'd expect to hear "I'm eating blue strawberries", but I'm not sure why it always jumps to the last message so I ended up hearing "I don't like those" instead.
It only happens when I'm moving from the above messages to the ones below.

### Steps to reproduce:
1 - Open Unigram
2 - Select the Chats" tab.
3 - Open any chat that contains a bounch of messages.
4 - Navigate to the top message by pressing the up arrow, then press the down arrow to navigate to the below message.

### Actual behavior:
Instead of moving to the next message, NVDA moves to the last one in the conversation.

### Expected behavior:
NVDA should move to the next message and not to the last one.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.1

#### Windows version:
Windows 10 21H2

#### Name and version of other software in use when reproducing the issue:
Unigram Telegram for Windows

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not at the moment.

#### If NVDA add-ons are disabled, is your problem still occurring?
No addons installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
The tool it's already installed

**Comment by seanbudd** [comment] 2022-07-07 01:38
Welcome @SpanishCrusader,

- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- This is very likely a problem with the implementation of the application/website, as a starting point please submit feedback to the authors to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by amirmahdifard** [comment] 2022-07-07 16:57
hello, you can close this one, because this problem is completely in last direct unigram. has been fixed, microsoft stor users stil have to wait sometimes.

**Comment by amirmahdifard** [comment] 2022-07-07 17:01
and from now on, please dont report other apps problem to nvda, because the app developer should fix they bugs, not nvda, its fixed anyway.

**Closed** 2022-07-08 03:43 UTC
Labels: blocked/needs-external-fix, p3, triaged

**Comment by SpanishCrusader** [comment] 2022-07-20 14:52
Happy to know that the issue is already fixed. I hope the update for unigram is released soon.
For the time being, if someone else is having this problem like me, I found that if you hold down the CTRL key while navigating through the messages using the up/ down arrow it will move like normal.
