### ISSUE TITLE
Focus mode skips over link after following button

### ISSUE THREAD

**Issue by GeraldJ4** [nvaccess/nvda#12937] opened 2021-10-14 20:41 UTC
### Steps to reproduce:
When using down arrow in focus mode, focus skips over link, and stays on input when an input comes before it.
Notice when using the  up arrow, Change Activity Display name button gains focus.  
![inputqquestion](https://user-images.githubusercontent.com/92549700/137391892-059f3000-bbf0-4ccd-9feb-e9ab72336ce8.gif)
html setup:
`<input type='text' /> <a> A link </a> <span> Example </span>`

Code pen example: https://codepen.io/seanbudd/pen/MWvaLgx, https://cdpn.io/seanbudd/fullpage/MWvaLgx

### Actual behavior:
Link doesn't gain focus when navigating using down arrow, and an input comes before it.
### Expected behavior:
Link should gain focus. 
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

**Comment by seanbudd** [comment] 2021-10-15 03:05
Could you confirm the browser and browser version you are using?

**Comment by seanbudd** [comment] 2021-10-15 05:35
I've added a codepen sample. I can't reproduce this issue by:

1. tabbing into the input field, then pressing the down arrow
2. clicking into the input field, then pressing the down arrow

I tried using `Chrome 94.0.4606.81 (Official Build) (64-bit)` and `Firefox 93.0 (64-bit)`

**Comment by feerrenrut** [comment] 2021-10-15 08:34
It would be good to get to the bottom of this, however the impact isn't high enough (and unlikely to be a regression) to block 2021.3

**Comment by feerrenrut** [comment] 2022-02-28 05:11
With the updated code pen link, this may be reproducible. However the initial description is not clear, @GeraldJ4 can you please confirm?

Copying from the speechviewer with:
- NVDA settings, browse mode, "Audio indication of focus and browse modes  check box  checked".  So "focus mode" / "browse mode" shows in the speechviewer.
- `NVDA+4` used to turn "speak command keys on"

```
edit  blank
Focus mode
NVDA+space
Browse mode
down arrow
link    first link
down arrow
first example
tab
second link  link  
```

Steps:
- Focus the text input, NVDA will automatically swap to focus mode with a "click" sound.
- Press `NVDA+space` to swap to browse mode
- press down arrow twice
- press tab

Actual:
Speech: `second link  link`

Expected:
What? I believe this is the expected behavior.

**Comment by Adriani90** [comment] 2024-11-25 23:01
This is not reproducible with NVDA 2024.4.1, Firefox 132 or Chromium canary 133. Closing as works for me. If you are still having this issue, please provide a minimal test case and we can reopen.

**Closed by Adriani90** 2024-11-25 23:01 UTC
Labels: close/worksforme, app/chrome, feature/focus-mode, needs-triage
