### ISSUE TITLE
Search history of NVDA find dialog does not handle Escape correctly when using Japanese IME

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#9954] opened 2019-07-19 23:31 UTC
### Steps to reproduce:

1. start NVDA and Internet Explorer
2. make sure NVDA is in browse mode
3. press NVDA+Ctrl+F and open search dialog of NVDA
4. enable Japanese IME. editing of reading string starts.
5. type Latin characters, such as: t e s u t o
6. press Escape key, instead of IME translation key

### Actual behavior:

Search dialog closes.

### Expected behavior:

The reading string of IME is cleared.
Search dialog should not close.

#### NVDA installed/portable/running from source:

installer

#### NVDA version:

nvda_snapshot_beta-18133,b29acb42

#### Windows version:

Windows 10 version 1903 (Japanese)

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.1.1 works as expected.

We believe it is related to #8482

**Comment by josephsl** [comment] 2019-07-19 23:37
CC @marlon-sousa

This isn't limited to Japanese - it also shows up when I try to type Korean text and attempt to close it - find dialog closes, whereas it should close composition window.

Thanks.

**Comment by josephsl** [comment] 2019-07-20 01:23
Hi,

Threshold nor wxPython 4.1.0 will resolve this problem unless we hack wxWidgets/wxPython. One possible solution might be wx.ComboCTRL, but it is a bit risky at this point unless we're aiming for 2019.3.

Thanks.

**Comment by josephsl** [comment] 2019-07-20 01:53
Hi,

According to:
https://trac.wxwidgets.org/ticket/11386

This is caused by the escape key being eaten by wxPython. In this case, we need to edit onCancel event in cursor manager's find dialog to not destroy the window if IME (input method editor) is on. Because of the fact that it affects languages with IME, this is a major regression (chiefly Chinese, Japanese, Korean, possibly more).

I can think of three ways to resolve this, depending on severity of this problem and how long it takes to edit and test a potential fix:

1. If it can be done this weekend or sometime next week: fix it as part of 2019.2 release candidate 1.
2. If it requires more testing: prepare 2019.2.1.
3. If this will impact more languages besides CJK: revert search history, reintroduce it in 2019.3 with Python 3 changes and fixes added.

I personally vote for option 2. Although someone can come up with a fix in the next few days, it must be tested to make sure it won't introduce more problems. Option 3 is a bit risky at the moment because my own fix for find dialog issue may or may not revert cleanly and we need to make sure the improved find dialog is Python 3 compliant (and test to see if it can be subjected to GUI helper enhancements).

Thanks.

**Comment by marlon-sousa** [comment] 2019-07-20 05:20
L.Hello,
Can you confirm that this bug is found only in this version? I did not change anything related to key handling at all. If the behaviour is already found, we can take care of it latter.

Obrigado,
Marlon

Em 19 de jul de 2019, à(s) 20:37, Joseph Lee <notifications@github.com> escreveu:

**Comment by josephsl** [comment] 2019-07-20 05:25
Hi, yes, this is a regression in 2019.2, caused by wxWidgets/wxPython/combo boxes. Thanks.

**Comment by marlon-sousa** [comment] 2019-07-20 05:25
Hi, I am currently ouut of the city, with no access to computer. I won.t be able to work on this issue during the weekend. Sorry it hasn.t been found before. The strategy of checking in the cancel event seens good.

Obrigado,
Marlon

Em 19 de jul de 2019, à(s) 22:53, Joseph Lee <notifications@github.com> escreveu:

**Comment by marlon-sousa** [comment] 2019-07-24 13:26
Joseph,


Strangely the issue you pointed out seems to have been fixed and closed 
long time ago.


Unless wx python is using a really really old version of wxwidgets this 
shouldn't be happening.


I have no ime support here, I am trying to activate it at the moment. 
Once I can do it and reproduce the problem I will try to develop a fix.


I however suspect that edit and other typing fields in other dialogs 
closeable with scape key are likely to be affected, if the bug related 
on that issue on wx widgets has been reintroduced.


Thanks,

Marlon

**Comment by nishimotz** [comment] 2019-07-26 00:15
Is it possible to revert search history for 2019.2?

**Comment by marlon-sousa** [comment] 2019-07-26 00:57
It should be. As things stand, I’m not sure it is possible to have a quick fix for that, as the problem is not on NVDA side. I am still learning how to use ime and my fixes will either enable or disable the escape key depending on if ine is or is not active but the true fix should only consider the escape key if no suggestions are currently been shown. I still don’t know how to perform this and have no expectations to discover it on Time for this release. I am extremely sorry it just hasn’t been found before, delaying these important enhancement even more.

Obrigado,
Marlon

Em 25 de jul de 2019, à(s) 21:15, Takuya Nishimoto <notifications@github.com> escreveu:

**Comment by nishimotz** [comment] 2019-07-29 15:22
It seems that 2019.2 rc1 does not address this issue.

**Comment by josephsl** [comment] 2019-07-29 15:24
Hi, yes, no changes at the moment. I’m thinking a call to wxWidgets and/or wxPython people are in order. Thanks.

**Comment by nishimotz** [comment] 2019-07-30 00:41
I vote for reverting search history, reintroduce it in 2019.3.
ping @leonardder @feerrenrut @Qchristensen

**Comment by josephsl** [comment] 2019-07-30 00:44
Hi, I concur – I’ll introduce an emergency PR that reverts this. Also, before we can have search history back, I think it would be best to have representatives of language communities affected by this regression contact wxWidgets and wxPython developers to seek a solution. I will also test wxPython 4.1.0 to see if it is something to do with older wxWidgets releases. Thanks.

**Comment by feerrenrut** [comment] 2019-07-30 14:50
Unfortunately, I have only just become aware of this issue. It is the end of the day for me now, but I will consider our options and make a decision about the the best way forward tomorrow. I would prefer to avoid having another translation freeze if possible.

**Comment by nishimotz** [comment] 2019-08-02 00:27
I support the decision. Thank you.

**Comment by Adriani90** [comment] 2019-09-08 19:50
@nishimotz after the reverting of the search history PR, is this issue still occuring? Or is this invalid now?

**Comment by josephsl** [comment] 2019-09-08 19:55
Hi, I’m not @Nishimotz, but it is no longer happening. However, I advise leaving this open as a reminder for everyone. Thanks.

**Comment by Adriani90** [comment] 2019-09-08 19:58
I have reopened #8482. I think it is a better idea to discuss this one in course of implementing #8482. I am closing this for now. Thanks.

**Closed by Adriani90** 2019-09-08 19:58 UTC
Labels: invalid, p1, regression
