### ISSUE TITLE
nvda jumping the text box to enter the text to translate in google translator

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8992] opened 2018-11-29 17:04 UTC
### Steps to reproduce:
enter google translate
https://translate.google.com.br/
In nvda the autofocus mode is disabled.
press and to go to the edit box.
Press an up arrow.
Now press the down arrow.
### Actual behavior:
the focus goes to the button
Enable Virtual Keyboard
### Expected behavior:
the focus should return to the text box.
#### NVDA Installed/portable/running from source:
install
#### NVDA version:
alfa 16321
#### Windows version:
10 17763.134
#### Name and version of other software in use when reproducing the issue:
chrome 70
#### Other information about your system:
I do not understand anything programming, but it seems to me that it is google who is determining which object gets focus after moving with the keyboard, depending on which object is currently in focus.
Another issue I noticed:
While in the text box to insert text to be translated, press the up arrow and you will be in the translate button.
If I press home I hope I would be at the beginning of the word translate.
What happens is that nvda announces clear text and the keyboard will be in the letter c to clear text 
I do not know if nvda can do anything here, plus a consistency on these pages that manipulate the focus of the keyboard depending on where the focus is would be very important for beginner users.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment] 2018-11-30 17:51
I was able to reproduce your described STR with NVDA 2018.1 and Firefox 56.0.2 on win7x64. Furthermore I also noticed the NVDA says (TTS) and shows (Braille) different things around this multi-line text field when moving up and down using the arrow keys in browse/focus mode. The behaviour here is strange – and confusing if you don't have a braille display.

As Google redesigned its Translator a little bit a few days ago, I guess that the issue is on Google's side. I recently sent a link to this issue here via the feedback link which is available on the Translator website.

Note that the multi-line text field has auto focus on loading the page. So you don't have to move to the text field by pressing E (in browse mode) manually. Of course, this doesn't solve the problem. I just wanted to mention it.

**Comment by Adriani90** [comment] 2018-12-07 13:12
@DrSooom,  @fernando-jose-silva can you still reproduce this with NVDA 2018.4 Beta 4? I have noticed that NVDA became more stable in web Browsers in last beta Versions.

**Comment by fernando-jose-silva** [comment] 2018-12-07 16:07
Many thanks @Adriani90 Adriani90 unfortunately still encountered the same problem when testing the beta.

**Comment by Adriani90** [comment] 2018-12-07 21:48
ok I can reproduce it either. I found out that this is caused by incorect parameter in NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole. Now there must be a way to see the parameters assigned and how to adjust it.

**Comment by Adriani90** [comment] 2019-12-20 22:29
This is not reproducible anymore in NVDA 2019.3 Beta 1 and Chrome 79. Closing as works for me.

**Closed by Adriani90** 2019-12-20 22:29 UTC
Labels: worksforme

**Comment by DrSooom** [comment] 2019-12-20 23:40
Also no longer reproducible with NVDA 2019.2.1 and Firefox 71.0 on Win7x64.
