### ISSUE TITLE
Play silence to keep audio device awake

### ISSUE THREAD

**Issue by haruncetinkaya306** [nvaccess/nvda#16148] opened 2024-02-08 12:56 UTC
### Is your feature request related to an issue? Please define.
It will be difficult for those who want to change the silence duration (default = 30 seconds) setting in the advanced settings panel that comes with the play silence feature to keep the audio device awake.
### Describe your desired solution
Moving it to the sound panel in the settings would be better for users who want to change this setting.
### Describe the alternatives you considered
No.
### Additional context

**Comment by CyrilleB79** [comment] 2024-02-08 21:00
I was one of those who asked this feature to be in the advanced settings panel while discussing #16099. In the beginning, there were two options and they were called "play silence" and "volume of white noise". This seemed quite technical parameters to me for normal users.

At the end, the "white noise volume" parameter was removed from the GUI. And the "play silence duration" parameter was renamed "keep audio awake duration", with a better description in the User Guide. IMO this lead to a much more understandable UX in the GUI for normal users.

Given this UX improvement in the GUI and the fact that this parameter may have a significant effect on the audio device battery charge, I am now rather in favor of moving the parameter to the audio panel.

I may implement it in #16147. I'd just wait for NV Access green light, since they had reviewed and validated #16099 with the parameter in the advanced settings panel.

@seanbudd, what is your opinion on this?

**Comment by OzancanKaratas** [comment] 2024-02-08 21:38
I vote for the keep device open setting to be in the Audio panel and the white noise parameter to be in the Advanced panel. So, I think we should not hide the white noise setting, at least for now.

**Comment by CyrilleB79** [comment] 2024-02-08 22:37
Folowwing https://github.com/nvaccess/nvda/pull/16099#issuecomment-1915714479, and more generally the whole discussion in this PR, it has been decided to remove the white noise volume from the GUI since it may only be used for debug purpose.

If you have other use cases or disagree with this decision, please provide examples.

Though, @cary-rowen has written in https://github.com/nvaccess/nvda/pull/16099#issuecomment-1918233640:
> If the white noise volume is only used for development and debugging, it should be recorded in an appropriate doc. Otherwise, even developers will not know how to use it because it is too hidden.

I fully support the documentation of hidden config parameters.
If your concern is that this parameter is too hidden, this may be an alternative solution to a full GUI control.

**Comment by seanbudd** [comment] 2024-02-08 23:04
I agree this can be moved to the audio settings panel.

I have just thought up a potential use case that may warrant adding white noise to advanced settings:

1. As a user I wish to configure the "Silence" duration for my ideal period of time
2. to gauge how long feels appropriate based on my working patterns, I must know when the "silence" duration ends.

Doing this without white noise is tedious:
   - if its too short, I can figure out because speech is clipped.
   - to get the right length, I can increase it just past where speech is regularly clipped.

So to get this right you'd have to start small and incrementally increase the value.
You can't really "binary" search, as there's no easy way to gauge if it's too long.
With white noise, you can easily tell if the duration is too long or too small.

**Comment by cary-rowen** [comment] 2024-02-09 00:37
> With white noise, you can easily tell if the duration is too long or too small.

I totally agree with the use case @seanbudd said.

**Comment by Brian1Gaff** [comment] 2024-02-09 09:37
Its not particularly dangerous so it should be in the audio settings. That is my view, as I say, I've not any need of it on my current machine.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: haruncetinkaya306 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Thursday, February 08, 2024 12:57 PM
  Subject: [nvaccess/nvda] Play silence to keep audio device awake (Issue #16148)



  Is your feature request related to an issue? Please define.
  It will be difficult for those who want to change the silence duration (default = 30 seconds) setting in the advanced settings panel that comes with the play silence feature to keep the audio device awake.

  Describe your desired solution
  Moving it to the sound panel in the settings would be better for users who want to change this setting.

  Describe the alternatives you considered
  No.

  Additional context

**Comment by CyrilleB79** [comment] 2024-02-09 09:58
> > With white noise, you can easily tell if the duration is too long or too small.
> 
> I totally agree with the use case @seanbudd said.

On the opposite, I find this use case is not very relevant.

On one side, I understand the need for a user to define a trade-off between avoiding glitches and saving the device's battery. If there is a control to help the user to determine it, it should not be reserved only for advanced users or developers. Thus it should be in audio settings.
Though, the trade off may not need to be very precise. If the user can hear glitches with 3 minutes of silence, he may increase the duration to 5 minutes. If instead the optimal value was 4 minutes instead, the effect on the battery will not be so significant. In any case, even without white noise, the user will be able to know that 30 minutes will be too much for him.

I am also concerned by the fact that defining an option called "White noise volume" is not explicit enough in advanced settings, and not explicit at all in audio settings.
And also, we should ensure that people do not use change this option inadvertently and then complain of NVDA's bad audio quality. There is probably no sense to save this in the config after restart.

Maybe we can release NVDA 2024.2 as is to see if people have difficulties with setting the "Keep audio awake duration " option. If people experiment issue with it, we can think to introduce the white noise option in a subsequent release.

Anyway, the current issue is to move the existing "Keep audio awake" option to audio settings. For clarity, I'd recommend to open a new issue to discuss the opportunity to introduce "White noise volume" option in the GUI, where and with which name (label).

**Comment by Adriani90** [comment] 2024-02-09 13:28
I think if this setting already solves the audio problems people had before, there is no need to introduce the white noise setting to the gui. I am with @CyrilleB79 on releasing the next NVDA version with the improvmenets he just proposed and request users on older issues such as #8017 and #15483, to reproduce the issues afterwards.

**Closed** 2024-02-21 23:12 UTC
Labels: p4, triaged
