### ISSUE TITLE
role="status" live region not announced when injected into DOM

### ISSUE THREAD

**Issue by joe-watkins** [nvaccess/nvda#14591] opened 2023-01-27 14:42 UTC
Hello :) 

When injecting live region with `role="status"` into the DOM with JavaScript, the live region is not announced, but it is announced when `role="alert"` is used. Is this by design? Same experience in JAWS/Chrome.

VoiceOver/Safari on iOS and macOS do successfully announce all live regions: `role="status"`, `role="alert"`, and even `aria-live="polite" when injected into the DOM, as expected. 

**Use Case:** Author wants to present a Toast-style notification to the user so they inject a container into the DOM with `role="status"` because they feel that role would be more appropriate for that content than `role="alert"` - they also feel this would be a better screen reader experience. At this time, most Toast Notification plugins are using `role="alert"` because it works (announced by popular screen readers), but I'm not certain that is ideal in all cases and I am hoping that `role="status"` (as well as `aria-live="polite"`) could behave the same to give authors choice. 

**Workaround:** Must have `role="status"` present in the DOM at page load and update its contents **OR** use JavaScript `document.createElement()` to create a Live Region and stagger presentation with `setTimeout();` to inject the live region, which is not ideal.

### Steps to reproduce:
1. Start NVDA
2. Open Firefox or Chrome
3. Visit this URL: https://cj53kj.csb.app/
4. Activate the first button with the label "Toggle role="status" Notification" and listen for an announcement of the live region.
5. Activate the next button with the label "Toggle role="alert" Notification" and listen for an announcement of the live region.

### Actual behavior:
1. NVDA does **not** announce live region with `role="status"` that is introduced to the page.
2. NVDA does successfully announce the live region with `role="alert"` that is introduced to the page.

**Note**: Both Firefox and Chrome expose the live region in the Accessibility Tree once it is introduced into the DOM. At least it can be found in the accessibility inspectors for each browser.

![Screenshot of Chrome DevTools Accessibility inspector highlighting the exposed live region, HTML code of live region highlighted as well as the content in the viewport.  ](https://user-images.githubusercontent.com/3695795/215117087-a50dc429-1476-44e7-9727-d295b1d23789.png)

### Expected behavior:
1. NVDA would announce all Live Regions that are added to the DOM.

#### NVDA installed/portable/running from source:
NVDA installed

**Comment by michaelDCurran** [comment] 2023-01-30 01:21
My reading of the ARIA spec and aria-live on MDN only suggests that ATs should speak updates. They make no suggestion that an AT should read initial value. As role=status is implicitly a node with aria-live=polite, then the same rule applies.
If you strongly disagree with this, then I would like to see evidence in the ARIA spec that suggests we handle it otherwise. Or, if this is in deed problematic for any author to implement, then consider discussing with the ARIA workinggroup to have the spec amended.

**Comment by joe-watkins** [comment] 2023-01-30 18:26
@michaelDCurran May I ask why NVDA does announce `role="alert"`, which is another instance of a node with implicit `aria-live`, but only its value `assertive` is different from `polite` when compared to `role="status"`? Where in the ARIA spec does it suggest AT should make an exception `role="alert"` and announce that live region when it's not an update either?

Folks within the ARIA WG are pretty quick to say it's not their job to tell AT what to do with how/when you announce things. They'd point me to here or browser manufacturers. Browsers appear to be doing their part by exposing things in the accessibility tree.

**Comment by polent** [comment] 2023-06-19 11:20
Interesting to add, that other assistive systems like voice over behave like the expected behavior.

**Comment by jinyoungca** [comment] 2023-09-07 21:46
> My reading of the ARIA spec and aria-live on MDN only suggests that ATs should speak updates. They make no suggestion that an AT should read initial value. As role=status is implicitly a node with aria-live=polite, then the same rule applies.

@michaelDCurran alongside what @joe-watkins mentioned, "injecting a container into the DOM" feels very much like an implementation detail vs. what is expected and required from the spec. Can we agree that the behavior expected via modification of specific element roles and attributes are separate concerns from whether or not they have been injected into the DOM? To @polent's point `VoiceOver` honors the desired behavior. Working around such exceptions forces those who trying to build accessible UI to make unnecessary workarounds to achieve the intended behavior.

Would you consider reopening this issue?

**Comment by Jakooth** [comment] 2023-10-10 13:47
Same issue for us. We use mostly React.js and role="status" does not work in many cases where the message should appear in a particular HTML fragment, which is rendered conditionally, so we use role="alert" as a workaround.
Probably having an ever existing container to push status messages there will be the way to do it, but in reality I just want to announce what is on the screen - the simplest example: "No results found" for a search widget.
By the way it is not just role-status, just anything with aria-live sometimes does not work unless it is an alert.

**Comment by LaurenceRLewis** [comment] 2023-10-26 22:23
I don't believe this is a bug in NVDA as this is how live regions have always worked to my knowledge. I get the same experience testing the provided code examples with JAWS. Happy to be corrected :-)

If the container with role=status exists in the DOM before the message is injected it is announced. If the container with role status is injected with the message it will not announce. This is the expected behaviour in my experience.

**Comment by joe-watkins** [comment] 2023-10-27 18:28
The solve is to just put `role="alert"` on all the things :) That feels weird but works.

**Comment by LaurenceRLewis** [comment] 2023-10-27 21:54
Used Role Alert is a really bad idea unless you really need to. Just code according to the spec.

**Comment by Adriani90** [comment] 2023-10-27 23:27
cc: @jcsteh since it affects Firefox in particular, but not only.

**Comment by jcsteh** [comment] 2023-10-29 21:57
See https://github.com/nvaccess/nvda/issues/7906#issuecomment-807957477, https://github.com/nvaccess/nvda/issues/11410#issuecomment-663285942, https://github.com/nvaccess/nvda/issues/8873#issuecomment-432487794. Also #12464.

This isn't specifically an implementation detail about how the live region was created: DOM injection, page load, layout unhiding, whatever. It's about updates to a live region (which is what the spec talks about) vs the content present in the live region when it was initially created (which is arguably not an "update").

To give a practical example of why the proposed behaviour is problematic, imagine there is a page which has a massive live region (or multiple live regions) when it initially loads. Per the proposed behaviour, NVDA would read all of that content as soon as the page loads, spamming the user with content. It's also a performance problem, since NVDA would have to scan the page to find all live regions at load time.

The intuitive argument at this point is, "well, just don't read them on page load." But on the modern web, page load is very difficult to define. Do we mean DOM load (DOMContentLoaded), load of all resources (load event) or whenever JS has stopped doing stuff (there's not even an event for that). We could say, "just don't scan the page for initial live regions,", but that would mean that initial live regions sometimes load and sometimes don't, depending on the timing of the page load and how that affects the browser's firing of events and NVDA's capturing of said events.

See also the nasty chat log example in https://github.com/nvaccess/nvda/issues/8873#issuecomment-432487794.

**Comment by ramoncorominas** [comment] 2023-11-03 17:52
I would add that the proper action here is to stop announcing the injection of any region with role="alert", since it's not the expected behavior according to the spec

**Comment by Adriani90** [comment] 2024-03-19 00:36
It is definitely worth it to design a live region in such a way that screen reader users get the relevant information at the right time with the right priority. All the roles for live regions such as alert, relevant, atomic=BOOLEAN etc. might be important for designing the live region. So just using the role= status for the whole region and making the screen reader announce all of the updates will definitely overwelm users. For us it is important to get the same information as sighted people at the same time if possible.

More information on the roles you can find here:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

I am closing this issue for now but feel free to comment in case you have a strong argument for continuing the discussion on this proposal.

**Closed by Adriani90** 2024-03-19 00:36 UTC
Labels: ARIA, p4, triaged

**Comment by jinyoungca** [comment] 2024-03-19 02:50
Thanks for considering our feedback! Not sure how relevant this is but I remember hearing something around introducing a new web API that would allow us to trigger screen-reader specific announcements through javascript (vs. injecting something into the DOM). I think that could go a long way towards making this behavior a lot more straightforward and ergonomic on the engineering side.

**Comment by Adriani90** [comment] 2025-06-29 11:39
Just to add a note, in Jaws the virtual cursor of its browse mode is moved to the new content added to the DOM, how ever I have no idea how Jaws scans the DOM for the new content and moves the virtual cursor there.
The drawback is that the user is loosing the previous position when the virtual cursor is automatically redirected, and this is not desirable actually. Jaws does not provide a key stroke to move virtual cursor back to its initial position. Especially when the newly added content is placed very far away from the initial position of the virtual cursor, the user gets lost.

I think NVDA could provide a feature like a key stroke to move back to the initial virtual cursor position after it has been redirected to the newly added content, but then it needs a storage method for the initial virtual cursor position which is applied whenever the virtual cursor is redirected automatically.
@jcsteh, @SaschaCowley do you think this might make sense?? If yes, we could reopen this one.
