### ISSUE TITLE
Role="none" on <ins> element does not hide semantics from AT. 

### ISSUE THREAD

**Issue by mvita11y** [nvaccess/nvda#9165] opened 2019-01-16 20:55 UTC
### Steps to reproduce:
<h1 role="none">Heading with role="none"</h1>
<p> 
  <ins role=“none”>This</ins>
  <ins role=“none”>is</ins>
  <ins role=“none”>it</ins>
</p>

### Actual behavior:

The `<h1>` with `role="none"` is reported in the accessibility tree as a text string with no semantic meaning.

The  `<ins>` elements  with `role="none"` wrapped in the `<p>` are announced as, "inserted this, inserted in, inserted it".

### Expected behavior:

The `<h1>` with `role="none"` is reported in the accessibility tree as a text string with no semantic meaning. (Same as actual)

The `<ins>` elements with` role="none"` are reported in the accessibility tree as a text string with no semantic meaning just as the `<h1>`. NVDA announces the string as, "This is it".

**Comment by mvita11y** [comment] 2019-01-16 20:58
@sh0ji

**Comment by DrSooom** [comment] 2019-01-17 02:46
@mvita11y: Please list all browsers (incl. version) where this issue occurs. Thanks.

**Comment by Adriani90** [comment] 2020-05-12 21:43
cc: @leonardder do you have any suggestions on why the -ins> atributes are reported here?

**Comment by Adriani90** [comment] 2023-05-07 08:13
According to this statement, the role="none" has been introduced as synonym for role="presentation" to minimize confusions for web authors.
https://www.digitala11y.com/none-role/

cc: @michaelDCurran, @jcsteh applying NVDA support for role="none" and role="presentation" on as much use cases as possible will probably improve user experience by reducing noisy reportings, not only in browsers but also in Chromium embeded windows, mail clients etc.

**Comment by jcsteh** [comment] 2023-05-07 11:03
Can't reproduce in Firefox:
`data:text/html,<p><ins>ins</ins><ins role="none">none</ins></p>`
The text "none" is not read as inserted, only the "ins" text is read as inserted.

**Comment by Adriani90** [comment] 2023-05-07 12:54
Ok tested in Chrome and edge also with different elements like section, landmarks etc. It seems role="none" indeed works as expected.

I am closing this as works for me. Please feel free to post a minimal test case where it doesn't work and we can reopen.

**Closed by Adriani90** 2023-05-07 12:54 UTC
Labels: close/worksforme
