### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#8060] opened 2018-03-06 11:54 UTC
in 2018.1 NVDA version, do not forget to enable grammar error feature. that feature was very useful for a person with visual impairment when editing grammar. it was available in NVDA 2017.1 but it was removed because there was a burg in it.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by ehollig** [comment] 2018-03-07 03:24
I am closing this as duplicate of #7319

**Closed by ehollig** 2018-03-07 03:24 UTC
