### ISSUE TITLE
Different browse mode behaviour for multiple span elements next to each other

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#6529] opened 2016-11-02 08:06 UTC
It seems that, when a page source contains multiple span elements without any separator such as <br /> or similar, the result is different across browsers. Observe [this file](https://github.com/nvaccess/nvda/files/565934/Spantest.html.txt)
 to reproduce.

## Internet explorer, use screen layout off
This is
a test

## Google Chrome Kanari
This isa test

## IE with screen layout on/Firefox/Edge
This is a test

Particularly the Chrome one is quite annoying, honestly, as I've seen multiple situations where browse mode didn't add a space between multiple elements, resulting in weird output.
Any thoughts?

**Comment by feerrenrut** [comment] 2016-11-03 03:11
I am able to reproduce this.

The space between "This is" and "a test" is only inserted in Firefox when the `span`s are on separate lines. If you put them on the same line with no space between them visually and with nvda you get "This isa test".

In Chrome, with the `span`s on separate lines, visually you get "This is a test" and with nvda you get "This isa test". When on the same line with no space between the `span` tags visually and with nvda you get "This isa test".

This seems like its caused by a bug in chrome. P2 to log a bug against chrome.

**Comment by leonardder** [comment] 2016-11-04 08:21
```It seems that
this also
fails in chrome```

The code above with the ``` cintax is on three lines, but chrome prints it on one line.

**Comment by leonardder** [comment] 2016-11-04 08:29
Alright, here's a better preview.
http://stackoverflow.com/questions/3961265/get-line-number-of-certain-phrase-in-file-python

This is just a random question that contains a code snippet in the first answer, below the first level 2 heading. In firefox, new line characters are respected, in Chrome, they aren't at all.

**Comment by darbaga** [comment] 2017-03-06 06:43
Some more pages where this happens:

http://manishearth.github.io/blog/2017/03/04/what-are-sum-product-and-pi-types/

http://www.cppsamples.com/common-tasks/return-multiple-values.html

http://rustbyexample.com/fn/hof.html

https://googlechrome.github.io/samples/classes-es6/index.html

**Comment by jcsteh** [comment] 2017-09-05 03:53
It seems the major concern here is that Chrome incorrectly strips spaces and line breaks in some cases, particularly code blocks. This is covered by #7057, which, while filed later, contains more up to date info. Closing as a duplicate of #7057.

**Closed by jcsteh** 2017-09-05 03:53 UTC
Labels: GoogleWork, p2
