### ISSUE TITLE
NVDA breaks Excel randomly when editing

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#7704] opened 2017-10-26 18:07 UTC
### Steps to reproduce:
I really don't know how to reproduce this, but Excel keeps hanging after some editing.

Sometimes it happens when pressing enter after editing a cell.

Sorry for the too basic information ...

### Expected behavior:
Just edit without problems and without a broken session after using excel ...

### Actual behavior:
After editing a sheet ten minutes it starts hanging and the entire user session breaks. I need to restart my PC to work again.

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable: Installed

Other information:
I have office Pro Plus 2016 32bits installed in a 64bits laptop because I wanted to use Math Type.

Windows version: Windows 10 Pro Build 16299.19

I don't know if it is relevant, but I have Eset Internet Security installed on my system.

### Other questions:

Does the issue still occur after restarting your PC?
Yes, after some time working well it makes the user session unusable again.

Have you tried any other versions of NVDA?
No, I didn't.

**Comment by francipvb** [comment] 2017-10-26 18:09
Can be solved by solving #7409 or it is unrelated to this?

**Comment by ehollig** [comment] 2017-11-06 03:28
I do not believe I can reproduce your issue @francipvb. Is it possible to get an NVDA log with logging set to debug demonstrating the issue attached to this ticket?

**Comment by francipvb** [comment] 2017-11-06 13:02
Hello,

I'm confused. I cannot reproduce this too. May be a problem with Creators Update or a problem when running with battery?

I've upgraded my system two weeks ago and didn't tested it before.

If I can get this issue again I'll post a log here.

Cheers,

**Comment by francipvb** [comment] 2017-11-07 02:13
Hello,

I got a [log](https://github.com/nvaccess/nvda/files/1448428/log.log) with the session. I've read it but I didn't found valuable info.

I opened Excel two times:

* The first was with the CA adapter connected and no other office program running.
* The second ones was without CA adapter and Word running alongside Excel.

I hope that this log and this new info would help you.

Cheers,

**Comment by francipvb** [comment] 2018-02-03 13:36
Hello,

¿What about this issue?

Cheers,

**Comment by ehollig** [comment] 2018-02-04 02:55
[**@francipvb**](https://github.com/francipvb) commented on [Nov 6, 2017, 7:13 PM MST](https://github.com/nvaccess/nvda/issues/7704#issuecomment-342353364 "2017-11-07T02:13:28Z - Replied by Github Reply Comments"):
> Hello,
> 
> I got a [log](https://github.com/nvaccess/nvda/files/1448428/log.log) with the session. I've read it but I didn't found valuable info.

I was not able to find valuable info in the log either. Also, it is several lines long. Unfortunately, I am still unable to reproduce your issue.

**Comment by Adriani90** [comment] 2019-05-01 08:47
@francipvb this seems to be a very specific issue. I cannot reproduce it either. So we rely on your tests and updates. Is it still an issue for you?

**Comment by fernando-jose-silva** [comment] 2019-05-01 15:24
My excel was also catching a lot.
I discovered that in my case the problem was the .nvda-addon focusHighlight-Now I can no longer test the add-on, nvda 17110 does not install or run the add-in anymore because it is asking for the update of the add-on for 2019.2 compatibility.

**Comment by Adriani90** [comment] 2019-05-01 17:22
cc: @nishimotz

**Comment by Adriani90** [comment] 2019-05-02 16:52
Since this seems to have been caused by an addon, I am closing this as works for me. fernando feel free to contact Nishimotz (cc above) and provide feedback regarding to the addon. But since NVDA will have a native focus highlight I guess the addon might be obsolete at some point in the future.
@francipvb if you are still having this problem though, feel free to comment on this issue and we can reopen it. Thanks.

**Closed by Adriani90** 2019-05-02 16:52 UTC
Labels: Microsoft Office support, worksforme
