### ISSUE TITLE
Combobox expanded state not always read on focus

### ISSUE THREAD

**Issue by jdrush89** [nvaccess/nvda#10245] opened 2019-09-18 18:49 UTC
### Steps to reproduce:
Use the keyboard to focus a div with role combobox when its input child is not a direct descendant.  It can be repoduced here: https://codesandbox.io/s/strange-haibt-rd3ub
steps:
1. click in the white box then tab to focus the first combobox
2. shift+tab to move focus before the first combobox
3. tab to move focus back on the combobox
4. repeat steps 2 and 3, notice that the expanded state is only sometimes read (usually just the first time)
### Actual behavior:
The aria-expanded state of the combobox is only announced sometimes.  It seems to be announced the first time the combobox is focused, but not subsequent times.  This behavior is only present on NVDA with chrome, FF seems to work all the time.
### Expected behavior:
NVDA should announce the aria-expanded state of the combobox whenever it receives focus.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2017.4
#### Windows version:
Version	10.0.18362 Build 18362
#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
#### Other information about your system:
NA
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by lukaszgo1** [comment] 2019-09-18 18:58
@jdrush89 Can you reproduce this with NVDA 2019.2? It is generally good idea to test with the latest version  before reporting a bug.

**Comment by jdrush89** [comment] 2019-09-18 19:55
I updated to 2019.2. With this version, NVDA doesn't seem to announce the expanded state of any combobox, including the ones on the W3 example site https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
Is this expected?  Before it would announce "combobox collapsed" when these were focused.

**Comment by Adriani90** [comment] 2019-09-19 20:42
I am testing with NVDA Version alpha-18699,0e4bb4ad
On Chrome 77 I cannot reproduce this issue. Everytime when I land on the combobox, no matter if in browse mode or focus mode or if I am moving with arrow keys or tab and shift + tab, NVDA reports the expanded or the colapsed status as it should be.

@jdrush89 could you please test with Chrome 77?

**Comment by jdrush89** [comment] 2019-09-20 17:08
@Adriani90 NVDA 2019.2 with chrome 77 does not work, but NVDA Version alpha-18699,0e4bb4ad with Chrome 77 does work on the W3 sample site.  The original issue still exists in the codesandbox though, the collapsed state is not being announce there.  Is that what you are seeing?

**Comment by Adriani90** [comment] 2020-04-25 14:41
@jdrush89 could you please test with NVDA Version: alpha-20045,a335297e in Chrome 81? I cannot reproduce this issue with these verisons.
You can download the alst alpha here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment] 2020-05-27 22:13
Working as expected in Chrome 83.Closing as works for me. Please comment on this issue if you are still having it and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-27 22:13 UTC
Labels: close/worksforme
