### ISSUE TITLE
Remove deprecated alias App Modules.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#13627] opened 2022-04-22 09:57 UTC
### Is your feature request related to a problem? Please describe.
Before PR #13366 the only way to use a single App Module for multiple binaries was to create an alias module and import everything from the real module into it. The mentioned PR improves things so that we can now map an App Module to a given binary. While all alias App Modules currently in core are mapped that way they cannot be simply removed as NVDA 2022.2 should preserve backward compatibility and some add-on may rely on one of these.
### Describe the solution you'd like
These alias App Modules should be removed in the first compatibility breaking release after 2022.2. If any add-on imports from them an appropriate warning is logged so add-on authors have plenty of time to prepare. Note also that this is not backward incompatible i.e. if add-on imported from App Module for Spring Tool Suite and now it should import from the Eclipse module this does not break compatibility with earlier NVDA releases.
Most of these aliases are causing linter failures and in addition some of them cause Sphinx warnings when generating developer documentation
### Describe alternatives you've considered
Leave these aliases alone.
### Additional context
If it is decided we should remove alias modules this issue should be added into 2023.1 milestone.

**Comment by Brian1Gaff** [comment] 2022-04-23 07:54
This is over my head, but I do know that there will come a time when a lot 
of the routines used by all sorts of software that mainly are part of the 
old  Internet Explorer code will vanish, and a lot of software will then not 
work any more.
I still use  software like that on Windows 7, which is fine, but it could be 
an issue for nvda if it assumes something is available when its not.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Łukasz Golonka" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, April 22, 2022 10:57 AM
Subject: [nvaccess/nvda] Remove deprecated alias App Modules. (Issue #13627)

**Comment by seanbudd** [comment] 2022-04-27 05:50
If there is minimal ongoing maintenance cost for keeping these aliases, lets defer and keep these aliases if possible.

**Comment by feerrenrut** [comment] 2022-05-17 07:14
We don't intend to remove these aliases in the foreseeable future. If there is some impact caused by this a new issue should be opened to describe. Closing this.

**Closed by feerrenrut** 2022-05-17 07:14 UTC
Labels: deprecated/2023.1
