### ISSUE TITLE
Alternative to Alt+Del in Jaws - position of cursor in MS Word

### ISSUE THREAD

**Issue by jaxcze** [nvaccess/nvda#6352] opened 2016-09-06 12:14 UTC
In Jaws screenreader is shortcut Alt+Del. This one says position of cursor from left edge of paper or printing mirror in MS Word.
This is missing in NVDA.

**Comment by jcsteh** [comment] 2016-09-06 12:16
Duplicate of #3707.

**Closed by jcsteh** 2016-09-06 12:16 UTC
Labels: duplicate
