### ISSUE TITLE
How does Gmail automatically override NVDA single letter navigation?

### ISSUE THREAD

**Issue by bergatron** [nvaccess/nvda#10047] opened 2019-08-07 15:40 UTC
I noticed that when using Gmail, the `j` and `k` shortcuts for navigating the message list work *without* first disabling NVDA "single letter navigation". How is this achieved? I'd like my app to work like this.

### Steps to reproduce:

1. Open Gmail and login.
2. Press the `j` and `k` keys to navigate up and down the list of messages.

### Actual behavior:

`j` and `k` keys navigate through the list of messages.

### Expected behavior:

Expected that NVDA would default to "single letter navigation", like it does for other web apps, requiring `NVDA` + `shift` + `space` to be pressed in order to turn single letter navigation off before `j` and `k` worked for navigating the list of messages.

**Comment by codeofdusk** [comment] 2019-08-08 11:39
I can't reproduce this on Chrome 76.0.3809.100 on Windows 10 1903.

**Comment by larry801** [comment] 2019-08-09 00:22
This is a Gmail feature and it is not enabled by default.
If you want to implement similar feature in a website or desktop
application.Just write a keyboard shortcut on your own.

**Comment by bergatron** [comment] 2019-08-13 18:34
So just to clarify things a bit, check out the difference between Twitter and Gmail. In Gmail, the `j` and `k` shortcuts work immediately. In Twitter, the user is first required to exit single letter navigation by pressing `NVDA` + `shift` + `space`, then the `j` and `k` shortcuts become active.

Why do the `j`/`k` shortcuts work immediately in Gmail, but not in Twitter?

**Comment by Adriani90** [comment] 2019-08-17 17:41
I guess in GMail the shortcuts are directly linked only to the system focus and the focus mode while in Twitter the gestures are also registered in the virtual buffer. But I am not 100% sure.
Maybe @josephsl can help clarify this?

**Comment by Adriani90** [comment] 2019-08-17 17:43
Actually the approach from twitter is the ideal one because you are not forced to use focus mode in their application if you want to use their own shortcuts.

**Comment by Adriani90** [comment] 2019-08-17 17:45
that means in twitter you can use their shortcuts also in browse mode but you only have to disable the quick navigation keys provided by NVDA which is done by pressing nvda+shift+space.

**Comment by Adriani90** [comment] 2020-05-02 18:25
Closing this issue. We can discuss further questions on gitter if required.

**Closed by Adriani90** 2020-05-02 18:25 UTC
