### ISSUE TITLE
Browse Mode Buffer Out of Sync

### ISSUE THREAD

**Issue by dan1982code** [nvaccess/nvda#7844] opened 2017-12-09 15:39 UTC
I'm using Firefox ESR here, with NVDA next-14699,4f6fe6f3.

1. If you start here: https://en.wikipedia.org/wiki/Roland_MT-32
2. Click "List of MT-32-compatible computer games".
3. A big page of tables shows up.
4. Now, alt+left to go back to the prior page, with title "Roland MT-32". You can verify this with NVDA+T. However, the browse mode buffer is still the "List of MT-32-compatible computer games".
5. Alt+tab back and forth seems to fix it, as does an NVDA+F5 followed by a tab.

**Comment by derekriemer** [comment] 2017-12-09 22:35
Did this happen after update, or does it survive a reboot of the browser?

**Comment by derekriemer** [comment] 2017-12-09 22:36
s/after update/after an NVDA update/

**Comment by dan1982code** [comment] 2017-12-10 01:47
Absolutely survives browser/computer restarts.

**Comment by derekriemer** [comment] 2017-12-10 13:11
does anyone else have ESR to test this on?

**Comment by dan1982code** [comment] 2017-12-10 14:49
I've just reproduced in Firefox 57/58. No one can reproduce this? I'll try to dig further here, then. Thanks!

**Comment by derekriemer** [comment] 2017-12-10 23:26
1. I click the link.
2. I press / (my nvda+ctrl+f3 equiv). 3. I type "List of MT-32-compatible computer games"
4. I click the link.
5. I press alt+left.
6. I wait for the resulting buffer.
7.  I press NVDA+t to confirm the title.
8. I press NVDA+l:

Result: 
See also: (link) List of MT-32-compatible computer games

**Comment by derekriemer** [comment] 2017-12-10 23:27
59.0a1 (2017-12-09) (64-bit)

**Comment by mohdshara** [comment] 2017-12-11 07:08
wierd. I have just downloaded firefox ESR portable but I couldn't reproduce this issue. I can't reproduce it with firefox 58 beta 10 as well.

**Comment by Brian1Gaff** [comment] 2017-12-11 17:53
Exactly what is the issue. I'm mega confused now. I have 52ESR on Windows 7 
332 bit ff but 64 bit windows.
 Brian

**Comment by dan1982code** [comment] 2017-12-11 18:03
The issue is that hitting alt+left does not change the browse mode buffer at all, even though Firefox goes back to the prior page as it should.

**Comment by feerrenrut** [comment] 2017-12-12 08:01
It seems like perhaps in your case NVDA is not notified that the page has changed.

@dan1982code If you hit F5 after `alt+left` does the title report as you expect?
@jcsteh do you have any suggestions here?

**Comment by jcsteh** [comment] 2017-12-12 11:37
It does sound like a focus event went missing for some reason. However, several other users have reported they can't reproduce this, and while I'm not able to test this just now myself (though I can later if needed), I'm pretty sure I've not seen issues like this in a long time.

Do you have any NVDA or Firefox add-ons installed? If so, please try restarting NVDA with add-ons disabled and also starting Firefox in safe mode (available from the Help menu).

I doubt this, but just to double check are you running any other assistive technology software at the same time or in the same session of Firefox? For example, are you starting another screen reader, exiting that reader and then starting NVDA without also restarting Firefox?

**Comment by dan1982code** [comment] 2017-12-12 15:59
No other assistive tech, happens with safe mode too, happens on multiple Windows 10 computers... so confused here.

I can also reproduce this on Google Scholar. For example:
*go to https://scholar.google.com
*Search for Ido Golding, and click their search result
*Now, in the co-authors grouping, chose one of their co-authors
*Now, alt+left back to Ido Golding's page. The virtual buffer does not reset.

It seems to happen on a page with a large table. This is what this has in common with the MT32 Wikipedia page that I showed earlier.

Sorry -- I will try on more machines and will reinstall NVDA from scratch and try to figure out something that will help here.

**Comment by feerrenrut** [comment] 2017-12-21 03:44
I am not able to reproduce this with Firefox Version 57.0.2 and NVDA Version: next-14753,cae9ca42
If you can reproduce this issue reliably, could you attach a debug level NVDA log to this issue. There might be something relevant in the log.

**Comment by Adriani90** [comment] 2019-01-23 21:31
@dan1982code are you still having this issue? If yes, could you please attach a log file when it occurs?

**Comment by dan1982code** [comment] 2019-01-23 22:00
I can't get this to happen anymore. In fact, I have not seen this issue in a long time now.

**Comment by Adriani90** [comment] 2019-01-23 22:56
wow this was fast. Thank you for the reply. Closing as works for me.

**Closed by Adriani90** 2019-01-23 22:56 UTC
Labels: Browse mode, worksforme
