### ISSUE TITLE
Firefox: When navigating by words with the review cursor in the markup view inspector single characters are treated as words

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#13838] opened 2022-06-23 19:25 UTC
### Steps to reproduce:
1. Start Firefox
2. Open google.com
3. From the context menu choose inspect
4. In the markup view Move to the h1 tag named "Accessibility links"
5. With the object navigation move to its class name and try to navigate it by word with numpad 4 and 6
### Actual behavior:
The single characters are reported as words i.e. when moving by word from the beginning NVDA reports "c", "l", "a" etc.
### Expected behavior:
Entire words are reported.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
NVDA version alpha-25684,ac7215b1
#### Windows version:
Windows 7 X64
#### Name and version of other software in use when reproducing the issue:
Firefox Nightly 103 X64
#### Other information about your system:
None relevant
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tried

cc @jcsteh

**Comment by jcsteh** [comment] 2022-06-24 00:24
I don't seem to have an "Accessibility Links" heading on google.com. Nevertheless, I reproduced this with this test simple case:
`data:text/html,<div class="test">test`

This is already fixed by our ongoing Cache the World refactor (currently disabled while under development).

**Comment by lukaszgo1** [comment] 2022-06-24 10:12
I can confirm that enabling CTW makes words offset correct here.

**Comment by Adriani90** [comment] 2023-05-10 07:59
Cache is enabled by default in Firefox 113, closing as works for me.

**Closed by Adriani90** 2023-05-10 07:59 UTC
Labels: close/worksforme, blocked/needs-external-fix, p3, app/firefox, triaged
