### ISSUE TITLE
drupal.org website, NVDA announces too many <Clickable> voices

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#8802] opened 2018-09-28 18:37 UTC
### Steps to reproduce:
1. Open URL: https://www.drupal.org/project/d8_blog_theme
2. h Press the key four times
### Actual behavior:
NVDA says too much Clickable messages.
Example speech message:
main landmark clickable  clickable  clickable  clickable  clickable  clickable  clickable  clickable  clickable

### Expected behavior:
I think there should be additional options apart from disabling or enabling options. <Clickable> element I hear too much of a notification message, and I think it interferes with the navigation of the web page.
#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
Alpha
#### Windows version:
W10(version 1803)
#### Name and version of other software in use when reproducing the issue:
Firefox(nightly), chrome(Canary)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment] 2018-09-28 18:54
Duplicate of #7430

**Closed by ehollig** 2018-09-28 18:54 UTC
