### ISSUE TITLE
NVDA reads data twice

### ISSUE THREAD

**Issue by SwathiMicro** [nvaccess/nvda#8707] opened 2018-09-03 04:31 UTC
### Steps to reproduce:
Save the attached html file in local machine in .html format.
Open the file in chrome browser.
Start NVDA.

### Actual behavior:
NVDA reads the date column present in the file twice due to presence of title attribute and label attribute in chrome browser.

### Expected behavior:

NVDA should not read the title attribute. if it is reading it should mention it as tooltip. This is causing confusion as the data is read twice.

### System configuration:
Windows 10 OS 1806, 64 bit OS

#### NVDA Installed/portable/running from source:
NVDA installed
#### NVDA version:
2018.2.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Chrome Browser
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
NO
[Sample.docx](https://github.com/nvaccess/nvda/files/2344203/Sample.docx)

**Comment by Adriani90** [comment] 2020-05-16 23:42
@feerrenrut is this a duplicate of #7841?

**Comment by feerrenrut** [comment] 2020-06-16 10:05
Yes, it looks like it. Closing as duplicate.

**Closed by feerrenrut** 2020-06-16 10:05 UTC
