### ISSUE TITLE
Combobox with grid aria-activedesendant switching to browse mode for non gridcell elements

### ISSUE THREAD

**Issue by adamsamec** [nvaccess/nvda#16414] opened 2024-04-17 15:38 UTC
### Steps to reproduce:

1. Turn on NVDA.
2. Visit this [combobox with aria-activedescendant grid containing interactive elements example][fluentui example].
3. Using the Tab key, navigate to the "Search" combobox.
4. Using the Down arrow key and then Down/Up/Right/Left arrow keys, try to navigate by cells in the grid popup.
5. Visit this [W3C combobox with aria-activedescendant grid containing only focusable gridcells][apg example].
6. Using the Tab key, navigate to the "Fruits and vegetables" combobox.
7. Using the Down arrow key and then Down/Up/Right/Left arrow keys, try to navigate by cells in the grid popup.

### Actual behavior:

In the first example, after transitioning to the grid and trying to navigate with the Down/Up/Right/Left arrow keys, NVDA switches to browse mode as soon as element other than role="gridcell" is referenced using the aria-activedescendant attribute set on the combobox. Compare this with the second example by W3C, where NVDA stays in the forms mode as one navigates grid using arrow keys.

### Expected behavior:

NVDA should stay in the forms mode no matter which focusable element is referenced using the aria-activedescendant attribute set on the combobox.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

NVDA 2024.1.0.31547.

#### Windows version:

Windows 11, version 23H2 (OS Build 22631.3447).

#### Name and version of other software in use when reproducing the issue:

* Google Chrome, version 124.0.6367.61.
* Mozilla Firefox, version 125.0.1.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes.

[fluentui example]: https://fluentuipr.z22.web.core.windows.net/pull/30892/public-docsite-v9/storybook/iframe.html?id=concepts-developer-accessibility-activedescendantcomboboxes--grid-active-descendant-combobox-cell-navigation&viewMode=story
[apg example]: https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/grid-combo/

**Comment by Adriani90** [comment] 2024-04-17 20:08
Closing as duplicate of #11413.

**Closed by Adriani90** 2024-04-17 20:08 UTC
Labels: close/duplicate, ARIA
