### ISSUE TITLE
NVDA sometimes plays error sounds continually when reading incoming text in cmd

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#13063] opened 2021-11-16 05:14 UTC
/CC @codeofdusk 

### Steps to reproduce:

1. Windows+r, type cmd and press enter to open the command prompt.
2. Type or do something that causes incoming text to be read.

### Actual behavior:

```
ERROR - diffHandler.DiffMatchPatch.diff (13:10:15.680) - Dynamic_WinConsoleUIAEditableTextWithAutoSelectDetectionUIA._monitorThread (16244):
Exception in DMP, falling back to difflib
Traceback (most recent call last):
  File "diffHandler.pyc", line 71, in diff
  File "diffHandler.pyc", line 58, in _initialize
  File "subprocess.pyc", line 753, in __init__
  File "subprocess.pyc", line 1107, in _get_handles
  File "subprocess.pyc", line 1119, in _make_inheritable
OSError: [WinError 50] The request is not supported
```

Incoming text is still read, just that each time it is accompanied with error tones.

### Expected behavior:

No errors

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-24184,fd9ae8c4

#### Windows version:
Windows 10.0.19043.1348

#### Does the issue still occur after restarting your computer?
It fixes itself after restarting NVDA

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/a

**Comment by codeofdusk** [comment] 2021-11-16 05:18
This is odd, thought #12827 would've fixed.

What's your API level (NVDA+f1)? Guessing you're using a `FORMATTED` build since fd9ae8c4 disabled DMP in older versions.

**Comment by Neurrone** [comment] 2021-11-16 05:20
API level: 0 (END_INCLUSIVE)

**Comment by codeofdusk** [comment] 2021-11-16 05:21
OK, please make sure that your "diff algorithm" is set to "automatic".

**Comment by Neurrone** [comment] 2021-11-16 05:24
I've since changed it from dfp to automatic. I'll observe to see if this happens again.

**Comment by Adriani90** [comment] 2024-11-27 23:41
I cannot reproduce this with NvDA 2024.4.1. I am closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-11-27 23:41 UTC
Labels: close/worksforme, app/windows-terminal, app/windows-console
