### ISSUE TITLE
NVDA reader does not announce the dialog title and content upon Alert Dialog open.

### ISSUE THREAD

**Issue by rulyu** [nvaccess/nvda#10186] opened 2019-09-10 17:30 UTC
### Steps to reproduce:
Go to the example [alertdialog example on the W3C Standards site](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html),
click on the "save" or "discard" button to trigger alert dialog open.
Listen to what nvda reader reads for the dialog. 
![image](https://user-images.githubusercontent.com/55103654/64635871-68110d00-d3b5-11e9-8b02-1fe789d2d7cb.png)

### Actual behavior:
The nvda reader only reads the "no" button in the dialog, does not read the title and the content of the dialog.
### Expected behavior:
NVDA reader should read the title and the content of the dialog.

Narrator on Edge reads out the title and content of the dialog correctly. NVDA on Chrome, however, does not
#### NVDA installed/portable/running from source:
installed on Windows
#### NVDA version:
NVDA version 2019.2

#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Chrome version 76
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

**Comment by Brian1Gaff** [comment] 2019-09-10 19:38
It worked in Waterfox just now.
on the latest Alpha.


bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by emilyuhde** [comment] 2020-01-27 16:46
I'm running into this issue with NVDA as well when `role="alertdialog"` and the content text is being pointed to with `aria-describedby`. It would be great if this issue could be addressed soon.

**Comment by Adriani90** [comment] 2020-02-27 20:43
This is still reproducible in NVDA 2019.3.1 and Chrome 80.
cc: @feerrenrut

**Comment by Adriani90** [comment] 2020-02-27 21:02
Closing as duplicate of #9368.

**Closed by Adriani90** 2020-02-27 21:02 UTC
Labels: duplicate
