### ISSUE TITLE
NVDA screen reader problems while reading code word by word in Microsoft  visual studio code  editor

### ISSUE THREAD

**Issue by snufas** [nvaccess/nvda#7605] opened 2017-09-14 16:27 UTC
NVDA screen reader problems while reading code word by word in Microsoft  visual studio code  editor 

Steps to Reproduce:
use NVDA screen reader with VS code editor it does not matter what language or file type.
open a code example  javascrypt for example 
focus to the editor like you would use a text box in the browser because thats how it works.
CTRL+ right arrow to read word by word
issues using screen reader. Screen reader repeats words multiple times when reading word by word when using VS code. ataching short recording video, audio  of the problem and comparing with notepad++, the nvda screen reader interacts with the text differently while using VS code.
it would be nice if you watch the video and try to make sense what i am trying to explain. it would be very good if devs of VS code fix that. this fix would help blind or low vision community who uses screen reader to use VS code.
i hope that can be fixed because this is the problem that there is no way to get around and is very annoying to work with.
thanks
https://w ww.dropbox.com/s/ujbemn92u90ojfe/nvda_vs_Code_problems.mp4? dl=0
 👍 1

**Comment by snufas** [comment] 2017-09-14 16:28
issue link on the github VS code page 
https://github.com/Microsoft/vscode/issues/34319#issuecomment-329400121

**Comment by bramd** [comment] 2017-09-23 13:45
The reason is that VSCode has another way to navigate by word and NVDA doesn't expect this. If you look at the cursor position in braille or using review commands, you'll see that the cursur moves to start/end of the current word. This is sometimes quite useful in code and I guess it's a feature of VSCode. NVDA might need an appmodule to handle this better.

**Comment by ironcross32** [comment] 2018-12-05 21:47
I can confirm that this is an issue. Though I do see the value in their way of doing things, if you want to read past the method itself and into the arguments you've given it, you must press the control right arrow key a number of times more than would be needed in a normal text editor.

**Comment by leonardder** [comment] 2019-07-25 09:55
cc @derekriemer

**Comment by Adriani90** [comment] 2019-07-25 12:46
and cc: @pawelurbanski

**Comment by pawelurbanski** [comment] 2019-07-31 10:51
I will check how it works with my CS Code add-on. And if there is a fix, which is rather easy to implement, I will gladly contribute - together with a few suggestions I got from the otehr users.

**Comment by feerrenrut** [comment] 2020-03-10 12:03
This was being tracked in microsoft/vscode#28306 which seems to have been addressed. Closing this issue.

**Comment by leonardder** [comment] 2020-03-12 12:16
There's now a new issue for this: https://github.com/microsoft/vscode/issues/90578#issuecomment-598141858

**Comment by Adriani90** [comment] 2023-04-01 22:30
That issue reference by Leonard above is now also fixed via a workaround in VS Code. I think we should track this further in #12091 which also affects this. Please comment there, I am closing this one.

**Closed by Adriani90** 2023-04-01 22:30 UTC
