### ISSUE TITLE
Excel suggestion: provide a way to reach out to the data presented in a scattered format on a sheet.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5132] opened 2015-06-02 09:07 UTC
**Reported by sumandogra on 2015-06-02 09:07**
SUGGESTION:  On an Excel sheet that has data scattered, it takes a lot of time to find out the start and end of the data.  Sometimes the next cell with data is far from the last cell with data.  Using ARROWS or CTRL+UP/DOWN/LEFT/RIGHT ARROW consumes time.  A sighted person quickly can navigate and fill this sheet or read this kind of sheet but for a NVDA user , it takes time to find out the data on this sheet.  It will be helpful to introduce a quick navigation key D and SHIFT+D  in browse mode to quickly navigate to the cells with data or get a list of cells that has some data in excel sheets with data in a scattered format.
Use case:
For persons working in travel agencies such kind of sheets with data scattered can be a big time consuming factor, where they have to check out for the trains/aero planes/buses along with places, time, payments etc.  if they have a way to reach out to a cell that has data, their time will be saved.

**Comment by ehollig** [comment] 2017-08-21 14:56
Marking this issue as feature.

**Comment by Adriani90** [comment] 2024-10-04 00:00
Actually this is a duplicate of #9145 which contains more discussion on this issue. Closing in favor of #9145.

**Closed by Adriani90** 2024-10-04 00:00 UTC
Labels: close/duplicate, app/microsoft-office, feature
