### ISSUE TITLE
NVDA could narrate "checked" stated for radiogroup in toolbar 

### ISSUE THREAD

**Issue by kolaps33** [nvaccess/nvda#12678] opened 2021-07-23 12:26 UTC
### Steps to reproduce:

1. Go to [https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html  ]( https://www.w3.org/TR/wai-aria-practices-1.1/examples/toolbar/toolbar.html  )
2. Navigate into the toolbar
3. Use right arrow key until you reach radio button with name "Text Align Left"
4. Use right arrow key to navigate to next radio button
5. press Enter/Space

### Actual behavior:
Radio item/button is selected(checked).
NVDA is silent.

### Expected behavior:
NVDA could narrated information that item was selected/checked.
Similar way as NVDA narrated that radio button is checked here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-1/radio-1.html

#### NVDA installed/portable/running from source:
Installed 

#### NVDA version:
2020.4

#### Windows version:
10.0.19043

#### Name and version of other software in use when reproducing the issue:
Chrome
Version 92.0.4515.107 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
YES 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NO

#### If add-ons are disabled, is your problem still occurring?
no applicable 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
didn't try

**Comment by feerrenrut** [comment] 2021-07-26 03:50
I can't reproduce this with NVDA 2021.1 and Chrome canary `94.0.4586.0` or Edge `92.0.902.55`, NVDA announced "checked".

This doesn't seem like a common way to navigate to the buttons. Why not use `tab` or `f` to move to the buttons?

Can you please:
- Try NVDA 2021.1 (the latest NVDA release)
- Confirm you don't have add-ons running
- Try the COM registration Fixing Tool

**Comment by Adriani90** [comment] 2023-04-20 20:26
I can't reproduce this issue either in NVDA last alpha and Edge, Chromium or Firefox 112. No matter how I navigate to the ratio buttons, NVDA reports "enabled" or "disabled" when I press space bar or enter.
Note that checkboxes can be only checked and unchecked by pressing space bar, and not by pressing enter.

Closing as works for me. If you are still having this issue, please comment on this with updated steps to reproduce and we can reopen.

**Closed by Adriani90** 2023-04-20 20:26 UTC
Labels: close/worksforme
