### ISSUE TITLE
Strange error in add ons download section

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#8262] opened 2018-05-12 08:59 UTC
When going to the add ons via tools in the latest master version, I then went to the  get add ons, and got to the web site. Navigating to an add on I wanted to  install, using firefox 52esr in windows 7, I proceeded to download the file by clicking the link on the web site. The result was...
IO - speech.speak (09:23:08.565):
Speaking [LangChangeCommand ('en_GB'), u'list with 2 items', u'stable version', u'link']
IO - inputCore.InputManager.executeGesture (09:23:11.030):
Input: kb(desktop):enter
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:23:11.073):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:23:12.920):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:23:12.923):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (09:23:12.947):
Speaking [LangChangeCommand ('en_GB'), u'Opening Mozilla-1.5.nvda-addon  dialog  You have chosen to open: Mozilla-1.5.nvda-addon  which is:  NVDA add-on package (53.1 KB)  from:  \u2026ithub-production-release-asset-2e65be.s3.amazonaws.com  Would you like to save this file? ']
IO - speech.speak (09:23:12.967):
Speaking [LangChangeCommand ('en_GB'), u'What should Firefox do with this file?  grouping']
IO - speech.speak (09:23:12.973):
Speaking [LangChangeCommand ('en_GB'), u'Open with  radio button  checked  Alt+o  1 of 2']
IO - inputCore.InputManager.executeGesture (09:23:28.302):
Input: kb(desktop):tab
IO - speech.speak (09:23:28.336):
Speaking [LangChangeCommand ('en_GB'), u'combo box  NVDA  collapsed']
IO - inputCore.InputManager.executeGesture (09:23:29.918):
Input: kb(desktop):tab
IO - speech.speak (09:23:29.948):
Speaking [LangChangeCommand ('en_GB'), u'OK  button']
IO - inputCore.InputManager.executeGesture (09:23:32.127):
Input: kb(desktop):space
IO - speech._speakSpellingGen (09:23:32.147):
Speaking character u'space'
DEBUG - queueHandler.registerGeneratorObject (09:23:32.147):
Adding generator 5
DEBUG - queueHandler.pumpAll (09:23:32.158):
generator 5 finished
IO - speech.speak (09:23:32.346):
Speaking [LangChangeCommand ('en_GB'), u'Mozilla Apps Enhancements - Mozilla Firefox']
IO - speech.speak (09:23:32.415):
Speaking [LangChangeCommand ('en_GB'), u'Mozilla Apps Enhancements  document']
IO - speech.speak (09:23:32.418):
Speaking [LangChangeCommand ('en_GB'), u'\u2022 download ', u'link', u'stable version']
DEBUGWARNING - RPC process 4488 (nvda_slave.exe) (09:23:32.446):
Python warning:
C:\Program Files (x86)\NVDA\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
ERROR - RPC process 4488 (nvda_slave.exe) (09:23:32.471):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 101, in main
ValueError: No such action
IO - inputCore.InputManager.executeGesture (09:23:43.111):
Input: kb(desktop):control+alt+r
IO - speech.speak (09:23:43.157):
Speaking [LangChangeCommand ('en_GB'), u'Taskbar']
IO - speech.speak (09:23:43.201):
Speaking [LangChangeCommand ('en_GB'), u'reboot nvda with log  terminal']
IO - speech.speak (09:23:43.203):
Speaking [LangChangeCommand ('en_GB'), u'80 space', u'blank']
INFO - core.main (09:23:43.315):
Exiting
As you see i exited to get the log..
The dialogue I was in vanished leaving me in the browser.
 
Not tried anything else as yet, but since an update to a new version is up coming, I thought I'd raise this. Note there are already add ons installed but I've not had problems of this kind previously. I have rebooted everything a couple of times with the same result. Note i do have the latest focus highlight installed but have deactivated it as it made things a whole lot worse and cluttered the log with lots of stuff about pen and ink :-)
If you want me to try anything else let me know

**Comment by Adriani90** [comment] 2019-05-06 18:38
hey @Brian1Gaff this was possibly caused by an addon which tried to introduce Python 3 compatibility. Are you still seeing this issue in NVDA 2019.1.1 and Firefox 66.0.3?

**Comment by Brian1Gaff** [comment] 2019-05-07 07:53
I'm on a later version of Firefox and all seems to be well now in the latest 
versions etc.
 Obviously its hard to be sure about all conditions.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by Adriani90** [comment] 2019-05-07 08:17
Thanks Brian for replying. Closing as works for me. If you are still encountering this problem, please comment on this issue and we can reopen it.

**Closed by Adriani90** 2019-05-07 08:17 UTC
Labels: worksforme

**Comment by Brian1Gaff** [comment] 2019-05-08 08:05
I'll keep an eye on it, I think there have been issues with add ons in FF 
for some time on and off and its muddied the waters regarding what nvda is 
doing
 As an aside at the e moment I use waterfox as the default browser here 
since FF is seemingly always changing and each new version can bring 
unexpected oddities.



bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
