### ISSUE TITLE
Core freezes when trying to exit Word 2019 by keyboard shortcut

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#11391] opened 2020-07-16 20:39 UTC
### Steps to reproduce:

1.  Open MS Word 2019 (untested in other versions).
2.  Press enter to create a new text document.
3.  Type some text.
4.  Press Alt+F4 to exit.
5.  Press tab then enter, to select "Don't save".
6.  Repeat steps 1 through 4.
7.  This time press "n" to invoke the "don't save" button.

### Actual behavior:

* At step 5, Word exits normally and the desktop or some other application is voiced.
* At step 7, NVDA freezes for between 10 and 20 seconds, in the middle of which an error sound is heard, and user input is not logged or acted upon.

### Expected behavior:

NVDA acts in step 7, as it does in step 5. Which is to say: it doesn't freeze.

### Log

Here is a log. The real fun starts at "Mark 3"--search for that to skip right to the juicy bit.
"Mark 1" will give you my first entry into Word, and the various normal Wordish NVDA errors and tracebacks that occur there.
"Mark 2" will give you my successful exit from Word in step 5.
[nvda-core-frozen-when-exiting-word.txt](https://github.com/nvaccess/nvda/files/4934038/nvda-core-frozen-when-exiting-word.txt)

#### NVDA:

* alpha-20548,e1f3ba99 installed. No other versions tested.
* Tried with add-ons enabled and disabled. No difference; log is with them enabled.
* Ran Com Reg Fix Tool to no effect.

#### Windows version:

2004 (OS Build 19041.388)

#### Name and version of other software in use when reproducing the issue:

Microsoft Office 2019

**Comment by josephsl** [comment] 2020-07-16 20:52
@MichaelDCurran, I get a feeling that it could be a thread waiting for something that it never shows up, or something is going on with UIA. Thanks.

**Comment by XLTechie** [comment] 2020-07-16 21:13
> 
> @michaelDCurran, I get a feeling that it could be a thread waiting for something that it never shows up, or something is going on with UIA.

No difference when turning on or off various UIA combinations in advanced, for what that's worth.

**Comment by Brian1Gaff** [comment] 2020-07-17 06:16
Actually being really controversial this sort of oddity I can get even on my 
old windows 7 machine and word 2003. It seems pretty random to me, Its 
annoying and sometimes windows will put up, Word is not responding, but will 
eventually exit as if nothing untoward has happened. I thought these events 
might be something to do with the file it was actually editing.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by XLTechie** [comment] 2020-07-17 06:43
I am reasonably sure that is a different issue entirely. Word is responding 
normally. It is NVDA that is not responding here according to the 
perceived effects and the log.

Now, it is possible, I suppose, that Win 10 is giving a "Word is not responding" 
message during the 20 seconds or so that NVDA is silent, but none of the other 
effects of a Word crash seem to be extant, so I doubt it.

Most tellingly, when running Narrator, there is no delay at all upon exiting 
Word via the method described.

**Comment by man0528** [comment] 2020-07-17 12:02
I am using office365, Confirm that this problem exists. The content of the start menu will not be read after closing Word. It also won't read the contents of Explorer. Reopening Word will not read. The version I tested is NVDA2020.2RC1, Office365 Version 2006 (Build 13001.20266).

**Comment by Adriani90** [comment] 2020-07-17 19:47
I cannot reproduce this in NVDA Alpha 20548,e1f3ba99 and

Office 365 MSO (16.0.13001.20266) 32-Bit 

Could you please go to MS Word, then to file ribbon, then to account and check for updates? If there are updates, please install them and try to reproduce the issue again with last NVDA alpha. Please report the results.

**Comment by XLTechie** [comment] 2020-07-17 22:16
Immediately after I updated Word 2019 in this way, the error did not occur.
However after I restarted NVDA with add-ons disabled, it continued to occur.

That is consistent with the behavior I previously observed: about one time out 
of 10, the error does not happen. The rest of the time it does.

**Comment by ruifontes** [comment] 2020-07-17 23:16
Same here!

Windows 10 2004, Microsoft® Word for Microsoft 365 MSO 
(16.0.13001.20338) 64 bits, NVDA 2020.2RC.


Rui Fontes

**Comment by fisher729** [comment] 2020-07-21 12:12
Hi.

So, after conducting a few tests, here are my findings:
1. With UIA in Word disabled and add-ons disabled: Issue replicated
2. With UIA in Word disabled and add-ons enabled: Issue not replicated. However, I cannot seem to pinpoint which specific add-on seems to fix the issue, as I have 32 add-ons installed.
3. With UIA in Word enabled and add-ons disabled: Issue replicated. It gets worse, as the Start menu also seems to not work when this freeze occurs (seems to be separate issue).
4. With UIA enabled and add-ons enabled: Issue not replicated, although the Start menu does not work after Word is exited.

Using Office 16.0.13001.20338, Windows 10 1909 64-bit, NVDA 2020.2rc1

**Comment by Adriani90** [comment] 2020-11-30 11:45
This might be improved by Windows 10 apps essentials. cc: @josephsl

**Comment by Adriani90** [comment] 2020-11-30 11:46
Can anyone still reproduce this issue with addons disabled in NVDA's last alpha?

**Comment by fisher729** [comment] 2020-12-24 13:03
Hi.

With the latest stable 2019.3 release, I can no longer reproduce this bug. I'm using Microsoft Office version 16.0.13426.20332

**Comment by Adriani90** [comment] 2020-12-25 21:50
Closing as works for me. Thanks for the update.

**Closed by Adriani90** 2020-12-25 21:50 UTC
Labels: close/worksforme
