### ISSUE TITLE
Broken phonetic spelling option in NVDA in the last few alpha snapshots

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#10891] opened 2020-03-21 08:39 UTC
### Description:
In NVDA's settings, in the "Speech" category, there is an option called "Use spelling functionality if supported". You all probably know what this option is supposed to do, so I'm not going to bother explaining it.

Before NVDA 2019.3, this option was not working correctly for the most used bulgarian SAPI5 speech synthesizer "SpeechLab" (the voice "Gergana"), so we were disabling it on a new NVDA installation when using that voice. After the speech refactor in NVDA 2019.3 however, the option started working correctly for our voice. And by "correctly" I mean that with it disabled, separately read consonant characters from our cyrillic alphabet were spoken by "SpeechLab" as de vocalized (hope I'm using the most correct term here - it is hard for me to explain it), which is not the default behavior. With the option enabled, the consonants are read normally when read separately. And I think that is how the option should work.

In recent alpha snapshots of NVDA however, this option got broken again for voice "SpeechLab". No matter if the option is enabled or disabled, the synthesizer reads separate consonants as if the option is enabled. I think the option got broken after fixing the issue which prevented NVDA from reading single characters when the Speech Viewer was enabled.

### Steps to reproduce:
1. Add a bulgarian/cyrillic input method in Windows.
2. Install NVDA 2019.3.1.
3. Install the bulgarian SAPI5 speech synthesizer "SpeechLab" (the voice "Gergana").
4. Configure NVDA to use the SAPI5 voice "Gergana".
5. Configure for this voice the option "Use spelling functionality if supported" to be enabled.
6. Open a text editor and type a few consonant characters and observe how the voice "Gergana" pronounces them.
7. Configure for this voice the option "Use spelling functionality if supported" to be disabled.
8. Open a text editor and type a few consonant characters and observe how the voice "Gergana" pronounces them.
9. Notice how there is a difference in the pronunciation with the "Use spelling functionality if supported" option enabled and disabled.
10. Install the latest NVDA alpha snapshot.
11. Repeat steps from 4 to 8.
12. Notice how there is no difference in the pronunciation with the "Use spelling functionality if supported" option enabled and disabled.

### Actual behavior:
With the latest NVDA alpha snapshot, there is no difference in the pronunciation of consonant characters with the "Use spelling functionality if supported" option enabled and disabled.

### Expected behavior:
There should be a difference in the pronunciation of consonant characters with the "Use spelling functionality if supported" option enabled and disabled.

### System configuration
- Operating system: Windows 10 Pro version 1909 (build 18363.720), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-19811,ced1faff, in bulgarian.
- SpeechLab version: 2.0.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The problem started occurring a few alpha snapshots ago. It was working OK in NVDA 2019.3.1.

#### If addons are disabled, is your problem still occurring?
Yes, it is.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, my issue is not related to unregistered components.

**Comment by CyrilleB79** [comment] 2020-03-23 09:28
Cc @feerrenrut, @michaelDCurran 
IMO should be triaged to 2020.1 since this seems to be a 2020.1 regression.
Just reading the issue, I did not test myself.

**Comment by zstanecic** [comment] 2020-03-23 09:36
Comment to Kostadin:
the speech lab synth is not publicly available outside of the bulgarian sources.
Please update the comment accordingly and share the link.
I will install it now and telll how it works

**Comment by zstanecic** [comment] 2020-03-23 09:43
Hi!
This option works, but in an opposite way.
You need to uncheck it now

**Comment by Adriani90** [comment] 2024-07-02 21:58
@k-kolev1985, @zstanecic are you still having this issue in NVDA 2024.3 Beta?

**Comment by k-kolev1985** [comment] 2024-07-03 06:43
@Adriani90 At least according to my testing, the problem seems to be fixed now. I'm running the latest NVDA snapshot (alpha-32721,9eca851a).
I'll leave the ticket opened though, in case @zstanecic wants to comment as well.

**Comment by seanbudd** [comment] 2024-07-03 06:47
Closing unless further information is provided

**Closed by seanbudd** 2024-07-03 06:47 UTC
Labels: component/speech

**Comment by zstanecic** [comment] 2024-07-03 06:52
Hi,
Cannot reproduce anymore. 
Best,
Zvonimir
