### ISSUE TITLE
SVOX Pico tts addon incompatible since last update 2019.1.1, cannot be reinstalled anymore

### ISSUE THREAD

**Issue by JohnnyTiresias** [nvaccess/nvda#9643] opened 2019-05-30 17:12 UTC

**Comment by lukaszgo1** [comment] 2019-05-30 17:36
This is a duplicate of #9289 even though the add-on in question is different the error cause is the same. As SVox is hosted directly on NV Access server it would be nice to update manifest to the new format.

**Comment by Brian1Gaff** [comment] 2019-05-31 08:28
Yes this and the  speech player in Espeak and other synths do not work in 
later snaps. Whether this is just a manifest issue, I'm not sure, certainly 
speech refactoring etc will break them and python3 definitely does.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Brian1Gaff** [comment] 2019-05-31 08:31
You can do this yourself after its installed, but remember if you do push 
the working version of nvda too   far ahead, say 2019.4, it will probably 
really break by then due to work on the nvda core code.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by josephsl** [comment] 2019-05-31 08:36
Hi, have you tried contacting the add-on author about this? I advise doing that first, as the author might not be aware of changes in recent NVDA releases or may have something else to say. Thanks.

**Comment by lukaszgo1** [comment] 2019-05-31 08:41
The add on author is NV Acces, so I believe it is proper place for this discussion.

**Comment by leonardder** [comment] 2019-05-31 08:50
@michaeldcurran: Do you think this add-on can be updated for speec hrefactor at some point?

**Comment by michaelDCurran** [comment] 2019-05-31 09:18
I'm sure it is possible. Not of great priority as only about 0.1% of 
people use it according to our statistics.

**Comment by JohnnyTiresias** [comment] 2019-05-31 12:30
The SVOX Pico add-on had the advantage of being effctively included on the portable version in the usb key. So I could run NVDA with Pico without the precondition of having preinstalled the tts engine on the level of the OS, and Pico has a reasonable quality much better than espeak. 

In contrast the high quality voices offered by Windows 10 itself, are NOT included/integrated in tue portable version, those voices require the preinstallation on OS level by principle, and that's rather contradictory regarding the concept of portability. 

In my view, Pico certainly is not the best tts synthesizer, but the best FREE one. Please make it fully compatible again, i.e. in combination with the coming NVDA versions (adjustments in the source code of the NVDA main app itself may be helpful, too, for a working solution) ! For the benifit for all NVDA users. Many thanks!
Best regards

**Comment by Adriani90** [comment] 2019-05-31 18:36
@michaelDCurran I guess the statistics show a low number of users because the addon as such is not well known to the community. It would be nice to post all addons from NV Access on the official addon website. AS of now I can find the addon only in wiki article "extra voices".
Otherwise, if NV Access is not prioritizing this in the near future, you could officially donate the addons to the community, along with the OCR addon for being maintained by people who are interested.
Is there a source code repo for this addon?

**Comment by michaelDCurran** [comment] 2019-05-31 23:12
No repo as far as I am aware. I think the last time I touched that 
add-on was in 2010 or earlier?


Of course the beauty of open source is anyone can unpack that add-on, 
fix the issue and release a new one. :) Otherwise, NV Access will get 
around to it at some date.

**Comment by Brian1Gaff** [comment] 2019-06-03 19:36
I think the speech player in Espeak will go under soon based as it is on the 
older version of  espeak.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- O

**Comment by Adriani90** [comment] 2020-05-17 12:41
When trying to run this addons from the Wiki article "extra voices", NVDA says file format not supported. There are errors due to incompatible manifest.ini 

```
DEBUG - NVDAHelper.nvdaControllerInternal_installAddonPackageFromPath (14:37:55.104) - Dummy-11 (5404):
Requesting installation of add-on from C:\Users\adria\Downloads\svox-pico-2.0.nvda-addon
WARNING - addonHandler._report_manifest_errors (14:37:55.124) - MainThread (3916):
Error loading manifest:
{'name': True, 'summary': True, 'description': VdtTypeError('the value "[\'Svox Pico is a rather small but human sounding synthesizer that supports English U.S.\', \'English U.K.\', \'Spanish\', \'French\', \'Italian\', \'and German languages.\']" is of the wrong type.'), 'author': True, 'version': True, 'minimumNVDAVersion': True, 'lastTestedNVDAVersion': True, 'url': True, 'docFileName': True}
ERROR - gui.addonGui.installAddon (14:37:55.124) - MainThread (3916):
Error opening addon bundle from C:\Users\adria\Downloads\svox-pico-2.0.nvda-addon
Traceback (most recent call last):
  File "gui\addonGui.pyc", line 480, in installAddon
  File "addonHandler\__init__.pyc", line 582, in __init__
addonHandler.AddonError: Manifest file has errors.
```

**Comment by Adriani90** [comment] 2020-05-17 12:43
@qchristensen, @feerrenrut, if this addon is not maintained at all, then at least it should be removed completely from the article extra voices. There are still people outthere being held to older NVDA versions by incompatible addons. So it would be good at least not to promote incompatible addons at all. Maybe someone of you can clean up abit the extra voices page and update the link there.

**Comment by Adriani90** [comment] 2020-05-17 12:43
I am closing this issue for now due to discontinued maintenance for that addon.

**Closed by Adriani90** 2020-05-17 12:43 UTC

**Comment by feerrenrut** [comment] 2020-06-16 11:15
I think that list would be easier to maintain if we move it into the repo, alongside the user docs.
