### ISSUE TITLE
Creating a keystroke to read a whole row in a table

### ISSUE THREAD

**Issue by KerryFielding** [nvaccess/nvda#6318] opened 2016-08-30 13:28 UTC
Hi.  Is it possible to create a keystroke to enable us to read a whole row at once in a table.  In JFW you can use alt+win+up or down arrows to read next and previous rows.  This would be incredibly helpful.

**Comment by jcsteh** [comment] 2016-08-30 22:37
Duplicate of #1911.

**Closed by jcsteh** 2016-08-30 22:37 UTC
Labels: duplicate
