### ISSUE TITLE
Unknown braille-characters viewed as ascii

### ISSUE THREAD

**Issue by JordyDew** [nvaccess/nvda#5763] opened 2016-02-19 17:18 UTC

**Comment by JordyDew** [comment] 2016-02-19 17:23
Unknown braillecharacters will be viewed as ascii-characters (e.g. '\x200e' ). Solving this will be effect that I'll use NVDA a
 
lot more! The problem described here is the only one that I have with NVDA

**Comment by josephsl** [comment] 2016-02-19 17:35
Hi, hmmm, no comment? But based on recent users list discussion, I can tell what the poster had in mind: This is LibLouis doing it (unless NVDA is involved somehow). Thanks.

**Comment by josephsl** [comment] 2016-02-19 17:50
Hi, actually, they are hexadecimal numbers. Solving them will require defining what the dot combinations are for these characters (I believe this is a duplicate of a ticket somewhere). Thanks.

**Comment by JordyDew** [comment] 2016-02-19 20:34
Hello,

The symbol I named is normally no dot-defenition. There can be used 0 dots as defenition for this character.

I’m volontier to translate some characters to braille, if I can find a list of unknown (not definded yet) characters. Can you send me one, or can I cind one on the web?

Thanks in advance!

Kind regards,

Jordy Deweer

 

Vriendelijke groeten

Jordy Deweer.

 

Tel. +32(0)497/40.70.01

E-mail: jordydeweer@hotmail.com

 

Van: josephsl [mailto:notifications@github.com] 
Verzonden: vrijdag 19 februari 2016 18:51
Aan: nvaccess/nvda <nvda@noreply.github.com>
CC: JordyDew <jordydeweer@hotmail.com>
Onderwerp: Re: [nvda] Unknown braille-characters viewed as ascii (#5763)

 

Hi, actually, they are hexadecimal numbers. Solving them will require defining what the dot combinations are for these characters (I believe this is a duplicate of a ticket somewhere). Thanks.

**Comment by josephsl** [comment] 2016-02-19 20:37
Hi, for which language is this? Remember that each language may assign different dot combinations for these characters, hence I’m reluctant to accept this kind of files (it is better to ask on the LibLouis list). Thanks.

**Comment by JordyDew** [comment] 2016-02-19 20:54
Hi, this is for German Computerbraille 8dots

 

Vriendelijke groeten

Jordy Deweer.

 

Tel. +32(0)497/40.70.01

E-mail: jordydeweer@hotmail.com

 

Van: josephsl [mailto:notifications@github.com] 
Verzonden: vrijdag 19 februari 2016 21:38
Aan: nvaccess/nvda <nvda@noreply.github.com>
CC: JordyDew <jordydeweer@hotmail.com>
Onderwerp: Re: [nvda] Unknown braille-characters viewed as ascii (#5763)

 

Hi, for which language is this? Remember that each language may assign different dot combinations for these characters, hence I’m reluctant to accept this kind of files (it is better to ask on the LibLouis list). Thanks.

**Comment by josephsl** [comment] 2016-02-19 21:06
Hi, yes, this is something that needs to be fixed from LibLouis end (@jcsteh, is that right?). Thanks.

**Comment by jcsteh** [comment] 2016-02-22 03:05
Duplicate of #2949.

**Closed by jcsteh** 2016-02-22 03:05 UTC
Labels: duplicate
