### ISSUE TITLE
NVDA Speech viewer is showing the title of a dialogue but it is not announcing it

### ISSUE THREAD

**Issue by NitinPem** [nvaccess/nvda#13557] opened 2022-03-29 14:20 UTC
I have a a weird situation. NDVA speech viewer is showing a dialogue title. But it is not being announced by NVDA
Have anyone ever come across this situation? Please refer to attached. The highlighted part is showing in the NVDA speech viewer but not being announced by NVDA. It only announces 'Create' then it jumps to Reason combo Box.

I have a feeling that this may be a bug within NVDA
![2022-03-28 21_14_51-Window](https://user-images.githubusercontent.com/102540782/160629729-061a3fde-badf-49bf-852e-1a8ef35b2eb5.png)
.

**Comment by seanbudd** [comment] 2022-03-30 03:59
Closing as duplicate of #13558

**Closed by seanbudd** 2022-03-30 03:59 UTC
