### ISSUE TITLE
NVDA is very slow when two or more configuration profiles are created

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#7923] opened 2018-01-21 15:18 UTC
### Steps to reproduce:
1. Create a new profile in NVDA menu under configuration profiles
2. Change some settings in one of the two profiles
3. Let one profile being triggered only for a specific application (i.e. Outlook)

### Expected behavior:
NVDA should work as fast as in standard configuration where only one profile exists.

### Actual behavior:
NVDA becomes very slow, especially when changing tthe active window to the application where the new profile is bein triggered.

### System configuration:
NVDA version:
2017.4

NVDA Installed or portable:
Both

Other information:

Windows version:
Windows 10.0.16299 Build 16.299.64

Name and version of other software in use when reproducing the issue:
Different applications

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
No

**Comment by feerrenrut** [comment] 2018-01-22 04:55
I haven't been able to reproduce this. Could you reproduce this issue with debug logging enabled and attach the NVDA log to this issue? The log has timing information in it that will help to see where the slow down occurs. At debug level the log also includes the configuration details, which will help to highlight configuration options that may be slow to enable.

**Comment by Adriani90** [comment] 2018-01-22 22:34
@feerrenrut, I have found out that the sluggness occurs only when changing the window and while NVDA is triggering the corresponding profile.

 

For example do following:

1.	Open Outlook and create a configuration profile in NVDA for Outlook.
2.	For Outlook profile, change voice rate to a much higher value than usual
3.	Change to Desktop by pressing Windows m
4.	Change back to Outlook by pressing Alt+Tab.

 

You will notice that NVDA does nor react until it triggered the profile. And in my case this takes some seconds. I don’t see any information on that in the log file with debugging activated.

 

Any other suggestions?

 

Tank you very much in advance.

 

Von: Reef Turner [mailto:notifications@github.com] 
Gesendet: Montag, 22. Januar 2018 05:56
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA is very slow when two or more configuration profiles are created (#7923)

 

I haven't been able to reproduce this. Could you reproduce this issue with debug logging enabled and attach the NVDA log to this issue? The log has timing information in it that will help to see where the slow down occurs. At debug level the log also includes the configuration details, which will help to highlight configuration options that may be slow to enable.

**Comment by michaelDCurran** [comment] 2018-01-22 22:43
What synthesizer are you using? If this is Windows onecore, it is 
possible there is a long delay while it  reloads the voice. I'm not sure 
if we check to see if the synth actually needs to change or not.

**Comment by Adriani90** [comment] 2018-01-22 23:06
I have tried it with the eloquence and vocalizer addon from code factory and with eSpeak. Both show the same effect.

 

Thanks for your reply.

 

 

Von: Michael Curran [mailto:notifications@github.com] 
Gesendet: Montag, 22. Januar 2018 23:43
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [nvaccess/nvda] NVDA is very slow when two or more configuration profiles are created (#7923)

 

What synthesizer are you using? If this is Windows onecore, it is 
possible there is a long delay while it  reloads the voice. I'm not sure 
if we check to see if the synth actually needs to change or not.

**Comment by feerrenrut** [comment] 2018-01-23 01:18
The log contains a timestamp for each log message, by looking at the differences in timestamps we can determine approximately what NVDA was doing when the slowdown occured.

**Comment by Adriani90** [comment] 2018-01-23 11:29
Hello, I have to do some more testings. I have tried it now on Windows 8.1 and the issue does not occur. I will post the log file for Windows 10 soon. Maybe it is related to my Laptop but I have a kabylake I7 2.8 ghz. I have cleaned registry and so on.

**Comment by Adriani90** [comment] 2018-01-23 18:54
So, I thought it could be related to my sound card which goes in standby after 5 seconds of silence. But this is not the case. Here are two log files: one with an additional profile for MS word and one only with the standard profile.
[nvda with additional settings profile for MS word, speech rate for word changed.log](https://github.com/nvaccess/nvda/files/1657210/nvda.with.additional.settings.profile.for.MS.word.speech.rate.for.word.changed.log)
[nvda without extra profile.log](https://github.com/nvaccess/nvda/files/1657211/nvda.without.extra.profile.log)

**Comment by Adriani90** [comment] 2018-01-30 19:54
Can someone reproduce this issue on Windows 10? Otherwise I think it can be closed. Unfortunately I have only one windows 10 machine where I can test it.

**Comment by zstanecic** [comment] 2018-01-30 20:05
I don’t have any problems.
You can close it.


Wysłane z aplikacji Poczta dla Windows 10

Od: Adriani90
Wysłano: wtorek, 30 stycznia 2018 20:54
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] NVDA is very slow when two or more configurationprofiles are created (#7923)

Can someone reproduce this issue on Windows 10? Otherwise I think it can be closed. Unfortunately I have only one windows 10 machine where I can test it.

**Comment by ehollig** [comment] 2018-01-31 01:07
Closing as suggested in https://github.com/nvaccess/nvda/issues/7923#issuecomment-361714306 and unable to reproduce the issue. If this still is an issue, we can reopen it.

**Closed by ehollig** 2018-01-31 01:07 UTC
