### ISSUE TITLE
Unable to locate texts in .pdf files using microsoft hedge

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7933] opened 2018-01-22 16:38 UTC
### Steps to reproduce:
Open a .pdf file in microsoft hedge.
I tested 2 files and the problem was the same.
As an example you can open the attached .pdf file.
With the file open press ctrl + nvda + f to locate.
Type a text as an example in the attachment file you can enter storage.
Press enter to locate.

### Expected behavior:
The nvda should find the searched text and should focus on the word found and allow to navigate the text from the localized word.

### Actual behavior:
Nvda informs that the text was not found, even if the text is present in the body of the localized pdf.

### System configuration:
NVDA version:
> Example: next-14799

NVDA Installed or portable:
instaled
Other information:
this problem did not occur when locating texts in open internet pages in microsoft hedge.
Windows version:
> Example: Windows 10 Version 1709 16299.192 64bits
Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result

no
[cs-cern-na-143-0812-pt.pdf](https://github.com/nvaccess/nvda/files/1652759/cs-cern-na-143-0812-pt.pdf)

**Comment by feerrenrut** [comment] 2018-01-22 23:07
I get the same behaviour with the provided PDF, and also with a PDF in English.

**Comment by Adriani90** [comment] 2020-05-07 19:42
Works as expected in Edge Chroumium 81. Closing as works for me and addint appropriate label since it could still be reproducible with the old edge spartan.
However, with Windows 10 2004 update the edge chromium will be distributed to most users.

**Closed by Adriani90** 2020-05-07 19:42 UTC
Labels: app/edge, app/edge/spartan, close/worksforme, feature
