### ISSUE TITLE
In Chrome and FireFox wrong info spoken when navigating by heading

### ISSUE THREAD

**Issue by henkabma** [nvaccess/nvda#6666] opened 2016-12-22 18:58 UTC
The following behavior can be observed with the latest Chrome and FireFox browsers:
1. Open https://kunstencadeau.org/
2. Navigate using H key until you reach "Steigerhouten groeimeter" and press h once more.
3. result: "Steigerhouten dienblad" followed by the description of the "steigerhouten groeimeter".
4. press shift+h 
5. result: "steigerhouten groeimeter" with the description of "steigerhouten dienblad".

Notes: 
- the braille display shows only "steigerhouten dienblad" or "steigerhouten groeimeter" with no extra unexpected information, so Braille is correct.
- Chrome version used: 55.0.2883.87 m
- The issue does not show on Internet Explore 11.

**Comment by jcsteh** [comment] 2016-12-23 03:17
I'm testing in Firefox and I can't reproduce this. I should first note that this page renders differently for me (and in fact, it seems it is rendering differently to the way it was yesterday). In order, I now see: Steigerhouten Groeimeter, Tas, salontafel, Steigerhouten dienblad. That said, I never hear the description of the previous entry when I move forward by heading.

Can you please provide a log capturing this issue with the log level set to input/output? See [Log Files and Crash Dumps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for details on how to do that.

**Comment by henkabma** [comment] 2016-12-23 20:19
Please find attached an example of the described behavior using Chrome.
[kunstencadeau-nvda-chrome.txt](https://github.com/nvaccess/nvda/files/671405/kunstencadeau-nvda-chrome.txt)

**Comment by ehollig** [comment] 2017-09-12 23:24
@henkabma, is this still an issue? I am not able to reproduce the described behavior in the original post. It appears that the link provided may have changed.

**Comment by ehollig** [comment] 2018-10-26 00:41
Unfortunately, @jcsteh and I am not able to reproduce this issue. Furthermore, it appears the site has changed, as I am not able to find the text, "Steigerhouten" on the page. In addition, we have not heard from the original author in over a year and a half. Closing as invalid.

**Closed by ehollig** 2018-10-26 00:41 UTC
