### ISSUE TITLE
Nvda read the time in skype messages

### ISSUE THREAD

**Issue by IoanMan** [nvaccess/nvda#7487] opened 2017-08-11 08:14 UTC
Hello. I want to signal a problem that is quite disturbing. When I write a message or receive a message on skype, Nvda reads me the date and time that this message was sent or received. Although we disabled this skype setting, nvda continues to read this. Is there any solution to this problem? Would be interesting, I know there is an addon for nvda that more or less makes it easier to use it with skype. Maybe the solution would be right there. Thanks in advance to developers and those who might be directly involved in solving this problem.## Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by josephsl** [comment] 2017-08-11 08:18
Hi, I’ll assume this is Skype desktop 7.x? Thanks.

**Comment by florianionascu7** [comment] 2017-08-11 08:33
Hello, I really confirm the issue raported by Ioan here. I hope it'll be fixed soon.

**Comment by leonardder** [comment] 2017-08-11 08:38
Closing as duplicate of #5648

**Closed by leonardder** 2017-08-11 08:38 UTC
Labels: needsExternalFix

**Comment by IoanMan** [comment] 2017-08-11 09:00
Microsoft isn't very responsive. I wrote an report about skype on the ios about the problems with new interface. And the response was this problems resolving with the next update. Sorry for the inconvenience.
