### ISSUE TITLE
Multi enter press to navigate mui select component

### ISSUE THREAD

**Issue by rhodh** [nvaccess/nvda#14062] opened 2022-08-24 15:41 UTC
### Steps to reproduce:
Created a minimum app to reproduce the error. Clone the following app https://github.com/amdigital-co-uk/reproduce-nvda-mui-select-issue. 

Requirements: 
- node 16.10.0

Setup the app using 

```cmd  
npm i
```

Start using app using

```cmd
npm run start
```

While NVDA is running.

Tab on the select component on screen and press enter to open menu.

### Actual behavior:
Unable to navigate the menu with the up and down arrows - you must first press enter before being able to navigate the menu.

### Expected behavior:
When the menu has been opened you should be able to navigate said menu with the up and down arrows.

Expected behavior occurs when NVDA is not running.

### NVDA logs, crash dumps and other attachments:
N/A

#### NVDA installed/portable/running from source:
NVDA install on windows
#### NVDA version:
2022.2.1
#### Windows version:
Windows 11 Business 21H2
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Reproduced on 2021.3.5 
#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons installed 
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2022-08-25 00:32
We are unable to process this issue as it stands.

- To be able to reproduce this issue, we need a minimal code sample. Provide a minimal HTML sample to reproduce this using [codepen](https://codepen.io/).

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2022-08-25 05:20
Closing as blocked, we will reopen this when a sample is provided

**Comment by rhodh** [comment] 2022-08-25 16:12
Hi @seanbudd here's a codepen sample https://codepen.io/aleoy/pen/rNdgyyQ, there's also a the repo you can clone for a local version of the issue.

**Comment by Adriani90** [comment] 2024-01-31 10:47
This issue is not reproducible with NVDA 2024.1 Beta and last Chromium browser versions. In the local app it is not reproducible as well.
You are using browse mode when navigating to the menu button, so when you press enter a menu list appears. To navigate it with arrow keys, you have to switch to focus mode with nvda key+space bar.
Alternatively you can enable automatically switch to focus mode when focus changes in NVDA browse mode settings.
Closing as works for me.

**Closed by Adriani90** 2024-01-31 10:47 UTC
Labels: close/worksforme, needs-triage
