### ISSUE TITLE
NVDA repeats the last spoken text (two times ago) when tabbing html if an application is inbetween

### ISSUE THREAD

**Issue by onzag** [nvaccess/nvda#15795] opened 2023-11-17 00:10 UTC
### Steps to reproduce:

https://jsfiddle.net/Lnvmzjar

content of the fiddle in case it goes down

```
<p tabindex="0">
  hello
</p>
<div role="application" aria-label="app" tabindex="0">
  APP
</div>
<p tabindex="0">
  world
</p>
```

Start tabbing start, from hello.

it should say "Hello" "app" "World"

Tested with Firefox and Google Chrome, equal results.

### Actual behavior:
NVDA says "Hello", "app", "Hello World" it repeats whatever was the last spoken element so as long as there was an "application" inbetween.

If you shift+tab and then tab it will simply say "World World", equally if you start from Hello, and then tab, and then shift tab, it will say "Hello Hello", it simply repeats whatever was focused before the application was in focus.

Applications existing alongside bits of content are very common in forms of interactive content, that's how I spot the issue to begin with, where there was an application sandwiched in-between label text, but the application just took keystrokes, so it was similar to this small case scenario; the fiddle is just a small recreation of what actually occurs in a production system.

VoiceOver on ios and Orca on linux read correctly, which leds me to believe the issue is NVDA specific, unless it's windows?...

### Expected behavior:
NVDA should say "Hello" "app" "World"

### NVDA logs, crash dumps and other attachments:
No crashes

#### NVDA version:
2023.3

#### Windows version:
Windows 10

**Comment by Brian1Gaff** [comment] 2023-11-17 10:01
Have you looked through the issues? This sounds very familiar to me, from a very long time ago. Somebody needs to see what jaws does in this context.
 
I don't think its windows version specific, as it does it on 7. Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: Onza 
  To: nvaccess/nvda 
  Cc: Subscribed 
  Sent: Friday, November 17, 2023 12:10 AM
  Subject: [nvaccess/nvda] NVDA repeats the last spoken text (two times ago) when tabbing html if an application is inbetween (Issue #15795)



  Steps to reproduce:
  https://jsfiddle.net/Lnvmzjar

  content of the fiddle in case it goes down

<p tabindex="0">
  hello
</p>
<div role="application" aria-label="app" tabindex="0">
  APP
</div>
<p tabindex="0">
  world
</p>
Start tabbing start, from hello.

  it should say "Hello" "app" "World"

  Tested with Firefox and Google Chrome, equal results.

  Actual behavior:
  NVDA says "Hello", "app", "Hello World" it repeats whatever was the last spoken element so as long as there was an "application" inbetween.

  If you shift+tab and then tab it will simply say "World World", equally if you start from Hello, and then tab, and then shift tab, it will say "Hello Hello", it simply repeats whatever was focused before the application was in focus.

  Applications existing alongside bits of content are very common in forms of interactive content, that's how I spot the issue to begin with, where there was an application sandwiched in-between label text, but the application just took keystrokes, so it was similar to this small case scenario; the fiddle is just a small recreation of what actually occurs in a production system.

  VoiceOver on ios and Orca on linux read correctly, which leds me to believe the issue is NVDA specific, unless it's windows?...

  Expected behavior:
  NVDA should say "Hello" "app" "World"

  NVDA logs, crash dumps and other attachments:
  No crashes

  NVDA version:
  2023.3

  Windows version:
  Windows 10

**Comment by onzag** [comment] 2023-11-17 12:00
I couldn't check Jaws, because it's not available in my country and I'd need a VPN and just wasn't worth the Hassle, VoiceOver and Orca I did check and they just read it as expected.

I searched through the issues and I did not find anything, maybe they worded it differently.

**Comment by Adriani90** [comment] 2024-11-19 17:51
Closing as invalid. As per
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

you should avoid using tabindex on non interactive elements because these are not listed in the accessibility tree and so the screen reader cannot handle them properly. Closing as invalid.

**Closed by Adriani90** 2024-11-19 17:51 UTC
Labels: close/invalid, p4, bug/double-speaking, triaged, needs-technical-investigation
