### ISSUE TITLE
Passwords spoken in WSL

### ISSUE THREAD

**Issue by SaschaCowley** [nvaccess/nvda#11554] opened 2020-09-04 04:55 UTC
### Steps to reproduce:

1. If not already enabled and installed, enable WSL, and install and setup a distro (I am using Ubuntu 20.04 on WSL2, but I observed this issue on WSL1).
2. Make sure "Speak typed characters" is enabled in NVDA.
3. Within the WSL distro, try to do something that requires a password (EG run a command via `sudo`).

### Actual behavior:

The password is spoken by NVDA, even though it is not displayed on screen.

### Expected behavior:

The password should not be spoken, or, a masking symbol (such as "*") should be spoken instead.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.2

#### Windows version:

Microsoft Windows [Version 10.0.19041.450]

#### Name and version of other software in use when reproducing the issue:

Windows Subsystem for Linux with Ubuntu 20.04.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I believe this issue occurs in prior versions of NVDA, but am going from memory.

#### If addons are disabled, is your problem still occurring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes. Same result before and after.

**Comment by josephsl** [comment] 2020-09-04 05:05
Hi, I can’t reproduce this on the same exact configuration as you described, although I’m using NVDA alpha build to test this. Can you check if UIA is used to access consoles (NVDA menu/Preferences/Settings/Advanced)? Thanks.

**Comment by XLTechie** [comment] 2020-09-04 05:24
Try: NVDA+n, p, s, a, tab, space, Alt+P.

That will take you to the "Speak passwords in UIA consoles (may improve 
performance)" option of the Advanced settings panel.

Uncheck that (space), then press enter.

Is your problem resolved?

**Comment by akash07k** [comment] 2020-09-04 05:57
Yes, it works when we enable the UIA checkbox.

However, when we are into SSH session, then NVDA responds very, very 
slowly. Although this is altogether a new issue.

**Comment by SaschaCowley** [comment] 2020-09-04 06:51
> Can you check if UIA is used to access consoles (NVDA menu/Preferences/Settings/Advanced)?

UIA was not being used. Enabling it fixed the issue.

**Comment by Brian1Gaff** [comment] 2020-09-04 09:47
UIA slugs everything in many command settings, and so perhaps its  a 
Microsoft issue?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by codeofdusk** [comment] 2020-10-12 06:22
By default, on Windows 10 version 1607 and later, NVDA currently speaks all characters typed in consoles, whether they appear onscreen or not. Technical: I disabled typed character queuing/dispatch on `textChange` in `EnhancedTermTypedCharSupport` on legacy console since it takes about 250 ms to detect text changes (severely slowing down speaking of typed characters).

Your options:

* Use UIA console. @carlos-zamora and I have been doing a lot of work to improve the experience in the console for the next version of Windows.
    * Use [Windows Terminal](https://github.com/microsoft/terminal). Terminal has a good UIA implementation (which is always used, regardless of the user setting).
    * Test the new 21H1 UIA console. You can test the new console separately, or replace your existing console with the new version. See #10618.
    * Install an insider build of Windows 10. The inbox console on insider dev builds has many of the latest accessibility fixes, and should have all of them by the end of November or so.
    * Alternatively, wait for the next version of Windows (21H1) in the first half of 2021.
* Disable "use the new typed character support in legacy Windows Console" in NVDA advanced settings. This will suppress passwords, but re-introduce #513.
* When typing passwords in untrusted environments, disable "speak typed characters" and "speak typed words".

**Comment by codeofdusk** [comment] 2020-10-12 06:23
I think this issue should probably be closed (if not now, then definitely when #10964 is merged).

**Closed** 2022-06-21 10:42 UTC
