### ISSUE TITLE
aria-valuetext for progress bar is not working with NVDA(2015.2) in form mode in IE

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5282] opened 2015-08-11 07:22 UTC
**Reported by tapan.basak on 2015-08-11 07:22**
The issue is coming when you navigate in '''form mode''' using only arrow keys(up/down). '''Form mode''' can be enabled by pressing 'CAPS LOCK + TAB' keys after opening NVDA. When '''form mode''' is enabled, NVDA is not reading the aria-valuetext property of progress bar instead it is reading the aria-valuenow property.

**Comment by leonardder** [comment] 2017-07-22 14:44
Closing as duplicate of #913. Also related to #6561

**Closed by leonardder** 2017-07-22 14:44 UTC
Labels: bug
