### ISSUE TITLE
Chrome 97: navigation/echo issue with some edit combo boxes

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#13217] opened 2022-01-06 05:54 UTC
### Steps to reproduce:
1. With Chrome 97, go to google.com. Make sure you are actually opening a new tab or bringing up Chrome 97 for the first time instead of switching to Google.com via Control+Tab.
2. Locate the Search edit combo box with the letter E and press Enter to activate Focus mode.
3. Type a few letters.
4. Press Left/Right or press Insert+Tab.
### Actual behavior:
NVDA doesn't echo the typed characters with Left/Right or, upon pressing Insert+Tab, says: "unknown defunct." If you move away and to this tab or use ALT+Tab to move away and to it, the issue will be resolved. Moreover, if you go to bing.com and type in its edit combo box with Chrome 97, NVDA echoes each typed letter twice not once.
### Expected behavior:
NVDA should echo each letter as we press Left/Right, and Insert+Tab shouldn't say "unknown defunct."
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha 24399
#### Windows version:
Win 11, Version 21H2 (OS Build 22000.376)
#### Name and version of other software in use when reproducing the issue:
Google Chrome 97
#### Other information about your system:
These can't be duplicated with MS Edge which, at the time of this writing, is at V96.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Haven't tried

**Comment by amirsol81** [comment] 2022-01-06 05:59
Just a revision: the echo issue where NVDA strangely echoes each typed character twice can also be duplicated with MS Edge 96 on bing.com.

**Comment by amirsol81** [comment] 2022-01-06 06:18
I just noticed that the Left/Right issue with google.com also affects deleting characters with Backspace: NVDA doesn't echo the deleted character when Backspace is pressed.

**Comment by amirsol81** [comment] 2022-01-06 06:25
Another website exhibiting this issue is https://www.merriam-webster.com
Start typing into its Edit box, type at least 3 characters until you hear something like "XXX results are available." At that point, press Left/Right or try deleting with Backspace, or reading with Insert+Tab -- you'll hear "unknown defunct."

**Comment by feerrenrut** [comment] 2022-01-07 03:23
Could you please attach an NVDA (debug level) log after reproducing this issue.

I'm not able to reproduce the issue from the instructions given, a log may help me to see what I'm doing differently.

**Comment by amirsol81** [comment] 2022-01-07 11:03
MS Edge was just updated to V97, and it also suffers from the very same issue. So the bug seems to be related to Chromium as JAWS is also affected.

**Comment by OzancanKaratas** [comment] 2022-01-07 13:55
@feerrenrut, is it enough?

IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 305, in _getLineOffsets
  File "comtypes\__init__.pyc", line 851, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'Parametre hatalı.', (None, None, None, 0, None))

**Comment by codeofdusk** [comment] 2022-01-10 09:13
Also seeing this in M98 for the past few weeks.

**Comment by DraganRatkovich** [comment] 2022-01-11 04:41
@feerrenrut #13223 It contains full log

**Comment by XLTechie** [comment] 2022-03-01 01:38
Maybe this should be re-titled as a Chromium issue? It's happening in various versions of Chrome, Brave, and Edge. Obviously not just a Chrome 97 issue.

**Comment by Adriani90** [comment] 2022-03-01 13:35
cc: @ObjectInSpace, @aleventhal

**Comment by feerrenrut** [comment] 2022-03-02 06:01
Can you please test with Chrome version 100 (or later) and confirm if the behavior is resolved?

**Comment by feerrenrut** [comment] 2022-03-02 09:59
In that case I'll close this issue. Please comment if I have misunderstood.

**Closed by feerrenrut** 2022-03-02 09:59 UTC
Labels: app/chrome

**Comment by DraganRatkovich** [comment] 2022-03-02 10:04
@feerrenrut Sure, you can close.
