### ISSUE TITLE
google schrome crashes when selecting a list item

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#9419] opened 2019-03-29 15:12 UTC
### Steps to reproduce:
1. open schrome and go to:
https://sites.google.com/site/secretariapiloto188cvv/diarioplantao
2. fill the e-mail and tab to the button called "próximo" and activate it.
3. when the next page loads, press tab and you will be placed in a list. press some arrowdown and press spacebar to select an item.
In this moment, schrome will crash.
   
### Actual behavior:
schrome crashes when I press the spacebar to select an item
### Expected behavior:
Select the item
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2019.1
#### Windows version:
windows10 64 bits
#### Name and version of other software in use when reproducing the issue:
schrome last version
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
in version 2018.4.1 it worked fine
[nvda error log.log](https://github.com/nvaccess/nvda/files/3023229/nvda.error.log.log)
[nvda error log.log](https://github.com/nvaccess/nvda/files/3023234/nvda.error.log.log)

**Comment by lukaszgo1** [comment] 2019-03-29 18:49
Looks like another duplicate of #9364. @Adriani90 what do you think?

**Comment by Adriani90** [comment] 2019-03-29 18:49
Closing as duplicate of #9364. Thanks for reporting.

**Closed by Adriani90** 2019-03-29 18:49 UTC
Labels: Chrome, appCrash, duplicate
