### ISSUE TITLE
outlook 2007 crashes frequently.

### ISSUE THREAD

**Issue by stickbear2015** [nvaccess/nvda#6014] opened 2016-05-29 02:01 UTC
Using outlook 2007, the following conditions cause outlook itself to frequently crash.
Switching folders, opening e-mails, and closing e-mails.

using latest public release of NVDA, this also happens on the release candidate.

**Comment by jcsteh** [comment] 2016-06-24 00:33
Duplicate of #3308.

**Closed by jcsteh** 2016-06-24 00:33 UTC
Labels: duplicate
