### ISSUE TITLE
Object location tones

### ISSUE THREAD

**Issue by Goldcreditcard** [nvaccess/nvda#10390] opened 2019-10-16 06:24 UTC
Hi! This feature request is not related to any problems. I'm always imagining about NVDA having a lot of new features and this is just one of the many ideas I have made. It is about the "Play audio coordinates when mouse moves" in mouse settings in NVDA. My idea is, there is an add-on which uses that audio and it's called Object location tones. It will play tones to indicate where the object is located on the screen while you're navigating. It will be helpful and also awesome if the add-on's functions will become a part of NVDA! If the feature will be included, please put a new setting under the general category of NVDA settings to enable/disable this feature. Thanks! :)
[Object location tones.zip](https://github.com/nvaccess/nvda/files/3732699/Object.location.tones.zip)

**Comment by leonardder** [comment] 2019-10-16 06:30
Thanks for your suggestion. There's a pull request for this, see #8457. I'm closing this as duplicate of #2559

**Closed by leonardder** 2019-10-16 06:30 UTC
