### ISSUE TITLE
The portable copy creation dialogue lacks a dynamic progress bar

### ISSUE THREAD

**Issue by Piciok** [nvaccess/nvda#8552] opened 2018-07-24 10:47 UTC
### Steps to reproduce:
1. Go to Tools >> Create a Portable Copy;
2. Follow the wizard until the creation process starts;

### Actual behavior:
As the copy is being created there is no dynamic progress bar present indicating the progress of the task. I can't check what the visual representation is but in the beeps mode the beep is constant and in the Speech mode no values are reported.

### Expected behavior:
A progress bar should indicate how much of the copy is created already.

#### NVDA Installed/portable/running from source:
installed

#### NVDA version:
2018.2.1

#### Windows version:
Windows 10

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, present in older releases as well

**Comment by Brian1Gaff** [comment] 2018-07-24 13:16
This I think was done for a reason. I can recall it could not be made to 
work any other way so it merely bleeps till the process is finished.
 Brian

bglists

**Comment by ehollig** [comment] 2018-07-28 01:20
Duplicate of #2313

**Closed by ehollig** 2018-07-28 01:20 UTC
