### ISSUE TITLE
When entering a table in Libre, a freeze occurs

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6720] opened 2017-01-11 19:45 UTC
While implementing table nav support in Libre, I came across this. What more needs done to fix this freeze? There's a two second pause and then this debug Warning.

IO - speech.speak (12:42:58):
Speaking [u'dddd']
IO - inputCore.InputManager.executeGesture (12:42:58):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (12:43:00):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speak (12:43:00):
Speaking [u' table  with 5 rows and 3 columns ', u'row 1  column 1']

I'll need to eliminate this freeze, or users won't be happy.

**Comment by derekriemer** [comment] 2017-01-11 19:46
Change ..txt to .odt

**Comment by derekriemer** [comment] 2017-01-11 19:48
[testTableFreeze.odt.txt](https://github.com/nvaccess/nvda/files/699885/testTableFreeze.odt.txt)

**Comment by jcsteh** [comment] 2017-01-12 06:43
* What version were you testing with? I don't see a freeze here with an old version (5.0.3.2). I do see other weird behaviour though like the caret being reported incorrectly.
* Does this happen with all tables, just this one or is there some pattern?
* I don't have any specific thoughts as to where this is occurring, so you'd need to stick some logging in various places to figure it out. I'd guess it's some call to Libre which is taking a while, perhaps one of the table calls.

**Comment by ehollig** [comment] 2018-04-08 22:09
@derekriemer, is this still the case or still relevant to you? If it is still happening, can you answer the questions in https://github.com/nvaccess/nvda/issues/6720#issuecomment-272089012

**Comment by Adriani90** [comment] 2018-12-11 11:34
@derekriemer can you still reproduce this issue? Maybe @Qchristensen can also help reproducing it?

**Comment by Qchristensen** [comment] 2018-12-11 23:13
Using LibreOffice 6.1.3.2 x64 (the latest version as of 12/12/2018), and NVDA 2018.4rc1 (installed), I still get warnings in the log, but it doesn't seem to impact performance.  In a blank document, I left two blank lines then inserted a 2x2 table.  Here is my debug level log down arrowing into the table:

IO - inputCore.InputManager.executeGesture (10:05:50.786):
Input: kb(desktop):downArrow
IO - speech.speak (10:05:50.825):
Speaking [LangChangeCommand (u'en_AU'), u'blank']
IO - inputCore.InputManager.executeGesture (10:05:51.762):
Input: kb(desktop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (10:05:51.887):
accRole failed: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:51.908):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speak (10:05:51.918):
Speaking [LangChangeCommand (u'en_AU'), u' table  with 2 rows and 2 columns ', u'row 1  column 1']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (10:05:51.937):
accRole failed: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:51.944):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:52.538):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:05:52.749):
COM pointer <POINTER(IAccessible) ptr=0x63ec8d4 at 75cd9e0> already deleted
DEBUGWARNING - comtypesMonkeyPatches.newCpbDel (10:05:52.868):
COM pointer <POINTER(IAccessible2) ptr=0x70a6e4 at 75cd5d0> already deleted
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:52.898):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:52.913):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (10:05:52.969):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))

I get one extra unspecified error on the down arrows in 2018.3.2 (portable) but otherwise, the log is the same.

**Comment by Adriani90** [comment] 2019-03-30 17:59
Ok can anyone confirm that NVDA freezes in Libre when dealing with tables? How big is the user impact?

**Comment by Adriani90** [comment] 2019-04-05 15:12
I am closing this as works for me, see Quentin's comment above. Thanks and sorry for missunderstanding the comment. :-)

**Closed by Adriani90** 2019-04-05 15:12 UTC
Labels: freeze, libreoffice, worksforme
