### ISSUE TITLE
wxAssertionError while opening some NVDA dialogs

### ISSUE THREAD

**Issue by tspivey** [nvaccess/nvda#8121] opened 2018-03-24 21:50 UTC
### Steps to reproduce:
1. Open Firefox.
2. Press ctrl+NVDA+f.
Alternatively, try opening the Review cursor settings dialog.

### Expected behavior:
The dialog opens

### Actual behavior:
I hear the error sound

### System configuration:
NVDA version: next-14952,dd1cbe50

NVDA Installed or portable: installed

Other information:
Restarting NVDA fixes it for a while. Tracebacks below.

Windows version: Windows 10 Version 1709 (OS Build 16299.309)

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?
No, because restarting NVDA fixes it.

Have you tried any other versions of NVDA?
No

Entries from the log. One from opening find, the other from opening review cursor settings.
```
ERROR - scriptHandler.executeScript (14:24:49.002):
error executing script: <bound method Gecko_ia2.script_find of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x086D27B0>> with gesture u'ctrl+NVDA+f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "cursorManager.pyc", line 162, in script_find
  File "cursorManager.pyc", line 49, in __init__
wxAssertionError: C++ assertion "id == wxID_ANY || (id >= 0 && id < 32767) || (id >= wxID_AUTO_LOWEST && id <= wxID_AUTO_HIGHEST)" failed at ..\..\src\common\wincmn.cpp(372) in wxWindowBase::CreateBase(): invalid id value
ERROR - unhandled exception (14:27:05.150):
Traceback (most recent call last):
  File "gui\__init__.pyc", line 250, in onReviewCursorCommand
  File "gui\__init__.pyc", line 187, in _popupSettingsDialog
  File "gui\settingsDialogs.pyc", line 82, in __init__
  File "gui\settingsDialogs.pyc", line 808, in makeSettings
wxAssertionError: C++ assertion "id == wxID_ANY || (id >= 0 && id < 32767) || (id >= wxID_AUTO_LOWEST && id <= wxID_AUTO_HIGHEST)" failed at ..\..\src\common\wincmn.cpp(372) in wxWindowBase::CreateBase(): invalid id value
```

**Comment by leonardder** [comment] 2018-03-26 14:15
I've seen this only once, so I thought it was just an incident. However, given I've also got a report from @bramd, this seems to be a serious blocker for #7104.

**Comment by bramd** [comment] 2018-03-26 14:21
I can reproduce this right now in Firefox Nightly and have seen it before in Chrome as well. I don't know when it exactly starts happening, but as described in the issue a restart of NVDA fixes this and after some use the problem pops up again.

**Comment by josephsl** [comment] 2018-03-26 14:56
#7104. Looks like it is time for me to test Nightly to find out why…

**Comment by leonardder** [comment] 2018-03-26 15:09
I've also reproduced this in Firefox 60 beta. I don't think it has 
anything to do with a specific Firefox version.

**Comment by leonardder** [comment] 2018-03-29 13:08
The cause of this (WX Python 4 #7104) has been reverted from next. Therefore I'm closing this issue. New WX Python 4 try builds should have a fix for this issue. If not, please post your findings in #7104.

**Closed by leonardder** 2018-03-29 13:08 UTC
