### ISSUE TITLE
IAccessible2 fails in Windows Store apps such as Spotify

### ISSUE THREAD

**Issue by jcsteh** [nvaccess/nvda#7648] opened 2017-10-08 23:25 UTC
### Steps to reproduce:
1. Install Spotify Music from the Windows Store.
2. Launch spotify. The login screen appears.
3. Tab to the Username field and type some text.
4. Use the left arrow key to review the text you just typed.

### Expected behavior:
The characters you typed should be spoken.

### Actual behavior:
Nothing is spoken.

### System configuration:
NVDA version:
next-14486,b39b2bcd

NVDA Installed or portable:
installed

Windows version:
Windows 10 Version 1703 (OS Build 15063.632)

Name and version of other software in use when reproducing the issue:
Spotify (Windows Store app) version 1.0.64.403

### Other questions:
Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
2017.3

### Additional info:
Spotify is a Store app which uses the desktop bridge. It uses Chromium; the window class name is "Chrome_WidgetWin_0". The desktop version of the app does work as expected.

This probably occurs because the IAccessible2 proxy is not registered for Store apps. (It's possible we'd hit other roadblocks even if this were fixed; I'm not sure.)

NVDA explicitly avoids registering it because of #5417. From https://github.com/nvaccess/nvda/issues/5417#issuecomment-155343964:

> When setting up a new inprocThreadMgr thread, the thread waits on a mutex to guarentee that only one of these threads runs at any given time. However, the application's UI thread (where the initial injection winevent came from) waits until this mgr thread is initialized. But, if an old thmgrThread is currently terminating, that old mgrThread at some stage tries to send a window message to the UI thread (specifically to terminate IAccessible2 support). Therefore we end up in a deadlock. This also causes UIAHasServersideProvider (called from NVDA itself) to block.
> The main reason why we see this deadlock so frequently in the searchUI is because the searchUI process is suspended when it is not on screen. However, Windows does not bother unloading DLLs or breaking rpc connections while suspended. Therefore, if the process suspends, you then switch copies of NVDA, once the process resumes, rpc breaks, a winEvent is fired which injects the new nvdaHelperRemote, it waits on the old mgr thread to terminate... deadlock.
> The tempoary fix will be to not enable IAccessible2 support at all for suspendable (modern app) processes.
> Eventually we will want to rewrite nvdaHelperRemote to not deadlock.

Note that in the case of Spotify, the workaround is to use the desktop app instead.

**Comment by feerrenrut** [comment] 2017-10-18 07:01
Thanks @jcsteh, I'll give this a P3 for now since a work around is available.

**Comment by Adriani90** [comment] 2019-04-30 22:58
This is still reproducible in NVDA 2019.1.1.

**Comment by MarcoZehe** [comment] 2019-05-01 04:42
Probably solved in 19H1 due to Narrator now supporting Chrome and Electron apps via the IA2-to-UIA bridge.

**Comment by Adriani90** [comment] 2019-12-20 17:13
Solved in Spotify 1.1.22.633.g1bab253a (Microsoft Store-Version), Windows 10 1909 Update and NVDA 2019.3 Beta 1.
Closing as works for me.

**Closed by Adriani90** 2019-12-20 17:13 UTC
Labels: bug, p3, worksforme
