### ISSUE TITLE
Use UI Automation to access Equation editor in Word by default

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#17475] opened 2024-12-03 01:24 UTC
### Is your feature request related to a problem? Please describe.

The equation editor in Word currently only reads correctly when NVDA's advanced option "Use UI Automation to access Microsoft Word controls" is set to "Always".  Setting this option to "Always" currently changes some other behaviours in Word which may not be ideal for everyone.

### Describe the solution you'd like

Use UIA to access the Equation Editor by default so that users do not need to change this control to have access to the equation editor.

### Describe alternatives you've considered

None of the math add-ons provide full functionality in the equation editor without this option being set.

Currently users need to go into NVDA's advanced options to set this manually.  Which is daunting for some users, and also has other impacts users may not realise.

**Comment by seanbudd** [comment] 2024-12-09 23:16
Closing as can't reproduce with the default setting.
For the case "only necessary", this cannot be fixed.

**Closed by seanbudd** 2024-12-09 23:16 UTC
Labels: p2, component/UIA-ms-office, triaged
