### ISSUE TITLE
NVDA doesn't click on Focused link in internet explorer

### ISSUE THREAD

**Issue by Dennisl123** [nvaccess/nvda#6807] opened 2017-01-25 22:35 UTC
Hi, when doing this hearch I press heading to get to the search results try to click on the first link nothing happens it works with firefox.
[https://www.startpage.com/do/search](https://www.startpage.com/do/search)

**Comment by Qchristensen** [comment] 2017-01-27 00:51
I just tried this and can't activate links in this search engine in Internet Explorer on Windows 10 either with NVDA or Narrator.  As indicated, it works in Firefox.  Possibly they've used an unusual way to do links?  I could in some cases press the applications key and choose open / open in a new window and it would.  Google worked fine and also other pages like nvaccess.org.

**Comment by feerrenrut** [comment] 2017-01-31 10:49
P2 to investigate the problem. Enter seems to work without NVDA running in IE 11 but not with NVDA running.

**Comment by Adriani90** [comment] 2019-03-30 19:02
I am testing with NVDA 2019.1 in IE11 on Starpage. It works as expected. Note that startpage has undercome several changes in the design since the initial author reported this issue. Closing as works for me. If someone can reproduce this though, we can reopen it.

**Closed by Adriani90** 2019-03-30 19:02 UTC
Labels: p2, worksforme
