### ISSUE TITLE
NVDA freezes in SVN commit dialog

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#9619] opened 2019-05-25 11:49 UTC
### Steps to reproduce:
Assuming you are placed on a folder you checked out with SVN,
1. Run svn commit from the explorer context menu
2. Type something in the log text editor.
3. Delete the text
### Actual behavior:
NVDA freezes when deleting the last remaining character in the edit field
### Expected behavior:
NVDA works as usual.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
With the latest snapshot running portably, it works as expected. I don't know why my installed 2019.1.1 copy  does it.

**Comment by dnz3d4c** [comment] 2019-05-27 06:26
I hope this problem will be resolved soon. #8641 has been verified to be reproducible in the latest NVDA stable version.

**Comment by leonardder** [comment] 2019-05-27 06:29
I think this should be fixed in latest Alpha builds. See #9612.

**Comment by dnz3d4c** [comment] 2019-05-27 08:49
I tested it with the latest alpha build, and I could not reproduce the problem. This issue seems to have been fixed.

> 
> 
> I think this should be fixed in latest Alpha builds. See #9612.

**Comment by Adriani90** [comment] 2019-05-27 09:39
Closing as works for me. Please comment on it if you are still having it in future Releases of NVDA (i.e. 2019.2).

**Closed** 2019-05-27 09:39 UTC
