### ISSUE TITLE
starting with windows 10 14393 when opening Microsoft account validation settings window a few sikund closes. This does not happen to have customize without nvda.

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#6872] opened 2017-02-11 13:57 UTC
hi starting with windows 10 14393 when opening Microsoft account validation settings window a few sikund closes. This does not happen to have customize without nvda.

**Comment by mhussaincov** [comment] 2017-02-11 14:06
hi,
I can confirm this when nvda is closed down and windows narrator is
used the page will stay open.
in other words when narrator is running not nvda, and you relaunch the
verification page via the settings app, it will open.
same with the windows store I think.
i'm running nvda via it's next branch.
Majid Hussain

On 11/02/2017, nikita <notifications@github.com> wrote:
> hi starting with windows 10 14393 when opening Microsoft account validation
> settings window a few sikund closes. This does not happen to have customize
> without nvda.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6872


-- 
kind regards,
Majid Hussain

**Comment by gdata1** [comment] 2017-02-11 15:24
I tested it on all versions of nvda after windows 10 14393.

**Comment by derekriemer** [comment] 2017-02-12 06:17
Closing as a duplicate of #6311. Note that this was fixed in the build of windows coming out later this year.

**Closed by derekriemer** 2017-02-12 06:17 UTC
