### ISSUE TITLE
Table with multiple headers in a row only announces one of them

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#7731] opened 2017-11-06 13:16 UTC
I think I remember that NVDA in earlier versions announced all table headers of a row, not only one.

It seems this has changed! Take a look at the following table and browse the rows: each of them should have 2 `<th>` elements (e.g. "Agrisano" and "AGRIeco"), but only the last one is announced ("AGRIeco").

https://www.priminfo.admin.ch/de/praemien?location_id=56361661329074&insurer=312&plan=telfirst&display=comparison&models%5B%5D=base&models%5B%5D=ham&models%5B%5D=hmo&models%5B%5D=div&yob%5B0%5D=1983&franchise%5B0%5D=1000&coverage%5B0%5D=0&yob%5B1%5D=1980&franchise%5B1%5D=1500&coverage%5B1%5D=1&selectInsured=1

Is this a regression?

**Comment by feerrenrut** [comment] 2017-11-07 06:12
Thanks for raising this question, it sounds like it could be a regression. However, as it stands there is not enough information provided on this issue to investigate further. Please could you fill in the issue template, and provide a minimal testcase. If you could try some previous releases to report the last version that had the behaviour you expect that would also be excellent.

**Comment by Adriani90** [comment] 2019-05-01 08:29
This is not an issue in NVDA 2019.1.1, Firefox 66.0.3 and Chrome 74 anymore.
Closing as works for me.

**Closed by Adriani90** 2019-05-01 08:29 UTC
Labels: worksforme
