### ISSUE TITLE
Linebreaking using BrowseMode Find

### ISSUE THREAD

**Issue by dan1982code** [nvaccess/nvda#7344] opened 2017-06-30 13:41 UTC
Search (ctrl+NVDA+F) for the word math in this page in Firefox:
https://emu-docs.org/Super%20NES/General/snesdoc.html

It will be strangely found, but it's finding it across a linebreak with MA on one line and Th on the next.

**Comment by bhavyashah** [comment] 2017-08-06 11:42
Confirmed using NVDA version 2017.2 and Firefox 54.0.1. The sample URL and STR provided by @dan1982code were quite easy to follow. Apart from Firefox however, it is worth noting that this issue can be replicated in Chrome (and probably all other browsers) also.

**Comment by derekriemer** [comment] 2017-08-14 14:48
very simple test case of this.
`data:text/html,<p>The dcma</p><p>thinks the internet should b sensored.</p>`
This is caused when a paragraph ends adjacent to another paragraph. Fix: have virtual buffers put either a space or a lf at the end of a paragraph mark.

**Comment by derekriemer** [comment] 2017-08-14 14:49
This can probably be replicated in any browser using a buffer, probably not edge.

**Comment by Adriani90** [comment] 2020-06-25 19:59
This link does not reproduce the issue, the word math cannot be found there. Please open a new issue with an updated source and steps to reproduce. I am closing this one for now since investigation is not possible with this example.

**Closed by Adriani90** 2020-06-25 19:59 UTC
Labels: goodForNewDev
