### ISSUE TITLE
Wav samples don't work with wasapi. Only start.wav and exit.wav work.

### ISSUE THREAD

**Issue by Lo-lo78** [nvaccess/nvda#14906] opened 2023-05-05 10:48 UTC
Hi everyone!
I'm trying the NVDA version: alpha-28179,345154a6 and I noticed that the default waves with wasapi don't work.
Only the ones already mentioned work.
Greetings!

**Comment by beqabeqa473** [comment] 2023-05-05 11:21
Please fill the template.

Do you have this problem without addons running

On 5/5/23, Lo-lo78 ***@***.***> wrote:
> Hi everyone!
> I'm trying the NVDA version: alpha-28179,345154a6 and I noticed that the
> default waves with wasapi don't work.
> Only the ones already mentioned work.
> Greetings!
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/14906
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by zstanecic** [comment] 2023-05-05 11:21
I cannot confirm this. Error sound works too. And focus mode along with browse mode.

 

From: Lo-lo78 ***@***.***> 
Sent: Friday, May 5, 2023 12:49 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Wav samples don't work with wasapi. Only start.wav and exit.wav work. (Issue #14906)

 

Hi everyone!
I'm trying the NVDA version: alpha-28179,345154a6 and I noticed that the default waves with wasapi don't work.
Only the ones already mentioned work.
Greetings!

**Comment by Adriani90** [comment] 2023-05-05 15:47
This is very likely due to an add-on installed in your NVDA. Please contact the add-on author to fix the issue. I am closing this as works for me, I cannot reproduce this issue either.

**Closed by Adriani90** 2023-05-05 15:47 UTC
Labels: close/worksforme

**Comment by Lo-lo78** [comment] 2023-05-05 20:36
Yes, it's an add-on. I still don't know what it is but it is correct.
I restarted NVDA without the add-ons and it works fine.
Thank you

**Comment by XLTechie** [comment] 2023-05-06 03:55
It's probably a sound related one.

Likely Sound Splitter, Tony's Enhancements, or NVDA Global Extension.
