### ISSUE TITLE
Can not Activate Korean grade2/grade2(2006) Braille Table in NVDA 2019.1

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#9486] opened 2019-04-15 04:58 UTC
### Steps to reproduce:
1. Enabling the Braille Panel in the NVDA Settings dialog
2. Changed braille output to Korean grade 2 (2016) or Korean grade 2.
### Actual behavior:
Korean table not activate
### Expected behavior:
Korean table must be active.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2019.1
#### Windows version:
Windows10 version 1809(Language set Korean)
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not reproduced in alpha version.

**Comment by dnz3d4c** [comment] 2019-04-15 05:45
@josephsl I think this problem has a big effect on users who use Korean braille tables. Can you investigate further to resolve the issue?

**Comment by josephsl** [comment] 2019-04-15 06:05
Hi, I have rice, but no soy sauce in front of me – log please. Thanks.

**Comment by dnz3d4c** [comment] 2019-04-15 07:18
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "appModules\explorer.pyo", line 301, in event_gainFocus
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 967, in event_gainFocus
  File "braille.pyo", line 1832, in handleGainFocus
  File "braille.pyo", line 1837, in _doNewObject
  File "braille.pyo", line 1515, in getFocusRegions
  File "braille.pyo", line 614, in update
  File "braille.pyo", line 427, in update
  File "louisHelper.pyo", line 65, in translate
  File "louis\__init__.pyo", line 183, in translate
WindowsError: exception: access violation reading 0x0000012F

**Comment by josephsl** [comment] 2019-04-15 07:24
Hi, cannot reproduce this in 2019.1 on my computer. What about restarting with add-ons turned off? Thanks.

**Comment by Brian1Gaff** [comment] 2019-04-15 08:25
He did say a portable version could it be a permissions issue for a portable 
copy?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by dnz3d4c** [comment] 2019-04-15 08:29
The same issue occurs after you disable add-ons.
I tried to activate the Korean braille table after connecting the smartbittle braille display, but I can not activate it. Colleagues using other Braille displays have also experienced this problem.

**Comment by dnz3d4c** [comment] 2019-04-15 08:52
I additionally confirmed that it is not possible to activate only the Korean grade2, Korean grade (2006) version tables. For grade 1 tables, there is no problem. 
I have updated the content of the issue.

**Comment by josephsl** [comment] 2019-04-15 16:04
Hi, I believe the Korean grade 2 tables are the only ones affected? If yes, then this is a table issue. If not, then we need to figure out what happened with Liblouis 3.8. Thanks.

**Comment by dnz3d4c** [comment] 2019-05-07 02:06
I think this is an issue in Liblouis, and I can not reproduce the issue in 2019.2, so I will close this issue.

**Comment by dnz3d4c** [comment] 2019-06-20 09:09
Korean users have reported an issue that the Korean braille table is not activated in 2019.2 beta version. I will keep it open until the issue is resolved.

**Comment by josephsl** [comment] 2019-06-20 17:08
Hi,

Traced to optimized Liblouis.dll:

1. No errors if beta branch is compiled with optimizations off (default).
2. Errors are seen (specifically memory access violation) if optimization is on (scons source release=1).

This may mean other tables could be affected, so I advise raising an issue on Liblouis repo. Please tell my friends in Korea that this will require discussing the problem with Liblouis developers.

Thanks.

**Comment by josephsl** [comment] 2019-07-30 04:26
Hi,

Resolved in 2019.2 RC1, but won't close properly until stable version comes out.

Thanks.

**Comment by dnz3d4c** [comment] 2019-07-30 08:51
Thank you. Once the stable version is released, I will close this issue.
> 
> 
> Hi,
> 
> Resolved in 2019.2 RC1, but won't close properly until stable version comes out.
> 
> Thanks.

**Closed** 2019-08-15 03:18 UTC
