### ISSUE TITLE
Feature request - default form mode for web pages, Win Store App, etc.

### ISSUE THREAD

**Issue by TomVal** [nvaccess/nvda#5949] opened 2016-05-14 20:08 UTC
ALthough my eyes aren't good at all, I can still use my computer visually. I'd like to have NVDA started in background and use it when needed. But when I enter a web page, Windows Store app and other such things, NVDA switches to browsing mode, which gets in my way of controlling my PC visually and using standard keyboard shortcuts or webpage single-key kommands. It would be nice to be able to set a checkbox for entering form mode instead of browsing mode whenever appropriate.

**Comment by leonardder** [comment] 2017-12-16 14:48
Even though I wouldn't use this myself, I can see reasons why one prefers having browse mode disabled by default, at least when starting the browser. Probably not high priority at all, though.

**Comment by feerrenrut** [comment] 2017-12-20 03:57
From the use case, this makes sense as something we would try to support. It is probably something that needs to be explored, I imagine there are several features of NVDA that get in the way for people with this use case.

**Comment by Adriani90** [comment] 2019-02-19 20:04
Will be solved in #8846. cc: @leonardder I am closing this as duplicate of #8716.

**Closed by Adriani90** 2019-02-19 20:04 UTC
Labels: duplicate, feature
