### ISSUE TITLE
Rename "Speech" settings page to "Voice" for a logical connection to the V in the NVDA+control+v shortcut

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11204] opened 2020-05-26 04:56 UTC
### Is your feature request related to a problem? Please describe.

The shortcut key to get directly to NVDA's speech settings page is NVDA+control+v.

### Describe the solution you'd like

It is preferable to have shortcut keys use the first letter of the setting they are associated with (NVDA+control+k gets to keyboard settings, NVDA+control+d opens document settings, etc).

I propose renaming the "Speech" settings page to "Voice" settings, which brings it back in line with its shortcut of NVDA+control+v.

### Describe alternatives you've considered

Changing the shortcut key is the other potential change here.  That is problematic both because people are likely familiar with the existing shortcut, and also NVDA+control+s is already the shortcut key to get directly to NVDA's synthesizer dialog.

**Comment by feerrenrut** [comment] 2020-05-26 08:28
The problem is that "voice" is at odds with the general output concepts we use. Mostly throughout NVDA and docs we refer to braille and speech. Another option, is to use NVDA+control+s to open the speech panel, and the Synth Chooser dialog can become NVDA+control+shift+s or NVDA+control+alt+s. This way wall of the "settings panel" shortcuts are can become NVDA+control+first letter and since the synth chooser is also accessible from the speech settings panel it is like the "alt" version of the shortcut.

**Comment by CyrilleB79** [comment] 2020-05-26 10:32
At first thought, I would not recommand to rename "Speech settings" to "Voice settings". For now "speech" and "voice" seem two different contects that are clearly dinstinct in NVDA: "speech" is the way NVDA renders information via TTS output, whereas "voice" is an attribute of the TTS. Moreover, renaming "speech" to "voice" in this case would have a high impact in documentation, code and translations.

If the use case of this issue is considered useful, I would prrefer from far to change the shortcut of the speech panel.

At last, we should also remember that changing the shortcut would benefit only to people having NVDA UI in English or another language where Speech is translated to a word that starts with a "S" (German ?). I do not know of any language in NVDA translation having changed this type of gesture, even if it is doable.

**Comment by DrSooom** [comment] 2020-05-27 13:42
As those are called "Text-to-Speech" and "Speech output" and not "Text-to-Voice" and "Voice output" I strongly recommend not to change the category name in the NVDA Settings from "Speech" to "Voice". If you wanna change the hotkeys for opening the Speech and Braille NVDA Settings dialog and their Selecting/Choosing windows, then please open a new issue for this. Thanks.

**Comment by Adriani90** [comment] 2020-06-01 10:35
Regarding shortcut change, this could be discussed in another issue if required. I am also not in favor of changing the cathegory name to voice, because then we would have to create a new cathegory for synthesizer sellection.
Given the comments above, I am closing this request for now. But please comment on it if you have other justifications for implementing this and we can reopen the discussion afterwards.

**Closed by Adriani90** 2020-06-01 10:35 UTC
