### ISSUE TITLE
NVDA not reading tabs in Instantbird

### ISSUE THREAD

**Issue by tapper82** [nvaccess/nvda#13430] opened 2022-03-04 23:03 UTC
### Steps to reproduce:
Open Instantbird and try to read the tabs or the windows title.
### Actual behavior:
You just get the pings for a error. 
### Expected behavior:
It should read the windows title and the name of the chats that are the tabs you have open.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA Version: alpha-24876,2325be89
#### Windows version:
Windows 11
#### Name and version of other software in use when reproducing the issue:
Instantbird 1.5
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Here is a bit from my log. 

ERROR - eventHandler.executeEvent (23:02:18.998) - MainThread (784):
error executing event: gainFocus on <NVDAObjects.Dynamic_DocumentMozillaIAccessible object at 0x06CDBD10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 279, in executeEvent
  File "eventHandler.pyc", line 327, in doPreGainFocus
  File "browseMode.pyc", line 1321, in event_treeInterceptor_gainFocus
  File "speech\speech.pyc", line 558, in speakObject
  File "speech\speech.pyc", line 601, in getObjectSpeech
  File "speech\speech.pyc", line 433, in getObjectPropertiesSpeech
  File "NVDAObjects\IAccessible\mozilla.pyc", line 82, in hasDetails
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1554, in _get_detailsRelations
  File "NVDAObjects\IAccessible\__init__.pyc", line 1497, in _getIA2TargetsForRelationsOfType
  File "comtypes\__init__.pyc", line 1152, in QueryInterface
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467262, 'No such interface supported', (None, None, None, 0, None))

**Comment by ABuffEr** [comment] 2022-03-05 11:23
Hi @tapper82 ,
try to run COM utility from NVDA tools menu. But consider that Instantbird is an abandoned software (from 2013 or so), build over a very old graphical system of Mozilla products. So, if you have a strong necessity to use it and solve this problem, I suggest you to close this issue and ask in community for an add-on or similar that acts as workaround.

**Comment by lukaszgo1** [comment] 2022-03-05 12:10
Given that Instantbird is Gecko based this is almost certainly caused by #13399 cc @feerrenrut  
A similar problem has been reported on the users list fol older version of Thunderbird.

**Comment by tapper82** [comment] 2022-03-05 14:49
Hi I do know that Instantbird  is old. I would like to use something newer. I just use Instantbird for IRC does any one know anything that is as simple to use for IRC with NVDA?

**Comment by feerrenrut** [comment] 2022-03-11 09:02
@tapper82  Could you please test with this [try-build](https://ci.appveyor.com/api/buildjobs/qxi2p6nuywxc6gav/artifacts/output%2Fnvda_snapshot_try-fixFirefoxDetails-24931%2C43598547.exe ) of #13456

**Comment by tapper82** [comment] 2022-03-11 20:26
Hi thanks for the test build. 

I installed and all seems to be fine. Instantbird now works. I all so tested with the latest firefox and Thunderbird Daily just to make shure that nothing broke.
We have a fix thanks again.

**Comment by tapper82** [comment] 2022-03-12 04:34
Hi I rebooted and am getting this when I open Firefox 100.
error executing event: gainFocus on <NVDAObjects.IAccessible.mozilla.Mozilla object at 0x07BF5270> with extra args of {}
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1477, in _get__IA2Relations
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\__init__.pyc", line 1152, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1052, in reportFocus
  File "speech\speech.pyc", line 558, in speakObject
  File "speech\speech.pyc", line 601, in getObjectSpeech
  File "speech\speech.pyc", line 433, in getObjectPropertiesSpeech
  File "NVDAObjects\IAccessible\mozilla.pyc", line 81, in hasDetails
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1568, in _get_detailsRelations
  File "NVDAObjects\IAccessible\__init__.pyc", line 1550, in _getIA2RelationFirstTarget
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1479, in _get__IA2Relations
NotImplementedError


Firefox is working as it should I just wanted you to know about what it is saying in the logs.

**Comment by feerrenrut** [comment] 2022-03-12 05:12
Thanks for letting me know. I'll take another look at this on Monday.

**Comment by feerrenrut** [comment] 2022-03-14 07:51
Please could you test with the following [try build](https://ci.appveyor.com/api/buildjobs/o382y7t5bcxuc62m/artifacts/output%2Fnvda_snapshot_try-fixFirefoxDetails-24947%2C74ab929d.exe)

**Comment by tapper82** [comment] 2022-03-14 10:20
@feerrenrut Yes this fixes it thanks.

**Comment by CyrilleB79** [comment] 2022-03-15 09:00
Please change milestone to 2022.1 instead of 2022.2.

**Closed** 2022-03-17 06:30 UTC
