### ISSUE TITLE
[Edge Browser] Can't execute space/enter keyEvent on buttons when NVDA is on

### ISSUE THREAD

**Issue by kitty7756** [nvaccess/nvda#8173] opened 2018-04-12 21:48 UTC
I'm currently working on a web project that needs to be accessible in Edge. I have a toolbar which is `<ul>` that contains `<li>` elements, and inside each list element there is a `<button>`. When NVDA is on, space/enter keyEvents on buttons are not triggering when button elements are focused.

I found out about browse mode/focus mode. If I manually switch to focus mode, the buttons work as expected. However, I also noticed that NVDA is able to automatically switch between browse mode and focus mode. So my assumption would be that when the buttons are focused, NVDA automatically switches to focus mode from browse mode, but this isn't the case for me. 

 Another thing I found out is, some of the buttons do work as expected; even when I move them into the toolbar and put them as list elements. What could be causing this issue??

And I have no problem when I'm on Chrome. 

### System configuration:
NVDA version:
2018.1.1

NVDA Installed or portable:
Installed on Windows

Windows version:
Windows 10, Latest Microsoft Edge

**Comment by PratikP1** [comment] 2018-04-13 12:26
@kitty7756 Do you have any way to provide us with sample code affected in this manner? There could be multiple issues which can contribute to this problem. While you may not be able to provide a live example, it would be helpful if you could provide a HTML file with the CSS and JS you're using.

**Comment by feerrenrut** [comment] 2018-04-17 06:54
@kitty7756 Thanks for taking the time to report this, as it stands it's quite hard to confirm whether this is expected behaviour. Ideally you could provide an example, and instructions to demonstrate the behaviour that you are seeing. Another thing you could do to help is to test this in Firefox or Chrome and report any differences in behaviour. Some of this sounds like expected (and configurable) behaviour, but without specific steps to reproduce and an example it's hard to say for sure. If you haven't already done so, please read the [user guide](https://www.nvaccess.org/files/nvda/documentation/userGuide.html) and consider the [Basic training material for NVDA](https://www.nvaccess.org/product/basic-training-for-nvda-ebook/)

**Comment by MarcoZehe** [comment] 2018-05-10 12:33
I just recently saw something similar in the [Pinafore](https://pinafore.social) web app, an alternative web app for the Mastodon federated social network. There, toggle buttons cannot be toggled from within virtual mode using the space key (or enter). In Firefox, Chrome, and IE, this works as expected, even without NVDA having to enable focus mode. So the expectation, IMO, is totally valid that this should work from within browse mode in Edge, too.

**Comment by ruchirkemnaik** [comment] 2020-01-17 15:04
It seems like this issue has started occurring in Chrome and Firefox too where Enter and Space key events on a button are consumed by NVDA in the browse mode. Here is a quick example on codepen: https://codepen.io/ruchirkemnaik/pen/MWYqzxM

Turn on NVDA, click on the input field and press "Tab" to move the focus onto the button. Now try pressing Enter/Space. Notice that nothing is logged in the console when you press Enter/Space in the browse mode. However, if you change NVDA to focus mode, you can see statements logged in the console.

**Comment by Adriani90** [comment] 2020-04-22 17:29
I can reproduce with the example provided by @ruchirkemnaik using every browser with NVDA Version: alpha-20026,16ec967e.

**Comment by Adriani90** [comment] 2023-09-07 21:23
In browse mode this is expected behavior, because NVDA simulates mouse clicks instead of using the keydown definitions due to the inconsistent support of keypresses for many elements in the web. See #11143 for more details. I am closing this issue as works for me since in focus mode it works correctly.

**Closed by Adriani90** 2023-09-07 21:23 UTC
Labels: close/worksforme, app/chrome, app/firefox, app/edge/anaheim
