### ISSUE TITLE
Update NSIS to latest stable version

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#11127] opened 2020-05-07 18:36 UTC
### Is your feature request related to a problem? Please describe.

During instalation of NVDA there is shown a text string called "Please wait, while setup is loading"; which is a part of NSIS, which is used by NVDA as instaler system. NVDA uses version according to its readme 2.51, where this string was not translated to Slovenian. in3.x stable this string and others have been translated, so NVDA would probably "talk" completely in slovenian.

### Describe the solution you'd like

As I wrote, I suggest to update NSIS to latest stable if it would not raised other problems.

### Describe alternatives you've considered

Manually update problematic string or leave as it is.

### Additional context

This could have another plus, because as I know, it supports unicode.

thanks.

**Comment by leonardder** [comment] 2020-05-08 06:29
Closing as duplicate of #9134

**Closed by leonardder** 2020-05-08 06:29 UTC
