### ISSUE TITLE
Unable to assign people or labels in GitHub issue tracker

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#7698] opened 2017-10-26 00:54 UTC
### Steps to reproduce:
1. Open an issue in the GitHub issue tracker.
2. Press a to assign someone to the issue or l to apply a label.
3. Try using the arrow keys to make a selection or alternatively try typing the exact value and pressing Enter.

### Expected behavior:
The selected value should be spoken by NVDA when using the arrow keys, or according to GitHub support entering the exact value and pressing Enter should assign the person or add the label.

### Actual behavior:
Nothing is spoken by NVDA and it appears to be impossible to assign people or apply labels to issues in GitHub.

I have tried with both Chrome and Firefox with no success.

**Comment by ehollig** [comment] 2017-10-26 02:10
The [Greasemonkey scripts to improve the accessibility of various websites by NvAccess](https://github.com/nvaccess/axSGrease) should help with assigning labels. Specifically, the [GitHub Accessibility Fixes](https://github.com/nvaccess/axSGrease/raw/master/GitHubA11yFixes.user.js). Leaving this open in case these edit fields are found in the wild and could be improved internally.

**Comment by leonardder** [comment] 2017-10-26 05:10
What issue tracker are you using for this?

**Comment by mjanusauskas** [comment] 2017-10-27 02:13
The built-in issue tracker in GitHub. Navigate to a GitHub repository and click on the issues tab.

**Comment by leonardder** [comment] 2017-10-27 06:22
Sorry, I should have formulated my question more clearly. I actually meant to ask whether you had a specific repository in mind. Just to make sure, for the NVDA repository, only people with collaborator access have the ability to assign people to issues or apply labels.

**Comment by mjanusauskas** [comment] 2017-10-28 02:52
I am using a private GitHub repository at my workplace for which I have full write access.

**Comment by Adriani90** [comment] 2019-04-30 22:04
I can reproduce this issue with NVDA 2019.1.1, Firefox 66.0.3 and Chrome 74 as follows:
1. Open NVDA
2. Open Github and open a repository
3. Open an issue and make sure you are logged in
4. Switch to focus mode with nvda+space bar
5. Press a
6. Type one or more letters

Actual: NVDA announces the number of results but you can navigate the results only with object navigation
expected: NVDA should allow navigation by results with arrow keys like in the comment edit field.

**Comment by Adriani90** [comment] 2019-12-20 17:08
This isue is not reproducible anymore in NVDA 2019.3 Beta 1, Firefox 71 and Chrome 79. Closing as works for me.

**Closed by Adriani90** 2019-12-20 17:08 UTC
Labels: worksforme
