### ISSUE TITLE
Add an option to enable/disable the mouse movement to the left top corner after the systray got focus

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9462] opened 2019-04-05 09:54 UTC
### Steps to reproduce:
1. Press WIN+B to move the focus to the systray.
2. Press ArrowLeft once.
### Actual behaviour:
Quote from [@DataTriny's comment on issue #9461](https://github.com/nvaccess/nvda/issues/9461#issuecomment-480184474):
> This behavior seems to be here on purpose, here is what I found in the explorer app module:
> if mouseHandler.lastMouseEventTime < time.time() - 0.2:
> […]
> 	winUser.setCursorPos(0, 0)

The mouse cursor will be moved by default to the left top corner of the screen after the focus went into the list of icons in the systray.
### Expected behaviour:
This mouse movement here should be make enable or disabled by the user via a simple checkbox in the Mouse NVDA settings dialog. In some circumstances this solves some other issues regarding activating an icon in the systray. But the default behaviour shouldn't be changed.
#### NVDA installed/portable/running from source:
Only an installed version of NVDA 2018.1 was tested by me.
#### NVDA version:
2018.1
#### Windows version:
Win7 (tested) to Win10-1809 (based on issue #9461)
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA?
Same result with 2019.1 based on the comments in issue #9461.

**Comment by DataTriny** [comment] 2019-04-05 12:24
Hi @DrSooom,

Of course, this would just be a dirty workaround. If the mouse is over a tray icon, it would be impossible to navigate the whole notification toolbar. This behavior can be seen both with Windows Narrator and JAWS.

@michaelDCurran, @jcsteh, @josephsl, @lukaszgo1, @leonardder, @dkager: can the person who added this piece of code explain why moving the mouse over the focused icon is not an option? In which circumstance isn't it possible to move the focus out of another toolbar icon?

(I apologize to the people who are not concerned by this issue, as I haven't been able to trace who exactly wrote these lines.)

**Comment by lukaszgo1** [comment] 2019-04-05 14:46
It was introduced by @jcsteh in 67f792b9f3291101697bb2aeb768fd8ea979365f

**Comment by DrSooom** [comment] 2019-04-07 04:21
I just want to note down, that you are able to change the visibility behaviour of these icons in the systray since Windows 7 (or already since Vista). They will than moved into an expandable area, which can be reached by activating the NotificationChevron button. And if you move the focus to it and within it by pressing ArrowRight or ArrowLeft, the mouse cursor will stay where it was. And furthermore it is possible to change the order of these icons in the systray and in the hidden systray area via Drag&Drop. You can also move these icons between the systray and this hidden area by Drag&Drop. Well, you can also change the visibility of these icons via DropDown lists in a dialog too.

Therefore it might be better to disable this mouse movement by default. If it still causes issues for some users on Win7 and higher, they can enabled it. Note that this mouse movement in the systray was introduced for Windows XP users (see issue #10). And this systray in WinXP sucked.

**Comment by DataTriny** [comment] 2019-04-07 12:57
Hi @DrSooom,

Thank you for suggesting this setting.

Unfortunately, if we decide to stop moving the mouse to the top left of the screen, the problem is still there. I would even say that it is more likely to happen since in my opinion people who don't use the mouse have a better chance to accidentally move it so that it is off-centered, but not on the bottom right of the screen. Like in the normal notification area, if the mouse hovers over one of the icons, if the user try to navigate with the keyboard, the focus will go back under the mouse after one second or so.

Funny thing is that if you manually move the cursor to coordinates 0,0 you wont be able to interact with OneDrive notification tray and the like with Windows Narrator either. That's why I would like to know what is preventing us from moving the mouse over the selected tray icons.

**Comment by DrSooom** [comment] 2019-04-07 13:40
> That's why I would like to know what is preventing us from moving the mouse over the selected tray icons.

An appearing Help Balloon in Windows 7 on moving the mouse cursor on such an icon. It really depends on the application behind such an icon. Sadly there isn't a general answer for all possibilities. Therefore the checkbox for advanced users. They should be able to know the consequences.

**Comment by lukaszgo1** [comment] 2019-04-07 13:42
I am wondering how it is solved in JAWS.

**Comment by DataTriny** [comment] 2019-04-07 14:11
Hi @lukaszgo1,

JAWS 2019.1903 (demo version) behaves exactly like Windows Narrator (at least on my setup: Windows 10 Education version 1809):

- it doesn't move the mouse,

- it can't reliably bring the focus to a tray icon if the mouse is hovering over another one (Windows behavior by the way),

- and OneDrive's tray icon can't be activated if the mouse is sitting on the top-left corner of the screen.

**Comment by DataTriny** [comment] 2019-04-07 14:36
OK, I just found a stupid and dirty solution that seems to cover all our cases.

Instead of moving the mouse to coordinates `x=0, y=0` when a tray icon get focus, simply move it to `x=1, y=0`.

What do you guys think?

**Comment by DrSooom** [comment] 2019-04-08 08:41
@DataTriny: Changing the coordinates from 0×0 to 1×1 Pixel will maybe fix issue #94621, but not this one here. Furthermore we must think about the magnifier users too. Such unexpected mouse movements should be made disabled by them via a checkbox.

Background information: The mouse cursor is in most cases an arrow which head points to the left top corner. From WinXP to Win7 these *.cur files are 32 × 32 pixel tall, but the essential pixel in such cur files for the normal mouse cursor is the one in the top left corner. In the earlier days the default mouse cursor was white with a one pixel think border around the arrow. The rest of the 32 × 32 pixel cur file was fully transparent. Animated mouse cursors have the file ending *.ani.

In other words: If you move the mouse cursor to the top left corner, you can see the whole mouse cursor. If you move it near the bottom of the screen, the lower pixel of the cursor will leave the screen and aren't visible any longer. And it's the same behaviour when you move it to the right side of the screen.

Depending how much the magnifier user can see and how the mouse cursor looks like, it is sometimes quite difficult to find him on the screen without moving it. The easiest way to recognise/find the mouse cursor again, is to move it to the top of the screen.

Therefore it is absolutely unwanted that the mouse cursor moves suddenly just on pressing Win+B followed by ArrowLeft. The magnifier user must find the mouse cursor again. And yes, sometimes it's faster to active icons in the systray via the keyboard and TTS feedback instead of moving the mouse on it. And last but not least this mouse movement could influence the magnifier application in a negative way.

Therefore I ask you to find all mouse movements, such as the one for the systray, in the whole source code of NVDA, because we should make them all disabled via one single checkbox – if possible of course. Otherwise we need more checkboxes.

PS: I created such cur files in the past. And there are keyboards and mouse users out there. And some users aren't able to keep hundreds of hotkeys in mind or to use a keyboard (keyword: [tongue drive system](http://atwiki.assistivetech.net/index.php/Tongue_drive_system)).

**Comment by DataTriny** [comment] 2019-04-08 09:47
Hi again @DrSooom,

Don't worry, I'm one of those magnifier users and I also find quite annoying when an application moves my cursor. I am just trying to find the best answer to the problem.

The checkbox you suggested may be a good idea afterall: let's assume magnifier users won't put their mouse over the system tray, (if they do, well we can't really do that much).

I would be glad to take ownership of this PR.

In which category would you place this checkbox? The "Mouse" one sounds good to me.

**Comment by DataTriny** [comment] 2019-04-08 09:56
- Which text would best convey the meaning of this setting?

- I would enable this mouse movement by default (simply because it seems there are more keyboard only users).

**Comment by lukaszgo1** [comment] 2019-04-08 09:56
What about moving mouse cursor only if it is placed on a system tray icon and otherwise do nothing?

**Comment by DataTriny** [comment] 2019-04-08 09:59
@lukaszgo1 I didn't think about this? Sounds reasonable to me.

**Comment by DrSooom** [comment] 2019-04-08 12:00
@lukaszgo1: I'm not sure, if I understood you correctly. Here is the StR:
1. Press Win+B followed by ArrowRight.
2. Mouse cursor is moved to 0×0.
3. Move it now over another icon in the systray.
4. Press ArrowRight again.
5. Et voilà, the mouse cursor moved again to 0×0.

@DataTriny: We should figure out how many mouse movements are hard-coded in NVDA first. But we can do this later on in a separate issue/PR too.

Then I suggest: "Move the mouse cursor out of the systray when it gets focus". Okay, "systray" might not be the correct wording for it. I guess Notification Area could be the more correct one based on my quick researches. The Mouse category would be the right for it, as I suggested already in the issue description.

And you are right – the actual behaviour shouldn't be changed by default.

**Comment by lukaszgo1** [comment] 2019-04-08 12:09
I haven't tested but I've thought about the following:
1. Move to system tray
2. press an arrow key.
3. Check if the mouse cursor is positioned on a system tray icon and then
3.1 if it is move it to 0.0
3.2 if it isn't do nothing.

**Comment by DataTriny** [comment] 2019-04-08 12:48
@DrSooom:

The steps you give produce exactly the issue we are trying to fix!

If we don't move the mouse, here is what happens:

1. press Win+B followed by arrow right,
2. move mouse cursor on another icon in the system tray,
3. this new icon now get the focus,
4. press right arrow a second time,
5. the icon next to the one focused by the mouse will get focus,
6. after a short amount of time the icon focused by the mouse will get back the focus,
7. you can press right arrow as much as you want, the icon below the mouse will always get back the focus.

I already took a look at all the places where the mouse is moved by NVDA. In most of the cases, it is done to activate an object if we fail to do it programmatically, but the cursor is moved back right after, so I guess that's not an issue.

@lukaszgo1 that's what I had in mind, and I think it is doable.

**Comment by DrSooom** [comment] 2019-04-09 05:11
I have always disabled "Follow mouse cursor" in the NVDA's Review Cursor Settings. Could you do the same and repeat your steps?

**Comment by DataTriny** [comment] 2019-04-09 07:55
Hi @DrSooom,

Whether mouse tracking is enabled or not doesn't matter here since, as I wrote here before, this is a Windows behavior (which means that it occures with NVDA, JAWS, Windows Narrator and even with no running screen reader at all).

At least in Windows 10, as soon as the mouse is hovering on a system tray icon, it get focused and we can't do much about it. That's why we move it out of the notification area in the first place.

**Comment by DrSooom** [comment] 2019-04-09 11:17
@DataTriny: I didn't talk about the mouse tracking (NVDA+M).

But you're right, Windows 7 puts the focus onto the icon behind the mouse cursor, no matter if "Follow mouse cursor" in the NVDA's Review Cursor Settings is enabled or not. And this behaviour exists not only in the always visible area of the systray, it also exists in the expanded, normally hidden area of the systray.

Well, and if you press Win+B first, you'll land on the NotificationChevron button. And if you now expand the systray by pressing Space or Enter and move into it with ArrowLeft, the mouse cursor will stay on its position. Ergo the focus issue isn't solved here by this mouse movement, as it is limited only to the visible area of the systray.

Furthermore I've set the task bar to show small icons, therefore the icons in the systray are located in one single row. If you use "big" icons in the task bar – I'm not talking here about the systray area; press Win+T – or if you changed the height of the task bar, the icons in the systray are located within two or even more rows, which is by the way the case in the expanded systray area. But I don't think that this make any differences here.

PS: As far as I remember me correctly, the start menu button is always located on the very left or on the very top side of the task bar. Therefore moving the mouse cursor to 1×1 shouldn't be a problem, even if the task bar isn't located at the bottom of the screen.

**Comment by DrSooom** [comment] 2019-04-09 15:31
Well, but you have to do the same procedure after Space or Enter was pressed at the NotificationChevron button, as there are two systray areas.

Furthermore I'm asking me if it's better just to move the mouse cursor – let's say – 100 px to left and 100 px up. Of course this only works correctly, if the task bar is located at the bottom or at the right side. But we can fetch the position of the systray. Therefore this shouldn't be a problem any longer. I guess you know, what I mean. If the task bar is on the left side, move the mouse cursor 100 px to right instead of left. And if it is at the top, move it down instead up. That should be possible. Maybe a little bit more complex instead of moving the mouse cursor to 1×1 pixel, but possible in my opinion. That could be better for the magnifier users.

**Comment by DataTriny** [comment] 2019-04-10 13:10
Hi, I don't find moving the mouse a little bit (by say 50px) is a particularely difficult task, plus I agree that it would cause less trouble for magnifier users. Will work on that soon.

**Comment by lukaszgo1** [comment] 2019-09-18 10:35
@DataTriny Are you still planning to work on this?

**Comment by DataTriny** [comment] 2019-09-18 11:57
Hello, yes eventually. But I wont have that much free time until the start of October. So, don't expect anything before this date.

**Comment by Adriani90** [comment] 2020-03-26 22:50
cc: @feerrenrut

**Comment by Adriani90** [comment] 2020-06-18 21:23
This is solved via #11176. The mouse can now be moved manually to the system tray for example with nvda+shift+m in laptop layout. Once the mouse on over the system tray, its position will move to the left corner as it was default behavior previously. But the mouse will not move to system tray when pressind windows+b and then arrow keys.
I am closing as works for me.

**Closed by Adriani90** 2020-06-18 21:23 UTC
Labels: close/worksforme
