### ISSUE TITLE
Report list count in Office 365 Insert icons feature

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10596] opened 2019-12-08 21:49 UTC
### Is your feature request related to a problem? Please describe.

Possibly related to #10595.

In Word 365:
1. In a blank document, press alt+n, n, s to select "Icons" from the Insert ribbon.
2. Press TAB twice to move from the edit, past the categories, to the icon list itself.
3. NVDA reports the movement
4. Press the down arrow twice to move past the first (Accessibility) category, to the first item in the Analytics category.

At step 3 and step 4, NVDA reports a list, but does not report the position within the list.
 
### Describe the solution you'd like

NVDA should report the position within the list.

### Additional context
Windows 10 Version: 
18362.388
 
Office 365 Version: 
16.0.12228.20322

**Comment by francipvb** [comment] 2019-12-12 13:12
Confirmed. The fact is that NVDA does not report the element name for MSHTML elements in some cases.

**Comment by Adriani90** [comment] 2024-06-29 12:20
This works as expected now with NVDA 2024.2 in Office 365 Microsoft 365 MSO (Version 2405 Build 16.0.17628.20006) 64 Bit or newer.
Closing as works for me.

**Closed by Adriani90** 2024-06-29 12:20 UTC
Labels: close/worksforme
