### ISSUE TITLE
Sign In account NVDA is reading unwanted table information on all list items under Pick an account pane.

### ISSUE THREAD

**Issue by eDADMSFTChristopher** [nvaccess/nvda#10997] opened 2020-04-13 17:28 UTC
User Experience:
Screen reader dependent users won't be able to navigate pane properly or screen reader users confused to navigate pane through screen reader, if NVDA is reading unwanted table information on all list items under Pic an account pane.

Repro Steps:
1. Open URL: https://www.office.com/
2. Navigate to 'Sign In' control and select it lying on Welcome to Office window.​
3. Navigate to all controls like listed User name, Use another account etc. lying on Microsoft Pick an account window.
4. Verify the issue.

Actual Result:
In normal mode NVDA is reading table table information on all list items under Pic an account pane.

Expected Result:
Screen reader should not read table information on all list items under Pic an account pane.

Note:-
Same type of issue exists in below screens.
1. Sign In-->NVDA is reading 'table' on Sign in edit field.
2.Enter password--> NVDA is reading 'table' on enter password edit field.

Test Environment:
Build: Version 1809 (OS Build 18290.1000) 
Browser: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
Screen Reader: NVDA 2019.3.2

Repro Steps:
1. Open URL: https://www.office.com/
2. Navigate to 'Sign In' control and select it lying on Welcome to Office window.​
3. Navigate to all controls like listed User name, Use another account etc. lying on Microsoft Pick an account window.
4. Verify the issue.

Actual Result:
In normal mode NVDA is reading table table information on all list items under Pic an account pane.

Expected Result:
Screen reader should not read table information on all list items under Pic an account pane.

Note:-
Same type of issue exists in below screens.
1. Sign In-->NVDA is reading 'table' on Sign in edit field.
2.Enter password--> NVDA is reading 'table' on enter password edit field.

Test Environment:
Build: Version 1809 (OS Build 18290.1000) 
Browser: Chrome Version 72.0.3626.119 (Official Build) (64-bit)
Screen Reader: NVDA 2019.3.2

**Comment by josephsl** [comment] 2020-04-13 17:36
Hi, confirmed (setup: Windows 10 Version 2004 (build 19041.173), Chrome 80, NVDA alpha.19938). Apart from asking whoever wrote this page (perhaps at Microsoft or somewhere) to not expose tables to screen readers, one temporary workaround is disabling table announcements from NVDA (NVDA menu/Preferences/Settings/document formatting/uncheck tables). Thanks.

**Comment by Adriani90** [comment] 2020-05-30 20:34
It is better now. In Chrome 83, NVDA reads table only when pressing next and the focus lands on the password field. But after that NVDA does not report table again when you navigate with tab and shift+tab. So the user impact is here very very low.

**Comment by Adriani90** [comment] 2023-04-20 14:33
Closing as duplicate of #12497 which contains more discussion.

**Closed by Adriani90** 2023-04-20 14:33 UTC
Labels: close/duplicate
