### ISSUE TITLE
NVDA has an issue related to memory load in 2016.4

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#6701] opened 2017-01-05 12:47 UTC
Hi the greatest team of nvAccess. Here is my another report about the most favourite screen reader for windows!
In the latest release of NVDA, it has seam to be heavy footprint on the system memory/resources. The base of this report is the behaviour change of NVDA when system is doing some tasks in the background or forground, NVDA stop reading the focussed windows, stop reporting the opened windows while pressing alt+tab, and even not report the focus change to another windows.
I have acer core i5 4th gen with 2.4GHZ along with turbo support, 6GB of RAM and 4GB of NVIDIA as well as 3GB of intel HD graphic 4400. This type of specification is strong enough to handel every kind of software including screen reader. The regular performance of NVDA is good, but the problem began when there is some process going on!
For example, If winRAR is extracting files from an archive at the time, and i want to use firefox to brows a web, NVDA does not told me to switch to the open windows, or navigate freely in the user interface. Instead of this, it just announce the title of the windows with press of alt+tab, and does not allow to go inside that windows and use that software! Moreover, After this type of situation, NVDA stop reading the folder list in the "this PC" as well, even after completion of extraction. And it become necessary to restart NVDA, or sometime need to restart the whole system to normalize its performance back to default state.
This type of issue is not appears before this release. the 2016.3 sometime act in such way, but that was not obvious. But 2016.4 is becoming more problematic in such situations. The simple words to explain are, NVDA is not being able to handel the situation where system memory or processer is busy in doing some other tasks.
I have varified this behaviour with different laptops, before reporting here. The case of winRAR extraction is just an example to explain my point, You can asume any type of task that may going on the system while initializing my report. Even most of the time, the simple process of copying files in my computer cause for this type of behaviour in the current release,
while the previous releases are still working fine on the same machine.

**Comment by josephsl** [comment] 2017-01-05 15:41
Hi, which version of Windows is this, and did you try running NVDA without add-ons (if you have add-ons installed) to see if it improves things? Thanks.

**Comment by abdullah5490** [comment] 2017-01-06 02:17
It is windows10x64, completely updated. Without any antivirus program, 
without any extra add-ons except eloquence, NVDA remote, and clip board 
announcement.
regards,
Abdullah Zafar from Islamabad Pakistan!
CEO at
Blind Help Project <http://www.blindhelp.net>
Trainning coordinator at
Masiha Educational Welfare Society <http://www.facebook.com/masews>
Media manager at
Pakistan Paraclimbing Club <http://www.facebook.com/pakparaclimbing>
Add me on skype as Abdullah.93@outlook.com
Meet on facebook
Abdullah Zafar on facebook! <http://www.facebook.com/abdullah5490>
Or on twitter
Abdullah5490 on twitter! <http://www.twitter.com/abdullah5490>
Send from thunderbird for windows e-mail client!

**Comment by feerrenrut** [comment] 2017-01-06 07:36
@abdullah5490 also on this issue it would be helpful if you could provide the nvda log at debug level, again please see the [wiki page for log files and crash dumps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps).

When this occurs could you please collect some extra information that could help us:
- The exact amount of memory that nvda is using.
- The CPU usage percentage

We cant reproduce this, and have not had other reports of this happening, for now I will mark this issue as blocked until we can get some more concrete information on what might be causing it. If this is affecting you regularly I would suggest continuing to run 2016.3 for the time being. Please let us know if the issue starts to occur in 2016.3 also.

**Comment by zahra21** [comment] 2017-05-07 12:58
hi.
i confirm this behaviour in nvda 2016.4 too!
its very heavy in using system resources and even simple tasks sometimes causes nvda become silent or does not allow me to navigate in windows softwares, browser etc.
but i decided to keep nvda 2016.4 and use it forever, because newer versions dont have any outstanding feature and i recieved 2016.4 in one of the best days and wish to always use it!
i completely uninstalled and reinstalled nvda 2016.4 and it helped me to reduce the issue very much!
thanks so much and God bless you all.

**Comment by leonardder** [comment] 2017-11-17 11:20
@zahra21, @abdullah5490, is this still the case in NVDA 2017.3 or 2017.4 RC1?

**Comment by abdullah5490** [comment] 2017-11-17 11:22
Not yet used the rc version, but that is not an issue for 2017.3 at least.

—
Disclaimer: This e-mail aimed to broadcast valuable information or to seek significant response. The contents of this message are constructed while keeping full responsibility under mind and does not contains any viruses or other types of threatening material.
Sent from outlook for iOS on the go!
Best regards,
Abdullah Zafar.
CEO blind help project - www.blindHelp.net
Trainning coordinator at Masiha educational welfare society - www.masews.org
Marketing and media manager at pakistan para climbing club for PWD’s - www.ppcc.pk
Skype: abdullah.93@outlook.com
Facebook/twitter: abdullah5490

________________________________

**Comment by zahra21** [comment] 2017-11-17 14:02
hello.
i confirm hanging of nvda 2017.2 and needing for restarting of system.
but i dont have this problem using nvda 2017.3 which is the best version for me forever!
also 2017.1 was great for me.
in 2017.3, sometimes nvda does not work properly and i need to restart it, but the problem is not very critical to need restarting windows!
God bless you all and his infinite mercy i pray for you.

**Comment by leonardder** [comment] 2017-11-17 14:42
@abdullah5490: As you are the original author of this ticket, do you agree with closing it as works for me?

**Comment by zahra21** [comment] 2017-11-17 14:50
if you want my views, i agree to close this bug as resolved fix.

**Comment by Brian1Gaff** [comment] 2017-11-17 15:55
I got the impression that the original poster was using windows xp, so would 
not be able to try the latest version anyway, but feel free to contradict 
me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by abdullah5490** [comment] 2017-11-18 19:41
I agree with @zahra21 that 2017.3 ocasionally stop responding, where i need to restart it to fix. You can close this issue, but I cannot say that it is completely resolved. However, it is too much improved and i want to express my gratitude on it for you. But still, i need to set my computer to "high performance" to avoid hanging up of NVDA on my machine, that was not the case at the time of older releases. And also, on the other side, I've made this experiment with JWS, but that work fine in even "balanced or power saver", even that one is too much heavier on system resources than NVDA. I'm not comparing these two, but just saying that if NVDA is already too light for a computer, then it shouldn't be required to run the processer at its maximum power and battery consumtion. because, of course, its a light-wait screen reader, not a graphically-ritch game! and @Brian1Gaff I am using windows 10 enterprise x64,but didn't got the time to test out the RC build yet. Windows XP, o no man! I left that one completely in 2009!

**Comment by ehollig** [comment] 2017-11-18 22:15
Closing as worksforme

**Closed by ehollig** 2017-11-18 22:15 UTC
Labels: p2, performance
