### ISSUE TITLE
Modal Dialog text gets read twice.

### ISSUE THREAD

**Issue by CharlesgdHill** [nvaccess/nvda#10398] opened 2019-10-18 21:04 UTC
### Steps to reproduce:
https://developer.microsoft.com/en-us/fabric#/controls/web/dialog
Open NVDA and tab to a button that says 'open dialog'
Press enter.

### Actual behavior:
Issue is that with NVDA on Chrome, the narrator is rereading parts of the dialog and its content:
My Sample Label Dialog, My Sample Description, Close Button, My Sample Label, Button Close, "Do you want to send this message without a subject?", Button Send, Button Don't Send
### Expected behavior:
Dialog text should only be read once.
#### NVDA installed/portable/running from source:
installed.
#### NVDA version:
latest.
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Chrome
#### Does the issue still occur after restarting your PC?
Yes

**Comment by Adriani90** [comment] 2020-05-12 16:21
Closing as duplicate of #8971.

**Closed by Adriani90** 2020-05-12 16:21 UTC
Labels: close/duplicate
