### ISSUE TITLE
Input help doesnt say what shifted carachters are when they change

### ISSUE THREAD

**Issue by Gene703122** [nvaccess/nvda#13549] opened 2022-03-28 08:02 UTC
### Is your feature request related to a problem? Please describe.
When using input help, if shifting a key produces something other than the shifted carachter, input help doesn't announce it.  It announces everything as shift plus the unshifted character.  For example, input help announces shift semicolon as shift semicolon, not colon.  
### Describe the solution you'd like
Input help should announce the actual character such as colon for shift semicolon, at for shift 2, etc.
### Describe alternatives you've considered
No alternatives.
### Additional context
If typing echo is set to speak characters, shifted characters are spoken correctly.  Input help should give the same information.

**Comment by CyrilleB79** [comment] 2022-03-28 14:22
This issue seems a duplicate of #6621.
If you agree, please close it and comment there further if needed.
If you disagree, please be more specific.

**Closed** 2022-03-29 07:04 UTC
