### ISSUE TITLE
Can not read page after chrome download

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7140] opened 2017-05-04 01:25 UTC
To play:
Download a file in chrome, such as those available on the nvda page:
Https://www.nvaccess.org/files/nvda/snapshots/
After downloading the file press ctrl + j to go to the chrome downloads page.
Now close the chrome downloads page with ctrl + f4.
The focus is expected to return to the nvda page and you can re-read the page with the arrows.
What happens is that when walking with the arrows assima and below is read only a url address and the content of the page is not read.
Using the nvda master 14008, windows 10 15063 64bits and chrome 58 64bits.
Follow the log:

IO - inputCore.InputManager.executeGesture (22:20:43):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getFormatFieldAndOffsets (22:20:43):
could not get attributes
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 197, in _getFormatFieldAndOffsets
  File "comtypes\__init__.pyc", line 795, in __call__
COMError: (-2147467263, 'N\xe3o implementado', (None, None, None, 0, None))
IO - speech.speak (22:20:43):
Speaking [u'https://www.nvaccess.org/files/nvda/snapshots/']
IO - inputCore.InputManager.executeGesture (22:20:53):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (22:20:54):
Developer info for navigator object:
name: u'Barra de endere\xe7o e de pesquisa'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_EDITABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x05840AD0>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (144, 35, 1159, 24)
value: u'https://www.nvaccess.org/files/nvda/snapshots/'
appModule: <'appModuleHandler' (appName u'chrome', process ID 13396) at address 4f036d0>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'58.0.3029.96'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 655616L
windowClassName: u'Chrome_WidgetWin_1'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 14248
windowText: u'NVDA Development Snapshots - Google Chrome'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x9ab0bb4 at a7dbad0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=655616, objectID=-4, childID=-1
IAccessible accName: u'Barra de endere\xe7o e de pesquisa'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: None
IAccessible accValue: u'https://www.nvaccess.org/files/nvda/snapshots/'
IAccessible2 windowHandle: 655616
IAccessible2 uniqueID: -1
IAccessible2 role: ROLE_SYSTEM_TEXT
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_EDITABLE (1032)
IAccessible2 attributes: u'text-model:a1;'

**Comment by ehollig** [comment] 2017-09-06 02:15
@fernando-jose-silva, is this still an issue for you? What version of Chrome are you using?

**Comment by fernando-jose-silva** [comment] 2017-09-06 19:37
Yes, I still have this problem
64bit chrome
Version 61.0.3163.79 (Official version) 64-bit
nvda masterpiece 14386
windows 7 64bit

**Comment by Adriani90** [comment] 2019-04-16 21:41
@fernando-jose-silva are you still seeing this issue in NVDA 2019.1.1 and Chrome 73? I cannot reproduce it.

**Comment by fernando-jose-silva** [comment] 2019-04-17 01:08
perfect, everything works fine now.

**Comment by Adriani90** [comment] 2019-04-17 21:21
Closing as works for me

**Closed by Adriani90** 2019-04-17 21:21 UTC
Labels: Chrome, worksforme
