### ISSUE TITLE
related to the search box of windows 11

### ISSUE THREAD

**Issue by alireza1385mamani** [nvaccess/nvda#15656] opened 2023-10-20 06:52 UTC
### Steps to reproduce:
1- go to the start menue
2- search for an app (in this example google chrome)
### Actual behavior:

there is a sound and nothing is spoken heare and I can not intract with anything.
### Expected behavior:

it says google chrom app and then when I press enter, it has to open it.
### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/13050818/nvda.log)

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.2
#### Windows version:
Windows 11 22H2 (AMD64) build 22621.2428
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes. 2023.1 same behave
#### If NVDA add-ons are disabled, is your problem still occurring?
yes. I've tryed with all addons disabled.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes.

**Comment by Adriani90** [comment] 2023-10-20 21:52
I cannot reproduce this issue.
Do you hear an error sound? Please upload a log file from NVDA with the logging set to "debug" in the general settings of NVDA.

**Comment by alireza1385mamani** [comment] 2023-10-21 07:04
Actually I heare the suggestionsClosed.wav sound and afterthat I can not see anything.
[nvda deebug.log](https://github.com/nvaccess/nvda/files/13060109/nvda.deebug.log)

**Comment by josephsl** [comment] 2023-10-21 10:10
Hi,

I have experienced this issue until recently. Sometimes a server side change can create this issue, mostly when there is a delay between people typing search terms and Windows returning results coming from both local and online sources.

Thanks.

**Comment by seanbudd** [comment] 2023-10-23 22:59
could you provide a log of this happening with add-ons disabled?

**Comment by OzancanKaratas** [comment] 2023-10-28 09:31
This has been fixed in the latest build of Windows.

**Comment by Adriani90** [comment] 2023-10-28 10:15
Thanks for the update. Closing as works for me. If you are still having this issue in the last stable Build of Windows, please comment and we can reopen.

**Closed by Adriani90** 2023-10-28 10:15 UTC
Labels: close/worksforme, p3, platform/Windows11, triaged, blocked/needs-technical-investigation
