### ISSUE TITLE
NVDA only reads the first line of multi-line messages in Windows Mail in Windows 10

### ISSUE THREAD

**Issue by mreiser** [nvaccess/nvda#6168] opened 2016-07-11 03:51 UTC
I am currently using NVDA version next-13407,bb103e63 on windows 10 insider build 14372 in case that makes any difference.  In multi-line messages in mail, nvda only reads the first line of the message.  To reproduce, do the following.  
1.  Create a new message to your self and type at least two lines of text in the body.  
1.  Open the message when it arrives.  Expected results: NVDA should read all the lines in the message.  

Actual results: NVDA only reads the first line.

**Comment by josephsl** [comment] 2016-07-11 03:55
Hi,

Confirmed (build 14385). Workaround is to use Control+arrow keys or review cursor.

@MichaelDCurran: somehow, one will need to use control+arrow keys to read message contents. Thanks.

**Comment by ehollig** [comment] 2017-08-01 23:29
@michaelDCurran, is this fixed in NVDA 2017.2 or will this be fixed as apart of #7289?

**Comment by michaelDCurran** [comment] 2017-08-01 23:43
This is again fixed in 2017.3 in pr #7295. It was originally fixed, but 
then broke due to issue #7289.

**Comment by michaelDCurran** [comment] 2017-08-01 23:48
Originally fixed in PR #6271.  It regressed due to Windows 10 Creators Update, and was again fixed in PR #7295.

**Closed** 2017-08-01 23:49 UTC
