### ISSUE TITLE
Navigation problems on thunderbird's chat interface in a line with abnormal numbers of spaces.

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#17032] opened 2024-08-20 18:26 UTC
### Steps to reproduce:

On Thunderbird's IRC interface, try to navigate over a line that contains a very large number of spaces.

The example that triggers it in my case:

```
20:05
eryc
                                                                                                                    0                                                                                                                              0
```

### Actual behavior:

The up arrow does not navigate up the line, and gets stuck on the 0.

```
Input: kb(desktop):upArrow
IO - speech.speech.speak (20:17:20.017) - MainThread (9396):
Speaking ['up arrow']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (20:17:20.021) - MainThread (9396):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (20:17:20.022) - MainThread (9396):
Speaking ['                                 0']
IO - inputCore.InputManager.executeGesture (20:17:20.480) - winInputHook (13256):
Input: kb(desktop):upArrow
IO - speech.speech.speak (20:17:20.481) - MainThread (9396):
Speaking ['up arrow']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (20:17:20.484) - MainThread (9396):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (20:17:20.486) - MainThread (9396):
Speaking ['                                  0']
IO - inputCore.InputManager.executeGesture (20:17:20.929) - winInputHook (13256):
Input: kb(desktop):upArrow
IO - speech.speech.speak (20:17:20.930) - MainThread (9396):
Speaking ['up arrow']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (20:17:20.933) - MainThread (9396):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (20:17:20.934) - MainThread (9396):
Speaking ['                                   0']
IO - inputCore.InputManager.executeGesture (20:17:21.368) - winInputHook (13256):
Input: kb(desktop):upArrow
IO - speech.speech.speak (20:17:21.369) - MainThread (9396):
Speaking ['up arrow']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (20:17:21.373) - MainThread (9396):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (20:17:21.374) - MainThread (9396):
Speaking ['                                    0']
IO - inputCore.InputManager.executeGesture (20:17:21.720) - winInputHook (13256):
Input: kb(desktop):upArrow
IO - speech.speech.speak (20:17:21.721) - MainThread (9396):
Speaking ['up arrow']
DEBUGWARNING - NVDAObjects.IAccessible.normalizeIA2TextFormatField (20:17:21.725) - MainThread (9396):
Unsupported value for text-align attribute: "start"
IO - speech.speech.speak (20:17:21.726) - MainThread (9396):
Speaking ['                                     0']
```

### Expected behavior:

Up arrow should navigate up without getting stuck on that line.

#### NVDA installed/portable/running from source:
NVDA installed.

#### NVDA version:
NVDA 2024.3.

#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4780

#### Name and version of other software in use when reproducing the issue:
Thunderbird 128.1.0 ESR.

#### Does the issue still occur after restarting your computer?
Not sure, it's an unusual line to get.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Did not try.

**Comment by SaschaCowley** [comment] 2024-08-20 23:53
Duplicate of #2812

**Comment by Adriani90** [comment] 2024-08-21 07:17
Closing as duplicate.

**Closed by Adriani90** 2024-08-21 07:17 UTC
Labels: close/duplicate
