### ISSUE TITLE
NVDA freezes in Outlook 2013 on Windows 7 in 2019.2 beta 2 and beta 3

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9991] opened 2019-07-29 06:21 UTC
### Steps to reproduce:
Issue reported by user.

1. Open Outlook.
2. Arrow through message list.

### Actual behavior:

A tone plays and a dialog "Waiting for Outlook" is displayed.  Then no further reponse from NVDA.

Log fragment:
```
Input: kb(desktop):upArrow
IO - speech.speak (15:38:11.562):
Speaking [LangChangeCommand ('en_US'), u'Table View  table']
ERROR - RPC process 4768 (nvda_slave.exe) (15:38:11.737):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 93, in main
  File "comHelper.pyo", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyo", line 180, in GetActiveObject
  File "comtypes\__init__.pyo", line 1247, in GetActiveObject
  File "_ctypes/callproc.c", line 946, in GetResult
WindowsError: [Error -2147221021] Operation unavailable
DEBUGWARNING - Python warning (15:38:11.756):
C:\Program Files\NVDA\library.zip\api.py:274: DeprecationWarning: Yield() is deprecated
IO - speech.speak (15:38:11.778):
Speaking [LangChangeCommand ('en_US'), u'Waiting for Outlook...  dialog']
IO - speech.speak (15:38:12.819):
Speaking [LangChangeCommand ('en_US'), u'From Amazon.com, Subject Your Amazon.com order #113-3328309-7992269 has shipped, Received Thu 7/25/2019 1:17 PM, Size 85 KB,  row 43  column 1  through 11']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (15:38:12.861):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (15:38:12.898):
Speaking [LangChangeCommand ('en_US'), u'Inbox  - Outlook']
IO - speech.speak (15:38:12.901):
Speaking [LangChangeCommand ('en_US'), u'Table View  table']
DEBUGWARNING - watchdog._watcher (15:38:13.394):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyo", line 519, in main
  File "wx\core.pyo", line 2134, in MainLoop
  File "gui\__init__.pyo", line 1003, in Notify
  File "core.pyo", line 490, in run
  File "queueHandler.pyo", line 86, in pumpAll
  File "queueHandler.pyo", line 53, in flushQueue
  File "eventHandler.pyo", line 62, in _queueEventCallback
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 1030, in event_gainFocus
  File "NVDAObjects\behaviors.pyo", line 481, in reportFocus
  File "NVDAObjects\__init__.pyo", line 918, in reportFocus
  File "speech.pyo", line 416, in speakObject
  File "speech.pyo", line 289, in speakObjectProperties
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "appModules\outlook.pyo", line 469, in _get_name

ERROR - RPC process 2876 (outlook.exe) (15:38:23.280):
Thread 5656, build\x86\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_ef5f541f18673a1c580e2f8ae5fd8903>::operator (), 101:
Could not fetch MAPI property, code -2147467259

DEBUGWARNING - RPC process 3384 (dwm.exe) (15:38:23.305):
Thread 3904, build\x86\remote\injection.cpp, inproc_winEventCallback, 66:
SetWindowsHookEx with WH_GETMESSAGE failed, GetLastError returned 5

DEBUGWARNING - RPC process 3384 (dwm.exe) (15:38:23.309):
Thread 3904, build\x86\remote\injection.cpp, inproc_winEventCallback, 69:
SetWindowsHookEx with WH_CALLWNDPROC failed, GetLastError returned 5
```
Then when pressing another arrow key:

```
Input: kb(desktop):downArrow
ERROR - RPC process 2876 (outlook.exe) (15:38:27.638):
Thread 5656, build\x86\remote\outlook.cpp, nvdaInProcUtils_outlook_getMAPIProp::<lambda_ef5f541f18673a1c580e2f8ae5fd8903>::operator (), 101:
Could not fetch MAPI property, code -2147467259
```

### Expected behavior:
NVDA should read message details while moving through Outlook message list.

#### NVDA installed/portable/running from source:

Temporary copy.

#### NVDA version:

2019.2 Beta 2 and beta 3. (Log generated from beta 3

#### Windows version:
Windows version 6.1.7601 service pack 1 workstation

#### Name and version of other software in use when reproducing the issue:

Outlook 2013

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2 Beta 2

**Comment by josephsl** [comment] 2019-07-29 06:26
Hi, I’m wondering if registration fixing tool might help, and if not, perhaps restarting with add-ons off. Thanks.

**Comment by Brian1Gaff** [comment] 2019-07-29 07:38
Also, two other things.
 Does it currently work on the last stable version? Also, has Avast anti 
virus ever been or is on the machine. The removal of that software breaks 
all sorts of things, some are fixed by a reinstall but others not or by the 
registry tool. I ended up having to reinstall windows and then use a back up 
to restore stuff to get the things to behave. Unfortunately I do not have 
that version of Office or I'd test it for you.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Qchristensen** [comment] 2019-07-29 08:13
Thanks Joseph and Brian.  I've written back to the user to ask.

My understanding is that it DID work in NVDA 2019.1, and I had also asked them to test with add-ons disabled so I'm hopeful they've done that too.  I'll report back once they've tried the COM registration fixing tool, and if they've ever had Avast.

**Comment by leonardder** [comment] 2019-07-29 10:01
I think this could have to do with this copy running temporarily, i.e. not being installed. I wonder whether that makes a difference.

**Comment by Brian1Gaff** [comment] 2019-07-29 14:21
Windows 7 is a lot less finicky on this than 10 seems to be. He could always 
create a temp copy of his installed stable and see if that fails. If it does 
then there is your answer, but if it works it might be worth making a clean 
install with the beta, then   if it works you have proved this point I 
guess. However if it fails, he might as well delete the beta and  reinstall 
the   stable from his newly created temp version saving him the 
configuration stage.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by howardgld** [comment] 2019-07-29 15:47
I'm the guy who reported this issue to Quentin. Thanks for all your comments.

1. The issue does exist under 2019.1 although it manifests itself a little differently. I get the freeze the first time I hit an arrow key in the message list but things work OK after that. With the beta I get the freeze the first time I hit an arrow key and a tone with every subsequent arrow key pressed.

2. Running the COM Registration Fixing tool did not help.
3. I have never had AVAST on this machine. However, I did use a different email client at one time and that may be what's messed things up. I'm going to try a full repair of Office to see if that helps unless someone has a better idea.

-- Howard

**Comment by DrSooom** [comment] 2019-07-29 15:48
See also: Issue #8961. Outlook 2010 (32-Bit on Win7x64) seems to work as expected with NVDA 2019.2 Beta-18176 Portable (excluding that mentioned error in issue #8961). Navigating within the e-mail list, jumping between folders and reading e-mails works as expected – after a quick look.

**Comment by howardgld** [comment] 2019-07-29 17:42
I forgot to mention in my earlier post that the issue persists after a full clean install of 2019.2 beta 3.

 

-- Howard

**Comment by leonardder** [comment] 2019-09-18 17:35
@howardgld Would you be able to test this with last Alpha version of NVDA?

**Comment by howardgld** [comment] 2019-09-18 19:47
I’d be happy to test if you could provide me with a link to the version of NVDA you’d like me to try.

**Comment by XLTechie** [comment] 2019-09-18 19:57
@howardgld This is the one he wants you to test (latest alpha): 
https://ci.appveyor.com/project/nvaccess/nvda/build/alpha-18699,0e4bb4ad

Luke Davis
Moderator: the new NVDA Help mailing list! (https://groups.io/g/NVDAHelp)
Author: Debug Helper NVDA add-on (https://addons.nvda-project.org/addons/debugHelper.en.html)

**Comment by howardgld** [comment] 2019-09-18 20:49
Thanks, but I’m afraid I’m still lost. I’ve never downloaded an alpha build and I don’t see anything at the link you provided for downloading. I’ll be happy to test if I can get my hands on the code.

 

-- Howard

**Comment by lukaszgo1** [comment] 2019-09-18 20:55
@howardgld Perhaps it would be easier to:
1. Go to https://www.nvaccess.org/files/nvda/snapshots/
2. Move to the first table on the page.
3. Activate first link called download there.

**Comment by howardgld** [comment] 2019-09-18 21:28
Ah! Much easier. I’ve downloaded it and will test later. Thanks.

**Comment by howardgld** [comment] 2019-09-19 00:13
Leonard,

 

I’m sorry to say that the behavior of Outlook with the alpha build is the same as what I reported earlier.

 

I am pretty certain that the fault is with my installation rather than with NVDA. I’ve noticed other oddities with Outlook. The system doesn’t fully recognize it as the default mail client. MailTo links on web pages work all right but if I try to invoke Outlook from another program such as SendTo Mail Recipient from Explorer or pressing the “Mail” button on my scanner I get the following message:

Either there is no default mail client or the current mail client cannot fulfill the

messaging request.  Please run Microsoft Outlook and set it as the default 

mail client.

 

I’ve been trying sporadically to fix that problem without any luck. I think that the only way to fix it would be to do a complete reinstall of Windows and Office but since I’m planning to upgrade to Windows 10 and a newer version of Office soon I didn’t think it was worth the trouble. I’m pretty sure that the NVDA issue as well as the default client issue will go away when I upgrade.

 

-- Howard

**Comment by lukaszgo1** [comment] 2019-09-19 10:02
You've mentioned that you have used different mailer before. May I ask what mail client it was?

**Comment by howardgld** [comment] 2019-09-19 13:59
Sure. It was Outlook Express for Windows 7 8 and 10 from runasxp.com.

**Comment by Adriani90** [comment] 2020-01-31 19:49
@howardgld are you still having this issue?
Could you run a registry clean with CCleaner on your system? I think Outlook Express still figures as the default mail client which should be incorrect.

**Comment by howardgld** [comment] 2020-01-31 19:59
Thanks, but I’ve moved to a new Windows 10 machine and no longer have the issue.

 

-- Howard

**Comment by Adriani90** [comment] 2020-01-31 20:19
Thanks for reporting. Since this was machine specific and we are not able to reproduce it, I will close it for now. Please report it again if you still have it and we can reopen this issue.

**Closed by Adriani90** 2020-01-31 20:19 UTC
