### ISSUE TITLE
Improvement of  configure profiles

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#6183] opened 2016-07-17 21:00 UTC
Is it possible to improve configure profiles so users will be able to choose how should NVDA be configured on special websites. Configure profiles dialog allows to define how NVDA is set in apps. It will be useful if this function was provided also for websites. e.g. on one website, user wants to turn off automatic switching from focus to browse mode, but on majority websites this feature can be enabled.

thanks, Jožef

**Comment by ehollig** [comment] 2017-09-12 16:11
Duplicate of #4442

**Closed by ehollig** 2017-09-12 16:11 UTC
Labels: Configuration profiles
