### ISSUE TITLE
DetailsList column header sorting order is not Reading in NVDA

### ISSUE THREAD

**Issue by sagoenka** [nvaccess/nvda#9642] opened 2019-05-30 09:30 UTC
### Steps to reproduce:
https://codepen.io/anon/pen/EzNoGP?&editable=true
### Actual behavior:

For Fabric.DetailsList we have columns when we navigate to each column header through clicking on Tab button ,once Tab entered to the DetailsList then i used down Arrow key to navigate to the column Headers and after clicking space on column header, grid is sorting but not reading everytime by NVDA when we click as sorting in Ascending order or Descending order, NVDA reading sometimes only and sorting order is changing every click of space.
While navigating to each column header, NVDA is not reading as 'Press space to sort the column header'(Except for 'File type' column header) and when when user presses enter on the header to sort NVDA is not reading the action performed as 'sorted Ascending or sorted Descending'

![image](https://user-images.githubusercontent.com/49481953/58623387-831aae00-82eb-11e9-8609-88d13bf0e89b.png)
![image](https://user-images.githubusercontent.com/49481953/58623413-94fc5100-82eb-11e9-8613-b01dfb490cc7.png)

### Expected behavior:
NVDA should read Sorting order(Ascending/Descending) of column for every click of space on column header of Fabric.DetailsList.

#### NVDA version:
2018.4.1
####Web Browser:
Google chrome
Version 74.0.3729.131
#### Windows version:
Windows 10 enterprise

**Comment by Adriani90** [comment] 2020-01-16 21:21
Closing as duplicate of #9017

**Closed by Adriani90** 2020-01-16 21:21 UTC
Labels: duplicate
