### ISSUE TITLE
<a> link containing a <span> tag cannot be activated in Microsoft Edge when the "Use UIA with Microsoft Edge and other Chromium-based browsers when available" option is set to "yes".

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14718] opened 2023-03-15 10:31 UTC
### Steps to reproduce:
[demo.txt](https://github.com/nvaccess/nvda/files/10978495/demo.txt)
1. Download the above 'demo.txt' and change the extension to '.html'
2. Enable 'Use UIA with Microsoft Edge and other Chromium based browsers when available' in the NVDA advanced settings panel
3. Open 'demo.html' in Microsoft Edge
4. Navigate to "open Github [website]" Try activating it with Space or Enter.
### Actual behavior:
Could not activate, nothing happened.
### Expected behavior:
The Github home page will open.
### NVDA logs, crash dumps and other attachments:
Actually there isn't any error log:
```
IO - speech.speech.speak (18:25:46.707) - MainThread (24396):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
IO - inputCore.InputManager.executeGesture (18:25:48.659) - winInputHook (12068):
Input: kb(laptop):space
IO - inputCore.InputManager.executeGesture (18:25:51.395) - winInputHook (12068):
Input: kb(laptop):shift+control+NVDA+f1
```
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-27830
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2604
#### Name and version of other software in use when reproducing the issue:
MS Edge: 111.0.1661.41
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, NVDA2022.1 can reproduce this too.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2023-04-04 12:20
Should this be closed as duplicate of #14612? We can upload the minimal test case to that issue.

**Comment by cary-rowen** [comment] 2023-04-05 01:36
@Adriani90 why? Is it because #14612 was created earlier?

**Comment by Adriani90** [comment] 2023-04-05 06:14
Yes, basically, but the older one is also talking about other controls that do not work, not just links. So it is broader in the scope.

**Comment by cary-rowen** [comment] 2023-04-05 09:07
You can suggest me to improve this title, I don't think it should be closed because I provided a minimal demo.
The earliest is not necessarily the best. For problem solving, it is more helpful to solve the problem to provide the minimal demo as detailed as possible.
I don't think #14612 is more detailed than this issue.

Thx

**Comment by Adriani90** [comment] 2023-04-05 09:45
See Mick's explanation in the older issue.

I am copying your minimal test case there and close this issue as duplicate. This will make it easier to track in a pull request that solves the focus problem in Edge all together.

**Closed by Adriani90** 2023-04-05 09:45 UTC
Labels: close/duplicate, p3, app/chrome, app/edge/anaheim, api/uia, triaged, blocked/needs-technical-investigation
