### ISSUE TITLE
NVDA+Chrome: Office Fabric DetailsList - Column header values read twice in scan mode

### ISSUE THREAD

**Issue by just-joshing** [nvaccess/nvda#10066] opened 2019-08-10 04:29 UTC
### Steps to reproduce:
1. Navigate to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic in Google Chrome
2. Start NVDA screen reader
3. Tab to the DetailsList sample on the page (or alternatively use the t key to jump to the DetailsList sample)
4. Ensure NVDA is in browse mode
5. Press ctrl+alt+left/ctrl+alt+right to move back and forth between the name and value column headers

### Actual behavior:
The first time each cell is visited in the column headers NVDA correctly says, for example, "Name column 2 clickable Name". But subsequent times through NVDA reads "Name Name column 2 clickable Name Name".

![animated gif depicting user reproducing the issue with NVDA speech viewer opened](https://user-images.githubusercontent.com/1325800/62817661-2871af80-baef-11e9-999e-32badcd65d30.gif)

![image of the NVDA speech viewer with the content "namename column 2 clickable name name" highlighted](https://user-images.githubusercontent.com/1325800/62226992-fb473380-b36f-11e9-8237-352f820d4476.png)

### Expected behavior:

Column header values are only read once.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 Enterprise version 1903

#### Name and version of other software in use when reproducing the issue:
Google Chrome version 75.0.3770.142

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by JllyGrnGiant** [comment] 2019-08-10 04:41
I do not reproduce the issue using NVDA+Firefox nor Narrator+Edge.

**Comment by josephsl** [comment] 2019-08-10 04:44
Hi, does this also happen with Edge based on Chromium? Also, for reference purposes, there is no “scan mode” in NVDA- actually, there is, it is just called “browse mode”. Thanks.

**Comment by JllyGrnGiant** [comment] 2019-08-10 04:49
Hi @josephsl 
Yes, I reproduce this issue in NVDA+Chromium-Based Edge as well.

**Comment by josephsl** [comment] 2019-08-10 04:51
CC @DerekRiemer and other Google people.

**Comment by XLTechie** [comment] 2019-08-10 06:54
Joshua wrote:

>  4. Switch NVDA to scan mode

NVDA doesn't have a scan mode. How exactly are you doing this? Do you mean 
browse mode?
Only it's already in browse mode at that point, so not sure how you're switching 
to the mode it's already in.

>   Actual behavior:
> 
> The first time each cell is visited in the column headers NVDA correctly says just, for example, "Name column 2 clickable Name". But subsequent times
> through NVDA reads "Name Name column 2 clickable Name Name".

I can confirm this in Chrome 76.0.3809.100. I can also confirm that it doesn't 
happen in latest Firefox.

> image

Fyi, most of the developers here are blind; un-alt-tagged images aren't helpful.

>     NVDA version:
> 
> 2019.1.1

I can also replicate this in latest beta. However it seems to be fixed in recent 
alphas.

**Comment by XLTechie** [comment] 2019-08-10 06:55
As an aside: all you need to do is hit t once you're on the page, in order to 
jump to the table. No need to tab all the way there.

**Comment by JllyGrnGiant** [comment] 2019-08-10 09:56
@XLTechie
Thank you for the information. I will update my original post.

I believe Narrator calls it "scan mode", which is why I mistakenly wrote that in the steps to reproduce the issue. I've updated my original post to say "browse mode".

I'll also update it to say "ensure NVDA is in browse mode" instead of "switch NVDA to browse mode".

Additionally I'll update the alt texts of the images of my original post. They depict NVDA's speech viewer logging the double announcement of the column header values.

Thanks again for the information, and I apologize for any confusion.

**Comment by Adriani90** [comment] 2020-01-16 21:34
Closing this as duplicate of #10177.

**Closed by Adriani90** 2020-01-16 21:34 UTC
Labels: duplicate
