### ISSUE TITLE
Position is lost when a button changes another elements display 

### ISSUE THREAD

**Issue by gpalmer00** [nvaccess/nvda#13393] opened 2022-02-25 20:38 UTC
Following the steps below, the navigation position is lost after activating one of the three buttons.  Occasionally it will work the first time however, continuing to navigate between the buttons and activating them will eventually cause the position to be lost preventing further navigation with the arrow keys.

### Steps to reproduce:

1. Open Chrome
2. Browse to [https://jsfiddle.net/asL8gcd5/1/](https://jsfiddle.net/asL8gcd5/1/)
3. Navigate to the button labeled "Button One"
4. Hit the down arrow to advance to the button "Button Two"
5. Hit `enter` to activate the button

### Actual behavior:
NVDA announces "unknown" and the navigation position is lost preventing you from using the arrow keys to navigate between the buttons.

### Expected behavior:
Current position in not lost and you continue to be able to navigate between the buttons using the arrow keys.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.3.3

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.3.1, same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by XLTechie** [comment] 2022-02-26 08:51
> #### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
> 
> N/A

Why is that N/A? It is not a very painful step to attempt.

**Comment by XLTechie** [comment] 2022-02-26 08:57
For what it is worth, I can replicate this in Brave, using NVDA alphas 24718,ba11e8a6 and 24817,618bfb6e. And yes, I did try COM fixes.
This does not replicate in Firefox.

When I got the error, this was the log: 
[logfrag1.txt](https://github.com/nvaccess/nvda/files/8146239/logfrag1.txt)
After I got "unknown", and the buffer stopped responding to arrow keys or browse mode in general, I pressed tab, which moves to the next button, as if nothing had happened. That log contains the actual traceback: 
[logfrag2.txt](https://github.com/nvaccess/nvda/files/8146240/logfrag2.txt)

**Comment by Brian1Gaff** [comment] 2022-02-26 09:36
Hmm, Here on my old windows 7 machine, all is well in Firefox and Waterfox, 
but Edge on the other hand firstly has no navigation on entry to the page, 
until you toggle focus mode, then  as described in the ticket after 
operating button 2, it goes into sulk mode and either claims unknown or just 
goes silent. Admittedly  Edge on Windows 7 is not the latest version though. 
Looking at the errors there are a lot of not implemented  and timeouts etc.
 Not tried other versions of nvda other than the stable branch.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Gerry Palmer" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Friday, February 25, 2022 8:38 PM
Subject: [nvaccess/nvda] Position is lost when a button changes another 
elements display (Issue #13393)

**Comment by gpalmer00** [comment] 2022-02-26 13:44
> > #### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
> > N/A
> 
> Why is that N/A? It is not a very painful step to attempt.

Updated

**Comment by Adriani90** [comment] 2023-04-20 19:28
@gpalmer00 I cannot reproduce this issue with NVDA last alpha version and Chrome or Edge 112 or Firefox 112.

Could you please test with last alpha if this issue still occurs for you?

You can download the last alpha at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Adriani90** [comment] 2024-07-25 22:06
I cannot reproduce this issue and we didn't get any updates from the initial author. I am closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-07-25 22:06 UTC
Labels: close/worksforme, needs-triage

**Comment by XLTechie** [comment] 2024-07-26 04:18
It looks like I was one of the original testers on this, so I tested it again. I also can not repro after multiple attempts.
