### ISSUE TITLE
NVDA ignores reading aria-error message with id reference

### ISSUE THREAD

**Issue by sripalreddyadamala** [nvaccess/nvda#8605] opened 2018-08-07 14:44 UTC
Hi All,
I have error messages for username and password fields and I am referencing it with newly added aria 1.1 aria-error message with id. NVDA Screen reader ignores reading error messages  in chrome ie and Firefox. 

[aria-errormessage.txt](https://github.com/nvaccess/nvda/files/2266823/aria-errormessage.txt)

Steps to reproduce:
Actual behavior:
Ignores reading error message on password and username label.

Expected behavior:
Need to read error validation message  on tab from username to password textbox.

System configuration:
NVDA Installed/portable/running from source:
NVDA version:
218.2.1

Windows version:
7

Other information about your system:
windows 7 or mac

Other questions:
Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?
No

![image](https://user-images.githubusercontent.com/17653691/43782960-873f7bec-9a2e-11e8-9620-5252a62b9121.png)

**Comment by Adriani90** [comment] 2019-05-08 18:09
Closing as duplicate of #8318.

**Closed by Adriani90** 2019-05-08 18:09 UTC
Labels: ARIA, duplicate
