### ISSUE TITLE
correct some phrases reported in braille to be consistent and some other braille related suggestions

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7450] opened 2017-07-28 14:41 UTC
This ticket is not a clasical bug. it would be a feature request and also slightly duplicate of#217 and others.

### Expected behavior:
in braille (english version of NVDA a words such as taskbar and tool bar should be written with spaces or all of them without spaces (same as in JAWS)

### Actual behavior:
now taskbar is written without spaces and tool bar is written with space.

### System configuration:
NVDA version:
2017.2 and next versions

NVDA Installed or portable:
both

Windows version:
10 (1703) with latest updates installed

### post scriptum
some suggestions:
- is it possible to abriviate these phrases so they would be written "tskbar or tlbar" same as mnubar for menu bar and others?
- I suggest you that space between row and colomn coordinates would be removed. new patern would be "RxCy"
- can NVDA reports at braille information how many elements are in table or in a list?
it means tb with x rows and y colomns or lst with z items. if it is possible, tb before first element in a table or lst before first element on the list could be removed. if it is not possible, I suggest, that tb and lst stays together with all paterns not only with a first element of a table or a list. It would be more consistent then now.

**Comment by leonardder** [comment] 2017-07-28 15:01
Where do you read taskbar exactly? Note that most of this is already incubating in next.

**Comment by gregjozk** [comment] 2017-07-28 15:19
Hi,

when you close some programs or when NVDA is started, NVDA says taskbar and it is written on braille display.

**Comment by dkager** [comment] 2017-07-28 15:28
> I suggest you that space between row and colomn coordinates would be removed.

Please open a separate issue for this. While it looks trivial, I think it requires some more thought.

> can NVDA reports at braille information how many elements are in table or in a list?

Another separate issue. It already shows up in list views, e.g. the desktop.

**Comment by dkager** [comment] 2017-07-28 15:40
As for the Taskbar, that is the name of that specific control (hence the capital) whereas tool bar, menu bar, etc are types of widgets. Whether or not there should be a space is a valid question, though we pretty much cover that by the abbreviations that are currently incubating.

**Comment by leonardder** [comment] 2017-07-28 17:24
Given @Dkager's reply in https://github.com/nvaccess/nvda/issues/7450#issuecomment-318684192 which I agree with, I think it's best to close this as a duplicate of #7188.

**Closed by leonardder** 2017-07-28 17:24 UTC
