### ISSUE TITLE
Latest next snapshot triggers an error when trying to read merged cells in Excel 2007

### ISSUE THREAD

**Issue by sukiletxe** [nvaccess/nvda#6889] opened 2017-02-15 23:55 UTC
Steps:
1. Merge two or more cells in Excel 2007.
2. Move around and focus the cell.

Expected: NVDA reads the cell's contents.
Acttual: NVDA triggers an error.
Log:
```
IO - inputCore.InputManager.executeGesture (00:54:17):
Input: kb(laptop):upArrow
ERROR - eventHandler.executeEvent (00:54:17):
error executing event: gainFocus on <NVDAObjects.window.excel.ExcelMergedCell object at 0x0593D090> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\sukil etxenike\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 341, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 893, in event_gainFocus
  File "NVDAObjects\window\excel.pyc", line 1405, in reportFocus
  File "textInfos\offsets.pyc", line 398, in getTextWithFields
  File "NVDAObjects\window\excel.pyc", line 992, in _getFormatFieldAndOffsets
  File "comtypesMonkeyPatches.pyc", line 37, in new__getattr__
  File "comtypes\client\dynamic.pyc", line 93, in __getattr__
  File "comtypes\automation.pyc", line 643, in GetIDsOfNames
COMError: (-2147352570, 'Nombre desconocido.', (None, None, None, 0, None))
```

Latest stable works.

"Nombre desconocido" = "Unknown name"

**Comment by sukiletxe** [comment] 2017-02-16 14:41
If I disable the announcement of cell borders, the bug is no longer present. Also, NVDA + Tab always works.

**Comment by jcsteh** [comment] 2017-02-17 06:02
This sounds like it might be a regression introduced by #3044. @feerrenrut, would you mind investigating?

**Comment by feerrenrut** [comment] 2017-02-17 18:39
This issue seems to effect excel 2007, and not excel 2013.

The relevant difference in the API is the `DisplayFormat` property that [exists in excel 2013](https://msdn.microsoft.com/en-us/library/ff838814.aspx) but [not in excel 2007](https://msdn.microsoft.com/en-us/library/bb225606(v=office.12).aspx). If the call to `DisplayFormat` fails instead we access the borders via the [range.borders property](https://msdn.microsoft.com/en-us/library/bb213512(v=office.12).aspx).

**Comment by feerrenrut** [comment] 2017-03-14 06:00
Closing this issue since this regression on next has been resolved. See #6895 and #3044

**Closed by feerrenrut** 2017-03-14 06:00 UTC
Labels: incubating, regression
