### ISSUE TITLE
NVDA is not reading the non interactive element with role ="combobox"

### ISSUE THREAD

**Issue by WiproCRMAccessibility** [nvaccess/nvda#9108] opened 2018-12-28 10:38 UTC
**Steps to reproduce:**

Turn on NVDA, Open the html page in chrome and use arrow key-down to read the data of non-interactive elements.

**Actual behavior:**

NVDA is not Reading  the value of non-interactive element which is child of element with role="combobox".

**Expected behavior:**

NVDA should read all child elements under role="combobox".

**System configuration:**

windows 10 64bit ,16GB ram

**NVDA Installed/portable/running from source:**

**NVDA version: 2018.2.1**

**Windows version:**

Windows 10 Enterprise, version 1803

**Name and version of other software in use when reproducing the issue:**
[combobox.zip](https://github.com/nvaccess/nvda/files/2714633/combobox.zip)

Latest version of chrome and Edge.

**Other information about your system:**

**Other questions:**

Does the issue still occur after restarting your PC?

yes

Have you tried any other versions of NVDA?

NO

**Comment by Brian1Gaff** [comment] 2018-12-28 11:16
What does it do with the  later version of NVDA after the one you mention?


bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment] 2020-01-24 21:54
This is still reproducible on NVDA 2019.3 Beta 2, Firefox 72.0.2 and Chrome 79. Only in IE it works correctly.
cc: @jcsteh, @MarcoZehe

**Comment by MarcoZehe** [comment] 2020-01-25 06:19
NVDA has never read all combobox options in virtual cursor if the combobox was collapsed. Imagine a country select combo box with 200 or so items. Reading those with the virtual cursor would not make sense. AFAICS, this works as intended.

**Comment by Adriani90** [comment] 2020-04-20 20:28
@MarcoZehe try to open the html file in Internet explorer. When you press down arrow, NVDA reports "combo box active". This should be reported in other browsers as well. Or am I wrong here?

**Comment by MarcoZehe** [comment] 2020-04-21 04:55
AFAIK, this is an NVDA bug, unless @jcsteh proves me otherwise. For some reason, it doesn't report the current selection in virtual cursor mode in some combo boxes. It does this in Google Calendar and other apps as well that have custom combo boxes. Interacting with the combo box reveals the current value, but NVDA doesn't render it in the virtual buffer for some reason, unlike normal select size=! elements.

**Comment by jcsteh** [comment] 2020-04-21 06:00
There are a few issues here.

First, the combo box isn't focusable, which is I guess what @WiproCRMAccessibility meant in saying that it is non-interactive. I don't follow how a non-focusable combo box makes sense. A combo box control is inherently interactive. This is why NVDA doesn't render the control at all when it can't determine a value.

Second, regarding NVDA not being able to determine a value, it's unclear whether this is a spec/browser bug or an NVDA bug. HTML select controls (and Win32 combo box controls) expose the current value via the value property (IAccessible::accValue). Non-editable ARIA comboboxes do not. The Core AAM spec doesn't specify that value should be exposed. I'd argue it should, which would fix this.

Interestingly, if the combobox is focusable, Chrome does now expose accValue in this case. I think Firefox should do this also.

**Comment by jcsteh** [comment] 2020-04-21 06:22
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1631693 for the Firefox part of this.

**Comment by seanbudd** [comment] 2022-07-26 01:33
Closing as duplicate of #13947

**Closed** 2022-07-26 01:33 UTC
