### ISSUE TITLE
Outlook show/hide password button has no accessible indication of state

### ISSUE THREAD

**Issue by XLTechie** [nvaccess/nvda#11513] opened 2020-08-20 08:19 UTC
Not very important I think, except that it may effect other buttons in other places that are more important.
Also, I suspect this is Microsoft's problem, and NVDA can't actually fix it.

### Steps to reproduce:

1.  Press alt+f, i, d, to add a new account.
2.  Enter an email address. I used `fake@fake.com`.
3.  Tab to then select each of the following chain of options:
    * `advanced options`.
    * `Let me setup my account manually`.
    * `Connect`.
    * `IMAP`
4.  Enter "`localhost`" for both servers, and leave everything else at default.
5.  Select `next`.
6.  Enter anything in the password field. Stars are spoken as might be expected.
7.  Press tab, to go to the `show or hide password` option.

### Actual behavior:

The full button name in step 7, is:

> Show or hide password  button  Show password. Press Shift + Tab to go back to password

And that's the name of the button no matter which mode it's in--whether the password is shown or not.

### Expected behavior:

NVDA should indicate whether the button is set to show or hide the password, not just always be suggesting that it is shown.

### System configuration

NVDA installed, alpha-20758,0098a31a
Add-ons, restarts, and COM Reg fixes don't change anything.
Windows 10 Version 2004 (OS Build 19041.450)
MS Outlook 2019

### DevInfo for password button with shown password

name: 'Show or hide password'
role: ROLE_BUTTON
roleText: None
states: STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x04A682D0>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: 'Show password. Press Shift + Tab to go back to password'
location: RectLTWH(left=1129, top=384, width=20, height=20)
value: None
appModule: <'outlook' (appName 'outlook', process ID 8828) at address 5982f90>
appModule.productName: 'Microsoft Outlook'
appModule.productVersion: '16.0.13029.20344'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 198480
windowClassName: 'NetUIHWND'
windowControlID: 0
windowStyle: 1442840576
extendedWindowStyle: 0
windowThreadID: 6372
windowText: ''
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x57401e0 at 1178300>
UIA automationID: 
UIA frameworkID: 
UIA runtimeID: (42, 198480, 4, 614423056, 0)
UIA providerDescription: [pid:8828,providerId:0x0 Main(parent link):Unidentified Provider (unmanaged:mso40uiwin32client.dll)]
UIA className: NetUISimpleButton
UIA patterns available: InvokePattern, LegacyIAccessiblePattern

**Comment by leonardder** [comment] 2020-08-25 17:16
It looks like there isn't an UIA pattern that exposes this, so yes, this is indeed an issue that has to be fixed by Microsoft.

**Comment by Adriani90** [comment] 2020-08-31 22:20
cc: @Qchristensen

**Comment by Qchristensen** [comment] 2020-08-31 23:26
This is definitely an Outlook issue.  The problem isn't that there is no "accessible" indication of state of the show password button, but that there is no indication of state at all.

For anyone looking visually at this:

Password hidden:
![image](https://user-images.githubusercontent.com/15902216/91778136-020c3e00-ec35-11ea-9de7-b0e45caf72bb.png)

Password shown:
![image](https://user-images.githubusercontent.com/15902216/91778182-1819fe80-ec35-11ea-9b6f-9579f245a08f.png)

I'll share this with Microsoft, but will also close as "NeedsExternalFix".

**Closed by Qchristensen** 2020-08-31 23:26 UTC
Labels: blocked/needs-external-fix
