### ISSUE TITLE
NVDA becomes unresponsive on Firefox in some webpages

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#10637] opened 2019-12-18 08:34 UTC
### Steps to reproduce:

Open https://www.xunta.gal/dog/Publicados/2019/20191127/AnuncioCA01-251119-0001_es.html with Firefox.

### Actual behavior:

NVDA says loading document, and Firefox (or NVDA, not sure) stops responding to keyboard input.

### Expected behavior:

Webpage loads and can be read normally.

#### NVDA installed/portable/running from source:

NVDA installed.

#### NVDA version:

NVDA 2019.2.1.

#### Windows version:

Reproduced on Windows 7 and Windows 8.1.

#### Name and version of other software in use when reproducing the issue:

Firefox 71.0 64 bit.

#### Does the issue still occur after restarting your PC?

Yes. It happens on two different computers.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No.

**Comment by Brian1Gaff** [comment] 2019-12-18 14:53
Yes I found this on a web site called milkandmore which is a home delivery 
site in the UK.
 I ended up blipping the power button and heard an nvda ding before the 
computer shut down. I used waterfox on the site, but then encountered a very 
odd effect where the displayed visible  picture was not what nvda was 
reading.
 Has anyone else seen this effect in windows 7?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Adriani90** [comment] 2019-12-19 12:12
Can you reproduce this with NVDA 2019.3 Beta 1?

**Comment by davidacm** [comment] 2019-12-24 13:24
This is a very large document. process html documents in Firefox is very slow compared with chrome. I ran some tests comparing the performance of screen readers with different tasks. NVDA is the fastest loading html documents in any browser, but in firefox this task always takes a long time for any screen reader, even NVDA.

I think that if you wait for a long time, the document will be loaded. If you try it with chrome, the process will take a few seconds.

I don't know if the performance when processing html documents in Firefox can be improved. But is Firefox fault, I think.

**Comment by bingen13** [comment] 2020-03-01 08:55
I was holding off upgrading to 2019.3 due to some add-on incompatibility issues, but I have now reproduced it with 2019.3.1. and Firefox 73.0.1 64-bit.

**Comment by Adriani90** [comment] 2020-05-28 20:18
Closing as duplicate of #9383.

**Closed by Adriani90** 2020-05-28 20:18 UTC
Labels: close/duplicate
