### ISSUE TITLE
Excel hangs when using new feature in vision Enable Highlighting

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#10535] opened 2019-11-23 00:38 UTC
### Steps to reproduce:
enable Enable Highlighting
open a spreadsheet in excel
press f2 in a cell that contains content.
edit the cell.
Hit enter.
### Actual behavior:
excel locks up and sometimes reopens again.
### Expected behavior:
excel does not lock and works correctly
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
alfa 19266
#### Windows version:
10 1909 18363.476
#### Name and version of other software in use when reproducing the issue:
EXCEL.EXE 16.0.12130.20344

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

if Enable Highlighting is disabled excel works correctly and does not lock.
This is true even with add-ons disabled.

log:
[excel.txt](https://github.com/nvaccess/nvda/files/3881967/excel.txt)

**Comment by ruifontes** [comment] 2019-11-23 00:55
Not reproducible here...


Rui Fontes


Às 00:38 de 23/11/2019, fernando-jose-silva escreveu:

**Comment by Brian1Gaff** [comment] 2019-11-23 08:21
I've seen something similar on an older version of the software if focus 
highlight add on is enabled. Have you tried disabling all add ons and seeing 
what happens?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by lukaszgo1** [comment] 2019-11-23 10:16
cc @leonardder

**Comment by lukaszgo1** [comment] 2019-11-23 15:34
@fernando-jose-silva Please try to reproduce this with all add-ons disabled.

**Comment by fernando-jose-silva** [comment] 2019-11-23 17:00
I can reproduce the problem with disabled adons.￼￼

Enviado do meu iPhone

**Comment by leonardder** [comment] 2019-11-23 18:16
I think the NVDA Highlighter isn't in error here, but the vision framework probably tries to fetch the location from the focus object in such a way the Excel object model does not appreciate.
I recall that I was able to reproduce this, and will try to look into it next week.

**Comment by fernando-jose-silva** [comment] 2019-11-23 18:38
thanks.￼

Enviado do meu iPhone

**Comment by leonardder** [comment] 2019-11-26 11:58
@fernando-jose-silva There have been some changes to the highlighter recently. Can you still reproduce this?

**Comment by fernando-jose-silva** [comment] 2019-11-26 13:20
I'm not on my personal machine where the crash occurs, I'm on the work machine that uses a different office version:
EXCEL.EXE 16.0.4927.1000
Updated nvda to last alpha
nvda.exe alpha-19297, a8aad369
and couldn't replicate the problem
The other difference between the two machines is that the personal nvda is installed, the working nvda is portable, I have no permission to install software.
thank you.
On Friday I'll be on my personal machine and I'll be able to test this machine.

**Comment by fernando-jose-silva** [comment] 2019-11-29 16:01
I tested it on my personal machine, and unfortunately the crash occurred again in excel.
The windows view is the same between both personal and work machines. 18363.476
The nvda verse also seems to make no difference, now I tested with nvda alfa 18346.
Finally, the difference between the two machines is that on the personal machine nvda is installed and on the work machine nvda is not installed.
The excel version that is on the personal machine is:
EXCEL.EXE 16.0.12130.20410
remembering that on the working machine the problem did not occur and on the personal machine the problem occurred.
abstract:
problem machine
EXCEL.EXE 16.0.12130.20410
nvda installed

machine without problem
EXCEL.EXE 16.0.4927.1000
nvda port
log:
[noaddonexcel.txt](https://github.com/nvaccess/nvda/files/3905866/noaddonexcel.txt)

**Comment by bdorer** [comment] 2019-12-02 21:35
I'm not able to reproduce this.

Am 26.11.2019 um 12:58 schrieb Leonard de Ruijter:

**Comment by leonardder** [comment] 2019-12-05 18:51
@fernando-jose-silva Can you reproduce this when NVDA is running as a portable copy on your home system?

**Comment by fernando-jose-silva** [comment] 2019-12-06 17:06
I tested and unfortunately can reproduce the problem on the home computer with a portable copy.
So I think it's due to my office verion
[excel_portable.txt](https://github.com/nvaccess/nvda/files/3933210/excel_portable.txt)

Thank you very much for your attention, follows the log of the portable copy on the home computer.

**Comment by Adriani90** [comment] 2020-05-23 11:16
@fernando-jose-silva if you update your excel vie file ribbon / account / update options, is this issue still occuring with NVDA last alpha version?

**Comment by fernando-jose-silva** [comment] 2020-05-26 14:38
I continue with the reported problem, even after your suggestions.
The log continues with the active add-ons, but the problem occurs without the active add-ons.
If I disable 
[excel1.txt](https://github.com/nvaccess/nvda/files/4682932/excel1.txt)
the enable realse option I don't have this problem.
Thank you.

**Comment by Adriani90** [comment] 2020-05-26 16:13
Sorry which setting you disable for the problem to be solved? I didn’t understand that.

 

 

Von: fernando-jose-silva <notifications@github.com> 
Gesendet: Dienstag, 26. Mai 2020 16:39
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Excel hangs when using new feature in vision Enable Highlighting (#10535)

 

I continue with the reported problem, even after your suggestions.
The log continues with the active add-ons, but the problem occurs without the active add-ons.
If I disable
excel1.txt <https://github.com/nvaccess/nvda/files/4682932/excel1.txt> 
the enable realse option I don't have this problem.
Thank you.

**Comment by fernando-jose-silva** [comment] 2020-05-26 21:17
nvda

 

vision

 

Configure visual aids.

 

Enable Highlight

De: Adriani90 <notifications@github.com> 
Enviada em: terça-feira, 26 de maio de 2020 13:14
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [nvaccess/nvda] Excel hangs when using new feature in vision Enable Highlighting (#10535)

 

Sorry which setting you disable for the problem to be solved? I didn’t understand that.





Von: fernando-jose-silva <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Dienstag, 26. Mai 2020 16:39
An: nvaccess/nvda <nvda@noreply.github.com <mailto:nvda@noreply.github.com> >
Cc: Adriani90 <adriani.botez@googlemail.com <mailto:adriani.botez@googlemail.com> >; Comment <comment@noreply.github.com <mailto:comment@noreply.github.com> >
Betreff: Re: [nvaccess/nvda] Excel hangs when using new feature in vision Enable Highlighting (#10535)



I continue with the reported problem, even after your suggestions.
The log continues with the active add-ons, but the problem occurs without the active add-ons.
If I disable
excel1.txt <https://github.com/nvaccess/nvda/files/4682932/excel1.txt> 
the enable realse option I don't have this problem.
Thank you.

**Comment by Adriani90** [comment] 2020-05-27 19:47
@leonardder could you have a deeper look at this if you have time? It seems the problem is not occuring if the highlighter is disabled. This might be also due to some comtypes errors that could cause a event_gainfocus to fail. I think the first half of the log is more related to this issue.

**Comment by Adriani90** [comment] 2023-09-05 17:34
@fernando-jose-silva are you still having this issue with NVDA 2023.2 in Excel 2016 or Excel 365?

**Comment by fernando-jose-silva** [comment] 2023-09-05 17:48
Thank you very much, the problem no longer happens.Enviado do meu iPhoneEm 5 de set. de 2023, à(s) 14:34, Adriani90 ***@***.***> escreveu:﻿
@fernando-jose-silva are you still having this issue with NVDA 2023.2 in Excel 2016 or Excel 365?

**Comment by Adriani90** [comment] 2023-09-05 17:59
Thanks for the quick reply. Closing as works for me.

**Closed by Adriani90** 2023-09-05 17:59 UTC
Labels: close/worksforme, p3, component/vision
