### ISSUE TITLE
Problem with NVDA

### ISSUE THREAD

**Issue by BEdenhofer6** [nvaccess/nvda#16935] opened 2024-07-31 09:43 UTC
When you unload jaws, and go to launch NVDA, jaws will launch, the same time, NVDA does. I can reproduce this problem, every time, my current version of NVDA that I have installed on my PC's, is NVDA 2024.2 The snapshot that I am running is, 33138,410e42eb.

**Comment by josephsl** [comment] 2024-07-31 14:59
Hi,

Short of asking you to fill out the template to the fullest (starting with choosing the bug report template and answering all the questions in the template), I advise looking at the properties for JAWS desktop shortcut (press Alt+Enter when focused on JAWS icon) and se if Control+Alt+N is entered into the hotkey field. If it is, then remove the hotkey from JAWS shortcut (just press Delete to remove the hotkey from the hotkey field). Otherwise, it could be something inside NVDA or JAWS that’s causing both to start (I can’t reproduce this on my system).

A warning with concern: I believe this is the third time that you were asked to fill out the template; come to think of it, I think you are using a regular new issue process rather than using a bug report template. If you did use the regular new issue fields, next time you raise an issue, please go to https://github.com/nvaccess/nvda/issues/new/choose then choose "bug report". Doing so can help you gather all the information you need to help developers (and the rest of the NVDA community) better understand your situation - needed info include NVDA version, Windows version, app version, exact (or almost exact) steps to reproduce, and what NVDA is doing versus what you are expecting. I'm giving you a stern warning with concern: next time you raise an issue and people learn that you didn't fill out the template, NV Access, NVDA community, an others may not look at future issues from you favorably (or outright ignore you), so please take advice from the community to heart.

Also, another thing to remember: when filling out issue templates, title matters. Just saying "problem with NVDA" does not tell the community what you are after - people do not read GitHub issues unless the title resonates with them or they are mentioned (please do NOT mention my GitHub name unless you think I might be the best person to handle specific parts of NVDA). So next time you fill out an issue template, please provide a more descriptive title (writing a descriptive title is an art and requires critical thinking).

Thanks.

**Comment by Adriani90** [comment] 2024-07-31 20:18
Closing this issue because template is not filled completely and we are missing important information for investigation. Also this seems to occur due to conflicting keystrokes between NVDA and Jaws. Given NVDA uses this  keystroke for ages now and is in muscle memory of so many users, NVDA cannot be changed.

**Closed by Adriani90** 2024-07-31 20:18 UTC
