### ISSUE TITLE
Keyboard shortcut is sometimes not properly read for Java applications

### ISSUE THREAD

**Issue by raducoravu** [nvaccess/nvda#10994] opened 2020-04-13 08:50 UTC
In a Java application I have a menu item with Ctrl-F6 set as accelerator.
NVDA reads the shortcut as "control plus" without reading the F6 key at all. JAWS properly reads the entire shortcut.

      public static void main(String[] args) {
        JFrame fr = new JFrame();
        JMenuBar mb = new JMenuBar();
        JMenu menu = new JMenu("windows");
        JMenuItem mi = new JMenuItem("abc");
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F6, KeyEvent.CTRL_DOWN_MASK));
        menu.add(mi);
        mb.add(menu);
        fr.setJMenuBar(mb);
        fr.setSize(500, 500);
        fr.setVisible(true);
      }

**Comment by mwhapples** [comment] 2022-05-09 15:54
This should be fixed by pull request #13676 and duplicates issue #13643

**Comment by mwhapples** [comment] 2022-05-19 10:19
Duplicate of #13643

**Comment by mwhapples** [comment] 2022-05-19 10:20
We should close this now that the duplicate issue is resolved.

**Comment by mwhapples** [comment] 2022-05-19 10:27
@seanbudd could you close this issue?

**Comment by seanbudd** [comment] 2022-05-19 11:08
Closed by #13676

**Closed by seanbudd** 2022-05-19 11:08 UTC
Labels: component/java-access-bridge
