### ISSUE TITLE
Allow to use Windows 11 Neural Voices

### ISSUE THREAD

**Issue by nicopn** [nvaccess/nvda#15874] opened 2023-12-03 21:59 UTC
### Is your feature request related to a problem? Please describe.
I would like for NVDA to support the neural voices found on Windows 11 22h2 and above, which include Aria, Genny and Guy. Currently, Narrator is the only screen reader that supports these.
### Describe the solution you'd like
Add a speech synthesizer that interfaces with the neural voices, if possible
### Describe alternatives you've considered
None
### Additional context
Since the neural voices are windows11-specific, the synth should only appear in supported versions of Windows 11.

**Comment by seanbudd** [comment] 2023-12-03 22:31
Closing as duplicate of #13288

Please note that microsoft doesn't allow free third party use currently. You need to ask microsoft to allow screen readers to use these.

**Closed by seanbudd** 2023-12-03 22:31 UTC
