### ISSUE TITLE
NVDA does not read text when using left arrow in search edit in Google or YouTube in Chrome or Edge

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13272] opened 2022-01-25 03:06 UTC
### Steps to reproduce:

1. Open Chrome (or Edge)
2. Load google.com (note, not the start page on some computers)
3. Start typing, at least two or three characters in the search edit.
4. Press left arrow

### Actual behavior:

Errors are written to the log after a couple of characters are typed at step 3.
At step 4, nothing is read (and more errors are logged).

Log fragment at step 4:
IO - inputCore.InputManager.executeGesture (13:24:46.931) - winInputHook (29636):
Input: kb(desktop):leftArrow
ERROR - eventHandler.executeEvent (13:24:46.989) - MainThread (5964):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x09E93EB0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "browseMode.pyc", line 1322, in event_caret
  File "eventHandler.pyc", line 107, in next
  File "NVDAObjects\behaviors.pyc", line 196, in event_caret
  File "NVDAObjects\IAccessible\__init__.pyc", line 1491, in event_caret
  File "NVDAObjects\__init__.pyc", line 1226, in event_caret
  File "review.pyc", line 174, in handleCaretMove
  File "documentBase.pyc", line 22, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 116, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 228, in _findContentDescendant
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 30, in __call__
_ctypes.COMError: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (13:24:48.592) - winInputHook (29636):

### Expected behavior:

NVDA should read the characters while arrowing through the text.

#### NVDA version:

NVDA 2021.3.1 installed.

#### Windows version:
Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1466 

#### Name and version of other software in use when reproducing the issue:
Chrome Version: 97.0.4692.71 
Microsoft Edge Version 97.0.1072.62

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, tested back to NVDA 2019.2.1 and also jumped back to 2016.4 (all portable copies).  Same results.

#### If NVDA add-ons are disabled, is your problem still occurring?
No add-ons installed.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes, also reported by multiple users in the NVDA user group: https://nvda.groups.io/g/nvda/message/91754

Workarounds involve moving focus - tab and shift+tab or alt+tab away and back.  The form seems to work as expected after that.

**Comment by Adriani90** [comment] 2023-04-20 19:45
I get this error only when using UIA for Chromium and pressing backspace to delete some text in the search field.

I think this issue is only related to UIA.

**Comment by Adriani90** [comment] 2024-03-29 19:09
The issue described in https://github.com/nvaccess/nvda/issues/13272#issuecomment-1516858935 is only reproducible with UIA in MS Edge, tested with Edge 123 on NVDA 2024.1 RC1. Following error is written to the log:



```
IO - inputCore.InputManager.executeGesture (20:05:57.799) - winInputHook (18580):
Input: kb(laptop):backspace
ERROR - scriptHandler.executeScript (20:05:57.804) - MainThread (11456):
error executing script: <bound method EditableText.script_caret_backspaceCharacter of <NVDAObjects.Dynamic_ChromiumUIAEditableTextWithAutoSelectDetectionUIA object at 0x04FFFFD0>> with gesture 'Rücktaste'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "editableText.pyc", line 282, in script_caret_backspaceCharacter
  File "editableText.pyc", line 264, in _backspaceScriptHelper
  File "NVDAObjects\UIA\web.pyc", line 190, in move
  File "NVDAObjects\UIA\web.pyc", line 181, in _collapsedMove
  File "NVDAObjects\UIA\web.pyc", line 148, in _moveToEdgeOfReplacedContent
  File "baseObject.pyc", line 41, in __get__
  File "NVDAObjects\UIA\web.pyc", line 119, in _get_UIAElementAtStartWithReplacedContent
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

**Comment by Adriani90** [comment] 2024-04-21 21:38
Closing as works for me, this affects now only backspace and that case is covered already in #12033.

**Closed by Adriani90** 2024-04-21 21:38 UTC
Labels: close/worksforme, api/uia
