### ISSUE TITLE
Synthesizer: NVDA reports number When the Chinese character is encountered by espeak

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#7787] opened 2017-11-20 18:48 UTC
Hi,
Thanks Zhi-chao Wu points out this issue via email.

### Steps to reproduce:
1. Open general settings (NVDA+control+g), and change language to Chinese traditional (Taiwan) zh_TW.
2. Open Synthesizer (NVDA+control+s), and choose eSpeak.
3. Read Chinese characters "鋼鐵人馬斯克：從特斯拉到太空探索，大夢想家如何創造驚奇的未來"

### Expected behavior:
NVDA reads smoothly.

### Actual behavior:
NVDA reads "鋼1鐵3人4馬3斯1克4：從2特4斯1拉1到4太4空1探4索3，大4夢4想3家1如2何2創4造4驚1奇2的5未4來2."

### System configuration:
NVDA version: 2017.4rc1
NVDA Installed or portable: Installed
Windows version: Windows 10 Version 1709

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
No.

**Comment by ehollig** [comment] 2017-11-20 23:01
I am not able to reproduce this using the latest Master of NVDA when I select Chinese from the voice settings, although, I do not know Chinese myself. Both lines of text sound different to me. It is possible this has to be fixed in ESpeak, and you may want to create an [espeak-ng/espeak-ng issue](https://github.com/espeak-ng/espeak-ng).

**Comment by surfer0627** [comment] 2017-11-21 03:38
@ehollig
> It is possible this has to be fixed in ESpeak, and you may want to create an espeak-ng/espeak-ng issue.

Agree, I'll try to create an issue. At the same time, Could you please consider the following thing: In 2017.4, if NVDA use eSpeak NG 1.49.2, it will be hard for Chinese user to use it (user don't understand what did espeak say). 
Perhaps, it is not possible to downgrade to eSpeak NG to 1.49.1. Although, this version works well with NVDA2017.3. The reason is that Espeak-ng 1.49.2, resolving some issues with producing release builds.

> I am not able to reproduce this using the latest Master of NVDA when I select Chinese from the voice settings.

Could you please confirm that if it could be reproduced when UI language change to zh-TW? I could reproduce this in master-14625 and 2017.4rc1. 
Thanks.

**Comment by Mary5958** [comment] 2017-11-21 17:16
I wonder if the Chinese Cantonese dictionary (zhy_dict) is available there or not? I remember there were some problems with the particular dictionary that the eSpeak-ng update for NVDA couldn't be built properly for some reason so the file was excluded then. One workaround for now would be copying the zhy_dict file from an older version that worked into the NVDA\synthDrivers\espeak-ng-data folder of the new version. But something needs to be done eventually so that all languages could be included properly.

**Comment by ehollig** [comment] 2017-11-21 20:35
CC @michaelDCurran @feerrenrut

**Comment by dingpengyu** [comment] 2017-11-22 12:53
Hello, I'm a NVDA user from mainland China. My friend and I have the same problem in Taiwan. The content is as follows:
Hi,
Thanks Zhi-chao Wu points out this issue via email.
Steps to reproduce:
Open general settings (NVDA+control+g), and change language to Chinese traditional (Taiwan) zh_TW.
Open Synthesizer (NVDA+control+s), and choose espeak.
Read Chinese characters "鋼鐵人馬斯克：從特斯拉到太空探索，大夢想家如何創造驚奇的未來"
Expected behavior:
NVDA reads smoothly.
Actual behavior:
NVDA reads "鋼1鐵3人4馬3斯1克4：從2特4斯1拉1到4太4空1探4索3，大4夢4想3家1如2何2創4造4驚1奇2的5未4來2."
System configuration:
NVDA version: 2017.4rc1
NVDA Installed or portable: Installed
Windows version: Windows 10 Version 1709
Other questions:
Does the issue still occur after restarting your PC?
Yes.
Have you tried any other versions of NVDA?
No.
ps
In fact, this may not be the problem of NVDA. It may be espeak Chinese bug, espeak Chinese has long been no maintenance. The best way is to send a git to the expeak warehouse in issue.

**Comment by Brian1Gaff** [comment] 2017-11-22 16:08
I cannot obviously say anything about Chinese, but could this be due to the 
same issues we had with that symbol stopping Espeak earlier in the release 
cycle after this version of Espeak was merged in? Might it not be prudent to 
unmerge it and put the old version back for this release?

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by surfer0627** [comment] 2017-11-29 09:47
Now, Valdisvi have pushed fix to repository. But, I do not know how to test it without using NVDA. Could someone help?
Thanks.

**Comment by ehollig** [comment] 2017-11-29 15:05
@valdisvi says you can test it online by going to http://odo.lv/Espeak

**Comment by surfer0627** [comment] 2017-11-30 06:20
@ehollig, Thank you for the reply. I visit this page. Actually, I do not know how to test it online. It seems that this page is in Latvian.

**Comment by valdisvi** [comment] 2017-11-30 08:59
Language switch is in upper right corner of the page.
Or, pass it in link: http://odo.lv/Espeak?language=en

Valdis

**Comment by surfer0627** [comment] 2017-12-01 02:01
Hi @ehollig @valdisvi,
After testing, this issue has been resolved. Thanks a lot.

**Comment by ehollig** [comment] 2017-12-01 02:15
Thank you @surfer0627 for confirming. Closing this issue

**Closed by ehollig** 2017-12-01 02:15 UTC
