### ISSUE TITLE
Error in translation into Portuguese Brazil option graphics in element list

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9215] opened 2019-01-30 17:07 UTC
### Steps to reproduce:
Create a spreadsheet in excel where you have a chart.
Open the list of items with nvda + f7.
Walk with taboos until
the list with the type option buttons.
Look up with the arrow below the graphic type.
### Actual behavior:
There is no graphic (gráfico) option button.
The radio button that chooses and selects a chart is named as a folder (pasta).
### Expected behavior:
There should be an option button named as a chart.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
2018.4.1

#### Windows version:
10 16299
#### Name and version of other software in use when reproducing the issue:
excel 2016
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2019-01-30 19:32
Cc: @ruefontes

**Comment by ruifontes** [comment] 2019-01-31 12:22
I am a member of european portuguese team...
I have forwarded the message to the brazilian team...

Rui Fontes


Às 19:32 de 30/01/2019, Adriani90 escreveu:

**Comment by Adriani90** [comment] 2019-01-31 13:07
Thanks Rui. If you know someone from the brazilian portuguese Team who has a github account, could you please mark one Person in this issue so we get a Status update when the issue is solved?

**Comment by Adriani90** [comment] 2020-05-03 10:49
No updates on this since long time, I guess the issue has been solved now by the translators. If not, please contact them via the translators mailing list. Closing this for now.

**Closed by Adriani90** 2020-05-03 10:49 UTC
