### ISSUE TITLE
[nvda] No speaks after selecting the correct word in OpenOffice Writer.

### ISSUE THREAD

**Issue by lowvisiontek** [nvaccess/nvda#5823] opened 2016-03-18 22:07 UTC
This has been observed and tested for quite long time. Everytime I
proof reading in the openoffice Writer file. Right after I selected
the appropriate word the nvda stops speaking. In order to get resume
its speaks I usually minimize the said application. Not sure if this
is the same as with the Microsoft Word or any  third party text editor as
well.

**Comment by Brian1Gaff** [comment] 2016-03-19 16:03
Just out of interest, do you have another application running at the same time when this happens. as that was my experience and the reason I went back to word, that and the lack of a complete say all.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
  ----- Original Message ----- 
  From: lowvisiontek 
  To: nvaccess/nvda 
  Sent: Friday, March 18, 2016 10:07 PM
  Subject: [nvda] [nvda] No speaks after selecting the correct word in OpenOffice Writer. (#5823)


  This has been observed and tested for quite long time. Everytime I
  proof reading in the openoffice Writer file. Right after I selected
  the appropriate word the nvda stops speaking. In order to get resume
  its speaks I usually minimize the said application. Not sure if this
  is the same as with the Microsoft Word or any third party text editor as
  well.

**Comment by lowvisiontek** [comment] 2016-03-19 20:25
No, typically when I do and creating document I make sure that I run one 
application in this case the only that was open is just an OpenOffice 
Writer. This event has been experience way back when my Pc was into Win 
7after  I fully decided to upgraded to Win 10 operating system.  It's 
kinda annoying specially when you are do some proof reading to one 
particular file. But, this was never happen if I write email messages in 
Mozilla Thunderbird.I was working and I could select the the correct 
word with no problem. Not sure what the differences but that is the analogy.

Robert Mendoza

**Comment by jcsteh** [comment] 2016-03-22 14:49
I'm not sure how you're selecting the correct word. Are you using the spell checker, the context menu or something else? Please provide thorough steps to reproduce; e.g. what you typed, what you then pressed, what you expected and what happened instead.

**Comment by lowvisiontek** [comment] 2016-03-22 22:42
I will site you an example  though this the same logic applies into it. 
usually nvda announces or report if there is mispelled word after you 
typed then, OpenOffice Writer automatically  highlight the mispelled 
words. And, by placing the cursor or focus to the first letter I usually 
right-click into that word and slect the correct word in the dialog box 
in order to replace the  mispelled word.   That is the time nvda freezes 
or reading as I type. In order to continue my typing I usually minimize 
the OpenOffice Writer. Here is a simple example: Let say you are going 
to type a sentence. e.g. We went to cuty. . The word cuty automatically 
highlight by default by Openoffice Writer.which means cuty spells an 
errors and nvda will report it. Then, replace it with correctword of 
city. Hope this helps.

Robert Mendoza

**Comment by jcsteh** [comment] 2016-04-05 10:19
Okay. So you're referring to the context menu.

This is due to a bug in OpenOffice which I reported over two years ago. See [OpenOffice bug 123631](https://bz.apache.org/ooo/show_bug.cgi?id=123631). That bug refers to Calc, but the root cause is the same. We're already tracking this as #4004, so closing as duplicate.

**Closed by jcsteh** 2016-04-05 10:19 UTC
Labels: duplicate
