### ISSUE TITLE
Weird effects on recent alpha snaps with Windows 7 on GUI

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#15146] opened 2023-07-15 09:47 UTC
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.

Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:

- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by XLTechie** [comment] 2023-07-15 19:19
Duplicate of #15147.  Please close.

**Comment by Brian1Gaff** [comment] 2023-07-16 07:37
Am I allowed to close tickets? I could never figure outhow to do that. I'd 
rather somebody else did it in case I make a pigs ear of it!
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message ----- 
From: "Luke Davis" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Brian Gaff" ***@***.***>; "Author" 
***@***.***>
Sent: Saturday, July 15, 2023 8:19 PM
Subject: Re: [nvaccess/nvda] Weird effects on recent alpha snaps with 
Windows 7 on GUI (Issue #15146)

**Closed** 2023-07-16 23:26 UTC

**Comment by XLTechie** [comment] 2023-07-17 00:58
@Brian1Gaff, while this one has been closed, for your future reference: 
immediately before the button you pressed to submit your comment, was a button 
to close it. Push it. It is closed. No pig, no ear.
