### ISSUE TITLE
NVDA is not reading emojy on windows 11 if you try to insert emojy by key combination "windows +dot"

### ISSUE THREAD

**Issue by abhijitkasbe** [nvaccess/nvda#13183] opened 2021-12-21 05:11 UTC
### Additional contextthe things those were available on windows 10 should be carry forward on windows 11.
NVDA is not reading emoji on windows 11.

**Comment by OzancanKaratas** [comment] 2021-12-21 12:35
Duplicate of #13104.

@josephsl, Please link this issue to #13107 or close it directly.

**Closed** 2021-12-21 13:40 UTC
