### ISSUE TITLE
NVDA Randomly Stops Talking, May Not Be Crash

### ISSUE THREAD

**Issue by jhomme** [nvaccess/nvda#8162] opened 2018-04-11 11:10 UTC
I need help diagnosing. I never know when this will happen. NVDA randomly stops talking. I can usually restart it with the keyboard shortcut. I tried to follow the steps in the Wiki. I couldn't locate a dump. I blame whatever Microsoft did in the last Windows update, but that doesn't help diagnose. Please help.

**Comment by Brian1Gaff** [comment] 2018-04-12 07:33
Is there any pattern at all, like always when a certain app is running or on 
certain synths?

I have to say I've not seen this on any version for a time in windows 7, 
though the last windows update seems to have screwed up my scanner 
software... grin, nvda is still mostly OK.

Brian

**Comment by jhomme** [comment] 2018-04-16 22:55
Hi,
This is happening less now. It is not related to Outlook. I know this because for a while now, I've stopped using Outlook and am using Windows 10 Mail and Calendar. I am running with one add-on enabled: the latest Code Factory voices for Eloquence and Vocalizer. I've tried to follow the instructions for finding a dump file and can't find one. I wonder if for whatever reason NVDA is just stopping speaking. I will switch to the ESpeak synthesizer and see if I get the same results now.

Is there anything else I can do to try to figure this out?

**Comment by feerrenrut** [comment] 2018-04-17 05:55
First please set your logging level to "Debug". Immediately after the next time this happens make a copy of `nvda.log` and `nvda-old.log`. You can get to to these files by pressing `windows+r` and typing `%temp%` and pressing enter. This folder will have several other files in it too.

Please be aware that these files contain a full log of all typed text and output speech from NVDA, feel free to inspect and redact any content, for example passwords, before attaching it to this issue.

**Comment by jhomme** [comment] 2018-04-20 18:40
Hi,
If NVDA stops talking, and it really has not crashed, and I restart
it, does it put the log files in the temp folder? The issue just
happened, and I did not see those files. What else can I check?

Thanks.

Jim

On 4/17/18, Reef Turner <notifications@github.com> wrote:
> First please set your logging level to "Debug". Immediately after the next
> time this happens make a copy of `nvda.log` and `nvda-old.log`. You can get
> to to these files by pressing `windows+r` and typing `%temp%` and pressing
> enter. This folder will have several other files in it too.
>
> Please be aware that these files contain a full log of all typed text and
> output speech from NVDA, feel free to inspect and redact any content, for
> example passwords, before attaching it to this issue.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/8162#issuecomment-381854205


-- 
==========

Jim Homme
http://www.jimhommewebdev.com
Twitter: @jimhomme
Facebook: http://www.facebook.com/jimhomme
LinkedIn: https://www.linkedin.com/in/jimhomme

**Comment by jhomme** [comment] 2018-04-23 10:14
> Hi,
Next time this happens, I’ll fire up another screen reader and try again to find the logs.

**Comment by fernando-jose-silva** [comment] 2018-04-23 16:02
I'm also encountering random crashes on nvda, specifically on a windows 7 64bits machine.
Today I was finally able to take the previous log of the nvda, it follows if it is útio:
IO - inputCore.InputManager.executeGesture (12:46:16.194):
Input: kb(laptop):NVDA+f7
DEBUGWARNING - RPC process 4764 (dwm.exe) (12:46:19.680):
Thread 2136, build\x86_64\remote\injection.cpp, inproc_winEventCallback, 66:
SetWindowsHookEx with WH_GETMESSAGE failed, GetLastError returned 5

DEBUGWARNING - RPC process 4764 (dwm.exe) (12:46:19.694):
Thread 2136, build\x86_64\remote\injection.cpp, inproc_winEventCallback, 69:
SetWindowsHookEx with WH_CALLWNDPROC failed, GetLastError returned 5

IO - inputCore.InputManager.executeGesture (12:46:19.778):
Input: kb(laptop):NVDA+t
DEBUGWARNING - watchdog._watcher (12:46:19.900):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 473, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 444, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1136, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1210, in _set_selection
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 311, in _get_NVDAObjectAtStart
  File "virtualBuffers\__init__.pyc", line 176, in _getNVDAObjectFromOffset
  File "virtualBuffers\__init__.pyc", line 157, in _getFieldIdentifierFromOffset

WARNING - watchdog._watcher (12:46:34.901):
Core frozen in stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 473, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 444, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1136, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1210, in _set_selection
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 311, in _get_NVDAObjectAtStart
  File "virtualBuffers\__init__.pyc", line 176, in _getNVDAObjectFromOffset
  File "virtualBuffers\__init__.pyc", line 157, in _getFieldIdentifierFromOffset

WARNING - watchdog._watcher (12:46:49.907):
Core frozen in stack:
  File "nvda.pyw", line 212, in <module>
  File "core.pyc", line 473, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 444, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1136, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1210, in _set_selection
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 311, in _get_NVDAObjectAtStart
  File "virtualBuffers\__init__.pyc", line 176, in _getNVDAObjectFromOffset
  File "virtualBuffers\__init__.pyc", line 157, in _getFieldIdentifierFromOffset

DEBUGWARNING - RPC process 4568 (chrome.exe) (12:46:14.030):
Thread 7760, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 822:
Could not locate node at offset, returning NULL

ERROR - queueHandler.flushQueue (12:47:03.438):
Error in func _loadBufferDone from eventQueue
Traceback (most recent call last):
  File "queueHandler.pyc", line 50, in flushQueue
  File "virtualBuffers\__init__.pyc", line 442, in _loadBufferDone
  File "browseMode.pyc", line 1136, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1210, in _set_selection
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 311, in _get_NVDAObjectAtStart
  File "virtualBuffers\__init__.pyc", line 176, in _getNVDAObjectFromOffset
  File "virtualBuffers\__init__.pyc", line 157, in _getFieldIdentifierFromOffset
WindowsError: [Error 1726] Falha na chamada de procedimento remoto
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:47:03.671):
accRole failed: (-2147023174, 'O servidor RPC n\xe3o est\xe1 dispon\xedvel.', (None, None, None, 0, None))
IO - speech.speak (12:47:03.671):
Speaking [u'chrome']
DEBUG - appModuleHandler.cleanup (12:47:03.980):
application chrome closed
DEBUG - appModuleHandler.cleanup (12:47:03.980):
application excel closed
DEBUG - appModuleHandler.cleanup (12:47:03.980):
application firefox closed
DEBUG - treeInterceptorHandler.killTreeInterceptor (12:47:04.000):
Killed treeInterceptor: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x09537C70>
DEBUG - treeInterceptorHandler.killTreeInterceptor (12:47:04.000):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x096670D0>
DEBUG - treeInterceptorHandler.killTreeInterceptor (12:47:04.000):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x094AD5D0>
WARNING - eventHandler._EventExecuter.next (12:47:04.010):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.objloc module due to unsupported kwargs: {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
IO - tones.beep (12:47:04.010):
Beep at pitch 559.533333333, for 40 ms, left volume 15, right volume 15
IO - speech.speak (12:47:04.051):
Speaking [u'Lista de Elementos  di\xe1logo']
IO - speech.speak (12:47:04.061):
Speaking [u'\xe1rvore']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (12:47:05.940):
accRole failed: (-2147023174, 'O servidor RPC n\xe3o est\xe1 dispon\xedvel.', (None, None, None, 0, None))
DEBUG - appModuleHandler.cleanup (12:47:06.180):
application lync closed
WARNING - eventHandler._EventExecuter.next (12:47:06.180):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.objloc module due to unsupported kwargs: {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
IO - speech.speak (12:47:06.180):
Speaking [u'Caixa de Entrada - G Suite - fernando.silva@abril.com.br - Outlook']
IO - speech.speak (12:47:06.250):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (12:47:06.280):
oleacc.AccessibleObjectFromEvent with window 132198, objectID 7 and childID 0: [Error -2147467259] Erro não especificado
IO - speech.speak (12:47:07.470):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:07.700):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:07.921):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:08.601):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:09.180):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:09.480):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - speech.speak (12:47:09.710):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
IO - inputCore.InputManager.executeGesture (12:47:10.561):
Input: kb(laptop):alt+tab
WARNING - eventHandler._EventExecuter.next (12:47:10.591):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.objloc module due to unsupported kwargs: {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
IO - tones.beep (12:47:10.591):
Beep at pitch 551.466666667, for 40 ms, left volume 15, right volume 15
IO - speech.speak (12:47:10.601):
Speaking [u'Lista de Elementos  \xedcone  2 de 3']
WARNING - eventHandler._EventExecuter.next (12:47:10.611):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.objloc module due to unsupported kwargs: {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
IO - tones.beep (12:47:10.611):
Beep at pitch 551.466666667, for 40 ms, left volume 15, right volume 15
IO - speech.speak (12:47:10.631):
Speaking [u'Lista de Elementos  \xedcone  2 de 3']
DEBUG - appModuleHandler.cleanup (12:47:11.413):
application outlook closed
WARNING - eventHandler._EventExecuter.next (12:47:11.433):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.objloc module due to unsupported kwargs: {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
IO - tones.beep (12:47:11.433):
Beep at pitch 431.2, for 40 ms, left volume 12, right volume 18
IO - speech.speak (12:47:11.483):
Speaking [u'di\xe1logo  1 programa ainda precisa ser fechado:\nPara fechar o programa que est\xe1 impedindo que o Windows seja\ndesligado, clique em Cancelar e feche o programa.']
IO - speech.speak (12:47:11.483):
Speaking [u'Cancelar  bot\xe3o  Alt+c']
DEBUG - fileUtils.FaultTolerantFile (12:47:11.542):
C:\Users\a50596\AppData\Roaming\nvda\nvda.ini9hgwfk.tmp
INFO - config.ConfigManager.save (12:47:11.582):
Base configuration saved
INFO - core.onEndSession (12:47:12.663):
Windows session ending

**Comment by jhomme** [comment] 2018-04-29 12:55
Hi,
Here is a log that I saved after NVDA froze for a while, then recovered. Here is my memory of what lead up to it.

Yesterday afternoon, I was doing some work, when I decided to upgrade my Sirius XM package. I had Spotify, Firefox, Excel, and EdSharp, my text editor, open. When I was talking to the customer service person, I opened a second instance of Firefox. I had forgotten that I had the first one open. I reset my password. Then I put my computer to sleep.

This morning, I woke it up. All of the apps were still open. When my computer woke up, it was sitting at the Sirius XM site. I found that NVDA was sluggish, so I restarted it. The attached log picks up from that point. In the middle of the log is a freeze. NVDA recovered from it.
[nvda.log](https://github.com/nvaccess/nvda/files/1958739/nvda.log)

**Comment by jhomme** [comment] 2018-04-29 16:04
This is another log after waking up the computer. This time NVDA did not recover. I used Narrator to save the log. While I was using Narrator, NVDA started talking again, but I had limited keyboard use. I restarted NVDA, used the pass-through key, stopped Narrator, then opened GitHub to write this.
[nvda2.log](https://github.com/nvaccess/nvda/files/1958918/nvda2.log)

**Comment by jhomme** [comment] 2018-07-07 14:38
Hi,
I think that I may have captured a log that shows what the problem may be. Here is how it is set up and what happens.

1. Get the latest copy of the CodeFactory Eloquence and Vocalizer voices.
2. Disable all add-ons except the CodeFactory one.
3. Choose Eloquence as your synthesizer.

In this log, I believe it is showing that NVDA is restarting, but not finding the Eloquence synthesizer. When NVDA does not find it, NVDA chooses the silent speech synthesizer. This, I believe, is why I thought NVDA was crashing, and why I could not find an ol
[nvda-2018-07-07.log](https://github.com/nvaccess/nvda/files/2172836/nvda-2018-07-07.log)
[nvda-2018-07-07.log](https://github.com/nvaccess/nvda/files/2172838/nvda-2018-07-07.log)

d log.

**Comment by Adriani90** [comment] 2019-05-02 22:27
@jhomme are you still having this problem in NVDA 2019.1.1 and Windows 10 1809 Update?

**Comment by Adriani90** [comment] 2019-08-22 22:37
@jhomme this issue occured usually when another application crashed. At that point NVDA becase silent and recovered after that specific application has been terminated. Are you sure there was no application crashing while NVDA became silent?

**Comment by Adriani90** [comment] 2019-08-22 22:37
how is it now in NVDA 2019.2?

**Comment by Adriani90** [comment] 2019-12-20 19:01
@jhomme last reminder before closing this issue as abandoned. Is it still reproducible for you in NVDA 2019.3 Beta 1?

**Comment by seanbudd** [comment] 2023-01-09 05:05
Closing this as stale/abandoned

**Closed by seanbudd** 2023-01-09 05:05 UTC
