### ISSUE TITLE
NVDA key Caps Lock ceases functioning

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#6752] opened 2017-01-18 07:31 UTC
The NVDA modifier key (Caps Lock in my case, though this issue does apply to other modifiers too) often stops responding to NVDA key commands after a long freeze. Please find below the conclusive log of my previous session of NVDA which I exit after the NVDA key stopped working after I reproduced a recently reported OCR add-on freeze:

DEBUGWARNING - RPC process 2396 (nvda_slave.exe) (11:30:21):
Python warning:
C:\Program Files (x86)\NVDA\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
INFO - core.main (11:30:21):
Exiting
DEBUG - core._terminate (11:30:21):
Terminating updateCheck
DEBUG - core._terminate (11:30:21):
Terminating watchdog
DEBUG - core._terminate (11:30:21):
Terminating global plugin handler
DEBUG - core._terminate (11:30:21):
Terminating gui
INFO - config.ConfigManager.save (11:30:21):
Base configuration saved
DEBUG - core._terminate (11:30:21):
Terminating treeInterceptorHandler
DEBUG - treeInterceptorHandler.killTreeInterceptor (11:30:21):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x04A3B490>
DEBUG - treeInterceptorHandler.killTreeInterceptor (11:30:21):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0498FC90>
DEBUG - treeInterceptorHandler.killTreeInterceptor (11:30:21):
Killed treeInterceptor: <NVDAObjects.window.winword.WordDocumentTreeInterceptor object at 0x04BA3650>
DEBUG - treeInterceptorHandler.killTreeInterceptor (11:30:21):
Killed treeInterceptor: <virtualBuffers.adobeAcrobat.AdobeAcrobat object at 0x04984090>
DEBUG - core._terminate (11:30:21):
Terminating IAccessible support
DEBUG - core._terminate (11:30:21):
Terminating UIA support
DEBUGWARNING - _UIAHandler.UIAHandler.terminate (11:30:22):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (11:30:22):
Terminating winConsole support
DEBUG - core._terminate (11:30:22):
Terminating Java Access Bridge support
DEBUG - core._terminate (11:30:22):
Terminating app module handler
DEBUG - core._terminate (11:30:22):
Terminating NVDAHelper
DEBUG - core._terminate (11:30:22):
Terminating touchHandler
DEBUG - core._terminate (11:30:22):
Terminating keyboard handler
DEBUG - core._terminate (11:30:22):
Terminating mouseHandler
ERROR - stderr (11:30:22):
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyo", line 801, in __bootstrap_inner
  File "threading.pyo", line 754, in run
  File "winInputHook.pyo", line 73, in hookThreadFunc
OSError: could not unregister key hook 131647
DEBUG - core._terminate (11:30:22):
Terminating inputCore
DEBUG - core._terminate (11:30:22):
Terminating brailleInput
DEBUG - core._terminate (11:30:22):
Terminating braille
DEBUG - core._terminate (11:30:22):
Terminating speech
DEBUG - core._terminate (11:30:22):
Terminating addonHandler
DEBUG - core.main (11:30:23):
core done
INFO - __main__ (11:30:23):
NVDA exit

P.S. By saying that the modifier key stopped working, I mean that pressing Caps Lock toggles its state, pressing it in conjunction with other keys to issue NVDA keyboard shortcuts does not happen, etc.

**Comment by jcsteh** [comment] 2017-01-18 23:53
Duplicate of #2003. (The exit log indicates that the key hook was prematurely removed by Windows.)

**Closed by jcsteh** 2017-01-18 23:53 UTC
Labels: duplicate
