### ISSUE TITLE
Windows 10 build 15025 problem in switching the Russian and English languages in Microsoft edge.

### ISSUE THREAD

**Issue by Nikita34196** [nvaccess/nvda#6855] opened 2017-02-08 07:35 UTC
Hello. When you switch keyboard layouts in microsoft edge nvda continues to refer to the symbols on the keyboard recruited which was originally. helps you switch between Windows.
[nvda.txt](https://github.com/nvaccess/nvda/files/759959/nvda.txt)

and when you open a Microsoft edge nvda publishes sound error.

```
ERROR - RPC process 5708 (MicrosoftEdgeCP.exe) (07:12:20):
Thread 7268, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook failed with 9
```

**Comment by josephsl** [comment] 2017-02-08 16:27
Hi,

Does this happen if you run Narrator instead of NVDA? If so, sounds like it's something Microsoft will need to look into. Thanks.

**Comment by gdata1** [comment] 2017-02-08 16:45
with the Narrator the same situation.

**Comment by josephsl** [comment] 2017-02-08 16:55
Hi, in this case, please file a feedback with Microsoft via Feedback Hub app. Thanks.

**Comment by gdata1** [comment] 2017-02-08 17:24
Hello. I wrote to the Center reviews microsoft.

**Comment by leonardder** [comment] 2018-02-17 08:42
I'm also getting the MH_CreateHook failed with 9 quite a lot of times when I start Edge, and once in a second when Edge is focused. I have no idea whether this has to do with the keyboard layout I have in use (Dutch Netherlands, United Stated International).

**Comment by gdata1** [comment] 2018-02-17 09:11
Hello. I'm not getting any errors when switching. Just Nvda doesn't tell me which language I switched to.

**Comment by leonardder** [comment] 2018-03-06 14:13
@gdata1: Are you saying you aren't getting MH_CreateHook failed with 9 errors any more?

**Comment by leonardder** [comment] 2018-03-06 14:23
@gdata1: Are you saying you aren't getting MH_CreateHook failed with 9 errors any more?

Let´s devote #6989 to the issue that keyboard layout changes aren´t reported when in Edge. As for the MH?CreateHook issue, that seems different and unrelated.

**Comment by gdata1** [comment] 2018-03-07 03:29
I can confirm this problem with the narrator as well.

**Comment by leonardder** [comment] 2018-04-10 04:01
I added some debugging as part of #8142, and the errors I get now look like this:

```
ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:26.951):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function CreateCompatibleDC in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.012):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function SelectObject in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.063):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function DeleteDC in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.115):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function FillRect in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.167):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function DrawFocusRect in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.217):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function BeginPaint in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.267):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function BitBlt in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.318):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function StretchBlt in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.368):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function GdiTransparentBlt in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.421):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function PatBlt in module GDI32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.483):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScrollWindow in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.536):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScrollWindowEx in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.595):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function DestroyWindow in module USER32.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.648):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScriptStringAnalyse in module USP10.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.701):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScriptStringFree in module USP10.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.760):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScriptStringOut in module USP10.dll failed with 9

ERROR - RPC process 11884 (MicrosoftEdge.exe) (05:57:27.813):
Thread 11848, build\x86_64\remote\apiHook.cpp, apiHook_hookFunction, 109:
MH_CreateHook for function ScriptTextOut in module USP10.dll failed with 9
```

**Comment by Adriani90** [comment] 2020-04-25 00:16
When I am in Edge Chromium 81 and try to switch languages with alt+shift, NVDA now totally crashes, even the the log is not completely written. Here is a part from the nvda_old.log after NVDA chrashed.

```
IO - inputCore.logTimeSinceInput (02:06:56.369) - MainThread (10748):
1.268 sec since input
IO - speech.speak (02:06:56.369) - MainThread (10748):
Speaking ['Koreanisch - Microsoft-IME', 'Microsoft-IME']
IO - inputCore.logTimeSinceInput (02:06:56.599) - MainThread (10748):
1.498 sec since input
IO - speech.speak (02:06:56.599) - MainThread (10748):
Speaking ['Rumänisch (Rumänien) - Rumänisch (Standard)-Tastatur', 'Rumänisch (Standard)-Tastatur']
IO - inputCore.logTimeSinceInput (02:06:57.264) - MainThread (10748):
2.164 sec since input
IO - speech.speak (02:06:57.264) - MainThread (10748):
Speaking ['Englisch (Vereinigte Staaten) - US-Tastatur', 'US-Tastatur']
IO - inputCore.logTimeSinceInput (02:06:57.839) - MainThread (10748):
2.739 sec since input
IO - speech.speak (02:06:57.839) - MainThread (10748):
Speaking ['Deutsch (Deutschland) - Deutsch-Tastatur', 'Deutsch-Tastatur']
DEBUG - config.ConfigManager._triggerProfileEnter (02:06:58.619) - MainThread (10748):
Activating triggered profile msedge
DEBUG - synthDriverHandler.SynthDriver.loadSettings (02:06:58.629) - MainThread (10748):
Loaded changed settings for SynthDriver ibmeci
IO - inputCore.logTimeSinceInput (02:06:58.639) - MainThread (10748):
3.539 sec since input
IO - speech.speak (02:06:58.639) - MainThread (10748):
Speaking ['Windows 10 build 15025 problem in switching the Russian and English languages in Microsoft edge. · Issue #6855 · nvaccess/nvda - Persönlich – Microsoft\u200b Edge', 'Fenster']
IO - inputCore.InputManager.executeGesture (02:06:59.229) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:00.199) - winInputHook (11032):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (02:07:00.619) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:00.922) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:01.179) - winInputHook (11032):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (02:07:02.009) - winInputHook (11032):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (02:07:02.189) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:02.479) - winInputHook (11032):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (02:07:03.089) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:04.059) - winInputHook (11032):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (02:07:04.339) - winInputHook (11032):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (02:07:04.529) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:04.769) - winInputHook (11032):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (02:07:05.019) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:05.329) - winInputHook (11032):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (02:07:05.539) - winInputHook (11032):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (02:07:05.819) - winInputHook (11032):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (02:07:06.309) - winInputHook (11032):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (02:07:06.614) - winInputHook (11032):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (02:07:06.749) - winInputHook (11032):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (02:07:06.959) - winInputHook (11032):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (02:07:07.429) - winInputHook (11032):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (02:07:08.744) - winInputHook (11032):
Input: kb(laptop):alt+tab
DEBUGWARNING - watchdog._watcher (02:07:08.889) - watchdog (3460):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1032, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 469, in speakObject
  File "speech\__init__.pyc", line 537, in getObjectSpeech
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1115, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 70 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 678, in _getTextWithFieldsForUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

WARNING - watchdog._watcher (02:07:23.947) - watchdog (3460):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1032, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 469, in speakObject
  File "speech\__init__.pyc", line 537, in getObjectSpeech
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1115, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 72 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 594, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 424, in _getControlFieldForObject
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

WARNING - watchdog._watcher (02:07:38.964) - watchdog (3460):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1032, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 469, in speakObject
  File "speech\__init__.pyc", line 537, in getObjectSpeech
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1115, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 70 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 664, in _getTextWithFieldsForUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

WARNING - watchdog._watcher (02:07:53.979) - watchdog (3460):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1032, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 469, in speakObject
  File "speech\__init__.pyc", line 537, in getObjectSpeech
  File "speech\types.pyc", line 49, in _flattenNestedSequences
  File "speech\types.pyc", line 49, in <genexpr>
  File "speech\__init__.pyc", line 1115, in getTextInfoSpeech
  File "NVDAObjects\UIA\__init__.pyc", line 716, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 686, in _getTextWithFieldsForUIARange
  [Previous line repeated 66 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 678, in _getTextWithFieldsForUIARange
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
```

**Comment by Adriani90** [comment] 2020-04-25 00:17
I think this issue is quite severe, might be related to UIA.
cc: @josephsl, @michaelDCurran

**Comment by josephsl** [comment] 2020-04-25 00:27
Hi, if this is still happening in Edge 81, then we should consider this, otherwise I propose closing and recommending a reopen if the problem persists. Besides, build 15025 is too old (an Insider Preview); the closest is 15063 (Version 1703) but it is out of support. Thanks.

**Comment by Adriani90** [comment] 2020-04-25 00:42
Hi, as I said, I tested in Edge Chromium 81.

Windows 1909 Update

NVDA Version: alpha-20045,a335297e

Thanks.

 

 

Von: Joseph Lee <notifications@github.com> 
Gesendet: Samstag, 25. April 2020 02:28
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] Windows 10 build 15025 problem in switching the Russian and English languages in Microsoft edge. (#6855)

 

Hi, if this is still happening in Edge 81, then we should consider this, otherwise I propose closing and recommending a reopen if the problem persists. Besides, build 15025 is too old (an Insider Preview); the closest is 15063 (Version 1703) but it is out of support. Thanks.

**Comment by Adriani90** [comment] 2023-03-01 19:06
I am testing with Edge Chromium 110.0.1587.57, NVDA last alpha version and Windows 11. The crash is not occuring anymore. I think this is solved meanwhile. I am closing this as works for me but please feel free to comment in case you are still having this issue. We can reopen this one then.

**Closed by Adriani90** 2023-03-01 19:06 UTC
Labels: close/worksforme, p2, blocked, app/edge
