### ISSUE TITLE
Nvda sometimes stops reading in Microsoft Edge

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7912] opened 2018-01-16 20:25 UTC
Hello. The problem is not constant, but I will try to describe it.
Sometimes Nvda hangs in Microsoft edge in other applications running as usual. When this happens Nvda reads only the title of the window and everything. Up-down arrows and tab do not work If you move through object navigation, Edge will be read.
After rebooting the NVDA problem disappears. windows 10 1709 17074 and windows 10 1709 16299. NVDA next-14783,eda951dd

**Comment by feerrenrut** [comment] 2018-01-16 23:48
Could you please attach a debug level log file to this issue? This might help us to track down the cause. If you are unsure, please see the [wiki page on collecting log files](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps)

**Comment by gdata1** [comment] 2018-01-17 05:19
Ok. As soon as the problem manifests I will do.

**Comment by gdata1** [comment] 2018-01-17 05:35
Now the problem has manifested itself.
[Uploading nvda.txt…]()

**Comment by gdata1** [comment] 2018-01-17 05:37
INFO - __main__ (08:30:49.079):
Starting NVDA
INFO - core.main (08:30:49.246):
Config dir: C:\Users\nikit\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (08:30:49.246):
Loading config: C:\Users\nikit\AppData\Roaming\nvda\nvda.ini
INFO - core.main (08:30:49.338):
NVDA version next-14783,eda951dd
INFO - core.main (08:30:49.338):
Using Windows version 10.0.17074 workstation
INFO - core.main (08:30:49.338):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (08:30:49.338):
Using comtypes version 1.1.3
INFO - external:synthDrivers.RHVoice.SynthDriver.__init__ (08:30:49.582):
Using RHVoice version 0.5
INFO - synthDriverHandler.setSynth (08:30:49.588):
Loaded synthDriver RHVoice
INFO - core.main (08:30:49.588):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (08:30:49.589):
Braille input initialized
INFO - braille.initialize (08:30:49.589):
Using liblouis version 3.3.0
INFO - braille.BrailleHandler.setDisplayByName (08:30:49.591):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (08:30:49.628):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (08:30:49.632):
UIAutomation: IUIAutomation3
INFO - core.main (08:30:50.142):
NVDA initialized

**Comment by Adriani90** [comment] 2020-04-22 17:41
This does not occur in Edge Chromium 81. Closing as works for me since Edge Chromium will be distributed to most users via Windows 10 20H1 update.

**Closed by Adriani90** 2020-04-22 17:41 UTC
Labels: app/edge, bug/appFreeze, close/worksforme

**Comment by Adriani90** [comment] 2020-04-30 21:13
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
