### ISSUE TITLE
Change NVDA Sounds

### ISSUE THREAD

**Issue by Elshara** [nvaccess/nvda#5978] opened 2016-05-20 10:20 UTC
NVDA uses the same default sounds for every action. It would be cool to have a dialogue within NVDA settings where this sound functionality could be changed.

**Comment by bhavyashah** [comment] 2016-05-20 18:11
Hi,
Hi,
In actuality, though the average user may not be aware of this, nor
would be expected to, you can yourself pretty simply change sound
schemes for specific actions.
The NVDA folder under Program Files (or x86 for 64 bit added) has a
subfolder named waves. Replace any file with a .wav file with the same
name with the corresponding action, and restart NVDA.
All the same, a GUI for sound scheme management and its volume control
would be extremely helpful, but I think there is a ticket that covers
that functionality already.
Thanks.
P.S. Though this may be a very subjective viewpoint, and changing
sound schemes it being that most users having got so accustomed to it
would not be the best idea, the browse and focus mode sounds really
should be substituted with more pleasant schemes. I am unsure if I
have already filed a ticket for this or not, won't if I haven't
already, just noting this request here.

On 5/20/16, Elshara Silverheart <notifications@github.com> wrote:
> NVDA uses the same default sounds for every action. It would be cool to have
> a dialogue within NVDA settings where this sound functionality could be
> changed.
>
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5978


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by Elshara** [comment] 2016-05-21 07:01
That's actually the one thing that motivated me to create this ticket,
was the browser sounds specifically.

**Comment by surfer0627** [comment] 2016-05-23 01:15
Duplicated of #1007.

**Comment by feerrenrut** [comment] 2016-10-28 04:41
Closing due to duplicate of #1007. Please continue discussion of this issue there.

**Closed by feerrenrut** 2016-10-28 04:41 UTC
Labels: duplicate
