### ISSUE TITLE
Row Headers are not read

### ISSUE THREAD

**Issue by jmn90** [nvaccess/nvda#11721] opened 2020-10-02 18:35 UTC
I was testing the accessibility on some tables and notice that the behavior of row headers does not seem ok. I tried with the scope and headers attributes and the same result occurred. 
References : 

- https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced

- https://webaim.org/articles/nvda/tables.htm

### Steps to reproduce:

- Visit https://mdn.github.io/learning-area/html/tables/advanced/items-sold-scope.html 

- Navigate the table with the arrow keys until you reach the cell with "56" as content

### Actual behavior:
- NVDA should read the row headers, but only the column headers are read.

### Expected behavior:
- the row headers should be read when the row cell is read

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.2

#### Windows version:
Win 10 Pro , Version 1903

#### Name and version of other software in use when reproducing the issue:
Chrome 85
Firefox 81
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by Adriani90** [comment] 2020-10-06 21:39
This is expected behavior. When you navigate only with arrow keys, NVDA treats the movement from left to right, so it reports the column header. You have to navigate with ctrl+alt+arrow keys (i.e. up and down to hear the row headers or left and right to hear the column headers).
Closing as works for me.

**Closed by Adriani90** 2020-10-06 21:39 UTC
Labels: close/worksforme
