### ISSUE TITLE
Track changes navigation in MS word works only forward but not backwards

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8584] opened 2018-08-01 10:19 UTC
### Steps to reproduce:
1. Open a document with track changes in MS Word
2. Change to browse mode by pressing NVDA+space
3. Press a to navigate between anotations
4. Press shift+a to navigate back to the previous anotation

### Actual behavior:
NVDA says "no further anotation available"

### Expected behavior:
NVDA should navigate to the previous anotation.

#### NVDA Installed/portable/running from source:
Both

#### NVDA version:
2017.3

#### Windows version:
Windows 8.1

#### Name and version of other software in use when reproducing the issue:
MS Word 2010

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment] 2018-08-01 10:19
I will test with NVDA 2018.2.1 and MS Word 2016 later today.

**Comment by Adriani90** [comment] 2018-08-01 18:34
Tested with NVDA 2018.2.1 on Windows 10 and MS Word 2016. The issue is still valid.

**Comment by Qchristensen** [comment] 2018-12-16 21:41
Closing as a duplicate of #7342 (This problem still exists as at 2018.4rc2, but please follow issue #7342 for updates)

**Closed by Qchristensen** 2018-12-16 21:41 UTC
Labels: duplicate
