### ISSUE TITLE
When typing in an empty document in googles docs nvda announces twice the characters typed.

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7940] opened 2018-01-23 19:58 UTC
### Steps to reproduce:
 to reproduce the issue.
Open an empty document in google docs.
Type a text.
### Expected behavior:
Nvda should only announce the typed character once.

### Actual behavior:
All characters you enter are announced twice as they are typed.

### System configuration:
NVDA version:
> Example: next-14799

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM
The option to announce typed characters is enabled on nvda
Windows version:
> Example: Windows 7

Name and version of other software in use when reproducing the issue:
firefox 57

### Other questions:

Does the issue still occur after restarting your PC?
yes

Have you tried any other versions of NVDA?

> Please list them and the result

**Comment by Brian1Gaff** [comment] 2018-01-23 20:33
Just a quicky, Have you tried this in other browsers? Older Firefox or 
Chrome or ie?
 I was trying to use google docs about a week ago and gave up as it seems to 
be so counter intuitive and slow.
 Brian

**Comment by PratikP1** [comment] 2018-01-23 21:51
Everyone trying to use Google Docs, Sheets, etc. should review all the documentation that Google provides regarding screen reader usage. If you do a general search for “Google Docs screen readers,” you will find the general documentation on how to use Docs with screen readers as well as documentation on using different suite products with screen readers. The first thing to note is that the way that Docs must be implemented, it requires that keyboard typing echo must be switched off with NVDA. This, therefore, is not a bug.

**Comment by ehollig** [comment] 2018-01-23 21:55
Duplicate of #7660

**Closed by ehollig** 2018-01-23 21:55 UTC
