### ISSUE TITLE
NVDA snapshots cause Foobar to crash when playing tracks from the playlist list box

### ISSUE THREAD

**Issue by pitermach** [nvaccess/nvda#7709] opened 2017-10-28 11:56 UTC
### Steps to reproduce:

1. Open Foobar 2000
2. Open a few files to make a playlist.
3. You might see foobar crash immediately. If  not, tab to the playlist list, and  press enter on tracks to play them. The crash will then occur sooner or later.

## Expected behavior:
No crashes

### Actual behavior:
Foobar 2000 crashes with the "Foobar 2000 has crashed" message. The issue is definitely NVDA related, and doesn't occur with other screen readers (Narrator and JAWS 2018 tested). The nvda log and a foobar crash dump is here
https://cloud.tardis.pw/owncloud/index.php/s/8WlcuQ7rhLNkENH/download

### System configuration:

NVDA version: next-14552,085e89fa

NVDA Installed or portable:
Installed

Windows version:
Windows 10 16299.19

Name and version of other software in use when reproducing the issue:
Foobar 2000 1.3.15 and 1.3.16
### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Yes. 2017.3 works fine, so this seems to be a recent regression

**Comment by Brian1Gaff** [comment] 2017-10-28 12:40
Could it be something  that removing the nvda service might have caused?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by tspivey** [comment] 2017-11-02 23:34
git bisect output, from master:
    58e1946e415b8ffcea836b953310696e1d452b3c is the first bad commit

**Comment by feerrenrut** [comment] 2017-11-07 08:14
Attached the crash reports from the original description (in case they stop being hosted). 
[crash reports.zip](https://github.com/nvaccess/nvda/files/1449157/crash.reports.zip)

**Comment by michaelDCurran** [comment] 2017-11-08 06:14
I believe I have fixed the bug. Please test the following try build as soon as you can and confirm it is fixed:
https://ci.appveyor.com/api/buildjobs/jl9lqma0cuk63j0q/artifacts/output%2Fnvda_snapshot_try-i7709-14599%2C4f6cfcf3.exe
If so  we will try and get this into NVDA 2017.4.

**Comment by ondrosik** [comment] 2017-11-10 13:24
I can't reproduce it on my machine e. g. Foobar was working as expected, but my friend told me, that it is fixed in this provided version.

**Comment by Brian1Gaff** [comment] 2017-11-10 19:47
No I never got the crash to happen either.
I suspect you need a big playlist file.
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Closed** 2017-11-14 21:30 UTC
Labels: appCrash, bug, p2, regression
