### ISSUE TITLE
System tests regularly fail

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#14533] opened 2023-01-12 08:08 UTC
### Steps to reproduce:

When submitting PRs, from time to time, the following system test fail:
* Robot.symbolPronunciationTests.symbolInSpeechUI  lien
* Robot.symbolPronunciationTests.selectionByCharacter  lien
* Robot.symbolPronunciationTests.delayedCharacterDescriptions  lien
* Robot.symbolPronunciationTests.moveByWord  lien
* Robot.symbolPronunciationTests.moveByCharacter  lien
* Robot.symbolPronunciationTests.moveByLine  lien
* Robot.symbolPronunciationTests.selectionByWord  lien
* Robot.symbolPronunciationTests.selectionByLine  lien

For example, see [failed test results](https://ci.appveyor.com/project/NVAccess/nvda/builds/45901608/tests) for commit a3ebf6b0db in PR #14523. Note that re-running tests on the same code (after empty commit b988b17) made the tests [pass](https://ci.appveyor.com/project/NVAccess/nvda/builds/45903353/tests).

For another example, see also [test results](https://ci.appveyor.com/project/NVAccess/nvda/builds/45913522/tests) for commit 52662b1e0c in PR #14531.

### Actual behavior:
System tests are reported FAILED on appVeyor

### Expected behavior:
System tests should pass on appVeyor.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
N/A
#### NVDA version:
Recent alpha, e.g. commit 816496f178e3964323d0a8f8f19825274554e096.
#### Windows version:
N/A
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
N/A
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by seanbudd** [comment] 2023-01-12 22:51
Closing as duplicate of https://github.com/nvaccess/nvda/issues/14372

**Closed by seanbudd** 2023-01-12 22:51 UTC
