### ISSUE TITLE
Browse Mode 'Move Focus' not working

### ISSUE THREAD

**Issue by fisherandrew04** [nvaccess/nvda#7667] opened 2017-10-17 15:41 UTC
### Steps to reproduce:
> Open a webpage. Toggle Browse Mode and move the browse cursor away from the Focus. Press NVDA+Shift+numpadminus. Notice how Focus stays at original location and does not move to browse cursor.

### Expected behavior:
> Focus should move to browse cursor.

### Actual behavior:
> NVDA announces 'Move Focus' but Focus is still at original location.

### System configuration:
NVDA version:
> 2017.3

NVDA Installed or portable:
> Installed

Other information:
> None

Windows version:
> Windows 10, Version 1703 (OS Build 15063.540)

Name and version of other software in use when reproducing the issue:
> Firefox 56.0.1

### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
> No

**Comment by derekriemer** [comment] 2017-10-17 17:40
can you give steps to reproduce with a specific webpage? focus in this case does not refer to the exact browse mode position, but the actual system focus (so not any text in general). In fact, focus can't be set to an arbitrary chunk of text necessarily. I can see how this is confusing to users however, because it was confusing to me.

**Comment by ehollig** [comment] 2018-11-20 03:41
@fisherandrew04 can you give steps to reproduce with a specific webpage, or does https://github.com/nvaccess/nvda/issues/7667#issuecomment-337309800 solve this issue.

**Comment by Adriani90** [comment] 2018-11-20 07:48
@leonardder I think this issue should be solved now. Right?

**Comment by Adriani90** [comment] 2019-04-30 22:40
We do not have an answer from the initial author since more than two years and I guess there was something wrong in the settings applied by the initial author. I am closing this for now. if the author comments on it we can reopen the discussion.

**Closed by Adriani90** 2019-04-30 22:40 UTC
