### ISSUE TITLE
Fetching children of LibreOffice Calc table freezes/crashes NVDA

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7994] opened 2018-02-12 16:14 UTC
### Steps to reproduce:
1. Start LibreOffice Calc. Tested both 5.4.4.2 and 6.01
2. Focus a cell in the tbale
3. Start a python console
4. Type focus.table.children
5. Press enter

### Actual behavior:
NVDA crashes.

### Expected behavior:
Yes, that's the question. What should we expect here? It seems that LibreOffice has all table cells as direct children of the table object, which results in an enormous amount of children. We could expect that NVDA has major issues with this, but how should we avoid or work around these?

### Additional details
Running JAWS and NVDA side by side reveals that LibreOffice itself does not crash. Running different versions of nVDA does not make any difference.b

**Comment by feerrenrut** [comment] 2018-02-14 06:25
Can we catch / or detect this and avoid the crash? What are the technical details that lead to the crash in this situation?
What user action might cause this? or if this is blocking another issue / work could you link it here?

Asking so that I can get a better idea of the priority for this one.

**Comment by leonardder** [comment] 2018-02-14 07:28
[**@feerrenrut**](https://github.com/feerrenrut) commented on [14 feb. 2018 07:25 CET](https://github.com/nvaccess/nvda/issues/7994#issuecomment-365508671 "2018-02-14T06:25:45Z - Replied by Github Reply Comments"):
> Can we catch / or detect this and avoid the crash? What are the technical details that lead to the crash in this situation?

It looks like all table cells are direct children of the table

```
>>> nav.table.childCount
1073741824
```

May be we could make the children property check the childCount and refuse its fetching when the childCount exceeds a particular value?

> What user action might cause this? or if this is blocking another issue / work could you link it here?

I don't think that this could be easily reproduced for an end user. For a developer, it's important to note that the python console fetches all magic properties when doing an auto complete. So if you type nav.table. and press tab, the crash occurs as well. It actually took me some time to find out that children was the culprit here.

**Comment by feerrenrut** [comment] 2018-02-15 03:00
I think we need to investigate the core cause of this issue. Presumably, the crash is caused by an out of memory error somewhere when trying to fetch all the children. If this is something we have control over, perhaps we could harden this code?

**Comment by michaelweghorn** [comment] 2021-07-05 09:03
Has this been addressed/fixed in the meanwhile? I just tried to reproduce and couldn't, but get this:

    >>> focus.table
    <appModules.soffice.SymphonyTable object at 0x089965D0>
    >>> focus.table.childCount
    1073741824
    >>> focus.table.children
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "baseObject.pyc", line 42, in __get__
      File "baseObject.pyc", line 146, in _getPropertyViaCache
      File "NVDAObjects\IAccessible\__init__.pyc", line 1058, in _get_children
      File "IAccessibleHandler\__init__.pyc", line 442, in accessibleChildren
      File "oleacc.pyc", line 308, in AccessibleChildren
    OverflowError: array too large

(with LibreOffice 7.1.4.2 (x64) and NVDA 2020.4)

**Comment by seanbudd** [comment] 2023-01-03 02:00
Closing this as stale/fixed.
Note previous comment and #13232

**Closed by seanbudd** 2023-01-03 02:00 UTC
Labels: app/libreoffice
