### ISSUE TITLE
some symbols are treated as emojis

### ISSUE THREAD

**Issue by alipanjei** [nvaccess/nvda#12086] opened 2021-02-20 12:32 UTC
Some symbols used in Persian language (mainly "،" and "؟")  are being treated as emojis when reading a text in all windows. This happens when the option to include Unicode Consortium data when processing characters and symbols is enabled.
### Steps to reproduce:
-Turn on the Unicode data option from NVDA Speech settings
-Read any Persian text that includes the symbols mentioned above. Writing those symbls with the keyboard is also an option.
### Actual behavior:
Instead of the correct name, those symbols are announced as Arabic comma and question mark. They're also repeated continuously while reading a text, even if symbol level is none  
### Expected behavior:
NVDA should announce those symbol names correctly. They also should be treated as symbols, which means they shouldn't be announced everywhere unless symbol level is set to all, and speech should have a short pause just like when dealing with equivalents of these symbols in other languages.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.4
#### Windows version:
WINDOWS 10 ENTERPRISE Version	10.0.19041 Build 19041

#### Name and version of other software in use when reproducing the issue:
HAPPENS EVERYWHERE, INCLUDING NOTEPAD/FIREFOX/CHROME
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This was fine in NVDA 2020.3. I was seeing the expected behavior there.
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes

**Comment by alipanjei** [comment] 2021-02-20 12:39
I just tried removing the mentioned symbols from "cldr.dic" file related to Persian and English languages and it worked.
Now I'm seeing the expected behavior. I'm not sure if It's possible to include this change in the project so people won't have to remove things manually; I'm really new to GitHub and opensource projects.

**Comment by cary-rowen** [comment] 2021-02-20 12:55
Try defining these symbols in symbols.dic and it should solve your doubts.

**Comment by OzancanKaratas** [comment] 2021-05-06 17:37
Duplicate of #11963. Please close this.

**Comment by CyrilleB79** [comment] 2021-05-06 22:32
> Duplicate of #11963. Please close this.

No it does not seem to be a duplicate to me:
* This issue is about punctuation symbols that seem to be included recently in CLDR (also in some other languages if not all such as French or Italian)
* #11963 also presents punctuation issues but overall is about "↑↑↑" in CLDR files (lines that should not be there or at least not loaded by NVDA)

I recommend further investigation in both problems before stating they have the same cause.

**Comment by zersiax** [comment] 2021-05-23 17:16
I'm inclined to agree. Language-specific punctuation should be considered as such, punctuation, and should therefore respect the punctuation setting set to NVDA irrespective of these characters being present in the list of emoji and other such symbols. I've seen this in various Non-Latin languages and it makes them rather annoying to read.

**Closed** 2022-06-23 09:47 UTC
