### ISSUE TITLE
allow automatic reading of subtitles in chrome on youtube

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13783] opened 2022-06-09 21:49 UTC
open youtube in chrome
I signed in with my account, I don't know if this is necessary.
Now in the submenu button in the details focus mode I chose the subtitles menu with the arrows.
inside subtitles I marked
Automatically generated Portuguese subtitles.
Now I pressed the button that says
No subtitles/closed captions available
now using browse mode you can go to where nvda pronounces
clickable submenu button
Profile picture of the account that opens the list of alternate accounts
press a couple more arrows below and you should hear the subtitle text generated by youtube
now note that whenever the subtitle changes nvda does not read automatically, so that the user can read the text of the updated subtitle it is necessary to keep pressing arrows up and down every few seconds.### Steps to reproduce:

### Actual behavior:
to read the updated text of the subtitles it is necessary to keep pressing arrows like this and down periodically.
### Expected behavior:
nvda could read the new updated text on the screen automatically.
I believe that youtube does not make this available in an accessible and conventional way for nvda, I would like the nvda developers to check if this is the case.
If not, it is due to an nvda bug, I would like to ask the nvda developers to resolve the issue.
If the problem is with google, nv access could report this to google, or tell me which channel could tell google this.
Another solution would be if nvda could provide the user with how to mark a section of the screen, and the user could ask nvda to monitor this section and when any new text appears, nvda would read this to the user.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-25478,841925b7

#### Windows version:
10 19044.1706
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 102.0.5005.63

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log
[youtube.txt](https://github.com/nvaccess/nvda/files/8874158/youtube.txt)

**Comment by surfer0627** [comment] 2022-09-12 09:21
fernando-jose-silva commented on 10 Jun
> now note that whenever the subtitle changes nvda does not read automatically, so that the user can read the text of the updated subtitle it is necessary to keep pressing arrows up and down every few seconds.### Steps to reproduce:

@@fernando-jose-silva
Perhaps, this what you need.

* [maxe-hsieh/subtitle_reader](https://github.com/maxe-hsieh/subtitle_reader)
* command: Toggle subtitle reader on / off: NVDA + y
* [download subtitle_reader V2.47](https://github.com/maxe-hsieh/subtitle_reader/releases/download/%E9%9B%A8%E6%BB%B4%E4%B9%8B%E6%AD%8C/subtitle_reader.nvda-addon)
* note: The description is in Chinese.

**Comment by fernando-jose-silva** [comment] 2022-09-12 19:32
perfect, I texted the add-on and it works fine.
I would like to ask nv access not to close the request, but to see the possibility of including the add-on in nvda's core.

**Comment by Adriani90** [comment] 2023-05-06 00:05
Closing as duplicate of #10625.

**Closed by Adriani90** 2023-05-06 00:05 UTC
Labels: close/duplicate, blocked/needs-external-fix, p3, triaged
