### ISSUE TITLE
Error in the logfile regarding pending updates when opening the NVDA menu

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9972] opened 2019-07-25 14:14 UTC
### Steps to reproduce:
1. Install a portable copy of [NVDA 2019.2 Beta-18133](https://ci.appveyor.com/api/buildjobs/t7pflc1win8kdioo/artifacts/output/nvda_snapshot_beta-18133,b29acb42.exe) or 2019.1.1 (on a SSD).
2. Disable the options "Automatically check for updates to NVDA" and "Notify for pending update on startup" in the General NVDA Settings.
3. Restart NVDA with debug logging level via NVDA+Q.
4. Then just press NVDA+N. (Maybe you have to wait a few seconds before pressing NVDA+N. I didn't check that out.)
### Actual behavior:
I found the following in the logfile:
```
Input: kb(desktop):NVDA+n
DEBUG - gui.MainFrame.evaluateUpdatePendingUpdateMenuItemCommand (15:43:35.900):
Error while removing  pending update menu item
Traceback (most recent call last):
  File "gui\__init__.pyc", line 233, in evaluateUpdatePendingUpdateMenuItemCommand
wxAssertionError: C++ assertion "node" failed at ..\..\src\msw\menu.cpp(890) in wxMenu::DoRemove(): bug in wxMenu::Remove logic
IO - speech.speak (15:43:35.950):
Speaking [u'NVDA  Men\xfc']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (15:43:35.951):
Potential unimplemented child class: <NVDAObjects.IAccessible.IAccessible object at 0x059DA630>
IO - braille.BrailleBuffer.update (15:43:35.951):
Braille regions text: [u'NVDA mn\xfc']
```

### Expected behavior:
No error.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2019.2 Beta-18133
#### Windows version:
Win7x64
#### Does the issue still occur after restarting your PC?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same result with 2019.1.1 (Portable)

**Comment by leonardder** [comment] 2019-07-25 15:08
This is an error, but it is logged at the debug level. So in fact, it is safe to  ignore this error altogether. In fact it is expected when there is no "install pending update" menu item in the menu.
Unless people may insist in rewording this debug logging statement, I'm tempted to close this.

**Comment by XLTechie** [comment] 2019-07-25 17:01
@leonardder, with all due respect, without knowing what you know, I'm not 
sure if there is any way to be aware that this is the expected behavior.

I'm not used to seeing tracebacks in logs for situations that are "normal". NVDA doesn't usually do that.

If there is a way to make it known by some text that this is not actually an 
issue to be reported or concerned over, that would be better imo. Right now it 
just looks like an unhandled (set of) error(s), and since pending update errors 
do occur for real reasons that do need to be fixed, this one should be flagged 
as harmless in some way, if it has to be logged in my opinion.

Can it not be caught, and a statement be logged that the expected for a certain 
circumstance happened?

**Comment by leonardder** [comment] 2019-07-26 06:16
> If there is a way to make it known by some text that this is not actually an issue to be reported or concerned over, that would be better imo.

In my opinion, there is such an indication. The log reads:

```
DEBUG - gui.MainFrame.evaluateUpdatePendingUpdateMenuItemCommand (15:43:35.900):
Error while removing  pending update menu item
```

Note the first line, that clearly states `debug`. Therefore, this is a message on the debug level, meant to never be seen by the normal user unless strictly instructed or decided to enable debug logging. There are several other errors logged at the `debugWarning` level which are safely to ignore.

The only errors to be really concerned with are the errors that generate the error sound on test builds.

Happy for someone to file a pr with `Error while removing  pending update menu item` reworded to `Could not remove pending update menu item, likely already removed`

**Comment by Brian1Gaff** [comment] 2019-07-26 09:19
Yes and its still there in the new threshold as well.
 It can unfortunately make the display of the  a new update is available 
also persist after it has in fact been downloaded  so alt tab gives the 
install and the download  dialogue like a toggle sometimes. I got the 
impression these two weird things were inter related in the failure to 
unflag if that is a word a d dialogue sometimes.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Brian1Gaff** [comment] 2019-07-26 09:23
In the old days I got the impression that no matter what the error level 
errors that did not matter came up as error warning, not full tracebacks.
 See my other comment in case its relevant, ie if you have downloaded an 
update why is it that sometimes that dialogue is not removed and is still 
usable to download it again?
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2020-05-24 02:12
@DrSooom are you still seeing this issue in NVDA 2020.1?

**Comment by DrSooom** [comment] 2020-05-24 13:05
It is still reproducible with [NVDA 2019.3.1](https://www.nvaccess.org/files/nvda/releases/2019.3.1/nvda_2019.3.1.exe) (portable). [NVDA 2020.1](https://www.nvaccess.org/files/nvda/releases/2020.1/nvda_2020.1.exe) is currently the latest stable version, so I didn't test that one.
```
IO - inputCore.InputManager.executeGesture (14:50:35.688) - winInputHook (8088):
Input: kb(desktop):NVDA+n
DEBUG - gui.MainFrame.evaluateUpdatePendingUpdateMenuItemCommand (14:50:35.698) - MainThread (7836):
Error while removing  pending update menu item
Traceback (most recent call last):
  File "gui\__init__.pyc", line 227, in evaluateUpdatePendingUpdateMenuItemCommand
wx._core.wxAssertionError: C++ assertion "node" failed at ..\..\src\msw\menu.cpp(890) in wxMenu::DoRemove(): bug in wxMenu::Remove logic
IO - speech.speak (14:50:35.740) - MainThread (7836):
Speaking [LangChangeCommand ('de'), 'NVDA', 'Menü']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (14:50:35.740) - MainThread (7836):
Potential unimplemented child class: <NVDAObjects.IAccessible.IAccessible object at 0x053B0B90>
IO - braille.BrailleBuffer.update (14:50:35.741) - MainThread (7836):
Braille regions text: ['NVDA mnü']
IO - braille.BrailleHandler.update (14:50:35.741) - MainThread (7836):
Braille window dots: 6 6 1345 1236 145 1 - 134 1345 45 25 136
```

**Comment by Adriani90** [comment] 2023-04-02 19:28
Given the limited impact here and given the fact that this will not affect the functionality of NVDA's update check, I am closing this issue. If I understand correctly, NVDA does not do anything wrong here, it just logs that the pending update menu item cannot be removed, because it does not exist. Since the error is expected and should remain logged, I am closing this issue as works for me.

**Closed by Adriani90** 2023-04-02 19:28 UTC
Labels: close/worksforme
