### ISSUE TITLE
Keyboard shortcuts not working with Microsoft Office with UIA enabled

### ISSUE THREAD

**Issue by Nael-Sayegh** [nvaccess/nvda#16335] opened 2024-03-25 21:19 UTC
### Steps to reproduce:
  * Activate UIA in Word and Excel
  * Go to, for example, Excel or a Word table
  * Use the NVDA+Shift+C shortcut to set the table header

### Actual behavior:

Currently with UIA enabled, shortcuts in Word and Excel do not work, such as NVDA+Shift+C for example.

### Expected behavior:

The keyboard shortcuts for Word and Excel should work as if UIA were disabled.

### NVDA logs, crash dumps and other attachments:
n/a

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2023.3.4

#### Windows version:
windows 11

#### Name and version of other software in use when reproducing the issue:
office 365

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes since 2022.4

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2024-03-25 21:47
Closing as duplicate of #12882. I added a comment there that this affects also MS Word.

**Closed by Adriani90** 2024-03-25 21:47 UTC
Labels: close/duplicate

**Comment by CyrilleB79** [comment] 2024-03-26 08:40
@Nael-Sayegh, I'd handle the Word and the Excel issues separately:
* Regarding Excel, the issue is already being tracked in #12882 as explained by @Adriani90; it's worth noting though that UIA for Excel is not activated by default because the feature is still incomplete.
* Regarding Word, when pressing `NVDA+shift+c/r`, there is an appropriate error message and the way to have headers read in a Word table is documented in the User Guide from NVDA 2024.1 onwards (PR #15617). Please test with NVDA 2024.1rc1 and open a new separate issue if the user experience is not satisfactory, e.g. if you want to set another column/row than the first one for headers.
