### ISSUE TITLE
Chromium Edge: NVDA announces page load status from a tab other than the site being loaded

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#16010] opened 2024-01-07 03:17 UTC
Hi,

Perhaps an oversight from NVDA side: Edge uses UIA notification to announce page load and other status messages.

### Steps to reproduce:
1. Open at least two tabs in Microsoft Edge. One of them must be a site that loads slowly.
2. Open the first tab with a site that opens quickly (say, Google website).
3. Open a second tab and navigate to a site that opens slowly.
4. Switch to the first tab while the second tab is loading.

### Actual behavior:
NVDA says "loading page" and other status messages while not focused on the site being loaded.

### Expected behavior:
NVDA announces stauts messages while focused on the tab being loaded.

### NVDA logs, crash dumps and other attachments:
None

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30533,88ceef4c

#### Windows version:
Windows 11 23H2 beta (10.0.22635.2921)

#### Name and version of other software in use when reproducing the issue:
Edge beta 121.0.2277.4

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Reproducible in 2023.x, 2024.1 beta, and earlier versions

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

### Additional context:
A somewhat similar thing happened when Spartan Edge was actively supported. I imagine the solution would involve checking focus ancestors.

Thanks.

**Comment by beqabeqa473** [comment] 2024-01-07 06:35
the same thing happens with download notifications in issue created by
me, unfortunately cannot find a number for this time, so i think this
is duplicate.

On 1/7/24, Joseph Lee ***@***.***> wrote:
> Hi,
>
> Perhaps an oversight from NVDA side: Edge uses UIA notification to announce
> page load and other status messages.
>
> ### Steps to reproduce:
> 1. Open at least two tabs in Microsoft Edge. One of them must be a site that
> loads slowly.
> 2. Open the first tab with a site that opens quickly (say, Google website).
> 3. Open a second tab and navigate to a site that opens slowly.
> 4. Switch to the first tab while the second tab is loading.
>
> ### Actual behavior:
> NVDA says "loading page" and other status messages while not focused on the
> site being loaded.
>
> ### Expected behavior:
> NVDA announces stauts messages while focused on the tab being loaded.
>
> ### NVDA logs, crash dumps and other attachments:
> None
>
> ### System configuration
> #### NVDA installed/portable/running from source:
> Installed
>
> #### NVDA version:
> alpha-30533,88ceef4c
>
> #### Windows version:
> Windows 11 23H2 beta (10.0.22635.2921)
>
> #### Name and version of other software in use when reproducing the issue:
> Edge beta 121.0.2277.4
>
> #### Other information about your system:
> N/A
>
> ### Other questions
> #### Does the issue still occur after restarting your computer?
> Yes
>
> #### Have you tried any other versions of NVDA? If so, please report their
> behaviors.
> Reproducible in 2023.x, 2024.1 beta, and earlier versions
>
> #### If NVDA add-ons are disabled, is your problem still occurring?
> Yes
>
> #### Does the issue still occur after you run the COM Registration Fixing
> Tool in NVDA's tools menu?
> Yes
>
> ### Additional context:
> A somewhat similar thing happened when Spartan Edge was actively supported.
> I imagine the solution would involve checking focus ancestors.
>
> Thanks.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/16010
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment] 2024-01-07 12:23
I cannot find that issue @beqabeqa473. So we should let this open and discuss here until we find any duplicate.

**Comment by beqabeqa473** [comment] 2024-01-07 13:09
#13235

**Comment by Adriani90** [comment] 2024-01-07 14:48
Ah thanks for that. Closing as duplicate of that issue.

**Closed by Adriani90** 2024-01-07 14:48 UTC
Labels: close/duplicate
