### ISSUE TITLE
Spotify: The focus should automatically move to the pop up menu at the bottom when pressing application key…

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6958] opened 2017-03-09 21:41 UTC
Feedback from an NVDA user, directed at @nvdaaddons. If anyone has time, a PR is welcome.
@NVDAAddons The focus should automatically move to the pop up menu at the bottom when pressing application key on a song. Pressing enter is not consistent to bring up a particular playlist.

**Comment by jcsteh** [comment] 2017-03-09 23:03
The reporter should try providing this feedback to Spotify. It's going to
be a lot better/less fragile/more broadly applicable if the issue is fixed
by them.

**Comment by Adriani90** [comment] 2023-04-21 23:14
Testing with NvDA last alpha, This is fixed now in Spotify for Windows. The focus jumps to the bottom where the menu is located. Closing as works for me.

**Closed by Adriani90** 2023-04-21 23:14 UTC
Labels: close/worksforme, p4
