### ISSUE TITLE
the Beta notification lacks information

### ISSUE THREAD

**Issue by BrianOlesen02** [nvaccess/nvda#17189] opened 2024-09-18 16:42 UTC
### Is your feature request related to a problem? Please describe.
no
### Describe the solution you'd like
Dear NVDA
I have an idea I hope you’ll consider worth working on.
I’m super happy for participating in the beta program, and I’m so proud of all the great effort you put into this world class screen reader.
There is just one thing I really miss, when I get an update notification.
I wish you’d include a direct link in the notification, where we can read about the specific news for this particular iteration of NVDA.
Another more somewhat demanding way to do it is including some text in the window, but this probably would require internationalization. But a link to at least the English text would help a lot.
I believe that many just update their NVDA not knowing a single bit about what is going on with the version.

Best regards
Brian

### Additional context
I think this addition will be of great value to the users.

**Comment by seanbudd** [comment] 2024-09-19 00:35
Closing as duplicate of #14274

**Closed by seanbudd** 2024-09-19 00:35 UTC
