### ISSUE TITLE
Adobe Digital Editions: Books text not shown in braile

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#5634] opened 2015-12-23 12:36 UTC
In the Book content Window of Adobe Digital Editions, the text is read by speech synthesizer, but not shown in braille displays.
Furthermore, the cursor can't be moved using braille keys.
Test envyronment:
- Adobe Digital Editions 4.5.
- NVDA 2015.4.
- Ecobraille display (Ecoplus).
  The attached zip file contains NVDA.log and another log with the developer info corresponding to the Book content window.
  Thanks.
  [logs.zip](https://github.com/nvaccess/nvda/files/70760/logs.zip)

**Comment by dkager** [comment] 2016-01-06 15:52
I can confirm this. Note that when reading an ePUB3 file you also get a browser document which you can navigate with braille using browse mode.

**Comment by nvdaes** [comment] 2016-01-06 16:00
Yes, I tested that ePUB an 3 file has the possibility of viewing
documents in browse mode.
Hope it can be fixed when this feature isn't available.
Thanks.

**Comment by Adriani90** [comment] 2019-02-12 10:33
@nvdaes, @dkager I duess this issue is still reproducible. Right? I know that Adobe was quite reluctant regarding adjustments in their products to improve accessibility. Are there any updates? cc: @jcsteh

**Comment by ruifontes** [comment] 2019-02-12 10:57
Windows 10 1809
Adobe Digital Editions 4.5.7
NVDA last Alpha
Handytech Basic Braille 20

The text is shown in the Braille display...

Rui Fontes


Às 10:33 de 12/02/2019, Adriani90 escreveu:

**Comment by Adriani90** [comment] 2019-02-12 12:43
I have got also a report from a german nvda user with braille display Baum super vario 40. The text is shown on the display as well.

**Comment by nvdaes** [comment] 2019-02-12 12:45
Hi, I think we could close this issue:
- The text is shown in braille reading a purchased epub file.
- A crash is produced and NVDA needs to be started reading a valid ePUB 3 file created by @daisy for testing the accessibility of reading systems like ADE. I think this can't be tested due to its lack regarding stability.
Please see
http://epubtest.org/testsuite/accessibility/

**Comment by Adriani90** [comment] 2019-02-12 12:52
Ok, then closing it as works for me. If the issue is occuring for a specific braille display, then we can reopen it.

**Closed by Adriani90** 2019-02-12 12:52 UTC
Labels: AdobeWork, Braille, worksforme
