### ISSUE TITLE
Nvda does not read the suggested options in the start menu in windows 7

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7013] opened 2017-03-24 13:04 UTC
I'm using nvda next 13946 on windows 7 64bits, and I noticed a problem.
When pressing the start menu the nvda error sound is heard.
When typing letters, typing letters is also not heard.

The log is attached.

It is worth mentioning that in the previous version of the nvda that was using next 13933 these problems did not occur.

IO - speech.speak (09:48:57):
Speaking [u'Menu Iniciar']
IO - speech.speak (09:48:57):
Speaking [u'Caixa de Pesquisa  edi\xe7\xe3o  Pesquisar programas e arquivos']
ERROR - eventHandler.executeEvent (09:48:57):
error executing event: gainFocus on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x05EB56F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\focusHighlight\globalPlugins\focusHighlight.py", line 416, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 199, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\AudioThemes3D\globalPlugins\audioThemes\__init__.py", line 125, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\enhancedTouchGestures\globalPlugins\enhancedTouchGestures.py", line 94, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\remote\globalPlugins\remoteClient\__init__.py", line 410, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\Favorite folders\globalPlugins\FavoriteFolders\__init__.py", line 161, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\easyTableNavigator\globalPlugins\easyTableNavigator.py", line 82, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\explorer.pyc", line 280, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 900, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 812, in reportFocus
  File "speech.pyc", line 368, in speakObject
  File "speech.pyc", line 719, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 581, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 443, in _getTextWithFieldsForUIARange
  File "baseObject.pyc", line 21, in __get__
  File "NVDAObjects\UIA\__init__.pyc", line 84, in _get__controlFieldUIACacheRequest
COMError: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:48:59):
Input: kb(laptop):b
IO - speech._speakSpellingGen (09:49:00):
Speaking character u'b'
IO - speech.speak (09:49:00):
Speaking [u'Modo de Exibi\xe7\xe3o de Itens  lista']
IO - speech.speak (09:49:00):
Speaking [u'Programas  grupo  expandido']
IO - speech.speak (09:49:00):
Speaking [u'Skype for Business 2015']
IO - inputCore.InputManager.executeGesture (09:49:03):
Input: kb(laptop):l
DEBUGWARNING - eventHandler.executeEvent (09:49:03):
error executing event: typedCharacter on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {'ch': u'l'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\reportSymbols\globalPlugins\reportSymbols.py", line 58, in event_typedCharacter
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 847, in event_typedCharacter
  File "speech.pyc", line 625, in speakTypedCharacters
  File "api.pyc", line 239, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (09:49:03):
error executing event: UIA_elementSelected on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1256, in event_UIA_elementSelected
  File "NVDAObjects\UIA\__init__.pyc", line 1380, in event_stateChange
  File "NVDAObjects\__init__.pyc", line 886, in event_stateChange
  File "speech.pyc", line 270, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:49:05):
Input: kb(laptop):o
DEBUGWARNING - eventHandler.executeEvent (09:49:05):
error executing event: typedCharacter on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {'ch': u'o'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\reportSymbols\globalPlugins\reportSymbols.py", line 58, in event_typedCharacter
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 847, in event_typedCharacter
  File "speech.pyc", line 625, in speakTypedCharacters
  File "api.pyc", line 239, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (09:49:05):
error executing event: UIA_elementSelected on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1256, in event_UIA_elementSelected
  File "NVDAObjects\UIA\__init__.pyc", line 1380, in event_stateChange
  File "NVDAObjects\__init__.pyc", line 886, in event_stateChange
  File "speech.pyc", line 270, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:49:06):
Input: kb(laptop):c
DEBUGWARNING - eventHandler.executeEvent (09:49:06):
error executing event: typedCharacter on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {'ch': u'c'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\a50596\AppData\Roaming\nvda\addons\reportSymbols\globalPlugins\reportSymbols.py", line 58, in event_typedCharacter
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 847, in event_typedCharacter
  File "speech.pyc", line 625, in speakTypedCharacters
  File "api.pyc", line 239, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
DEBUGWARNING - eventHandler.executeEvent (09:49:06):
error executing event: UIA_elementSelected on <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\UIA\__init__.pyc", line 1256, in event_UIA_elementSelected
  File "NVDAObjects\UIA\__init__.pyc", line 1380, in event_stateChange
  File "NVDAObjects\__init__.pyc", line 886, in event_stateChange
  File "speech.pyc", line 270, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 958, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 657, in _getUIACacheablePropertyValue
COMError: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:49:11):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (09:49:11):
Developer info for navigator object:
name: ''
role: ROLE_LISTITEM
states: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
isFocusable: exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
hasFocus: False
Python object: <NVDAObjects.Dynamic_UIItemListItemUIA object at 0x0574D8B0>
Python class mro: (<class 'NVDAObjects.Dynamic_UIItemListItemUIA'>, <class 'NVDAObjects.UIA.UIItem'>, <class 'NVDAObjects.UIA.ListItem'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: ''
location: None
value: ''
appModule: <'explorer' (appName u'explorer', process ID 3172) at address 5530bf0>
appModule.productName: u'Sistema operacional Microsoft\xae Windows\xae'
appModule.productVersion: u'6.1.7600.16385'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 852962
windowClassName: u'DirectUIHWND'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 4404
windowText: u''
displayText: exception: 'NoneType' object is not iterable
UIAElement: <POINTER(IUIAutomationElement) ptr=0x43fad78 at 5e6bd00>
UIA automationID: Exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))
UIA frameworkID: DirectUI
UIA runtimeID: (3172, 106010768, 0)
UIA providerDescription: [pid:3172,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:EXPLORERFRAME.dll)]
UIA className: Exception: (-2147220991, 'Um evento n\xe3o p\xf4de chamar assinantes', (None, None, None, 0, None))

**Comment by jcsteh** [comment] 2017-03-26 22:16
@MichaelDCurran, possible regression from #6994?

**Comment by Brian1Gaff** [comment] 2017-03-27 08:18
Seems to be working here. No sometimes errors as it tended to do before
 Incidentally my win 10 machine is off line at present as the psu went bang, 
literally over the weekend.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by fernando-jose-silva** [comment] 2017-03-27 12:38
Thank you very much.
Has the issue been fixed.

**Comment by jcsteh** [comment] 2017-03-27 12:53
Just to clarify (just some linguistic confusion), do you mean "yes, I
tested and the issue has been fixed for me"? Thanks.

**Comment by fernando-jose-silva** [comment] 2017-03-27 17:26
Yes I tested it and it's working for me.
Many thanks, and sorry, speaking English is still complicated.

**Comment by jcsteh** [comment] 2017-03-27 23:09
No problem at all; thanks for your efforts. I was pretty sure I understood you correctly, but wanted to be absolutely clear. Closing as fixed.

**Closed by jcsteh** 2017-03-27 23:09 UTC
Labels: p1, regression
