### ISSUE TITLE
Input Gestures dialog: detect duplicate keyboard gestures and rimnd users about them

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#7734] opened 2017-11-06 19:29 UTC
Idea behind this issue is that NVDA will warn user if conflicted keyboard gesture exists. This may heppen, when a new addon was installed and it has added a new gesture or when one of gestures has been 
changed manually.

### Steps to reproduce:

1. open Input gesture dialog
2.asign e.g. NVDA+f12 to the other script.

### Expected behavior:

NVDA should warn you, that this gesture already exists and tell you what this (old gesture does. Here should also be a question, if we really want to asign a new script to gesture, because old script will not be reachable via this gesture.. another option can be separate category which can list duplicated gestures.

### Actual behavior:

As I tested, NVDA does not react if there exist more than one unique gesture-script pair so NVDA tolerats if one gesture calls more than one script.

### System configuration:
NVDA version:
Last next version (14588...
)
NVDA Installed or portable:
installed

Windows version:

w10 (1709) tith latest updates

**Comment by josephsl** [comment] 2017-11-06 19:35
Hi, isn’t this a duplicate of something? Thanks.

**Comment by ehollig** [comment] 2017-11-07 02:11
Duplicate of #3605

**Closed by ehollig** 2017-11-07 02:11 UTC

**Comment by Brian1Gaff** [comment] 2017-11-07 15:30
Not sure if it is, but then github issue search is built by Klingons...
 Its a good idea if it can be achieved. it sounds like a logic nightmare 
when you are talking two different layouts and multiple languages as well as 
add ons that may come already with existing conflicted key sequences.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----
