### ISSUE TITLE
NOTEPAD ++ code is automatically completed and NVDA can not be read normally

### ISSUE THREAD

**Issue by dpy013** [nvaccess/nvda#7233] opened 2017-05-31 08:44 UTC
NOTEPAD ++ code is automatically completed and NVDA can not be read normally
Operating environment:
windows10 1703 x64
NVDA version 14084
NOTEPAD++ version :NOTEPAD++-7.4.1
Problem Description:
I used a NOTEPAD ++ learning html beginners, the use of the NVDA screen reader. However, the recent code in the code when I found a problem, I opened NOTEPAD + + code automatically fill up after the input code NVDA can not show the normal selection Code list, he read out the blank, in fact, there is a list of the following examples.
examples
First switch the schema dimension HTML
<html>(No list)
<a>(No list)
<a>(There is a list, NVDA can not display properly)
abbr   
above   
absolute   
accept   
accept-charset   
accesskey   
action   
address   
alt   
always   
aqua   
area   
armenian   
article   
aside   
async   
attr   
audio   
auto   
autocomplete   
autofocus

**Comment by derekriemer** [comment] 2017-07-06 00:00
The notepad++ addon for NVDA might help. https://github.com/derekriemer/nvda-notepadPlusPlus

**Comment by derekriemer** [comment] 2017-07-06 00:00
I'm not sure what you are trying to ask here.

**Comment by dingpengyu** [comment] 2017-07-06 00:22
NVDA is not the normal choice to read aloud notepad + + code automatically fill up.

**Comment by Adriani90** [comment] 2019-04-17 22:00
@dingpengyu are you still having this issue in NVDA 2019.1.1?

**Comment by dingpengyu** [comment] 2019-04-17 22:34
hi Adriani
I used NVDA alpha 17077 to test the problem. NVDA still can't read the code selection list of np++. Here's nvda. log
[nvda.log](https://github.com/nvaccess/nvda/files/3091808/nvda.log)

**Comment by Adriani90** [comment] 2019-04-24 12:13
cc: @leonardder, @josephsl

**Comment by Adriani90** [comment] 2020-05-05 20:01
I think this issue is about the automatic suggestions which appear in Notepad++ when entering code. But I am not sure if I understand this issue correctly.
cc: @DataTriny

**Comment by DataTriny** [comment] 2020-05-09 16:24
Hi,
I'm sorry but I can't understand the issue you are describing here @dingpengyu . Did you just meant that in Notepad++, when navigating the autocompletion popup, only the last typed word is read instead of the suggestions?
If yes, then I can confirm that the issue is still reproduceable (Windows 10 version 1909, NVDA 2020.1, Notepad++ v7.5.4).

**Comment by Adriani90** [comment] 2024-04-22 19:21
Given the issue description is not clear enough and we cannot understand what the user really expects, I am closing this issue. Please open a new issue with a clearer description and fill the complete template.

**Closed by Adriani90** 2024-04-22 19:21 UTC
Labels: app-specific
