### ISSUE TITLE
NVDA is stopping during touchscreen exploration

### ISSUE THREAD

**Issue by grishakonzalaev** [nvaccess/nvda#14803] opened 2023-04-06 20:06 UTC
### Steps to reproduce:
1. touch exploring with different gestures of sliding.
### Actual behavior:
NVDA stops after many times of sliding gestures.
### Expected behavior:
NVDA must work correctly.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-28043,14bc6bd2 (2023.2.0.28043)

#### Windows version:
22H2 build OS 19045.2728)

#### Does the issue still occur after restarting your computer?
yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
there is no bug on stable NVDA 2023.1.
#### If add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes.
[nvda-old.log](https://github.com/nvaccess/nvda/files/11174104/nvda-old.log)

**Comment by Adriani90** [comment] 2023-04-07 13:06
cc: @jcsteh, @leonardder

**Comment by leonardder** [comment] 2023-04-07 13:59
Does the issue also occur with [alpha-27996](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-27996,d8396f9b.exe)?

**Comment by josephsl** [comment] 2023-04-07 14:13
Possibly similar to #14753, or if the underlying issue is the same, a duplicate of the linked issue but now on Windows 10 22H2. Thanks.

**Comment by grishakonzalaev** [comment] 2023-04-07 14:35
> Does the issue also occur with [alpha-27996](https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-27996,d8396f9b.exe)?

yes.

**Comment by seanbudd** [comment] 2023-04-11 01:54
Was this an issue with older versions of Windows and NVDA?

**Closed** 2023-05-15 04:10 UTC
Labels: feature/touch-screen, p2, triaged
