### ISSUE TITLE
role="alert" with div element is read twice

### ISSUE THREAD

**Issue by tapanbasak** [nvaccess/nvda#6680] opened 2016-12-26 08:54 UTC
When role="alert" is added to a div element, inner content is reading twice by NVDA reader (version >=2016.1) with IE11 browser. In chrome it is working fine as expected. For example -
`<div class="validation-message-danger" style="display:none;" role="alert" id="c3text_err_1_inline_minLength">This field is required</div>`

When above div element is made visible, NVDA reader is reading like "**This field is required alert This field is required**" in IE 11 browser.

If anyone has any workaround,  please suggest... 

Thanks

**Comment by ehollig** [comment] 2017-10-10 15:16
@tapanbasak is this still an issue with the latest version of NVDA? Do you have an example site that is demonstrating this behavior?

**Comment by Adriani90** [comment] 2019-03-25 21:46
@tapanbasak are you still available?

**Comment by aloeugene** [comment] 2019-05-29 13:34
Hi all,

I can say that it still reproduces for me in IE11 with NVDA 2019.1.

Code sample:
```
<section role="alert" aria-live="assertive">
  <img />
  <span>You have removed the item.</span>
  <button>Close</button>
</section>
```

**Comment by mattgh94** [comment] 2021-07-13 12:37
We have the same issue in Chrome and Firefox. The fix of using aria-described by is not possible because we are using NGBModal options where only ariaLabelledBy is available. Additionally, we need the entire modal content to read and can't just set a custom aria-label for the element being used with described by. Is there any update on this issue?

**Comment by Adriani90** [comment] 2024-10-03 13:56
NVDA does nothing against Aria specs here, the current behavior is intended. The span text is reported because this is where NVDA's virtual cursor lands to in browse mode, and the aria live message is reported according to aria spec.
If you load the page with NVDA in focus mode, only (uncheck enable  browse mode on page load in NVDA browse mode settings), then only the aria live assertive will be reported.
What is the use case of having the same text in the span text and the aria allert live message? Why not using different information, if you want to communicate something via the aria live message?
I am closing this as invalid, ut feel free to comment on the use case and we can reopen the discussion.
@mattgh94 can you please open a new issue with exact steps to reproduce and a minimal test case for your use case? I didn't get fully the problem you describe in the last comment.

**Closed by Adriani90** 2024-10-03 13:56 UTC
Labels: close/invalid, ARIA, app/chrome, app/internet-explorer, bug/double-speaking
