### ISSUE TITLE
After latest update NVDA hangs Windows 10 System: Google Chrome hangs, Cursor isn't controlled, CPU usage increases up to 99%

### ISSUE THREAD

**Issue by aloeugene** [nvaccess/nvda#10346] opened 2019-10-07 16:19 UTC
### Steps to reproduce:
1. Launch NVDA
2. Launch Google Chrome (Version 77.0.3865.90 (Official Build) (64-bit))
3. Just use browser as usual

### Actual behavior:
NVDA stops announcing, Chrome is in "Not responding" status, mouse cursor stops responding, "Insert + Q" hotkey doesn't turn off NVDA, and other system lags.

### Expected behavior:
No system lags at all.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Does the issue still occur after restarting your PC?
Yes

**Comment by lukaszgo1** [comment] 2019-10-07 16:27
cc @JulienCochuyt May this be caused by your Chrome fixes? I don't have Chrome installed myself, so cannot test.

**Comment by zstanecic** [comment] 2019-10-07 16:31
I cannot reproduce this.

 

Win 10 intel i3 6006u, lenovo ideapad 320 isk15

The latest alpha

**Comment by JulienCochuyt** [comment] 2019-10-07 17:08
> cc @JulienCochuyt May this be caused by your Chrome fixes? I don't have Chrome installed myself, so cannot test.

I hardly think so.
We just filter out huge base64 data from img src.
A log of the incident might be useful.
I do not reproduce either.

**Comment by dingpengyu** [comment] 2019-10-07 17:33
> ### Steps to reproduce:
> 1. Launch NVDA
> 2. Launch Google Chrome (Version 77.0.3865.90 (Official Build) (64-bit))
> 3. Just use browser as usual
> 
> ### Actual behavior:
> NVDA stops announcing, Chrome is in "Not responding" status, mouse cursor stops responding, "Insert + Q" hotkey doesn't turn off NVDA, and other system lags.
> 
> ### Expected behavior:
> No system lags at all.
> 
> ### System configuration
> #### NVDA installed/portable/running from source:
> Installed
> 
> #### NVDA version:
> 2019.2.1
> 
> #### Windows version:
> #### Name and version of other software in use when reproducing the issue:
> #### Other information about your system:
> ### Other questions
> #### Does the issue still occur after restarting your PC?
> Yes
> 
> #### Have you tried any other versions of NVDA? If so, please report their behaviors.
hi aloeugene
I used Google Chrome version 77.0.3865.75 x64 plus NVDA version alpha-18874 plus NVDA2019.2.1 according to your feedback. I did not reproduce the related issues on my Lenovo Saver notebook.
thank

**Comment by Adriani90** [comment] 2019-10-07 19:24
Could you please try to reproduce this with last NVDA Alpha? I am using it and I cannot reproduce this issue. I am on Chrome now and everything works as expected.
You can find the last alpha here:
https://www.nvaccess.org/files/nvda/snapshots/

**Comment by Brian1Gaff** [comment] 2019-10-08 07:59
Did he try this with a clean copy with no add ons?
 Brian

bglists@blueyonder.co.uk 
Sent via blueyonder. 
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by tech55541** [comment] 2019-10-14 23:43
Hello,

This happens for me in Chrome when first opening it. CPU can sometimes sky rocket. My environment is:

Windows 7 Professional, 16GB CPU, Intel quad core 3.7GHZ

Other websites such as helpscout.net and bitbucket.org can also make load increase and NVDA become non-responsive.

Thanks.

**Comment by Adriani90** [comment] 2020-05-27 22:37
I think this is telated to websites where many elements have to be rendered (i.e. tables with thousants of rows). But this is not Chrome specific. There are already some issue about this out there but I cannot find them just now.

**Comment by JulienCochuyt** [comment] 2020-05-28 06:32
@aloeugene, do you still experience this faulty behavior with latest Chrome?
Also, as pointed out by @Brian1Gaff in https://github.com/nvaccess/nvda/issues/10346#issuecomment-539397350, it seems you've removed two questions when filling the bug report template. Please take the time to answer these as well:
> #### If addons are disabled, is your problem still occuring?

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Note the COM registry fixing tool often needs restarting the PC to fully take effect.

**Comment by aloeugene** [comment] 2020-05-28 08:25
@JulienCochuyt, I haven't really tested the issue for couple months already. I've switched to MacOS 2 months after opening this issue, so I currently cannot test this out 😬

**Comment by Adriani90** [comment] 2020-05-28 14:21
Unfortunately we are not able to really reproduce this reliably. I know that there were big improvements in Chrome 83 and Chrome 81 regarding performance on complex web pages.
I am closing this issue for now but please feel free to comment on it in case you are still able to reproduce and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-28 14:21 UTC
