### ISSUE TITLE
Incorrect display of element position information when that information is not available

### ISSUE THREAD

**Issue by tarikhadzirovicofficial** [nvaccess/nvda#17207] opened 2024-09-23 18:37 UTC
I understand that the nature of this function is unstable, as it retrieves information when it is not available. However, I am curious if there is any way to change the approach to that information, whether it's counting or something else.
So, when in NVDA settings, in the "Object Presentation" category, the checkbox "Report object position information" along with "Guess object position information when unavailable" is checked, NVDA reports the position of elements for which this information is not already embedded and inherently available.

### Steps to reproduce:

1. Open the Add-on Store.
2. Navigate to the tab list.

### Actual behavior:

NVDA says:

* Installed add-ons tab selected 1 of 6
* Updatable add-ons tab selected 2 of 6
* Available add-ons tab selected 3 of 6
* Installed incompatible add-ons tab selected 4 of 6

As we know, only four categories are available here, not six as NVDA represents.

### Expected behavior:

NVDA should be announcing the correct number of items.

### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2024.3.1.33894
#### Windows version:
Windows 11 23H2 (AMD64) build 22631.4169
#### Name and version of other software in use when reproducing the issue:
NVDA 2024.3.1

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Their behaviors were same.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment] 2024-09-23 23:46
Duplicate of #14976

**Closed by seanbudd** 2024-09-23 23:46 UTC
