### ISSUE TITLE
Vscode reading issue with screenreaders

### ISSUE THREAD

**Issue by snufas** [nvaccess/nvda#10105] opened 2019-08-16 14:54 UTC
- Version: 1.37.1 (user setup)
-  Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
- Date: 2019-08-15T16:17:55.855Z
- Electron: 4.2.7
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.31-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

hello, I have a problem with nvda reading code in the  visual studio code application. I am  providing example code below and how nvda reads the code I took the output from the speech viewer.
the code sample I am trying to read 

text = print("hello world ")
vs code speech reading by word using ctrl plus right arrow. 

- text = 
- text = 
- print("
- hello 
- hello 
- world ")
- world ")

so, from the output above we can clearly  identify that it is not correct simply because the information is repeated which confuses me where my cursor is. 
notepad++  same code output 

- =
- print
- ("
- hello
- world
- ")

for me notepad++  works much better then vs code does. I know it is related to electron being used in vs code, so the question is: is  something possible to do to solve the problem either by changing something in nvda or vs code? I just want to work with vs code Reliably  since it is so powerful, and everyone seams to use the editor now a days plus there is a tun of extensions available. 
For me the work around this problem is use ctrl plus shift plus right arrow, so I am selecting the code an then it reads the text as it should without  repetition. 
I wonder on which end the problem exists? I suspect that it is a nvda problem since cursor moves saime way,  on both notepad++ and vs code.  I am Shure that I am not the only one who is encountering  this problem, so there for it would be nice if someone could investigate this issue, so developers please notice this issue because it is important… 

I am posting same issue on NVDA and vs code github pages so it may get attention from both sides. 
Thanks for reading and I am hoping that this issue could be addressed  and fixed in the  future.

**Comment by Adriani90** [comment] 2020-05-25 16:12
This issue is in many application, it's simply because every application defines words in different ways and NVDA does include i.e. characters or spaces in the word navigation in some cases. You can for example also reproduce it in edit fields in Chrome etc. This issue is a duplicate of #7605. Closing as duplicate.

**Closed by Adriani90** 2020-05-25 16:12 UTC
Labels: close/duplicate
