### ISSUE TITLE
Large freeze when trying to go to line in windows notepad

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#15903] opened 2023-12-11 12:52 UTC
### Steps to reproduce:
* Open windows notepad
* type several lines
* Press Ctrl+g

### Actual behavior:
It is not possible to get go to line window information from first press. I must close window and re-open go to line window, after several seconds i can get window information but navigation inside is very sluggish

### Expected behavior:
NVDA should not freeze and be responsive in this area.

### NVDA logs, crash dumps and other attachments:
[NVDA-notepad.log](https://github.com/nvaccess/nvda/files/13635530/NVDA-notepad.log)

#### NVDA installed/portable/running from source:
Installed and portable, the same behaviour
#### NVDA version:
alpha-30286,c3055011, also reproduceable with 2023.3
#### Windows version:
(Windows 11 23H2 (AMD64) build 22631.2792
#### Name and version of other software in use when reproducing the issue:
Microsoft.WindowsNotepad 11.2310.13.0

#### Other information about your system:
It is observed On a different machine.
The bug is not reproduceable with Jaws and Narrator

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same with 2023.3
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Didn't try

**Comment by zstanecic** [comment] 2023-12-11 13:51
I can reproduce this issue, too and i can confirm it on windows 11, 23h2, latest possible notepad from microsoft store.
There is just one small difference: i get no logs as the output, it just freezes endlessly.

**Comment by a11cf0** [comment] 2023-12-11 17:35
I can  also confirm this. No log output in my case.

**Comment by cary-rowen** [comment] 2023-12-13 10:05
Are there any "potential freezes" in the log?

**Comment by a11cf0** [comment] 2023-12-13 12:57
[Freeze.log](https://github.com/nvaccess/nvda/files/13660890/Freeze.log)
Okay, here's what I get in the log.

**Comment by Adriani90** [comment] 2024-02-22 21:16
I get following to the log with all addons disabled in NVDA last alpha:

```
IO - inputCore.InputManager.executeGesture (22:07:56.379) - winInputHook (10052):
Input: kb(laptop):control+home
DEBUG - editableText.EditableText._hasCaretMoved (22:07:56.388) - MainThread (15272):
Caret move detected using event. Elapsed 0 sec, retries 0
IO - speech.speech.speak (22:07:56.393) - MainThread (15272):
Speaking ['Steps to reproduce:\r']
IO - inputCore.InputManager.executeGesture (22:07:57.754) - winInputHook (10052):
Input: kb(laptop):control+g
INFO - watchdog.waitForFreezeRecovery (22:07:58.295) - watchdog (20184):
Starting freeze recovery after 0.5001598999999715 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (22:07:58.298) - watchdog (20184):
Listing stacks for Python threads:
Python stack for thread 12624 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 3860 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x06A63F30>)):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "watchdog.pyc", line 382, in run
  File "threading.pyc", line 629, in wait
  File "threading.pyc", line 327, in wait

Python stack for thread 8772 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 452, in _run
  File "winUser.pyc", line 460, in getMessage

Python stack for thread 20184 (watchdog):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "watchdog.pyc", line 159, in _watcher
  File "watchdog.pyc", line 166, in waitForFreezeRecovery
  File "logHandler.pyc", line 64, in getFormattedStacksForAllThreads

Python stack for thread 10052 (winInputHook):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 9784 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "UIAHandler\__init__.pyc", line 534, in MTAThreadFunc
  File "queue.pyc", line 171, in get
  File "threading.pyc", line 327, in wait

Python stack for thread 9236 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "threading.pyc", line 982, in run
  File "concurrent\futures\thread.pyc", line 81, in _worker

Python stack for thread 16532 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 1002, in _bootstrap
  File "threading.pyc", line 1045, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 258, in run

Python stack for thread 15272 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 892, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 822, in processRequest
  File "core.pyc", line 837, in Notify
  File "IAccessibleHandler\__init__.pyc", line 1059, in pumpAll
  File "IAccessibleHandler\__init__.pyc", line 650, in processGenericWinEvent
  File "IAccessibleHandler\__init__.pyc", line 560, in winEventToNVDAEvent
  File "UIAHandler\__init__.pyc", line 1229, in isUIAWindow
  File "UIAHandler\__init__.pyc", line 1145, in _isUIAWindowHelper

DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (22:07:59.961) - Dummy-1 (8460):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1292, in getNearestWindowHandle
_ctypes.COMError: (-2146233083, None, (None, None, None, 0, None))
INFO - watchdog.waitForFreezeRecovery (22:07:59.968) - watchdog (20184):
Recovered from freeze after 2.172503000000006 seconds.
IO - speech.speech.speak (22:07:59.973) - MainThread (15272):
Speaking ['Fenster', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (22:08:01.437) - winInputHook (10052):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (22:08:01.748) - winInputHook (10052):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (22:08:01.918) - winInputHook (10052):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (22:08:02.238) - winInputHook (10052):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (22:08:02.696) - winInputHook (10052):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (22:08:02.876) - winInputHook (10052):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (22:08:03.028) - winInputHook (10052):
Input: kb(laptop):downArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (22:08:03.213) - watchdog (20184):
Potential freeze, waiting up to 10 seconds.
IO - inputCore.InputManager.executeGesture (22:08:03.276) - winInputHook (10052):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (22:08:03.843) - winInputHook (10052):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (22:08:04.014) - winInputHook (10052):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (22:08:04.138) - winInputHook (10052):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (22:08:04.370) - winInputHook (10052):
Input: kb(laptop):upArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (22:08:05.216) - watchdog (20184):
Recovered from potential freeze after 2.5043062999999393 seconds.
```

**Comment by Adriani90** [comment] 2024-02-22 21:43
it seems only the go to dialog is affected.
cc: @josephsl could this be related to #14622?

**Comment by josephsl** [comment] 2024-02-23 00:48
Hi,

I don't think so as I can reproduce this with Notepad status bar getter code removed.

Thanks.

**Comment by XLTechie** [comment] 2024-02-23 04:53
Can repro in W11, 23H2.
Tried in 2024.1beta7 and alpha 31154.

**Comment by seanbudd** [comment] 2024-04-29 01:45
Has this been reported to Microsoft? They may be able to provide more information on the cause.
[Accessibility Insights](https://accessibilityinsights.io/) may help with debugging here, by tracking what Windows events are raised.

**Comment by beqabeqa473** [comment] 2024-04-29 05:33
this problem only happens with nvda.

**Comment by seanbudd** [comment] 2024-04-29 05:39
@beqabeqa473 - the issue is likely with Notepad raising events incorrectly. It doesn't really matter if the issue can only be reproduced with NVDA

**Comment by beqabeqa473** [comment] 2024-04-29 10:24
i tried Accessibility Insights, but unfortunately, when keeping goto window opened, whole system performance with nvda is slowing down, and Accessibility Insights is not responding untill i close goto window in notepad.

**Comment by seanbudd** [comment] 2024-04-30 07:12
A sighted dev is probably needed here to debug this without NVDA running. Alternatively, using Narrator/JAWS + Accessibility Insights

**Comment by seanbudd** [comment] 2024-06-06 02:05
This needs to be reported to Microsoft, debugging showed UIA events being flooded

**Comment by mzanm** [comment] 2024-06-23 11:40
Hello. I'm running Windows 11 24H2 (ARM64) build 26100.863 and Notepad - version 11.2405.13.0 and I no longer encounter any lag, navigating the dialog is smooth.
However, NVDA detects the line number edit box as a dialog, which results in NVDA not announcing the value when tabbing to it.
Should I report that in another issue? It would be great if someone else could confirm both of these. Thanks.

**Comment by seanbudd** [comment] 2024-06-24 04:20
please open a new bug report for separate issues

**Comment by SaschaCowley** [comment] 2024-08-27 05:49
Using Notepad 11.2407.3.0 and I can't reproduce this. Closing as fixed.

**Closed** 2024-08-27 05:55 UTC
Labels: blocked/needs-external-fix, bug/app-freeze, p2, triaged
