### ISSUE TITLE
NVDA treats an empty HTML table row like the edge of the table

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4927] opened 2015-02-16 19:25 UTC
**Reported by spmealin on 2015-02-16 19:25**
When navigating a table using the table commands (ctrl+alt+arrow keys), NVDA treats an empty table row (an opening tr tag followed directly by a closing tr tag) as the edge of the table, even though there may be more rows beyond that empty table row.  This can be seen at the URL https://news.ycombinator.com/ for example.

This problem is found in both Firefox 35.0.1 and Internet Explorer 11.0.9600.17631 with NVDA 2014.4.

**Comment by david-kirkland** [comment] 2016-07-14 22:20
It has the same bug for a row with a single th.

```
<tr>
  <th></th>
</tr>
```

...in a table like this...

```
<table>
  <thead>
    <tr>
      <th>a</th>
      <th>b</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th id="test-1" colspan="3">this one creates an error</th>
    </tr>
    <tr>
      <th headers="test-1">row header 1</th>
      <td headers="test-1"></td>
      <td headers="test-1"></td>
    </tr>
    <tr>
      <th headers="test-1">row header 2</th>
      <td headers="test-1"></td>
      <td headers="test-1"></td>
    </tr>
    <tr>
      <th id="test-2" colspan="3">this one creates an error</th>
    </tr>
    <tr>
      <th headers="test-2">row header 3</th>
      <td headers="test-2"></td>
      <td headers="test-2"></td>
    </tr>
  </tbody>
</table>
```

**Comment by bhavyashah** [comment] 2018-08-19 03:02
@leonardder I was unable to replicate such an issue with the one table present on https://news.ycombinator.com/. Could you please provide a status update for this ticket?

**Comment by Adriani90** [comment] 2019-01-20 01:32
In Chrome it also works as expected. So it seems the issue is only related to internet explorer.

**Comment by Adriani90** [comment] 2023-03-09 01:01
I could reproduce this now in Firefox 110 with NVDA last alpha. Following error is relevant:

IO - inputCore.InputManager.executeGesture (01:57:42.175) - winInputHook (15136):
Input: kb(laptop):t
IO - speech.speech.speak (01:57:42.190) - MainThread (18264):
Speaking ['Keine weitere Tabelle']
IO - inputCore.InputManager.executeGesture (01:57:42.738) - winInputHook (15136):
Input: kb(laptop):downArrow
IO - speech.speech.speak (01:57:42.768) - MainThread (18264):
Speaking ['Link', 'Guidelines', ' | ']
IO - inputCore.InputManager.executeGesture (01:57:43.560) - winInputHook (15136):
Input: kb(laptop):alt+control+rightArrow
IO - speech.speech.speak (01:57:43.591) - MainThread (18264):
Speaking ['Tabellenrand']
IO - speech.speech.speak (01:57:43.607) - MainThread (18264):
Speaking ['Tabelle', 'mit 1 Zeilen und 1 spalten', 'Reihe 1', 'Spalte 1', ' ', 'Tabelle Ende', '\n', 'Link', 'Guidelines', ' | ', 'Link', 'FAQ', ' | ', 'Link', 'Lists', ' | ', 'Link', 'API', ' | ', 'Link', 'Security', ' | ', 'Link', 'Legal', ' | ', 'Link', 'Apply to YC', ' | ', 'Link', 'Contact', '\n\n', 'Search: ', 'Eingabefeld', ' ']
IO - inputCore.InputManager.executeGesture (01:57:43.989) - winInputHook (15136):
Input: kb(laptop):alt+control+leftArrow
IO - speech.speech.speak (01:57:44.019) - MainThread (18264):
Speaking ['Tabellenrand']
ERROR - scriptHandler.executeScript (01:57:44.023) - MainThread (18264):
error executing script: <bound method DocumentWithTableNavigation.script_previousColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x084DAC90>> with gesture 'Alt+Strg+Pfeiltaste nach links'
Traceback (most recent call last):
  File "documentBase.pyc", line 362, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 577, in _getNearestTableCell
  File "documentBase.pyc", line 276, in _getNearestTableCell
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 559, in _getTableCellAt
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "documentBase.pyc", line 384, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 567, in _getTableCellAt
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "documentBase.pyc", line 485, in script_previousColumn
  File "documentBase.pyc", line 417, in _tableMovementScriptHelper
  File "documentBase.pyc", line 386, in _tableFindNewCell
RuntimeError: ('Unable to find current cell.', LookupError())

I think this could be a web authoring issue. But without a minimal test case it will be difficult to detect where exactly the problem is.

**Comment by Adriani90** [comment] 2024-03-27 20:38
This is not reproducible anymore with NvDA 2024.1 RC1 and Firefox 124.0.1. Closing as works for me.

**Closed by Adriani90** 2024-03-27 20:38 UTC
Labels: bug, close/worksforme, feature/browse-mode, app/internet-explorer
