### ISSUE TITLE
HTML file input value is not read in Chrome

### ISSUE THREAD

**Issue by tahoon-ms** [nvaccess/nvda#9710] opened 2019-06-10 16:37 UTC
### Steps to reproduce:
1. Open Chrome
2. Go to any website that has a HTML file input (`<input type="file">`)
3. Activate the input and select a file
4. Press SHIFT+TAB and then TAB again to focus the control

### Actual behavior:
NVDA reads the name of the control and the selected file.

### Expected behavior:
NVDA just reads the name of the control

#### NVDA version:
2019.1.1

#### Windows version:
10.0.18362 Build 18362

#### Name and version of other software in use when reproducing the issue:
Chrome version: 74.0.3729.169

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No. NVDA debug log doesn't seem to be useful. Looks like a Chrome bug.

**Comment by Adriani90** [comment] 2020-05-20 22:08
@tahoon-ms could you please test with NVDA 2020.1 and Chrome 83?

Please also provide a test website where we can reproduce this. Thankks.

**Comment by tahoon-ms** [comment] 2020-05-20 23:26
I tried with latest NVDA and Chrome and the issue is still there. It's really easy to repro. I have created a simple sandbox at https://output.jsbin.com/nuxujiloqi.
Here is the HTML if the site is down:
```
<button>hello</button>
<input type='file' aria-label='example' />
<button>goodbye</button>
```

It's a file input sandwiched by two buttons for convenience.

1. Tab to the file input. NVDA just says "example, button" and does not mention it is is part of the file input control.
2. Select a file with the file input. After selecting a file, tab to the button next to it and then shift + tab back to the file input. NVDA just says "example, button" and does not mention which file was selected.

Chrome Version 83.0.4103.61
NVDA 2020.1

**Comment by Adriani90** [comment] 2023-03-22 22:55
Testing with NVDA 2023.1 RC1, the issue is reproducible only when pressing tab or shift+tab while you are in browse mode.

In focus mode the file is spoken when you press tab or shift+tab. This works also as expected when you press nvda+tab or nvda+shift+o in brose mode to report the currently focues object.

**Comment by Adriani90** [comment] 2024-11-07 15:25
In Chrome Canary 132, everything works as expected, but now the selected file is repeated twice. I am closing as works for me.

**Closed by Adriani90** 2024-11-07 15:25 UTC
Labels: close/worksforme
