### ISSUE TITLE
error when outlook 2010 is starting

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4749] opened 2014-12-25 07:27 UTC
**Reported by mohammed on 2014-12-25 07:27**
NVDA: next-11418,187fad1

when outlook is starting, NVDA plays error sound and the following is found in the log:

DEBUGWARNING - RPC process 5792 (nvda_slave.exe) (10:15:45):
Python warning:
C:\Program Files (x86)\NVDA\library.zip\configobj.py:28: DeprecationWarning: The compiler package is deprecated and removed in Python 3.x.
ERROR - RPC process 5792 (nvda_slave.exe) (10:15:45):
**main**.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 90, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client__init__.pyc", line 180, in GetActiveObject
  File "comtypes__init__.pyc", line 1165, in GetActiveObject
  File "_ctypes/callproc.c", line 945, in GetResult
WindowsError: [-2147221021](Error) Operation unavailable

possibly a regression caused by #2975?

**Comment by bhavyashah** [comment] 2017-10-11 07:50
According to the original author's https://github.com/nvaccess/nvda/issues/4749#issuecomment-155331755, the reported error has no user-facing implications whatsoever, unless Outlook status bar reading being possible only after an Alt+Tab back and forth is considered related behaviour. As noted subsequently in https://github.com/nvaccess/nvda/issues/4749#issuecomment-155331760, this error ceases after an Alt+Tab back and forth, may fix itself in some time (indicating that this error is not consistently reproducible), User mohammed  concludes by suggesting the priority Trivial (now P4) or closing this ticket altogether. Since this ticket is over two years old and we seem to have receivved this report of an NVDA error during Outlook 2010 startup exclusively, I find it likely that this issue may not even transpire anymore. Unfortunately however, I do not use Outlook at all, making me unable to contribute any substantial testing feedback.

**Comment by feerrenrut** [comment] 2017-10-18 08:19
Closing this issue, if anyone can reproduce this issue please comment and we will investigate further.

**Closed by feerrenrut** 2017-10-18 08:19 UTC
Labels: bug, Microsoft Office support
