### ISSUE TITLE
NVDA only announcing link and button title text in IE9

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4815] opened 2015-01-15 16:45 UTC
**Reported by Adsmith289 on 2015-01-15 16:45**
In IE7, when we have web page links or buttons with titles and the titles are different than the displayed link or button text, NVDA only announces the title text, twice, and not the displayed text. 
Code example:
`<a title="Select to see more of what you have been doing" href="/company.net/tells/requests.html">View Recent Activity</a>`
Result: This will be announced as "Select to see more of what you have been doing, link, Select to see more of what you have been doing."
Similar results for buttons.

**Comment by ehollig** [comment] 2017-08-17 14:46
I am not able to reproduce this using IE 11 and the attached example.
[example.html.txt](https://github.com/nvaccess/nvda/files/1231619/example.html.txt)

1. Open the attach document (after removing the .txt extention) in Internet Explorer.
2. Arrow down to the link.
3. NVDA reports the link text.
4. Go to the top of the page and navigate to the next link by pressing K.
5. Same results.

With regards to buttons, this will be covered in #3158. Closing, unless someone can produce a different behavior.

**Closed by ehollig** 2017-08-17 14:46 UTC
Labels: bug
