### ISSUE TITLE
NVDA crashes Google Chrome on certain websites

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#15451] opened 2023-09-14 22:09 UTC
NVDA's interaction with webpages on some websites crashes Google Chrome. Log is attached. Also I can't duplicate it with JAWS 2023.
### Steps to reproduce:
1. Go to the following website: https://www.raiplaysound.it/
2. Navigate a bit on the page, then press ALT+D to move to the Address Bar, then tab a couple of times to reach the Translate this page button.
3. Optionally, you may want to translate the page into English.
### Actual behavior:
While interacting with the page contents or as the cursor moves around upon pressing ALT+D then Tab, Google Chrome crashes. Sometimes NVDA remains silent.
### Expected behavior:
No crash should occur whatsoever.
### System configuration
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/12613915/nvda-old.log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha 29194
#### Windows version:
Windows 11, 22 H2, (OS Build 22621.2283)
#### Name and version of other software in use when reproducing the issue:
Google Chrome version 117.0.5938.63
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2023.3 Beta 1, the same crash
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes, happens without add-ons
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by leonardder** [comment] 2023-09-15 08:49
Could you also test this with 2023.2 stable? We need to know whether this is a recent regression.

**Comment by amirsol81** [comment] 2023-09-15 08:52
@leonardder Sure, but can I do it from a portable installation? It's much easier and doesn't require several installation/uninstallation efforts.

**Comment by Adriani90** [comment] 2023-09-15 17:03
I tested and could reproduce this crash of Chrome with NVDA 2023.2 and NVDA 2023.1 as well. Here is a crashdump from Chrome and the chrome debug log file. This should be sent to the Chrome developers I guess, but maybe also NVDA developers can look into it. i could find the crash in the Chrome log file but I don't know the root of it.

It seems the crash is triggered either when closing the translation dialog via "close button", when accepting the cookies dialog or when refreshing the page.

The crash can be reproduced more reliably after deleting all the browser data in Chrome itself including coockies etc.

[chrome_debug.txt](https://github.com/nvaccess/nvda/files/12622035/chrome_debug.txt)
[afe50a87-91b8-40bd-b205-5f81f4f529bd.dmp.txt](https://github.com/nvaccess/nvda/files/12622036/afe50a87-91b8-40bd-b205-5f81f4f529bd.dmp.txt)

**Comment by Adriani90** [comment] 2023-09-17 07:21
Not sure if this is related, but I had a severe freeze of Chrome and NVDA while navigating the github website, I had to restart NVDA.
Here is the fragment of the log, addons are disabled:

```
IO - inputCore.InputManager.executeGesture (09:12:49.301) - winInputHook (20316):
Input: kb(laptop):downArrow
IO - speech.speech.speak (09:12:49.307) - MainThread (2304):
Speaking ['about:blank']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:12:49.312) - MainThread (2304):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:12:49.314) - MainThread (2304):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:12:49.316) - MainThread (2304):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:12:49.832) - winInputHook (20316):
Input: kb(laptop):downArrow
IO - speech.speech.speak (09:12:49.837) - MainThread (2304):
Speaking ['Überschrift', 'Ebene 2', 'How to Download a File from GitHub']
DEBUGWARNING - RPC process 2764 (chrome.exe) (09:12:50.281) - Dummy-4 (13224):
Thread 5344, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::unlinkFieldNode, 766:
Node at 000001C40AD64060 is not in buffer at 000001C40327B360. Returnning false

DEBUGWARNING - RPC process 2764 (chrome.exe) (09:12:50.284) - Dummy-4 (13224):
Thread 5344, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::removeFieldNode, 808:
Could not unlink field node

DEBUGWARNING - RPC process 2764 (chrome.exe) (09:12:50.287) - Dummy-4 (13224):
Thread 5344, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::replaceSubtrees, 687:
Error removing node. Skipping

DEBUGWARNING - RPC process 2764 (chrome.exe) (09:12:50.291) - Dummy-4 (13224):
Thread 5344, build\x86_64\vbufBase\backend.cpp, VBufBackend_t::update, 215:
Error replacing one or more subtrees

IO - inputCore.InputManager.executeGesture (09:12:51.031) - winInputHook (20316):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (09:12:51.394) - winInputHook (20316):
Input: kb(laptop):downArrow
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (09:12:51.545) - watchdog (7040):
Potential freeze, waiting up to 10 seconds.
IO - inputCore.InputManager.executeGesture (09:12:51.811) - winInputHook (20316):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (09:12:52.332) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:52.511) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:52.689) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:52.894) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:53.073) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:53.667) - winInputHook (20316):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (09:12:56.499) - winInputHook (20316):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (09:12:57.108) - winInputHook (20316):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (09:12:57.403) - winInputHook (20316):
Input: kb(laptop):alt+tab
IO - inputCore.InputManager.executeGesture (09:12:58.321) - winInputHook (20316):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (09:12:58.493) - winInputHook (20316):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (09:12:59.271) - winInputHook (20316):
Input: kb(laptop):windows+m
IO - inputCore.InputManager.executeGesture (09:12:59.670) - winInputHook (20316):
Input: kb(laptop):ö
INFO - watchdog.waitForFreezeRecovery (09:12:59.717) - watchdog (7040):
Starting freeze recovery after 8.67221789999985 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (09:12:59.719) - watchdog (7040):
Listing stacks for Python threads:
Python stack for thread 10956 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x089FFC60>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 17932 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 455, in _run
  File "winUser.pyc", line 459, in getMessage

Python stack for thread 7040 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 165, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 20316 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6532 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 519, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 19832 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "concurrent\futures\thread.pyc", line 78, in _worker

Python stack for thread 10172 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 17924 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 2304 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 813, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "wx\core.pyc", line 3407, in <lambda>
  File "core.pyc", line 746, in processRequest
  File "core.pyc", line 762, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 561, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 274, in script_moveByLine_forward
  File "cursorManager.pyc", line 138, in _caretMovementScriptHelper
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 479, in __init__
  File "virtualBuffers\__init__.pyc", line 215, in _getSelectionOffsets

DEBUGWARNING - RPC process 16540 (StartMenuExperienceHost.exe) (09:13:00.265) - Dummy-6 (18780):
Thread 23248, build\x86_64\remote\ia2Support.cpp, IA2Support_inProcess_initialize, 169:
Not installing IA2 support as  process is suspendable

ERROR - watchdog.waitForFreezeRecovery (09:13:14.724) - watchdog (7040):
Core frozen in stack! (23.67916349999996 seconds)
INFO - watchdog.waitForFreezeRecovery (09:13:14.844) - watchdog (7040):
Listing stacks for Python threads:
Python stack for thread 24160 (nvwave.playWaveFile(error.wav)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
  File "nvwave.pyc", line 379, in feed
  File "nvwave.pyc", line 394, in _feedUnbuffered_handleErrors
  File "nvwave.pyc", line 424, in _feedUnbuffered

Python stack for thread 10956 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x089FFC60>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 17932 (visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 455, in _run
  File "winUser.pyc", line 459, in getMessage

Python stack for thread 7040 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 158, in _watcher
  File "watchdog.pyc", line 186, in waitForFreezeRecovery
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 20316 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 6532 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 519, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 19832 (ThreadPoolExecutor-0_0):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "concurrent\futures\thread.pyc", line 78, in _worker

Python stack for thread 10172 (synthDrivers._espeak.BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "synthDrivers\_espeak.pyc", line 201, in run
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 17924 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 283, in run

Python stack for thread 2304 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 813, in main
  File "wx\core.pyc", line 2237, in MainLoop
  File "wx\core.pyc", line 3407, in <lambda>
  File "core.pyc", line 746, in processRequest
  File "core.pyc", line 762, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "scriptHandler.pyc", line 243, in _queueScriptCallback
  File "keyboardHandler.pyc", line 561, in executeScript
  File "inputCore.pyc", line 222, in executeScript
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 274, in script_moveByLine_forward
  File "cursorManager.pyc", line 138, in _caretMovementScriptHelper
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 479, in __init__
  File "virtualBuffers\__init__.pyc", line 215, in _getSelectionOffsets

DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (09:13:17.349) - Dummy-3 (17732):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1230, in getNearestWindowHandle
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'Ein Ereignis konnte keinen Abonnenten
```

**Comment by Adriani90** [comment] 2023-09-17 07:22
I use NVDA alpha-29167,89c815bb (2024.1.0.29167)

**Comment by seanbudd** [comment] 2023-09-18 23:46
Has this been reported to Chrome? We need technical information from them to confirm if this is an NVDA bug

**Comment by amirsol81** [comment] 2023-09-19 02:02
@Adriani90 @seanbudd I haven't reported it to Google - really don't know how, but the point is that I can't duplicate this glitch using JAWS. That's why I thought it might be more of an NVDA issue.

**Comment by seanbudd** [comment] 2023-09-19 02:07
I found this guide by googling "report chrome bug": https://support.google.com/chrome/answer/95315?hl=en&co=GENIE.Platform%3DDesktop

If you are comfortable with the more technical GitHub style reporting, you can file an issue directly with their issue tracker: https://www.chromium.org/for-testers/bug-reporting-guidelines/reporting-crash-bug/

The files @Adriani90 provided would be helpful to send with the report, but shouldn't be necessary if it easy to reproduce

**Comment by Adriani90** [comment] 2023-09-19 02:37
Ok here are some further errors I could catch while the crash occured,

```
DEBUG - treeInterceptorHandler.update (04:25:30.142) - MainThread (7576):
Adding new treeInterceptor to runningTable: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x012B5910>
ERROR - virtualBuffers.VirtualBuffer._loadBuffer (04:25:30.529) - NVDAObjects.IAccessible.chromium.VirtualBuffer.loadBuffer (15252):
Traceback (most recent call last):
  File "virtualBuffers\__init__.pyc", line 464, in _loadBuffer
OSError: [WinError 1726] Der Remoteprozeduraufruf ist fehlgeschlagen
```




```
IO - inputCore.InputManager.executeGesture (04:29:08.390) - winInputHook (23412):
Input: kb(laptop):downArrow
IO - speech.speech.speak (04:29:08.413) - MainThread (7576):
Speaking ['Englisch', 'Registerkarte', 'ausgewählt', CancellableSpeech (still valid)]
IO - speech.speech.speak (04:29:08.439) - MainThread (7576):
Speaking ['Übersetzungsoptionen', 'Schalter', CancellableSpeech (still valid)]
IO - speech.speech.speak (04:29:08.455) - MainThread (7576):
Speaking ['Schließen', 'Schalter', CancellableSpeech (still valid)]
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (04:29:08.517) - watchdog (17560):
Potential freeze, waiting up to 10 seconds.
IO - speech.speech.speak (04:29:08.690) - MainThread (7576):
Speaking ['Link', 'Überschrift', 'Ebene 3', 'Rai Radio Trst A']
IO - speech.speech.speak (04:29:08.699) - MainThread (7576):
Speaking ['Grafik', 'Ascolta in diretta Rai Radio Trst A']
IO - speech.speech.speak (04:29:08.915) - MainThread (7576):
Speaking ['Übersetzung in die Sprache Englisch abgeschlossen', 'Benachrichtigung', CancellableSpeech (still valid)]
DEBUG - watchdog._waitUntilNormalCoreAliveTimeout (04:29:09.027) - watchdog (17560):
Recovered from potential freeze after 1.009782800000039 seconds.
IO - inputCore.InputManager.executeGesture (04:29:09.098) - winInputHook (23412):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (04:29:09.407) - winInputHook (23412):
Input: kb(laptop):downArrow
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2States (04:29:09.499) - MainThread (7576):
could not get IAccessible2 states
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 1894, in _get_IA2States
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147023170, 'Der Remoteprozeduraufruf ist fehlgeschlagen.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (04:29:09.500) - MainThread (7576):
IAccessibleObject.attributes COMError (-2147023174, 'Der RPC-Server ist nicht verfügbar.', (None, None, None, 0, None))
DEBUGWARNING - scriptHandler.executeScript (04:29:09.501) - MainThread (7576):
error executing script: <bound method CursorManager.script_moveByLine_back of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x01040050>> with gesture 'Pfeiltaste nach oben'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 270, in script_moveByLine_back
  File "cursorManager.pyc", line 138, in _caretMovementScriptHelper
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 479, in __init__
  File "virtualBuffers\__init__.pyc", line 215, in _getSelectionOffsets
OSError: [WinError 1753] In der Endpunktzuordnung sind keine weiteren Endpunkte verfügbar
DEBUGWARNING - scriptHandler.executeScript (04:29:09.501) - MainThread (7576):
error executing script: <bound method CursorManager.script_moveByLine_forward of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x01040050>> with gesture 'Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 274, in script_moveByLine_forward
  File "cursorManager.pyc", line 138, in _caretMovementScriptHelper
  File "documentBase.pyc", line 74, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 210, in __init__
  File "textInfos\offsets.pyc", line 479, in __init__
  File "virtualBuffers\__init__.pyc", line 215, in _getSelectionOffsets
OSError: [WinError 1753] In der Endpunktzuordnung sind keine weiteren Endpunkte verfügbar
DEBUG - browseMode.BrowseModeDocumentTreeInterceptor.terminate (04:29:09.501) - MainThread (7576):
Saving caret position Offsets(startOffset=1652, endOffset=1652) for document at https://www.raiplaysound.it/
DEBUG - treeInterceptorHandler.killTreeInterceptor (04:29:09.503) - MainThread (7576):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x01040050>
DEBUG - config.ConfigManager._triggerProfileExit (04:29:09.513) - MainThread (7576):
Deactivating triggered profile Chrome

**Comment by Adriani90** [comment] 2023-09-19 02:40
It seems there is a problem with the RPC server when calling the remote process, however I am not as skilled to understand exactly how those process calls are really working, but it seems it is also related to different endpoints.

**Comment by Adriani90** [comment] 2023-09-19 02:43
I am not sure a user can really report this to Google without any technical background.

cc: @aleventhal, @ObjectInSpace could we have a conversation here whether this is NVDA bug or not, before reporting it to Chromium? I think this might be more efficient.

**Comment by seanbudd** [comment] 2023-09-19 02:47
>I am not sure a user can really report this to Google without any technical background.

The information in the bug report provided here by @amirsol81 is totally sufficient to report to Google.
They don't need more information than us in a bug report. Just a way to reproduce the issue and a crash log if possible or reproduction is difficult.
Chromium has a much larger team and capacity for debugging Chrome crashes.

**Comment by Adriani90** [comment] 2023-09-19 03:32
By the way the complete crash occurs also in Edge 117, so the most suitable place to report might be here:
https://bugs.chromium.org/p/chromium/issues/list

**Comment by amirsol81** [comment] 2023-09-19 05:04
@Adriani90 @seanbudd While that argument re reporting to Google is definitely valid, the fact that JAWS doesn't exhibit this bug probably indicates that maybe something should be done at NVDA's end. Unfortunately I can't report this to Google, so would appreciate it if others do.

**Comment by CyrilleB79** [comment] 2023-09-19 08:02
> @Adriani90 @seanbudd While that argument re reporting to Google is definitely valid, the fact that JAWS doesn't exhibit this bug probably indicates that maybe something should be done at NVDA's end. Unfortunately I can't report this to Google, so would appreciate it if others do.

Be careful with such argument, it's not always true.
If NVDA does not use the same accessibility API as Jaws  or does not use them the same way, the crash can occur with NVDA and not with Jaws even if the bug lies in the application (e.g. Chrome).

Since Chrome is crashing, Chrome is the first place where the issue should be reported. When Chrome devs analyse the crash, they will be able to say if the crash is due to a bug internal to Chrome or if it is caused by NVDA performing  non authorized operations; in this last case, NVDA will have more information to fix the issue.

**Comment by leonardder** [comment] 2023-09-19 09:02
If this problem also occurs with Edge, there are some additional things to test:

1. Force UIA in Edge (advanced settings)
2. How about older version of Chrome/Edge? It might be a bit hard to disable updating though.

While I think reporting this upstream makes sense, we must at least try to be sure that this is not something in our injected vbuf code.

**Comment by amirsol81** [comment] 2023-09-19 09:36
@CyrilleB79 Again, as an NVDA user, sadly I don't have the time to report bugs on multiple fronts. This particular one affects NVDA and doesn't affect JAWS, so I'd rather report it here and leave the rest, including notifying Google, to NVAccess and others.
Moreover, there are other Chrome bugs, like NVDA's inability to spell bookmarks or menus with NVDA key+Up pressed twice, which have been reported to Google, but no action has been taken yet. The spelling NVDA spelling bug doesn't affect JAWS either.

**Comment by CyrilleB79** [comment] 2023-09-19 09:57
> @CyrilleB79 Again, as an NVDA user, sadly I don't have the time to report bugs on multiple fronts. This particular one affects NVDA and doesn't affect JAWS, so I'd rather report it here and leave the rest, including notifying Google, to NVAccess and others.

No problem. Everybody makes things or not depending on his/her possibility and available time, NV Access staff and contributors included.

Moreover, there are other Chrome bugs, like NVDA's inability to spell bookmarks or menus with NVDA key+Up pressed twice, which have been reported to Google, but no action has been taken yet. The spelling NVDA spelling bug doesn't affect JAWS either.

The situation is different. In the case of Chrome crash, we expect that Chrome never crashes but it does. Thus something is going wrong in Chrome's process, either in Chrome code or in NVDA's injected code as explained by @leonardder. In the case of the spelling issue, there is nothing specific, a priori, indicating that there is a Chrome issue.

When writing this, my concern was that sometimes, people make such assertion as the following:
"The bug is present with NVDA and not with Jaws/Narrator, so the cause is in NVDA's code"

I just want to emphasize that this assertion is not always true.

**Comment by Adriani90** [comment] 2023-09-19 10:12
Not only Chrome crashes, but also Edge as pointed above.

Enforcing UIA does not make any difference, both continue to crash with UIA enabled. So I guess it is not only the AP issue here, I am quite sure Jaws uses also UIA to  get information.

Nevertheless it is definitely worthy to start discussoins on the Chromium bug tracker as well. I will see if I have some time to report it there as well in the next days, though I would be glad if someone could take this over.

**Comment by leonardder** [comment] 2023-09-19 10:15
> Enforcing UIA does not make any difference, both continue to crash with UIA enabled.

That means it's not our VBuf in process code that's the culprit, which is at least nice for us.

**Comment by aleventhal** [comment] 2023-09-19 11:45
You can report the bug to Chrome at crbug.com, which is the best way to get
it looked at.
Ideally there would be both repro steps and a crash id.
You can get the crash id from the chrome://crashes page.

**Comment by Slivicon** [comment] 2023-09-19 15:33
Also ran into this issue with myself and a few people in my organization, both with Edge and Chrome, on Windows 10 Enterprise, using 2023.2. Also tried the COM fix and reboot, but issue persisted.

If it is of any help, here is the debug log output:
`IO - speech.speech.speak (11:13:04.149) - MainThread (15264):
Speaking [LangChangeCommand ('en_US'), 'Network Data Available ']
IO - speech.speech.speak (11:13:04.150) - MainThread (15264):
Speaking [LangChangeCommand ('en_US'), '4 requests 10.0\xa0kB transferred 0\xa0B resources   ']
DEBUG - config.featureFlag._validateConfig_featureFlag (11:13:04.160) - Dummy-1 (10264):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2WindowHandle (11:13:04.868) - MainThread (15264):
IAccessible2::windowHandle failed: (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speech.speak (11:13:05.025) - MainThread (15264):
Speaking [LangChangeCommand ('en_US'), 'Loading complete']
IO - speech.speech.speak (11:13:06.565) - MainThread (15264):
Speaking [LangChangeCommand ('en_US'), 'dialog', 'This page is having a problem\nTry coming back to it later.\nYou could also:\nOpen a new tab\nRefresh this page\nError code: STATUS_ACCESS_VIOLATION', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:13:06.565) - MainThread (15264):
Speaking [LangChangeCommand ('en_US'), 'Refresh', 'button', CancellableSpeech (still valid)]
IO - speech.speech.speak (11:13:07.797) - MainThread (15264):
`

**Comment by Adriani90** [comment] 2023-09-19 16:24
Created bug https://bugs.chromium.org/p/chromium/issues/detail?id=1484647

@aleventhal which template should we use for accessibility bug reports? I didn't find one suitable bug template and I reported several issues via chromium.org template but they didn't get any attention.

**Comment by aleventhal** [comment] 2023-09-19 19:43
Thanks for filing. When you file bugs, does it allow you to select a
component? If so, choose Blink>Accessibility.
I can't promise we will get traction on everything you file, but we will
try. Crash bugs definitely get attention.
For this one you filed, it has a crash id, but I believe that's the wrong
ID. I need the one from chrome://crashes for the report that is sent to our
servers.
Also, if you have the chance to try in Chrome Canary that would be helpful
as well.

**Comment by Adriani90** [comment] 2023-09-19 20:44
Hmm it seems in Canari 119.0.6018.0 I cannot reproduce this issue.
The only difference I see is that the menu which opens when you click the translating options button in the translation dialog in Chrome 117 does not get focus with NVDA while in Canary it does. This is the translation dialog which appears imediately after the website has loaded.

I think we can close this and continue the discussion on the Chromium bug in case something needs to be backported to Chrome 117 or so.

**Comment by Adriani90** [comment] 2023-09-19 20:52
@aleventhal thanks very much for your assistance.
When I create a new issue it says "please add a component" but I cannot choose one. The only think I can change is the template.

Also I cannot edit or close my own issues, I see the issues that I have reported at Chromium but they have the component infra>documentation and not blink>accessibility.

**Comment by seanbudd** [comment] 2023-09-19 23:40
Thanks for the investigation everyone.
Closing as fixed in Chrome canary

**Closed by seanbudd** 2023-09-19 23:40 UTC
Labels: p2, app/chrome, triaged, blocked/needs-technical-investigation

**Comment by bramd** [comment] 2023-10-09 14:36
I know this one is closed, but for other users who might experience a Chrome/Edge crash in 1Password while autofilling credentials, 1Password support indicated that the crash is also caused by this bug.
