### ISSUE TITLE
NVDA crashes after renaming a file in Windows Explorer

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#6772] opened 2017-01-20 05:54 UTC
On a Windows 8.1 laptop, NVDA is consistently crashing right now when I am renaming .MP3 files in the Downloads folder in Windows Explorer. Although I can replicate this with absolute repetition at the moment, this is something I am experiencing only during this Windows session. What is all the more curious that after I rename a file, Windows plays an error-indicating sort of sound, and then NVDA automatically restarts. I apologize for the length of this log snippet, but below pasted is all the log activity in the old NVDA session after I hit Enter to apply changes to my renamed file:
DEBUGWARNING - watchdog._watcher (11:20:25):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 190, in <module>
  File "core.pyo", line 385, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 355, in Notify
  File "IAccessibleHandler.pyo", line 891, in pumpAll
  File "IAccessibleHandler.pyo", line 658, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 525, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 299, in isUIAWindow
  File "_UIAHandler.pyo", line 293, in _isUIAWindowHelper

DEBUGWARNING - watchdog._watcher (11:20:26):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 190, in <module>
  File "core.pyo", line 385, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 356, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "eventHandler.pyo", line 61, in _queueEventCallback
  File "eventHandler.pyo", line 138, in executeEvent
  File "eventHandler.pyo", line 151, in doPreGainFocus
  File "api.pyo", line 107, in setFocusObject
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1493, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 475, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1479, in _get_parent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyo", line 266, in _get_parent
  File "NVDAObjects\__init__.pyo", line 184, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 102, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 299, in isUIAWindow
  File "_UIAHandler.pyo", line 293, in _isUIAWindowHelper
  File "watchdog.pyo", line 175, in _crashHandler
  File "logging\__init__.pyo", line 1212, in critical
  File "logHandler.pyo", line 134, in _log
  File "logging\__init__.pyo", line 1286, in _log
  File "logging\__init__.pyo", line 1296, in handle
  File "logging\__init__.pyo", line 1336, in callHandlers
  File "logHandler.pyo", line 218, in handle

CRITICAL - watchdog._crashHandler (11:20:26):
NVDA crashed! Minidump written to C:\Users\DELL-PC\AppData\Local\Temp\nvda_crash.dmp
INFO - watchdog._crashHandler (11:20:28):
Python stack for thread 4528
Stack trace:
  File "threading.pyo", line 774, in __bootstrap
  File "threading.pyo", line 801, in __bootstrap_inner
  File "threading.pyo", line 754, in run
  File "winInputHook.pyo", line 70, in hookThreadFunc
INFO - watchdog._crashHandler (11:20:28):
Python stack for thread 2868
Stack trace:
  File "threading.pyo", line 774, in __bootstrap
  File "threading.pyo", line 801, in __bootstrap_inner
  File "threading.pyo", line 754, in run
  File "_UIAHandler.pyo", line 198, in MTAThreadFunc
  File "threading.pyo", line 614, in wait
  File "threading.pyo", line 340, in wait
INFO - watchdog._crashHandler (11:20:28):
Python stack for thread 5036
Stack trace:
  File "threading.pyo", line 774, in __bootstrap
  File "threading.pyo", line 801, in __bootstrap_inner
  File "threading.pyo", line 754, in run
  File "watchdog.pyo", line 112, in _watcher
INFO - watchdog._crashHandler (11:20:28):
Python stack for thread 5084
Stack trace:
  File "threading.pyo", line 774, in __bootstrap
  File "threading.pyo", line 801, in __bootstrap_inner
  File "synthDrivers\_espeak.pyo", line 152, in run
  File "Queue.pyo", line 168, in get
  File "threading.pyo", line 340, in wait
INFO - watchdog._crashHandler (11:20:28):
Python stack for thread 4300
Stack trace:
  File "nvda.pyw", line 190, in <module>
  File "core.pyo", line 385, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 356, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "eventHandler.pyo", line 61, in _queueEventCallback
  File "eventHandler.pyo", line 138, in executeEvent
  File "eventHandler.pyo", line 151, in doPreGainFocus
  File "api.pyo", line 107, in setFocusObject
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1493, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 475, in _get_container
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyo", line 1479, in _get_parent
  File "baseObject.pyo", line 34, in __get__
  File "baseObject.pyo", line 110, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyo", line 266, in _get_parent
  File "NVDAObjects\__init__.pyo", line 184, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyo", line 102, in getPossibleAPIClasses
  File "_UIAHandler.pyo", line 299, in isUIAWindow
  File "_UIAHandler.pyo", line 293, in _isUIAWindowHelper
  File "watchdog.pyo", line 180, in _crashHandler
INFO - watchdog._crashHandler (11:20:28):
Restarting due to crash

**Comment by josephsl** [comment] 2017-01-20 05:57
Hi, can you attach the dump file, perhaps zipped up inside a .zip file? Thanks.

**Comment by derekriemer** [comment] 2017-01-20 07:48
If you don't know how to do this, go grab [Crash Hero](http://addons.nvda-project.org/addons/crashHero.en.html) and zip what it gives you.
Thanks.

**Comment by bhavyashah** [comment] 2017-01-20 07:55
I hope an e-mail attachment comes across, since I am currently
replying via mail itself and have attached the zipped version of the
crash contents. Thanks Joseph for the instructions, and Derek for the
Crash Hero add-on which helped me in locating and zipping the same.
Thanks.

On 1/20/17, derekriemer <notifications@github.com> wrote:
> If you don't know how to do this, go grab [Crash
> Hero](http://addons.nvda-project.org/addons/crashHero.en.html) and zip what
> it gives you.
> Thanks.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6772#issuecomment-273999588


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by leonardder** [comment] 2017-01-20 18:10
I'm afraid the attachment didn't come through.
De issue you describe looks very similar to #6384.

**Comment by bhavyashah** [comment] 2017-01-20 18:15
[Fri 20 January 2017 13-23-42 File Renaming Crash.zip](https://github.com/nvaccess/nvda/files/720159/Fri.20.January.2017.13-23-42.File.Renaming.Crash.zip)

**Comment by Brian1Gaff** [comment] 2017-01-21 09:55
Funnily enough, this sort of crash can sometimes be explorer crashing and 
pushing out a page nvda seems not to read and of course with no explorer you 
cannot get at the desktop either.Sometimes you can get at task manager 
though.
 It happens sometimes when creating a folder as well as renaming things. I 
do not know if its nvda assisted or not. Windows 7 and up.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by derekriemer** [comment] 2017-01-22 04:34
When I try to attach this to a debugger, I get an error, and visual studio claims this is an older style crash dump.

**Comment by jcsteh** [comment] 2017-01-23 00:43
According to the Python stack, this seems to be crashing when we try to call UiaHasServerSideProvider while walking parents in setFocusObject. Strangely, it's not crashing anywhere in UIAutomationCore or ctypes, though:

> ```
> 0:000> kp 500
>  # ChildEBP RetAddr  
> WARNING: Frame IP not in any known module. Following frames may be wrong.
> 00 0018d858 0462d828 0x9
> 01 0018d87c 743f0444 0x462d828
> 02 0018d8a4 743ee19f python27!call_function(struct _object *** pp_stack = 0x0018d900, int oparg = 0n4451696)+0x334 [c:\build27\cpython\python\ceval.c @ 4372]
> 03 0018d91c 743f0521 python27!PyEval_EvalFrameEx(struct _frame * f = 0x0462b498, int throwflag = 0n0)+0x23cf [c:\build27\cpython\python\ceval.c @ 2990]
> 04 0018d93c 743f0432 python27!fast_function(struct _object * func = 0x00000000, struct _object *** pp_stack = 0x0018d9c8, int n = 0n4451696, int na = 0n2, int nk = 0n0)+0x91 [c:\build27\cpython\python\ceval.c @ 4436]
> 05 0018d96c 743ee19f python27!call_function(struct _object *** pp_stack = 0x0018d9c8, int oparg = 0n4451696)+0x322 [c:\build27\cpython\python\ceval.c @ 4370]
> 06 0018d9e4 743f0521 python27!PyEval_EvalFrameEx(struct _frame * f = 0x047cdcd8, int throwflag = 0n0)+0x23cf [c:\build27\cpython\python\ceval.c @ 2990]
> 07 0018da04 743f0432 python27!fast_function(struct _object * func = 0x00000000, struct _object *** pp_stack = 0x0018da90, int n = 0n4451696, int na = 0n2, int nk = 0n0)+0x91 [c:\build27\cpython\python\ceval.c @ 4436]
> ...
> ```

It continues like this; nothing useful.

**Comment by michaelDCurran** [comment] 2017-02-16 00:08
Is this issue reproducible for you with NVDA 2017.1rc1 or other recent snapshot? I am unable to reproduce this on Windows 8.1 so far.

**Comment by bhavyashah** [comment] 2017-02-16 00:39
I will test for the presence and replication of this issue with NVDA
2017.1 RC 1. In case I am able to reproduce it, I will definitely
revert confirming so.
Thanks.

On 2/16/17, Michael Curran <notifications@github.com> wrote:
> Is this issue reproducible for you with NVDA 2017.1rc1 or other recent
> snapshot? I am unable to reproduce this on Windows 8.1 so far.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6772#issuecomment-280184669


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by feerrenrut** [comment] 2017-04-25 08:51
@bhavyashah did you manage to reproduce this with 2017.1 or a more recent snapshot?

**Comment by feerrenrut** [comment] 2017-06-20 07:22
@bhavyashah any update on this issue? Are we able to close it?

**Comment by bhavyashah** [comment] 2017-07-29 14:23
Apologies for not responding earlier, I missed the reminders by @feerrenrut .
There is no longer any crash with NVDA 2017.2 on the same system (but with latest Windows updates installed, I expect), but a very noticeable and consistent freeze once I press Enter to apply the renamed file name. I hope the following log snippet suffices (I renamed test.MP3 to hey.MP3, I think, in case that matters):
DEBUG - queueHandler.registerGeneratorObject (19:52:57):
Adding generator 30309
IO - speech.speak (19:52:57):
Speaking [LangChangeCommand ('en_GB'), u'selection removed']
DEBUG - queueHandler.pumpAll (19:52:57):
generator 30309 finished
IO - inputCore.InputManager.executeGesture (19:52:58):
Input: kb(laptop):o
IO - speech._speakSpellingGen (19:52:58):
Speaking character u'o'
DEBUG - queueHandler.registerGeneratorObject (19:52:58):
Adding generator 30310
DEBUG - queueHandler.pumpAll (19:52:58):
generator 30310 finished
IO - inputCore.InputManager.executeGesture (19:52:58):
Input: kb(laptop):enter
DEBUGWARNING - watchdog._watcher (19:52:58):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyo", line 391, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 362, in Notify
  File "queueHandler.pyo", line 83, in pumpAll
  File "queueHandler.pyo", line 50, in flushQueue
  File "scriptHandler.pyo", line 145, in _queueScriptCallback
  File "scriptHandler.pyo", line 187, in executeScript
  File "editableText.pyo", line 113, in script_caret_newLine
  File "editableText.pyo", line 62, in _hasCaretMoved
  File "api.pyo", line 267, in processPendingEvents
  File "IAccessibleHandler.pyo", line 888, in pumpAll
  File "IAccessibleHandler.pyo", line 655, in processFocusWinEvent
  File "IAccessibleHandler.pyo", line 522, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 299, in isUIAWindow
  File "_UIAHandler.pyo", line 293, in _isUIAWindowHelper
Please let me know if further testing or diagnostic information is necessary.

**Comment by Brian1Gaff** [comment] 2017-07-30 09:31
I have missed the forgoing, but I rename a lot with my windows 7 machine 
here, and since fixing the processor idling issues often mentioned, the 
delay went away completely when enter was pressed.
 Might not be relevant, don't know, I'm using latest master snap.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by feerrenrut** [comment] 2017-10-02 04:42
Looks like the crash dump was from 2016.4 and the issue has stopped occurring in 2017.2. In Feb of 2017 we introduced a change to the way wx assertions were handled  which was likely responsible for the initial freeze. I will close this issue. @bhavyashah if you are still experiencing the freeze could you raise a new issue and attach a full log please.

**Closed by feerrenrut** 2017-10-02 04:42 UTC
Labels: crash, p1

**Comment by Brian1Gaff** [comment] 2017-10-02 11:16
I can also confirm that the crash that occurred by creating a new folder 
from the keyboard has also gone away in the recent issues of nvda. It used 
to upset Explorer and itself randomly before.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----
