### ISSUE TITLE
Problem reading the last line of multi-line edit boxes

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#11098] opened 2020-05-03 14:38 UTC
### Steps to reproduce:
1. This can be duplicated with all multi-line edit boxes, but for an example please go to https://www.gsmarena.com/postreviewcomment.php3?idReview=2108
2. Locate the 3rd edit box on the page which is a multi-line edit box with the following label: "Your comment edit multi line".
3. We need at least two lines of text here, and the last or second line should be blank. So please type one or more words and then press enter to create a new blank line.
4. Simply press Up/Down to move around the lines.
### Actual behavior:
As the down arrow is pressed, NVDA erroneously echos the first character of the first line as it reaches the last blank line in multi-line edit boxes. In addition, as Enter is pressed to create a new line in multi-line edit boxes, NVDA erroneously echos the contents of the previous line.
### Expected behavior:
NVDA should say, blank, as the cursor reaches the last blank line in multi-line edit boxes. Moreover, NVDA should say something like, "new line", when Enter is pressed to create a new line in such edit boxes.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Alpha 20,097, but also duplicable with many older alphas.
#### Windows version:
Windows 10 Pro 64-Bit, version 2004
#### Name and version of other software in use when reproducing the issue:
Chrome 81 stable but also duplicable with Chrome 80
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Some of the older alphas up 2 a month or so.
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by amirsol81** [comment] 2020-05-03 14:39
The issues described above can also be duplicated with the Comment multi-line edit box on Github.

**Comment by Adriani90** [comment] 2020-05-03 15:06
Confirmed here, it is only occuring in Chromium browsers.
cc: @aleventhal

**Comment by Brian1Gaff** [comment] 2020-05-04 07:41
This strange effect has been going on for some time, however does it 
actually miss reading a line at all, for me it tends to repeat the last line 
as if its in a buffer somewhere.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by Adriani90** [comment] 2020-05-20 21:33
This is working fine now in Chrome 83.

Closing as works for me.

**Closed by Adriani90** 2020-05-20 21:33 UTC
Labels: close/worksforme
