### ISSUE TITLE
Chrome: Omnibox: User is not notified of useful information in the first item of keyword search

### ISSUE THREAD

**Issue by cdkim1212** [nvaccess/nvda#13522] opened 2022-03-21 19:45 UTC
### Steps to reproduce:
1. Turn on NVDA and Chrome Browser
2. Activate keyword search by typing a letter that corresponds to a saved keyword search in the Omnibox

### Actual behavior:
As user types, they don’t hear any useful/friendly information that the sighted user sees in item 0, such as the title of the page they will get, or the fact that there are additional buttons

### Expected behavior:
The user should be notified of the title of the page and of the buttons one can tab to and activate as part of suggestions

#### Does the issue still occur after restarting your computer? 
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.3.3. Same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
N/A

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by feerrenrut** [comment] 2022-03-28 05:10
See also: #13145 
Related and likely to be addressed by an overhaul of user interactions with the omnibar.

**Comment by michaelDCurran** [comment] 2022-10-18 21:27
Examples would be very much appreciated here.
Most likely Chromium is not firing further selection events as the top 
suggestion changes. but I shall look into this.
Certainly it does correctly fire selection changes when arrowing up and 
down the suggestions or when tabbing onto the inner suggestion controls.

**Comment by nidza07** [comment] 2022-10-18 22:49
Hello,
I can confirm what @amirsol81 says, here is an example:
Open Chrome and make sure you are in the omnibox.
The next steps will depend on suggestions Chrome is giving to you, but here are mine:
Type G.
NVDA gives the following suggestion:
GitHub github.com location from history, press Tab then Enter to Remove Suggestion.  1 of 8.
Type o.
The next behaviour appears to be inconsistent and random, but one of the following might happen:
1. NVDA will report just "o unselected", completely useless and  meaningless. The selected suggestion is google.com, but NVDA gives no indication about this. If I continue writing the suggestion, i.e. type another O, NVDA again reports "o unselected", and this continues as long as there is a suggestion being offered.
2. NVDA will report "ogle.com" selected instead, because the selection has indeed changed and the next suggestion being offered is now google.com. Note that this is a little more useful, but it's not always the case, and still the entire suggestion isn't being reported, neither the page title nor where it comes from.

I have also noticed that the suggestion is always spoken correctly if you switch tabs, i.e. type g, suggestion is spoken. Go to a different tab, come back to the previous one, type O, the new suggestion is properly spoken. However, obviously this is inpractical, but it may help when debugging.

Let me know if any logs are needed, this is observed in my case under Chrome 106.0.5249.119.

**Comment by amirsol81** [comment] 2022-10-19 22:12
@michaelDCurran The examples @nidza07 provides are quite helpful, so I won't add extra examples.

**Comment by michaelDCurran** [comment] 2022-10-19 23:55
pr #14222 partially fixes this issue, as NVDA now announces the top suggestion when it first appears, and arrowing up and down the list / tabbing to the inner controls all read.
However, if continuing to type into the field causes the top suggestion to change, NVDA does not announce anything for this.
This is a limitation in the browser, as Chromium fails to fire further EVENT_OBJECT_SELECTION or nameChange events on the top suggestion. Thus NVDA has no good way of telling that the top suggestion has changed. NVDA could keep checking on typed input or on the valuechange event on the edit field, but this would be flaky at best as the list may update slower. It also deceives the whole point of the controllerFor selection event pattern.
this must be reported to Google.

**Comment by amirsol81** [comment] 2022-10-20 07:14
@michaelDCurran Thanks for the explanation. As I don't have any Google contacts, would it be possible for you or NVAccess to report this to Google? If fixed, this would make Omnibox a whole lot more accessible.

**Comment by michaelDCurran** [comment] 2022-10-20 13:15
I have reported this to the Google accessibility team. Will update the 
issue with a Chrome bug if/when created.

**Comment by amirsol81** [comment] 2022-10-20 16:31
@michaelDCurran Interestingly, this is handled much more elegantly with MS Edge 106. That is, NVDA reads the newly highlighted suggestions or page titles as we keep typing letters into the Omnibox although suggestions are read with a short delay of 1 or 2 seconds. Perhaps suggestions pop up with such a delay - I'm not sure. At any event, it seems that this is more of a Google Chrome-specific issue rather than an MS Edge-oriented one.

**Comment by michaelDCurran** [comment] 2022-10-20 21:07
I think MS Edge fires focus events on each suggestion, rather than 
selection events in conjunction with the controllerFor property.

**Comment by Adriani90** [comment] 2023-04-14 07:37
Filled Chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1433204

**Comment by Adriani90** [comment] 2024-05-07 17:50
In Chrome 124 with NVDA 2024.1, NVDA reports the title of the page, the URL and the fact that you can press tab to remove the suggestion. This works when the suggestion is already part of your browsing history.As Chrome developers explained, it would be anyway too much verbosity to get all the suggestion related info while typing, you can navigate to the list of suggestions with the tab key and access the information. I am closing this as works for me.
If you are still having any strong arguments why NVDA should still report as much information as possible while typing, please comment and we can rediscuss.

**Closed by Adriani90** 2024-05-07 17:50 UTC
Labels: close/worksforme, blocked/needs-external-fix, app/chrome, triaged

**Comment by amirsol81** [comment] 2026-06-25 06:38
@Adriani90 @seanbudd @michaelDCurran I suggest re-opening this as the auto-complete option/ readout works only for the first item with the latest NVDA alpha, the latest, NVDA official release, and Chrome 148/ 149.
In short, NVDA can't read the auto-complete suggestions in the address bar in Google Chrome. If you type one letter, it reads the first suggestion. But when you type a second letter o
