### ISSUE TITLE
Windows 10/UIA: After running NVDA for a while, NVDA does not pick up UIA selection events

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#5589] opened 2015-12-06 05:30 UTC
Hi,
I don't know if it is specific to Windows 10 Version 1511 or not, but after using NVDA for a while, NVDA seems to not understand UIA selection events when it fires.

STR:
1. Start using NVDA and perform actions such as searching for something from Start menu or toggling something from Settings app.
2. Repeat this after a few minutes.
Expected: NVDA catches UIA selection events in places such as Start search box.
Actual: NvDA does not detect this event after a while. This was observed with NvDA running with or without add-ons loaded.

Setup:
* NVDA version: next.12878.
* OS version: Windows 10 Version 1511 (build 10586)

Additiona information:
* Issue occurrence: every time NVDA is run.
* Easy to reproduce: no, haven't figured out which action or event causes NVDA to stop acknowledging UIA selection events.
* Are other UIA events affected: Haven't tested it deeply yet to see if other UIA events are affected.
* Other branches/versions affected: possibly 2015.4/master.

Thanks.

**Comment by jcsteh** [comment] 2015-12-06 11:04
Duplicate of #5470. I wouldn't classify this as a UIA performance issue, btw; we use that label for speed/efficiency issues.

It's worth noting that I suspect this only affects UIA selection events from the Start Menu, not from everywhere else, though I haven't verified this. Also, I think we may be dealing with a bug in Windows UIA core, as terminating and reinitialising UIA does not fix this problem.

**Closed by jcsteh** 2015-12-06 11:04 UTC
Labels: duplicate
