### ISSUE TITLE
NVDA announces table headers that it shouldn't

### ISSUE THREAD

**Issue by warriotox** [nvaccess/nvda#14373] opened 2022-11-14 16:20 UTC
I was testing the w3 org example on complex tables and observed very strange behavior with NVDA where it would announce table headers which were not relevant to where I was located in the table. For example when moving to the second column of the Rome section NVDA would also announce Paris for some reason. 

Issue is I am not sure if the problem lies with NVDA or with how the example is coded as I am only learning about how to make accessible tables.

See the attached screenshot for a bit more context. 

### Steps to reproduce:
1. Open Edge
2. Browse to [https://www.w3.org/WAI/tutorials/tables/multi-level/](https://www.w3.org/WAI/tutorials/tables/multi-level/)
3. Press T twice to navigate to the second table
4. Press arrow down once to enter the table context on 1st row
5. Press ctrl+alt+arrow down to get to the 2nd table row
6. Press ctrl+alt+arrow down to get to the 3rd table row
7. Press ctrl+alt+arrow down to get to the 4th table row
8. Press ctrl+alt+arrow down to get to the 5th table row
9. Press ctrl+alt+arrow down to get to the 6th table row
10. Press ctrl+alt+arrow down to get to the 7th table row
11. Press ctrl+alt+arrow down to get to the 8th table row
12. Press ctrl+alt+arrow down to get to the 9th table row 
13. Press ctrl+alt+arrow right to get to the second column of 9th row

### Actual behavior:
On step #4 NVDA announces "row 1 Paris **Rome** column 1"
On step #5 NVDA announces "row 2 **Rome** column 1 through 5 Paris"
On step #6 NVDA announces "row 3 Paris **Rome** column 1 1 bedroom"
On step #9 NVDA announces "row 6 **Paris** column 1 through 5 Rome"
On step #10 NVDA announces "row 7 **Paris** Rome column 1 1 bedroom"
On step #13 NVDA announces "Studio **Paris** Rome column 2 -"

### Expected behavior:
On step #4 NVDA announces "blank" ?? I am actually not sure what the correct behavior should be here. But seems strange to get "Paris and Rome" since the cell is blank...
On step #5 NVDA announces "row 2 Paris column 1 through 5"
On step #6 NVDA announces "row 3 Paris column 1 1 bedroom"
On step #9 NVDA announces "row 6 Rome column 1 through 5"
On step #10 NVDA announces "row 7 Rome column 1 1 bedroom"
On step #13 NVDA announces "Studio Rome column 2 -"

#### NVDA installed/portable/running from source: 
installed

#### NVDA version: 
2022.3.1

#### Windows version: 
Windows 11 Pro 2022H2

#### Name and version of other software in use when reproducing the issue: 
Version 107.0.1418.42 (Official build) (64-bit)

![ApplicationFrameHost_WifXeox7J9](https://user-images.githubusercontent.com/5864114/201711007-6a796861-de5c-401d-9b5c-649fdc24ed37.png)

**Comment by Adriani90** [comment] 2023-04-20 14:08
This is probably related or even a duplicate of #12482.

**Comment by Adriani90** [comment] 2024-10-13 15:38
Closing as duplicate of #6890.

**Closed by Adriani90** 2024-10-13 15:38 UTC
Labels: app/chrome, app/edge/anaheim, blocked/needs-technical-investigation, needs-triage
