### ISSUE TITLE
The Find a text function should start searching from the beginning when the string cannot be found AFTER CURRENT CURSOR POSITION.

### ISSUE THREAD

**Issue by rober555x** [nvaccess/nvda#7891] opened 2018-01-03 14:01 UTC
### Steps to reproduce:
1. Open Firefox
2. Browse to www.google.com
3. Place the cursor by the search field and make sure that browse mode remains active.
4. Press NVDA command control +Shift +F.
5. In the Find Text dialogue that appears type "mail" without the quotes and press Enter.

### Expected behavior:
NVDA should notify the user that the string was not located and start the search from the top of the page.  That notification can be given in the form of a spoken message such as "starting from top".  
### Actual behavior:
An error message is displayed indicating that the string was not found.  I believe the way it works now is the intended behavior for this feature, but in my opinion it may affect productivity an even create some confusion for many users.
### System configuration:
NVDA version:  2017.4

NVDA Installed or portable: Installed

Windows version:
Windows 10 Version 1709 Build 16299.125

**Comment by ehollig** [comment] 2018-01-04 02:41
Duplicate of #4637 

This is actually something I may be interested in investigating at some point.

**Closed by ehollig** 2018-01-04 02:41 UTC

**Comment by Brian1Gaff** [comment] 2018-01-04 10:18
Many apps, such as search in emails etc search from current too end then 
give the option do you want to start again from the top or start of the 
page text or whatever. This would be my favoured way this should work.
 Brian

**Comment by rober555x** [comment] 2018-01-04 12:59
I would think that most of the time our user would answer yes to that question and that is why I suggest to just perform the search and notify the user that it has started from top. The question of whether to start the search from top would just slow down the user in most cases. It can also become a configurable setting presented as a checkbox in the Find text dialogue.

 

Roberto.
