### ISSUE TITLE
NVDA gives extraneous table layout information in Outlook, making the message too verbose

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#11022] opened 2020-04-17 10:59 UTC
### Is your feature request related to a problem? Please describe.
Yes. In Microsoft Outlook, for complex HTML Email messages, NVDA will say something like "table with x columns and y rows, table with x columns and y rows, ..., [content]". This makes the Email message difficult to consume. Most of the time I'd argue it's impossible to consume because I have to wade through all the tables, and to add to that NVDA won't even focus properly on a link (for instance, if all I'm looking for is an "unsubscribe" link so I use TAB.) I can't even get to the link in many cases simply because of extraneous information.

### Describe the solution you'd like
NVDA should recognize layout tables in Outlook accurately and ignore them.

For example, JAWS does a great job at getting straight to the content and doesn't give any table information for the same Email message.

I do have "Include layout tables" off in Browse Mode Settings.

### Describe alternatives you've considered
Right now, I take the contents of the Email message and paste it into Notepad so I get the text only. This makes the message easier to read.

### Additional context
This happens with Browse Mode either on or off in Outlook.

**Comment by Adriani90** [comment] 2020-04-17 11:54
Closing as duplicate of #9541.

**Closed by Adriani90** 2020-04-17 11:54 UTC
Labels: close/duplicate
