### ISSUE TITLE
While navigating through the video in NVDA screenreader, once we enter the Full screen mode and if we Press Enter key again, focus is moving out from full screen button.

### ISSUE THREAD

**Issue by AmirShareef** [nvaccess/nvda#9580] opened 2019-05-17 06:26 UTC
User Experience: Users who rely on screen readers will be affected if While navigating through the video, once we enter the Full screen mode and if we Press Enter key, Focus is moving on to the top of the page.

Test Environment:
OS: Windows 10
Browser: Chrome

URL: https://www.microsoft.com/en-th/surface/devices/surface-laptop-2?activetab=surface_laptop_2_pivot:primaryr3

Screen readers: NVDA

**Repro Steps:**

Step 1: Open the above URL using Chrome browser.

Step 2: Navigate to the section video player section above heading "Power your passions".

Step 3: Press Enter key on the “Play Button” and navigate through the video and verify if the While navigating through the video, once we enter the Full screen mode and if we Press Enter key, Focus is moving on to the top of the page or not.

**Actual:**

While navigating through the video, once we enter the Full screen mode and if we Press Enter key, 

1. on first iteration, exit full screen is not working on hitting enter, even SR is not narrating anything

2. When user goes back to play icon and navigate to exit full screen button and hit enter then user come out of full screen but Focus is moves on to the top of the page.

**Expected:**

While navigating through the video, once we enter the Full screen mode and if we Press Enter key, Focus should not move on to the top of the page.

Traverse the below site for reference,
https://ableplayer.github.io/ableplayer/demos/video1.html

**Comment by DrSooom** [comment] 2019-05-17 16:57
@AmirShareef: Please specify the Windows 10, the NVDA and the Google Chrome version. Thanks.

**Comment by Adriani90** [comment] 2019-05-18 07:35
I can reproduce this issue in NVDA 2019.1.1 and Chrome 74. In Chrome, after pressing the full screen button, NVDA says "notification:press escape to exit the full screen. The site displays the media player in a separate dialog, similar to a modal dialog. If you press enter on exit full screen, the cursor jumps to the top of the page.
It seems related to azure media player. I tested in other media players and the cursor is not jumping.
cc: @michaelDCurran

**Comment by Adriani90** [comment] 2019-05-18 07:40
The cursor is also jumping when websites use media players which display the controls in a dialog after pressing full screen. See for example also a website with BRIGHTCOVE PLAYER like this one:
https://www.brightcove.com/de/player
The cursor is not jumpic right at the top of the page but directly above the the media controls.
cc: @mltony, @leonardder

**Comment by AmirShareef** [comment] 2019-05-20 05:34
Windows 10:  version 1809 , OS build 17134.765
NVDA: 2017.4
Chrome Version 74.0.3729.157 (Official Build) (64-bit)

**Comment by Adriani90** [comment] 2023-03-22 22:28
@AmirShareef do you have another test case for this issue? Can you still reproduce it with NVDA 2023.1 RC1 and Chrome 111?
The link in the issue description does not lead to a video anymore.

**Comment by JohnBernardsson** [comment] 2023-04-24 13:55
@Adriani90 this is easily reproducible with any Youtube video. Enter full screen mode, and then either pressing "Esc" key or navigating to the Full Screen toggle button and pressing Enter, focus will move to the top of the page.

Not sure if this is a NVDA issue or a browser behavior though... Just mentioning it here because was found out by our team in an Accessibility check.

**Comment by Adriani90** [comment] 2024-05-25 08:54
Ok I can reproduce this, it seems this is an issue with the Youtube. They redirect the focus to another area out of the video frame, but the focus should rather be redirected to the button on which you press enter or escape. Thiss needs to be reported to Google.

**Comment by Adriani90** [comment] 2024-05-25 13:33
I am closing as can't fix because it is totally related to youtube and their web authoring.

**Closed by Adriani90** 2024-05-25 13:33 UTC
Labels: close/cantfix
