### ISSUE TITLE
A bug report about braille scrrolling with NVDA and office word 2016

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#7202] opened 2017-05-24 06:16 UTC
Hello, I’m Hyongsp Kim in Korea. 
Today, I want to report one bug about reading braille in NVDA with office word 2016. 
In office word, I open another document or type some lines and read with my braille display, scroll panning has one problem.
Every time changing line, there is some delay.
Once I panned, if it is in same line, my braille display scrolling is very smooth.
But once I press panning button, if line is changed, scrolling time is a little more delayed.
It is tested without browse mode.
Please check this issue.

Thank you.

**Comment by stickbear2015** [comment] 2017-05-24 06:22
Can you provide more details? Windows operating system, version of NVDA, 
braille display in use? The more details you can provide the more likely 
myself or another community member can reproduce the issue and determine 
weather it's system or hardware specific, a bug in NVDA's braille 
support, or some other bug.
Thanks.
Shane

**Comment by khsbory** [comment] 2017-05-24 06:31
Of course.
My os is Windows 10.
My NVDA version is next snapshot, most newest.
My braille display is Hims BrailleSenseU2.
If you need more, please let me know.


Thank you.





김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark





-----Original Message-----

**Comment by stickbear2015** [comment] 2017-05-24 06:38
Can you reproduce this with the official stable release, 2017.1 or the 
RC release, 2017.2?
If this seems to be an issue that's cropped up in just the latest next 
snapshot, we'll have to determine what's changed between the version 
where it worked properly and the current next snapshot.
Thanks.
Shane

**Comment by khsbory** [comment] 2017-05-25 01:44
Hello, as you said, I tested with NVDA 2017.1.
But the problem is same.
But in other word program, such as notepad, there is no problem.


Thank you.





김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark





-----Original Message-----

**Comment by dkager** [comment] 2017-05-27 10:17
Looks like a duplicate of #4995.

**Comment by feerrenrut** [comment] 2017-05-29 06:09
Thanks @dkager, yes this issue seems to be a duplicate.

**Closed by feerrenrut** 2017-05-29 06:09 UTC
