### ISSUE TITLE
Odd behaviour in Firefox

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10790] opened 2020-02-16 17:22 UTC
Win10 / Version: 2019.2.1 / portable

Hello. I have no idea if this is a bug or entirely expected behaviour, and am hoping someone can shed some light.

Yesterday Windows10 updated itself from the late 2018 build to the late 2019 build.

I was looking through the Narrator settings to see what's new and saw a link for adding new voices.

This took me to a "Speech" category in the settings app, which had its own dropdown box for selecting a voice, and a link to install new voice packs.

I installed the US English pack, tried out some of the new voices before deciding I preferred George, and so I set the voice dropdown boxes in both the speech and Narrator categories, back to George.

Note at this point I had not changed any NVDA settings from what they were before the update and US voicepack install.

So here's the problem. I launched NVDA and Firefox and noticed that while it was mainly speaking in its normal George voice, with some menus and buttons it was speaking with one of the new American male voices. Whether hovering over the element, or tabbing to it. Previously it had always read that element on that website as George.

I decided I did not like that and thought it must be some quirk of the new voicepack install . So I went back to Speech settings in the settings app and uninstalled the new American pack.

But now NVDA remains silent when I try to read the elements that it was previously using the new US voice for.

Obviously that was a bit disconcerting., Fortunately I found a fix. For the first time I opened the NVDA settings and spotted an option for "Automatic language switching (when supported)". This had always been onm, nbut I turned it off and so far things seem to be back to normal. NVDA is now back to reading out those certain elements, and in the same George voice it uses for everything else.

So, is this a bug or entirely expected given what I have described?

Why would NVDA pick a random voice from a new pack to read out certain elements on a webpage, such as certain menus and buttons, but not others?

Why would it remain silent on certain elements when that pack is not there anymore, when it was using the George bvoice to read those buttons etc, before I installed it (even with auto-language switching enabled)?

Or is this indicative of me having caused some sort of corruption with my act of installing a new voicepack and then removing it?

Finally, am I likely to lose anything by leaving Automatic language switching disabled? Maybe there are some things that won't get read at all if it is OFF?

Sorry for the length! Thanks.

**Comment by josephsl** [comment] 2020-02-16 17:26
Hi, this is expected behavior – the setting you have discovered is powered by the language for documents and elements set by document author. For example, if an element is coded as United States English, an American English voice would read this option; if on the other hand if parts of a document is exposed as written in another language, a voice from that language would come up. Thanks.

**Comment by TechHorseG** [comment] 2020-02-16 18:41
Thanks. But is it expected for NVDA to remain silent at such an element if its language pack is not installed?

To reiterate, NVDA always used to read those elements before. It stopped doing so when I installed and then subsequently uninstalled the US voice pack? Surely that is not normal?

**Comment by josephsl** [comment] 2020-02-16 19:10
Hi, at least it is a limitation of language detection code. If this happens with Espeak NG, then yes, it is something we do need to look at (I think there is another issue that addresses this). Thanks.

**Comment by Brian1Gaff** [comment] 2020-02-16 20:21
Presumably though would you not expect if no us voice was present, it would 
have to use the George voice. It sounds like Microsoft are not putting the 
registry back properly after the uninstall to me.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by TechHorseG** [comment] 2020-02-17 03:03
Ah, so looks like there is a bug in the voice pack uninstall process.

If I could ask one last technical question. If NVDA can read out an element in the following circumstances:
only UK voice  pack is installed
using UK George 
auto-language switching is enabled

Then is there any technical reason why it could not read out that same element when auto-language switching is disabled, but the other two remain the same?

As mentioned before, disabling this option seems to be getting me back to hearing all the things I used to hear on my most frequently-visited websites, but want to make sure I am not now potentially going to be missing out on things I would otherwise have heard read out when I was in the first set of circumstances?

Thanks.

**Comment by josephsl** [comment] 2020-02-17 04:19
Hi, as for that, I don’t know. @JCSTeh and Marco, any thoughts? Thanks.

**Comment by jcsteh** [comment] 2020-02-17 05:03
This does seem like a bug in the voice pack uninstall process. I think that's worth reporting as feedback to Microsoft.

With language switching disabled and only one language installed, you shouldn't miss out on any information as compared with having language switching enabled. If you had more than one language installed, though, it gets more complicated because one voice might not be able to speak words from the other language at all.

**Comment by Brian1Gaff** [comment] 2020-02-17 07:23
But in many ways, uk English is a subset of US English, and has been as far 
back as XP, from what I recall. If somebody knew what the default reg 
entries were that were modified by the language pack one might be able to 
merge them back into the registry, assuming that is where the issue lies of 
course.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users

**Comment by TechHorseG** [comment] 2020-02-17 22:15
"With language switching disabled and only one language installed, you shouldn't miss out on any information as compared with having language switching enabled."

That's a relief! Managed this far with only having UK voice pack installed so I'll just keep auto-switching off and not worry. Thanks for all responses.

**Comment by Adriani90** [comment] 2020-05-17 11:39
@TechHorseG  This seems specific for voice language for a synthesizer and is a bug which should be fixed by Microsoft. If you like, you can post a link for the bug with Microsoft to this issue so that we can keep track on that. Did you report it already to Microsoft?

**Comment by Adriani90** [comment] 2020-05-30 00:48
I am closing this for now since it is not something that can be solved in NVDA. If you have a link to the bug reported to Microsoft, please post it here and we can reopen and track that bug here also.

**Closed by Adriani90** 2020-05-30 00:48 UTC
