### ISSUE TITLE
unable to read word or character in chrome menus

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#14088] opened 2022-08-30 20:47 UTC
### Steps to reproduce:
using notebook keyboard layout:
open chrome
if it is not in the document you can press f6 until it is in the document
press alt to open the menu bar
scroll a few times with the arrow below to focus on a menu item as an example:
new tab
now try reading character by character with nvda + ctrl + right and left arrows, or try reading line by line with nvda + up or down arrow
### Actual behavior:
nvda announces
in blank
I copied below as I understood that the model asks for the speech viewer snippet from when I pressed alt, down arrow to a menu item and when I tried the commands
nvda + up and down arrow, and nvda + ctrl + right and left arrow.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
in blank
Background
in blank
Background
in blank
Top
in blank

### Expected behavior:
i would like it to be possible to read the name of the option in focus i.e. read the name of the entire line when pressing nvda + arrow like this or below,
pressing nvda + right arrow or nvda + left arrow will be able to spell the current item in focus, as well as pressing
nvda + ctrl + left or right arrow read the menu item in focus word by word.
I tried to do this in word and it worked the way I expected,
I opened word, and when I was in a blank document I pressed alt, left arrow to be in the file menu, down arrow to be in a menu item and repeated the commands already informed like this
nvda + right and left arrow it was possible to read the focused item character by character.
nvda + ctrl + left and right arrows where it was possible to read the item in focus word by word.
nvda + arrow like or below where it was possible to read the nenu item in focus.
I would like this experience obtained in word also in chrome
I've tried naming the speech from the speech viewer below to tell me what I want to hear.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
New Tab Ctrl+T g 1 of 19
Background
New Tab Ctrl+T g 1 of 19
Top
N
Background
O
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda.exe, NVDA alpha-26412,28b47560

#### Windows version:
windows 10 19044.1806
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 104.0.5112.102

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by seanbudd** [comment] 2022-08-31 03:30
We are unable to process this issue as it stands.

- Please fill out the issue template fully. We need to know which versions of Chrome and NVDA you have reproduced this on,
- please provide an example website

Kind Regards,
NV Access Software Developers

**Comment by fernando-jose-silva** [comment] 2022-08-31 09:48
### Actual behavior:
<!--
Use "nvda announces
in blank
I copied below as I understood that the model asks for the speech viewer snippet from when I pressed alt, down arrow to a menu item and when I tried the commands
nvda + up and down arrow, and nvda + ctrl + right and left arrow.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
in blank
Background
in blank
Background
in blank
Top
in blank

### Expected behavior:
i would like it to be possible to read the name of the option in focus i.e. read the name of the entire line when pressing nvda + arrow like this or below,
pressing nvda + right arrow or nvda + left arrow will be able to spell the current item in focus, as well as pressing
nvda + ctrl + left or right arrow read the menu item in focus word by word.
I tried to do this in word and it worked the way I expected,
I opened word, and when I was in a blank document I pressed alt, left arrow to be in the file menu, down arrow to be in a menu item and repeated the commands already informed like this
nvda + right and left arrow it was possible to read the focused item character by character.
nvda + ctrl + left and right arrows where it was possible to read the item in focus word by word.
nvda + arrow like or below where it was possible to read the nenu item in focus.
I would like this experience obtained in word also in chrome
I've tried naming the speech from the speech viewer below to tell me what I want to hear.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
New Tab Ctrl+T g 1 of 19
Background
New Tab Ctrl+T g 1 of 19
Top
N
Background
O
### NVDA logs, crash dumps and other attachments:

### System configuration
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda.exe, NVDA alpha-26412,28b47560

#### Windows version:
windows 10 19044.1806
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 104.0.5112.102

#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by fernando-jose-silva** [comment] 2022-08-31 09:53
### Steps to reproduce:
using notebook keyboard layout:
open chrome
if it is not in the document you can press f6 until it is in the document
press alt to open the menu bar
scroll a few times with the arrow below to focus on a menu item as an example:
new tab
now try reading character by character with nvda + ctrl + right and left arrows, or try reading line by line with nvda + up or down arrow
### Actual behavior:
nvda announces
in blank
I copied below as I understood that the model asks for the speech viewer snippet from when I pressed alt, down arrow to a menu item and when I tried the commands
nvda + up and down arrow, and nvda + ctrl + right and left arrow.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
in blank
Background
in blank
Background
in blank
Top
in blank

### Expected behavior:
i would like it to be possible to read the name of the option in focus i.e. read the name of the entire line when pressing nvda + arrow like this or below,
pressing nvda + right arrow or nvda + left arrow will be able to spell the current item in focus, as well as pressing
nvda + ctrl + left or right arrow read the menu item in focus word by word.
I tried to do this in word and it worked the way I expected,
I opened word, and when I was in a blank document I pressed alt, left arrow to be in the file menu, down arrow to be in a menu item and repeated the commands already informed like this
nvda + right and left arrow it was possible to read the focused item character by character.
nvda + ctrl + left and right arrows where it was possible to read the item in focus word by word.
nvda + arrow like or below where it was possible to read the nenu item in focus.
I would like this experience obtained in word also in chrome
I've tried naming the speech from the speech viewer below to tell me what I want to hear.

toolbar
Chrome Menu Button SubMenu Customize and Control Google Chrome
submenu selected menu
Use the up and down arrows to move through the pop-up menu options.
New Tab Ctrl+T g 1 of 19
Use arrow keys to move between menu items.
Top
New Tab Ctrl+T g 1 of 19
Background
New Tab Ctrl+T g 1 of 19
Top
N
Background
O
### NVDA logs, crash dumps and other attachments:

### System configuration
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
nvda.exe, NVDA alpha-26412,28b47560

#### Windows version:
windows 10 19044.1806
#### Name and version of other software in use when reproducing the issue:
chrome.exe, Google Chrome 104.0.5112.102

#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by fernando-jose-silva** [comment] 2022-08-31 10:00
the information was present from the beginning.
 Any error in the git hub interpretation please edit the first comment, and you will see that all text is present.  anyway, i edited the line that seemed to have the problem, not knowing what i was doing, and the problem was solved.
 Please reopen the issue.

**Comment by LeonarddeR** [comment] 2024-03-12 18:19
I looked into this briefly. It looks like in these cases the objects expose an IAccessibleText object with only object replacement characters (0xFFFC). That's why text review doesn't report anything reasonable.
I'm not sure what's the best way to fix this. I think looking up all the text and find out whether it consists only of replacement characters is a bit expensive.

**Comment by lukaszgo1** [comment] 2024-03-12 18:27
Isn't this a duplicate of #15159? From the discussion on that issue it looks like not falling back to what text info provides for non editable cases should be a reasonable solution.

**Comment by CyrilleB79** [comment] 2024-03-12 22:39
@lukaszgo1 wrote:

> Isn't this a duplicate of #15159? From the discussion on that issue it looks like not falling back to what text info provides for non editable cases should be a reasonable solution.

I am not sure to understand your comment. #15159 is about controls in the webpage whereas the current issue is about controls in the GUI of the browser itself. Are you saying that it may be caused by the same issue anyway?

**Comment by lukaszgo1** [comment] 2024-03-13 18:41
Yes, these controls use exactly the same implementation of text info i.e. `NVDAObjects.IAccessible.IA2TextTextInfo` which exposes their value as object replacement characters / empty string.

**Comment by Adriani90** [comment] 2024-12-08 15:02
Closing as duplicate of #13611.

**Closed by Adriani90** 2024-12-08 15:02 UTC
Labels: close/duplicate, needs-triage
