### ISSUE TITLE
Firefox: Unnecessary Text presented in Browse Mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5469] opened 2015-11-07 10:46 UTC
**Reported by elliott94 on 2015-11-07 10:46**
For several years, I've noticed that on some websites that the text "BESs" can sometimes be seen when reading the content of a web page in Browse Mode. Strangely, I haven't been able to figure out a pattern when this occurs; the text can only be seen for several seconds, at which point it disappears. An examination of the page source doesn't show this particular text either - that said, the text can be seen again if a simple reload of the page is performed.

**Comment by ehollig** [comment] 2017-07-11 18:19
Could you provide an example site where this text appears? Also, does this still happen with the latest version of Firefox?

**Comment by feerrenrut** [comment] 2017-07-12 06:39
Unfortunately there is no way for elliott94 to get the latest comment on this issue. This issue was created automatically during the migration from Trac to Github. I'm going to close this issue, since its quite old and I don't think anyone is able to reproduce it. If someone can reproduce it, please comment and add some more information about how to make it happen and we will be happy to investigate the issue further.

**Closed by feerrenrut** 2017-07-12 06:39 UTC
Labels: bug

**Comment by jcsteh** [comment] 2017-07-13 01:05
@elliott94, can you still reproduce this?

**Comment by elliott94** [comment] 2017-07-13 17:15
This isn't something that I've seen for a while now - happy for it to be closed unless anybody else disagrees.
