### ISSUE TITLE
NVDA's Python Console's input() Function Has an Error

### ISSUE THREAD

**Issue by malukus** [nvaccess/nvda#13412] opened 2022-03-01 23:08 UTC
### Steps to reproduce:
test = input("Please type in your name: ")

### Actual behavior:
Traceback (most recent call last):
  File "<console>", line 1, in <module>
RuntimeError: input(): lost sys.stdin

### Expected behavior:
User input being stored in the "test" variable.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.3.3

#### Windows version:
10

#### Name and version of other software in use when reproducing the issue:
Not Applicable

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment] 2022-03-09 03:26
Closing this as this is intended behaviour. Consider providing the input directly - there is no need to use input

**Closed by seanbudd** 2022-03-09 03:26 UTC

**Comment by feerrenrut** [comment] 2022-03-09 03:31
The python console in NVDA is really for testing / experimenting with code within an NVDA context. I.E. with access to the variables and data, modules, classes, functions that are available within NVDA.

It seems like you may be trying to follow a python tutorial, the python console the tutorial refers to will be a console outside of NVDA, search your start menu for python console or IDLE.

More information about why this doesn't work in NVDA:
The input command gets input via the standard input stream, this would work in a console application. NVDA is a GUI application, these streams are intentionally not available. So the short answer is the python console in NVDA can't / won't support input, and it doesn't really make sense for it to do so.
