### ISSUE TITLE
NVDA SayAll reads multiple lines repeatedly in web browsers

### ISSUE THREAD

**Issue by btman16** [nvaccess/nvda#11158] opened 2020-05-13 02:41 UTC
### Steps to reproduce:
1. Run the latest NVDA alpha snapshot.
2. Open for example the NVDA what's new.
3. Press NVDA's say all command to start reading.

### Actual behavior:
On my system NVDA starts out reading ok, reading each line as it should, but then after a few lines it begins to read part of the line then goes back to the start of the line. On the second time through it reads the line as you'd expect. The debug log should show more about this.
### Expected behavior:
NVDA only reads the line once.

#### NVDA installed/portable/running from source:
NVDA was running as a temporary copy.
#### NVDA version:
Latest alpha snapshot as of Wed May 13 02:14:23 2020
#### Windows version:
19H2 build 18363.778
#### Name and version of other software in use when reproducing the issue:
Internet Explorer, and Firefox both have the issue.
#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
All stable NVDA versions work ok.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.
[nvda.log](https://github.com/nvaccess/nvda/files/4619495/nvda.log)

**Comment by Adriani90** [comment] 2020-05-13 05:50
Closing as duplicate of #11132

**Closed by Adriani90** 2020-05-13 05:50 UTC
Labels: close/duplicate
