### ISSUE TITLE
Additional (sometimes garbage) information read out when in the To: field in Outlook

### ISSUE THREAD

**Issue by LMuk** [nvaccess/nvda#11278] opened 2020-06-19 07:55 UTC
### Steps to reproduce:
Start NVDA
Start Outlook
Reply to an email
Navigate to the "To:" field
### Actual behavior:
Because it is a reply the To field is already populated
It will read out:

- The contact
- The online status for the contact (online/away/busy/)
- additional information

The additional information will either be some crazy large number, or it will be some text that was previously read out (for example the subject line of another email)

### Expected behavior:
Once the online status is read out it would stop

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
NVDA version 2020.1
#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook for Microsoft 365 MSO (16.0.12827.20200) 32-bit

#### Does the issue still occur after restarting your computer?
This issue persists after applying latest Windows and Office updates. 
It persists after restarts.
It occurs for me and at least one colleague (with broadly the same configuration Windows/NVDA/Outlook)

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
n/a
#### If addons are disabled, is your problem still occuring?
There are no add-ons listed in the Add-on manager.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Issue still occurs after trying this.

#### Finally
I am not a regular or expert user of NVDA, please just let me know if there is any additional information I can gather to help reproduce this. I have tried to complete the template with everything I know

**Comment by Adriani90** [comment] 2020-06-21 19:22
This is a duplicate of issue #10254. Closing as duplicate.

**Closed by Adriani90** 2020-06-21 19:22 UTC
Labels: close/duplicate
