### ISSUE TITLE
problems working with tables in powerpoint 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12799] opened 2021-09-01 22:59 UTC
### Steps to reproduce:
open a presentation in powerpoint, and create a presentation with a table, in my case I created a table with 3 rows and 2 columns.
Walking with tabe between the cells, I filled in the table as follows:
row 1 column 1 type a1
row 1 column 2 type b1
row 2 column 1 type a2
row 2 column 2 type b2
row 3 column 1 type a3
row 3 column 2 type b3

now press ctrl + home, and try using the commands ctrl + alt + directional arrows, commands used in word.
these commands are not available in powerpoint, nvda is muted.
First request, make the same word experience available for the powerpoint where ctlr + alt + directional arrows navigate the table.
now being in the table, press ctrl + home, and press down arrows:
expected, nvda should read a2 and then on the next line a3
what happens is that nvda is always repeating the contents of the first cell row 1 column 1, or the contents of row 2 column 1.

another request, when navigating with the arrows like this or down through a column, nvda should announce the cell that gains focus, expected when walking with the arrows below:
a2, a3.

Now press esc, and tabe walk through the presentation, note that when there is a table nvda does not announce the existence of the table, announcing something like form content location, the user only knows that there is a table if they press enter.
expected, when walking with tabe through a presentation and listening to a table this should be announced to the user.
when tabbing a slide and there is another object such as an image, nvda does not announce either, only if the image has an alt text, even with the absence of alt text nvda should announce the existence of an image. 

Finally the last request, when reading a presentation in slideshow mode with f5, when finding a table nvda does not announce the existence of the table and it is also not possible to walk through the table using the commands ctrl + alt + directional arrows.
expected when reading a presentation in f5 slideshow mode, nvda should announce that there is a table and allow navigation with ctrl + alt + directional arrows. 

### Actual behavior:

it is not possible to use the table navigation commands ctrl + alt + directional arrows when reading a table in powerpoint when editing a table or when in slideshow mode.
nvda does not announce the cell in focus when walking with up and down arrows while editing a spreadsheet. 
when walking with tabe down a slide, nvda must announce the existence of a table in the field in focus. 
nor does it announce the existence of other objects such as figures without alt text. 
### Expected behavior:

it should be possible to use the ctrl + alt + directional arrows commands when navigating a table in powerpoint during editing and slideshow mode.
nvda should announce the focus cell when editing a table in powerpoint.
When walking with tabe on a slide nvda must announce that in the field to a table. 
including other objects such as images without text alt. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23661,c45f5f76

#### Windows version:
10.0.19044.1202
#### Name and version of other software in use when reproducing the issue:
POWERPNT.EXE, Microsoft Office 16.0.14326.20238

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Qchristensen** [comment] 2023-12-13 06:00
Testing this with the following setup:

NVDA 2023.3
 
Windows 11 (64-bit) Version: 22H2, Build: 22621.2792 
 
Office 365 (64-bit) Version: 16.0.17029.20028 

I found that in editing mode:
- Control+alt+arrows do not work as they do in say Word (as reported)
- up and down arrow do read the first cell in the column, as reported
- tab does move through the table left to right, top row to bottom row, as it does in other tables such as in Word.  This is how I would recommend navigating in the meantime.

When presenting (F5):
- control+alt+arrows do not work
- up and down arrows move by one cell at a time in the same order as tab does when editing
- tab does not navigate the table

**Comment by CyrilleB79** [comment] 2023-12-13 08:50
Duplicate of #5350.
Closing.

**Closed by CyrilleB79** 2023-12-13 08:50 UTC
