### ISSUE TITLE
NVDA loses its keyboard hook when the system is under high load

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#5629] opened 2015-12-22 21:54 UTC
I've been using a 2009 laptop for dev work because I'm a bit of a masochist and I figured that I should run my apps on similar hardware to my users.
This is a core 2 duo, running at around 2.4 GHz. Often times when I kick off a compile or some other processor-intensive activity, and then use NVDA keys to review the screen, the NVDA keys do not work at all, instead passing through directly to the OS. This results in my capslock key often getting toggled, and in loads of random typing. Once this happens, the keyboard hook never comes back and I must restart NVDA to use it.

Here's a typical experience I have, perhaps you will understand my frustration.

Open a website with some active Javascript that spikes the CPU. Note the system goes kind of unresponsive. Tap a keystroke like NVDA+f12 to get the time and measure screen reader latency. Have the already sluggish browser window open the devtools console and NVDA simply ignore the keystroke.

This is profoundly annoying and dramatically impacts my productivity.

**Comment by jcsteh** [comment] 2015-12-22 22:32
This is a duplicate of #2003. To cut a long story short, Windows kills keyboard hooks without any warning if they take longer than a certain (very short) period. I get the reason for this, but when a system is under load, pretty much everything takes a while, and the fact that we don't even get notified about this makes it very difficult to solve.

One question: what version of Windows is this? From reports we've seen, this seems to be far more likely on Windows 7 than any other OS, though we very rarely saw it ourselves even on Windows 7.

**Closed by jcsteh** 2015-12-22 22:32 UTC
Labels: duplicate

**Comment by ctoth** [comment] 2015-12-22 22:36
This is, in fact, windows 7.
How expensive would it be to periodically reinitialize the hook? Maybe 
have a benchmark task running on the main loop and if it takes longer 
than whatever rehook?

**Comment by jcsteh** [comment] 2015-12-22 22:49
> How expensive would it be to periodically reinitialize the hook?

I'm not happy about the idea of periodically rehooking without a condition, as one might miss a keystroke that way.

> Maybe 
> have a benchmark task running on the main loop and if it takes longer 
> than whatever rehook?

The keyboard hook actually runs in its own thread, largely to combat issues like this, but even that's apparently not enough. The problem is that any timer we use within the hook doesn't account for time spent in C land, including (I suppose) time waiting to acquire the Python GIL, etc. And unfortunately, we can't do this purely in C; we need to ask NVDA's Python bits whether the key should be eaten. I guess a hybrid approach could work: write the hook in C, do timing in the C hook and call the Python bit ourselves so we can measure it. However, the fact that we can't reproduce this (I saw it maybe a handful of times in the years i was running Windows 7) makes it difficult for us to road test the theory ourselves. Still, it's definitely worth investigating.

**Comment by ctoth** [comment] 2015-12-22 23:32
Can we not trust the output of time.clock() and simply do our own check to see if it's been too long since last recorded value? I.E. record at the beginning of keyhook, check at end, if too long reregister.

Alternatively I see from your comment on #2003 that if we try unregistering the hook after it's already been unhooked by Windows it raises an error. Does this also happen if you try to reregister the same hook?

**Comment by jcsteh** [comment] 2015-12-23 00:09
> Can we not trust the output of time.clock() and simply do our own check to see if it's been too long since last recorded value? I.E. record at the beginning of keyhook, check at end, if too long reregister.

No. As I said, the hook timeout will include any time spent in C land before and after Python actually calls our function. You can't assume that's instantaneous, particularly not with the GIL. In fact, I very much suspect the GIL is the cause of the delay here.

> Alternatively I see from your comment on #2003 that if we try unregistering the hook after it's already been unhooked by Windows it raises an error. Does this also happen if you try to reregister the same hook?

I'm actually not sure. Certainly, SetWindowsHookEx doesn't document that it will prevent installing the same callback twice. If it's undocumented, we'd at least have to restrict this to specific versions of Windows (service packs included) where it's been tested. Registering the same callback twice would have disastrous results.

**Comment by amandarush** [comment] 2015-12-23 00:49
Since this is a duplicate I can go leave this comment on the referenced issue thread as well, but definitely experiencing this. My primary dev machine is running Win7 as its OS, and I have seen the broken keyhook while doing JS-intensive stuff as well as with Outlook 2016. Running the latest NVDA stable release, and if necessary can test this on the Win8 box.

**Comment by amandarush** [comment] 2015-12-23 00:58
Machine specs: Core2 duo, 4G RAM, Win7 latest service pack.
