### ISSUE TITLE
Scratchpad in Firefox Developer Tools fails to act like a text editor

### ISSUE THREAD

**Issue by signalsender103** [nvaccess/nvda#7675] opened 2017-10-19 19:29 UTC
### Steps to reproduce:
1. Open Firefox Developer Edition.
2. Press Shift+F4.
3. Type some text.
4. Try using any of the navigation commands, or backspace or delete some characters.

### Expected behavior:
NVDA should read the characters as with other HTML controls.

### Actual behavior:
When deleting or navigating, NVDA says "blank."

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable: Installed

Other information:

Windows version: 8.1

Name and version of other software in use when reproducing the issue: Firefox Developer Edition

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No

**Comment by derekriemer** [comment] 2017-10-19 19:52
This must be a mozilla bug. @jcsteh do you want to file this?

**Comment by dnz3d4c** [comment] 2017-10-20 12:53
MozillaBug: 1088804https://bugzilla.mozilla.org/show_bug.cgi?id=1088804

**Comment by Adriani90** [comment] 2019-04-30 22:18
This seems solved in Firefox Nightly. @jcsteh should we close this one?

**Comment by jcsteh** [comment] 2019-04-30 22:51
This is a duplicate of #4471. And yes, a workaround landed in Firefox to deal with this; see https://github.com/nvaccess/nvda/issues/4471#issuecomment-483125697 for details.

**Closed by jcsteh** 2019-04-30 22:51 UTC
Labels: Firefox, needsExternalFix
