### ISSUE TITLE
Windows 10 stop responding when using NVDA

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5449] opened 2015-10-30 22:53 UTC
**Reported by DataTriny on 2015-10-30 22:53**
Hello,
I'm using Windows 10 and the latest version of NVDA.
The problem generally occures when opening or closing a window.
Then, it is impossible to close any program, nor opening the task manager or the command prompt to close NVDA.
The only way to resolve the problem is to log out.
If it is important, i'm using the Windows Magnifier and I use the mouse to navigate.
I can't tell more about this bug since it seems to occures randomly.
Thanks in advance for your work.

**Comment by ehollig** [comment] 2017-07-11 18:17
I am not able to replicate this bug. Could you provide an NVDA log with debug enabled that shows what may be happening? Also, which version of Windows 10 are you using?

**Comment by feerrenrut** [comment] 2017-07-12 06:42
Thanks @ehollig, the information you requested would indeed be useful. Unfortunately there is no way for DataTriny to get the latest comment on this issue. This issue was created automatically during the migration from Trac to Github. I'm going to close this issue, since its quite old and I don't think anyone is able to reproduce it. If someone can reproduce it, please comment and add some more information about how to make it happen and we will be happy to investigate the issue further.

**Closed by feerrenrut** 2017-07-12 06:42 UTC
Labels: bug
