### ISSUE TITLE
enable description of images in nvda

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7671] opened 2017-10-18 15:13 UTC
Using the narrator in windows 10 16299 there is a function of reading image descriptions by pressing capslook + shift + d.
Would it be possible to make this function available to nvda?
Thank you very much.

**Comment by josephsl** [comment] 2017-10-18 15:17
Hi, it’ll require that we find a way to work with Azure (perhaps through subscriptions or as part of an API). Also, I think this is a duplicate of another issue. Thanks.

**Comment by fernando-jose-silva** [comment] 2017-10-18 22:10
Thank you very much.

**Comment by Adriani90** [comment] 2019-04-30 22:37
cc: @larry801, @OliverEdholm in my opinion this feature should remain as an addon. What do you think? I don't think NV Access have the time and the ressources to maintain data bases and what not.

**Comment by Adriani90** [comment] 2024-04-24 21:37
Closing this in favor of #16281 which contains more valuable discussion.

**Closed by Adriani90** 2024-04-24 21:37 UTC
Labels: close/duplicate
