### ISSUE TITLE
Error reading message in outlook 2016

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#6632] opened 2016-12-09 11:46 UTC
Hello everyone.
I'm hearing a sound of errors while reading some messages in Outlook 2016 using the nvda next 13751.
The error occurs only in some messages.
Follow the log below.
Another note is that in a nvda build that was previously using rc 13741 it was not getting this error.
The office is 32bits running on windows 64bits 10.0.14393.
I'll also attach the Outlook message.

Speaking [u'Mensagem  documento  multilinha']
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:54):

[{cracolandia} dica de aquisição de máquina de passar cartão   qual é acessível .zip](https://github.com/nvaccess/nvda/files/642058/cracolandia.dica.de.aquisicao.de.maquina.de.passar.cartao.qual.e.acessivel.zip)
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:54):
Speaking [u'ola prezados,']
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:54):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:54):
Speaking [u'cursor Editar']
IO - inputCore.InputManager.executeGesture (09:16:55):
Input: kb(laptop):downArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:56):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:56):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (09:16:57):
Input: kb(laptop):upArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:57):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:57):
Speaking [u'ola prezados,']
IO - inputCore.InputManager.executeGesture (09:16:58):
Input: kb(laptop):downArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:58):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:58):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (09:16:59):
Input: kb(laptop):downArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:16:59):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:16:59):
Speaking [u'estou precisando comprar uma m\xe1quina de cart\xe3o de cr\xe9dito para uso no meu trabalho e pergunto algu\xe9m me d\xe1 dicas de como  se pode usar com autonomia e independ\xeancia  e se podemos acoplar ao celular e o ']
IO - inputCore.InputManager.executeGesture (09:17:07):
Input: kb(laptop):downArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:17:07):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:17:07):
Speaking [u'android.']
IO - inputCore.InputManager.executeGesture (09:17:09):
Input: kb(laptop):downArrow
ERROR - RPC process 5644 (OUTLOOK.EXE) (09:17:10):
Thread 8480, build\x86\remote\winword.cpp, detectAndGenerateColumnFormatXML, 870:
error getting textColumn count. res: -2146823683 count: -1

IO - speech.speak (09:17:10):
Speaking [u'em branco']
IO - inputCore.InputManager.executeGesture (09:17:15):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (09:17:15):
Developer info for navigator object:
name: u'Mensagem'
role: ROLE_DOCUMENT
states: STATE_MULTILINE, STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject object at 0x09E1D790>
Python class mro: (<class 'NVDAObjects.Dynamic_OutlookWordDocumentIAccessibleWordDocumentWindowNVDAObject'>, <class 'appModules.outlook.OutlookWordDocument'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.winword.WordDocument'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (8, 269, 1333, 450)
value: None
appModule: <'outlook' (appName u'outlook', process ID 5644) at address 528f2b0>
appModule.productName: u'Microsoft Outlook'
appModule.productVersion: u'16.0.6965.2105'
TextInfo: <class 'NVDAObjects.window.winword.WordDocumentTextInfo'>
windowHandle: 67696
windowClassName: u'_WwG'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 8480
windowText: u'Mensagem'
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x630700 at 5b47ad0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=67696, objectID=-4, childID=0
IAccessible accName: u'Mensagem'
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: None
IAccessible accValue: None

**Comment by josephsl** [comment] 2016-12-09 16:21
A regression due to section announcement in Word.

One thing to note is that this happens if reading plain text messages, not HTML.
Thanks.

**Comment by feerrenrut** [comment] 2017-01-16 08:16
Fixed in https://github.com/nvaccess/nvda/pull/6498 see commit d9d66076a839dbfc0a79a1a7e2c5e78bb614a07c

**Closed by feerrenrut** 2017-01-16 08:16 UTC
Labels: p1
