### ISSUE TITLE
an error with an unhandled exception on skype8 when doing ocr with built-in windows10 OCR support

### ISSUE THREAD

**Issue by kianoosh-shakeri** [nvaccess/nvda#9832] opened 2019-06-27 12:55 UTC
### Steps to reproduce:
open skype8, open a chat, when the chat is opened focus the browsmode on the chat's edit box and press insert+r
### Actual behavior:
gives an error before the virtual document appeers which the error is an unhandled exception:
ERROR - unhandled exception (17:15:21.562):
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "contentRecog\uwpOcr.pyo", line 97, in callback
  File "contentRecog\recogUi.pyo", line 162, in _recogOnResult
  File "NVDAObjects\__init__.pyo", line 138, in __call__
  File "appModules\skype.pyo", line 232, in event_NVDAObject_init
AttributeError: 'Dynamic_Skype8IAccessibleRecogResultNVDAObject' object has no attribute 'event_objectID'
### Expected behavior:
view the recognised text in a virtual document or if nothing can be recognised, say no content available
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2019.2 Beta2
#### Windows version:
Windows 10Ver1903 (64-bit) build 18362.175
#### Name and version of other software in use when reproducing the issue:
skype8 compiled with electron
#### Other information about your system:
lenovo laptop, 12 gigs of RAM memory, Intel(R) Core(tm)I7 7500U

**Comment by Adriani90** [comment] 2020-04-16 20:58
@kianoosh-shakeri I cannot reproduce this with NVDA 2020.1 Beta 1 and Skype Electron 8.58 on Windows 10 1909 update.

Could you please report if this is still reproducible for you?

**Comment by Adriani90** [comment] 2020-05-20 22:10
No updates from the initial author. I am closing this as works for me. Please feel free to comment on this if you are still having this problem and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-20 22:10 UTC
Labels: close/worksforme
