### ISSUE TITLE
aria-errormessage is not output

### ISSUE THREAD

**Issue by JAWS-test** [nvaccess/nvda#10642] opened 2019-12-19 04:52 UTC
### Steps to reproduce:
* Go to https://codepen.io/jaws-test/pen/VwYPRJg
* Go with tab key to the input field

### Actual behavior:

No output of the error message

### Expected behavior:

* Output of the error message (see https://www.w3.org/TR/wai-aria-1.2/#aria-errormessage)
* or at least a hint to the error message and how to navigate to it (e.g. via accesskey)

#### NVDA installed/portable/running from source:

* installed
* running from source

#### NVDA version:

2019.2.1

#### Windows version:

* Windows 10
* Windows 8

#### Name and version of other software in use when reproducing the issue:

* Chrome 79.0.3945.88
* The problem also occurs in Firefox and IE 11 (current versions)

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

**Comment by Adriani90** [comment] 2019-12-20 18:26
Closing as duplicate of #8318.

**Closed by Adriani90** 2019-12-20 18:26 UTC
Labels: duplicate
