### ISSUE TITLE
google chrome chrome's task manager is in accessible when arrowing up and down the list of chrome processes

### ISSUE THREAD

**Issue by mhussaincov** [nvaccess/nvda#10606] opened 2019-12-10 19:27 UTC
### Steps to reproduce:
1. launch google chrome
2. access chrome's task manager by going to the more tools option 
arrow up and down the list of chrome processes,

### Actual behavior:
nvda does not read out the name of the chrome process, it just says unknown when arrowing up and down the list

### Expected behavior:
nvda should read the list of chrome processes

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2019.2.1
#### Windows version:
windows 10 v1909

#### Name and version of other software in use when reproducing the issue:
google chrome up-to-date and nvda
#### Does the issue still occur after restarting your PC?
YES
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A

**Comment by Adriani90** [comment] 2019-12-10 22:48
cc: @feerrenrut

**Comment by francipvb** [comment] 2019-12-12 13:01
Confirmed with Edge beta.

**Comment by Adriani90** [comment] 2020-04-19 13:40
Works as expected in Edge 81 and Crome 81 with NVDA Version: alpha-20015,56a62097
In Crome NVDA repeats "list. Browser." on every list item but this is another issue.

Try to run the COM registration fixing tool and try again. I think this list is sort of Java code and might also work only if Java Access Bridge is enabled.

I am closing this as works for me. Feel free to comment if you still have this issue with the versions in my comment and we can reopen it. Thanks.

**Closed by Adriani90** 2020-04-19 13:40 UTC
Labels: close/worksforme
