### ISSUE TITLE
Does not notify upon reaching end of DOM content

### ISSUE THREAD

**Issue by pieman72** [nvaccess/nvda#8004] opened 2018-02-15 20:29 UTC
### Steps to reproduce:
1. Open Chrome
2. Browse to www.google.com
3. Use CTRL + DOWN ARROW to start linear navigation through each line of DOM structure
4. Go all the way down the content on the page
5. Listen for audio feedback on attempting to move further past the last element on the page

### Expected behavior:
Reader should voice a message indicating that the end of the page has been reached.

### Actual behavior:
No audible message is produced.

### System configuration:
NVDA 2017.4 (Installed)
Firefox 52.6.0 ESR
Windows 10 Enterprize

### Other questions:
Does the issue still occur after restarting your PC? 
Yes.

Have you tried any other versions of NVDA?
No, the above is the only one readily available for our work.

**Comment by fernando-jose-silva** [comment] 2018-02-16 14:34
This behavior could also be adopted by walking only with the arrows down or down on the web pages.

**Comment by ehollig** [comment] 2018-02-18 01:42
Duplicate of #1001

**Closed by ehollig** 2018-02-18 01:42 UTC
