### ISSUE TITLE
Windows 10 build 17120: OneCore voices sound as though high-pitch effect was put on them

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#8082] opened 2018-03-13 22:33 UTC
Hi,

This is considered a critical showstopper: Windows OneCore voices sound a bit different, in that it looks like high0pitch effect was put on them.

STR:

1. Install Windows 10 build 17120 (Insider Fast).
2. Switch to Windows OneCore voices.

Expected: pitch stays the same.
Actual: you'll notice the effects.
Additional: this does not happen with JAWS and Narrator.

Thanks.

**Comment by michaelDCurran** [comment] 2018-03-13 23:36
I'm assuming this happens with multiple versions of NVDA, including 
2018.1 and Next?


No doubt the sample rate of the audio has changed and we don't know 
about it.


I'm currently stuck on Skip ahead build 17604 and am not seeing the 
issue, but this build is getting rather old. I might need to roll back 
to rs4 builds to see this.

**Comment by josephsl** [comment] 2018-03-14 00:38
Hi, yes, confirmed with 2017.3, 2018.1 and latest next. Thanks.

**Comment by leonardder** [comment] 2018-03-14 17:44
Could this have to do with NVDA not yet using the most recent OneCore speech API that also supports faster speech rates?

In any case, confirmed here as well.

**Comment by Qchristensen** [comment] 2018-03-14 22:02
Ditto here, the only thing I'd add is just to document:
- The speech rate is faster than it was previously.  EG I had previously set the rate in Windows' speech settings as fast as possible and NVDA's to about the middle.  If I now set the Windows speech rate to the middle, the rate is similar.
- The pitch is also much higher than previously.  There is no option in Windows (that I have found, unless there's a registry key or something?) to change pitch.  Changing NVDA's pitch has a minimal effect.

Neither restarting NVDA or the computer, or changing synthesizers to something else and back changes the behaviour.

Interestingly with the sample rate theory, I tried recording the audio with the "Voice recorder" app by Microsoft from the Windows store, and the recording came out sounding like a chipmunk, so it seems they have changed sample rates and not adjusted even across their own apps.

I made a recording on my phone illustrating the new behaviour which I've uploaded here: https://www.dropbox.com/s/zmfn27sn5twml2j/My%20recording%20%234.wav?dl=0

**Comment by michaelDCurran** [comment] 2018-03-14 22:14
So it is looking like the sample rate is now 16000 hz or something. NVDA 
has always assumed it is 22050 hz.


Microsoft is aware of the issue, and we are working together to find the 
root cause.


Solutions would be either:

* Microsoft changes the sample rate back to 22050 hz.

* NVDA hardcodes the sample rate to 16000 for Windows build 17120 and 
above... though weirdly this is not yet in RS5 (17618).

* NVDA quries onecore speech for the correct sample rate. this is the 
most appropriate solution I'd say, except that I cannot work out anyway 
to get this information.

**Comment by jcsteh** [comment] 2018-03-15 03:36
Could those experiencing this please try [this try build](https://ci.appveyor.com/api/buildjobs/si9ct3l9t03ystam/artifacts/output%2Fnvda_snapshot_try-ocSpeechWavParams-14950%2C0e7c5e45.exe)? I'm not running that build, so I can't test it myself, but I think this should fix it.

**Comment by Qchristensen** [comment] 2018-03-15 04:00
Just had a bit of a play with it and the voice sounds much better.  It seems a bit sluggish, but I think that's my system today.

**Comment by josephsl** [comment] 2018-03-15 04:03
Hi, it works. BTW, if I may ask: could we tweak the code a bit to make it Python 3 compatible? Thanks.

**Comment by jcsteh** [comment] 2018-03-15 04:23
Oops. This broke indexing, which means it also broke reading by character. [Here's a new try build which fixes it](https://ci.appveyor.com/api/buildjobs/kg4kt6t3hc2y31uy/artifacts/output%2Fnvda_snapshot_try-ocSpeechWavParams-14951%2Cf1c9d487.exe).

As for Python 3 compat, I think there's going to be a bit of tweaking to make nvwave (and everything that uses it) Python 3 compatible, given the bytes/string stuff. Therefore, I think this is out of scope here.

**Closed** 2018-03-27 21:58 UTC
