### ISSUE TITLE
Braille scrolling in Notepad++ is broken

### ISSUE THREAD

**Issue by dreinn** [nvaccess/nvda#7419] opened 2017-07-19 08:43 UTC
### Steps to reproduce:
1. Open Notepad++ with a text file.
2. press scrolling button on display braille, you will see a new line for about half a second, then braille display return to previous position.
So scrolling is impossible.
This doesn't happen on other software like thunderbird, Microsoft Word, Notepad.
In 2017.2 all works ok.

### Expected behavior:
Show the new text normally.

### Actual behavior:
New text is showed for less that half a second.

### System configuration:
NVDA version: next-14210,6158737f

NVDA Installed or portable: portable

Other information:

Windows version: Windows7 64bit

Name and version of other software in use when reproducing the issue: Notepad++ 6.5.1

### Other questions:

Does the issue still occur after restarting your PC? Yes.

Have you tried any other versions of NVDA? Yes, 2017.2 and it is ok.

**Comment by leonardder** [comment] 2017-07-19 10:09
CC @BramD

This is most likely caused by commit https://github.com/nvaccess/nvda/commit/e5cc1931e0ebf4b37e72b1f634c30f9482543dcb, see https://github.com/nvaccess/nvda/pull/7332#issuecomment-314720772

**Comment by dkager** [comment] 2017-07-20 13:44
I would say p2, because this makes Notepad++ (and possibly others) pretty much unusable with a braille display.

**Comment by feerrenrut** [comment] 2017-07-31 09:06
Yes, this is caused by https://github.com/nvaccess/nvda/commit/e5cc1931e0ebf4b37e72b1f634c30f9482543dcb . I am looking into a fix for this problem. While we could just try to block show/hide caret events for scintilla window classes (which fixes the problem in Notepad++) , it seems that this problem does not occur in at least one other Scintilla based editor (SciTE).

**Comment by dreinn** [comment] 2017-08-11 10:51
sorry if this comment is not useful, any chances that this issues will be solved before 2017.3?
It is really frustrating because notepad++ is not usable anymore with a display braille, and it is a quite important text editor...

**Comment by leonardder** [comment] 2017-08-11 11:25
There isn't anything to be solved before 2017.3, as the brokenness only occurs in next, not in master.

**Comment by feerrenrut** [comment] 2017-08-29 04:36
This should be fixed on next with the re-incubation of #7332. See commit 95999d2. Please comment on or reopen this issue if the problem is ongoing.

**Closed by feerrenrut** 2017-08-29 04:36 UTC
Labels: Braille, p2, regression
