### ISSUE TITLE
NVDA Speech Viewer Not Announcing Column Headers for each row when using AG-Grid in Firefox

### ISSUE THREAD

**Issue by Roberto-Livi** [nvaccess/nvda#13656] opened 2022-05-02 13:31 UTC
### Steps to reproduce:
Using Firefox:
- open NVDA's speech viewer
- Click on a cells row from the ag-grid provided here: https://www.ag-grid.com/example.php

Notice that the column headers aren't announced for each row.
Example: `France selected row 7 column 3`.

### Actual behavior:

`France selected row 7 column 3`

### Expected behavior:

`France selected row 7 Country column 3`
**(Note works in Chrome)**

#### NVDA version: 

2021.3.4
2022.1beta4

#### Windows version:

Windows 10

#### Does the issue still occur after restarting your computer?

Yes

**Comment by XLTechie** [comment] 2022-05-02 20:00
>     NVDA version:
> 
> 2019.2.1

Why are you using such an old version of NVDA? NVDA is at least 14 versions 
newer than that now, and has had significant internal changes since then.

Please try either the newest stable version available from https://nvaccess.org, 
or the 2022.1 beta 4 version.

There is a very low likelihood that anyone will care to debug a problem 
happening in such a vastly outdated version of the screenreader.

If you can't use a new version for some reason, you can still download it, and 
run it as a temporary copy (by pressing the "continue running" button in the 
installer, instead of "install" or "make portable copy"), and see if your 
problem can be replicated there.

**Comment by Roberto-Livi** [comment] 2022-05-03 15:51
> NVDA version: 2019.2.1
> Why are you using such an old version of NVDA? NVDA is at least 14 versions newer than that now, and has had significant internal changes since then. Please try either the newest stable version available from https://nvaccess.org, or the 2022.1 beta 4 version. There is a very low likelihood that anyone will care to debug a problem happening in such a vastly outdated version of the screenreader. If you can't use a new version for some reason, you can still download it, and run it as a temporary copy (by pressing the "continue running" button in the installer, instead of "install" or "make portable copy"), and see if your problem can be replicated there.

This is happening with the latest versions of NVDA as well. If you guys are not able to reproduce, it would be great to know which versions you were using.

**Comment by seanbudd** [comment] 2022-05-05 05:54
I can reproduce this with 2022.1beta4 using FireFox, and cannot reproduce this issue with Chrome.

**Comment by Roberto-Livi** [comment] 2022-05-05 17:51
> I can reproduce this with 2022.1beta4 using FireFox, and cannot reproduce this issue with Chrome.

Yes, I am getting same results and wondering why this is happening and if its an issue with NVDA.

**Comment by Adriani90** [comment] 2024-10-13 15:54
When I move the mouse from left to right and click onto a column, the header is announced as expected, it doesn't matter in which row I am.
So I am not able to reproduce this issue with NVDA 2024.4 RC on Firefox 131. Closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-10-13 15:54 UTC
Labels: close/worksforme, p4, app/firefox, triaged
