### ISSUE TITLE
Constantly error sound by switching and closing window

### ISSUE THREAD

**Issue by lallerke1** [nvaccess/nvda#7501] opened 2017-08-16 09:20 UTC
1. Open nvda.
2. Open skype in compact view.
3. Or press any key in a win 10 machine.
I attached a log of my friend, who has constantly the problem.
[nvda.txt](https://github.com/nvaccess/nvda/files/1227684/nvda.txt)

*Edit:* Information from the log:
* Using NVDA version `next-14310,844f3145`
* Trying SAPI5 synth, unknown voice results in `Unsupported speech command: LangChangeCommand ('en_US')` warnings
 - Warnings do not produce the error sound so these are not the cause of the sounds.
 - It looks like swapping to espeak stops these warnings

Errors from log:
```
error executing event: gainFocus on <appModules.skype.Conversation object at 0x04FD6030> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "appModules\skype.pyc", line 259, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\skype.pyc", line 83, in event_gainFocus
  File "appModules\skype.pyc", line 70, in _gainedFocus
AttributeError: 'IAccessible' object has no attribute 'startMonitoring'
ERROR - eventHandler.executeEvent (11:05:48.841):
error executing event: gainFocus on <NVDAObjects.IAccessible.ContentGenericClient object at 0x04F84B30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 138, in setFocusObject
  File "appModuleHandler.pyc", line 254, in handleAppSwitch
  File "appModules\skype.pyc", line 263, in event_appModule_loseFocus
  File "appModules\skype.pyc", line 92, in lostFocus
AttributeError: 'IAccessible' object has no attribute 'stopMonitoring'
```

And this looks concerning as well:
```
DEBUGWARNING - WX Widgets (11:07:16.325):
..\..\src\msw\toplevel.cpp, line 1544:
assert m_menuDepth > 0: No open menus?
Stack trace:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 226, in OnAssert
```

**Comment by bhavyashah** [comment] 2017-08-24 15:22
@lallerke1  Constant errors is quite worrying. Could you please ask your friend to disable all add-ons and then report whether the reported issues still arise? Also, do these constant errors only reflect in the log or do they adversely affect NVDA's performance as well? Answers to these questions would greatly assist us in diagnosing this ticket.

**Comment by ehollig** [comment] 2017-11-03 18:44
I think the most concerning warning in the log is:
Unsupported speech command: LangChangeCommand ('en_US')
Does anyone know what may cause this? It appears the user was using Sapi5.

**Comment by Brian1Gaff** [comment] 2017-11-06 18:53
I'd ignore the  speech synth error warnings, they are in my experience quite 
normal if the voice is not multilingual.

IO - inputCore.InputManager.executeGesture (18:43:14.009):
Input: kb(desktop):downArrow
DEBUG - speechDictHandler.SpeechDict.load (18:43:14.023):
Loading speech dictionary 
'C:\Users\Brian\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\sapi5\sapi5-ScanSoft 
Serena_Full_22kHz.dic'...
DEBUG - speechDictHandler.SpeechDict.load (18:43:14.025):
1 loaded records.
IO - speech.speak (18:43:14.045):
Speaking [LangChangeCommand ('en_GB'), u'ScanSoft Serena_Full_22kHz']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:14.046):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:18.049):
Input: kb(desktop):tab
IO - speech.speak (18:43:18.088):
Speaking [LangChangeCommand ('en_GB'), u'Rate:  slider  50  Alt+r']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:18.088):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:21.105):
Input: kb(desktop):upArrow
IO - speech.speak (18:43:21.112):
Speaking [LangChangeCommand ('en_GB'), u'51']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:21.114):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:21.328):
Input: kb(desktop):upArrow
IO - speech.speak (18:43:21.447):
Speaking [LangChangeCommand ('en_GB'), u'52']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:21.448):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:22.993):
Input: kb(desktop):tab
IO - speech.speak (18:43:23.036):
Speaking [LangChangeCommand ('en_GB'), u'Pitch:  slider  50  Alt+p']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:23.036):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:24.280):
Input: kb(desktop):tab
IO - speech.speak (18:43:24.437):
Speaking [LangChangeCommand ('en_GB'), u'Volume:  slider  100  Alt+o']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:24.438):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:26.641):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:26.750):
Speaking [LangChangeCommand ('en_GB'), u'99']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:26.752):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:26.914):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:27.035):
Speaking [LangChangeCommand ('en_GB'), u'98']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:27.036):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:28.065):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:28.173):
Speaking [LangChangeCommand ('en_GB'), u'97']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:28.174):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:28.296):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:28.413):
Speaking [LangChangeCommand ('en_GB'), u'96']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:28.414):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:28.497):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:28.609):
Speaking [LangChangeCommand ('en_GB'), u'95']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:28.611):
Unsupported speech command: LangChangeCommand ('en_GB')
IO - inputCore.InputManager.executeGesture (18:43:28.690):
Input: kb(desktop):downArrow
IO - speech.speak (18:43:28.795):
Speaking [LangChangeCommand ('en_GB'), u'94']
DEBUGWARNING - synthDrivers.sapi5.SynthDriver.speak (18:43:28.796):
Unsupported speech command: LangChangeCommand ('en_GB')

I need not go on I think.
 I was always told its expected. However I also have a 16bit voice called 
Emily Dry and that does not say its name or indeed work in nvda in my 
machine, but that is a whole other issue of course.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by feerrenrut** [comment] 2017-11-07 05:38
I updated the description with the information I could pull from the attached log file.

In terms of the language change warning, these warnings can be ignored.
In short it looks like there is / was some problem with using skype. Is anyone able to reproduce this issue? If not we will have to assume it has been fixed by a skype update.

The wx assertion is also concerning. The stack trace doesn't tell us much, and the log doesn't include much information about what the user did to trigger this assertion. If it could be reproduced with the log level set to Debug that would help to track down the cause.

**Comment by feerrenrut** [comment] 2017-11-07 06:26
I believe the wx assertion issue is covered here: #6637 so we can safely ignore it on this issue.

We would still like to know if the skype problem is on going.

**Comment by Adriani90** [comment] 2019-01-12 13:42
@lallerke1 are you still having this issue? I saw another issue here which has been also caused by skype for business and has been fixed by running the com registration fixing tool. Can you please try that in case you sill have the problems?

**Comment by Adriani90** [comment] 2019-04-22 21:13
@lallerke1 this is just a reminder, can you still reproduce this issue or is your friend still able to reproduce it? This is a very specific issue and that's why it is very hard to reproduce withough any updates from you and your friend. I cannot reproduce this issue with NVDA 2019.1.1 and Skype UWP 8.42 as well as Skype Electron for Desktop 8.43. If we do not get updates from your side, this issue might be closed sooner or later without any result unfortunately.

**Comment by Adriani90** [comment] 2019-04-29 14:34
Closing for now because we don't have any answer from the initial author. If someone can reproduce this, please comment on it and we will reopen the discussion.

**Closed by Adriani90** 2019-04-29 14:34 UTC
Labels: Speech, bug
