### ISSUE TITLE
Uninstaller: Add option to remove existing user configuration upon unisntallation

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#11620] opened 2020-09-16 19:37 UTC
### Is your feature request related to a problem? Please describe.

Currently, when choosing to uninstall NVDA the configuration for the current user is retained. On single-user systems - or when a user/administrator wishes to perform a more thorough clean-up, we could consider adding a checkbox to the uninstaller to remove the configuration for the current user. For single-user systems in particular, this would save a step when wishing to perform a clean installation of NVDA.

**Comment by XLTechie** [comment] 2020-09-16 19:42
I would second this feature request.

It is sometimes necessary, in user support situations, to have users uninstall 
NVDA, and then manually remove the user config.  Having this as an optional 
automation would be handy.

The primary use case would be when reinstalling.
Therefore an alternative to this feature, would be a feature in the installer to 
allow a new copy of NVDA which is being installed, to first remove the existing 
user configuration.  In other words: to, instead of upgrading, do a fresh 
install.

**Comment by leonardder** [comment] 2020-09-18 09:43
Closing as duplicate of #6869

**Closed by leonardder** 2020-09-18 09:43 UTC
