### ISSUE TITLE
NVDA becomes unresponsive for a while in the TortoiseSVN commit dialog

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#8641] opened 2018-08-17 07:52 UTC
### Steps to reproduce:
1. Install TortoiseSVN, if you don't have it already.
2. Create a local clone of a repository (e.g. the one for the NVDA translation).
3. Choose a file to commit in that repository, by selecting it and activating the "SVN Commit" command from its context menu.
4. In the "Commit" dialog, activate the "Recent messages" button.
5. From the "Log History" dialog, select a commit message to insert it and press ENTER on it.

### Actual behavior:
After the "Log History" dialog closes, the focus returns to the "Commit" dialog and NVDA starts reading that dialog. For a few seconds then, NVDA becomes unresponsive and pressing CONTROL does not stop the speech. This started with version 1.10 of TortoiseSVN, if I'm not mistaking.

### Expected behavior:
After the "Log History" dialog closes, the focus returns to the "Commit" dialog and NVDA starts reading that dialog. NVDA should not become unresponsive in the "Commit" dialog, as it was before the update of TortoiseSVN to version 1.10 (it was OK with version 1.9).

### System configuration:
- Operating system: Windows 10 Pro version 1803 (build 17134.228), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-15878,fabb3cd4.
- TortoiseSVN version: 1.10.1.28295-x64 based on SVN v1.10.2.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA?
No, I haven't

**Comment by Adriani90** [comment] 2019-05-08 20:54
This is still reproducible in NVDA 2019.1.1. I get following in the log file:


```
IO - inputCore.InputManager.executeGesture (22:52:12.710):
Input: kb(laptop):downArrow
IO - inputCore.logTimeSinceInput (22:52:12.750):
0.040 sec since input
IO - speech.speak (22:52:12.750):
Speaking [u'small fix']
IO - inputCore.InputManager.executeGesture (22:52:15.770):
Input: kb(laptop):enter
IO - inputCore.logTimeSinceInput (22:52:15.930):
0.159 sec since input
IO - speech.speak (22:52:15.930):
Speaking [u'C:\\NVDA\\translations\\de - Commit - TortoiseSVN  Dialogfeld  Commit to:\nhttp://subversion.assembla.com/svn/screenReaderTranslations/de/nvda.po\nA new version of TortoiseSVN is available. Please go to http://tortoisesvn.net to get it.\nCheck:\nAll\nNone\n0 files selected, 0 files total']
IO - inputCore.logTimeSinceInput (22:52:15.950):
0.179 sec since input
IO - speech.speak (22:52:15.950):
Speaking [u'Recent messages  Schalter']
IO - inputCore.logTimeSinceInput (22:52:15.970):
0.199 sec since input
IO - speech.speak (22:52:15.970):
Speaking [u'small fix  Eingabefeld  mehrzeilig']
IO - inputCore.InputManager.executeGesture (22:52:18.119):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (22:52:19.359):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (22:52:19.599):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (22:52:20.720):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (22:52:20.920):
Input: kb(laptop):tab
IO - inputCore.InputManager.executeGesture (22:52:22.970):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (22:52:23.259):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (22:52:23.480):
Input: kb(laptop):shift+tab
IO - inputCore.InputManager.executeGesture (22:52:25.779):
Input: kb(laptop):tab
DEBUGWARNING - watchdog._watcher (22:52:26.319):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 231, in <module>
  File "core.pyc", line 519, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1003, in Notify
  File "core.pyc", line 490, in run
  File "queueHandler.pyc", line 86, in pumpAll
  File "queueHandler.pyc", line 53, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 179, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 966, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 854, in reportFocus
  File "speech.pyc", line 415, in speakObject
  File "speech.pyc", line 346, in _speakPlaceholderIfEmpty
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1044, in _get__isTextEmpty
  File "textInfos\offsets.pyc", line 559, in move
  File "textInfos\offsets.pyc", line 437, in _getUnitOffsets
  File "NVDAObjects\window\scintilla.pyc", line 222, in _getCharacterOffsets
  File "watchdog.pyc", line 339, in cancellableSendMessage
```
cc: @Robert-J-H, @josephsl

**Comment by Adriani90** [comment] 2023-08-24 13:23
@k-kolev1985 could you please test with the last NVDA alpha version if this is still occuring?

**Comment by k-kolev1985** [comment] 2023-08-24 13:52
@Adriani90 I tested it with the latest alpha build of NVDA and it does not occur anymore. Though I haven't observed the described behavior for quite some time now, so it seems that it has been fixed for a while now, though I don't know if on NVDA's side or on TortoiseSVN's.

**Comment by Adriani90** [comment] 2023-08-24 14:19
Thanks very much for the quick testing. Closing as works for me.

**Closed by Adriani90** 2023-08-24 14:19 UTC
Labels: close/worksforme
