### ISSUE TITLE
Avira free anti virus version 14.0.7.468: excessive verbosity by nVDA on going to Updates submenu > Start Update

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4817] opened 2015-01-17 13:36 UTC
**Reported by bhavyashah on 2015-01-17 13:36**
Steps to reproduce
1 Download, install and open Avira free anti virus version 14.0.7.468.
2 Go to Updates submenu > Start Update and hit Enter.
3 the update begins.
Results
- On my system, Avira (according to the NVDA beeps for progress bar updates) seemed to have finished checking/downloading/installing updates in two seconds.
- However, NVDA instead of interrupting speech to speak progress bar updates, announces excess information, reads the window and says other strange things.
- It reads the update window's contents like time remaining and data transmitted, then in continuity speaks the progress bar percent (the progress bar has already reached and then 'Close [10', 'Cose [9', 'Close [8' and so on until it reaches 'Close [4'.
  All this verbosity is strange and confusing, sorry if I was unable to explain clearly enough.

**Comment by leonardder** [comment] 2018-02-14 20:22
@bhavyashah: Could you provide a status update?

**Comment by bhavyashah** [comment] 2018-08-15 17:27
@leonardder Unfortunately, I do not use Avira anymore. Hence, I will be unable to provide a status update on this issue. However, if there are a bunch of Avira specific issues on the tracker (most of which would probably have been filed by me), I could probably seek assistance from an existing Avira user in testing these by asking on the NVDA Users e-group.

**Comment by Adriani90** [comment] 2019-01-11 20:42
Ok I have installed Avira for testing. The interface seems to have changed significantly since @bhavyashah reported this issue.

**Comment by Adriani90** [comment] 2019-05-05 18:13
We do not have other reports from users since many years. And I cannot reproduce this issue in NVDA 2019.1.1. Closing as works for me.

**Closed by Adriani90** 2019-05-05 18:13 UTC
Labels: App specific, bug, worksforme
