### ISSUE TITLE
NVDA stops working in edge beta after page load

### ISSUE THREAD

**Issue by francipvb** [nvaccess/nvda#10638] opened 2019-12-18 13:24 UTC
### Steps to reproduce:

1. Install Microsoft Edge Beta from [here](https://www.microsoftedgeinsider.com/download).
1. Open _Microsoft Edge Beta_ from start menu and load any web page.
1. Wait until NVDA says "page loaded" or something similar in your language.

### Actual behavior:

NVDA stops responding. This may be related to #10631, but the fact is that browse mode is not activated in any case.

### Expected behavior:

NVDA should act as normal. We know that browse-mode is not implemented for Chrome UIA implementation but focus mode should work.

#### NVDA installed/portable/running from source:

NVDA installed

#### NVDA version:

alpha-19460,d7229eff

#### Windows version:

Windows 10 pro 64-bit version 1909 (Build 18363.535)

#### Name and version of other software in use when reproducing the issue:

Microsoft Edge chrome-based, version 79.0.309.54

#### Other information about your system:

Locale set to es-AR.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes, tried previous build with same results.

[NVDA log file in debug mode](https://github.com/nvaccess/nvda/files/3978556/nvda-old.log)

**Comment by leonardder** [comment] 2019-12-19 18:42
I've seen this happening as well. I'm afraid this requires some extensive testing, may be even cooperation with Microsoft to solve this.

@michaelDCurran: Is this somewhere on the NV Access roadmap in the near future?

**Comment by gdata1** [comment] 2019-12-20 13:31
I can confirm that, too. but if you disable the UIA, the edge problem disappears.

**Comment by feerrenrut** [comment] 2020-01-13 07:14
Closed in b8347bd03588f1380cb668b5e0f10ce0bbe65db6 via #10675

**Closed by feerrenrut** 2020-01-13 07:14 UTC

**Comment by ivnc** [comment] 2020-01-20 09:02
We have received a report from a Spanish-speaking user saying that, when opening and closing context menu in Edge 79 Beta (Shift+F10) NVDA locks during a few seconds, the same that happens on page load without this fix. The problem has been successfully reproduced and looks like to be Native UIA fault, since disabling it makes Edge working as expected, including the context menu. the duration of the lock, according to the performed tests, is proportional to the document size.
This happens in NVDA 2019.2.1 with winTenApps 19.11.5 as well.
[NVDA Error in edge.log](https://github.com/nvaccess/nvda/files/4085243/NVDA.Error.in.edge.log)

Regards.
