### ISSUE TITLE
Say-all repeats some lines.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#11132] opened 2020-05-08 13:37 UTC
### Steps to reproduce:
Using `alpha-20175,9967903a ` or later.

1. Open #10885 with Chrome
1. Jump by heading with 'h' until you get to the heading "Description of how this pull request fixes the issue"
1. Start say-all (NVDA+down arrow)

The problem does not require changing the `Attempt to cancel speech for expired focus events` setting.

### Actual behavior:
After a few lines, the following is read twice:
"Tested moving through emails (and across table boundaries) in Gmail" 

### Expected behavior:
The line should be read once.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
Alpha build, post #10885 merge: `alpha-20175,9967903a `
Does not repro with prior alpha: alpha-20168,1cf36fbe

#### Windows version:
Win 10: 1909

#### Name and version of other software in use when reproducing the issue:
Chrome 81

#### If addons are disabled, is your problem still occuring?
No addons

**Comment by Mary5958** [comment] 2020-05-09 16:42
The same can be reproduced when reading pages in Firefox and with emails in HTML format in Thunderbird.

**Comment by gregjozk** [comment] 2020-05-11 17:33
Hello,

one more test case:
- open addons.nvda-project.org
- choose addon developer toolkit
- start say all
- nvda repeats many lines in a list of keyboard shortcuts etc

**Comment by amirsol81** [comment] 2020-05-13 17:23
Hi. NVDA also repeats sentences until a "period" is encountered. For instance, open https://www.zdnet.com/article/i-just-dumped-one-of-apples-worst-most-beautiful-products
NVDA repeats many sentences in continuous reading. The first repeated one is "It all must have seemed like a good idea at the time." It is located after the first heading. Simply place the cursor on the heading, or even on the last character of the heading, and press Insert+Down to initiate continuous reading.
This is with NVDA Version alpha-20204,0f54e8ce and Chrome 81/IE 11 on Windows 10 Version 2004.

**Comment by tapper82** [comment] 2020-05-14 15:47
Hi same on my windows 10 64.
NVDA
Version: alpha-20206,dba33431
 Firefox 78.1

**Comment by tapper82** [comment] 2020-05-14 23:01
@derekriemer @josephsl Can you reproduce this?

**Comment by Adriani90** [comment] 2020-05-15 16:10
@tapper82 this issue is reproducible and it is already known. See the PR referenced in the issue description for more details.

**Comment by leonardder** [comment] 2020-05-25 06:02
This is getting a bit annoying.

@feerrenrut not trying to force you at all, but could a revert be considered if a fix can't be available soon?

**Comment by josephsl** [comment] 2020-05-25 06:20
Hi,

Seconded - would like to get this done before beta freeze please.

Thanks.

**Comment by tapper82** [comment] 2020-05-25 08:38
+1

**Comment by Neurrone** [comment] 2020-05-31 05:59
Agreed with the other calls to revert this, because it is really quite annoying when using say all.

**Comment by dingpengyu** [comment] 2020-06-15 01:57
Used version: alpha-20317,6bf3ae5f
has been tested in Simplified Chinese, the problem has been solved.
[testing.log](https://github.com/nvaccess/nvda/files/4777645/testing.log)

**Comment by tapper82** [comment] 2020-06-15 10:26
Come on now this is getting to be a joke. How hard is it to getting it in to your heads that we cant read webpages properly. This is not a bug that can stay in NVDA. It is not fixt. Fix your code or back it out for god sake!

**Comment by codeofdusk** [comment] 2020-06-15 10:35
Apparently fixed in #11245.

**Comment by amirsol81** [comment] 2020-06-15 10:38
No, I can still duplicate it with Alpha-20317.

**Comment by leonardder** [comment] 2020-06-15 10:39
While I agree that this is an annoying issue, Two points:

1. There is an open pr that will solve this, #11245 
2. This code is only in Alpha snapshots. Note the following from the development snapshots page:

    > Alpha snapshots contain bleeding-edge code. These snapshots are generated straight from NVDA's mainline (master) branch. Once a feature is implemented, it will be merged straight into this branch. Although there are some automated tests, code in this branch may have not been tested at all by users. This should never be used in a production environment!

Comments with a harsh tone of voice like the one written by @tapper82 really aren't helpful in this situation. Please stay kind to each other.

**Comment by leonardder** [comment] 2020-06-15 10:39
#11245 is not yet merged...

**Comment by amirsol81** [comment] 2020-06-15 10:42
Looking forward to it then.

**Closed** 2020-06-16 08:25 UTC
Labels: bug/regression, component/speech, p1
