### ISSUE TITLE
Nvda stopped reading headlines named video in Yutube in microsoft edge

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7539] opened 2017-08-29 17:51 UTC
Hi, I noticed today that NVDA doesn't read the name video on Yutube
.
1. Open Microsoft Edge.
2 Open www.yutube.com
3. Press H. The NVDA should read the headings with the name video and so on. Nvda says it's empty. If the NVDA says that OCR is empty, the result is the title..nvda next-14358,f53e4910.
windows 10 1703 .

**Comment by feerrenrut** [comment] 2017-09-20 05:53
@gdata1 Could you comment on why you closed this? Is this now working for you?

**Comment by gdata1** [comment] 2017-11-05 21:59
Hello. It doesn't work for me.

**Comment by ehollig** [comment] 2017-11-05 23:06
Closing as duplicate of #7611, as it contains more information.

**Closed by ehollig** 2017-11-05 23:06 UTC
Labels: Edge
