### ISSUE TITLE
NVDA will be freezed When I Search the unexist string in firefox.

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#5912] opened 2016-04-29 00:19 UTC
Hi:
Step to reproduce:
1. Open firefox.
2. Press NVDA+Control+f to open the find dialog.
3. Enter a string that is not included in the current document.
4. Press enter key to perform the search.
5. A error dialog is occured, and the error announcing is interupted by itself.
6. Try to press any key to leave this dialog, but nothing is done. NVDA is seemed to be freezed.
note: this condition persist only several seconds.
Thanks!

**Comment by jcsteh** [comment] 2016-04-29 00:44
I can't reproduce this. I did the following:

1. Opened www.nvaccess.org in Firefox.
2. Pressed NVDA+control+f.
3. Typed "chickens" and pressed enter.
 * Result: NVDA says: Find Error dialog, text "chickens" not found, OK button
4. Pressed enter.
 * Result: The dialog disappears and I'm returned to the document.

I'm using eSpeak. What synthesiser are you using? Does this occur with eSpeak? Does it occur if you disable any add-ons?

**Comment by vgjh2005** [comment] 2016-04-30 09:43
Hi:
I am using IBM ViaVoice text to speech. It is a SAPI4 synthesizer. It is the most popular synthesizer in China. Thanks!

**Comment by jcsteh** [comment] 2016-05-01 02:57
Please note that unless you have a special license (and I'm not aware of 
any), using this synthesiser with NVDA is illegal. Regardless, it'd be 
great if you can test with eSpeak to see if you have the same problem. 
If you don't, the problem is somehow specific to the synthesiser.

**Comment by bhavyashah** [comment] 2017-08-03 06:27
@vgjh2005  Could you please test this issue with the ESpeak-NG synthesizer and then respond to https://github.com/nvaccess/nvda/issues/5912#issuecomment-216011467?

**Comment by vgjh2005** [comment] 2017-08-06 03:39
Fixed! Thanks!

**Comment by bhavyashah** [comment] 2017-08-06 04:50
Based on https://github.com/nvaccess/nvda/issues/5912#issuecomment-320483607, I guess it is time to close this ticket. @ehollig

**Comment by Brian1Gaff** [comment] 2017-08-06 08:49
Via Voice is very old now and sundry versions were made, one sounding 
uncannily like  Eloquence of course. However in two archives of home page 
reader here, i see different versions of via voice. One seems buggy and apt 
to just stop, and the other one OK.
 As I do not know the legality of still installing these after the long time 
period, I'm loathe to ask about the one mentioned  to try to see if the 
problem is the buggy one. Either way, its certainly not nvda, but what makes 
the synth freeze up is anyone's guess and on abandonware, unlikely to be 
sorted now.



For the record. these synths are standard Sapi4 and hence nvda can use them, 
and unlike the microsoft Mary in space and similar silly things, they are 
not laggy.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Closed** 2017-08-07 00:18 UTC
