### ISSUE TITLE
Screen Reader Reads the same element multiple times

### ISSUE THREAD

**Issue by MalekFarag** [nvaccess/nvda#14598] opened 2023-01-30 20:05 UTC
### Steps to reproduce:

1. Have a <div> with `role"alertdialogue"`
2. Add <button> inside (we included aria-label attribute)

### Actual behavior:
1. Read out the notification dialogue
3. (tabbed into confirm button) Read out "Confirm button. Confirm. Button Confirm. Button Cancel"
4. When tabbing to the Cancel button.... nothing is read out
5. When tabbing back to confirm... all behavior works as expected, including the cancel button

This only happens on the first read of this popup. 

We have tried the JAWS & Google chrome extension screen reader and they work fine. This just happens with NVDA screen reader

### Expected behavior:
![image](https://user-images.githubusercontent.com/43182938/215582175-4fdf8604-9275-4e9a-abfe-185f455d7e07.png)
1. Read out the notification dialogue
2. Read out "Confirm Button"
3. When tabbing to the Cancel button.... Read out "Cancel Button"

### System configuration
Windows 10
App running on localhost. This also happens in production

#### NVDA version:
NVDA 2021

#### Windows version:
Windows 10

#### Name and version of other software in use when reproducing the issue:
Latest version of jquery/kendo UI

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, just 2021.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2023-02-07 11:24
Duplicate of #4079 and probably very related to #8221. Closing as duplicate

**Closed by Adriani90** 2023-02-07 11:24 UTC
Labels: close/duplicate
