### ISSUE TITLE
on nvaccess.org with Firefox, the tab key jumps back to the start of the page

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#11004] opened 2020-04-14 12:06 UTC
### Steps to reproduce:
Using Firefox, visit https://nvaccess.org
make sure you are not focused on the start of the page. Use heading or simply arrow down to be some where else.
now press the tab key once.
### Actual behavior:
NVDA jumps to the start of the page, no matter from where you pressed your tab key.
### Expected behavior:
NVDA should jump to the next element on the page.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.1beta1

#### Windows version:
1909 (OS Build 18363.752)
#### Name and version of other software in use when reproducing the issue:
Firefox 76.0b4 (64-bit)
#### Other information about your system:
none relevant
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
not yet.
#### If addons are disabled, is your problem still occuring?
yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
not needed in this case

**Comment by Neurrone** [comment] 2020-04-15 13:29
I've seen this before on the React blog as well and the React docs, in case having another example helps with isolating the root cause.

**Comment by zahra21** [comment] 2020-04-15 16:56
hi.
as i mentioned in different places,
my favorite version of nvda, is nvda 2017.2.
i tested with this version and reproduced this issue.

**Comment by Adriani90** [comment] 2020-04-16 20:26
Do you have by chance disabled the automatic focus movement to focusable objects? Press nvda+8 or enable it in the advanced settings again and see if the issue is still reproducible.

**Comment by Adriani90** [comment] 2020-04-16 20:26
Also maximize the window with windows+up arrow when reproducing this.

**Comment by mohdshara** [comment] 2020-04-17 10:04
automatic focus movement to focusable objects is checked in the advanced settings. also maximizing the window doesn't make a difference.

**Comment by Neurrone** [comment] 2020-04-17 11:30
I think it might be caused by that setting.

When disabled and when on the first h2, when pressing tab nothing happens.

**Comment by Adriani90** [comment] 2020-04-17 17:53
@Neurrone this is ok, if you disable it the system focus does not move when you press tab out of the browse mode because it is blocked and does not follow the virtual cursor. However, if automatically set focus to focusable objects is enabled, everything should work as expected.
Is this also reproducible in Firefox 75? Or did this start with Firefox 76?
cc: @MarcoZehe

**Comment by mohdshara** [comment] 2020-04-18 07:48
I have Firefox portable at version 75. I notice the same behavior.

**Comment by Neurrone** [comment] 2020-04-23 15:22
Here's [another example where this behaviour occurs](https://www.mediacurrent.com/blog/what-is-gatsbyjs/)

**Comment by Adriani90** [comment] 2020-05-13 20:53
Closing as duplicate of #9234.

**Closed by Adriani90** 2020-05-13 20:53 UTC
Labels: app/firefox, close/duplicate
