### ISSUE TITLE
Impossible to close the log viewer while an update is in progress

### ISSUE THREAD

**Issue by Mohamed00** [nvaccess/nvda#8453] opened 2018-06-27 10:05 UTC
### Steps to reproduce:
1. Update to a recent next snapshot.
2. Try to open the log viewer while the update is in progress (during the final updating NVDA phase of the update with the indeterminate progress bar).
### Actual behavior:
The log viewer opens but it's impossible to exit it with the escape key or the exit item in the log menu.
### Expected behavior:
The log viewer should exit when the escape key is pressed or the exit item in the log menu is selected.
#### NVDA Installed/portable/running from source:
Installed.
#### NVDA version:
next-15430,77fff08b
#### Windows version:
Windows 10 build 17134.137.
#### Name and version of other software in use when reproducing the issue:
NVDA.
#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA?

Yes, latest master and stable versions of NVDA, this isn't happening in either one of them. This might be another WX Python 4 issue rearing its head again.

**Comment by Mohamed00** [comment] 2018-07-18 12:21
This is still happening as of the latest alpha snapshot with WX Python 4.0.3.

**Comment by lukaszgo1** [comment] 2018-07-19 18:29
CC @josephsl

**Comment by josephsl** [comment] 2018-07-19 18:41
Hi, I’m guessing that this hasn’t been fixed with latest alpha? If so, that’s concerning indeed. Thanks.

**Comment by Mohamed00** [comment] 2018-07-20 00:04
No, it hasn't.

**Comment by Adriani90** [comment] 2024-05-20 21:20
I cannot reproduce this while updating from NVDA alpha-31971,c5954630 to NVDA alpha-31994,b54c62f5. It seems this issue is solved, maybe by the last updates of WX Python or so. I am closing as works for me. if you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-05-20 21:20 UTC
Labels: close/worksforme, component/NVDA-GUI
