### ISSUE TITLE
when sound split is disabled, the feature as it is in NVDA core now interferes with everything else that changes channel volumes, whether an add-on or not.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#16287] opened 2024-03-10 16:10 UTC
### Describe the solution you'd like
Some add-ons allow you to modify application channel volumes individually.
Since the introduction of the "sound split" feature, NVDA systematically returns sound to both channels of applications to hear sound equally on both channels when "Disabled" mode is selected.
In this case, the modifications made by the add-ons are canceled

### Describe alternatives you've considered
The "disabled" mode should mean that NVDA does nothing in this case and works as before the feature was introduced.
### Additional context
This concerns alpha versions of NVDA.

**Comment by Adriani90** [comment] 2024-03-10 17:06
Cc:  @mltony

**Comment by paulber19** [comment] 2024-03-10 22:05
Correction: it is not the applications that are centered, but only the 
system sounds.

**Comment by CyrilleB79** [comment] 2024-03-10 23:23
@paulber19 could you indicate the names of these add-ons as examples? Thanks.

**Comment by mltony** [comment] 2024-03-11 00:19
I implemented sound split in a generic enough way, so that add-on authors can reuse it to customize functionality - use `audio.soundSplit.applyToAllAudioSessions` function with a custom lambda. I think add-ons should go through this way, because pycaw is now included in NVDA and it's not a good idea to bring another version of pycaw in an add-on.

**Comment by XLTechie** [comment] 2024-03-11 04:16
@mltony
> I implemented sound split in a generic enough way, so that add-on authors can reuse it to customize functionality - use
> audio.soundSplit.applyToAllAudioSessions function with a custom lambda. I think add-ons should go through this way, because pycaw is now included in NVDA

Would this be worth documenting in the dev guide?

**Comment by paulber19** [comment] 2024-03-11 07:54
Totally agree. However, to continue providing functionality in previous 
versions of NVDA, this is necessary.

**Comment by paulber19** [comment] 2024-03-11 08:04
NVDAExtensionGlobalPlugin
With this add-on, it is possible to place nvda on one side and all 
applications on the other side, including system sounds.
But, although NVDA's "sound split" feature mode is disabled, NVDA puts 
the system sounds in the center.

**Comment by CyrilleB79** [comment] 2024-03-11 15:14
@paulber19
 what you are describing just seems another sound split feature; am I correct?
If yes, there is no point in keeping it enabled in the add-on for NVDA 2024.2 since the feature is in core. You may though want to keep it in the add-on for older versions of NVDA though.

However, if @paulber19's add-on only uses functions in the API (i.e. public) for this feature, the introduction in NVDA core of Sound Split feature would be an API breaking change, what should not be allowed for 2024.2.
I did not check though which functions are used by the add-on.

@mltony do you know if the introduction of Sound Split feature in core has changed the behaviour of existing public functions?

**Comment by Adriani90** [comment] 2024-03-11 15:37
An API breaking change can be allowed in 2024.3 though, is this correct?

cc: @gerald-hartig, in case sound split needs to be reverted and rescheduled to 2024.3 including documentation adjustments.

**Comment by paulber19** [comment] 2024-03-11 17:49
what you are describing just seems another sound split feature; am I 
correct?
Yes, but much finer. It is possible to do this pretty much like NVDA 
does, but also on an application by application basis or just for the 
application under focus. It is also possible to adjust the channel 
balance of NVDA or any other application including system sounds.
So I won't say it's the same functionality.
The difference in common with NVDA is that NVDA directs any new audio 
output according to the audio separation mode chosen. This is the 
problem because even in "Disabled" mode, any new output will be placed 
in the center by NVDA and therefore will cancel the choice made using 
the add-on.
Let's take the "foobar2000" application as an example. With the add-on, 
the user can choose to put NVDA on one side and Foobar2000 on the other 
side without touching the other applications.
And this was only done once. Until now, if foobar2000 was stopped then 
restarted, it found itself on the same side. It is Windows which 
memorizes the balance of applications.
Now when the sound separation mode is "Disabled", foobar2000 is found on 
both channels.
So this mode does not mean that NVDA does nothing, but that NVDA must 
put any new audio source on both channels.
I hope I was clearer, even if it was a little long,
For this functionality and so far, the add-on does not use any part of NVDA.

**Comment by mltony** [comment] 2024-03-11 18:40
@paulber19,
so it seems that you can modify your  add-on to make it to work with sound split by making use of `applyToAllAudioSessions` function - I don't understand why that's not enough.
@Adriani90 ,
I wouldn't call this API breaking change as sound split just inroduced some new API. The problem is that @paulber19 's addon had some functionality that is conflicting with sound split even back in the days when sound split was an add-on. I would argue that we shouldn't aim at the attitude of never breaking a single add-on, this attitude would be counterproductive, especially given the fact that there is no well-defined set of NVDA API that can be called addon API, so if we adopt that attitude, any change in nVDA core might be at risk. Any internal NVDA API might be used by an add-on. In this case, new API is not even the root cause. The root cause is that @paulber19 is using the same wasapi api as sound split. And this conflict can be resolved on the add-on side using the way I described above. So I guess the ultimate question is given such incompatibility between an add-on and a new feature, is that the responsibility of add-on or the author of new feature to resolve this? I would argue that addon author should resolve this - at least when my addons were broken by new features (like tab QuickNav command) - that was the case - I was expected to fix my addon. But LMK if you think otherwise.

**Comment by XLTechie** [comment] 2024-03-11 22:58
@mltony I don't particularly care if one or two add-ons are broken by a new NVDA 
feature, if it doesn't actually change the definite public API.

However, I would like to understand better why you consider @paulber19 to be 
wrong, in regards to NVDA forcing centering/reset to stereo, when set to 
disabled. I find that problematic if there is no workaround. Disabled should 
mean "don't touch".

**Comment by seanbudd** [comment] 2024-03-11 23:06
Closing this issue for reasons @mltony outlined. This is just a consequence of NVDA development. As already discussed, the API hasn't changed here, just the nature of NVDA's behaviour.

**Comment by XLTechie** [comment] 2024-03-11 23:20
@seanbudd I wonder if I might get clarification on my question before this issue 
is closed?

My understanding of the issue, is that the implication has been made that the 
"disable" state is not being honored, that in fact NVDA is causing undocumented 
and, frankly, unexpected behavior when this feature is set to disabled. I for 
one would like to know if that is true, and why it should be the case.

As I said above, disable is generally assumed to mean "do not touch". I.e. the 
behavior should be the same as if this feature did not exist at all, such as in 
2023.3.4.

If I'm wrong about what is being claimed here, then fine, but that was how I 
read the later comments.

**Comment by seanbudd** [comment] 2024-03-12 02:42
@XLTechie  Is the difference in expected behaviour just limited to interacting with add-ons? What has changed here is a new feature has been implemented to track and manage the state of stereo output. My understanding is that without add-ons, the disable state is identical to the "do not touch" case for users. Now that NVDA has an API for stereo manipulation, I think it is the responsibility of add-ons to utilise the API to maintain/respect the "disabled" state.

**Comment by cary-rowen** [comment] 2024-03-12 11:21
I totally agree with @mltony regarding API and 3rd party add-on compatibility.

> I wouldn't call this API breaking change as sound split just inroduced some new API. The problem is that   @paulber19  's addon had some functionality that is conflicting with sound split even back in the days when sound split was an add-on. I would argue that we shouldn't aim at the attitude of never breaking a single add-on, this attitude would be counterproductive, especially given the fact that there is no well-defined set of NVDA API that can be called addon API, so if we adopt that attitude, any change in nVDA core might be at risk. Any internal NVDA API might be used by an add-on. In this case, new API is not even the root cause. The root cause is that   @paulber19  is using the same wasapi api as sound split. And this conflict can be resolved on the add-on side using the way I described above. So I guess the ultimate question is given such incompatibility between an add-on and a new feature, is that the responsibility of add-on or the author of new feature to resolve this? I would argue that addon author should resolve this - at least when my addons were broken by new features (like tab QuickNav command) - that was the case - I was expected to fix my addon. But LMK if you think otherwise.

**Comment by paulber19** [comment] 2024-03-12 12:13
>the API hasn't changed here, just the nature of NVDA's behavior.
And it's just this new behavior that was the subject of the issue: sound 
split is still active even in "Off" mode.
The discussion drifted into an API issue and I don't know why.
There are no API problem with the add-on.

**Comment by cary-rowen** [comment] 2024-03-12 14:16
Hi Paul,

Regarding the issues you mentioned:
> sound split is still active even in "Off" mode.

This is already tracked by #16292.

The reason you find this discussion confusing is that I think you added to the confusion in your answer to @CyrilleB79's question.

Anyway, this issue has been closed, let us focus on the discussion of #16292.

Thanks
Cary

**Comment by LeonarddeR** [comment] 2024-03-16 12:21
Reopening as per https://github.com/nvaccess/nvda/issues/16292#issuecomment-1998527072, changing the title accordingly

**Comment by Adriani90** [comment] 2024-03-20 13:45
In my view there is no add-on for this needed anymore, if people invest a bit of energy to enhance what we have already. In this case it is probably a very small change to achieve what your add-on already can do.
Installing an add-on just for this small change is an overkill in my view.

**Comment by paulber19** [comment] 2024-03-20 16:47
Thank you Leonard for clarifying because I was unable to make myself 
understood.
I used your last sentence as the title.

**Comment by Adriani90** [comment] 2024-03-21 14:40
Thanks @LeonarddeR I think I got the issue now.
@mltony what you introduced as "disabled" is actually rather enforcing "everything in both channels". I propose renaming the currently "disabled" state to "everything in both channels" and add an additional state called "disabled" which entirely disables this feature and sets the underlying API to "off".

So for example if I change my apps audio settings via an external tool such as eartrumpet
https://github.com/File-New-Project/EarTrumpet
, then the sound split feature of NVDA will not honor this when setting to disabled because it enforces its own both channels setting.

@seanbudd I think this needs a quite high priority to be fixed.

**Comment by LeonarddeR** [comment] 2024-03-21 17:41
@mltony  with respect, but do you really not want to understand what is going wrong here? Just because you are not aware of another program that adjusts channel volumes does not mean that NVDA is free to unnecessarily mess with channel volumes of third party applications without the end user's permission. If sound split is enabled, the end user explicitly chooses to do so. If sound split is disabled (default) the feature should simply be off as @Adriani90 explained in https://github.com/nvaccess/nvda/issues/16287#issuecomment-2012477077 .
In fact, there is a similar audio mixer program created by Babbage (my former employee) that does similar things as sound split.

CC @seanbudd: Do you acknowledge that the sound split feature when in disabled state *should not* change channel volumes of other applications by any means?

**Comment by paulber19** [comment] 2024-03-21 18:40
> The only known program is @paulber19's add-on, 

No and I already quoted it:
soundVolumeView (Nirsoft) 
<https://www.nirsoft.net/utils/sound_volume_view.html>

And even if it were the only one, it seems to me that it must be taken 
into account even if it is an add-on.

> hich was incompatible with Tony's enhancements in the first place, 
I would like to know what this adds to the discussion other than simply 
to denigrate the add-on.
before, I provided API for @paulber19 to fix that on his side
his sideThis also adds nothing to the discussion. It's not the add-on 
that is the problem.
It works fine without this so-called API.

**Comment by Adriani90** [comment] 2024-03-21 20:25
@mltony are there any technical limitations that hold you back from introducing an additional state in the combo box called "disabled" which entirely disables this feature and the underlying API as I proposed above?
What is the reason not to do it? In general, any external tool that changes something in terms of audio on the system should be possible even while running NVDA. It is not an option to restrict external tools to make changes to the audio channels. If there are any technical limitations for implementing an additional "disabled" state, then this feature must be reverted unfortunately. The impact would be too negative for users if this makes it into the stable release.
If there is no technical limitation but it needs more discussion, then I propose to make this feature available only in the alpha releases and hold it back from stable or beta releases until a solution is found.

**Comment by XLTechie** [comment] 2024-03-21 23:02
@mltony, @seanbudd, we should not need to prove this.

Disabled should mean disabled. In this case it's false.

We can not predict every user's situation, and just because there aren't 
real-world effected use cases in this (and the other) thread, only means that 
the limited number of people following this issue, don't have specific use 
cases.

Disabled *HAS TO* mean disabled. Otherwise the word needs to change, and we need 
to warn in the userguide that NVDA *WILL* absolutely be changing the audio 
performance of your computer, even if most users don't care.

To do otherwise is irresponsible.

**Closed** 2024-04-08 00:40 UTC
