### ISSUE TITLE
NVDA error when navigating subreddits with headings in Firefox

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#13244] opened 2022-01-17 10:54 UTC
### Steps to reproduce:
1. Navigate to a subreddit, for example 
https://www.reddit.com/r/eluktronics/
Then atempt to navigate posts with headings.
### Actual behavior:
NVDA navigates headings with error tone in dev, and following segment appears in log

ERROR - RPC process 17524 (firefox.exe) (04:50:40.730) - Dummy-446 (12556):
Thread 19316, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::fillVBuf, 955:
AccessibleChildren failed (count: 2), res: -2147417848

### Expected behavior:
NVDA navigates headings normally with no error tone and no error in log
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-24471,c6a6df82
#### Windows version:
windows 11  Version 21H2 (OS Build 22000.434)
#### Name and version of other software in use when reproducing the issue:
Firefox 64 bit, version 96.01
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by lukaszgo1** [comment] 2022-01-17 16:10
Please try this with NVDA 2021.3.1 to check if this an Alpha regression or not.

**Comment by enessaribas** [comment] 2022-01-17 16:28
hi,
Would a portable version be acceptable? I prefer not uninstalling/reinstalling my current NVDA.

**Comment by enessaribas** [comment] 2022-01-17 16:29
I also tried before doing the update to alpha today, and this problem did not happen until the snapshot today came out.

**Comment by lukaszgo1** [comment] 2022-01-17 16:56
cc @feerrenrut  Looks like a regression from #13126.

**Comment by lukaszgo1** [comment] 2022-01-17 21:34
Another STR for this issue is as follows:
1. Open https://www-tiflocomp-ru.translate.goog/?_x_tr_sch=http&_x_tr_sl=ru&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=sc
2. Inspect the log

```
ERROR - RPC process 7696 (firefox.exe) (22:29:51.719) - Dummy-21 (7004):
Thread 6684, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::fillVBuf, 955:
AccessibleChildren failed (count: 1), res: -2147467262

ERROR - RPC process 7696 (firefox.exe) (22:29:53.344) - Dummy-21 (7004):
Thread 6684, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::fillVBuf, 955:
AccessibleChildren failed (count: 1), res: -2147467262

ERROR - RPC process 7696 (firefox.exe) (22:29:53.494) - Dummy-21 (7004):
Thread 6684, build\x86_64\vbufBackends\gecko_ia2\gecko_ia2.cpp, GeckoVBufBackend_t::fillVBuf, 955:
AccessibleChildren failed (count: 1), res: -2147467262


```

These errors were probably already occurring but we were logging them at a lover level.  In #13126 failures when getting accessible children are logged at the error level so this becomes quite noisy. cc @jcsteh  For awareness. Can these issues be fixed in Firefox?

**Comment by jcsteh** [comment] 2022-01-18 02:35
Thanks for the ping. To debug this, I'd need to know the unique id of the Accessible that is failing. The log doesn't include that, so I need to modify the build. However, I'm having trouble with Visual Studio not giving me the Windows 11 SDK as an option on this machine, so that'll have to wait until I can rectify that.

That said, while this isn't the issue in the Google Translate example, it's entirely possible for the parent Accessible itself or any of its children to die between the call to accChildCount and AccessibleChildren. Those calls are currently not atomic; the tree can mutate underneath, since in Firefox, NVDA is currently talking to a remote process even when injected. The re-architecture we're working on changes this, but that's months away from shipping yet. I'm fairly sure that's what's going on in the Reddit case. I would suggest that AccessibleChildren failures should be debugWarnings, not errors.

The Google Translate case is different, as it fails with E_NOINTERFACE every time you refresh the buffer. That's going to need more debugging.

**Comment by jcsteh** [comment] 2022-01-18 05:15
For the Google Translate issue, I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1750680.

I can't fix the Reddit issue for now; that's due to the tree mutating between calls as I described.

**Comment by feerrenrut** [comment] 2022-01-18 06:25
We could reduce the logging level, I'm a little hesitant, I think it's likely that this error results in a change in behavior for users.

**Comment by jcsteh** [comment] 2022-01-18 07:02
The E_NOINTERFACE error certainly results in a behavioural difference for users. That one is 100% a Firefox bug. However, CO_E_OBJNOTCONNECTED indicates that the parent died since the query to accChildCount, and returning no children indicates that all children died since the call to accChildCount. There's no behavioural difference there because the objects already died, so even if they had been rendered, they would've been removed immediately thereafter.

**Comment by feerrenrut** [comment] 2022-01-19 03:05
Ok. Thanks for that explanation @jcsteh. If you know, are those error codes specific to Firefox or shared with Chromium?
I'll add a special cases for those errors and include your comment if you don't mind the plagiarism.

**Comment by feerrenrut** [comment] 2022-01-19 04:01
PR created: https://github.com/nvaccess/nvda/pull/13257 I intend the PR to close this issue, however the `E_NOINTERFACE` failure will continue to emit an error sound until it is resolved in Firefox.

**Comment by jcsteh** [comment] 2022-01-19 05:23
> If you know, are those error codes specific to Firefox or shared with Chromium?

Chromium seems to just return E_FAIL for a dead object, which isn't ideal. As I noted in the PR, I realised COM is actually returning RPC_E_DISCONNECTED for Firefox, not CO_E_OBJNOTCONNECTED, but you should handle both the same. (If you're curious, RPC_E_DISCONNECTED is what COM throws when a server calls CoDisconnectObject and then a client tries to call that object. In contrast, CO_E_OBJNOTCONNECTED is normally something a server chooses to return.)

I wouldn't ever expect to see Chromium throw E_NOINTERFACE for an AccessibleChildren call. The fact that this is happening in Firefox is a very obscure bug involving interactions with the COM runtime and our sandbox.

Btw, I've submitted a patch for the Firefox bug and it is now awaiting review.

**Closed** 2022-01-21 02:32 UTC
