### ISSUE TITLE
Error in hardware support with some events in Thunderbird and other places

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#14895] opened 2023-05-02 10:58 UTC
### Steps to reproduce:

With a Handy Tech display attached and running: 
1. Create a new message in Thunderbird and write some text.
2. Tab around the UI, out of and back into the main text area. Note that you may have to repeat this a few times.

### Actual behavior:

After some tries, the Braille display stops working, I hear one or more error sounds emitted by NVDA, and even restarting the Braille display doesn't fix the problem. auto detection of Braille displays is broken until I restart NVDA.

### Expected behavior:

Braille display continues working and doesn't suddenly fail.

### NVDA logs, crash dumps and other attachments:

the following is logged in the NVDA log file:

LookupError: Object has no text descendants
ERROR - stderr (12:41:48.263) - hwIo.ioThread.IoThread (13352):
Exception in thread hwIo.ioThread.IoThread:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 201, in run
OSError: exception: access violation reading 0x1BF30058
ERROR - core.CorePump.Notify (12:41:48.678) - MainThread (19800):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 750, in Notify
  File "braille.pyc", line 2653, in pumpAll
  File "braille.pyc", line 2414, in handlePendingCaretUpdate
  File "braille.pyc", line 2423, in _doCursorMove
  File "braille.pyc", line 2431, in scrollToCursorOrSelection
  File "braille.pyc", line 1645, in scrollTo
  File "braille.pyc", line 1686, in updateDisplay
  File "braille.pyc", line 2273, in update
  File "braille.pyc", line 2194, in _updateDisplay
  File "C:\Users\marco\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\patches.py", line 563, in _displayWithCursor
    self._writeCells(cells)
  File "braille.pyc", line 2242, in _writeCells
  File "braille.pyc", line 2247, in _writeCellsInBackground
  File "hwIo\ioThread.pyc", line 121, in queueAsApc
  File "hwIo\ioThread.pyc", line 77, in _getApc
RuntimeError: Thread is not running

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

version alpha-28166,e77bde9a

#### Windows version:

Windows 11 22H2 (10.0.22621) workstation AMD64

#### Name and version of other software in use when reproducing the issue:

Thunderbird beta 113.0B5. I've also seen this happen in Firefox Nightly on occasion, but the Thunderbird usecase is more reproducible.

#### Other information about your system:

Handy Tech ActiveBraille 2021.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No, as I didn't want to loose the speed improvements in the current alphas compared to 2023.1.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes.

CC @jcsteh

**Comment by CyrilleB79** [comment] 2023-05-02 13:16
@MarcoZehe you have indicated that the issue also occurs with add-on disabled. However the log fragment that you have provided shows the usage of 
BrailleExtender add-on. Could you confirm that the issue also occurs with add-ons disabled and provide the corresponding log?

**Comment by Adriani90** [comment] 2023-05-02 15:04
cc: @aaclause

**Comment by tapper82** [comment] 2023-05-03 20:30
NVDA version:
version alpha-28166,e77bde9a is buggy. Say all is broken in firefox and Thunderbird. All so you cant use letters to jump to different links on the desktop or when in folders.

**Comment by seanbudd** [comment] 2023-05-09 02:29
@leonardder  - do you think this could be related to #14312

@tapper82  - please open a new issue for this, what you are reporting is not related to this issue.

**Comment by leonardder** [comment] 2023-05-09 05:32
I wasn't aware of this GH issue. Actually, #14899 was made to provide more logging for exactly this issue.
@MarcoZehe Could you please provide another log with the newest alpha? That should also log the stack info of all the threads within NVDA.
This could indeed be related to #14312, though I have seen this in earlier versions of NVDA as well. In fact, both #14312, and #14627 were attempts to mitigate this issue.
I'm glad to see that we can actually somehow reproduce this reliably now.

**Comment by leonardder** [comment] 2023-05-09 05:34
> #### Have you tried any other versions of NVDA? If so, please report their behaviors.
> 
> No, as I didn't want to loose the speed improvements in the current alphas compared to 2023.1.

While this is very understandable, it would really be very helpful if you could try to reproduce this with NVDA 2023.1 and 2022.4. I really want to track down the cause of this, but I'm afraid it is caused within an APC that somehow doesn't end up in the stack info.

**Comment by tapper82** [comment] 2023-05-09 12:02
@seanbudd  It's OK I fixt my bug. It was my sinth I was using. The bug was because of the sound API changes. by @jcsteh https://github.com/nvaccess/nvda/commit/e77bde9a5f50df276eab9008e280850d3a727bc7
Old sinth drivers will need a update to work with the changes. Sorry for the noise and thanks for all the hard work the devs do on NVDA.

**Comment by seanbudd** [comment] 2023-05-10 05:14
Thanks, closing this

**Comment by seanbudd** [comment] 2023-05-10 05:14
my mistake - ignore

**Comment by MarcoZehe** [comment] 2023-05-10 11:46
@leonardder See above comment. It took until now to get another failure and log, but this time it has the threads.

**Comment by leonardder** [comment] 2023-05-10 11:53
Thanks. Looks like this is again not giving interesting dumps, so the 
crash happens in code that's not Python. It must be something like 
Windows calling an APC Python has garbage collected somehow. This is 
exactly what I tried to avoid by storing them in a cache dictionary so 
they wouldn't be.

I probably need to look into ctypes internals to see how function 
pointers are passed to c style functions. May be my assumption is wrong 
that it should be enough to keep a reference to the cfunctype object.

**Comment by jcsteh** [comment] 2023-05-11 00:46
Holding a reference to the cfunctype object should indeed be enough. That said, I'd be inclined to change things so that instead of caching an APC function, you just cache Python functions and parameters. There would be a single `@winKernel.PAPCFUNC` which uses its parameter to identify the cached Python function to call. This way, you're not messing around with holding references to ctypes things. That means you're going to have to use an int to identify things, though, not a UUID.

**Comment by jcsteh** [comment] 2023-05-11 00:47
Note that holding references to ctypes functions defined inside an instance method is also prone to cycle collection issues.

**Comment by leonardder** [comment] 2023-05-11 11:08
Ah, these are very helpful suggestions. I'll try to prototype this later today.

**Comment by MarcoZehe** [comment] 2023-05-11 11:56
I had two more failures today, both in Firefox, both when displaying text-only content, for example a raw diff in Phabricator. One such log was:

```
CRITICAL - hwIo.ioThread.IoThread.run (08:39:13.544) - hwIo.ioThread.IoThread (13116):
Exception in IoThread function
Traceback (most recent call last):
  File "hwIo\ioThread.pyc", line 203, in run
OSError: exception: access violation reading 0x1C870058
INFO - hwIo.ioThread.IoThread.run (08:39:13.558) - hwIo.ioThread.IoThread (13116):
Listing stacks for Python threads after IoThread crash:
Python stack for thread 3868 (watchdog.CancellableCallThread.execute(<_FuncPtr object at 0x1B983738>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 378, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 14916 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 145, in _watcher
  File "winKernel.pyc", line 315, in waitForSingleObject

Python stack for thread 11956 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 81, in hookThreadFunc

Python stack for thread 11720 (UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "UIAHandler\__init__.pyc", line 520, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 13568 (Thread-1):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer_automotive_driver\synthDrivers\vocalizerAutomotive\_vocalizer.py", line 36, in run
    func(*args, **kwargs)
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer_automotive_driver\synthDrivers\vocalizerAutomotive\_vocalizer.py", line 279, in _processText2Speech
    vautoDll.vauto_ttsProcessText2Speech(instance, byref(inText))
  File "C:\Users\marco\AppData\Roaming\nvda\addons\vocalizer_automotive_driver\synthDrivers\vocalizerAutomotive\_vocalizer.py", line 96, in callback
    player.feed(data[prevByte:])
  File "nvwave.pyc", line 890, in feed

Python stack for thread 13116 (hwIo.ioThread.IoThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "hwIo\ioThread.pyc", line 208, in run
  File "watchdog.pyc", line 65, in getFormattedStacksForAllThreads

Python stack for thread 1124 (MainThread):
  File "nvda.pyw", line 406, in <module>
  File "core.pyc", line 794, in main
  File "wx\core.pyc", line 2237, in MainLoop

ERROR - core.CorePump.Notify (08:39:13.726) - MainThread (1124):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 750, in Notify
  File "braille.pyc", line 2653, in pumpAll
  File "braille.pyc", line 2414, in handlePendingCaretUpdate
  File "braille.pyc", line 2423, in _doCursorMove
  File "braille.pyc", line 2431, in scrollToCursorOrSelection
  File "braille.pyc", line 1645, in scrollTo
  File "braille.pyc", line 1686, in updateDisplay
  File "braille.pyc", line 2273, in update
  File "braille.pyc", line 2194, in _updateDisplay
  File "braille.pyc", line 2258, in _displayWithCursor
  File "braille.pyc", line 2242, in _writeCells
  File "braille.pyc", line 2247, in _writeCellsInBackground
  File "hwIo\ioThread.pyc", line 122, in queueAsApc
  File "hwIo\ioThread.pyc", line 78, in _getApc
RuntimeError: Thread is not running
```

**Comment by leonardder** [comment] 2023-05-11 19:15
@jcsteh I tried to prototype this and while this should work for APCs, overlapped completion routines are a bit more difficult as they have no parameter we can reuse. I can restore the pre 2023.2 behavior for this (i.e. store the routine on the IoBase again), but then we have the hypothetical case of Windows calling a routine that was garbage collected.

**Comment by jcsteh** [comment] 2023-05-11 23:03
Can we somehow use the overlapped pointer as a key?

**Closed** 2023-06-02 04:54 UTC
Labels: component/braille, bug/regression, p1, triaged
