### ISSUE TITLE
addon store: NVDA announces tab titles only when the focus is on tab area

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15946] opened 2023-12-20 19:02 UTC
### Steps to reproduce:
1. Open the NVDA add-on store
2. Focus any combo box, list or edit field or button with tab key
3. Press ctrl+tab to switch the tab

### Actual behavior:
NVDA reports "tab control panel"

### Expected behavior:
NVDA should report the tab title when pressing ctrl+tab, no matter where the system focus is within the dialog.

### NVDA logs, crash dumps and other attachments:
n/a
#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-30354,72e65dbd (2024.2.0.30354)

#### Windows version:
Windows 11 23 H2

#### Name and version of other software in use when reproducing the issue:
n/a

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2023.3 same behavior

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by CyrilleB79** [comment] 2023-12-20 21:47
Duplicate of #14986.

**Closed by CyrilleB79** 2023-12-20 21:47 UTC
