### ISSUE TITLE
In any dialog when screen reader is enable once after tabbing from close button focus is moving to whole slide content and reading continuously .

### ISSUE THREAD

**Issue by Amanullah0123** [nvaccess/nvda#9253] opened 2019-02-08 00:51 UTC
Repro Steps: https://www.xbox.com/en-US/xbox-one-x?xr=shellnav 
Step 1: Open NVDA from desktop.
Step2: Open the above URL in **chrome**.
Step 3: Navigate to image link and press ENTER key.
Step 4: Dialog will open and focus is on close button.
Step 5: by using TAB key/Scan mode focus is moving to whole slide content and reading the slide content continuously. 
Step 6: Verify whether by using left and right arrow keys able to access the slide buttons. 
 
Actual:
In Scan mode/tab mode once after pressing down arrow/tab key focus is moving to whole content of slides and reading the slide content continuously. Only by using right and left arrow key able to access the slide content. 
 
Expected:
In all browsers and screen readers:
In Scan mode/tab mode once after pressing down arrow/tab key focus should move directly to slide buttons and by using left and right arrow keys user should access the slide buttons. And by pressing TAB/Down arrow key focus should move to Play/Pause button.

**Comment by DrSooom** [comment] 2019-02-08 13:41
@Amanullah0123: Please list all browsers (incl. version) and your OS as well as your NVDA version where this issue occurs by completely filling out the bug report draft. Thanks.

**Comment by Amanullah0123** [comment] 2019-02-08 19:49
@DrSooom 
Chrome Version 71.0.3578.98 (Official Build) (64-bit)

NVDA version 2018.4.1

**Comment by Amanullah0123** [comment] 2019-02-21 23:35
@DrSooom Any update on this ?

**Comment by DrSooom** [comment] 2019-02-22 01:24
@Amanullah0123: I'm not a developer. CC: @michaelDCurran

**Comment by Adriani90** [comment] 2019-02-22 12:17
cc: @jcsteh

**Comment by Adriani90** [comment] 2020-05-12 15:57
For this to work correctly you have to change to focus mode with nvda+spacebar. Currently dialogs are being openend in browse mode by NVDA because this is the common request of many users worldwide. There is more background on this in issue #9135 and #4493. That being said, the described behavior here is the currently expected behavior in browse mode. Closing as invalid

**Closed by Adriani90** 2020-05-12 15:57 UTC
Labels: close/invalid
