### ISSUE TITLE
When table auto fitted to content in microsoft word is created, Microsoft word crashes when the in-process implementation is used and table navigation using UIA is not working

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#11567] opened 2020-09-06 08:22 UTC
### Steps to reproduce:
1. open the blank microsoft word document
2. create the structure like this
On page one, 
introduction, then one blank line
after that:
page two
another some title
then page tri
example table
3. table should be created as follows:
11 columns and 20 rows,
it should auto fit to content
### Actual behavior:
document creates successfully only when the uia for microsoft word is turned on, but table navigation is broken
### Expected behavior:
table navigation should work using uia, and document should open using the word im-process implementation and should be edited with the classic commands
Note that NVDA doesn't produce any logs.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
alpha-20840,c8d6ab95

#### Windows version:
windows 10 20h2 latest insider build
#### Name and version of other software in use when reproducing the issue:
nicrosoft office word 2019/365 MSO (16.0.13127.20266), 64--bit 
#### Other information about your system:
Note that when the UIA for office is turned on, it is turned on with the selective registration option.
The file which crashes the in-process implementation is attached here, too;.
[kapuscinski.docx](https://github.com/nvaccess/nvda/files/5179256/kapuscinski.docx)
Note: it is a sample file
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
not applicable

**Comment by zstanecic** [comment] 2020-09-06 10:02
Update: the crash with in-process implementation was caused by the braille extender addon 
cc @Andre9642 
The version which makes the problematic crash is the latest dev version.
Uia part of the issue needs to be resolved.

**Comment by Andre9642** [comment] 2020-09-06 16:04
Duplicate of #11457 and #11043.

**Closed** 2020-09-07 05:51 UTC
