### ISSUE TITLE
NVDA reads selected cells in a column as if the whole row is selected

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#5922] opened 2016-05-04 04:46 UTC
If you have a table in word of say 4x4 cells.  If you start in row 1, column 2, and press shift+down arrow to select row 1, column 2 and row 2, column 2, Word selects only those two cells.  NVDA reads as if you had selected row 1, columns 2, 3 and 4 and row 2 columns 1 and 2 (similar to what would happen if you pressed shift+down arrow from the middle of a line in the middle of a paragraph of regular text).

In tables, Word keeps the selection as a "rectangle", the same way Excel does (selecting cells in Excel works fine) - so having selected row 1 column 2 and gone down to include row 2, column 2, if you then press shift+right arrow, the cells row 1, column 2, row 1 column 3, row 2 column 2 and row 2 column 3 will all be selected (4 cells) but nothing in columns 1 or 4 will be selected.

Visually the correct cells are selected and any actions performed (deleting or reformatting cells or contents) affects the correct cells.

Tested in Word 2016.

**Comment by PratikP1** [comment] 2016-05-04 10:57
I can verify this. This behavior has been tested in Office 2013 as well.

**Comment by jcsteh** [comment] 2016-06-07 06:14
Duplicate of #3653.

**Closed by jcsteh** 2016-06-07 06:14 UTC
Labels: duplicate
