### ISSUE TITLE
Notepad++ sometimes crash with latest nvda

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [nvaccess/nvda#14577] opened 2023-01-22 13:48 UTC
Hello everybody. Some versions ago notepad++ crashed during starting of it with nvda. Now it was fixed partially,because sometimes notepad++ still crashed,but not constantly,as before. Whether it difficult to fix this issue? I have nvda 2022.3. Thanks.

**Comment by zstanecic** [comment] 2023-01-22 15:12
Hi,

Try with newest notepad ++ and newest NVDA 2022.4

Thanks!

 

From: Саша Козловский ***@***.***> 
Sent: Sunday, January 22, 2023 2:49 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Notepad++ sometimes crash with latest nvda (Issue #14577)

 

Hello everybody. Some versions ago notepad++ crashed during starting of it with nvda. Now it was fixed partially,because sometimes notepad++ still crashed,but not constantly,as before. Whether it difficult to fix this issue? I have nvda 2022.3. Thanks.

**Comment by CyrilleB79** [comment] 2023-01-23 08:28
Hello @AlexandrKozlovskiy 

For issues to be looked at, it's always better to use the provided templates, specifically the [bug report template](https://github.com/nvaccess/nvda/issues/new?assignees=&labels=&template=bug_report.md) in your case.
Could you please edit the initial description of this ticket to follow the template and give the requested information? E.g. Notepad++ version would be useful.

Also an additional questions: Have you installed Notepad++ plugins? If yes, do the issue also occur if they are disabled (I do not know if it is possible) or uninstalled?

**Comment by Xavier74** [comment] 2023-02-10 12:17
Good morning,

I don't know if it's related to this problem, but I had the case of notepad++ which crashes at each start by opening a file.
The problem is related to the fact that I was using the 64 bit version of notepad++ which is not supported with NVDA.
Using the 32 bit version (x86) everything is back to normal.

**Comment by josephsl** [comment] 2023-02-10 12:23
Hi, Notepad++ 64-bit version please. Thanks.

**Comment by CyrilleB79** [comment] 2023-02-10 13:28
@Xavier74 wrote:
> Good morning,
> 
> I don't know if it's related to this problem, but I had the case of notepad++ which crashes at each start by opening a file. The problem is related to the fact that I was using the 64 bit version of notepad++ which is not supported with NVDA. Using the 32 bit version (x86) everything is back to normal.

According to NVDA 2022.1's change log:
> NVDA no longer causes 64-bit versions of Notepad++ 8.3 and above to crash. (#13311)

So Notepad++ 64-bit not working with NVDA is not expected anymore.

@Xavier74, to help diagnose the issue, same questions as for @AlexandrKozlovskiy:
* NVDA version?
* Notepad++ version (and 32/64)?
* Additional Notepad++ plugins? If yes, do the issue also occur if they are disabled (I do not know if it is possible) or uninstalled?

**Comment by Xavier74** [comment] 2023-02-10 15:28
what i found this morning was this
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11629
this is related to v8.4 of notepad++

**Comment by Adriani90** [comment] 2023-02-10 21:19
It seems notepad++ 64bi is working now, I cannot reproduce any crash on Windows 11 with NvDA 2022.4. I am closing this for now, but we can reopen it in case some one reports any crashes of Notepad++ again.

**Closed by Adriani90** 2023-02-10 21:19 UTC
Labels: close/worksforme

**Comment by Adriani90** [comment] 2023-02-10 21:20
It seems the crash was related to the notepad++ addon, at least this is what I understad from the issues filled with notepad++ repository.
