### ISSUE TITLE
Crashes When Navigating to Landmarks Tab in Elements List

### ISSUE THREAD

**Issue by UCDharriman** [nvaccess/nvda#6410] opened 2016-09-27 20:09 UTC
My NVDA is crashing when I navigate to the Landmarks tab in the elements list.

As soon as I do, I get a Visual C++ Runtime Library Runtime error message (screenshot attached). NVDA remains open, but unusable, after the message and while I can request the task manager open (so I can close NVDA through it), it never actually does. All other functions are inhibited and ultimately I've had to restart the computer in order to use it.

I've tried downloading NVDA again (2016.3) and continue to experience the error.

Has anyone else encountered this? Does anyone know how to resolve it?

Text of the following image:

> Title: Microsoft Visual C++ Runtime Library
> Runtime Error!
> Program: C:\Program Files (x86)\NVDA\nvda.exe
> This application has requested the Runtime to terminate it in an  unusual way.
> Please contact the application support team for more information.

![runtime error](https://cloud.githubusercontent.com/assets/22482526/18889746/256aee98-84b3-11e6-87ac-9613c7cf569f.png)

**Comment by josephsl** [comment] 2016-09-27 20:22
Hi, can you provide us with steps to reproduce, such as which program you were in and so on? Thanks.

**Comment by UCDharriman** [comment] 2016-09-27 21:01
I first experienced the issue last week when testing an eCourse in Internet Explorer (the eCourse was created with Lectora and features SCORM LMS integration). I was then able to replicate the issue in Chrome and Firefox as well, still within the eCourse. Then, I was able to replicate the issue in all three browsers outside of the eCourse in standard websites (I believe cnn.com was one of them). This led me to believe it was an NVDA or CPU issue and not necessarily the eCourse. The process of generating the bug was otherwise the same in every test: go to test location, NVDA key + F7 to bring up the Elements List, then either right arrowing, or clicking, to the Landmarks tab, and as soon as the tab was selected, the error would occur.

I even replicated the issue in Chrome, on cnn.com, right before posting the issue.

Now, however, I'm only able to replicate the issue in the eCourse; normal websites are operating as expected in the three aforementioned browsers. The only thing that's changed, that I can think of, is that after the pre-post issue replication I mentioned above, instead of restarting the computer, as I've been forced to do after previous crashes, I was able to get NVDA to close by telling the computer I wanted to log off, at which point it started forcing quitting my open programs but as soon as it closed NVDA, I canceled the log off, and maybe somehow this changed something within NVDA..? Either that or it's the magic of an issue resolving itself as soon as you complain about it to others, so that you look like a delusional fool; technology can be a jerk like that.

Thanks!

**Comment by jcsteh** [comment] 2016-09-27 22:47
What version of Windows is this?

**Comment by UCDharriman** [comment] 2016-09-27 22:50
Windows 7 Enterprise

**Comment by feerrenrut** [comment] 2016-10-07 02:53
We should try to reproduce this on a Windows 7 machine. @jcsteh has been unable to reproduce this on Windows 10, by going to CNN.com with Firefox.

Todo:
- [ ] Reproduce the issue.
- [ ] Can we get a crash dump?
- [ ] NVDA logs, after the crash occurs?

**Comment by bhavyashah** [comment] 2016-10-08 12:43
Hi,
Although I have no specific cases to report right now, I too do
experience significant lags when I change the element type in the
Elements List dialog between links and headings, two elements whose
lists I commonly seek. I usually attribute this noticeable delay to
the number of instances of that element present on the webpage, i.e.
the more headings and links (and presumably landmarks) on a webpage,
the more unresponsive would be the Elements List dialog when changing
element types (direct proportionality).
Thanks.

On 10/7/16, Reef Turner <notifications@github.com> wrote:
> We should try to reproduce this on a Windows 7 machine. @jcsteh has been
> unable to reproduce this on Windows 10, by going to CNN.com with Firefox.
>
> Todo:
> - [ ] Reproduce the issue.
> - [ ] Can we get a crash dump?
> - [ ] NVDA logs, after the crash occurs?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6410#issuecomment-252141686


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by fernando-jose-silva** [comment] 2016-10-08 15:39
I received the same error mentioned above
C ++ Runtime Library Runtime Visual
Today to update my copy of the next version of NVDA 13616 to 13628 master.
I was not able to repeat this mistake sometimes, what seems to be some momentânio error.
Sorry if there has nothing do with the reported in the call in question, just thought worth mentioning because the same mistake has been doing a totally different of that activity.
Using windows 10.0.14393 64bits.

**Comment by feerrenrut** [comment] 2016-10-12 12:45
I can't reproduce this in Windows 7. @UCDharriman it sounds like perhaps NVDA got into a strange state, which caused the continued crashes. Without knowing a little more about how it got into this state, I think it's going to be difficult to progress this issue.

Perhaps I can try using the Lectora tool. @UCDharriman there seems to be a few different versions, can you advise which one you are using?

@bhavyashah while slowdowns are undesirable, this issue is about the "Visual C++ Runtime Library Runtime error message" showing when trying to open the elements list on certain webpages.

**Comment by UCDharriman** [comment] 2016-10-12 15:32
Unfortunately, the Lectora output I was testing on that caused these crashes was produced by a vendor and we're not sure ourselves what Lectora version was used. If/when we're able to find out, we'll post here. Thanks!

**Comment by feerrenrut** [comment] 2016-10-26 02:43
Unfortunately we won't be able to progress this issue without some more information, since we are unable to reproduce it here.

@UCDharriman if you are still able to reproduce this issue, here are some things that might help us to generate a lead on the cause of this:

- NVDA logs (with log level set to `Debug`) see the [log files and crash dumps wiki page](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for more information about this.
- The Lectora output you were testing on when the crash occured.

**Comment by bhavyashah** [comment] 2017-07-27 04:31
Just curious, shouldn't a ticket with the blocked label also be closed, or is there a difference between the two states?

**Comment by leonardder** [comment] 2017-07-27 06:13
[**@bhavyashah**](https://github.com/bhavyashah) commented on [27 jul. 2017 06:31 CEST](https://github.com/nvaccess/nvda/issues/6410#issuecomment-318255739 "2017-07-27T04:31:45Z - Replied by Github Reply Comments"):
> Just curious, shouldn't a ticket with the blocked label also be closed, or is there a difference between the two states?

Yes, a blocked ticket either requires more information as above but isn't considered to be invalid. You'll mostly see blocked for tickets depending on other tickets.

@UCDharriman: Would you be able to answer https://github.com/nvaccess/nvda/issues/6410#issuecomment-256235214

**Comment by UCDharriman** [comment] 2017-07-27 15:39
Unfortunately I'm not currently able to reproduce the issue; access to the Lectora output will be restricted for the next month or so while its host platform undergoes an upgrade. Feel free to treat the ticket as needed. Thank you.

**Comment by ehollig** [comment] 2017-11-06 04:08
@UCDharriman, are you still able to reproduce this issue? If so, can you provide the information requested in https://github.com/nvaccess/nvda/issues/6410#issuecomment-256235214

**Comment by ehollig** [comment] 2018-08-15 23:32
As we have not been able to hear from the original author regarding this issue, and no one has been able to reproduce, I am going to close this issue.
@UCDharriman, if you still can reproduce this issue, please provide a test case where we can replicate the issue, along with the other things mentioned and requested in https://github.com/nvaccess/nvda/issues/6410#issuecomment-256235214

**Closed by ehollig** 2018-08-15 23:32 UTC
Labels: blocked, crash
