### ISSUE TITLE
When opening a new page using Firefox, NVDA often says the word "unknown" after speaking the title of the page

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4882] opened 2015-02-04 16:08 UTC
**Reported by dgoldfield on 2015-02-04 16:08**
When using the latest NVDA master with Firefox, NVDA says the word "unknown" after speaking the title of the page. This does not occur in all cases. As an example, when going to www.nvaccess.org, I do not hear NVDA say the word "unknown." One page where I hear this is www.loc.gov.

**Comment by ehollig** [comment] 2017-08-01 01:11
I can not reproduce this using NVDA Master and Firefox 54. Can anyone else reproduce this?

**Comment by bhavyashah** [comment] 2017-08-01 03:14
Neither can I. This is too old an issue and it is quite unlikely that this bug still stands. Unless we receive any feedback stating otherwise, within, let's say the next week or two, I would suggest closing. @feerrenrut

**Comment by Brian1Gaff** [comment] 2017-08-01 08:22
Well this effect can occur momentarily on slow machines in a similar way to 
repeated blank or some other random spoken text in Firefox as it is 
notorious, especially the first time it runs in a session for causing nvda 
watchdog operation and lots of apparent messing about. It is what it is and 
seems not to cause any issues. Far more likely seems to be the  tendency for 
Firefox to not go into its say all or even have the window in focus 
sometimes and it needs the alt pressing and escape to get it to focus. This 
is a very old one and I suspect that this, too is due to the length or time 
and  processor use by Firefox at those times.

It is usually fine on subsequent pages and sessions.


bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by Adriani90** [comment] 2018-07-28 08:32
@jcsteh I think this is not reproducible in FF 60 or higher. #8389.

**Comment by netblue44** [comment] 2018-07-30 15:22
Yes it is, I Reproduce it everry day.

**Comment by netblue44** [comment] 2018-08-06 15:11
I have tried all of what yousay and the problem still exist

I can reproduce this menny times a day on all versions of windows

**Comment by feerrenrut** [comment] 2018-08-07 05:00
@netblue44 Could you please attach the information to this issue. This will help us to reproduce the issue on our own system.

1. Start NVDA with add-ons disabled.
1. Select Debug level logging from the General settings dialog
1. Start Firefox in safe-mode:
    1. Push Windows Key + R to open a run dialog
    1. Type `firefox -safe-mode` and press enter
1. Confirm that you hear "unknown"
1. Press Ctrl + Print Scn to take a screenshot of Firefox (we will save it in a moment)
1. Press NVDA + F1 to open the log viewer.
1. Press `ctrl+s` to save the log file. Put it somewhere you can find.
1. Save the screenshot from the clipboard:
    1. Open paint.exe and push `ctrl+v`. 
    1. Press `ctrl+s` to save this file. Put it somewhere you can find.
1. Attach the screenshot to this issue.
1. Attach the NVDA log to this issue.

**Comment by Adriani90** [comment] 2019-05-03 18:53
We didn't get any updates from the initial author if he tried our suggestions or not. I am closing this one for now given that the discussion continues on other issues more or less related to this like #8389. If you still have this problem after trying our suggestions, plese comment on this issue and we can reopen the discussion. Thanks!

**Closed by Adriani90** 2019-05-03 18:54 UTC
Labels: bug
