### ISSUE TITLE
Error triggered on Google docs

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#8150] opened 2018-04-09 02:27 UTC
I don't know what is causing this in next, but this triggers in braille mode in firefox in docs. If it is harmless, I'd appriciate if we could squelch the tone somehow, so users of master and next providing valuable feedback don't hear the error ding over and over when typing.
1. Type text in google docs with braille mode enabled. Every few chars, this error occurs.

Input: kb(desktop):t
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:19.809):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:19.868):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (20:24:19.881):
error executing event: caret on <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x070CB0D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 175, in event_caret
  File "editableText.pyc", line 299, in detectPossibleSelectionChange
  File "editableText.pyc", line 306, in _updateSelectionAnchor
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 626, in compareEndPoints
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 600, in _getAncestors
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 172, in _getEmbedding
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 168, in _makeRawTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 36, in _getRawTextInfo
AttributeError: 'NoneType' object has no attribute 'role'
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:19.940):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:19.950):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:19.960):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (20:24:19.979):
Input: kb(desktop):e
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:20.023):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:20.069):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (20:24:20.079):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (20:24:20.105):
Input: kb(desktop):space

**Comment by Adriani90** [comment] 2019-05-06 17:18
Closing as duplicate of #8861

**Closed by Adriani90** 2019-05-06 17:18 UTC
Labels: GoogleWork, duplicate
