### ISSUE TITLE
Error when trying to read mail in Windows 10 Mail

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#5775] opened 2016-02-23 15:45 UTC
When attempting to read mail in Windows 10 Mail in current Win 10 Insider Preview 14267, latest Mail and Calendar update from Windows Store, opening an e-mail first yields no speech. When I then try to navigate down from the document to the children using Navigator, I get this error:

ERROR - scriptHandler.executeScript (16:32:37):
error executing script: <bound method GlobalCommands.script_navigatorObject_firstChild of <globalCommands.GlobalCommands object at 0x04D37950>> with gesture u'shift+NVDA+down arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "globalCommands.pyc", line 875, in script_navigatorObject_firstChild
  File "speech.pyc", line 371, in speakObject
  File "speech.pyc", line 675, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 249, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 120, in _getControlFieldForObject
  File "NVDAObjects\__init__.pyc", line 926, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 78, in __init__
LookupError

The developer info for the element I land on is:

INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (16:32:42):
Developer info for navigator object:
name: u'Message'
role: ROLE_EDITABLETEXT
states: STATE_FOCUSABLE, STATE_READONLY
isFocusable: True
hasFocus: 0
Python object: <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x05169C30>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA'>, <class 'NVDAObjects.behaviors.EditableTextWithoutAutoSelectDetection'>, <class 'editableText.EditableTextWithoutAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (895, 210, 1205, 535)
value: None
appModule: <'appModuleHandler' (appName u'hxmail', process ID 6348) at address 5169650>
appModule.productName: u'Microsoft Office 2016'
appModule.productVersion: u'16.0.6568.4612'
TextInfo: <class 'NVDAObjects.UIA.UIATextInfo'>
windowHandle: 197636
windowClassName: u'Windows.UI.Core.CoreWindow'
windowControlID: 0
windowStyle: 1409286144
windowThreadID: 2224
windowText: u'Mail'
displayText: u''
UIAElement: <POINTER(IUIAutomationElement) ptr=0xb197008 at 4dea2b0>
UIA automationID: UIA_AutomationId_Word_Content_Page_1
UIA frameworkID: 
UIA runtimeID: (42, 197636, 2, 262503116, 3)
UIA providerDescription: [pid:6348,hwnd:0x0 Main(parent link):Unidentified Provider (unmanaged:MSOIMM.dll)]
UIA className: 

Latest Next snapshot as of February 23, 2016.

**Comment by josephsl** [comment] 2016-02-23 17:45
Hi, have you tried review cursor instead? Sometimes review cursor keys do work (in this case, more so). Thanks.

**Comment by dreinn** [comment] 2016-02-24 08:30
Hello,
This is same of my ticket, at:
https://github.com/nvaccess/nvda/issues/5635

The review cursor doesn't work, the only way to read is pressing Shift 
key and down arrow. So selecting text, NVDA is able to report it, but it 
is unconfortable.
Anyway, thank you for your report, I hope developers  will pay attention 
to this issue!

Il 23/02/2016 18:45, josephsl ha scritto:

**Comment by josephsl** [comment] 2016-07-05 06:49
Hi,

Duplicate of #5635 - Mick is investigating. Thanks.

**Closed by josephsl** 2016-07-05 06:49 UTC
