### ISSUE TITLE
Zoom: No character announced in edit field for entering meeting ID 

### ISSUE THREAD

**Issue by DGartmann** [nvaccess/nvda#10917] opened 2020-03-30 09:39 UTC
### Steps to reproduce:

Open the Zoom Windows client
Make sure the "Home" tab is selected.
Tab to the "Join" button and hit Enter to activate.
You are in the field to enter the meeting ID.
Type a digit or 2 and move over them using the Left and Right arrow keys.

### Actual behavior:
No character is announced.

### Expected behavior:
Each character should be spoken as the cursor moves over it.

#### NVDA installed/portable/running from source:
Installed.

#### NVDA version:
2019.3.1

#### Windows version:
Windows10
Using Windows version 10.0.18363 workstation

#### Name and version of other software in use when reproducing the issue:
Zoom version 4.6.8.

#### Other information about your system:

From the log when the cursor is in the edit field for entering meeting ID:
```
Developer info for navigator object:
name: 'Please enter your Meeting ID or Personal Link Name'
role: ROLE_EDITABLETEXT
roleText: None
states: STATE_FOCUSED
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x09034CD0>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 
'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 
'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, 
<class 'baseObject.AutoPropertyObject'>, <class 'object'>)
description: None
location: RectLTWH(left=711, top=408, width=498, height=72)
value: 'Enter meeting ID or personal link name'
appModule: <'zoom' (appName 'zoom', process ID 14876) at address 826b810>
appModule.productName: 'Zoom'
appModule.productVersion: '4,6,19178,0323'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 330582
windowClassName: 'zWaitHostWndClass'
windowControlID: 0
windowStyle: -1765277696
extendedWindowStyle: 264
windowThreadID: 15508
windowText: 'Zoom'
displayText: 'Enter meeting ID or personal link name'
IAccessibleObject: <POINTER(IAccessible) ptr=0x5e1e5b0 at 13268f0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=330582, objectID=102031168, 
childID=0
IAccessible accName: 'Please enter your Meeting ID or Personal Link Name'
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_VALID (4)
IAccessible accDescription: exception: (-2147467263, 'Ikke implementeret', 
(None, None, None, 0, None))
IAccessible accValue: 'Enter meeting ID or personal link name'
```

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes.

**Comment by stickbear2015** [comment] 2020-03-31 04:54
This also appears in the search edit field as well.
I switched to the beta, with the same results, and same with the build from source.

**Comment by DGartmann** [comment] 2020-05-01 07:42
Issue still present in the 5.0.1 version of the Zoom client.

**Comment by DGartmann** [comment] 2020-05-01 07:45
Sorry. Closed by mistake.

**Comment by feerrenrut** [comment] 2020-05-01 11:53
Have you tried contacting Zoom support for this issue?

**Comment by DGartmann** [comment] 2020-05-01 14:20
No. I'm not sure what to tell them because Jaws 2020, as far as I can tell, works in these edit fields.

**Comment by Adriani90** [comment] 2020-05-03 13:01
This is a duplicate of #8804 which talks about more edit fields in Zoom. It might be a displaymodel specific issue.
I am closing this as duplicate.

**Closed by Adriani90** 2020-05-03 13:01 UTC
Labels: close/duplicate
