### ISSUE TITLE
SAPI 5 Loquendo 6 voices not properly handling certain pauses

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#10665] opened 2020-01-08 18:15 UTC
Reported by an user from the Spanish-speaking community. The reproducibility hasn't been tested yet since we don't have Loquendo 6 nor W7.
### Steps to reproduce:

1. Change to the voice Loquendo 6 Jorge, via SAPI5 (anyway, the issue may exist with another Loquendo 6 voices too). This doesn't happen with another SAPI voices neither with eSpeak.
2. Go to the desktop, open the NVDA installer or some web browser, for example.

### Actual behavior:

NVDA only reports the first piece of information: "Escritorio lista", "Mozilla Firefox"... In case of the NVDA installer, it doesn't automatically read the first line of the license agreement.

### Expected behavior:

The syntesizer should read all the information that is being send by NVDA. From each of the following line pairs, only the first line is read.
Pair 1:
IO - speech.speak (11:04:05.347) - MainThread (3096):
Speaking ['FolderView', 'lista']
IO - speech.speak (11:04:05.389) - MainThread (3096):
Speaking ['Papelera de reciclaje', '1 de 11']

Pair 2:
IO - speech.speak (11:04:13.539) - MainThread (3096):
Speaking ['Mostrar escritorio', 'botón']
IO - speech.speak (11:04:13.970) - MainThread (3096):
Speaking ['Mostrar escritorio', 'consejo']

Pair 3:
IO - speech.speak (11:04:16.018) - MainThread (3096):
Speaking ['NotificationChevron', 'botón']
IO - speech.speak (11:04:16.473) - MainThread (3096):
Speaking ['Mostrar iconos ocultos', 'consejo']

The user has tried with another TTS software and pauses outside of the text (introduced by the software) cause the same behavior that the described here.
I attach the first part of the log (until NVDA initialized) to give a summary of the testing environment and NVDA configuration.
[nvda.log](https://github.com/nvaccess/nvda/files/4036663/nvda.log)

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-19460,d7229eff (Python 3)

#### Windows version:

Windows 7 (6.1.7601 service pack 1)

#### Name and version of other software in use when reproducing the issue:

N/A

#### Other information about your system:

No addons.

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

This problem happens with development releases powered by Python 3. In previous versions the issue isn't reproducible.

**Comment by zstanecic** [comment] 2020-01-08 18:45
No,

Voice doesn’t know how to send indexes to NVDA properly, i.e, it newer gets the answer that NVDA received the index.

The problems of this sort started with the speech refactor change.

Not only loquendo has a problem of this sort, but there are tons of old synthesizers, which are now discontinued. 

So, we even cannot get in touch with the respective manufacturers, because of the following: 

a.	Manufacturer, the company has been sold to another company,
b.	Manufacturer doesn’t produce the synth anymore and discontinues it in favor of other product. 

The problem with loquendo is stated in the point a)

Because of this, I would suggest closing this as wontfix. 

Yep, we’ve get to the point where this breaking change, i.e speech refactor brokes old synths in a such way, that these are completely unusable, even with say all.

It means, that we can even frely drop support for sapi4, as od synthesizers powered by this protocol work buggy.

The problems we have also with the polish Neurosoft syntalk speech synthesizers.

Loquendo and Neurosoft syntalk 1.6 ar both synthesizer classified as abandonware.

Best,

Zvonimir

**Comment by zstanecic** [comment] 2020-01-08 18:50
Adriano Barbieri reported this on the NVDA add-ons mailing list in some of the alpha snaps.
@josephsl 
Your thoughts?
@feerrenrut 
your opinion?

**Comment by zstanecic** [comment] 2020-01-08 18:53
This is the serious and critical issue, because many people will refuse to upgrade to the new release just because of their favorite synth is not working..

**Comment by Brian1Gaff** [comment] 2020-01-09 08:23
I was just thinking that. People are passionate about the voice they can 
work with. I could never use Eloquence, yet others swear by it, and for 
quick and dirty navigation even on windows 10, I much prefer Espeak Quincy 
to anything else. Its just the way my ears work. Now if i am reading a 
document, many voices are preferable to Espeak, but navigation is not 
reading.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by feerrenrut** [comment] 2020-02-03 09:25
If I understand this issue correctly, it seems that the synthesizer needs to be updated. Please contact the synthesizer manufacturer and ask them to fix the issue or donate the code so that someone else can. Closing as won't fix.

**Closed by feerrenrut** 2020-02-03 09:25 UTC

**Comment by lukaszgo1** [comment] 2020-02-03 11:43
@feerrenrut The synthesizer in question is a SAPI 5 one, and given the fact that it works correctly in 2019.2.1 according to the OP the problem is likely on the  NVDA side. As SAPI 5 is a standard it would be good to support it completely.

**Comment by zstanecic** [comment] 2020-02-03 12:27
Hi Łukasz,

Well, maybe you are righ.

Please note that polish syntalk speech synthesizer is also not compatible with the neewst standard, although sapi4 interface is completely implemented.

Sorry, but loquendo is no more produced. NVDA can be problematic, bit it’s not the case.

**Comment by lukaszgo1** [comment] 2020-02-03 12:38
No, it is not. In the pr implementing speech refactor  @michaelDCurran mentioned that some problems with SAPI 4 are expected due to its age. SAPI 5 is, or at least in my opinion should be different story altogether.

**Comment by zstanecic** [comment] 2020-02-03 12:44
yes, but now the problem of loquendo is not a problem of NVDa.

Speech synthesizer wendors need to patch their speech synthesizers.

The good example of these are Acapela and Codefactory.

In the statistical sense, we may loose the users of NVDA especially from Poland, because of the NVDA 2019.3 not upporting syntalk properly.

For some, syntalk is good, because it doesn’t produce rubbish in the output

For the further discussion,

Please contact me privately on my e-mail

In polish

Zvonimirek222@yandex.com
