### ISSUE TITLE
impossible to download last nvda alpha 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13280] opened 2022-01-25 20:12 UTC
### Steps to reproduce:
in nvda's help menu click the update function, after pressing the skip button on the donation request a message is displayed
Error downloading update.
if you try to download from the page the error is displayed
{"message":"Artifact download limit (1024 MB/day) exceeded."} 
### Actual behavior:
impossible to download last alpha 
### Expected behavior:
possible to download the latest alpha nvda 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-24501,b45926cd

#### Windows version:
windows 11 22000.466
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Brian1Gaff** [comment] 2022-01-26 08:18
Confirmed.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "fernando-jose-silva" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, January 25, 2022 8:13 PM
Subject: [nvaccess/nvda] impossible to download last nvda alpha (Issue 
#13280)

**Comment by Qchristensen** [comment] 2022-01-26 21:52
We are aware of the issue and are investigating.
I'm going to close this as a duplicate of #13281.

**Closed by Qchristensen** 2022-01-26 21:52 UTC
