### ISSUE TITLE
Disabling "automatic say all on page load" doesn't prevent nvda from talking and talking and talking

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4999] opened 2015-03-26 08:03 UTC
**Reported by jmuheim on 2015-03-26 08:03**
When I disable "automatic say all on page load", nvda still reads everything on the page.

[[Image(http://i.snag.gy/YyLAZ.jpg)]]

Is this a bug?

**Comment by ehollig** [comment] 2017-07-10 19:43
I am not able to replicate this in Internet Explorer, Firefox, or Chrome using master-14172,0fb961db.

**Comment by jcsteh** [comment] 2017-07-10 23:31
Closing as worksforme, given that I and two others can't reproduce this. Note that there are few possibilities to consider here:

1. If mouse tracking is enabled, NVDA will read whatever is under the mouse. That could be quite a lot of text if the mouse is moved a lot.
2. It's possible that auto say all was enabled in a configuration profile triggered for the browser. If the Browse Mode settings dialog was opened while another application had focus, it would reflect the settings for that app instead. There's a "Temporarily disable all triggers" option in the Configuration Profiles dialog that might help in testing for this.
3. An add-on might have some impact here. Restarting with add-ons disabled would help to determine this.

**Closed by jcsteh** 2017-07-10 23:31 UTC
Labels: Browse mode, bug
