### ISSUE TITLE
Replace Private Use codepoints in Word by plain text

### ISSUE THREAD

**Issue by dkager** [nvaccess/nvda#6706] opened 2017-01-06 19:43 UTC
These often show up as bullets in lists, e.g. [U+F0B7](https://codepoints.net/U+F0B7?lang=en). Because these fall in a Private Use Area they cannot be added to a braille table.
Maybe the app module can replace them by a plain equivalent, e.g. an asterisk for this bullet.

**Comment by jcsteh** [comment] 2017-01-08 22:37
Duplicate of #5267. There's actually a PR for this (#5508) which maps the common ones to Unicode. The contributor of this patch is no longer involved, so someone else would need to make any required amendments.

**Closed by jcsteh** 2017-01-08 22:37 UTC
Labels: duplicate
