### ISSUE TITLE
Radio button groups within table - Chrome 131 issue 

### ISSUE THREAD

**Issue by Ivanho92** [nvaccess/nvda#17535] opened 2024-12-16 09:05 UTC
### Steps to reproduce:
1. Go to following codepen for bug reproduction: https://codepen.io/ivanho92/full/zxONrNB
2. Open NVDA and focus on the top right radio button
![image](https://github.com/user-attachments/assets/ab752f5d-1024-4952-ba41-bc0410954119)

### Actual behavior:
NVDA with Chrome (131.0.6778.140) reads the following:
"_Aria Label B  row 2  Actions  column 4
Aria Label B  radio button  (un)checked  **1 of 1**_"

### Expected behavior:
**1 of 1** is incorrect, as the button is part of a radiogroup. Note that NVDA with Firefox (132.0.2) is read correctly:
"_row 2  Actions  column 4
Aria Label B  radio button  (un)checked  **2 of 2**_"

#### NVDA installed from source:
https://www.nvaccess.org/download/

#### NVDA version:
2024.1.0.31547

#### Windows version:
Windows 10 Pro - version 22H2

#### Name and version of other software in use when reproducing the issue:
- Chrome 131.0.6778.140 (NOK)
- Firefox 132.0.2 (OK)

**Comment by SaschaCowley** [comment] 2024-12-16 22:51
Duplicate of #113970

**Closed by SaschaCowley** 2024-12-16 22:51 UTC
