### ISSUE TITLE
nvda does not recognize that the focus is on the firefox address bar

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8130] opened 2018-03-27 20:18 UTC
### Steps to reproduce:
Open firefox on a homepage, as an example google page.
Now using the menu bar files, press enter on the new tab option.
Now try typing a web address, as an example starting with w.
 to reproduce the issue.

### Expected behavior:
The address is not typed.

### Actual behavior:
The nvda should automatically exit navigation mode and go into focus mode, since we are in the address bar.
The nvda continues in navigation mode and does not allow the address to be entered.
The option
Autofocus mode when focus changes
is disabled.
If you try to open another tab, nvda returns to focus mode as expected.
But if you close firefox and repeat the installs the error occurs again.
I played many times, but sometimes it was not possible to reproduce the error.

### System configuration:
NVDA version:
next 14952

NVDA Installed or portable:
instaled

Other information:
> Example: Running in a VM

Windows version:
windows 7 64bits

Name and version of other software in use when reproducing the issue:
firefox 59.0.2 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no
log:
IO - inputCore.InputManager.executeGesture (16:58:03.660):
Input: kb(laptop):enter
IO - speech.speak (16:58:04.668):
Speaking [u'Barra de navega\xe7\xe3o  barra de ferramentas']
IO - speech.speak (16:58:04.668):
Speaking [u'Pesquisar ou abrir endere\xe7o  caixa de combina\xe7\xe3o  recolhido']
IO - speech.speak (16:58:04.678):
Speaking [u'edi\xe7\xe3o  possui autocompletar']
IO - speech.speak (16:58:04.688):
Speaking [u'em branco']
IO - speech.speak (16:58:05.000):
Speaking [u'Google  documento']
IO - speech.speak (16:58:05.010):
Speaking [u'Pesquisar  caixa de combina\xe7\xe3o  recolhido  possui autocompletar  edit\xe1vel']
IO - inputCore.InputManager.executeGesture (16:58:07.141):
Input: kb(laptop):w
IO - speech.speak (16:58:07.151):
Speaking [u'N\xe3o suportada neste documento']
IO - inputCore.InputManager.executeGesture (16:58:11.821):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (16:58:11.891):
Developer info for navigator object:
name: u'Pesquisar'
role: ROLE_COMBOBOX
states: STATE_COLLAPSED, STATE_OFFSCREEN, STATE_FOCUSABLE, STATE_AUTOCOMPLETE, STATE_EDITABLE
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible object at 0x055FE490>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateEditorMozillaIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.mozilla.BrokenFocusedState'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (701, 402, 403, 34)
value: None
appModule: <'firefox' (appName u'firefox', process ID 2852) at address 54bd870>
appModule.productName: u'Firefox'
appModule.productVersion: u'59.0.2'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 11274622L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 382664704
windowThreadID: 7540
windowText: u'Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x6b6c744 at 560b120>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=11274622, objectID=-4, childID=-33554536
IAccessible accName: u'Pesquisar'
IAccessible accRole: ROLE_SYSTEM_COMBOBOX
IAccessible accState: STATE_SYSTEM_OFFSCREEN, STATE_SYSTEM_FLOATING, STATE_SYSTEM_HASPOPUP, STATE_SYSTEM_COLLAPSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1074861056)
IAccessible accDescription: u''
IAccessible accValue: None
IAccessible2 windowHandle: 11274622
IAccessible2 uniqueID: -33554536
IAccessible2 role: ROLE_SYSTEM_COMBOBOX
IAccessible2 states: IA2_STATE_SUPPORTS_AUTOCOMPLETION, IA2_STATE_OPAQUE, IA2_STATE_EDITABLE, IA2_STATE_SINGLE_LINE (41992)
IAccessible2 attributes: u'text-input-type:text;margin-left:0px;text-align:start;text-indent:0px;autocomplete:list;id:lst-ib;tag:input;class:gsfi;xml-roles:combobox;margin-top:0px;margin-bottom:0px;margin-right:0px;display:block;explicit-name:true;'

**Comment by tapper82** [comment] 2018-04-02 05:06
Hi this bug is still in Firefox 61 on windows 10. It will only work on the second tab you open, if you open a third tab it will switch to the address bar and type as expected.

**Comment by derekriemer** [comment] 2018-04-02 23:15
I'll submit a mozilla bug for this tonight.

**Comment by ehollig** [comment] 2018-06-26 16:52
@derekriemer, did you file a Firefox bug?
@fernando-jose-silva, is this still an issue?
CC @jcsteh

**Comment by derekriemer** [comment] 2018-06-26 20:58
This is fixed now I believe. I can't reproduce now. I can't remember if I submitted one, because I think I ended up bugging internal contacts directly to have them fix something unrelated which was a different manifestation of the same bug. I'm gonna close this if noone reports that this bug is still occurring within the next week.

**Comment by jcsteh** [comment] 2018-06-26 21:06
I've never heard of this bug before, but I can reproduce it. Interestingly, this never happens when you press control+t to open a new tab, only if you use the option in the File menu. This is why I've never noticed it; I never use the File menu to do it myself. I'll file a Mozilla bug soon.

**Comment by jcsteh** [comment] 2018-06-26 21:07
Btw, the fact that control+t doesn't trigger this also means there's a simple workaround until this is fixed: use control+t to open a new tab.

**Comment by jcsteh** [comment] 2018-06-27 03:40
Fired [Mozilla bug 1471466](https://bugzilla.mozilla.org/show_bug.cgi?id=1471466).

**Comment by jcsteh** [comment] 2018-07-04 07:02
I've fixed this for Firefox 63.

**Closed by jcsteh** 2018-07-04 07:02 UTC
Labels: Firefox, needsExternalFix
