### ISSUE TITLE
Report formatting changes after the cursor isn't working

### ISSUE THREAD

**Issue by bdorer** [nvaccess/nvda#11115] opened 2020-05-05 20:55 UTC
### Steps to reproduce:
1. Open a document or create one with different font atributes, left and right justified, colors, Line spacing.
2. activate Report formatting changes after the cursor.
3. Read the text using arrows. 
### Actual behavior:
NVDA does not inform about the made changes in the document
### Expected behavior:
NVDA should tell changed font atributes and so on.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.2beta1
#### Windows version:
Windows 10 update 1909
#### Name and version of other software in use when reproducing the issue:
Microsoft 365 Word 16.0.12730.20188
#### Other information about your system:
Intel Core I5, 8 GB RAM, 
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by josephsl** [comment] 2020-05-05 20:58
Hi, it isn’t used in say all because there is no implementation for it, and the setting in question is meant to announce font changes as you use arrow keys to read text. Thanks.

**Comment by bhavyashah** [comment] 2020-06-20 16:27
@bdorer  After reading https://github.com/nvaccess/nvda/issues/11115#issuecomment-624302755, would you like to change your bug report into a feature request that formatting changes be reported during say all, or do you think arrowing around meets your needs?

**Comment by bdorer** [comment] 2020-06-21 11:07
ok, after another round of testing it isn't working the other way. I updated the description accordingly.

**Comment by CyrilleB79** [comment] 2023-07-24 14:49
@bdorer, I am not sure to understand.

Have you enabled the corresponding options in document formatting settings (e.g. Chaaracter attributes, Line spacing, etc.)?
* If yes please indicate it more clearly in your description
* If no, it may be that you have not understood what the option "Report formatting changes after the cursor" does. Have you read the corresponding paragraph in the User Guide?

Looking at the option's label, I agree that it's not clear at all. The User Guide gives a little more explanations, but I think that we could do better.

Waiting for your answer to know if GUI and U ser Guide rephrasing could solve the current issue.

**Comment by Adriani90** [comment] 2024-07-03 11:53
I cannot reproduce with the settings in the GUI enabled accordingly. Regarding user guide improvement, please open a new issue about that. i am closing this as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-07-03 11:53 UTC
Labels: close/worksforme
