### ISSUE TITLE
Tables in Word: Extra column reported during Say all with UIA disabled

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#13663] opened 2022-05-04 04:43 UTC
### Steps to reproduce:

1. Ensure NVDA is not set to use UI Automation in Word (or set to "Default (Where suitable)" in 2022.1 betas)
2. Open a blank Word document.
3. Insert a table, say 4 columns by 2 rows.
4. Populate the table with data.
5. Move to the top of the document and read with say all.
6. Enable NVDA to use UI Automatin in Word
7. Repeat step t - move to top of document and read with say all.

### Actual behavior:

With UIA disabled:

When NVDA encounters the table, it correctly identifies "Table with two rows and four columns".  When reading, NVDA will announce an extra column:
Column 3 text, column 4 more text, column 5, row 2, column 1...

With UIA enabled, NVDA reads as expected.

### Expected behavior:

Column 5 should not be reported

#### NVDA version:

NVDA 2022.1 Beta 4 Installed
Also tried with NVDA 2021.3.5.

#### Windows version:

Windows 10 (64-bit) Version: 21H2 (2009), Build: 19044.1645 

#### Name and version of other software in use when reproducing the issue:

Office 365 (64-bit) Version: 16.0.15128.20140 

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2021.3.5.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment] 2022-05-05 05:38
@michaelDCurran Could you assess this for priority please?

This is not a regression, and affects the object model in word (which NVDA is moving away from). I'd suggest P3.

**Comment by Brian1Gaff** [comment] 2022-05-05 07:21
I guess when the last version of Office accepted by windows 10 that used 
object model is no longer supported then you could ignore it then.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by michaelDCurran** [comment] 2022-05-06 03:04
I agree. I have given it p3.

**Comment by CyrilleB79** [comment] 2022-07-13 10:01
Seems a duplicate of #4876. The description of this one is better but the scope of #4876 is broader (even if the root issue is the same).

**Comment by Adriani90** [comment] 2023-04-03 12:09
Closing this one as duplicate of #4876.

**Closed by Adriani90** 2023-04-03 12:09 UTC
Labels: close/duplicate, app/microsoft-office, p3, triaged
