### ISSUE TITLE
Improper initialization of UIA during NVDA start

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#13347] opened 2022-02-16 14:54 UTC
### Steps to reproduce:
1. Start or restart NVDA.
2. See the log.
INFO - __main__ (15:43:24.276) - MainThread (21816):
Starting NVDA version alpha-24688,af3b8440
INFO - core.main (15:43:24.339) - MainThread (21816):
Config dir: C:\Users\ninos\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (15:43:24.340) - MainThread (21816):
Loading config: C:\Users\ninos\AppData\Roaming\nvda\nvda.ini
INFO - core.main (15:43:24.427) - MainThread (21816):
Windows version: Windows 11 21H2 (10.0.22000) workstation
INFO - core.main (15:43:24.427) - MainThread (21816):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (15:43:24.428) - MainThread (21816):
Using comtypes version 1.1.8
INFO - core.main (15:43:24.428) - MainThread (21816):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDrivers.espeak.SynthDriver.__init__ (15:43:24.737) - MainThread (21816):
Using eSpeak NG version 1.51-dev
INFO - synthDriverHandler.setSynth (15:43:24.818) - MainThread (21816):
Loaded synthDriver espeak
INFO - core.main (15:43:24.818) - MainThread (21816):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (15:43:24.820) - MainThread (21816):
Braille input initialized
INFO - braille.initialize (15:43:24.821) - MainThread (21816):
Using liblouis version 3.20.0
INFO - braille.initialize (15:43:24.824) - MainThread (21816):
Using pySerial version 3.5
INFO - braille.BrailleHandler.setDisplayByName (15:43:24.834) - MainThread (21816):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - core.main (15:43:25.054) - MainThread (21816):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (15:43:25.167) - UIAHandler.UIAHandler.MTAThread (21952):
UIAutomation: IUIAutomation6
ERROR - NVDAHelperLocal (15:43:25.309) - UIAHandler.UIAHandler.MTAThread (21952):
Thread 21952, build\x86\UIARemote\UIARemote.cpp, initialize, 141:
Error activating activation context for C:\Program Files (x86)\NVDA\lib\alpha-24688,af3b8440\Microsoft.UI.UIAutomation.dll.manifest

INFO - core.main (15:43:25.394) - MainThread (21816):
NVDA initialized

### Actual behavior:
NVDA starts with error above, which also has the impact when navigating word documents.
### Expected behavior:
No errors.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
Starting NVDA version alpha-24688,af3b8440
NVDA version alpha-24688,af3b8440

#### Windows version:
Windows 11 21H2 (10.0.22000) workstation

#### Name and version of other software in use when reproducing the issue:
Microsoft word version 16.0.14827.20186 - 64 bit
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, previous version of alpha, no problem in previous version whatsoever
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
not applicable

**Comment by seanbudd** [comment] 2022-02-16 22:15
Possibly caused by #13283 and fixed by #13350.
Can you confirm that this is fixed by updating to the next alpha build? The next alpha with the fix is still building, but it should be ready in 30min.

cc @michaelDCurran

**Comment by seanbudd** [comment] 2022-02-17 00:42
The latest alpha is ready: https://www.nvaccess.org/files/nvda/snapshots/alpha/nvda_snapshot_alpha-24701,80ac33a8.exe

**Comment by MarcoZehe** [comment] 2022-02-17 07:44
I can confirm that this is fixed in the latest alpha. I was also seeing that error yesterday, but after updating, it is gone.

**Comment by feerrenrut** [comment] 2022-02-17 10:22
Closing as fixed with revert (see PR https://github.com/nvaccess/nvda/pull/13350)

**Closed by feerrenrut** 2022-02-17 10:22 UTC
