### ISSUE TITLE
Reading the icon/image source path

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5159] opened 2015-06-17 18:57 UTC
**Reported by Madhava on 2015-06-17 18:57**
While i was using the NVDA version for the screen reading on our app, noticed that it's reading the icon/image's source path also. For e.g: HTTPS://FQDN/tat/static/images/bcgimg.png.

As per my understanding of the NVDA, reader should not read the icon paths. It should only read the messages displayed in the UI.

**Comment by HerinHentry** [comment] 2018-05-21 06:14
Hi,

Can we please have this in the pipeline for a fix at some point? 

Thanks,

**Comment by Adriani90** [comment] 2019-12-14 18:45
@HerinHentry could you please provide an updated test case? The links above are not working anymore. Thanks.

**Comment by HerinHentry** [comment] 2019-12-16 23:27
Looks like issue related to https://github.com/nvaccess/nvda/issues/2491. With NVDA 2019, this is not happening.

**Comment by Adriani90** [comment] 2019-12-17 20:21
@HerinHentry that issue was for Firefox. Do you mean this is not happening in Internet Explorer?

**Comment by Adriani90** [comment] 2020-01-11 21:24
Ok, it seems it works just fine now. Closing as works for me.

**Comment by d3p4n5hu** [comment] 2020-07-08 08:42
Please re-open as I'm currently facing this issue.
Version: 2020.1

Open IE, go to [https://www.nvaccess.org/](https://www.nvaccess.org/) and hover over any images.
Along with alt text, src is also being read by screen reader.

**Comment by Adriani90** [comment] 2020-07-08 22:07
Thanks for the update, testing in IE11, it seems the url is read although is not visible.

**Comment by Adriani90** [comment] 2023-03-09 00:54
This is also reproducible in Firefox and Chrome with NVDA 2022.4.

**Comment by Adriani90** [comment] 2024-04-03 19:47
Closing this as duplicate of #12521. It seems it is the same issue and it affects only Firefox. Chrome and Edge work as expected in this case.

**Closed by Adriani90** 2024-04-03 19:47 UTC
Labels: bug, close/duplicate
