### ISSUE TITLE
In excel, a certain document causes freezes

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6216] opened 2016-07-28 00:54 UTC
I will send the document to @MichaelDCurran Privately.
1. Open the excel document.
2. Navigate down to row 9. Other rows in the 40's freeze NVDA as well.
3. Expected behavior: Contents are read. 
Behavior: NVDA freezes.
This is being sent privately because I don't want the document in the public since I didn't create it, and can't figure out how to reproduce.

**Comment by feerrenrut** [comment] 2016-10-28 04:27
P1 to investigate the severity of this, and see if we can reproduce.

**Comment by derekriemer** [comment] 2016-10-28 04:56
@feerrenrut do you want me to send the document again? @michaelDCurran has it somewhere but I can send again if needed.

**Comment by michaelDCurran** [comment] 2016-10-31 06:58
I still have the file - am looking into this.

**Comment by michaelDCurran** [comment] 2016-10-31 07:26
The freeze in NVDA is due to all 16384 columns in that particular row being merged. NVDA currently has to collect all the column widths of merged cells to work out if the text goes outside the cell (overflow/crop).
However, we can improve this in two ways:
1. rather than accumulating column widths, just  get the last column's left+width.
2. We can actually remove all the gdi code by simply comparing width-columnWidth. If it is greater than 0, then the cell is overflowed/cropped.

**Comment by michaelDCurran** [comment] 2016-10-31 07:56
No, scrap number 2. width always seems to be at least 48.0 no matter how much text is there.

**Closed** 2017-01-09 04:33 UTC
Labels: p1
