### ISSUE TITLE
braille tethered issue, review or focus

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5694] opened 2016-01-21 11:45 UTC
Hello, I'm Hyongsop Kim in Korea.
As you know, braille is tethered to focus or review.
It is not possible to tether both review and focus.
I think many screen reader users want to use NVDA without voice, with braille display only.
But since both navigate with focus and review mode are not supported with braille display, they can't use only braille display, not voice.
So please consider braille tethered to both focus and review cursor.
Then power braille users can use NVDA with just braille display.

Thank you.

**Comment by jcsteh** [comment] 2016-01-21 22:13
Tethering doesn't mean you can't use NVDA with braille only. You just switch between them as you wish.

It's not possible to tether to focus and review at the same time, since the two cursors could be in entirely different places. If you mean automatic switching, that is difficult to define, since NVDA needs to know which cursor to move when you move with the braille display. It's worth noting that even speech users do not ever get both at the same time. They use two entirely different sets of commands, which means there's no ambiguity as to which cursor they want to deal with. That is not the case with braille, hence tethering.

In any case, this is a duplicate of #2385, where there is more discussion.

**Closed by jcsteh** 2016-01-21 22:13 UTC
Labels: duplicate
