### ISSUE TITLE
IE11 tabindex="-1" announces "Edit" on non-editable elements

### ISSUE THREAD

**Issue by michelhebert** [nvaccess/nvda#6639] opened 2016-12-13 21:59 UTC
In IE11 (firefox does not have this issue), I'm running into an issue where elements with tabindex="-1" are announced as "Edit".  The reason I use tabindex="-1" is to programmatically focus an element (such as skip links).

I searched the issues list, and did not find this already submitted.

Thanks!

**Comment by feerrenrut** [comment] 2016-12-15 09:21
Thanks for reporting this @michelhebert . I haven't been able to reproduce this. Could you provide a minimal standalone html file that reproduces this issue?

**Comment by michelhebert** [comment] 2016-12-15 18:13
Sure. I should have provided an example from the beginning.

Test examples: https://jsfiddle.net/63Lrk2bv/7/
NVDA version: 2016.3
IE version: 11 (11.0.9600.18524)

The tests are set up to test focusing elements with tabindex="-1" programmatically on:
- `<h1>`
- `<div>` with `role="heading"` and `aria-level="2"`
- `<div>` with no semantics (no ARIA attributes to define it)
- `<p>`
- `<div>` with `role="dialog"` (which also has `aria-labelledby` and `aria-describedby`)

The tests have setTimeout on them so each scenario is read with enough time to hear a pause between each.

What I see is that NVDA only says "edit" when it encounters semantic HTML, _but not_ when it's a `<div>`/`<span>`, or, if ARIA is used to define the semantics.

FYI: As an unrelated note, the div with `role="dialog"` is repeating the contents with/without `aria-describedby` and `aria-labelledby`

Thanks!

**Comment by feerrenrut** [comment] 2016-12-16 09:13
Thanks @michelhebert for the example. While this isn't ideal behaviour, the severity for the end user is low. I think we need to investigate a little in order to get a feel for the cost to fix this. I'll give this a priority 2 to this then re-prioritise if appropriate.

**Comment by michelhebert** [comment] 2017-01-23 01:00
Thanks. I thought this was severe enough for a blind user. Incorrectly announcing an element as editable, would make all "editable" elements questionable right?

I suppose on the scale of high to low, there may be more critical issues to address. Thanks for looking into this!

Cheers.

**Comment by michelhebert** [comment] 2017-04-11 17:48
Update.

I see that any "tabindex" value will trigger the same issue.

Thanks.

**Comment by michelhebert** [comment] 2018-01-24 15:31
@feerrenrut  Any chance this is still under the radar or considered for a release in the near future?

Cheers.

**Comment by feerrenrut** [comment] 2018-01-30 05:29
@michelhebert In general bugs that affect IE11 are lower priority, based on the number of users. Feel free to make a case for this being higher priority but be aware there are many issues that need attention.

I think this issue is related to #7936

**Comment by michelhebert** [comment] 2018-09-20 20:41
> @michelhebert In general bugs that affect IE11 are lower priority, based on the number of users. Feel free to make a case for this being higher priority but be aware there are many issues that need attention.
> 
> I think this issue is related to #7936

Yes, that is indeed the same issue. Thanks.

**Comment by Adriani90** [comment] 2019-03-25 22:20
Closing as duplicate of #7936.

**Closed by Adriani90** 2019-03-25 22:20 UTC
Labels: Internet Explorer, duplicate, p2
