### ISSUE TITLE
NVDA suddenly stops reading the content when pressing the Home/End keys and the left/right arrows.

### ISSUE THREAD

**Issue by tarikhadzirovicofficial** [nvaccess/nvda#17002] opened 2024-08-13 18:38 UTC
I finally managed to catch and record the issue that has been happening to me countless times. The problem occurs very rarely, and I don't know what causes it or how to reproduce it. While I was playing around with artificial intelligence, I noticed the problem and immediately displayed it. I also attached a log file that will hopefully be helpful.
So, the specific thing that happens is that NVDA suddenly stops reading the content displayed when pressing keys like Home and End, the left and right arrows, as well as Control+Home and Control+End, and Control+left arrow and Control+right arrow. I went online to the website [benchmark.rs](https://benchmark.rs/) (a media outlet dedicated to reporting news from the world of technology).
No matter which of the above keys or key combinations I press, NVDA says nothing, absolutely nothing. The only time NVDA reads the text is when using the up and down arrows, as well as Control+Shift+left arrow and Control+Shift+right arrow. I hope all these things I'm describing are visible in the log file.

### Actual behavior:
NVDA speaks nothing.
### Expected behavior:
NVDA should speak the text as usual.
### NVDA logs, crash dumps and other attachments:
[nvda-old.log](https://github.com/user-attachments/files/16604001/nvda-old.log)
#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
NVDA 2024.3rc1
#### Windows version:
Windows 11 23H2 (AMD64) 22631.3958
#### Name and version of other software in use when reproducing the issue:
Any.
In this case: Brave Browser 127.1.68.137

#### Does the issue still occur after restarting your computer?
The problem is temporarily solved, but rarely it occurs again.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. I have been using NVDA since version 2022.1, and in each of those versions, the problem occurred at least once.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by SaschaCowley** [comment] 2024-08-19 05:51
Can you please provide a debug log of the problem occurring with add-ons disabled?

**Comment by tarikhadzirovicofficial** [comment] 2024-08-22 13:30
Hi @SaschaCowley!
I'm sorry for the delayed response.
Unfortunately, since I don't know what's causing the problem and because it occurs rarely, I'm not sure I can fulfill your request, as most of my add-ons are of great importance to me.
However, I will try on another computer with the same version of Windows, the same NVDA version, and the same NVDA configuration (with add-ons disabled). I will do what I usually do when the problem occurs.
If I succeed, I will get back to you with the details.

**Comment by Adriani90** [comment] 2024-08-22 17:43
@tarikhadzirovicofficial it is understandable that you need add-ons, but if you restart NVDA with disabled add-ons, nvda+q, and then choose "restart with disabled add-ons", then reproduce the issue, this is not a big deal. When you restart NVDA again, all your add-ons will be automatically enabled as before.

**Comment by Adriani90** [comment] 2024-11-15 23:38
Since we don't have the vonfirmation that this occurs with add-ons disabled, I am closing for now. Please provide the information requested and we can continue investigating.

**Closed by Adriani90** 2024-11-15 23:38 UTC
Labels: blocked/needs-info, needs-triage
