### ISSUE TITLE
Request: enabling option "Automatically set system focus to focusable elements" by default

### ISSUE THREAD

**Issue by VovaMobile** [nvaccess/nvda#11654] opened 2020-09-21 15:01 UTC
### Actual behavior:
When option "Automatically set system focus to focusable elements" is disabled, some sites do not have the ability to write in the input field by moving the cursor keys. When you move the tab key, everything works normally.
### Expected behavior:
Option "Automatically set system focus to focusable elements" Should remain enabled by default.
#### NVDA installed/portable/running from source:
Installed, running from home notebook
#### NVDA version:
2020.3beta1
#### Windows version:
Windows 10 PRO Version 2004 build 19041.508
#### Name and version of other software in use when reproducing the issue:
Webbrowsers Firefox and Google Chrome, latest versions
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, in the previous version this option was enabled
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by lukaszgo1** [comment] 2020-09-21 15:06
Please give example websites where this problem occurs, otherwise it cannot be fixed.

**Comment by VovaMobile** [comment] 2020-09-21 15:10
This problem detected on touch.facebook.com

**Comment by VovaMobile** [comment] 2020-09-21 15:14
Also problem with copying text from read-only field detected on the website translate.ru. This sites work correctly if the option "Automatically set system focus to focusable elements" is enabled.

**Comment by lukaszgo1** [comment] 2020-09-21 15:24
@VovaMobile Sorry but this is not enough to investigate this further. Please give list of actions which needs to be performed on these websites to reproduce the problem, explain exactly what happens and what should happen instead.  It'd be great if you can concentrate on touch.facebook.com since the translation website seems to be available only in Russian and therefore fixing the issue there would be harder for someone who does not speak it.

**Comment by VovaMobile** [comment] 2020-09-21 16:32
When the option "Automatically set system focus to focusable elements" is disabled, i can not write comments in some posts at touch.facebook.com in this case:
When I use the cursor keys to find the edit box and the focus falls on it, focus mode is activated.
When I type letters, they are not entered in this edit box.
This is a part from logfile:
Input: kb(desktop):f
IO - speech.speak (19:14:10.458) - MainThread (3032):
Speaking [CharacterModeCommand(True), 'f', EndUtteranceCommand()]
DEBUGWARNING - external:synthDrivers.newfon.SynthDriver.speak (19:14:10.458) - MainThread (3032):
Unsupported speech command: CharacterModeCommand(True)
DEBUG - speech.manager.SpeechManager._handleIndex (19:14:10.458) - MainThread (3032):
Unknown index 5590, speech probably cancelled from main thread.
DEBUGWARNING - external:synthDrivers.newfon.SynthDriver.speak (19:14:10.478) - MainThread (3032):
Unsupported speech command: CharacterModeCommand(True)
IO - inputCore.InputManager.executeGesture (19:14:10.628) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:10.803) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:10.958) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:11.098) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:11.348) - winInputHook (5612):
Input: kb(desktop):f
IO - speech.speak (19:14:11.358) - MainThread (3032):
Speaking [CharacterModeCommand(True), 'f', EndUtteranceCommand()]
DEBUGWARNING - external:synthDrivers.newfon.SynthDriver.speak (19:14:11.358) - MainThread (3032):
Unsupported speech command: CharacterModeCommand(True)
DEBUGWARNING - external:synthDrivers.newfon.SynthDriver.speak (19:14:11.375) - MainThread (3032):
Unsupported speech command: CharacterModeCommand(True)
IO - inputCore.InputManager.executeGesture (19:14:11.523) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:11.688) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:11.848) - winInputHook (5612):
Input: kb(desktop):backspace
IO - inputCore.InputManager.executeGesture (19:14:12.538) - winInputHook (5612):
Input: kb(desktop):escape
I tried write f letter in comment edit field at https://touch.facebook.com/story.php?story_fbid=3441653289234336&id=129959817070383
However, when I get edit box pressing tab, this site work correct.
Also incorrect work detected, if edit box activating automatic.
Other example for illustrating this error: reverso.net
Cannot read text in read-only window

**Comment by akash07k** [comment] 2020-09-21 16:42
If the issue is there, then it doesn't mean that that option should be
disabled by default.
"automatically set system focus to focusable elements" is turnned on
in recent builds because it improves browsing, and you are saying to
revert back this behaviour and that too for your own convenience?

**Comment by VovaMobile** [comment] 2020-09-21 17:25
I'm not just talking about my convenience.
Many blind users use the mobile version of Facebook.
In addition, incorrect work is observed on other sites. I already mentioned Reverso.
In recents builds this option was turned on and all works correctly.
If you leave this option disable by default in the future, some users may be unhappy. Not all users read the documentation and not all users will understand why NVDA's interaction with some sites has deteriorated.

**Comment by lukaszgo1** [comment] 2020-09-21 19:37
I can reproduce the Facebook problem. It is important to note that you need to have automatic focus mode for caret movement enabled. It looks  like when focus mode is activated as a result of caret moving `_focusLastFocusableObject` is not called.

**Comment by Brian1Gaff** [comment] 2020-09-22 08:08
Does this choice have a hot key? That would seem to be the answer here. I 
think I've seen this also, but thought it was my being thick. I was using 
the beta as I recall, but don't remember the web site.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by akash07k** [comment] 2020-09-22 08:44
Insert+8

**Comment by VovaMobile** [comment] 2020-09-22 09:51
Again and again: users will install a new version of NVDA after its
release and will be surprised at the deterioration of its performance
on some sites.
What improvements does this feature provide when it is disabled? I did
not notice any improvements. But I noticed a deterioration.
Instead, when it's enabled, everything works fine.
My focus mode and browse mode switching when navigating with the arrow
keys. This speeds up the work.
The user should not waste time learning why work has gotten worse.
Please check this feature again in different conditions before making
this change in the final version.

**Comment by feerrenrut** [comment] 2020-09-22 12:22
The alternative is to investigate and fix this particular bug. I understand that encountering bugs is annoying and frustrating, but generally this improves the experience for many. If the option was disabled by default, others would encounter bugs. Those bugs tend to be harder to address.

@lukaszgo1 it seems like you have been looking at the technical side of this, are you investigating a fix?

**Comment by akash07k** [comment] 2020-09-22 12:56
Are you aware about rubber band effect?
That is so annoying and this feature majorly fixes it

**Comment by VovaMobile** [comment] 2020-09-22 15:57
@akash07k, I don't understand what you want to say

**Comment by feerrenrut** [comment] 2020-09-22 16:18
@akash07k Let's try to keep this discussion on topic as much as possible. I'm going to mark this comments as off topic to try to keep the thread easy to read.

**Comment by lukaszgo1** [comment] 2020-09-22 23:05
> @lukaszgo1 it seems like you have been looking at the technical side of this, are you investigating a fix?


I've looked at this very quickly yesterday hoping the solution for this would be obvious, but it either isn't or I'm too unfamiliar with this part of the code. I won't have time to look more thoroughly, sorry.

**Comment by lukaszgo1** [comment] 2020-09-25 17:46
@VovaMobile Please test with [this build](https://ci.appveyor.com/api/buildjobs/33iveog3w1298s22/artifacts/output%2Fnvda_snapshot_pr11665-21047%2C854b0137.exe) all websites witch was causing you troubles and report back.

**Comment by leonardder** [comment] 2020-09-26 06:59
I'm closing this in favor of #11663. Though that issue is newer, it has a clearer steps to reproduce.

**Closed by leonardder** 2020-09-26 06:59 UTC

**Comment by VovaMobile** [comment] 2020-09-26 07:39
Thanks, sites works normally with build  pr11665-21047,854b0137
