### ISSUE TITLE
Request regarding mouse hover

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10744] opened 2020-02-02 15:28 UTC
Win10 / Version: 2019.2.1 / portable

Hello, I would like to request that the mouse hover gives more information when hovering over options, controls or browser elements, than just their name text. Namely their accelerator or shortcut keys, and / orr their current setting.

For example, in the Notepad find dialogue if I hover over "wrap around" that is all it says. Whereas in Narrator I am informed: "checked, wrap around, checkbox, alt and r"

This tells me everything I need to know. Not just what it is, but what it is set to, and how to quickly get there.

Another example is CloneSpy, a duplicate file finder app. I can see enough to see that there is a list of options on the right, but not which one precisely has been selected (I think it is a radio button list). If I hover over the items NVDA just tells me what they are, "newer" or "older" etc. 
Whearas a Narrater mouse hover used to also add a "selected" or "unselected" to the option, so I can know quickly that, for example, the app is set to delete files that are older.

This means that unlike with Narrator, with NVDA If I want to check I may have to press TAB up to eight times to get to that section with the KB. at which point NVDA will then tell me the selected setting. and Then once I have checked that the current setting is set as I thought it was, I might then have to shift+TAB another eight times to get back to the directories pool. Clearly I would prefer a mouse hover to tell me, and save up to 16 key presses :)

One final example is the browse mode elements on a webpage. Once again, if I hover NVDA just tels me what its text is. If it would also tell me such things as whether it is a level 4 heading, a button, a frame etc, I could get the keyboard focus there so much quicker than the current trial and error method until I eventually land on it (only to then be told it was a level 4 heading say, and so I could have got there just by pressing 4 a few times)

So I would dearly love NVDA to include more information in the mouse hover of these sorts of items, Thanks for reading.

(I have already made a request regarding the mouse hover revealing accelerator keys of controls so there is a partial overlap with this more fuller request. Sorry about that)

**Comment by Adriani90** [comment] 2020-05-30 00:26
Closing as duplicate of #10319 and #3930

**Closed by Adriani90** 2020-05-30 00:26 UTC
Labels: close/duplicate, feature, feature/mouse-tracking
