### ISSUE TITLE
[Word] : content control announced as "edit" and does not announce exit

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#8293] opened 2018-05-16 06:42 UTC
###Steps to reproduce:
1.	click on the developer tab
2.	insert a rich text content control
3.	add some text to it
4.	open the context menu for the content control, select properties
5.	add a title to the developer tab
6.	Read the line with the content control on it

### Expected behavior:
Tell us what should happen.

### Actual behavior:
Tell us what happens instead.

### System configuration:
NVDA version: 2018.1.1
App Name: Word
NVDA Installed or portable: Installed
**Other information:**
Windows version:
> Example: Windows 10 Version 1803 Build 17134.48
Name and version of other software in use when reproducing the issue:

### Other questions:
Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No
> Please list them and the result

**Comment by Adriani90** [comment] 2020-05-08 18:46
I cannot reproduce. When pressing right arrow key or ctrl+right arrow key, NVDA 2020.1 reports as expected edit field "my title" end of edit field.
Closing as works for me. Please open a new issue and fill the complete template accordingly. Thanks.

**Closed by Adriani90** 2020-05-08 18:46 UTC
Labels: close/worksforme
