### ISSUE TITLE
Removing user configuration during uninstall

### ISSUE THREAD

**Issue by AppleUser03** [nvaccess/nvda#14699] opened 2023-03-06 21:16 UTC
### Is your feature request related to a problem? Please describe.
When I uninstall NVDA from my computer by launching the uninstaller, NVDA is removed, but user configuration files remain there.
### Describe the solution you'd like
It would be useful to be able to choose whether or not to remove the user configuration during uninstall, similar to when uninstalling JAWS.

**Comment by Adriani90** [comment] 2023-03-06 23:18
Closing as duplicate of #6869.

**Closed by Adriani90** 2023-03-06 23:18 UTC
Labels: close/duplicate
