### ISSUE TITLE
Windows 10 start menu search and braille display out issue

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#6414] opened 2016-09-30 02:24 UTC
Hello, I'm Hyongsop Kim in Korea and NVDA user.
In newest NVDA next version, in start search, once I type keyword of program name or filename usch as nvda, NVDA says first results very well, such as nvda desktop app.
However, in my braille display, the first result is not appeared.
And in case of second or other results, even if NVDA says program name and category such as settings or desktop apps, category is not appeared braille display.
Please check this issue and fix it.

Thank you.

**Comment by jcsteh** [comment] 2016-10-05 04:13
When the results appear, the focus is actually still in the search box. Braille needs to show this so you can edit the text in the search box if you wish.

The only thing we can really do here is display the suggestion as an informational message which disappears after a few seconds.

**Comment by josephsl** [comment] 2016-10-08 04:42
Hi,

Tentative design: add a call to braille.handler.message (appModules.searchui.py, line 25) with the parameter being the message that synthesizers would have spoken (see NVDAObjects.behaviors.Notification class).

Questions to consider:

1. Should suggestion item selection event be treated as an alert event?
2. If answer to question 1 is no, besides braille.handler.message, would introducing a flash message function in braille.handler or ui module be helpful?

Thanks.

**Comment by josephsl** [comment] 2017-05-31 20:18
Hi,

Rolling this into #6241 PR. Thanks.

**Comment by Adriani90** [comment] 2019-03-09 12:21
@dkager could you please test if this is still reproducible in NVDA 2019.1 Beta 1? I think there were improvements related to this (see referenced pull requests).

**Comment by josephsl** [comment] 2022-03-26 17:32
Hi,

2022 check-in: any updates from anyone? If this is fixed, I vote to close this one this year.

Thanks.

**Comment by Adriani90** [comment] 2024-05-07 18:24
@burmancomp, @Emil-18 can you reproduce this issue with NVDA 2024.1?

As a workaround in case this is still an issue, NVDA is now able to emulate speech on braille displays, by choosing "follow speech" in the braille settings. Then the suggestions should definitely appear on the display.

**Comment by Emil-18** [comment] 2024-05-22 16:36
@Adriani90 When braille is auto tethered or tethered to review, it works as expected, because the navigator object is moved to the focused suggestion. I personally think this is acceptable behavior. Sorry for late reply

**Comment by Adriani90** [comment] 2024-05-22 19:08
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2024-05-22 19:08 UTC
Labels: close/worksforme, p3
