### ISSUE TITLE
Stramge effects  in gui of nvda alpha snaps on windows 7

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#15147] opened 2023-07-15 10:11 UTC
### Steps to reproduce:
Run the latest snapshot as a portable version with add ons disabled NVDA version alpha-28685,a8b79c76 on a windows 7 machine. Observe that   an error ding is heard

###
 Actual behavior:
The  prefererences/vision  options do not work and make an error.
 Also, if you then selectively enable add ons such asRead feeds and Tesseract, the guis of these do no longer appear anywhere.

###
 Expected behavior:
There should be no errors or problems with the Gui. It seems that any add on with its own gui can be affected, but it used to be OK in the release version 2023.1

#### NVDA installed/portable/running from source:
Portable as  mentioned, but not tried it installed.
#### NVDA version:
See top of report
#### Windows version:
Windows 7 pro with all updates.
#### Name and version of other software in use when reproducing the issue:
None, but running software will make no difference that I can see.
#### Other information about your system:
Nothing exciting, running Microsoft anti virus only which is still updating.
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Stable version as portable and installed. 2023.1, all guis work and all addons work that I have installed.

#### If NVDA add-ons are disabled, is your problem still occurring?
The vision one is, yes. The issue will get worse as add ons with guis are enabled.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes and after a restart.

**Comment by seanbudd** [comment] 2023-07-16 23:47
Closing as duplicate of #15142

**Closed by seanbudd** 2023-07-16 23:47 UTC
