### ISSUE TITLE
Akelpad editable field is causing some issues with windows Kernel APi function used by NVDA

### ISSUE THREAD

**Issue by JanuszChmiel** [nvaccess/nvda#6609] opened 2016-11-30 22:29 UTC
Dear MR Tech and others,
When long document is opened by akelpad, file which contain more than 620000 characters, there is A following error shortly after opening The file and when I press down arrow key inside editable text inside Akelpad window.
error executing script: <bound method Dynamic_AkelEditIAccessibleAkelEditWindowNVDAObject.script_caret_moveByLine of <NVDAObjects.Dynamic_AkelEditIAccessibleAkelEditWindowNVDAObject object at 0x0536DB70>> with gesture u'\u0161ipka dol\u016f'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 143, in script_caret_moveByLine
  File "editableText.pyc", line 103, in _caretMovementScriptHelper
  File "editableText.pyc", line 89, in _caretScriptPostMovedHelper
  File "speech.pyc", line 721, in speakTextInfo
  File "textInfos\offsets.pyc", line 393, in getTextWithFields
  File "baseObject.pyc", line 21, in __get__
  File "textInfos\offsets.pyc", line 411, in _get_text
  File "NVDAObjects\window\edit.pyc", line 348, in _getTextRange
  File "winKernel.pyc", line 117, in virtualAllocEx
WindowsError: [Error 8] Ke zpracování tohoto příkazu není dostatečný prostor.

Would you implement some loop inside nvda.core or inside akelpad dynamic editable code which would inform user, that core of Windows is ready to accept requests from screen reader?
I do not know, if Akelpad or Windows itself can generate glass hours on The screen to inform user that user should wait.
I it 32 bit release of Akelpad.

**Comment by jcsteh** [comment] 2016-11-30 22:39
This error indicates that Windows was unable to allocate sufficient memory in the remote process to fetch the text of the line. A few questions:

1. Does this happen whenever you try to move by line in that file or only when the application is first opened? As I understand it, this has nothing to do with the application not being ready; we simply can't allocate enough memory.
2. You noted that the file contains 620000+ characters. How long are the lines in this file? Are they of reasonable length or are there thousands of characters per line?

**Comment by Adriani90** [comment] 2019-03-25 20:44
@JanuszChmiel are you still able to reproduce this issue in NVDA 2019.1 RC1?

**Comment by Brian1Gaff** [comment] 2019-03-25 21:17
I have had some issues recently but its hard to pin down what is going on. 
Sometimes it seems the data is blank but its not.
  It works most of the time but not all the time.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by JanuszChmiel** [comment] 2019-03-26 21:46
I can confirm, that bug is gone for ever. I have opened Pascal source 
code unit, which have more than 400000 characters and there is not such 
error like before.
And speed while browsing editable field even inside such long text Ascii 
file is very fast. COngratulations, very well done.

**Comment by Adriani90** [comment] 2019-03-26 22:44
@JanuszChmiel thanks very much for reporting back. Glad to hear that it works for you. I am closing this for now as works for me. @Brian1Gaff could you please open a new issue for that problem including steps to reproduce and a log file when NVDA shows blank field although there is data in it? Thanks!

**Closed by Adriani90** 2019-03-26 22:44 UTC
Labels: blocked, worksforme
