### ISSUE TITLE
Strange behaviour in an audio player in firefox compared to jaws or ie with nvda

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#10379] opened 2019-10-14 09:20 UTC
Problem on a web page that plays audio.
 Note this page will work on Jaws and latest Firefox when in the mode where links are on a line of their own, but not in nvda under the same conditions.
Steps to reproduce
Go to:
https://kingston.talking-news.info/
Using Firefox, any version or Waterfox if you like.
Try to find the play button or try to play an individual track number. 
Most times you do not find the play button or indeed any of the controls unless you refresh the page, or sometimes going down with cursors and up again.
 They should appear between the  email address of our service, and the track listing.
 The fact that the tracks do not play is interesting. If you have visited the play button, when you can get to it, the tracks will play OK.
The nvda log shows errors when you are accessing parts of this page, reoccuring multiple times and strange errors on the track player buttons
None of these errors are flagged by sound on dev snapshots..
Also, when you do get the buttons to show, B tends to read only half the name or a cluster of button names so you are not sure which button has focus.

What you expect to happen pressing B or the player link should end up on the play controls directly.
 This seems to be the case in Internet Explorer with nvda,  and Jaws with Firefox, but not nvda. Note the Jaws version is 2018
Other system and useful information.
 Machine is I5 3.2 Mhz 8 gig of ram ssd drive running up to date copy of windows 7 pro. Firefox is 64 bit on the beta channel and up to date.
Other versions of nvda.
 Tested with 2019.2.1 and alpha latest as portable version.
 Switching add ons off makes no noticeable difference.

restarting machine no change.
 Final comment
The fact that sometimes it works is peculiar, at other times very mangled text is spoken for the controls.

Over to you.

**Comment by Brian1Gaff** [comment] 2019-10-27 09:51
Hi again. Recent changes to NVDA Alpha have sorted this in Waterfox, but there are still issues in the latest Firefox, ie, you do not see the player region and without that none of the track play buttons will operat.
 Here is the latest log. It seems to have  something todo with the buffer since a refresh with f5 will normally allow one to find the player.
 Its as if its not actually managed to see it.
 Here is the latest log fragment in Firefox.
IO - inputCore.InputManager.executeGesture (09:25:52.400) - winInputHook (4888):
Input: kb(desktop):f5
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:52.411) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:52.423) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:52.847) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:52.850) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (09:25:52.935) - MainThread (1028):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x08242490>
DEBUG - treeInterceptorHandler.update (09:25:52.935) - MainThread (1028):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x03E8D130>
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (09:25:53.149) - MainThread (1028):
IAccessibleObject.attributes COMError (-2147220995, 'Object is not connected to server', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (09:25:53.151) - MainThread (1028):
error executing event: alert on <NVDAObjects.Dynamic_DialogMozillaIAccessible object at 0x0413EED0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\nvda extra\userConfig\addons\Mozilla\appModules\firefox.py", line 75, in event_alert
    url = shared.searchObject(path)
  File "C:\nvda extra\userConfig\addons\Mozilla\appModules\shared\__init__.py", line 81, in searchObject
    obj = searchAmongTheChildren(milestone, obj)
  File "C:\nvda extra\userConfig\addons\Mozilla\appModules\shared\__init__.py", line 91, in searchAmongTheChildren
    if key in obj.IA2Attributes.keys():
AttributeError: 'NoneType' object has no attribute 'IA2Attributes'
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (09:25:53.229) - virtualBuffers.gecko_ia2.VirtualBuffer.loadBuffer (1344):
Buffer load took 0.293 sec, 2376 chars
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.253) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.274) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (09:25:53.276) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'KTN Weekly current edition']
IO - speech.speak (09:25:53.282) - MainThread (1028):
Speaking [<speech.commands.CallbackCommand object at 0x0413EC90>, LangChangeCommand ('en_GB'), 'main landmark ', 'heading  level 1', 'align center', 'Media player']
IO - speech.speak (09:25:53.286) - MainThread (1028):
Speaking [<speech.commands.CallbackCommand object at 0x0413E750>, LangChangeCommand ('en_GB'), 'audio player region ', 'Selected Track:']
IO - speech.speak (09:25:53.294) - MainThread (1028):
Speaking [<speech.commands.CallbackCommand object at 0x080A6330>, LangChangeCommand ('en_GB'), 'Track 1 of 55 ']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.301) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.302) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.304) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.306) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (09:25:53.309) - MainThread (1028):
Speaking [<speech.commands.CallbackCommand object at 0x0413EBF0>, LangChangeCommand ('en_GB'), 'clickable', 'audio timeline  slider', 'align default', '0 seconds']
IO - speech.speak (09:25:53.309) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'Paused ']
IO - speech.speak (09:25:53.335) - MainThread (1028):
Speaking [<speech.commands.CallbackCommand object at 0x041564B0>, LangChangeCommand ('en_GB'), 'button', 'Play', <speech.commands.CallbackCommand object at 0x080A8DB0>, 'button', 'Restart', <speech.commands.CallbackCommand object at 0x03E84CF0>, 'button', 'Rewind', <speech.commands.CallbackCommand object at 0x03E84850>, 'button', 'Forward', <speech.commands.CallbackCommand object at 0x041645B0>, 'button', 'Previous track', <speech.commands.CallbackCommand object at 0x0415DDB0>, 'button', 'Next track']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.602) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.604) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.635) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.637) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.955) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:53.957) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:54.111) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (09:25:54.112) - MainThread (1028):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (09:25:59.592) - winInputHook (4888):
Input: kb(desktop):upArrow
IO - speech.speak (09:25:59.605) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'align center', 'Selected Track:']
IO - inputCore.InputManager.executeGesture (09:26:01.376) - winInputHook (4888):
Input: kb(desktop):upArrow
IO - speech.speak (09:26:01.391) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'level 1', 'Media player']
IO - inputCore.InputManager.executeGesture (09:26:03.040) - winInputHook (4888):
Input: kb(desktop):upArrow
IO - speech.speak (09:26:03.055) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'reference items as well. To email us use ktnews@blueyonder.co.uk ']
IO - inputCore.InputManager.executeGesture (09:26:05.184) - winInputHook (4888):
Input: kb(desktop):tab
IO - speech.speak (09:26:05.299) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'audio timeline  0 seconds']
IO - inputCore.InputManager.executeGesture (09:26:13.329) - winInputHook (4888):
Input: kb(desktop):control+alt+r
IO - speech.speak (09:26:13.409) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'Taskbar']
IO - speech.speak (09:26:13.488) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), 'reboot nvda with log']
IO - speech.speak (09:26:13.491) - MainThread (1028):
Speaking [LangChangeCommand ('en_GB'), '80 space', 'blank']
INFO - core.main (09:26:13.571) - MainThread (1028):
Exiting
DEBUG - core._terminate (09:26:13.571) - MainThread (1028):
Terminating updateCheck
DEBUG - core._terminate (09:26:13.571) - MainThread (1028):
Terminating watchdog
DEBUG - core._terminate (09:26:13.571) - MainThread (1028):
Terminating global plugin handler
DEBUGWARNING - Python warning (09:26:14.080) - MainThread (1028):
C:\nvda extra\userConfig\addons\audiothemes\globalPlugins\audiothemes\__init__.py:66: wxPyDeprecationWarning: Call to deprecated item. Use Remove instead.
  gui.mainFrame.sysTrayIcon.menu.RemoveItem(self.studioMenuItem)
DEBUG - core._terminate (09:26:14.081) - MainThread (1028):
Terminating gui
DEBUG - fileUtils.FaultTolerantFile (09:26:14.090) - MainThread (1028):
C:\nvda extra\userConfig\nvda.inie4jpcu7v.tmp
INFO - config.ConfigManager.save (09:26:14.092) - MainThread (1028):
Base configuration saved
DEBUG - core.main (09:26:14.092) - MainThread (1028):
calling lose focus on object with focus
DEBUG - core._terminate (09:26:14.094) - MainThread (1028):
Terminating treeInterceptorHandler
DEBUG - treeInterceptorHandler.killTreeInterceptor (09:26:14.095) - MainThread (1028):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x03E8D130>
DEBUG - core._terminate (09:26:14.097) - MainThread (1028):
Terminating IAccessible support
DEBUG - core._terminate (09:26:14.097) - MainThread (1028):
Terminating UIA support
DEBUGWARNING - _UIAHandler.UIAHandler.terminate (09:26:14.297) - MainThread (1028):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (09:26:14.297) - MainThread (1028):
Terminating Legacy winConsole support
DEBUG - core._terminate (09:26:14.297) - MainThread (1028):
Terminating Java Access Bridge support
DEBUG - core._terminate (09:26:14.297) - MainThread (1028):
Terminating app module handler
DEBUG - core._terminate (09:26:14.297) - MainThread (1028):
Terminating NVDAHelper
DEBUG - core._terminate (09:26:14.300) - MainThread (1028):
Terminating touchHandler
DEBUG - core._terminate (09:26:14.300) - MainThread (1028):
Terminating keyboard handler
DEBUG - core._terminate (09:26:14.300) - MainThread (1028):
Terminating mouseHandler
DEBUG - core._terminate (09:26:14.301) - MainThread (1028):
Terminating inputCore
DEBUG - core._terminate (09:26:14.301) - MainThread (1028):
Terminating vision
DEBUG - core._terminate (09:26:14.301) - MainThread (1028):
Terminating brailleInput
DEBUG - core._terminate (09:26:14.301) - MainThread (1028):
Terminating braille
DEBUG - core._terminate (09:26:14.315) - MainThread (1028):
Terminating speech
DEBUG - core._terminate (09:26:14.316) - MainThread (1028):
Terminating addonHandler
DEBUG - core.main (09:26:15.377) - MainThread (1028):
core done
INFO - __main__ (09:26:15.387) - MainThread (1028):
NVDA exit


Note ignore the error from the add on near the end that is just something else entirely.
Hope this can be fixed.

**Comment by Adriani90** [comment] 2020-01-16 20:15
@Brian1Gaff it works just fine for me in N'VDA 2019.3 Beta 2 and Firefox 72.0.1. Can you confirm?
It looks like you use the addon mozilla app enhancements which throws and error here. Could you please deactivate that addon and try again?

**Comment by Adriani90** [comment] 2020-01-16 20:16
I can jump with b to the play button and the button is found instantly. All buttons are pronounced correctly. The track is playing also properly when pressing enter on the button.

**Comment by Adriani90** [comment] 2020-01-31 19:21
@Brian1Gaff last reminder before closing because we do not have further user reports in different mailing lists and we cannot reproduce this. Can you confirm that it works for you with addons disabled in NVDA 2019.3 Beta 4 and Firefox 72?

**Comment by Adriani90** [comment] 2020-02-27 20:37
No updates from the initial author and the issue is not reproducible.
Closing as works for me.

**Closed by Adriani90** 2020-02-27 20:37 UTC
Labels: worksforme
