### ISSUE TITLE
Office UI fabric- DetailsList - NVDA non interactive column header pronounce as clickable

### ISSUE THREAD

**Issue by MdAmeerMind** [nvaccess/nvda#10749] opened 2020-02-03 07:26 UTC
Actual behavior:
NVDA is pronouncing column header name with word clickable

Expected:
If column is non interactive (No Column sorting is there), then NVDA should read it only column name.

Code repro
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/compact

In Above example, Name and value column are non intractable, but NVDA is pronounce it as clickable.

I have already raise same bug with Office UI Fabric team , so they confirm that its form NVDA side.
https://github.com/OfficeDev/office-ui-fabric-react/issues/11828

**Comment by feerrenrut** [comment] 2020-02-03 12:59
Thanks for raising an issue @MdAmeerMind though please in future gives steps to reproduce to help us ensure we are looking at the same thing as you. 

I assume you are talking about the column header with name "Name". Firefox Developer tools shows that a click handler is registered for this element. It may be that this click handler does nothing, but there is now way for NVDA to know that. I think NVDA is doing the best it can in this sample. I will leave a comment on the OfficeDev/office-ui-fabric-react#11828

**Comment by feerrenrut** [comment] 2020-02-05 10:28
I'm going to close this issue. I don't see any evidence to suggest that NVDA is doing something other than intended. The sample has a click handler, it potentially could do something, visually it invites you to click it also. The only way to find out what it does is to click it. If NVDA did not report clickable, there would be no way for the user to become aware that it's possible it clicking might do something. In a real application I expect the sample would be extended to provide sort behavior for the columns or something similar.

**Closed by feerrenrut** 2020-02-05 10:28 UTC
Labels: bug, needsExternalFix
