### ISSUE TITLE
Create a setting to turn off/bypass the NVDA touch interface/overlay in order for touch screen actions to pass through to windows as it normally would when NVDA is disabled

### ISSUE THREAD

**Issue by Deon588** [nvaccess/nvda#10321] opened 2019-10-03 19:56 UTC
### Describe the solution you'd like
IT would be nice to be able to toggle the touch screen interface, I am a low vision user and would like the ability to use a touch screen laptop's touch screen without the NVDA touch interface while NVDA is running.
### Additional context
Using a laptop with a touch screen

**Comment by josephsl** [comment] 2019-10-03 20:01
Hi, ah yes, thanks for reminding me to send a pull request regarding this one – effectively transferring parts of Enhanced Touch Gestures add-on to NVDA Core. But for now, closing as duplicate of #9682. Thanks.

**Closed** 2019-10-03 20:02 UTC
