### ISSUE TITLE
Landmarks, some links, lists and text from headings display on same line

### ISSUE THREAD

**Issue by eltonfreak** [nvaccess/nvda#8741] opened 2018-09-13 01:16 UTC
- [ ] In firefox some ellaments display on same line as text underneath even thow document formatting is set to simple layout.
https://www.fanfiction.net/s/10684896/1/The-Heir-to-Prince-Manor
http://en.wikipedia.org/wiki/3D_audio_effect#Some_products
blank lines are set to ignore.

**Comment by jscholes** [comment] 2018-09-13 10:44
In NVDA's browse mode settings, do you have the check box "Use screen layout (when supported)" checked or unchecked?  If it is checked this is expected behaviour.  If it is unchecked and this behaviour persists, please tell us which links or other elements seem out of place.

Also note that landmarks do not appear on the page, they are spoken by NVDA before their content regardless of the setting mentioned above.

**Comment by Adriani90** [comment] 2018-11-06 20:43
@eltonfreak, I cannot really understand your issue. What do you mean by "simple!? Could you please edit the description and make it more understandable?

If I should guess, screen layout is unchecked but still some elements are announced like if they are in the same row.

@jscholes, On the first page linked above (fanfiction) there is following part announced in the same row despite screen layout disabled.

**Comment by Adriani90** [comment] 2018-11-06 20:44
Fiction T - English - Hurt/Comfort/Family - Chapters: 35 - Words: 190,153 - Reviews:

601 - Favs: 1,118 - Follows: 660 - Updated: Dec 17, 2014 - Published: Sep 11, 2014 - Status: Complete - id: 10684896.

**Comment by Adriani90** [comment] 2018-11-06 20:46
Actually the single charcteristics should be announced under eachother when screen layout is disabled. But I think this is not an NVDA issue. I guess it is rather related to the css style of the website. I guess the developer of the website did not clearly defined carriages etc.

Comments are appreciated.

**Comment by ehollig** [comment] 2018-11-07 04:00
@eltonfreak please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead. If we are not able to understand your issue from one of the links above, we will have to close this issue.

**Comment by Adriani90** [comment] 2020-05-09 11:55
Closing as duplicate of #11073 and #11096.

**Closed by Adriani90** 2020-05-09 11:55 UTC
Labels: close/duplicate
