### ISSUE TITLE
NVDA reading code snippets written inside <script> tag in IE11

### ISSUE THREAD

**Issue by midhun1** [nvaccess/nvda#6028] opened 2016-06-01 08:02 UTC
![image](https://cloud.githubusercontent.com/assets/19682996/15702355/457298de-27fd-11e6-9ed4-cc7250114542.png)

```
 <!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title of the document</title>
<script style="display:none;">
var brand='maruthi';
var car={
    brand:'nissan',
    getBrand:function(){
        console.log(this.brand);
    }
}
var carBrand=car.getBrand.bind(car);
carBrand();
</script>
</head>

<body>
<b><b>Content of the document......</b></b>
</body>

</html>
```

**Comment by jcsteh** [comment] 2016-06-02 00:48
Please provide steps to reproduce. When I open the document in IE 11, NVDA just reads "Content of the document". Using the cursor keys to move around just reads that text.

**Comment by chrisd27** [comment] 2016-06-08 13:11
Hi midhun1,

I have been experiencing this issue recently also. 
I think I've found the answer, the script tag has no **type** so is invalid so NVDA is reading it as HTML. I assume most browsers realised it's javascript and treat it so but good old IE can be a pain.

Try changing the script tag from <script></script> to <script type="type/javascript"></script>

Also, remove the style="none" from the script tag as this is also invalid.

Thanks,

Chris

**Comment by chrisd27** [comment] 2016-06-08 13:12
Sorry, didn't like my code being out of a code insert - 
try changing the opening script tag from `<script>` to `<script type="text/javascript">`

**Comment by hkdennis2k** [comment] 2016-06-22 04:17
I having similar issue.
On a page contains JavaScript and it will lazy load partial HTML and extra <script> tags into the body.

I it is reproducible to be after a clean restart

Tested with 
IE Version 11.420.10586.0 / Update Versions 11.0.32 on Windows 10
NVDA version 2015.4  and NVDA version 2016.2.1 

[test.html.txt](https://github.com/nvaccess/nvda/files/326980/test.html.txt)

**Comment by petiso** [comment] 2016-12-21 14:26
Hi, Ihaving a similar issue.
Did you find any solution?
Would appreciate some help
Thanks a lot

**Comment by ajitbubu** [comment] 2017-01-06 16:14
I am having similar kind of issues, when the I focus the cursor into the input filed NVDA reading the input tag when there is no text enter into the field, but once there is some text in the input field its all fine.

**Comment by Adriani90** [comment] 2019-05-23 19:08
I am testing with NVDA 2019.1.1 in all browsers, including IE11. No code snippets are being read. NVDA reports "title of the document document", "content of the document". So I cannot reproduce this issue. Steps to reproduce are missing in the description and so we are not able to understand exactly what's going on.
@midhun1, @ajitbubu, @petiso, @chrisd27, @hkdennis2k are you still having this issue in NVDA 2019.1.1? Could you please post a minimal test case and steps to reproduce? Thanks.

**Comment by Adriani90** [comment] 2020-05-17 12:06
I cannot reproduce this in IE11 with NVDA 2020.1. See also issue #10733, maybe this is the same issue. However, that one can be reproduced reliably. Closing this one in favor of #10733.

**Closed by Adriani90** 2020-05-17 12:06 UTC
Labels: close/duplicate, p3
