### ISSUE TITLE
NVDA  goes silent  when skip link is clicked on Microsoft Edge.

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#12651] opened 2021-07-15 05:15 UTC
### Steps to reproduce:
- From the NVDA's advance setting, Change the dropdown value of "Use UIA with Microsoft Edge and other 
Chromium based browsers when available:" to "Yes".
- Visit on any site which has "Skip link" present.
For example, [Microsoft](https://www.microsoft.com/en-in/) site.
- Find The "Skip link" at the top of the page and press enter on it.
### Actual behavior:
NVDA goes silent for more than 5 seconds and starts reading the focused content afterwards.
Note: This behavior is not observed when the "Use UIA with Microsoft Edge and other 
Chromium based browsers when available:" is set to "Use only when necessary".
### Expected behavior:
NVDA should start reading focused content as soon as it gets focused.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2021.1
#### Windows version:
Windows 10(21H1)
#### Name and version of other software in use when reproducing the issue:
Microsoft EdgeVersion 91.0.864.67 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This feature was not available in prior versions.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2024-04-21 21:47
Tested with NVDA Version: alpha-31645,bf96860d (2024.2.0.31645) and Edge 124 UIA enabled, this issue is not occuring anymore. I am closing as works for me. If you are still seeting this 5 seconds freeze, please comment and we can reopen.

Note though sometimes NvDA will not report the content to which the virtual cursor / system focus has been redirected after cliciking on "skip" link. This is probably because the focus is redirected to a grouping, blank, separator or replacement character near the content and not on the content itself.
The focus redirection is handled by the web author, so NVDA cannot really do anything about this.

**Closed by Adriani90** 2024-04-21 21:47 UTC
Labels: close/worksforme, app/edge/anaheim, api/uia

**Comment by XLTechie** [comment] 2024-04-22 09:23
@Adriani90 may I suggest not closing issues if the fix is only verified in alpha? If the change gets reverted for whatever reason, the issue becomes valid again, but it might be unnoticed that it had been closed.

Since the issue is not tracked by any pull request, nobody knows to re-open it.

I suggest waiting until fixes are closed at least by a beta.

CC @gerald-hartig

**Comment by Adriani90** [comment] 2024-04-22 10:33
It is also working as described in my previous comment also with NVDA 2024.1 stable.Luke it would be of a much greater help if you took the little time to test yourself and report if this is still reproducible, in which case I would have reopened this imediately.Instead, you decided to spend time for the comment above which just brings more noise into this discussion.In general I test issues both on alpha and stable, and report the latest version I tested, which was ofcourse alpha.Next time, please comment with your test results and we reopen issues without objections.Von meinem iPhone gesendetAm 22.04.2024 um 11:23 schrieb Luke Davis ***@***.***>:﻿
@Adriani90 may I suggest not closing issues if the fix is only verified in alpha? If the change gets reverted for whatever reason, the issue becomes valid again, but it might be unnoticed that it had been closed.

Since the issue is not tracked by any pull request, nobody knows to re-open it.

I suggest waiting until fixes are closed at least by a beta.

CC @gerald-hartig

**Comment by gauravahir28** [comment] 2024-04-22 10:39
I can confirm that this issue  no longer replicates at my end!

**Comment by XLTechie** [comment] 2024-04-22 10:55
@Adriani90 I should have clarified that I was speaking generally, not of this issue in particular. I did not notice this issue before now. As you were the one reporting test results and closing the issue as a result of them, I was suggesting a possible concern.
If your tests replicate in 2024.1, then my concern did not apply to this issue, and I will raise it somewhere more on topic.

**Comment by seanbudd** [comment] 2024-04-23 05:16
@XLTechie - it's standard triaging to close issues when they are fixed on alpha. This even happens by default when merging a PR that fixes a closing issue.
