### ISSUE TITLE
NVDA freezes when selecting large blocks of text in Microsoft Word

### ISSUE THREAD

**Issue by rkingett** [nvaccess/nvda#10965] opened 2020-04-09 00:06 UTC
# Steps to reproduce:

* Open a document with more than 20 paragraphs.
* Hold Control, and Shift. 
* Press down arrow and hold it for 4 seconds or longer. Keep holding the down arrow. 

### Actual behavior:

NVDA Seems to crash and seems to shut completely down. Speech completely stops, but the computer itself is not frozen. NVDA has to be restarted to get speech back.

### Expected behavior:

NVDA should not crash when selecting text in this manner. Perhaps it could just say, selected, when selecting text in this manner.

#### 
NVDA installed. 

#### NVDA version:

2020.1

#### Windows version:

Version; Value: 10.0.18363 Build 18363

#### Name and version of other software in use when reproducing the issue:

Microsoft® Word for Office 365 MSO (16.0.12527.20260) 32-bit 

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Yes. This happens in all versions of NVDA.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

Yes.
[Kingett nvda.log](https://github.com/nvaccess/nvda/files/4453329/Kingett.nvda.log)

**Comment by Adriani90** [comment] 2020-04-09 19:58
Closing as duplicate of #9463.

**Closed by Adriani90** 2020-04-09 19:58 UTC
Labels: app/microsoft-office, bug/crash, close/duplicate, p3
