### ISSUE TITLE
Adobe Flash content no longer appears to read in NVDA

### ISSUE THREAD

**Issue by zersiax** [nvaccess/nvda#11131] opened 2020-05-08 12:04 UTC
### Steps to reproduce:
1. Load a page with at least somewhat accessible Flash Content in Internet Explorer or the new Microsoft Edge.
2. Press enter on the flash object.

### Actual behavior:
In Internet Explorer, chosen because it tends to support Flash by default, the only thing that happens is that the name of the object gets spoken after "embedded object". No focus change, the content of the object remains unreachable. In the logs, nothing at all is reported when pressing enter or loading the relevant page, not even in Debug mode.

In Edge based on Chrome, the embedded object reports as being "unavailable", and this, possibly relevant, log output shows up. Note: This might also be happening because of me navigating to the permissions popup to allow flash.
```
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:55:26.198) - MainThread (5608):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (13:55:26.659) - MainThread (5608):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speak (13:55:26.669) - MainThread (5608):
Speaking [LangChangeCommand ('en'), 'Laden voltooid']
IO - braille.BrailleBuffer.update (13:55:26.670) - MainThread (5608):
Braille regions text: ['Laden voltooid']
IO - braille.BrailleHandler.update (13:55:26.670) - MainThread (5608):
Braille window dots: 6 123 1 145 15 1345 - 1236 135 123 2345 135 135 24 145
IO - inputCore.InputManager.executeGesture (13:55:28.397) - winInputHook (8388):
Input: kb(laptop):f6
DEBUG - treeInterceptorHandler.killTreeInterceptor (13:55:28.428) - MainThread (5608):
Killed treeInterceptor: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x07209630>
DEBUG - treeInterceptorHandler.update (13:55:28.446) - MainThread (5608):
Adding new treeInterceptor to runningTable: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x07277B90>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (13:55:28.447) - NVDAObjects.IAccessible.chromium.VirtualBuffer.loadBuffer (18740):
Buffer load took 0.001 sec, 1 chars
DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.471) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::findNodeByAttributes, 967:
 offset 1 is past end of buffer, returning NULL

DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.478) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 859:
Offset 1 out of range. Returnning NULL

DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.487) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 879:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (13:55:28.487) - MainThread (5608):
Couldn't get NVDAObject from offset 1
DEBUGWARNING - browseMode.BrowseModeDocumentTreeInterceptor._set_selection (13:55:28.487) - MainThread (5608):
Invalid NVDAObjectAtStart

IO - speech.speak (13:55:28.488) - MainThread (5608):
Speaking [LangChangeCommand ('en'), 'Game Page']
IO - speech.speak (13:55:28.489) - MainThread (5608):
Speaking [<speech.commands.CallbackCommand object at 0x005EB330>]
DEBUGWARNING - RPC process 22284 (msedge.exe) (13:55:28.498) - Dummy-5 (152):
Thread 14452, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::getLineOffsets, 1055:
Offset of 1 too big for buffer, returning false

```

### Expected behavior:
The contents of the flash object should be readable.
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No

**Comment by leonardder** [comment] 2020-05-08 12:06
Do you by any chance have a page to test with?

**Comment by zersiax** [comment] 2020-05-08 12:24
I'm afraid not, the example I used is behind a login

**Comment by Adriani90** [comment] 2020-05-08 12:27
Maybe this one
https://www.dhs.state.il.us/accessibility/tests/flash/video.html

**Comment by Adriani90** [comment] 2020-05-08 12:30
otherwise I saw this problem often in online webinars or online trainings. Many corporates still use old training material which works only with Flashplayer.

**Comment by zersiax** [comment] 2020-05-08 12:43
Yup, that example exhibits the same symptoms here.

**Comment by codeofdusk** [comment] 2020-05-08 12:50
Flash will reach end of life (and will be removed from Windows) [on 31 December](https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support).

**Comment by leonardder** [comment] 2020-05-08 14:04
> 
> 
> Flash will reach end of life (and will be removed from Windows) [on 31 December](https://docs.microsoft.com/en-us/lifecycle/announcements/adobe-flash-end-of-support).

Does this mean that after the 31th of december, no browser will be able to access flash content at all? In that case, we can deprecate flash support and remove it from NVDA in 2021.1.

**Comment by lukaszgo1** [comment] 2020-05-08 14:12
This is a duplicate of #10565

The end of support for Flash in Windows means only that it cannot be used in iE or Edge, however it still would be possible to use it in FF or Chrome on a per site basis I believe. It is very important to have it fixed not only because it is a regression but also because some government sites at least in Poland still require it and it is quite unlikely to change in the near future.

**Comment by lukaszgo1** [comment] 2020-05-08 18:05
It  seems to be depended on the Windows version in use. I am unable to reproduce in Internet Explorer 11 on Windows 7 x64, whereas on my Windows 10 1909 install with the same version of IE it is reproducible. Assuming that this in deed a regression from 2018.4 the most likely candidates are #8479 and #8866

**Comment by lijianwei2019** [comment] 2020-05-14 14:09
Flash will reach end of life

https://theblog.adobe.com/adobe-flash-update/#content

**Comment by bhavyashah** [comment] 2020-06-20 16:17
https://github.com/nvaccess/nvda/issues/11131#issuecomment-625835140 suggests that this ticket is a duplicate of #10565. If that is indeed the case, please close one of the two tickets so as to unify discussions.

**Comment by Adriani90** [comment] 2020-06-21 20:08
The issue referenced here is already closed in favor of this.

**Comment by leonardder** [comment] 2021-01-01 13:59
Now it is January 2021, I think we can safely consider removing Flash support from NVDA:

1. It is no longer supported in IE, Edge and Chrome
2. As of the end of January, it is no longer supported in FireFox as well.

If people really must use Flash, they can safely use an older version of NVDA.

**Comment by Brian1Gaff** [comment] 2021-01-02 09:22
It was stated on the BBC yesterday that there is an open source version 
being developed to allow flash content to still be accessed. Maybe somebody 
knows who is doing this and could try to make sure accessible code is being 
written.
 Does it really matter if the code stays in nvda then? I think some people 
will still be using other browsers which still support it. I have it set to 
ask on my machine, and indeed it does say, that flash content is present do 
you want to enable flash etc, and it still works assuming the page authors 
have done it right. In my view it will take a couple of years at least 
before its gone, and I say good riddance, provided nothing worse ends up 
being used of course!

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by leonardder** [comment] 2021-03-19 06:42
@feerrenrut Would you be open to a pr that removes flash support from NVDA?

**Comment by feerrenrut** [comment] 2021-03-22 06:43
Yes, I think we can go ahead with removing Flash.

**Closed** 2021-03-23 09:46 UTC
