### ISSUE TITLE
Add-on store - Add-on information is in English

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#14973] opened 2023-06-06 11:59 UTC
### Steps to reproduce:
* Open add-on store in available add-on and installed add-on tabs
### Actual behavior:
The add-on name and the add-on description are in English no matter NVDA's language.
### Expected behavior:
The add-on name and description should honor NVDA's language if a translation exists in the add-on.
### NVDA logs, crash dumps and other attachments:
N/A
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
nvda_snapshot_alpha-28355,02199b76
#### Windows version:
Windows 10 21H2 (AMD64) build 19044.2965
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
N/A
#### If NVDA add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, unrelated

### Additional note

* Regarding the installed add-on tab, it's a regression with respect to old add-on manager which displayed translated information for installed add-ons (and for incompatible add-ons).
* Regarding the available add-on, browsing the community website where the information is translated may be preferred by non-English speaking users.
* IMO translation should be priorized and even included in 2023.2 if we want the add-on store to be accepted and adopted by non-English speaking users (who are the majority of the users). I fear however that providing translation for the available add-ons tab may be an important piece of work requiring an evolution in the add-on store database.

**Comment by seanbudd** [comment] 2023-06-07 00:39
Hi @CyrilleB79, thanks for making an issue for this.
We aim to have translations supported both in NVDA and the `addon-datastore` server side ecosystem by 2023.2.

**Comment by ruifontes** [comment] 2023-07-05 13:21
Testing with NVDA Alpha-28584,5c4e6e1f all add-ons installed from the store have the name and description in english, since the information is based on .JSON file...
Add-ons installed from external sources have the name and description in NVDA language, in my case portuguese.
So, it seems that is enough to installed add-ons get the information from same place of external add-ons to solve the problem of no translation in the installed add-ons list...

**Comment by seanbudd** [comment] 2023-07-17 03:45
This will be closed by

- [ ] #15152
- [x] #15137
- [x] https://github.com/nvaccess/addon-datastore-validation/pull/32
- [x] https://github.com/nvaccess/addon-datastore-transform/pull/23
- [x] https://github.com/nvaccess/addon-datastore/pull/1095
- [x] https://github.com/nvaccess/addon-datastore-transform/commit/490dfe5a9f30cdc3fd8712a6b95d14e0e91bc358

**Comment by seanbudd** [comment] 2023-07-17 04:49
Alpha should now be using translated add-on store data correctly in the available and updatable add-on tab views

**Comment by nvdaes** [comment] 2023-07-17 05:58
> Alpha should now be using translated add-on store data correctly in the available and updatable add-on tab views

Not in alpha-28690,08de8de3

Maybe next Alpha...

**Comment by nvdaes** [comment] 2023-07-17 06:01
Edition of my previous comment: This works in alpha if language is not set to default. If I set the language to Spanish it works well.

**Comment by seanbudd** [comment] 2023-07-17 06:50
@nvdaes - I am surprised if NVDA language is set to default, that this does not work. When using default language, and a Spanish system, can you confirm the value of `cachedLanguage` in `_cachedCompatibleAddons.json` ?

**Comment by nvdaes** [comment] 2023-07-17 06:55
cachedLanguage value is es_ES (not just es)

**Comment by CyrilleB79** [comment] 2023-07-17 08:15
Same here: not working with system language = "fr_FR" vs working with forced language = "fr".

@seanbudd could you please reopen?

Also when fixing this, it may be interesting to test with:
* "fr" (NVDA language) vs "fr_FR" (system language), or the same with "es" vs "es_ES"
* NVDA language = "es_CO", i.e. NVDA language with a country code, opposed to only "es"
* "pt_BR" or "pt_PT": NVDA language with country code for which no NVDA language with no country code exists (i.e. no "pt" version of NVDA exists)

**Comment by ruifontes** [comment] 2023-07-17 11:17
Tried using only "pt" as NVDA language and add-on information is not translated.
Other annoyance is the punctuation announced in english!

**Comment by CyrilleB79** [comment] 2023-07-17 13:37
Reopening, since I realize I can do it myself.

**Comment by josephsl** [comment] 2023-07-17 15:50
Hi, the “pt” folder is part of add-on datastore views branch, caused by add-ons including “pt” in their locale folder. This confirms that manifest folder structure is taken into account when constructing localized metadata, therefore it is really up to add-ons to resolve this. Thanks.

**Comment by seanbudd** [comment] 2023-07-17 23:56
@josephsl - that's correct
The add-ons found in this [GH search](https://github.com/search?q=repo%3Anvaccess%2Faddon-datastore+%22%5C%22pt%5C%22%2C%22&type=code) have translations for "pt". I'm not sure if NVDA will ever use these translations, unless perhaps the default Windows language is set to "pt" without a country code. `pt` is handled as `pt_PT` by gettext in NVDA.

**Comment by seanbudd** [comment] 2023-07-21 03:38
The add-on store server should now fallback to language without locale, if the language with locale is unsupported

**Closed by seanbudd** 2023-07-21 03:38 UTC
Labels: component/i18n, p2, feature/i18n, triaged, feature/addon-store

**Comment by CyrilleB79** [comment] 2023-07-21 07:52
> The add-on store server should now fallback to language without locale, if the language with locale is unsupported

There is still an issue with "pt_PT" not listing the add-ons having only "pt". I have opàened #15173 for this.
