### ISSUE TITLE
error in firefox

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#6495] opened 2016-10-23 15:48 UTC
hello all.

when searching something on youtube, error is happening in firefox.

1. go to youtube.com.
2. in searchbox enter some search query and press enter.

ERROR - scriptHandler.executeScript (19:44:45):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionEditorMozillaIAccessible object at 0x05351610>> with gesture u'numpad enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 128, in script_caret_newLine
  File "speech.pyc", line 691, in speakTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 303, in getTextWithFields
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 252, in _getText
AttributeError: 'NoneType' object has no attribute 'obj'

**Comment by feerrenrut** [comment] 2016-10-25 01:47
Closing as a duplicate of #6496, since we have already looked into that issue.

**Closed by feerrenrut** 2016-10-25 01:47 UTC
