### ISSUE TITLE
Espeak-ng: Pitch and inflection settings are set to 51 instead of 50

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#9811] opened 2019-06-25 23:34 UTC
### Steps to reproduce:
1. go to NVDA voice settings dialog
2. Set pitch and inflection to 50
3. Click "ok"
4. Check with settings ring, and you will see that pitch and inflection are set to 51. This only occurs with espeak-ng, not with other synthesizers. It only happens when you try to set those values to 50, not something else.
### Actual behavior:
Pitch and inflection are set to 51 instead of 50.
### Expected behavior:
Pitch and inflection are set to 50.
### System configuration
windows7 64-bit
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.1.1
#### Windows version:
7
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the issue has been happening since prittey long ago.

**Comment by DataTriny** [comment] 2019-06-26 13:26
Hello, this is due to the fact that the sliders used to control those settings range from 0 to 100, but we only send 0 to 99 ranges to eSpeak. However, here is what I have found in speak_lib.h:
```
espeakPITCH:   base pitch, range 0-100.  50=normal
espeakRANGE:   pitch range, range 0-100. 0-monotone, 50=normal
```

If I set `maxPitch=100` in synthDrivers/_espeak.py everything seems to work as expected.
@leonardder, @michaelDCurran: is this intentional?

**Comment by seanbudd** [comment] 2022-07-19 06:50
It appears that 0-99 (inclusive) is the correct range for pitch for eSpeak.

https://github.com/espeak-ng/espeak-ng/blob/863655903ab6e04e21725075b65ce6a2aa09b5c4/src/libespeak-ng/setlengths.c#L394-L398

NVDAs scale of 0-100 does not map 1-1 with eSpeak's range of 0-99. The will always be one value of the range in eSpeak that will map to 2 values in NVDA. As a result 50 and 51 in NVDA both equal to 51 in eSpeak.

Setting `maxPitch=100` will just mean that NVDA's pitch setting for eSpeak will be the same for 99 and 100.

One thing to consider is using the range 1-100 or 0-99 consistently in NVDA, to match with synthesizers that use the range 0-99.

**Comment by seanbudd** [comment] 2022-07-21 06:43
Closing this as won't fix, this is not a bug that affects the user.

**Closed by seanbudd** 2022-07-21 06:43 UTC

**Comment by XLTechie** [comment] 2022-07-27 06:48
> One thing to consider is using the range 1-100 or 0-99 consistently in NVDA, to match with synthesizers that use the range 0-99.

+1 to that. 1-100 is more user friendly than any zero-based system.
