### ISSUE TITLE
Feature request toggle order of what is read out re controls

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#10752] opened 2020-02-03 18:44 UTC
Win10 / Version: 2019.2.1 / portable

Hello. My request is for an option to read the value of a field or control BEFORE  the information about what the object is. Whether the item has been navigated to by KB, or moused over.

For example, in Firefox and File explorer  I regularly press alt+D to focus the address bar to check the URL or folder path I am on. In FF I also do this to check if the website is secure (as in a https address).

But each and every time I first have to wait for a preamble of:

"Navigation  tool bar
combo box  collapsed
Search with Google or enter address  edit  has auto complete
selected https..."

and

"Address  combo box  collapsed
edit  d
selected ..."

before I find out what I want to know.

This also happens with other things. If filling out a form and wish to tab back to a previous field to check the value, I first have to wait for the notices about how this item has autocomplete enabled, a drop down box that is collapsed etc, before the value is read out.

Now obviously some people prefer to have the info before the value, and there might be times I too would find this useful. hence my request for a togglable option to change the order as the user needds / prefers.

Again, my request is for the order of what is read out by both mouse hover and KB navigation, as I use both to check or work with controls

Note I am not talking about disabling the info 
altogether. There are many times I actually want to know what the object is. I just want it to come AFTER the value, more often than not.

Thanks for reading and hope it is possible.

**Comment by josephsl** [comment] 2020-02-03 19:38
Hi, surprise! You are not the first one to request this, and perhaps one day, it will be possible to configure this. Thanks.

**Comment by Brian1Gaff** [comment] 2020-02-04 08:10
Yes indeed, I seem to recall there are issues of lag introduced when a work 
around to do this was tried last time several years ago. It would be nice 
though to have this sort of thing under a verbosity tab.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Adriani90** [comment] 2020-05-30 00:10
Closing as duplicate of #8909 and #7232..

**Closed by Adriani90** 2020-05-30 00:10 UTC
Labels: close/duplicate
