### ISSUE TITLE
Aria-live "polite" not reading at all

### ISSUE THREAD

**Issue by nattri** [nvaccess/nvda#12464] opened 2021-05-26 13:43 UTC
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)

### Steps to reproduce:
1. Insert new html element to the DOM having aria-live="polite" property
2. Screen reader should announce newly added element as soon as user is idle.

### Actual behavior:
Newly added element is never announced

### Expected behavior:
Should announce newly element with as soon as user is idle (expected behaviour of arial-live="polite")

#### NVDA installed/portable/running from source:
Installed on windows 10 machine

#### Name and version of other software in use when reproducing the issue:
Google chrome - Version 90.0.4430.212

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by cary-rowen** [comment] 2021-05-26 14:26
Hi,

Have you checked the status of NVDA Plus 5?

Thanks!

**Comment by nattri** [comment] 2021-05-27 05:42
> NVDA Plus 5

Hi,

I don't know what that is but, I have download latest NVDA from nvaccess.org.

**Comment by seanbudd** [comment] 2021-06-29 03:59
Hi @nattri. "NVDA+5" refers to pressing your NVDA key and 5. Usually the NVDA key is mapped to capslock and/or insert.

**Comment by ChilupuriAnilReddy** [comment] 2022-08-08 05:01
Do we have solution for this. Facing this issue now.

**Comment by owenniblock** [comment] 2023-07-13 12:08
I've also seen this issue, please let me know if additional reproduction steps would be helpful.

**Comment by Coldknife2** [comment] 2024-01-22 16:18
Same, having the issue also

**Comment by owenniblock** [comment] 2024-01-23 09:43
I do wonder if this is a bug or intended behaviour. Since the content of the element isn't changing (the whole element changes) perhaps not announcing the content is intentional (the same as when a page loads with existing content inside aria-live containers 🤔 

To work around this issue, we've created an aria-live element that exists on every page and we update that with our updates. It's not perfect but it gets around this issue (which is especially common when we're using React and a whole section of the DOM gets swapped out.

**Comment by Adriani90** [comment] 2024-11-19 19:21
Closing as invalid, per last comment by @ramoncorominas. If you are having still any other arguments why this should not be the expected behavior, please comment and we can reopen.

**Closed by Adriani90** 2024-11-19 19:21 UTC
Labels: close/invalid, ARIA, p3, triaged

**Comment by Adriani90** [comment] 2024-11-19 19:22
See also related issues #15857 and #13774.
