### ISSUE TITLE
Word document is not scrolled to selected Illustration when moving in tab loop with NVDA

### ISSUE THREAD

**Issue by WiproPSAccTest** [nvaccess/nvda#9396] opened 2019-03-22 08:54 UTC
### Steps to reproduce:
1. Open a multipage word document with multiple objects(PIcture/Shape/SmartArt/Chart/Video/icon etc)
2. All object should be "Inline with Text" (Select object and then Navigate to related Format tab -->then "Wrap Text" and chose Inline with text.
3. Insert all these illustrations and write something in next line then again insert illustration and write something in very next line (Means insert Image in line 1(Make it inline with text) --> press enter-->Insert anything in line 2-->Press Enter-->Insert Shape in line 3 (Make it inline with text)-- >press enter-->Insert anything in line 4-->Press Enter-->Insert illustration in line 5 and so on)
4. Select the first object using Ctrl+Alt+5 and use Tab to loop through the different objects
5. Observe that when object of next page is get's selected then also doc is not scrolled to the selected object. NVDA is announcing about the selected content.

### Actual behavior:
Document is not scrolled to selected object when moving in tab loop with NVDA

### Expected behavior:
Document should scroll to the selected object position as if user is showing the document to any normal person then user may think that the content which they can hear is visible to the another user but that is not actual case here.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No

**Comment by Adriani90** [comment] 2024-05-29 20:43
@WiproPSAccTest are you still seeing this issue with NVDA 2024.2 Beta?
Is this issue reproducible when you use focus mode? Or only in browse mode?
Also is there any difference when you enable / disable UIA for Microsoft word in NVDA's advanced settings?

**Comment by Adriani90** [comment] 2024-11-07 15:15
@msftedad can you please test whether this issue is still reproducible with NVDA 2024.4? See also my last comment above.

**Comment by msftedad** [comment] 2024-11-08 12:18
Hi @Adriani90, we will discuss with the PO team and update you soon.

**Comment by Adriani90** [comment] 2024-11-11 14:01
Thank you very much for testing, this is very appreciated. I am closing as works for me. If anyone still has this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-11-11 14:01 UTC
Labels: close/worksforme, app/microsoft-office
