### ISSUE TITLE
NVDA logs lots of errors when opening and, closing and focusing edge tabs after some time

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#14791] opened 2023-04-05 06:29 UTC
### Steps to reproduce:
open, close or focus edge tab after 20-30 minute usage of the browser
### Actual behavior:
NVDA logs errors and makes it impossible to automatically focus a tab.
User needs to press for example tab key to fire a focus, but in this case focus which was already saved is no more valid and user needs to do more actions to get to the place where they were.
### Expected behavior:
No errors should be logged and focus should be placed where user left on previous tab when closing a current tab
### NVDA logs, crash dumps and other attachments:

ERROR - comtypes._comobject.call_without_this (10:03:53.369) - Dummy-2 (6100):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 154, in call_without_this
  File "UIAHandler\__init__.pyc", line 712, in IUIAutomationEventHandler_HandleAutomationEvent
  File "comtypes\__init__.pyc", line 278, in __getattr__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147220991, 'An event was unable to invoke any of the subscribers', (None, None, None, 0, None))
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-27996,d8396f9b (2023.2.0.27996)
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2728
#### Name and version of other software in use when reproducing the issue:
Microsoft edge Version 111.0.1661.62 (Official build) (64-bit) Version 111.0.1661.62 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2023-04-05 12:25
Did you set the UIA in Edge setting in NVDA's advanced settings to "yes"? Or how is that set on your side? I cannot reproduce when having the UIA in Edge set to"standard (when necessary)".

**Comment by Adriani90** [comment] 2023-04-05 12:35
Maybe not 100% related to Edge, but might help to understand where it could come from:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/36cbac92-cdb1-4c60-b4fd-54fc6b72c75e/an-event-was-unable-to-invoke-any-of-the-subscribers-ui-automation?forum=winappswithnativecode

Are you having this issue on 2023.1 stable release as well?

**Comment by beqabeqa473** [comment] 2023-04-05 12:40
Cannot test now.
I am not sure test with portable version will be sufficient, but anyway, i will try to test at week-ends

**Comment by Adriani90** [comment] 2023-04-20 18:59
Closing as duplicate of #14219.

**Closed by Adriani90** 2023-04-20 18:59 UTC
Labels: close/duplicate, app/edge/anaheim, blocked/needs-info, blocked/needs-technical-investigation

**Comment by beqabeqa473** [comment] 2023-04-20 19:33
wrong reason

On 4/20/23, Adriani90 ***@***.***> wrote:
> Closed #14791 as completed.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/14791#event-9060604247
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Adriani90** [comment] 2023-04-20 19:57
Please elaborate on this. What makes you think it is wrong? The error is the same and it appears in similar if not even the same situation.
