### ISSUE TITLE
Nvda gets extremely slow in excel

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#11661] opened 2020-09-23 14:21 UTC
### Steps to reproduce:
create a spreadsheet in excel, type a large amount of text in a cell
press enter to go...
### Actual behavior:
nvda is extremely slow mainly to edit in a new cell.
### Expected behavior:
nvda should work correctly.

more information:

If you type a small amount of text into a spreadsheet, there are usually no crashes.
it is necessary sometimes to type in several cells for the problem to happen.
I uninstalled office 2016 and reinstalled, and before office automatically updated the problem did not occur, the original installed version of office was something like 16.0.4xxx.
When the office updated to the EXCEL.EXE version, Microsoft Office 16.0.13127.20408
the problem returned.
The problem does not occur with the narrator.
I have already uninstalled and reinstalled nvda, as well as running without add-ons and the error occurs.
I also ran the registry fix with
the error persists.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
nvda.exe, NVDA alpha-21012,66bcf8ea

#### Windows version:
10 19042.508
#### Name and version of other software in use when reproducing the issue:
EXCEL.EXE, Microsoft Office 16.0.13127.20408

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes
log:
[travando excel.txt](https://github.com/nvaccess/nvda/files/5268758/travando.excel.txt)

**Comment by Adriani90** [comment] 2020-09-23 22:23
Did you by chance enabled Use UIA support in Microsoft Word" in NVDA's advanced settings? Note that while this setting is labeled for Microsoft Word, it impacts all the MS Office products including MS Excel.

**Comment by fernando-jose-silva** [comment] 2020-09-24 00:10
yes, uia is enabled.
I disabled it and it seems to have no effect, it remains slow in excel if the text in a cell is very large. Thank you.

**Comment by leonardder** [comment] 2020-09-24 06:19
UIA in Word does not have effect in Excel. See https://github.com/nvaccess/nvda/issues/6587, where this was discussed I believe.

**Comment by DGartmann** [comment] 2020-09-24 07:36
I am experiencing the slowness issue in Excel as well. I use Office 365.

**Comment by comanna** [comment] 2020-09-24 09:13
Hi all you patient Excel users!

 

I have had this trouble, too! It was not an NVDA problem in my cases. 

 

I sometimes have a large workbook with many pages full of formulas that are doing a lot of recalculating. I found the whole workbook becoming frustratingly slow. After much searching, I realised that I was recalculating after every keystroke. Turning off “automatic calculation” relieved that problem but left me having to press F9 every time I needed to see a result. 

 

I learned that Excel is bad at clearing the cache as you work. The clipboard can get clogged.

 

I found this  article which touches at least five of the issues that I faced. So, I hope it helps to relieve you of this awful problem:

https://www.pcworld.com/article/229504/five_excel_nightmares_and_how_to_fix_them.html

 

I gave up the elaborate formulas and learned to write macros instead. At first, the macro worked almost instantly instead of the lengthy waiting periods previously experienced. Then I found that running the same macro on a large file with many repeated tries, slowed down excel again! However, it is easy to close Excel and start again when all the instructions are in a macro and return to  a nice quick flow again.

 

I hope these notes and the link above resolves your difficulty!

 

All the best,

 

Cearbhall

 

m +353 (0)833323487 Ph: _353 (0)1-2864623 e: cearbhall.omeadhra@blbc.ie

**Comment by fernando-jose-silva** [comment] 2020-09-24 13:00
thank you very much for returning.
 I believe my problem is another, the problem occurs even when the spreadsheet in question does not have formulas, it seems that the trigger is when a cell has enough text or not to fit in the cell.

**Comment by comanna** [comment] 2020-09-24 15:07
Hi, Fernando-Jose,

I don’t understand what you mean when you say: “it seems that the trigger is when a cell has enough text or not to fit in the cell.”

 

Are you saying that you hit the maximum amount of text that can fit in one cell? Does this happen when only one cell is full or must there be a number of cells filled up?

 

 

All the best,

 

Cearbhall

 

m +353 (0)833323487 Ph: _353 (0)1-2864623 e: cearbhall.omeadhra@blbc.ie

**Comment by fernando-jose-silva** [comment] 2020-09-24 20:50
sorry, this is a translated text.  the error occurred with 2 cells with 30 characters

**Comment by fisher729** [comment] 2020-09-25 10:09
Hi.

Which versions of NVDA did you try this with, and what was the result? I can say that I am not experiencing this issue, even filling the cells with hundreds of characters.

**Comment by cary-rowen** [comment] 2020-09-25 11:35
Not only EXCEL but also Visual Studio are slow to respond.

**Comment by fernando-jose-silva** [comment] 2020-09-25 11:48
I noticed the problem in the last alphas, sorry I can't speak specifically the alpha number, it also occurred with 2020.2.The office is 32 bits,

**Comment by codeofdusk** [comment] 2020-10-12 05:53
There is work to add UIA support for Excel, which greatly improves performance on my system. See the excelWithUIA branch. Cc @michaelDCurran.

**Comment by Adriani90** [comment] 2023-03-15 15:34
@fernando-jose-silva I cannot reproduce this issue with NVDA 2023.1 RC1 and Excel 2016 or Excel 365. Is this issue still occuring? If yes, could you please change the Office language in Excel file menu / settings and test again?
I entered about 700 characters with all different punctuations and did this for more than 2 cells. I don't see any performance issue.

**Comment by fernando-jose-silva** [comment] 2023-03-15 19:59
I don't have that problem anymore, thank you very much.

**Comment by Adriani90** [comment] 2023-03-15 20:58
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2023-03-15 20:58 UTC
Labels: close/worksforme
