### ISSUE TITLE
Problem navigating web content in Edge

### ISSUE THREAD

**Issue by FelixGruetzmacher** [nvaccess/nvda#7206] opened 2017-05-25 08:02 UTC
### Steps to reproduce:
1. Open Microsoft Edge.
2. Go to www.heise.de
3. Press "h".

### Expected behavior:
First heading on page should be navigated to.

### Actual behavior:
Nothing is spoken, and NVDA becomes unresponsive in that Edge window.

### System configuration:
NVDA version:
2017.2 RC1

NVDA Installed or portable:
Installed.

Windows version:
Windows 10 Creators Update

### Other questions:

Does the issue still occur after restarting your PC?
Yes.

Have you tried any other versions of NVDA?
No.

**Comment by jcsteh** [comment] 2017-05-26 00:13
Confirmed. The Edge content process is actually crashing and restarting (the process id for the document area changes). So, this is a bug in Edge we'll need to report to Microsoft. The question is what is triggering this bug.

**Comment by FelixGruetzmacher** [comment] 2017-05-26 08:45
Just found out it also happens when just arrowing down for some time.
Arrowing down until it says "Kontakt" then one more press of down arrow will do it.
So maybe something on the page causes it when traversed.

**Comment by leonardder** [comment] 2017-05-26 09:19
I've seen similar things incidentally, even on the nv access home page. NVDA freezes and after a restart, the Edge window reports itself as not responding.

**Comment by gdata1** [comment] 2017-05-26 10:57
Hello. I have the same problem, and it's the same when I click the Start button. Number of my problem # 7181

**Comment by ehollig** [comment] 2018-10-13 00:08
I am getting the expected behavior when I perform the below steps. The first heading is navigated to. I am using Edge 42.17134.1.0. Please reopen if I missed something. Closing.

> ### Steps to reproduce:
> 
>     1. Open Microsoft Edge.
> 
>     2. Go to [www.heise.de](http://www.heise.de)
> 
>     3. Press "h".
> 
> ### Expected behavior:
> 
> First heading on page should be navigated to.

**Closed by ehollig** 2018-10-13 00:08 UTC
Labels: Edge, appCrash, freeze, needsExternalFix, p2

**Comment by Adriani90** [comment] 2020-04-30 21:27
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
