### ISSUE TITLE
allow the user to specify where data is stored, to support cloud-synced data directories

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#11525] opened 2020-08-25 22:09 UTC
### Is your feature request related to a problem? Please describe.
Not really.

### Describe the solution you'd like
It seems like it should be possible to use cloud solutions to sync user settings, installed add-ons, and the like. For instance, add a pronunciation dictionary item on your work computer, and it shows up on your personal laptop.

To support this without NVDA having its own cloud infrastructure, allow the user to decide where data goes. That is, allow %appdata%\roaming\nvda to be set to, say, c:\users\user\dropbox\apps\nvda. This way, you need only restart NVDA on any computer actively using that Dropbox account to pick up changes made on any other computer. This would work with other services, such as iCloud for Windows or Google Drive.

The two use cases that I can think of are:

* easily sync settings between multiple machines, such as work/school/home
* when setting up a new computer, use default settings long enough to set up your cloud service of choice, wait for the service to download all your files, restart NVDA, and have all your settings immediately restored

The problems that come to mind are:

* add-ons that require activation, such as the Nuance speech add-ons, may have trouble
* add-ons with a lot of data, such as Nuance, may want to look into alternative data storage, such as running from the configured user data folder but saving voices in %appdata%\local. If a voice is not present when NVDA starts, fall back to a different voice and start downloading the needed voice to %appdata%\local.

### Describe alternatives you've considered

* a dedicated cloud syncing service would be expensive to build and maintain
* running a portable version of NVDA from Dropbox was sluggish when I tried it a year or so ago, and requires syncing more data than only settings
* a VoiceOver-style mechanism, like portable preferences, means dealing with external drives and having the user remember to move the drive from machine to machine all the time

### Additional context
I don't think any is needed.

**Comment by lukaszgo1** [comment] 2020-08-25 22:13
Duplicate of #11129

**Comment by feerrenrut** [comment] 2020-08-26 08:31
You may want to investigate if using the `--config-path=CONFIGPATH` option. For more info see https://www.nvaccess.org/files/nvda/documentation/userGuide.html#CommandLineOptions

You could modify the NVDA shortcut to include this command line option.

**Comment by mehgcap** [comment] 2020-08-26 11:05
Thank you, this will work. I'd still suggest this setting be available in the settings GUI, for easier access and to make syncing of this directory easier to set up for those less comfortable with modifying shortcuts or launching from the command line.

**Closed** 2020-08-26 11:04 UTC

**Comment by feerrenrut** [comment] 2020-08-26 11:22
I agree it could be made more user friendly, though a configurable settings location opens the doors to a lot of potential issues.

**Comment by XLTechie** [comment] 2020-08-26 13:00
Alex Hall wrote:

> Thank you, this will work. I'd still suggest this setting be available in the settings GUI, for easier access and to make syncing of this directory easier
> to set up for those less comfortable with modifying shortcuts or launching from the command line.

Do you really think that "those less comfortable" should be messing around with 
such a setting, or such a setup?

Consider what might happen if the multiple versions of NVDA installed across 
different machines, but accessing the same config, were desynchronized.
Consider what might happen if there was a config schema update.

I wonder about how Add-on Updater would play with this setup.
And other add-ons that might be running concurrently on different machines, 
updating data on disk (for those that do), without appropriate locks and 
concurrency checks.

Also, what about NVDA exits or other cases of config saving?  You may run into 
the situation of multiple NVDAs saving different versions of the config file, 
and stomping on each other.
And how would gestures.ini work under such a setup?

It's not like a config database with locking rows; we're dealing with text and 
binary datafiles here.

To me, unless a lot more development goes into it, this really shouldn't be 
unleashed on someone who would be squeamish about modifying a shortcut, or 
dealing with commandline options.  This is an advanced user concept if ever 
there was one.
