### ISSUE TITLE
Name of the sender should be announced when navigating to the next/previous checkbox while using gmail website.with hot key 'x' 

### ISSUE THREAD

**Issue by yogeshtaneja12** [nvaccess/nvda#11390] opened 2020-07-16 19:00 UTC
Actual behavior:
When letter 'x' is pressed on gmail, it only announces "check box not checked".
Expected behavior:
When navigating to the checkbox with hot key 'x' the sender's name should also be announced as it will make the navigation quicker and user will be able to decide weather to open that mail or to delete that mail.
Steps to reproduce:
1. open www.gmail.com
2. login with the user name and password.
3. you will be landed in the inbox of your mail, use 'x' to jump to the checkbox of your first mail.
4. it announces check box not checked".
system configuration:
Windows 10.
Browser: Google chrome, firefox and internet explorer.

**Comment by Adriani90** [comment] 2020-07-16 20:31
I can not reproduce this in any browser. NVDA report "unread <sender> <subject> etc. when pressing x.
Did you try to run the COM registration fixing tool in NVDA settings / tool?
Also did you try to reproduce this with all addons disabled?

**Comment by Adriani90** [comment] 2020-07-16 20:32
Also sender, subject and so on is read when pressing x.

**Comment by Adriani90** [comment] 2020-07-17 19:55
Ok the only browser I can reproduce this in is Internet Explorer.

**Comment by yogeshtaneja12** [comment] 2020-07-18 14:38
Hello,

I am still able to reproduce the same. If we use downarrow after
pressing 'x'  then only it reads the sender's name though is should
announce the sender's name with checkbox status.


On 7/18/20, Adriani90 <notifications@github.com> wrote:
> Ok the only browser I can reproduce this in is Internet Explorer.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11390#issuecomment-660309594


-- 
Thanks/Regards,
Yogesh Taneja,
President |Cricket Association for Blind in Delhi
Mob: +91- 99 71 93 87 37
Skype ID:yogesh.taneja

**Comment by Adriani90** [comment] 2020-07-20 17:53
@yogeshtaneja12 this is expected behavior since the checkbox and the senders name are in different columns of the table. If you want to hear the checkbox status first, you have to use ctrl+alt+arrow keys which is the standard way of table navigation in NVDA. Or you press x, then down arrow, then up arrow. This would also give you the checkbox status directly.

I am closing this issue. But feel free to comment if I missunderstood the problem here and we can reopen. Thanks.

**Closed by Adriani90** 2020-07-20 17:53 UTC
Labels: app/internet-explorer, close/worksforme

**Comment by yogeshtaneja12** [comment] 2020-07-21 11:52
Hello,

Yes, the sender's name is in different column. But if you use the
quick key navigation 'X' to move to the next checkbox, the screen
reader JAWS says "name of sender check box not checked" which help
users to decide to change the state of the checkbox if they are
deleting multiple mails.

On 7/20/20, Adriani90 <notifications@github.com> wrote:
> Closed #11390.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/11390#event-3567095398


-- 
Thanks/Regards,
Yogesh Taneja,
President |Cricket Association for Blind in Delhi
Mob: +91- 99 71 93 87 37
Skype ID:yogesh.taneja
