### ISSUE TITLE
When typing in the search edit box on LinkedIn.com, NVDA speaks characters when typing echo is off and speaks double characters when typing echo is turned on.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4928] opened 2015-02-17 04:38 UTC
**Reported by dgoldfield on 2015-02-17 04:38**
When you go to LinkedIn.com and type text in the first edit box which is used for searching, NVDA speaks the names of characters if typing echo is turned off, although it does not speak the spacebar. If you turn keyboard echo on, NVDA speaks the character twice. I am not able to duplicate this so far in other edit fields on other pages.

**Comment by ehollig** [comment] 2017-08-03 22:40
I am not able to reproduce this in Firefox or Chrome, and if @jcsteh is right in https://github.com/nvaccess/nvda/issues/4928#issuecomment-155334672 that this is a live region, this is not an NVDA issue, but an authoring error. Closing

**Closed by ehollig** 2017-08-03 22:40 UTC
Labels: bug
