### ISSUE TITLE
character navigation only reports character from the right site of the visual marker

### ISSUE THREAD

**Issue by NicklasMCHD** [nvaccess/nvda#7580] opened 2017-09-09 19:22 UTC
Hi.
This is about the navigation in nvda (request to make it like Mac OS Voice Over and iOS Voice Over) character

### Steps to reproduce:
1. Open any text editor.
2. Type something (for this example we'll just use "hello world").
3. Go to a letter (we'll use "r" in world as the example).
4. Then if you press backspace (delete) it should delete "r" not "o".
5. Optional: if you press left arrow and then right arrow, it should move a whole character but just report the same character but move the visual marker to the left and right site of the character.

### Expected behavior:
The functionality like Mac OS or iOS Voice Over character navigation.

### Actual behavior:
The speech only reports whats to the right site of the marker (wich means that if your speech report "r" in "hello world" and you then delete a character you delete "o" not "r").

### System configuration:
version: NVDA 2017.3
NVDA are installed on the machine (but it should work regardless).

Other information:
System OS: Windows 10 (64) build 15063.

Name and version of other software in use when reproducing the issue:
Any application that uses character navigation (everything from web browsers, to email clients, to text editors).

Have you tried any other versions of NVDA?
It have never been a part of NVDA.

**Comment by josephsl** [comment] 2017-09-09 19:24
Hi, this is rather a Windows thing, not really specific to NVDA unless I’m terribly wrong. I request cantfix. Thanks.

**Comment by NicklasMCHD** [comment] 2017-09-09 19:27
It can be done. But it is general practice for windows screen readers not to. But it isn't specific to Windows but something never done for a Windows screen reader, for some strange reason...

**Comment by josephsl** [comment] 2017-09-09 19:32
Hi, sure, it might be possible to do it (notice the difference). What we’re looking for is at least one compelling justification to research this issue. Just saying that you want this in NVDA just because screen readers for other operating systems have this isn’t strong enough (I’d say). Thanks.

**Comment by tbdalgaard** [comment] 2017-09-09 19:35
Hi!

I've tested this myself and can reproduce the issue with both NVDA and JAWS, so it is a thing screenreader manifactures have done for many many years. I became aware of this issue when I picked up my first Mac and later on my iOS device. I first thought it was a Windows issue, but the [Dolphin Guide program](https://yourdolphin.com/product?id=5)
can actually do the expected behaviour, so you should be able to make this an option in NVDA. Perhaps under the keyboard options?

**Comment by josephsl** [comment] 2017-09-09 19:39
Hi, when I tested with no screen reader running and if I move cursor to the letter “r” and press backspace, the letter “o” is deleted. Thanks.

**Comment by tbdalgaard** [comment] 2017-09-09 20:06
Hi Joseph!

That is because the cursor actually is at the letter o. What you never know on Windows is that any screenreader reads to the right of the cursor.
So the first time you press the right arrow you tell the physical cursor to move to the right of the character h. On Mac and iOS we often hear the first character repeated. That is because the screenreader is letting us know that we now are going to the right.
If you do this with NVDA you may notice that after you've pressed the home key NVDA says: Home, h.
That is because NVDA reads to the right side of the physical system cursor. Sighted people have confirmed this to me, but I fully understand the confusion here, because screenreader manifactures for years have hidden this information from us.

**Comment by josephsl** [comment] 2017-09-09 20:11
Hi, before I let others get involved, I need one more confirmation: is Narrator doing the same thing? If Narrator is behaving like VoiceOver, then that’s a compelling justification because it forces us to approach this from consistency point of view. CC @MichaelDCurran, @DerekRiemer

**Comment by bdorer** [comment] 2017-09-09 23:14
Hi,

your example is wrong for Deletion on Windows. I don't know the mac 
keyboard but on iOS you have only one delete key. In Windows you have 
one delete key which remooves the right character. Pressing backspace 
will delete the left character so you're more flexible while deleting.
Furthermore deleting Text is done by your text editor not by NVDA so 
this part is can't fix.

Am 09.09.2017 um 21:22 schrieb Nicklas Tegner:

**Comment by derekriemer** [comment] 2017-09-10 08:47
Closing as wontfix, and cantfix. The delete key already deletes the character you are on, and the backspace key is designed to delete backward. Even if we could fix this reliably in all applications, this is an operating system feature, not a screen reader feature. NVDA is designed to help you read the screen, not force its will on how you navigate. There are good cases for backspace to do something other than what it already does in some apps (Like delete the selection, delete a whole email in gmail) and much more. This is not something NVDA would be able to, nor should override.

**Closed by derekriemer** 2017-09-10 08:47 UTC

**Comment by derekriemer** [comment] 2017-09-10 08:49
edited to add clarification on what I meant by email.
