### ISSUE TITLE
Message dialog "nvdaHelperRemote (outprocMgrThreadFunc) Error registering focus winEvent hook" at startup, no focus events working

### ISSUE THREAD

**Issue by MarcoZehe** [nvaccess/nvda#11443] opened 2020-07-31 04:16 UTC
### Steps to reproduce:

1. Install latest alpha snapshot and start it.

### Actual behavior:

Immediately, the above error dialog appears. After okaying it, no focus events work in any application.

### Expected behavior:

No error, normal focus events.

#### NVDA installed/portable/running from source:

Installed.

#### NVDA version:

alpha-20655,39606f14

#### Windows version:

10. 2004.

#### Name and version of other software in use when reproducing the issue:

Firefox, Slack, Outlook.

#### Other information about your system:

Braille display connected.

#### Does the issue still occur after restarting your computer?

No, after two restarts, the error went away.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Earlier alphas, they also exhibit this issue all of a sudden.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No.

CC @michaelDCurran

**Comment by MarcoZehe** [comment] 2020-07-31 04:39
Update: After two restarts of my PC, the error went away even with the latest alpha build.

Mick, do you want to keep this open, or can this sometimes happen if one switches screen readers too often during a Windows session? I was doing comparative NVDA and JAWS testing yesterday, and the error started happening after I woke up the machine this morning and installed the latest snapshot.

Feel free to close this if you feel it is a glitch NV Access can't do anything about.

**Comment by CyrilleB79** [comment] 2020-07-31 05:26
Duplicate of #7834.

**Comment by Adriani90** [comment] 2020-07-31 12:51
Closing as duplicate

**Closed by Adriani90** 2020-07-31 12:51 UTC
Labels: close/duplicate

**Comment by Brian1Gaff** [comment] 2020-08-01 07:27
I had this also occur after a system restore to earlier the same morning. No 
obvious reason for it I could see.
 Obviously some file gets out of sync somewhere.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----
