### ISSUE TITLE
Unable to read E-mail in windows mail application

### ISSUE THREAD

**Issue by gauravahir28** [nvaccess/nvda#16781] opened 2024-07-01 03:51 UTC
### Steps to reproduce:
- Open the windows mail application.
- Open Open any e-mail present in the inbox.
- use arrow keys to read the e-mail content.
### Actual behavior:

NVDA plays the error sound, and does not read any content.
### Expected behavior:

NVDA should read the content present  in the e-mail.
### NVDA logs, crash dumps and other attachments:
ERROR - eventHandler.executeEvent (09:18:47.788) - MainThread (9472):
error executing event: gainFocus on <NVDAObjects.Dynamic_MailWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIA object at 0x01862790> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 340, in executeEvent
  File "eventHandler.pyc", line 415, in doPreGainFocus
  File "browseMode.pyc", line 1554, in event_treeInterceptor_gainFocus
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 314, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 437, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
ERROR - scriptHandler.executeScript (09:18:48.580) - MainThread (9472):
error executing script: <bound method CursorManager.script_moveByLine_back of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x01862C90>> with gesture 'up arrow'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 270, in script_moveByLine_back
  File "cursorManager.pyc", line 171, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 314, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 437, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2024.3 Beta 1
#### Windows version:
Windows 11 23H2
#### Name and version of other software in use when reproducing the issue:
Windows mail Version 16005.14326.21968.0
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Was working with NVDA 2024.2
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2024-07-01 04:21
Closing as duplicate of #16689

**Closed by seanbudd** 2024-07-01 04:21 UTC
Labels: close/duplicate
