### ISSUE TITLE
Ability to set specific voices for specific language 

### ISSUE THREAD

**Issue by sine-w** [nvaccess/nvda#10479] opened 2019-11-11 11:57 UTC
#6377 # Is your feature request related to a problem? Please describe.
Now If I choose Windows One Core as the default TTS, then select Tracy (Hong Kong Cantonese) as the primary voice
and enable auto language switching

Issue 1:
NVDA still use Cantonese voice to speak many of the English 
NVDA can use Tracy to read Chinese word, but most  of the English are still be processed by Tracy 
Only few situation, e.g. reading some English from overseas website, NVDA will use English voice to read English content

Issue 2:
For those situation where NVDA auto switched to English voice,
NVDA auto selected one of the male voice to process English, where I prefer female voice instead of the male voice, however I have no way to configure this  
 
 ### Describe the solution you'd like
Referenced to the IOS Voiceover,
Voiceover can allow user to set specific voice for particular language.
e.g. under English US, if we selected Ava, then after auto language switching, Voiceover will only use Ava to read English 
   
   Therefore, I would like NVDA to have a similar function.
   If a multi-voice TTS is being selected, e.g. sspeak, Microsoft One Core, etc, instead of just choosing the primary voice,
   we can make further configuration by setting voices for specific language.
   
### Additional context
Take Windows One core as an wxample
NVDA can set to exclude some of the voices for auto language switching, so that those voices will not be applied during auto switching

**Comment by Adriani90** [comment] 2020-05-27 22:48
Closing as duplicate of #406 and #279 which also contains an entire driver.

**Closed by Adriani90** 2020-05-27 22:48 UTC
Labels: close/duplicate
