### ISSUE TITLE
NVDA hangs when a program crashes

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#9036] opened 2018-12-09 04:41 UTC
### Actual behavior:
When a program that has focus crashes or hangs, NVDA does the same. Usually, I have to restart NVDA or "blindly" press ENTER to dismiss the supposed generic program crash message (the one with buttons to send a report to Microsoft.)

### Expected behavior:
NVDA's responsiveness shouldn't be reliant on programs running correctly.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2018.3

#### Windows version:
10, 1803

#### Name and version of other software in use when reproducing the issue:
I've seen this happen with Microsoft Word and other similar large programs.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes. It happens on all of them.

**Comment by Adriani90** [comment] 2020-05-11 00:02
I think @tspivey developed an addon for killing nvda in certain situations. I also have alot of problem at work when programs are crashing and NVDA becomes silent.
In this case it seems the warning promt from Windows asking if you want to close a program which crashed causes NVDA to become silent for whatever reason.
cc: @josephsl

**Comment by Adriani90** [comment] 2020-05-11 00:03
In general, it should not be required to kill NVDA in order to solve such issues, so I hope that a solution will be found in which NVDA can handle the warning promt properly without becoming silent at all.

**Comment by Adriani90** [comment] 2023-03-29 23:08
The addon mentioned above is called Kill NVDA and can be found here:
https://github.com/tspivey/killNVDA

**Comment by Adriani90** [comment] 2024-05-28 17:27
@munawarb can you still reproduce this issue with NVDA 2024.2 Beta? In my tests NVDA always reports the restore or programm exit windows when a program crashes. I cannot reproduce this anymore.

**Comment by munawarb** [comment] 2024-05-28 22:52
Hi,I’ll let you know if I get this issue again but so far I haven’t had a program crash like that in quite some time. I used to notice the hang mostly while trying to connect to an inaccessible network drive.On May 28, 2024, at 1:27 PM, Adriani90 ***@***.***> wrote:﻿
@munawarb can you still reproduce this issue with NVDA 2024.2 Beta? In my tests NVDA always reports the restore or programm exit windows when a program crashes. I cannot reproduce this anymore.

**Comment by Adriani90** [comment] 2024-06-08 22:33
@munawarb thanks for your update. I am closing this for now, but feel free to comment as soon as it occurs again and we can reopen.

**Closed by Adriani90** 2024-06-08 22:33 UTC
Labels: close/worksforme
