### ISSUE TITLE
Search and column sorting in dictionnary

### ISSUE THREAD

**Issue by iubito** [nvaccess/nvda#10897] opened 2020-03-25 08:14 UTC
### Is your feature request related to a problem? Please describe.
In the dictionnary dialog, it's very hard to find a previously entered word to change its pronounciation. No search field like in punctuation dialog, no sorting when clicking on headers

### Describe the solution you'd like
A search field on top of the dialog, like in punctuation dialog
Allowing sorting on columns

### Describe alternatives you've considered
I browse line by line, and I never find the word I want to correct 👎

**Comment by DrSooom** [comment] 2020-03-25 21:05
Duplicate of issue #2478, #8547 and #8548.

**Comment by feerrenrut** [comment] 2020-03-30 13:56
Closing as:
duplicate of #2478
duplicate of #8547
duplicate of #8548

**Closed by feerrenrut** 2020-03-30 13:56 UTC
