### ISSUE TITLE
NVDA reading script font by announcing letters and numbers. for instance, the sentence "A new "on-demand" speech mode has been added." it reads: 𝓐 𝓷𝓮𝔀 "𝓸𝓷-𝓭𝓮𝓶𝓪𝓷𝓭" 𝓼𝓹𝓮𝓮𝓬𝓱 𝓶𝓸

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#16108] opened 2024-01-29 21:02 UTC
### Steps to reproduce:
Start menu>Documents>What's New in NVDA 2024.1Beta6.docx>press Enter>press arrows to read
### Actual behavior:
NVDA reads characters written in script font by mixing letters and numbers. i followed the following steps to reach and read the document with script font characters:
Start  window
Search  window
Search box  edit  Search for apps, settings, and documents  blank
tab
Pinned  list
Microsoft Edge  1 of 6
Microsoft Edge  tool tip
tab
All apps  button  Show all my apps and websites
tab
Recommended  list
Google Chrome Recently added  1 of 6
tab
More  button  Show more of my recommended files, apps, and websites
tab
list
User account for Jacob Chawala, you have an important account notification
Jacob Chawala, you have an important account notification  tool tip
right arrow
Places  list
Documents  1 of 7
Documents  tool tip
enter
Documents
Items View  list
What's New in NVDA 2024.1 Beta 6.docx  40 of 40
enter
What's New in NVDA 2024.1 Beta 6.docx - Word
document  page 1  section 1  The following sentence written in English adapted from “what’s new in NVDA 2024.1 Beta 6” will be read 
up arrow
The following sentence written in English adapted from “what’s new in NVDA 2024.1 Beta 6” will be read 
down arrow
as follows in script font:
down arrow
blank
down arrow
English sentence adapted from “What’s New in NVDA 2024.1 Beta 6
down arrow
A new "on-demand" speech mode has been added.
down arrow
blank
down arrow
English sentence in script font:
down arrow
𝓐 𝓷𝓮𝔀 "𝓸𝓷-𝓭𝓮𝓶𝓪𝓷𝓭" 𝓼𝓹𝓮𝓮𝓬𝓱 𝓶𝓸down arrow

### Expected behavior:
NVDA should interpret Script font to be pronounced as in other text written in other normal fonts commonly used.
it should read characters of any language as required. For instance, it should read in English: A new "on-demand" speech mode has been added. instead of announcing in script font: 𝓐 𝓷𝓮𝔀 "𝓸𝓷-𝓭𝓮𝓶𝓪𝓷𝓭" 𝓼𝓹𝓮𝓮𝓬𝓱 𝓶𝓸.
It bores listening to this kind of text in script font.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: 2024.1beta6 (2024.1.0.30866)

#### Windows version:
Windows 11 23H2 Version	10.0.22631 Build 22631

#### Name and version of other software in use when reproducing the issue:
Microsoft® Word LTSC MSO (Version 2312 Build 16.0.17126.20132) 64-bit 
#### Other information about your system:
Machine name: JFC
               Machine Id: {2539A4FE-4CBE-4745-A161-FBBC4A7E6405}
         Operating System: Windows 11 Pro 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: English (Regional Setting: English)
      System Manufacturer: HP
             System Model: HP ENVY x360 Convertible 15-cn0xxx
                     BIOS: F.30 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16204MB RAM

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. the behaviour is the same as this version of NVDA
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2024-01-29 22:40
Closing as duplicate of #3805

**Closed by seanbudd** 2024-01-29 22:40 UTC
