### ISSUE TITLE
braille scroll issue in desktop list with nvda and hims braille display.

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5786] opened 2016-03-02 10:07 UTC
Hello, I’m Hyongsop Kim in Korea.
In nvda with my hims braille display, even if I press braille display scroll keys in desktop, I can’t move the focus to next or prior item.
In other words, in web page or windows explorer, once I press scroll keys, my focus or carret is moving.
But in desktop list, it doesn’t work, and to let focus to move with braille display, I have to press dot 4 or dot 1.
Please check this issue.

Thank you.

**Comment by leonardder** [comment] 2017-07-15 13:44
@khsbory: What Hims display are you using?

**Comment by khsbory** [comment] 2017-07-17 01:21
I'm using BrailleSenseU2.
Thank you.



김 형 섭	 / Hyongsop Kim
(주)엔비전스 / 웹접근성사업팀 팀장	

서울시 종로구 가회동 1-29 
1-29 Gahoe-dong, Jongno-gu, Seoul, Korea
T. +82 70 4900 0895   F. +82 2 313 3645   M. +82 10 5359 5996

http://dialogueinthedark.co.kr
http://cafe.naver.com/dialogueinthedark





-----Original Message-----

**Comment by jcsteh** [comment] 2017-07-17 01:27
This is about moving the focus with the scrolling keys when there is no more text to scroll to; i.e. moving to the next icon on the Desktop. NVDA doesn't currently support this. This is a duplicate of #4097. See the comments on that issue for explanation of the issues involved.

**Closed by jcsteh** 2017-07-17 01:27 UTC
Labels: Braille, bug
