### ISSUE TITLE
NVDA reads out input element title text present in HTML table header for each cell value 

### ISSUE THREAD

**Issue by vikasbansal27** [nvaccess/nvda#7909] opened 2018-01-15 16:16 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>I have an HTML table which has the option of applying filters in the table column header (pretty much like MS Excel). The icon to apply the filter has a title (shown whenever the cursor is over it). While reading the contents of the table, the filter image title is read out for each cell which is very annoying.

### Expected behavior:
> Tell us what should happen.
It should not read out the icon title for each cell value.

### Actual behavior:
> Tell us what happens instead.
It reads out the icon title for each cell value.

### System configuration:
NVDA version:
>2016.3

NVDA Installed or portable:

Windows version:
> Windows 10

Name and version of other software in use when reproducing the issue:
HTML page

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
> N/A

**Comment by PratikP1** [comment] 2018-01-15 16:22
Could you please provide an example page or the code you’re using so that we can test this? Thank you.

**Comment by vikasbansal27** [comment] 2018-01-15 16:29
![code](https://user-images.githubusercontent.com/2263733/34952275-d44a329c-f9de-11e7-9a49-07b49ec81c85.JPG)
![headinginputtitlereadeachtime](https://user-images.githubusercontent.com/2263733/34952276-d45aa14a-f9de-11e7-850d-221e3bd6eb12.JPG)

The highlighted text (in code) is the title of highlighted icon in table header (in table screenshot). The title is repeated for each cell value that is read by NVDA.

**Comment by PratikP1** [comment] 2018-01-15 16:33
Many of the contributors and developers of NVDA are blind and, thus, unable to read the included images.

**Comment by vikasbansal27** [comment] 2018-01-15 17:56
But the image is part of the table header which does not need to mention its presence in every cell.

**Comment by PratikP1** [comment] 2018-01-15 20:55
I understand the concern. What I’m suggesting is that we need to see either the implementation or the code so that we can replicate the issue.

**Comment by vikasbansal27** [comment] 2018-01-15 21:03
Oh I did provide a screenshot above of the HTML table and the code behind being used. Can you tell me what exact part of the code do you need from me?

**Comment by PratikP1** [comment] 2018-01-15 21:05
I and others who may be reviewing this are blind. We cannot read the code that you provided in the screenshot. Do you have a live example that we could actually review with NVDA?

**Comment by vikasbansal27** [comment] 2018-01-15 21:07
Oh I am sorry I misunderstood. I don't have anything live as of now. The implementation is on my local computer. I will have to find a place where I could reproduce it where you could also access.

**Comment by Adriani90** [comment] 2019-05-01 10:34
@vikasbansal27 it is not possible for us to reproduce this issue with the parts of the screenshot. If you could paste some html code in here or an example website which shows this issue, then we can take further steps to improve it. as of now I am closing this issue because we did not get an example for more than one year. Please comment on it with an example or open a new issue. Thanks.

**Closed by Adriani90** 2019-05-01 10:34 UTC
