### ISSUE TITLE
Crash when reloading config

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#13189] opened 2021-12-23 04:25 UTC
While attempting to reproduce #13187 with NVDA 2021.2
I encountered an NVDA crash and then system freeze.
I misread the steps to reproduce, so I am documenting the variation here.

### Steps to reproduce:
I haven't been able to reproduce this, the approximate steps I took immediately before the crash.
- Start NVDA 2021.2
- Open explorer `Win+e`
- Create a profile triggered automatically by explorer
  - `NVDA+n`, configuration profiles, new, type "explorer", use this profile for "current application (explorer)" ok
- Open notepad
- Create a profile triggered automatically by explorer
  - `NVDA+n`, configuration profiles, new, type "notepad", use this profile for "current application (notepad)" ok
- Change symbol level `NVDA+p`
- Focus explorer `Alt+tab`
- Change symbol level `NVDA+p`
- Focus notepad `Alt+tab`
- Reload config `NVDA+ctrl+r`

I also (accidentally) used `NVDA+r` (OCR) then pressed `escape` to leave the OCR result.

### Actual behavior:
While reloading config, NVDA crashed and tried to restart. Then shortly after the system locked up.
The minidump file created was invalid (zero size).

Note the timestamps, watchdog crash entry happened before the prior lines in the log. However there is nothing else that stands out in the log around the `11:31:47.945` mark.
<details><summary>Excerpt from the log
</summary><pre><code>
IO - speech.speech.speak (11:31:47.987) - MainThread (10880):
Speaking [LangChangeCommand ('en_US'), 'Configuration applied']
CRITICAL - watchdog._crashHandler (11:31:47.945) - Dummy-6 (21480):
NVDA crashed! Minidump written to C:\Users\reef-\AppData\Local\Temp\nvda.log\..\nvda_crash.dmp
INFO - watchdog._crashHandler (11:31:50.217) - Dummy-6 (21480):
Listing stacks for Python threads:
Python stack for thread 9544 (braille._BgThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "braille.pyc", line 2201, in func

Python stack for thread 21480 (Dummy-6):
  File "watchdog.pyc", line 212, in _crashHandler
  File "watchdog.pyc", line 62, in getFormattedStacksForAllThreads

Python stack for thread 11556 (watchdog.CancellableCallThread.execute(<CFunctionType object at 0x059440A8>)):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "watchdog.pyc", line 332, in run
  File "threading.pyc", line 552, in wait
  File "threading.pyc", line 296, in wait

Python stack for thread 20932 (watchdog):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "watchdog.pyc", line 111, in _watcher
  File "winKernel.pyc", line 261, in waitForSingleObject

Python stack for thread 3376 (winInputHook):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "winInputHook.pyc", line 79, in hookThreadFunc

Python stack for thread 16272 (_UIAHandler.UIAHandler.MTAThread):
  File "threading.pyc", line 890, in _bootstrap
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "_UIAHandler.pyc", line 340, in MTAThreadFunc
  File "queue.pyc", line 170, in get
  File "threading.pyc", line 296, in wait

Python stack for thread 10880 (MainThread):
  File "nvda.pyw", line 362, in <module>
  File "core.pyc", line 746, in main
  File "wx\core.pyc", line 2237, in MainLoop

INFO - watchdog._crashHandler (11:31:50.217) - Dummy-6 (21480):
Restarting due to crash
</code></pre></details>

Logs:
- [nvda-old-with-crash.log](https://github.com/nvaccess/nvda/files/7766658/nvda-old-with-crash.log)
- [nvda-after-crash-restart.log](https://github.com/nvaccess/nvda/files/7766659/nvda-after-crash-restart.log)

### Expected behavior:
Config should be reloaded without a crash.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.2

#### Windows version:
Windows 10 
Version	21H1
OS build	19043.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
No addons

**Comment by Adriani90** [comment] 2024-05-09 20:07
I ried to reproduce this issue in lots of different situations during last weeks, I couldn't manage to reproduce. NVDA improved a lot since this issue has been reproduced, I am closing as works for me. If this issue is still reproducible for anyone, please comment and we can reopen.

**Closed by Adriani90** 2024-05-09 20:07 UTC
Labels: close/worksforme, bug/crash
