### ISSUE TITLE
Shorten landmark titles on web pages

### ISSUE THREAD

**Issue by vlegoff** [nvaccess/nvda#6160] opened 2016-07-08 18:30 UTC
On the Braille display, when navigating to a webpage, landmarks are displayed as is, without being shortened (like links being shortened to lnk, vlnk for visited links, and so on).  This takes room on the display, particularly since the name of the landmarks isn't shortened either.  One can often see something like:

banner landmark

OR

navigation landmark

On some Braille displays, it takes more than half of the available display, forcing to move to the next line to see what is there.  Some websites extensively use landmarks, which makes it cumbersome to navigation with Braille display.  Is there any way to shorten both the 'landmark' keyword and its name?

nav ldk (navigation landmark) would save much room, for instance.

**Comment by leonardder** [comment] 2016-07-08 20:52
I think this is a good idea, though I'd vote for lm or lmrk to identify 
them. Other abbreviations could be:

* content info: cnfo
* main: main
* navigation: nav
* search: srch
* form: form

Today I've been looking into several element types, and I think more 
elements could be abbreviated in braille. @dkager, what do you think?

**Comment by surfer0627** [comment] 2016-07-08 23:23
See also #3975.

**Comment by josephsl** [comment] 2016-07-08 23:26
Duplicate of #3975, with @dkager saying he'll look into it. Thanks.

**Closed by josephsl** 2016-07-08 23:26 UTC
