### ISSUE TITLE
Do not automatically prompt user to update while reading in say-all mode

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#8441] opened 2018-06-26 00:31 UTC
### Steps to reproduce:

- Read, for instance using Kindle or QRead
- Be prompted to update NVDA

### Actual behavior:

The update notification steals focus and stops say-all

### Expected behavior:

Since the best thing to do is never to steal focus, but since we need to steal focus as otherwise the user won't know that an update may be waiting, the best thing I think we can do here is just not interrupt say-all.
If NVDA is currently reading, I would expect after stopping reading that the update window would then appear, possibly after a short delay.

**Comment by derekriemer** [comment] 2018-06-26 00:58
This is a completely valid request. Speech refactor might help us out with this. To be cleare are you asking for NVDA to not present the update dialog until after the sayall stops, or more specifically not interrupting speech in the middle of text?

**Comment by ctoth** [comment] 2018-06-26 01:33
The former.

**Comment by gregjozk** [comment] 2018-06-27 23:08
Hello,

possible solution might be notification via baloon in system tray like some other notifications such as java update notification etc.
nvda would then only read a notification and continue with reading of text.
this is only one of ideas.

regards

**Comment by PratikP1** [comment] 2018-06-29 21:14
I’d like to see a sound notification as well. So no interruption during read all but perhaps a sound notification. Is this making things too  complicated?

**Comment by bdorer** [comment] 2019-01-13 15:13
I like the idea with a sound. May NVDA could even create a notification in the windows 10 notification center. Should I open a new ticket for this idea as this ticket deals with update notification during say all?

**Comment by Adriani90** [comment] 2023-04-02 19:47
Closing as duplicate of #2257.

**Closed by Adriani90** 2023-04-02 19:47 UTC
Labels: close/duplicate, feature
