### ISSUE TITLE
NVDA+Control+RightArrow(Moves to the next available setting in the synth settings ring) hotkey is not working

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#5796] opened 2016-03-07 09:44 UTC
str:
1. Press NVDA+Control+RightArrow(Moves to the next available setting in the synth settings ring)
- Result: not working. But, numpad+NVDA+Control+RightArrow is working.

- Test NVDA version: next-13251
- Keyboard layout: desktop layout

Please fix this issue. Thanks!

**Comment by jcsteh** [comment] 2016-03-07 11:16
Duplicate of #2637. Unfortunately, certain keyboards just refuse to accept certain combinations of keys. Every keyboard seems to be different in this respect. There's nothing we can do to work around this.

**Closed by jcsteh** 2016-03-07 11:16 UTC
Labels: duplicate
