### ISSUE TITLE
Outlook 2010: Inconsistent Announcement of Capitalisation when Navigating by Word

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10854] opened 2020-03-07 14:39 UTC
### Steps to reproduce:

1. Open Outlook, and open the New Message window

2. In the body of the message, type the following: "A&B Test"

3. Go to the start of the just-entered line, and use ctrl + right to navigate by word

### Actual behavior:

NVDA announces the letter "A" as being capitalised, but does not for the letter "B"

### Expected behavior:

NVDA should treat both letters the same and provide consistent output

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1 with eSpeak and all default settings

#### Windows version:

Windows 7 X64

**Comment by stickbear2015** [comment] 2020-03-07 16:02
This is not specific to outlook 2010.
I can reproduce it using outlook in office365 and a multitude of synthesizers from onecore, to vocalizer from codefactory.

**Comment by Adriani90** [comment] 2020-03-08 21:32
This is only reproducible if there is a space or a white space directly after the letter B.
For example if you type A&B.
or A&B&
then the capitalization is read correctly.
But if you type
A&B 
then the capitalization will not be reported.
cc: @feerrenrut, @lukaszgo1, @leonardder this seems reproducible in any kind of editor. I can reprotuce this in
* Notepad++
* Wordpad
* MS Word
* MS Excel when editing a cell

In edit fields in browsers capitalization is not reported at all when navigating by word. The pitch does not change regardless of small or capital letter.

Interestingly, the only editor where it seems to work correctly is Libre office writer. I wonder how characters are rendered there and what is the difference between Libre office writer and other editors in this regard?

**Comment by Adriani90** [comment] 2020-06-23 19:07
This has been greatly fixed by @JulienCochuyt in #11167. My guess is that capital letters are treated as symbols in some cases.
I am closing as works for me, tested in NVDA Version alpha-20381,c081e515.

**Closed by Adriani90** 2020-06-23 19:07 UTC
Labels: close/worksforme
