### ISSUE TITLE
It is not possible to move caret to review cursor in Android Studio code editor

### ISSUE THREAD

**Issue by PeterLecky** [nvaccess/nvda#14361] opened 2022-11-10 12:17 UTC
### Steps to reproduce:
1. Open Android studio and go to code editor
1. Move caret e.g. to start of some method
1. Press and hold `capslock` (using laptop layout) and press down arrow few times to move review cursor to other place than caret (whole code editor is nicely accessible using review cursor)
1. Press `nvda+shift+backspace` twice to move caret to review 

### Actual behavior:
Nvda speaks line where is the review cursor, but caret is not moved. Use arrows to verify that caret didn't move.

### Expected behavior:
Caret moves to the position of review cursor and current line is announced, same as in other edits e.g. notepad.

#### NVDA installed/portable/running from source:
Tested installed and portable version

#### NVDA version:
tested with Version: 2022.4beta3 (2022.4.0.27128)
And with latest stable with same behavior.
#### Windows version:
2010

#### Name and version of other software in use when reproducing the issue:
Android Studio Dolphin | 2021.3.1
Build #AI-213.7172.25.2113.9014738, built on August 31, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
See above
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2022-11-15 02:48
Closing as a duplicate of #9512. If this is not case, please confirm

**Closed by seanbudd** 2022-11-15 02:48 UTC
Labels: app-specific, component/java-access-bridge
