### ISSUE TITLE
Windows 10/Windows Search: add support for File Explorer embedded search experience in Version 1909 and later

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#10341] opened 2019-10-06 21:11 UTC
Hi,

Another one in a series of issues on Windows 10/Windows Search:

### Background:
Windows 10 Version 1909 (likely to be called October 2019 Update) and later includes online search capability in File Explorer. This feature, powered by redesigned Windows Search, is used to allow users to search OneDrive content. As the search progresses, a live region informs result count. Because of the way search box is handled, braille will initially display "suggestions" instead of displaying this live region.

### Is your feature request related to a problem? Please describe.
As noted above, a live region text is used to announce results count. Unfortunately this region isn't labeled, and the text itself is the first child of this region, necessitating NVDA descending one level to announce this live region.

Also, when using braille, the word "suggestions" is brailed before the live region is displayed. This is caused by search box recognition code in SearchUI app module where Start menu search field is recognized as a pure UIA search field. Thus suggestionsOpened event must be modified in sTart menu search field to not braille suggestions message (a separate issue but is grouped under this one to provide context).

### Describe the solution you'd like
Add support for Version 1909 File Explorer/Windows Search facility by:

1. For the live region: give it the name of the child object so live region change event can function properly.
2. Add a custom version of suggestionsOpened event for Start menu search field so braille won't have to say "suggestions".
3. Optionally, rename searchui.StartMenuSearchField to something else (later).

### Describe alternatives you've considered
Leave it as is.

### Additional context
The fix described above is part of Windows 10 App Essentials add-on and is being tested. Also, it would be ideal to see this feature implemented by 2019.3 or shortly after. Also, in 20H1, Windows Search executable has been renamed to SearchApp.exe, so we need to take care of that by 2020.1 release.

Thanks.

**Comment by feerrenrut** [comment] 2021-07-08 05:46
How to test: 
- Open explorer window `Windows + e`
- Press F3 to focus search
- Type something. Note "10 suggestions available, press down arrow key to access results" announced, this is new.
- Press down arrow, file name and details should be announced

**Comment by feerrenrut** [comment] 2021-07-08 05:47
Sorry, my last comment was intended for the PR. Marking as off-topic.

**Closed** 2021-07-08 06:18 UTC
