### ISSUE TITLE
bug? Caps pitch change not working as it did in older versions

### ISSUE THREAD

**Issue by TechHorseG** [nvaccess/nvda#11442] opened 2020-07-31 03:02 UTC
Hello. I recently updated my portable copy of NVDA from 2019.2.1 to 2020.2 on my Windows10 1909 PC. I have noticed a small few bugs / niggles that I would like to ask about.

Using MS UK George voice.

Basically the pitch change is way less noticeable than it was in the older version. When I first noticed that I wasn't hearing the pitch change for known capital letters I wondered if the update process had turned the setting off, but no, it was still set at 30% as it always had been.

I had to turn it up to 90% to get it sounding something like it used to.

Is this a deliberate choice to make the effect more subtle? I have started using the "say cap" option to make absolutely sure I do not miss a capital. But I prefer the way it used to sound with the pitch change being unambiguous and clearly noticeable, even at 30%..

**Comment by Adriani90** [comment] 2020-08-02 14:48
Closely related to #10896 and #10940.

cc: @michaelDCurran

**Comment by seanbudd** [comment] 2022-07-19 04:37
Closing as duplicate of #7514

**Closed by seanbudd** 2022-07-19 04:37 UTC
