### ISSUE TITLE
nvda freezes in sibelius with wosapi enabled in the sibelius program

### ISSUE THREAD

**Issue by alireza1385mamani** [nvaccess/nvda#17385] opened 2024-11-11 04:55 UTC
### Steps to reproduce:
with nvda wasapi enabled and device set to speakers
1- download sibelius from https://www.avid.com/sibelius
2- install it.
3- when installed open a project from the recent tab.
4- go to the menue and choose the play tab.
5- go to playback devices.
6- go to audio engin options.
7- change the audio interface from the default one to speakers realtech wasapi.
### Actual behavior:

nvda freezes and speech stops completely.
### Expected behavior:

nvda should speak as usual.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2024.3.1.33894
#### Windows version:
Windows 11 24H2 (AMD64) build 26100.1742
#### Name and version of other software in use when reproducing the issue:
sibelius 2024.10
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
nvda 2023 abd erlier versions do have this problem as well.
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
[nvda freeses in siblius.log](https://github.com/user-attachments/files/17695329/nvda.freeses.in.siblius.log)

**Comment by Adriani90** [comment] 2024-11-11 05:34
Can you confirm that this does not happen when Wasapi is disabled in advanced settings?
Please upload a log file with log level set to debug in NVDA general settings.

**Comment by alireza1385mamani** [comment] 2024-11-11 14:00
> Can you confirm that this does not happen when Wasapi is disabled in advanced settings?
it is still happening with wasapi disabled
> Please upload a log file with log level set to debug in NVDA general settings.
[nvda freezes sibelius.log](https://github.com/user-attachments/files/17703397/nvda.freezes.sibelius.log)

**Comment by seanbudd** [comment] 2024-11-12 22:47
Closing as invalid. This is the intended behaviour of how Sibelius is using WASAPI. Please report this issue to the developers of Sibelius

**Closed by seanbudd** 2024-11-12 22:47 UTC

**Comment by Adriani90** [comment] 2024-11-12 23:17
@seanbudd this doesn't seem to be related to wASAPI, see the last comment from the user above. This happens also when WASAPI is disabled.

**Comment by seanbudd** [comment] 2024-11-12 23:50
@Adriani90 - winMM uses WASAPI as an underlying API these days. The issue is with how Sibelius uses WASAPI exclusively, it's going to mess with a lot of other software and is probably the intended behaviour of using that audio output method
