### ISSUE TITLE
Edge fails to read gmail message.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#6941] opened 2017-03-07 08:36 UTC
1. Open gmail in edge.
2. Try to read a message in the list by down arrowing. You just hear "grouping"

**Comment by josephsl** [comment] 2017-03-07 16:00
Hi, I cannot reproduce this. Once I open a message, I can read it fine (although table announcements are annoying). CC @MichaelDCurran

**Comment by derekriemer** [comment] 2017-03-07 16:11
> Hi, I cannot reproduce this. Once I open a message, I can read it fine (although table announcements are annoying). 

Hi:
I think this is clear that I don't mean the body, but I'll give a more detailed STR.
1. press alt+d.
2. type gmail.com and press enter.
3. if you don't land in focus mode inside a table, put yourself in it.
4. Down arrow or up arrow.

Expected: message headers are read.
Actual: "Grouping"

**Comment by josephsl** [comment] 2017-03-07 16:19
Hi, this is working as described in build 15048, but not in 14393 where I hear edit when I switch to focus mode inside the table. Thanks.

**Comment by michaelDCurran** [comment] 2017-03-16 02:15
This seems to work for me fine in Windows build 15058.

**Comment by michaelDCurran** [comment] 2017-03-16 02:21
@josephsl do you mean it works as expected in 15048, or that in 15048 you could reproduce Derek's bug? Either way It works fine for me in 15058 (and therefore will be in the Creaters Update).

**Closed by michaelDCurran** 2017-03-16 02:21 UTC
Labels: Edge

**Comment by josephsl** [comment] 2017-03-16 02:26
Hi, it works in 15048/15058. Thanks.
