### ISSUE TITLE
Word 365: NVDA often does not report word or paragraph selections (Shift+Ctrl+arrow keys)

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#15288] opened 2023-08-14 05:20 UTC
### Steps to reproduce:
1 Open a Word document and type in at least a paragraph of text.
2 Press Shift+Ctrl+arrow.
### Actual behavior:

NVDA is silent.
### Expected behavior:

NVDA says "{selected text} selected."
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.2 Beta 2
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Word 365
#### Other information about your system:
Just a note that this issue isn't perfectly consistent but happens the majority of the time. Also, I am on default UIA settings.
#### Does the issue still occur after restarting your computer?
Not tested
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tested
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by Brian1Gaff** [comment] 2023-08-14 10:35
Is this like the delay in selection of items in explorer, which often means you think you are on one item, but you are in fact on another? This effect gets worse if  a laptop is used on battery.
 Its the kind of thing that only a sighted person will see is happening of course.
 This is one reason why I don't like the latest Word updates. Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment] 2023-08-15 00:02
- Please fill out the issue template fully. What is the version of Office you are using?
- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2023-08-15 00:03
When generating the log, please enable UIA logging in advanced preferences

**Comment by Adriani90** [comment] 2024-02-20 21:48
This is not reproducible with NVDA last alpha and Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64 Bit. I am closing this as works for me. If you are still having this issue with NVDA 2024.1 Beta 9 or NVDA last alpha, please comment and we can reopen.

**Closed by Adriani90** 2024-02-20 21:48 UTC
Labels: close/worksforme, app/microsoft-office, needs-triage
