### ISSUE TITLE
nvda and windows mail: backspace issue

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#7456] opened 2017-07-29 08:05 UTC
1. Open the Windows 10 Mail App.
2. Compose a message.
3. Make an error or force the use of backspace in any field (To, Subject, etc.)
Expected: NVDA announces the character that is removed.
Actual: NVDA announces absolutely nothing.

NVDA version: master-14241,57432f41, but noticed with NVDA 2017.2 as well.
Windows version: Windoes 10 1703 (OS Build 15063.483, but noticed with other variants of Windows 10 Creator)

Narrator does not have this issue.

**Comment by josephsl** [comment] 2017-07-29 08:13
CC @MichaelDCurran, and I, too, can reproduce this.

**Comment by fisher729** [comment] 2017-08-03 01:24
@josephsl, could this be related to issue #7466 that I created recently?

**Comment by josephsl** [comment] 2017-08-03 01:40
Hi, probably not. Thanks.

**Comment by jmwalton92** [comment] 2017-08-16 01:34
I am able to reproduce this as well using Version: master-14308,9d1d47fa, on windows 10 1703.

**Comment by josephsl** [comment] 2018-01-03 05:59
Hi,

Update: #7849 is incubating, which does fix this problem. Thanks.

**Comment by derekriemer** [comment] 2018-01-04 01:53
fixed by #7849
Github, by your magic, close this when #7849 merges.

**Comment by zstanecic** [comment] 2018-01-04 02:01
Hi,
It works. 
The UIA in Microsoft word works, too
I am using the latest next.
Wysłane z aplikacji Poczta dla Windows 10

Od: Derek Riemer
Wysłano: czwartek, 4 stycznia 2018 02:54
Do: nvaccess/nvda
DW: Subscribed
Temat: Re: [nvaccess/nvda] nvda and windows mail: backspace issue (#7456)

fixed by #7849
Github, by your magic, close this when #7849 merges.

**Comment by Adriani90** [comment] 2019-04-30 19:55
I am not able to reproduce this issue with NVDA 2019.1.1 on Windows 10 1809 Update.
Closing as works for me.

**Closed by Adriani90** 2019-04-30 19:55 UTC
Labels: worksforme
