### ISSUE TITLE
Table navigation does not work on this page in firefox

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#10915] opened 2020-03-29 05:29 UTC
### Steps to reproduce:

1. On Firefox, navigate to [this page](https://www.mas.gov.sg/development/fintech/financial-api-register---transaction) and try to use table navigation on the only table there.

### Actual behavior:

Table navigation doesn't work, and the command to navigate by column produces the following error:

```
ERROR - scriptHandler.executeScript (13:27:08.764) - MainThread (3288):
error executing script: <bound method DocumentWithTableNavigation.script_nextColumn of <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x08BE1110>> with gesture 'alt+ctrl+right arrow'
Traceback (most recent call last):
  File "documentBase.pyc", line 157, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 441, in _getNearestTableCell
  File "documentBase.pyc", line 132, in _getNearestTableCell
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 429, in _getTableCellAt
  File "comtypes\__init__.pyc", line 857, in __call__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "documentBase.pyc", line 180, in script_nextColumn
  File "documentBase.pyc", line 163, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyc", line 437, in _getTableCellAt
LookupError
```

### Expected behavior:

Table navigation works as usual

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
Version: alpha-19834,2cdf280b
#### Windows version:
Windows 10 1909
#### Name and version of other software in use when reproducing the issue:
Firefox 75.0 b10
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by DrSooom** [comment] 2020-03-29 23:02
The table starting with Entity, Sector and so on works in Firefox 74.0x64 with NVDA 2019.2.1 on Win7x64 as expected. Maybe a regression.

**Comment by feerrenrut** [comment] 2020-03-30 14:44
@Neurrone Could you please test with Chrome and report back? Helpful to know if this is browser specific.

**Comment by Neurrone** [comment] 2020-03-30 15:01
Its not recognized as a table at all by Chrome 80.0.3987.149, and is recognized as a table in IE11 (with working table navigation).

**Comment by feerrenrut** [comment] 2020-03-30 15:19
I'm not able to reproduce this with `Firefox 74.0 (64-bit)` and `NVDA alpha-19834,2cdf280b`
The table is recognized, moving by column / row works for me with `ctrl+alt+left / right / up / down`

It might be broken in Firefox beta.
@Neurrone Can you try Firefox stable to confirm?
FYI @jcsteh

Looking at the a11y tools in Chrome `80.0.3987.149 (Official Build)`, this table has a `LayoutTable` role.

**Comment by jcsteh** [comment] 2020-03-31 01:29
Chrome really shouldn't be treating this as a layout table, but it happens because the table has CSS display: inline-block. This is weird, but is becoming more common with modern responsive websites.

Firefox tries to handle this, but it seems it's not handling it correctly in this case, at least from 75 onwards. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1626137

**Comment by Neurrone** [comment] 2020-03-31 13:23
Thanks a lot @MarcoZehe for the quick fix. This will land with Firefox 75.

**Comment by MarcoZehe** [comment] 2020-03-31 13:51
Yes, it was approved, and even landed on 75 for C1 before actually being merged into Central from Autoland. :-) Sorry for the temporary breakage! This issue can be closed.

**Closed** 2020-03-31 13:52 UTC
Labels: app/firefox, blocked/needs-external-fix, bug

**Comment by Neurrone** [comment] 2020-03-31 13:55
Actually, I know this issue also happens in Chrome although the title says Firefox (since that's my main browser).

Should I open another one specifically for Chrome?

**Comment by feerrenrut** [comment] 2020-03-31 14:11
Please do @Neurrone, can you refer to the comment from JcsTeh above. It has some insight into what the problem might be in chrome.
