### ISSUE TITLE
Firefox: braille keyboard input, NVDA does not Speak Typed Characters.

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#10914] opened 2020-03-28 20:09 UTC
### Steps to reproduce:
1. Open Firefox.
2. Link to Google.
3. Press e to Move to the edit field.
4. Press enter to Switch to focus mode.
5. Type string to search "nvda ideas list 2020".

(Use the Perkins-style braille keyboard on my Focus display.)
### Actual behavior:
NVDA does not Speak Typed Characters.
### Expected behavior:
NVDA reads typed characters.
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2019.3.1
#### Windows version:
Windows 10.0.18362 workstation
#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 74.0 (x64 zh-TW)
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA_2019.2.1 / NVDA_2020.1beta1
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by DrSooom** [comment] 2020-03-28 22:36
Is the behavior the same for all three NVDA versions you have posted? This isn't clear. Thanks.

**Comment by surfer0627** [comment] 2020-03-29 09:35
> Is the behavior the same for all three NVDA versions you have posted?

Yes.

**Comment by Adriani90** [comment] 2024-07-02 21:48
@surfer0627 are you still having this issue with NVDA 2024.3 Beta in Firefox 127?

**Comment by SaschaCowley** [comment] 2024-07-18 01:49
Closing as I'm unable to reproduce and @surfer0627 hasn't responded.

**Closed by SaschaCowley** 2024-07-18 01:49 UTC
Labels: component/braille
