### ISSUE TITLE
NVDA randomly becomes unresponsive

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#10112] opened 2019-08-17 18:32 UTC
### Steps to reproduce:
Computer should be booted for 2-3 days, and the randomness starts
### Actual behavior:
NVDA becomes unresponsive, NvDA key doesn't wrok and it does not interrupt when switching through icons.
### Expected behavior:
NvDA responds
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2
#### Windows version:
1903 build 18362.295
#### Does the issue still occur after restarting your PC?
It goes away after restarting, but when the computer has been running or a while it starts again.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.1.1, but I have switched the windows10 a short while ago before the latest release so I'm not sure.

**Comment by Brian1Gaff** [comment] 2019-08-19 07:38
Just a comment here. If it was updated from Windows 7, the issue can be 
other software, like Office or something else being just a little corrupted 
when its reinstalled in 10 by the update system. I think, though its a real 
pain, many of these strange things seem not to happen on clean installs.

Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by burakyuksek** [comment] 2019-08-19 10:05
Hello,
This computer was updated from windows 1809 to 1903. Thanks for your advice.

Brian Gaff <notifications@github.com> şunları yazdı (19 Ağu 2019 10:38):

**Comment by Qchristensen** [comment] 2019-09-02 22:17
Although Windows today is much more stable than in the past, it still often goes a bit funny after days running, and I think this is likely to be Windows itself rather than NVDA here.  If you restart only NVDA rather than the whole computer, does it still act randomly?  Also, if you could attach a copy of your NVDA log, that might show whether NVDA is doing anything strange here.

**Comment by leonardder** [comment] 2019-09-03 17:25
I have the feelling that these issues are caused by a crashed keyboard hook. In this case, NVDA is unable to detect any keys pressed on the system, and therefore its mechanisms to cancel speech when a key is pressed do not longer function. A restart of NVDA usually fixes this.

**Comment by burakyuksek** [comment] 2019-09-04 22:56
Hello,
To which level should I set logging level? Yes, it still acts randomly when I restart NVDA.

**Comment by burakyuksek** [comment] 2019-09-27 23:38
Hello,
So I am in a time where those crashes happen prittey often. I managed to capture a crash prittey close to the last restart of NVDA using debug logging mode. After I quit NVDA, I launched narrator and got the file %tempt%/nvda.log. I am uploading the file here in hopes that it's the correct one.
[nvda.log](https://github.com/nvaccess/nvda/files/3664830/nvda.log)

**Comment by zahra21** [comment] 2020-03-04 09:04
hi.
unfortunately i face nvda becoming unresponsive too.
when, firefox loads heavy cpu user website, sometimes my nvda does not speek, sometimes my keyboard becomes unresponsive and i cant do anything except turnning off my laptop with power key button,
and many times, firefox becomes unresponsive and nvda does not says anything for me.
when i press alt f4, nvda says end program, this program is not responding!
i faced this issue even with javascript disabled sometimes that firefox becomes unresponsive even in github or gmail!
and, many many times when javascript is enabled for me.

**Comment by Adriani90** [comment] 2020-05-25 15:29
@burakyuksek are you still having this issue with NVDA 2020.1 under Windows 10 1909 Update?
1. Please try to reproduce this with all addons disabled
2. Please rung the COM registry fixing tool in NVDA menu under tools

It looks like you have a bug in your registry, you should run a registry cleaning program like CCleaner and clean up the registry. Also please update your graphic driver, as I understand your graphic card is from Nvidia.

Please give an update on this after you cleaned up and updated drivers. Thanks.

**Comment by burakyuksek** [comment] 2020-05-27 09:56
Hello,
I reset windows and the issue was mostly solved, except when running a resource intensive game. Then I updated the graphics driver and it was completely gone.
Thanks for your advices.

**Comment by Adriani90** [comment] 2020-05-27 19:49
Thank you for reporting. Closing as works for me.

**Closed by Adriani90** 2020-05-27 19:49 UTC
Labels: close/worksforme
