### ISSUE TITLE
Table navigation fails occasionally

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#16824] opened 2024-07-05 06:38 UTC
### Steps to reproduce:
No exact steps to reproduce, I encountered this error in inbox table in GMail. I've encountered this on other web pages that contain tables.

### Actual behavior:
NVDA Logging Error Table navigation not working.
Works as expected after restarting NVDA.
The problem occurred again shortly after
### Expected behavior:
NVDA should not error.
### NVDA logs, crash dumps and other attachments:
IO - speech.speech.speak (14:26:49.579) - MainThread (14748):
Speaking ['日志片段开始点已标记，再按一次复制到剪贴板']
DEBUG - speech.manager.SpeechManager._handleIndex (14:26:50.268) - MainThread (14748):
Unknown index 6038, speech probably cancelled from main thread.
IO - inputCore.executeGesture (14:26:50.380) - winInputHook (14660):
Input: kb(laptop):alt+control+rightArrow
IO - speech.speech.speak (14:26:50.408) - MainThread (14748):
Speaking ['表格边缘']
ERROR - scriptHandler.executeScript (14:26:50.410) - MainThread (14748):
error executing script: <bound method DocumentWithTableNavigation.script_nextColumn of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x17222790>> with gesture 'Alt+Ctrl+右光标'
Traceback (most recent call last):
  File "documentBase.pyc", line 358, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 622, in _getNearestTableCell
  File "documentBase.pyc", line 285, in _getNearestTableCell
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "virtualBuffers\gecko_ia2.pyc", line 604, in _getTableCellAt
  File "comtypes\_memberspec.pyc", line 482, in __call__
_ctypes.COMError: (-2147023179, '接口未知。', (None, None, None, 0, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "documentBase.pyc", line 384, in _tableFindNewCell
  File "virtualBuffers\gecko_ia2.pyc", line 612, in _getTableCellAt
LookupError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "documentBase.pyc", line 480, in script_nextColumn
  File "C:\Users\wencong\AppData\Roaming\nvda\addons\googleDocs\globalPlugins\googleDocs.py", line 369, in myTableMovementScriptHelper
    originalTableMovementScriptHelper(selfself, movement, axis)
  File "documentBase.pyc", line 415, in _tableMovementScriptHelper
  File "documentBase.pyc", line 386, in _tableFindNewCell
RuntimeError: ('Unable to find current cell.', LookupError())
IO - inputCore.executeGesture (14:26:51.110) - winInputHook (14660):
Input: kb(laptop):NVDA+shift+control+f1

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.3Beta1 and Alpha version
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.4529
#### Name and version of other software in use when reproducing the issue:
Google Chrome: Version 126.0.6478.127 (Official Build) (64-bit)
#### Does the issue still occur after restarting your computer?
No, Works as expected after restarting NVDA
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2024.1 and even earlier versions can reproduce this
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment] 2024-07-05 07:36
@cary-rowen could you edit the initial description:
* fixing NVDA version
* indicating the browser's name (we only have the version)

*

**Comment by cary-rowen** [comment] 2024-07-05 09:13
Thanks @CyrilleB79 Sorry I lost some information, it's done now

**Comment by Adriani90** [comment] 2024-07-05 09:51
You seem to have solved this by running the COM registration fixing tool. Closing as fixed.

**Comment by cary-rowen** [comment] 2024-07-05 22:33
Hi @Adriani90 

This was a filling error. I have corrected it. Please open it.
I have to say that I'm very confused by the unreliable caret movement in Github's comment area recently with NVDA.
I have to say that recently NVDA seems to be very unreliable in moving the system caret in the Github comment area.

**Comment by Adriani90** [comment] 2024-07-05 22:50
I am reopening, thanks for adjusting the description.

Regarding caret navigation, please describe in a new issue step by step the problem you have. I cannot reproduce anything unexpected in the last alpha.

**Comment by mltony** [comment] 2024-07-14 23:45
I also experience this problem with the same exception. In my case this happens when browsing pandas dataframes rendered as tables in Jupyter. This happens approximately once or twice a week for me, so really hard to reproduce.

**Comment by jcsteh** [comment] 2024-07-25 11:06
Duplicate of #15862. See also related #16020.

**Closed by jcsteh** 2024-07-25 11:06 UTC
Labels: p5, triaged, papercuts
