### ISSUE TITLE
Office 2010: Certain Symbols not Recognised by NVDA

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10381] opened 2019-10-14 19:35 UTC
### Steps to reproduce:

Tested with Office 2010 - I unfortunately haven't had the chance to test with any later versions as of yet.

1. Open a new Word document, and type a smiley face (a ":" and a ")")

2. Read the just-typed character with NVDA

### Actual behavior:

NVDA announces this symbol as a closing bracket ("(") symbol, rather than as a smiley face

### Expected behavior:

It'd be really useful if NVDA could recognise these types of symbols in Office 2010; it sometimes becomes hard to properly interact with people who add symbols to email messages when it's not possible to see what the symbol actually is!

#### NVDA version:

2019.2.1

**Comment by CyrilleB79** [comment] 2019-10-15 07:19
Duplicate of #9120

**Closed** 2019-10-15 07:24 UTC
