### ISSUE TITLE
Multiple column headers are read wrong

### ISSUE THREAD

**Issue by sherman89** [nvaccess/nvda#14649] opened 2023-02-17 14:54 UTC
When having subheaders, NVDA always reads both headers when focusing on a cell. JAWS only reads the relevant column header of the cell. The headers of the cells are explicitly set in the `headers` attribute.

Example: First table on this page: https://www.w3.org/WAI/tutorials/tables/multi-level/
Code here: https://www.w3.org/WAI/tutorials/tables/examples/multiplecolumnheaders/

![image](https://user-images.githubusercontent.com/20951158/219687660-6da4a069-960a-457b-9edc-9652d8e47d49.png)

When focusing on the first cell for example, both "Example 1 Ltd" and "Example 3 Ltd" headers are read, when only "Example 1 Ltd" should be read.

NVDA Version: **2022.4.0.27401**
Browser: **Chrome 110.0.5481.104 (64-bit)**
OS: **Windows 11 22H2 (OS Build 22621.1265)**

Thank you!

**Comment by josephsl** [comment] 2023-02-17 14:58
Hi, hmmm, could you mind adding some more sauce to the issue please i.e. NVDA version, browser and version in use, Windows release and build number? Thank you.

**Comment by josephsl** [comment] 2023-02-17 15:07
Hi,

Thanks for the "sauce" i.e. more info to help us understand what's going on. Please do fill out the template next time.

I can verify this, more so if reading some articles from places such as Wikipedia (especially with say all). My guess is that NVDA wants to gather headers from all locations.

Thanks.

**Comment by sherman89** [comment] 2023-02-17 16:00
@josephsl Noted 🙂 Thought it would be better to just get straight to the point.

**Comment by Brian1Gaff** [comment] 2023-02-18 09:54
Well its hard to duplicate the errors if you don't have the same 
configuration, as has been said many times.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by sherman89** [comment] 2023-02-19 07:46
@Brian1Gaff Alright.. but anyway I had everything on default except for the voice

**Comment by seanbudd** [comment] 2023-02-24 01:34
Welcome @sherman89 ,

We are unable to process this issue as it stands.

Please fill out the issue template fully.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment] 2024-10-13 15:40
Closing as duplicate of #6890.

**Closed by Adriani90** 2024-10-13 15:40 UTC
Labels: close/duplicate, p4, triaged, blocked/needs-technical-investigation
