### ISSUE TITLE
eSpeak NG Attempts to Pronounce Certain Strings of Non-English Characters Strangely

### ISSUE THREAD

**Issue by ntcarver0** [nvaccess/nvda#12465] opened 2021-05-26 16:04 UTC
### Steps to reproduce:
Read the following string with eSpeak NG and NVDA 2021.1beta1:
Warning: Will cause broken English speech. This can be fixed by restarting NVDA or by changing the variant or language and then setting it to the previous setting.
ᎯℳℐℕᎯ
### Actual behavior:
After reading the string (or other strings like it), eSpeak NG attempts to read English in a strange, unintelligible accent. This can be fixed by restarting NVDA or by changing the variant or language and then setting it to the previous setting.
### Expected behavior:
NVDA should read the string (or strings like it), but should not try to speak other English words in a strange accent.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2021.1beta1
#### Windows version:
Windows 10 Pro version 20H2
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
eSpeak NG settings
Voice: English (America)
Variant: Nguyen
Rate: 40
Rate boost: checked
Pitch: 51 (caused by issue #9811/#11832)
Inflection: 51 (caused by issue #9811/#11832)
Volume: 100
Automatic language switching (when supported): unchecked
Automatic dialect switching (when supported): unchecked
Punctuation/symbol level: most
Trust voice's language when processing characters and symbols: Checked
Include Unicode Consortium data (including emoji) when processing characters and symbols: checked
Capital pitch change percentage: 50
Say cap before capitals: unchecked
Beep for capitals: unchecked
Use spelling functionality if supported: checked
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2020.4 does not do this.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by feerrenrut** [comment] 2021-05-26 23:06
For investigators: See if this can be replicated by using espeak directly. If so, then it will be easier to create an issue directly on the espeak repository.

**Comment by feerrenrut** [comment] 2021-05-26 23:27
I can't reproduce the issue with:
```
echo 'hello world<break time="2s"/>ᎯℳℐℕᎯ<break time="2s"/>hello world' | ./espeak-ng.exe --stdin -m
```
I hear "hello world", unintelligible sounds, "hello world"
The issue would replicated as: "hello world", unintelligible sounds, more unintelligible sounds

Unfortunately the most recent espeak release is `1.50` from Dec 2, 2019. NVDA is using a much newer version than this. To test the same version outside of NVDA we would have to build all of espeak-ng from source.

**Comment by michaelDCurran** [comment] 2021-05-27 06:07
Bisecting shows that this issue was introduced in espeak-ng/espeak-ng@19e2f697f63a2

**Comment by michaelDCurran** [comment] 2021-05-27 06:09
I'm guessing that the change assumes that the language can only change due to ssml or by the user. But in this case, the language is changed by the actual characterset itself. I can file an issue against espeak-ng.

**Comment by michaelDCurran** [comment] 2021-05-27 07:09
Filed issue espeak-ng/espeak-ng#950

**Comment by Brian1Gaff** [comment] 2021-05-27 08:27
I have an Espeak  sapi 5 on this machine with the same voice as I use inside 
espak in nvda, and on the inbuilt one I get hello world and the 
unintelligible stuff, but with the sappi 5 it just says the characters as it 
would in other foreign languages, not the actual unintelligible stuff, How 
do I tell which espeak I have.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by TheQuinbox** [comment] 2021-05-28 16:20
SAPI eSpeak hasn't been updated in a long while AFAIK, so that might not even be NG.

**Comment by codeofdusk** [comment] 2021-05-31 02:48
I also filed this a while ago at espeak-ng/espeak-ng#915.

**Comment by michaelDCurran** [comment] 2021-05-31 05:51
Looks like this kind of bug has been noticed previously, reported in issue espeak-ng/espeak-ng#915 and a revert of the bad commit in pr espeak-ng/espeak-ng#929. However, that pr has not yet been merged as the printed phoneme output does not seem to change. Yet, the synthesized audio does.
Both the commit I thought it was, plus the commit the existing pr reverts are both code cleanup commits which remove static global variables. However, other than that, it is totally unclear how these commits could logically cause what we are hearing. Thus it is most likely this is a buffer overrun which has simply been made worse by the memory moving around in these commits.
I am continuing to debug further to try and get to the real root cause, which is the fact that phoneme data seems to become a bit corrupt when a particular character is processed.

**Comment by seanbudd** [comment] 2021-06-03 03:32
Closed by #12495

**Closed by seanbudd** 2021-06-03 03:32 UTC

**Comment by seanbudd** [comment] 2021-06-23 03:31
Can anyone confirm this issue hasn't be reintroduced in the latest alpha (which uses the latest espeak)?

**Comment by codeofdusk** [comment] 2021-06-24 04:26
Attempting to read the string in espeak-ng/espeak-ng#915 now says nothing, but Espeak doesn't get stuck in the other language either.

**Comment by ntcarver0** [comment] 2021-07-09 16:01
The issue still occurs in NVDA 2021.1rc2 as demonstrated by this Wikipedia article.
https://en.wikipedia.org/wiki/Mi%EA%9E%8Ckmaq_language

**Comment by seanbudd** [comment] 2021-07-12 01:24
> The issue still occurs in NVDA 2021.1rc2 as demonstrated by this Wikipedia article.
> https://en.wikipedia.org/wiki/Mi%EA%9E%8Ckmaq_language

@ntcarver0 
This seems have the same behaviour of 2020.4 (and likely older versions of NVDA/espeak). I could also reproduce this on alpha23308. This can only be fixed by espeak, it might be worth raising a new issue or commenting on espeak-ng/espeak-ng#915, I would highlight some example sentences that cause the problem.
