### ISSUE TITLE
Something is broken in updating nvda

### ISSUE THREAD

**Issue by Brian1Gaff** [nvaccess/nvda#7595] opened 2017-09-12 17:44 UTC
First download latest next snap. Then attempt to update the current next running. This can either be via the alert  using firefox or whatever you like.
 All seems to be OK but sometimes  one of the following will occur.
 If you select  start new copy after update, it freezes at the point it is about to restart. Nothing in the log to show anything but that it has stopped, sometimes you might hear the windows error and  then you can restart and the log shows..
INFO - __main__ (18:30:44.180):
Starting NVDA
INFO - core.main (18:30:44.257):
Config dir: C:\Users\Brian\AppData\Local\Temp\nstA07B.tmp\app\userConfig
INFO - config.ConfigManager._loadConfig (18:30:44.257):
Loading config: .\userConfig\nvda.ini
CRITICAL - __main__ (18:30:44.289):
core failure
Traceback (most recent call last):
  File "nvda.pyw", line 202, in <module>
  File "core.pyc", line 193, in main
IOError: zipimport: can not open file C:\Users\Brian\AppData\Local\Temp\nstA07B.tmp\app\library.zip

Then other times during the update it will complain that a file cannot be removed and you tell it to ignore but at the end it boots back in anyway.
 Is this something to do with the unhooking of dlls again?
 Are there any tests that I can do to help?
 I'm using Windows 7 64 pro and really not a lot else matters. However I was having the lock up on the installed copy of master but the last two updates have gone OK except for the issue recently on erasing the dictionaries after an update.

**Comment by feerrenrut** [comment] 2017-09-13 05:53
A couple of extra questions here:
* What version were you updating from?
* Could you attach the full log to this issue?

**Comment by leonardder** [comment] 2017-09-13 06:39
I haven't been able to reproduce this on two different systems. My concerns from https://github.com/nvaccess/nvda/issues/7592#issuecomment-329073145 also apply here.

**Comment by Brian1Gaff** [comment] 2017-09-13 16:48
Well see my comments in my other ticket. as you say if you cannot duplicate 
these in windows 7, then there has to be something different here that 
causes this. Its going to be a real pain to figure out what it is. The new 
Espeak issue with the word  for in some contexts is also strange.
 I've deliberately only mentioned this in the dev list in case anyone can 
duplicate it, as from what I read there are significant sound and espeak 
alterations in work as well as updates pending and this new run the portable 
copy flag which has caused me grief before. Seeing as I only have the one 
machine and its my working one, I'm not going to fiddle with the copies 
unless they become unusable.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by leonardder** [comment] 2017-09-15 05:27
@Brian1Gaff: Do I understand correctly that you consider this to be a duplicate of #7592?

**Comment by mohdshara** [comment] 2018-01-04 10:49
isn't this a duplicate or at least related to https://github.com/nvaccess/nvda/issues/7830

**Comment by feerrenrut** [comment] 2018-01-08 00:10
@mohdshara Yes this does seem quite related. Personally I suspect the cause is the same for both. However, since the logs refer to different parts of the installer process, I think it's best to keep these two issues open for now.

**Comment by Adriani90** [comment] 2019-04-30 21:23
@Brian1Gaff are you still having this issue?

**Comment by feerrenrut** [comment] 2019-12-03 09:41
Since we have no extra information on this issue, and it has been addressed I am going to close it. Please let me know if this issue is still ongoing.

**Closed by feerrenrut** 2019-12-03 09:41 UTC
