### ISSUE TITLE
Custom descriptions/labels NVDA

### ISSUE THREAD

**Issue by peterpacult** [nvaccess/nvda#12488] opened 2021-05-31 08:50 UTC
In JAWS you can create custom descriptions for graphics, form fields or text links (https://www.freedomscientific.com/SurfsUp/Custom_Labels.htm). It would be very helpful if NVDA also had this functionality. Either directly in the programme or possibly with the help of an add-on.

**Comment by cary-rowen** [comment] 2021-05-31 09:28
There are many software developed that do not follow the accessibility standards and may not add accurate leabel to the button. If you can use this function to add it yourself, it may be good, including google Talkback also has such a function.

**Comment by XLTechie** [comment] 2021-05-31 19:29
As does iOS Voiceover, though it doesn't work some of the time.

**Comment by lijianwei2019** [comment] 2021-06-06 13:39
repeat #2111

**Comment by Adriani90** [comment] 2023-02-08 21:29
closing as duplicate of #2111

**Closed by Adriani90** 2023-02-08 21:29 UTC
Labels: close/duplicate
