### ISSUE TITLE
Mapping Braille Gestures

### ISSUE THREAD

**Issue by dan1982code** [nvaccess/nvda#7350] opened 2017-07-03 04:17 UTC
Hi all,

The HIMS Braille Sense/Braille EDGE/Smart Beetle Series driver maps tons of braille gestures to useful keyboard commands, like page up, page down, ctrl+page up, ctrl+page down, etc. So it seems that braille displays can map such gestures. However, I cannot see how to do this with my Brailliant BI display. Is it possible?

This is a feature request, but also a request for whether there is even a hacky way to do this currently.

**Comment by jcsteh** [comment] 2017-07-03 04:47
This is a duplicate of #6060.

While having a UI for this would be ideal, you can achieve this at present by manually editing gestures.ini. gestures.ini can be found in the NVDA user configuration directory, which will be `%appdata%\nvda` for an installed copy. If it doesn't exist, create it. The file might look something like this:

> ```
> [globalCommands.GlobalCommands]
> kb:windows = br(baum):dot2+dot4+dot5+dot6+b9
> kb:tab = br(baum):dot2+dot3+dot4+dot5+b9
> ```

The identifier after the equals sign can be obtained by doing the following:

1. Press NVDA+1 to turn on input help.
2. Press the keys you want to bind on the braille display.
3. Press NVDA+1 to turn off input help.
4. Press NVDA+f1 to open the NVDA Log Viewer.
5. You will see lines like this: `Input help: gesture br(baum):dot1+b9`

**Closed by jcsteh** 2017-07-03 04:47 UTC

**Comment by ruifontes** [comment] 2017-07-03 09:58
Hi!

James wrote:
While having a UI for this would be ideal, you can achieve this at present 
by manually editing gestures.ini.

Yes, but most users don't know how to do it and are afraid of do such thing!
With a UI it will be very easier!

Rui

**Comment by jcsteh** [comment] 2017-07-03 11:30
I'm aware of that, which is why I said having a UI would be ideal. The reporter asked whether there is currently a workaround, so I provided the information as requested.
