### ISSUE TITLE
On Windows 10 1903 NVDA starts after logon even when this is disabled

### ISSUE THREAD

**Issue by a11cf0** [nvaccess/nvda#9528] opened 2019-04-30 17:45 UTC
### Steps to reproduce:
1. Install NVDA,
2. Do not configure NVDA for starting automatically after logon, but let it run on secure screens,
3. Restart Windows or sign out and in.

### Actual behavior:
NVDA starts right after logon just as if the corresponding option is enabled.

### Expected behavior:
NVDA shouldn't autostart when it isn't told to do so.

#### NVDA installed/portable/running from source:
Obviously NVDA is installed.

#### NVDA version:
I'm running NVDA alpha-17099,0d2a1525.

#### Windows version:
Windows 10 Version 1903 18362.53 x64.
This issue doesn't occur on older systems.

#### Name and version of other software in use when reproducing the issue:
I think this is irrelevant. This happens after a fresh OS install.

#### Other information about your system:
As expected, the registry key normally responsible for automatic startup doesn't exist on my system.

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not yet. I can do this if needed.

**Comment by leonardder** [comment] 2019-04-30 19:35
Is NVDA also started at the logon screen? What happens if you disable that?

**Comment by a11cf0** [comment] 2019-04-30 21:06
> Is NVDA also started at the logon screen? What happens if you disable that?

If this option is disabled NVDA doesn't autostart at all.
but if starting on logon screens is enabled NVDA starts both at and after logon.

**Comment by btman16** [comment] 2019-06-25 23:51
Hello,

Please see this link for more context on the issue.

In short, I talked to people at MS immediately when this issue occurred and they had many months before release to get it fixed and they failed to.
Narrator is also affected. If it's possible, are others able to upvote this please?

https://aka.ms/AA4g3cq

Thanks,

Brandon

**Comment by snowflake-tvi** [comment] 2019-07-18 12:54
Good morning, 
The last comment here was three weeks ago...I just started having this problem last week when our network admin updated Windows.  Every computer in my school (WI School for the Blind and VI) has NVDA installed, and everyone is contacting me to report/solve the issue.  Has there been any change yet and if so, is there anything I can do to resolve it?  So far everything I've tried everything I can think of (even installing a previous version of NVDA) and nothing has worked.  Suggestions are most appreciated :)

**Comment by Adriani90** [comment] 2019-07-18 20:59
cc: @feerrenrut

**Comment by btman16** [comment] 2019-07-20 17:07
Hello,

As far as I know the only thing you could do right now is that after you use NVDA to enter your password, then quit NVDA before pressing enter to log in.

Thanks,

Brandon

**Comment by XLTechie** [comment] 2019-07-20 19:20
This is comical. I decided to test your problem. On my system running 1903, 
which always starts NVDA after logon, I entered general settings to turn the 
option off.
Only to find that it already was!

So, on beta-18133 (latest), I can definitely replicate this bug.

**Comment by XLTechie** [comment] 2019-07-20 19:27
btman16 wrote:

> As far as I know the only thing you could do right now is that after you use NVDA to enter your password, then quit NVDA before pressing enter to log in.

That doesn't actually work.

**Comment by josephsl** [comment] 2019-07-20 20:15
Hi,

Brandon's workaround won't work because this scenario will repeat after a restart.

Having confirmed this on another computer, I'm thinking this may have to do with registry. The fact that this problem doesn't show up if "use NVDA on the logon screen" checkbox (Settings/General) is unchecked suggests something is going on with Ease of Access portion of Windows Registry. Specifically:

* HKCU\Software\Microsoft\Windows NT\CurrentVersion\Accessibility determines whether or not NVDA will start after you log in.
* Replacing "HKCU" with "HKLM" gets us to secure screens.

At the source code level, I recommend looking at config/__init__.py and easeOfAccess.py.

Thanks.

**Comment by XLTechie** [comment] 2019-07-20 20:26
I assumed it had something to do with Ease of Access controls, but couldn't 
figure out what.

**Comment by snowflake-tvi** [comment] 2019-07-20 23:30
I totally appreciate all the feedback guys! I’m in Assistive Technology specialist, not a network administrator, so this kind of thing is totally outside of my wheelhouse. I forwarded your comments onto our network administrator  and hope he will be able to implement the solution.

**Comment by josephsl** [comment] 2019-07-20 23:33
Hi, when you do tell the IT professional, please let this person know that Microsoft and NV Access were notified, and the solution proposed (turning off starting NVDA from secure screens) has a side effect of preventing NVDA from speaking in places such as User Account Control. Thanks.

**Comment by snowflake-tvi** [comment] 2019-07-20 23:45
Will do! Sounds like if this truly is implemented that our school may wish to use narrator for secure logon screens to prevent future issues. I certainly appreciate your help

**Comment by josephsl** [comment] 2019-07-20 23:50
Hi, not so fast, actually: it was noted that, according to Brandon, if Narrator is enabled from secure screens, Narrator will come up after one logs in even though it is told not to. Provided that this is indeed the case, I advise against implementing it, as this is something that should be looked at by Microsoft (hopefully by later this year or early next year if the fix makes it to a cumulative update for 1903, part of 19H2, or resolved in 20H1). Thanks.

**Comment by snowflake-tvi** [comment] 2019-07-20 23:59
Well now I know why am I not a network administrator... this is way too much thinking for a Saturday night ...

**Comment by XLTechie** [comment] 2019-07-21 02:45
But will they? If I understand things correctly, Microsoft intends this 
behavior.
If you look at the Narrator section in Ease of Access, the control to use 
Narrator on secure screens, makes pretty clear that it will cause Narrator to 
work everywhere, on all accounts.
"Start Narrator for everyone before log-in."

At least, that's my understanding of the option. I'm unwilling to try it on the 
system I have available right now, for fear of fuing it bar for good and all.

It would seem that the same effect is occurring with NVDA.

It's a one size fits all solution--exactly MS's style. They seem to be 
anticipating that only one screen reader will be needed on the system at any one 
time. Having the annoying side effect described in this thread.

Or maybe I'm wrong--like I said, I'm unwilling to test to the depth I would 
like. Maybe someone has a VM they can play with and prove me wrong.:)

**Comment by josephsl** [comment] 2019-07-21 03:04
Hi,

Perhaps. In short, that option performs NVDA's equivalent of starting from secure screens.

Technical: in order to understand this, we need to talk about sessions. Although Windows did support what's called "session space" for years (a session space is a range of system memory locations subject to context switches in order to give appearance of multi-user environment, which is prerequisite of Remote Desktop/Terminal Services (Windows internals, Fourth Edition)), it wasn't until Vista that sessions became more prominent (Windows Internals, Fifth Edition). That is, when Windows boots, it starts in session 0, which is used to manage services, certain global system processes, and as a side effect, used to display secure desktops such as User Account Controll; this is typically what is meant by secure screens. Session 1 and beyond refers to interactive user session. in effect, when using Windows, one is effectively using two sessions: normal user interface, and secure screens.

A subtle beneficiary of multiple sessions is Ease of Access. Because assistive technologies might be used from login and other secure (session 0) interfaces (including from logonui.exe), Ease of Access will check which AT executables should run before and after a user logs on. The way Ease of Access knows about it is through registry hive: HKLM (local machine) for session 0, HKCU (current user) for session 1 and beyond. This is the reason why one can run one screen reader before logging in and another while logged on, and that's precisely the intention behind the Narrator option noted above. This also explains why it takes a while for NVDA to speak User Account Control if it uses certain speech synthesizers because Ease of Access must run another copy of NVDA, this time from within secure desktop, and NVDA can detect it and fall back to system configuration and can remember that it is a secure copy via a flag.

As for Microsoft confirming this: yes, confirmed by a member of the Narrator team, and engineers are looking into this. I asked her (Narrator engineer) if this will impact 19H2 and 20H1, and no reply at the moment.

Thanks.

**Comment by josephsl** [comment] 2019-07-21 03:42
Hi,

Update: apparently this affects 19H2 and 20H1 as well, which means this issue will haunt admins for a long time.

Thanks.

**Comment by SCSchilling1** [comment] 2019-07-29 20:33
Hi, this is Shou-Ching from Microsoft. I was wondering if I could gather some information on this issue.  Things like:
(1) How many machines were affected?
(2) Does it repro 100% of the time?  Does it repro after reboot?
(3) What are the OS version and configurations? [Multiple users? single users? password protected? domain joined? AT installed and their configuration? etc.)
(4) Briefly describe what happened?  (Feel free to reply here or via the feedback hub's add more detail or conversation area).

Thank you very much for your help!
Shou-Ching Schilling
Windows Accessibility Community Champ
@SCMuiLan

**Comment by snowflake-tvi** [comment] 2019-07-31 20:48
Good afternoon,

My apologies for the delay in response.  There is so much to do to get ready for the start of school in a few weeks!


1.    It’s hard to say exactly how many machines were affected.  There was no real rhyme or reason for why some machines were affected and some were not.

2.    Yes, the problem would persist after a reboot or when settings were changed.  Even an uninstall and reinstall would reproduce the same problem.  At one time, I thought uninstalling NVDA, Rebooting, running Fusion (from Freedom Scientific/Vispero), shutting Fusion down, rebooting, then reinstalling NVDA would work, and it did for a while, but my guess is whatever I did was overwritten by an update or some sort or some other change because the fix lasted perhaps 7-10 days before the issue reoccurred.

3.    We are a Center for the Blind and our computers are networked.  Installs and updates of NVDA are “pushed out” by our network administrator.  Users have a password protected roaming profile and can log into any PC with that profile and access their data (domain wcbvi).  Most of those affected were using only one or maybe two computers (not logged in simultaneously) on the campus.  We are using Windows 10.0.18362 on desktop Lenovo computers.

4.    All of our computers are outfitted with NVDA running on the logon screen, but not once the user profile is loaded.  The user profile determines whether NVDA or JAWS runs upon logging in.  When the affected user logged into the affected PC, NVDA was on when logging in even though in the NVDA settings this option was not enabled.  Even if the option was disabled and the computer rebooted, NVDA still started up when the user logged in.

An idea that would work for institutions like ours would be to configure Narrator to speak on logon or secure screens and have a separate option for starting (or continuing) NVDA once the individual logs in to Windows.  Currently it’s an all or nothing option, with Narrator speaking on the logon screen and once the user is logged on, but not having a separate setting for either option.  I hope that made sense.

Also, please know that I am not a network admin or programmer.  My specialty is teaching use of assistive tech and doing evals as well as some occasional helpdesk and troubleshooting.  So please forgive me if anything here is not clear or if I do not use the correct terminology.

Thank you for following up!  I’ve included my contact info below if you’d like to touch base and brainstorm.  I’m always open to learning and sharing knowledge with others!

Have a wonderful Wednesday!

Amy Snow


Amy Snow
Certified Assistive Technology Instructional Specialist
Teacher of the Visually Impaired
1700 W State Street
Janesville, WI 53546
Phone: 608 758 6157
Fax: 608 758 6169
amy.snow@wcbvi.k12.wi.us<mailto:amy.snow@wcbvi.k12.wi.us>
Check out our AT Loan Library!<https://www.wcbvi.k12.wi.us/outreach/at-loan/>

**Comment by SCSchilling1** [comment] 2019-08-01 08:40
Hi Amy,
Thank you very much for taking the time to gather this information.  It is very clear and very useful. Thank you!

Thanks for the offer to provide further assistance. I will get in touch with you via email if I need more information, or if I have something to update.
Have a good day!

Shou-Ching
Windows Accessibility Community Champ

**Comment by snowflake-tvi** [comment] 2019-08-05 14:13
Good morning!
My network admin requested that I throw this question out there:
Does anyone know how to do a silent uninstall of NVDA
Thanks for any help you can provide!

**Comment by btman16** [comment] 2019-08-05 14:40
Hello,

To do a silent install of NVDA, I believe you put --install-silent at the end of the command. In order to achieve this, you'd have to launch it from either the run dialog (windows key+R) or Command Prompt.
So if the file is called nvda-2019.1.1.exe then you would put:
nvda-2019.1.1.exe --install-silent
if I remember correctly.

Does that make sense?

Thanks,

Brandon

**Comment by snowflake-tvi** [comment] 2019-08-05 18:54
Great thanks!  I'm guessing for an uninstall you'd just replace the word install with uninstall in the command line?  Totally appreciate the help!

**Comment by btman16** [comment] 2019-08-05 19:15
Hello,

Unfortunately, I'm not certain that this will work. I think you'll have to do it through Programs and Features in Control Panel.

Thanks,

Brandon

**Comment by SCSchilling1** [comment] 2019-09-06 17:47
[Update] We included a fix for this AT startup issue in the Windows Insiders Preview build 18975 released today (aka.ms/wip18975): "We fixed a bug where assistive technology (e.g. Narrator, Magnifier, NVDA) were starting after sign-in when only the before sign-in setting was set."  
If any of you are part of the Windows Insider Program, we would really appreciate it if you could update to this build and see if the fix resolves the issue.  Thanks!!!

Shou-Ching Schilling
Windows Accessibility Community Champ

**Comment by josephsl** [comment] 2019-09-06 17:49
Hi, two questions: what was the cause of this issue, and will this be backported to 1903 and 1909? Thanks.

**Comment by SCSchilling1** [comment] 2019-09-07 04:54
I don't have answers for these two questions right now.  I will see if I can find out.
Thanks,
Shou-Ching

**Comment by josephsl** [comment] 2019-09-07 04:57
Hi, if the answer to the second question is “yes”, that’ll suffice for everyone. Thanks (won’t close this issue for a while).

**Comment by leonardder** [comment] 2019-09-11 07:45
I wonder, does toggling NVDA"s start at logon and after logon help if done from the ease of access center? Control panel > ease of access > sign in settings

**Comment by btman16** [comment] 2019-09-12 02:34
Hi,

No, that didn’t work when I tried it before.

Thanks,

Brandon

**Comment by btman16** [comment] 2019-10-03 16:08
Hi everyone,

Even though we don't know yet whether the fix for this issue will get backported to 1903/1909, I believe I've identified the cause of the issue, which Joseph was asking about.

Back in 1903 preview build 18334 there was a known issue where if Magnifier was set to docked mode, and set to load after sign in the machine would enter a reboot loop. I think this only happened if Magnifier was also set to start at sign in. Do you notice the trend?
The immediate issue was fixed in the following build, but the fix to that bug caused this to start screen readers when they shouldn't.

There isn't much more we as users can really do at this point and it comes down to the fact that Microsoft needs to do more thorough testing.

Sincerely,

Brandon Tyson

Sent from my iPhone

On Sep 11, 2019, at 3:45 AM, Leonard de Ruijter <notifications@github.com> wrote:

﻿
I wonder, does toggling NVDA"s start at logon and after logon help if done from the ease of access center? Control panel > ease of access > sign in settings

**Comment by SCSchilling1** [comment] 2019-10-03 18:20
Hi, everyone,
Thanks for your patience.  I don't have anything to update.  I am monitoring this issue closely and will post an update in three weeks or so.

Thanks,
Shou-Ching Schilling
Windows Accessibility Community Champ

**Comment by josephsl** [comment] 2019-10-24 18:07
Hi,

Resolved via KB4522355 (build 18362.449) based on changelog for the optional cumulative update. Closing as fixed externally.

Thanks.

**Closed by josephsl** 2019-10-24 18:07 UTC

**Comment by SCSchilling1** [comment] 2019-10-24 21:34
Thank you for bringing this issue to our attention.  
As Joseph said, the fix is in KB4522355 (OS Build 18362.449), 
https://support.microsoft.com/en-us/help/4522355

Shou-Ching
Windows Accessibility Champ
