### ISSUE TITLE
nvda can't identify some Word tables in focus mode

### ISSUE THREAD

**Issue by mohdshara** [nvaccess/nvda#8263] opened 2018-05-12 15:56 UTC
### Steps to reproduce:
Open the attached file. in the second page you can only find one table consisting of 6rows. this is followed by another table that has 5 rows. NVDA can't identify it in focus mode. in browse mode the table is identified just fine.
 
### Expected behavior:
NVDA should report all available tables.

### Actual behavior:
one table in page 2 is found while in browse mode 2 are reported.

### System configuration:
NVDA Version: master-15117,8566c376

NVDA Installed or portable:
Installed

Windows version:
Windows 10 Version 1803 (OS Build 17134.4

Name and version of other software in use when reproducing the issue:
Microsoft word 2016
### Other questions:

Does the issue still occur after restarting your PC?
yes.
Have you tried any other versions of NVDA?
I tried the stable 2018.1.1
[PROPOSITION LOGIC.docx](https://github.com/nvaccess/nvda/files/1997736/PROPOSITION.LOGIC.docx)

**Comment by michaelDCurran** [comment] 2018-05-13 22:13
Have you manually configured NvDA to use UI Automation in Microsoft Word 
at all?
Also, when you say it does not report the table, do you mean it fails to 
identify it as a table but the text in the table is still read, or do 
you mean  the cursor jumps straight over the table?

**Comment by mohdshara** [comment] 2018-05-14 05:15
I suspected that configuring NVDA to use UI automation in word would be of help, but I couldn't find how to do that at all. I read all relevant tickets though. could you please tell me how to make word use UI automation manually so that it may be of help to anyone else who can't figure it out?

**Comment by netblue44** [comment] 2018-05-14 15:39
Hi you have to do the folloing
You will need to:
1. Open nvda.ini (from your user settings directory) with a text editor.
1. Use the run dialog and type "%appdata%/nvda/"
2. Look for UIA or useInMSWordWhenAvailable
1. If there is already a UIA section just add the line 
useInMSWordWhenAvailable = True indented with a tab
2. If both are present, ensure that it is set to True not False
3. If neither are available then add the following to the bottom of the 
file:
[UIA]
     useInMSWordWhenAvailable = True
3. After you finish testing, you should delete this entry or restore 
from your backup.
—

**Comment by netblue44** [comment] 2018-05-15 15:18
If NVDA did not do this before then UIA is working note that UIA support 
is not yet stable in NVDA so please report enny bugs you find.

**Comment by Adriani90** [comment] 2019-05-07 17:09
To reproduce this issue in any word version, please do the following:
1. Open a word document
2. Create two tables under each other
3. In the second table, go to table properties
4. For the text, choose "around"
5. For the alignment, choose "left wrap"

Actual: What happens is, the text in your second table will not be in the table itself, but it will flow around the table. It might make sense for visual presentations, but from an accessible point of view this is really bad practice. I don't really understand what the use case for this design would be in practice. Why do people want to see text flowing around a table? ...
However it seems many people use this feature.
NVDA does not report the second table in focus mode when navigating line by line with up and down arrow keys. However, strange enough, you are able to access the second table when using ctrl+down arrow or just right arrow to jump from the first table into the second table. After taht you can navigate the second table also in focus mode. To do this, place the carret into the last row of the first table (for ctrl+down arrow) or into the last cell of the first table (for right arrow).

Expected: NVDA should actually treat the second table as a normal table with text although the text flows around it. It should be possible to focus the table when using up and down arrow keys in focus mode.

cc: @feerrenrut, @michaelDCurran this issue persists also when using UIA.

**Comment by Adriani90** [comment] 2023-04-03 15:28
Closing as duplicate of #6543 which has more discussion on this.

**Closed by Adriani90** 2023-04-03 15:28 UTC
Labels: close/duplicate, app/microsoft-office
