### ISSUE TITLE
NVDA doesn't link labels with custom made form elements

### ISSUE THREAD

**Issue by adkurz** [nvaccess/nvda#12641] opened 2021-07-13 08:24 UTC
Different sites use custom made form elements. Example: Instead of using a select tag for combo boxes, a div element with role="combobox" is used. If a label with a for-attribute is used to label such an element, NVDA doesn't detect that the label is linked with the element.

### Steps to reproduce:

1. Go to https://bad-nauheim.de
2. Jump with c to the next combo box

### Actual behavior:

NVDA says "combo box  collapsed  clickable"

### Expected behavior:

NVDA should say "Veranstaltungstyp combo box  collapsed  clickable"

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

alpha-23336,9409b9dd

#### Windows version:

Windows 10 21h1 x64

#### Name and version of other software in use when reproducing the issue:

Firefox 90.0 (x64)

Google Chrome 93.0.4574.0 canary (x64)

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Problem exists in nvda 2020.4 too and in other alphas since this release.

#### If add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by feerrenrut** [comment] 2021-07-13 08:56
This looks like authoring error to me, if you disagree please provide a minimal sample that we can test with. Here is the HTML copied from this control on the site (culled to two options in the combo, class and data attributes removed for brevity):

Note: 
- The label "for" is the ID of an aria-hidden element.
- element with `role="combobox"` is labelled by `'select2-category-container'` which has `title` attribute and contents of `&nbsp;` I assume this will hold the text for the selection once an item is selected.

```HTML
<div class="default">
  <label for="category">Veranstaltungstyp</label>
  <select id="category" name="category" tabindex="-1" aria-hidden="true">
    <option value=" " disabled="" selected="">&nbsp;</option>
    <option value="4312">Ausstellungen</option>
  </select>
  <span style="width: 100%;">
    <span >
      <span role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-category-container">
        <span id="select2-category-container" role="textbox" aria-readonly="true" title="&nbsp;">&nbsp;</span>
        <span role="presentation">
          <b role="presentation"></b>
        </span>
      </span>
    </span>
    <span class="dropdown-wrapper" aria-hidden="true"></span>
  </span>
</div>
```

I'm going to close this issue, it can be re-opened if an issue with NVDA is identified.

**Closed by feerrenrut** 2021-07-13 08:56 UTC

**Comment by adkurz** [comment] 2021-07-13 10:33
Ok, this wasn't the best example.

Here is a minimal example I created. Other Screen readers, like JAWS, detect the linked label, NVDA doesn't.

https://adkurz.de/test.html

**Comment by feerrenrut** [comment] 2021-07-13 10:57
This example is malformed: `<form <label="" for="test">Select test type`

When a label is part of the page content it is read as per its layout on the page, this is intended behavior.
However, when jumping to a labelled element with a (browse mode) quick nav key speaking the label would be helpful. 

@michaelDCurran What do you think about this?

**Comment by michaelDCurran** [comment] 2021-07-14 04:49
@feerrenrut  We definitely already do announce the label from aria-labelledby when jumping to an element with a browse mode quick nav key. 
See my testcase: 
[label.html.txt](https://github.com/nvaccess/nvda/files/6813553/label.html.txt)

**Comment by feerrenrut** [comment] 2021-07-14 05:16
@adkurz it turns out that browsers do not link the accessible name in a `<label>` element to a `<div>` like they would for a standard `<input>` or `<select>` element. If you are going to use a create a custom (`<div>`) combobox, use either aria-label or aria-labelled-by attributes.

**Comment by feerrenrut** [comment] 2021-07-16 02:50
You can see the list of "labelable" elements here:
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable

> Elements that can be associated with `<label>` elements. Contains `<button>`, `<input>`, `<keygen>`, `<meter>`, `<output>`, `<progress>`, `<select>`, and `<textarea>`.
