### ISSUE TITLE
Lines with too many spaces cause NVDA not to return to the previous line

### ISSUE THREAD

**Issue by brunoprietog** [nvaccess/nvda#13317] opened 2022-02-08 09:36 UTC
### Steps to reproduce:

Read the next line.

```bash
Before
                                                                                                                        
After
```

Now, press the up arrow and try to get to the first instruction.

### Actual behavior:

NVDA gets stuck on that line with many spaces. This happens in any environment where browse mode is enabled.

### Expected behavior:

NVDA should correctly return to the previous line

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

NVDA 2021.3.1

#### Windows version:

Windows 11 21H2 (x64) build 22000.469

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

I haven't tested recently, but I'm sure it's an old bug.

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by Brian1Gaff** [comment] 2022-02-08 16:27
Erm, what is going on is cursor down misses out the spaces, but cursor up 
goes in steps as witnessed by the tone you hear as you cursor up on indent 
detection.
 Not sure if that is what you mean, sounds the reverse of what you get, but 
then my email display is based on IEs engine, not anything else. Its 
probably different in Tbird or any other mail reader that uses a form of 
browse mode.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message ----- 
From: "Bruno Prieto" ***@***.***>
To: "nvaccess/nvda" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: Tuesday, February 08, 2022 9:36 AM
Subject: [nvaccess/nvda] Lines with too many spaces cause NVDA not to return 
to the previous line (Issue #13317)

**Comment by brunoprietog** [comment] 2022-02-09 09:15
I'm not sure I understand what you mean, but yes, the indent pitch sounds upward as you press the up arrow on that line with lots of spaces.

If you stand on the line below the spaces and go up with the arrow, you can count the number of spaces that NVDA detects using the review cursor with NVDA and right arrow. In this case, it starts with 20 spaces. Then you can press the up arrow and count the spaces again, now it is 21, and so NVDA again emits a higher pitched tone. This happens until it reaches a very high number of spaces and then returns to the previous line.

**Comment by CyrilleB79** [comment] 2022-08-31 12:18
For a real-life example, see [this thread](https://groups.io/g/nvda-fr/topic/re_nvda_fr_les_voix/93367432?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,93367432,previd%3D1661941202821629305,nextid%3D1658874156644888856&previd=1661941202821629305&nextid=1658874156644888856) on a French mailing list.
* With NVDA+control+F search for "Provenance Courrier de Windows"
* Try to up-arrow from there.
You remain stuck on the same line.

*

**Comment by Adriani90** [comment] 2023-12-14 21:05
Closing as duplicate of #2812.

**Closed by Adriani90** 2023-12-14 21:05 UTC
Labels: close/duplicate
