### ISSUE TITLE
allow synthesizers  that has multiple languages to have their speech rates differently for each language

### ISSUE THREAD

**Issue by mrdin8877** [nvaccess/nvda#6556] opened 2016-11-11 21:49 UTC
Hi and sorry if duplicates,

i am sorry because maybe my title is not quite descriptive. but, i will try to explain.
now i use vocalizer synthesizer and it has multi language switching capability.
all i want is the ability for me to use vocalizer for english language at fast speech rate while keeping vocalizer arabic at slow rate since i am new to this language. i hope it is possible in the future.
and also, not to vocalizer but to any other synthesizers such as espeak.

**Comment by bhavyashah** [comment] 2016-11-12 09:55
Hi,
I am uncertain about how such capabilities would be implemented. On a
related note, a technique of currently achieving the same would be to
use the SwitchSynth add-on, set Vocalizer English at a fast speech
rate for one slot, Vocalizer Arabic at a slower speech rate for the
second slot, and simply switch between them using single keystrokes
(documented on the add-on's webpage).
Thanks.

On 11/12/16, mrdin8877 <notifications@github.com> wrote:
> Hi and sorry if duplicates,
>
> i am sorry because maybe my title is not quite descriptive. but, i will try
> to explain.
> now i use vocalizer synthesizer and it has multi language switching
> capability.
> all i want is the ability for me to use vocalizer for english language at
> fast speech rate while keeping vocalizer arabic at slow rate since i am new
> to this language. i hope it is possible in the future.
> and also, not to vocalizer but to any other synthesizers such as espeak.
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/6556


-- 
Best Regards
Bhavya Shah

Avid Enthusiast and User of the Free NVDA Screen Reader (www.nvaccess.org)

Contacting Me
E-mail Address: bhavya.shah125@gmail.com
Follow me on Twitter @BhavyaShah125 or www.twitter.com/BhavyaShah125
Mobile Number: +91 7506221750

**Comment by leonardder** [comment] 2016-11-12 10:20
If this would be possible, I suggest integrating this with the
    configuration profiles structure somehow. That would also allow
    changing braille tables on the fly when the language changes.

**Comment by jcsteh** [comment] 2016-11-13 22:25
Duplicate of #4738.

**Closed by jcsteh** 2016-11-13 22:25 UTC
Labels: duplicate
