### ISSUE TITLE
NVDA reads the suggestion in the Monaco editor will read the whole line

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12721] opened 2021-08-07 17:07 UTC
Monaco editor's github repo:
https://github.com/Microsoft/monaco-editor/
### Steps to reproduce:
1. Open [this](https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=1) web page, and then click  the "Enter focus mode button ;
2. After entering, press the letter E in the browse mode to jump to the code editing area;
3. Press the space key to enter the focus mode, try typing "Console.";
4. Use the up/down arrows to browse the code suggestions provided;

### Actual behavior:
As the up/down arrow move, NVDA will not only report suggestions, but also report the entered "Console". For example:
- Console.BackgroundColor, suggestion
- Console.Beep, suggestion 
- Console.BufferHeight, suggestion 
- BufferWidth, suggestion 
### Expected behavior:
NVDA only reports suggestion And ignore the whole line. such as:
- BackgroundColor, suggestion 
- Beep, suggestion 
- BufferHeight, suggestion 
- BufferWidth, suggestion 
#### NVDA installed/portable/running from source:
installed and portable
#### NVDA version:
NVDA2021.1
#### Windows version:
Windows 10 21H1 (x64) build 19043.1110
#### Name and version of other software in use when reproducing the issue:
Google Chrome 92.0.4515.131
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by cary-rowen** [comment] 2021-08-07 17:14
From the description of the readme, you can know that the editor is the same as the one used in VS Code, so I think the behavior of NVDA should be the same.

In addition: I think NVDA should invest more time in the development tools of programmers, which of course includes Visual studio.

Thanks

**Comment by akash07k** [comment] 2021-08-14 08:26
I second this, this issue is really irritating sometimes

**Comment by Adriani90** [comment] 2021-08-17 14:13
cc: @leonardder

**Comment by leonardder** [comment] 2021-08-17 16:02
The behavior I experience in this instance of Monaco is *not* the same as in VS Code. IN VS code, this does not occur.
cc @isidorn

**Comment by cary-rowen** [comment] 2021-08-17 16:09
Yes, I also created an issue in the Monaco repo:
https://github.com/microsoft/monaco-editor/issues/2615

**Comment by isidorn** [comment] 2021-08-18 12:20
I have commented on the issue. To have it all in one place, here's what I said (regarding NVDA):

I tried reproducing this using your exact steps on Windows with monaco editor and NVDA and I can not reproduce. Though I did not explicitly change NVDA modes. So this seems to be very specific for NVDA and explicitly changing modes. Why would NVDA append the word `suggestion` in focus mode?

**Comment by leonardder** [comment] 2021-08-18 13:03
I'm under the impression that NVDA reads suggestions using a live region in this instance of Monaco, whereas in VS Code, suggestions are exposes using a list view.

**Comment by isidorn** [comment] 2021-08-18 13:47
That should not be the case. We do not use live regions for suggestions.
Though there might be some corner case I am not thinking of

**Comment by leonardder** [comment] 2021-08-18 16:07
Yet, it is definitely a live region. Here is output from the NVDA event tracker add-on
```log
DEBUG - external:globalPlugins.evtTracker.GlobalPlugin.evtDebugLogging (18:05:36.397) - MainThread (20508):
EvtTracker: object: <NVDAObjects.Dynamic_DialogDialogIa2WebIAccessible object at 0x07CE61B0>
name: None
role: ALERT
event: liveRegionChange
app module: <'appModuleHandler' (appName 'msedge', process ID 21056) at address 6ac32b0>
window class name: Chrome_RenderWidgetHostHWND
IAccessible accName: None
IAccessibleChildID: 0
```

I'm also getting the "occurred again" message if a suggestion repeats. That somehow sounds familiar.
Could we track down what version of monaco is active in the example?

**Comment by isidorn** [comment] 2021-08-19 07:29
@hediet can you double check if the monaco editor for that version ever calls [`alert`](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/aria/aria.ts#L49) or [`status`](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/aria/aria.ts#L67). It should not, since we do all the focus goodness for suggest widgets and then those methods are not needed. I checked the code and I could not find any calls, but maybe there is something special going on for the editor.

**Comment by hediet** [comment] 2021-08-19 08:36
I don't know all the details of the monaco editor yet. @alexdima do you know if alert or status is called?

**Comment by isidorn** [comment] 2021-08-19 08:52
I checked all the references and could not find it.
The best would be if we are successful in reproducing this, and I could not repro.
@hediet did you give it a try?

**Comment by hediet** [comment] 2021-08-19 09:03
I can verify that:
* the issue happens as described on https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=1 when entering focus mode
* this issue is not reproducible on https://microsoft.github.io/monaco-editor/
* this issue is not reproducible in Vs Code

I guess either https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/tutorials/hello-world?tutorial-step=1 uses an outdated version of monaco or they do some other stuff that interfers with NVDA.

**Comment by cary-rowen** [comment] 2021-08-19 09:15
You can also test the behavior of the Monaco editor from https://try.dot.net/.

**Comment by isidorn** [comment] 2021-08-19 09:24
Since the issue is not reproducible with latest monaco-editor I suggest to close this.
This is just an outdated version of the editor. Those websites should update.

**Comment by cary-rowen** [comment] 2021-08-19 09:35
To be honest, I chose CSharp in the editor at https://microsoft.github.io/monaco-editor/ and typed "Console." in the editor. I didn't get any code suggestions.
This prevents me from confirming the true behavior of NVDA in this editor.
@isidorn

**Comment by isidorn** [comment] 2021-08-19 09:50
@cary-rowen we do not have full language support for CSharp in the web editor. We have just word completions.
We have stronger language support for Javascript, so you can confirm using that, or CSHarp and word completions.

**Comment by leonardder** [comment] 2021-08-19 11:01
It is likely that all the versions of monaco where this problem occur are simply not up to date.
Closing as works for me.

**Closed by leonardder** 2021-08-19 11:01 UTC

**Comment by cary-rowen** [comment] 2021-08-19 14:34
Thanks @leonardder for the answer.
