### ISSUE TITLE
NVDA freezes briefly with WASAPI enabled and receives AttributeError: 'NoneType' object has no attribute 'feed'

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#15311] opened 2023-08-18 11:21 UTC
cc @jcsteh Maybe you can take a look at this Issue.
### Steps to reproduce:
This issue may require a specific add-on to reproduce, but I've confirmed that it can only be reproduced with WASAPI enabled.

1. Install [ClipBoardEnhancement add-on](https:github.com/cary-rowen/clipboardEnhancement/releases/download/v2.7.1/clipboardEnhancement-2.7.1.nvda-addon).
2. Please press Ctrl+C copy a file to the system clipboard at will.
3. Press Ctrl+Numpad7/Numpad9.
    - Laptop: NVDA+Alt+UpArrow/DownArrow
    - The function of this gesture is to report the name and path of the file in the clipboard.
   - `nvwave.playWaveFile` is called in the process.
4. Repeat step (3) repeatedly.
5. When performing steps (3) and (4), you can feel that NVDA freezes briefly, and you can find some errors in the log.
### Actual behavior:
Found the following in the NVDA log:
```
IO - inputCore.InputManager.executeGesture (18:54:14.232) - winInputHook (8472):
Input: kb(laptop):alt+NVDA+downArrow
ERROR - stderr (18:54:16.126) - nvwave.playWaveFile(FileInClipboard.wav) (9880):
Exception in thread nvwave.playWaveFile(FileInClipboard.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
```
### Expected behavior:
NVDA should not brief freezes without 'AttributeError'.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-28879,a7981cad 
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.3324
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
nvda-2023.2Beta3 can also reproduce this as long as WASAPI is enabled.
#### If NVDA add-ons are disabled, is your problem still occurring?
No
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by zstanecic** [comment] 2023-08-18 11:23
Hi,

I can see this even without addons installed, and it is random. 

 

 

From: Rowen ***@***.***> 
Sent: Friday, August 18, 2023 1:21 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] NVDA freezes briefly with WASAPI enabled and receives AttributeError: 'NoneType' object has no attribute 'feed' (Issue #15311)

 

cc @jcsteh <https://github.com/jcsteh>  Maybe you can take a look at this Issue.


Steps to reproduce:


This issue may require a specific add-on to reproduce, but I've confirmed that it can only be reproduced with WASAPI enabled.

1.	Install ClipBoardEnhancement add-on <https://github.com/cary-rowen/clipboardEnhancement/releases/download/v2.7.1/clipboardEnhancement-2.7.1.nvda-addon> .
2.	Please press Ctrl+C copy a file to the system clipboard at will.
3.	Press Ctrl+Numpad7/Numpad9. 

*	Laptop: NVDA+Alt+UpArrow/DownArrow
*	The function of this gesture is to report the name and path of the file in the clipboard.
*	nvwave.playWaveFile is called in the process.

4.	Repeat step (3) repeatedly.
5.	When performing steps (3) and (4), you can feel that NVDA freezes briefly, and you can find some errors in the log.


Actual behavior:


Found the following in the NVDA log:

IO - inputCore.InputManager.executeGesture (18:54:14.232) - winInputHook (8472):
Input: kb(laptop):alt+NVDA+downArrow
ERROR - stderr (18:54:16.126) - nvwave.playWaveFile(FileInClipboard.wav) (9880):
Exception in thread nvwave.playWaveFile(FileInClipboard.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'

Expected behavior:


NVDA should not brief freezes without 'AttributeError'.


NVDA logs, crash dumps and other attachments:


System configuration


NVDA installed/portable/running from source:


Installed


NVDA version:


alpha-28879,a7981cad


Windows version:


Windows 10 22H2 (AMD64) build 19045.3324


Name and version of other software in use when reproducing the issue:


None


Other information about your system:


None


Other questions


Does the issue still occur after restarting your computer?


Yes


Have you tried any other versions of NVDA? If so, please report their behaviors.


nvda-2023.2Beta3 can also reproduce this as long as WASAPI is enabled.


If NVDA add-ons are disabled, is your problem still occurring?


No


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


Yes

**Comment by cary-rowen** [comment] 2023-08-18 11:25
"AttributeError: 'NoneType' object has no attribute 'feed'"

I've also observed this error with other add-ons that use `nvwave.playWaveFile`, but it doesn't freeze NVDA.
such as: https://github.com/nvda-es/TeleNVDA

**Comment by seanbudd** [comment] 2023-08-31 04:52
cc @jcsteh - @cary-rowen, this may be fixed in the next alpha build (building soon)

**Comment by jcsteh** [comment] 2023-08-31 05:49
I suspect this is a different issue, but it'll be interesting to see. I don't really understand how WASAPI could be causing this.

**Comment by seanbudd** [comment] 2023-08-31 06:34
If this can't be reproduced with add-ons disabled with the latest alpha, we can probably close the issue

**Comment by jcsteh** [comment] 2023-08-31 06:37
To clarify my previous comment, it looks like fileWavePlayer becomes None. fileWavePlayer is set up the same way regardless of whether it's WASAPI or not. Exceptions can certainly occur within WASAPI, but nothing in the WASAPI code can clear references to the actual instance altogether.

**Comment by cary-rowen** [comment] 2023-08-31 13:34
I tested the latest alpha-29021 and it can be reproduced.
It should be noted that there is a possibility of encountering this problem even if I disable the add-on, but it cannot be reproduced stably. The reason why I mention this add-on is because I hope to clarify this bug in a feasible way.

**Comment by Adriani90** [comment] 2023-09-08 08:06
This is the only issue I can see so far that might or not be related to Wasapi. This should not prevent Wasapi from becomming the default in 2023.3. as of now using Wasapi is the default only in alpha channel right?

**Comment by seanbudd** [comment] 2023-09-08 08:12
WASAPI will be default in the 2023.3beta1 and is current default in alpha. It is not default in 2023.2.

We consider fixing this issue a "nice to have" for 2023.3

**Comment by beqabeqa473** [comment] 2023-10-25 08:04
This issue is still reproduceable.
Are there attempts to fix that?
@jcsteh

**Comment by beqabeqa473** [comment] 2023-10-25 08:06
ERROR - stderr (12:01:44.523) - MainThread (13532):
Exception ignored in:
ERROR - stderr (12:01:44.535) - MainThread (13532):
<function WasapiWavePlayer.__del__ at 0x03E59ED0>
ERROR - stderr (12:01:44.949) - nvwave.playWaveFile(error.wav) (16680):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:44.949) - MainThread (13532):
Traceback (most recent call last):
ERROR - stderr (12:01:44.963) - MainThread (13532):
  File "nvwave.pyc", line 840, in __del__
ERROR - stderr (12:01:45.378) - nvwave.playWaveFile(error.wav) (17520):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:45.378) - MainThread (13532):
  File "weakref.pyc", line 146, in __delitem__
ERROR - stderr (12:01:45.391) - MainThread (13532):
KeyError
ERROR - stderr (12:01:45.402) - MainThread (13532):
:
ERROR - stderr (12:01:45.822) - nvwave.playWaveFile(error.wav) (10648):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:45.822) - MainThread (13532):
64153688
ERROR - stderr (12:01:45.840) - MainThread (13532):
Exception ignored in:
ERROR - stderr (12:01:45.850) - MainThread (13532):
<function WasapiWavePlayer.__del__ at 0x03E59ED0>
ERROR - stderr (12:01:46.267) - nvwave.playWaveFile(error.wav) (15236):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:46.267) - MainThread (13532):
Traceback (most recent call last):
ERROR - stderr (12:01:46.279) - MainThread (13532):
  File "nvwave.pyc", line 840, in __del__
ERROR - stderr (12:01:46.695) - nvwave.playWaveFile(error.wav) (10784):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:46.695) - MainThread (13532):
  File "weakref.pyc", line 146, in __delitem__
ERROR - stderr (12:01:46.708) - MainThread (13532):
KeyError
ERROR - stderr (12:01:47.124) - nvwave.playWaveFile(error.wav) (11032):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'
ERROR - stderr (12:01:47.124) - MainThread (13532):
:
ERROR - stderr (12:01:47.137) - MainThread (13532):
64151768
ERROR - stderr (12:01:47.554) - nvwave.playWaveFile(error.wav) (14288):
Exception in thread nvwave.playWaveFile(error.wav):
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "threading.pyc", line 870, in run
  File "nvwave.pyc", line 710, in play
AttributeError: 'NoneType' object has no attribute 'feed'

**Comment by jcsteh** [comment] 2023-10-25 08:56
Does the add-on play sounds from a background thread? I guess that might cause weirdness, but again, that's not unique to WASAPI.

**Comment by jcsteh** [comment] 2023-10-25 09:02
Ah. Is it possible there are some earlier exceptions in the log? I think the key part might be the weakref KeyError part, rather than the AttributeError part. The weakref part is specific to WASAPI, but I don't know how we're getting into that state.

**Comment by jcsteh** [comment] 2023-10-25 09:15
Aha. It intermittently seems to be due to playing multiple sounds rapidly. You can reproduce it with this Python console snippet:

`import nvwave; nvwave.playWaveFile("waves/browseMode.wav"); nvwave.playWaveFile("waves/browseMode.wav"); nvwave.playWaveFile("waves/browseMode.wav")`

**Comment by beqabeqa473** [comment] 2023-10-25 09:30
It is not depended to the addon. It happens even with addons disabled.

On 10/25/23, James Teh ***@***.***> wrote:
> Aha. It intermittently seems to be due to playing multiple sounds rapidly.
> You can reproduce it with this Python console snippet:
>
> `import nvwave; nvwave.playWaveFile("waves/browseMode.wav");
> nvwave.playWaveFile("waves/browseMode.wav");
> nvwave.playWaveFile("waves/browseMode.wav")`
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/15311#issuecomment-1778848394
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Closed** 2023-10-26 22:06 UTC
Labels: bug/regression, p4, component/audio, triaged
