### ISSUE TITLE
nvda bug in win 10 mail app

### ISSUE THREAD

**Issue by mjonsson1986** [nvaccess/nvda#10094] opened 2019-08-14 14:50 UTC
seems it only happen with some emails
in the mail app when you are in the mail list and e.g press down arrow
ERROR - eventHandler.executeEvent (16:42:52.007):
error executing event: becomeNavigatorObject on <NVDAObjects.Dynamic_MailItemRowListItemUIA object at 0x014A8DF0> with extra args of {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1061, in event_becomeNavigatorObject
  File "braille.pyc", line 1963, in handleReviewMove
  File "braille.pyc", line 1839, in _doNewObject
  File "braille.pyc", line 1520, in getFocusRegions
  File "braille.pyc", line 619, in update
  File "braille.pyc", line 429, in update
  File "louisHelper.pyc", line 65, in translate
  File "louis\__init__.pyc", line 171, in translate
  File "louis\__init__.pyc", line 57, in <lambda>
UnicodeEncodeError: 'utf-32-le' codec can't encode character '\ude6a' in position 111: surrogates not allowed
ERROR - eventHandler.executeEvent (16:48:10.629):
error executing event: becomeNavigatorObject on <NVDAObjects.Dynamic_MailItemRowListItemUIA object at 0x0132D630> with extra args of {'isFocus': True}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 1061, in event_becomeNavigatorObject
  File "braille.pyc", line 1963, in handleReviewMove
  File "braille.pyc", line 1839, in _doNewObject
  File "braille.pyc", line 1520, in getFocusRegions
  File "braille.pyc", line 619, in update
  File "braille.pyc", line 429, in update
  File "louisHelper.pyc", line 65, in translate
  File "louis\__init__.pyc", line 171, in translate
  File "louis\__init__.pyc", line 57, in <lambda>
UnicodeEncodeError: 'utf-32-le' codec can't encode character '\ude6a' in position 111: surrogates not allowed

latest nvda dev snapshot of 2019.3

**Comment by Adriani90** [comment] 2019-08-14 15:41
cc: @leonardder, @Andre9642.

**Comment by Andre9642** [comment] 2019-08-14 16:56
Currently I'm unable to reproduce the issue. What braille table do you use? In which language?
However it's likely a quick fix, like an `errors="surrogatepass"` argument to pass.
@leonardder what do you think? Should we modify the Python binding or try to fix on the NVDA side rather?

**Comment by Andre9642** [comment] 2019-08-14 17:13
OK, now I confirm the issue. I'll fill an issue on Liblouis repo and make a PR shortly.

**Comment by Andre9642** [comment] 2019-08-14 18:14
Finally, @leonardder has already fixed this issue in https://github.com/liblouis/liblouis/pull/784.
This will be fixed in Liblouis 3.11 (begin of september)

**Closed** 2019-10-04 00:12 UTC
