### ISSUE TITLE
table with colspans in first row results in second row's initial cell's header attribute ignored

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5240] opened 2015-07-23 13:34 UTC
**Reported by powrsurg on 2015-07-23 13:34**
We came have a complicated table where we wanted an image to have a rowspan="2" as defined in the first row, and then would use the headers attribute on the various cells to read the appropriate table header to the user.  In the first row this reads header for the next cell (which has a colspan="2"), but in the second row the first cell is ignored as it just reads that it's the start of the next row, and then reads the second cell's header appropriately. The following codepen (with help from Steve Faukner) illustrates this example:

http://codepen.io/stevef/pen/zGJJON

**Comment by leonardder** [comment] 2018-02-17 12:32
@powrsurg: Are you the one who opened this issue? If so, could you still reproduce this? Note that current NVDA next snapshots will automatically read row and column span for table cells.

**Comment by Adriani90** [comment] 2019-01-29 21:52
@powrsurg I am using NVDA 2018.4.1 and Firefox 64.0.2. I cannot really reproduce this issue. When I am in a column other than column 1, all headers are reported properly. That is:
1. From left to right the course title and cousre status where possible
2. From top to bottom the course title and course time.

Note: The cell where course status is reported can only be reached from the cell where course time is the row header.

Can you confirm that the issue is not reproducible anymore with NVDA 2018.4.1? Thanks.

**Comment by Adriani90** [comment] 2020-04-19 12:29
We do not have any update on this, and I cannot reproduce it really. Closing as works for me. We can reopen if there is any further update which proves that this is is still an issue.

**Closed by Adriani90** 2020-04-19 12:29 UTC
Labels: bug, close/worksforme
