### ISSUE TITLE
random errors in NVDA

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#5844] opened 2016-03-31 00:03 UTC
good night, darlings.
During use NVDA on several occasions appears a windows error that says something like:
error in nvda.exe application, unknown error when reading memory at:
During this error can not do anything on the machine, full lock, having to restart.
I received this error when typing enter a message in the Inbox in Outlook, and then to open the windows explorer.
This error does not occur every time you use the Explorer and Outlook, but is more or less a 2 times a day for computer use.
attached a recovered file NVDA log.
Thank you very much.
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/196775/nvda-old.log.txt)

**Comment by jcsteh** [comment] 2016-03-31 01:29
Do you have any add-ons installed? If so, please try with add-ons disabled, which you can do from the Exit NVDA dialog.

What we really need here is a crash dump. See [this article for details about where to find it](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps).

**Comment by fernando-jose-silva** [comment] 2016-04-02 16:03
Good afternoon, thank you forreturning.
I usedNVDAwithoutsupplements andrandom errorscontinued,is attachedwindowserrorfile,this callis very similarto the opencall:5849.
[nvda_crash.dmp.txt](https://github.com/nvaccess/nvda/files/200900/nvda_crash.dmp.txt)

**Comment by derekriemer** [comment] 2016-04-02 22:40
I'll take a look. Also, did you know that your computer seems to not be 
inserting spaces between most of your words?

On 4/2/2016 10:03 AM, fernando-jose-silva wrote:
>
> Good afternoon, thank you forreturning.
> I usedNVDAwithoutsupplements andrandom errorscontinued,is 
> attachedwindowserrorfile,this callis very similarto the opencall:5849.
> nvda_crash.dmp.txt 
> <https://github.com/nvaccess/nvda/files/200900/nvda_crash.dmp.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5844#issuecomment-204744645>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment] 2016-04-02 22:56
This is odd, when I decode his words, I see this which looks 
suspiciously like a phishing email or some crappy way to get people to 
be spammed. If you are not a bot, I am really sorry. I think this 
because I see the word supplements in here, which seems like a spamming 
trick. However, this information is part of the attached file.

Dump Summary
------------
Dump File:    nvda_crash.dmp : C:\Users\derek_2\Downloads\nvda_crash.dmp
Last Write Time:    4/2/2016 4:41:21 PM
Process Name:    nvda.exe : C:\Program Files (x86)\NVDA\nvda.exe
Process Architecture:    x86
Exception Code:    0xC0000005
Exception Information:    The thread tried to read from or write to a 
virtual address for which it does not have the appropriate access.
Heap Information:    Not Present

System Information
------------------
OS Version:    10.0.10586
CLR Version(s):

Modules
-------
Module Name    Module Path    Module Version
-----------    -----------    --------------
nvda.exe    C:\Program Files (x86)\NVDA\nvda.exe    0.0.0.0
ntdll.dll    C:\Windows\System32\ntdll.dll    10.0.10586.122
kernel32.dll    C:\Windows\System32\kernel32.dll    10.0.10586.0
KERNELBASE.dll    C:\Windows\System32\KERNELBASE.dll 10.0.10586.162
apphelp.dll    C:\Windows\System32\apphelp.dll    10.0.10586.0
AcGenral.dll    C:\Windows\AppPatch\AcGenral.dll    10.0.10586.17
msvcrt.dll    C:\Windows\System32\msvcrt.dll    7.0.10586.0
sechost.dll    C:\Windows\System32\sechost.dll    10.0.10586.0
rpcrt4.dll    C:\Windows\System32\rpcrt4.dll    10.0.10586.0
sspicli.dll    C:\Windows\System32\sspicli.dll    10.0.10586.0
CRYPTBASE.dll    C:\Windows\System32\CRYPTBASE.dll    10.0.10586.0
bcryptPrimitives.dll    C:\Windows\System32\bcryptPrimitives.dll 
10.0.10586.0
shlwapi.dll    C:\Windows\System32\shlwapi.dll    10.0.10586.0
combase.dll    C:\Windows\System32\combase.dll    10.0.10586.103
gdi32.dll    C:\Windows\System32\gdi32.dll    10.0.10586.63
user32.dll    C:\Windows\System32\user32.dll    10.0.10586.20
ole32.dll    C:\Windows\System32\ole32.dll    10.0.10586.162
oleaut32.dll    C:\Windows\System32\oleaut32.dll    10.0.10586.0
shell32.dll    C:\Windows\System32\shell32.dll    10.0.10586.122
cfgmgr32.dll    C:\Windows\System32\cfgmgr32.dll    10.0.10586.0
windows.storage.dll    C:\Windows\System32\windows.storage.dll 
10.0.10586.162
advapi32.dll    C:\Windows\System32\advapi32.dll    10.0.10586.63
kernel.appcore.dll    C:\Windows\System32\kernel.appcore.dll 10.0.10586.0
SHCore.dll    C:\Windows\System32\SHCore.dll    10.0.10586.0
powrprof.dll    C:\Windows\System32\powrprof.dll    10.0.10586.0
profapi.dll    C:\Windows\System32\profapi.dll    10.0.10586.0
uxtheme.dll    C:\Windows\System32\uxtheme.dll    10.0.10586.0
winmm.dll    C:\Windows\System32\winmm.dll    10.0.10586.0
samcli.dll    C:\Windows\System32\samcli.dll    10.0.10586.0
msacm32.dll    C:\Windows\System32\msacm32.dll    10.0.10586.0
version.dll    C:\Windows\System32\version.dll    10.0.10586.0
userenv.dll    C:\Windows\System32\userenv.dll    10.0.10586.0
dwmapi.dll    C:\Windows\System32\dwmapi.dll    10.0.10586.0
urlmon.dll    C:\Windows\System32\urlmon.dll    11.0.10586.122
winspool.drv    C:\Windows\System32\winspool.drv    10.0.10586.122
mpr.dll    C:\Windows\System32\mpr.dll    10.0.10586.0
WINMMBASE.dll    C:\Windows\System32\WINMMBASE.dll    10.0.10586.0
iertutil.dll    C:\Windows\System32\iertutil.dll    11.0.10586.122
bcrypt.dll    C:\Windows\System32\bcrypt.dll    10.0.10586.0
imm32.dll    C:\Windows\System32\imm32.dll    10.0.10586.0
gwmhook.dll    C:\Windows\System32\gwmhook.dll    0.0.0.0
psapi.dll    C:\Windows\System32\psapi.dll    10.0.10586.0
oleacc.dll    C:\Windows\System32\oleacc.dll    7.2.10586.0
msvcr90.dll 
C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9\msvcr90.dll 
9.0.30729.9177
python27.dll    C:\Program Files (x86)\NVDA\python27.dll 2.7.11150.1013
_ctypes.pyd    C:\Program Files (x86)\NVDA\_ctypes.pyd    0.0.0.0
_hashlib.pyd    C:\Program Files (x86)\NVDA\_hashlib.pyd    0.0.0.0
cryptsp.dll    C:\Windows\System32\cryptsp.dll    10.0.10586.0
rsaenh.dll    C:\Windows\System32\rsaenh.dll    10.0.10586.0
winsound.pyd    C:\Program Files (x86)\NVDA\winsound.pyd    0.0.0.0
wx._core_.pyd    C:\Program Files (x86)\NVDA\wx._core_.pyd 0.0.0.0
wxbase30u_vc90.dll    C:\Program Files (x86)\NVDA\wxbase30u_vc90.dll    
3.0.2.0
wxbase30u_net_vc90.dll    C:\Program Files 
(x86)\NVDA\wxbase30u_net_vc90.dll    3.0.2.0
wxmsw30u_core_vc90.dll    C:\Program Files 
(x86)\NVDA\wxmsw30u_core_vc90.dll    3.0.2.0
comdlg32.dll    C:\Windows\System32\comdlg32.dll    10.0.10586.0
FirewallAPI.dll    C:\Windows\System32\FirewallAPI.dll 10.0.10586.162
netapi32.dll    C:\Windows\System32\netapi32.dll    10.0.10586.0
wxmsw30u_adv_vc90.dll    C:\Program Files 
(x86)\NVDA\wxmsw30u_adv_vc90.dll    3.0.2.0
msvcp90.dll 
C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9177_none_5093cc7abcb795e9\msvcp90.dll 
9.0.30729.9177
wsock32.dll    C:\Windows\System32\wsock32.dll    10.0.10586.0
ws2_32.dll    C:\Windows\System32\ws2_32.dll    10.0.10586.0
comctl32.dll 
C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.10586.0_none_d3c2e4e965da4528\comctl32.dll 
6.10.10586.0
davhlpr.dll    C:\Windows\System32\davhlpr.dll    10.0.10586.0
fwbase.dll    C:\Windows\System32\fwbase.dll    10.0.10586.162
wx._gdi_.pyd    C:\Program Files (x86)\NVDA\wx._gdi_.pyd    0.0.0.0
wx._windows_.pyd    C:\Program Files (x86)\NVDA\wx._windows_.pyd 0.0.0.0
wxmsw30u_html_vc90.dll    C:\Program Files 
(x86)\NVDA\wxmsw30u_html_vc90.dll    3.0.2.0
wx._controls_.pyd    C:\Program Files (x86)\NVDA\wx._controls_.pyd    
0.0.0.0
wx._misc_.pyd    C:\Program Files (x86)\NVDA\wx._misc_.pyd 0.0.0.0
MMDevAPI.dll    C:\Windows\System32\MMDevAPI.dll    10.0.10586.0
devobj.dll    C:\Windows\System32\devobj.dll    10.0.10586.0
propsys.dll    C:\Windows\System32\propsys.dll    7.0.10586.0
wdmaud.drv    C:\Windows\System32\wdmaud.drv    10.0.10586.0
ksuser.dll    C:\Windows\System32\ksuser.dll    10.0.10586.0
avrt.dll    C:\Windows\System32\avrt.dll    10.0.10586.0
AudioSes.dll    C:\Windows\System32\AudioSes.dll    10.0.10586.71
WinTypes.dll    C:\Windows\System32\WinTypes.dll    10.0.10586.103
msacm32.drv    C:\Windows\System32\msacm32.drv    10.0.10586.0
midimap.dll    C:\Windows\System32\midimap.dll    10.0.10586.0
clbcatq.dll    C:\Windows\System32\clbcatq.dll 2001.12.10941.16384
_socket.pyd    C:\Program Files (x86)\NVDA\_socket.pyd    0.0.0.0
_ssl.pyd    C:\Program Files (x86)\NVDA\_ssl.pyd    0.0.0.0
crypt32.dll    C:\Windows\System32\crypt32.dll    10.0.10586.0
msasn1.dll    C:\Windows\System32\msasn1.dll    10.0.10586.0
unicodedata.pyd    C:\Program Files (x86)\NVDA\unicodedata.pyd 0.0.0.0
pyexpat.pyd    C:\Program Files (x86)\NVDA\pyexpat.pyd    0.0.0.0
liblouis.dll    C:\Program Files (x86)\NVDA\liblouis.dll    0.0.0.0
windowsAccessBridge-32.DLL 
C:\Windows\System32\windowsAccessBridge-32.DLL    2.0.6.0
win32clipboard.pyd    C:\Program Files (x86)\NVDA\win32clipboard.pyd    
2.7.218.0
pywintypes27.dll    C:\Program Files (x86)\NVDA\pywintypes27.dll 2.7.218.0
nvdaHelperLocal.dll    C:\Program Files 
(x86)\NVDA\lib\nvdaHelperLocal.dll    0.0.0.0
usp10.dll    C:\Windows\System32\usp10.dll    10.0.10586.0
UIAutomationCore.dll    C:\Windows\System32\UIAutomationCore.dll 
7.2.10586.17
nvdaHelperRemote.dll    C:\Program Files 
(x86)\NVDA\lib\nvdaHelperRemote.dll    0.0.0.0
dbghelp.dll    C:\Windows\System32\dbghelp.dll    10.0.10586.0
dbgcore.dll    C:\Windows\System32\dbgcore.dll    10.0.10586.0
IAccessible2Proxy.dll    C:\Program Files 
(x86)\NVDA\lib\IAccessible2Proxy.dll    0.0.0.0
minHook.dll    C:\Program Files (x86)\NVDA\lib\minHook.dll 1.2.2.0
ve.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\vocalizer_expressive_driver\synthDrivers\vocalizer_expressive\common\speech\components\ve.dll 
1.1.1.13071
msvcr80.dll 
C:\Windows\WinSxS\x86_microsoft.vc80.crt_1fc8b3b9a1e18e3b_8.0.50727.9193_none_d09188224426efcd\msvcr80.dll 
8.0.50727.9193
nuan_platform.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\vocalizer_expressive_driver\synthDrivers\vocalizer_expressive\common\speech\components\nuan_platform.dll 
0.0.0.0
msctf.dll    C:\Windows\System32\msctf.dll    10.0.10586.71
sxs.dll    C:\Windows\System32\sxs.dll    10.0.10586.0
msftedit.dll    C:\Windows\System32\msftedit.dll    10.0.10586.17
soft_oal.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\winWizard\globalPlugins\winWizard\camlorn_audio\soft_oal.dll 
0.0.0.0
libsndfile-1.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\winWizard\globalPlugins\winWizard\camlorn_audio\libsndfile-1.dll 
1.0.25.0
camlorn_audio_c.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\winWizard\globalPlugins\winWizard\camlorn_audio\camlorn_audio_c.dll 
0.0.0.0
dsound.dll    C:\Windows\System32\dsound.dll    10.0.10586.0
bass.dll    C:\Users\ferna\AppData\Roaming\nvda\addons\Weather 
Plus\globalPlugins\weather\bass.dll    2.4.11.0
NapiNSP.dll    C:\Windows\System32\NapiNSP.dll    10.0.10586.0
pnrpnsp.dll    C:\Windows\System32\pnrpnsp.dll    10.0.10586.0
nlaapi.dll    C:\Windows\System32\nlaapi.dll    10.0.10586.0
mswsock.dll    C:\Windows\System32\mswsock.dll    10.0.10586.0
dnsapi.dll    C:\Windows\System32\dnsapi.dll    10.0.10586.0
nsi.dll    C:\Windows\System32\nsi.dll    10.0.10586.0
winrnr.dll    C:\Windows\System32\winrnr.dll    10.0.10586.0
wshbth.dll    C:\Windows\System32\wshbth.dll    10.0.10586.0
mdnsNSP.dll    C:\Program Files (x86)\Bonjour\mdnsNSP.dll    3.1.0.1
IPHLPAPI.DLL    C:\Windows\System32\IPHLPAPI.DLL    10.0.10586.0
win32api.pyd    C:\Program Files (x86)\NVDA\win32api.pyd 2.7.218.0
secur32.dll    C:\Windows\System32\secur32.dll    10.0.10586.0
win32process.pyd 
C:\Users\ferna\AppData\Roaming\nvda\addons\sayProductNameAndVersion\globalPlugins\sayProductNameAndVersion\win32process.pyd 
2.7.216.0
_psutil_windows.pyd 
C:\Users\ferna\AppData\Roaming\nvda\addons\resourceMonitor\globalPlugins\resourceMonitor\psutil\_psutil_windows.pyd 
0.0.0.0
wtsapi32.dll    C:\Windows\System32\wtsapi32.dll    10.0.10586.0
select.pyd    C:\Program Files (x86)\NVDA\select.pyd    0.0.0.0
_imaging.pyd 
C:\Users\ferna\AppData\Roaming\nvda\addons\ocr\globalPlugins\ocr\PIL\_imaging.pyd 
0.0.0.0
_portaudio.pyd 
C:\Users\ferna\AppData\Roaming\nvda\addons\googleSpeechRecognition\globalPlugins\googleSpeechRecognition\_portaudio.pyd 
0.0.0.0
etree.pyd    C:\Users\ferna\AppData\Roaming\nvda\addons\File 
Reader\globalPlugins\reader\lxml\etree.pyd    0.0.0.0
libsndfile-1.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\audioScreen\globalPlugins\audioScreen\deps\libaudioverse\libsndfile-1.dll 
1.0.25.0
libaudioverse.dll 
C:\Users\ferna\AppData\Roaming\nvda\addons\audioScreen\globalPlugins\audioScreen\deps\libaudioverse\libaudioverse.dll 
0.0.0.0
twinapi.dll    C:\Windows\System32\twinapi.dll    10.0.10586.0
twinapi.appcore.dll    C:\Windows\System32\twinapi.appcore.dll 10.0.10586.0
netutils.dll    C:\Windows\System32\netutils.dll    10.0.10586.0
wkscli.dll    C:\Windows\System32\wkscli.dll    10.0.10586.0
srvcli.dll    C:\Windows\System32\srvcli.dll    10.0.10586.0
rasadhlp.dll    C:\Windows\System32\rasadhlp.dll    10.0.10586.71
FWPUCLNT.DLL    C:\Windows\System32\FWPUCLNT.DLL    10.0.10586.0
actxprxy.dll    C:\Windows\System32\actxprxy.dll    10.0.10586.0
pythoncom27.dll    C:\Program Files (x86)\NVDA\pythoncom27.dll 2.7.218.0
mshtml.dll    C:\Windows\System32\mshtml.dll    11.0.10586.162
ieproxy.dll    C:\Windows\System32\ieproxy.dll    11.0.10586.0
dispex.dll    C:\Windows\System32\dispex.dll    5.812.10586.0
setupapi.dll    C:\Windows\System32\setupapi.dll    10.0.10586.0

Good afternoon, thank you for returning.
I used NVDA without supplements and random errors continued,is attached 
windows error file,this callis very similar to the open call:5849.

The windows error
On 4/2/2016 10:03 AM, fernando-jose-silva wrote:
>
> Good afternoon, thank you forreturning.
> I usedNVDAwithoutsupplements andrandom errorscontinued,is 
> attachedwindowserrorfile,this callis very similarto the opencall:5849.
> nvda_crash.dmp.txt 
> <https://github.com/nvaccess/nvda/files/200900/nvda_crash.dmp.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5844#issuecomment-204744645>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by fernando-jose-silva** [comment] 2016-04-04 17:15
Good afternoon, thank you for returning.
The lack of space in the words, I believe that the error is in the fact that I use google translator to support me to speak English, in print texts is happening any errors.
I'm not a bot, please inform me how I can help more in solving this problem.

**Comment by derekriemer** [comment] 2016-04-04 18:26
I'm sorry. I did not intend to mistaking you for a bot. Especially not a spambot (please forgive me) now I understand The message look to the way it did with your translations.

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by derekriemer** [comment] 2016-04-04 18:31
Your crash dump seems to not show exactly what is going on (can you give a log I noticed that you are using unspoken or audio screen).
If you are able to reproduce this crashed again and you can set your log level (NBA's General settings) to at least input and output it will be extremely helpful.
Once you do this, after the crash happens go into your temp directory and find the file titled  nvda-old.log %temp%\nvda-old.log 
If you look at the end of it there should probably be a trace back of some sort and if you're able to get that and send it it would be great. I'll try to take another look at the crash dump and see if I can find anything but there was no memory information or trace available.

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by fernando-jose-silva** [comment] 2016-04-04 19:14
Good afternoon friend, no problem, we are trying to overcome the language barrier, I thank you for that effort.
Now when using the machine, NVDA caught twice in Outlook 2016 when you tap enter the menu to move a message to another folder, the check in the temporary files folder found a new error .dmp file and NVDA file -old.log, sending the two 
[nvda-old.log.txt](https://github.com/nvaccess/nvda/files/203140/nvda-old.log.txt)
[nvda_crash.dmp.txt](https://github.com/nvaccess/nvda/files/203142/nvda_crash.dmp.txt)

files attached.

set NVDA log level for input / output, sorry to be in Portuguese, but NVDA caught the latch it to aplication key and press enter on the item move to another folder.

**Comment by derekriemer** [comment] 2016-04-04 20:45
Hi, are you able to explain how you caused this to happen?

One odd thing I see is
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (15:18:00):
oleacc.AccessibleObjectFromEvent with window 55117630, objectID 3127 and 
childID 0: [Error -2147467259] Erro não especificado
seems to ruffly  translate as unspecified error.
I don't know why this object is emitting this over and over again.

Also, the error that lead to the crash seems to be this.
error executing event: typedCharacter on <NVDAObjects.UIA.UIA object at 
0x0A37FF10> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
   File "eventHandler.pyc", line 143, in executeEvent
   File "eventHandler.pyc", line 91, in __init__
   File "eventHandler.pyc", line 98, in next
   File 
"C:\Users\ferna\AppData\Roaming\nvda\addons\ReportSymbols\globalPlugins\reportSymbols.py", 
line 35, in event_typedCharacter
   File "eventHandler.pyc", line 98, in next
   File "NVDAObjects\__init__.pyc", line 830, in event_typedCharacter
   File "speech.pyc", line 593, in speakTypedCharacters
   File "api.pyc", line 235, in isTypingProtected
   File "baseObject.pyc", line 34, in __get__
   File "baseObject.pyc", line 110, in _getPropertyViaCache
   File "NVDAObjects\UIA\__init__.pyc", line 538, in _get_states
   File "comtypes\__init__.pyc", line 266, in __getattr__
COMError: (-2147220991, 'Un evento n???o p??? call subscribers (None, 
None, None, 0, None)) [[[[0, None)) ???DEBUGWARNING - watchdog._watcher 
(15:18:03):
Now, I can't figure out those unicode symbols. They are probably special 
marks for a specific font. That seems to be an error message, probably a 
bad call to a function in windows, or maybe a call that was canceled.
The symbols that were ??? are described here.
http://unicode-table.com/en/blocks/private-use-area/

Trying to recover from freeze, core stack:
   File "nvda.pyw", line 191, in <module>
   File "core.pyc", line 382, in main
   File "wx\_core.pyc", line 8657, in MainLoop
   File "wx\_core.pyc", line 7952, in MainLoop
   File "wx\_misc.pyc", line 1367, in Notify
   File "wx\_core.pyc", line 16869, in Notify
   File "core.pyc", line 475, in _callLaterExec
   File "IAccessibleHandler.pyc", line 816, in _fakeFocus
   File "NVDAObjects\__init__.pyc", line 262, in objectWithFocus
   File "NVDAObjects\__init__.pyc", line 69, in __call__
   File "NVDAObjects\UIA\__init__.pyc", line 405, in __init__
   File "_UIAHandler.pyc", line 294, in getNearestWindowHandle

DEBUGWARNING - unhandled exception (15:18:03):
Traceback (most recent call last):
   File "wx\_misc.pyc", line 1367, in Notify
   File "wx\_core.pyc", line 16869, in Notify
   File "core.pyc", line 475, in _callLaterExec
   File "IAccessibleHandler.pyc", line 816, in _fakeFocus
   File "NVDAObjects\__init__.pyc", line 262, in objectWithFocus
   File "NVDAObjects\__init__.pyc", line 69, in __call__
   File "NVDAObjects\UIA\__init__.pyc", line 405, in __init__
   File "watchdog.pyc", line 198, in _COMError_init
CallCancelled
DEBUGWARNING - watchdog._watcher (15:18:04):
Trying to recover from freeze, core stack:
   File "nvda.pyw", line 191, in <module>
   File "core.pyc", line 382, in main
   File "wx\_core.pyc", line 8657, in MainLoop
   File "wx\_core.pyc", line 7952, in MainLoop
   File "core.pyc", line 352, in Notify
   File "IAccessibleHandler.pyc", line 884, in pumpAll
   File "IAccessibleHandler.pyc", line 617, in processGenericWinEvent
   File "IAccessibleHandler.pyc", line 521, in winEventToNVDAEvent
   File "_UIAHandler.pyc", line 279, in isUIAWindow
   File "_UIAHandler.pyc", line 273, in _isUIAWindowHelper

That's it. So maybe an invalid UIA object? I have been seeing this a lot 
lately.


On 4/4/2016 1:14 PM, fernando-jose-silva wrote:
>
> Good afternoon friend, no problem, we are trying to overcome the 
> language barrier, I thank you for that effort.
> Now when using the machine, NVDA caught twice in Outlook 2016 when you 
> tap enter the menu to move a message to another folder, the check in 
> the temporary files folder found a new error .dmp file and NVDA file 
> -old.log, sending the two
> nvda-old.log.txt 
> <https://github.com/nvaccess/nvda/files/203140/nvda-old.log.txt>
> nvda_crash.dmp.txt 
> <https://github.com/nvaccess/nvda/files/203142/nvda_crash.dmp.txt>
>
> files attached.
>
> set NVDA log level for input / output, sorry to be in Portuguese, but 
> NVDA caught the latch it to aplication key and press enter on the item 
> move to another folder.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5844#issuecomment-205452761>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by derekriemer** [comment] 2016-04-04 21:03
Your translation wrote "caught twice when"
I think it translated wrong. Do you mind explaining farther? I am 
assuming you wrote something similar to "crashed twice when I pressed enter"
Thanks.

On 4/4/2016 1:14 PM, fernando-jose-silva wrote:
>
> Good afternoon friend, no problem, we are trying to overcome the 
> language barrier, I thank you for that effort.
> Now when using the machine, NVDA caught twice in Outlook 2016 when you 
> tap enter the menu to move a message to another folder, the check in 
> the temporary files folder found a new error .dmp file and NVDA file 
> -old.log, sending the two
> nvda-old.log.txt 
> <https://github.com/nvaccess/nvda/files/203140/nvda-old.log.txt>
> nvda_crash.dmp.txt 
> <https://github.com/nvaccess/nvda/files/203142/nvda_crash.dmp.txt>
>
> files attached.
>
> set NVDA log level for input / output, sorry to be in Portuguese, but 
> NVDA caught the latch it to aplication key and press enter on the item 
> move to another folder.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5844#issuecomment-205452761>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment] 2016-04-04 23:04
@derekriemer: It's worth noting that the exceptions in the log usually aren't related to a crash. That is, you can't look at the last error in the log and assume it's what caused the crash. To put it another way, stuff in the log is Python exceptions, whereas a crash is a system exception, either in the Python C code or an external dll. We'll need to take a look at the dump files in WinDBG to figure this out.

**Comment by derekriemer** [comment] 2016-04-04 23:17
Oh. Good to know! What's the best way for looking at it in that way? Do I run that against NVDA some out when I run the debugger?

Sent from my heavily encrypted iPhone.
Please disregard errors as this is a smaller device.

**Comment by fernando-jose-silva** [comment] 2016-04-05 01:58
good evening everyone, thank you for your support.
For clarity the moment NVDA failed:
Pressed down arrow in the Outlook inbox, NVDA will read the message in focus.
I pressed the aplication key (right-click), walked with arrow up to the item of the right mouse button called move, pressed arrow right, NVDA will read the folder name where the selected message would be moved.
I pressed enter on the folder name, and this time was that NVDA stopped responding.

**Comment by feerrenrut** [comment] 2017-09-27 05:16
We think this was likely fixed with the wx assertions change.

@fernando-jose-silva have you seen this error recently? Could you let us know if you are still experiencing this problem?

**Comment by Brian1Gaff** [comment] 2017-09-27 08:22
Just about lack of spaces in some text. I do not know the reasons, but I've 
seen this on some emails lists and indeed other places where text is 
inputted when it becomes live it has no spaces. I put it down to the 
probblems of some software coding space as some odd code then further 
decoding strips these codes out.
 On the case of weird errors in nvda from windows. I've not seen the 
described error here for nearly a year on any software.
 it was quite rare before but may well have affected some users using 
different language choices in that programs concerned.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.

**Comment by fernando-jose-silva** [comment] 2017-09-27 11:36
thank you, I do not have these problems anymore, a lot has happened since the opening of this call, I even changed the Windows machine.

Enviado do meu iPhone

Em 27 de set de 2017, à(s) 05:22, Brian Gaff <notifications@github.com> escreveu:

**Comment by feerrenrut** [comment] 2017-10-02 04:10
Thanks for the feedback, we will close this issue now. If this reoccurs please comment or open a new issue.

**Closed by feerrenrut** 2017-10-02 04:10 UTC
Labels: blocked, crash, p1
