### ISSUE TITLE
nvda and firefox

### ISSUE THREAD

**Issue by mohammad-aloufi** [nvaccess/nvda#7223] opened 2017-05-30 12:14 UTC
The problem is with fire fox.
If I am in a web page, and restart nvda while the focus on the fire fox window,
nvda gets stuck in focus mode, the only way I can solve it is to restart nvda.
I didn't have this problem before upgrading to the creators update by the way.
nvda version: 2017.2
fire fox version: 53.0.3 (32-bit)
windows version: Windows 10 creators update, version 1703 (OS Build 15063.296)

**Comment by PratikP1** [comment] 2017-05-30 14:35
This has been a problem for a while. But it’s not related to NVDA. It’s a Firefox bug.

**Comment by jcsteh** [comment] 2017-05-30 23:48
It's not a bug in Firefox. It's caused by the fact that focus doesn't actually change when you restart NVDA, so Windows doesn't fire focus and thus NVDA's code can't be injected into Firefox.

This is a duplicate of #5758.

**Closed by jcsteh** 2017-05-30 23:48 UTC
