### ISSUE TITLE
make possible to also write into a file, what NVDA sends to synth and braille

### ISSUE THREAD

**Issue by gregjozk** [nvaccess/nvda#10326] opened 2019-10-04 14:14 UTC
### Is your feature request related to a problem? Please describe.
during test of one syinth, I spotted an unusual behaveour of synth; results which have been heard, were confused.
I tried to see, what NVDA sent to synth, within log viewer, but there is too much noise for my usage.
### Describe the solution you'd like
is it possible that optionally NVDA could write into special file, what it talks along as it does when it is set to debug level but without its log messages like errors, warnings etc. just strings, which have been sent to synth, braille or speech viewer
### Describe alternatives you've considered
ideal solution would be option like in Balabolka, where it converts a written text into audio file; but here NVDA would "analyse a text and rewrite it into special file with its messages like link, report font atributes, if enabled etc,so I won't wait to results too much time, when say all command was pressed.
### Additional context
If text is written, it is much more easyer to compare original and what is sent to synth or braille and to spot potential problems.
if it is not possible and is abroad a skope of NVDA,I would close it and search another solution for my problem.
anyway, thanks.

**Comment by Brian1Gaff** [comment] 2019-10-04 15:35
As by definition this issue is synth dependent, then I do not see how you 
could do this. All you can do is see what that synth actually was given. If 
you want to record the output of nvdas synth, I tend to use the stand alone 
software virtual recorder, I set it up to start recording then perform the 
tasks including the dodgy output, then alt tab to virtual recorder and stop 
it. I can then listen to it over and over. You can if you like shove the 
file into an audio editor to shorten it.
 Sadly I'm not aware of a standard method of seeing what goes on inside any 
given synth. If its Espeak, you may wish to visit their list and ask.

You may get more ideas if you post to the dev list here or one of the 
general query lists.


Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by Adriani90** [comment] 2019-10-07 19:49
For the speech you can use the speech viewer. For the braille a basic braille viewer will be implemented soon.

**Comment by Adriani90** [comment] 2019-10-07 19:50
@feerrenrut if you have something else to add, otherwise I think this issue can be closed.

**Comment by leonardder** [comment] 2019-10-08 11:59
@Adriani90  The question here is to have speech and/or braille output written to a special file. I don't think that's covered by the speech viewer or braille viewer. It is somehow covered by the log though, but according to @gregjozk it has too much noise in it.

**Comment by feerrenrut** [comment] 2019-10-08 16:57
I don't think this use case (investigating unexpected behavior from a synth) is common enough to warrant a feature like this. Instead I would suggest filtering your log file to remove things you do not care about. Consider awk, sed, and grep if you are familiar, or perhaps a simple python script. It's hard to know what to suggest without knowing more details about what you are trying to do. In the first part of this issue you talk only about a synth, but in the additional context part you talk about comparing to braille.

**Comment by leonardder** [comment] 2019-10-17 13:24
@gregjozk: DO you think this issue can be closed based on the comments above?

**Comment by Adriani90** [comment] 2020-02-06 23:37
I am closing this issue since it is already possible to copy out the information from the log file if you really want. And anyway, if something else like a new file is implemented, then the question is how to structure it? There would be a chaos for a user to see just the spoken feedback or the braille feedback just thrown into a file without structure.
What I would like to see in NVDA is a speech history, for example last 10 word,last 10 sentences, this could be configurable. However, for that there is already another issue.

**Closed by Adriani90** 2020-02-06 23:37 UTC
