### ISSUE TITLE
NVDA hangs when reading a long string of text.

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#8455] opened 2018-06-27 14:12 UTC
I've been doing a lot of work with Solidity which requires me to take the bytecode generated by the compiler and paste it somewhere, like an Ethereum wallet. During this process, I've found it difficult to use NVDA as described here.

### Steps to reproduce:
* generate a long string of text, such as Solidity bytecode.
* Try to get NVDA to read the text. NVDA will freeze.
* I have to somehow avoid NVDA reading the bytecode. One solution I've found is to turn on word wrap in my text editor. These word wraps are soft, so when I copy the text from the editor the bytecode appears on one line as intended.

### Actual behavior:
NVDA freezes when I arrow over Solidity bytecode because the hex string is so long that the synthesizer can't process it.

### Expected behavior:
NVDA should smoothly read a string of text, no matter how long it is.

### System configuration:
64-bit, Core i7-3520M 2.9 GHz, 128 GB SSD

#### NVDA Installed/portable/running from source:
Installed

#### NVDA version:
2018.2.1
#### Windows version:
Windows 10
#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
Yes, they all exhibit the same behavior.

**Comment by Adriani90** [comment] 2019-05-08 16:25
@munawarb if you are still having this issue in NVDA 2019.1.1, could you please provide an example of such a long string in a file uploaded to this issue? In which editor are you having this issue?

**Comment by munawarb** [comment] 2019-05-08 17:10
Hi @Adriani90, Sure, I've attached a file to this message containing Solidity bytecode. The first line is simply the word "bytecode:". the next line is a string of hex digits that's the actual bytecode. On that line NVDA will hang. I've tried with 2019.1.1 with the same results as previously reported.

I have word wrap turned off so NVDA is trying to process the whole string at once. This is in Notepad++.
[test bytecode.txt](https://github.com/nvaccess/nvda/files/3158543/test.bytecode.txt)

**Comment by Adriani90** [comment] 2019-05-08 17:17
cc: @DataTriny maybe you have any idea why this could happen? I know that such issues also exist in other editors like text editors.

**Comment by DataTriny** [comment] 2019-05-09 10:44
Hi everyone,
@munawarb which synthesizer are you using? Also, does NVDA crash or does it just do nothing for such a long time that you stop the process? If it crash, when does this happen exactly? Does it start reading some text or just exit when cursor jumps on the line?

Testing with all synthesizers installed on my machine, here are the results:
- Espeak NG: no problem,
- ETI-Eloquence: no problem,
- Microsoft Speech API version 5: no problem,
- Windows OneCore Voices: can't read the line after waiting for more than 20 seconds.

@Adriani90 do you know who is in charge of Windows OneCore maintenance? If yes, could you mention him/her here please?

**Comment by munawarb** [comment] 2019-05-09 12:33
Hi @DataTriny,
I went back and tried using ESpeak and still the screen reader hung when I arrowed down to the line containing the bytecode. I have word wrap turned off, so the whole string of code appears on one line (this is line 2 in my text editor.)

NVDA hangs for such a long time that I restart the process by pressing CTRL+ALT+N. Before I restart NVDA, the fans on my laptop become active and spin at their highest speed as if the system is under heavy load.

Pressing ALT+TAB or anything else generates no response from NVDA. However, I can tell that the system itself hasn't frozen because if I proceed to press UP ARROW to take the cursor off of the bytecode line (so that NVDA won't freeze again when I restart it and re-focus the text editor,) I find that I am on the line reading "bytecode:". So the UP ARROW command has registered.

I use Eloquence as my primary but like I said I also switched to ESpeak after your comment and saw the same results with ESpeak: a frozen NVDA until NVDA restart.

**Comment by DataTriny** [comment] 2019-05-09 13:19
I caught a MemoryError on NVDA's log with Windows OneCore Voices synthesizer. Do you know @munawarb how much RAM is installed on your machine? I have 8 Go on mine. I suspect that you have less than that. I mean: when I try to read the second line the memory usage rises quite high.

**Comment by munawarb** [comment] 2019-05-09 13:30
Hi @DataTriny,
Here is the system info for my computer. It's a pretty powerful system.
```
         Operating System: Windows 10 Home 64-bit (10.0, Build 17763) (17763.rs5_release.180914-1434)
                 Language: English (Regional Setting: English)
      System Manufacturer: Dell Inc.
             System Model: Latitude E6430s
                     BIOS: BIOS Date: 05/08/17 11:43:27 Ver: A19.00  (type: BIOS)
                Processor: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz (4 CPUs), ~2.9GHz
                   Memory: 8192MB RAM
      Available OS Memory: 8096MB RAM
                Page File: 2446MB used, 6928MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Not Available
Microsoft Graphics Hybrid: Not Supported
           DxDiag Version: 10.00.17763.0001 64bit Unicode
```

**Comment by leonardder** [comment] 2019-09-19 06:09
Closing as duplicate of #4669

**Closed by leonardder** 2019-09-19 06:09 UTC
