### ISSUE TITLE
NVDA renders invisible objects as frames

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4922] opened 2015-02-14 21:57 UTC
**Reported by tspivey on 2015-02-14 21:57**
Testing with Firefox, NVDA renders invisible objects as frames. For example, the one in the attached test file.

This is really noticeable on amazon, for example on this book page, where about 200k of js/css is put in the buffer at the bottom:
http://www.amazon.com/The-Martian-Novel-Andy-Weir-ebook/dp/B00EMXBDMA/

(I assume they're invisible because they have width="0" and height="0".)

**Comment by bhavyashah** [comment] 2017-09-06 08:29
@jcsteh wrote in https://github.com/nvaccess/nvda/issues/4922#issuecomment-155334628 "This will need further investigation."
@feerrenrut Do you think we should assign a priority to investigate the reported issue further?

**Comment by feerrenrut** [comment] 2017-09-12 06:01
@bhavyashah Since this is an old issue, can you test this with Firefox and see if it is still reproducible? Please document the steps you took to try to reproduce it on this issue. Thanks!

**Comment by bhavyashah** [comment] 2018-08-15 17:05
@feerrenrut As delayed as I am, I would give testing this issue a shot, but it is unclear to me what control is actually an invisible object but is being reported as a frame by NVDA on https://www.amazon.com/The-Martian-Novel-Andy-Weir-ebook/dp/B00EMXBDMA/. Since @jcsteh is now at Mozilla and was able to replicate this back then as documented in https://github.com/nvaccess/nvda/issues/4922#issuecomment-155334628 and @tspivy, the original author of this ticket,  is still around, I would ask them to kindly share an update on the present standing of this bug.

**Comment by jcsteh** [comment] 2018-08-16 00:07
I checked this Amazon page and I don't see any code at the bottom of the page. In fact, there are no object tags at all on that page. So, it would seem have Amazon have changed this.

I also tested the test case with an iframe instead of an object tag and it doesn't make a difference. While it's certainly odd, the text really is rendered behind the scenes; it's just considered "off screen". Given that the original real world use case is now fixed, unless we start seeing other instances of this, I think we should just consider this authoring error and leave it at that.

Closing as won't fix.

**Closed by jcsteh** 2018-08-16 00:07 UTC
Labels: Browse mode, bug
