### ISSUE TITLE
document review mode stops to work when switching between whatsapp and a web browser

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#8469] opened 2018-06-30 12:35 UTC
### Steps to reproduce:
you must have the whatsapp app installed and configured. I installed it from the windows10's store.
1. open whatsapp.
2. open a web browser (I tested with schrome and firefox).
3. open a page and read some content of it.
4. press alt+tab to switch to whatsapp.
you will notice that nvda doesn't read the content.
If you close whatsapp and open it again, nvda will read the content.
But if you change to the web browser, the document review mode will stop to work again.

### Actual behavior:
the document review mode stop to work in whatsapp after the user switch from a web browser
### Expected behavior:
the document review mode should work in both applications
### System configuration:
windows10 64 bits
#### NVDA Installed/portable/running from source:
installed
#### NVDA version:
2018.2.1

**Comment by Adriani90** [comment] 2019-05-08 18:31
@alexandretoco do you still have this issue with NVDA 2019.1.1 on Windows 10 1809 Update?

**Comment by alexandretoco** [comment] 2019-05-11 22:26
Hello!
Yes. 
A good way to reproduce it is:
1. Open whatsappweb.
2. Open kindle for pc and read some lines of a book that supports screen reader.
3. Switch back to WhatsApp with alt+tab. NVDA will no longer read the WhatsApp screen.
4. The only way to resolve this is to close and reopen whatsaap. But if you repeat the above procedure, NVDA will stop to read the WhatsApp screen again.



Enviado do Email para Windows 10

De: Adriani90
Enviado:quarta-feira, 8 de maio de 2019 15:31
Para: nvaccess/nvda
Cc:alexandretoco; Mention
Assunto: Re: [nvaccess/nvda] document review mode stops to work when switchingbetween whatsapp and a web browser (#8469)

@alexandretoco do you still have this issue with NVDA 2019.1.1 on Windows 10 1809 Update?

**Comment by Adriani90** [comment] 2020-05-09 10:19
@alexandretoco I cannot reproduce this with NVDA 2020.1. Could you please run the COM registration fixing tool in NVDA menu / tools and try to reproduce again?

**Comment by alexandretoco** [comment] 2020-05-12 17:03
Hi Adriani!I did what you suggest and the problem persists.For example, I was reviewing some messages in WhatsApp.So I opened the site https://www.rappi.com.br/aliados/vila-das-frutas in google schrome and Interact with it.So I pressed alt + tab to switch back to WhatsApp and nvda doesn’t read any thing.I restarted nvda and the problem persists.So I closed and reopen WhatsApp and the things begin to work again.  Enviado do Email para Windows 10 De: Adriani90Enviado:sábado, 9 de maio de 2020 07:19Para: nvaccess/nvdaCc:alexandretoco; MentionAssunto: Re: [nvaccess/nvda] document review mode stops to work when switching between whatsapp and a web browser (#8469) @alexandretoco I cannot reproduce this with NVDA 2020.1. Could you please run the COM registration fixing tool in NVDA menu / tools and try to reproduce again?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lukaszgo1** [comment] 2020-05-12 17:26
@alexandretoco Could you please try to move Whac APP window with Windows+left arrow and then Windows + right arrow next time when it happens?

**Comment by alexandretoco** [comment] 2020-05-12 17:45
Great! I never heard about these commands. But they solve the problem.One interesting thing: I did what you suggest and then I switched between WhatsApp and schrome many times with alt + tab andnvda could recognize and Interact with WhatsApp normally.Are these nvda’s commands?   Enviado do Email para Windows 10 De: Łukasz GolonkaEnviado:terça-feira, 12 de maio de 2020 14:26Para: nvaccess/nvdaCc:alexandretoco; MentionAssunto: Re: [nvaccess/nvda] document review mode stops to work when switching between whatsapp and a web browser (#8469) @alexandretoco Could you please try to move Whac APP window with Windows+left arrow and then Windows + right arrow next time when it happens?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lukaszgo1** [comment] 2020-05-12 17:53
No, they are Windows native commands to minimize and maximize the window. I don't use WhatsApp, but similar problem exists in MS Teams and it is also Electron based so it was worth a try. Have you reported this to WhatsApp developers? This is not an NVDA issue just a bug in Electron so there is nothing which could be done on NVDA side I'm afraid.

**Comment by Adriani90** [comment] 2023-03-04 11:57
Closing this issue since this is not related to NVDA but rather a bug in electron.

**Closed by Adriani90** 2023-03-04 11:57 UTC
