### ISSUE TITLE
NVDA goes silent, "core frozen in stack" appears in log

### ISSUE THREAD

**Issue by mehgcap** [nvaccess/nvda#7048] opened 2017-04-03 19:08 UTC
I've noticed recently that NVDA will sometimes stop responding for a minute. It sometimes recovers, but I often have to do a hard shutdown of the computer and then boot it back up to get speech back. I've found this to happen apparently randomly, unrelated to a specific application or action. I could be wrong about that, though.

Here's what I see in the log. This is after the most recent problem, from which NVDA recovered on its own:

```
WARNING - watchdog._watcher (14:57:42):
Core frozen in stack:
  File "nvda.pyw", line 194, in <module>
  File "core.pyo", line 391, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 361, in Notify
  File "IAccessibleHandler.pyo", line 888, in pumpAll
  File "IAccessibleHandler.pyo", line 755, in processForegroundWinEvent
  File "IAccessibleHandler.pyo", line 522, in winEventToNVDAEvent
  File "_UIAHandler.pyo", line 299, in isUIAWindow
  File "_UIAHandler.pyo", line 293, in _isUIAWindowHelper

```

The end of that traceback is not a mistake; I see no actual exception text, just a blank line after the last line of file information.

I'm on Windows 10 (64-bit, build 14393), NVDA 2017.1.

**Comment by jcsteh** [comment] 2017-04-03 22:24
Closing as a duplicate of #6062. That one is specifically related to Skype, but the point where the freeze occurs is the same.

**Closed by jcsteh** 2017-04-03 22:24 UTC
