### ISSUE TITLE
An error occurs while reading some articles from the verge

### ISSUE THREAD

**Issue by burakyuksek** [nvaccess/nvda#13266] opened 2022-01-21 15:21 UTC
### Steps to reproduce:
1. Go to https://www.theverge.com/22892044/wordle-free-game-online-how-to-puzzle
2. Press h until you get to share this article heading.
3. Press down arrow to continue to the list where the platforms are found.
4. When you get past that list, NVDA is going to stop speaking. If it does not, press shift h then try down arrowing past the list again. You will eventually encounter the issue.
### Actual behavior:
NVDA stops speaking, I have to alt tab back and forth to get it to continue speaking, and it also loses position in the webpage. I need to get past the share this article heading and go up from there until I find the beginning of the article.
### Expected behavior:
NVDA should continue as normal.
#### NVDA installed/portable/running from source:
İnstalled
#### NVDA version:
2021.3.1
#### Windows version:
windows10 21h2
#### Name and version of other software in use when reproducing the issue:
Chrome 97.0.4692.71
#### Does the issue still occur after restarting your computer?
Not known
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Didn't try with addons disabled
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes
[nvda.log](https://github.com/nvaccess/nvda/files/7914742/nvda.log)

**Comment by enessaribas** [comment] 2022-01-23 01:33
I have encountered this happening just by loading a page, requiring an NVDA restart and termination of Firefox through  taskmgr.

**Comment by burakyuksek** [comment] 2022-02-02 14:08
This issue is becoming more wide spred with time.
For example, https://www.theverge.com/2022/2/2/22912367/logmein-rebranding-as-goto-like-gotomeeting
Has the same kind of issue.

**Comment by ehollig** [comment] 2022-09-22 15:44
I am not able to reproduce this issue using NVDA 2022.3. Is this still an issue?

**Comment by burakyuksek** [comment] 2022-09-22 16:29
Hello,
I am no longer encountering this problem. If @enessaribas isnt either, then I can close this issue.

**Comment by seanbudd** [comment] 2022-09-26 00:30
Closing this as fixed

**Closed by seanbudd** 2022-09-26 00:30 UTC
