### ISSUE TITLE
Refreshing in log viewer results in assertions

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6637] opened 2016-12-13 07:30 UTC
When the log menu is accessed and refresh is chosen a debug warning showing an assertion failure and stack is present in the log. The assertion seems to be missing the message.

> DEBUGWARNING - WX Widgets (11:55:25):
> ..\..\src\msw\toplevel.cpp, line 1544:
> assert ..\..\src\msw\toplevel.cpp: ..\..\src\msw\toplevel.cpp
> Stack trace:
>   File "nvda.pyw", line 191, in <module>
>   File "core.pyc", line 390, in main
>   File "wx\_core.pyc", line 8657, in MainLoop
>   File "wx\_core.pyc", line 7952, in MainLoop
>   File "core.pyc", line 220, in OnAssert

[logviewer-assert-nvda.log.txt](https://github.com/nvaccess/nvda/files/648214/logviewer-assert-nvda.log.txt)

**Comment by michaelDCurran** [comment] 2016-12-13 08:07
Oh dear.


This looks like we're no longer using our custom build of wxPython. The 
standard build had a bug where filename was used instead of the message. 
I patched that in our custom build.

Perhaps miscDeps has gotten confused... I shall look into this.

In my copy of 2016.4rc1 producing another assert I know did have a 
message, that is also missing now.

**Comment by michaelDCurran** [comment] 2016-12-13 08:49
Oh dear. It looks like although the custom wxPython got into 2016.3, it 
was then dropped out of master in commit 
03e1de94a0dfd6b40530c496c84208e103369215 (September 19), pr #6268.


In pr 6268, miscDeps was updated to commit 
c1f4f7df89be9e1499e5175baae55b14f483ed94.


However, its parent was 792a25485cc0029b4160779a161d8802f75d888a (April 
29), but it should have been 66534082b60d4266d9352f7462953213eb05156a 
(July 17).

**Comment by jcsteh** [comment] 2016-12-13 11:37
Uh oh. That will possibly qualify for an rc3. We shouldn't need to bake it too long, though, since it's already in 2016.3 and has thus already had wide exposure.

**Comment by jcsteh** [comment] 2017-01-25 06:21
This is a problem in wx. These wx commits explain (and fix) the issue: wxWidgets/wxWidgets@9280f83 wxWidgets/wxWidgets@1966dfb wxWidgets/wxWidgets@c87c432. See also pcsx2/pcsx2#853, which is where I found this info.

Those commits appear to be part of wxWidgets 3.1. I think we should consider upgrading for this and other reasons. As per [the release notes](http://www.wxwidgets.org/news/2016/02/wxwidgets-3.1.0-released/):

> Please notice that while 3.1.0 is officially a "development" version because it is not fully compatible with 3.0.x, the list of backwards incompatible changes is very short, so you shouldn't have any problems updating to this version from 3.0.x in practice, and you're encouraged to try this version out and use it in production in spite of its odd version number.

**Comment by feerrenrut** [comment] 2017-11-07 06:35
I believe this be reproduced in any part of our GUI by pressing alt then escape

The following reproduces it in the synthesizer menu:
1. Open synth settings: NVDA+n, p, s
1. Press alt.

See Log:  [nvda.log](https://github.com/nvaccess/nvda/files/1448911/nvda.log)

And in the log viewer
1. Open log viewer NVDA+F1
1. press alt
1. press escape

See Log:  [nvda.log](https://github.com/nvaccess/nvda/files/1448920/nvda.log)

**Comment by feerrenrut** [comment] 2017-11-07 06:36
The previous comment by Jamie indicates that this could be fixed by upgrading wxWidgets. After the move to wxPython 4 we should see if this issue is resolved. @josephsl Could you comment on whether this issue is fixed with wxPython 4?

**Comment by josephsl** [comment] 2017-11-07 06:40
Hi, I cannot reproduce this on latest next snapshot at the moment (powered by wxPython 3.0.2), nether in Synthesizer dialog or log viewer. Thanks.

**Comment by feerrenrut** [comment] 2017-11-07 07:02
Could you give some more details about what you tried? I am using install NVDA version `next-14588,6a175cf6` which has wxPython 3.02. This is on Windows 10 version 1703 build `15063.674`

There is no error sound, the log must be inspected to locate the assertion.

**Comment by josephsl** [comment] 2017-11-07 07:10
Hi, I followed the steps outlined in the above comment (pressed Control+NVDA+S to open Synthesizer dialog, pressed Alt, then escape, then opened log viewer to inspect if something was recorded). Thanks.

**Comment by feerrenrut** [comment] 2017-11-07 07:24
Could you confirm that you are using an installed version of NVDA and its version number, and the version of windows that you are using. This helps us to see what the differences are between our two systems. The steps you listed differ from the ones that I posted, however I can reproduce the issue that way as well.

**Comment by josephsl** [comment] 2017-11-07 07:26
Hi, this is NVDA next.14588 installed on Windows 10 build 17025. Thanks.

**Comment by feerrenrut** [comment] 2017-12-04 05:27
I'm convinced that this is fixed with wxPython 4. By doing the following first with NVDA 2017.3 to replicate, then with `nvda_snapshot_wxPy4-20171030.exe`
- run from the launcher
- ensure log output is set to `DEBUG`
- open synthesizer dialog.
- press alt
- press escape
- Open NVDA log and search for DEBUGWARNING expecting to find
> DEBUGWARNING - WX Widgets (13:26:26.918):
..\..\src\msw\toplevel.cpp, line 1544:
assert m_menuDepth > 0: No open menus?
Stack trace:
  File "nvda.pyw", line 199, in <module>
  File "core.pyo", line 396, in main
  File "wx\_core.pyo", line 8657, in MainLoop
  File "wx\_core.pyo", line 7952, in MainLoop
  File "core.pyo", line 226, in OnAssert

In  `nvda_snapshot_wxPy4-20171030.exe` this is not found.

**Comment by jcsteh** [comment] 2017-12-04 05:48
The question is what commit of wxWidgets is being used by wxPython 4. I believe wxPython 4 is based on wxWidgets 3.0.x, and this fix was originally made in 3.1 (see https://github.com/nvaccess/nvda/issues/6637#issuecomment-275029011). However, they may have been back-ported to wxPython 3.0, and wxPython 4 does appear to be using something later than 3.0.2.0 (currently [wxWidgets @ 8ac6290](https://github.com/wxWidgets/wxWidgets/tree/8ac6290cd437ce38d923d47cb943a4b78cbd6a43); see the submodule in phoenix's [ext directory](https://github.com/wxWidgets/Phoenix/tree/master/ext)). So, if you want to know for certain, just check whether those commits have been cherry-picked.

**Comment by feerrenrut** [comment] 2017-12-04 06:44
Yes, so not only does manual testing show this is fixed. But also the key change ( I think ) from [Under certain conditions, selecting a menu item triggers an assert](https://github.com/wxWidgets/wxWidgets/commit/9280f836c2569d0f50301a1117f7ba144e5240d2) is included in currently [wxWidgets @ 8ac6290](https://github.com/wxWidgets/wxWidgets/tree/8ac6290cd437ce38d923d47cb943a4b78cbd6a43) see:
https://github.com/wxWidgets/wxWidgets/blame/8ac6290cd437ce38d923d47cb943a4b78cbd6a43/src/msw/utils.cpp#L1498

**Comment by Adriani90** [comment] 2019-01-12 13:40
So is this issue now completely solved with WX Python 4?

**Comment by josephsl** [comment] 2019-01-12 17:15
Hi, as far as I can tell, this issue does not exist in 2018.3 9wxPython 4) and later at the moment. Thanks.

**Comment by Adriani90** [comment] 2019-01-15 13:43
Closing as works for me. We can reopen this one if the issue comes up again. Thanks.

**Closed by Adriani90** 2019-01-15 13:43 UTC
Labels: p2, worksforme
