### ISSUE TITLE
Filtering entries in the speech dictionary windows

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#8548] opened 2018-07-24 02:57 UTC
### Paths:
NVDA menu » Preferences » Speech dictionaries » …
+ … » Default dictionary
+ … » Voice dictionary
+ … » Temporary dictionary
### Actual behaviour:
It isn't possible to filter/search for an entry.
### Expected behaviour:
Add a text field to filter entries by their name, replacement and comment.
#### NVDA installed/portable:
Both should be supported the same.
#### NVDA version:
Issue/Feature Request based on 2015.3 and 2018.1

**Comment by leonardder** [comment] 2019-10-26 07:32
Duplicate of #2478

**Closed by leonardder** 2019-10-26 07:32 UTC
