### ISSUE TITLE
HIMS Braille displays don't work on next

### ISSUE THREAD

**Issue by vlegoff** [nvaccess/nvda#6436] opened 2016-10-08 18:07 UTC
I have upgraded to the latest next version of NVDA yesterday (10/7/2016) and everything seemed to work well.  Next time the computer started, though, NVDA wasn't able to connect to my Braille display (I use a HIMS BrailleSense QWERTY U2).  This could have no link to NVDA, so I restored my system a week back, installed NVDA again, checked the BrailleSense hardware and so on.  When I install NVDA's stable (2016.3), it works perfectly well, the BrailleSense is identified and NVDA communicates with it just as usual.  I can't tell you what the problem is, but it seemed I had a lot of errors in the latest next anyway.  Since I couldn't do much, I couldn't check the logs, particularly without Braille display, so hopefully someone else would have more information on that issue.

**Comment by josephsl** [comment] 2016-10-08 18:18
CC @leonardder

**Comment by jcsteh** [comment] 2016-10-11 06:47
NVDA next includes the updated HIMS dll (#6334) as requested to fix an issue covered in #6063. However, if this is indeed causing regressions, we should back it out.

@leonardder? Anyone else? Can you confirm whether NVDA next works with HIMS displays, particularly the BrailleSense QWERTY U2 since it's the one reported as broken here? If we can't get confirmation on this, I think we should back this out in the next few days.

CC @feerrenrut.

**Comment by jcsteh** [comment] 2016-10-11 06:48
P1 because this might stop an existing braille user from being able to use NVDA and is probably a regression.

**Comment by leonardder** [comment] 2016-10-11 08:15
I tested a braille edge yesterday which worked perfectly. I will be able to test a braille sense next thursday.

**Comment by leonardder** [comment] 2016-10-12 12:09
@vlegoff: Would you be able to give more details about what works and what not? For example, do you get a "Could not load the Hims display" error, or does the driver load correctly? Do you use bluetooth or USB?
Are you sure you're using the latest firmware on BS U2?

**Comment by leonardder** [comment] 2016-10-13 08:33
I tried a BS U2 Perkins, no problems. Also, no problems with the Braille Edge either.

**Comment by vlegoff** [comment] 2016-10-13 16:00
I now use NVDA 2016.3, but I can try again on next, perhaps a Portable version.  And I'll make sure to log this time (it's not easy to do without Braille, as far as I'm concerned).

**Comment by leonardder** [comment] 2016-10-14 13:43
Reproduced this:

Error initializing display driver
Traceback (most recent call last):
  File "braille.pyc", line 1259, in setDisplayByName
  File "brailleDisplayDrivers\hims\__init__.pyc", line 137, in __init__
KeyError: 5

It seems that the new dll reports display identifiers we do not know of. The Hims representative I contacted on behalf of @BabbageCom didn't have a detailed changelog available, unfortunately.

These display identifiers are slightly vague anyway.

**Comment by jcsteh** [comment] 2016-10-18 02:03
Since this regresses some users and we don't have a solution yet, we're backing out #6334, which will fix this regression.

**Comment by feerrenrut** [comment] 2016-10-18 07:56
#6334 has now been reverted.

**Comment by leonardder** [comment] 2017-07-31 19:19
This is already backed out. I'm planning to put all future Hims efforts into #7459, so I guess this can be closed if we agree that this is the right way to go.

**Comment by jcsteh** [comment] 2017-07-31 23:19
Closing, since the regression is fixed. Note that #6063 remains open, since we don't have a fix for that yet which doesn't break other things.

**Closed by jcsteh** 2017-07-31 23:19 UTC
Labels: blocked, p1, regression
