### ISSUE TITLE
nvda not reade deleted characters in google chrome search field canary

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8805] opened 2018-09-29 19:56 UTC
### Steps to reproduce:
using chrome canary 71 64bit open google page
www.google.com
enter a text in the search field for example, test.
Now press back space to delete the characters.
### Actual behavior:
in most of the letters deleted nvda makes the error sound and does not inform the deleted character
### Expected behavior:
nvda should speak the deleted character and the error sound should not be heard.
#### NVDA Installed/portable/running from source:
instaled
#### NVDA version:
alfa 16123
#### Windows version:
10 17134.320
#### Name and version of other software in use when reproducing the issue:
chrome canary 71
### Other questions:
this does not occur with the final chrome version and not test 69.
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no
log:
Input: kb(laptop):backspace
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (16:45:24.780):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (16:45:24.785):
error executing script: <bound method Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible.script_caret_backspaceCharacter of <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x053FD470>> with gesture u'b\xe9c speice'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "editableText.pyc", line 231, in script_caret_backspaceCharacter
  File "editableText.pyc", line 221, in _backspaceScriptHelper
  File "editableText.pyc", line 87, in _hasCaretMoved
  File "documentBase.pyc", line 24, in makeTextInfo
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 93, in __init__
  File "NVDAObjects\IAccessible\ia2TextMozilla.pyc", line 201, in _findContentDescendant
COMError: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (16:45:24.819):
accRole failed: (-2147467259, 'Erro n\xe3o especificado', (None, None, None, 0, None))
IO - speech.speak (16:45:24.891):
Speaking [u'Pesquisar  caixa de combina\xe7\xe3o  possui autocompletar  edit\xe1vel  Pesquisar']
IO - speech.speak (16:45:24.914):
Speaking [u'te']
IO - inputCore.InputManager.executeGesture (16:45:32.068):
Input: kb(laptop):NVDA+f1
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (16:45:32.526):
Developer info for navigator object:
name: u'Pesquisar'
role: ROLE_COMBOBOX
states: STATE_FOCUSABLE, STATE_FOCUSED, STATE_EDITABLE, STATE_AUTOCOMPLETE
isFocusable: True
hasFocus: True
Python object: <baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible object at 0x055027F0>
Python class mro: (<class 'baseObject.Dynamic_EditableTextWithAutoSelectDetectionEditorIa2WebIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.DocumentWithTableNavigation'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u'Pesquisar'
location: None
value: u'te'
appModule: <'appModuleHandler' (appName u'chrome', process ID 4572) at address 53effd0>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'71.0.3565.0'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 656756L
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: -1228154752
windowStyle: 1445986304
windowThreadID: 11248
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible2) ptr=0xa2c1a94 at 54fe490>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=656756, objectID=-4, childID=-738
IAccessible accName: u'Pesquisar'
IAccessible accRole: ROLE_SYSTEM_COMBOBOX
IAccessible accState: STATE_SYSTEM_HASPOPUP, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1074790404)
IAccessible accDescription: u'Pesquisar'
IAccessible accValue: u'te'
IAccessible2 windowHandle: 656756
IAccessible2 uniqueID: -738
IAccessible2 role: ROLE_SYSTEM_COMBOBOX
IAccessible2 states: IA2_STATE_SELECTABLE_TEXT, IA2_STATE_SUPPORTS_AUTOCOMPLETION, IA2_STATE_OPAQUE, IA2_STATE_EDITABLE, IA2_STATE_SINGLE_LINE (46088)
IAccessible2 attributes: u'display:block;tag:input;xml-roles:combobox;autocomplete:list;explicit-name:true;haspopup:menu;class:gsfi lst-d-f;id:lst-ib;text-model:a1;text-input-type:text;'

**Comment by Adriani90** [comment] 2019-12-20 21:04
I cannot reproduce this issue in NVDA 2019.3 Beta 1 and Crhome 79. Closing as works for me.
If you still have this issue please comment on it and we can reopen it. Thanks.

**Closed by Adriani90** 2019-12-20 21:04 UTC
Labels: worksforme
