### ISSUE TITLE
NVDA incorrectely associated symbols with wrong replace text

### ISSUE THREAD

**Issue by sine-w** [nvaccess/nvda#11963] opened 2020-12-22 13:58 UTC
### Steps to reproduce:
1. Create portable copy of NVDA 2020.4 beta 1 and set Windows One Core Voice to Microsoft Tracy (Hong Kong Cantonese)
2. typing specific symbols or reading specific symbols will incorrectly spoken with wrong replace text
For example:
english comma are now spoken as 逗號 not comma
 symboles like ; @!.&^%*[]\ etc are all spoken as ↑↑↑

3. I try pressing the reset configurations to default setting, and the issue described above disappeared
4. Then I try changing the Windows OneCore voice from Microsoft HanHan (Taiwan Mandarin)to Microsoft Tracy (Hong Kong Cantonese), the problem come back again 
 
### Actual behavior:
When I take a look at the Punctuation/symbol pronunciation window,
I noticed the following issues

searching with , I found that the text replacement for , is now written as 逗號 (chinese name for comma) not comma

searching for symbols like @, I found that the replacement for @ is ↑↑↑ 

searching for symbols like ; there will have two results matching this search, where one symbol has a replacement of semi, where the other has a text replacement of ↑↑↑

### Expected behavior:
symboles should be spoken with correct replace text, say , should say comma; ; should say semi; @ should say at etc.
 
#### NVDA installed/portable/running from source:
portable

#### NVDA version:
2020.4 beta 1
#### Windows version:
win 10 20h1

#### Other information about your system:
My nvda language is set to Hong Kong Traditional Chinese
I have try switching nvda language to Taiwan Traditional Chinese, the problem still exist
My Windows language is Hong Kong Traditional Chinese

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
The above issue I have not experience in any other nvda versions that I have used before. i.e. 2020.2, 2020.3 etc.

#### If addons are disabled, is your problem still occuring?
This issue identified when the portable copy is newly created, thus without addons

**Comment by CyrilleB79** [comment] 2020-12-22 16:36
Hello
Seems you have deleted some paragraphs of the template.
Especially, you have not indicated if you have tested with previous versions of NVDA, and what the result was.

**Comment by sine-w** [comment] 2020-12-22 23:10
Hi,
Well, I don't know why you think I have deleted something from the template.
This is a fresh portable copy created via the beta installer.

Second, yes I have not tested this issue in other versions, this is because I have not experience this problem in any other versions that I have used before, include but not limited to 20.3, 20.2 etc.

**Comment by CyrilleB79** [comment] 2020-12-23 07:48
> Well, I don't know why you think I have deleted something from the template.

The bug report template has the following paragraphs at the end
* Name and version of other software in use when reproducing the issue:
* Does the issue still occur after restarting your computer?
* Have you tried any other versions of NVDA? If so, please report their behaviors.
* If addons are disabled, is your problem still occuring?
* Did you try to run the COM registry fixing tool in NVDA menu / tools?

They do not appear in your bug report. If some items are probably not relevant in your case, some other (e.g. test without add-ons, computer restart, etc.) do.

> Second, yes I have not tested this issue in other versions, this is because I have not experience this problem in any other versions that I have used before, include but not limited to 20.3, 20.2 etc.

OK so it seems a regression of 2020.4beta1.
Cc. @feerrenrut, @michaelDCurran

**Comment by sine-w** [comment] 2020-12-23 08:05
> 
> 
> > Well, I don't know why you think I have deleted something from the template.
> 
> The bug report template has the following paragraphs at the end
> 
>     * Name and version of other software in use when reproducing the issue:
> 
>     * Does the issue still occur after restarting your computer?
> 
>     * Have you tried any other versions of NVDA? If so, please report their behaviors.
> 
>     * If addons are disabled, is your problem still occuring?
> 
>     * Did you try to run the COM registry fixing tool in NVDA menu / tools?
> 
> 
> They do not appear in your bug report. If some items are probably not relevant in your case, some other (e.g. test without add-ons, computer restart, etc.) do.
> 
Oh, you men this part, oh sorry, I thought it was irrelevant and so I excluded them.
Now I put them back.

**Comment by feerrenrut** [comment] 2020-12-23 09:39
There may be problems with the translations for `zh_hk` but there has not been any update to this since 2018 and I can't the the examples mentioned in there. See [the file (on beta)](https://github.com/nvaccess/nvda/blob/beta/source/locale/zh_HK/symbols.dic)

I'd like to confirm that this is not related to your specific config, could you please test the following:
- Start NVDA with the following arguments: `nvda -c %temp%/tempNVDAconfig/`
- NVDA will start using a fresh temporary profile.
- Set your language and OneCore synthesizer.
- Test these symbols again.

**Comment by sine-w** [comment] 2020-12-23 10:14
* Start NVDA with the following arguments: `nvda -c %temp%/tempNVDAconfig/`

Sorry, I do not know exactly how this is accomplished.
run power shell at the portable nvda folder and run this command?

**Comment by CyrilleB79** [comment] 2020-12-23 10:38
> ```
>  * Start NVDA with the following arguments: `nvda -c %temp%/tempNVDAconfig/`
> ```
> 
> Sorry, I do not know exactly how this is accomplished.
> run power shell at the portable nvda folder and run this command?

This command is rather intended to be used in the command window.
If you have opened a PowerShell at the portable nvda folder, you need to type `cmd` and Enter to get the command Window.
Then type this command.

**Comment by sine-w** [comment] 2020-12-23 10:44
> 
> 
> > ```
> >  * Start NVDA with the following arguments: `nvda -c %temp%/tempNVDAconfig/`
> > ```
> > 
> > 
> > Sorry, I do not know exactly how this is accomplished.
> > run power shell at the portable nvda folder and run this command?
> 
> This command is rather intended to be used in the command window.
> If you have opened a PowerShell at the portable nvda folder, you need to type `cmd` and Enter to get the command Window.
> Then type this command.

Yes, I have follow your instructions and the same problem is observed.
Also, I have just updated to beta 2, and the issue is still here.

**Comment by lukaszgo1** [comment] 2020-12-23 10:46
Try unchecking "Include Unicode Consortium data (including emoji) when processing characters and symbols" in NVDA's speech settings and report back.

**Comment by sine-w** [comment] 2020-12-23 10:53
unchecking "Include Unicode Consortium data (including emoji) when processing characters and symbols" 
THE PROBLEM MENTIONED HERE DISAPPEARED

**Comment by lukaszgo1** [comment] 2020-12-23 11:01
Given that this issue is new in 2020.4 the most likely candidate is #11817.
@sine-w Could you please try [this build](https://ci.appveyor.com/api/buildjobs/891wfi6lv598w58s/artifacts/output%2Fnvda_snapshot_pr11943-21533%2C521270b9.exe) with "Include Unicode Consortium data (including emoji) when processing characters and symbols" checked and report back?
Assuming that CLDR 38.1 does not fix this the most logical course of action would be to revert #11817 from the beta.

**Comment by sine-w** [comment] 2020-12-23 11:07
Adding to this issue,
The current NVDA that I am running is NVDA 2020.2 and the 
option "Include Unicode Consortium data (including emoji) when processing characters and symbols" is checked

**Comment by sine-w** [comment] 2020-12-23 11:16
> @sine-w Could you please try [this build](https://ci.appveyor.com/api/buildjobs/891wfi6lv598w58s/artifacts/output%2Fnvda_snapshot_pr11943-21533%2C521270b9.exe) with "Include Unicode Consortium data (including emoji) when processing characters and symbols" checked and report back?
> Assuming that CLDR 38.1 does not fix this the most logical course of action would be to revert #11817 from the beta.

I have try this build, but the problem is still here

**Comment by sine-w** [comment] 2020-12-23 23:23
Added to that,
1. I try unchecking 'Trust Voice's language when processing character and punctuation' 
2. keep the voice as Microsoft Tracy 
3. If NVDA language kept as ZHHK, the problem is still there, but if I shift the language to ZHTW, the problem disappeared and all the punctuation marks will be reported according to ZHTW dict file.

**Comment by CyrilleB79** [comment] 2021-01-05 08:21
@feerrenrut, would you consider adding this issue to 2020.4 milestone? According to https://github.com/nvaccess/nvda/issues/11963#issuecomment-750144684, this is a regression in 2020.4 and thus it seems logical to fix it in current beta.

**Comment by feerrenrut** [comment] 2021-01-12 04:24
At this stage of the release the best we could do is to revert the CLDR change, which we aren't willing to do. Further investigation is required to pin point the issue. It may be a mistake in:
- CLDR
- Current translations for NVDA symbols file

It seems likely that this can this be fixed on an individual basis by making changes in the symbols list, which is the best course of action for now.

**Comment by zstanecic** [comment] 2021-01-12 06:38
Hi reef,
I cannot reproduce the issue for the languages i maintain, even on the master snapshots.
I would like to see, is the symbols file updated correctly for these languages? I mean, are these languages maintained in the translation system in the correct way?
As i know, Hong kong translation has a lot of outdated parts, thus cluthering space on our translation system. 
I suggest trying to contact the chinese translators for each of the locales.
Maybe the symbols file needs an extensive diagnosing?

**Comment by twonghkbu** [comment] 2021-02-04 09:10
> At this stage of the release the best we could do is to revert the CLDR change, which we aren't willing to do. Further investigation is required to pin point the issue. It may be a mistake in:
> 
> * CLDR
> * Current translations for NVDA symbols file
> 
> It seems likely that this can this be fixed on an individual basis by making changes in the symbols list, wh

ich is the best course of action for now.

Hello,
We have checked the CLDR file and noticed that the annotations were not complete. We would like to update the CLDR file. May I know if there is any way we could submit the file? Thanks.

**Comment by zstanecic** [comment] 2021-02-04 09:23
Hi,

The new cldr annotations are already part of NVDA snapshots. 

You should wait new release.

**Comment by twonghkbu** [comment] 2021-04-20 06:54
May I know what action could we do if most of the emoji was defined as "↑↑↑" in the CLDR file and could not be announced at all?
[cldr_zh_HK.txt](https://github.com/nvaccess/nvda/files/6341250/cldr_zh_HK.txt)

**Comment by CyrilleB79** [comment] 2021-04-22 22:24
Hello

Here are some more information on the "↑↑↑" symbol:

From [CLDR 36 Release Note](http://cldr.unicode.org/index/downloads/cldr-36#TOC-Migration) in Migration paragraph:
> 2. The data in main cldr git repository includes element values with “↑↑↑”. 
> 1. Such values indicate that translators explicitly determined that the parent value is always valid.
> 2. These values (and the paths they belong to) are removed from the release data, but tools that explicitly access the repository information directly need to remove them.
> 3. A new tool in CLDR, GenerateProductionData.java, is used to strip the ↑↑↑ and minimize the data. (Those implementations that don't use that tool can remove lines that contain ↑↑↑; they will always be leaf nodes in XML.)
> 4. A new repository cldr-staging contains data that has already been processed with GenerateProductionData.java (this is the data that is used for the release).

Moreover, the "↑↑↑" symbol is also present in the pt_PT cldr.dic file, not only in the zh_HK cldr.dic file.

It seems these symbols should not be retained when compiling our cldr.dic files.

Cc @OzancanKaratas, @leonardder would you have a look at it?
That would be nice for such users to have this repaired for 2021.1.

**Comment by OzancanKaratas** [comment] 2021-04-23 15:03
> Hello,
> We have checked the CLDR file and noticed that the annotations were not complete. We would like to update the CLDR file. > May I know if there is any way we could submit the file? Thanks.

The only way to do this is to follow the instructions in the CLDR repository.

**Comment by twonghkbu** [comment] 2021-04-26 03:35
> > Hello,
> > We have checked the CLDR file and noticed that the annotations were not complete. We would like to update the CLDR file. > May I know if there is any way we could submit the file? Thanks.
> 
> The only way to do this is to follow the instructions in the CLDR repository.

The incomplete annotations were caused by the "↑↑↑" symbol issue that @CyrilleB79 mentioned above.

**Comment by OzancanKaratas** [comment] 2021-04-26 13:07
I am aware of the problem. However, there is nothing NVDA developers can do to fix this. This problem is caused by incomplete translations in the original CLDR files. If the CLDR team doesn't fix these issues, your problem can't be solved.

**Comment by CyrilleB79** [comment] 2021-04-26 14:49
@OzancanKaratas did you read https://github.com/nvaccess/nvda/issues/11963#issuecomment-825222081? Specifically
> These values (and the paths they belong to) are removed from the release data, but tools that explicitly access the repository information directly need to remove them.
How do you understand it?
Why are you saying that the translation is incomplete?
Could you please elaborate on what should be modified on CLDR side?

Personally, I understand that "↑↑↑" is a valid value for CLDR and that it should be stripped out by people using CLDR data, i.e. us (NVDA) and it should be replaced by an inherited value, the so-called parent value. What is the parent value for zh_HK values? Value coming from zh_CN or zh_TW or en?
Maybe I missed some point in how CLDR works so please let me know what I missed if applicable.
Thanks.

**Comment by OzancanKaratas** [comment] 2021-04-26 22:03
To @CyrilleB79:

Some values in the CLDR's Chinese and Portuguese XML files have been translated as ↑↑↑ instead of the valid translations. For example, I found the following line in zh_Hant_HK.xml:

		<annotation cp="🏻" type="tts">↑↑↑</annotation>

**Comment by CyrilleB79** [comment] 2021-04-26 22:24
@OzancanKaratas, sorry, but you did not reply to all the questions I am asking. Especially if you have read the release notes that I have quoted and what you think about it.

I do not have so much time to investigate further for now, but I am really convinced that the issue of “↑↑↑” symbols is coming from the way we integrated CLDR in NVDA (especially after its migration to git, not from CLDR itself.

If my previous comment was not enough, I am quoting below the firsts lines of the readme.html in our CLDR submodule repo:

> Important notes for CLDR 36 and later:
> • The CLDR repository has switched from subversion to git.
> • Data in the main CLDR repository now includes some elements with the value “↑↑↑” indicating that translators have explicitly determined that the inherited value should always be used.
> • To generate data in the form that was used for CLDR 35.1 and earlier, in which “↑↑↑” is resolved appropriately (either removed or replaced with an apropriate value) and other minimization is performed, a new tool GenerateProductionData is provided (command-line options provide the ability to specify source and destination directory, among other things).
> • CLDR data that has been processed by GenerateProductionData is available in the parallel “cldr-staging” repository.

To @OzancanKaratas or anybody else who want to work on it, please take this information in consideration.

**Comment by twonghkbu** [comment] 2021-04-27 02:03
> @OzancanKaratas did you read [#11963 (comment)](https://github.com/nvaccess/nvda/issues/11963#issuecomment-825222081)? Specifically
> 
> > These values (and the paths they belong to) are removed from the release data, but tools that explicitly access the repository information directly need to remove them.
> > How do you understand it?
> > Why are you saying that the translation is incomplete?
> > Could you please elaborate on what should be modified on CLDR side?
> 
> Personally, I understand that "↑↑↑" is a valid value for CLDR and that it should be stripped out by people using CLDR data, i.e. us (NVDA) and it should be replaced by an inherited value, the so-called parent value. What is the parent value for zh_HK values? Value coming from zh_CN or zh_TW or en?
> Maybe I missed some point in how CLDR works so please let me know what I missed if applicable.
> Thanks.

Hi @CyrilleB79 @OzancanKaratas 
I am not sure if it helps. It appears that the annotation in zh_hk will become "↑↑↑" if the values are missing from the "Sublocales..." column in the Locale Data Summary for Chinese Traditional.
(https://unicode-org.github.io/cldr-staging/charts/latest/summary/zh_Hant.html)

**Closed** 2021-05-17 00:41 UTC
