### ISSUE TITLE
Odd aria-live region behavior

### ISSUE THREAD

**Issue by ctoth** [nvaccess/nvda#5736] opened 2016-02-09 03:30 UTC
I was trying to make a userscript to enhance the accessibility of chatzy.com
I created a new room on Chatzy, found the second table was the one with the chat info in it.
 I set aria-live='polite' on the table
Now, every time I send a chat the entire table is read. I ensured that aria-atomic was set false on the table.

**Comment by jcsteh** [comment] 2016-02-09 03:54
I can't reproduce this behaviour with the following test case:

```
<table id="tbl" aria-live="polite">
<tr><th>1</th><th>2</th></tr>
</table>
<button onClick="var row = document.getElementById('tbl').insertRow(); row.innerHTML = '<td>3</td><td>4</td>';">Insrt row</button>
```

So this case is doing something odd. Any ideas how it might be different?

**Comment by ehollig** [comment] 2017-08-16 20:52
@ctoth, any updates with a specific use case for this issue?

**Comment by ehollig** [comment] 2018-01-14 23:50
Closing this as invalid as @jcsteh was unable to reproduce this issue, and we have not heard from @ctoth for an update on this.

**Closed by ehollig** 2018-01-14 23:50 UTC
Labels: ARIA
