### ISSUE TITLE
Edit Fields: Allow Jumping to Embedded Multiline Edit Controls with Navigation Commands

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#6696] opened 2017-01-04 16:52 UTC
I realise that the summary of this request may sound vague, but I unfortunately don't know the name of this specific control.

When using several web-based applications, some offer multiline edit fields that cannot currently be navigated to by using the next/previous edit field commands. It'd be really useful if these could be included - I've pasted the dev info for one such control below, but let me know if/how I can provide more information on how the control is actually displayed.

Developer info for navigator object:
name: u'about:blank'
role: ROLE_DOCUMENT
states: STATE_FOCUSABLE, STATE_EDITABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateDocumentEditorMozillaIAccessible object at 0x05B09B30>
Python class mro: (<class 'NVDAObjects.Dynamic_EditableTextWithAutoSelectDetectionBrokenFocusedStateDocumentEditorMozillaIAccessible'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.IAccessible.mozilla.BrokenFocusedState'>, <class 'NVDAObjects.IAccessible.mozilla.Document'>, <class 'NVDAObjects.IAccessible.ia2Web.Document'>, <class 'NVDAObjects.IAccessible.ia2Web.Editor'>, <class 'NVDAObjects.IAccessible.mozilla.Mozilla'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: u''
location: (227, 546, 850, 288)
value: None
appModule: <'firefox' (appName u'firefox', process ID 10928) at address 58031b0>
appModule.productName: u'Firefox'
appModule.productVersion: u'50.1.0'
TextInfo: <class 'NVDAObjects.IAccessible.ia2TextMozilla.MozillaCompoundTextInfo'>
windowHandle: 132076L
windowClassName: u'MozillaWindowClass'
windowControlID: 0
windowStyle: 399441920
windowThreadID: 10932
windowText: u'Window Name - Mozilla Firefox'
displayText: u''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x878e6a4 at 5b08120>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=132076, objectID=-4, childID=-492882144
IAccessible accName: u'about:blank'
IAccessible accRole: ROLE_SYSTEM_DOCUMENT
IAccessible accState: STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048580)
IAccessible accDescription: u''
IAccessible accValue: u'about:blank'
IAccessible2 windowHandle: 132076
IAccessible2 uniqueID: -492882144
IAccessible2 role: ROLE_SYSTEM_DOCUMENT
IAccessible2 states: IA2_STATE_OPAQUE, IA2_STATE_EDITABLE (1032)
IAccessible2 attributes: u'margin-left:8px;text-align:start;text-indent:0px;margin-right:8px;tag:body;margin-top:8px;margin-bottom:8px;display:block;line-number:1;explicit-name:true;'

**Comment by jcsteh** [comment] 2017-01-04 23:04
Duplicate of #5534, though I'll adjust the title for that issue to make it clearer.

**Closed by jcsteh** 2017-01-04 23:04 UTC
