### ISSUE TITLE
problem with file explorer and nvda lag on windows 10

### ISSUE THREAD

**Issue by kianoosh-shakeri** [nvaccess/nvda#8225] opened 2018-05-02 21:43 UTC
Working with the system for an almost long time causes the lag problem to happen.
Going in and out of folders makes the nvda stop being able to read items in the folder, Just the title bar can be read with the "nvda+T" keys.
using nvda 2018.1.1 and windows10 1803, 64 bit build 17133.1, no virtual machine

**Comment by leonardder** [comment] 2018-05-03 08:07
Sounds like a duplicate of #8224. Closing

**Closed by leonardder** 2018-05-03 08:07 UTC
