### ISSUE TITLE
nvda does not report current focus after application closes 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#12954] opened 2021-10-18 17:24 UTC
### Steps to reproduce:
During this period of pandemic, the organization where I work installed software called software on employees' home computers
open vpn gui for vpn connection to the office.
The behavior of this software at least after configuration by the information technology personnel is as follows.
We hit enter over the open vpn gui item in the toolbar, the software opens, and after the connection is successfully established the software interface closes automatically and the focus is usually on the desktop.
Previously when the software closed and the focus went to the desktop nvda would announce the focus to the desktop.
After a few alpha versions, unfortunately I don't know how to correctly start from which alpha version, I believe that since the alpha of Tuesday 11/10, nvda doesn't report anything after the automatic closing of the application and the focus on the desktop. 
### Actual behavior:
after the software interface automatically closes nvda is muted 
### Expected behavior:
to recover the previous performance of nvda the reader should inform the focus on the desktop.
Ideally if I can make a suggestion, it would be interesting for nvda to announce itself that the current application has closed, and then soon announce the focus on the desktop.
I would like this information that the application was closed, as this is a direct result of the application's behavior, the application crash was not due to a user action that closed the window.
The announcement of the termination of the application could be configurable, since I know that there are users who don't want that many fidbacks, I'm already part of the group that the more information the better, especially thinking about less experienced users.
Again, the priority would be to return the lost fidback from the desktop focus announcement after automatic application closing.
Suggested improvements would be the announcement of the automatic closing of the application. 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-23971,f2bb38cf

#### Windows version:
11 10.0.22000.282
#### Name and version of other software in use when reproducing the issue:
OpenVPN 2.4.6-I602 ; OpenVPN Technologies, Inc.; 

#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[1openvpn.txt](https://github.com/nvaccess/nvda/files/7367357/1openvpn.txt)

**Comment by feerrenrut** [comment] 2021-10-19 02:21
In terms of investigating further, is the devInfo in the attached log (1openvpn.txt) is for NVDA's focus when in the problem state described by this issue?

If so, it indicates that there is an Open vpn window with focus, the control is an editable text and contains information about the VPN software.
From the log:
```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (13:52:54.249) - MainThread (11104):
Developer info for navigator object:
name: None
role: Role.EDITABLETEXT
roleText: None
states: State.MULTILINE, State.FOCUSABLE, State.READONLY
isFocusable: True
hasFocus: False
Python object: <NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject object at 0x098837B0>
Python class mro: (<class 'NVDAObjects.Dynamic_IAccessibleRichEdit20WindowNVDAObject'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.edit.RichEdit20'>, <class 'NVDAObjects.window.edit.RichEdit'>, <class 'NVDAObjects.window.edit.Edit'>, <class 'NVDAObjects.behaviors.EditableTextWithAutoSelectDetection'>, <class 'NVDAObjects.behaviors.EditableText'>, <class 'editableText.EditableText'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=420, top=228, width=526, height=210)
value: 'Mon Oct 18 13:52:06 2021 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018\rMon Oct 18 13:52:06 2021 Windows version 6.2 (Windows 8 or greater) 64bit\rMon Oct 18 13:52:06 2021 library versions: OpenSSL 1.' (truncated)
appModule: <'appModuleHandler' (appName 'openvpn-gui', process ID 5156) at address 3f6b730>
appModule.productName: None
appModule.productVersion: None
TextInfo: <class 'NVDAObjects.window.edit.ITextDocumentTextInfo'>
windowHandle: 918360
windowClassName: 'RichEdit20W'
windowControlID: 162
windowStyle: 1343244484
extendedWindowStyle: 512
windowThreadID: 9848
windowText: 'Mon Oct 18 13:52:06 2021 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018\r\nMon Oct 18 13:52:06 2021 Windows version 6.2 (Windows 8 or greater) 64bit\r\nMon Oct 18 13:52:06 2021 library versions: OpenSSL ' (truncated)
displayText: 'Mon Oct 18 13:52:06 2021 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEMon Oct 18 13:52:06 2021 Windows version 6.2 (Windows 8 or greater) 64bitMon Oct 18 13:52:06 2021 library versions: OpenSSL 1.1.0h  27 Mar 2018, LZO 2.1' (truncated)
IAccessibleObject: <POINTER(IAccessible) ptr=0x7383458 at 9734da0>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=918360, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_TEXT
IAccessible accState: STATE_SYSTEM_READONLY, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048640)
IAccessible accDescription: None
IAccessible accValue: 'Mon Oct 18 13:52:06 2021 OpenVPN 2.4.6 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Apr 26 2018\rMon Oct 18 13:52:06 2021 Windows version 6.2 (Windows 8 or greater) 64bit\rMon Oct 18 13:52:06 2021 library versions: OpenSSL 1.' (truncated)
```

**Comment by Adriani90** [comment] 2023-03-01 14:31
@fernando-jose-silva does this problem still occur with NVDA 2022.4?

**Comment by Adriani90** [comment] 2023-03-01 18:46
It is likely that this does not occur anymore since #10567 has been merged a while ago. It might depend on which Windows version you are. Please open a new issue with updated steps to reproduce and NVDA and Windows version if you have this problem again.
I am closing this one for now since we cannot reproduce it reliably with these STR.

**Closed by Adriani90** 2023-03-01 18:46 UTC
