### ISSUE TITLE
Update the user guide section 7 to include Mathcat instead of Mathplayer 

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15352] opened 2023-08-31 07:53 UTC
### Is your feature request related to a problem? 
The section 7 in the user guide is outdated. MathPlayer has been discontinued and Mathcat is the follow-up project. This should be described and updated in the user guide.

### Describe the solution you'd like
Updated information in the user guide.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by lukaszgo1** [comment] 2023-10-04 18:10
I'm not sure from where the information about MathType being discontinued was taken, but it is most certainly not true. According to its [release notes](https://docs.wiris.com/mathtype/en/mathtype-office-tools/mathtype-office-tools-release-notes.html) last update was released in August 2023, so it is pretty recent. This part of the issue is invalid, and the initial comment should probably be edited to avoid confusion.

**Comment by Adriani90** [comment] 2023-10-10 21:53
Thanks @lukaszgo1 you are right, it seems my info was outdated, it was a forum on Microsoft support web page but it seems the information was wrong. I edited the issue to include Mathplayer only.

**Closed** 2024-01-22 02:00 UTC
Labels: component/documentation, p5, triaged
