### ISSUE TITLE
Feature request: add "jump to next/previous text paragraph" feature to NVDA

### ISSUE THREAD

**Issue by mltony** [nvaccess/nvda#8532] opened 2018-07-21 22:02 UTC
SentenceNav add-on includes "Jump to previous/next text paragraph" keystroke, currently bound to Alt+Shift+Up/Down arrows. Text paragraph is defined as a paragraph that contains one or more full sentences, ending with a punctuation mark such as period, question mark or exclamation mark. This feature would be especially useful on the websites that don't have proper headings, since it allows users to quickly find the beginning of the article or forum post. It is also useful even on web pages with headings, since it allows to skip over non-important elements of the page, such as advertisements, graphics, menus, "Like us on social media" buttons, etc.

I presented this feature on NVDACon 2018 and received very positive feedback from the audience. For a demo of this feature, listen to my talk:
https://www.nvdacon.org/18snin

I feel this feature can be useful to the majority of NVDA users. It might be especially useful to the new screenreader users struggling to learn all the possible ways of navigating around web pages, as it allows to easily find the main content of web pages in a single keystroke. 

Therefore, I propose to add "Jump to next/previous text paragraph" feature to NVDA.

**Comment by josephsl** [comment] 2018-07-21 22:05
Hi, could you mind reformatting this to follow the issue template please? Thanks.

**Comment by mltony** [comment] 2018-07-21 23:18
This issue is not a bug report, but a feature request. I looked at the 
issue template, and it seems to be designed only for bug reports. Steps 
to reproduce,  Actual behavior,  Expected behavior, System configuration 
- none of these make sense here.

**Comment by netblue44** [comment] 2018-07-23 14:48
I completely agree

**Comment by gregjozk** [comment] 2018-07-29 02:00
Hello,

it would be great if it could be included; but here are my concerns:
- this implementation may possibly frustrate JAWS users, because this script was linked (previous/next paragraph) to ctrl+up/down

due to this reason I remapped key and found when ctrl+up/down is mapped to paragraph script, this combination is unusable in windows explorer and other programs/windows, where you can check multiple items at once.
due to these reason personally I'm against to implement this feature to NVDA as it was designed now.

### str:

- remap script next/previous paragraph to ctrl+up/down
- go to desktop/windows explorer etc
- press ctrl+down to move to next item without checking it

### actual behaviour:
error sound

### expected
working as in JAWS so I could check items because ctrl+left/right works just fine

### nvda version:
alpha 15693...

### addon version:
1.1

## p.s.

usually I would post it to another forum but due to presented as this issue as a feature request for NVDA core I commented here.

Other bugs, which have been found, will be posted to nvda addons list.

Thanks.

regards, Jožef

**Comment by mltony** [comment] 2018-07-29 19:23
@gregjozk, this feature request is not about next or previous paragraph. This is about previous or next text paragraph. See my definition of what is a text paragraph in my first comment on this page. As far as I know Jaws has no similar feature.

**Comment by bhavyashah** [comment] 2023-09-15 09:25
Similar (not the same though) to #10648. I'd say only one of the two should be implemented.

**Comment by Adriani90** [comment] 2024-02-20 22:14
Closing as this has been inroduced in #16031.

**Closed by Adriani90** 2024-02-20 22:14 UTC
Labels: close/worksforme
