### ISSUE TITLE
Slow response time when working with Microsoft Office Word and the Freedom Scientific braille driver

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#9243] opened 2019-02-05 20:40 UTC
### Steps to reproduce:

1. Start NVDA with a Focus/PacMate braille display connected, using the Freedom Scientific driver.
2. Open Microsoft Office Word (in my case Word 2016, but I could also reproduce this with Word 2003+WinXP in another computer).
3. Navigate with arrow keys. Response time is higher than when using only speech or another application.
4. Write or modify the document. Sometimes braille is not completely refreshed, and I need to move the caret or write and then delete a space to have it displayed.
5. Disconnect the braille display.
6. Restart NVDA, so it is running with speech only.
7. Repeat step 3. I notice the response time is lower.

### Actual vehavior:

Response time in Word increases when a FS Braille Display is connected, both with Bluetooth and Braille, and decreases when I disconnect it and restart NVDA.

### Expected behavior:

Same response time or one not so high.

#### NVDA installed/portable/running from source:

Installed in all cases.

#### NVDA version:

2018.4.1

#### Windows version:

Windows 10 1803 (build 17134.523) and Windows XP SP3 (reproduced over a year ago in a different computer).

#### Name and version of other software in use when reproducing the issue:

* Microsoft Office Word 2016 (Win10) and 2003 (WinXP)
* Hardware: Focus 40 Blue 5th Generation (firmware version 5.81-40) and PacMate Braille Display 40

#### Other information about your system:

None

### Other questions:

I don't know if this could be fixed by #7727 as I haven't tested any NVDA builds packaged with the proposed native driver. I also don't know if BRLTTY solves this, because I tried to test but I couldn't achieve to get any information from NVDA through it.

#### Does the issue still occur after restarting your PC?

Yes.

#### Have you tried any other versions of NVDA?

Yes, it was reproducible too.

**Comment by lukaszgo1** [comment] 2019-02-05 20:42
Duplicate of #4995.

**Comment by Adriani90** [comment] 2019-02-06 10:02
Closing as duplicate.

**Closed by Adriani90** 2019-02-06 10:02 UTC
Labels: duplicate
