### ISSUE TITLE
An opened file prevents add-on removal in the future

### ISSUE THREAD

**Issue by CyrilleB79** [nvaccess/nvda#12629] opened 2021-07-09 14:22 UTC
### Steps to reproduce:

Example with the Character Information add-on
1. Open a file of the add-on in an editor, e.g. `%appdata%\nvda\addons\charInfo\globalPlugins\charinfo\__init__.py`
2. Open Add-on manager and remove Character Information add-on
   The status of the add-on is "Enabled, Removed after restart"
3. Close add-on manager and restart NVDA as asked.
4. Open add-on manager
   The status of the add-on is "Enabled, Removed after restart". This is expected because the add-on could not be removed due to the file opened in the editor.
5. Close the file of the add-on opened in the editor.
6. Close the add-on manager and restart NVDA as asked.
7. Open add-on manager and check the add-on's status
8. Execute steps 5. to 7. as many times as you want.

### Actual behavior:
At step 7., the status of the add-on is "Enabled, Removed after restart".
The only way I have found to remove this add-on is to remove manually its folder or to reinstall it before removing it again.

### Expected behavior:
At step 7., the add-on should not appear anymore in the list since nothing prevents NVDA anymore to remove the add-on after step 6.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.1rc2
#### Windows version:
Windows 10 1809 (64-bit) build 17763.1935

#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this error has always been present, surely in all versions of NVDA 2019.3 and beyond.

#### If add-ons are disabled, is your problem still occurring?
N/A
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Brian1Gaff** [comment] 2021-07-11 08:36
Yes, I have a feeling that  a second file is involved in setting the state 
and it is now going to contradict itself until those settings agree. It 
fails safe in that it does not disable anything, as you say, it has to be 
reinstalled then removed the legal way again. Its been like that for some 
time. Not sure if its deliberate or not, but I'm sure somebody will 
remember.
 Brian

***@***.***
Sent via blueyonder.
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by lukaszgo1** [comment] 2021-08-04 18:56
I cannot reproduce this with 2021.1 nor with latest Alpha running from sources. At first I thought this might be specific to Char Info but its not reproducible with it either. @CyrilleB79 Perhaps you've forgot to close the folder from which you've started the editor - this happened to me several times in the past and  caused add-on removal process to fail.

**Comment by CyrilleB79** [comment] 2021-08-08 20:52
@lukaszgo1 I cannot re-test for now.
Anyway if Windows Explorer is opened at step 1. along with the file but closed at step 5., the add-on may not be removed at step 2. but should be removed at step 6. in any case. Do you agree?
Would it be reproducible on your side keeping opened not only the file but also Windows Explorer before step 5.?

**Comment by lukaszgo1** [comment] 2021-08-09 10:24
I agree that add-on should be removed as soon as both the file in the editor and Windows Explorer opened in the add-on folder are closed and that is already the case for me in the latest Alpha / 2021.1.

**Comment by Adriani90** [comment] 2021-08-13 08:59
@CyrilleB79 could it be possible that the process of the editor is still running in the task manager after closing the file? Did you check that?

**Comment by CyrilleB79** [comment] 2021-08-24 15:26
Retesting it, I cannot reproduce with the exact same steps but I can reproduce with slightly differents steps. To simplify the issue and avoid phantom processes, I do not open any file in the editor but only keep a subfolder of the add-on opened in the Explorer, e.g. the doc subfolder.
And instead of only removing the add-on, I re-install (or update) an add-on that is already installed.
This may happen with any add-on and not only charInfo. This time, I have tested with sayProductNameAndVersion.

@lukaszgo1 could you try this? Thanks.

**Comment by lukaszgo1** [comment] 2021-08-24 17:50
Yeah - I can reproduce with your latest  STR  - caused by a very simple coding mistake. I'll submit a PR for this and some other issues related to the add-on removal which I've found along the way when testing later today or tomorrow.

**Closed** 2021-09-08 09:33 UTC
