### ISSUE TITLE
NVDA reads not checked for the custom radio buttons with aria-checked property in IE11

### ISSUE THREAD

**Issue by hithp** [nvaccess/nvda#7436] opened 2017-07-24 11:15 UTC
NVDA reads "Not checked" for the custom radio buttons both in focus and brows mode in IE 11.
The code is according to the aria specifications and aria-checked is dynamically updated based on the user action.
The sample URL to verify the Same:
https://dequeuniversity.com/library/aria/custom-controls/sf-checkboxes-radios

Platform Specs:
NVDA 2017.2.
IE11 latest.
Windows7 professional 64 bit.
NVDA has been installed on this machine

**Comment by ehollig** [comment] 2017-08-16 21:58
Duplicate of #6381

**Closed by ehollig** 2017-08-16 21:58 UTC
