### ISSUE TITLE
Generated tones sometimes do not match audio device of synthesizer.

### ISSUE THREAD

**Issue by ultrasound1372** [nvaccess/nvda#7883] opened 2018-01-01 03:26 UTC
If the synthesizer is changed during an NVDA session, tones.beep does not update it's output audio device to reflect it until NVDA is restarted with the config saved on this new device.
### Steps to reproduce:
> 1. Launch NVDA configured to output to the microsoft sound mapper.
> 2. (possibly optional), change system default output device. I always run into this while doing so, because I am changing system device to a virtual audio cable.
> 3. Set NVDA synthesizer to a specific device, such as speakers or headphones.

### Expected behavior:
> If a progress bar or other tones are output by NVDA, they should match the audio device of the synthesizer. In the case of virtual cables being sent to voicechat apps, people on the other end should not hear the beeps directly.

### Actual behavior:
> Beeps are routed through unwanted device, probably the microsoft sound mapper. This results in people receiving virtual cable pipes to hear the beeps but not the synthesizer's speech.

### System configuration:
NVDA version:
> (any) Has been noticed on 2014.1 upwards due to usage habbits.

NVDA Installed or portable:
Installed
Other information:
> Using virtual audio cable technology to send system device output to people on team talk, but telling my speech to go somewhere else so it doesn't bother them.

Windows version:
> Observed on Windows 8.1 or later.

Name and version of other software in use when reproducing the issue:
vb audio virtual cable
https://www.vb-audio.com/Cable/index.htm

Hopefully this can be corrected, it does annoy people on the team talk servers I go on when progress bars exist. It should be noted that if configuration is saved and NVDA is restarted, beeps go through the specified device and not the previous one.

**Comment by josephsl** [comment] 2018-01-01 07:10
Hi,

I think I saw a similar report a few weeks back. CC @TSpivey

**Comment by ehollig** [comment] 2018-08-16 20:05
Possibly related to #7798 and #7797

**Comment by ultrasound1372** [comment] 2018-08-16 21:01
Not quite related, this issue is that NVDA does not bring its sounds output to specific devices when you set them in the synthesizer dialog until restart. Though I can see why you would think it would be since I gave the routing scenario. If I were to set my NVDA output to my laptop speakers, save config, and restart, speech and tones would be coming out of the laptop as planned. Then I would set my synthesizer back to a different device than that, without changing windows default playback device. Whether it is the mapper or not doesn't matter. If I make tones play at this point, they would come out of the laptop speakers. However, speech is coming out of the other device fine. This seems to be specific to tones, NVDA audio files like the exit sound and browse/focus mode sounds don't seem to suffer this problem. NVDA 2018.2.1, I literally just tested this and it does the behavior I just mentioned with the laptop thing.

**Comment by XLTechie** [comment] 2019-09-17 23:58
Duplicate of #2167 

@Adriani90 I think that one has more extensive comments. Although this one's problem description is a bit different, the same solution will fix both as made clear by the comments here.

**Comment by leonardder** [comment] 2019-12-03 11:45
Duplicate of #2167

**Closed by leonardder** 2019-12-03 11:45 UTC
Labels: Add-ons repository, audio, bug, p2
