### ISSUE TITLE
Focus jumps to different element on page after closing and attempting to Open Material UI Dialog component

### ISSUE THREAD

**Issue by UchuuKani** [nvaccess/nvda#12230] opened 2021-03-25 20:52 UTC
### Steps to reproduce:
1. Open Chrome or Edge
2. Browse to https://material-ui.com/components/dialogs/
3. With NVDA active in browse mode, navigate to the first dialog demo and focus on the button which reads "Open simple dialog" (in browse mode, navigate to "Simple dialogs" heading then tab twice to reach the button)
4. Open the dialog using the keyboard using Enter or Space while focused on button
5. Close the dialog by pressing Escape, Enter or Space
6. Attempt to re-open the dialog

### Actual behavior:
The "Change language" menu is opened instead of the dialog

### Expected behavior:
The dialog is opened again

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2020.4
#### Windows version:
Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
#### Name and version of other software in use when reproducing the issue:
Chrome version 89.0.4389.90 (Official Build) (64-bit)
Microsoft Edge version 89.0.774.45 (Official Build) (64-bit)
#### Other information about your system:
Running Windows 10
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If add-ons are disabled, is your problem still occurring?
Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by sergiidiak** [comment] 2021-06-04 15:50
👍 
You can also reproduce it here: https://xlbfh.csb.app/
When the Dialog is closed, despite the active element is the button (reported by Chrome using document.activeElement Live Expression), when you hit space/enter then nothing happens.

**Comment by Adriani90** [comment] 2023-04-13 23:18
Filled Chromium bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=1433125

**Comment by thyore** [comment] 2023-09-28 14:42
This is still replicable as of now, any update?

**Comment by seanbudd** [comment] 2023-10-01 23:39
@thyore - this was just closed by Chrome as fixed.
Can you confirm what NVDA and Chrome version you can reproduce this with?

According to the [chrome triage](https://bugs.chromium.org/p/chromium/issues/detail?id=1433125) this is fixed with:

- Chrome: 119.0.6020.3 (Official Build) dev (64-bit) (cohort: Dev) 
- NVDA: 2023.2
- Unable to reproduce this with NVDA and Chrome 117 and 119.

**Comment by Adriani90** [comment] 2024-01-30 22:25
Fixed in Chrome, closing as works for me. If the isue is still reproducible, please comment and we can reopen.

**Closed by Adriani90** 2024-01-30 22:25 UTC
Labels: close/worksforme
