### ISSUE TITLE
nvda threshold does not save the configured voice speed

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9578] opened 2019-05-16 13:54 UTC
### Steps to reproduce:
In the nvda settings on the speech tab configure the one core synthesizer.
Select the check box
Special increase in speed
At the speed slider control set the speed to 35.
Press the apply buttons and ok.
Save nvda settings
Restart the nvda.
### Actual behavior:
Voice speed is at 50%
### Expected behavior:
the speed should be at 35, which was set by me, and saved in the settings.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
threshold 17249
#### Windows version:
10 17763.475
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
in alpha ver- sions the voice speed is recorded.
However in alpha verifications the Special speed increase option does not exist.
I checked this setting Special increase of speed at the time with problem threshold 17249

**Comment by leonardder** [comment] 2019-05-16 15:29
Duplicate of #9558

**Comment by Adriani90** [comment] 2019-05-16 18:34
Closing as duplicate.

**Closed by Adriani90** 2019-05-16 18:34 UTC
