### ISSUE TITLE
NVDA not reading all columns in grid

### ISSUE THREAD

**Issue by shard2001** [nvaccess/nvda#16496] opened 2024-05-07 06:56 UTC
### Steps to reproduce:

Navigate to https://runner.telerik.io/fullscreen/@anthony2001/OfOkadiY 
Click on a cell and use the arrow keys to move around

### Actual behavior:

NVDA reads out the 3rd->nth columns but not the first or second

### Expected behavior:

It should read all columns

#### NVDA version:

2024.1.0.31547

#### Windows version:

Windows 11

#### Name and version of other software in use when reproducing the issue:

Latest version of Chrome and Edge have the behaviour
Firefox doesn't
An old version of Chromium doesn't show the behaviour either. This is version 102.0.5002.0

This is using the Telerik grid software. They say they can't reproduce the issue, which may be because of the version of Chrome they are using

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

I don't have any

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by shard2001** [comment] 2024-05-07 09:38
Just to add. This happens for me 80% of the time on my work and home PC. It doesn't happen for Telerik at all

**Comment by Adriani90** [comment] 2024-05-07 10:16
I can reproduce this only when reporting of tables is enabled in document formating settings.
Following is written to the log:
```
IO - inputCore.InputManager.executeGesture (12:02:44.144) - winInputHook (12944):
Input: kb(laptop):rightArrow
IO - speech.speech.speak (12:02:44.256) - MainThread (11080):
Speaking ['Tabelle', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:02:44.259) - MainThread (11080):
Speaking ['Ship Country Ship Country edit column settings', 'Spaltenbeschriftung', 'Untermenü', 'Press ctrl + space to group', 'Reihe 32', 'Spalte 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:44.413) - winInputHook (12944):
Input: kb(laptop):rightArrow
IO - speech.speech.speak (12:02:44.457) - MainThread (11080):
Speaking ['Ship City Ship City edit column settings', 'Spaltenbeschriftung', 'Untermenü', 'Press ctrl + space to group', 'Reihe 32', 'Spalte 2', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:46.499) - winInputHook (12944):
Input: kb(laptop):rightArrow
IO - speech.speech.speak (12:02:46.550) - MainThread (11080):
Speaking ['ShipAddress ShipAddress edit column settings', 'Spaltenbeschriftung', 'Untermenü', 'Press ctrl + space to group', 'Reihe 32', 'Spalte 3', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:47.061) - winInputHook (12944):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (12:02:47.614) - winInputHook (12944):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (12:02:49.391) - winInputHook (12944):
Input: kb(laptop):downArrow
IO - speech.speech.speak (12:02:49.447) - MainThread (11080):
Speaking ["59 rue de l'Abbaye", 'Reihe 2', 'Spalte 3', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:51.874) - winInputHook (12944):
Input: kb(laptop):leftArrow
IO - speech.speech.speak (12:02:51.919) - MainThread (11080):
Speaking ['Reims', 'Reihe 2', 'Spalte 2', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:52.785) - winInputHook (12944):
Input: kb(laptop):leftArrow
IO - speech.speech.speak (12:02:52.837) - MainThread (11080):
Speaking ['France', 'Reihe 2', 'Spalte 1', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:02:55.088) - winInputHook (12944):
Input: kb(laptop):leftArrow
ERROR - eventHandler.executeEvent (12:02:55.143) - MainThread (11080):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x05323A70> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "browseMode.pyc", line 1689, in event_gainFocus
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\__init__.pyc", line 1288, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1139, in reportFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1184, in _get_rowNumber
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (12:02:55.590) - winInputHook (12944):
Input: kb(laptop):leftArrow
ERROR - eventHandler.executeEvent (12:02:55.619) - MainThread (11080):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0094F3B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "browseMode.pyc", line 1689, in event_gainFocus
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\__init__.pyc", line 1288, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1139, in reportFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1184, in _get_rowNumber
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
IO - inputCore.InputManager.executeGesture (12:02:56.071) - winInputHook (12944):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (12:02:56.623) - winInputHook (12944):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (12:02:58.814) - winInputHook (12944):
Input: kb(laptop):upArrow
ERROR - eventHandler.executeEvent (12:02:58.856) - MainThread (11080):
error executing event: gainFocus on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x0071E130> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 325, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "browseMode.pyc", line 1689, in event_gainFocus
  File "eventHandler.pyc", line 124, in next
  File "NVDAObjects\__init__.pyc", line 1288, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1139, in reportFocus
  File "speech\speech.pyc", line 628, in speakObject
  File "speech\speech.pyc", line 668, in getObjectSpeech
  File "speech\speech.pyc", line 520, in getObjectPropertiesSpeech
  File "baseObject.pyc", line 62, in __get__
  File "baseObject.pyc", line 168, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1184, in _get_rowNumber
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Unbekannter Fehler', (None, None, None, 0, None))
```

This error appears on every column that cannot be read by NVDA, this seem to be the first two columns.
I am not sure but this might be a web authoring issue. However, I wonder why there is a difference when I disable reporting of tables? Then it works as expected and all 5 columns are reported.

cc: @jcsteh any suggestions?

**Comment by Adriani90** [comment] 2024-05-07 10:17
I tested in Chrome 124 with NVDA 2024.1.
cc: @aleventhal this seems to be reproducible only in Chromium browsers.

**Comment by shard2001** [comment] 2024-08-30 13:37
This seems to be fixed in the latest version of Chrome and with the latest download of NVDA. The code hasn't changed

**Comment by Adriani90** [comment] 2024-08-30 20:47
Thanks for the update, closing as works for me.

**Closed by Adriani90** 2024-08-30 20:47 UTC
Labels: close/worksforme, blocked/needs-external-fix, p3, app/chrome, app/edge/anaheim, triaged
