### ISSUE TITLE
Say all command doesn't work in Balabolka

### ISSUE THREAD

**Issue by nvdaes** [nvaccess/nvda#5627] opened 2015-12-21 21:58 UTC
It seems that the text read corresponds to the displayed text, that is, scroll is not working.
Tested in NVDA 2015.4 with Portable Balabolka:
http://www.cross-plus-a.com/balabolka_portable.zip
Thanks.

**Comment by jcsteh** [comment] 2015-12-21 22:47
Duplicate of #659.

**Closed by jcsteh** 2015-12-21 22:47 UTC
Labels: duplicate
