### ISSUE TITLE
Preferences Dialog: Only display Apply Button if Changes have been Made

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#9065] opened 2018-12-13 14:47 UTC
Currently, the "Apply" button is always displayed within the Preferences dialog - even if no changes have actually been made. To match the behaviour of most dialogs within Windows, would it be possible for this button to only display if changes have been detected? I wasn't sure if this is a current limitation of WX.

**Comment by leonardder** [comment] 2018-12-13 14:50
Duplicate of #8430

**Comment by lukaszgo1** [comment] 2018-12-13 14:50
Duplicate of #8430

**Closed by leonardder** 2018-12-13 14:50 UTC
