### ISSUE TITLE
Say All with Speech Platform voices problem

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5779] opened 2016-02-26 13:39 UTC
When I use the Microsoft Speech Platform voices with NVDA, when performing a Say all, I hear a slight pause at the end of a line. This makes reading less fluent.

**Comment by leonardder** [comment] 2017-11-01 17:09
Could we treat this as a duplicate of #1961?

**Comment by feerrenrut** [comment] 2017-11-08 12:13
@leonardder I think so.

**Closed by feerrenrut** 2017-11-08 12:13 UTC
Labels: bug, Speech
