### ISSUE TITLE
Focus order becomes incorrect after navigating between pages with a table element inside of an aside element

### ISSUE THREAD

**Issue by epiconsin** [nvaccess/nvda#15043] opened 2023-06-21 18:44 UTC
### Steps to reproduce:
1. Navigate to a webpage with a `main` element and a `table` element inside of an `aside` element where focus is set at the top of the page
2. Navigate to another webpage with a `main` element and a `table` element inside of an `aside` element where focus is set at the top of the page
3. Navigate back to the webpage in Step 1
4. Press TAB and see that the focus is on the next element after the `table` element

Example code:
```html
<main>
    <div>
        <h1>Main</h1>
    </div>
    <!-- More Content -->
</main>
<aside>
    <div>
        <table>
            <!-- Table Content -->
        </table>
    </div>
    <h2>Links</h2>
    <div>
        <a href="website.com">Link1</a>
    </div>
</aside>
```

### Actual behavior:
When loading a webpage with a `main` element and a `table` element within an `aside` element for the first time, focus is correctly set at the top of the webpage. However, when navigating to another webpage with a `main` element and a `table` element within an `aside` element and back, the focus is incorrectly set on the element after the `table` element when it should be at the top of the page. 

Navigating to any other webpage and back will set the focus to the element after the `table` element, regardless of whether the page navigated to has a `table` element within an `aside` element or not. In other words, the bug seems to be persistent once it occurs.

### Expected behavior:
When loading a webpage with a `main` element and a `table` element within an `aside` element, focus should always be set at the top of the webpage regardless of the page the user was on before or how the user navigated to the page.

This bug only occurs when using NVDA and not with other popular screen readers.

### NVDA logs, crash dumps and other attachments:
No relevant logs, crash dumps, etc.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2023.1.0.27913

#### Windows version:
Windows 10 Enterprise (10.0.19045 Build 19045)

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge Version 114.0.1823.51 (Official build) (64-bit)
Mozilla Firefox Version 114.0.2 (64-bit)
Google Chrome Version 114.0.5735.134 (Official Build) (64-bit)

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, same behavior.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by Adriani90** [comment] 2024-12-20 00:02
This is intended behavior. If you focus a link or any other focusable element before opening a new page and going back, NVDA will try to put the focus at the element which was focused before opening the new page.

If you don't focus anything with tab or shift+tab, but go back and forth with alt+left arrow and alt+right arrow, the focus is always at the top of the page as you expect.

For screen reader users it doesn't make sense though to always redirect the focus to the top of a page, because this slows down efficient navigation significantly. The focus should ideally always be put as near as possible to the previously focused element when returning back to a web page.

I am closing as invalid.

**Closed by Adriani90** 2024-12-20 00:02 UTC
Labels: close/invalid, p4, triaged, needs-technical-investigation
