### ISSUE TITLE
Standard User Prevents NVDA From Accurately Reading Install Dialogs

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#7669] opened 2017-10-18 00:51 UTC
### Steps to reproduce:
1. Create an Administrator account.
2. Switch to or change the current account to a standard user account
3. Install something, such as Microsoft Office 2016.
4. When UAC comes up, enter the Administrator password as prompted and try to proceed with the installation.
#### Other Places I've Noticed This Behavior:
1. Open registry editor with the standard user account by typing "regedit" into the Run dialog and pressing ENTER. UAC will come up. Enter the administrator password and press ENTER.
2. Observe that NVDA will not read the treeview or list view in Registry Editor.

### Expected behavior:
NVDA should flawlessly read all controls in the dialog.

### Actual behavior:
NVDA reports "invisible focus" on things like edit controls and list boxes; additionally, object navigation shows no usable objects on screen. In some instances, the entire window, such as Registry Editor, just reports as "pane" as I tab around. If I encounter check boxes, their states are incorrectly always reported as "not checked."

Performing the installs with an Administrator account solves the issue (IE: the same dialog which was previously inaccessible on the standard user account is fully accessible on the Administrator account.)

### System configuration:
NVDA version: 2017.3

NVDA Installed or portable: Installed

Other information: Only occurs with standard user accounts, not Administrator accounts.

Windows version: Windows 10 Creator's Update

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? Yes: 2017.2, with same result

**Comment by derekriemer** [comment] 2017-10-18 03:48
This almost certainly has to do with NVDA being run as not an admin, so it can't access stuff running at a higher privilege than it. I'm not sure what we can do to fix this.

**Comment by leonardder** [comment] 2017-10-18 04:12
This does not only apply to running software as an admin, but in general, running software as a different user could cause problems. For example, when running a management console under a different user, the SysListView32 code causes invalid handle errors for winKernel.virtualAllocEx.

This is *not* an issue in JAWS, for example, when MMC reads just fine when running under a different user.

**Comment by munawarb** [comment] 2017-10-18 08:18
Hi,
I remember Window-Eyes had this issue at one point and they corrected it somehow. How they did it is beyond me. I'll try reinstalling NVDA as admin this weekend and report back to you.

Correct that JAWS does not have this issue.

**Comment by leonardder** [comment] 2017-10-18 09:18
Here is some additional technical background.

For every window, NVDA tries to create a process handle with certain rights, see oleacc.GetProcessHandleFromHwnd. However, when the process in question is running under a different user, no handle can be retrieved and obj.processHandle is 0. Some ideas:

NVDA never seems to check whether the processHandle is 0, and just executes stuff that depends on a proper processHandle, for example in SysListView32 code. This is super duper ugly :)

**Comment by leonardder** [comment] 2017-10-18 09:23
[**@munawarb**](https://github.com/munawarb) commented on [18 okt. 2017 10:18 CEST](https://github.com/nvaccess/nvda/issues/7669#issuecomment-337498718 "2017-10-18T08:18:17Z - Replied by Github Reply Comments"):
> I remember Window-Eyes had this issue at one point and they corrected it somehow. How they did it is beyond me. 

I belief Window-Eyes runs as admin, which isn't the solution we should provide by default here.

> I'll try reinstalling NVDA as admin this weekend and report back to you.

I'm afraid this won't make any difference.

**Comment by Brian1Gaff** [comment] 2017-10-18 09:58
Hmm, could this be an issue contributing to the update and restart issues?
 IE it seems not to have any idea if stuff has terminated before it restarts 
things like overwriting files or restarting nvda.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by leonardder** [comment] 2017-10-18 10:45
[**@Brian1Gaff**](https://github.com/Brian1Gaff) commented on [18 okt. 2017 11:58 CEST](https://github.com/nvaccess/nvda/issues/7669#issuecomment-337533414 "2017-10-18T09:58:27Z - Replied by Github Reply Comments"):
> Hmm, could this be an issue contributing to the update and restart issues?

No.

**Comment by munawarb** [comment] 2017-10-18 12:05
@leonardder  So I would have to explicitly tell the NVDA process to run as admin, and not just install it using an admin account?

**Comment by leonardder** [comment] 2017-10-18 12:16
[**@munawarb**](https://github.com/munawarb) commented on [18 okt. 2017 14:05 CEST](https://github.com/nvaccess/nvda/issues/7669#issuecomment-337568840 "2017-10-18T12:05:30Z - Replied by Github Reply Comments"):
> @leonardder  So I would have to explicitly tell the NVDA process to run as admin, and not just install it using an admin account?

I have tested this and even this does not work, at least not on the Windows 10 fall creators update.

**Comment by leonardder** [comment] 2017-10-23 06:23
I filed feedback for this issue, see https://aka.ms/V55e3e . Feel free to upvote :)

**Comment by craigbrett17** [comment] 2017-10-24 08:13
Seems related to: #3671

If WindowEyes runs as admin, how does it then read things that are run as a standard user? If NVDA could run as admin but still manage to read things on the standard user, I'd say that's an acceptable work around. But that doesn't seem to be the case right now.

The way things stand, I have to flick between an administrative NVDA and a standard one, depending on what I want to read. I was coming here to suggest maybe in these instances whether running multiple instances would be acceptable... even if not ideal.

**Comment by leonardder** [comment] 2018-02-15 12:10
I've actually been able to reproduce this issue in JAWS when using the touch cursor. Just wanted to point this out. This is certainly not NVDA specific, though JAWS seems to have found a nice way to work around it.

**Comment by leonardder** [comment] 2019-01-31 18:43
I tested this this morning with Windows 10 version 1809. Either I did something wrong, or this issue has been partly solved. I was able to use the registry editor under a different user without any issues.

**Comment by Adriani90** [comment] 2024-04-24 21:43
@LeonarddeR suggestes the issue was fixed, and we didn't get any contrary updates since many years. I am closing this as works for me. Please comment if you are still having this issue and we can reopen.

**Closed by Adriani90** 2024-04-24 21:43 UTC
Labels: close/worksforme, blocked/needs-external-fix
