### ISSUE TITLE
in chrome, sometimes focus is jumping

### ISSUE THREAD

**Issue by beqabeqa473** [nvaccess/nvda#8013] opened 2018-02-19 04:26 UTC
hello all.

there is a problem with google chrome.

for example visit
https://github.com/beqabeqa473
and in repositories tab navigate text with up/down arrows, specifically, repositories which are forked.

focus is jumping every time and some quicknav keys should be pressed to jump to the farther element to get rid of this trap.

**Comment by Adriani90** [comment] 2018-02-21 08:53
Related to 
#2039

**Comment by Adriani90** [comment] 2019-12-20 17:18
@beqabeqa473 I cannot reproduce this anymore in NVDA 2019.3 Beta 1 and Google Chrome version 79. Could you please test under the same setup and see if the issue stil occurs on your side?

**Comment by Adriani90** [comment] 2020-06-25 15:09
This example does not reproduce the issue anymore, I guess the web Autor changed the design. Anyway, this is rather a duplicate of #2039. I am closing as duplicate.

**Closed by Adriani90** 2020-06-25 15:09 UTC
Labels: close/duplicate
