### ISSUE TITLE
 NVDA focus does not move separately on the 'ccccc' text while navigating using the down arrow key in browse mode.

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#16649] opened 2024-06-04 07:15 UTC
### Steps to reproduce:
1. Open the url [A Pen by Xinhao Du (codepen.io)](https://codepen.io/xinhaodu_microsoft/pen/OJYbJPp)
2. Navigate on the 'ccccc' text in browse mode.
3. Observe the issue.

### Actual behavior:

NVDA focus does not move separately on the 'ccccc' text while navigating using the down arrow key in browse mode.
NVDA focus moves to 'aaaaa' link control while navigating using the down arrow key in browse mode and NVDA announce as 'link aaaaa > link bbbbb' > cccccc,in one go and on pressing down arrow, NVDA focus is not moving to the next link or 'ccccc' text.

### Expected behavior:

NVDA focus should move separately on 'bbbbb' link and 'ccccc' text while navigating using the down arrow key in browse mode.

### NVDA logs, crash dumps and other attachments:

https://github.com/nvaccess/nvda/assets/93735775/c71126cf-a25a-435f-b1cd-9ac8aa6cb2d6

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2024.1.0.31547

#### Windows version:
Windows 11 23H2 22631.3593

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NA

#### If NVDA add-ons are disabled, is your problem still occurring?
NA

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
NA

**Comment by Adriani90** [comment] 2024-06-04 21:26
Closing as duplicate of #11073.

**Closed by Adriani90** 2024-06-04 21:26 UTC
Labels: close/duplicate
