### ISSUE TITLE
Some text will be ignored in internet explorer when using say all command with ESpeak.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4755] opened 2014-12-28 12:52 UTC
**Reported by vgjh2005 on 2014-12-28 12:52**
Hi:
Using say all command in internet explorer with ESpeak read long text, some text will be ignored then text is after that will be read. Thanks!

**Comment by bhavyashah** [comment] 2017-08-03 08:01
CC @jcsteh

**Comment by Adriani90** [comment] 2019-01-11 21:21
@vgjh2005 are you still able to reproduce this issue?

**Comment by Adriani90** [comment] 2019-05-05 17:40
I am testing with NVDA 2019.1.1 and IE11 on this website with One core voices, eloquence and eSpeak:
http://www.msn.com/de-de/?cobrand=dell17win10.msn.com&ocid=DELLDHP17&pc=DCTE
I do not see any difference after 5 minutes of say all with every voice. I guess this could have been caused by a notification or an allert which appeared. NVDA is interupted from say all when reading the notification or the allert. afterwards, NVDA starts say all again. You can create a profile for say all and disable tooltips in NVDA settings / object presentation. Probably this will be also touched by speech refactoring.
Closing as works for me.
If you are still having this problem, please comment and we can reopen the discussion.

**Closed by Adriani90** 2019-05-05 17:40 UTC
Labels: bug, worksforme
