### ISSUE TITLE
Allow for "select all" in Add-on Manager to copy list of Add-ons and versions and enabled/disabled status

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#11240] opened 2020-06-08 22:24 UTC

**Comment by DrSooom** [comment] 2020-06-09 06:05
Adding a button to copy all useful information about the NVDA environment in the NVDA About window to the clipboard could help here. See also: Issue #8709

**Comment by feerrenrut** [comment] 2020-06-11 11:32
The bug report template asks you to test with add-ons disabled. The list of enabled add-ons can be derived from the log. If a bug only occurs with an add-on enabled, the report should go to the add-on author. Narrowing this down requires disabling half the add-ons, testing, based on the result you'll know which batch contains the problematic add-on. Then you can continue to divide this group until you have one remaining.

I'm going to close this issue, since the log contains the information if it was ever needed for a bug report, but also a bug report doesn't ask for this.

**Comment by josephsl** [comment] 2020-06-11 16:58
Hi,

Actually, what Brian is asking is not this - he wants to make sure people have an easy way to copy and paste information on installed add-ons (you can do this from Python Console, although that is something beginners will stay away from).

I'm not reopening this until Brian comments on this.

Thanks.

**Comment by britechguy** [comment] 2020-06-11 17:10
Joseph,

          You are correct with regard to what I'm asking about and for.  It is more than a bit of a surprise that there is no "select all" along with copy ability in the Add-On Manager in NVDA, and not just solely for the purpose of bug reporting.

           Also, the bug report template has a certain minimum required information.  As someone who's done software development in the past, I often want, and greatly appreciate, something beyond the minimum.  In most cases, when I am reporting what I suspect is an NVDA bug, I am not going to have shutdown and restarted my machine, started with all add-ons disabled, etc., before having done so.  Most users won't.  I'm also inclined to report the Add-Ons I do have, and for me it's a mere inconvenience to look at them (literally) and type them out, but it should not be necessary, and it's a major stumbling block for a blind user to do the same thing with any ease.  I just had my last bug report resolved because I reported I still had the Focus Highlight Add-On installed and enabled, and since that functionality has been integrated into NVDA 2020.1 this was causing some sort of conflict and malfunction.  The issue was not with NVDA at all, and once the list of Add-Ons was reviewed, the first thing I was asked to do was to disable (and subsequently uninstall) this Add-On and the issue was resolved.

Users need to be easily able to report information about the actual state of NVDA, as they are using it at the time of an issue occurring, and being able to give the list of add-ons being used, the versions of same, and their respective enabled/disabled states is part of that.  And it's often asked about (as it was in my case) long before logs would ever be requested.

**Comment by britechguy** [comment] 2020-06-11 17:30
On an unrelated note, if someone can tell me why my last comment has everything but "Joseph" and the last paragraph represented inside that grey box with slider, I'd love to know why.  

I even copied my entire comment, pasted it into notepad, then copied it back in an effort to get that to go away.  I have not included any hidden formatting, so I don't know what's up.

**Comment by tspivey** [comment] 2020-06-11 18:09
@britechguy Some of your paragraphs are indented. If you edit your comment, you can remove the spaces at the beginning, which should remove the unwanted formatting.

**Comment by britechguy** [comment] 2020-06-11 18:12
Thank you Mr. Spivey!!   I never in a million years would have thought that indenting the initial word of a paragraph or paragraphs would trigger that!

Original corrected.

**Comment by XLTechie** [comment] 2020-06-11 21:25
Another possible reason why this might be useful, is if it is desirable to 
replicate an NVDA setup without copying.

I.E. if something has corrupted NVDA and you need to reinstall, or to provide a 
list of add-ons that interact to perform some desired tasks, or whatever.

A "Copy list of add-ons to clipboard" button would probably be easier to arrange 
than a select all and copy capability, which I believe would require 
re-engineering the whole dialog.

**Comment by britechguy** [comment] 2020-06-11 22:40
XLTechie wrote:  A "Copy list of add-ons to clipboard" button

And that, in my opinion, would be perfect.  I was not really envisioning anything that allowed line-by-line selection and copying (unless you could also do a Select All first) because in virtually all cases you need that information as a whole.

**Comment by feerrenrut** [comment] 2020-06-12 13:21
The reason I closed this was because the the "why" part of the request doesn't make sense. We don't want a list of addons to be added to bug reports. If it was necessary to debug complicated issues a log is likely required.

>  just had my last bug report resolved because I reported I still had the Focus Highlight Add-On installed and enabled, and since that functionality has been integrated into NVDA 2020.1 this was causing some sort of conflict and malfunction

This is exactly why the template requests trying to reproduce the problem without add-ons installed.

> Another possible reason why this might be useful, is if it is desirable to
replicate an NVDA setup without copying.

Again the log is a much better solution for this, since at debug level it also includes the user config.

The request as it stands is a solution looking for a problem. If the problem is that it is hard to gather the information about NVDA required for a bug report, then a better solution is to have a "copy NVDA info for bug report" option somewhere (tools menu?)

Happy for a debug utility to be added, I'm quite against adding a debug utility to the front of the add-on dialog. 

Again closing this, as it stands it doesn't describe the problem well, and actively misleading as to how we want bugs raised.

**Closed by feerrenrut** 2020-06-12 13:21 UTC
