### ISSUE TITLE
Feature request:  Lock focus-mode:

### ISSUE THREAD

**Issue by LarrySilvermintz** [nvaccess/nvda#8716] opened 2018-09-04 21:58 UTC
Overview: It is sometimes preferred to default to interacting with the Web in focus mode.  For example, partially-sighted people using a magnifier with NVDA may prefer to start in, and stay in Focus Mode. 
Therefore, the locked-focus setting would maintain focus-mode even when opening new browser windows, restarting the browser or possibly even when switching browsers.

 First, please create a key command to lock focus mode, default could be NVDA+ctrl+space.

Second:  Please create a configuration file setting to lock focus mode, The user could place this in either a global or a triggered-configuration.

**Comment by Brian1Gaff** [comment] 2018-09-05 07:34
I'd have thought that the place for this sort of thing is the settings for 
focus mode where you can  already set it to be auto or not auto focus mode. 
Some tweaks to the logic and another checkbox could be introduced.
 I'm still not really clear how this is supposed to help magnification users 
though, as if you set focus mode to auto  as I have it it slips into it when 
an interactive control  appears in focus.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
-----

**Comment by LarrySilvermintz** [comment] 2018-09-05 16:04
Thank you for your immediate acknowledgement.

As further examples,

These browser characteristics work best in focus (pass-through) mode:
selecting text with the mouse (a feature that obviously necessitates
eyesight), page up/down.  Firefox features such as "Search for text when you
start typing" necessitate pass-through.

Partially-sighted people can use the visual appearance of the screen to see
the layout and to navigate, using the screen reader for things like hover
echo and reading selected-text. 

 

That is why it would be great to lock pass-through mode.

 

Is there any way to get pass-through behavior without changing the NVDA
program?

 

Larry Silvermintz

Sarasota, FL

  _____

**Comment by LarrySilvermintz** [comment] 2018-09-06 23:52
Thank you Daniel!

Im so glad you see the value of my request and perhaps will help to
implement it.

Cheers!

Larry Silvermintz

Sarasota, FL

  _____

**Comment by leonardder** [comment] 2018-09-08 17:27
At @babbagecom, we also see the impmortance of this feature. Therefore, I will take this.

**Comment by LarrySilvermintz** [comment] 2018-09-08 17:42
Great!

Thank you so much!

 

Regards,
Larry Silvermintz

  _____

**Comment by leonardder** [comment] 2018-09-11 14:00
I've almost got it settled, however there is one thing I'd really like to implement. When someone explicitly disabled browse mode (i.e. enabled pass through), I'd like NVDA to remember that decision. So for example:

1. Open google.com
2. Focus the edit box with browse mode
3. Press NVDA+space
4. Enter a search term and press enter.

Since the user explicitly disabled browse mode here, it makes sense to remember that state. However, pass through is now remembered on a per tree interceptor basis, and since a new page load creates a new tree interceptor, the initial pass through mode gets lost.

@jcsteh or @michaeldcurran: Any idea how to address this? May be we should get rid of browseMode.reportPassThrough.last while at it, that is, it should no longer be a property on the reportPassThrough method.

**Comment by LarrySilvermintz** [comment] 2018-09-11 17:33
That's the right idea!  Thank you.

  _____

**Comment by josephsl** [comment] 2019-03-29 19:41
Hi,

I'm reopening this due to regression caused by the associated pull request in Microsoft Word.

Thanks.

**Comment by LarrySilvermintz** [comment] 2019-03-29 19:51
Thank you Joseph.  Would be good to get the feature.

 

Regards,
Larry Silvermintz

941-556-9200

Sarasota, FL

  _____

**Comment by leonardder** [comment] 2019-03-29 20:23
I disagree with reopening. There's no need to reopen this as long as #8846 is not reverted. I will most likely provide a fix to this at the start of next week, which progress can be tracked in #9422. In browsers, the feature is implemented as advertised.

**Comment by leonardder** [comment] 2019-03-29 20:45
I just confirmed that this feature works as advertised in cases where browse mode is enabled by default on page load. The regression in Word, caused by #8846, is not related to this functionality. I just filed #9423 to fix #9422. Closing this one again.

**Closed by leonardder** 2019-03-29 20:45 UTC
Labels: Browse mode, feature
