### ISSUE TITLE
adding a menu to include all the addons

### ISSUE THREAD

**Issue by fatmamehanna** [nvaccess/nvda#5707] opened 2016-01-24 07:22 UTC
hi all,
i'd like to ask for a menu, or even a menu item, to be devoted to include all the addons and its preferences. for instance, we find some addons in the tools menu, others in the preferences menu, etc. so i think it would be easier to devote a menu or a menu item to go to when we want to control/modify an addon settings.
thanks.

**Comment by leonardder** [comment] 2017-07-17 11:25
CC @DerekRiemer @JosephSL

**Comment by ehollig** [comment] 2017-08-14 19:40
Duplicate of #4689

**Closed by ehollig** 2017-08-14 19:40 UTC
Labels: Add-on management
