### ISSUE TITLE
Strange error raised in Word regarding browse mode when browse mode is off

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7161] opened 2017-05-09 10:17 UTC
Steps to reproduce:

1. Open a new word document and press down arrow
2. Enable browse mode with nvda+space and press down arrow
3. Disable browse mode with nvda+space and press down arrow

The expected result for those three situations are the same, namely that NVDA says blank. However, in the third case, the following error is raised.

```
ERROR - eventHandler.executeEvent (12:16:45):
error executing event: caretMovementFailed on <NVDAObjects.Dynamic_IAccessibleWordDocumentWindowNVDAObject object at 0x0532EF70> with extra args of {'gesture': <keyboardHandler.KeyboardInputGesture object at 0x052E5E10>}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "browseMode.pyc", line 1195, in event_caretMovementFailed
AttributeError: 'BrowseModeWordDocumentTextInfo' object has no attribute 'UNIT_CONTROLFIELD'
```

**Comment by jcsteh** [comment] 2017-05-09 22:49
Confirmed. Note that this only happens if "Automatic focus mode for caret movement" is enabled. For future reference, please note that this is an important setting to mention in issues related to moving the cursor where browse mode or focus mode is concerned.

P3, since although it is an exception, it is caught by eventHandler and does not affect any calling code.

**Comment by Adriani90** [comment] 2019-04-16 22:29
I can still reproduce this issue in NVDA 2019.1.1.
In my opinion this issue should be investigated further due to following reasons:
1. When switching from browse mode to focus mode and pressing up and down arrow, NVDA will not read anything if the text is only one line long. But itwill read characters if you press left and right arrow.
2. The error seems to be raised only when reaching the borders of the document (i.e. at the top of the document or at the bottom. in case there is only one line of text, the error will be also raised when reaching the left edge and right edge of the line.
3. It seems it also affects NVDA's performance during navigation. In big documents it could be very important. See e.g. this example from a document with 4 lines where the error is raised:

```
IO - speech.speak (00:17:39.029):
Speaking [u'Seite 1  Abschnitt 1', u'Hello']
IO - inputCore.InputManager.executeGesture (00:17:39.367):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (00:17:39.433):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - inputCore.logTimeSinceInput (00:17:39.523):
0.157 sec since input
IO - speech.speak (00:17:39.523):
Speaking [u'Leer']
IO - inputCore.InputManager.executeGesture (00:17:39.678):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (00:17:39.743):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - inputCore.logTimeSinceInput (00:17:39.832):
0.154 sec since input
IO - speech.speak (00:17:39.832):
Speaking [u'How are you?']
IO - inputCore.InputManager.executeGesture (00:17:39.993):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (00:17:40.055):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - inputCore.logTimeSinceInput (00:17:40.131):
0.137 sec since input
IO - speech.speak (00:17:40.131):
Speaking [u'Leer']
IO - inputCore.InputManager.executeGesture (00:17:40.332):
Input: kb(laptop):downArrow
DEBUG - editableText.EditableText._hasCaretMoved (00:17:40.648):
Caret didn't move before timeout. Elapsed: 100 ms
ERROR - eventHandler.executeEvent (00:17:40.653):
error executing event: caretMovementFailed on <NVDAObjects.IAccessible.winword.WordDocument object at 0x05424330> with extra args of {'gesture': <keyboardHandler.KeyboardInputGesture object at 0x053F60B0>}
Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "browseMode.pyc", line 1290, in event_caretMovementFailed
AttributeError: 'BrowseModeWordDocumentTextInfo' object has no attribute 'UNIT_CONTROLFIELD'
IO - inputCore.logTimeSinceInput (00:17:40.773):
0.441 sec since input
```

So the performance in the middle of the document is 0.137 sec  but at the borders is slower, at 0.441 sec. When disabling automatic switch to focus mode, the performance at borders improved to approx. 0.37 sec.

**Comment by Adriani90** [comment] 2020-04-24 23:41
I cannot reproduce this in NVDA Version: alpha-20045,a335297e and MS Word 2016, MS Word 365 or MS Word 2010.
It might have been fix after the porting to Python 3. I am closing this as works for me, but feel free to reopen if it is still occuring for you.

**Closed by Adriani90** 2020-04-24 23:41 UTC
Labels: close/worksforme, p3
