### ISSUE TITLE
Issue with addon store

### ISSUE THREAD

**Issue by agtheblade** [nvaccess/nvda#15275] opened 2023-08-10 01:16 UTC
There is a bug when using the addon store in 2023.2 beta 2. When navigating the store using control tab, NVDA does not properly report the updates tab when switching to it from the installed addons tab. It is necessary to shift tab to the tab groups in order to know you are on that tab. NVDA announces "tab control panel" when using shift tab to bring up the updatable addons tab.

**Comment by seanbudd** [comment] 2023-08-10 01:46
Closing as duplicate of #14986

In future, please fill out the issue template and use a descriptive title.
Kind regards,
NV Access

**Closed by seanbudd** 2023-08-10 01:46 UTC
