### ISSUE TITLE
NVDA loses window focus upon receiving a notification in windows 11

### ISSUE THREAD

**Issue by OlegTheSnowman** [nvaccess/nvda#14715] opened 2023-03-12 07:50 UTC
When using Windows 11, I have noticed that NVDA, version 2022.4, Installed, loses window focus upon receiving notifications. If any window is open and a notification is received, the focus of the window disappears. While the functions of the window can still be used, the screen reader won't narrate anything and will be focused on nothing.
Steps to Reproduce:
1. Install Windows 11 22H2 (AMD64) build 22621.1265
2. Install NVDA, version 2022.4, or a newer version
3. Open any window
4. Wait for a notification to be received
Expected Result:
NVDA should continue narrating the window's functions after a notification is received.
Actual Result:
NVDA loses focus upon receiving a notification, and the screen reader won't narrate anything, leaving the focus on nothing.
Additional Information:
This issue did not occur on Windows 10, and only started happening after updating to Windows 11.

**Comment by Adriani90** [comment] 2023-03-12 19:15
cc: @josephsl

**Comment by Adriani90** [comment] 2023-03-12 19:20
@OlegTheSnowman could please thest with NVDA 2023.1 RC1 and report if the issue is also occuring with this NVDA version? I guess it could be a duplicate of #14039.

**Comment by josephsl** [comment] 2023-03-12 19:54
Hi,

Is this happening with NVDA 2022.3 and earlier and/or Narrator?

Thanks.

**Comment by mdyer1** [comment] 2023-03-12 20:24
Hi,  

A is the only screenreader having this problem.  I only seen this with 2022.4 and 2023.1 RC.  Jaws 2023 does not have this problem.

 

Matthew

**Comment by jcsteh** [comment] 2023-03-13 23:35
Duplicate of #14039.

**Closed by jcsteh** 2023-03-13 23:35 UTC
