### ISSUE TITLE
addons manager: add a toggel option to disable and enable all addons, exactly like the toggel option for disable and enable a single addon

### ISSUE THREAD

**Issue by amirmahdifard** [nvaccess/nvda#14644] opened 2023-02-16 13:37 UTC
### Is your feature request related to a problem? Please describe.
currently, if we want to disable all our addons to report a bug to nvda, we should use the restart with addons disabled, and if we restart our nvda again, all the addons are gonna be enabled again back: and if we want our addons not to enable anymore until we actually enable it our selves, we have to disable all of them one by one, and later we have to enable them again: please add a toggel option to the addons manager dialog, called (disable all addons button), and when we press it, it should turn to (enable all addons button): and the shortcuts for it can be alt + shift + e to enable, and alt + shift + d to  disable, where as alt + e and alt + d is for a single addon:
### Describe the solution you'd like
we can use restart with addons disabled, but i don't like to use this option too much, because this option is for reporting a bug, and if you restart your nvda again, it's gonna be enabled again, i know that this could be so easy if you add this toggel option, even the bug reporters can use this option instead of the option in nvda restart dialog after you add it.
### Describe alternatives you've considered
please add a toggel option to the addons manager dialog to disable or enable all addons at once, and as same as the option for the single addon, if we toggeled it and exited that dialog, it should ask a question to restart the nvda now or later, as it does when an addon has some changes and the nvda asks to restart
### Additional context
this is not gonna breake any compatability api, as you are not removing or modifying anything that is already exist, you are just adding a new option to the addons manager dialog, and after you added this in some version of nvda, then, in 2024.1 since you will have an api breaking compatability, you can then remove the restart with addons disabled option, so that people can use this toggel option from that point forward, as this toggel option would be more nicer and makes more sence to me if we have an ability to disable or enable all our addons from it's dialog, just by pressing enter and toggeling it, and when we close that dialog, the nvda is gonna be restarted anyway, so it would do anything that the restart with addons disabled option did: i would be really happy if you added this option, it doesn't matter if you remove the restart with addons disabled option right after that, or in some difrent versions, or even never did that, at least i would use this option from that point forward.

**Comment by amirmahdifard** [comment] 2023-02-16 13:42
guys, when i thort about this option and i got excited for it so much, and i thort it's so nice if we have this option in there if possible: please tell me do you also think same as me? and can this one be added possibly? thank you!

**Comment by Brian1Gaff** [comment] 2023-02-16 16:40
My thoughts are that even if you disable a single add on you are restarting 
nvda in effect. Maybe  The question is, if you disable all by restarting, 
when you turn them all back on one assumes it remembers any that have been 
disabled in any case.
 I guess I'm not getting the real point behind what you are trying to 
achieve here.
 As far as I know, because python is compiled, you have to restart if you 
add in or remove any code, and there is not  any easy way around that unless 
you are going to make the routine run as an interpreted piece of code,which 
would make it slow and you still would need it to hook in to already running 
nvda code in multiple areas, making it very hard to do and hacky by nature.
 Brian

-- 
***@***.***
Sent via blueyonder.(Virgin media)
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by seanbudd** [comment] 2023-02-16 18:33
I'm going to close this as a duplicate of #11317, which covers this use case and more.

**Closed by seanbudd** 2023-02-16 18:33 UTC
