### ISSUE TITLE
Google chrome freezing when entering the comment edit box on YouTube

### ISSUE THREAD

**Issue by hozosch** [nvaccess/nvda#14907] opened 2023-05-05 16:35 UTC
### Steps to reproduce:
1. Open a YouTube video in chrome
2. Navigate to the field to type your comment in the comments section
### Actual behavior:
When pressing enter on the "add comment" edit box, chrome freezes, and closing it is a nightmare. It comes up with that "site does not respond" dialogue. It also makes my fan go very mad, and it's very annoying. Hope it made sense. I'm unfortunately very unexperienced in sending the correct logs and other attachments of this kind you ask for. 
### Expected behavior:
Well, obviously, chrome shouldn't freeze and I'm able to enter that edit box correctly and type my comment!
### NVDA logs, crash dumps and other attachments:
Unfortunately none, as I don't know which one would give a clue to the problem.
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2023.1
#### Windows version:
windows 11 home 64 bit, 22 h2, build 22621
#### Name and version of other software in use when reproducing the issue:
google chrome, or the youTube web app for chrome
#### Other information about your system:
Don't know what to put here, it happens on other machines as well, although not as aggressively as on this one.
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I may still need to do that.
#### If NVDA add-ons are disabled, is your problem still occurring?
When using the "restart with disabled add-ons" option in the exit dialogue, yes. I don't know if it makes a difference when disabling all add-ons manually, or completely removing all add-ons.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes, it does.

This may be the wrong place to post, but this is where I'm able to describe my issue the best, as I use NVDA in conjunction with chrome or the youTube web app for it. If this turns out to be a Chrome issue though, I'm sorry for posting this here. Using another browser would be an option, I guess, but I just got used to Chrome so much.

**Comment by seanbudd** [comment] 2023-05-09 02:08
Welcome @hozosch 

We are unable to process this issue as it stands.

- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- This is very likely a problem with the implementation of the application or website, as a starting point please submit feedback to Chromium to let them know about the problem.

Kind Regards,
NV Access Software Developers

**Comment by Adriani90** [comment] 2023-05-09 21:37
Yeah I can reproduce this in Chrome 113 and also in Edge. 113. Jaws works as expected so I think it is indeed an NVDA bug when trying to fetch the comment edit field. I get an error with the error code "out of memory" and the browser page crashes. With Jaws running the page does not crash.

Unfortunately I couldn't catch the errors in the log yet. Bu I have seen alot of garbageHandler errors in the log when the crash occured.

**Comment by hozosch** [comment] 2023-05-09 21:42
Glad to have someone here who brought in some more useful information. I was going to try the things that @seanbudd suggested, setting the log to debug, but now that may not be necessary anymore. Or is it?

**Comment by Adriani90** [comment] 2023-05-09 21:43
It seems when tabbing to the comment edit field in focus mode, this crash does not occur. So it might also be something hapening when trying to build the virtual document while using browse mode and NVDA cannot sync the system focus to the virtual cursor position when pressing enter on the comment edit field.

So this might occur exactly when NVDA tries to sync the system focus to the virtual cuursor position and fails, causing the page to crash.

cc: @jcsteh I've seen a crash in Firefox as well but this happened only once and I was too late to catch any errors. But maybe you have an idea what's hapenning here.

**Comment by Adriani90** [comment] 2023-05-09 21:45
@hozosch your log would be very useful in case you hear any error sounds when the crash occurs. You can enable the error sounds in the NVDA advanced settings, reproduce the issue and as soon as you hear any error sounds, try to open the log and save it instantly.

**Comment by Adriani90** [comment] 2023-05-09 21:56
It seems in Chromium browsers, if you click with the mouse on the edit field first, then you can press enter while you are in browse mode and then the focus seems to sync properly. In this case the crash is not occuring.

In Firefox it works much better, the focus syncs as expected most of the times.

**Comment by hozosch** [comment] 2023-05-09 21:58
Well, the error sound does not seem to work for me, but may this give a clue to the error?
INFO - watchdog.waitForFreezeRecovery (23:53:14.487) - watchdog (1208):
Recovered from freeze after 0.6706087000000025 seconds.
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (23:53:16.086) - MainThread (2160):
Foreground took too long to change. Foreground still 525766 (Chrome_WidgetWin_1). Should be 262594 (XamlExplorerHostIslandWindow)
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets (23:53:20.975) - MainThread (2160):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 327, in _getLineOffsets
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (23:53:24.020) - MainThread (2160):
accRole failed: (-2147024809, 'Falscher Parameter.', (None, None, None, 0, None))

**Comment by hozosch** [comment] 2023-05-09 22:01
I think I should point out here that "Falsch" is German for wrong or false. So wrong parameter.

**Comment by Adriani90** [comment] 2023-05-09 22:02
It seems in Firefox this edit field is properly recognized as an contentEditable edit field and it is also spoken as "edit field" when moving the mouse to the control with NVDA+shift+m
However, in Chromium browsers this seems to be recognized only as text, no control type announced when moving the mouse to it. I wonder if this is a rendering issue here as well?

**Comment by hozosch** [comment] 2023-05-09 22:28
Well at least there's a way round it. Thanks adriani for that one. I think it would still be good to have this fixed, but with that way round, it's not as urgent.

**Comment by Gene703122** [comment] 2023-06-03 17:31
It has been reported on the large English NVDA user's list that when using Narrator, the problem doesn't occur either.  this is not a problem with the implementation of the web page.  Since neither JAWS nor Narrator has the problem, it is an NVDA problem.  Also, it has been reported on the user's list that the problem occurs in Edge.  It is therefore likely to be a problem in Chrome-based browsers in general.

Also, I am not a tech, but I think it may be intimidating to inexperienced ticket creators to ask for a log in a case like this where the problem can be easily replicated and indeed will be as a matter of confirmation and the log will then be available on the replicating machine.

**Comment by Adriani90** [comment] 2024-03-29 18:58
This issue is not reproducible anymore with NvDA 2024.1 RC1, Chrome Canary 125, Edge 123 or Firefox 124. Closing as works for me.

**Closed by Adriani90** 2024-03-29 18:58 UTC
Labels: close/worksforme, bug/app-freeze, p2, blocked/needs-info, triaged

**Comment by hozosch** [comment] 2024-03-29 19:00
Right, thanks for closing.  Works here too.
