### ISSUE TITLE
If the Status Bar is not found, NVDA just silently errors.

### ISSUE THREAD

**Issue by trypolis464** [nvaccess/nvda#11938] opened 2020-12-13 18:48 UTC
### Steps to reproduce:
Open a blank WX Frame or Dialog and attempt to get the status bar.
### Actual behavior:
Silence/error sound.
### Expected behavior:
NVDA to speak "No Status Bar information".
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-21485,d3ba21a3

#### Windows version:
Windows 10 2004 (64-bit) build 19041.685
#### Name and version of other software in use when reproducing the issue:
No other software needed (except any app without a statusbar).
#### Other information about your system:
Intel I7, 4.2 GHZ, 8 cores. 16 GB RAM.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.3 also does this.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No.

### Error output
ERROR - scriptHandler.executeScript (10:16:06.119) - MainThread (33000):
error executing script: <bound method GlobalCommands.script_reportStatusLine of <globalCommands.GlobalCommands object at 0x0755F890>> with gesture 'NVDA+end'
Traceback (most recent call last):
  File "globalCommands.pyc", line 1604, in script_reportStatusLine
  File "baseObject.pyc", line 26, in __get__
  File "appModuleHandler.pyc", line 612, in _get_statusBarTextInfo
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scriptHandler.pyc", line 208, in executeScript
  File "globalCommands.pyc", line 1606, in script_reportStatusLine
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 146, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 1191, in _get_flatReviewPosition
  File "baseObject.pyc", line 26, in __get__
  File "textInfos\offsets.pyc", line 506, in _get_pointAtStart
  File "virtualBuffers\gecko_ia2.pyc", line 30, in _getBoundingRectFromOffset
  File "virtualBuffers\__init__.pyc", line 373, in _getUnitOffsets
OSError: [WinError 1775] A null context handle was passed from the client to the host during a remote procedure call

**Comment by Adriani90** [comment] 2023-09-16 19:23
This is not reproducible in NVDA 2023.2. Closing as works for me. If you are still having this issue, please domment and we can reopen.

**Closed by Adriani90** 2023-09-16 19:23 UTC
Labels: close/worksforme
