### ISSUE TITLE
Discussion: Should the NVDA master branch use the new main name of github?

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#11452] opened 2020-08-03 11:02 UTC
The current branch of Hello World [GitHub Guides](https://guides.github.com/activities/hello-world/#repository) has been transferred from master to main.
NVDA  Should I use the latest specification of github to update NVDA's master and branch names?

**Comment by feerrenrut** [comment] 2020-08-03 11:21
If we were to change it, I think we'd make it "alpha" instead. This then makes it clear this is where the alpha builds come from. That said, changing the name of the branch is no small task. Our build system, release system, and documentation would need updating.

**Comment by zstanecic** [comment] 2020-08-03 11:31
Is it a high priority issue?

I mean… no.

Changing just to reflect how is with github is something which may break translation system.

We need to solve more higher priority problems, like adding new addons to the translation system and its future.

Thanks

**Comment by lukaszgo1** [comment] 2020-08-03 11:43
I have to agree with @zstanecic here - wasting resources on a name change which is caused by the fact that some people wants to be politically correct and enforce their vision of political correctness on others is not a good use of anyone's time. I vote to close this and #11451 as well.

**Comment by dingpengyu** [comment] 2020-08-03 11:52
> I have to agree with @zstanecic here - wasting resources on a name change which is caused by the fact that some people wants to be politically correct and enforce their vision of political correctness on others is not a good use of anyone's time. I vote to close this and #11451 as well.
In fact, I also disagree with the change, because I recently saw that most of the github projects are modifying the names of the names, so I sent an issue to investigate.

**Comment by Brian1Gaff** [comment] 2020-08-03 19:56
I don't understand what their issue is with master, Many English words have 
many meanings after all.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by feerrenrut** [comment] 2020-08-03 20:06
Ignoring the political nature of the prompt to do this, using "alpha" for our alpha branch makes sense, and reflects our beta and rc branches.

**Comment by Adriani90** [comment] 2020-08-03 21:27
It seems there is a concensus here towards leaving this as is. I am closing this issue for now, please comment if I misunderstood it and then we can reopen. Thanks.

**Closed by Adriani90** 2020-08-03 21:27 UTC
