### ISSUE TITLE
Problem with alt + down arrow and choosing item from dropdown list in chrome

### ISSUE THREAD

**Issue by michaldziwisz** [nvaccess/nvda#7224] opened 2017-05-30 12:51 UTC
### Steps to reproduce:
1: Open chrome
2: go to http://www.autos.com.pl/pl/oddzialy/polska
3: Try select e.g. thirt value from the list by pressing alt + down arrow when focus is on the list.

### Expected behavior:
User should be able to select any value from the list, e.g. like in Firefox

### Actual behavior:
alt + down arrow doesn't work, and direct interaction with list cause reloading the webpage

### System configuration:
NVDA version:
2017.2

NVDA Installed or portable:
installed
Other information:

Windows version:
Windows 7 X64 Proffeional

Name and version of other software in use when reproducing the issue:
Google Chrome Canary 61.0.3115.0 
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment] 2017-09-06 02:10
@michaldziwisz, is this still an issue? I am not able to load the page that you have provided in the original post.

**Comment by michaldziwisz** [comment] 2018-10-23 00:54
@ehollig yes, problem still exists.

**Comment by ehollig** [comment] 2018-10-23 16:16
I am not able to reproduce this issue. I performed the following steps:

1. Go to http://www.autos.com.pl/pl/oddzialy/polska in Chrome
2. Press C to go to the next combo box.
3. Press alt+down arrow.
4. Select the third item in the list and press enter.

Are these the steps you took or slightly different?

**Comment by PratikP1** [comment] 2018-10-23 18:09
@michaldziwisz Did you press enter when you landed on the combo box? It is necessary to enter focus mode before interacting with the combo box. I got the same results as @ehollig.

**Comment by Adriani90** [comment] 2019-04-18 00:15
I cannot reproduce this issue in NVDA 2019.1.1 and Chrome 73.
Closing as works for me, since we have the same results by other users. @michaldziwisz if you are still having this issue, please comment on it and we can reopen it. Thanks.

**Closed by Adriani90** 2019-04-18 00:15 UTC
Labels: Chrome, worksforme
