### ISSUE TITLE
Significant hang due to speech processing when web page focuses an element containing a large amount of content

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#16307] opened 2024-03-15 06:27 UTC
Cc @jcsteh 

### Steps to reproduce:

1. Visit [this page](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html), warning: this will cause Firefox and NVDA to freeze severely as it tries to load the page
2. Close Firefox, this will probably require assistance. Then try to restart NVDA to restore speech

### Actual behavior:

NVDA never responds when attempting to load the page even after waiting for several minutes.

After closing Firefox and restarting NVDA, repeatedly, no speech is heard. NVDA seems to have crashed so badly that a full restart of the machine was the only way to get it working again, which is very concerning.

### Expected behavior:

The page should load. More importantly, restarting NVDA should restore speech.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-31360,dd44cbb7 (2024.2.0.31360)

#### Windows version:
Windows 10 22H2 19045.4046

#### Name and version of other software in use when reproducing the issue:
Firefox 123.0.1

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
N/A

**Comment by jcsteh** [comment] 2024-03-15 06:39
I think the page URL is missing from your link.

**Comment by Neurrone** [comment] 2024-03-15 07:20
Apologies, have updated the description with the link.

**Comment by jcsteh** [comment] 2024-03-15 07:36
I can't reproduce this. The page does take about 15 seconds to load for me, but I don't get a hang beyond 15 seconds or so.

That said, NVDA really shouldn't freeze at all here, so I took a look at the log. It seems it got frozen processing an absolutely massive chunk of speech. The page seems to focus a div when it loads, which contains most of the content of the page. My guess is that NVDA catches the focus event and starts trying to read the entire div (most of the page) in one go.

What speech synth are you using? Or do you have any add-ons which additionally process speech? If the synth (or something else) blocks for a while when trying to process a massive chunk of speech, that's going to make this a lot, lot worse. eSpeak alone doesn't have that problem though.

**Comment by jcsteh** [comment] 2024-03-15 08:01
Distilled test case:

```
data:text/html,
<button autofocus>before</button>
<div tabindex="-1" id="content"></div>
<script>
setTimeout(() => {
  let html = "";
  for (i = 0; i < 10000; ++i) {
    html += `<p>${i} <a href="/">This is a test.</a> This is a test. <a href="/">This is a test.</a></p>`;
  }
  content.innerHTML = html;
  content.focus();
}, 1000);
</script>
```

If you load this test case, NVDA will hang. The log will show a freeze like this:

```
INFO - watchdog.waitForFreezeRecovery (17:54:16.093) - watchdog (24736):
Starting freeze recovery after 10.389960300002713 seconds.
DEBUGWARNING - watchdog.waitForFreezeRecovery (17:54:16.514) - watchdog (24736):
Listing stacks for Python threads:
...
Python stack for thread 24308 (MainThread):
  File "nvda.pyw", line 399, in <module>
  File "core.pyc", line 864, in main
  File "wx\core.pyc", line 2262, in MainLoop
  File "wx\core.pyc", line 3427, in <lambda>
  File "core.pyc", line 794, in processRequest
  File "core.pyc", line 810, in Notify
  File "queueHandler.pyc", line 97, in pumpAll
  File "queueHandler.pyc", line 64, in flushQueue
  File "eventHandler.pyc", line 84, in _queueEventCallback
  File "eventHandler.pyc", line 327, in executeEvent
  File "eventHandler.pyc", line 115, in __init__
  File "eventHandler.pyc", line 124, in next
  File "browseMode.pyc", line 1706, in event_gainFocus
  File "speech\speech.pyc", line 1325, in speakTextInfo
  File "speech\speech.pyc", line 1033, in speak
  File "speech\speech.pyc", line 164, in processText
  File "characterProcessing.pyc", line 709, in processSpeechSymbols
  File "characterProcessing.pyc", line 626, in processText
  File "characterProcessing.pyc", line 622, in _regexpRepl
```

See also #16233, which is similar in that NVDA is trying to speak a huge chunk of text due to REASON_FOCUS in browse mode.

**Comment by jcsteh** [comment] 2024-03-15 08:02
The best part with this particular freeze is that if you restart NVDA, it will catch the focus event again from Firefox and do it all over again.

**Comment by jcsteh** [comment] 2024-03-15 08:04
Note that this isn't Firefox specific. You would see the same issue in Chromium if an absolutely massive container got focus in browse mode.

**Comment by jcsteh** [comment] 2024-03-15 22:17
I'm reopening this because even though the hang isn't as bad with eSpeak, it still hangs NVDA in a very undesirable way.

> I'm curious how you figured out the focus was the issue?

An educated guess after seeing where NVDA was hanging. Say all on page load can never send chunks this big because it breaks it up into lines. In contrast, we always report focus in one chunk. I then verified my guess by pressing NVDA+tab, which reported "section" instead of the document, meaning that a div had focus. Further investigation then revealed what this div contained.

**Comment by jcsteh** [comment] 2024-03-15 22:21
Actually, it probably makes most sense to close this as a duplicate of #16233.

**Closed by jcsteh** 2024-03-15 22:21 UTC
Labels: close/duplicate
