### ISSUE TITLE
make switching between synthisizers easier

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4679] opened 2014-12-10 07:11 UTC
**Reported by mohammed on 2014-12-10 07:11**
Hi.

those of us who have to use more than one synthesizer a lot would appreciate making switching between 2 synthesizers easier. I propose one of the following as a solution:
1. include Synthesizer in the synth settings ring.
2. the ability to hide unused synthesizers from  the synthisizer list (NVDA +ctrl +s)

**Comment by leonardder** [comment] 2017-07-13 19:09
For the synthesizer in the settings ring part, this is a duplicate of #2590. Leaving it open due to the second idea.

**Comment by leonardder** [comment] 2017-07-13 19:16
Actually, I can't see a use case for having synthesizers hidden in the synthesizer dialog, since it allows first letter navigation as @JCSTeh pointed out. Closing as duplicate for the first issue and a won't fix for the second one. But, feel free to provide a valid use case for the latter and we can consider reopening.

**Closed by leonardder** 2017-07-13 19:16 UTC
Labels: enhancement, NVDA GUI
