### ISSUE TITLE
NVDA not reading Insert Function dialog auto-completion textbox in Excel 2016 and earlier

### ISSUE THREAD

**Issue by ivnc** [nvaccess/nvda#11573] opened 2020-09-08 08:27 UTC
This issue has been received from a Spanish-speaking user. I only have Office 365 and was unable to reproduce it, so all of the below info is based on user comments.

### Steps to reproduce:

1. Open Microsoft Office Excel.
2. Place the focus in a blank cell (you may need to press escape to close the welcome page).
3. Go to the Formula ribbon, then press "Insert function". With Office set to Spanish you can access by pressing the key sequence Alt+U, 3.
4. Write part of a function's name, for example, "sum".

### Actual behavior:

NVDA doesn't handle what is supposed to be an auto-completion textbox, according to this user and tests performed by JAWS users with similar Office versions that confirm this. The user says that if she presses down arrow with JAWS, she can locate the "sumar.si" function ("sumif" in English), while when using NVDA she couldn't use this functionality.
Log entry (might be relevant or not) after triggering the Insert function button:
DEBUGWARNING - NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor._get_isAlive (18:01:20.049) - MainThread (11216):
could not compare sheet names
Traceback (most recent call last):
  File "NVDAObjects\window\excel.pyc", line 461, in _get_isAlive
  File "comtypesMonkeyPatches.pyc", line 82, in new__getattr__
  File "comtypes\client\lazybind.pyc", line 168, in __getattr__
  File "comtypes\automation.pyc", line 729, in _invoke
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147418111, 'La llamada fue rechazada por el destinatario.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.killTreeInterceptor (18:01:20.050) - MainThread (11216):
Killed treeInterceptor: <NVDAObjects.window.excel.ExcelBrowseModeTreeInterceptor object at 0x0999EA30>

### Expected behavior:

NVDA should read auto-completion suggestions.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2020.2

#### Windows version:

Windows 10 V2004

#### Name and version of other software in use when reproducing the issue:

Reproducible: Excel 2016 and 2010. Tested only with JAWS in Office 2013.
Not reproducible: tested exclussively with NVDA, in Office 365, the dialog shows a search box with a "go" button.

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No, or not known

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No

**Comment by Adriani90** [comment] 2020-09-10 20:39
cc: @lukaszgo1, @josephsl

**Comment by Adriani90** [comment] 2024-06-25 13:56
I cannot reproduce this in MS Office 2016 with NVDA 2024.2. There is no suggestion combo box, it is a list of functions which is filtered while you type the letters in the edit field. NVDA can focus this list after you press enter on the edit field, and then you can navigate the list items properly.
1. Focus the insert function dialog / search function edit field
2. Type SUM
3. Pres enter

Actual and expected: NVDA moves to the list with the filtered functions, where you can use up and down arrow to navigate.

In this case, jaws probably move to the list items when you press the arrow key in the edit field, but this is not a MS Office feature. Visually the focus doesn't move unless you really focus the list with tab key first. Jaws probably handles this via its script for MS outlook, and the user can just move to the list with a press of an arrow key and continue to select the desired function from the filtered list with the system focus.

Since NVDA can do the same but by pressing the enter key instead of arrow key, I think this is a 100%  equivalent alternative. Closing as works for me.

**Closed by Adriani90** 2024-06-25 13:56 UTC
Labels: close/worksforme
