### ISSUE TITLE
Can't open some links on Firefox including Google search results

### ISSUE THREAD

**Issue by bingen13** [nvaccess/nvda#11379] opened 2020-07-15 08:50 UTC
### Steps to reproduce:

Open a page that has links with an empty href attribute, such as google.com - perform a search and use h to navigate by headers to one of the results - press enter or space to try to open the link.

### Actual behavior:

Nothing happens (that is, the link does not open).

The link shows on Braille as clk and speech as clickable, but neither lnk/vlnk is announced or braille, nor is link announced by speech.

### Expected behavior:

The link would show as lnk/vlnk on Braille, be announced as a link by speech, and when enter is pressed, it would open.

#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:

2020.1

#### Windows version:

Windows 8.1 64-bit

#### Name and version of other software in use when reproducing the issue:

Firefox 78.0.2 64-bit

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If addons are disabled, is your problem still occuring?

Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, will do that now.

This used to work, very very recently.

It's not limited to Google either, but occurs on other sites that have anchors without a href that get activated via js.

**Comment by Adriani90** [comment] 2020-07-15 18:38
@bingen13 did you run the COM registration fixing tool? Is the issue still occuring?

Also please try to disable screen layout in browse mode settings or by pressing nvda+v when you are in browse mode.

**Comment by bingen13** [comment] 2020-07-15 20:25
Ok, inexplicably this has stopped happening by itself. I don't understand what happened, but whatever it is, it's fixed now. 😕

**Comment by Adriani90** [comment] 2020-07-19 16:18
I could reproduce it when automatically set focus to focusable elements is disabled (nvda+8). I tested on google search results by pressing h or shift+h and then enter on search results. Sometimes it works and the search result is activated, but you hear i.e. "visited visited" because NVDA drags the system focus to the link and performs the click action afterwards. So it repeats the word "visited".
But sometimes (I would say in 3 of 5 times), NVDA only drags the system focus to the virtual cursor and does not perform any click action on the search result, so you have to press enter twice to activate the link. You can check with nvda+tab where the focus is.

@jcsteh, @leonardder any idea how to solve this? In my view this is quite important to solve before having this behavior set by default. Otherwise users will wonder why links are not activated on first enter press out of browse mode. This issue might exist on buttons and other elements also, I tested only with heading links in Google with Firefox 78.

I am reopening this issue.

**Comment by jcsteh** [comment] 2020-07-19 22:19
I've actually never experienced this, and I have auto set focus off all the
time and use Google search a lot. I'll watch for it, but at this stage, I
can't provide any input.

**Comment by leonardder** [comment] 2020-07-20 05:36
I've also experienced this from time to time, really no idea what can cause this.

**Comment by Adriani90** [comment] 2020-07-20 18:10
I have some snippet from the log which might help:

```
Input: kb(laptop):h
IO - inputCore.logTimeSinceInput (20:03:25.603) - MainThread (9296):
0.020 sec since input
IO - speech.speak (20:03:25.613) - MainThread (9296):
Speaking ['Fußzeilenlinks', 'Überschrift', 'Ebene 1']
IO - inputCore.InputManager.executeGesture (20:03:26.403) - winInputHook (1324):
Input: kb(laptop):h
IO - inputCore.logTimeSinceInput (20:03:26.423) - MainThread (9296):
0.020 sec since input
IO - speech.speak (20:03:26.423) - MainThread (9296):
Speaking ['Keine weitere Überschrift']
IO - inputCore.InputManager.executeGesture (20:03:26.813) - winInputHook (1324):
Input: kb(laptop):shift+h
IO - inputCore.logTimeSinceInput (20:03:26.853) - MainThread (9296):
0.040 sec since input
IO - speech.speak (20:03:26.853) - MainThread (9296):
Speaking ['Technology Info: arosak.com', 'Überschrift', 'Ebene 3', 'Link']
IO - inputCore.InputManager.executeGesture (20:03:28.123) - winInputHook (1324):
Input: kb(laptop):enter
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (20:03:28.173) - MainThread (9296):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (20:03:28.173) - MainThread (9296):
Clicking with mouse
IO - inputCore.InputManager.executeGesture (20:03:30.493) - winInputHook (1324):
Input: kb(laptop):enter
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (20:03:30.533) - MainThread (9296):
doAction failed
DEBUGWARNING - virtualBuffers.gecko_ia2.Gecko_ia2._activateNVDAObject (20:03:30.533) - MainThread (9296):
Clicking with mouse
IO - inputCore.logTimeSinceInput (20:03:30.713) - MainThread (9296):
0.220 sec since input
IO - speech.speak (20:03:30.713) - MainThread (9296):
Speaking ['besucht']
DEBUG - treeInterceptorHandler.killTreeInterceptor (20:03:31.693) - MainThread (9296):
Killed treeInterceptor: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x0626D1D0>
DEBUG - treeInterceptorHandler.update (20:03:31.698) - MainThread (9296):
Adding new treeInterceptor to runningTable: <virtualBuffers.gecko_ia2.Gecko_ia2 object at 0x06EA26F0>
DEBUG - virtualBuffers.VirtualBuffer._loadBuffer (20:03:31.932) - virtualBuffers.gecko_ia2.VirtualBuffer.loadBuffer (13808):
Buffer load took 0.235 sec, 13373 chars
IO - inputCore.logTimeSinceInput (20:03:32.032) - MainThread (9296):
1.539 sec since input
IO - speech.speak (20:03:32.032) - MainThread (9296):
Speaking ['arosak.com - Technology Info', 'Dokument', CancellableSpeech (still valid devInfo( isCanceledCache: False, isValidCallback: True, isValidCallbackDevInfo:  )]
```

It is more often reproducible when you
1. Press ctrl+end to reach the end of the search result page
2. Press shift+h until you land on a search result
3. Press enter

**Comment by bhavyashah** [comment] 2021-01-17 03:39
I routinely experience this issue. One work-around that has worked fairly consistently for me is to navigate to that link and switch to focus mode before pressing Enter on it; focus mode makes all the difference.

**Comment by Adriani90** [comment] 2023-02-06 15:11
Did anyone have this issue in the last time using the last version of NVDA and the newest Firefox updates? I will try to test later again.

**Comment by jcsteh** [comment] 2023-06-09 11:19
Previously, this might have happened if the link contained another element which was not clickable, in which case NVDA would have tried to simulate a mouse click itself. If there was something obscuring the link or similar, that might not work. That should no longer ever happen, since Firefox 101 and later now allows NVDA to programmatically click anything without NVDA falling back to simulating a mouse click. See https://bugzilla.mozilla.org/show_bug.cgi?id=1395181.

If no one can still reproduce this, I would suggest it be closed.

**Comment by seanbudd** [comment] 2023-06-13 02:52
Closing as fixed. Please let us know if it is still an issue and we will reopen it.

**Closed by seanbudd** 2023-06-13 02:52 UTC
Labels: p2, app/firefox, triaged
