### ISSUE TITLE
NVDA send two dots instead of one to synthesizer

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#11175] opened 2020-05-18 14:17 UTC
### Steps to reproduce:
Open window "Symbol pronunciation". For "." set parameter "send actual symbol to synthesizer" = always. Read sentence "translate.google.com"
### Actual behavior:
nvda read "translate.google.com" as "translate dot dot google d o t dot com". NVDA read first dot two times. NVDA read second dot two times too, but first time spell by letter.
### Expected behavior:
nvda should read "translate.google.com" as "translate dot google dot com"
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2020.1
#### Windows version:
Windows 10 Version 10.0.18363 Build 18363
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by fisher729** [comment] 2020-05-18 16:28
Hi.

Did you set both dot symbols (.) including the sentence ending punctuation, present in the Symbol Pronunciation dialog to always be processed by the synthesizer? I feel this occurs because you've only configured one of them to do so.

**Comment by AlexeyCAT** [comment] 2020-05-18 16:49
Hi! Download NVDA 2020.1. Install it as portable in new fresh folder. Run nvda from this folder. Open window "Symbol pronunciation". For "." set parameter "send actual symbol to synthesizer" = always. Dont't do anything else. And you will see how nvda read every dot twice. I dont't touch ". sentence ending".

**Comment by fisher729** [comment] 2020-05-18 17:19
Hi. I can confirm that this does occur. However, it most likely occurs because there are two entries in the Symbols dictionary for the dot (.), one for sentence ending and the other for general use. Sentence ending dots are always sent to the synthesizer, and once you set the general dot to be sent to the synthesizer, the result is that NVDA thinks both dots are to be reported.

I honestly do not see a use case for this issue, though. It's not recommended that this be done, and can easily be fixed by the user.

**Comment by AlexeyCAT** [comment] 2020-05-18 17:37
I need this because i read texts where english and russian languages occur simultaneously. RHVoice synthesizer for example can read punctuation in english sentences in english, and in russian sentences in russian without manual switching. But to make it work i need to send actual symbol of dot to synthesizer.

**Comment by Adriani90** [comment] 2020-05-18 20:47
I think this is a problem in the synthesizer, not in Nvda. Can you reproduce this with every synth? I.e. espeak, one core, sapi5 voices, vocalizer etc.
Cc: @ruifontes

**Comment by AlexeyCAT** [comment] 2020-05-19 04:01
Hi! I reproduced this problem now with espeak, rhvoice, one core.

**Comment by fisher729** [comment] 2020-05-20 15:45
Have you tried to set the sentence ending dot (.) to never in the dialog? Try that and report your findings.

**Comment by AlexeyCAT** [comment] 2020-05-20 18:53
fisher729, If i set always for "." and set never for ". sentence ending", then nvda read every dot once. That is good. But nvda doesn't pause after sentences in that case. That is bad.

fisher729, i only now fully understand what you said to me previously. So now i understand why nvda send two dots. But i would prefer that nvda send general dot to synthesizer only when that dot is not sentence ending dot.

**Comment by fisher729** [comment] 2020-05-20 18:59
Hi.

Try setting the dot (not the sentence ending one) to only voice below the
symbol level. Does this help?

**Comment by AlexeyCAT** [comment] 2020-05-21 07:18
fisher729, please tell me needed values in:

1. preferences->settings->speech->Punctuation/symbol level
1. "level" and "send actual symbol" at preferences->punctuation/symbol pronunciation->"."
1. "level" and "send actual symbol" at preferences->punctuation/symbol pronunciation->". sentence ending"

**Comment by Adriani90** [comment] 2024-07-03 09:50
I think this is still reproducible if I am not misunderstanding something here.
cc: @CyrilleB79 can you test as well?

**Comment by CyrilleB79** [comment] 2024-07-03 11:33
Still reproducible, with the following precisions:

I have tried to reproduce, starting `nvda --lang=en -c d:\newFolderThatDoesNotExistYet`, and setting the preserve parameter to "Always" in English, French and Italian for the dot symbol (or its equivalent). I did not change anything for the "end of sentence dot".

The results are as follow for eSpeak and OneCore:
* NVDA speaks only "dot" (OK):
  * eSpeak fr, it
* NVDA speaks "dot dot":
  * OneCore Hazel (en GB), Susan (en GB), George (en GB), Cosimo (it), Elsa (it), Hortense (fr), Paul (fr), Julie (fr)
  * eSpeak: English Great Britain, English America
* NVDA speaks "d o t dot":
  * OneCore Mark (en US), Zira (en US), David (en US)

With detailed logging (speech manager), we can see the actual speech sequence that is actually passed to the synth:
```
DEBUG - speech.manager.SpeechManager._pushNextSpeech (12:46:03.858) - MainThread (8568):
SpeechManager- Synth Gets: [LangChangeCommand ('en_US'), 'translate dot.google dot.com  ', IndexCommand(222)]
```

So the spelling issue is clearly a synth issue and only with OneCore US English voices.

The double speaking issue occurs quite often but not always. The synth is passed the string "dot.com"; whether it pronounces or not the dot symmbol in the middle of this string is really a synth choice only. E.g. it is not pronounced with eSpeak Italian or French (France).

Setting preserve=always, you ask NVDA to pass both "dot" (word) and "." (dot symbol) to the synthesizer. NVDA cannot do anything else.

@ghost NVDA supports language automatic switching in text that are correctly tagged. In this case, you should not modify the configuration at all and NVDA should handle it correctly.
Though, maybe you cannot rely on language tagging in text, either because the text is not correctly tagged (e.g. URLs not tagged in English) or not tagged at all (e.g. text in Notepad). In this case, if I understand correctly, you rely on RHVoice to automatically distinguish English and Russian text. In this case, NVDA should not pass the symbol's name at all to the synth, it should only pass the real symbol.
So for this use case, I'd suggest to set preserve="only below symbol's level" and level=character.

Though, if you wish RHVoice 

@ghost, have I understood correctly your use case? Is the suggested solution working?

**Closed** 2024-07-03 11:37 UTC
