### ISSUE TITLE
There are some inconsistencies with the way braille is represented in NVDA version 2017.3 English US grade 2 tables

### ISSUE THREAD

**Issue by Daredevilsprmcy** [nvaccess/nvda#7525] opened 2017-08-26 05:12 UTC
Using NVDA version 2017.3, go to NVDA key+n, preferences, braille settings, change to your braille display, set output and input as English US Grade 2, press enter.
Open Notepad and type the following on your computer keyboard:
afterlife, boyfriend, boyfriends, girlfriend, and girlfriends.
The text in Notepad shows correct representations of the above words.
However, on the braille display your read all the words incorrectly represented as:
aft(12456)life, boyfri(26)d, boyfri(26)ds, girlfri(26)d, and girlfri(26)ds.
Instead the braille display had to show:
aflife, boyfr, boyfrs, girlfr, and girlfrs.
Furthermore, when you type the above words on your braille display's keyboard, the Notepad shows the misspelled words:
aflife, boyfr, boyfrs, girlfr, and girlfrs.
Surprisingly, the words:
friendship, newsletter, and newsletters are all typed and read correctly throughout.
Lastly, if you change the output and input tables to UEB grade 2, none of the above issues are present. Everything is contracted as should.
Thank you.

**Comment by josephsl** [comment] 2017-08-26 05:30
CC @JCSTeh, @DKager and other braille table experts, as this is something to do with back-translation in en-us-g2.ctb. Thanks.

**Comment by Daredevilsprmcy** [comment] 2017-08-26 06:05
I don’t have their direct e-mail addresses though.

Can you cc this to them yourself.

Thank you.

 

Dmitriy

**Comment by josephsl** [comment] 2017-08-26 06:28
Hi, already done it via at mentions. Thanks.

**Comment by ehollig** [comment] 2017-11-03 18:38
CC @JCSTeh, @DKager, @leonardder and others. As @josephsl pointed out in https://github.com/nvaccess/nvda/issues/7525#issuecomment-325089017, this has to do with back-translation in en-us-g2.ctb.. Does this need to be fixed in Liblouis?

**Comment by Daredevilsprmcy** [comment] 2017-11-04 01:35
No, UEB doesn’t have those problems because it doesn’t have the contraction for o’clock. Problems with translating boyfriend and afterlife is also accurate in UEB grade 2.

Only US grade 2 has those issues. Note, if one uses UK grade 2, everything becomes perfect. o’clock is properly contracted and words like afterlife, girlfriends are contracted the way they should.

 

Dmitriy

**Comment by jcsteh** [comment] 2017-11-04 07:10
Actually, this is related to forward translation, not backward, since the reporter noted typing on the computer keyboard. And yes, any such issues need to be addressed in the liblouis project.

**Comment by Adriani90** [comment] 2019-04-29 15:07
@Daredevilsprmcy could you please give an update on this? Do you still have this problem in NVDA 2019.1.1? If yes, did you already fill and issue agains Liblouis on Github?

**Comment by Daredevilsprmcy** [comment] 2019-06-06 20:53
Hello,

 

I don’t know how to file a proper complaint against LibLouis, but the US Grade 2 errors are still there.

In the newest version of NVDA, they have fixed only the o’clock into o’c as should be.

But for words like girlfriend, girlfriends, boyfriend, boyfriends, and afterlife, the errors are still there.

That said, when you change the input and the output to UK Grade 2, those errors aren’t there.

 

If it’s at all possible, could you send a complaint either the way it should be done properly or on my behalf.

If not, what are the steps to do so.

Sorry for such a long delay; I’ve been sick.

 

Thank you for the work on improving NVDA.

 

Sincerely,

 

Dmitriy

**Comment by Adriani90** [comment] 2020-05-05 20:37
cc: @Andre9642,

**Comment by Andre9642** [comment] 2020-05-06 08:58
I recommend to [open another issue on liblouis repository](https://github.com/liblouis/liblouis/issues/new). Indeed, it's not a bug on NVDA's side.
However, I'm trying to fix it and I can see that it's the same thing for other words beginning by 'after' or ending by 'friend' (e.g.: aftercare, afterlife, aftermath, befriend, ladyfriend, schoolfriend, etc.), is this correct? Sorry, I'm not an English contracted braille expert and I don't know differences between UEB contracted and English US contracted.

**Comment by Adriani90** [comment] 2020-05-06 23:01
I also recommend to open an issue on Liblouis for this, there are certainly native speakers there who can help in solving this. Unfortunately I am not an expert in braille abbreviations at all, apart from some basic knowledge in german.
Let's continue the discussion on Liblouis, in case someone would like to create a new issue there. I am closing this for now, but please comment here with the link to the new issue for reference. Thanks.

**Closed by Adriani90** 2020-05-06 23:01 UTC
Labels: component/braille

**Comment by Daredevilsprmcy** [comment] 2020-06-05 01:35
Hello,

 

As far as I know, Contracted Grade 2 Braille has rules about words like “newslr” to stand for “newsletter.”

So both of our lists of words are interesting because if for “boyfriend” it should be “boyfr,” then for your examples it should also work. For “afterlife” and ”aftermath” absolutely they should work as well.

Another thing I’ve noticed that even in iOS braille tables LibLouis or not, “o’clock” is supposed to be “o’c.” It is when you type in Grade 2 Braille on iOS, but when you read, it is shown incorrectly.

But for some time now, NVDA is showing “o’clock” as “o’c,” so that means that you guys have corrected it.

 

Thank you, stay safe.

 

Dmitriy
