### ISSUE TITLE
Give the user the possibility to manage modifications of input gestures

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#14366] opened 2022-11-12 06:56 UTC
### Is your feature request related to a problem? Please describe.

NVDA allows the user to modify script input gestures: add or remove.
But in the "Input gestures" dialog, these modifications are not identifiable by the user as being his own modifications.
The functionality would consist in allowing the user to find the modifications he has made and to be able to cancel them if necessary.

### Describe the solution you'd like

It would be helpful to be able to filter modified gestures.
It would also be helpful to label gestures 
e.g.

```
(default) NVDA+shift+b (Keyboard, all layouts)
(custom) NVDA+f12 (Keyboard, all layouts)
(custom) NVDA+f11 (Keyboard, Laptop layout)
```

**Comment by ABuffEr** [comment] 2022-11-12 10:56
Hi,
I agree, even if I'm not sure to have understood your solution. But, why don't we introduce labels, instead of duplicating dialogs?
Something like:
(default) NVDA+Shift+b (Keyboard, all layouts)
(disabled) NVDA+f12 (Keyboard, all layouts)
(customized) NVDA+F11 (Keyboard, Laptop layout)
It could be better even for filter feature, I think.

**Comment by paulber19** [comment] 2022-11-12 11:21
Hi Alberto.
Me to, I don't think the dialogue should be doubled either.
If possible, This can be either an option, or a filter in the existing 
"Input gesture" dialog to show only scripts modified by the user.
A label would force the user to go through all the scripts to find the 
ones they modified.
Best regards.

**Comment by seanbudd** [comment] 2022-11-15 02:07
>Me to, I don't think the dialogue should be doubled either.
If possible, This can be either an option, or a filter in the existing
"Input gesture" dialog to show only scripts modified by the user.
A label would force the user to go through all the scripts to find the
ones they modified.

I've updated the issue description to be more reflective of this.

We are happy for this to be worked on.

**Comment by Adriani90** [comment] 2024-03-27 20:49
This is basically a duplicate of #4900. Adding a filter checkbox would already solve this problem, and the need of labeling the gestures can be discussed in #4900.

**Closed by Adriani90** 2024-03-27 20:49 UTC
Labels: close/duplicate, p5, feature, feature/input-gestures, triaged
