### ISSUE TITLE
NVDA threshold_py3_staging-17931 opens NVDA settings and reports errors after using tab browsing

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#9868] opened 2019-07-04 06:08 UTC
In the process of using the NVDA threshold_py3_staging-17931 test, open the NVDA settings and use the tab to browse and report the error.
### Steps to reproduce:
First run NVDA threshold_py3_staging-17931 portable version, then open the NVDA settings tab to browse the settings, this time there will be an error tone
### Actual behavior:
Error sound
### Expected behavior:
An error occurred
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
threshold_py3_staging-17931
#### Windows version:
windows10-1903-10.0.18362.175
#### Name and version of other software in use when reproducing the issue:
threshold_py3_staging-17931
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
NVDA-log:
[nvda.log](https://github.com/nvaccess/nvda/files/3357897/nvda.log)

**Comment by dingpengyu** [comment] 2019-07-04 06:16
The following is the log content:
INFO - __main__ (13:45:14.236):
Starting NVDA
INFO - core.main (13:45:15.173):
Config dir: F:\nvda-py3\userConfig
INFO - config.ConfigManager._loadConfig (13:45:15.173):
Loading config: .\userConfig\nvda.ini
INFO - core.main (13:45:15.529):
NVDA version threshold_py3_staging-17931,5a0fb7f4
INFO - core.main (13:45:15.529):
Using Windows version 10.0.18362 workstation
INFO - core.main (13:45:15.529):
Using Python version 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
INFO - core.main (13:45:15.530):
Using comtypes version 1.1.7
INFO - core.main (13:45:15.530):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (13:45:16.019):
Loaded synthDriver oneCore
INFO - core.main (13:45:16.019):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5 with six version 1.12.0
INFO - brailleInput.initialize (13:45:16.021):
Braille input initialized
INFO - braille.initialize (13:45:16.021):
Using liblouis version 3.10.0
INFO - braille.initialize (13:45:16.024):
Using pySerial version 3.4
INFO - braille.BrailleHandler.setDisplayByName (13:45:16.028):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (13:45:16.131):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (13:45:16.144):
UIAutomation: IUIAutomation6
INFO - core.main (13:45:16.487):
NVDA initialized
ERROR - unhandled exception (13:45:44.194):
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 155, in call_without_this
  File "comtypes\automation.pyc", line 575, in __setitem__
  File "comtypesMonkeyPatches.pyc", line 64, in newVARIANT_value_fset
  File "comtypes\automation.pyc", line 218, in _set_value
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2147352568] 不正确的变量类型。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "comtypes\_comobject.pyc", line 51, in winerror
TypeError: 'OSError' object is not subscriptable
ERROR - unhandled exception (13:45:57.496):
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 155, in call_without_this
  File "comtypes\automation.pyc", line 575, in __setitem__
  File "comtypesMonkeyPatches.pyc", line 64, in newVARIANT_value_fset
  File "comtypes\automation.pyc", line 218, in _set_value
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2147352568] 不正确的变量类型。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "comtypes\_comobject.pyc", line 51, in winerror
TypeError: 'OSError' object is not subscriptable
ERROR - unhandled exception (13:46:05.770):
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 155, in call_without_this
  File "comtypes\automation.pyc", line 575, in __setitem__
  File "comtypesMonkeyPatches.pyc", line 64, in newVARIANT_value_fset
  File "comtypes\automation.pyc", line 218, in _set_value
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2147352568] 不正确的变量类型。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "comtypes\_comobject.pyc", line 51, in winerror
TypeError: 'OSError' object is not subscriptable
ERROR - unhandled exception (13:46:09.870):
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 155, in call_without_this
  File "comtypes\automation.pyc", line 575, in __setitem__
  File "comtypesMonkeyPatches.pyc", line 64, in newVARIANT_value_fset
  File "comtypes\automation.pyc", line 218, in _set_value
  File "_ctypes/callproc.c", line 933, in GetResult
OSError: [WinError -2147352568] 不正确的变量类型。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 232, in 'calling callback function'
  File "comtypes\_comobject.pyc", line 176, in call_without_this
  File "comtypes\_comobject.pyc", line 51, in winerror
TypeError: 'OSError' object is not subscriptable

**Comment by leonardder** [comment] 2019-07-04 06:19
Duplicate of #9768

**Closed by leonardder** 2019-07-04 06:19 UTC

**Comment by josephsl** [comment] 2019-07-04 06:21
Hi,

Closing as duplicate of #9768.

Thanks.
