### ISSUE TITLE
Chrome sign in dialog is totally inaccessible.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5838] opened 2016-03-29 00:15 UTC
I don't know who to report this to, but, in both chrome canary and stable, with NVDA Next, if you go to settings>sign iin, and then try to sign in, it fails. NVDA reports an embeded object and that's all besides sometimes one unlabeled button.

**Comment by jcsteh** [comment] 2016-03-29 01:42
Duplicate of #5512 (which is just tracking [Chromium issue 589325](https://bugs.chromium.org/p/chromium/issues/detail?id=589325)).

**Closed by jcsteh** 2016-03-29 01:42 UTC
Labels: duplicate
