### ISSUE TITLE
Add-on store, Updatable add-ons show add-ons which you installled and don't require an update

### ISSUE THREAD

**Issue by mohammedradwan2003** [nvaccess/nvda#15935] opened 2023-12-18 14:01 UTC
### Steps to reproduce:
1 - Download and install some add-ons from the store.
2 - Go to the add-on store and updatable add-ons. Make sure you have the latest versions.

### Actual behavior:

 You'll see the add-ons which you installed with their current versions that you have and latest versions which are the same as what you have and then NVDA will say that they're updatable or have a latest update or something along these lines when they actually don't.

### Expected behavior:

These add-ons shouldn't show up at all.

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2024.1 beta1
#### Windows version:
&Windows 11 latest insider version.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
It has been occurring since the add-on store existed. It is one reason I kept on using the add-on updater for sometime.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by josephsl** [comment] 2023-12-18 14:07
Hi,

I think I know why, but just to make sure:

* Which add-ons are exhibiting this problem?
* Which versions of add-ons did you install?

Thanks.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:03
Hey.
 I thought i replied. Turns out that no, I didn't, oopse.
Here's the  reply:
If I installed them from the store with their latest versions, This will probably happen.
Here is a list of add-ons which show this.
Clip contents designer.
Emodicons.
Instant translate.
Outlook extended.
Resource monitor.
Sound splitter.
Unigram plus.
Update channel selector.
Tony's enhancements.
Tesract OCR.
URL shortener.
Windows App Essentials.

**Comment by josephsl** [comment] 2023-12-18 20:09
Hi,

Did you:

* Select "all" from channels list? If yes, updatable add-ons list will show updates across stable, eta, and dev channels.
* Ask NVDA to include incompatible add-ons? If yes, it will show all available updates even if new updates are incompatible with the NVDA version you've got.

I can speak for two of these add-ons: Resource Monitor and Windows App Essentials. Both add-ons do have dev channel builds registered on the ad-on store, so if update channel is set to "all", updates coming from channels other than stable channel will be shown.

Thanks.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:11
Yes and Yes. What strikes me though is that it shows the latest version as the version which I already own.

**Comment by josephsl** [comment] 2023-12-18 20:13
Hi,

Did you download these add-ons via the add-on store and not from places like community add-ons website or through Add-on Updater? If so, try installing al available add-on updates, restart NVDA, and see if the add-on store no longer shows updates.

Thanks.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:23
Alrighty.
I tried but with the combobox on  stable version and with the incompatible checked.
7 Add-ons updated and 5 failed to open their updated file according to nvda.
I no longer get the updatable thing for these 7 add-ons again.

**Comment by josephsl** [comment] 2023-12-18 20:28
Hi,

This points to store json file storage issue. When add-ons are downloaded and installed from add-on store directly, json files are created to report latest add-on releases to NVDA. However, when add-ons are installed from external sources (including Add-on Updater), json files are not created.

CC @SeanBudd in case we need to update the version detection logic in 2024.1 beta and/or 2024.2.

Thanks.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:31
I have right now tried updating  the add'ons again but to development versions, I had 13 updates. 3 worked and 10 failed to open.
I think something that I might try is to remove, and reinstall, these add'ons again.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:50
Yup. Totally what I expected. I faced the same issue.
Totally unrelated, but add-ons couldn't be removed when I selected them in bulk. I had to remove them one by one.

**Comment by josephsl** [comment] 2023-12-18 20:52
CC @CyrilleB79 as it seems to be related to #15921 regression (at least to me).

**Comment by josephsl** [comment] 2023-12-18 20:53
Hi,

For bulk removals, you must be in "instaled add-ons" tab, select add-ons to be removed, then select "remove" from the context menu.

Thanks.

**Comment by mohammedradwan2003** [comment] 2023-12-18 20:54
It is what I did.
Here's a list of affected add-ons  which I couldn't update.
Add-ons documentation.
Clip contents designer.
Custom notifications.
Dropbox.
Emodicons.
Mozilla apps enhancements.
resource monitor.
say product name and version.
sys tray list.
tesract OCR, Though for honesty, This add-on doesn't download at all. It says pending download and never finishes downloading.

**Comment by CyrilleB79** [comment] 2023-12-18 21:28
> CC @CyrilleB79 as it seems to be related to #15921 regression (at least to me).

#15921 has been written by @seanbudd. Did you mean another PR for CCing me instead?

**Comment by josephsl** [comment] 2023-12-18 21:35
Hi, yep – I may have confused between that and another PR. Thanks.

**Comment by seanbudd** [comment] 2023-12-18 22:40
Welcome @mohammedradwan2003 ,

We are unable to process this issue as it stands.

- Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
- Please provide clearer steps to reproduce. It should look something like:

1. Install add-on emoticons version 1.5 using external install
2. Restart NVDA
3. Go to updatable tab, note that emoticons 1.5 is displayed in the updatable tab

Is this the correct steps to reproduce?

Kind Regards,
NV Access Software Developers

**Comment by mohammedradwan2003** [comment] 2023-12-19 07:56
Hello.
I can no longer reproduce as unfortunately as these add-ons somehow no longer open after I uninstalled and attempted  to reinstall them.
It brings me that the file in updata is unable to open.

**Comment by seanbudd** [comment] 2023-12-19 23:23
Are you saying that a new issue is occurring?
Could you please be more descriptive on how to reproduce the new issue?

I'm thinking this might be fixed in #15937 which will be released in 2024.1beta2.

**Comment by wmhn1872265132** [comment] 2023-12-20 04:55
This issue was tested and reproduced in alpha-30354,72e65dbd (2024.2.0.30354)
This issue is more complicated to reproduce by following the complete reproduction steps:
1. Install any Add-on from the Add-on Store
2. Update the Add-on through external means
3. Upload the same Add-on version updated from external sources to the Add-on Store
4. Check Add-on updates in Add-on Store
Simplified steps to reproduce:
1. Install any Add-on from the Add-on Store
2. Restart NVDA
3. Edit the "addonVersionNumber" of %appdata%\NVDA\addons\Add-on name.json and modify its version to be lower than the actual version of the Add-on.
4. Restart NVDA and check Add-on updates in the Add-on Store
actual behavior
The Add-on will show that there is an update for the Add-on, and the version number is the same as the installed version.
expected behavior
There is no update for this Add-on

**Comment by seanbudd** [comment] 2024-01-11 03:55
@wmhn1872265132 I could not reproduce this with NVDA 2023.3beta3. Can you confirm which add-on name and version you can reproduce this with using the add-on store?

**Comment by seanbudd** [comment] 2024-01-11 03:56
@mohammedradwan2003 - can you please explain what issues you are still having with 2023.3beta3?

**Comment by wmhn1872265132** [comment] 2024-01-11 07:04
It can be reproduced using any Add-ons. The Add-on I am currently using to reproduce this issue is Windows App Essentials version 24.01.23.

**Comment by wmhn1872265132** [comment] 2024-01-11 08:03
After my careful testing, the problem seems to be with the Add-on Updater.
The Add-on updated through the Add-on Updater does not delete the JSON file of the Add-on, causing this problem to occur.
When installing the Add-on via an external channel, NVDA deletes the JSON file, so the issue cannot be reproduced, but the manual reproduction steps I reported are still available.

**Comment by CyrilleB79** [comment] 2024-01-11 09:12
> After my careful testing, the problem seems to be with the Add-on Updater. The Add-on updated through the Add-on Updater does not delete the JSON file of the Add-on, causing this problem to occur. When installing the Add-on via an external channel, NVDA deletes the JSON file, so the issue cannot be reproduced,

Cc @XLTechie and @josephsl: for a bugfix in Add-on Updater.

Also cc @hxebolax in case [Tienda](https://github.com/hxebolax/Tienda-para-NVDA) is also causing this issue.

> but the manual reproduction steps I reported are still available.

What do you call "manual reproduction steps"?
Is it "Simplified steps to reproduce:" in https://github.com/nvaccess/nvda/issues/15935#issuecomment-1863843703? If yes, this STR is not valid since:
1. You are not meant to modify manually the config files of NVDA
2. There is no equivalent STR using only the GUI that would lead to a version number differing between the manifest and the Json (without Add-on Updater bug of course)

**Comment by hxebolax** [comment] 2024-01-11 12:11
Good day, in the latest version 0.9.2 of the store.es just released, I have added the removal of the control JSON when updating add-ons from store.es.
Now the add-ons updated from store.es will be external.
Regards.

**Comment by XLTechie** [comment] 2024-01-11 13:26
Thanks @CyrilleB79. I will see about releasing a fix on Saturday.

**Comment by josephsl** [comment] 2024-01-11 14:15
Hi, as part of the release, do remove the legacy declaration on Add-on Updater (at least in code). Also, keep in mind that Windows App Essentials uses higher build numbers for dev channel releases, so update availability will persist even after installing latest beta channel release. Thanks.

**Comment by seanbudd** [comment] 2024-01-11 22:30
Closing this issue as it cannot be reproduced without an add-on

**Closed** 2024-01-11 22:30 UTC
Labels: p3, blocked/needs-info, triaged, feature/addon-store

**Comment by CyrilleB79** [comment] 2024-03-21 10:22
@XLTechie or @josephsl, has Add-on Updater been fixed for this issue? I cannot see anything in the change log regarding such a fix. And this issue is still being discussed [here](https://nvda.groups.io/g/nvda/topic/105047903?p=Created,,,100,1,0,0::recentpostdate/sticky,,,100,2,0,105047903,previd=1711010542371323549,nextid=1707979847061409013).

**Comment by XLTechie** [comment] 2024-03-21 11:48
There is a dev version in the store now (24.2.501), which is testing a fix for 
this.

I am waiting for more updates to come along to be sure it works as expected, but 
it appears to from my limited experimenting so far.

https://github.com/josephsl/addonUpdater/releases/download/v24.2.501-dev/addonUpdater-24.2.501.nvda-addon

**Comment by XLTechie** [comment] 2024-03-21 13:24
> Since people will update add-ons massively in the next few days, it would be worth to release the stable version IMO.

Yes, already did. 24.2.1 is in the store now. I was able to test with a live 
add-on that somebody updated, and it appears to act correctly.
