### ISSUE TITLE
speech viewer does not open on nvda last alpha 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13139] opened 2021-12-06 22:28 UTC
### Steps to reproduce:
go to nvda's tools menu, and press enter on
speech viewer 
### Actual behavior:
speech viewer does not open 
### Expected behavior:
the speech viewer should open 
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-24318,a674652b

#### Windows version:
11 22.000.348
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log:
[viwer.txt](https://github.com/nvaccess/nvda/files/7663952/viwer.txt)

**Comment by CyrilleB79** [comment] 2021-12-07 09:07
Hello Fernando

It seems that there is an issue in the following config file defining your Chrome profile
`C:\Users\ferna\AppData\Roaming\nvda\profiles\chrome.ini`
i.e. some information definning the position of your speech viewer is saved in the config (x, y, width, height) and some other not (displays).

Here are some questions to confirm the nature of this issue and to help understand how it could have occurred:
* Did you by chance edit this file manually?
* Did you change display settings (screen resolution, usage of 2 screens or usage of a docking station, switching from desktop monitor to laptop screen)
* Could you test with last stable NVDA version? I expect that the issue is also present (Note, you should do the test when the Chrome window is opened as you did before) and if you are using a portable version (in case the alpha is already installed on your machine) you should launch NVDA with your config, i.e.:
  `path\to\portable\nvda.exe -c C:\Users\ferna\AppData\Roaming\nvda`

Since the issue is in the Chrome profile, you can solve the issue by deleting the Chrome profile and re-creating it again from scratch.

Depending on how you have reached this situation, it could also be interesting to make this part of code more robust.

**Comment by fernando-jose-silva** [comment] 2021-12-07 15:02
Thank you very much
@CyrilleB79 
as for your question:
• Did you happen to edit this file manually?
not.
• You have changed the display settings (screen resolution, using 2 screens or using a docking station, switching from desktop monitor to laptop screen)
neither
can any software change this, I remembered that I installed an app
Live Tiles Anywhere - Customize and widgetize your Live Tiles
from the microsoft store, after i unchecked it to not start with windows more i believe i had not restarted my system since then.
Since the issue is with the Chrome profile, you can resolve it by deleting the Chrome profile and recreating it from scratch.
perfect deletes the chrome profile and everything worked perfectly.
• Could you test with the latest stable version of NVDA? I hope the problem is also present
I did the test and the problem did not occur in this version
nvda 2021.2
But I don't believe in nvda regression, I believe that something in my system was not working correctly, maybe because of the mysteries that we will never be able to discover the reason.
Depending on how you've reached this situation, you might also want to make this piece of code more robust.
Thank you very much, I believe I didn't understand how I got to this situation either, but now everything works fine excluding the chrome profile.
Thank you for your attention.

**Comment by CyrilleB79** [comment] 2021-12-08 08:15
OK thanks.
Let us know if this issue happens again so that we can try to investigate why this unforeseen situation has occurred.

Another question: did you ever move the speech viewer window? E.g. with the mouse (most common) or with the keyboard.

**Comment by fernando-jose-silva** [comment] 2021-12-08 21:53
yes inform.
 He never hears the window, neither with the mouse nor with the keyboard.
 At least not wanting to, because when I find some inaccessible software, I try to see if I can work with it by moving the mouse, maybe at some point I might have moved or clicked on something that made the window move, I don't know if that's so easy too thus.
 Anyway, on my own volition, I never moved the window, neither using the mouse nor using another keyboard.
 Thank you very much.

**Comment by XLTechie** [comment] 2022-04-30 05:00
@fernando-jose-silva should this still be open? Please close it if it has been resolved as it seems.

**Closed** 2022-04-30 14:51 UTC
