### ISSUE TITLE
Previous or next sentence don't work in some applications

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#5904] opened 2016-04-27 17:40 UTC
This function does not work in browsers, some texte editors like Notepad++, Writer from OpenOffice or LibreOffice.
Pressing alt+downarrow or alt+uparrow does nothing in those applications.

**Comment by derekriemer** [comment] 2016-04-27 18:16
Correct. This only works in word. I don't know, it might be nice to fix 
this in a browser. In something like notepad++ it may or may not make 
sense, although I don't see why putting it into core should be a problem.


On 4/27/2016 11:40 AM, MichelSuch wrote:
>
> This function does not work in browsers, some texte editors like 
> Notepad++, Writer from OpenOffice or LibreOffice.
> Pressing alt+downarrow or alt+uparrow does nothing in those applications.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5904>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment] 2016-04-27 23:17
These applications either don't have a concept of sentences or don't expose it to accessibility APIs. NVDA depends on this to support sentence navigation. Even if NVDA could detect sentences itself, this would cause performance problems and there's also no reliable way to jump to arbitrary points in the text in most cases.

That said, LibreOffice Writer needs further investigation, since it should have a concept of sentences internally and it'd make sense for it to expose this to accessibility if it doesn't already.

**Comment by derekriemer** [comment] 2016-04-28 01:34
Oh. I figured NVDA parsed this internally.


On 4/27/2016 5:17 PM, James Teh wrote:
>
> These applications either don't have a concept of sentences or don't 
> expose it to accessibility APIs. NVDA depends on this to support 
> sentence navigation. Even if NVDA could detect sentences itself, this 
> would cause performance problems and there's also no reliable way to 
> jump to arbitrary points in the text in most cases.
>
> That said, LibreOffice Writer needs further investigation, since it 
> should have a concept of sentences internally and it'd make sense for 
> it to expose this to accessibility if it doesn't already.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/5904#issuecomment-215261103>
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by jcsteh** [comment] 2017-08-14 04:30
Closing as a duplicate of #1873. In particular, see https://github.com/nvaccess/nvda/issues/1873#issuecomment-322097839.

**Closed** 2017-08-14 04:30 UTC
Labels: duplicate
