### ISSUE TITLE
Word 365: incorrect extra information read when selecting a recent document to open

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#8987] opened 2018-11-27 23:37 UTC
### Steps to reproduce:

There are two ways to reproduce this which I believe are related:
A) From the start screen:
1) Open Word and wait for the start screen to appear.
2) Press TAB twice to move to the "Recent" heading.

B) Using the Open task pane:
1) From within Word, press CONTROL+O to bring up the Open task pane.
2) Press TAB to move to the "Documents" heading in "recents".

### Actual behavior:

For task A) NVDA reads: "Open  grouping  You haven't opened any documents recently. Click Open to browse for a document."

For task B) NVDA reads: "
Recent Documents  grouping  You haven't opened any documents recently. Pick a place to browse for a document."

These messages are read even though there are recent documents which can be accessed by pressing TAB one more time.

### Expected behavior:

As long as there are recent documents which are listed in the task pane, the message about not having opened any documents recently should not be read.  It does not appear visually on screen, or happen when using Narrator.

#### NVDA Installed/portable/running from source:
Installed
#### NVDA version:
2018.4beta2
#### Windows version:
Windows 10 insider build 18272.1000 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.11001.20093 

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
NVDA 2018.3.2
NVDA 2018.2.1

**Comment by michaelDCurran** [comment] 2018-11-28 03:09
In both cases there is a grouping control exposed by UI Automation, with a helpText property of "You haven't opened any documents recently. Pick a place to browse for a document.". NVDA always maps the UIA helpText property to an NVDAObject's description poroperty, and therefore it gets announced as the control's description.
Microsoft should remove this text from the UIA helpText property when there are recent documents.
The reason Narrator does not announce this is because it does not  fetch the UIA helpText property for focus ancestors. If that grouping was to actually get focus itself, Narrator would announce it, after a small delay, like it does other descriptions.
The UIA element in question has a controlType of grouping, and a UIA className of NetUISlabContainer.

**Comment by Adriani90** [comment] 2024-06-08 13:27
This is not reproducible anymore with NVDA 2024.2 Beta and Microsoft 365 MSO (Version 2405 Build 16.0.17628.20006) 64 Bit

I am closing as works for me. If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2024-06-08 13:27 UTC
Labels: close/worksforme, blocked/needs-external-fix
