### ISSUE TITLE
a page that freezes nvda 2018.2.1 in microsoft edge

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#8468] opened 2018-06-30 12:21 UTC
### Steps to reproduce:
1. open edge.
2. go to https://www.pontosmultiplus.com.br
3. after the page load, press arrowdown to read the page. the freeze occur after nvda find a edit control

### Actual behavior:
nvda stop speak and I have to close edge with ctrl + f4.
I confirm it is a nvda's problem because I opened the same page with narrator and it read the page.
### Expected behavior:
nvda should read the page
### System configuration:
windows10 64 bits
#### NVDA Installed/portable/running from source:
nvda installed
#### NVDA version:
2018.2.1
#### Name and version of other software in use when reproducing the issue:
microsoft edge

**Comment by amirsol81** [comment] 2018-06-30 14:29
I can duplicate this. However, here I don't need to close Edge to regain speech. Once I press the Up arrow key a couple of times, or Control+Home or Control+End once, or, say, Windows+M to move to the Desktop NVDA resumes speech. This seems to be the LogIn graphical link which forces NVDA to get stuck in Edge. This is on a 64-Bit Win 10 Pro and NVDA 2018.2.1.

**Comment by Adriani90** [comment] 2020-04-21 22:07
I cannot reproduce this in Edge Chromium 81. I am closing this as works for me since Edge Chromium will be distributed to most users through Windows 10 20 H1 update.
Please comment on it if you can reproduce it in Edge Chromium, then we can reopen it. Thanks.

**Closed by Adriani90** 2020-04-21 22:07 UTC
Labels: close/worksforme

**Comment by Adriani90** [comment] 2020-04-30 20:52
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
