### ISSUE TITLE
After updating an Add-on that does not meet the system requirements, the old version of the Add-on is lost

### ISSUE THREAD

**Issue by wmhn1872265132** [nvaccess/nvda#16702] opened 2024-06-16 12:23 UTC
### Steps to reproduce:
1. Start NVDA on Windows 10 Version 21H2 and install the following Add-on
https://github.com/kefaslungu/resourceMonitor/releases/download/23.06/resourceMonitor-23.06.nvda-addon
2. Restart NVDA and update the Add-on through the store
3. During installation, it prompts that the system does not meet the requirements.
4. Restart NVDA

### Actual behavior:

The old version of Add-on is lost, and the `resourceMonitor.json` file appears in the `%appdata%\NVDA\addons` folder

### Expected behavior:

The old version of Add-on is retained and the `resourceMonitor.json` file should not be generated

### NVDA logs, crash dumps and other attachments:
none

#### NVDA installed/portable/running from source:
installed

#### NVDA version:
2024.2beta3(2024.2.0.32151)

#### Windows version:
Windows 10 21H2 (AMD64) build 19044.4412

#### Name and version of other software in use when reproducing the issue:
none

#### Other information about your system:
none

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not tested

#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested

**Comment by josephsl** [comment] 2024-06-16 14:57
Hi,

I think this extends to any add-on that raises exceptions in the end, and Resource Monitor is one of those. If yes, I think we may have a record of this issue somewhere.

Thanks.

**Comment by josephsl** [comment] 2024-06-16 15:22
Hi,

Also, could you mind testing the issue with latest alpha release to make sure the issue can be reproduced across NVDA releases?

Thanks.

**Comment by josephsl** [comment] 2024-06-16 15:39
Hi,

Turns out this issue is reproducible in alpha builds as well and occurs whenever add-on install routine raises exceptions (tested with a modified Windows App Essentials bundle with installTasks.onInstall function that does nothing but raises RuntimeError exception). I propose creating a more general issue or changing the scope of this problem to cover other cases.

Thanks.

**Comment by josephsl** [comment] 2024-06-16 16:21
Hi,

Closing in favor of #16704 as that issue addresses the root cause of this problem. Thanks.

**Closed by josephsl** 2024-06-16 16:21 UTC
