### ISSUE TITLE
A link on an image map brings user to the last text link out of the map.

### ISSUE THREAD

**Issue by Dragonium** [nvaccess/nvda#5496] opened 2015-11-14 17:02 UTC
_Tested under Firefox._

**Problem :**
When you have text links before an image on which several areas are active with the `<map>` tag, you cannot follow the links on the active zones of the picture.

**How to reproduce this bug :**
With the TAB key, jump from link to link in the page, until you select the [1] or the [2] active zone on the picture.
Then, press ENTER.
The selected area will jump back to the last text link before the picture and will open it, instead of the link you have chosen.

**Test page :** http://www.dragonium.net/bugnvda/

**Source code :**

``` HTML
<html>
<body>
<a href="http://www.google.com">Google</a><br>
<a href="http://www.wikipedia.fr">Wikipedia</a><br>
<img src="http://www.dragonium.net/bugnvda/image.jpg" usemap="#liens" border="0" height="50" width="233" alt="This is a picture with 2 links on it" title="This is a picture with 2 links on it"><br>
<map name="liens">
  <area shape='rect' coords='50,11,81,37' href='http://www.yahoo.com' alt="Yahoo" title="Yahoo">
  <area shape='rect' coords='151,11,182,37' href='http://www.duckduckgo.com' alt="Duckduckgo" title="Duckduckgo">
  <area shape="default" nohref alt="This area has no link." title="This area has no link.">
</map>
</body>
</html>
```

**Comment by leonardder** [comment] 2017-07-17 14:00
@Dragonium: Could you please reupload this file or add is as an attachment to this issue?

**Comment by ehollig** [comment] 2018-10-25 23:48
@leonardder attached is the HTML file from the code provided in the original description. If I tab from link to link and activate one of the links in the image map, it opens the corresponding website. I am not able to reproduce this issue using alpha-16188.
[issue5496.html.txt](https://github.com/nvaccess/nvda/files/2517123/issue5496.html.txt)

**Comment by Adriani90** [comment] 2019-02-02 13:07
Tested with NVDA Alpha 16691,10590C87 and Firefox 65, I cannot reproduce it either. Closing as works for me.

**Closed** 2019-02-02 13:07 UTC
Labels: worksforme
