### ISSUE TITLE
The keystroke to read sentence by sentence (alt+down arrow or alt+up arrow does not work in browse mode in microsoft-word, HTML documents, PDF Documents, and websites

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#12029] opened 2021-02-04 02:39 UTC
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Actual behavior:
When using NVDA, the keystroke to read sentence by sentence (alt+down arrow or alt+up arrow does not work in browse mode in microsoft-word, HTML documents, PDF Documents, and websites
### Expected behavior:
because the keystroke to read sentence by sentence (alt+down arrow or alt+up arrow is working in focus mode in microsoft-word, it is expected to work in browse mode in microsoft-word, HTML documents, PDF Documents, and websites
#### NVDA installed/portable/running from source:
NVDA installer
#### NVDA version:
NVDA 2020.4 Beta 4
#### Windows version:
Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)

#### Name and version of other software in use when reproducing the issue:
Microsoft-word office 2019
Google Chrome Version 88.0.4324.104 (Official Build) (64-bit)
Microsoft Edge Version 88.0.705.56 (Official build) (64-bit)
#### Other information about your system:
Machine name: DESKTOP-JJC96NM
               Machine Id: {7DF14EB0-F3A0-49E1-A882-0E29E93F09A1}
Language: English (Regional Setting: English)
System Manufacturer: HP
System Model: HP ENVY x360 Convertible 15-cn0xxx
BIOS: InsydeH2O Version 05.12.09F.22 (type: BIOS)
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
Memory: 16384MB RAM
Available OS Memory: 16218MB RAM         
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, but the behaviour remain the same
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes, but the behaviour remain the same

**Comment by mltony** [comment] 2021-02-28 05:52
In nVDA sentence navigation is only implemented in Microsoft Word focus mode, so that's expected. If you wish to try sentence navigation in other apps, try my SentenceNav add-on:
https://github.com/mltony/nvda-sentence-nav/

**Comment by CyrilleB79** [comment] 2021-02-28 20:20
This seems to me a duplicate of #8518.
@jacobchawala if you confirm this, please close this ticket as duplicate.

**Comment by Adriani90** [comment] 2023-04-04 23:08
Closing as duplicate of #8518.

**Closed by Adriani90** 2023-04-04 23:08 UTC
Labels: close/duplicate
