### ISSUE TITLE
NVDA becomes unresponsive while switching keyboard layouts with windows+space and windows+shift+space

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11917] opened 2020-12-08 12:18 UTC
### Steps to reproduce:
1. press windows spacek or windows+sh'ft+space to switch between keyboard layouts
2. You will notice that NVDA won't interrupt speech before telling the next or previous layout if you press the keystroke twice or thrice quickly
### Actual behavior:
NVDA does not interrupt speech when you press windows+space or windows+shift+space twice or thrice quickly
### Expected behavior:
NVDA should interrupt saying the first layout and should tell the second layout immediately 
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
windows 10 1909&2004
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Adriani90** [comment] 2023-09-16 19:28
@fatihyuksek1 are you still able to reproduce this issue in NVDA 2023.2?

**Comment by fatihyuksek1** [comment] 2023-09-17 11:31
No, I'm not experiencing this issue anymore, however I'm experiencing a similar issue with windows 11:
1. press win+space
2. NVDA will say "list of language changers" or a similar thing when trying to switch keyboards with win+space.
3.

**Comment by Adriani90** [comment] 2023-09-17 11:59
This is expected and it is given by the new design in Windows. Either you wait until you hear the list with languages appearing and then continue pressing windows+space, or you press and release windows+space quickly. In both cases NVDA reports the current keyboard language as it changes. Thanks for reporting, closing as works for me.

**Closed by Adriani90** 2023-09-17 11:59 UTC
Labels: close/worksforme
