### ISSUE TITLE
Outlook 2016: Settings button or menu under the info tab is misidentified

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6858] opened 2017-02-08 15:26 UTC
See pasted log below to see the problem.
STR:
1 Open Outlook
2 press alt+f to enter the file tab
3. Press i to enter the info tab
4 Press s to get to the account settings item.

IO - inputCore.InputManager.executeGesture (10:11:27):
Input: kb(laptop):alt+f
IO - inputCore.InputManager.executeGesture (10:11:29):
Input: kb(laptop):i
IO - speech.speak (10:11:30):
Speaking [LangChangeCommand ('en'), u'Info  tab  selected  Info  Alt, F, I']
IO - inputCore.InputManager.executeGesture (10:11:30):
Input: kb(laptop):s
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:11:30):
oleacc.AccessibleObjectFromEvent with window 6165388, objectID 72726 and childID 0: [Error -2147467259] Unspecified error
IO - speech.speak (10:11:30):
Speaking [LangChangeCommand ('en'), u'menu']
DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (10:11:30):
oleacc.AccessibleObjectFromEvent with window 6165388, objectID 72727 and childID 0: [Error -2147467259] Unspecified error
IO - speech.speak (10:11:30):
Speaking [LangChangeCommand ('en'), u'menu']
IO - speech.speak (10:11:30):
Speaking [LangChangeCommand ('en'), u'menu']
IO - inputCore.InputManager.executeGesture (10:11:59):
Input: kb(laptop):shift+NVDA+rightArrow
IO - speech.speak (10:11:59):
Speaking [LangChangeCommand ('en'), u'Minimize  button  Moves the window out of the way']
IO - inputCore.InputManager.executeGesture (10:12:00):
Input: kb(laptop):shift+NVDA+leftArrow
IO - speech.speak (10:12:00):
Speaking [LangChangeCommand ('en'), u'menu']
IO - inputCore.InputManager.executeGesture (10:12:02):
Input: kb(laptop):shift+NVDA+downArrow
IO - speech.speak (10:12:02):
Speaking [LangChangeCommand ('en'), u'No objects inside']

**Comment by dkager** [comment] 2017-02-09 15:28
Interesting, with speech turned off (braille only) this doesn't happen and I see "Account settings..."

**Comment by PratikP1** [comment] 2017-02-09 18:50
When the user lands on that button while tabbing, the account settings button is identified. But, when pressing enter/space bar, the unidentified menu pops up.

**Comment by Adriani90** [comment] 2019-04-01 18:01
This is not reproducible anymore in NVDA 2019.1 and Outlook 2016. @PratikP1, @dkager can you also confirm? If yes, we should close this as works for me.
I tested as follows:
1. Open Outlook
2. Open the file ribbon
3. Navigate with arrow keys to "information"
4. Navigate with tab to "account settings"
Actual: NVDA reports "Acount settings colapsed" which is also expected. Pressing space bar on it opens the menu.

**Comment by dkager** [comment] 2019-04-01 18:12
Yes, works for me.

**Closed by dkager** 2019-04-01 18:12 UTC
Labels: Microsoft Office support
