### ISSUE TITLE
NVDA reads list item twice on chrome

### ISSUE THREAD

**Issue by pidixit** [nvaccess/nvda#9653] opened 2019-05-31 11:12 UTC
### Steps to reproduce:
Following is the html snippet which is causing the issue:
```
	<ul>
		<li style="display:flex">
			<input type="checkbox" id="abc1" />
			<label for="abc1" style="overflow: hidden;">Hello1</label>
		</li>
		<li style="display:flex">
			<input type="checkbox" id="abc2" />
			<label for="abc2">Hello2</label>
		</li>
	</ul>
```

Start NVDA and navigate through the list.

### Actual behavior:

Following is the Speech viewer output while running on Chrome (Version 74.0.3729.169 (Official Build) (64-bit)):

```
list  with 2 items
Hello1
Hello1  check box  not checked
Hello2
check box  not checked

```
Here, the list item is read twice for item "Hello1".

Analysis:
This behavior seems to be related to combination of styles **"display:flex" on li tag** and **"overflow: hidden;" on label tag**. 
If list item has this combination then item is read twice. Otherwise it is working fine as seen with second list item "Hello2".

Additionally, this issue is not occurring in Firefox (Verified on version 67.0 (32-bit)). Following is the speech viewer output on Firefox:

```
list  with 2 items
Hello1  check box  not checked
Hello2  check box  not checked
```

### Expected behavior:

Ideally list item name should be read only once.

#### NVDA installed/portable/running from source:
NVDA installed 

#### NVDA version:
2019.1.1

#### Windows version:
Windows 10 

#### Name and version of other software in use when reproducing the issue:
N/A

#### Other information about your system:
N/A

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by DrSooom** [comment] 2019-05-31 18:16
@pidixit: Please also add the Firefox and Google Chrome version to the issue description. Thanks.

**Comment by pidixit** [comment] 2019-06-04 10:16
> @pidixit: Please also add the Firefox and Google Chrome version to the issue description. Thanks.

Updated version details.

**Comment by Adriani90** [comment] 2024-06-25 19:35
This is not reproducible anymore with NVDA 2024.2 on Chrome Canary 128. Closing as works for me.

**Closed by Adriani90** 2024-06-25 19:35 UTC
Labels: close/worksforme, bug/double-speaking
