### ISSUE TITLE
Could you please add an item description order feature like talkback

### ISSUE THREAD

**Issue by jiangtiandao** [nvaccess/nvda#8117] opened 2018-03-24 03:31 UTC
### Steps to reproduce:
In talkback I can configure item description setting to arrange sequence of state name and type of current object.It provided three options 
state name type
type name state
name type state
There are also some settings to toggle whether to speak type of object.
In browse mode of NVDA items are always spoken in the sequence of state type content like clickable edit multi line blank.States and types are helpful in a new page but in a familiar context these info can be annoying. Could you please add a setting to allow users to arrange their orders and even turn on and off state or type.

### Expected behavior:
Add a setting to allow users to arrange their orders and even turn on and off state or type.

### Actual behavior:
In browse mode of NVDA items are always spoken in the sequence of state type content like clickable edit multi line blank

### System configuration:
NVDA version:
> 2018.1

NVDA Installed or portable:
installed

**Comment by josephsl** [comment] 2018-03-24 03:34
Hi, hmmm, isn’t this a duplicate of a similar request by another user made recently? In theory, it can be done, but user experience research must be done. In terms of GUI for this, it’ll require wxPython 4 because that version includes RearrangeCtrl (rearrange control) for cases like this. Thanks.

**Comment by jiangtiandao** [comment] 2018-03-24 04:06
I  tried to write a plugin for this.
But after viewing speech.py module I found it is impossible without changing NVDA itself.
Why it is related with GUI?

**Comment by josephsl** [comment] 2018-03-24 04:09
Hi, the GUI comes in when configuring this setting. At the moment there is no way to let users rearrange items in a list (without introducing a custom control), but wxPython 4 will include such a possibility. However, before we go any further, I’d like to know if others think this is a duplicate of another issue and/or offer any thoughts and use cases. Thanks.

**Comment by jiangtiandao** [comment] 2018-03-24 04:52
A group of 6 radio button would be a work around without wxpy4.

**Comment by josephsl** [comment] 2018-03-24 05:17
Hi, let’s worry about GUI portion later. Right now, I want two questions answered: is this a duplicate, and if not, use cases and comments from others please. Thanks.

**Comment by leonardder** [comment] 2018-03-24 08:03
@josephsl is correct. Closing as duplicate of #7232.

**Closed by leonardder** 2018-03-24 08:03 UTC
