### ISSUE TITLE
NVDA doesn't move focus to input from button via element list

### ISSUE THREAD

**Issue by subhajit9614** [nvaccess/nvda#14873] opened 2023-04-25 12:47 UTC
### Steps to reproduce:
1. Go to https://codepen.io/sd4951/pen/ZEqepaM
2. Press tab and focus on "Button".
3. Press Insert + F7 to open Elements List
4. Move to Form fields.
5. Select First Name input and click on "Move to" button.
### Actual behavior:
Focus still remains on "Button" as indicated by Red border around it(shown on focus).

### Expected behavior:
Focus should move properly to First Name input element. This issue doesn't occur when initial focus is on an input element instead of Button.
For ex: Keep focus on First name and open elements list. Select Last name and click on "Move to" button and focus moves perfectly to Last name.

#### NVDA version:
2022.3.1
#### Windows version:
Edition  Windows 10 Enterprise
Version  21H2
OS build  19044.2846
#### Name and version of other software in use when reproducing the issue:
N/A
#### Other information about your system:
N/A
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If NVDA add-ons are disabled, is your problem still occurring?
Not tested
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Not tested, probably not related

**Comment by Adriani90** [comment] 2024-12-18 22:08
This is not reproducible with NVDA alpha-34843,2477780d (2025.1.0.34843), Firefox 133 and Chromium canary 133. Closing as works for me.
If you are still having this issue, please provide an updated test case and we can reopen.

**Closed by Adriani90** 2024-12-18 22:08 UTC
Labels: close/worksforme, p3, triaged, needs-technical-investigation
