### ISSUE TITLE
Confusing status report for toggle switches/buttons in Skype 8's options window

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#9219] opened 2019-01-31 10:12 UTC
### Steps to reproduce:
1. Install the latest version of Skype 8.
2. Open its settings/options window with Control+comma.
3. Activate the "General" tab (this is the first one to have toggle switches, but the behavior is the same with all toggle switches in Skype's settings window).
4. Press TAB a few times, until you get to a toggle switch which is enabled/toggled to "On".
5. Observe what NVDA reports for that enabled toggle switch.

### Actual behavior:
NVDA reports "toggle button  not pressed  checked  On", from which only "On" comes from Skype and the other comes from NVDA itself. This reporting is incorrect, because the toggle cannot be "not pressed" and "checked" at the same time. This kind of behavior/status reporting can be confusing for a screen reader user.

### Expected behavior:
NVDA should report "toggle button  pressed  checked  On". Or even better - suppress the "pressed" or "checked" status, because they duplicate each other. Since these controls are toggle buttons, my suggestion is to fix the status reporting for pressed/not pressed, use it for status reporting and remove "checked/not checked"

### System configuration
- Operating system: Windows 10 Pro version 1809 (build 17763.292), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-16671,6a680851, installed.
- Skype version: 8.38.76.134 Insider Preview release.
- Processor: Intel Core i5-4670 at 3.40GHz.
- RAM Memory: 8.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory + 4065MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC887 at Intel Lynx Point PCH - High Definition Audio Controller.

#### Does the issue still occur after restarting your PC?
Yes, it does.

#### Have you tried any other versions of NVDA?
Yes, the behavior is the same since a long time ago and I've tested with lots of "alpha" versions of NVDA.

**Comment by leonardder** [comment] 2019-01-31 11:13
This can be treated as a duplicate of #9187, since Skype is using the switch role for these toggle buttons/switches. Yet, I'm tempted to leave this open for now, as the link between the two issues isn't very obvious.

**Comment by Adriani90** [comment] 2019-04-22 20:14
Testing with NVDA 2019.1.1 and Skype 8.42.0.60,
I cannot reproduce this issue anymore. @k-kolev1985 can you confirm?

**Comment by k-kolev1985** [comment] 2019-04-22 20:24
I can still reproduce it with both NVDA latest alpha snapshot and 2019.1.1 and Skype 8.44.76.27.

**Comment by Adriani90** [comment] 2019-04-22 20:35
Ok here it was my fault since I was testing with Skype UWP. Testing again with Skype electron for desktop 43.0.56, the issue is still reproducible.

**Comment by Adriani90** [comment] 2020-04-16 21:08
In NVDA alpha-19988,66fcfe69 now NVDA reports check box checked on or unchecked off. I guess "on" or "off" are provided by UIA and NVDA reports both. I guess the skype app module needs to be edited accordingly.
Maybe @leonardder can help here.

**Comment by leonardder** [comment] 2020-04-17 06:20
SKype Electron does not use UIA, it uses IAccessible2.

Anyhow, while reporting ON and Off is redundant, there are more cases where information is doubled like this. I don't consider it of very high priority.

@k-kolev1985 Could you also confirm that the initial issue, namely something like `not pressed checked` being reported for toggle buttons, is fixed? IN that case, we can close this issue.

**Comment by k-kolev1985** [comment] 2020-04-17 06:51
@leonardder Yes, the initially reported problem with the confusing status for the toggle switches is fixed now (tested with Skype version 8.59.76.73 and NVDA version alpha-19988,66fcfe69).

**Comment by leonardder** [comment] 2020-04-17 07:17
In that case, closing as works for me.

**Closed by leonardder** 2020-04-17 07:17 UTC
