### ISSUE TITLE
Browse mode: Braille tethered to focus, does not update messages in say all

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5029] opened 2015-04-10 08:49 UTC
**Reported by surfer0627 on 2015-04-10 08:49**
Hi, 
This case occurred in browser Internet Explorer, Firefox, chrome.
STR:
1.Braille tether to focus.
2.Open browser, and press ctrl+home to top.
3.Press NVDA+DownArrow (say all).
result: Braille got stuck in the first line.
Thanks.

**Comment by Adriani90** [comment] 2019-01-28 22:40
@surfer0627 is this issue still reproducible with NVDA 2018.4.1?

**Comment by leonardder** [comment] 2019-03-25 07:22
Closing as duplicate of #3287

**Closed by leonardder** 2019-03-25 07:22 UTC
Labels: Braille, bug
