### ISSUE TITLE
Unable to read dropdown list of suggested names in the To field of Outlook 2016

### ISSUE THREAD

**Issue by Ednunp** [nvaccess/nvda#8630] opened 2018-08-14 15:17 UTC
### Steps to reproduce:
Hit control n to compose a new message in Outlook 2016.
Write the first few letters of a persons name in the address field. It must be a person you have written to before and there should be more than one person with the same first few letters of a name, or if possible the same name. For example, you have previously written to emily johnson and an emily smith.
after writing the first few letters, hit the down arrow key to scroll between the choices of names. I.e. emily johnson and emily smith.

### Actual behavior:
NVDA is completely silent and does not tell you what is selected.

### Expected behavior:
NVDA should announce the names as you scroll up and down between them.

### System configuration:
, , Outlook 2016 on Office 365 
#### pro, build 16.0.10325.20082

NVDA Installed/:

#### NVDA version:
NVDA alpha 15849
#### Windows version:
Windows 10

Please note, this seems to be a regression issue and has only happened after I updated to monthly channel updates of Office 365.

**Comment by josephsl** [comment] 2018-08-14 16:29
Hi, ah yes, I think it should be given P2 because this is a major regression. Thanks.

**Comment by dkager** [comment] 2018-08-17 10:33
May be a duplicate of #8502.

**Comment by ehollig** [comment] 2018-08-17 15:31
Duplicate of #8502

**Closed by ehollig** 2018-08-17 15:31 UTC
Labels: Microsoft Office support
