### ISSUE TITLE
NVDA freezes when copying link in Microsoft Edge Chromium

### ISSUE THREAD

**Issue by artindk** [nvaccess/nvda#10719] opened 2020-01-24 14:49 UTC
### Steps to reproduce:
* Open a web page in Edge Chromium
* Scroll to a link
* Open the context menu
* And press Copy Link.
[nvda-old.log](https://github.com/nvaccess/nvda/files/4108989/nvda-old.log)

### Actual behavior:
After I activate the copy option, NVDA freezes and I have to restart NVDA.

### Expected behavior:
The link is copied without NVDA freezing.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.3beta2

#### Windows version:
Windows 10 version 1909 (build 18363.592)

#### Name and version of other software in use when reproducing the issue:
Microsoft Edge 79.0.309.71

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by artindk** [comment] 2020-01-30 05:54
I have tested with the new NVDA 2019.3beta 3 and still have the same problem.

**Comment by feerrenrut** [comment] 2020-01-30 19:26
From attached log:
```
WARNING - watchdog._watcher (15:20:55.811) - watchdog (63196):
Core frozen in stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1102, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 988, in reportFocus
  File "speech\__init__.pyc", line 501, in speakObject
  File "speech\__init__.pyc", line 952, in speakTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 704, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 674, in _getTextWithFieldsForUIARange
  [Previous line repeated 35 more times]
  File "NVDAObjects\UIA\__init__.pyc", line 581, in _getTextWithFieldsForUIARange
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 902, in findOverlayClasses
  File "NVDAObjects\UIA\__init__.pyc", line 802, in _getUIACacheablePropertyValue
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
```

**Comment by ivnc** [comment] 2020-01-30 22:16
This is a general issue with context menu, not only with the Copy link option, my details are as follows:

Report from a spanish-speaking user related to #10638.

### Steps to reproduce:

1. Open any website in Edge 79 Beta (Chromium-based) with Native UIA turned on.
2. Focus on a link and press Shift+F10 or applications key to open the context menu.
3. Either press any element from it or directly close the menu.

### Actual behavior:

NVDA locks (freezes) during a few seconds, the same that happens on page load without Edge79 fix implemented via #10675. The problem has been successfully reproduced also by me and a NVDA group member (https://nvda.groups.io/g/nvda/message/69415) and looks like to be Native UIA fault, since disabling it makes Edge working as expected, including the context menu. Lock duration, according to the performed tests, is proportional to the document size.
[NVDA Error in edge.log](https://github.com/nvaccess/nvda/files/4085243/NVDA.Error.in.edge.log)

### Expected behavior:

After context menu closes NVDA works correctly and you can navigate through the page as usual.

### System configuration
#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3Beta2

#### Windows version:

Build 18363

#### Name and version of other software in use when reproducing the issue:

Microsoft Edge 79 (Chromium-based)

#### Other information about your system:

### Other questions
#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

2019.2.1 with WinTenApps 19.11.5: reproducible as well.
With add-ons disabled, in both versions: reproducible as well.

**Comment by rkingett** [comment] 2020-01-31 14:07
This happens in 2019.3 beta 3 as well, with the same thing happening.

**Comment by michaelDCurran** [comment] 2020-03-19 01:47
This has been addressed in Edge Chromium 81. And, NVDA 2019.3 does not use UIA in Edge Chromium anymore, rather it uses IAccessible2.

**Closed by michaelDCurran** 2020-03-19 01:47 UTC
Labels: app/edge, bug/freeze, p2
