### ISSUE TITLE
Freezing NVDA in Windows Media Player

### ISSUE THREAD

**Issue by kvark128** [nvaccess/nvda#5645] opened 2016-01-02 21:33 UTC
To reproduce the problem, follow these steps:
1. Find in Windows Explorer any mp3 file;
2. Turn it through the Windows Media Player;
3. In the WMP set the focus to the slider to fast-track;
4. Press alt+f4 close the WMP;
After that, NVDA freezes, says "Unknown" and other windows is not perceived.
Helps only restart NVDA by ctrl+alt+n.
Windows 7 32-bit, Windows Media Player 12.0, system language - Russian.
[nvda log](https://github.com/nvaccess/nvda/files/76399/nvda.txt)

**Comment by jcsteh** [comment] 2016-01-04 04:09
Duplicate of #5467.

**Closed by jcsteh** 2016-01-04 04:09 UTC
Labels: duplicate
