### ISSUE TITLE
NVDA Causes Microsoft Outlook to Crash

### ISSUE THREAD

**Issue by AlexKLMan** [nvaccess/nvda#13621] opened 2022-04-21 09:21 UTC
### Steps to reproduce:
Opening an email.
### Actual behavior:
It sometime restarts Outlook, 10% chance
### Expected behavior:
Nothing should happen, and I should be able to just read the email.
#### NVDA installed/portable/running from source:
NVDA Installed
#### NVDA version:
2021.3.5
#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook (365)
#### Other information about your system:
Windows 10
#### Does the issue still occur after restarting your computer?
Yes
#### If add-ons are disabled, is your problem still occurring?
Haven't yet tested disabling all addons.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
On a work computer so no admin rights.

```
NVDA Log Viewer:
ERROR - eventHandler.executeEvent (10:06:30.653) - MainThread (8560):
error executing event: scrollingStart on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x01540ED0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "virtualBuffers\gecko_ia2.pyc", line 495, in event_scrollingStart
  File "browseMode.pyc", line 1703, in _handleScrollTo
  File "documentBase.pyc", line 22, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 206, in __init__
  File "textInfos\offsets.pyc", line 457, in __init__
  File "virtualBuffers\__init__.pyc", line 202, in _getOffsetsFromNVDAObject
LookupError
ERROR - eventHandler.executeEvent (10:06:30.795) - MainThread (8560):
error executing event: scrollingStart on <NVDAObjects.IAccessible.ia2Web.Ia2Web object at 0x01540450> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 284, in executeEvent
  File "eventHandler.pyc", line 98, in __init__
  File "eventHandler.pyc", line 107, in next
  File "virtualBuffers\gecko_ia2.pyc", line 495, in event_scrollingStart
  File "browseMode.pyc", line 1703, in _handleScrollTo
  File "documentBase.pyc", line 22, in makeTextInfo
  File "virtualBuffers\__init__.pyc", line 206, in __init__
  File "textInfos\offsets.pyc", line 457, in __init__
  File "virtualBuffers\__init__.pyc", line 202, in _getOffsetsFromNVDAObject
LookupError
ERROR - RPC process 4744 (nvda_slave.exe) (10:10:45.032) - Dummy-7 (12636):
__main__.main:
slave error
Traceback (most recent call last):
  File "nvda_slave.pyw", line 112, in main
  File "comHelper.pyc", line 22, in _lresultFromGetActiveObject
  File "comtypes\client\__init__.pyc", line 180, in GetActiveObject
  File "comtypes\__init__.pyc", line 1239, in GetActiveObject
  File "_ctypes/callproc.c", line 935, in GetResult
OSError: [WinError -2147221021] Operation unavailable
```

**Comment by CyrilleB79** [comment] 2022-04-21 11:22
I also face random Outlook crashes with NVDA. I report here the conditions and environment in case it is linked to this issue:
* Outlook 2016
* NVDA 2022.1beta3 (also already occurred with NVDA 2021.3.x)
* The crash occurs when I open a message.
* It seems to happen with newsletters, not with more simple messages.
* I have tried to run the COM reg fixing tool without success
* Since the crash is not reproducible, I have not been able to test with add-on disabled.

**Comment by CyrilleB79** [comment] 2022-04-21 19:53
The crash is quite frequent anyway so I have finally been able to reproduce with add-on disabled. Here is the log: 
[nvda[OutlookCrashAndRestart]_extraction.log](https://github.com/nvaccess/nvda/files/8534638/nvda.OutlookCrashAndRestart._extraction.log)

This piece of log should be enough, but in case you want the whole log from NVDA start, I can provide it privately.

System:
* Outlook 2016, version '16.0.15028.20204'
* Windows 10 2004 (x64) build 19041.388
* NVDA 2022.1beta3 with add-ons disabled)

**Comment by josephsl** [comment] 2022-04-21 20:13
Hi, does this happen on newer Windows 10 releases such as 21H2? That’s the biggest concern apart from the log we have here (Versio n2004 is out of support). Thanks

**Comment by CyrilleB79** [comment] 2022-04-22 06:50
> Hi, does this happen on newer Windows 10 releases such as 21H2? That’s the biggest concern apart from the log we have here (Versio n2004 is out of support). Thanks

Thanks @josephsl.
Strangely, it is a personal computer, so it should have updated automatically the version of Windows. I will check why it did not, I will update (if possible) and let you know what happens.

**Comment by seanbudd** [comment] 2022-05-17 06:45
Welcome @AlexKLMan ,

Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences. Please include a crash dump from Outlook using the instructions in the log file wiki page.

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2022-06-30 03:58
>>Hi, does this happen on newer Windows 10 releases such as 21H2? That’s the biggest concern apart from the log we have here (Version 2004 is out of support). Thanks

@CyrilleB79 - any updates here?
Capturing an Outlook [crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for us to debug would be great.

**Comment by CyrilleB79** [comment] 2022-07-04 08:19
> > Hi, does this happen on newer Windows 10 releases such as 21H2? That’s the biggest concern apart from the log we have here (Version 2004 is out of support). Thanks
> 
> @CyrilleB79 - any updates here? Capturing an Outlook [crash dump](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for us to debug would be great.

@seanbudd, I have not been able to upgrade from Windows 2004 to 21H2 for now; I need to have some time to investigate why the update fails; a quick google search with the error code was not enough.
If you are happy with it, I can try anyway to get an Outlook minidump, but with Windows 10 2004.
Just let me know.

**Comment by seanbudd** [comment] 2022-07-04 08:33
> If you are happy with it, I can try anyway to get an Outlook minidump, but with Windows 10 2004.
> Just let me know.


An Outlook crash dump from Windows 10 2004 would be great, but we are unlikely to action it without a newer version of Windows reproducing the issue.

**Comment by seanbudd** [comment] 2022-07-07 05:50
Closing this until it can be progressed.

**Comment by AlexKLMan** [comment] 2022-08-12 12:25
@seanbudd thanks!

**Comment by seanbudd** [comment] 2022-08-15 01:06
>Will attach the file here, could you remove it once you read it please?

@AlexKLMan - In the mean time I've rehosted the log so only NV Access can access it via Google Drive.

**Comment by AlexKLMan** [comment] 2022-08-15 09:42
@seanbudd  Cheers! Let me know I can provide any other info.
Alex

**Comment by AlexKLMan** [comment] 2022-11-21 13:58
Hi, just dropping in for an update if any? This is happening a lot more now, so it's getting frustrating when it comes to losing work.
Thank you,
Alex

**Comment by Adriani90** [comment] 2023-03-10 20:35
I did some research and found this:
https://stackoverflow.com/questions/37589935/operation-unavailable-exception-from-hresult-0x800401e3-mk-e-unavailable-wh

It seems it is a common problem in Outlook, especially if you run it as an administrator and NVDA tries to get the active object.
Especially the penultimate comment in the stackoverflow provides a code example which could contribute to solve this problem also in other cases.

cc: @michaelDCurran

**Comment by CyrilleB79** [comment] 2023-03-10 21:26
@Adriani90, I am still facing the issue from time to time on newsletter e-mails. But I am still with my old unsupported Win 10 2004 release and have not yet resolved my update issue.

**Comment by andrew-l-d** [comment] 2024-01-29 00:58
This issue has not occurred here for some time, but has recurred with the betas of 2024.1.  I have a vague recollection that it also occurred with previous betas, so that may be the issue.  I am running beta 5 as a portable.  The problem is more likely to occur with more complex emails such as those sent by commercial organisations.
Log file attached.
[nvda-2024-beta5.log](https://github.com/nvaccess/nvda/files/14078546/nvda-2024-beta5.log)

**Comment by seanbudd** [comment] 2024-04-29 02:54
@andrew-l-d - what version of outlook is this occurring on?
So far all the reports are only with unsupported, very old outlook versions.
Closing this issue as fixed by MS until we can confirm this exists with modern Outlook.

**Closed by seanbudd** 2024-04-29 02:54 UTC
Labels: bug/app-crash, p2, blocked, component/UIA-ms-office, blocked/needs-info, needs-triage

**Comment by andrew-l-d** [comment] 2024-04-29 04:29
I am using Office 365 32 bit version.  After the spate of crashes when running the beta, the issue has not occurred for some time.  If the problem does recur I will raise another ticket.

**Comment by seanbudd** [comment] 2024-04-29 04:39
Can you please include the version number

**Comment by seanbudd** [comment] 2024-04-29 04:41
Can you please include the version number of outlook and NVDA the crashes occurred

**Comment by andrew-l-d** [comment] 2024-04-29 05:40
Betas of NVDA 2024.1 and whatever Outlook under 365 was at the time.  It has certainly not happened since the release of NVDA 2024.1.

**Comment by CyrilleB79** [comment] 2024-04-29 09:41
Note that I can still reproduce this issue quite regularly with NVDA 2024.1 and Outlook 2016 up-to-date (I can provide the version tonight if needed).

However, it's happening on a computer with an outdated version of Windows that I cannot update. That's why my report could not be considered as valid in this issue. If you change your mind regarding the relevance of the Windows version, I can provide more information of course.

**Comment by seanbudd** [comment] 2024-04-29 23:24
I think for the issue to be valid we need up-to-date windows + outlook + NVDA
