### ISSUE TITLE
Excel 2019: NVDA doesn't pick up on column headers when creating Excel tables

### ISSUE THREAD

**Issue by chojiro** [nvaccess/nvda#12324] opened 2021-04-22 09:50 UTC
### Steps to reproduce:
1. Open Excel and create a new sheet
2. When you are on A1, write some text across the different columns (for instance A1 to C1)
3. When on C1, press shift+down arrow three times to select the rows from C1 to C4, then press shift+left arrow to select to A4
4. Press Ctrl+L to create a table, and it should show =$A$1:$C$4 even though NVDA apparently can't read this
5. Tab once and select the check box to make them column headers, then press enter

### Actual behavior:
NVDA doesn't automatically pick up on column headers defined using this method, so you have to use NVDA+Shift+C and NVDA+Shift+R to define column and row headers. Unfortunately, that just creates complications when you have multiple tables with different headers, and not all the cells between are part of the headers above, since it doesn't respect the values define in the "Create table" dialog and I at least can't find a way to tell NVDA when to stop defining them as headers.
### Expected behavior:
I expect that NVDA works with the methods that Excel uses. Defining column headers this way should make it possible for NVDA to read them automatically the way you'd expect. Once I've selected the rows and columns and used the dialog to create a table (Ctrl+L) and told Excel where the data is, that should be it. If I only wanted four rows to have the headers, that should be doable. NVDA+Shift+R and NVDA+Shift+C lets me define the beginning of the headers, but not where it should end until I define new headers elsewhere in the sheet. Isn't it possible to make something that actually works with the features of Excel instead of something separate? It just feels clunky and not quite ideal.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2020.4
#### Windows version:
Windows 10 20H2 (64-bit) build 19042.928
#### Name and version of other software in use when reproducing the issue:
Microsoft® Excel® 2019 MSO (16.0.10373.20050) 64-bit 
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by TestPartners** [comment] 2021-11-19 03:24
The issue also occurs with NVDA 2017.1 and 2021.2 with Excel 365.

It also does not recognise the cells in the first column as row headers if you have checked the First Column checkbox in Excel.

JAWS 2019 and 2021 recognise both the row and column headers, although the row headers are buggy.

**Comment by Adriani90** [comment] 2023-04-20 16:02
Closing as duplicate of #8791.

**Closed by Adriani90** 2023-04-20 16:02 UTC
Labels: close/duplicate
