### ISSUE TITLE
Mouse movement in chrome context menu reads every item

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#9442] opened 2019-04-03 07:14 UTC
Initially reported by a user (DM on twitter) and reproduced by me.

### Steps to reproduce:

1. Press the context menu key or right click the mouse in a web page in Chrome
2. move the mouse down through the items quickly enough that it should skip some.

### Actual behavior:

NVDA reads every menu item completely that the mouse moves over (if the mouse is moved sideways out of the menu, down, and then back onto a lower item, only the item which now has the mouse over it is read).

### Expected behavior:

NVDA's reading of each item should be interrupted as the mouse moves over the next item, as happens in other places.

#### NVDA version:

NVDA 2019.1 installed

#### Windows version:
Windows 10, insider build 18362.1

#### Name and version of other software in use when reproducing the issue:
Chrome 73.0.3683.86 (official build, 64 bit)

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
The same issue happens with NVDA 2018.4.1, but NOP with NVDA 2018.3.2

**Comment by Adriani90** [comment] 2023-08-29 17:38
@Qchristensen can you still reproduce this in Chrome 116 with NVDA 2023.2 RC? Also try to enable cancelable speech in the NVDA advanced settings and see if it makes a difference.

**Comment by Adriani90** [comment] 2023-08-30 22:06
I suggest not to close this issue until cancelable speech for focus events is enabled by default. Currently no is the default behavior.
I vote for enabling cancelable speech by default. 
cc: @seanbudd the PR #11266 enabled cancellable speech by default only until 2021.1, so maybe this should be re-enabled by default in the beta at least. The issues raised in that PR are now solved according to my tests.

**Comment by Adriani90** [comment] 2023-08-30 22:09
by the way cancellable speech is not experimental anymore, as per #12454, so it should be moved from advanced category to speech settings category.

**Comment by Adriani90** [comment] 2023-09-17 11:06
Ok it seems cancellable speech is already enabled by default, I am closing this as works for me.

**Closed by Adriani90** 2023-09-17 11:06 UTC
Labels: close/worksforme
