### ISSUE TITLE
you can not dial a radio button using the navigation mode

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8170] opened 2018-04-12 17:20 UTC
open the page:
https://support.microsoft.com/pt-br/help/10164/fix-windows-update-errors
press r to go to the first radio button, in the case of windows 10, press enter to highlight this button.
now press r until the option button is not in portuguese brazilian the button calls:
não
press enter and also space, see that the button is not marked.
### Expected behavior:
Pressing enter the button must be marked.

### Actual behavior:
pressing enter or space the radio button is not checked.
you need to check the button to enable the next page in the microsoft page.
If you switch nvda to focus mode, you can select the button and continue the pages on the microsoft page.

### System configuration:
NVDA version:
next 15007

NVDA Installed or portable:
instaled
Other information:

Windows version:
windows 10 1803 build 17133.73
Name and version of other software in use when reproducing the issue:
firefox 59.2 64bits
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment] 2019-05-02 22:23
This is not reproducible in Firefox 66.0.3 and NVDA 2019.1.1. @fernando-jose-silva if you are still having this problem, please comment on it and we can reopen the discussion. I am closing this as works for me.

**Closed by Adriani90** 2019-05-02 22:23 UTC
Labels: worksforme
