### ISSUE TITLE
Google Inbox: focus events should override name change events

### ISSUE THREAD

**Issue by minorninth** [nvaccess/nvda#6421] opened 2016-09-30 18:37 UTC
Users are reporting a bug when navigating Google Inbox in Chrome with NVDA - as you move between messages, NVDA is announcing both the old message and new message.

See http://crbug.com/600150 for context.

I've reduced this down to the essential issue, which is that Inbox is effectively renaming the old and new messages at the same time as it's moving focus. If NVDA gets the name change event on the old list item before it gets the focus event on the new item, it reads out the name change but doesn't interrupt / cut it off when it gets the focus event.

I don't think it's incorrect that NVDA reads out the changed name of the old list item because it was focused, but I think it should interrupt that when focus changes, just like it interrupts any speech from a previous focus event when focus changes again.

The attached standalone HTML file demonstrates the issue in both Firefox and Chrome. Other screen readers work fine with the same example.

[listbox-namechange.zip](https://github.com/nvaccess/nvda/files/503597/listbox-namechange.zip)

**Comment by jcsteh** [comment] 2016-10-01 02:34
We don't (and I don't think we should) cancel speech for every focus event. Doing so would cause important info to be silenced in some cases; e.g. foreground changes, alert messages and key presses (some users configure reading of pressed keys).  It would also sometimes cause an audible stutter, which can annoy users. We do silence on key presses, but then, it's very clearly a user triggered action.

What we might be able to do is look at the focused state, since it's possible the object has lost that state by then and we just haven't handled the event yet. We do Wm

**Comment by jcsteh** [comment] 2016-10-01 02:38
Bah, premature send. :( We do this already for certain state changes, so it might work for name changes as well.

As far as I know, JAWS doesn't read most name changes at all in Firefox (this was  mentioned in another issue recently). If that's true, that would explain why it handles this case.

**Comment by minorninth** [comment] 2016-10-01 04:22
Yes, I think that checking the focused state would work. We will have already updated the focused state even though the name change happened to get queued up before the focus change.

You're right, most other screen readers don't read name change events, at least not in general, and I think it's actually a good thing that NVDA does.

**Comment by Brian1Gaff** [comment] 2016-10-01 09:43
Is this not related to the Chromium message forwarded to the dev list a 
short while ago, where its the of change which is the problem as nvda is 
already handling saying the change when another change occurs.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by ssawczyn** [comment] 2016-10-04 19:11
I'm not sure if it makes sense to submit any additional bugs on similar behavior since this appears to be a known issue, however, this situation seems to also exist in the Google Calendar when auto-completing fields.  NVDA announces the correct index (1 of 8 1 of 5 1 of 3) as the choices get narrowed down, but doesn't read the information being auto-populated.  Fortunately these issues don't seem to exist in Firefox; I suspect once this is resolved in Chrome, it'll fix a lot of issues across the board.  I should also note that these same issues exist when using other Chrome-based browsers such as Vivaldi, i.e. anything using the Chrome engine, not specifically Google's Chrome.

**Comment by jcsteh** [comment] 2016-10-04 20:13
This sounds it might be a different issue. Please file a separate issue. Thanks.

**Comment by jcsteh** [comment] 2016-10-06 02:18
P2 because:

* This is very annoying for users; and
* It should be a fairly easy fix on our side.

**Comment by Adriani90** [comment] 2019-03-09 12:23
@minorninth is this issue still reproducible with last NVDA Alpha or Beta version?

**Comment by Adriani90** [comment] 2019-12-15 15:16
Ok I tested with Chrome 79 and Firefox 71. It seems only in Firefox 71 this issue is still reproducible. Tested with NVDA 2019.3 Beta 1.
cc: @MarcoZehe

**Comment by MarcoZehe** [comment] 2019-12-16 07:06
@jcsteh Do you believe your original proposed solution is still the right approach here? Chrome may have changed something on their end which made it go away. Or should we just not fire name change events if the item in question doesn't have the focused state or similar? That would probably reduce the name change events we fire in Firefox, but also may cause other issues of not having an up to date buffer or the like in NVDA.

**Comment by jcsteh** [comment] 2020-01-20 06:05
> @jcsteh Do you believe your original proposed solution is still the right approach here?

It's one reasonable approach which doesn't break things. I can't rule out other reasonable approaches on both sides.

> Chrome may have changed something on their end which made it go away.

[The Chromium issue was marked as fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=600150#c24). Unfortunately, no commit was referenced, so I don't know exactly what they changed.

> Or should we just not fire name change events if the item in question doesn't have the focused state or similar? That would probably reduce the name change events we fire in Firefox, but also may cause other issues of not having an up to date buffer or the like in NVDA.

Yes and yes: less events, but that would definitely break things. I have some experimental Firefox code which always dispatches focus events first when processing the event queue. That way, clients always learn about the focus change first, improving perceived performance and allowing them to filter out events like this. Unfortunately, the patch causes some breakage. I can't quite remember the specifics, but I think it was causing a focus event for a new object to fire before the show event for that object, which breaks cross-proc caching (and probably other things).

**Comment by Adriani90** [comment] 2020-05-08 12:24
@feerrenrut do you think it is ok to close this issue now that #10885 is merged?

**Comment by feerrenrut** [comment] 2020-05-08 12:33
No, don't close this yet. The change in #10885 is not enabled by default, we hope to get wider testing to confirm this doesn't cause issues. If anyone can confirm it fixes this issue and comment that would be great.

The approach taken in #10885 is not what @jcsteh suggested here, and was developed before I was aware of this issue. @jcsteh if you have time, your feedback / testing of the (disabled by default) behavior in #10885 would be appreciated! It can be enabled with the 'Attempt to cancel speech for expired focus events' option in advanced settings panel.

**Comment by ramchaitanyap** [comment] 2020-11-16 14:10
Lets say, I change focus by some timeout, NVDA is still not cancelling expired focus speech.

function getFocus() {
  document.getElementById("myAnchor").focus();
  setTimeout(() =>   document.getElementById("myAnchor2").focus(), 500);
}

Its still reading #myAnchor text and then #myAnchor2 text

**Comment by Adriani90** [comment] 2023-04-14 11:48
@ramchaitanyap this should be fixed when you enable cancelable speech in NVDA advanced settings.

Otherwise it seems the issue is fixed now in Firefox 111, Chrome and Edge 112 with NVDA last alpha.

I am closing as works for me.

If you are still having this issue, please comment and we can reopen.

In that case, Please test with last alpha version of NVDA. You can download it at this link:
https://www.nvaccess.org/files/nvda/snapshots/

**Closed by Adriani90** 2023-04-14 11:48 UTC
Labels: close/worksforme, p2, app/firefox, issue-tracking/crbug
