### ISSUE TITLE
Existence of more items in listbox not announced in Browse Mode

### ISSUE THREAD

**Issue by isplunke** [nvaccess/nvda#12350] opened 2021-04-28 16:29 UTC
When reading a listbox in browse mode it may not be clear to a user there are more items than what is announced.

### Steps to reproduce:
Using a list box with many items eg from the aria-practices example below:
```
1. Transuranium elements
2. Neptunium
3. Plutonium
4. Americium
5. ...
28. Notes
```

1. Navigate to https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-scrollable.html
2. Enable browse mode (typically insert + space)
3. Press the down arrow key

### Actual behavior:
1. Transuranium elements
2. Neptunium
3. Notes

### Expected behavior:
Notify the user that there are more items in the listbox, which must be interacted with via focus mode.
Perhaps something like:
```
1. Transuranium elements
2. Neptunium
3. Notes
To access more items use Focus mode
```

#### Name and version of other software in use when reproducing the issue:
Edge 90.0.818.49 (Official build) (64-bit)
Chrome 90.0.4430.93 (Official Build) (32-bit)
Firefox 78.10.0esr (64-bit)

**Comment by josephsl** [comment] 2021-04-28 16:33
Hi, you must be in focus mode to interact with list boxes (tested with Edge 90+NVDA alpha). Thanks.

**Comment by feerrenrut** [comment] 2021-10-04 03:17
Since this is expected behavior, I'm mutating this issue to make it more clear to the user that in Browse mode only the visible items will be announced.

**Comment by Adriani90** [comment] 2023-05-10 08:26
This is already documented properly in chapter 6 of the user guide and imo there is no need to add extra verbosity here.

I am closing as won't fix, but feel free to comment with arguments why this should be implemented though and we can reopen.

**Closed by Adriani90** 2023-05-10 08:26 UTC
Labels: close/wontfix, feature/browse-mode
