### ISSUE TITLE
In Word, NVDA repeats last context change when going in and out of browse mode

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4854] opened 2015-01-27 14:00 UTC
**Reported by MarcoZehe on 2015-01-27 14:00**
Steps:
1. Open a document in Word.
2. Make sure it has some context changing things such as a table, or heading, or the like.
3. Now press NVDA+Space.
4. Move the cursor with down arrow. Result: NVDA will repeat the last context change, for example, by announcing the page number.
5. Navigate around to a different item such as a heading or table cell.
6. Press NVDA+Space again to turn off browse mode.
7. Move the cursor. Result: Again, NVDA will repeat the last context change, e. g. speak the entering into the table.

I think this double announcement of the context should be suppressed. Since the actual Word caret moves along anyway when navigating in browse mode, and the browse mode cursor likewise when editing a document, double-speaking the context change is superfluous. It would be more polished if the switching was just seamless and one can continue working without being distracted by this extra context announcement that one already knows about.

**Comment by bhavyashah** [comment] 2017-09-06 06:11
Confirmed in Word 2010 using NVDA 2017.3. When pressing NVDA+Space while browsing Word documents for my school textbook's soft copies, NVDA unnecessarily reports the page number, which can get slightly annoying and obtrusive when focus and browse mode are both required for productivity purposes. CC @michaelDCurran (Microsoft Office expert)

**Comment by Adriani90** [comment] 2019-05-05 18:29
I am not reproducing this issue with NVDA 2019.1.1, Word 2010 and Word 2016 / 365. Closing as works for me.
@MarcoZehe if you are still having this problem, please feel free to comment on it and we can reopen the discussion. Thanks.

**Closed by Adriani90** 2019-05-05 18:29 UTC
Labels: Microsoft Office support, bug, worksforme
