### ISSUE TITLE
Windows 8.1 Taskbar: first Tab/Shift+Tab after pressing Windows+T does not cause focus change

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#7549] opened 2017-08-31 07:52 UTC
# STR #
1. Press Windows+T and observe that NVDA says:
Running applications  tool bar
Internet Explorer  button (may vary, but that hardly matters)
2. Press Tab.
Expected Result: Focus should move to the Notification Chevron button.
Actual Result: NVDA says put and says ‘Internet Explorer  button’.
3. Go to the Desktop, Alt+Tab to someplace, and then repeat step 1.
4. Press Shift+Tab.
Expected Result: Focus should move to the Start button.
Actual Result: NVDA says put and says ‘Internet Explorer  button’.
# Test Environment #
* NVDA 2017.3
* Windows 8.1 64 bit
# Notes #
* In either cases, whether Tab or Shift+Tab, pressing the either key the second time does move focus to the expected buttons.
* It may be worth testing and ascertaining the scope of this ticket, i.e. whether it is limited to the Windows 8.1 Taskbar or it applies to Windows 7, Windows 10, etc. also.
* I have Classic Shell installed, but I don’t believe it modifies the Taskbar in any way, so this issue should be universally and consistently reproducible.

**Comment by leonardder** [comment] 2017-08-31 08:08
Could you replicate this with narrator as well?

**Comment by bhavyashah** [comment] 2017-08-31 08:18
Apart from the fact that Narrator does not report 'Running applications toolbar', the reported issue very much applies to Narrator also. In other words, yes, I was able to replicate this with Narrator.

**Comment by leonardder** [comment] 2017-08-31 08:55
In that case, could you give a valid use case as why this should be fixed? Please consider the following points.

1. If you use windows+t and tab as a way to reach the system tray, there is a quicker method by using windows+b
2. Windows 8.1 isn't the most recent version of Windows any more, and updates to Windows 10 are still free for sr users. While I can think of valid reasons to stick to Windows 7, I think there aren't that many for Windows 10

Having said that, I think this issue is quite trivial and fixing this in NVDA's code base shouldn't be considered. You are free to file an issue against Microsoft, but it is very unlikely that they fix such issues in older versions of Windows. I"m leaning towards a won't fix here.

**Comment by bhavyashah** [comment] 2017-08-31 11:19
A few things:
* I completely agree that this issue is very trivial.
* You are correct - Windows+B and the Windows key alone are functional keyboard shortcuts to access the Start menu and System Tray respectively.
* My reasons for sticking to Windows 8.1 are quite different and special. Windows 10 resulted in notable battery life reduction for my laptop, something I cannot afford to retest with the current state of Windows 10, since long-lasting battery is crucial for getting me through the day at school and other classes. Anyways, I am sure there are other Windows 8.1 users (CC @jcsteh, @feerrenrut or @michaelDCurran from NV Access for specific figures) who are NVDA users also. Thus, this argument you provide sort of translates to our unwillingness to address Windows 8.1 specific bugs, which is clearly not the case since NVDA still offers official support for Windows 8.1.
* Having said that, I agree that the reported issue remains very low priority and might need an external fix from Microsoft's side. Therefore, I am happy for this to be labelled NeedsExternalFix, assigned a P4 priority or triaged along those lines. A wontfix seems a little unjustified to me, but either way works since this is not at all life-threatening, just something I noticed and considered worth reporting.

**Comment by josephsl** [comment] 2017-08-31 12:19
Hi, partially reproducible, but workarounds do exist: press Windows+D, then press TAB twice, or as Leonard pointed out, press Windows+B. Thanks.

**Comment by leonardder** [comment] 2017-08-31 12:29
[**@bhavyashah**](https://github.com/bhavyashah) commented on [31 aug. 2017 13:19 CEST](https://github.com/nvaccess/nvda/issues/7549#issuecomment-326265948 "2017-08-31T11:19:05Z - Replied by Github Reply Comments"):
* Thus, this argument you provide sort of translates to our unwillingness to address Windows 8.1 specific bugs, which is clearly not the case since NVDA still offers official support for Windows 8.1.

The point is that this bug is not at all related to NVDA. I agree that it is important to provide workarounds in cases where a bug in software or an OS causes real accessibility concerns, but this is clearly not the case here.

> A wontfix seems a little unjustified to me.

I hope my previous point clears that up a little. Anyway, I"m not nV Access, so I'll leave the decision up to the mighty guys :)

**Comment by ehollig** [comment] 2017-11-03 18:33
Marking this as NeedsExternalFix. As @leonardder points out above, there are plenty of workarounds. You are welcome to file a bug with Microsoft on this issue if you would like. CC @feerrenrut in case he has other opinions on this issue

**Comment by leonardder** [comment] 2018-09-08 17:45
Since this is very unlikely to ever get fixed and there are plenty of workarounds, I'm closing this.

**Closed by leonardder** 2018-09-08 17:45 UTC
Labels: needsExternalFix
