### ISSUE TITLE
Adding user data synchronisation features to NVDA using WebDAV

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#12536] opened 2021-06-10 08:47 UTC
### Is your feature request related to a problem? Please describe.
We may have more than one computer, or we may have re-purchased a brand new computer. In this case, we need to restore the NVDA user configuration.
A portable version with the configuration is one solution, but it is not enough if we have not created a portable version beforehand, or if the configuration of the portable version has not been updated in time, or if the portable version has accidentally been lost.

### Describe the solution you'd like
It would be nice to add the ability to use the web to synchronise profiles for NVDA. So I thought of WebDAV.

### Describe alternatives you've considered
None.

### Additional context
Each country or region may have a WebDAV-enabled online service such as Box, Dropbox, teracloud, yandex, TransIP and so on.
So there may be good speeds in many regions to ensure a good user experience, and some advanced users may even be able to set up their own WebDAV service.

**Comment by zstanecic** [comment] 2021-06-10 08:56
Hi Rowen,

This will be very harpd to implement, thus includes privacy concerns. 

And… each service has their own api. 

Thanks,

Zvonimir

 

From: Rowen ***@***.***> 
Sent: Thursday, June 10, 2021 10:48 AM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Adding user data synchronisation features to NVDA using WebDAV (#12536)

 


Is your feature request related to a problem? Please describe.


We may have more than one computer, or we may have re-purchased a brand new computer. In this case, we need to restore the NVDA user configuration.
A portable version with the configuration is one solution, but it is not enough if we have not created a portable version beforehand, or if the configuration of the portable version has not been updated in time, or if the portable version has accidentally been lost.


Describe the solution you'd like


It would be nice to add the ability to use the web to synchronise profiles for NVDA. So I thought of WebDAV.


Describe alternatives you've considered


None.


Additional context


Each country or region may have a WebDAV-enabled online service such as Box, Dropbox, teracloud, yandex, TransIP and so on.
So there may be good speeds in many regions to ensure a good user experience, and some advanced users may even be able to set up their own WebDAV service.

**Comment by josephsl** [comment] 2021-06-10 09:06
HI, more importantly, is this a duplicate of a suggestion made a few years ago? Thanks.

**Comment by ABuffEr** [comment] 2021-06-10 10:35
Hi,
very interesting, but it raises a lot of questions about security, privacy and so on.
However, it could be a good project for an add-on.

**Comment by seanbudd** [comment] 2021-06-10 11:09
Would a potential solution be the ability to customize where the config is stored? That way you can store it in a folder that is synced with a cloud service like Google Drive, OneDrive, Dropbox, etc across devices.

**Comment by surfer0627** [comment] 2021-06-10 12:10
I guess that it is related to #2926.

**Comment by XLTechie** [comment] 2021-06-10 12:32
> HI, more importantly, is this a duplicate of a suggestion made a few years ago? Thanks.

I thought there was such an one, relating to Dropbox, but I can't find it.

If I remember accurately, difficulties started with executable version and 
add-on version differences potentially requiring different configs, and 
only got more thorny from there.

@seanbudd's suggestion would seem like a prerequisite to any of these 
ideas, and might have some other uses also.

I would be in favor of being able to change config dir location, although 
having my configurations and such stored by means of WebDAV or an NV 
Access web back-end, is not appealing to me personally.

**Comment by aaclause** [comment] 2021-06-10 12:48
Personally my user config folder is a git repository hosted on gitlab in private.
In this way I like the possibility to track changes when I update some add-on or I patch one of them.
In the .gitignore I have just the following:

```
__pycache__
*.key
*.py[co]
*.pickle
addons/Acapela TTS Voices for NVDA - HQ voice */
addons/codefactory/File/
addons/vocalizer-expressive-voice-*/
addons/vocalizer-voice-*/
```

**Comment by cary-rowen** [comment] 2021-06-11 03:38
Hello

Yes, if it is very difficult to implement this feature in NVDA itself, it may be good as a third-party add-on function.
Allowing to change the directory is also a good feature. 
now, The feasibility of using mklink with OneDrive requires further verification.

WebDAV may be able to solve the cost and technical problem in #2926, At least to make it simple.
NVDA needs to get better and more advanced.

Thanks

**Comment by Adriani90** [comment] 2024-03-24 10:52
closing in favor of #2926 which contains some discussion on the backend. This alternative approach can be discussed there.

**Closed by Adriani90** 2024-03-24 10:52 UTC
