### ISSUE TITLE
NVDA hangs when entering a formula in Excel 2019

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#9468] opened 2019-04-08 12:25 UTC
Using NVDA 2019.1, as well as NVDA 2019.1rc1, NVDA hangs when the following occurs:

1. Type a number in a cell. (e.g. 24)
2. Go below that cell with Enter and type another number (e.g. 12)
3. Go below that cell, then type the addition formula to add the two prior cells =(24+12)

You will realise that NVDA hangs a little bit, with no character echo.

Using Windows 10, 1809, Office 2019, didn't test with prior versions before 2019.1, here is what I get from the log:
```
ERROR - eventHandler.executeEvent (07:19:47.927):
error executing event: typedCharacter on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x04E43830> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyo", line 155, in executeEvent
  File "eventHandler.pyo", line 92, in __init__
  File "eventHandler.pyo", line 100, in next
  File "NVDAObjects\__init__.pyo", line 913, in event_typedCharacter
  File "speech.pyo", line 683, in speakTypedCharacters
  File "api.pyo", line 248, in isTypingProtected
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyo", line 787, in _get_isProtected
  File "baseObject.pyo", line 47, in __get__
  File "baseObject.pyo", line 147, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyo", line 1116, in _get_states
  File "NVDAObjects\UIA\__init__.pyo", line 741, in _getUIACacheablePropertyValue
COMError: (-2146233083, None, (None, None, None, 0, None))
```

**Comment by leonardder** [comment] 2019-04-08 13:02
Could you reproduce this with NVDA 2018.4?

**Comment by leonardder** [comment] 2020-04-30 07:18
@fisher729 Could you still reproduce this?

**Comment by leonardder** [comment] 2020-04-30 14:23
I"m not sure as of what can cause performance issues in Excel. Some people report major lag, but al seems to work quite smooth here as of late.

**Comment by fisher729** [comment] 2020-04-30 17:57
You can close the ticket.

**Comment by Adriani90** [comment] 2020-04-30 21:53
Closing as works for me. Thanks for reporting.

**Closed by Adriani90** 2020-04-30 21:53 UTC
Labels: app/microsoft-office, close/worksforme, performance
