### ISSUE TITLE
Braille: Displaying of capital letters in Braille in other than Computer Braille

### ISSUE THREAD

**Issue by winman3000** [nvaccess/nvda#10912] opened 2020-03-28 14:09 UTC
### The problem
NVDA is more and more used also by primary school children with a Braille display. If the output table is set to a table other than computer Braille, the capitalized words are no longer visible on the Braille display. However, it is very important for a primary school pupil to know which words are written in capital letters.

### The solution
In the German Braille table, there is the possibility to display the capitalized words with a so-called uppercase character sign. Many screen readers offer the option to display these uppercase characters. I also consider this function very important for NVDA, because otherwise no primary school pupil can work with NVDA. Advanced Braille readers do not need the display of the uppercase letters.

**Comment by winman3000** [comment] 2020-03-28 14:17
I just noticed that the uppercase character sign is displayed, but only when you place the cursor on the uppercase letter. Unfortunately, this is a bug.

**Comment by DrSooom** [comment] 2020-03-28 22:45
@winman3000: Which NVDA version is used? Try it with [NVDA 2020.1 Beta 1](https://ci.appveyor.com/api/buildjobs/7tih7jg3w06cyqn0/artifacts/output/nvda_2020.1beta1.exe) (portable). I guess that new German 6-dot braille tables are going to be included into NVDA 2020.2. See: Pr #10832.

**Comment by DrSooom** [comment] 2020-03-29 22:15
#### Possible workaround No. 1 for NVDA 2019.2.1 – not tested!
1. Run Notepad++ as Admin, if NVDA is installed.
2. Open "louis\tables\de-chardefs6.cti" in the NVDA program folder.
3. Press CTRL+G and go to line 54.
4. Replace "include latinLetterDef6Dots.uti" with "include latinLetterDef8Dots.uti".
5. Save the file and restart NVDA.

#### Possible workaround No. 2 for NVDA 2019.2.1 – not tested!
1. Run Notepad++ as Admin, if NVDA is installed.
2. Open "louis\tables\de-de-g0.utb" in the NVDA program folder.
3. Press CTRL+G and go to line 32.
4. Replace "include de-chardefs6.cti" with "include de-chardefs8.cti".
5. Save the file and restart NVDA.

**Comment by winman3000** [comment] 2020-03-30 07:04
These two workarounds do not bring the desired effect. With these workarounds the capitalized words are marked with a dot 7. What should be achieved, however, is that the capitalized word should first be announced with the points 4-6.

**Comment by DrSooom** [comment] 2020-03-30 23:37
@leonardder: [NVDA Alpha-19852](https://ci.appveyor.com/api/buildjobs/w9bawnorj5alkkbl/artifacts/output/nvda_snapshot_alpha-19852,c6b6904b.exe) already includes the new German 6-dot braille tables, which could solve this issue here (see the [Liblouis release notes for 3.13.0](http://liblouis.org/liblouis/2020/03/02/liblouis-release-3.13.0.html)), but they aren't available via the GUI. See [my comment in PR ##10832](https://github.com/nvaccess/nvda/pull/10832#issuecomment-593723179). Could you please follow my suggestion and add two new entries? Then it's possible to test these new German braille tables in an easier way for end users. Thanks.

#### Possible workaround right now for NVDA Alpha-19852 – not tested!
1. Open the Windows Explorer and move to the folder "louis\tables\\" in the NVDA program folder.
2. Rename "de-g0.utb" to "de-g0-bak.utb" and "de-g1.ctb" to "de-g1-bak.ctb".
3. Copy "de-g0-bidi.utb" and rename the copy to "de-g0.utb".
4. Copy "de-g1-bidi.ctb" and rename the copy to "de-g1.ctb".
5. Restart NVDA.

Important notes: There is no new German Grade 2 6-dot braille table (= Deutsche Kurzschrift) in Liblouis 3.13.0. But be warned that the above workaround will influence that German Grade 2 braille table! This won't be the case after the two new entries were added to the GUI.

**Comment by Adriani90** [comment] 2020-06-12 22:53
cc: @Andre9642

**Comment by Adriani90** [comment] 2020-06-23 19:10
Closing as duplicate of #505.

**Closed by Adriani90** 2020-06-23 19:10 UTC
Labels: close/duplicate, component/braille, ux
