### ISSUE TITLE
nvda spells itens when using eloquence through sapi5

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#15978] opened 2023-12-28 16:09 UTC
### Steps to reproduce:
1. install eloquence as a sapi voice
2. press ctrl+shift+s and selected sapi 5
3. select an eloquence voice (I tested with english and portuguese).
4. press nvdaKey+n and use arrows to navegate menus. 

p.s.: the item is read normally if I press numpad 2 for example.
also, the unwanted spell doesn't happen if I use sapi 5 with another voice (for example microsoft maria)
### Actual behavior:

you will note that nvda spells the menu itens instead of read the words
### Expected behavior:

nvda should read the words as it does with other synthesizers 
#### NVDA installed/portable/running from source:
portable
#### NVDA version:
2024.1 beta2
#### Windows version:
windows11 
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
it works fine in version 2023.3 
I guess this issue also existed and was fixxed in 2023. It was an issue with eloquence addon.

**Comment by Adriani90** [comment] 2023-12-28 17:50
Closing as duplicate of #15940. This is up to the synth developers to support properly broader speech sequences. Pleare report to them this behavior.

**Closed by Adriani90** 2023-12-28 17:50 UTC
Labels: close/duplicate

**Comment by alexandretoco** [comment] 2023-12-28 18:35
But it Works fine in 2023.3.Why does it breaks in 2024.1 since the speech interface is the same ( sapi 5 )?  Enviado do Email para Windows De: Adriani90Enviado:quinta-feira, 28 de dezembro de 2023 14:50Para: nvaccess/nvdaCc:alexandretoco; AuthorAssunto: Re: [nvaccess/nvda] nvda spells itens when using eloquence through sapi5 (Issue #15978) Closing as duplicate of #15940. This is up to the synth developers to support properly broader speech sequences. Pleare report to them this behavior.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by alexandretoco** [comment] 2023-12-28 18:45
well, it works fine in 2023.3. Why did it break in 2024.1 since the interface stays the same ( sapi5 )?

**Comment by lukaszgo1** [comment] 2023-12-28 21:01
cc @CyrilleB79 for awareness.

**Comment by CyrilleB79** [comment] 2024-01-01 18:04
The issue is probably coming from your SAPI voice that do not handle correctly `CharacterModeCommand`. This bug from the SAPI voice was not noticeable in NVDA 2023.3 because `CharacterModeCommand` was not used in a broader speech sequence (except than in MathCAT add-on).

To confirm this, try the following with NVDA 2023.3:
* open the Python console with NVDA+control+Z
* paste the following line and press enter:
  `from speech.commands import CharacterModeCommand;import core;seq=['hello', CharacterModeCommand(True), 'a', CharacterModeCommand(False), 'world'];core.callLater(1000,lambda: speech.speak(seq))`

If "hello" and "world" are spelt, the bug is in the SAPI synth not handling correctly character mode commands.

Please, try this and confirm or not the result. Thanks.
