### ISSUE TITLE
Level 6 headings do not show up in the elements list

### ISSUE THREAD

**Issue by rnickelson** [nvaccess/nvda#7896] opened 2018-01-05 18:31 UTC
### Steps to reproduce:

>
> Example:
>
> 1. Open FireFox
> 2. Browse to https://labs.ssbbartgroup.com/index.php/ARIA_Heading_Role
> 3. Bring up the elements list and select headings
> 4. Notice expected Results is announced as a level 5 heading when it is actually level 6.

### Expected behavior:
The level announced should match the heading level

### Actual behavior:
Heading 6 is announced as level 5

### System configuration:
NVDA version: 2017.4> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:

Windows version:

Windows 7

Note the headings on this page use ARIA but the same issue can be noticed with HTML headings. h1-h6

**Comment by josephsl** [comment] 2018-01-05 18:46
Hi, no, this works as designed. If you look at level 1 headings from elements list, they may have no tree view level announcements (because they are level 0 in this tree view). This is also the case when I open elements list/headings in IE and Edge in Windows 10. Thanks.

**Comment by leonardder** [comment] 2018-01-06 10:23
Joseph is right. Closing this as duplicate of #7142, which describes the same issue although from a different perspective.

**Closed by leonardder** 2018-01-06 10:23 UTC
