### ISSUE TITLE
If file list in file explorer include more files, NVDA will become slow.

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4655] opened 2014-12-02 13:29 UTC
**Reported by vgjh2005 on 2014-12-02 13:29**
Hi:
If including files is more than 90, NVDA will become slow by pressing arrors key to browse the file list.
Thanks!

**Comment by bhavyashah** [comment] 2017-08-18 16:10
I suggest closing this in favour of (#4530) , to which this seems not only related but of which this might also be a duplicate, in order to consolidate further discussion there. @ehollig

**Comment by ehollig** [comment] 2017-08-19 22:43
Duplicate of #4530

**Closed by ehollig** 2017-08-19 22:43 UTC
Labels: bug
