### ISSUE TITLE
in windows 10 fall creators update, when multiple voices are installed the one core driver driver fail to load

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#7673] opened 2017-10-19 12:26 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
>
> Example:
>
> 1. go to settings and install new croatian voice 
> 2. open synthesizer dialog
> 3. select one core synth
> 4. details in the log.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> the synthesizer should load and it can speak.

### Actual behavior:
> the error dialog is present that synthesizer cannot load see log for details..

### System configuration:
NVDA version: 2017.3
> Example: next-14027,c80e529f

NVDA Installed or portable:
installed
Other information:
> tested with portable master and stil the same./ 

Windows version:
> windows 10 1709 build 16299.19

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?y
yes
Ha0ve you tried any other versions of NVDA?
> Please list them and the result
latest master, the issue occurs when th nvda is installed

above goes the log fragment> 
note using polish version of the windows 10 os 
Synthesizer 'audiologic' doesn't pass the check, excluding from list
DEBUGWARNING - synthDriverHandler.getSynthList (14:24:36.522):
Synthesizer 'mssp' doesn't pass the check, excluding from list
DEBUGWARNING - synthDriverHandler.getSynthList (14:24:36.522):
Synthesizer 'sapi4' doesn't pass the check, excluding from list
IO - speech.speak (14:24:36.868):
Speaking [u'Syntezator  dialog']
IO - speech.speak (14:24:36.882):
Speaking [u'Syntezator  Lista rozwijana  eSpeak NG  zwini\u0119te  Alt+s']
IO - inputCore.InputManager.executeGesture (14:24:37.155):
Input: kb(desktop):g
IO - speech.speak (14:24:37.178):
Speaking [u'G\u0142osy Windows OneCore']
IO - inputCore.InputManager.executeGesture (14:24:37.780):
Input: kb(desktop):enter
WARNING - synthDriverHandler.SynthDriver.loadSettings (14:24:38.098):
Invalid voice: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech_OneCore\Voices\Tokens\MSTTS_V110_plPL_PaulinaM
ERROR - synthDriverHandler.setSynth (14:24:38.299):
setSynth
Traceback (most recent call last):
  File "synthDriverHandler.pyo", line 88, in setSynth
  File "synthDriverHandler.pyo", line 497, in loadSettings
  File "synthDriverHandler.pyo", line 33, in changeVoice
  File "synthSettingsRing.pyo", line 143, in updateSupportedSettings
  File "synthSettingsRing.pyo", line 40, in __init__
  File "baseObject.pyo", line 21, in __get__
  File "synthDriverHandler.pyo", line 387, in _get_availableVoices
  File "synthDrivers\oneCore.pyo", line 229, in _getAvailableVoices
  File "synthDrivers\oneCore.pyo", line 241, in _isVoiceValid
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 16: ordinal not in range(128)
INFO - synthDrivers.espeak.SynthDriver.__init__ (14:24:38.355):
Using eSpeak NG version 1.49.1 dev
DEBUG - speechDictHandler.SpeechDict.load (14:24:38.566):
Loading speech dictionary 'C:\Users\Zvonimir\AppData\Roaming\nvda\speechDicts\espeak-croatian.dic'...
DEBUG - speechDictHandler.SpeechDict.load (14:24:38.568):
file 'C:\Users\Zvonimir\AppData\Roaming\nvda\speechDicts\espeak-croatian.dic' not found.
INFO - synthDriverHandler.setSynth (14:24:38.569):
Loaded synthDriver espeak
IO - speech.speak (14:24:38.648):
Speaking [u'B\u0142\u0105d syntezatora  dialog  Nie mo\u017cna za\u0142adowa\u0107 syntezatora oneCore.']
IO - speech.speak (14:24:38.653):
Speaking [u'OK  przycisk']
IO - inputCore.InputManager.executeGesture (14:24:39.068):

**Comment by leonardder** [comment] 2017-10-21 17:45
I don't think this has to do with multiple voices, rather with voice names containing unicode characters.

**Comment by zstanecic** [comment] 2017-10-21 18:19
Further details
When one voice stops working, this error occurs

Od: Leonard de Ruijter
Wysłano: sobota, 21 października 2017 19:45
Do: nvaccess/nvda
DW: zstanecic; Author
Temat: Re: [nvaccess/nvda] in windows 10 fall creators update, when multiplevoices are installed the one core driver driver fail to load (#7673)

I don't think this has to do with multiple voices, rather with voice names containing unicode characters.

**Comment by nishimotz** [comment] 2018-04-04 05:30
I have reproduced this UnicodeDecodeError with Windows Japanese environment.

Tentative workaround is as follows:

```
diff --git a/source/synthDrivers/oneCore.py b/source/synthDrivers/oneCore.py
index aeeb074d8..67dcdc967 100644
--- a/source/synthDrivers/oneCore.py
+++ b/source/synthDrivers/oneCore.py
@@ -277,7 +277,7 @@ class SynthDriver(SynthDriver):
                try:
                        hkey = _winreg.OpenKey(rootKey, subkey)
                except WindowsError as e:
-                       log.debugWarning("Could not open registry key %s, %s" % (ID, e))
+                       log.debugWarning("Could not open registry key %r, %r" % (ID, e))
                        return False
                try:
                        langDataPath = _winreg.QueryValueEx(hkey, 'langDataPath')
```

I have tested with the current nvaccess master source.
Without this modification, OneCore Japanese voice can not be used from launcher executable.
(UnicodeDecodeError occurs as mentioned above)

With my modification, debugWarning log is as follows and Japanese OneCore Ayumi voice works.

```
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (14:19:33.454):
Could not open registry key u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM', WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (14:19:33.454):
Could not open registry key u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_ZiraM', WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')
DEBUGWARNING - synthDrivers.oneCore.SynthDriver._isVoiceValid (14:19:33.456):
Could not open registry key u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_MarkM', WindowsError(2, '\x8ew\x92\xe8\x82\xb3\x82\xea\x82\xbd\x83t\x83@\x83C\x83\x8b\x82\xaa\x8c\xa9\x82\xc2\x82\xa9\x82\xe8\x82\xdc\x82\xb9\x82\xf1\x81B')
DEBUG - speechDictHandler.SpeechDict.load (14:19:33.463):
Loading speech dictionary 'C:\Users\nishimotz\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft Ayumi.dic'...
DEBUG - speechDictHandler.SpeechDict.load (14:19:33.463):
file 'C:\Users\nishimotz\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft Ayumi.dic' not found.
INFO - synthDriverHandler.setSynth (14:19:33.463):
Loaded synthDriver oneCore
```

**Comment by Adriani90** [comment] 2019-04-30 22:27
@zstanecic I am testing with NVDA 2019.1.1 on Windows 10 1809 update. My voices are english, german, romanian and french. I cannot reproduce this issue.
Are you still having this problem?

**Comment by Adriani90** [comment] 2019-04-30 22:28
cc: @nishimotz

**Comment by zstanecic** [comment] 2019-05-01 07:38
This issue is fixed in the 

Newest NVDA.

You can close it.

**Comment by Adriani90** [comment] 2019-05-01 08:04
Closing as works for me. Thanks very much for reporting back.

**Closed by Adriani90** 2019-05-01 08:04 UTC
Labels: Speech synth drivers, worksforme
