### ISSUE TITLE
NVDA mashes up code when reading on Chrome

### ISSUE THREAD

**Issue by darbaga** [nvaccess/nvda#6932] opened 2017-03-06 00:29 UTC
I'm using NVDA 2017.1 with Chrome 56.0.2924.87. Some example links:

http://manishearth.github.io/blog/2017/03/04/what-are-sum-product-and-pi-types/ (under the second level 2 heading)

http://www.cppsamples.com/common-tasks/return-multiple-values.html

http://rustbyexample.com/fn/hof.html

This doesn't seem to happen with Python or Javascript, i'm not sure why. These all work fine on firefox, but not in Chrome.

**Comment by leonardder** [comment] 2017-03-06 05:12
This seem to be a duplicate of #6529.

**Comment by darbaga** [comment] 2017-03-06 05:17
Huh, looks like it. Should I just close the issue in this case? (I did look to see if there was an existing issue, but didn't see that one, my bad)

**Comment by leonardder** [comment] 2017-03-06 06:39
No problem. Your additional urls are good as references though, so please post them in the older ticket as well. Thanks!

N.B. Sent on behalf of @BabbageCom

**Closed** 2017-03-07 00:36 UTC
