### ISSUE TITLE
Block elements in links: they all are announced as separate links. Is there a best practice?

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#5541] opened 2015-11-25 15:35 UTC
Let's say we have a page with articles' teasers where each teaser consists of the following constituents: an image, an h2 and a paragraph.

If we put all these things into an anchor, NVDA will announce each of the constituents as a link on its own. This is confusing.

I played around with the problem, and I didn't find a perfect solution. My best bet was using `display: inline-block` for the constituents, but this still has problems.

My current solution is this: http://codepen.io/jmuheim/pen/xwBEjP

When navigating using `ctrl+up/down`, everything works well, as the full article teasers are treated as one link.

But when only using `up/down`, the first two elements are still divided into two constituents, as their content is longer than 100 characters.

Also, when I use `h` to jump to a heading, and then press `down` to read the underlying paragraph, it doesn't read it from the start, but only from character 101 of the full article.

So is there a better approach to this problem? In my opinion, NVDA should say something like the following, when it encounters block elements within a link:

```
link start

Bla heading level 2

Bla

link end
```

**Comment by jcsteh** [comment] 2015-11-25 23:05
NVDA speaks things differently depending on whether they're classified as single line, containers, etc. For example, we speak "list" and "out of list" for lists because a list is always a container.

The majority of links are single line, so we optimise the verbosity such that we never speak "out of link" (unless moving by character or word). The problem with this, as you are seeing, is that if a link *is* multi-line, we have to speak "link" again because otherwise, the user doesn't know they're still in a link. "Out of link" isn't appropriate because the user never expects to hear this for links, so if the link crosses quite a few lines, the user won't know they're still in the link for the lines in the middle.

Saying "link start" or the like for block also has problems.

1. We don't say "x start" for anything else, so it would be inconsistent.
2. There are probably many cases where a link contains a block element, but it only occupies one line. In that case, we'd be increasing verbosity for no good reason.
3. If the user walks into the link somewhere other than the start (e.g. from the end or jumps to text in the middle), "link start" is incorrect, but we do need to report something.

From an authoring perspective, I also feel it's not ideal to have links this long; I don't feel it makes sense for the teaser in particular to be part of the link. However, that's probably a different philosophical debate.

**Comment by jcsteh** [comment] 2015-11-25 23:18
Actually, this is a duplicate of #374.

**Closed by jcsteh** 2015-11-25 23:18 UTC
Labels: duplicate
