### ISSUE TITLE
NVDA unexpectedly closes when cmd window closes

### ISSUE THREAD

**Issue by IlyaBiryukov** [nvaccess/nvda#8738] opened 2018-09-13 00:24 UTC
### Steps to reproduce:
1. Start NVDA
2. Start cmd
3. Close cmd window by clicking on [x] button in top right corner

### Actual behavior:
NVDA closes
[nvda.log.zip](https://github.com/nvaccess/nvda/files/2377273/nvda.log.zip)

### Expected behavior:
NVDA stays running

#### NVDA Installed/portable/running from source:
Installed from https://www.nvaccess.org/download/

#### NVDA version:
2018.2.1

#### Windows version:
Windows 10 OS Build 17134.285 x64

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by Mohamed00** [comment] 2018-09-13 01:26
Duplicate of #1682.

**Comment by leonardder** [comment] 2018-09-13 07:48
Closing as duplicate.

**Closed** 2018-09-13 07:47 UTC
