### ISSUE TITLE
NVDA Freezes when entering Excel 2016 help screen

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#7231] opened 2017-05-31 05:37 UTC
### Steps to reproduce:
1. Open Excel 2016
2. Press Escape key
3. Press F1

### Expected behavior:
- N- BVDA should not be down and should be able to navigate the help search screen.

### Actual behavior:
- NVDA will stop working.

### System configuration:
- NVDA version: next-14076,c3587de7
- NVDA Installed or portable: Installed
- Windows version: Windows7/64bit

Thanks.

**Comment by ehollig** [comment] 2017-08-21 20:12
I am not having an issue opening and reading Excel help when performing the above steps using Excel 2016 on Windows 10. After pressing F1, I need to press tab to begin reading Excel help information.
Could you please try this with all addons disabled and if the problem persists, could you provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) with logging set to debug in general settings?

**Comment by ehollig** [comment] 2017-12-13 01:11
@dnz3d4c, is this still an issue?
@Brian1Gaff or @feerrenrut, is this something you could test on Windows 7?

**Comment by feerrenrut** [comment] 2017-12-13 02:57
Unfortunately I do not have Excel 2016, I did test this in a VM with Windows 7 and Excel 2013 and could not replicate the issue.

**Comment by dnz3d4c** [comment] 2017-12-13 10:44
I was able to reproduce this problem on a Windows 10 commuter. I am currently using the Code Factory Voices for NVDA add-on(Voice language: Korean/sora). Attach the error log file. Thanks.
[error.log](https://github.com/nvaccess/nvda/files/1555140/error.log)

**Comment by dnz3d4c** [comment] 2017-12-13 10:48
I can not test because I do not have a Windows 7 computer.

**Comment by PratikP1** [comment] 2017-12-16 12:56
I can confirm this on 
* Windows 10 1709 Build 17046.100. 
* Office 2016 (16.0.8431.2110) 
* NVDA version next-14728,d60e4746

I'm including the debug log below. A few things to note:
1. There are several freezes when accessing the help screen. Aside from the initial toolbar announcement and panel, no further output. It may be worth reviewing the log starting at 07:09:33.009.
2. Excel crashes at 07:10:39.089
3. speech is lost for almost a minute.

[NVDA crashes with Excel help.txt](https://github.com/nvaccess/nvda/files/1564749/NVDA.crashes.with.Excel.help.txt)

**Comment by fernando-jose-silva** [comment] 2017-12-16 14:04
If I can help, I have also been able to reproduce this.
windows 10 16299.64 64bit
nvda next 14728
excel 16.0.8730.2127 32bits
I could not reproduce the error when using jaws 18.
In my case the nvda stops responding and errors are heard.
After a while excel also crashes.

**Comment by fernando-jose-silva** [comment] 2017-12-16 14:05
[excel.txt](https://github.com/nvaccess/nvda/files/1564822/excel.txt)

**Comment by derekriemer** [comment] 2017-12-24 19:30
yes, I can confirm this too.

**Comment by feerrenrut** [comment] 2017-12-26 23:22
Several logs show freezes with the following stack trace:
```
DEBUGWARNING - watchdog._watcher (07:09:40.124):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 200, in <module>
  File "core.pyc", line 468, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 439, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 62, in _queueEventCallback
  File "eventHandler.pyc", line 147, in executeEvent
  File "eventHandler.pyc", line 175, in doPreGainFocus
  File "eventHandler.pyc", line 152, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\__init__.pyc", line 943, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 808, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1054, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 624, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 115, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 994, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 684, in _prefetchUIACacheForPropertyIDs
```

**Comment by Adriani90** [comment] 2019-02-04 14:36
@dnz3d4c, @PratikP1, @fernando-jose-silva can any one test if this issue is still reproducible? Which Synthesizers are you using? Did you try with a clean Version of NVDA, without any add-on installed?

**Comment by dnz3d4c** [comment] 2019-02-04 17:22
When I tested, I noticed that the help screen opens. But there are other issues. Perhaps this should be registered as a new issue.

> 
> 
> @dnz3d4c, @PratikP1, @fernando-jose-silva can any one test if this issue is still reproducible? Which Synthesizers are you using? Did you try with a clean Version of NVDA, without any add-on installed?

**Comment by Adriani90** [comment] 2019-02-04 20:00
I am testing with NVDA 2018.4.1 and with Alpha 16991.10950C87 on Excel 365, I cannot reproduce this issue. The help window opens and NVDA works properly. It does not crash. Please create new issues if you find some. I will close this as works for me. Please comment on it if you don't agree and we can reopen it.

**Closed by Adriani90** 2019-02-04 20:00 UTC
Labels: Microsoft Office support, bug, crash, p2, worksforme
