### ISSUE TITLE
Nvda is not re-reading the automatic completion of addresses in outlook

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9330] opened 2019-02-27 12:36 UTC
### Steps to reproduce:
This is a chronic problem of nvda and outlook that returns almost always.
I am sure that it has already been discussed in other problems, and already solved, more fearful in returning.
Now a lot of things have changed, I am using nvda alphas most resentful, using office 2019 and with esperimental uia support enabled (I do not know if it makes any difference here).
Open a new message in Outlook.
Start typing the email address that is already in your address book.
### Actual behavior:
Nvda does not automatically advertise the suggested addresses as you type.
It also does not announce that the address suggestions list has been displayed, however you can navigate through the list with the arrow keys.
### Expected behavior:
The nvda automatically read the address suggestions suggested by Outlook.
Nvda notifies you that the address suggestions list is open and has items.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
alfa 16813
#### Windows version:
10 17763.316
#### Name and version of other software in use when reproducing the issue:
outlook Microsoft Office version 16.0.11231.20174

#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no
log:
[outlook_addressbook.txt](https://github.com/nvaccess/nvda/files/2910281/outlook_addressbook.txt)

**Comment by leonardder** [comment] 2019-02-27 12:46
Closing as duplicate of #8502. Nevertheless, thanks for bringing this up again.

**Closed by leonardder** 2019-02-27 12:46 UTC
