### ISSUE TITLE
PowerPoint 365: Bullet state not reported in context menu

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10442] opened 2019-10-30 00:44 UTC
### Steps to reproduce:
1. Open a blank presentation in PowerPoint 365
2. Press CONTROL+M to add a new Title and layout slide
3. Tab to the content object placeholder and press enter to edit it.
4. Add at least one point and then read it to confirm it is bulleted
5. Open the context menu and down arrow to "bullets".

### Actual behavior:

NVDA reports the bullets item.  Visually the square icon at the left (showing the Office bullets ribbon icon) is slightly coloured, indicating it is checked.  This is not reported.

### Expected behavior:

NVDA should report the item as "Checked".

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
18362.1 
#### Name and version of other software in use when reproducing the issue:
Office 365 Version: 
16.0.12026.20344 
#### Other information about your system:
Narrator treats the bullet list item as several distinct items (requiring pressing the down arrow several times to move past), but reports the item as checked.

#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by lukaszgo1** [comment] 2019-10-31 13:39
In PowerPoint 2010 checked is announced.

**Comment by Adriani90** [comment] 2024-06-29 13:29
In Powerpoint 365, when the item is checked, NVDA does not report it, but NVDA reports "not selected" when the item is not checked. So the user can still make the difference of what is selected and what is not selected. Given this is not a multi select control, it is expected behavior. Closing as works for me.

**Closed by Adriani90** 2024-06-29 13:29 UTC
Labels: close/worksforme, app/microsoft-office
