### ISSUE TITLE
It is then no longer possible to search for an update.

### ISSUE THREAD

**Issue by paulber19** [nvaccess/nvda#15284] opened 2023-08-13 09:18 UTC
- first, check that the "update" folder of the user configuration is empty, or delete it.
- try to check update: "NVDA+n", ""Help" sub-menu, "Check for update" sub-menu.
- "NVDA update" dialog comes up and offers a new version.
- "enter" on "download" button
- "Please donate" dialog appears, press "no now" button.
- after downloading,  "NVDA update" dialog is displayed. and report that the new version is ready to be installed but some add-ons are no compatible.
- - move by tab to "I understand that incompatible add-ons will be disabled and can be manually re-enabled at my own risk after installation." checkbox.
- hit "enter" key. The "NVDA update" dialog  is closed.
- now try to check update again: "NVDA+n", ""Help" sub-menu, "Check for update" sub-menu.

### Actual behavior:

There is no check and an error is logged in NVDA log:
Traceback (most recent call last):
  File "wx\core.pyc", line 3407, in <lambda>
  File "updateCheck.pyc", line 382, in __init__
TypeError: bad operand type for unary +: 'str'
It is then no longer possible to search for an update.
To restore this possibility, either delete the "update" folder or its contents.
### Expected behavior:
No error and update check available.
#### NVDA installed/portable/running from source:
NVDA portable
#### NVDA version:
NVDA version alpha-28791,43c2bed6

#### Windows version:
Windows 10 22H2 (10.0.19045) workstation

#### Name and version of other software in use when reproducing the issue:
none
#### Other information about your system:
ras
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
This does not happen with nvda 2022.4.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2023-08-14 01:18
Duplicate of https://github.com/nvaccess/nvda/issues/15028

**Closed** 2023-08-14 03:21 UTC
