### ISSUE TITLE
NVDA repeats twice announcing list items (numbered list, bulleted list, lettered list) when pressing control+down/up arrow to go to another list item

### ISSUE THREAD

**Issue by jacobchawala** [nvaccess/nvda#13712] opened 2022-05-19 15:05 UTC
In Microsoft word 2021 (version number: Microsoft® Word LTSC MSO (Version 2204 Build 16.0.15128.20240) 64-bit) NVDA 22.1 RCA 1 and 2 repeats twice announcing list items (numbered list, bulleted list, lettered list) when pressing control+down/up arrow to go to another list item. 

It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

### Actual behavior:
NVDA repeats twice announcing list items when reading paragraph to paragraph by pressing control+down/up arrow. I already have updated Microsoft office 2021 professional plus to the latest version, but the problem is still occurring in the same way.  The version number of word is Microsoft® Word LTSC MSO (Version 2204 Build 16.0.15128.20240) 64-bit 
### Expected behavior:
It should not announce twice the list iteme when pressing control+down/up arrow
#### NVDA installed/portable/running from source:
NVDA installer
#### NVDA version:
NVDA 2022.1 RC2
#### Windows version:
Operating System: Windows 11 Pro 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)
#### Name and version of other software in use when reproducing the issue:
Microsoft office 20201 professional plus
The version number of word is Microsoft® Word LTSC MSO (Version 2204 Build 16.0.15128.20240) 64-bit
#### Other information about your system:
Machine name: JACOBCHAWALA
Machine Id: {8A4A0A4B-6524-4A4E-9CDB-22AD55F2EB94}

Language: English (Regional Setting: English)
System Manufacturer: HP
System Model: HP ENVY x360 Convertible 15-cn0xxx
BIOS: F.28 (type: UEFI)
Processor: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 CPUs), ~2.0GHz
Memory: 16384MB RAM
Available OS Memory: 16212MB RAM

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
It also occurs in NVDA 2022.1 RC1
I confirm that this isn't an issue in 2021.3.5.
#### If add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
YES
[nvda_2022.1rc2.log](https://github.com/nvaccess/nvda/files/8747073/nvda_2022.1rc2.log)

**Comment by seanbudd** [comment] 2022-05-19 23:30
Please reproduce this issue and provide a [log file](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) of the behaviour. Ensure your log level is set to debug in general preferences.
Could you also confirm that this isn't an issue in 2021.3.5?

Kind Regards,
NV Access Software Developers

**Comment by seanbudd** [comment] 2022-05-19 23:33
Can you [follow these](https://support.microsoft.com/en-us/office/about-office-what-version-of-office-am-i-using-932788b8-a3ce-44bf-bb09-e334518b8b19) steps to get the version number of word? Can you update to the latest version?

**Comment by seanbudd** [comment] 2022-05-19 23:33
Potentially related: https://github.com/nvaccess/nvda/issues/13462

**Comment by seanbudd** [comment] 2022-05-26 06:03
Can you try updating word?

**Comment by seanbudd** [comment] 2022-05-26 06:06
Relates to #10821

**Comment by michaelDCurran** [comment] 2022-05-26 06:14
From the other issue:
Microsoft Word handles paragraph navigation (control+arrows) a little unexpectedly when on list items. Essentially, the bullet/number is treated as a character stop. I.e. moving with control+downArrow, Word moves to the bullet, and then the content. the next bullet, and then the content. However, Microsoft word has no current way of exposing whether the caret is actually on the bullet or the first character in the content. They booth are the same when it comes to UI Automation or the object model.
The only way we can really fix this is to provide scripts in NVDA for control+upArrow / control+downArrow, which will jump over the bullets.

**Comment by Adriani90** [comment] 2024-02-20 21:38
In the settings category "document navigation" you can choose NVDA to use one linebreak as indicator for a new paragraph. Choosing that setting fixes this issue. So i am closing as works for me.

**Closed by Adriani90** 2024-02-20 21:38 UTC
Labels: close/worksforme, app/microsoft-office, p4, bug/double-speaking, needs-triage

**Comment by CyrilleB79** [comment] 2024-02-21 21:51
I disagree with the reason why it was closed as explained in https://github.com/nvaccess/nvda/issues/10821#issuecomment-1955555316.

Anyway, I'd say that this issue can remain closed as duplicate of #10821.
