### ISSUE TITLE
Feature suggestion - option to allow users to auto-update to RC builds (only, not snapshots!)

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#6149] opened 2016-07-06 04:13 UTC
When a new version is released, one (or more) release candidates are made available just prior to the final version - with the idea that they should be pretty much solid and ready to go unless any major issues are found. Currently, you only get the RC build if you see the announcement for it and go and download it deliberately.

Would it be worth considering an option, in the general options next to "automatically check for updates") something like a checkbox to "also check for new release candidates".  This way the majority of people are able to easily get release candidates (particularly if it was checked by default) and easy to opt out of.  This is only in reference to release candidates, not "next" or "master" builds.

The Word Grammar bug is potentially a good argument for this as at around the same time as that feature was added, a new Insider build (used by a lot of the same people who test pre-release versions of NVDA) caused random Word crashes, and none of the Word crashes were explicitly linked to NVDA.  If release candidates were automatically distributed more widely, it would enable major bugs such as this to be more likely to be detected prior to a final, stable version being released.

Note again that this suggestion is for release candidate versions only.  Users who wish to use the "next" or "master" builds would still need to download those manually.

**Comment by leonardder** [comment] 2017-07-17 11:39
Hmm, interesting idea. One additional thing that can be covered here as well, is that people will be able to automatically update from a rc to a stable release, if that's not already possible.

**Comment by jcsteh** [comment] 2017-07-18 00:27
[**@leonardder**](https://github.com/leonardder) commented on [17 Jul 2017, 23:39 GMT+12](https://github.com/nvaccess/nvda/issues/6149#issuecomment-315732071 "2017-07-17T11:39:43Z - Replied by Github Reply Comments"):
> Hmm, interesting idea. One additional thing that can be covered here as well, is that people will be able to automatically update from a rc to a stable release, if that's not already possible.

It already happens.

**Comment by jcsteh** [comment] 2017-07-18 00:31
@Feerrenrut, @MichaelDCurran, thoughts on priority? On one hand, anything that helps us catch critical bugs before the final release is a good thing. On the other hand, it doesn't fit our current pattern of a build only querying for builds on the same update channel. (Rc to stable still uses the rc channel; it's just that the rc channel returns the stable release once the stable release is made. In contrast, stable builds always query the stable channel, which always returns a stable release.)

**Comment by feerrenrut** [comment] 2017-07-18 05:52
If I understand correctly, one way to achieve this might be to introduce an option in the GUI to pick which channel to look at for updates, regardless of the source channel for the version currently running?

Presumably this isn't a large block of work?

**Comment by leonardder** [comment] 2017-07-18 06:03
If it is done this way, I'd love it if this channel switching capabilities would allow for development versions as well, e.g. allow stable, rc, next and master, at least by editing the configuration. I don't think detailed switching capabilities should be added to the GUI itself, though.

**Comment by jcsteh** [comment] 2017-07-18 06:41
Generic update channel switching has been requested before. I oppose this (and have closed issues accordingly) because testing various types of test builds should require a great deal of intent from the user, as they need to be fully aware of the potential risks of running test builds. Also, a user might change this setting and forget and at some point expect stable builds but instead get test builds. Requiring users to explicitly download the build type they want to work with solves these issues. By way of precedent, it's worth noting that major apps that have multiple update channels do not support this kind of switching. The case discussed in this issue is a very specific case, though, and is under consideration because rc builds only exist for a very short period and then update to stable.

**Comment by DrSooom** [comment] 2018-07-18 18:34
I would prefer a new combobox below the update checkbox in the General NVDA settings window with the following values: Stable [default value], RC, Beta and Alpha. If "Beta" or "Alpha" was chosen by the user a warning prompt should appear immediately after moving the focus with the tab key or the enter key. … No, it might be better that this warning prompt will appear every time after the button "OK" or "Apply" was pressed - of course with the option to permanently disable this warning prompt through a checkbox within the warning prompt itself as well as in the General settings below this new combobox.

**Comment by DrSooom** [comment] 2018-07-19 01:07
@josephsl: Sadly you can say the exactly thing regarding to the "logging level" combobox which can be changed via the NVDA GUI. And changing this without knowing what you are exactly doing will lead to very high security and privacy issue. See also: bug #8515 and #8516.

Quote from the NVDA user guide:
> Logging level
> This is a combo box that permits you to choose how much NVDA will log as it's running. Generally users should not need to touch this as not too much is logged. However, if you are wanting to provide information in a bug report, then it may be a useful option.

Well, and in the end you can say nearly the same thing to the update channel. In my opinion it doesn't make any changes if a so called "power user" say to someone the way through the python console or through the GUI. The result is both the same – the update channel was changed by the user.

Well, and finally: NV Access is never responsible for absolutely irresponsible so called "power users" which don't care about anything regarding to stability, security and privacy. It isn't NV Access' job to protect "normal users" from such irresponsible acting users.

**Comment by josephsl** [comment] 2018-07-19 01:18
Hi,

No, this issue has nothing to do with that bug linked.

To follow precedent from the past, I'll close this issue, and it should be reopened if and only if a very strong justification is put forth. Thanks.

**Comment by Adriani90** [comment] 2019-03-06 19:03
I would also propose a combobox which allows to decide which update channel to stay on. We had lots of situations in the past where users reported major bugs just after a final release and then a 201x.x.x followed a week after or so. It causes regressions and additional work for developers who actually could rather concentate on alpha builds for the next version and not on bugs which have been reported right after a final release leading to regressions or something like that. Many users are not very open to downloading the last Alpha or Beta snapshots from the website. But they would rather do it by choosing an option in the gui.
@feerrenrut, @leonardder, @michaelDCurran how about integrating a combobox in the new advanced dialog called "update channel" or so?

**Comment by Adriani90** [comment] 2020-01-19 20:45
Actually I would close this one as duplicate in favor of #10679 because that one is newer and contains also a link to an addon as well as some discussion. Please feel free to comment on this one if you don't agree and we can reopen it. Thanks.

**Closed by Adriani90** 2020-01-19 20:45 UTC
Labels: NVDA GUI, duplicate, feature
