### ISSUE TITLE
Sentence reading in MS Word breaks after going into browse mode

### ISSUE THREAD

**Issue by andrew-l-d** [nvaccess/nvda#5911] opened 2016-04-28 21:53 UTC
Reading by sentence in Word (alt-up and alt-down arrow) works until switching to browse mode.  When reverting from browse mode sentence reading does not work without restarting NVDA.  The issue has existed since at least 2015.3 (ran a portable copy to check).  Apologies if already reported - could not find anything by searching.

**Comment by jcsteh** [comment] 2016-04-28 23:11
Duplicate of #5805.

**Closed by jcsteh** 2016-04-28 23:11 UTC
Labels: duplicate
