### ISSUE TITLE
Control+backspace reports "DeleteBackWord" in Word 365

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#10851] opened 2020-03-07 04:27 UTC
### Steps to reproduce:

1. Open Word 365 to a blank document.
2. Type a word
3. press CONTROL+BACKSPACE.

### Actual behavior:

NVDA reports "DeleteBackWord".

### Expected behavior:

NVDA should report the word deleted.

#### NVDA version:

Installed 2019.3.1
Portable 2019.2
Portable alpha-19755,6d40a54e

#### Windows version:
Windows 10 Build 1903 Version 18362.388

#### Name and version of other software in use when reproducing the issue:

Office 365 Version: 
16.0.12430.20286 

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, as above.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

No change.  One user noted that at the same time as this started, CONTROL+X, CONTROL+C and CONTROL+V now report "Cut", "Copy" and "Paste" in Word.  Note that this is WITHOUT any add-ons which otherwise provide that functionality and only seems to do this in Word.  Note that this behaviour is the same whether the Use UIA in Word option (in NVDA's Advanced options) is enabled or not.

Log snipped below:

IO - inputCore.InputManager.executeGesture (15:12:13.467) - winInputHook (14180):
Input: kb(desktop):control+backspace
DEBUGWARNING - Python warning (15:12:13.495) - MainThread (18304):
C:\Program Files (x86)\NVDA\library.zip\keyboardHandler.py:538: DeprecationWarning: Yield() is deprecated
DEBUGWARNING - Python warning (15:12:13.495) - MainThread (18304):
C:\Program Files (x86)\NVDA\library.zip\api.py:287: DeprecationWarning: Yield() is deprecated
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (15:12:13.501) - MainThread (18304):
oleacc.AccessibleObjectFromEvent with window 199388, objectID 43 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (15:12:13.502) - MainThread (18304):
oleacc.AccessibleObjectFromEvent with window 199388, objectID 44 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - editableText.EditableText._hasCaretMoved (15:12:13.511) - MainThread (18304):
Caret move detected using bookmarks. Elapsed: 0 ms
IO - speech.speak (15:12:13.511) - MainThread (18304):
Speaking [LangChangeCommand ('en_AU'), 'fox']
DEBUG - synthDrivers.oneCore.SynthDriver._processQueue (15:12:13.524) - MainThread (18304):
Begin processing speech
DEBUG - synthDrivers.oneCore.SynthDriver.cancel (15:12:13.528) - MainThread (18304):
Cancelling
IO - speech.speak (15:12:13.530) - MainThread (18304):
Speaking [LangChangeCommand ('en_AU'), 'DeleteBackWord']

**Comment by Adriani90** [comment] 2020-03-08 21:35
cc: @michaelDCurran

**Comment by josephsl** [comment] 2020-03-09 04:34
HI, caused by UIA notification event. I’ll release a quick workaround for Windows 10 App Essentials users. Thanks.

**Comment by burakyuksek** [comment] 2020-03-21 23:25
Won't this be fixed in a future update?

**Comment by josephsl** [comment] 2020-03-21 23:29
Hi, I wrote a fix, which is awaiting one more review check. In the meantime, my add-on provides the fix (I know this is not the news you want to hear, but given the present circumstance, that’s the next best thing we have). Thanks.

**Comment by burakyuksek** [comment] 2020-03-22 12:28
Hello,
Thanks for trying to implement a fix. I hope the fix you submited makes it into the next version.

**Closed** 2020-03-30 10:30 UTC
