### ISSUE TITLE
MS Teams: "Unavailable" reported for ANY Button click.

### ISSUE THREAD

**Issue by sanketdixit2013** [nvaccess/nvda#14292] opened 2022-10-25 08:24 UTC
### Steps to reproduce:
1.Enable NVDA Screen Reader
2.Focus on the any adaptive card button.
3.observe the screen reader input.

### Actual behavior:

If there is a response card , when we hit the submit/cancel button of adaptive card. The screenreader is reading it as unavailable message
### Expected behavior:

If there is a response card , when we hit the submit/cancel button. The screenreader should read it like response is submitted/response sent to an app.

#### NVDA installed/portable/running from source:
Windows 10
#### NVDA version:
2022.3.1
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
MS Teams
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes pervious versions also had the same behaviour

**Comment by feerrenrut** [comment] 2022-11-01 02:54
It's hard to know the cause of this. Has it been reported to Microsoft?
Because there are so many layers of tech between an application like teams and NVDA, we typically need a minimal sample in order to be able to investigate effectively. For an app like teams, a minimal HTML sample is usually appropriate. This also ensures that some developer has considered whether this sample is using the appropriate accessibility features.

**Comment by sanketdixit2013** [comment] 2022-11-01 05:19
Hello @feerrenrut,

Yes we have reported this to Microsoft and they have suggested us to get in touch with NVDA team.
Please find the below sample json of the adaptive card which is having the issue.
{
  "schema": null,
  "type": "AdaptiveCard",
  "version": "1.3",
  "body": [
    {
      "type": "TextBlock",
      "text": "Some Text",
      "inlines": null,
      "placeholder": null,
      "maxLength": 0,
      "value": null,
      "choices": null,
      "actions": null
    },
    {
      "type": "Input.Text",
      "text": null,
      "inlines": null,
      "placeholder": "Some Text",
      "id": "FeatureSuggestion",
      "maxLength": 100,
      "choices": null,
      "actions": null,
      "color": null,
      "wrap": false,
      "label": "Some Text",
      "isRequired": true,
      "errorMessage": "Some Text",
      "regex": "^.*[\u30A0-\u30FF\u4e00-\u9fa5_a-zA-Z0-9ЁёА-я]+.*$"
    },
    {
      "type": "Input.Text",
      "text": null,
      "inlines": null,
      "placeholder": "Some Text",
      "id": "FeatureDescription",
      "maxLength": 0,
      "choices": null,
      "actions": null,
      "color": null,
      "wrap": false,
      "label": "Some Text",
      "isRequired": true,
      "errorMessage": "Some Text",
      "regex": "^.*[\u30A0-\u30FF\u4e00-\u9fa5_a-zA-Z0-9ЁёА-я]+.*$"
    },
    {
      "type": "ActionSet",
      "text": null,
      "inlines": null,
      "placeholder": null,
      "maxLength": 0,
      "value": null,
      "choices": null,
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Share my suggestion",
          "data": {
            "Action": "NewFeatureSuggestion",
            "Intent": "BTNFSNewFeatureSuggestion"
          },
          "id": "Submit"
        },
        {
          "type": "Action.Submit",
          "title": "Cancel",
          "data": {
            "Action": "GenericAdaptiveCancel"
          },
          "associatedInputs": "none"
        }
      ],
      "color": null,
      "wrap": false
    },
    {
      "type": "TextBlock",
      "text": "Some Text",
      "inlines": null,
      "placeholder": null,
      "maxLength": 0,
      "value": null,
      "choices": null,
      "actions": null,
      "color": "Good",
      "isVisible": false,
      "wrap": true
    }
  ],
  "id": "UH",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}

**Comment by feerrenrut** [comment] 2022-11-01 05:29
@sanketdixit2013 This is sample is not usable with NVDA. Microsoft engineers (who work on teams) will need to supply a minimal HTML / Javascript / CSS sample that reproduces the issue in a web browser. This helps us to ensure that the bug is not caused by teams itself.

**Comment by sanketdixit2013** [comment] 2022-11-01 09:36
Do you mean we need to ask Microsoft to share this sample?
The issue is within the bot application that is for MS Teams platform. The bot shows these adaptive cards to users who chat with it. If you want I can share with you a video of the issue?

**Comment by sanketdixit2013** [comment] 2022-11-15 04:06
Hi @feerrenrut , Could you please confirm on the above comment?

**Comment by feerrenrut** [comment] 2022-11-15 06:35
@sanketdixit2013, yes or someone else who can reproduce the underlying issue between Chromium and NVDA. Typically, these situations are caused by bugs at the HTML level. The sample allows us to ensure that is not the case, it also makes reproducing the problem easier, as well as investigating the cause.

**Comment by sanketdixit2013** [comment] 2022-11-16 03:35
Ok @feerrenrut. I will try to get the sample from MS.

**Comment by sanketdixit2013** [comment] 2022-11-22 10:39
Hi @feerrenrut 

We would really appreciate if you could provide steps to get this sample? 

This would be helpful as we as bot engineers may be able to get this sample by reproducing this issue on MS Teams using web browser.

Thanks!

**Comment by feerrenrut** [comment] 2022-11-24 04:31
@sanketdixit2013 Yes, you might be able to do it that way. This requires some understanding of the html structure. You'll need to copy the HTML from the application, simplify the sample (by removing elements, attributes etc) and testing that the issue can still be reproduced. The ultimate goal of this is to show that there is some unhandled scenario for NVDA / the browser. Most often however, it turns out that there is some accessibility problem with the web application itself, IE aria-hidden elements, incorrect `role=presentation`, unlabeled elements etc.

**Comment by sanketdixit2013** [comment] 2022-12-14 11:08
Hello @feerrenrut ,

I tried getting the sample. But I'm finding it difficult to get what exactly you will need as sample.  I can chat with the bot via chrome browser in web teams so It would be great if you can mention the steps that I need to follow to get this sample.

Thanks!

**Comment by seanbudd** [comment] 2022-12-14 23:03
You may need to talk to Microsoft engineers. Debugging their platform and building a minimal sample from it is not within our ability or scope.

**Comment by sanketdixit2013** [comment] 2023-01-18 09:23
Hello @seanbudd,

PFA for the minimal html sample for this issue.
[MinimalSample.txt](https://github.com/nvaccess/nvda/files/10444163/MinimalSample.txt)

**Comment by seanbudd** [comment] 2023-01-18 22:33
Thanks @sanketdixit2013

**Comment by sanketdixit2013** [comment] 2023-01-31 09:41
Hello @seanbudd,

Is there any updates regarding this issue?

Thanks!

**Comment by sanketdixit2013** [comment] 2023-02-09 09:29
Hello @seanbudd,

Is there any updates regarding this issue?

Thanks!

**Comment by Adriani90** [comment] 2023-03-02 22:59
Hmm I see here combinations of display:none and aria_hidden=true and also overflow:hidden partially on same divs and separators. I am not sure if these conflict with each other causing objects to appear and disappear very fast from the DOM.
Also using display:flex and flex:direction to implement flexboxes could have an impact on finding child objects while re-focusing an object.
cc: @jcsteh I think your valuable expertise is very welcome here.

@sanketdixit2013 just to make sure, did you run the COM registration fixing tool in NVDA menu under tools? If not, please run it and try again to reproduce the problem.

**Comment by Adriani90** [comment] 2023-03-02 23:15
This seems NVDA specific issue as reported in #13832.

**Comment by jcsteh** [comment] 2023-03-02 23:34
Pressing the buttons in this test case doesn't report unavailable (or anything for that matter) because there is no script attached to them. So, this test case is not sufficient to reproduce the problem.

That aside, it is entirely reasonable for a button to report "unavailable" if pressing the button disables it, which often happens to prevent the user from pressing it twice. The expected results say:
"The screenreader should read it like response is submitted/response sent to an app."
What message are you expecting exactly? If the app doesn't provide such a message (e.g. in a dialog or alert), then no message is going to be reported.

**Comment by Adriani90** [comment] 2023-03-03 00:07
Ah maybe I missunderstood the issue. I thought the author describes a case where NVDA reports „unavailable“ because it looses the focus in the window after pressing the Button. meinem iPhone gesendetAm 03.03.2023 um 00:34 schrieb James Teh ***@***.***>:﻿
Pressing the buttons in this test case doesn't report unavailable (or anything for that matter) because there is no script attached to them. So, this test case is not sufficient to reproduce the problem.
That aside, it is entirely reasonable for a button to report "unavailable" if pressing the button disables it, which often happens to prevent the user from pressing it twice. The expected results say:
"The screenreader should read it like response is submitted/response sent to an app."
What message are you expecting exactly? If the app doesn't provide such a message (e.g. in a dialog or alert), then no message is going to be reported.

**Comment by Adriani90** [comment] 2023-03-03 00:11
But anyway, I think in that case NVDA would report „unknown“ and not „unavailable“Von meinem iPhone gesendetAm 03.03.2023 um 01:07 schrieb Adriani Botez ***@***.***>:﻿Ah maybe I missunderstood the issue. I thought the author describes a case where NVDA reports „unavailable“ because it looses the focus in the window after pressing the Button. meinem iPhone gesendetAm 03.03.2023 um 00:34 schrieb James Teh ***@***.***>:﻿
Pressing the buttons in this test case doesn't report unavailable (or anything for that matter) because there is no script attached to them. So, this test case is not sufficient to reproduce the problem.
That aside, it is entirely reasonable for a button to report "unavailable" if pressing the button disables it, which often happens to prevent the user from pressing it twice. The expected results say:
"The screenreader should read it like response is submitted/response sent to an app."
What message are you expecting exactly? If the app doesn't provide such a message (e.g. in a dialog or alert), then no message is going to be reported.

**Comment by Adriani90** [comment] 2023-03-03 13:55
I think I found a scenario in Microsoft Teams where NVDA reports unavailable, but this is expected behavior.
1. Open MS Teams
2. Choose the tab "chats"
3. Go to "new chat"
4. at this point, you can enter a message iven though you didn't choose a contact
5. navigate to the send button
6. notice NVDA reporting
7. Press enter on the send button
8. Notice NVDA reporting

Result: NVDA reports unavailable on the send button, even though I entered a message in the message edit field. However, when pressing enter on it, the button is activated and NVDA says "please choose a contact".

When I choose a contact but let the message edit field empty, NVDA does not report "unavailable" on the send button. This is actually strange because the send button does not send an empty message. Actually it should report "unavailable" as well. When I press enter on the "send button", NVDA says "please enter a message".

I am testing with NVDA alpha-27769,872db60c (2023.2.0.27769) and Microsoft teams 1.6.0, January 2023 update.

Conclusion: I think this needs to be solved by the app developer. Microsoft needs to put the aria-disabled="true" for any scenarios that meet the relevant conditions in which an user cannot perform an action when pressing the button.

I can imagine that there might be scenarios which are not implemented with aria-disabled="true" on the relevant buttons. Or situations where the aria-disabled="true" is applied on wrong scenarios. But this is not something NVDA can solve.

I am closing this one as works for me, because I couldn't find a scenario in Microsoft Teams where NVDA reports "unavailable" on a valid action like sending a text message to a certain contact.

**Closed by Adriani90** 2023-03-03 13:55 UTC
Labels: close/worksforme, app-specific, p2, triaged, app/ms-teams, blocked/needs-technical-investigation
