### ISSUE TITLE
Characters not reported when deleting by character in VS Code command palette

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#16193] opened 2024-02-19 02:55 UTC
### Steps to reproduce:

1. Launch Visual Studio code, and install Python extension.
2. Go to View -&gt; Command Palette.
3. Type and select &quot;Python : Select Interpreter&quot;, select interpreter option will open.
4. Type any number or word in the textbox.
5. Delete characters using delete
6. Delete characters using backspace

### Actual behavior:

Nothing reporting when deleting character by character.

### Expected behavior:

NVDA should provide feedback as happens in other programs.   User advised that this DOES WORK in the main VS Code editor, and in the VS Code terminal as well as in other places such as WSL and Notepad++

#### NVDA version:

NVDA 2023.3 Installed*

#### Windows version:

Windows 10 and Windows 11

#### Name and version of other software in use when reproducing the issue:

Visual Studio Code*

*This is all I got from the user, I will update as I get more precise information

**Comment by seanbudd** [comment] 2024-02-19 22:36
This needs to be reported to VS Code. Their design choice here is to refocus the results, rather than allow the text changes to be announced.
Closing this as it is not a bug with NVDA, rather a design choice by the developers.

**Closed by seanbudd** 2024-02-19 22:36 UTC
Labels: blocked/needs-external-fix
