### ISSUE TITLE
Chrome 75: NVDA says, "document, blank," when CTRL+Tab is pressed to move to newly opened pages

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#9817] opened 2019-06-26 05:39 UTC
### Steps to reproduce:
Simply open Google.com, search for something, and press Control+Enter on some of the search results to open them as new tabs in the background. Of course, you can also do that by pressing Control+Enter on links in any webpage you have open.

### Actual behavior:
As Control+Tab is pressed to move to the new page or as Control+W is pressed to close the current tab and move to the next tab, NVDA first says, "Document, blank," before reading the title of the newly focused tab page. This is announced for all tab pages which gain focus for the first time, and once a page gains focus, the message isn't announced for a second time upon returning the focus to it.
### Expected behavior:
As Control+Tab is pressed to move to the new page or as Control+W is pressed to close the current tab and move to the next tab, NVDA should read the title of the newly focused tab page.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.1, and 2019.2 Beta 1/Beta 2
#### Windows version:
Windows 10 1903 64-Bit, and Windows 7 64-Bit
#### Name and version of other software in use when reproducing the issue:
Chrome 75. Chrome 74 didn't exhibit this issue.
#### Other information about your system:
Both desktop machine and laptop machine.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Both current official build and the latest two beta releases for 2019.2. Also with add-ons enabled/disabled.

**Comment by Adriani90** [comment] 2019-07-02 21:27
@amirsol81 I cannot reproduce this issue in NVDA alpha-17901,ac6ea147. Could you please test with last alpha version of NVDA and report back? In any case, please run the com registration fixing tool in NVDA menu / tools before testing again. Thanks.

**Comment by Adriani90** [comment] 2019-07-09 18:48
@amirsol81 this is the last reminder before closing this issue. Can you still reproduce it in last NVDA Alpha? I cannot reproduce it.

**Comment by Adriani90** [comment] 2019-07-16 18:09
Closing as works for me. Feel free to comment on it if you are still having this issue.

**Closed by Adriani90** 2019-07-16 18:09 UTC
Labels: worksforme
