### ISSUE TITLE
Appropriate speech dictionary isn't loaded when automatically switching language

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4739] opened 2014-12-21 18:26 UTC
**Reported by burakyuksek on 2014-12-21 18:26**
I have added some entries to the voice dictionary for the turkish language. However, when I switch to an English voice via the quick settings ring, the same entry for Turkish still applies to English.

**Comment by ehollig** [comment] 2017-08-09 18:18
This appears to be a duplicate of #4382

**Closed by ehollig** 2017-08-09 18:18 UTC
Labels: bug, Speech
