### ISSUE TITLE
MS-Excel 2016 Closing Unexpectedly when NVDA 2020.1 is running, NVDA stays open

### ISSUE THREAD

**Issue by britechguy** [nvaccess/nvda#11236] opened 2020-06-08 14:29 UTC
### Steps to reproduce:
1. Open an Excel spreadsheet with focus on the first column header.
2. Open NVDA (Steps 1 and 2 can be in either order)
3. Navigate with tab between column headers.
4. Within a couple of tabs, Excel closes.

**Comment by Adriani90** [comment] 2020-06-08 18:35
Could you please
1. Update your MS Excel 2016 via ffile ribbon > account > update options > check for updates?
2. Try to reproduce this with all add-ons in NVDA disabled?
3. Upload a excel file to this issue so that we can reproduce?

Also are you using a braille display? Or is it reproducible without a braille display?

**Comment by britechguy** [comment] 2020-06-08 18:47
1. Am currently doing a manual update on Excel 2016.

2. Will try both with add-ons functional and disabled to see if there is any difference.

3. Am inquiring with the source of the Excel file as to whether it can be used for sample submission or not.  I am not the primary source of the spreadsheet and am not certain whether it's considered private or not

No braille display is involved.

**Comment by britechguy** [comment] 2020-06-08 19:16
Excel has been updated and the machine had been restarted prior to having done the update.

Error is still present if NVDA Add-ons remain enabled, but disappears when started with Add-ons disabled.  The list of add-ons I currently have installed:
Add-ons documentation
Add-on Updater
BluetoothAudio
Focus Highlight
Golden Cursor
Mozilla Apps Enhancement
NoBeepsSpeechMode
ObjPad
Remote Support
Speech history review and copying
Windows 10 App Essentials

The Excel file I have been using when testing all this out is attached.  I do not dismiss the warning I get about external data connection disabled, and I have protected mode OFF by default for all my MS-Office programs.  I believe you will get a protected mode warning if you do not.
[NDA Report 06-04-2020.xlsx](https://github.com/nvaccess/nvda/files/4748060/NDA.Report.06-04-2020.xlsx)

If you would like for me to go through the steps required to narrow down which add-on is causing the error, let me know.

**Comment by Adriani90** [comment] 2020-06-08 19:22
Thanks for the report, this helps. Could you try following?

1.	Disable focus highlight addon, restart NVDA and try to reproduce.
2.	Let the focus highlight add-on disabled and do the same steps with speech history add-on.
3.	If the issue is still reproducible, do the same with bluetooth audio add-on
4.	Finally try the same with Windows 10 app essentials

 

I am prety sure that either speech history or focus highlight might cause this issue to occur.

Note that focus highlight is deprecated add-on and is not really maintained anymore because the focus highlight feature is already integrated into NVDA’s core.

 

 

Von: Brian Vogel <notifications@github.com> 
Gesendet: Montag, 8. Juni 2020 21:17
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [nvaccess/nvda] MS-Excel 2016 Closing Unexpectedly when NVDA 2020.1 is running, NVDA stays open (#11236)

 

Excel has been updated and the machine had been restarted prior to having done the update.

Error is still present if NVDA Add-ons remain enabled, but disappears when started with Add-ons disabled. The list of add-ons I currently have installed:
Add-ons documentation
Add-on Updater
BluetoothAudio
Focus Highlight
Golden Cursor
Mozilla Apps Enhancement
NoBeepsSpeechMode
ObjPad
Remote Support
Speech history review and copying
Windows 10 App Essentials

The Excel file I have been using when testing all this out is attached. I do not dismiss the warning I get about external data connection disabled, and I have protected mode OFF by default for all my MS-Office programs. I believe you will get a protected mode warning if you do not.
NDA Report 06-04-2020.xlsx <https://github.com/nvaccess/nvda/files/4748060/NDA.Report.06-04-2020.xlsx> 

If you would like for me to go through the steps required to narrow down which add-on is causing the error, let me know.

**Comment by britechguy** [comment] 2020-06-08 21:00
Disabling Focus Highlight stopped the issue from occurring.

I know that Joseph Lee is/was the developer for Add-On Updater, is there no way to have it identify deprecated add-ons and ask if you wish to remove them - sort of the converse of checking if a newer version of an add-on is available?  I'd imagine that at each release of NVDA, where applicable, it would be possible to generate a list of deprecated add-ons for Add-On Updater to check and either remove itself or tell the user to remove it/them.

As an aside, related to Excel, NVDA is not noting that the column headings in are, in actuality, a form of split button when you land on them.  One can filter values displayed in the spreadsheet by using that dropdown for the column in question and checking/unchecking the unique values that Excel finds in each.  I'm sure there is another way, too, but it's the first time I've hit something like this where, by all appearances, we have a split button in functionality, but where the actual label for same is the column heading text, which the user can change, as opposed to a regular split button.  I don't want to open an issue for this if one already exists, but I'm not quite sure how to search for it to make sure it doesn't.

Will have to look through NVDA settings to enable what had been the function of the Focus Highlight Add-On.

Your assistance is appreciated.

**Comment by josephsl** [comment] 2020-06-08 21:05
Hi, I can, but may take a while to go through deprecated add-ons for each NVDA release. The earliest time I can work on it will be July as I’m in vacation. Thanks.

**Comment by britechguy** [comment] 2020-06-08 21:08
Joseph, thanks for this input.  I never expect any changes to code to be immediate or anywhere near to it.  I'm just glad the seed I planted appears to have sprouted where it needed to!

**Comment by Adriani90** [comment] 2020-06-08 21:29
The other issue is already addressed in #5012 and #6065.
I am closing this issue for now since it is not related to NVDA but to a deprecated add-on.

**Closed by Adriani90** 2020-06-08 21:29 UTC

**Comment by XLTechie** [comment] 2020-06-09 01:20
Before you go through and enable each add-on one by one, try first disabling 
Focus Highlight. I don't believe you need it in modern NVDA, and it had some 
very strange bugs for a while.
