### ISSUE TITLE
Browse Mode does not work in Chromium-based Edge or Chrome with UIA enabled

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [nvaccess/nvda#10631] opened 2019-12-17 18:13 UTC
### Steps to reproduce:
1. Install the Microsoft Edge beta from https://www.microsoftedgeinsider.com/en-us/download or Google Chrome from https://www.google.com/chrome/
2. Launch Edge as usual, or launch Chrome with runtime flag --enable-experimental-ui-automation (e.g. "chrome.exe --enable-experimental-ui-automation"
3. Start NVDA and navigate to https://www.nytimes.com
4.  Press the down-arrow to navigate through items in NVDA Browse Mode

### Actual behavior:
Page scrolls with each down-arrow key press 

### Expected behavior:
Page does not scroll with each down-arrow key press - instead items in headers or links are read aloud

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

Chromium has implemented TextPattern support, currently behind a runtime flag "--enable-experimental-ui-automation". Edge Beta has enabled this flag by default.

The source of this bug is that browse Mode in NVDA decides whether to rely on IA2 or UIA based on the FrameworkID of the client application. I verified that changing Chromium's FrameworkID to "MicrosoftEdge" will fall into the NVDA UIA Browse Mode path and function as expected. However, relying on FrameworkID to determine TextPattern support is the real issue here, as Edge's FrameworkID will continue to be "Chrome", as that is the platform that it is based on.

The line of code where this path is decided is here - https://github.com/nvaccess/nvda/blob/ae5027d126db157f6d96440f1d316428e0799907/source/NVDAObjects/UIA/__init__.py#L856

**Comment by leonardder** [comment] 2019-12-18 13:20
Closing as duplicate of #10631

**Closed by leonardder** 2019-12-18 13:20 UTC
