### ISSUE TITLE
Provide alternative in braille to always have the focus object at the start of the line

### ISSUE THREAD

**Issue by leonardder** [nvaccess/nvda#7191] opened 2017-05-22 07:14 UTC
When you move the focus, NVDA tries to fill a braille display with as much relevant information as possible. However, this has the down side that the start position of the focus object presentation differs from time to time.

### Steps to reproduce:
Note: These steps are based on the assumption that there are "This PC" and "Mozilla Firefox" icons on the desktop. Also, there are some cases where Desktop is shown instead of FolderView

1. Set your braille output table to Unified English Braille (grade 1)
2. Disable "Avoid splitting words when possible"
3. Go to the desktop with windows+d, and focus the "This PC" icon
    > Braille output: ⠠⠋⠕⠇⠙⠑⠗⠠⠧⠊⠑⠺⠀⠇⠎⠞⠀⠠⠞⠓⠊⠎⠀⠠⠠⠏⠉⠀⠼⠃⠀⠕⠋⠀⠼⠁⠙
4. Now, focus the Firefox icon:
    > Braille output: ⠑⠗⠠⠧⠊⠑⠺⠀⠇⠎⠞⠀⠠⠍⠕⠵⠊⠇⠇⠁⠀⠠⠋⠊⠗⠑⠋⠕⠭⠀⠼⠁⠁⠀⠕⠋⠀⠼⠁⠙

## Expected behavior:
The problem here is that the start position of the textual icon representation differs if the icon text exceeds a certain length.

Now, what I'd like to suggest here is an option which will always present the focus object at the start of the display. So, for every icon, put the icon text at the start of the display. This has the downside of requiring a user to scroll back in order to read the focus ancestry, but it improves navigation speed for braille oriented users.

### System configuration:
NVDA version: next-14051,e102a7e0

NVDA Installed

Windows version: Windows 10 version 1703 (OS Build 15063.296)

CC @dkager

**Comment by jcsteh** [comment] 2017-05-25 06:47
Duplicate of #217.

**Closed by jcsteh** 2017-05-25 06:47 UTC
