### ISSUE TITLE
nvda does not report correct title of open folder when using new tabs feature in explorer

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#13803] opened 2022-06-16 10:09 UTC
### Steps to reproduce:
I know that this feature on windows is in testing and that improvements and troubleshooting can be done.
But please investigate if nv access should already do something to adapt nvda to the new feature.
download update from windows 11 beta channel
windows 11 version 22,621,160
in addition to having this update if it is not contemplated with the test it may be necessary to enable the new features manually
Now open explorer using the shortcut windows + and
I used the shortcut in the Brazilian Portuguese version of windows, I hope this shortcut is in other languages.
open a folder like example documents.
now press the shortcut to open a new tab in explorer ctrl+t, i didn't find button in the interface to do this action.
Shortcut windows Portuguese Brazil.
alternatively when pressing the application key there is an option to open the folder in a new tab.
Now open another folder like images example.
press ctrl + tab
you switched to the previously opened documents tab
now press nvda + t to read the currently open folder name.
### Actual behavior:
nvda will always report the name of the last opened folder, in this example we are inside the documents folder first opened, but nvda announces images that it was the last opened folder, navigating with the arrows can be sure that the documents folder is currently open.
### Expected behavior:
when opening a folder using open new tab, pressing nvda + t nvda should announce the name of the opened folder correctly, in this case documents.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-25587,fb1ce94d

#### Windows version:
22.621.160
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes
log if it helps
[explorer621.160.txt](https://github.com/nvaccess/nvda/files/8917892/explorer621.160.txt)

**Comment by josephsl** [comment] 2022-06-27 01:26
Hi,

Feedback filed (turns out it affects Narrator as well): https://aka.ms/AAh8lh9

Thanks.

**Comment by rperez030** [comment] 2022-07-21 22:29
I just confirmed that this has been fixed in the latest insiders build. I think this can be closed.

**Comment by josephsl** [comment] 2022-07-21 22:34
Hi, indeed resolved in build 25163, so I expect this will be made available to nickel beta (build 22622) users soon. Thanks.

**Closed** 2022-07-22 00:17 UTC
Labels: platform/Windows11, feature/windows-explorer
