### ISSUE TITLE
Windows 10: NVDA does not interrupt speech when keyboards are switched using windows plus space

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#11058] opened 2020-04-25 01:52 UTC
### Steps to reproduce:
1. Add some keyboards. In this example, I use English (united states) and Serbian Latin.
2. Try holding the windows key down and pressing the space bar continuosly to switch between different keyboards.
### Actual behavior:
NVDA does not interrupt speech as soon as you press space bar to announce the name of the currently active keyboard and instead continues to announce the previous keyboards.
### Expected behavior:
As you hold the windows key and press space, NVDA should interrupt itself each time you press space to announce the keyboard that you switched to
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
alpha-20045,a335297e but happens on all recent versions, stable or alpha.
#### Windows version:
Windows 10 version 1909
#### Name and version of other software in use when reproducing the issue:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Same behaviour is observed on the currently latest stable version, 2019.3.1
#### If addons are disabled, is your problem still occuring?
Yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes

**Comment by Adriani90** [comment] 2020-04-25 11:26
cc: @josephsl, @leonardder

**Comment by amirsol81** [comment] 2020-04-28 09:22
In many ways, this is quite similar to, or related to #9816. I can also duplicate it with Win 10 Pro 2004 64-Bit and the latest NVDA alpha.

**Comment by Adriani90** [comment] 2020-12-08 21:10
cc: @feerrenrut is this something that could be solved via cancelable speech? Currently even if cancelable speech is enabled the reporting is not interupted when pressing windows+space bar multiple times.

**Comment by Qchristensen** [comment] 2021-02-26 01:51
Here is a debug log fragment reproducing this:

IO - inputCore.InputManager.executeGesture (10:07:37.867) - winInputHook (11984):
Input: kb(desktop):windows+space
IO - speech.speak (10:07:37.893) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'space', EndUtteranceCommand()]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (10:07:38.017) - MainThread (8052):
Foreground took too long to change. Foreground still 262168 (Shell_TrayWnd). Should be 4458766 (Shell_InputSwitchTopLevelWindow)
IO - speech.speak (10:07:38.201) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'English (United States) - US keyboard', 'US keyboard']
IO - speech.speak (10:07:48.679) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Japanese - Microsoft IME', 'Microsoft IME']
IO - speech.speak (10:07:49.540) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'French (France) - French keyboard', 'French keyboard']
IO - speech.speak (10:07:50.231) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'German (Germany) - German keyboard', 'German keyboard']
IO - speech.speak (10:07:50.730) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Bengali (India) - Bangla – INSCRIPT keyboard', 'Bangla – INSCRIPT keyboard']
IO - speech.speak (10:07:51.306) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Spanish (Mexico) - Latin American keyboard', 'Latin American keyboard']
IO - speech.speak (10:07:51.921) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'English (Australia) - US keyboard', 'US keyboard']
IO - speech.speak (10:07:53.154) - MainThread (8052):
Speaking [LangChangeCommand ('en_US'), 'Taskbar']
IO - inputCore.InputManager.executeGesture (10:07:56.906) - winInputHook (11984):
Input: kb(desktop):NVDA+f1

Note that "Speech interrupt for typed characters" is enabled in NVDA's keyboard settings.
Also note, with "Report object descriptions" enabled in NVDA's object presentation settings, when reading any language, NVDA reads the keyboard information twice.

**Comment by Adriani90** [comment] 2023-09-16 19:45
This is fixed when enabling cancellable speech after focus event expired in NVDA advanced settings.

**Comment by Adriani90** [comment] 2023-09-17 11:05
Since cancellable speech is the default behavior, I am closing this issue as works for me.

**Closed by Adriani90** 2023-09-17 11:05 UTC
Labels: close/worksforme
