### ISSUE TITLE
[bug report] typing Korean characters and reading word in keyboard settings issue

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#7305] opened 2017-06-20 01:38 UTC
Hello, I'm Hyongsop Kim in Korea and NVDA user.
In NVDA keyboard settings, I set to read word checked and unchecked of read character.
By the way, if I type English, NVDA read words whenever I press space key, but in Korean characters it is not work.
To test, open notepad and type some Korean characters such as dkssud and hit space.
NVDA say nothing even if keyboard typed word reading is checked.
Please check this issue.

Thank you.

**Comment by josephsl** [comment] 2017-06-20 02:06
CC @michaelDCurran

**Comment by ehollig** [comment] 2017-09-13 01:46
Duplicate of #2762

**Closed by ehollig** 2017-09-13 01:46 UTC
