### ISSUE TITLE
NVDA reads to many column headers in Chrome

### ISSUE THREAD

**Issue by bramd** [nvaccess/nvda#9426] opened 2019-03-31 18:05 UTC
### Steps to reproduce:
1. Open `data:text/html,<table><thead><tr><th>One</th><th>Two</th></tr></thead><tr><td>Foo</td><td>Bar</td></tr><tr><th>Three</th><th>Four</th></tr></table>`
1. Read the table either by continuous reading or by navigating from cell to cell

### Actual behavior:
1. NVDA reads "One" and "Three" as header of "Foo" in Chrome
1. NVDA reads "Two" and "Four" as header of "Bar" in Chrome

### Expected behavior:

1. NVDA only reads the headers in the first row ("One" and "Two" respectively), this works fine in Firefox and Edge

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.1

#### Windows version:
Windows 10, build 1809

#### Name and version of other software in use when reproducing the issue:
Chrome 73

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA?
No

**Comment by bramd** [comment] 2019-03-31 22:20
This seems to be an issue in Chrome's IATableCell interface. I filed this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=947881

**Comment by Adriani90** [comment] 2020-04-19 14:50
@bramd could you please comment on the Cromium bug so it gets triaged again? I have the feeling that they will close it without any solution and in my view this issue is very important.

**Comment by Adriani90** [comment] 2020-04-19 15:12
I think this is a duplicate of  #3245.

**Comment by Adriani90** [comment] 2020-04-19 15:13
Closing as duplicate.

**Closed by Adriani90** 2020-04-19 15:13 UTC
Labels: close/duplicate
