### ISSUE TITLE
[Firefox] Button Focus is not announced as they are in other browsers (Focusing with Javascript)

### ISSUE THREAD

**Issue by kylesavoca** [nvaccess/nvda#9579] opened 2019-05-16 16:41 UTC
We have an issue with a focusing on a <button type="button">Play </button> that swaps out to a pause button when pressed, and then forcing focus after said swap. The button has a child element, a visually hidden span that is read when toggling & focusing.
When clicked to pause or play the carousel, the button is swapped for a new button, and in JavaScript we are forcing focus on the new button. 
In every browser using NVDA this works fine, except for Firefox. The state change is not read for some reason. This works in iOS with voice over as well. 

We tried a few solutions here, like adding aria-label to the button rather itself; and added aria-live="assertive"; and that didn't quite do the trick. We had to add additional logic before it worked in Firefox, which involved setting the aria label to an empty string and then immediately back to its intended value. This, along with aria-live did the trick in Firefox.

    node.setAttribute("aria-label", "");
    node.setAttribute("aria-label", label);

However, this made it read twice in every other browser besides Firefox, and on iOS devices with voice over.  We tried several combinations above the above solutions. 

### Expected behavior:
The toggling of buttons, focusing on a button with javascript should read the same across all browsers and devices. 

#### NVDA version:
2018.4.1

#### Windows version:
Windows 8.1

#### Name and version of other software in use when reproducing the issue:
Firefox 65

#### Other information about your system:
Running Windows 8.1 on a Virtualbox VM

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment] 2019-05-16 18:46
@kylesavoca could you please test also with NVDA 2019.1.1? Is there the same issue?
cc: @jcsteh

**Comment by Brian1Gaff** [comment] 2019-05-17 07:36
Would be interesting to know if waterfox has this issue, as its based on 
older code of Firefox, and wondered if this is in fact just a firefox bug?
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by DrSooom** [comment] 2019-05-17 16:53
I suggest to wait for Firefox 67.0 which should be released next week.

**Comment by Adriani90** [comment] 2019-08-23 08:44
@kylesavoca do you still see this issue in NVDA 2019.2?
cc: @MarcoZehe

**Comment by Adriani90** [comment] 2019-11-21 19:51
Unfortunately we cannot reproduce this issue due to a missing minimal test case. Please comment on this issue if you have a minimal test case and we can reopen it. I am closing this as of now since we did not get any answer from the initial author. Thanks.

**Closed by Adriani90** 2019-11-21 19:51 UTC
Labels: Firefox
