### ISSUE TITLE
Unable to turn off reporting of spelling errors when using mail for windows 10

### ISSUE THREAD

**Issue by ghost** [nvaccess/nvda#7947] opened 2018-01-30 01:25 UTC
I'm running the beta version of NVDA, whitch is 2018.1, and when I type a message in the mail app for windows10, it keeps saying spelling error, so I went into the setting into the mail app, to see if it was disabled, and it doesn't say if the spelling button is checked, either way, it justsays spelling error. Other than that, the snapshot of NVDA works better then the final release whitch is 2017.4

**Comment by ehollig** [comment] 2018-01-30 03:31
Hello @BEdenhofer. If you are running the Master or next versions of NVDA, (Beta and Alpha, respectively), you may experience some issues as there is bleeding edge code that is a part of items being tested for possible inclusion in the next release. For this issue, however, it sounds as if you may have the spelling error check box in the document formatting settings checked. If unchecking this box, does this fix the issue?

**Comment by BEdenhofer** [comment] 2018-01-30 23:39
No it doesn't fix the issue my friend, it doesn't tell me if the spelling button is checked or unchecked. Thank you so verry kindly my kind friend, I'm glad we can be a team to develop NVDA! perhaps you may want to subscribe to my NVDA mailing list on groups.io the address to subscribe is, nvdadiscussion+subscribe@groups.io

**Comment by ehollig** [comment] 2018-01-31 01:00
I think I understand. There is a spell check button in the Windows 10 Mail app Settings, and NVDA does not indicate if it is pressed or not pressed. If this is not correct, please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead. CC @josephsl for more information on Windows 10 Mail

**Comment by josephsl** [comment] 2018-02-17 00:18
Hi,

I'm not clear as to what's going on here. Did unchecking "Play sound for spelling errors while typing" checkbox in keyboard settings help? If it didn't, I need exact steps to reproduce this problem. I also need this info because we need to change the issue title, as just saying "NVDA" as the issue title is so generic (for me, even if someone mentions my ID, I won't even look at this issue if the issue title is so generic; others may have different opinions).

Thanks.

**Comment by josephsl** [comment] 2018-02-17 00:18
Hi,

As a follow-up: can we NOT use GitHub issue tracker to advertise mailing lists please?

Thanks.

**Comment by BEdenhofer** [comment] 2018-02-18 13:53
No problem my kind friend, I won't mention my mailing list

**Comment by BEdenhofer** [comment] 2018-02-18 13:54
No problem my kind friend, I will respect your wishes Joseph

**Comment by ehollig** [comment] 2018-02-27 02:38
@BEdenhofer, I noticed that you reopened this issue. Did unchecking the spelling error check box in the document formatting settings help with this issue? If not, could you please be more specific what the issue you are experiencing is? Please provide exact detailed steps to reproduce, including what you did, what you expected to happen and what happened instead.

**Comment by Adriani90** [comment] 2019-05-01 11:24
@ghost are you still having this issue in Windows 10 mail with NVDA 2019.1.1? I assume this could be related to #7917. cc: @Qchristensen

**Comment by Qchristensen** [comment] 2019-05-20 07:28
When I test in Windows 10, 18362.1 (May 2019 update) with NVDA 2019.1, by opening Windows mail, creating a new message, and moving to the body and typing:

- With reporting of "spelling errors" enabled in NVDA's document formatting settings, spelling errors are reported correctly, but no other words are reported as spelling errors.
- With reporting of "spelling errors" disabled, spelling errors are not reported.

That all seems to be working for me.

**Comment by Adriani90** [comment] 2023-05-05 19:38
Closing as works for me as per Quentin's comment above.

**Closed by Adriani90** 2023-05-05 19:38 UTC
Labels: close/worksforme
