### ISSUE TITLE
NVDARemoteHelper: (Injection terminate. error waiting for local thread to die; already dead or not responding. - reference: issue #3944 

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#9380] opened 2019-03-17 03:26 UTC
Hello,
My fiancee receives this message each and every time she quits NVDA on her work-issued Toshiba Notebook, running Windows 10 64 bit, which is connected to a corporate network. 
Message start:
NVDARemoteHelper: (Injection terminate. error waiting for local thread to die; already dead or not responding.
Message end.
The issue occurs at work, as well as on our personal WiFi. 
It occurs with NVDA 2019.1 Beta, as well as NVDA 2018.4.x.
It occurs with or without add-ons running.
It occurs when running NVDA portably, or from an installed copy, or when running with Admin rights.
I've attempted running the COM Registration Fixing tool...  but the issue persists.
To dismiss the dialogue, it is necessary to alt tab, then escape, after which, exit.wav will play and NVDA closes.
A log is attached which I hope is of assistance. There is no crash dump file available.
Thanks
Sam
 
[nvda.log](https://github.com/nvaccess/nvda/files/2974729/nvda.log)

**Comment by leonardder** [comment] 2019-03-18 09:32
I've seen this last week on a notebook of one of my colleagues. I was able to fix this by removing some obsolete software, including AddGuard, older versions of ZoomText as well as Cyberlink/HP bloadware.

**Comment by zstanecic** [comment] 2019-03-18 09:44
Hi,

How Adguard affects This?

I am using adguard for blocking ads, and o haven’t seen the problem there so far.

How you reproduce it?

**Comment by leonardder** [comment] 2019-03-18 09:51
I wasn't intending to say that AddGuard causes this. I haven't been able to track down the cause of the issue, it's just that the issues was solved after I removed several programs from the particular system, including AddGuard.

**Comment by Adriani90** [comment] 2020-01-19 19:48
@sjtaylor82 are you still seeing this issue with NVDA 2019.3 Beta 2?

**Comment by sjtaylor82** [comment] 2020-01-19 21:38
This problem seems to have disappeared with an IT system refresh. 
Thanks 
Sam 

Sent from my iPhone

> On 20 Jan 2020, at 5:49 am, Adriani90 <notifications@github.com> wrote:
> 

﻿
@sjtaylor82 are you still seeing this issue with NVDA 2019.3 Beta 2?

**Comment by Adriani90** [comment] 2020-01-19 22:23
Thanks for reporting back. I am closing this for now. Feel free to comment on this or open a new issue if the problem comes up again.

**Closed by Adriani90** 2020-01-19 22:23 UTC
Labels: worksforme
