### ISSUE TITLE
Error reading window in chrome

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#7519] opened 2017-08-23 20:08 UTC
Today I received a window in the chrome where nvda can not read the content.
Steps:
Using crome 60 64bit and windows 7 64 bit with nvda master 14328, visit:
Https://www.toppn.com/view/190629.html

Soon to open the link the nvda speaks
Chrome Legacy Window
unknown
When navigating with tabe through the window, nvda pronounces
unknown
It is not possible to navigate with the arrows and also could not alternate of the modes of navigation and exploration with nvda + space.
By pressing nvda + t you are informed:
Privacy error
What he hoped was that nvda could read the error, and could read the options that chrome tells us.
Here's a log:
IO - inputCore.InputManager.executeGesture (17:03:28.400):
Input: kb(laptop):enter
DEBUG - editableText.EditableText._hasCaretMoved (17:03:28.523):
Caret didn't move before timeout. Elapsed: 100 ms
IO - speech.speak (17:03:28.581):
Speaking [u'cursor Inicializa\xe7\xe3o de aplicativo']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:03:30.594):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (17:03:30.612):
Speaking [u'Chrome Legacy Window']
IO - speech.speak (17:03:30.615):
Speaking [u'desconhecido']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:03:30.747):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (17:03:30.760):
Speaking [u'desconhecido']
IO - speech.speak (17:03:30.809):
Speaking [u'cursor Desconhecido']
IO - inputCore.InputManager.executeGesture (17:03:34.168):
Input: kb(laptop):tab
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:03:34.173):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:03:34.184):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IO - speech.speak (17:03:34.191):
Speaking [u'desconhecido']
IO - inputCore.InputManager.executeGesture (17:03:37.746):
Input: kb(laptop):NVDA+f1
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (17:03:37.756):
accRole failed: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (17:03:37.806):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.IAccessible object at 0x06577730>
Python class mro: (<class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: None
value: None
appModule: <'appModuleHandler' (appName u'chrome', process ID 4440) at address 5c1db70>
appModule.productName: u'Google Chrome'
appModule.productVersion: u'60.0.3112.101'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 1836380
windowClassName: u'Chrome_RenderWidgetHostHWND'
windowControlID: 367856304
windowStyle: 1445986304
windowThreadID: 7928
windowText: u'Chrome Legacy Window'
displayText: exception: 'NoneType' object is not iterable
IAccessibleObject: <POINTER(IAccessible) ptr=0x84f8180 at 9ff5d00>
IAccessibleChildID: -165805
IAccessible event parameters: windowHandle=1836380, objectID=-4, childID=-165805
IAccessible accName: exception: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IAccessible accRole: exception: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IAccessible accState: exception: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IAccessible accDescription: exception: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147024809, 'Par\xe2metro incorreto.', (None, None, None, 0, None))

**Comment by PratikP1** [comment] 2017-08-24 00:41
It appears that this is a Chrome window, warning of an insecure connection. Chrome does not show the actual page but a warning  instead. This warning is not accessible.

**Comment by fernando-jose-silva** [comment] 2017-08-24 12:29
Will we be able to enable the ocr for this window while the chrome does not solve, I tried to use the ocr in windows and I heard an error sound, the ocr works in other windows

Enviado do meu iPhone

> Em 23 de ago de 2017, às 21:41, PratikP1 <notifications@github.com> escreveu:
> 
> It appears that this is a Chrome window, warning of an insecure connection. Chrome does not show the actual page but a warning instead. This warning is not accessible.

**Comment by Adriani90** [comment] 2019-04-29 15:24
@fernando-jose-silva are you still having this issue in Chrome 74 and NVDA 2019.1.1? Did you try to run the com registration fixing tool in NVDA menu / tools? Did it solve this problem? I cannot reproduce it.

**Comment by fernando-jose-silva** [comment] 2019-04-30 00:45
Thanks, I no longer have this problem, updated software:
chrome 74
nvda 17110
windows 10 18362
thank you

**Comment by Adriani90** [comment] 2019-04-30 10:20
Closing as works for me.

**Comment by fernando-jose-silva** [comment] 2019-05-01 02:11
I believe that it can close the call, everything works at a reasonable speed now.
everything updated:
nvda 17110
windows 10 18362.

**Comment by ehollig** [comment] 2019-05-09 02:56
Thank you for reporting @fernando-jose-silva. Closing

**Closed by ehollig** 2019-05-09 02:56 UTC
Labels: Chrome, worksforme
