### ISSUE TITLE
Outlook desktop app: When NVDA is loaded, Outlook sometimes crashes when using the F6 and shift-F6 keyboard shortcuts to traverse the panes of the calendar view

### ISSUE THREAD

**Issue by Luke-Robinett** [nvaccess/nvda#14096] opened 2022-09-01 21:09 UTC
### Steps to reproduce:
1. Open Outlook
2. Press control-2 to show the calendar view
3. Press F6 to move into the day navigation section where forward and back buttons are found
4. Press enter or space to activate one of the buttons
5. Press shift-F6 to return to the main area of the calendar

### Actual behavior:

This issue is intermittent but reliably reproduceable with a few tries. Sometimes Outlook behaves normally and sometimes it crashes suddenly.

### Expected behavior:

Focus lands in the main appointment area of the calendar.

### NVDA logs, crash dumps and other attachments:
N/A

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.3.5 but has happened for years across multiple versions

#### Windows version:
Windows 10 Pro

#### Name and version of other software in use when reproducing the issue:
Microsoft Outlook from Office 365 suite

#### Other information about your system:
Dell XPS laptop

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes. Multiple earlier versions of NVDA exhibit the same behavior.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by Yeldece** [comment] 2022-09-07 12:25
Does nvda gets frozen when outlook is loading for you too?

**Comment by FalkoBabbage** [comment] 2022-11-09 10:30
I can reproduce this on my machine as well.
Disabling the CalenderView in the builtin appmodules of outlook seems to "solve" the problem. So I expect that it is the same issue as #12246, which is on hold for an external fix.

**Comment by seanbudd** [comment] 2024-04-29 02:50
Can this still be reproduced with the latest Outlook and NVDA?
Please provide the version of Outlook and NVDA you can reproduce this with.
The issue is missing the Outlook version number.

**Comment by seanbudd** [comment] 2024-04-29 02:51
The next steps to investigating this issue would be creating a crash dump from explorer using [these steps](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps#minidumps-for-other-applications).
Once a crash dump is created we can debug the cause.

**Comment by FalkoBabbage** [comment] 2024-04-29 06:30
I have tested this with NVDA 2024.1 (portable version) with Outlook 365 MSO (Version 2403 Build 16.0.17425.20176) 64-bit and cannot reproduce it anymore

**Comment by seanbudd** [comment] 2024-04-29 07:03
Thanks for confirming - closing for now.  Please let us know if this can be reproduced with the latest Outlook and NVDA

**Closed by seanbudd** 2024-04-29 07:03 UTC
Labels: bug/app-crash, app/microsoft-office, p2, blocked/needs-info, triaged, bug squash target
