### ISSUE TITLE
Navigation problems in outlook

### ISSUE THREAD

**Issue by CoreyQCP** [nvaccess/nvda#10163] opened 2019-09-03 14:18 UTC
You have arrived at a default issue template (bug report).
It is preferable to [choose the type of issue](https://github.com/nvaccess/nvda/issues/new/choose) to submit.
Hint: Swap to the preview tab to be able to click the links.
Direct links to the templates:
- [Bug report](https://github.com/nvaccess/nvda/issues/new?template=bug_report.md)
- [Feature request](https://github.com/nvaccess/nvda/issues/new?template=feature_request.md)

**Comment by Brian1Gaff** [comment] 2019-09-03 17:07
Well as I am reading this first. I think in order to be sure about this one 
needs to know the actual version of Outlook, and the build of windows 10 and 
what add ons are installed, including the win 10 essentials  add on.

It would also be a good idea to check in the latest stable version of nvda 
just to be sure.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by CoreyQCP** [comment] 2019-09-03 17:49
---------------------------
This Message was Encrypted.
---------------------------

Version of Outlook-outlook 2016
build of windows 10-version 1809, build 17763.292
add ons-insights, action items, templates, unsubscribe
win 10 essentials add ons-none found
NVDA has been updated to the latest version as stated in the ticket I opened.

It would also be a good idea to check in the latest stable version of nvda
just to be sure.

**Comment by Adriani90** [comment] 2019-09-03 21:04
@CoreyQCP can you please maximize the outlook windows with windows+up arrow? Does this issue still occure after you maximize the window?
Also please go to the NVDA menu in Extras and run the com registration fixing tool. Please report back if the issue is still occuring or not.

**Comment by Adriani90** [comment] 2020-05-13 10:31
I cannot reproduce this with NVDA 2020.1 in Outlook 2010 or Outlook 2016 or 365. Closing as works for me. Please comment on this issue if my suggestions above did not help and we can reopen.

**Closed by Adriani90** 2020-05-13 10:31 UTC
Labels: close/worksforme
