### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Menu Bar_Schema Compare_Screenreader: Improper focus order observed when activated 'Compare' or 'Stop' buttons while JAWS is on.

### ISSUE THREAD

**Issue by ShwetaBaglane** [nvaccess/nvda#10122] opened 2019-08-20 11:12 UTC
[“Check out Accessibility Insights! !](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.10.0-insider (user setup)
Commit: 1ff9a2ec4c7b88be01666bdd470bbbb4ab95716e
Date: 2019-08-09T07:49:00.254Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
JAWS Serial no: 32810

**Additional Details:**
Tools Name: JAWS
MAS References: MAS1.3.2

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Start screen reader as JAWS.
11. Navigate to 'Compare' button and hit Enter. 
12. Navigate to 'Stop' button and hit Enter. 

**Actual:**
When activated 'Compare' or 'Stop' buttons, screen reader moves focus to File menu item and announces as 'File Alt+fEdit Alt+e Ciew Alt+v Help Alt+h'.

**Expected:**
When activated 'Compare' or 'Stop' buttons, screen reader moves focus should not be moved to File menu item.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: (https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
Screen reader users will face difficulty while activated compare/ stop button as focus order is improper and will get information about File menu Item which is not present on schema compare screen.

**MAS Reference:**
MAS 1.3.2-
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1ee227a7-e3c5-47b8-ab18-48ca8595077b}

**Attachment for Reference:**
[A11y_AzureDataStudio(Schema,Dacpac,Backup)_Select Source-Target_Schema Compare_Screenreader.pptx](https://github.com/nvaccess/nvda/files/3520213/A11y_AzureDataStudio.Schema.Dacpac.Backup._Select.Source-Target_Schema.Compare_Screenreader.pptx)

**Comment by Adriani90** [comment] 2019-08-20 12:16
Just to make sure, did you test this with NVDA 2019.2? Or only with Jaws?

**Comment by ShwetaBaglane** [comment] 2019-08-20 12:19
I tested it with both tools but this issue repro with Jaws only.

**Comment by Adriani90** [comment] 2019-08-20 14:01
Ok, in this case I am afraid but we cannot help in this regard since thiss repository is for NVDA issues only. If you want to report an issue with Jaws, you could do it here:
https://github.com/FreedomScientific/VFO-standards-support/issues
I am closing this for now as invalid because it seems with NVDA this issue is not reproducible. However, if you have this issue with NVDA, please feel free to comment and we can reopen it. Thanks.

**Closed by Adriani90** 2019-08-20 14:01 UTC
Labels: invalid
