### ISSUE TITLE
Sometimes when navigating quickly between folders in Windows Explorer on Windows 7 current item is not read in recent Alpha snapshots

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#10491] opened 2019-11-14 16:18 UTC
### Steps to reproduce:
It is not reproducible 100% of the time, but happens when quickly navigating in Windows Explorer under Windows 7.

### Actual behavior:
Error sound is played twice, name of the folder with focus is not announced, and the following is in the log:
ERROR - comtypes._comobject.call_without_this (17:05:33.935) - Dummy-1 (6640):
Exception in IUIAutomationFocusChangedEventHandler.HandleFocusChangedEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 328, in IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event   can not invoke any of its subscribers.(None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (17:05:34.025) - Dummy-2 (5308):
Exception in IUIAutomationFocusChangedEventHandler.HandleFocusChangedEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 328, in IUIAutomationFocusChangedEventHandler_HandleFocusChangedEvent
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'An event   can not invoke any of its subscribers.', (None, None, None, 0, None))

### Expected behavior:
The folder name should be announced.
#### NVDA installed/portable/running from source:
Tried with a portable on my main system, and with an installed one on my secondary computer- happens in both cases.
#### NVDA version:
NVDA version alpha-19146,d473de81
#### Windows version:
Windows 7 pro X64
#### Name and version of other software in use when reproducing the issue:
Windows Explorer
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No such problems with 2019.2.1
## Additional information's.
I believe this is caused by #10393. 
With 2019.2.1 in such situations NVDA falls back to MSAA which is visible, because name of the folder is announced twice.

cc @leonardder

**Comment by josephsl** [comment] 2019-11-14 16:23
CC @LeonardDer

**Comment by Brian1Gaff** [comment] 2019-11-14 16:31
Yes it happens rarely here but did this morning. Another funny generally 
with windows 7 on most flavours of nvda is sometimes I  does not spot you 
opened a new folder, and you have to alt tab away and back again, as if 
something vital was not seen by the screenreader. Most peculiar.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by leonardder** [comment] 2019-11-14 18:19
Hmm. I don't think this could be caused by #10393. #10393 only makes comtypes log errors in the NVDA log, it does not change anything related to the behavior of the UIA handler. Without #10393, these errors are still there, they are simply not logged.

**Comment by leonardder** [comment] 2019-11-18 09:20
I guess the first step would be finding out whether #10393 is the cause. 
Though I'm pretty sure this isn't the case, I could be wrong of course. 
Proper way would probably be checking the alpha before and after this pr 
was merged.

**Comment by lukaszgo1** [comment] 2019-11-19 10:07
I've taken slightly different approach, i.e. tried working with build from PR #10397 for an hour, and these errors never occurred. @leonardder Would it be possible to include  #10397 into 2019.3?

**Closed** 2019-11-19 22:17 UTC
