### ISSUE TITLE
NVDA brows mode mangling clipboard contents

### ISSUE THREAD

**Issue by pranavlal** [nvaccess/nvda#5895] opened 2016-04-21 14:30 UTC
If I am on a webpage in Firefox or Internet explorer and copy a table into Excel, the formatting of the table is mangled. 
The same happens if I am in brows mode in Microsoft Word and try to copy a table and paste it into Excel. 

The table is transposed such that all the data comes in a single column but in a series of rows. If I want to retain formatting, then I have to copy data to the windows clipboard  after quitting NVDA.

To duplicate the problem, try the following.
1. Go to a webpage with a table.
2. Copy the table to the clipboard. You must use the keyboard and have NBDA running.
3. Swap to Excel and paste the table.
You will find the formatting mangled. 

Repeat the above experiment but this time, quit NVDA before copying the data to the clipboard. Paste the data into Excel. The formatting will be retained. 

You can try the experiment with Outlook too. Try copying a table from a message in Outlook to Excel. The formatting will be mangled if brows mode was active when you copyed the table to the clipboard.

nvda version = 2016.1
word versions: 2010 and 2016. This issue is universal.

**Comment by jcsteh** [comment] 2016-04-21 22:58
On the web, NVDA browse mode can't retain formatting when copying. This 
is an extremely difficult problem to solve and isn't likely to change 
any time soon, unfortunately.

In Word, we should change things so that we use Word's own copy command 
instead of our own.

CC @MichaelDCurran.

**Comment by Brian1Gaff** [comment] 2016-04-22 07:58
What happens in pdf  reader though. almost anything from my standpoint!
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal email to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
----- Original Message -----

**Comment by pranavlal** [comment] 2016-04-22 16:03
The same problem persists.

**Comment by ehollig** [comment] 2017-08-20 21:31
Closing as duplicate of #5354

**Closed by ehollig** 2017-08-20 21:31 UTC
