### ISSUE TITLE
NVDA read all text while reading word by word, in an edit field under chrome

### ISSUE THREAD

**Issue by abdullah5490** [nvaccess/nvda#7372] opened 2017-07-10 22:57 UTC
After fixing the issue #6699 by adding #7201 in the master build, the NVDA is now navigating absolutely fine as character by character. but when I try to read word by word in an edit field under chrome, it read out all the content in that field, not each word one by one. For example, after typing this comment in the edit field using chrome, I pressed ctrl+right/left, it read my whole text written in this edit field. Not each word. This is only the case of chrome. in firefox, it just work fine.

**Comment by derekriemer** [comment] 2017-07-11 12:05
[**@abdullah5490**](https://github.com/abdullah5490) commented on [Jul 10, 2017, 4:57 PM MDT](https://github.com/nvaccess/nvda/issues/7372#issue-241876112 "2017-07-10T22:57:58Z - Replied by Github Reply Comments"):
> After fixing the issue #6699 by adding #7201 in the master build, the NVDA is now navigating absolutely fine as character by character. but when I try to read word by word in an edit field under chrome, it read out all the content in that field, not each word one by one. For example, after typing this comment in the edit field using chrome, I pressed ctrl+right/left, it read my whole text written in this edit field. Not each word. This is only the case of chrome. in firefox, it just work fine.

Which version of chrome?

**Comment by abdullah5490** [comment] 2017-07-11 17:51
@derekriemer its Version 59.0.3071.115 (Official Build) (64-bit). Language english.

**Comment by Adriani90** [comment] 2019-04-24 12:44
@abdullah5490 I cannot reproduce this issue in Crhome 74. Are you still having this problem in NVDA 2019.1.1 in Crhome? If yes, is this issue happening in every edit field? Or only on example websites?

**Comment by abdullah5490** [comment] 2019-04-29 06:27
Hello there. no, this issue is now resolved, i'm testing it with chrome 74, and its working fine. you can now close this issue number.

**Comment by Adriani90** [comment] 2019-04-29 07:26
Thanks for reporting back. Closing as works for me.

**Closed by Adriani90** 2019-04-29 07:26 UTC
Labels: Chrome, worksforme
