### ISSUE TITLE
Edge: aria-pressed is exposed by NVDA as a checkbox rather than pressed/unpressed state.

### ISSUE THREAD

**Issue by PratikP1** [nvaccess/nvda#6981] opened 2017-03-15 23:02 UTC
The example below is exposed as a pressed/unpressed button by Narrator. Tested in NVDA version next-13926,0bb293f3 and Windows 10 insider build 15058.

STR:
1. Open Edge.
2. Go to addressbar by pressing alt+d.
3. Visit the following page: https://ibma.github.io/Va11yS/ARIA/ARIA5_example1.html
4. Examine the "bold label" button.

**Comment by jcsteh** [comment] 2017-03-15 23:30
Confirmed.

I fixed this for UIA in general in #5441 (aade0a3e). However, the role property is being overridden in EdgeNode. It maps the role based on the UIA ARIA role property, but that overrides the logic to figure out whether a button is a toggle button in the base UIA object. We must not override the superclass role for ARIA role button.

P3 because this is a bit silly, but the user still understands the fundamental intent of the author.

**Comment by PratikP1** [comment] 2017-03-15 23:33
I only reported this one because the behavior is distinctly different in FF and Chrome, both of which do it right.

**Comment by michaelDCurran** [comment] 2017-03-23 23:58
Technical info:
EdgeNode NVDAObject's role property always overrides the base UIA role logic with ARIA role if it exists. But in this case, the ARIA role is button, where it was already correctly toggleButton as it was it had a UIA controlType of button and the toggleState pattern existed. As the needed change will probably conflict with the edgeSpeedup code currentinly incubating, we should wait until that is in master before fixing this. This is certainly not high impact -- the control can still be used easily enough.

**Comment by PratikP1** [comment] 2017-06-22 16:00
Update: the url I reference in my steps has been updated to https://ibma.github.io/Va11yS/WCAG_ARIA/ARIA5_example1.html

**Comment by Adriani90** [comment] 2020-04-24 23:53
This is exposed and reported correctly by NVDA in Edge Chromium 81. Closing as works for me.

**Closed by Adriani90** 2020-04-24 23:53 UTC
Labels: app/edge, blocked, close/worksforme, p3
