### ISSUE TITLE
regression in VSCode cursor performance since 2020.1

### ISSUE THREAD

**Issue by camlorn** [nvaccess/nvda#11601] opened 2020-09-13 01:17 UTC
### Steps to reproduce:

1. Install NVDA 2020.2
2. Open a project that lets you edit stuff.  This is known to be broken with [Synthizer](https://github.com/synthizer/synthizer) but I've got at least one other friend complaining about it as well with whatever they do with VSCode, so it's probably not specific to that or to my config.
3.  Arrow around.  Watch as NVDA lags.

### Actual behavior:

90% of the time it lags.  If you arrow quickly, you can get it to drop cursor updates and skip characters (the cursor moves but NVDA skips announcing them).  Sometimes it's normal for really brief periods, and restarting NVDA seems to make it a little bit better but by no means normal.

I tried against a portable copy of 2020.1 and it works fine.  VSCode version is currently 1.48.2, but this has been going on for at least a few updates and I just haven't had the chance to report it.

### Expected behavior:

Not this.

#### NVDA installed/portable/running from source:

verified against 2020.2 installed and portable both.

#### NVDA version:

2020.2

#### Windows version:
Windows 10 Pro 1903.

#### Name and version of other software in use when reproducing the issue:
VSCode is 1.48.2 currently but as above it's happened in at least the last few updates.

#### Other information about your system:
This is a hex-core workstation with 64GB of ram and NVDA doesn't lag in anything else I use regularly, so it's unlikely to be system specs.

#### Does the issue still occur after restarting your computer?

Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2020.1 doesn't reproduce.
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no change.

**Comment by bradjrenshaw** [comment] 2020-09-13 01:26
I'm having the same issues plus a few others:

* The first time I open a file, NVDA freezes for at least 3 to 5 seconds (has been longer for larger files)
* The lag seems to get worse in general the longer VSCode is open
* this lag applies to the tree view as well, though far less severely
* When InteliSense shows suggestions, the lag gets exponentially worse while the popup is there

I can confirm that NVDA 2020.1 has no lag as well.

**Comment by Adriani90** [comment] 2020-09-13 09:31
cc: @leonardder I think there is already an issue for this. Could you please have a look?

**Comment by Adriani90** [comment] 2020-09-13 10:04
I found  the duplicate issue, it is #11533. Closing this in in favour of #11533.

**Closed by Adriani90** 2020-09-13 10:04 UTC
Labels: close/duplicate

**Comment by akash07k** [comment] 2020-09-14 07:09
I don't think that this is entirely related to #11533  since that issue reproduces even with NVDA 2019.2 and here in this issue, the reporter has mentioned that he is only having this issue with NVDA 2020.2
So, I think that this should be treated a different issue instead of duplicated one.
