### ISSUE TITLE
Windows 10: brightness button changes not announced

### ISSUE THREAD

**Issue by JamaicanUser** [nvaccess/nvda#5603] opened 2015-12-13 16:38 UTC
When I press the Brightness button, which toggles the brightness between 25, 50, 75 and 100, NVDA does not give any feedback. The user has to use object navigation to find out this information. Is there a workaround?

**Comment by jcsteh** [comment] 2015-12-13 22:49
What brightness button where? Please provide exact steps to reproduce.

**Comment by JamaicanUser** [comment] 2015-12-14 00:27
The one in Action Center. If I wanted to find out my current brightness setting, I'd have to press NVDA+NUMPAD 4 and then NVDA+NUMPAD 6. On further ispection, forget that I said it toggles between fixed percentage levels, as it varies.

**Comment by jcsteh** [comment] 2015-12-14 01:50
Looks like the value is exposed as a text child of the button, but the 
button's label doesn't change. Worse, the button exposes the toggle 
pattern, but it's not really a toggle. This makes absolutely no sense.

**Comment by ehollig** [comment] 2017-07-31 18:47
I do not see a brightness button in the action center. Can someone provide a clear STR? @jcsteh @josephsl

**Comment by ruifontes** [comment] 2017-07-31 21:25
1 - Press Windows+A;
2 - If you land in Expand quick Actions, press Enter to expand;
3 - Tab once and with the arrows look by Brightness button. In my case is 8 
of 16...;

By the way, NVDA announces 16 items but only shows 15...

Rui


-----Mensagem Original----- 
De: Ethan Holliger
Data: 31 de julho de 2017 20:10
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Windows 10: brightness button changes not 
announced (#5603)



I do not see a brightness button in the action center. Can someone provide a 
clear STR? @jcsteh @josephsl

**Comment by jcsteh** [comment] 2018-10-15 21:49
Oops. I just opened duplicate #8845. However, I'm going to close this one as a duplicate, as the steps to reproduce are clearer in that issue, as are the technical details of how we can hack around this in NVDA.

**Closed by jcsteh** 2018-10-15 21:49 UTC
