### ISSUE TITLE
Crash with NVDA and 2016.1 Rc in windows explorer.

### ISSUE THREAD

**Issue by derekriemer** [nvaccess/nvda#5764] opened 2016-02-21 03:53 UTC
Win 8.1 NVDA 2016.1  64 bit windows.
From the about dialog:
NonVisual Desktop Access (NVDA)
Version: rc-13230,fc1e3c3b
Oddly, this never occurred until I ran the latest batch of updates from microsoft and just started occurring today.

I can reliably reproduce this.
DEBUGWARNING - watchdog._watcher (20:42:34):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 190, in <module>
  File "core.pyc", line 382, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 352, in Notify
  File "IAccessibleHandler.pyc", line 872, in pumpAll
  File "IAccessibleHandler.pyc", line 654, in processFocusWinEvent
  File "IAccessibleHandler.pyc", line 521, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 279, in isUIAWindow
  File "_UIAHandler.pyc", line 273, in _isUIAWindowHelper

DEBUGWARNING - IAccessibleHandler.accessibleObjectFromEvent (20:42:34):
oleacc.AccessibleObjectFromEvent with window 395294, objectID 16181 and childID 0: [Error -2147467259] Unspecified error
DEBUGWARNING - watchdog._watcher (20:42:35):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 190, in <module>
  File "core.pyc", line 382, in main
  File "wx_core.pyc", line 8657, in MainLoop
  File "wx_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 353, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 61, in _queueEventCallback
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 107, in setFocusObject
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 1491, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 475, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\IAccessible__init__.pyc", line 1477, in _get_parent
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\window__init__.pyc", line 266, in _get_parent
  File "NVDAObjects__init__.pyc", line 184, in findBestAPIClass
  File "NVDAObjects\window__init__.pyc", line 102, in getPossibleAPIClasses
  File "_UIAHandler.pyc", line 279, in isUIAWindow
  File "_UIAHandler.pyc", line 273, in _isUIAWindowHelper
  File "watchdog.pyc", line 175, in _crashHandler
  File "logging__init__.pyc", line 1204, in critical
  File "logHandler.pyc", line 113, in _log
  File "logging__init__.pyc", line 1278, in _log
  File "logging__init__.pyc", line 1288, in handle
  File "logging__init__.pyc", line 1328, in callHandlers
  File "logHandler.pyc", line 197, in handle

CRITICAL - watchdog._crashHandler (20:42:35):
NVDA crashed! Minidump written to C:\Users\derek_2\AppData\Local\Temp\nvda_crash.dmp
INFO - watchdog._crashHandler (20:42:37):
Restarting due to crash
DEBUG - audioDucking._unensureDucked (20:42:37):
Decreased  ref count, _duckingRefCount=0

Dump attached.
1. Go to a folder. 
2. Go to the insert new item menu item of the ribbon.
3. Make sure you open the one that brings up the menu of different file types.
4. Select new text document. 
5. Type some text there.
6. Press enter to save the document.

On my machine, NVDA crashes reliably every time. Watchdog does reboot it though. It pauses for about 2 seconds before this happens. The text of the dump summary is pasted and for good measure I attached it. I changed the .dmp extention to .txt so github will accept it. You can change it back. I attached it in case I didn't extract everything. I am going to do some more debugging on this tonight and try to hunt something more down because we are like a day away from release. I am going to try reinstalling NVDA, downgrading, upgrading to master than next, and see how reliably I can get this to occurr.

**Comment by derekriemer** [comment] 2016-02-21 03:57
[nvda_crash.dmp.txt](https://github.com/nvaccess/nvda/files/139449/nvda_crash.dmp.txt)

**Comment by derekriemer** [comment] 2016-02-21 03:59
Speak of the devil, now I can't get it to occur again to produce more crashes to see what patterns there are. If I can get it to crash again I will let you know, otherwise it might be a buggy windows explorer session or something like that.

**Comment by jcsteh** [comment] 2016-02-21 17:15
Looking at the logged Python trace, it looks like UiaHasServerSideProvider crashed. However, I can't seem to see this function anywhere in the crash dump, which is very odd. I need to examine this again with the symbols for Python 2.7.11, but unfortunately, I suspect we're out of luck with this one.

**Comment by jcsteh** [comment] 2016-02-21 23:27
As suspected, adding python symbols doesn't reveal anything either. It seems to be crashing before it even hits UiaHasServerSideProvider, which is really odd. I also can't reproduce this locally.

**Comment by derekriemer** [comment] 2016-02-22 00:12
It doesn't seem that I am able to reproduce this anymore either so it might have just happened a couple of times for some reason. I just thought it was odd how it randomly occurred right after I did an update.

Sent from my iPhone
Please disregard errors as this is a smaller device.

**Comment by michaelDCurran** [comment] 2016-11-02 00:04
Closing due to inability to reproduce and the fact this is a dump from an old snapshot. If this can be reproduced reliably with 2016.3 or newer please reopen and attach a new dump and an NVDA log (which will now contain stacks for all Python threads).

**Closed by michaelDCurran** 2016-11-02 00:04 UTC
Labels: blocked, crash, p1
