### ISSUE TITLE
issues with Youtube and NVDA.

### ISSUE THREAD

**Issue by audiogamer22** [nvaccess/nvda#10278] opened 2019-09-25 23:53 UTC
NVDA reads the list of videos under the play/pause section after clicking on a video you search for.
### Steps to reproduce:
Go to youtube.com and search for something, then, press enter on a video and NVDA will start reading out the list of videos below the play/pause section of the site.

### Actual behavior:
NVDA reads out the videos in the list of videos on the site. Pressing control only stops it until it reaches the next video in the list.
### Expected behavior:
Once the video I search for has loaded, pressing control should stop NVDA from speaking.
#### NVDA installed/portable/running from source:
installed.
#### NVDA version:
2019.2
#### Windows version:

Version	10.0.17763 Build 17763

#### Name and version of other software in use when reproducing the issue:
The latest version of firefox and chrome.
#### Does the issue still occur after restarting your PC?
Yes.

**Comment by leonardder** [comment] 2019-09-26 05:01
I've also seen this.

cc @derekriemer

**Comment by JulienCochuyt** [comment] 2019-09-26 06:55
The suggestions are also announced when in sleep mode.
I guess they put them in a live region.
PR #9079 would come in handy if https://github.com/nvaccess/nvda/pull/9079#issuecomment-495149844 is taken into account, which would either allow WebAccess to do the trick or be a step towards fixing #7743.

**Comment by munawarb** [comment] 2019-10-15 11:59
I can also reproduce this. If they have done this using live regions it will be nice to have a feature to turn off certain live regions. These settings could be remembered on specific pages, just like JAWS and it's page-specific settings. IMO NVDA needs better customization in this area anyway.

**Comment by pbsinnett** [comment] 2020-04-09 02:31
Any progress on this? It's currently my biggest annoyance.

**Comment by audiogamer22** [comment] 2020-04-09 03:04
This kind of thing has gone on for a while now.

I put on a video then turn speech mode off.

Of, you can alt tab away from the page or press control a couple times
.Thanks for reading, Brad.

**Comment by Adriani90** [comment] 2020-04-09 20:17
I think @derekriemer works on a pull request which refactors the live region handler. But I am not sure about the current status.

**Comment by Adriani90** [comment] 2024-03-29 19:28
This is not reproducible anymore with NVDA 2024.1 RC1 and Firefox 124, Chrome 125 Canary or Edge 123. Closing as works for me.

**Closed by Adriani90** 2024-03-29 19:28 UTC
Labels: bug, close/worksforme, ux
