### ISSUE TITLE
NVDA IS NOT READING THE ALERT MESSAGE

### ISSUE THREAD

**Issue by pratik-pk** [nvaccess/nvda#8681] opened 2018-08-27 09:23 UTC
### Steps to reproduce: unzip the folder and open the html page on nvda supportable browser.

                                         click on the page and than use tab key to move to follow button.
                                          press enter key. A alert msg will open.

**Comment by leonardder** [comment] 2018-08-27 09:26
Did you intend to add an attachment? If so, it did not come through, it seems.

**Comment by pratik-pk** [comment] 2018-08-27 09:32
`<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
}

/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 30%;
	height:30%;
}
}
</style>
</head>
<body>

<h2>Follow example</h2>


<button id="myBtn">  FOLLOW </button>


<div id="myModal" class="modal">

  
  <div class="modal-content"> 
	 <div id="modalDialogView_6" aria-labelledby="dialogTitleText" aria-describedby="dialogMessageText" role="alertdialog" tabindex="-1">
          
      
            <div id="dialogTitleView" role="presentation" >
               <h1 aria-label="Confirm Follow">Confirm Follow</h1><br>
            </div>
            
      <div id="dialogTextContainer" role="presentation"><span id="dialogMessageText">You will have the option to stop Following this record in the future
        if desired.To continue click OK.
	  </span></div>
      <div id="buttonView" role="presentation"><button id="confirmButton" aria-label="OK" tabindex="0" type="button">
	  <span id="confirmButtonText">OK</span></button>
	  <button id="cancelButton" aria-label="Cancel" tabindex="0" type="button"><span id="cancelButtonTextName">Cancel</span></button>
	  </div>
    </div>
 </div> 
 </div>
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");



// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
	document.getElementById('confirmButton').focus();
}
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
	
        modal.style.display = "none";
    }
}
</script>

</body>
</html>
`

**Comment by pratik-pk** [comment] 2018-08-27 09:33
you can use this code and save this one as html page and than follow the repro steps

**Comment by pratik-pk** [comment] 2018-08-27 09:38
[nvda issue.zip](https://github.com/nvaccess/nvda/files/2323308/nvda.issue.zip)

**Comment by pratik-pk** [comment] 2018-08-27 09:41
@leonardder  please check with above file

**Comment by ehollig** [comment] 2019-03-18 02:27
@pratik-pk does it help if you remove the role of presentation from the div's?

**Comment by pratik-pk** [comment] 2019-03-18 09:00
@ehollig No on removing role="presentation", it's still not working.

**Comment by Adriani90** [comment] 2019-12-20 22:00
Still reproducible in NVDA 2019.3 Beta 1 and Chrome 79.
In Firefox it works just fine.

**Comment by Adriani90** [comment] 2020-02-27 21:12
Actually this seems a duplicate of #9368 .
The discussion in #9368 is more detailed, so let's continue it there.
Closing this one as duplicate.

**Closed by Adriani90** 2020-02-27 21:12 UTC
Labels: duplicate
