### ISSUE TITLE
it is not possible to open a list in chrome while in browsing mode

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9574] opened 2019-05-16 12:10 UTC
### Steps to reproduce:
Enter the satisfaction survey of the 2019 nvda

https://docs.google.com/forms/d/16Ze6P2WrJJNelH2APaSNdNp5u_n2esqYWdfnWXjaOLc/viewform?ts=5cda05eb&edit_requested=true

press 2 times l to go to the list
Is your use of NVDA primarily for accessibility testing? 

press enter, space, alt + arrow below to expand the list and change the options.
### Actual behavior:
enter, and alt + arrow below does not expand the list and you can not navigate the items in the list with arrows below.
If you enter focus mode with nvda + space, pressing 1 shift + tab you can navigate with the arrows below by the options, however for a beginner user this is not intuitive at all.

### Expected behavior:
The enter key, or alt + down arrow should make it possible to expand the list and navigate with arrows below by the options.

#### NVDA installed/portable/running from source:
install
#### NVDA version:
alfa 17162
#### Windows version:
10 build 17763.475
#### Name and version of other software in use when reproducing the issue:
chrome 74
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
[chrome_list.txt](https://github.com/nvaccess/nvda/files/3186962/chrome_list.txt)

**Comment by Adriani90** [comment] 2019-05-16 18:42
I can reproduce this issue as well.
@michaelDCurran is this something related to the changes which had to be reverted recently due to a bug in Google Chrome itself?

**Comment by DrSooom** [comment] 2019-05-17 16:36
@fernando-jose-silva and @Adriani90: Could you take a look at the combobox "Gehe zu..." on [this page](https://danielmayr.at/links.php) (located above the first headline) as well, as the Google Form combobox behavior is also a little bit strange in Firefox. And what happens exactly after pressing ALT+ArrowDown twice at the combobox?

**Comment by Adriani90** [comment] 2019-05-18 08:17
@DrSooom NVDA is behaving correctly with this combo box. In Firefox NVDA seems to read the title of the webpage when colapsing the combo box by pressing alt+down arrow twice. There was a bug filled for that but I cannot find it just now. Anyway, that is not related to this problem described here.

**Comment by Adriani90** [comment] 2020-05-17 17:06
This example does not work anymore, the survey is already finished. I am closing this issue since there is already one in place for combo boxes which do not expand when pressing enter on them.

**Closed by Adriani90** 2020-05-17 17:06 UTC
