### ISSUE TITLE
Prompt if a slide contains speaker notes during a slide show in PowerPoint

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14100] opened 2022-09-02 01:47 UTC
### Is your feature request related to a problem? Please describe.
Currently NVDA has a gesture ctrl+shift+s to Toggle speaker notes reading,
However, we tend to forget which slide has the speaker notes while we're speaking, and we have to manually press the gesture to confirm.
### Describe the solution you'd like
Prompt if a slide contains speaker notes during a slide show in PowerPoint,
For example: NVDA report "Has speaker notes"
If there are no speaker notes, nothing is prompted.
### Describe alternatives you've considered
Play a clipped sound to prompt to include speaker notes.
### Additional context
None

**Comment by seanbudd** [comment] 2022-09-08 06:02
Closing as a duplicate of #8049

**Closed by seanbudd** 2022-09-08 06:02 UTC
Labels: close/duplicate
