### ISSUE TITLE
Unable to navigate module configuration panel in Audacity 2.3.2

### ISSUE THREAD

**Issue by dnz3d4c** [nvaccess/nvda#9581] opened 2019-05-17 06:29 UTC
### Steps to reproduce:
1. Open Audacity (version 2.3.2)
2. Press Ctrl+P
3. Press the down arrow to move to module category Than press Tab key
### Actual behavior:
An event error occurs.
### Expected behavior:
You should be able to navigate the module category panel.
#### NVDA installed/portable/running from source:
- Installed
#### NVDA version:
Version: alpha-17252,7
#### Windows version:
Windows 10(language set to Korean)
#### Name and version of other software in use when reproducing the issue:
Audacity 2.3.2
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2018.4.1
#### My error log:
error executing event: gainFocus on <NVDAObjects.IAccessible.IAccessible object at 0x07560FF0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 150, in executeEvent
  File "eventHandler.pyc", line 163, in doPreGainFocus
  File "api.pyc", line 107, in setFocusObject
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1678, in _get_container
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 501, in _get_container
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\IAccessible\__init__.pyc", line 1664, in _get_parent
  File "baseObject.pyc", line 47, in __get__
  File "baseObject.pyc", line 147, in _getPropertyViaCache
  File "NVDAObjects\window\__init__.pyc", line 272, in _get_parent
  File "NVDAObjects\__init__.pyc", line 138, in __call__
  File "appModules\audacity.pyc", line 15, in event_NVDAObject_init
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Adriani90** [comment] 2019-05-18 07:17
@dnz3d4c did this work properly in NVDA 2018.4.1?
cc: @Robert-J-H, @paulber007

**Comment by paulber19** [comment] 2019-05-18 08:09
Hi,
I have not noticed any problem with:
-NVDA 2018.4.1,
-NVDA 2019.1.1
- NVDA alpha-17252,7e26d874
Cheers.

**Comment by Robert-J-H** [comment] 2019-05-18 10:52
Firstly, the error log is not directly related. The appmodule of Audacity uses "replace" to remove ampersand(&) characters which is actually not necessary any more. However, we kept it because people might still use very, very old versions.
We've tried to eliminate the occurrences on the Audacity side, alas, that's one we've missed.

As to modules: The module pane can be explored (tabbing) but the focus is unfortunately on the pane and not the text inside it.
The name of the pane is \x07, in other words a beep (control+g in a dos window).
I've proposed this workaround years ago in order to prevent NVDA from speaking "Pane" a zilion times when an object gains focus.
Anyways, I can tell only for the case that no modules are present, then, the wrong text is spoken for the simple reason that there is no element under the pane to gain focus.
Has to be fixed by the Audacity team.

It should be fine if modules are present.

**Comment by DavidBailes** [comment] 2020-02-20 10:01
This was fixed in Audacity 2.3.3
The problem was that there was a group box whose name was an empty string. In the Audacity appmodule, obj.name is NONE in this case, and obj.name = obj.name.replace('&','') fails.
Audacity was fixed so that the name of the group box is no longer an empty string.

**Comment by Robert-J-H** [comment] 2020-02-20 17:24
Confirmed, can be closed.

**Comment by Adriani90** [comment] 2020-05-17 17:02
Thanks for reporting, closing as works for me.

**Closed by Adriani90** 2020-05-17 17:02 UTC
Labels: close/worksforme
