### ISSUE TITLE
Screen reader is misreading a mixed character string

### ISSUE THREAD

**Issue by mmack66** [nvaccess/nvda#12340] opened 2021-04-26 17:26 UTC

**Comment by CyrilleB79** [comment] 2021-04-26 21:07
Hello

Which synthesizer are you using?
It seems a duplicate of the following issue: #12121.

Also related to (and maybe also duplicate of) #8959.

**Comment by mmack66** [comment] 2021-04-27 15:05
Hello Cyrille,

Thanks for the quick response.  My synthesizer is Windows OneCore.  Sorry,
my issue definitely seems to be a duplicate of #12121.

Best,
Marti

**Comment by CyrilleB79** [comment] 2021-04-27 21:40
Thanks.
In this case, no problem.
Please just close this issue and make additional comments in the other one if needed.

**Comment by mmack66** [comment] 2021-04-30 17:16
This is a  duplicate of #12121.

**Closed** 2021-04-30 17:15 UTC
