### ISSUE TITLE
NVDa reading of attachment broken in thunderbird 60.0

### ISSUE THREAD

**Issue by enessaribas** [nvaccess/nvda#9011] opened 2018-12-03 12:31 UTC
### Steps to reproduce:
Add an attachment to a message in the compose dialogue box, and shift tab to attachments list. 

expected: nvda reads attachment in a list, and gives options to navigate and delete individual attachments. 

Could one of the devs please look into this? 
### Actual behavior:
actual: nvda anounces attachment list, attach file, alt+m 

### Expected behavior:
expected: nvda reads attachment in a list, and gives options to navigate and delete individual attachments. 

### System configuration:
thunderbird 60.0
#### NVDA Installed/portable/running from source:
installed
#### NVDA version:
alpha-16331,fb680759
#### Windows version:
windows 10 64 bit, 1809
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by DrSooom** [comment] 2018-12-03 22:07
Dublicate of #8698.

**Comment by ehollig** [comment] 2018-12-04 21:43
Duplicate of #8698

**Closed by ehollig** 2018-12-04 21:43 UTC
