### ISSUE TITLE
When update NVDA online, the speech synthesizer will report the update information multiple times.

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10210] opened 2019-09-13 00:24 UTC
NVDA will report update information multiple times when using NVDA's online update 

### Steps to reproduce:
First download [NVDA alpha-18604](https://ci.appveyor.com/api/buildjobs/rr2kmwd740mf4r3s/artifacts/output/nvda_snapshot_alpha-18604,e295dbdd.exe)
Then perform the installation process
Finally, the prompt interface is being updated. At this time, the speech synthesizer will repeat the information that NVDA is being updated three times.
### Actual behavior:
NVDA will report redundant information
### Expected behavior:
Improve NVDA update tips
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
NVDA version alpha-18604,e295dbdd
#### Windows version:
windows10-1903
#### Name and version of other software in use when reproducing the issue:
NVDA version alpha-18604,e295dbdd
#### Other information about your system:
no
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
NVDA log:

IO - speech.speak (07:45:53.691):
Speaking [LangChangeCommand ('zh_CN'), 'Secure desktop']
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (07:45:53.692):
Unsupported speech command: LangChangeCommand ('zh_CN')
IO - speech.speak (07:45:56.507):
Speaking [LangChangeCommand ('zh_CN'), 'Updating NVDA Dialog Please upgrade your NVDA later.']
DEBUGWARNING - synthDrivers.sapi4.SynthDriver.speak (07:45:56.508):
Unsupported speech command: LangChangeCommand ('zh_CN')
IO - speech.speak (07:45:56.550):
Speaking [LangChangeCommand ('zh_CN'), 'Updating NVDA']
IO - speech.speak (07:45:56.666):
Speaking [LangChangeCommand ('zh_CN'), 'Updating NVDA']
thanks

**Comment by dingpengyu** [comment] 2019-09-13 12:26
> Related: Issue #10086
Thanks for tips

**Comment by Adriani90** [comment] 2020-05-21 00:13
actually this is a duplicate of that issue, they are having the same underlying problem even though slightly different descriptions. I am closing this one in favor of #10086.

**Closed by Adriani90** 2020-05-21 00:13 UTC
Labels: close/duplicate
