### ISSUE TITLE
Table in this page can not be browsed in chrome with ctrl+alt+arrow

### ISSUE THREAD

**Issue by vgjh2005** [nvaccess/nvda#7913] opened 2018-01-17 08:30 UTC
Hi:
[12345.zip](https://github.com/nvaccess/nvda/files/1638165/12345.zip)

I will upload the file to github. Please use ctrl+alt+arror keys to navigate on it. Thanks!

**Comment by Adriani90** [comment] 2018-01-17 13:32
I cannot navigate by ctrl+alt+ arro keys in interent Explorer. Here is the developer info:

```
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo (14:27:10.303):
Developer info for navigator object:
name: u'4'
role: ROLE_TABLECELL
states: STATE_FOCUSABLE
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.MSHTML.MSHTML object at 0x057A2890>
Python class mro: (<class 'NVDAObjects.IAccessible.MSHTML.MSHTML'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (10, 166, 157, 21)
value: None
appModule: <'appModuleHandler' (appName u'iexplore', process ID 7800) at address 553f650>
appModule.productName: u'Internet Explorer'
appModule.productVersion: u'11.00.9600.16384'
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
windowHandle: 198544
windowClassName: u'Internet Explorer_Server'
windowControlID: 0
windowStyle: 1442840576
windowThreadID: 7844
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x9749c9c at 5595e40>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=198544, objectID=None, childID=0
IAccessible accName: u'4'
IAccessible accRole: ROLE_SYSTEM_CELL
IAccessible accState: STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1048576)
IAccessible accDescription: exception: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
IAccessible accValue: exception: (-2147467263, 'Nicht implementiert', (None, None, None, 0, None))
MSHTML node has ancestor IAccessible: False
MSHTML nodeName: u'TD'
```

**Comment by vgjh2005** [comment] 2018-01-20 04:53
Please check Include layout tables checkbos.

**Comment by Adriani90** [comment] 2018-01-20 10:46
Hello, with layout tables checked it works in IE, Firefox and Edge. In Edge it works eve though layout tables are disabled. So it seems that NVDA handles tables in IE and Firefox in a different way compared to edge.

In Google Crome the table navigation does not work, even though layout tables are enabled.

In my opinion the next step would be to ensure that NVDA handles layout tables similarly in IE, Firefox and Crome. The second step would be to analyse why NVDA can navigate this table in edge when layout tables are disabled and why layout tables must be enabled for other browsers.

@feerrenrut, do you have any suggestions?

**Comment by Adriani90** [comment] 2018-01-20 10:48
@vgjh2005, to avoid missunderstandings, please edit your issue title to something like "table navigation on this page does not work when using Chrome".

**Comment by feerrenrut** [comment] 2018-01-22 05:08
The included sample does not have column headings, As such, I believe this is a duplicate of #7852

**Closed by feerrenrut** 2018-01-22 05:08 UTC

**Comment by Adriani90** [comment] 2018-01-22 06:02
As stated above, table navigation works in IE and Firefox if table layout is activated. But it does not work in Chrome. Moreover, in edge table navigation works properly in edge even without enabling layout tables. So, I think the definition of layout tables should be clearer.

Von meinem iPhone gesendet

**Comment by feerrenrut** [comment] 2018-01-23 00:44
We rely on Chrome to expose these tables. The given example has broken HTML with mismatched tags. Using the following examples:

**Example 1. with table headers:**
`data:text/html,<table style="width:100%"><tr><th>First name</th><th>Last name</th><th>Age</th></tr><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

**Example 2. without table headers:**
`data:text/html,<table style="width:100%"><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></table>`

Example 1. works as expected.
I see that in Chrome that Example 2 is not recognised as a table, regardless of whether the "Include layout tables" option is checked or not. Exploring this with Object navigation, and "Simple review mode" off, shows that each cell of the table is reported as a "Section". This means that Chrome is not exposing this as a table to NVDA, we do not have any control over this.

The question becomes, why is it expected that this should be interpreted as tabular data rather than structural? The web author has not provided column or row headers, or made it look like tabular data.

If it really is important to that this header information is not visible the following approach could be used:
`data:text/html,<head><style>.screen-reader-text { clip: rect(1px, 1px, 1px, 1px); height: 1px; width: 1px; overflow: hidden; position: absolute !important; }</style></head><body><table><thead class='screen-reader-text'><tr><td>first name</td><td>last name</td><td>age</td></tr><tbody><tr><td>Jill</td><td>Smith</td><td>50</td></tr><tr><td>Eve</td><td>Jackson</td><td>94</td></tr></tbody></table></body>`
