### ISSUE TITLE
Edge bookmarklet crash

### ISSUE THREAD

**Issue by BrentDT** [nvaccess/nvda#11757] opened 2020-10-13 21:16 UTC
### Steps to reproduce:
First create a bookmarklet.
In Edge Chromium, go to Favorites > Manage favorites > Add favorite.
Give it a name such as 'Test bookmarklet'.
Paste this code in the URL field:
    javascript:new function(){for(var e,i=0,a=document.getElementsByClassName('mw-uctop');e=a[i];i++)e.parentElement.style.display='none';}()
Go to https://en.wiktionary.org/wiki/Special:Contributions/BrentDT
Invoke the bookmarklet from the Favorites menu.
Try to read the page.
### Actual behavior:
NVDA crashes. The bookmarklet still hides list items with the 'Current' label.
### Expected behavior:
NVDA doesn't crash.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
NVDA 2020.3
#### Windows version:
Windows 10 Pro Version 1909 (OS Build 18363.1082)
#### Name and version of other software in use when reproducing the issue:
MS Edge 86.0.622.38 (Official build) (64-bit)
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
NVDA 2020.2 and earlier did not have this issue.
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

Google Chrome version 86 ran this bookmarklet without any issues.
A log file is attached.

[nvda-old.zip](https://github.com/nvaccess/nvda/files/5374172/nvda-old.zip)

**Comment by feerrenrut** [comment] 2020-10-14 19:26
Can you confirm that you have tried 2020.2 with MS Edge version `86.0.622.38` specifically? This will help us to understand whether this is likely to be due to a change in Edge or in NVDA.

**Comment by BrentDT** [comment] 2020-10-15 04:51
It could very well be Edge 86 causing this. I don't know when my Edge updated. I grabbed 2020.2 and ran it uninstalled. It exhibits the same issue, but possibly less often.

By chance, I found that this issue is actually a freeze, when I let it sit for at least three minutes. So I ran 2020.3 with debug logging. I accidentally ran the bookmarklet on the wrong page with no effect. Then I refreshed the offending page and tried again, and got the bookmarklet to work. Then I clicked the next 50, and this time I made it freeze twice in a row.

When I tried Edge 86 on my Windows 8.1 laptop, I could never get it to freeze. So this might be Win10-specific.

[nvda-old.zip](https://github.com/nvaccess/nvda/files/5382489/nvda-old.zip)

**Comment by Adriani90** [comment] 2023-03-28 22:25
@BrentDT are you still having this issue with NVDA 2023.1 or with NVDA last alpha version in Microsoft Edge 111? I cannot reproduce this one.

**Comment by BrentDT** [comment] 2023-03-30 22:34
@Adriani90 I am unable to reproduce the issue. I think it went away when Microsoft changed Edge's UI shortly after I posted originally. Feel free to close.

**Comment by Adriani90** [comment] 2023-03-30 23:07
Thanks for updaing. I am closing as works for me.

**Closed by Adriani90** 2023-03-30 23:07 UTC
Labels: close/worksforme, bug/freeze, app/edge/anaheim
