### ISSUE TITLE
NVDA causes crash of LibreOffice while counting words

### ISSUE THREAD

**Issue by karkenau** [nvaccess/nvda#11455] opened 2020-08-03 18:21 UTC
### Steps to reproduce:
1. Open LibreOffice and create anew "Writer" Document.
2. Write a frew words.
3. In the Menu, move to "Extras" and select "Word counting".
### Actual behavior:
LibreOffice crashes
### Expected behavior:
The result of the words counted should be displayed.
#### NVDA installed/portable/running from source:
NVDA 2020.2 installed
#### NVDA version:
2020.2
#### Windows version:
Windows 10 64 Bit
#### Name and version of other software in use when reproducing the issue:
LibreOffice 6.4.5.
#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
I tried 2019.3 and 2020.1
#### If addons are disabled, is your problem still occuring?
Yes.
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes

**Comment by danielzfranklin** [comment] 2020-08-11 21:15
I was able to replicate the issue on a fresh install of Windows 8.1, NVDA 2020.2, and Libreoffice 7.0.0.3. I'm going to try to figure out the root cause.

The relevant portion of the NVDA debug log appears to be:

```python
Speaking [LangChangeCommand ('en_GB'), 'Untitled 1 - LibreOffice Document']
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:46:24.154) - MainThread (3540):
oleacc.AccessibleObjectFromEvent with window 328252, objectID 5 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:46:24.154) - MainThread (3540):
oleacc.AccessibleObjectFromEvent with window 328252, objectID 6 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - watchdog._watcher (13:46:26.045) - watchdog (3932):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1052, in Notify
  File "core.pyc", line 516, in run
  File "mouseHandler.pyc", line 257, in pumpAll
  File "mouseHandler.pyc", line 213, in executeMouseMoveEvent
  File "NVDAObjects\__init__.pyc", line 285, in objectFromPoint
  File "NVDAObjects\__init__.pyc", line 225, in findBestAPIClass
  File "NVDAObjects\__init__.pyc", line 220, in findBestAPIClass
  File "NVDAObjects\window\__init__.pyc", line 104, in getPossibleAPIClasses
  File "_UIAHandler.pyc", line 582, in isUIAWindow
  File "_UIAHandler.pyc", line 560, in _isUIAWindowHelper
  File "speechViewer.pyc", line 93, in _onDialogActivated

IO - speech.speak (13:46:26.187) - MainThread (3540):
Speaking [LangChangeCommand ('en_GB'), 'Untitled 1 - LibreOffice Writer']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (13:46:26.230) - MainThread (3540):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (13:46:26.282) - MainThread (3540):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:46:26.285) - MainThread (3540):
oleacc.AccessibleObjectFromEvent with window 328252, objectID 7 and childID 0: [WinError -2147467259] Unspecified error
DEBUG - IAccessibleHandler.accessibleObjectFromEvent (13:46:26.289) - MainThread (3540):
oleacc.AccessibleObjectFromEvent with window 328252, objectID 8 and childID 0: [WinError -2147467259] Unspecified error
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (13:46:26.312) - MainThread (3540):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IA2Attributes (13:46:26.329) - MainThread (3540):
IAccessibleObject.attributes COMError (-2147467259, 'Unspecified error', (None, None, None, 0, None))
IO - speech.speak (13:46:26.335) - MainThread (3540):
Speaking [LangChangeCommand ('en_GB'), 'LibreOffice 7.0 Document Recovery', 'dialog']
```

**Comment by lukaszgo1** [comment] 2020-08-11 21:24
This issue can be  reproduced with JAWS running so it looks like the problem is in Libre Office rather than in NVDA.

**Comment by danielzfranklin** [comment] 2020-08-12 16:46
@lukaszgo1 I had the impression NVDA tended to add conditions to handle issues in other programs. Would a PR that addresses this crash be useful?

**Comment by lukaszgo1** [comment] 2020-08-12 20:22
@danielzfranklin It certainly would but if the root of the issue is indeed in Libre Office it makes sense to fix the problem there to benefit users of all screen readers.

**Comment by Adriani90** [comment] 2023-03-10 00:36
@danielzfranklin this is still reproducible in Libreoffice 7.5.1 with NVDA 2023.1 RC1. I think Libreoffice processes something in background while cutting words, is seems very power consuming. My 32 GB ram and Intel I12900HK with 5 GHZ computer runs really loud and its on full speed. This is definitely something very inefficient in Libreoffice while doing the word cutting.

**Comment by Adriani90** [comment] 2023-03-10 00:36
Anyway, the application chrashed after a while.

**Comment by seanbudd** [comment] 2023-03-23 05:36
CC: @michaelweghorn

**Comment by Adriani90** [comment] 2023-03-23 16:48
@michaelweghorn could you try with this document? Is it still not reproducible for you?
[ONKYO.docx](https://github.com/nvaccess/nvda/files/11053496/ONKYO.docx)

**Comment by Adriani90** [comment] 2023-03-28 22:51
@michaelweghorn I think I firstly did the wrong thing while reproducing the crash, instead of word counting I clicked on "redact" in the tools menu. This caused the crash on my side, not the word counting feature. Sorry for the confusion here. However, not sure if the crash cause after clicking on redact is even related to NVDA at all. I can reproduce it even without NVDA running in my attached document above.

Since the scope of this issue is about word counting, I agree this is not reproducible anymore. Closing as works for me.

**Closed by Adriani90** 2023-03-28 22:51 UTC
Labels: close/worksforme, bug/app-crash, blocked/needs-external-fix, p1, app/libreoffice, triaged

**Comment by michaelweghorn** [comment] 2023-03-29 07:29
@Adriani90 Thanks for the update and closing this issue. LibreOffice didn't crash for me in a quick test (without NVDA running) even when choosing "Redact", but feel free to report a bug at https://bugs.documentfoundation.org/ if this happens for you.
