### ISSUE TITLE
nvda does not show the basic html button in the browsing mode in firefox

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9307] opened 2019-02-21 19:38 UTC
### Steps to reproduce:
Open gmail in firefox using gmail's default view.
Walk with the arrows up and down and look for the basic html view mode button.
### Actual behavior:
The basic html view mode button is not found using the browse  mode on the nvda.
If you switch to focus mode in nvda and navigate with tab you will find the switch to basic html view mode.
### Expected behavior:
When using browse   mode it should be possible to find the change button for the basic html view mode.
Since it is visible in focus mode.
#### NVDA installed/portable/running from source:
install
#### NVDA version:
2018.4.1
#### Windows version:
10 17134
#### Name and version of other software in use when reproducing the issue:
firefox 65.0.1
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no

**Comment by Adriani90** [comment] 2020-05-02 18:39
This button is in browse mode at the top when using Chromium browsers. I think something is not correct here, the button can reached only in focus mode when trying this in Firefox.
cc: @jcsteh, @MarcoZehe

**Comment by jcsteh** [comment] 2020-05-04 23:38
The button reports as having a width and height of 0, which NVDA treats as invisible. This is not just Firefox a11y: the Javascript clientWidth and clientHeight properties also report 0.

**Comment by Adriani90** [comment] 2023-05-07 17:38
Ok then this is probably also visually hidden right?

@fernando-jose-silva could you please open a bug for Gmail on www.crbug.com and post the link here so we can keep track of it?
Thanks.

**Comment by fernando-jose-silva** [comment] 2023-05-08 01:24
Sorry, I didn't understand when opening the link, it opened a page to open tickets for Google Chrome, but we would have a complaint with it develops the Gmail pageEnviado do meu iPhoneEm 7 de mai. de 2023, à(s) 14:39, Adriani90 ***@***.***> escreveu:﻿
Ok then this is probably also visually hidden right?
@fernando-jose-silva could you please open a bug for Gmail on www.crbug.com and post the link here so we can keep track of it?
Thanks.

**Comment by Adriani90** [comment] 2023-09-12 21:52
@fernando-jose-silva did you report this to google meanwhile?

**Comment by fernando-jose-silva** [comment] 2023-09-13 10:06
I remember that I made the request to Google, however, due to my fault, I forgot to put it in this ticket, and this has been a long time ago, that I no longer have the email response to Louie's request, and that they would check.
After that I haven't tested it but to see if the problem still exists.
As soon as I have time, I will test to see if the problem still occurs.

**Comment by Adriani90** [comment] 2023-09-13 10:17
This is now also reproducible in Chromium browsers, not only firefox.
@Qchristensen could you please confirm if this basic html view button is visible at all from a sighted perspective? NVDA can focus it only in focus mode but it has width and hiht of 0 so this should actually not be visible at all.

**Comment by Adriani90** [comment] 2023-09-13 10:21
Related to #8070.

**Comment by fernando-jose-silva** [comment] 2023-09-13 13:46
I'm blind, so I don't know if this button is visible on the screen.

**Comment by seanbudd** [comment] 2023-11-24 03:21
Closing as duplicate of #13897

**Closed by seanbudd** 2023-11-24 03:21 UTC
