### ISSUE TITLE
nvda logs a lot of '\r\n\r\n' if UIA support for Windows console is enabled

### ISSUE THREAD

**Issue by cary-rowen** [nvaccess/nvda#14689] opened 2023-03-02 01:56 UTC
### Steps to reproduce:
1. In NVDA's Advanced Settings panel, make the following settings:
  - Windows Console support: combo box: UIA when available
2. Open cmd or git bash and press NVDA+Shift+M(Laptop);
### Actual behavior:
There are a lot of '\r\n' in the log.

### Expected behavior:
There won't be so many '\r\n' in the log
### NVDA logs, crash dumps and other attachments:
[log.txt](https://github.com/nvaccess/nvda/files/10866869/log.txt)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.1Beta2
#### Windows version:
Windows 10 22H2 (AMD64) build 19045.2604
#### Name and version of other software in use when reproducing the issue:
None
#### Other information about your system:
None
#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2022.4 is the same
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CyrilleB79** [comment] 2023-03-02 10:30
According to your log, the spoken string is 18095 character long. And there are 17994 characters after the last '>', i.e. 8997 '\r\n'.

@codeofdusk: any idea why so many new lines are captured in the command window when it becomes the foreground?


*

**Comment by codeofdusk** [comment] 2023-03-02 12:31
This is a known bug in API level 0 consoles (see microsoft/terminal#6986). In consoles with less than API level 2, no support is provided as indicated in the user guide.

Mitigation strategies:
* Ideally, upgrade to Windows 11 Sun Valley 2.
* If possible, use Windows Terminal (`wt.exe`), which is continuously updated.
* If all else fails, upgrade `conhost.exe` to the version included with Windows Terminal. I've provided guidance in other issues, etc. on how to do that.

@seanbudd I recommend closing as duplicate of microsoft/terminal#6986.

CC @carlos-zamora, @DHowett.

**Comment by cary-rowen** [comment] 2023-03-02 14:31
@codeofdusk 
If I can't upgrade to windows11 now, can you provide other solutions?

This problem bothers me because of: https://github.com/ABuffEr/numberProcessing/issues/4

But due to another issue, not forcing UIA support for Windows Console under Chinese operating systems will cause every Chinese character displayed on the screen to be reported twice by NVDA.

**Comment by ABuffEr** [comment] 2023-03-02 18:02
Hi,
just for documentation, the freeze seems to born in speechDictHandler.processText function. Adding something like:
```
	try:
		if config.conf["UIA"]["winConsoleImplementation"] == "UIA":
			stripText = text.rstrip()
			if len(text)-len(stripText) > 10000:
				text = stripText
	except KeyError:
		pass
```
before the dictionaries loop, no freeze happens. But I doubt it would be considered an acceptable solution for a PR...

**Comment by cary-rowen** [comment] 2023-03-03 09:57
@codeofdusk 
You wrote:
> If all else fails, upgrade conhost.exe to the version included with Windows Terminal. I've provided guidance in other issues, etc. on how to do that.
---
Can you provide a link on how to do this?

**Comment by seanbudd** [comment] 2023-03-07 01:17
@ABuffEr a fix similar to what you suggested is appropriate

**Closed** 2023-04-05 23:47 UTC
Labels: p3, app/windows-console, api/uia, triaged
