### ISSUE TITLE
Sentences and text blocks are repeating when performing SayAll in Thunderbird with NVDA Snapshot

### ISSUE THREAD

**Issue by sjtaylor82** [nvaccess/nvda#11257] opened 2020-06-14 03:46 UTC
This issue appears in alpha-20317,6bf3ae5f. When performing a SayAll in an open message with Thunderbird 68.9.0 (32-bit), sentences or portions of text are often repeated. This occurs with most emails and always only when reading is commenced from the top of the buffer. 
It occurs with Addons disabled. I have run the COM registry fixing tool. The behaviour does not occur in version NVDA 2020.1
 Please see log attached.   
[nvda.log](https://github.com/nvaccess/nvda/files/4775822/nvda.log)
<!--

**Comment by sjtaylor82** [comment] 2020-06-14 03:55
Update: This is happening also in other areas where browse mode is used including FireFox and Brave.

**Comment by sjtaylor82** [comment] 2020-06-14 03:57
Apologies, I did not intend to close this issue

**Comment by josephsl** [comment] 2020-06-14 04:25
Hi, there is a potential fix being worked on at the moment. Thanks.

**Comment by Brian1Gaff** [comment] 2020-06-14 08:16
Not sure if its related or not, but when I create a new folder there seems 
to be multiple attempts at voicing the newly opened folder before you are 
aware its open for editing its name, ie control shift n.

This is on windows 7. Its been around for a while.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
----- Original Message -----

**Comment by Adriani90** [comment] 2020-06-14 08:36
Closing as duplicate of #11132

**Closed by Adriani90** 2020-06-14 08:36 UTC
Labels: close/duplicate
