### ISSUE TITLE
nvdaremote accessibility in NVDA 2019.3 and beyond

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#10069] opened 2019-08-10 08:19 UTC
Hello. I wrote to the developers of this add-on, but received no response.
I know that with the 2019.3 version, NVDA is moving to python 3. I often use remote access through NVDA. tell me whether there are plans to further develop the supplement? if not, can I add this feature to nvda?

**Comment by lukaszgo1** [comment] 2019-08-10 13:33
@leonardder I believe you've talked in the past about possible integration of NVDA Remote into the core after Python 3 transition. Am i right?

**Comment by josephsl** [comment] 2019-08-10 13:36
Hi, this is another duplicate of #10067, but this one is more substantial. Thanks.

**Comment by Adriani90** [comment] 2019-08-11 21:56
I suggest to continue this discussion either in #4390 or in #3564. Having said that, I am closing this as duplicate of the referenced isues in this comment.

**Closed by Adriani90** 2019-08-11 21:56 UTC
Labels: duplicate

**Comment by josephsl** [comment] 2019-08-11 22:04
Hi, in this case, #4390 is better suited for this, as #3564 talks about a different technology. Thanks,
