### ISSUE TITLE
can't select audio device for some synths

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4827] opened 2015-01-19 07:47 UTC
**Reported by halim on 2015-01-19 07:47**
I've microsoft speech platform installed in my machine. When using that synth it's not possible to select other audio devices. EG.: I am using an usb headset. In the speech dialog microsoft soundmapper is selected but the synth doesn't use the headset. It uses  the onboard audiodevice.

**Comment by bhavyashah** [comment] 2017-08-03 07:54
CC @jcsteh

**Comment by Adriani90** [comment] 2019-01-12 00:02
@halim can you still reproduce it?

**Comment by Adriani90** [comment] 2019-05-05 18:36
We do not have an update from the author since more than three years. I am closing this for now. I am not able to reproduce it with NVDA 2019.1.1. 
If you are still having this problem, plese comment on it and we can reopen the issue.

**Closed by Adriani90** 2019-05-05 18:36 UTC
Labels: Speech synth drivers, bug
