### ISSUE TITLE
Cannot change languages in translate.yandex.com

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#11800] opened 2020-11-01 09:17 UTC
### Steps to reproduce:
1. visit translate.yandex.com
2. The source language will be English, and the target language will be Russian as default
3. Try to change to target language to something else, for example Turkish, by trying to set the ouse to the NVDA cursor and left clicking
4. You will notice that nothing will happen
### Actual behavior:
Nothing happens when you click on the text that says "russian"
### Expected behavior:
A list of langauge should appear, form which to select the desired language for translation
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2020.3
#### Windows version:
windows 10 build 1909
#### Name and version of other software in use when reproducing the issue:
Microsoft edge
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
no

**Comment by Adriani90** [comment] 2020-11-04 21:08
This is reproducible also in Chrome and Firefox.
cc: @jcsteh any idea i this is a web authoring issue or if this is something NVDA could support? I tend to think that this is a web authoring issue. There is no keyboard action implemented for this element and there is no aria role on it as far as I understand.

**Comment by fatihyuksek1** [comment] 2020-11-05 12:35
If this is a web authoring issue, could you please get in touch with Yandex to fix this problem? I couldn’t really find a way to get in touch with them, so I reported the problem here.Thank you Windows 10 için Posta ile gönderildi Kimden: Adriani90Gönderilme: 5 Kasım 2020 Perşembe 00:09Kime: nvaccess/nvdaBilgi: fatihyuksek1; AuthorKonu: Re: [nvaccess/nvda] Cannot change languages in translate.yandex.com (#11800) This is reproducible also in Chrome and Firefox.cc: @jcsteh any idea i this is a web authoring issue or if this is something NVDA could support? I tend to think that this is a web authoring issue. There is no keyboard action implemented for this element and there is no aria role on it as far as I understand.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Adriani90** [comment] 2023-04-19 13:59
This works as expected now with NVDA 2023.1 and Firefox, Chrome and Edge 112. Closing as works for me.

**Closed by Adriani90** 2023-04-19 13:59 UTC
Labels: close/worksforme
