### ISSUE TITLE
Exception in Windows hello setup dialog

### ISSUE THREAD

**Issue by lpintes** [nvaccess/nvda#6314] opened 2016-08-29 09:29 UTC
Just tried to set up a fingerprint in Windows Hello. After pressing the "begin" button, or whatever is this in english version of Windows, I received the following exception and the dialog was unusable:
error executing event: gainFocus on <NVDAObjects.UIA.UIA object at 0x05051A10> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 107, in setFocusObject
  File "baseObject.pyc", line 34, in **get**
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects__init__.pyc", line 475, in _get_container
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA__init__.pyc", line 630, in _get_parent
  File "NVDAObjects__init__.pyc", line 106, in **call**
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Dialog, UIA, Dialog

Tested with next-13526,f4a03d3f and one previous, but also fairly recent build.

**Comment by PratikP1** [comment] 2016-08-29 14:19
What version of Windows was this?

**Comment by josephsl** [comment] 2016-08-29 15:03
Hi, I think a more direct question might be, “what build of Windows 10?” Thanks.

**Comment by lpintes** [comment] 2016-08-29 15:49
Windows 10 anniversary, 10.0.14393 workstation


Dňa 29. 8. 2016 o 16:19 PratikP1 napísal(a):

**Comment by jcsteh** [comment] 2016-08-29 21:41
It's worth noting that NVDA cannot inject its own code into apps like the Settings app, so the crash cannot be directly caused by NVDA code. That suggests there is some UIA bug or similar in Windows that NVDA is triggering.

**Comment by jcsteh** [comment] 2016-08-29 21:42
Bleh, please disregard my last comment. Thinking of the wrong issue.

**Comment by lpintes** [comment] 2016-08-30 07:24
One more note about this: I created a portable copy of NVDA as a backup. 
The version is:

next-13444,0474b600

And guess what? The Windows Hello works! So I was able to setup it with 
the mentioned version.


Dňa 29. 8. 2016 o 23:42 James Teh napísal(a):

**Comment by josephsl** [comment] 2016-08-30 07:33
Hi, and what’s the version you’ve got installed? If it’s the same, sounds like something odd is happening, but if the installed copy runs 135xx, then something odd is going on. To fix this, we need access to a Windows Hello device such as a laptop with iris scanning camera, a fingerprint reader or an unlock device (Anniversary Update and later). Thanks.

**Comment by lpintes** [comment] 2016-08-30 08:22
I have installed version next-13526,f4a03d3f, I believe I mentioned this.



Dňa 30. 8. 2016 o 9:33 Joseph Lee napísal(a):

**Comment by lpintes** [comment] 2016-08-30 08:26
Yet another observation: The problematic part is only when a PIN is 
required. After successful PIN input, the dialog works ok. This is true 
in version next-13526,f4a03d3f. In previously-mentioned portable version 
it works, dialog isread normally.


Dňa 30. 8. 2016 o 9:33 Joseph Lee napísal(a):

**Comment by PratikP1** [comment] 2016-08-30 08:26
Sorry for the confusion. Joseph’s question was what I meant. What build of Windows 10?

**Comment by feerrenrut** [comment] 2016-10-28 04:22
I was unable to reproduce this in Windows 10 Version 1607 Build 14393.321 with a recent 'next' build of NVDA (version next-13637,233fa85b)

**Comment by ehollig** [comment] 2017-10-10 14:59
@lpintes, is this still an issue? It sounds as if, from @feerrenrut in https://github.com/nvaccess/nvda/issues/6314#issuecomment-256833121 that this issue has been resolved.

**Comment by lpintes** [comment] 2017-10-10 16:28
Unfortunately I cannot test it again, because my fingerprint reader ceased to work due to some driver problem. 

But I tried to open a dialog for PIN changing, and it worked fine.

**Comment by ehollig** [comment] 2017-10-10 16:32
Thank you for the reply @lpintes. Closing as worksforme. If this is still an issue, please create a new issue with exact steps to reproduce.

**Closed by ehollig** 2017-10-10 16:32 UTC

**Comment by jcsteh** [comment] 2017-10-11 06:27
FWIW, I set up a fingerprint on my new Win 10 machine recently and didn't encounter any problems.
