### ISSUE TITLE
object navigation with adding move to last or first object

### ISSUE THREAD

**Issue by khsbory** [nvaccess/nvda#5636] opened 2015-12-28 02:17 UTC
Hello, I’m Hyongsop Kim in Korea.
In case of NVDA’s object navigation, there is no function key that move to last object or first object.
In other words, if there are 5 objects, to go to the last item, I have to press key that go to next object many times.
So if move to last object or first object key function will be added, it will be very helpful for many users.

**Comment by parhamdoustdar** [comment] 2015-12-28 06:17
+1 on this one. I too would like a keystroke to move to the first or 
last sibling at the current level.

**Comment by ehollig** [comment] 2017-08-23 15:03
Duplicate of #4100

**Closed by ehollig** 2017-08-23 15:03 UTC
