### ISSUE TITLE
Windows 10 build 16215/Edge: UIA property fetcher/text infos range retriever throws errors when Edge is launched

### ISSUE THREAD

**Issue by josephsl** [nvaccess/nvda#7270] opened 2017-06-09 20:50 UTC
Hi,

A Windows Insider and I have confirmed the following issue:

In build 16215, when launching Edge, NVDA appears to do nothing when opening a new website or throws errors. The traceback varies depending on what the user wanted to do (see below), but it points to UIA text infos range retriever or property retriever code.

STR:

1. With build 16215 installed, open Edge.
2. Navigate to a site such as google.com.
3. Try tabbing around the site or use object navigation.

Expected: browse mode becomes activated or one can move to various elements on screen.
Actual: numerous tracebacks were observed, all pointing to UIA text infos/property fetcher code.
Workaround: open and close Start menu, then when Edge is focused, move to the document (the child of the focused panel), then route focus to it or activate the document.

Setup:
* OS: Windows 10 Insider Preview 16215
* NVDA version: next.14106

Traceback variations:

* Say current navigator object:

ERROR - scriptHandler.executeScript (13:45:09.838):
error executing script: <bound method GlobalCommands.script_navigatorObject_current of <globalCommands.GlobalCommands object at 0x06EDAD30>> with gesture u'NVDA+numpad 5'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 187, in executeScript
  File "globalCommands.pyc", line 799, in script_navigatorObject_current
  File "speech.pyc", line 329, in speakObject
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\edge.pyc", line 532, in _get_role
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\edge.pyc", line 428, in _get_role
  File "NVDAObjects\UIA\__init__.pyc", line 665, in _getUIACacheablePropertyValue
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

at this point, attempting to do object navigation results in NVDA saying "no next/previous/containing/objects inside".

* Tabbing around:

ERROR - eventHandler.executeEvent (13:46:23.944):
error executing event: typedCharacter on <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionEdgeHTMLRootUIA object at 0x07026AD0> with extra args of {'ch': u'\t'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 864, in event_typedCharacter
  File "speech.pyc", line 641, in speakTypedCharacters
  File "api.pyc", line 239, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\edge.pyc", line 437, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 980, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))

Thanks.

**Comment by jcsteh** [comment] 2017-06-11 23:38
CC @MichaelDCurran. I've had a great deal of trouble getting focus to the document in Edge in 16215 as well.

**Comment by Adriani90** [comment] 2019-04-17 21:56
@josephsl are you still seeing this issue? I cannot really reproduce it in NVDA alpha-17077,7f274eca. But maybe it is not reproducible every time.

**Comment by josephsl** [comment] 2019-04-17 22:27
Hi, haven’t come across this in more recent builds. I vote that we close this unless someone objects to this. Thanks,

**Comment by Adriani90** [comment] 2019-04-18 00:28
Closing as works for me.
If someone can reproduce it, please comment on it and We reopen it.

**Closed by Adriani90** 2019-04-18 00:28 UTC
Labels: Edge, p2, worksforme
