### ISSUE TITLE
Strange intonations and pauses when using SAPI5

### ISSUE THREAD

**Issue by jawhien** [nvaccess/nvda#11704] opened 2020-09-29 14:08 UTC
In recent builds, there was such a problem. When using the SAPI5 synthesizer, all phrases and even symbols began to be read with very strange intonations, interrogative, and as if the phrase was breaking off, there were pauses betweenфразами. 

### Steps to reproduce:
Use SAPI5 synthesizer by Acapela

### Actual behavior:
Pauses between phrases, speech is accompanied by interrogative intonations, or phrases sound interrupted, as if there is a comma at the end.

### Expected behavior:
Earlier, speech was smooth.

#### NVDA installed/portable/running from source:
Portable

#### NVDA version:
alpha-21035,37c7a29b, 2020.3 beta3

#### Windows version:
Windows 7 Home Premium (X64)

#### Name and version of other software in use when reproducing the issue:
Infovox desktop 2.2

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, previous versions do not cause such problems.

#### If addons are disabled, is your problem still occuring?
Yes.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
Yes.

**Comment by josephsl** [comment] 2020-09-29 16:48
Hi, I assume no issues with 2020.2? If yes, it could be either Acapela or SAPI5 speech command commit in alpha. CC @MichaelDCurran

**Comment by jawhien** [comment] 2020-09-29 17:01
Hello. Yes, in 2020.2 everything is fine. the problem only appeared in alpha-21035,37c7a29b.

**Comment by lukaszgo1** [comment] 2020-09-29 17:12
Could you please test with [this build from PR 11703](https://ci.appveyor.com/api/buildjobs/q525hgexujq3eake/artifacts/output%2Fnvda_snapshot_pr11703-21065%2Cf55d28c6.exe)

**Comment by josephsl** [comment] 2020-09-29 17:21
Hi, can you test earlier alpha builds so we can isolate the issue? Thanks.

**Comment by jawhien** [comment] 2020-09-29 18:22
@josephsl
Yes. I used almost all alpha builds, alpha-21032, ea8606c0 and earlier did not have this problem.

**Comment by jawhien** [comment] 2020-09-29 18:26
@lukaszgo1
Hello.
Everything seems to be fine in this build. At least at first glance :)

**Comment by feerrenrut** [comment] 2020-09-30 09:15
I would guess this was caused by #11586 now reverted with #11701 and merged to master (alpha builds) with #11703. Instead, an alternative approach to fix the original issue has been merged to master: #11651

I'm going to close this issue as fixed, the latest alpha builds contain the change you have tested, please comment / reopen if the problem remains. Thanks for reporting.

**Closed by feerrenrut** 2020-09-30 09:15 UTC
