### ISSUE TITLE
Tables in LibreOffice Write.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [nvaccess/nvda#16818] opened 2024-07-04 11:12 UTC
Hello, I would like to request the implementation of table accessibility in Libre Office Write. Currently, with NVDA, it is possible to insert a table, but nothing else can be done afterwards: you cannot read it, insert text into it, and possibly not even delete or modify it.

**Comment by vsfoote** [comment] 2024-07-04 12:21
Known enhancement request, #4133 

with duplicates: #1994, #2620,  #4752 , #7610

**Comment by Adriani90** [comment] 2024-07-04 23:12
Closing as duplicate of #4133

**Closed by Adriani90** 2024-07-04 23:12 UTC
Labels: close/duplicate
