### ISSUE TITLE
A11y_Resource Scheduling Optimization Stay Healthy _Optimization tab _Screen Reader: NVDA is not reading the sorting status when user presses space on the column headers. When user presses space NVDA is reading the column header name twice

### ISSUE THREAD

**Issue by Tanushagottipati** [nvaccess/nvda#9992] opened 2019-07-29 09:11 UTC
Environment Details: 
http://aurorav41970.aurorav41970dom.extest.microsoft.com/apps

Server version: 9.1.0000.7605
Client version: 1.3.2119
Org name: CITTest

Browser Details:​​
Google chrome 
Version 75.0.3770.142 (Official Build) (64-bit)
Screen Reader: NVDA

MAS Violated: MAS1.3.1
​
Repro Steps: ​
1. Hit the URL: http://aurorav41970.aurorav41970dom.extest.microsoft.com/apps and log in with appropriate credentials. Navigate to “Resource Scheduling Optimization” application and press enter
2.Start Narrator
3.Tab till Optimization Schedules link and press enter
4.Tab till any of the Optimization Schedule and press enter
5.Tab till Schedule board and press enter. Start Narrator
6.Navigate to Optimization tab and press enter. Tab till grid column headers
7.Verify if Narrator is reading the sorting status properly
​
Actual Result: ​
NVDA is not reading the sorting status when user presses space on the column headers. When user presses space NVDA is reading the column header name twice

Expected Result: ​
NVDA should read the sorting status as 'Status column header sorted Ascending/sorted descending' when users presses space on the column header

User Impact: ​
Screen reader users will not know about the sorting status of the column headers if NVDA does not read the status

MAS Reference: ​
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

![NVDA is reading the column header name twice when user presses space on the column header](https://user-images.githubusercontent.com/41109135/62035927-6c6ed580-b20e-11e9-805b-73626c595de5.png)

**Comment by feerrenrut** [comment] 2019-07-29 09:35
Please provide a minimal test case which demonstrates this is a bug in NVDA rather than in sharepoint, none of these links are publicly accessible.

Until this is provided, I will close this issue.

**Closed by feerrenrut** 2019-07-29 09:35 UTC

**Comment by SaisreeDandamudi** [comment] 2019-07-31 12:10
**Product Owner Comment on the bug :** 
The problem is not related to code it is related external to NVDA .As edge with narrator is verifying list element and announcing them.Though we have implied role to listitem but that is not enough for nvda to recognize it.ARIA semantics for each HTML element [Informative only], whether a feature
has implicit ARIA semantics [or something else] is defined in HTML  Accessibility API Mappings 1.0 <https://w3c.github.io/html-aam/>), it's up to the screen reader whether they announce the aria-label for any given element
