### ISSUE TITLE
NVDA does not voice language switching in Microsoft edge

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7974] opened 2018-02-08 07:06 UTC
hi Open Microsoft Edge and try to switch the language by pressing ALT + SHIFT
The expected NVDA should tell what language the layout switched to. Actually Nvda says nothing.
The same situation happens to the narrator. I think this is a Microsoft problem but decided to write here So we send feedback to Microsoft together.

**Comment by Adriani90** [comment] 2020-04-22 17:37
This works as expected in Edge Chromium 81. Closing as works for me since Edge Chromium will be distributed to most users via Windows 10 20 H1 update.

**Closed by Adriani90** 2020-04-22 17:37 UTC
Labels: close/worksforme

**Comment by Adriani90** [comment] 2020-04-30 21:11
Adding appropriate label since this is probably still reproducible in Edge Spartan and UIA related environments.
