### ISSUE TITLE
Disclosure button name is not announce when user closes the button with [Esc] key.

### ISSUE THREAD

**Issue by shirsha** [nvaccess/nvda#11560] opened 2020-09-04 15:23 UTC
### Steps to reproduce:

1. Open Chrome browser.
2. Start NVDA screen reader
3. Browse to W3c example:https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-navigation.html#mythical-page-content.
4. Navigate to "Action" button and activate it to expand.
5. Select the [Tab] key to navigate into the dropdown list.
6. Cloe the expanded dropdown using [Esc] key.

NVDA narration of the dropdown button after the menu is closed with the escape key. It appears the current experience is consistent with the w3 site's working example on disclosures.

https://www.w3.org/TR/wai-aria-practices-1.1/examples/disclosure/disclosure-navigation.html

The example navigation menu with "About", "Admissions", and "Academics" options will also not read the button's name if escape is pressed while the menu is open.

### Actual behavior:
The example navigation menu with "About", "Admissions", and "Academics" options will not read the button's name if escape is pressed while the button is open.

### Expected behavior:
The example navigation menu with "About", "Admissions", and "Academics" options will  read the button's name if escape is pressed while the button is open.

### System configuration
Default

#### NVDA installed/portable/running from source:
Installed

#### Other information about your system:
Edition: Windows 10 Enterprise
#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

#### If addons are disabled, is your problem still occuring?
Yes

**Comment by Adriani90** [comment] 2020-09-10 20:59
This works as expected in focus mode, nvda + space bar. So this seems to occur only in browse mode. @jcsteh this occurs also in Firefox. Is there a specific reason why NVDA does not report the button name when colapsing the menu in browse mode?

**Comment by Adriani90** [comment] 2020-09-10 21:15
Oops sorry, I found out this is a duplicate of #9464. Closing this as a duplicate, you will find more details on #9464.

**Closed by Adriani90** 2020-09-10 21:15 UTC
Labels: close/duplicate
