### ISSUE TITLE
NVDA freezes while a voice message plays on whatsapp desktop

### ISSUE THREAD

**Issue by fatihyuksek1** [nvaccess/nvda#15169] opened 2023-07-20 09:07 UTC
### Steps to reproduce:
1. Open a chat on whatsapp desktop
2. Listen to a voice message
3. Press up or down, or tab or shift tab keys to move inside the Whatsapp window
4. Nvda will freeze and won't react to any input until the voice message finishes playing.
### Actual behavior:

NVDA freezes and won't speak anything while the voice message is playing
### Expected behavior:

Nvda should continue to speak while the voice message is playing

### NVDA logs, crash dumps and other attachments:
[nvda.log](https://github.com/nvaccess/nvda/files/12104131/nvda.log)

#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Whatsapp desktop
#### Other information about your system:
ProcessorAMD A8-6410 APU with AMD Radeon R5 Graphics       2.00 GHz
Ram 8,00 GB (available: 6,96 GB)
System type	64-bit operating system, processor x64
Device brand and model: Lenovo g50-45
#### Does the issue still occur after restarting your computer?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by CoBC** [comment] 2023-09-05 12:12
This problem seems to be getting worse little by little, now NVDA no longer responds either once the voice message is finished, often you have to close the WhatsApp window and reopen it to be able to use the application again, sometimes even this is not enough because reopening NVDA is still crashed in WhatsApp

**Comment by Adriani90** [comment] 2023-09-05 15:11
@CoBC can you reproduce this also in NVDA 2023.2? And are all your addons in NVDA disabled when reproducing this issue?

**Comment by fatihyuksek1** [comment] 2023-09-06 10:33
Yes, I can reproduce this issue with addons disabled.5 сент. 2023 г., в 18:11, Adriani90 ***@***.***> написал(а):﻿
@CoBC can you reproduce this also in NVDA 2023.2? And are all your addons in NVDA disabled when reproducing this issue?

**Comment by burakyuksek** [comment] 2023-11-26 15:02
I am also having this issue. My log contains errors such as:
Speaking [LangChangeCommand ('tr'), 'WhatsApp', CancellableSpeech (still valid)]
DEBUGWARNING - UIAHandler.UIAHandler.getNearestWindowHandle (17:46:40.660) - Dummy-5 (6040):
error walking up to an element with a valid windowHandle
Traceback (most recent call last):
  File "UIAHandler\__init__.pyc", line 1233, in getNearestWindowHandle
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147467259, 'Belirtilmemiş hata', (None, None, None, 0, None))
IO - speech.speech.speak (17:46:40.751) - MainThread (9844):
Speaking [LangChangeCommand ('tr'), 'WhatsApp', 'pencere', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:46:40.756) - MainThread (9844):
Speaking [LangChangeCommand ('tr'), 'Mesajlar', 'liste', CancellableSpeech (still valid)]
IO - speech.speech.speak (17:46:40.760) - MainThread (9844):

**Comment by zstanecic** [comment] 2023-11-26 15:39
This will be fixed when the Uia event limiting kicks in in alphas. 
@michaelDCurran

**Comment by Adriani90** [comment] 2023-11-27 09:51
Closing as fixed in the last NVDA alpha by #14888.

**Closed by Adriani90** 2023-11-27 09:51 UTC
Labels: close/worksforme, bug/freeze, p2, triaged, blocked/needs-technical-investigation

**Comment by zstanecic** [comment] 2023-11-27 13:08
Hi, yes, i confirm that and i am going to add the changelog entry under the existing one in a Pr right now.

**Comment by zstanecic** [comment] 2023-11-27 13:09
by the way, some fixes to the changelog will be part of this pr, too.
