### ISSUE TITLE
nvda does not open the log window

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8794] opened 2018-09-27 13:21 UTC
### Steps to reproduce:
was trying to capture a logging moment where nvda does not advertise the object in focus.
What did I do:
I opened the start menu, typed word and hit enter.
The nvda announced panel.
Press nvda + f1.
### Actual behavior:
nothing acted.
### Expected behavior:
the nvda log window should open.
I restarted nvda, went to the desktop and pressed nvda + f1 and the log opened.
I repeated the first words to open the word and failed again.
#### NVDA Installed/portable/running from source:
instal
#### NVDA version:
alfa 16124
#### Windows version:
10 17134.286
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no
[log.txt](https://github.com/nvaccess/nvda/files/2424235/log.txt)

**Comment by fernando-jose-silva** [comment] 2018-09-27 13:27
nvda alfa 16123

**Comment by leonardder** [comment] 2018-09-29 11:52
Could this have been caused by the external keyboard you were using when you came across #8793?

**Comment by fernando-jose-silva** [comment] 2018-09-29 12:45
In this case I do not know if the problem was caused by the external keyboard.

However it was also another issue that I was able to solve, I restored nvda to factory settings and re-built my preferred settings.

After that it works fine.

So it seemed to be a setup I did not identify that might be causing, or even something corrupted.

 

De: Leonard de Ruijter <notifications@github.com> 
Enviada em: sábado, 29 de setembro de 2018 08:52
Para: nvaccess/nvda <nvda@noreply.github.com>
Cc: fernando-jose-silva <fernandoj.silva21@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [nvaccess/nvda] nvda does not open the log window (#8794)

 

Could this have been caused by the external keyboard you were using when you came across #8793 <https://github.com/nvaccess/nvda/issues/8793> ?

**Comment by Adriani90** [comment] 2019-04-03 22:30
@fernando-jose-silva so I am understanding correctly that this issue is now solved? Or are you still having it?

**Comment by fernando-jose-silva** [comment] 2019-04-04 01:23
perfect, everything solved.

**Comment by Adriani90** [comment] 2019-04-04 09:35
Closing as works for me.

**Closed** 2019-04-04 09:35 UTC
