### ISSUE TITLE
I can't navigate the youtube web site on windows 8.1 and windows 7

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4671] opened 2014-12-05 22:56 UTC
**Reported by fatih on 2014-12-05 22:56**
hi,
since I don't have the windwos 8.1 computer with me at the moment, I can't provide a log file now but whenever I go to the youtube site and load a video, I try to navigate the webpage and it makes an error sound. When I navigate the page with quick keys such as b and h, it says the heading or the button name and it makes an error sound. When I try to focus on or activate a button, nothing happens and it makes an error sound.

**Comment by derekriemer** [comment] 2016-12-28 04:19
Can't reproduce anymore. @michaelDCurran is this still valid?

**Comment by feerrenrut** [comment] 2016-12-28 11:43
Assigned priority 2 to investigate if this issue is still valid. Hopefully we can close it.

**Comment by leonardder** [comment] 2017-07-17 12:52
CC @JCSTeh

**Comment by bhavyashah** [comment] 2017-07-29 15:34
Any success in reproducing this issue? @feerrenrut @leonardder @jcsteh @derekriemer

**Comment by ehollig** [comment] 2018-10-05 03:48
As this issue looks pretty abandoned, I tried to reproduce in IE 11. Here are the steps I took:

1. Open [www.youtube.com ](http://www.youtube.com) in Internet Explorer.
2. Open any video on the page, the first one should work.
3. Try navigating to the next heading using H or B for the next button.
4. Try activating one of the buttons to pause or mute the volume by pressing space or enter.
Expected and actual result: No error sound.

I am going to close this issue. Please reopen if this is still an issue.

**Closed by ehollig** 2018-10-05 03:48 UTC
Labels: Browse mode, bug, p2
