### ISSUE TITLE
Ability to control volume of earcons / sounds independently of speech

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#11726] opened 2020-10-05 05:29 UTC
### Is your feature request related to a problem? Please describe.

Request from a user (Andrew via email), that the audio from the "Play audio coordinates when mouse moves" mouse setting is too loud and makes it hard to hear speech when NVDA is speaking at the same time.

As NVDA has several other earcons and sounds, it might be useful to have a control to adjust NVDA's sound volume, independently.

(Currently the speech volume can be adjusted, on the Speech settings page, or via the synth settings ring, but this does not affect the sounds)

### Describe the solution you'd like

Add a volume control to the settings somewhere for sound volume.  Possibly next to the speech volume slider as it is quite possible users will want to adjust them together, or adjust one in coordination with the other.

### Describe alternatives you've considered

Currently the only solution if the audio sounds are too loud to hear speech, would be to ensure not to move the mouse (for audio coordinates at least) while NVDA is speaking.

**Comment by Adriani90** [comment] 2020-10-06 21:33
Closing as duplicate of #1409.

**Closed by Adriani90** 2020-10-06 21:33 UTC
Labels: close/duplicate, component/audio, component/audio-ux
