### ISSUE TITLE
NVDA not starting

### ISSUE THREAD

**Issue by StormProductions** [nvaccess/nvda#7978] opened 2018-02-09 12:05 UTC
Today, I started my computer and NVDA didnțt start like it usually should start with Windows. The shortcut also didn't work. Uninstalling it with Revo Uninstaller. When tried to install it, the logo plays but NVDA won't start like it should. Any help would be appreciated.

**Comment by leonardder** [comment] 2018-02-09 14:25
What version of NVDA are you intending to use? 2017.4, or a master snapshot?

**Comment by StormProductions** [comment] 2018-02-09 14:26
2017.4.

**Comment by Brian1Gaff** [comment] 2018-02-09 16:59
Did the computer experience a bad shut down recently?
 This can cause this sort of issue.
Do you have a back up in a folder you can run portably? This I find 
invaluable if this happens. One can then simply reinstall it over the old 
broken copy.

**Comment by StormProductions** [comment] 2018-02-09 17:02
I managed to repair it
The problem was Bitdefender being an ass.
Thank you anyway.

**Comment by ehollig** [comment] 2018-02-10 03:57
It sounds from @StormProductions  in https://github.com/nvaccess/nvda/issues/7978#issuecomment-364493993 that this was an issue with Bitdefender and the problem is now resolved. Closing as worksforme

**Closed by ehollig** 2018-02-10 03:57 UTC
