### ISSUE TITLE
Incorrect hyperlink reading when mouse pointer shape announcement is enabled

### ISSUE THREAD

**Issue by peer-gustavsson** [nvaccess/nvda#14297] opened 2022-10-25 19:54 UTC
### Steps to reproduce:
1. Set NVDA to announce mouse pointer shape.
2. Unzip and open the MSG file in Outlook 2016/365: [fb2k v2 Cue Fix.zip](https://github.com/nvaccess/nvda/files/9863436/fb2k.v2.Cue.Fix.zip)
3. Let NVDA read the first line of the opened message. You will hear an incomplete hyperlink address accompanied by words such as "iunknown ptr at 0x".

### Actual behavior:

odkaz    styl <POINTER(IUnknown) ptr=0x67f75604 at 50e5080>  h  styl Normální  ttps://marc2k3.github.io/component/cue-fi  styl <POINTER(IUnknown) ptr=0x67f75604 at 50e5210>  x  

### Expected behavior:

https://marc2k3.github.io/component/cue-fix https://marc2k3.github.io/component/cue-fix

### NVDA logs, crash dumps and other attachments:
IO - speech.speech.speak (21:27:21.037) - MainThread (10104):
Speaking ['Počáteční pozice fragmentu protokolu označena, stiskněte znovu pro zkopírování do schránky']
IO - braille.BrailleBuffer.update (21:27:21.040) - MainThread (10104):
Braille regions text: ['Počáteční pozice fragmentu protokolu označena, stiskněte znovu pro zkopírování do schránky']
IO - braille.BrailleHandler.update (21:27:21.041) - MainThread (10104):
Braille window dots: 12347 135 146 16 2345 15 146 1345 34 - 1234 135 1356 24 14 15 - 124 1235 1 1245 134 15 1345 2345 136 - 1234 1235 135 2345 135 13 135 123 136 - 135 1356 1345
IO - inputCore.InputManager.executeGesture (21:27:23.786) - winInputHook (14456):
Input: kb(laptop):upArrow
IO - speech.speech.speak (21:27:24.140) - MainThread (10104):
Speaking ['Dohoda o CSOB identite.pdf', 'řádek 14', 'sloupec 1', '14 z 26', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:27:24.142) - MainThread (10104):
Potential unimplemented child class: <NVDAObjects.Dynamic_RecognizableFileObjectUIItemListItemUIA object at 0x02C7C950>
IO - braille.BrailleBuffer.update (21:27:24.143) - MainThread (10104):
Braille regions text: ['C:\\Users\\peers\\Documents ', 'Zobrazení položek sezn ', 'Dohoda o CSOB identite.pdf 14 z 26']
IO - braille.BrailleHandler.update (21:27:24.143) - MainThread (10104):
Braille window dots: 1457 135 125 135 145 1 - 135 - 147 2347 1357 127 - 24 145 15 1345 2345 24 2345 15 3 1234 145 124 - 18 1458 - 1356 - 128 1248
IO - inputCore.InputManager.executeGesture (21:27:24.548) - winInputHook (14456):
Input: kb(laptop):downArrow
IO - speech.speech.speak (21:27:24.894) - MainThread (10104):
Speaking ['fb2k v2 Cue Fix.msg', 'řádek 15', 'sloupec 1', '15 z 26', CancellableSpeech (still valid)]
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:27:24.895) - MainThread (10104):
Potential unimplemented child class: <NVDAObjects.Dynamic_RecognizableFileObjectUIItemListItemUIA object at 0x0874EB30>
IO - braille.BrailleBuffer.update (21:27:24.895) - MainThread (10104):
Braille regions text: ['C:\\Users\\peers\\Documents ', 'Zobrazení položek sezn ', 'fb2k v2 Cue Fix.msg 15 z 26']
IO - braille.BrailleHandler.update (21:27:24.896) - MainThread (10104):
Braille window dots: 124 12 128 13 - 1236 128 - 147 136 15 - 1247 24 1346 3 134 234 1245 - 18 158 - 1356 - 128 1248
IO - inputCore.InputManager.executeGesture (21:27:25.533) - winInputHook (14456):
Input: kb(laptop):enter
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (21:27:26.411) - MainThread (10104):
Foreground took too long to change. Foreground still 986214 (CabinetWClass). Should be 134664 (rctrl_renwnd32)
DEBUG - UIAHandler.shouldUseUIAInMSWord (21:27:27.377) - Dummy-2 (4628):
User has requested UIA in MS Word always
DEBUG - treeInterceptorHandler.update (21:27:27.816) - MainThread (10104):
Adding new treeInterceptor to runningTable: <NVDAObjects.UIA.wordDocument.WordBrowseModeDocument object at 0x05291AF0>
IO - speech.speech.speak (21:27:27.825) - MainThread (10104):
Speaking ['[fb2k v2] Cue Fix - Článek informačního kanálu RSS  ', CancellableSpeech (still valid)]
IO - speech.speech.speak (21:27:27.827) - MainThread (10104):
Speaking ['dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (21:27:27.841) - MainThread (10104):
Speaking ['dokument', CancellableSpeech (still valid)]
IO - speech.speech.speak (21:27:28.232) - MainThread (10104):
Speaking ['odkaz', 'strana 1', 'úsek 1', 'styl <POINTER(IUnknown) ptr=0x67f75604 at 50e5f30>', 'h', 'styl Normální', 'ttps://marc2k3.github.io/component/cue-fi', 'styl <POINTER(IUnknown) ptr=0x67f75604 at 50e54e0>', 'x', 'styl Normální', '\r']
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:27:28.235) - MainThread (10104):
Potential unimplemented child class: <NVDAObjects.IAccessible.IAccessible object at 0x05291F50>
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:27:28.237) - MainThread (10104):
Potential unimplemented child class: <NVDAObjects.IAccessible.IAccessible object at 0x0510E2B0>
DEBUG - NVDAObjects.NVDAObject._get_placeholder (21:27:28.237) - MainThread (10104):
Potential unimplemented child class: <NVDAObjects.Dynamic_OutlookUIAWordDocumentWordDocumentEditableTextWithAutoSelectDetectionUIAWindowNVDAObject object at 0x05291150>
IO - braille.BrailleBuffer.update (21:27:28.639) - MainThread (10104):
Braille regions text: ['[fb2k v2] Cue Fix - Článek informačního kanálu RSS   ', 'dlg ', 'dok ', 'odk https://marc2k3.github.io/component/cue-fix ']
IO - braille.BrailleHandler.update (21:27:28.640) - MainThread (10104):
Braille window dots: 135 145 13 - 125 2345 2345 1234 234 25 12456 12456 134 1 1235 14 128 13 148 3 1245 24 2345 125 136 12 3 24 135 12456 14 135 134 1234 135 1345 15 1345 2345 12456
IO - braille.BrailleHandler.update (21:27:28.640) - MainThread (10104):
Braille window dots: 135 145 13 - 125 2345 2345 1234 234 25 12456 12456 134 1 1235 14 128 13 148 3 1245 24 2345 125 136 12 3 24 135 12456 14 135 134 1234 135 1345 15 1345 2345 12456
IO - inputCore.InputManager.executeGesture (21:27:29.631) - winInputHook (14456):
Input: kb(laptop):upArrow
IO - speech.speech.speak (21:27:30.669) - MainThread (10104):
Speaking ['odkaz', 'styl <POINTER(IUnknown) ptr=0x67f75604 at 50e5ad0>', 'h', 'styl Normální', 'ttps://marc2k3.github.io/component/cue-fi', 'styl <POINTER(IUnknown) ptr=0x67f75604 at 50e5f80>', 'x', 'styl Normální', '\r']
DEBUG - speech.manager.SpeechManager._handleIndex (21:27:30.747) - MainThread (10104):
Unknown index 3485, speech probably cancelled from main thread.
IO - braille.BrailleBuffer.update (21:27:31.145) - MainThread (10104):
Braille regions text: ['[fb2k v2] Cue Fix - Článek informačního kanálu RSS   ', 'dlg ', 'dok ', 'odk https://marc2k3.github.io/component/cue-fix ']
IO - braille.BrailleHandler.update (21:27:31.146) - MainThread (10104):
Braille window dots: 135 145 13 - 125 2345 2345 1234 234 25 12456 12456 134 1 1235 14 128 13 148 3 1245 24 2345 125 136 12 3 24 135 12456 14 135 134 1234 135 1345 15 1345 2345 12456
IO - braille.BrailleHandler.update (21:27:31.148) - MainThread (10104):
Braille window dots: 135 145 13 - 125 2345 2345 1234 234 25 12456 12456 134 1 1235 14 128 13 148 3 1245 24 2345 125 136 12 3 24 135 12456 14 135 134 1234 135 1345 15 1345 2345 12456
IO - speech.speech.speak (21:27:31.160) - MainThread (10104):
Speaking ['Upravit kurzor']
IO - braille.BrailleBuffer.update (21:27:31.160) - MainThread (10104):
Braille regions text: ['Upravit kurzor']
IO - braille.BrailleHandler.update (21:27:31.161) - MainThread (10104):
Braille window dots: 1367 1234 1235 1 1236 24 2345 - 13 136 1235 1356 135 1235
DEBUG - UIAHandler.shouldUseUIAInMSWord (21:27:31.170) - MainThread (10104):
User has requested UIA in MS Word always
IO - braille.BrailleHandler.update (21:27:35.162) - MainThread (10104):
Braille window dots: 135 145 13 - 125 2345 2345 1234 234 25 12456 12456 134 1 1235 14 128 13 148 3 1245 24 2345 125 136 12 3 24 135 12456 14 135 134 1234 135 1345 15 1345 2345 12456
IO - inputCore.InputManager.executeGesture (21:27:55.913) - winInputHook (14456):
Input: kb(laptop):shift+control+NVDA+f1

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2022.3.1
#### Windows version:
Windows 11 22H2 22623.870
#### Name and version of other software in use when reproducing the issue:
Outlook 365
#### Other information about your system:
My system uses the Czech locale. I have UI Automation in Word documents turned on.

#### Does the issue still occur after restarting your computer?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this issue might occur in year-old version of NVDA and Office 365 as well with the same behaviour.
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by michaelDCurran** [comment] 2022-11-01 02:25
This is a duplicate of #11427

**Closed by michaelDCurran** 2022-11-01 02:25 UTC
