### ISSUE TITLE
NVDA hangs constantly when Eclipse opened

### ISSUE THREAD

**Issue by shadyar** [nvaccess/nvda#13512] opened 2022-03-20 12:25 UTC
### Steps to reproduce:
Just open Eclipse STS (Spring Suite Tool) 

### Actual behavior:
NVDA hangs and gets errors and plays ding ding.

### Expected behavior:
After opening Eclipse NVDA reads its components 
#### NVDA installed/portable/running from source:
NVDA installed

#### NVDA version:
(NVDA) Version: alpha-25008,c8d96591

#### Windows version:
Windows 11 enterprise 64-bit latest version

#### Name and version of other software in use when reproducing the issue:
Eclipse or STS 2021

#### Other information about your system:
Laptop Asus UM325UA

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, I tried (NVDA) Version: 2021.3.4 it works well.

#### If NVDA add-ons are disabled, is your problem still occurring?
I uninstalled and installed again only NVDA. but problem still occurred 

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes, it does.
[nvda.log](https://github.com/nvaccess/nvda/files/8311210/nvda.log)

I have attached The NVDA log.

**Comment by lukaszgo1** [comment] 2022-03-20 22:05
@shadyar If you would have tested with add-ons disabled (as asked in the issue template) you will discover that this is caused by the add-on for Eclipse not being compatible with the latest version of NVDA as it is backwards compatibility breaking release. This should be closed as invalid. @albzan why you set the last compatible value for your add-on to 2025.9.0? These values are verified for  NVDA for a reason and abusing them ultimately hurts users.

**Closed** 2022-03-20 22:09 UTC

**Comment by albzan** [comment] 2022-03-21 08:31
@lukaszgo1 , because it is unsustainable for me to updates all add-ons each time a new version of NVDA comes out. It doesn't make sense for me to do breaking changes every 3 versions of NVDA. Come on, JAWS has mantained its scripting API for the last 15 years, and you can run JAWS scripts written on the beginning of 2000s, while in NVDA you can't run a script you've made 3 years ago. 
So yes, I put 2099 as a last Tested NVDA Version, you don't like? help to improve it, fix it, make a merge request and I'll approve it for sure.
Cheers,
Alberto
