### ISSUE TITLE
Browse mode fails in Google Chrome

### ISSUE THREAD

**Issue by nidza07** [nvaccess/nvda#10429] opened 2019-10-27 23:18 UTC
### Steps to reproduce:
1. Open Chrome.
2. Wait for any page to load, and try to use the browse mode to read.

### Actual behavior:
Browse mode does not work correctly
### Expected behavior:
NVDA should allow you to navigate the page and use all the browse mode shortcuts
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2019.2.1
#### Windows version:
Windows 10
#### Name and version of other software in use when reproducing the issue:
Google chrome version 78
#### Other information about your system:
Clean Windows installation
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, the same happens with 2019.2
### Additional comments
This is an issue which started happening on a new Windows installation. Below is the log:
DEBUG - __main__ (00:12:36.042):
Provided arguments: ['C:\\Program Files (x86)\\NVDA\\nvda.exe', '-r', '--debug-logging']
INFO - __main__ (00:12:36.042):
Starting NVDA
DEBUG - __main__ (00:12:36.042):
Debug level logging enabled
DEBUG - core.main (00:12:36.197):
Core starting
INFO - core.main (00:12:36.197):
Config dir: C:\Users\wweni\AppData\Roaming\nvda
DEBUG - core.main (00:12:36.197):
loading config
INFO - config.ConfigManager._loadConfig (00:12:36.197):
Loading config: C:\Users\wweni\AppData\Roaming\nvda\nvda.ini
DEBUG - config.profileUpgrader.upgrade (00:12:36.197):
Current config schema version: 2, latest: 2
DEBUG - fileUtils.FaultTolerantFile (00:12:36.213):
C:\Users\wweni\AppData\Roaming\nvda\nvda.iniudumly.tmp
INFO - config.ConfigManager._loadConfig (00:12:36.243):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{u'schemaVersion': u'2', u'development': {}, u'upgrade': {}, u'update': {u'autoCheck': u'True', u'startupNotification': u'True', u'allowUsageStats': u'True', u'askedAllowUsageStats': u'True'}, u'general': {u'language': u'Windows', u'saveConfigurationOnExit': u'True', u'askToExit': u'True', u'playStartAndExitSounds': u'True', u'loggingLevel': u'INFO', u'showWelcomeDialogAtStartup': u'False'}, u'speech': {u'synth': u'espeak', u'outputDevice': u'Microsoft Sound Mapper', u'autoLanguageSwitching': u'False', u'oneCore': {u'voice': u'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM', u'volume': u'100'}, u'espeak': {u'voice': u'sr', u'variant': u'steph', u'rate': u'35', u'pitch': u'40', u'inflection': u'75', u'volume': u'100', u'rateBoost': u'True'}}, u'braille': {u'noBraille': {}}, u'virtualBuffers': {u'autoFocusFocusableElements': u'True'}, u'documentFormatting': {u'reportSpellingErrors': u'False'}}
DEBUG - core.main (00:12:36.529):
setting language to Windows
INFO - core.main (00:12:36.529):
NVDA version 2019.2.1
INFO - core.main (00:12:36.529):
Using Windows version 10.0.18362 workstation
INFO - core.main (00:12:36.535):
Using Python version 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:30:55) [MSC v.1500 32 bit (Intel)]
INFO - core.main (00:12:36.535):
Using comtypes version 1.1.7
INFO - core.main (00:12:36.535):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (00:12:36.535):
Initializing add-ons system
DEBUG - addonHandler._getAvailableAddonsFromPath (00:12:36.542):
Listing add-ons from C:\Users\wweni\AppData\Roaming\nvda\addons
DEBUGWARNING - touchHandler.touchSupported (00:12:36.732):
No touch devices found
DEBUG - core.main (00:12:36.851):
Initializing appModule Handler
DEBUG - core.main (00:12:36.851):
Initializing NVDAHelper
DEBUG - core.main (00:12:36.957):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (00:12:36.961):
Loading speech dictionary 'C:\Users\wweni\AppData\Roaming\nvda\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:12:36.961):
file 'C:\Users\wweni\AppData\Roaming\nvda\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (00:12:36.961):
Loading speech dictionary 'builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:12:36.961):
3 loaded records.
DEBUG - core.main (00:12:36.961):
Initializing speech
INFO - synthDrivers.espeak.SynthDriver.__init__ (00:12:37.042):
Using eSpeak NG version 1.49.3 dev
DEBUG - speechDictHandler.SpeechDict.load (00:12:37.117):
Loading speech dictionary 'C:\Users\wweni\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-Serbian.dic'...
DEBUG - speechDictHandler.SpeechDict.load (00:12:37.117):
file 'C:\Users\wweni\AppData\Roaming\nvda\speechDicts\voiceDicts.v1\espeak\espeak-Serbian.dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (00:12:37.117):
Loaded settings for SynthDriver espeak
INFO - synthDriverHandler.setSynth (00:12:37.117):
Loaded synthDriver espeak
INFO - core.main (00:12:37.117):
Using wx version 4.0.3 msw (phoenix) wxWidgets 3.0.5
DEBUG - core.main (00:12:37.117):
Initializing braille input
INFO - brailleInput.initialize (00:12:37.117):
Braille input initialized
DEBUG - core.main (00:12:37.117):
Initializing braille
INFO - braille.initialize (00:12:37.117):
Using liblouis version 3.10.0
INFO - braille.BrailleHandler.setDisplayByName (00:12:37.127):
Loaded braille display driver noBraille, current display has 0 cells.
DEBUG - core.main (00:12:37.127):
Initializing displayModel
DEBUG - core.main (00:12:37.127):
Initializing GUI
DEBUG - core.main (00:12:37.161):
initializing Java Access Bridge support
WARNING - core.main (00:12:37.161):
Java Access Bridge not available
DEBUG - core.main (00:12:37.161):
Initializing legacy winConsole support
DEBUG - core.main (00:12:37.161):
Initializing UIA support
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (00:12:37.177):
UIAutomation: IUIAutomation6
DEBUG - core.main (00:12:37.262):
Initializing IAccessible support
DEBUG - core.main (00:12:37.262):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (00:12:37.262):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (00:12:37.262):
No user gesture map
DEBUG - core.main (00:12:37.262):
Initializing keyboard handler
DEBUG - core.main (00:12:37.262):
initializing mouse handler
DEBUG - core.main (00:12:37.346):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (00:12:37.346):
No touch devices found
DEBUG - core.main (00:12:37.346):
Initializing global plugin handler
DEBUG - core.main (00:12:37.346):
Initializing core pump
DEBUG - core.main (00:12:37.346):
Initializing watchdog
DEBUG - core.main (00:12:37.351):
initializing updateCheck
INFO - core.main (00:12:37.351):
NVDA initialized
DEBUG - core.main (00:12:37.352):
entering wx application main loop
IO - speech.speak (00:12:37.391):
Speaking [u'Desktop  list']
IO - speech.speak (00:12:37.726):
Speaking [u'Google Chrome  4 of 47']
IO - inputCore.InputManager.executeGesture (00:12:38.762):
Input: kb(desktop):enter
IO - speech.speak (00:12:39.619):
Speaking [u'Untitled - Google Chrome']
IO - speech.speak (00:12:40.858):
Speaking [u'Google - Google Chrome']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (00:12:40.869):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUG - treeInterceptorHandler.update (00:12:41.142):
Adding new treeInterceptor to runningTable: <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x04CC57B0>
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.144):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.150):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.155):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.160):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.164):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.171):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.177):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.
IO - speech.speak (00:12:41.180):
Speaking [u'Google  document']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (00:12:41.344):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
DEBUGWARNING - virtualBuffers.VirtualBuffer.prepare (00:12:41.437):
appModule has no binding handle to injected code, can't prepare virtualBuffer yet.

**Comment by dingpengyu** [comment] 2019-10-27 23:29
The problem with
#10423 
repeat

**Comment by nidza07** [comment] 2019-10-27 23:34
A few main differences being that I am running an installed copy, not portable, as well as the fact it does not happen only when you press NVDA space, but rather the browse mode never loads. Also, it's on the latest stable release.

**Comment by beqabeqa473** [comment] 2019-10-28 00:13
hi.

uncheck run nvda as an administrator and problem should go on.

On 10/28/19, nidza07 <notifications@github.com> wrote:
> A few main differences being that I am running an installed copy, not
> portable, as well as the fact it does not happen only when you press NVDA
> space, but rather the browse mode never loads. Also, it's on the latest
> stable release.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/10429#issuecomment-546746744


-- 
with best regards beqa

**Comment by JulienCochuyt** [comment] 2019-10-28 07:49
@nidza07, in addition to the suggestion from @beqabeqa473 in https://github.com/nvaccess/nvda/issues/10429#issuecomment-546750190 have you tried to run the COM Registration Fixing Tool?
NVDA menu > Tools > Run COM Registration Fixing tool

**Comment by Brian1Gaff** [comment] 2019-10-28 09:04
On a new installation? Really?

I don't suppose either of t following might help.
 Did at any time when windows was installed, it attempt to load in avast or 
other third party  miler program.
 is the wn 10 essentials  in. That particular add on is I found absolutely 
essential most of the time, though I have no real understanding of its 
innards, and I cannot test as the only win 10 machine I have is not at home 
right now.
 Otherwise there have been strange browser quirks on different browsers 
popping up a lot of late, though mostly on Firefox, I raised a ticket myself 
on that one with a lot of the none none none issues.
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by JulienCochuyt** [comment] 2019-10-28 09:52
> On a new installation? Really?

Depending on the Windows installation medium, COM registrations can indeed be broken.
I witnessed it recently when assisting a corporate customer in their global migration to Windows 10.

Although the COM Registrations Fixing Tool normally runs during NVDA installation, the report does not state whether any other software was installed after NVDA was and before the issue occurred.

When diagnosing such browse mode issues, running the tool is always a good first step that does not spend much time and can spare a lot.

**Comment by nidza07** [comment] 2019-10-28 12:11
Yes, COM registration fixing came to my mind as well. Even though it mentions only Internet explorer and Firefox, I tried it but nothing changed. I'm not sure I understand Beka's suggestion though. Where exactly do you mean to uncheck run NVDA as an administrator? It's an installed copy, so it has administrative privileges by default, and disallowing those will just introduce other issues, unless you meant something else.

**Comment by nidza07** [comment] 2019-10-28 12:18
Update: I have tried this with chrome version 77.0.3865.90 and browse mode works just fine.

**Comment by leonardder** [comment] 2019-10-29 06:13
Have you tried refocussing the document area with pressing f6 several times? Also, are you able to tab/shift+tab through the pages you're visiting? Do the links and other controls on the page read correctly?

**Comment by mltony** [comment] 2019-11-07 03:01
I'm experiencing a similar problem with my Chrome - it   started recently - about the time this issue was filed.
It seems like starting from one of the recent releases, Chrome no longer allows NVDA to enter browse mode until the page fully loads. Before the page fully loads, it seems like there is no HTML document in the window at all, e.g. pressing F6 or tab would just skip over it.
One day my Internet connection was really bad and all the websites took minutes to load - and browse mode would not activate for minutes - even though someone sighted has confirmed that parts of the webpage were already being displayed.
This seems to be a recent change in Google Chrome - e.g. I remember being able to enter browse mode in chrome much faster after loading new pages.

I tried both NVDA 2019.2 and 2019.3 alpha.
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows 10.

**Comment by beqabeqa473** [comment] 2019-11-07 05:49
hello.

browsemode issue in latest chrome is due to running nvda from an admin user.

we have diagnosed this issue and discovered, that if nvda is running
as administrator user, this problem is starting to happen.


some users even had a tweak in registry which forced all apps to run as admin.

making nvda run as a normal user account with unchecking flag in
compatibility tab or deleting this tweak from registry, fixed problem
in chrome.

On 11/7/19, mltony <notifications@github.com> wrote:
> I'm experiencing a similar problem with my Chrome - it   started recently -
> about the time this issue was filed.
> It seems like starting from one of the recent releases, Chrome no longer
> allows NVDA to enter browse mode until the page fully loads. Before the page
> fully loads, it seems like there is no HTML document in the window at all,
> e.g. pressing F6 or tab would just skip over it.
> One day my Internet connection was really bad and all the websites took
> minutes to load - and browse mode would not activate for minutes - even
> though someone sighted has confirmed that parts of the webpage were already
> being displayed.
> This seems to be a recent change in Google Chrome - e.g. I remember being
> able to enter browse mode in chrome much faster after loading new pages.
>
> I tried both NVDA 2019.2 and 2019.3 alpha.
> Chrome Version 77.0.3865.120 (Official Build) (64-bit)
> Windows 10.
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/10429#issuecomment-550599150


-- 
with best regards beqa

**Comment by dingpengyu** [comment] 2019-11-07 06:03
> hello. browsemode issue in latest chrome is due to running nvda from an admin user. we have diagnosed this issue and discovered, that if nvda is running as administrator user, this problem is starting to happen. some users even had a tweak in registry which forced all apps to run as admin. making nvda run as a normal user account with unchecking flag in compatibility tab or deleting this tweak from registry, fixed problem in chrome.
> […](#)
> On 11/7/19, mltony ***@***.***> wrote: I'm experiencing a similar problem with my Chrome - it started recently - about the time this issue was filed. It seems like starting from one of the recent releases, Chrome no longer allows NVDA to enter browse mode until the page fully loads. Before the page fully loads, it seems like there is no HTML document in the window at all, e.g. pressing F6 or tab would just skip over it. One day my Internet connection was really bad and all the websites took minutes to load - and browse mode would not activate for minutes - even though someone sighted has confirmed that parts of the webpage were already being displayed. This seems to be a recent change in Google Chrome - e.g. I remember being able to enter browse mode in chrome much faster after loading new pages. I tried both NVDA 2019.2 and 2019.3 alpha. Chrome Version 77.0.3865.120 (Official Build) (64-bit) Windows 10. -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#10429 (comment)](https://github.com/nvaccess/nvda/issues/10429#issuecomment-550599150)
> -- with best regards beqa
hello beqabeqa
I tested with NVDA 2019.2.1 and NVDA 2019.3 alpha: Microsoft Edge Canary version 80.0.326.0 and Microsoft Edge Dev version 80.0.320.4, the problem has been solved at the latest edge.

**Comment by mltony** [comment] 2019-11-08 21:43
@beqabeqa473,
I believe I am not running my NVDA as administrator - the checkbox in the compatibility tab is not checked and I didn't do any register tweaks on my computer. I tried checking that checkbox - it didn't seem to affect browser mode behavior.

**Comment by Adriani90** [comment] 2020-01-31 19:16
@mltony are you still seeing this issue in Chrome 79?

**Comment by Adriani90** [comment] 2020-01-31 19:16
I cannot reproduce it with NVDA 2019.3 Beta 4 and Chrome 79.

**Comment by Adriani90** [comment] 2020-04-19 00:18
No update since almost 6 months and there are several crome versions released since then. Closing for now as works for me. If this is still happening, please comment on it and we can reopen. Thanks.

**Closed by Adriani90** 2020-04-19 00:18 UTC
Labels: Chrome, close/worksforme
