### ISSUE TITLE
Select elements are read with hidden and disabled options included in count

### ISSUE THREAD

**Issue by paytown** [nvaccess/nvda#10693] opened 2020-01-17 00:59 UTC
### Steps to reproduce:
- Go to this address with NVDA open: [https://codepen.io/plowe2/pen/VwYGgyO?editors=1010](https://codepen.io/plowe2/pen/VwYGgyO?editors=1010)
- Open menu
- Use arrow keys to navigate up and down through options

### Actual behavior:
NVDA reads selects options as +1 of the visual number in the list

Ex: When 4 options exist. Option 1 ---> "option 2 of 5", said NVDA.

### Expected behavior:
NVDA reads the actual number of non hidden options in list.

Ex: When 4 options exist. Option 1 ---> "option 1 of 4", said NVDA.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2019.2.1

#### Windows version:
MS Windows 10 Enterprise
10.0.17134 Vuild 17134

#### Name and version of other software in use when reproducing the issue:
Chrome 79.0.3945.130

#### Does the issue still occur after restarting your PC?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No

**Comment by Adriani90** [comment] 2020-05-29 23:17
I think this is a general issue in Chrome or Chromium and is quite related to #6097.
Even though the underlying code is a bit different, the effect in the end seems the same. It seems hidden elements are not excluded properly and are still exposed by the browser. This needs an external fix in my opinion.
This is also reproducible in Edge Chromium 83.

cc: @aleventhal, @ObjectInSpace.

**Comment by ObjectInSpace** [comment] 2020-06-01 16:58
Filed https://crbug.com/1088496, thanks!

**Comment by Adriani90** [comment] 2023-03-08 23:57
Closing as works for me. I cannot reproduce anymore with NvDA last alpha and Chrome 111.

**Closed by Adriani90** 2023-03-08 23:57 UTC
Labels: close/worksforme, app/edge, app/chrome, app/edge/anaheim, issue-tracking/crbug
