### ISSUE TITLE
option for NVDA to not automatically read first line of document

### ISSUE THREAD

**Issue by Dennisl123** [nvaccess/nvda#11157] opened 2020-05-12 23:25 UTC

**Comment by DrSooom** [comment] 2020-05-13 02:01
This makes sense for magnifier users.

@Dennisl123: Next time please completely fill out the draft. If you have problems with the multiline text field in the web browser, copy the whole content into the Windows-own Notepad, edit it there and then copy the whole text back in the text field at GitHub. Thanks.

**Comment by Dennisl123** [comment] 2020-05-13 02:20
Sorry for that.  Would this also apply if you were using speech if you add it?

**Comment by Adriani90** [comment] 2020-05-13 05:54
The window title is not read everytime when reading line by line.
What exactly is the issue here?

**Comment by Dennisl123** [comment] 2020-05-13 06:00
The issue is when you open an email it automatically starts reading.

**Comment by Adriani90** [comment] 2020-05-13 06:14
But this occurs only one time when you open the email and you can stop
 it by pressing ctrl key.
 meinem iPhone gesendet

**Comment by Dennisl123** [comment] 2020-05-13 06:16
I would prefer the option to not have it read anything.

**Comment by Adriani90** [comment] 2020-05-13 06:19
Is this in outlook? Or in which programs?

Von meinem iPhone gesendet

**Comment by Dennisl123** [comment] 2020-05-13 06:21
Outlook.

**Comment by Adriani90** [comment] 2020-05-13 19:37
Closing in favor of #11161.

**Comment by Dennisl123** [comment] 2020-05-13 19:49
Why has this been closed?

**Comment by Adriani90** [comment] 2020-05-13 19:51
See issue #11161

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 21:50
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Why has this been closed?

**Comment by Dennisl123** [comment] 2020-05-13 19:53
Unless I’m missing something It reads the first line I don’t want that.  Reading the subject and sender is fine I don’t want it reading the body of the email automatically.

**Comment by Adriani90** [comment] 2020-05-13 19:58
Then see issue #3020. And please try to fill the template with a clear description of your expected behavior in the future. Then we can make sure that discussions are meaningful and investigations are going faster without lots of simple questions. Thanks.

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 21:54
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Unless I’m missing something It reads the first line I don’t want that. Reading the subject and sender is fine I don’t want it reading the body of the email automatically.

**Comment by Dennisl123** [comment] 2020-05-13 20:04
How do I find issue 3020?

**Comment by Adriani90** [comment] 2020-05-13 20:08
If you open the link “issues” on this repository, then you press “e” to go to the edit field. There is already a code snippet filled, that is “is:issue is:open”. After “open “ you just inut the number 3020. And then you can navigate through the search results for example with k to jump from link to link.

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 22:05
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

How do I find issue 3020?

**Comment by Adriani90** [comment] 2020-05-13 20:09
Note that the issue that I referenced is a link. If you open github in your browser you can just press enter on the link in my comment and you will be redirected to the issue automatically.

Otherwise if you want to find an issue, you can also search for key word like "outlook", "reading" etc. You don't have to know the number.

**Comment by Dennisl123** [comment] 2020-05-13 20:14
I don’t see a link in your message.

**Comment by Adriani90** [comment] 2020-05-13 20:16
You are reading the message via your mail client, you have to open the issue in your browser for this to work. Not in the mail client. So you have to go to github.com

 

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 22:15
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

I don’t see a link in your message.

**Comment by Dennisl123** [comment] 2020-05-13 20:29
Issue 3020 seems to be  asking for the email to be read automatically.  I’m asking for the option to have it  not read the body of the email message.

**Comment by Adriani90** [comment] 2020-05-13 20:32
NVDA does not read the whole message body as of now unless you enabled “read entire page after load” in NVDA settings under browse mode settings. And even enabling this setting does not read the email body entirely which was the case in the past. This is what #3020 requests.

 

 

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 22:30
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Issue 3020 seems to be asking for the email to be read automatically. I’m asking for the option to have it not read the body of the email message.

**Comment by Dennisl123** [comment] 2020-05-13 20:37
That wasn’t what my original requested.

**Comment by Adriani90** [comment] 2020-05-13 20:41
Well, I think it’S better to continue the discussion on #3020 since what you are requesting is already possible by turning off automatic reading of entire page after load in NVDA settings under browse mode. If you don’t find something related there, then please create a new issue and fill the template with clear details on what exactly you experience and what exactly you are expecting. Thanks.

 

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 22:37
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

That wasn’t what my original requested.

**Comment by Dennisl123** [comment] 2020-05-13 20:46
It is not possible.  .  Expected behavior

1 press enter on email it reads no part of the body of the email.  Now in outlook 2016 it reads the first few lines.  No settings change I have made has made a difference.

**Comment by Adriani90** [comment] 2020-05-13 20:58
In this case, why would an user need a separate setting for this? Actually it is recommended not to overload NVDA with settings which can already be achieved very easily. Pressing the ctrl key right after pressing enter on the email will stop nvda from reporting the first line.

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Mittwoch, 13. Mai 2020 22:47
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

It is not possible. . Expected behavior

1 press enter on email it reads no part of the body of the email. Now in outlook 2016 it reads the first few lines. No settings change I have made has made a difference.

**Comment by josephsl** [comment] 2020-05-13 21:43
Hi,

For details as to implications of this feature, see recent comments in #11161. To summarize: this feature deals with focus change event behavior for documents. The most recent question I asked there applies to this issue: we need justifications other than a need for this feature, which may convince more people to say "yes" or "we will investigate".

Thanks.

**Comment by DrSooom** [comment] 2020-05-14 04:26
As I already wrote [here](https://github.com/nvaccess/nvda/issues/11157#issuecomment-627699355), this feature will only make sense for magnifier users. To be exactly: I mean visual and haptic readers, who don't use TTS as their primary feedback channel.

And no, pressing CTRL every time, after an e-mail, a document or a web page was opened, isn't a solution, as it rides on the user's nerves relatively quickly – especially because the TSS always starts reading stuff, which isn't desired by the end user to be spoken, because he already can see it visually or haptically.

As NVDA become more and more used by magnifier users, we will have to add features, which aren't really useful for primary auditive readers. We also should think about a GUI related checkbox called "Show advanced settings" in the NVDA Settings dialog, which hides options in that dialog, to keep the amount of options still handy for non-advanced users or NVDA beginners. But that's another topic.

**Comment by Dennisl123** [comment] 2020-05-14 07:08
If this option is added it should be able to be used by users who use speech  as well.  I agree repeatedly pressing the control key is not an option especially if you have a lot of an email a day.

**Comment by Adriani90** [comment] 2020-05-14 19:36
@Dennisl123 your request is still not clear here. Do you want NVDA to be silent only when opening the email? Or when you navigate line by line through the email?
You say:
> If you read line by line you will miss information by it automatically reading

What do you exactly mean by this? If you read line by line NVDA will follow what you read and it will not read something automatically.

You also mentioned that other screen readers do offer this feature. Which screen reader for example? How is the setting called there?

And one further question: do you by chance have enabled "allwo navigation during say all" in NVDA's key board settings?

@josephsl I have the impression that we tap in darkness here. Without a clear issue description from the author we cannot proceed on this.
If we do not get a clear description on what is expected here I vote for closing this issue since I don't see a clear justification for this.

@DrSooom what you mean is discussed in a broad manner like for example issue #4977. But I don't think this is what is requested here.

In my view, if it is requested that NVDA does not report anything when opening a document, then this should be covered in #46 instead of providing lots of low impact options. This could for example be part of a verbosity level for advanced users.

@josephsl I have the impression that we tap in darkness here. Without a clear issue description from the author we cannot proceed on this.
If we do not get a clear description on what is expected here I vote for closing this issue since I don't see a clear justification for this.

cc: @feerrenrut

**Comment by Dennisl123** [comment] 2020-05-14 20:25
When The email is opened I do not want any part of the body of the email spoken.  I do not see the setting you refer to.  Jaws has this option it is called  messages automatically read.

**Comment by Adriani90** [comment] 2020-05-14 20:28
The setting is in NVDA menu > preferences > settings and then under the cathegory “keyboard”. It’s a checkbox called “allow navigation during say all”. This should be disabled by default.

 

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 22:26
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

When The email is opened I do not want any part of the body of the email spoken. I do not see the setting you refer to. Jaws has this option it is called messages automatically read.

**Comment by Dennisl123** [comment] 2020-05-14 20:32
It is disabled.

**Comment by josephsl** [comment] 2020-05-14 20:50
Hi, that setting lives inside Settings Center/Web/HTML/PDF’s category, for which the NVDA equivalent is browse mode settings. You are right in that NVDA does not have a specific setting with the label provided – the closest is “Automatic Say All on page load “. As I implied in my explanation above, this setting is irrelevant to this issue, as this is focus change event behavior – NVDA is fulfilling its expectation that it will announce where the cursor is. As for the reasoning that it helps Magnifier users, we need a definitive confirmation that current NVDA behavior in regards to this issue is truly detrimental to screen magnification software users (to test, run NVDA with Windows Magnifier active and see if focus stays the same or bounces around). Thanks.

**Comment by josephsl** [comment] 2020-05-14 20:54
Hi, for English speakers, it is named “Allow skim reading in Say All”. Again this has nothing to do with the real focus of this issue (I’m afraid). Thanks.

**Comment by Adriani90** [comment] 2020-05-14 20:57
Joseph I think there is a big miss understanding here. If we talk about the jaws setting called “don’T read documents automatically” as suggested by the initial author, then we talk about one single think.

1.	Press enter on an email
2.	NVDA only reports the title of the window but pressing up and down arrow NVDA starts reading line by line as usual.

 

The setting I am talking about is “allow navigation during say all”which is located under key board settings. This is related to the second part of the sentence in the issue description which says that you miss information when reading line by line because NVDA reads the message body automatically. Actually I don’t understand why someone misses information when reading line by line because NVDA reports the line you are focusing. So what kind of information are the users missing?

 

 

Von: Joseph Lee <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 22:51
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Hi, that setting lives inside Settings Center/Web/HTML/PDF’s category, for which the NVDA equivalent is browse mode settings. You are right in that NVDA does not have a specific setting with the label provided – the closest is “Automatic Say All on page load “. As I implied in my explanation above, this setting is irrelevant to this issue, as this is focus change event behavior – NVDA is fulfilling its expectation that it will announce where the cursor is. As for the reasoning that it helps Magnifier users, we need a definitive confirmation that current NVDA behavior in regards to this issue is truly detrimental to screen magnification software users (to test, run NVDA with Windows Magnifier active and see if focus stays the same or bounces around). Thanks.

**Comment by Adriani90** [comment] 2020-05-14 20:58
Please read the issue description, especially the second sentence which says that user is missing information when reading line by line due to automatic reading. This would only happen if skim reading during say all is enabled.

 

 

Von: Joseph Lee <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 22:55
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Hi, for English speakers, it is named “Allow skim reading in Say All”. Again this has nothing to do with the real focus of this issue (I’m afraid). Thanks.

**Comment by josephsl** [comment] 2020-05-14 21:12
Hi,

The keyboard setting noted applies if say all is engaged automatically, which is actually not the case here unless NVDA somehow believes that the document is a browse mode document. In Outlook 365 at least, automatic say all is not engaged (which is different on web interfaces).

A serious follow-up question for Dennis: are you assuming that NVDA Wil perform an automatic say all when a document opens, and is say all automatically engaged whenever you open documents? If yes, what Adriani suggested will resolve it. If not, I'm afraid there's really nothing we can think of. The answer to this question will have implications, including teaching users that not all programs that can open so-called browse mode documents (including some email clients) will force NVDA to read to the end of the document; and that, too me, is a bigger failure - perpetuating wrong assumptions (I'm afraid).

Also, part of the confusion we are experiencing is because we don't have a way to replicate this reliably across programs and documents. This is another reason why you NEED to fill out the template (please do so in the future).

Thanks.

**Comment by Dennisl123** [comment] 2020-05-14 21:17
Ok I just opened your email that you wrote.  It started reading part of the first line.  It has read the entirety of other emails because they are only one line.  I’m using outlook 2016.  What I am wanting is it to not read the body of the email automatically.

**Comment by Dennisl123** [comment] 2020-05-14 21:20
Joseph could this be added as part of an add-on or could an addon be created to accomplish what I am wanting?  Is there someone that could create an addon if that would be an easier way to solve the issue?

**Comment by Adriani90** [comment] 2020-05-14 21:22
Denis sorry to intervene again, could you please post a comment in your native language describing what exactly is your problem and what you expect? I don’t understand your comment. Maybe I am not good enough in english, but I could definitely use something to translate from your native language.

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 23:20
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Joseph could this be added as part of an add-on or could an addon be created to accomplish what I am wanting? Is there someone that could create an addon if that would be an easier way to solve the issue?

**Comment by josephsl** [comment] 2020-05-14 21:42
Hi,

Yep, what Dennis described clears up many things.

As for this being an add-on, yes and no:

* Yes if a global plugin (or a collection of app modules) can detect tree interceptor classes for documents where this proposed behavior is desired and suppress announcement of the line where the cursor is located once it gains focus.
* No because the ideal solution will require patching code in modules that are fundamental to browse mode and speech operations.

Thanks.

**Comment by Adriani90** [comment] 2020-05-14 21:56
Moreover, the reporting should be suppressed only when entering the document, not everytime when the line is focused.

I would rather suggest, if impelementing this at all, to exclude the whole message body as object from being reported when pressing enter, not only the line gaining focus. I think this could be acomplished in the Outlook appmodule, but to be honnest I don’t see any big impact here. Pressing the ctrl key stops reporting the first line. Pressing any other key actually stops reporting the message body. And if you open the email and the body is not reported, you would have to interact with the message body anyway.

 

I will let the decision to anyone else from the community if this should be closed or not. Maybe there is someone who want to invest time in doing this work. But I am quite sure that a PR would need clear justification on what this would improve for an user.

 

Von: Joseph Lee <notifications@github.com> 
Gesendet: Donnerstag, 14. Mai 2020 23:43
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

Hi,

Yep, what Dennis described clears up many things.

As for this being an add-on, yes and no:

*	Yes if a global plugin (or a collection of app modules) can detect tree interceptor classes for documents where this proposed behavior is desired and suppress announcement of the line where the cursor is located once it gains focus.
*	No because the ideal solution will require patching code in modules that are fundamental to browse mode and speech operations.

Thanks.

**Comment by Dennisl123** [comment] 2020-05-14 22:04
As someone else stated pressing control key is not workable when you have a lot of emails.  It would be good if a setting or addon could be added.  It could be unchecked if it is a setting and require the user to enable it should they choose to do so.

**Comment by Adriani90** [comment] 2020-05-14 22:15
But if NVDA does not report anything when the email opens you would have to press a key anyway to interact with the email. Does pressing the ctrl key cause such a big inefficiency? You can even interupt automatic reading by pressing down arow key to read the second line of the email, or by pressing nvda+l to read the current line. This is what you would also do if NVDA does not report anyting when you open the email. So what would improve this new setting? How does this make your day to day work more efficient than it is now?

 

 

 

Von: Dennisl123 <notifications@github.com> 
Gesendet: Freitag, 15. Mai 2020 00:05
An: nvaccess/nvda <nvda@noreply.github.com>
Cc: Adriani90 <adriani.botez@googlemail.com>; State change <state_change@noreply.github.com>
Betreff: Re: [nvaccess/nvda] option for NVDA to not automatically read first line of document (#11157)

 

As someone else stated pressing control key is not workable when you have a lot of emails. It would be good if a setting or addon could be added. It could be unchecked if it is a setting and require the user to enable it should they choose to do so.

**Comment by DrSooom** [comment] 2020-05-15 10:29
@Adriani90: And could you please read the issue title as well?
> option for NVDA to not automatically read first line of document

I totally agree that the issue description and the issue title don't mean the exact same thing, especially the issue description is a little bit odd, but for me it seemed always clear. So I'll try again to give you the desired information in a clearer way. Hopefully I'm not wrong, otherwise @Dennisl123 have to correct me.

### Steps to reproduce:
- Microsoft Outlook/Mozilla Thunderbird: Open an e-mail or a RSS entry in a new window.
- Microsoft Word/LibreOffice Writer: Open a document or create a new one.
- Mozilla Firefox/Google Chrome/Microsoft Edge: Open a web page.
- Adobe Acrobat Reader/Foxit Reader: Open a pdf document.

### Actual Behavior:
The very first line is always spoken by the TTS and shown on a braille display.

### Expected behavior:
The very first line is no longer spoken by the TTS, which makes sense for magnifier users (see [my comment here](https://github.com/nvaccess/nvda/issues/11157#issuecomment-628378574)), but still shown on a braille display. In other words: NVDA should shut up in these situations, if the user wants this.

@josephsl: I don't think that a behavior change for the focus is required here. If there are focus issues in combination with magnifier software, then a new issue should be opened. The goal of this issue here is just to add a simple checkbox, which "automatically press CTRL" every time on processing the above mentioned situations.

**Comment by Dennisl123** [comment] 2020-05-15 10:32
Yes that is correct.  That is what I’m asking for an option the user can set.

**Comment by Adriani90** [comment] 2020-05-15 16:06
@DrSooom why would this be beneficial for a sighted person? NVDA anyway reports the new window title when it opens, so what is the real benefit of suppressing only the reporting of the first line for a sighted person?
Regarding pressing ctrl automatically when an email opens, this will be tricky to implement and could have other issues, i.e. if you press a letter to fast and the system is still processing the ctrl key press, you could end up in a situation where you press a command like ctrl+b for example which would trigger an action in some cases without the intention of the user.
Also note that it is programatically not possible to split speech and braille when something is focused. If you focus something, they are both displayed in braille and reported by speech unless you tether braille to review cursor for example while the review cursor does not follow system focus. So what you are proposing is (I) not possible programatically yet in NVDA and (II) there would not be any benefit for a blind or for a sighted user at all.
More than that, what here is requested is something very specific which would not improve a feature but it would go into the oposit direction. I don't recommend to implement this to be honnest. This option would be too low impact and if we take every small feature as an optional setting, then we end up with a software overloaded with useless settings.
Unless we have a clear justification here that this feature would improve user's experience here. But I don't see any clear justification sofar apart from not having to press a key to stop the reporting which an user would have to do anyway if he or she interacts with the document regardless wether this setting is implemented or not.

And as you see, there are lots of aspects to be considered here for such a low impact setting. Is the community work on this really reasonable and really needed?

**Comment by josephsl** [comment] 2020-05-15 16:28
Hi, actually, there might be a way to do it without emulating a key press, but that will require patching a function that is fundamental to speech operations. Thanks.

**Comment by DrSooom** [comment] 2020-05-16 07:47
> @DrSooom why would this be beneficial for a sighted person? NVDA anyway reports the new window title when it opens, so what is the real benefit of suppressing only the reporting of the first line for a sighted person?

That's quite easy: Visual readers normally don't start reading at the very top of a document or a letter, they're focusing within less than a second to the most important part of a document or letter due to the visual formatting and start reading from this point on. And that's it!

Furthermore they still can use the mouse and set the cursor directly to the part of the document, where NVDA should start reading. Reading the very first line is in most cases irrelevant for them.

And no, I never said something about reading the title bar. You're mixing lots of other things against this issue, which have absolutely nothing to do with this issue. Sorry, but I don't understand your arguments here – at least not yet. Maybe a pause wouldn't bad.

PS: Emulating pressing the CTRL key isn't a good solution by the way. It makes more sense to directly call the procedure to stop reading. Or even better: Add a new procedure that NVDA doesn't start reading in such cases.

**Comment by Dennisl123** [comment] 2020-05-16 07:49
I agree with you.  More over a user configurable option would be the way where you could have the best of both worlds.

**Comment by Adriani90** [comment] 2020-05-16 12:12
@DrSooom I don't really follow your argumentation. When you open a document NVDA reports the window title and the body of the document, sometime only the first line. For sighted person, when he or she is moving the mouse, NVDA reports what's under the mouse. It doesn't make sense at all to stop reporting only the first line. For a low vision user would make much more sense to stop reporting the window title as well and maybe consider even implementing speech on demand. So what you are trying to say it's not a justification for this feature.

Regarding a low vision user starting to read a document on lines other than the first one, such a person does not need to place the focus on a line to read it. So I don't really understand what you are exactly trying to explain.

**Comment by Adriani90** [comment] 2020-05-16 12:14
And again, I think #4977 already addresses the needs of low vision users in this regard anyway.

**Comment by DrSooom** [comment] 2020-05-17 07:46
I suggest to keep this issue here open, as it has nothing to do with issue #4977. After issue #4977 was solved, we should figure out the next steps regarding when on which situations a speech output is still desired and when not. And this issue here is one of them.

@Adriani90: Please ask a sighted person how he reads a letter or a newspaper. With "focusing" I meant focusing primary with the eyes, not with the mouse or the keyboard. Visual and haptic reading are totally different things. You cannot compare them.

**Comment by Dennisl123** [comment] 2020-05-17 07:48
I completely agree.

**Comment by Adriani90** [comment] 2020-05-17 10:46
@DrSooom > Please ask a sighted person how he reads a letter or a newspaper. With "focusing" I meant focusing primary with the eyes, not with the mouse or the keyboard. Visual and haptic reading are totally different things. You cannot compare them.

so we are on the same line here. Tough, suppressing only the first line from reporting does not make sense at all for a sighted person. Either we implement a systematik which  addresses this completely like #4977, or we let it be. For a low vision user it does not make sense to start with such small pieces like this. And unless we do not have the basis, we cannot start now already to raise features which do not make sense at all for now.

Sofar this discussion seems to go into an endless loop and for a developer starting to work on this it will be really difficult to understand what exactly the consensus should be here.
I am closing this issue once again. Please reopen a new one, fill the template completely and provide a clear justification why suppressing only the reporting of the first line of a document would make sense for an user, given the fact that the window title should still be reported and the user has to interact with the document anyway. Regarding improvements for sighted people, please continue the discussion on #4977 since this is a systematical approach. After implementing that, we can start raising specific features for certain cases if you feel that it is needed.

**Closed by Adriani90** 2020-05-17 10:46 UTC

**Comment by Dennisl123** [comment] 2020-05-17 19:32
No You unilaterally decided to close the thread again it should not be closed!

**Comment by Dennisl123** [comment] 2020-05-17 19:33
This thread needs reopened.

**Comment by leonardder** [comment] 2020-05-18 08:08
This thread is very long and messy and there I'm very reluctant to reopen it. I'd suggest opening a new issue using the feature template: https://github.com/nvaccess/nvda/issues/new?template=feature_request.md

@Dennisl123 please pay extra attention to the rationale, i.e. why you think this feature is benefitial).

**Comment by feerrenrut** [comment] 2020-05-18 08:11
Yes, agreed with @leonardder.

The issue description is not complete, and this is a very long discussion that does not clarify the problem.  This issue should stay closed. Please create a new issue and accurately describe the problem.

@Dennisl123 If have trouble with this, please ask for assistance on mailing lists or in your local NVDA community. Alternatively consider NV Access support: https://www.nvaccess.org/product/nvda-telephone-support/
