### ISSUE TITLE
NVDA and Google Search result tables: error and incorrect message.

### ISSUE THREAD

**Issue by fisher729** [nvaccess/nvda#8970] opened 2018-11-21 21:34 UTC
1. Open a web browser (excluding Edge, because it works there)
2. Google "Premier League table" or any result that will place results in a table format.
3. Navigate inside the table. Everything is read in the table just fine.
4. Try and move to the next rows and columns with the Alt+Control+Arrows
Expected: Rows/columns are moved to and read.
Actual: The error message is played, and NVDA says 'edge of table'.

Contents of Error:
ERROR - scriptHandler.executeScript (16:28:12.114):
error executing script: <bound method ChromeVBuf.script_nextColumn of <NVDAObjects.IAccessible.chromium.ChromeVBuf object at 0x05D09890>> with gesture u'alt+ctrl+right arrow'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 187, in executeScript
  File "documentBase.pyo", line 184, in script_nextColumn
  File "documentBase.pyo", line 167, in _tableMovementScriptHelper
  File "virtualBuffers\gecko_ia2.pyo", line 333, in _getTableCellAt
LookupError

Browsers affected: Firefox, Chrome (latest)
Version of NVDA: NVDA 2018.4beta1 and latest alpha

**Comment by fisher729** [comment] 2018-12-10 13:21
Hi.

Any updates on this. I Google these things often, so it's a bit disconcerting.

**Comment by Adriani90** [comment] 2018-12-10 14:05
this is also happening on gmail in the message lsit for example.

**Comment by Adriani90** [comment] 2019-12-20 22:35
I cannot reproduce this anymore on google search page with NVDA 2019.3 Beta 1. @fisher729 can you confirm?

**Comment by fisher729** [comment] 2019-12-21 03:00
I still can. Using latest stable of Firefox with the 2019.3 beta
release. If you google
"premier league standings", you'll see what I mean in the second table
with the standings present.

**Comment by Adriani90** [comment] 2020-04-21 20:40
@fisher729 could you please test now with NVDA 2020.1 Beta and Firefox 75? Or ideally you can test with last alpha version of NVDA from 21.04.2020.
I can navigate through the table without any errors with ctrl+alt+arrow keys.

**Comment by fisher729** [comment] 2020-04-22 19:35
It works here even with 2019.3

**Comment by Adriani90** [comment] 2020-04-23 08:54
Perfect, thanks for reporting. Closing as works for me.

**Closed by Adriani90** 2020-04-23 08:54 UTC
Labels: close/worksforme
