### ISSUE TITLE
Progress bar issues

### ISSUE THREAD

**Issue by danwainwright01** [nvaccess/nvda#7424] opened 2017-07-20 13:31 UTC
When changing the settings for output of progress bars, I am unable to get a percentage unless the option is set to beep and speak. Speak appears to not work.

**Comment by leonardder** [comment] 2017-07-20 19:12
Please provide steps to reproduce your problem as well as information about your system configuration and NVDA version. I'm afraid we won't be able to help you otherwise.

**Comment by danwainwright01** [comment] 2017-07-20 19:30
Win 10 and latest nvda

**Comment by leonardder** [comment] 2017-07-21 04:11
Again, we really need more information.

* Which steps do you take to produce the issue you're having? What software do you use, what actions do you perform in the software?
* What do you expect to happen?
* What happens instead?

**Comment by dan1982code** [comment] 2017-07-21 15:05
@danwainwright01 : for example, I can't reproduce your bug here. When set to Speak, progress bars speak percentages as expected. Without additional information, this bug may end up being closed even though you may have a legitimate bug here. In which application do you notice it? What is the progress bar that isn't working?

**Comment by ehollig** [comment] 2017-08-07 15:14
Closing because @danwainwright01 has not responded to @leonardder's questions in https://github.com/nvaccess/nvda/issues/7424#issuecomment-316897574.
@danwainwright01, if this is still happening, please reply with the steps that you take to produce the issue you're having, the software you use, the actions you perform in the software, what do you expect to happen, and what happens instead?

**Closed by ehollig** 2017-08-07 15:14 UTC
Labels: bug
