### ISSUE TITLE
In Edge NVDA-Cursor isn't able to copy or select more than 2 caracters

### ISSUE THREAD

**Issue by bdorer** [nvaccess/nvda#11060] opened 2020-04-26 12:41 UTC
### Steps to reproduce:
1. Open Edge
2. go to www.nvaccess.org
3. Arrow Down to the donation link
4. Press NVDA+f9 to place start for copying
5. Press Numpad 3 until you here n
6. Press NVDA+f10 one time.
7. Press NVDA+f10 2 times
### Actual behavior:
After Step 6 you here Do selected.
After step 7 you see only do in the clipboard.
### Expected behavior:
After step 6 NVDA should say donation selected.
After step 7 NVDA should say Donation copied to clipboard.
#### NVDA installed/portable/running from source:
installed and portable
#### NVDA version:
2019.2.1 and latest alpha2045.
#### Windows version:
Windows 10.0.18363 64bit
#### Name and version of other software in use when reproducing the issue:
Edge 44.18362.449.0
#### Other information about your system:
Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.20 GHz
8GB RAM
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
yes, it's the same
#### If addons are disabled, is your problem still occuring?
yes
#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
yes, no difference

**Comment by Adriani90** [comment] 2020-04-26 18:23
Could you try in Edge Chromium 81 stable please?

**Comment by Adriani90** [comment] 2020-04-30 13:19
This is not reproducible in Edge Chromium stable 81. Closing since Edge Chromium will be distributed with the next Windows 10 update. However, the label edge / spartan is assigned in case this needs to be reopened after switching bak to UIA at anytime in the future.

**Closed by Adriani90** 2020-04-30 13:19 UTC
Labels: app/edge, app/edge/spartan
