### ISSUE TITLE
LibreOffice Calc: NVDA reports "not selected" for every cell

### ISSUE THREAD

**Issue by surfer0627** [nvaccess/nvda#8988] opened 2018-11-28 03:18 UTC
In NVDA 2018.4beta2, NVDA reports "not selected" for every cell in Calc.

### Steps to reproduce:
1. Open application Calc.
2. Press downArrow to move through cells.

#### Actual behavior:
NVDA reports "not selected" and Cell coordinates.

#### Expected behavior:
NVDA reports Cell coordinates only.

P.S. (If this is the default behavior that NVDA reports "not selected). Could we add an toggle option to turn it on / off?)

#### NVDA Installed/portable/running from source:
Installed.

#### NVDA version:
2018.4beta2

#### Windows version:
6.1.7601 service pack 1

#### Name and version of other software in use when reproducing the issue:

LibreOffice 6.0.7.3

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA?
Yes. This issue does not occur in NVDA 2018.3.2.

**Comment by leonardder** [comment] 2018-11-28 06:35
Most likely caused by #8898 

Cc @michaelDCurran

**Comment by leonardder** [comment] 2018-12-03 08:46
Fixed in #8989

**Closed by leonardder** 2018-12-03 08:46 UTC
Labels: regression
