### ISSUE TITLE
Windows 11: Too much lag in the file explorer

### ISSUE THREAD

**Issue by brunoprietog** [nvaccess/nvda#12956] opened 2021-10-19 00:57 UTC
### Steps to reproduce:

1. In Windows 11, open the file explorer with Windows + E.
2. Enter a folder or the local disk.
3. Browse through the files and folders.

### Actual behavior:

NVDA takes a long time to respond when pressing the arrows to navigate through files and folders. It is practically impossible to move quickly through files without losing information.

### Expected behavior:

NVDA should read the files instantly. In Windows 10 there was also a delay, but it is not as annoying as the one perceived in Windows 11.

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2021.2

#### Windows version:

Windows 11 21H2 (x64) build 22000.258

#### Other information about your system:

Intel I7 8650U with 16 Gb Ram and 512 gb SSD

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

No

#### If NVDA add-ons are disabled, is your problem still occurring?

Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?

Yes

**Comment by josephsl** [comment] 2021-10-19 01:06
Hi, keep an eye out for build 22000.28x as apparently this issue is mitigated somewhat. Thanks.

From: Bruno Prieto ***@***.***> 
Sent: Monday, October 18, 2021 5:58 PM
To: nvaccess/nvda ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nvaccess/nvda] Windows 11: Too much lag in the file explorer (Issue #12956)

 


Steps to reproduce:


1.	In Windows 11, open the file explorer with Windows + E.
2.	Enter a folder or the local disk.
3.	Browse through the files and folders.


Actual behavior:


NVDA takes a long time to respond when pressing the arrows to navigate through files and folders. It is practically impossible to move quickly through files without losing information.


Expected behavior:


NVDA should read the files instantly. In Windows 10 there was also a delay, but it is not as annoying as the one perceived in Windows 11.


System configuration


NVDA installed/portable/running from source:


Installed


NVDA version:


2021.2


Windows version:


Windows 11 21H2 (x64) build 22000.258


Name and version of other software in use when reproducing the issue:


Other information about your system:


Intel I7 8650U with 16 Gb Ram and 512 gb SSD


Other questions


Does the issue still occur after restarting your computer?


Yes


Have you tried any other versions of NVDA? If so, please report their behaviors.


No


If NVDA add-ons are disabled, is your problem still occurring?


Yes


Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?


Yes

**Comment by brunoprietog** [comment] 2021-10-22 03:51
I just received the Windows 11 21H2 (x64) build 22000.282 update and I still feel annoying lag when browsing files and folders. This update was supposed to improve performance in scrolling through the file explorer, but at least as far as NVDA goes I feel it the same.

**Comment by mazen428** [comment] 2021-10-29 23:32
Strange thing is, Jaws works pretty well in file explorer, while NVDA and Narrator are just as laggy, not sure exactly why.
I tried disabling UIA in config and it seems to be back to normal, obviously this isn't a good idea and know one should do that by the way, but anyway, it might be useful info to know.

**Comment by brunoprietog** [comment] 2021-11-10 09:30
An update. Windows 11 update KB5007215 comes with file explorer performance improvements, but in terms of NVDA behavior it remains exactly the same. Windows 11 21H2 (x64) build 22000.318

**Comment by brunoprietog** [comment] 2022-02-08 09:08
Another update. I now have Windows 11 21H2 (x64) build 22000.469 and the lag is reduced, back to a similar level to Windows 10, although I feel it is a bit longer. Anyway, there is still perceived lag. The menu bar bug that caused unnecessary calculations when moving through files and folders is now fixed.

**Comment by cary-rowen** [comment] 2022-03-16 06:12
Seriously, I think NVDA is very slow to respond in both Windows 10 and Windows 11 explorer.

**Comment by Adriani90** [comment] 2023-04-05 23:15
Closing as duplicate of #8224.

**Closed by Adriani90** 2023-04-05 23:15 UTC
Labels: close/duplicate, performance, platform/Windows11, feature/windows-explorer
