### ISSUE TITLE
PowerPoint 2013 crashes NVDA when closing

### ISSUE THREAD

**Issue by tech55541** [nvaccess/nvda#5816] opened 2016-03-16 23:47 UTC
Hello,
Sometimes when closing PowerPoint 2013, NVDA will randomly crash. I have seen this happen the most when closing PowerPoint with Firefox open, it has also happened when Microsoft Outlook 2013 was opened. I am running Windows 7 Professional, latest version of Firefox and updates for Office/windows.

Thanks.

**Comment by jcsteh** [comment] 2016-03-16 23:53
Duplicate of #4479. Moving discussion there.

**Closed by jcsteh** 2016-03-16 23:53 UTC
Labels: duplicate

**Comment by tech55541** [comment] 2016-03-16 23:55
Sorry for the duplicate, glad you all are aware. 

Thanks.
