### ISSUE TITLE
Crippling lag with NVDA and Firefox on Google's homepage

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#8035] opened 2018-02-24 11:14 UTC
#### Steps to reproduce:

Go to https://google.com with NVDA and firefox. Find the search field and activate forms mode.

#### Expected behavior:

NVDA and Firefox should not freeze.

#### Actual behavior:

NVDA and firefox will freeze. This doesn't occur all the time - I suspect this may be caused by the doodle which changes. Its so bad that I'm forced to restart my computer, since NVDA can become unresponsive even when switching out of Firefox.

#### System configuration:
NVDA version: master-14883,c83231ec

NVDA Installed or portable: installed

Other information:

Windows version:
Windows 10 1709

Name and version of other software in use when reproducing the issue:
Firefox 52 ESR (anecdotally, heard multiple reports from others), 57, 58 developer's edition

#### Other questions:

Does the issue still occur after restarting your PC?
Yes

Have you tried any other versions of NVDA?
No

**Comment by ehollig** [comment] 2018-02-28 02:20
I am not able to reproduce this issue. @Neurrone, is this still happening for you? Could you provide an NVDA log with logging set to debug?

**Comment by Neurrone** [comment] 2018-02-28 04:16
@ehollig I'll let you know when this comes up again. I'm not sure how I can produce a log though, since I'm forced to restart my computer using the power button when that happens.

**Comment by Adriani90** [comment] 2019-05-02 21:52
This is not reproducible in NVDA 2019.1.1 and Firefox 66.0.3. I am closing this as works for me. Please comment on it if you still have the problem and we can reopen the discussion. Thanks!

**Closed by Adriani90** 2019-05-02 21:52 UTC
Labels: worksforme
