### ISSUE TITLE
Problems with several Handytech braille displays in NVDA 2018.1, probably com issue

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#8081] opened 2018-03-13 19:39 UTC
Hello all,

we have several users reporting issues with their handytech braille displays on different windows version with NVDA 2018.1.

Following displays are being disconnected automatically:
* Handytech BS40 (Braille Star)
* Handytech modular braille displays
* Handytech active and active star

Here is part of log file:

```
INFO - __main__ (14:43:46.621):
Starting NVDA
INFO - core.main (14:43:46.778):
Config dir: C:\Users\Admin\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (14:43:46.778):
Loading config: C:\Users\Admin\AppData\Roaming\nvda\nvda.ini
INFO - core.main (14:43:46.854):
NVDA version 2018.1
INFO - core.main (14:43:46.854):
Using Windows version 10.0.16299 workstation
INFO - core.main (14:43:46.855):
Using Python version 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
INFO - core.main (14:43:46.855):
Using comtypes version 1.1.3
INFO - synthDriverHandler.setSynth (14:43:47.141):
Loaded synthDriver eloquence
INFO - core.main (14:43:47.141):
Using wx version 3.0.2.0 msw (classic)
INFO - brailleInput.initialize (14:43:47.144):
Braille input initialized
INFO - braille.initialize (14:43:47.144):
Using liblouis version 3.3.0
INFO - braille.BrailleHandler.setDisplayByName (14:43:50.276):
Loaded braille display driver handyTech, current display has 40 cells.
ERROR - braille.BrailleHandler._writeCells (14:43:50.355):
Error displaying cells. Disabling display
Traceback (most recent call last):
File "braille.pyo", line 1604, in _writeCells
File
"C:\Users\Admin\AppData\Roaming\nvda\addons\handy_tech_braille_driver\brailleDisplayDrivers\handyTech.py",
line 160, in display
File "comtypes\__init__.pyo", line 659, in call_with_inout
AttributeError: 'tuple' object has no attribute '__ctypes_from_outparam__'
INFO - braille.BrailleHandler.setDisplayByName (14:43:50.438):
Loaded braille display driver noBraille, current display has 0 cells.
WARNING - core.main (14:43:50.438):
Java Access Bridge not available
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (14:43:50.438):
UIAutomation: IUIAutomation3
INFO - core.main (14:43:51.301):
NVDA initialized
WARNING - eventHandler._EventExecuter.next (14:43:51.335):
Could not execute function event_becomeNavigatorObject defined in globalPlugins.audioThemes module due to unsupported kwargs: {'isFocus': 
True}
Traceback (most recent call last):
File "eventHandler.pyo", line 100, in next
TypeError: event_becomeNavigatorObject() got an unexpected keyword argument 'isFocus'
INFO - globalCommands.GlobalCommands.script_navigatorObject_devInfo
(14:43:53.167):
Developer info for navigator object:
name: None
role: ROLE_UNKNOWN
states: STATE_INVISIBLE, STATE_FOCUSABLE, STATE_FOCUSED
isFocusable: True
hasFocus: True
Python object: <NVDAObjects.IAccessible.ContentGenericClient object at 
0x073E8B30>
Python class mro: (<class
'NVDAObjects.IAccessible.ContentGenericClient'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <type 'object'>)
description: None
location: (0, 0, 0, 0)
value: u''
appModule: <'explorer' (appName u'explorer', process ID 5352) at address 
73e8b70>
appModule.productName: u'Betriebssystem Microsoft\xae Windows\xae'
appModule.productVersion: u'10.0.16299.15'
TextInfo: <class 'displayModel.DisplayModelTextInfo'>
windowHandle: 65810
windowClassName: u'ApplicationManager_DesktopShellWindow'
windowControlID: 0
windowStyle: -2080374784
windowThreadID: 4936
windowText: u''
displayText: u''
IAccessibleObject: <POINTER(IAccessible) ptr=0x26c8578 at 7339b70>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=65810, objectID=-4, childID=0
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_CLIENT
IAccessible accState: STATE_SYSTEM_INVISIBLE, STATE_SYSTEM_FOCUSED, STATE_SYSTEM_FOCUSABLE, STATE_SYSTEM_VALID (1081348)
IAccessible accDescription: None
IAccessible accValue: None
```

**Comment by Adriani90** [comment] 2018-03-13 20:15
Active star works properly in windows 10 but not in windows 7.

**Comment by Adriani90** [comment] 2018-03-13 21:08
The same for modular 40  braille display

**Comment by leonardder** [comment] 2018-03-14 11:49
It seems the person from this log file has the Handy Tech braille driver installed. Removing this driver should fix most of the problems.

I had a short talk with @FelixGruetzmacher about this. Even though the used driver is an add-on and therefore not part of the NVDA core, the add-on did work in NVDA 2017.4 (older comtypes). Therefore, I'm labelling this as a regression. @michaeldcurran and @feerrenrut, It might be good to investigate this (i.e. whether this is an incompatibility in the legacy ht driver, or whether it is a bug in comtypes).

In any case, thanks for reporting!

**Comment by Adriani90** [comment] 2018-06-17 18:53
Braillestar40 works now properly in NVDA 2018.2. However, when switching the braillestar off and on again, the driver does not connect the braille display automatically.

**Comment by FelixGruetzmacher** [comment] 2018-06-18 07:30
That's expected, as autodetection is not yet in place. As soon as we have
autodetection, NVDA will switch to the appropriate driver as soon as a
device is found, which will provide the perfect illusion of a re-connect
when in fact it's a detect-and-use.

Am So., 17. Juni 2018 um 20:53 Uhr schrieb Adriani90 <
notifications@github.com>:

**Comment by leonardder** [comment] 2018-08-14 16:44
@Adriani90: Is this still applicable to NVDA 2018.3 Alpha and Beta versions?

**Comment by bdorer** [comment] 2018-12-02 22:09
I've got a BRW40 and can't reproduce any disconnect errors. The classic 
driver addon from handytech works with latest nvda next without the 
configuration dialog. Probably caused by wxpy4 incompatibility.

I'll ask the German community wheather they have problems with handytech 
displays.

**Comment by leonardder** [comment] 2019-01-22 17:37
I'm closing this as works for me. Please shout out if you believe this is wrong.

**Closed by leonardder** 2019-01-22 17:37 UTC
Labels: p2, regression
