### ISSUE TITLE
LibreOffice Calc: Selecting All Cells Crashes LibreOffice Calc

### ISSUE THREAD

**Issue by mush42** [nvaccess/nvda#13773] opened 2022-06-06 19:18 UTC
### Steps to reproduce:

* Start LibreOffice Calc. The focus will land in a fresh sheet
* Either of the following causes LibreOffice Calc to crash:
    * Select all cells using Ctrl+A
    * Select all rows of a specific column (e.g. A) by hitting Ctrl+down Arrow

### Actual behavior:
LibreOffice crashes by showing the familiar Windows dialog: LibreOffice Calc is not responding

### Expected behavior:
Selecting all cells should not crash LibreOffice Calc

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2022.1

#### Windows version:
Windows version: Windows 11 21H2 (10.0.22000) workstation

#### Name and version of other software in use when reproducing the issue:
LibreOffice Version: 7.3.3.2 (x64) / LibreOffice Community
Build ID: d1d0ea68f081ee2800a922cac8f79445e4603348
CPU threads: 8; OS: Windows 10.0 Build 22000; UI render: Skia/Vulkan; VCL: win
Locale: en-US (en_US); UI: en-US
Calc: CL

#### Other information about your system:
Intel Core i7 - 16 GB of RAM

#### Does the issue still occur after restarting your computer?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No.

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes.

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes.

**Comment by seanbudd** [comment] 2022-06-09 05:43
Duplicate of #13232

**Closed** 2022-06-09 05:45 UTC
