### ISSUE TITLE
significant  lag in Word 2016

### ISSUE THREAD

**Issue by netblue44** [nvaccess/nvda#7241] opened 2017-06-01 15:24 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
When Reading line by line with the arrow  keys or reading by paragraph  in word 2016
There is a half second delay before anything is red by NVDA. This is a 3 to 4 times slower than JAWS and Narrator.
I have tried with many documents long and small result is the same.
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f
All that i have tried.
NVDA Installed or portable:
Installed
Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066
Windows Creator
Name and version of other software in use when reproducing the issue:
Office 2016 Pro
### Other questions:

Does the issue still occur after restarting your PC?
Yes
Have you tried any other versions of NVDA?
> Please list them and the result
Post 2017.1 same result

**Comment by ehollig** [comment] 2018-04-18 20:45
@netblue44, is this still an issue? NVDA has made some changes with Word 2016 over the past year which has probably improved this experience.

**Comment by netblue44** [comment] 2018-04-18 21:17
In summ documents it is still so but with UIA  support IN WORD 2016 WHEN 
IT becomes oficial I thingk this problem will be solved.

**Comment by Adriani90** [comment] 2019-04-17 23:36
@netblue44 in NVDA 2019.1 there is a significant performance improvement made in MS Word. Are you still having this issue? Could you please test with UIA disabled?

**Comment by leonardder** [comment] 2019-10-28 07:17
@netblue44 Have you tried to disable some document formatting options you may be don't need, particularly pages, revision, etc.?

**Comment by zstanecic** [comment] 2019-10-28 07:19
Hi @leonardder

 

Combining with disabling something is not an option, as this process injection is buggy.

**Comment by Adriani90** [comment] 2023-03-07 11:03
Closing as duplicate of #10452.

**Closed by Adriani90** 2023-03-07 11:03 UTC
Labels: close/duplicate
