### ISSUE TITLE
Downgrade warning dialog is visually broken

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5325] opened 2015-08-29 14:18 UTC
**Reported by nishimotz on 2015-08-29 14:18**
Downgrade warning dialog of NVDA 2015.3 introduced by #5037 is visually broken.
Proceed and Cancel buttons are not shown in the window correctly.

The following patch should fix this:

```
diff --git a/source/gui/installerGui.py b/source/gui/installerGui.py
index 8438921..4ddb712 100644
--- a/source/gui/installerGui.py
+++ b/source/gui/installerGui.py
@@ -161,8 +161,11 @@ def showInstallGui():
            # Translators: The label of a button to proceed with installation,
            # even though this is not recommended.
            label=_("&Proceed with installation (not recommended)"))
+       sizer.Add(item)
        item = wx.Button(d, id=wx.ID_CANCEL)
        item.SetFocus()
+       sizer.Add(item)
+       mainSizer.Add(sizer)
        d.Sizer = mainSizer
        mainSizer.Fit(d)
        d.Center(wx.BOTH | wx.CENTER_ON_SCREEN)
```

**Comment by leonardder** [comment] 2017-07-22 15:23
Hmm, this is a strange one. This should have been closed by https://github.com/nvaccess/nvda/commit/fb00b52f7d3c81210dad81b584fd0170c0b47215, but it is still open. Probably because the particular commit ended up in a squashed commit which didn't explicitly state the closure of this issue. Confirmed that this code is in master, so closing anyway.

**Closed by leonardder** 2017-07-22 15:23 UTC
Labels: bug
