### ISSUE TITLE
"Speak Command Keys": don't speak arrow keys

### ISSUE THREAD

**Issue by jmuheim** [nvaccess/nvda#5608] opened 2015-12-14 15:58 UTC
I'd like NVDA to speak key combinations like Ctrl+N, but I don't want it to announce general browse keys, e.g. up arrow, down arrow, etc.

Is there a way to do this?

**Comment by ruifontes** [comment] 2015-12-14 16:02
Unfortunately not yet!

I would like to have a kind of keyboard manager, where we could set wich 
keys should be spoken and how...

Rui Fontes


-----Mensagem Original----- 
De: Joshua Muheim
Data: segunda-feira, 14 de dezembro de 2015 15:58
Para: nvaccess/nvda
Assunto: [nvda] "Speak Command Keys": don't speak arrow keys (#5608)



I'd like NVDA to speak key combinations like Ctrl+N, but I don't want it to 
announce general browse keys, e.g. up arrow, down arrow, etc.

Is there a way to do this?

-

**Comment by bhavyashah** [comment] 2015-12-14 17:38
Hi,
Even if a solution as advanced as a configurable Keyboard Manager was
not introduced, at least, speak command keys should either not have
the arrow keys at all, or introduce a third mode/toggle where all keys
apart from arrow keys would be spoken.
This has been requested before as well on the issue tracker I think,
on the NVDA Users list for sure more than once as well, and talking to
other NVDA users also resulted this request once or twice.
Thanks.

On 12/14/15, ruifontes <notifications@github.com> wrote:
> Unfortunately not yet!
>
> I would like to have a kind of keyboard manager, where we could set wich
> keys should be spoken and how...
>
> Rui Fontes
>
>
> -----Mensagem Original-----
> De: Joshua Muheim
> Data: segunda-feira, 14 de dezembro de 2015 15:58
> Para: nvaccess/nvda
> Assunto: [nvda] "Speak Command Keys": don't speak arrow keys (#5608)
>
>
>
> I'd like NVDA to speak key combinations like Ctrl+N, but I don't want it to
>
> announce general browse keys, e.g. up arrow, down arrow, etc.
>
> Is there a way to do this?
>
> -
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5608#issuecomment-164476310


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Comment by josephsl** [comment] 2015-12-14 17:49
Hi,

 

Yes, that’s correct: this is a special duplicate of an issue raised a while ago. Again I’d close this issue (only if I can find the duplicate of this), seeing that some might want to keep announcement of arrow keys on, and this is a subjective issue.

Thanks.

**Comment by josephsl** [comment] 2015-12-14 17:56
Hi,
This is a duplicate of [ticket 5484](https://github.com/nvaccess/nvda/issues/5484). See the original post on that ticket and responses from I and Jamie as to why we're closing this ticket. Thanks.

**Comment by bhavyashah** [comment] 2015-12-14 17:57
Hey Joseph,
If I am not wrong, Suman Dogra filed the earlier issue that this
ticket duplicates. Maybe that might quicken and simplify your
duplicate ticket search...
Thanks.

On 12/14/15, josephsl <notifications@github.com> wrote:
> Hi,
>
>
>
> Yes, that’s correct: this is a special duplicate of an issue raised a while
> ago. Again I’d close this issue (only if I can find the duplicate of this),
> seeing that some might want to keep announcement of arrow keys on, and this
> is a subjective issue.
>
> Thanks.
>
>
>
>
>
> From: bhavyashah [mailto:notifications@github.com]
> Sent: Monday, December 14, 2015 9:38 AM
> To: nvaccess/nvda <nvda@noreply.github.com>
> Subject: Re: [nvda] "Speak Command Keys": don't speak arrow keys (#5608)
>
>
>
> Hi,
> Even if a solution as advanced as a configurable Keyboard Manager was
> not introduced, at least, speak command keys should either not have
> the arrow keys at all, or introduce a third mode/toggle where all keys
> apart from arrow keys would be spoken.
> This has been requested before as well on the issue tracker I think,
> on the NVDA Users list for sure more than once as well, and talking to
> other NVDA users also resulted this request once or twice.
> Thanks.
>
> On 12/14/15, ruifontes <notifications@github.com> wrote:
>> Unfortunately not yet!
>>
>> I would like to have a kind of keyboard manager, where we could set wich
>> keys should be spoken and how...
>>
>> Rui Fontes
>>
>>
>> -----Mensagem Original-----
>> De: Joshua Muheim
>> Data: segunda-feira, 14 de dezembro de 2015 15:58
>> Para: nvaccess/nvda
>> Assunto: [nvda] "Speak Command Keys": don't speak arrow keys (#5608)
>>
>>
>>
>> I'd like NVDA to speak key combinations like Ctrl+N, but I don't want it
>> to
>>
>> announce general browse keys, e.g. up arrow, down arrow, etc.
>>
>> Is there a way to do this?
>>
>> -
>> Reply to this email directly or view it on GitHub.
>>
>>
>>
>>
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/nvaccess/nvda/issues/5608#issuecomment-164476310
>
>
> --
> Warm Regards
> Bhavya Shah
> Using NVDA (Non Visual Desktop Access) free and open source screen
> reader for Microsoft Windows
> To download a copy of the free screen reader NVDA, please visit
> http://www.nvaccess.org/
> Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
> Reach me through the following means:
> Mobile: +91 7506221750
> E-mail id: bhavya.shah125@gmail.com
> Skype id : bhavya.09
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nvaccess/nvda/issues/5608#issuecomment-164504984> .
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/nvaccess/nvda/issues/5608#issuecomment-164508157


-- 
Warm Regards
Bhavya Shah
Using NVDA (Non Visual Desktop Access) free and open source screen
reader for Microsoft Windows
To download a copy of the free screen reader NVDA, please visit
http://www.nvaccess.org/
Using Google Talkback on Motorolla G second generation Lollipop 5.0.2
Reach me through the following means:
Mobile: +91 7506221750
E-mail id: bhavya.shah125@gmail.com
Skype id : bhavya.09

**Closed by josephsl** 2015-12-14 17:56 UTC
