### ISSUE TITLE
NVDA Nemeth Code Support 

### ISSUE THREAD

**Issue by rthomas2018** [nvaccess/nvda#8840] opened 2018-10-13 18:09 UTC
### Actual behavior:

When using NVDA, MathML expressions will output on my braille display in Nemeth code only if they are a single line in length.

Any expressions longer than a single line will read verbally, but will not provide any braille output. 

### Expected behavior:

As long as I have verbal output, I should also have braille output, even for longer expressions. 

### System configuration:

Dell Lattitude 5580 
Intel Core I5  
8 GB RAM
Motherboard: Dell Inc. 0413VC

Note: These issues have been seen on another system. I don't know the specs for that unit.

#### NVDA Installed/portable/running from source:

Installed version of NVDA.

#### NVDA version:

2018.2.1

#### Windows version:

Windows Pro 10 64 bit

#### Name and version of other software in use when reproducing the issue:

Firefox 62.0.3 (64 bit)
Google Chrome 69.0.3497.100  
Internet Explorer 11.258.13147.0

#### Other information about your system:

Issue seen on multiple systems. No additional information.

### Other questions:

None

#### Does the issue still occur after restarting your PC?

Yes

#### Have you tried any other versions of NVDA?

No

**Comment by dkager** [comment] 2018-10-24 18:16
Is this while using MathPlayer?

It seems that the problem is a lack of braille output for multi-line expressions, rather than no Nemeth support at all. If so, the issue title should be updated to reflect that.

**Comment by Adriani90** [comment] 2024-05-25 13:05
This should be fixed now that the braille can follow speech. You can set braille to follow speech in braille settings in NVDA 2024.2 Beta.
Does this solve your problem?

**Comment by SaschaCowley** [comment] 2024-07-18 01:30
@Adriani90, perhaps I'm missing something, but I don't see how this would help? @rthomas2018's issue is that Nemeth expressions longer than a single line aren't being output. Your solution would output the math in worded form, wouldn't it?
Regardless, this issue is presumably with Math Player which is no longer supported.

**Closed by SaschaCowley** 2024-07-18 01:30 UTC
Labels: component/braille

**Comment by Adriani90** [comment] 2024-07-18 03:14
Sascha thanks for looking into this, yes you are right.
