### ISSUE TITLE
List items in Excel 2013 are not read.

### ISSUE THREAD

**Issue by feerrenrut** [nvaccess/nvda#6459] opened 2016-10-13 04:02 UTC
Not a duplicate of #6452. The effect is different for MS Excel 2013

Using MS Excel 2013. To recreate, from any cell in an Excel spreadsheet:

Press ALT+A for the Data ribbon
Press V for the Data Validation menu
Press V again to open the Data Validation dialog
TAB to "Allow" and choose "List".
TAB to Source, and type:
1,2,3
Press ENTER

From that cell, press ALT+DOWN ARROW to open the list, and down arrow through the list. NVDA does not read out the items.

**Comment by feerrenrut** [comment] 2016-10-13 04:05
p2 since this makes it impossible for users to access dropdown suggestion lists.

**Comment by Adriani90** [comment] 2019-03-09 11:03
This seems also to be the case in Excel 2016 / 365. cc: @lukaszgo1

**Comment by Adriani90** [comment] 2020-05-03 20:31
I get following error in MS Excel 365, the issue is also that the items are not read by NVDA:

```
IO - inputCore.InputManager.executeGesture (22:29:05.997) - winInputHook (9612):
Input: kb(laptop):shift+NVDA+downArrow
ERROR - scriptHandler.executeScript (22:29:06.017) - MainThread (11924):
error executing script: <bound method GlobalCommands.script_navigatorObject_firstChild of <globalCommands.GlobalCommands object at 0x069F3AF0>> with gesture 'Umschalt+NVDA+Pfeiltaste nach unten'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "globalCommands.pyc", line 990, in script_navigatorObject_firstChild
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 844, in _get_simpleFirstChild
  File "baseObject.pyc", line 42, in __get__
  File "baseObject.pyc", line 145, in _getPropertyViaCache
  File "NVDAObjects\window\excel.pyc", line 1570, in _get_firstChild
IndexError: list index out of range
```

**Comment by Qchristensen** [comment] 2020-05-13 05:33
Just clarifying, this issue is different to #10401, as this issue is about reading the drop-down list itself, whereas in #10401, the list itself is read (possibly twice, as per #6452), however NVDA loses focus upon leaving the list.

**Comment by kayatli** [comment] 2020-07-09 15:04
This is still an issue with NVDA 2020.2 Beta2 with Office 365. Wonder if this issue along with other issues referenced in previous comments may be related to #10589 although that deals with extraneous info whereas this is not reading any items in a dropdown.

**Comment by Qchristensen** [comment] 2023-04-20 01:41
Testing this now with:

NVDA 2023.1.0.27913 
Windows 11 (64-bit) Version: 22H2, Build: 22621.1555 
Office 365 (64-bit) Version: 16.0.16227.20244 

When you press alt+down arrow to open the list, NVDA reads:

combo box  expanded  Has a data validation drop-down menu.
2
2

Reading the selected item twice (in this case 2 was selected).  If you up and down arrow through the list at this point, NVDA reads each option once.

**Comment by Adriani90** [comment] 2023-04-20 12:48
Ok, so I am closing this issue now as works for me, @Qchristensen could you open then a new issue about the repetition of the selected option when entering the list?

**Closed by Adriani90** 2023-04-20 12:48 UTC
Labels: bug, close/worksforme, app/microsoft-office, p2
