### ISSUE TITLE
NVDA adds extra chatter when switching among tabs in Chrome

### ISSUE THREAD

**Issue by amirsol81** [nvaccess/nvda#8140] opened 2018-04-02 06:07 UTC
When Control+Tab and Control+Shift+Tab are used to switch among open tabs in Google Chrome, one expects NVDA to read the title of tabs as they gain focus. However, NVDA tends to read stuff like the address bar and the text inside it, messages like "has auto complete" or "menu button  View site information" before reading the title of the focused tab. This is really annoying and gets in the way of efficiently moving around tabs as one should wait to see if the newly focused tab is the desired one first.
This is tested with Google Chrome version 65.0.3325.181 and NVDA 2018.1.1 on a Windows 10 Pro 64-Bit, V1709.

**Comment by derekriemer** [comment] 2018-04-02 23:09
I've seen this too.

**Comment by amirsol81** [comment] 2018-04-03 02:57
Thanks for duplicating. This can also be observed on my Windows 7
Ultimate SP1 64-Bit work machine, so is OS-independent.

**Comment by NicklasMCHD** [comment] 2018-04-29 12:31
This is also the case for a Windows 10 Pro 64 bit build 16299 running the latest released version of NVDA and the latest version of Google Chrome.

**Comment by Adriani90** [comment] 2019-12-20 19:45
This is not reproducible in NVDA 2019.3 Beta 1 and Chrome 79 anymore. Closing as works for me.

**Closed by Adriani90** 2019-12-20 19:45 UTC
Labels: Chrome, worksforme
