### ISSUE TITLE
When placing the focus with the tab key in a table the nvda does not inform the cell text in focus 

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#9377] opened 2019-03-14 13:47 UTC
### Steps to reproduce:
I am working in an organization where there is a java application, this application has internal development, and unfortunately I can not grant external access to this application, and I do not have programming knowledge for great splendor.
However I believe this problem may occur in other java applications.
Open a java application that has some controls, between these controls there is a filled table.
When I am walking with the tab key by the application and the focus is placed on the table with content:
### Actual behavior:
Nvda announces only table
### Expected behavior:
nvda could advertise table and cell contents in focus.
I can read the contents of the cell if I walk with diagonal arrows.
#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
2018.4.1
#### Windows version:
10 1803
#### Name and version of other software in use when reproducing the issue:
aplication java jre 8 update 201
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA?
no
[table_java.txt](https://github.com/nvaccess/nvda/files/2966684/table_java.txt)

**Comment by mwhapples** [comment] 2022-11-09 16:55
This can be reproduced using the JDK demo application swingset2.

**Comment by Adriani90** [comment] 2024-06-24 17:30
This is not reproducible with NVDA 2024.2 and last jdf swingset version from here:
https://www.jdeploy.com/~jdeploy-demo-swingset2

The table demo works as expected when using arrow keys or tab key. Make sure Java access bridge is enabled.
Closing as works for me. In case you are still having this issue. please comment and we can reopen.

**Closed by Adriani90** 2024-06-24 17:30 UTC
Labels: close/worksforme, component/java-access-bridge
