### ISSUE TITLE
NVDA shows irelevant search results in certain web pages

### ISSUE THREAD

**Issue by ondrosik** [nvaccess/nvda#12256] opened 2021-04-01 08:43 UTC
When I search for certain string on this website:
http://kiwisdr.com/public/
NVDA shows also other irelevant results not related to entered string.

Steps to reproduce
:

-Open http://kiwisdr.com/public/
(I can reproduce it in Chrome and firefox)
- Invoke search dialog nvda+ctrl+f
- Type "czech" and press enter
- Depending on the current table status you will see something like UK or something different.
- - By navigating forward pressing nvda+F3 cursor jumps to other right occurences of this string but also to other not related to czech at all.
- You can test this also with other strings, like slovak.
- If I enter something what is not there at all, like abcdefghijklmno that is not found as expected

Tested on two machines with Windows 10, NVDA 2020.4 installed

**Comment by Adriani90** [comment] 2023-04-12 22:15
Very strange behavior here in my opinion.
I didn't see this on other websites though.

**Comment by CyrilleB79** [comment] 2024-03-29 20:55
Closing as duplicate of #16317 where there are more explanations.
Thanks @Adriani90 for having mentioned it.

**Closed by CyrilleB79** 2024-03-29 20:55 UTC
