### ISSUE TITLE
Browse mode doesn't work on some sites in Firefox

### ISSUE THREAD

**Issue by a11cf0** [nvaccess/nvda#10480] opened 2019-11-11 14:49 UTC
### Steps to reproduce:
Open Firefox and go to https://petitions.by/petitions/3014

### Actual behavior:
The page loads, but the browse mode document is completely empty. However, it's somewhat possible to navigate the page using the system focus.

### Expected behavior:
The page should be rendered in browse mode.

#### NVDA installed/portable/running from source:
NVDA is installed.

#### NVDA version:
NVDA alpha-19136.

#### Windows version:
Windows 10 1903 x64.

#### Name and version of other software in use when reproducing the issue:
Mozilla Firefox 70.0.1 x64.

#### Other information about your system:
The following appears in the log:
DEBUGWARNING - RPC process 8520 (firefox.exe) (17:45:07.673) - Dummy-10 (8972):
Thread 9052, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateTextFieldNodeAtOffset, 859:
Offset 0 out of range. Returnning NULL

DEBUGWARNING - RPC process 8520 (firefox.exe) (17:45:07.681) - Dummy-10 (8972):
Thread 9052, build\x86_64\vbufBase\storage.cpp, VBufStorage_buffer_t::locateControlFieldNodeAtOffset, 879:
Could not locate node at offset, returning NULL

DEBUGWARNING - virtualBuffers.VirtualBufferTextInfo._getNVDAObjectFromOffset (17:45:07.682) - MainThread (1056):
Couldn't get NVDAObject from offset 0

#### Does the issue still occur after restarting your PC?
Yes.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Not yet.

**Comment by lukaszgo1** [comment] 2019-11-11 15:34
I cannot reproduce this using NVDA 2019.2.1 nor NVDA version alpha-19141,e7196547 on Windows 7 with Nightly 72.
cc @jcsteh

**Comment by jcsteh** [comment] 2019-11-11 22:09
I can't reproduce it with Firefox Nightly either. However, there have been some fixes since 70 which might impact something like this, so I'll try to test some other versions when I get a chance.

**Comment by jcsteh** [comment] 2019-11-18 05:49
Urgh. I can reproduce this in Firefox 70. However, the good news is that this is already fixed in Firefox 71 (currently in beta). I'm really sorry about the breakage.

**Closed by jcsteh** 2019-11-18 05:49 UTC
