### ISSUE TITLE
Problem in Thunderbird and Firefox when restarting NVDA (next branch)

### ISSUE THREAD

**Issue by MichelSuch** [nvaccess/nvda#7442] opened 2017-07-25 08:30 UTC
### Steps to reproduce:
> A list of the steps you take to demonstrate the problem. 
This does not occur using 2017.2:
1. open a site in Firefox, or simply open thunderbird.
2. Now, restart NVDA.
If you switch to the Firefox window, you'll not be able to read the displayed page until you restart Firefox.
In tn, open a message, you won't be able to read its content until you restart tb.
The test was performed after removing all addons, to make sure the problem did not come from one of them.
>
> Example:
>
> 1. Open Chrome
> 2. Browse to www.google.com
> 3. Type "Hello"
> 4. Notice an error sound when enter is pressed.

> Please also remember to attach a zip of any files required to reproduce the issue.

### Expected behavior:
> Tell us what should happen.

### Actual behavior:
> Tell us what happens instead.

### System configuration:
NVDA version:
> Example: next-14027,c80e529f

NVDA Installed or portable:

Other information:
> Example: Running in a VM

Windows version:
> Example: Windows 10 Version 1607 Build 14393.1066

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC?

Have you tried any other versions of NVDA?
> Please list them and the result

**Comment by leonardder** [comment] 2017-07-26 06:34
Hmm, I had this issue for a little while, but now it seems to has magically gone away. Can't reproduce with next-14233,f78950a7 and Firefox 54.0.1 X64 on Windows 10 creators update.

**Comment by dan1982code** [comment] 2017-07-26 15:19
I can confirm this with next 14236,dcffa77f, Firefox 54.0.1 x64, Win 10 creator's. Weird: very similar setup to leonardder who couldn't reproduce this.

**Comment by jcsteh** [comment] 2017-07-27 06:08
Probably a duplicate of #7269, but might be #5758. However, neither of these issues are specific to the next branch. It'd be good if all affected people could re-test with NVDA 2017.2 just to be sure. CC @MichaelDCurran.

**Comment by dan1982code** [comment] 2017-07-27 14:02
I think it's #5758 for me. If I ctrl+alt+n from within Firefox, browse mode is unusable until I close Firefox. If I first open Notepad, then do ctrl+alt+n, Firefox browse mode is usable. So it only breaks if I ctrl+alt+n from within Firefox. Note that exactly the same behaviour is experienced with Thunderbird.

The "open some other application" trick is a useful workaround in the meantime. In fact, even going to the desktop and ctrl+alt+n keeps things OK.

**Comment by jcsteh** [comment] 2017-07-27 22:29
Okay. Closing as a duplicate of #5758.

**Closed by jcsteh** 2017-07-27 22:29 UTC
