### ISSUE TITLE
In mail for windows 10, when composing mail, the backspaced characters were not read

### ISSUE THREAD

**Issue by zstanecic** [nvaccess/nvda#7584] opened 2017-09-11 11:40 UTC
### Steps to reproduce:
> 1. Open mail for windows 10
> 2. Press ctrl+n to open the new mesage dialog
> 3. Type the e-mail address in the "to field" and try to press backspace, 
> 4. try the same with the subject field and the text of the message field
> 5. you will notice, that deleted characters are not spoken, and if user has a braille display, the text of the message is not refreshed

### Expected behavior:
> Nvda should read the delected characters in all fields in the composition dialog.

### Actual behavior:
> Nvda speaks nothing when pressing backspace, and braille display is not refreshed.

### System configuration:
NVDA 2017.3:

NVDA Installed or portable: Installed

Other information:
> Test with the Narrator is also performed. With narrator, the backspaced characters are spoken normally.

Windows version:
> Windows 10 Version 1703 Build 15063

Name and version of other software in use when reproducing the issue:

### Other questions:

Does the issue still occur after restarting your PC? Yes

Have you tried any other versions of NVDA? No

**Comment by ehollig** [comment] 2017-09-11 13:38
Duplicate of #7456

**Closed by ehollig** 2017-09-11 13:38 UTC
