### ISSUE TITLE
Outlook 2010: Presence of Subfolders not announced when Navigating through the Folder Tree

### ISSUE THREAD

**Issue by elliott94** [nvaccess/nvda#10913] opened 2020-03-28 19:04 UTC
### Steps to reproduce:

The following assumes that Outlook has been configured to connect to an Exchange mailbox:

1. Within the Inbox folder, perform a right-click and choose to create a new folder - you will have the choice of selecting where the folder should be placed. Choose to place it within the Inbox, give it a name, and hit the "OK" button

2. Collapse the Inbox folder by navigating to it within the folder tree, and hitting the left arrow

3. Move up/down the tree view that contains the list of folders within the Exchange account - you'll notice that our newly-created folder isn't listed. This is because the Inbox folder is currently collapsed - to expand it, navigate to "Inbox" and hit the right arrow. When you next cursor down, you'll notice that our newly-created folder is now listed

### Actual behavior:

The issue here appears to be that NVDA doesn't automatically recognise that folders may contain subfolders, so it's possible to miss subfolders unless you explicitly hit the right arrow on each of them

### Expected behavior:

To combat this, it would be really useful if NVDA could announce "not expanded" or similar when it detects that a folder contains one or more subfolders under it

#### NVDA installed/portable/running from source:

Installed

#### NVDA version:

2019.3.1

#### Windows version:

7 X64

#### If addons are disabled, is your problem still occuring?

Yes

**Comment by Adriani90** [comment] 2020-05-31 13:48
@elliott94 I cannot really reproduce this. In my case NVDA reports the expanded or colapsed status of folders. Are you using ctrl+tab to access the folders list? Or ctrl+y?

cc: @lukaszgo1 are you having Outlook 2010 and could try to reproduce this?

**Comment by elliott94** [comment] 2020-06-01 18:34
I'm using shift + tab to get to the main folder tree view. I should also note that after performing some additional testing, this appears to work as expected in Office 2016 - NVDA either announces "Expanded" or "Collapsed" depending on the status of a folder as navigation moves to it.

**Comment by Adriani90** [comment] 2020-06-01 18:37
So you see this issue only in Office 2010?

**Comment by elliott94** [comment] 2020-06-01 19:01
Yes - Office/Outlook 2016 announce this info as expected.

**Comment by Adriani90** [comment] 2023-03-14 17:50
Support for Office 2010 ended in Mai 2022 and even support for Exchange server 2010 is almost ended. I am closing this issue as not planed since there will not be any further updates from Microsoft to Office 2010.
https://learn.microsoft.com/en-us/microsoft-365/enterprise/exchange-2010-end-of-support?view=o365-worldwide

**Closed by Adriani90** 2023-03-14 17:50 UTC
