### ISSUE TITLE
NVDA reading entire line instead of focused button after modal dialog closes

### ISSUE THREAD

**Issue by msftedad** [nvaccess/nvda#13041] opened 2021-11-08 20:59 UTC
### Steps to reproduce:
1. Open [Codepen example](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodepen.io%2Fscottohara%2Fpen%2FKKvQjEJ&data=04%7C01%7CJeremy.Curry%40microsoft.com%7Cfc634ef06a19442d4d5b08d9a2cd97e1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637719826284594204%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mjZhYjeje3N5YbmjEqn4HVwsryR9%2B0UCuheuZ0c%2Ba%2F0%3D&reserved=0) in Edge
2. Tab to and activate ex2 button
3. Modal dialog will appear
4. Tab to close
5. Press enter

### Actual behavior:
The entire line of text is read "some content ex1 button ex2 button more stuff to read out". Note that if the editors are closed on the Codepen website, then this may not repro.  Be sure to put this into full screen in Code pen to repro successfully.

### Expected behavior:
The focused button, which is ex2, should be read.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
2021.2

#### Windows version:
21H2, Build 20000.258

#### Name and version of other software in use when reproducing the issue:
Edge, version 95.0.1020.44

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
unknown

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
unknown

**Comment by scottaohara** [comment] 2022-01-12 16:11
The following zip contains the HTML/JavaScript as found in the codepen, with an additional test where pressing the "focus another element" button sends focus to a "test button" that follows it in the DOM order.
[html-ex.zip](https://github.com/nvaccess/nvda/files/7855993/html-ex.zip)

Note: in trying to reproduce this issue with Edge/Chrome 97 and NVDA 2021.3, the described behavior of this ticket no longer reproduces with the test file.

However, testing with Firefox 96 and NVDA 2021.3, the original issue reproduces as described. (note to test the dialog example I have the dialog element feature flag turned on).  
The second test of having a button force focus to a second button in the document (without moving back and forth between a dialog) does not reproduce the issue.

**Comment by Adriani90** [comment] 2023-11-01 10:38
This is not reproducible anymore in Chrome, firefox or Edge 119 with NVDA last alpha. Closing as works for me.
If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2023-11-01 10:38 UTC
Labels: close/worksforme
