### ISSUE TITLE
NVDA and LaTeX

### ISSUE THREAD

**Issue by ptnapivoski** [nvaccess/nvda#13038] opened 2021-11-07 16:39 UTC
### Is your feature request related to a problem? Please describe.
Using NVDA with its dictionary feature to give access to LaTeX documents. For example: defining first \tanh as “hyperbolic tangent” and later \tan as “tangent” gives a correct natural reading but not if \tan is defined before \tanh.
### Describe the solution you'd like
Buttons to move Up and Down dictionary rules
### Describe alternatives you've considered
Was able to manipulate rules by editing default.dic file with text editor

**Comment by CyrilleB79** [comment] 2021-11-07 21:36
This issue seems a duplicate of #7750.

@ptnapivoski if you agree, please close this issue and comment further there, e.g. to explain your specific use case with LaTeX expressions. If not, please explain the difference with #7750.

**Closed** 2021-11-08 10:49 UTC
