### ISSUE TITLE
Outlook 2010: Unable to navigate via Characters in Recipient Fields

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5466] opened 2015-11-05 21:41 UTC
**Reported by elliott94 on 2015-11-05 21:41**
When composing a new item in Outlook 2010 and you wish to navigate ricipient names by character, it is not currently possible to do so other than either by focusing and copying the object to the clipboard, carrying out a select all and then proceeding to examine the list by pasting it into another application, or by reading the current line. When attempting to either use the left/right cursor keys or by navigating by character/word using object navigation, the entire name of the ricipient is read rather than the respective information.

**Comment by bhavyashah** [comment] 2017-10-12 06:25
@elliott94 Could you please test and confirm whether or not you are able to use NVDA's review cursor to access the contents of Outlook's Recipients field?
Also, I am not too sure if I agree with @jcsteh in that NVDA shouldn't overwrite Outlook's arrow keys because this how Outlooks intends it to work. Do you think this is intended behaviour (if so, why?) or can we consider it a bug? CC @Qchristensen

**Comment by Qchristensen** [comment] 2017-10-12 06:50
I tested this in Office 2016 just now, and it behaves the same, and this is how I have always known Office to work, so I feel it works the same across Outlook versions.

Once you've typed a name in any of the recipient fields (to, cc, bcc), and confirmed it, you can no longer navigate by character through that using the arrow keys.  Instead, as noted, it treats the whole name as one item.

I agree with not trying to override this behaviour.  If we did, then what should happen if you press backspace, delete, or type a character while in the middle of a name?

You can have the name spelt by pressing NVDA+up arrow (or NVDA+a for laptop layout) twice quickly, or by reading the current word or line twice with the review cursor.

Where I would say the bug is at our end, is that you should be able to navigate through the name, letter by letter, using the review cursor, however as @elliott94 noted in the original issue, this doesn't work.  Reading by letter results in the whole name being read out, just as reading by word.

**Comment by derekriemer** [comment] 2017-10-12 07:53
I agree that review cursor should read by whatever unit you select, but I don't think arrows should be overwritten.

**Comment by ruifontes** [comment] 2017-10-12 10:50
Agreed 100%!
Review cursor should work in this case!

Rui


-----Mensagem Original----- 
De: Derek Riemer
Data: 12 de outubro de 2017 08:53
Para: nvaccess/nvda
Cc: Subscribed
Assunto: Re: [nvaccess/nvda] Outlook 2010: Unable to navigate via Characters 
in Recipient Fields (#5466)



I agree that review cursor should read by whatever unit you select, but I 
don't think arrows should be overwritten.

**Comment by michaelDCurran** [comment] 2017-10-16 05:40
There is a pretty high implementation cost here. Some kind of new 
compound textInfo would need to be written that automatically descends 
into these embedded object labels when moving by character. Certainly 
not trivial.

**Comment by Adriani90** [comment] 2019-02-02 13:02
I agree this is how MS Outlook generally works. Note that if you move with left and right arrow with NVDA off, you also jump name by name in the field. This occurs because if you write down an address in the field, the address is saved to your address book and Outlook interprets it like an entry from the address book. If you want to navigate character by character, please do following:
1. In outlook options, Disable the setting which saves the addresses in your address book
2. If you are focusing an address in the edit field, press application key, open is visit card and navigate with tab to the field "e-mail address" where you can use left and right arrow to read the characters
3. Use the review cursor in object review.

So, there are several work arounds for this. I am closing it as works for me.

**Closed** 2019-02-02 13:47 UTC
Labels: Microsoft Office support, feature, worksforme
