### ISSUE TITLE
NVDA announced elements with display:none

### ISSUE THREAD

**Issue by MaksimShakavin** [nvaccess/nvda#6097] opened 2016-06-20 16:22 UTC
Having: 

```
<ul  style="overflow: hidden; display: block;">
    <div style="display: none" aria-hidden="true">
        <li> <input type="radio" value="1" name="category"></li>
        <li><input type="radio" value="2" name="category"></li>
    </div>
   <div>
        <li><input type="radio" value="3" name="category"></li>
        <li><input type="radio" value="3" name="category"></li>
        <li><input type="radio" value="4" name="category"></li>
   </div>
   <div  style="display: none;"  aria-hidden="true">
        <li><input type="radio" value="5" name="category"></li>
        <li><input type="radio" value="6" name="category"></li>
        <li><input type="radio" value="7" name="category"></li>
        <li><input type="radio" value="8" name="category"></li>
        <li><input type="radio" value="9" name="category"></li>
   </div>
</ul>
```

When I navigate to radio with value=3 using arrows, nvda announce: "List with two items", as expected. But when I navigate to it by tabbing, it announce: "radio button three of nine".

In my opinion it should not count invisible radio buttons.

**Comment by derekriemer** [comment] 2016-06-20 16:37
Which browser/browsers have you tested this on?

Thanks.


On 6/20/2016 10:22 AM, Maksim wrote:
>
> Having:
>
> |<ul style="overflow: hidden; display: block;"> <div style="display: 
> none" aria-hidden="true"> <li> <input type="radio" value="1" 
> name="category"></li> <li><input type="radio" value="2" 
> name="category"></li> </div> <div> <li><input type="radio" value="3" 
> name="category"></li> <li><input type="radio" value="3" 
> name="category"></li> <li><input type="radio" value="4" 
> name="category"></li> </div> <div style="display: none;" 
> aria-hidden="true"> <li><input type="radio" value="5" 
> name="category"></li> <li><input type="radio" value="6" 
> name="category"></li> <li><input type="radio" value="7" 
> name="category"></li> <li><input type="radio" value="8" 
> name="category"></li> <li><input type="radio" value="9" 
> name="category"></li> </div> </ul> |
>
> When I navigate to radio with value=3 using arrows, nvda announce: 
> "List with two items", as expected. But when I navigate to it by 
> tabbing, it announce: "radio button three of nine".
>
> In my opinion it should not count invisible radio buttons.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/nvaccess/nvda/issues/6097>, or mute the thread 
> <https://github.com/notifications/unsubscribe/AFGivV-_UCX4Lg2g6LnSuWZuRZbEeEnnks5qNr5TgaJpZM4I53-M>.
>

-- 
------------------------------------------------------------------------


    Derek Riemer

  * Department of computer science, third year undergraduate student.
  * Proud user of the NVDA screen reader.
  * Open source enthusiast.
  * Member of Bridge Cu
  * Avid skiier.

Websites:
Honors portfolio <http://derekriemer.com>
Awesome little hand built weather app! 
<http://django.derekriemer.com/weather/>

email me at derek.riemer@colorado.edu <mailto:derek.riemer@colorado.edu>
Phone: (303) 906-2194

**Comment by MaksimShakavin** [comment] 2016-06-21 08:26
Hi,
This issue can be reproduced on chrome(v 51.0.2704.84) and Firefox(v 47)
Thanks

**Comment by Adriani90** [comment] 2019-03-06 18:37
This is still reproducible in Chrome 71. cc: @jcsteh, @derekriemer

**Comment by Adriani90** [comment] 2019-12-14 17:34
Also reproducible in Chrome 79 with NVDA 2019.3 Beta 1:
cc: @leonardder

**Comment by Adriani90** [comment] 2023-03-08 23:54
This is not reproducible anymore in Chrome 111 with NVDA last alpha. I am closing as works for me.

**Closed by Adriani90** 2023-03-08 23:54 UTC
Labels: close/worksforme, p2, app/edge, app/chrome, app/edge/anaheim
