### ISSUE TITLE
The nvda speech viewer does not display information spoken by nvda in the outlook calendar

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#8113] opened 2018-03-22 15:35 UTC
### Steps to reproduce:
Open an accepted meeting in the outlook calendar.
Now enable nvda's speech viewer
Switch to the accepted meeting window and navigate with chift + tab to the local field, wait for the nvda to read the name of the meeting location, example room 2.
Now switch to the nvda speech viewer and look for the meeting location.

### Expected behavior:
in the speech display of the nvda should appear the text pronounced by the voice synthesizer, in the local case room 2.

### Actual behavior:
The location of the meeting that was read by the synthesizer (room 2) was not displayed in the speech viewer, only local dialog was displayed.

### System configuration:
NVDA version:
next 14952

NVDA Installed or portable:
instaled
Other information:
> Example: Running in a VM

Windows version:
windows 7

Name and version of other software in use when reproducing the issue:
outlook 2013
### Other questions:

Does the issue still occur after restarting your PC?
yes
Have you tried any other versions of NVDA?
> Please list them and the result
no

**Comment by Adriani90** [comment] 2020-05-07 20:18
@fernando-jose-silva can you still reproduce this in issue with NVDA 2020.1?
cc: @Qchristensen, @feerrenrut since I don't have Office 2013 currently installed for testing.

**Comment by fernando-jose-silva** [comment] 2020-05-08 03:10
unfortunately I currently do not have a machine with Office 2013, and meetings accepted in the out look to test.

Enviado do meu iPhone

**Comment by Qchristensen** [comment] 2020-06-17 09:09
I don't have Office 2013 either, all I can confirm is that it seems to be working for me in Office 365 (64-bit) Version 16.0.12827.20258.

Just to confirm:
- It is only the location field which is not working (and it's reading with NVDA, it's only that it isn't printed in the speech viewer?
- And is it still happening in Office 2013 with NVDA 2020.1?

**Comment by bhavyashah** [comment] 2020-06-20 11:54
Please consider adding the Microsoft Office label to this ticket.

**Comment by leonardder** [comment] 2020-06-20 12:17
The speech viewer implementation has seen an overhaul with speech refactor. Therefore, even if this was reproducible in the past, it is likely that it has since been fixed. Furthermore, as @fernando-jose-silva pointed out that he doesn't have a system to replicate his earlier findings, I'm closing this. We can always reopen.

**Closed by leonardder** 2020-06-20 12:17 UTC
