### ISSUE TITLE
Modal dialogue with multiple buttons - focus moves to last button read

### ISSUE THREAD

**Issue by jboehr** [nvaccess/nvda#12594] opened 2021-06-29 18:56 UTC
### Steps to reproduce:
Here is an example in JSFiddle: https://jsfiddle.net/m3tfjq1c/7/
Also, here is the general setup:
A modal dialog (a container with role="dialog" and aria-modal="true")
In the modal dialogue you have two button elements of type button
Those buttons must be inside a div with style "display: flex". 
Per accessibility guidelines, put focus on the first button element when the dialog is shown.

### Actual behavior:
The focused button is read first, followed by the second button. If you hit enter after the second button is read, the event tied to the second button is triggered, rather than the event tied to the first button. You also see the visual of the focus bolding around the element quickly move from the currently focused button to the second button. 

### Expected behavior:
The event tied to the currently focused button (the first button) is triggered when hitting the enter key.

**Comment by boompsy** [comment] 2021-07-30 20:58
Hi @jboehr, turns out this is related to / a duplicate of #8971, and in particular [this reply](https://github.com/nvaccess/nvda/issues/8971#issuecomment-573711119) was very helpful in identifying the actual behavior.

When a `role="dialog"` element is triggered, NVDA treats it as a new 'page' in relation to the 'Automatic Say All on page load' setting (Settings > Browse Mode). When a webpage first loads, NVDA announces all the content on the page, including links and buttons. If you happen to hit enter on a link / button during that time, that item will be activated. This is easier to notice if the label caption is long or if you slow down the speaking rate.

Hope that helps!

**Comment by Adriani90** [comment] 2023-02-07 11:00
Closing this as duplicate of #8971

**Closed by Adriani90** 2023-02-07 11:00 UTC
Labels: close/duplicate
