### ISSUE TITLE
Report "Press escape to close" on NVDA dialogs which the user needs to press escape to close

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#14641] opened 2023-02-15 23:57 UTC
### Is your feature request related to a problem? Please describe.

There are several places where a user will press a keystroke which opens a dialog which may not be obvious to all users.  Examples are:

NVDA+f pressed twice opens a dialog with the formatting of the current caret location
NVDA+r runs OCR and presents the results in a buffer the user can navigate
NVDA+k pressed twice (from NVDA 2023.1) opens a dialog with the destination URL of the current link.

Where opening something like NVDA settings should (generally) be obvious that the user is in a dialog,, these examples may not be.

### Describe the solution you'd like

My suggestion is to append "press escape to close" to the title of these dialogs / the information which is read when the user activates the keystroke.

### Describe alternatives you've considered

As it is currently, I think most users work it out, although it may still be confusing at first.  I think the proposal wouldn't inconvenience anyone, as the information would be read last and could be skipped / ignored.

### Additional context
Suggested during a conversation with user Jared via email.

**Comment by josephsl** [comment] 2023-02-16 00:00
Hi, my question is: what if the dialog is invoked on a tablet or via a braille display gesture? Thanks.

**Comment by Qchristensen** [comment] 2023-02-16 00:09
I'm not sure how easy it is to check for an input gesture copying escape?  I guess looking for that could be one option.  Otherwise, I would expect users who have setup such a gesture should understand that they can press the gesture they have setup in lieu of escape.  Much like most users understand when a general instruction says "click the link" or "click the button" - that using NVDA you move focus to it and press enter.

I would also anticipate that this would likely not be the first occasion when such a user would encounter something they needed to press "escape" to close.  My thought is this information would be most useful to new users who are less likely to have setup (or had someone setup) a gesture overriding escape.

But if there is a way to check for an input gesture for escape, then sure, that would work too.

**Comment by lukaszgo1** [comment] 2023-02-21 17:39
In JAWS this has been solved by placing a link which says something like 'Press Escape to close this message' at the end of each virtual viewer window. As a bonus clicking this link also closes the virtual viewer which nicely solves the concern about tablets and Braille only users. I'm by no means saying we should copy competition, but that flow seems worth considering.
Having said that in the initial description it was stated that:
> Where opening something like NVDA settings should (generally) be obvious that the user is in a dialog,, these examples may not be.

What is so different about these windows versus the regular settings dialog? understanding where the user confusion comes from is also valuable in this case.

**Comment by ChrisDuffley** [comment] 2023-02-21 17:59
In reply to @lukaszgo1: This is actually not a link, but a textual element at the end of the virtual viewer buffer that says this very message, or a variation of it, depending on how the script was configured in the first place.

**Comment by XLTechie** [comment] 2023-02-21 23:57
I actually wrote a PR for this issue a week or so back, but have hesitated to 
submit it because of @lukaszgo1's exact question.

Why don't users know pressing escape is the thing to do, but do know it in other 
contexts? What is so different about these windows?

Why is it more obvious that escape will work to get out of settings, etc., but 
it isn't obvious in these tool windows?

**Comment by Qchristensen** [comment] 2023-02-22 01:15
Good question re why would users know in one context but not another.  And I expect you'll find that some may, some may just assume it works everywhere, and some may not realise it works anywhere...

So, MY thinking was that when you open something like a settings window, you would generally expect it is going to present you with a bunch of options and therefore will almost certainly be in a Window.  Of course, the exact type of window, and how you close it will vary, but if you, as a user, know it is a Window you need to interact with, that's a good start.

When you ask NVDA to report formatting, or read the destination of a link, it just tells you the information, and you can continue on reading the current page you were reading.  You don't need to dismiss that information or do anything with it.  If you press the same keystroke twice - either deliberately looking for more information, or inadvertantly, it changes the behaviour, and opens it in a window you will need to dismiss.

By adding the reminder about how to close it to the end of the presented information, I figured it keeps it out of the way but still there for those who need it.  The problem with adding that kind of information to say the settings dialog, is that there are several different ways of closing that dialog, which change the behaviour (whether any changes to the settings are applied or not).

My other thought was that while there may be some users who would benefit from explicitly being reminded how to close the settings dialog.  In that case, it is no different to how do you close ANY window, etc.  And there may be a place for a "beginners add-on" which gives those hints, although that would be out of scope for this particular issue.

To date, I have had ONE question from a user about this in the context of the new link destination functionality.  So, is it likely to be a widespread issue?  I don't know.  The conversations I've had with users around OCR have often mentioned how to close the results, although I don't know whether any confusion there is around the behaviour of that window, or the wider behaviour of OCR.  I can't recall anyone being comfortable with navigating other windows like the settings, but then being unsure how to exit.

**Comment by XLTechie** [comment] 2023-02-22 03:19
@Qchristensen
Your original request here, was for a "Press escape to close" message to be 
added to titles.

Would you prefer that, or @lukaszgo1's mentioned Jaws approach, of a link at the 
end of the dialog (as just another line of text), which said something like 
"Select here or press escape to close."?

The latter may be better, as it should solve @josephsl's concern. But it does 
"contaminate" the contents of the dialog, though I'm not sure if there is any 
downside to that except when doing a select all.

**Comment by XLTechie** [comment] 2023-02-22 03:42
Here's a [test build](https://ci.appveyor.com/api/buildjobs/2xr02d0v3dpw34c8/artifacts/output%2Fnvda_snapshot_announceEscapeFromBrowseableMessage-90%2Cc74a2ed3.exe) of the first solution, limited though it may be.

**Comment by XLTechie** [comment] 2023-02-22 09:33
And here is a [build](https://ci.appveyor.com/api/buildjobs/hvepf4eqt166qyf0/artifacts/output%2Fnvda_snapshot_announceEscapeFromBrowseableMessage2-93%2Ccda0f9bc.exe) of what the alternative exit mechanism might look like.

From what @lukaszgo1 said, I think this approximates what Jaws would do.

Notes:
- It works, but not yet for Windows OCR results. It does work for Ctrl+k and Ctrl+f. This is just preliminary, to show what I had in mind.
- From a development point of view, the button added is causing an `Invalid NVDAObject: Couldn't get IAccessible, probably dead object` error, and I haven't figured out why yet.

The full traceback is:
```
  File "NVDAObjects\__init__.pyc", line 92, in __call__
  File "NVDAObjects\IAccessible\MSHTML.pyc", line 594, in __init__
NVDAObjects.InvalidNVDAObject: Couldn't get IAccessible, probably dead object
```

**Comment by michaelDCurran** [comment] 2023-02-24 01:44
I'm in support of the second option myself.

**Comment by CyrilleB79** [comment] 2023-02-24 08:09
Here is my feedback:
* The first question is who needs such a message and why do they need it? The answer may be different for `ui.browseableMessage` and OCR result
* Regarding `ui.browseableMessage`:
  * I do not find that appending the content with an extra text/link/button would be a good idea due to the impact on "select all". It would be specifically annoying in the case of the new NVDA+K command, where one would like to copy/paste the whole link.
  * I do not know why users accustomated to Windows basis would not understand how to close this window. The `ui.browseableMessage` window can be closed by escape or by alt+F4 so I cannot see the difficulty. The next time an issue is reported with this window, it should be investigated with the user the root cause of the difficulty and if the user has general difficulty with Windows or not.
* Regarding the OCR result: It is a very specific window and it's understandable that the user may not know how to use it. Also visual support from a sighted person would not be of any help in this case. So I understand the need of an extra message in this case only.
* For both cases but especially if it is decided to put the footer message in `ui.browseableMessage` despite my opinion, it may also be considered to include this feature in an add-on (if not already existing) instead of in NVDA core if the usage is found to be very specific. What about [Control Usage Assistant](https://addons.nvda-project.org/addons/controlUsageAssistant.en.html) add-on? I think it is maintained by @nvdaes.

**Comment by nvdaes** [comment] 2023-02-24 08:40
Hi Cyrille, in fact I maintain controlUsageAssistant, created by @josephsl 
Sincerely I prefer that NVDA's core don't include this feature, mainly since it may become redundant and, as you say, will cause difficulties to select and copy, and to know if the indication about Escape is part of the message itself.
If someone requests this to be included in controlUsageAssistant add-on, for example monkey patching the ui.browseableMessage method, I'll investigate this as a configurable option.
Add-on repo:

https://github.com/nvdaes/controlUsageAssistant

**Comment by XLTechie** [comment] 2023-02-24 10:34
Addressing a few people and points in this comment:

@michaelDCurran can you elaborate about why you prefer the second (button at 
bottom) approach? And is that just a preference for the "button vs. title bar" 
question, or do you prefer that even over doing nothing?

As I and now @CyrilleB79 have pointed out, it does rather inhibit the free use 
of select all.

@ChrisDuffley (or whoever knows) am I correct that in Jaws, if you do a select 
all in one of these windows, the "press escape to exit" link is captured in the selected text?

@CyrilleB79, @nvdaes while I'm not convinced on the button at the bottom 
approach because of the select all thing, I must disagree with you about the 
add-on idea.

If we are to do this, it should be in core. Any user presumed to need this level 
of help escaping from a browser instance, can not simultaneously be assumed to 
know what he doesn't know enough to find an add-on for it.

Yes a general use add-on such as Control Usage Assistant might be good here, but 
if this is as basic a problem as @Qchristensen, and apparently Freedom 
Scientific, seem to suggest, an add-on does not look like a solution to me.

**Comment by nvdaes** [comment] 2023-02-24 10:52
Hello, just reading Joseph's comment about what happens if this is invoked in a tablet, and for me this is a great concern. I think that a button to close, and even to copy if we agree that browseable messages may be often used to copy their info, can be used.
About add-ons, my impression is that frequently users without advanced knowledge may know add-ons even better than NVDA's core, and imo sometimes they use add-ons when they aren't needed, since people in general like to talk about different add-ons and play with them in a more flexible way than with core.
So for me an add-on maybe a useful resource if this is not added in the core. But imo, informing about a dialog can be closed is not needed, unless we also inform about pressing enter to accept and about other controls.

**Comment by XLTechie** [comment] 2023-02-24 11:05
@josephsl I did some playing with this tonight on my old touch laptop.
It does appear that currently, a user can close one of these windows by using 
object navigation and going to the close button.
Is that insufficient?
Or is your concern just that mentioning escape is exclusive?

If so, could the title bar message be like the following, if we used the title 
bar message option:

Press escape or use the close button to exit

As for OCR windows, these seem to behave strangely with object nav of any kind, 
including with the touch screen. I would have to explore more to figure out 
a full picture of what the exact behavior is currently. But almost anything 
either closes these, or takes the user out of them.
While the content is caret reviewable, any attempt to interact with the window 
itself, seems to be destructive to the window.

**Comment by josephsl** [comment] 2023-02-24 11:48
Hi, locating the close button could be one solution for touch users. I’m more concerned for braille users who may find that NVDA does not assign a command to emulate pressing the Escape key. One way to accommodate different input modalities is doing isinstance check for gestures and see which one is pressed and change the title bar text accordingly. As for the question of where the “close” text belongs, I think it should be part of NVDA Core so others can take advantage of it in the future (it isn’t just Control Usage Assistant that calls ui.BrowsableMessage, StationPlaylist does it for various purposes). Thanks.

**Comment by CyrilleB79** [comment] 2023-02-24 13:17
Some answers and clarifications from my part:

@XLTechie wrote:
> If we are to do this, it should be in core. Any user presumed to need this level of help escaping from a browser instance, can not simultaneously be assumed to know what he doesn't know enough to find an add-on for it.

Yes, this makes sense. But in this case, Control Usage Assistant would also need to be in core rather than in an add-on, as asked in #2699.

If the escape message is integrated in NVDA's browseable messages and if Control Usage Assistant is integrated in core in the future, it would be interesting to have an option to enable or disable this message. This options should be enabled by default so that new users have more information; it could then be disabled for more confortable users to be more efficient.

@josephsl wrote:
> (it isn’t just Control Usage Assistant that calls ui.BrowsableMessage, StationPlaylist does it for various purposes).

I was not talking of calling `ui.message` (and it is called by various add-ons and core functions). I was talking about patching `ui.message` to modify its behaviour everywhere.

**Comment by josephsl** [comment] 2023-02-24 13:25
Hi, on the last point: I think we are in agreement that it is something to be added to NVDA Core. What I’m getting at is the fact that it isn’t just Control Usage Assistant that can benefit from this global change. As for #2699, I think the best course of action is revisit the overall mechanics of context-sensitive help, separate it from “press Escape” message, then integrate  the help functionality into NVDA Core, perhaps by introducing an attribute/property/method into NVDA object classes (regarding Control Usage Assistant, I can say now that the add-on was meant to serve as one way to implement #2699 in a more familiar form, so the life of that add-on depended on how the linked issue is resolved). Thanks.

**Comment by Adriani90** [comment] 2023-10-31 19:36
If this is implemented as browseable message, I think it is not that trivial to exclude it from reporting when disabling reporting of help texts in object presentation settings. Additionally, browseable texts in dialogs only increase the amount of tab presses when navigating so in my view this is not the best user experience, see for example the new NVDA addon store.
I think the message should be browseable by review cursor and object navigation only.

I vote to include this reporting as object help text along with a new class called something like NVDAgeneratedHelptext and a new specific option in object presentation settings called "report NVDA generated help texts". so advanced users can turn it off. Anyway, every implemented help text from control ussage assistant should be part of this class so it can be turned off by disabling the NVDA generated help text setting.

**Closed** 2024-08-12 04:36 UTC
Labels: p4, triaged
