### ISSUE TITLE
On pressing down arrow, NVDA continue to announce "blank" even when the end content in the textarea is reached.

### ISSUE THREAD

**Issue by sulabh-msft** [nvaccess/nvda#10478] opened 2019-11-11 07:05 UTC
On pressing down arrow, NVDA continue to announce "blank" even when the end content in the textarea is reached.

### Steps to reproduce:
1. Go to https://codesandbox.io/s/textarea-vq9n8
![image](https://user-images.githubusercontent.com/13728069/68562957-e5b6cf00-0471-11ea-8655-148b56f195f8.png)
2. Now go the the textarea on the right side and add following content ( basically ->two ENTER key for adding two line feeds in the text area)
"Hello world 

"
3. Open NVDA and go to the text area.
4. Press down arrow inside the text area till it reaches end of content inside the textarea

### Actual behavior:
1. It reads 
"Hello world."
blank
blank
And if we continue pressing down arrow inside the textarea it continues to announce "blank".
![image](https://user-images.githubusercontent.com/13728069/68563189-c3718100-0472-11ea-85dc-8ed998ec4bc9.png)

### Expected behavior:
On pressing down-arrow key inside the text area
It should announce blank only for the lines which are actually blank and once end of content inside the text area is reached it should stop announcing "blank".

#### NVDA version:
2019.2.1
#### Windows version:
Windows 10

**Comment by Brian1Gaff** [comment] 2019-11-11 07:32
I think this happens in many editors and fields. However if you use cursor 
up you only hear the number of blanks that there are. Maybe as I seem to 
remember being discussed before, we could simply have a nice ping noise for 
the end of file. All the blank is saying is reading that line again as you 
have got to the bottom.
Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by leonardder** [comment] 2019-11-11 09:08
I think this happens in every editor, it is therefore standard NVDA 
behavior.

**Comment by sulabh-msft** [comment] 2019-11-11 09:17
The problem for me is here I'll not be able to differentiate if it is really a blank line of have we reached end of the content inside the textarea.

Consider this text inside textarea
```
Hello World!


This is another Hello world ( We new lines above)

```

On pressing down arrow key, NVDA will announce

Hello World!
blank
blank
This is another Hello world ( We new lines above)
blank
blank
.


From the first two blanks, I'll be able to understand that there are two blank lines in the content.
But after the last empty line ( at the end of the content), I'll not able to figure out how many blank lines are there.

Yeah,  a simple ping noise when we reach end of the content inside the textarea ( as proposed by @Brian1Gaff  or not announcing "blank" once we reach the end of the content might work well here.

**Comment by Brian1Gaff** [comment] 2019-11-11 14:39
Yes this has come out before though, some editors in themselves make a sound 
at end of file, while others do not.
Now all of this speech refactoring which has caused us a few lost hairs 
might be pointing to another way forward, ie perhaps a sound when the 
position of the cursor will not move up or down  any more.
Have you also noticed the change in 2019.3 where editable areas no longer 
have the verbose description of what they actually are?
 Brian
 Brian

bglists@blueyonder.co.uk
Sent via blueyonder.
Please address personal E-mail to:-
briang1@blueyonder.co.uk, putting 'Brian Gaff'
in the display name field.
Newsgroup monitored: alt.comp.blind-users
-----

**Comment by bhavyashah** [comment] 2020-07-06 21:44
As an NVDA users of many, many years, I would note that this issue still bothers me a little bit. When the end of a document is a piece of text, and you press down arrow only to hear NVDA repeat those same words, it is much easier to put two and two together than it would be if the end of a document is a blank line. The reason for this is that the probability of the same line being present over and over again, particularly in context of some content, is intuitively low. On the other hand, it might just be the case that there are a bunch of blank lines through which one is navigating in hope of discovering more content after the blank space. Nowadays, if I get too many blanks, I either do (a) a say all or (b) move a line or paragraph up in order to check if my suspicion is true. However, I don't think such guesswork should be expected of all users, particularly novice ones.

**Comment by Adriani90** [comment] 2023-09-05 17:17
Closing as duplicate of #4285.

**Closed by Adriani90** 2023-09-05 17:17 UTC
Labels: close/duplicate
