### ISSUE TITLE
can't read an e-mail in the windows's mail application

### ISSUE THREAD

**Issue by alexandretoco** [nvaccess/nvda#16785] opened 2024-07-01 14:09 UTC
### Steps to reproduce:
open an e-mail from the list and press arrow down to try to read the first line
### Actual behavior:

nvda plays a sound indicating error.
I got this from the log viewer:
Input: kb(desktop):downArrow
ERROR - scriptHandler.executeScript (10:52:45.634) - MainThread (12880):
error executing script: <bound method CursorManager.script_moveByLine_forward of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x081A4C30>> with gesture 'baixo'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 274, in script_moveByLine_forward
  File "cursorManager.pyc", line 171, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 314, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 437, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException

### Expected behavior:

read the e-mail
### NVDA logs, crash dumps and other attachments:
Input: kb(desktop):downArrow
ERROR - scriptHandler.executeScript (10:52:45.634) - MainThread (12880):
error executing script: <bound method CursorManager.script_moveByLine_forward of <appModules.hxmail.MailWordDocumentTreeInterceptor object at 0x081A4C30>> with gesture 'baixo'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "cursorManager.pyc", line 274, in script_moveByLine_forward
  File "cursorManager.pyc", line 171, in _caretMovementScriptHelper
  File "speech\speech.pyc", line 1416, in speakTextInfo
  File "speech\types.pyc", line 41, in __iter__
  File "speech\speech.pyc", line 1458, in getTextInfoSpeech
  File "treeInterceptorHandler.pyc", line 255, in getTextWithFields
  File "NVDAObjects\UIA\wordDocument.pyc", line 314, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 877, in getTextWithFields
  File "NVDAObjects\UIA\__init__.pyc", line 865, in _getTextWithFieldsForUIARange
  File "NVDAObjects\UIA\__init__.pyc", line 622, in _getTextWithFields_text
  File "NVDAObjects\UIA\wordDocument.pyc", line 437, in _getFormatFieldAtRange
  File "UIAHandler\remote.pyc", line 105, in msWord_getCustomAttributeValue
  File "UIAHandler\_remoteOps\operation.pyc", line 346, in execute
UIAHandler._remoteOps.operation.NoReturnException
IO - inputCore.InputManager.executeGesture (10:52:47.996) - winInputHook (9860):
Input: kb(desktop):alt+tab

#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2024.3 beta 1
#### Windows version:
windows 11
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2024.2 works fine

**Comment by Adriani90** [comment] 2024-07-01 14:26
Closing as duplicate of #16689.

**Closed by Adriani90** 2024-07-01 14:26 UTC
Labels: close/duplicate
