### ISSUE TITLE
Excel 2016 raises error when using Windows 10 Japanese IME is used

### ISSUE THREAD

**Issue by nishimotz** [nvaccess/nvda#6294] opened 2016-08-23 03:36 UTC
setup
- Microsoft Excel 2016 (32bit) English interface
- Windows 10 (32bit) Version 1607, English interface, Japanese IME added
- nvda master 13511 (portable)

steps
- start Excel and open new book
- Win+space to choose Japanese IME
- type something to a cell such as A1
- enter or arrow key to move next cell
- raises error as follows

```
INFO - __main__ (12:29:38):
Starting NVDA
INFO - core.main (12:29:39):
Config dir: C:\nvda\userConfig
INFO - core.main (12:29:39):
NVDA version master-13511,dde5ed4f
INFO - core.main (12:29:39):
Using Windows version 10.0.14393 workstation
INFO - core.main (12:29:39):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (12:29:39):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (12:29:40):
Loaded synthDriver sapi5
INFO - core.main (12:29:40):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (12:29:40):
Using liblouis version 2.6.5
INFO - braille.BrailleHandler.setDisplayByName (12:29:40):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (12:29:40):
Braille input initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (12:29:41):
UIAutomation: IUIAutomation3
INFO - core.main (12:29:41):
NVDA initialized
INFO - config.ConfigManager.save (12:29:43):
Base configuration saved
ERROR - scriptHandler.executeScript (12:29:47):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x045429F0>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 113, in script_caret_newLine
  File "editableText.pyc", line 67, in _hasCaretMoved
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 58, in __init__
COMError: (-2147220992, None, (None, None, None, 0, None))
ERROR - scriptHandler.executeScript (12:29:54):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x0471B2F0>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 113, in script_caret_newLine
  File "editableText.pyc", line 67, in _hasCaretMoved
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 58, in __init__
COMError: (-2147220992, None, (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (12:30:03):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x04692D50> with extra args of {'ch': u'\r'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 839, in event_typedCharacter
  File "speech.pyc", line 591, in speakTypedCharacters
  File "api.pyc", line 235, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 556, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 552, in _get_UIACachedStatesElement
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (12:30:05):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x04692D50> with extra args of {'ch': u'h'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 839, in event_typedCharacter
  File "speech.pyc", line 591, in speakTypedCharacters
  File "api.pyc", line 235, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 556, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 552, in _get_UIACachedStatesElement
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (12:30:05):
error executing event: typedCharacter on <NVDAObjects.UIA.ListItem object at 0x04692D50> with extra args of {'ch': u'e'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 839, in event_typedCharacter
  File "speech.pyc", line 591, in speakTypedCharacters
  File "api.pyc", line 235, in isTypingProtected
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 556, in _get_states
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 552, in _get_UIACachedStatesElement
COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

**Comment by nishimotz** [comment] 2016-08-23 09:50
reproduced with NVDA 2016.3-rc1 13516 (portable)

```
INFO - __main__ (18:48:10):
Starting NVDA
INFO - core.main (18:48:11):
Config dir: C:\nvdarc\userConfig
INFO - core.main (18:48:12):
NVDA version rc-13516,1dcfdd0f
INFO - core.main (18:48:12):
Using Windows version 10.0.14393 workstation
INFO - core.main (18:48:12):
Using Python version 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
INFO - core.main (18:48:12):
Using comtypes version 0.6.2
INFO - synthDrivers.espeak.SynthDriver.__init__ (18:48:13):
Using eSpeak version 1.48.15  16.Apr.15
INFO - synthDriverHandler.setSynth (18:48:13):
Loaded synthDriver espeak
INFO - core.main (18:48:13):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (18:48:13):
Using liblouis version 2.6.5
INFO - braille.BrailleHandler.setDisplayByName (18:48:13):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (18:48:13):
Braille input initialized
INFO - _UIAHandler.UIAHandler.MTAThreadFunc (18:48:13):
UIAutomation: IUIAutomation3
INFO - core.main (18:48:14):
NVDA initialized
INFO - updateCheck.AutoUpdateChecker._started (18:48:14):
Performing automatic update check
INFO - config.ConfigManager.save (18:48:16):
Base configuration saved
INFO - synthDriverHandler.setSynth (18:48:21):
Loaded synthDriver sapi5
INFO - config.ConfigManager.save (18:48:22):
Base configuration saved
ERROR - scriptHandler.executeScript (18:48:40):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIA.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIA object at 0x047E1730>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 186, in executeScript
  File "editableText.pyc", line 113, in script_caret_newLine
  File "editableText.pyc", line 67, in _hasCaretMoved
  File "NVDAObjects\__init__.pyc", line 958, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyc", line 58, in __init__
COMError: (-2147220992, None, (None, None, None, 0, None))
```

**Comment by jcsteh** [comment] 2016-08-23 10:33
Is this a recent regression or does it occur with NVDA 2016.2 as well?

**Comment by nishimotz** [comment] 2016-08-23 13:42
Actually it occurs with 2016.2 as follows, but it was ignored because the bell is muted for release builds.

```
INFO - __main__ (22:39:17):
Starting NVDA
INFO - core.main (22:39:18):
Config dir: C:\nvda-2016.2\userConfig
INFO - core.main (22:39:18):
NVDA version 2016.2
INFO - core.main (22:39:18):
Using Windows version 10.0.14393 workstation
INFO - core.main (22:39:18):
Using Python version 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
INFO - core.main (22:39:18):
Using comtypes version 0.6.2
INFO - synthDriverHandler.setSynth (22:39:18):
Loaded synthDriver sapi5
INFO - core.main (22:39:18):
Using wx version 3.0.2.0 msw (classic)
INFO - braille.initialize (22:39:18):
Using liblouis version 2.6.5
INFO - braille.BrailleHandler.setDisplayByName (22:39:18):
Loaded braille display driver noBraille, current display has 0 cells.
INFO - brailleInput.initialize (22:39:18):
Braille input initialized
INFO - core.main (22:39:20):
NVDA initialized
INFO - config.ConfigManager.save (22:39:20):
Base configuration saved
ERROR - scriptHandler.executeScript (22:39:32):
error executing script: <bound method Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject.script_caret_newLine of <NVDAObjects.Dynamic_EditableTextWithoutAutoSelectDetectionUIAWindowNVDAObject object at 0x044D03F0>> with gesture u'enter'
Traceback (most recent call last):
  File "scriptHandler.pyo", line 186, in executeScript
  File "editableText.pyo", line 113, in script_caret_newLine
  File "editableText.pyo", line 67, in _hasCaretMoved
  File "NVDAObjects\__init__.pyo", line 958, in makeTextInfo
  File "NVDAObjects\UIA\__init__.pyo", line 57, in __init__
COMError: (-2147220992, None, (None, None, None, 0, None))
```

**Comment by Adriani90** [comment] 2019-03-08 17:38
@nishimotz are you still able to reproduce this issue with NVDA 2019.1 Beta 1?

**Comment by nishimotz** [comment] 2019-03-09 02:23
I have not tested with beta, however, not reproduced the issue with the setup as follows:

* NVDA alpha 16885
* Windows 10 version 1809 64bit Japanese
* Office 365 Excel version 1902

**Comment by Adriani90** [comment] 2019-03-09 10:12
@nishimotz thank you very much for your availability. This is great. Closing as works for me.

**Closed by Adriani90** 2019-03-09 10:12 UTC
Labels: Microsoft Office support, worksforme
