### ISSUE TITLE
Adding a Feature to Select the Time Interval Between Beeps and Speech

### ISSUE THREAD

**Issue by tarikhadzirovicofficial** [nvaccess/nvda#17062] opened 2024-08-27 11:25 UTC
### Is your feature request related to a problem? Please describe.

NVDA has the option to choose between off, speak, beep, and speak and beep for some of its features, such as progress bar announcements.
I'm not sure what the exact time interval currently is between one beep and the next or between speech sequences when the announcements are enabled in a specific way.
Sometimes it happens that the user waits longer for information compared to the first time. For example, I've experienced the information being announced now, then after 10 seconds, then after four, and then after 11 seconds. Roughly speaking.

### Describe the solution you'd like

I think it would be beneficial for the user to be able to select how much time should pass before a beep or speech sequence occurs. For example, if they select three seconds for speech, then the speech synthesis being used would announce the progress bar result every three seconds, or in the case of a beep, the beep would play every three seconds.
This might also be useful in the context of page loading announcements (#16960).

**Comment by XLTechie** [comment] 2024-08-28 08:48
Status bar updates will only beep/speak when the status bar itself updates.

NVDA can't control how the status bar is setup (its granularity).

I suppose it could announce every two seconds or something, but then you would end up with something like "10%. 10%. 11%. 12%. 12%. 12%. 12%", for a bar that advances in jerky irregular intervals. Is that what you are requesting?

For indeterminate status bars, such as the one while NVDA is updating, the beeps, for example, are already at a defined interval--I think it's one second.

**Comment by CyrilleB79** [comment] 2024-08-28 08:58
There is already a discussion on this topic in #5031. So I'd be inclined to close this issue as duplicate.

@tarikhadzirovicofficial do you agree?

**Comment by CyrilleB79** [comment] 2024-08-28 09:01
Also see closed PR #10804

**Comment by tarikhadzirovicofficial** [comment] 2024-08-28 10:49
Hi @XLTechie!
What I am looking for is the ability for the user to select how frequently the beeps and speech occur. So, if a user wants to hear updates every two seconds, that's fine if it suits them. The same applies for intervals of 30 seconds. I note that, at least in my experience, I have noticed irregular intervals in other progress bars, including those that are indeterminate. For example, three seconds, then seven, then five, then seven...
However, this option should apply to all status bars (both determinate and indeterminate).

**Comment by seanbudd** [comment] 2024-09-03 00:06
Duplicate of https://github.com/nvaccess/nvda/issues/5031

**Closed by seanbudd** 2024-09-03 00:06 UTC
