### ISSUE TITLE
Reading the HTML Select options on mouseover in any  blank space in UI

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#5344] opened 2015-09-09 16:22 UTC
**Reported by Madhava on 2015-09-09 16:22**
Issue: NVDA reads all the page content and all the HTML Select options on mouseover any blank space. Issue observed only in IE Browser.
NVDA version: 2015.3
OS: Windows 7/8.1
Example: http://www.scriptingmaster.com/html/creating-a-selection-list.asp

Expected result: The html page content should be read when certain part of UI is focused by the user. Should not read when the focus is out of the text content or on any blank space.

Example: In the above link, there is an dropdown field: Select your favorite web site. In this there are three values in the dropdown. If i point the mouse over on little away from the dropdown, NVDA is reading all the three values instead of only selected value.

 Any help on confirming whether this is known limitation, would be appreciated.

**Comment by Adriani90** [comment] 2020-05-30 00:35
Closing as duplicate of #3034

**Closed by Adriani90** 2020-05-30 00:35 UTC
Labels: app/internet-explorer, bug, close/duplicate, feature/mouse-tracking
