### ISSUE TITLE
NVDA does not speak individual characters when navigating

### ISSUE THREAD

**Issue by adkurz** [nvaccess/nvda#10908] opened 2020-03-27 13:32 UTC
### Steps to reproduce:

Open any text field and press the key left arrow or right arrow.

NVDA doesn't speak the current character under the cursor.

### Actual behavior:

NVDA says nothing

### Expected behavior:

NVDA should speak the character under the cursor.

#### NVDA installed/portable/running from source:

installed

#### NVDA version:

alpha-19823,5cd0c3fd

#### Windows version:

Windows 10 1909 x64

#### Does the issue still occur after restarting your computer?

Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.

Problem doesn't exist in NVDA 2019.3.1, only in the later snapshots

#### If addons are disabled, is your problem still occuring?

Yes

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?

yes

**Comment by feerrenrut** [comment] 2020-03-27 16:33
I cant reproduce this with the latest alpha (`Version: alpha-19834,2cdf280b`).

Steps to test:
- Opened notepad.exe
- Type "hello"
- Use left arrow to move through the letters
- Use right arrow to move through the letters
Letters are announced.

@adkurz If this does not describe how you are encountering the problem, please update the steps to reproduce to be more specific.

**Comment by DrSooom** [comment] 2020-03-28 23:06
@adkurz: And also please report which synthesizer you are using. Thanks.

PS: And ensure that the window is big enough. Or just maximize it with Win+ArrowUp.

**Comment by DalisonCPU** [comment] 2020-03-30 23:21
This problem also happens to me. When you press WINDOWS + R, type some text and use the right or left arrows, NVDA does not read anything. In order for him to be able to read, I need to walk using the shift.
not even in the browser works, even to send this comment.

**Comment by DrSooom** [comment] 2020-03-31 02:13
I can't reproduce this with [NVDA Alpha-19852](https://ci.appveyor.com/api/buildjobs/w9bawnorj5alkkbl/artifacts/output/nvda_snapshot_alpha-19852,c6b6904b.exe) (Installer-portable temp copy) on win7x64 with SAPI-4 IBM ViaVoice TTS (German) in the Run Dialog (Win+R), in Notepad and in a multiline textfield in Firefox 74.0x64. Windows and NVDA are also in German.

So please report your used synthesizer and the NVDA language. Thanks.

**Comment by DalisonCPU** [comment] 2020-03-31 03:49
My version is 2020.1beta1

-----Mensagem original-----
De: Daniel Mayr
Enviada em: Segunda, 30 de Março de 2020 19:13
Para: nvaccess/nvda
Cc: DalisonCPU; Manual
Assunto: Re: [nvaccess/nvda] NVDA does not speak individual characters whennavigating (#10908)

I can't reproduce this with [NVDA Alpha-19852](https://ci.appveyor.com/api/buildjobs/w9bawnorj5alkkbl/artifacts/output/nvda_snapshot_alpha-19852,c6b6904b.exe) (Installer-portable temp copy) on win7x64 with SAPI-4 IBM ViaVoice TTS (German) in the Run Dialog (Win+R), in Notepad and in a multiline textfield in Firefox 74.0x64. Windows and NVDA are also in German.

So please report your used synthesizer and the NVDA language. Thanks.

**Comment by beqabeqa473** [comment] 2020-03-31 04:17
it can be because of speech history addon

On 3/31/20, DalisonCPU <notifications@github.com> wrote:
> My version is 2020.1beta1

>

> -----Mensagem original-----

> De: Daniel Mayr

> Enviada em: Segunda, 30 de Março de 2020 19:13

> Para: nvaccess/nvda

> Cc: DalisonCPU; Manual

> Assunto: Re: [nvaccess/nvda] NVDA does not speak individual characters
> whennavigating (#10908)

>

> I can't reproduce this with [NVDA
> Alpha-19852](https://ci.appveyor.com/api/buildjobs/w9bawnorj5alkkbl/artifacts/output/nvda_snapshot_alpha-19852,c6b6904b.exe)
> (Installer-portable temp copy) on win7x64 with SAPI-4 IBM ViaVoice TTS
> (German) in the Run Dialog (Win+R), in Notepad and in a multiline textfield
> in Firefox 74.0x64. Windows and NVDA are also in German.

>

> So please report your used synthesizer and the NVDA language. Thanks.

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/nvaccess/nvda/issues/10908#issuecomment-606355924

>

>

> --

> You are receiving this because you are subscribed to this thread.

> Reply to this email directly or view it on GitHub:

> https://github.com/nvaccess/nvda/issues/10908#issuecomment-606382858


-- 
with best regards beqa

**Comment by DalisonCPU** [comment] 2020-03-31 04:22
It is true. Can't fix it?
-----Mensagem original-----
De: beqa gozalishvili
Enviada em: Segunda, 30 de Março de 2020 21:17
Para: nvaccess/nvda
Cc: DalisonCPU; Manual
Assunto: Re: [nvaccess/nvda] NVDA does not speak individual characters whennavigating (#10908)

it can be because of speech history addon



On 3/31/20, DalisonCPU <notifications@github.com> wrote:

> My version is 2020.1beta1



>



> -----Mensagem original-----



> De: Daniel Mayr



> Enviada em: Segunda, 30 de Março de 2020 19:13



> Para: nvaccess/nvda



> Cc: DalisonCPU; Manual



> Assunto: Re: [nvaccess/nvda] NVDA does not speak individual characters

> whennavigating (#10908)



>



> I can't reproduce this with [NVDA

> Alpha-19852](https://ci.appveyor.com/api/buildjobs/w9bawnorj5alkkbl/artifacts/output/nvda_snapshot_alpha-19852,c6b6904b.exe)

> (Installer-portable temp copy) on win7x64 with SAPI-4 IBM ViaVoice TTS

> (German) in the Run Dialog (Win+R), in Notepad and in a multiline textfield

> in Firefox 74.0x64. Windows and NVDA are also in German.



>



> So please report your used synthesizer and the NVDA language. Thanks.



>



> --



> You are receiving this because you are subscribed to this thread.



> Reply to this email directly or view it on GitHub:



> https://github.com/nvaccess/nvda/issues/10908#issuecomment-606355924



>



>



> --



> You are receiving this because you are subscribed to this thread.



> Reply to this email directly or view it on GitHub:



> https://github.com/nvaccess/nvda/issues/10908#issuecomment-606382858





-- 

with best regards beqa

**Comment by Adriani90** [comment] 2020-05-30 20:16
This is related to the addon speech history. Please create an issue with the addon at
https://github.com/jscholes/nvda-speech-history

I am closing this issue for now.

**Closed by Adriani90** 2020-05-30 20:16 UTC
