### ISSUE TITLE
NVDA with Firefox - Enter Key on Anchor containing Font Awesome icons Drops Focus from Page

### ISSUE THREAD

**Issue by dovematrix** [nvaccess/nvda#13332] opened 2022-02-11 17:32 UTC
### Steps to reproduce:
1. Start NVDA 
2. use Firefox to open https://www.utrgv.edu/online/degrees-and-courses/online-programs/index.htm 
3. press the Tab key until focus is on the search link at the top right with the magnifying glass icon. 
4. Press the Enter key. 

### Actual behavior:
Focus is removed from the page and focus is now placed on the desktop instead of the browser. The expanded search area with a search field is not displayed. 

### Expected behavior:
A  hidden expanded area is displayed with a  search field to enter the search term. Focus is moved to the search field. 

#### NVDA installed/portable/running from source:
NVDA installed on laptop PC Dell Precision 3541

#### NVDA version:
Version 20212.3.1

#### Windows version:
Windows 10 Enterprise Version 20H2
Version	10.0.19042 Build 19042

#### Name and version of other software in use when reproducing the issue:
Firefox 97.0 (64-bit)

#### Other information about your system:
University controlled computer. I do not have administrative access. 

The page anchor that has unexpected behavior is coded with an anchor inside a list item. Contained within the anchor are two Font Awesome CSS icons. 

	<li class="nav-item dropdown search">
		<a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle white-text d-none d-lg-block" data-toggle="dropdown" href="#" id="navbarDropdownSearch">
			<span>Search</span>
			<i aria-hidden="true" aria-label="Search icon" class="fa fa-search"></i>
			<i aria-hidden="true" aria-label="Close menu icon" class="fa fa-times"></i>
		</a>

This gets rendered out on the page as SVGs.

<a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle white-text d-none d-lg-block" data-toggle="dropdown" href="#" id="navbarDropdownSearch">
      <span>Search</span>
      <svg aria-hidden="true" aria-label="Search icon" class="svg-inline--fa fa-search fa-w-16" focusable="false" data-prefix="fa" data-icon="search" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path></svg>
      <svg aria-hidden="true" aria-label="Close menu icon" class="svg-inline--fa fa-times fa-w-11" focusable="false" data-prefix="fa" data-icon="times" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512" data-fa-i2svg=""><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg>
    </a>

#### Does the issue still occur after restarting your computer?
Yes

#### If NVDA add-ons are disabled, is your problem still occurring?
Yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by lukaszgo1** [comment] 2022-02-14 12:15
cc @jcsteh

**Comment by Adriani90** [comment] 2023-03-13 23:29
This is not reproducible with NVDA 2023.1 RC1 and Firefox 110. Please make sure to maximize the window when activating the search link.

Closing as works for me.
If you are still having this issue, please comment and we can reopen.

**Closed by Adriani90** 2023-03-13 23:29 UTC
Labels: close/worksforme

**Comment by jcsteh** [comment] 2023-03-13 23:31
Note that as of Firefox 101, clicking things should be a lot more accurate and maximising the window should no longer be necessary.
