### ISSUE TITLE
Lines are no longer displayed correctly in Email-Software "The Bat!"

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4698] opened 2014-12-15 21:31 UTC
**Reported by medlem78 on 2014-12-15 21:31**
Since the Release of NVDA 2014.2 it is no longer possible to read or write mails in "The bat". When I read or write mails line by line, parts of the previous line even occure in the focused line. 

Example:

This is an exampe how 
NVDA and The Bat work together right now. example how
This problem did not occure right now
in NVDA 2014.1 and earlier versions. did not occure
I hope you can fix it. earlier versions.

**Comment by ehollig** [comment] 2017-08-03 23:26
CC @michaelDCurran

**Comment by Adriani90** [comment] 2019-01-11 19:39
@medlem78 is this issue still reproducible?

**Comment by Adriani90** [comment] 2019-05-05 17:51
The author is not available on Github anymore and we don't have any other user reports since more than three years regarding to this software. Closing due to missing updates.

**Closed by Adriani90** 2019-05-05 17:51 UTC
Labels: bug
