### ISSUE TITLE
NVDA menu disapears if a Nuance TTS is installed & used

### ISSUE THREAD

**Issue by nozem79** [nvaccess/nvda#12007] opened 2021-01-22 08:53 UTC
The issue is that when a Nuance voice like Claroread or Harposoftware Nuance voices are being used, the options menu disapears, the only way to get it back is to delete the nvda.ini file from \roaming\nvda\ .
After that the 'regular' voices will be used again and the menu is usable again.
 
- I repreduces this on three diffet laptops - Windows 10 (1809 - 20H2)
- I found this issue with NVDA 2020.3 (I saw this issue earlier in older versions)
- There where no add-ons installed with all tests

**Comment by CyrilleB79** [comment] 2021-01-23 20:40
Hi @nozem79
There was no need to open a second issue. I was expecting you to add missing information in the first issue (#11916).
Could you please copy from here the relevant missing information to #11916 and close this issue?

Also please specify in #11916 a clear way to reproduce the issue describing each steps, as well as expected and actual result. E.g.:
Steps to reproduce:
* start NVDA with OneCore
* press NVDA+shift+S to change synth to Nuance
* press NVDA+N to explore the menu
Actual result: Nothing happens
Expected result: NVDA menu is opened

**Comment by CyrilleB79** [comment] 2022-11-28 16:29
@seanbudd, could you please close this issue which is a duplicate of #11916?

**Closed** 2022-11-28 22:47 UTC
