### ISSUE TITLE
userguide: sentence going from line 1958 to 1960

### ISSUE THREAD

**Issue by bdorer** [nvaccess/nvda#12406] opened 2021-05-12 17:15 UTC
### Steps to reproduce:
1. open english userguide.t2t and go to line 1958.
### Actual behavior:
Confirm sentence goes including line 1960.
### Expected behavior:
This sentence should be in one line so translators have an easier translation workflow using userguide diffs.

**Comment by ehollig** [comment] 2022-11-10 19:37
@bdorer is this still an issue?? If so, this sounds to be a qucik fix. @Qchristensen

**Comment by seanbudd** [comment] 2022-11-10 23:22
I imagine the line number has changed greatly since this issue has been open.
In order to make a static link, use github: https://github.com/nvaccess/nvda/blob/master/user_docs/en/userGuide.t2t#L1958

I am closing this issue as it cannot be reproduced without a link to to the sentence (e.g. line number + commit reference)

**Closed by seanbudd** 2022-11-10 23:22 UTC
Labels: component/documentation, good first issue
