### ISSUE TITLE
links on Google search fail to activate - UIA Edge

### ISSUE THREAD

**Issue by k-kolev1985** [nvaccess/nvda#12030] opened 2021-02-04 10:34 UTC
### Steps to reproduce:
1. Launch NVDA.
2. From NVDA's advanced settings, enable the option "Use UIA with Microsoft Edge and other Chromium based browsers when available" (set it to "Yes").
3. Open the Microsoft Edge browser.
4. Go to Google Search and enter a search term. I entered "NV Access" (without the quotes). In my search results, NV Access's home page is the first result.
5. Go to one of the search results and press ENTER to activate it.

### Actual behavior:
The link does not activate.

### Expected behavior:
The link should activate and the page should load.

### System configuration
- Operating system: Windows 10 Pro version 20H2 (build 19042.746), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: alpha-21710,11ba984f, installed, in bulgarian.
- Microsoft Edge version: 88.0.705.56, 64-bit, in bulgarian.
- Processor: Intel Core i5-9400F at 2.90GHz.
- RAM Memory: 16.00GB.
- Graphics: MSI GeForce GTX-1050TI Gaming X 4G, 4096MB dedicated memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC892 at Intel Cannon Point PCH.

#### Does the issue still occur after restarting your computer?
Yes, it does.

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
No, because the feature that causes this issue is available only in alpha versions.

#### If addons are disabled, is your problem still occuring?
Yes, it is.

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No, because in this case it is probably not related to this issue.

**Comment by Adriani90** [comment] 2023-04-04 12:40
closing as duplicate of #14612 which contains more discussion.

**Closed by Adriani90** 2023-04-04 12:40 UTC
Labels: close/duplicate, app/edge/anaheim, api/uia
