### ISSUE TITLE
Open WORD with new document NVDA does get focus

### ISSUE THREAD

**Issue by BackuPs** [nvaccess/nvda#11868] opened 2020-11-26 09:49 UTC
Hi

When opening word with new document or by clicking a docx file and word opening the document NVDA does not take or get the focus. The user has to use alt+tab alt+tab in order to get the focus off the document on the braille device.

Please fix.

**Comment by Adriani90** [comment] 2020-11-26 20:02
Closing as duplicate of #8389.

**Closed by Adriani90** 2020-11-26 20:02 UTC
Labels: close/duplicate
