### ISSUE TITLE
NVDA freezes in firefox frequently after returning from a computer sleep.

### ISSUE THREAD

**Issue by davidacm** [nvaccess/nvda#10599] opened 2019-12-09 13:22 UTC
### Steps to reproduce:
1. Open many tabs and some windows in firefox. It depends on the site, lighter sities need more tabs to discover this bug. You can try with 4 opened windows, one of them with 30 tabs or more of different sities. Interact with some of them.
2. Sleep your computer and unsleep it.
3. Interact with the opened sities. Open more sities.

### Actual behavior:
At some point, NVDA will freeze. Maybe 10 or 15 minutes after the step 3.
You can unfreeze by sleeping and unsleeping the computer, but the problem won't disappear until you restart firefox. Restart NVDA won't solve the problem.
Is very tedious. I usually kill firefox process from task manager, to keep my old firefox session.
It only happends after sleep, you can use firefox all the day if you don't sleep the computer.
I tried this in many computers. The same happends for all of them.

### Expected behavior:
NVDA doesn't freeze using firefox.

#### NVDA installed/portable/running from source:
Installed.
#### NVDA version:
2019.2.1.
#### Windows version:
Windows 10 1903 pro

#### Name and version of other software in use when reproducing the issue:
Firefox.

#### Other information about your system:
MSI gs65, intel i7 8750h, NVIDIA 1070, 32gb ram, 2tb ssd for the operating system.

#### Does the issue still occur after restarting your PC?
Yes.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
2019.2.1 and older, the same behavior.

**Comment by Adriani90** [comment] 2019-12-09 16:51
Could you please try with nvda 2019.3 beta 1? There were some improvements regarding this problem which are introduced in beta 2019.3

**Comment by davidacm** [comment] 2019-12-11 01:42
Thanks. I tried with the beta. Is hard to get this issue, but the problem is still present. Now NVDA recovers of freeze by itself, but the issue won't disappear until restart firefox. The log in debug mode is here:

DEBUGWARNING - watchdog._watcher (19:30:09.718) - watchdog (16788):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 539, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 79, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 613, in __init__
  File "IAccessibleHandler.pyc", line 932, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1158, in QueryInterface
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

IO - tones.beep (19:30:13.101) - MainThread (17056):
Beep at pitch 6000, for 10 ms, left volume 50, right volume 50
IO - inputCore.InputManager.executeGesture (19:30:18.666) - winInputHook (15500):
Input: kb(laptop):NVDA+t
IO - inputCore.InputManager.executeGesture (19:30:29.028) - winInputHook (15500):
Input: kb(laptop):shift+control+escape
DEBUGWARNING - watchdog._watcher (19:30:32.451) - watchdog (16788):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 47, in flushQueue
  File "comtypesMonkeyPatches.pyc", line 101, in newCpbDel
  File "comtypes\__init__.pyc", line 918, in __del__
  File "comtypes\__init__.pyc", line 1172, in Release
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

IO - speech.speak (19:30:34.445) - MainThread (17056):
Speaking ['Catálogo']
IO - speech.speak (19:30:34.445) - MainThread (17056):
Speaking ['fotos(2).zip 24,7 MB — google.com — 19:28 Abrir la carpeta que lo contiene']
DEBUGWARNING - watchdog._watcher (19:30:35.030) - watchdog (16788):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 531, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 551, in isUIAWindow
  File "_UIAHandler.pyc", line 529, in _isUIAWindowHelper

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (19:30:36.160) - MainThread (17056):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
IO - speech.speak (19:30:36.190) - MainThread (17056):
Speaking ['Windows Task Manager', 'diálogo']
IO - speech.speak (19:30:36.220) - MainThread (17056):
Speaking ['Processes', 'página de propiedades']
DEBUGWARNING - RPC process 7208 (tm.exe) (19:30:36.227) - Dummy-943 (6556):
Thread 2416, build\x86_64\remote\sysListView32.cpp, nvdaInProcUtils_sysListView32_getGroupInfo, 28:
LVM_GETGROUPINFOBYINDEX failed

IO - speech.speak (19:30:36.229) - MainThread (17056):
Speaking ['Processes', 'lista']
IO - speech.speak (19:30:36.381) - MainThread (17056):
Speaking ['acrotray.exe *32; daevsmsi; 00 ; 1\xa0556 K; AcroTray']
IO - inputCore.InputManager.executeGesture (19:30:40.539) - winInputHook (15500):
Input: kb(laptop):downArrow
IO - speech.speak (19:30:40.570) - MainThread (17056):
Speaking ['ApplicationFrameHost.exe; daevsmsi; 00 ; 17\xa0544 K; Application Frame Host']
IO - inputCore.InputManager.executeGesture (19:30:41.132) - winInputHook (15500):
Input: kb(laptop):downArrow
IO - speech.speak (19:30:41.168) - MainThread (17056):
Speaking ['backgroundTaskHost.exe; daevsmsi; 00 ; 924 K; Background Task Host']
IO - inputCore.InputManager.executeGesture (19:30:41.843) - winInputHook (15500):
Input: kb(laptop):NVDA+n
DEBUG - gui.MainFrame.evaluateUpdatePendingUpdateMenuItemCommand (19:30:41.853) - MainThread (17056):
Error while removing  pending update menu item
Traceback (most recent call last):
  File "gui\__init__.pyc", line 227, in evaluateUpdatePendingUpdateMenuItemCommand
wx._core.wxAssertionError: C++ assertion "node" failed at ..\..\src\msw\menu.cpp(890) in wxMenu::DoRemove(): bug in wxMenu::Remove logic

**Comment by Adriani90** [comment] 2019-12-11 05:41
Cc: @jcsteh


Von meinem iPhone gesendet

**Comment by davidacm** [comment] 2019-12-11 08:46
Another log that seems to contain more info:

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:18.153) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.467) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.480) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.495) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.500) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.505) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.510) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:19.515) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:20.671) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:20.679) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:20.689) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:20.691) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:37:22.739) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))
DEBUGWARNING - watchdog._watcher (02:37:26.212) - watchdog (7604):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 915, in pumpAll
  File "IAccessibleHandler.pyc", line 772, in processForegroundWinEvent
  File "IAccessibleHandler.pyc", line 531, in winEventToNVDAEvent
  File "_UIAHandler.pyc", line 551, in isUIAWindow
  File "_UIAHandler.pyc", line 529, in _isUIAWindowHelper

IO - speech.speak (02:37:26.620) - MainThread (15176):
Speaking ['Inicio', 'ventana']
IO - speech.speak (02:37:26.620) - MainThread (15176):
Speaking ['Ventanas ancladas', 'lista']
IO - speech.speak (02:37:26.620) - MainThread (15176):
Speaking ['agrupación']
IO - inputCore.InputManager.executeGesture (02:37:28.073) - winInputHook (10068):
Input: kb(laptop):NVDA+t
IO - inputCore.InputManager.executeGesture (02:37:32.168) - winInputHook (10068):
Input: kb(laptop):NVDA+n
DEBUGWARNING - watchdog._watcher (02:37:36.795) - watchdog (7604):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 539, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 79, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 613, in __init__
  File "IAccessibleHandler.pyc", line 932, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1158, in QueryInterface
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

DEBUG - IAccessibleHandler.accessibleObjectFromEvent (02:37:41.946) - MainThread (15176):
oleacc.AccessibleObjectFromEvent with window 8587120, objectID 399 and childID 0: [WinError -2147467259] Error no especificado
IO - speech.speak (02:37:41.946) - MainThread (15176):
Speaking ['Inicio']
DEBUGWARNING - watchdog._watcher (02:37:42.467) - watchdog (7604):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 515, in run
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 47, in flushQueue
  File "comtypesMonkeyPatches.pyc", line 101, in newCpbDel
  File "comtypes\__init__.pyc", line 918, in __del__
  File "comtypes\__init__.pyc", line 1172, in Release
  File "comtypesMonkeyPatches.pyc", line 26, in __call__

DEBUG - gui.MainFrame.evaluateUpdatePendingUpdateMenuItemCommand (02:37:43.037) - MainThread (15176):
Error while removing  pending update menu item
Traceback (most recent call last):
  File "gui\__init__.pyc", line 227, in evaluateUpdatePendingUpdateMenuItemCommand
wx._core.wxAssertionError: C++ assertion "node" failed at ..\..\src\msw\menu.cpp(890) in wxMenu::DoRemove(): bug in wxMenu::Remove logic
DEBUGWARNING - watchdog._watcher (02:37:43.570) - watchdog (7604):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "wx\core.pyc", line 3240, in <lambda>
  File "gui\__init__.pyc", line 155, in showGui
  File "gui\__init__.pyc", line 560, in onActivate
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 539, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 42, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 347, in accessibleObjectFromEvent
  File "oleacc.pyc", line 265, in AccessibleObjectFromEvent

DEBUGWARNING - core.CorePump.run (02:37:45.017) - MainThread (15176):
errors in this core pump cycle
Traceback (most recent call last):
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 539, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 48, in getNVDAObjectFromEvent
  File "NVDAObjects\__init__.pyc", line 79, in __call__
  File "NVDAObjects\IAccessible\__init__.pyc", line 613, in __init__
  File "IAccessibleHandler.pyc", line 932, in getIAccIdentity
  File "comtypes\__init__.pyc", line 1158, in QueryInterface
  File "comtypesMonkeyPatches.pyc", line 34, in __call__
core.CallCancelled: COM call cancelled


IO - speech.speak (02:37:46.473) - MainThread (15176):
Speaking ['Escritorio Seguro']
IO - speech.speak (02:37:46.555) - MainThread (15176):
Speaking ['Escritorio', 'ventana']
DEBUGWARNING - watchdog._watcher (02:37:52.913) - watchdog (7604):
Trying to recover from freeze, core stack:
  File "nvda.pyw", line 215, in <module>
  File "core.pyc", line 545, in main
  File "wx\core.pyc", line 2134, in MainLoop
  File "gui\__init__.pyc", line 1030, in Notify
  File "core.pyc", line 514, in run
  File "IAccessibleHandler.pyc", line 912, in pumpAll
  File "IAccessibleHandler.pyc", line 635, in processGenericWinEvent
  File "IAccessibleHandler.pyc", line 539, in winEventToNVDAEvent
  File "NVDAObjects\IAccessible\__init__.pyc", line 42, in getNVDAObjectFromEvent
  File "IAccessibleHandler.pyc", line 347, in accessibleObjectFromEvent
  File "oleacc.pyc", line 265, in AccessibleObjectFromEvent

DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (02:38:10.382) - MainThread (15176):
accRole failed: (-2147024809, 'El parámetro no es correcto.', (None, None, None, 0, None))

**Comment by feerrenrut** [comment] 2020-01-29 14:44
This is not a regression in 2019.3, and it seems unlikely that NVDA is at fault here. If this only happens when you have many tabs open, it indicates to me it is either a problem caused by running out of memory, or perhaps firefox taking a long time to make API's useable again while pages are restored from cache (longer than NVDA is willing to wait).

**Comment by davidacm** [comment] 2020-01-29 15:56
Is not an issue introduced in the 2019.3 version. But the issue occurs with NVDA and not with other screen readers. My computer has enough memory (32gb of ram) that should be enough to run firefox in 64 bits.
The issue won't disappear even if I close all the tabs, leaving only one open.
In my opinion NVDA should take care when calling those unsecure functions, like  oledll.oleacc.AccessibleObjectFromEvent because sometimes those kind of functions return very slow. Maybe using a thread, so the user can close firefox if something bad happends. Since the function that is blocking NVDA is not part of firefox, this issue could happen in other applications. I've seen this sometimes in another places, but not as often as firefox.

Another question is: is NVDA releasing the resources taken from firefox correctly when closing a tab or window?

**Comment by Adriani90** [comment] 2020-05-28 20:28
cc: @jcsteh it would be interesting to know if this gets solved after your huge work regarding performance in Firefox and code clean up comes to live.

**Comment by jcsteh** [comment] 2020-05-28 23:01
Unfortunately, I don't think so. However, there's been other work lately
that might (or might not) help here.

**Comment by bhavyashah** [comment] 2020-07-08 23:17
I have only properly gone through the ticket description, and I can confirm the following:
* I face this issue even with Firefox 78.0.1 and NVDA 2020.2 Beta 2.
* I am currently experiencing this with only 7 tabs open in one Firefox window and literally one other window (Windows Explorer) on a computer with an I5 processor and 8 gb RAM.
* The issue is solved for a short while - maybe for 10 minutes - on putting the computer to sleep and then waking it up.
* The frustrating thing is that NVDA just goes silent and does not even restart despite pressing the Ctrl+Alt+N keyboard shortcut.
I cannot overstate how incredibly inconvenient it is to need to constantly put my computer to sleep and then wake it back up every 10 minutes. Please take a look at this issue.

**Comment by davidacm** [comment] 2020-07-08 23:33
Its a very tedious issue. If you can't change to another browser like Chrome or the modern Edge (as in my case) You can do the following to deal with this.

1. Kill the firefox process or close all tabs with ctrl + shift + q.
2. Open Firefox again.
3. If you killed the process, then select restore session option. If you just closed all windows and tabs, open the history menu and select the "Restore Previous Session" option.

You need to do it always after unsleep the computer. You can't solve it restarting NVDA. even doing it, this issue will appear again.

**Comment by davidacm** [comment] 2020-07-14 17:25
Can someone confirm if this happens on firefox 78.0.2 with NVDA 2020.1?

Before test it, please disable all UIA options available in advanced category on NVDA's options.

**Comment by gregjozk** [comment] 2020-07-27 05:41
Hello,

issue still exists. @jcsteh has informed me at simular issue, that one of problems are RPC - remote procedural calls. unfortunately, I cannot remember issue now. will add it after find it.
observed it some month after ff quantu (57) was released and neither updates of ff nor updates of NVDA has not fixed issue yet.
anyway I very appretiate a commitment of developers to fix this and related issues e.g. #9359 and others.

**Comment by jcsteh** [comment] 2020-07-27 05:47
Please see my recent update on https://github.com/nvaccess/nvda/issues/9359#issuecomment-664112238.

**Comment by jcsteh** [comment] 2022-04-24 11:37
We're currently undertaking a major re-architecture of Firefox's multi-process accessibility support using a cache. We are fairly certain this should resolve this problem. This is still very much under development and won't be ready for production use for several months yet, but I thought it worth providing an update here regardless.

**Comment by cary-rowen** [comment] 2022-04-24 12:52
@jcsteh 
It's good to hear the good news

**Comment by iubito** [comment] 2022-04-27 00:37
Hello! I'm facing the same issue with latest NVDA and Firefox. The issue appear randomly, several times in a day. The night, I "hibernate" my computer. I'll try to stop it to see if the issue disappear.
The freeze occurs mostly in firefox but it can be in another app.
I don't know if it has an impact on this issue, I was using Code Factory ETI Eloquence (using SAPI) as speech synth. I recently switched to IBMTTS, which includes the same voices, enhanced.
I'm to lazy to switch to another speech synth, as I'm not satisfied by other voices, and I adapted my pronounciation dictionnary to Glen voice ;)
I subscribed to this issue to be informed of changes. I'm ready to test a beta version when needed.

For now, my solution is to hit Ctrl+Alt+Del and wait for NVDA to wake up. It seems that if I don't do this, the freeze is longer, but I'm not sure. Sometimes it's fast, sometimes I've time to cook dinner!

**Comment by jcsteh** [comment] 2022-08-26 21:19
Sorry for cross-posting, but some of these issues have different audiences and I'm reluctant to close any of them as duplicates given they're all slightly different.

I'm pleased to announce that Cache the World, our major re-architecture of the Firefox accessibility engine to significantly improve performance, is now ready for preview on Windows in Firefox Nightly. If you're interested in testing, see this blog post for details and testing instructions: https://blog.mozilla.org/accessibility/cache-the-world-opt-in-preview/

**Comment by davidacm** [comment] 2022-08-26 21:42
hi @jcsteh.
Thanks for the notification. Currently, I'm not using firefox, due to the issue mentioned here. But I'd love to use firefox again.
So, I will try, I'm a heavy user of the web browsers.

Thanks again!

**Comment by bhavyashah** [comment] 2022-12-30 05:42
Just wanted to note that I haven't run into this issue in some time now. I use the latest stable versions of Firefox and NVDA. Thanks for the work on this!

**Comment by seanbudd** [comment] 2023-01-02 21:06
Closing this as fixed by cache the world. If this is still an issue, let us know and we can re-open it. Alternatively, open a fresh issue with the latest information.

**Closed by seanbudd** 2023-01-02 21:06 UTC
Labels: bug/freeze, blocked/needs-external-fix, app/firefox, triaged

**Comment by jcsteh** [comment] 2023-01-04 06:05
It's worth noting that Cache the World has not yet shipped in Firefox stable release. I'm glad to hear that people aren't experiencing this in stable, but I don't know what would have fixed it. It was always difficult to reproduce this reliably. My guess is that it's still lurking in stable, but definitely fixed in nightly.
