### ISSUE TITLE
Input text reading as auto complete

### ISSUE THREAD

**Issue by meghnshah** [nvaccess/nvda#8633] opened 2018-08-14 20:09 UTC
### Steps to reproduce:
https://personal.vanguard.com/us/openaccount?CompLocation=OVInvGoals&Component=OABanner&acctType=NewAcct
Username reads as edit has auto complete which is incorrect because this is just a input text field. Saw this behavior on random pages but not all input text says auto complete.

### Actual behavior:
input text = edit  has auto complete

### Expected behavior:
edit blank
#### NVDA Installed/portable/running from source:
installed
#### NVDA version:
2018.2
#### Windows version:
10
#### Name and version of other software in use when reproducing the issue:
NVDA 2018 and FF60
### Other questions:
This was reading right before we installed NVDA 2018
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
Yes it works on NVDA 2016/FF, It works with FF/JAWS and works with FF/Voiceover but reads auto complete with FF60/NVDA2018

**Comment by jscholes** [comment] 2018-08-14 20:48
This is expected behaviour because the browser itself can provide autocompletion suggestions for form fields.  You can test this by typing some text into the username field and submitting the form, then returning to the page and pressing the down arrow key in the username field to autocomplete what you've typed.  In some corner cases, a developer may explicitly disable this feature (perhaps for security reasons) by setting the [autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-autocomplete) to "off".

**Comment by Adriani90** [comment] 2019-05-08 19:29
As @jscholes pointed out, this behavior is normal due to the fact that the web developer can turn has autocomplete on or off. I am closing this issue for now. if there are other questions regarding this topic, please comment and we can reopen the discussion. Or you could also send a message on gitter at
https://gitter.im/nvaccess/NVDA

**Closed by Adriani90** 2019-05-08 19:29 UTC
