### ISSUE TITLE
aria-labelledby attribute, pointing to an element inside same container leads to double reading

### ISSUE THREAD

**Issue by PetyaMarkovaBogdanova** [nvaccess/nvda#13236] opened 2022-01-13 15:28 UTC
I am having this issue with NVDA:
### Steps to reproduce:
Open:
https://jsbin.com/geconakubu/edit?html,output
Focus on the container of the checkbox with label " Long Label 1"
### Actual behavior:
Long Label 1 Long Label 1 Long Label 2 - the "inner" label element is read out twice
### Expected behavior:
Long Label 1 Long Label 2 - that should be the read out information for the checkboxes
#### NVDA installed/portable/running from source:
installed
#### NVDA version:
2021.3.1
#### Windows version:
Windows 10 Enterprise

https://user-images.githubusercontent.com/15124079/150348438-2138a965-3c46-48b3-8631-109a3acdd06d.mp4

**Comment by PetyaMarkovaBogdanova** [comment] 2022-01-13 15:29
Just to mention, the issue is not reproducing on every attempt.
Best regards,
Petya Markova.

**Comment by feerrenrut** [comment] 2022-01-17 07:43
Please give the exact steps you are taking with NVDA, also include whether NVDA is in focus or browse mode.

To make this easier:
- press `NVDA+4` to turn on "speak command keys"
- ensure the setting ""Audio indication of focus and browse modes  check box" is unchecked in "browse mode" settings
- Open speech viewer via the NVDA menu, tools, speechviewer option.

When you have reproduced the problem you can copy from the speechviewer, this will give you a good start on a description of what you did.

Information on browse and focus mode:
By default, when changing to browse mode you hear a "boop" sound, changing to focus mode you hear a "click" sound. These can be replaced with speech via the option in NVDA settings, browse mode, "Audio indication of focus and browse modes  check box". A user can manually change between browse mode and focus mode with `NVDA+space`
- Focus mode may be called applications or forms mode in some other screenreaders, in this mode key presses are passed through to the underlying application.
- Browse mode allows a screenreader user to navigate with "quick nav" keys, eg 'h' jumps to the next heading. Keys presses aren't passed through to the underlying application.

**Comment by PetyaMarkovaBogdanova** [comment] 2022-01-20 13:33
Hi @feerrenrut ,
I made a video, where I am reproducing the issue. I am accessing the aria-labelledBy checkbox container by navigating via tab key.
I updated the original issue.
Best regards,
Petya Markova.

**Comment by feerrenrut** [comment] 2022-01-21 02:44
Note, many of the NVDA developers are blind or vision impaired.  This is covered by the [instructions for submitting new issues](https://github.com/nvaccess/nvda/blob/master/devDocs/githubIssueTemplateExplanationAndExamples.md#screenshots)

It looks like you are in focus mode, and press tab to focus the checkbox.

**Comment by PetyaMarkovaBogdanova** [comment] 2022-01-27 10:54
Hi @feerrenrut ,

I will try to describe the issue once again with these steps:

1. open https://codepen.io/yonkov/pen/mdqyQOa and turn on browse mode;
2. focus the checkbox;
3. the first label referenced via aria-labelledby is readout twice;

Best regards,
Petya Markova.

**Comment by PetyaMarkovaBogdanova** [comment] 2022-06-13 08:41
Hi team,
any news on that issue?
Thank you!
Best regards,
Petya Markova.

**Comment by feerrenrut** [comment] 2022-06-14 06:54
The example is confusing and appears to have several flaws, I can't recommend a solution, because I don't know what you are trying to achieve.

- What are you trying to achieve with this?
- Do you use the tab key to focus the checkbox?

When I use the example given (with speak command keys on) I get the following output in the speechviewer, does this match what you get?

```
tab
   check box  not checked    Long Label 1  Long Label 1 Long Label 2  check box  not checked  
```

Here a [codepen example](https://codepen.io/reefturner/pen/abqPebP) that makes it a little more clear what is going on, it is the same as your example except:
- it provides a "before test content" button for focus to land on before doing the test.
- it fixes the extra whitespace in `tabindex="  -1"
- it uses unique, short, nonsense words for content. This makes it easier to identify what NVDA is reporting

When I test this, NVDA reports.
```
shift+tab
before test content  button  
tab
cat  baz foo  check box  not checked  
```

Note that nothing is read twice.
Some strange things about the test case:
- The span with `Id1` is the target element for 'labelled-by', but it also then itself has a `aria-label="baz"` element.
- Nothing is `aria-hidden`, why are the explicit labels required at all?

**Comment by Adriani90** [comment] 2023-04-16 14:52
Possibly related or even duplicate of #10512.
cc: @seanbudd

**Comment by Adriani90** [comment] 2024-01-31 19:37
I cannot reproduce this issue in NVDA 2024.1 Beta 6 and Chromium browsers Edge or Chrome 121 or Firefox 122. Closing as works for me. If you are still having this issue, please provide an updated minimal test case and we can reopen.

**Closed by Adriani90** 2024-01-31 19:37 UTC
Labels: close/worksforme, needs-triage

**Comment by Adriani90** [comment] 2024-01-31 19:46
#10512 is still reproducible though.
