### ISSUE TITLE
Latest Version of NVDA crashing Chrome

### ISSUE THREAD

**Issue by nvaccessAuto** [nvaccess/nvda#4712] opened 2014-12-19 14:37 UTC
**Reported by jbirdgrant on 2014-12-19 14:37**
I have the latest version of NVDA installed (I can't seem to find the version number), and it works fine with Firefox. However, whenever I start NVDA with Chrome (version 39.0.2171.95 m), the page crashes. I get the "Aw, Snap!" error message. I have tried it on two different PCs (Windows 7 Enterprise and Windows Vista), with the same result.

**Comment by jcsteh** [comment] 2016-03-30 06:53
Can't reproduce and no feedback from reporter. Closing.

**Closed by jcsteh** 2016-03-30 06:53 UTC
Labels: appCrash, bug, GoogleWork, worksforme
