### ISSUE TITLE
Using HIMS Smart Beetle, pressing "scroll back" or "scroll forward" does not scroll the display

### ISSUE THREAD

**Issue by munawarb** [nvaccess/nvda#7679] opened 2017-10-21 11:15 UTC
When I press the scroll buttons on either side of the Smart Beetle display, NVDA does nothing, when it should scroll the display. I'm using NVDA 2017.3.

**Comment by leonardder** [comment] 2017-10-21 16:40
Closing as duplicate of #6086. This will be covered by #7459 in the near future.

**Closed by leonardder** 2017-10-21 16:40 UTC
Labels: Braille
