### ISSUE TITLE
NVDA not reading aria-label on a div with role “dialog” in Microsoft Edge

### ISSUE THREAD

**Issue by llevvi** [nvaccess/nvda#8512] opened 2018-07-18 18:15 UTC
In our website, there's a div element that has the role of "dialog" and an aria-label attribute. 

It works just fine for the following combinations: 

Voice Over + Google Chrome / Mozilla Firefox / Safari
NVDA + Google Chrome / Mozilla Firefox / Internet Explorer 

However, it is completely ignored when we use:

NVDA + Microsoft Edge* 

 * It actually works on an older version of Edge (38), but it doesn't work for the latest: 42.

This is the element:

    <div role="dialog" aria-label="name">
     <a title="Hide Dialog" href="#" id="eg"></a> 
    </div>

In all successful cases (e.g.: NVDA + Chrome), it reads `"name dialog"`, then `"hide dialog link"`.

In NVDA + Edge (42) it goes:

`"Hide dialog link, hide dialog"`. 

In NVDA + Edge (38) it goes:
`"Clickable link hide dialog"` then `"name dialog"`

System Details: 

Windows 10 Pro | Version 1803
Microsoft Edge  42.17134.1.0
Microsoft Edge HTML 17.17134

NVDA (Installed): 2018.2.1

**Comment by michaelDCurran** [comment] 2018-07-27 22:58
Actually, it seems for Microsoft Edge we have always deliberately been ignoring the root of the document. This is in contradiction to our spport for other browsers.
We should probably standardize on one or the other.
However,  why this works in Edge 38 and not 42 I'm not sure. Perhaps Edge placed another redundant element in the accessibility tree just below the root.
We will look into this, but I'm not putting a huge priority on it at the moment as there are many other aspects of dialogs and other content currently broken in Edge. The vast majority of blind users are on Firefox or chrome.

**Comment by llevvi** [comment] 2018-07-28 14:18
@michaelDCurran thanks a lot for your feedback! Although the issue might be solved soon given the context, it does help my team specifically since we are working for a client and this will give them some perspective of fix in the future. 
Congrats on your good work.

**Comment by Adriani90** [comment] 2020-04-21 22:04
This works fine in edge Chromium 81.
However, I discovered another issue. It seems the title "hide dialog" is a link and can be clicked in focus mode, but this is not focusable at all in browse mode. I tested with all browsers.
@jcsteh is this due to the title of the dialog being placed into a div? I guess this is not expected behavior. Right?

**Comment by Adriani90** [comment] 2020-04-25 14:59
I think this is a duplicate of #2745. Focusing elements in a div has become very problematic in every browser meanwhile.

**Comment by Adriani90** [comment] 2020-05-12 16:32
I am closing this issue since Edge Chromium will most probably be distributed via automatic update in Windows 10 20 H1 update to most users. But I add the propper label here so that developers can find old edge issues easily, see label edge / spartan.

**Closed by Adriani90** 2020-05-12 16:32 UTC
Labels: app/chrome, app/edge, app/edge/spartan, close/worksforme, p3
