### ISSUE TITLE
Sometimes partly loaded braille tables after including the HUC8 Braille Tables (2019-03-01) into NVDA 2019.2 Beta-18133

### ISSUE THREAD

**Issue by DrSooom** [nvaccess/nvda#9973] opened 2019-07-25 15:31 UTC
### Steps to reproduce:
1. Install a portable copy of [NVDA 2019.2 Beta-18133](https://ci.appveyor.com/api/buildjobs/t7pflc1win8kdioo/artifacts/output/nvda_snapshot_beta-18133,b29acb42.exe) on a USB flash drive as well as on a SSD.
2. Download and include the [HUC8 Braille Tables (2019-03-01)](https://danielmayr.at/files/huc/HUC8%20Braille%20Tables_2019-03-01.7z) into "de-de-comp8.ctb" by following [these instructions](https://danielmayr.at/huc/en.html#in20191p).
3. Now start NVDA and change the braille output table to German Computer-Braille (8-dot) and disable the checkbox "Expand to computer braille for the word at the cursor".
4. Restart NVDA with debug logging level via NVDA+Q.
### Actual behavior:
Sometimes the braille table couldn't be completely loaded if NVDA is running from a USB flash drive. Some ranges of code points couldn't be loaded e.g. U+2800 to U+2855 as well as some definitions from the Latin-1 Supplement Unicode block (U+0080 to U+00FF). This issue is new in NVDA 2019.2 Beta-18133 and it only occurs sometimes, but not always. Maybe you have to restart NVDA multiple times to get that unwanted behavior. If "NVDA ist bereit" (⡝⡧⡙⡁⠀⠊⠎⠞⠀⠃⠑⠗⠑⠊⠞) isn't displayed on the braille display (nothing is displayed), than the braille table couldn't be completely loaded. After pressing any key, which updates the braille output, the braille output seems to work again, but not fully correct due to the partly loaded braille table.

After I have installed a fresh portable version of NVDA to the SSD, the braille table seems now to work as expected, but I still get the following error in the logfile:
<details><summary><h4>SSD logfile:</h4></summary>
<code>Touch only supported on installed copies

DEBUG - core.main (15:43:21.563):

Initializing global plugin handler

DEBUGWARNING - braille.BrailleHandler.setDisplayByName (15:43:21.565):

Error in initial display after display load

Traceback (most recent call last):

  File "braille.pyc", line 1686, in setDisplayByName

  File "braille.pyc", line 1976, in initialDisplay

  File "braille.pyc", line 1840, in handleGainFocus

  File "braille.pyc", line 1845, in _doNewObject

  File "braille.pyc", line 1516, in getFocusRegions

  File "braille.pyc", line 615, in update

  File "braille.pyc", line 428, in update

  File "louisHelper.pyc", line 65, in translate

  File "louis\__init__.pyc", line 183, in translate

WindowsError: exception: access violation reading 0x2A8A97D0

IO - braille.BrailleBuffer.update (15:43:21.859):

Braille regions text: [u'NVDA ist bereit']

IO - braille.BrailleHandler.update (15:43:21.861):

Braille window dots: 13457 12367 1457 17 - 24 234 2345 - 12 15 1235 15 24 2345

DEBUG - core.main (15:43:21.862):

Initializing core pump</code>
</details>

#### Update – USB flash drive logfile (18:45 CEST):
I was now able to reproduce the error on the USB flash drive. [Here](https://github.com/nvaccess/nvda/files/3432516/NVDA-Bug.9973_USB.flash.drive.txt) is the complete logfile (see line 133 to 188). This error is different to the above mentioned.  The "Ä" (U+00C4, ⡰) isn't displayed correctly. It is displayed as ⠠⡌⠭⠬⠬⠉⠙⠠. In other words: This time this Unicode code point and many others aren't defined by the loaded braille table.
> Line 154: WindowsError: exception: access violation writing 0x00000000

<details><summary><h4>Additional information regarding the Optelec ALVA BC680:</h4></summary>
Regarding the Optelec ALVA BC680 I also get those error entries:

<code>initializing Java Access Bridge support

DEBUGWARNING - brailleDisplayDrivers.alva.BrailleDisplayDriver.__init__ (15:43:21.252):

Traceback (most recent call last):

  File "brailleDisplayDrivers\alva.pyc", line 167, in __init__

  File "hwIo.pyc", line 272, in __init__

WindowsError: [Error 5] Zugriff verweigert

DEBUG - braille.BrailleHandler.setDisplayByName (15:43:21.252):

Reinitializing noBraille braille display

INFO - braille.BrailleHandler.setDisplayByName (15:43:21.259):

Loaded braille display driver noBraille, current display has 0 cells.

DEBUG - brailleDisplayDrivers.alva.BrailleDisplayDriver._handleTime (15:43:21.295):

Time not synchronized. Display time 2019-07-25T15:43:26

INFO - brailleDisplayDrivers.alva.BrailleDisplayDriver.__init__ (15:43:21.302):

Found display with 80 cells connected via hid (\\?\hid#vid_0798&pid_0680&col02#6&38174385&0&0001#{4d1e55b2-f16f-11cf-88cb-001111000030})

DEBUG - braille.BrailleHandler.setDisplayByName (15:43:21.303):

Switching braille display from noBraille to alva

DEBUG - driverHandler.Driver.saveSettings (15:43:21.311):

Saved settings for BrailleDisplayDriver alva

INFO - braille.BrailleHandler.setDisplayByName (15:43:21.312):

Loaded braille display driver alva, current display has 80 cells.

DEBUG - NVDAObjects.NVDAObject._get_placeholder (15:43:21.312):

Potential unimplemented child class: <NVDAObjects.window.Desktop object at 0x05443490>

DEBUG - core.main (15:43:21.331):

Initializing legacy winConsole support</code>

This issue could be caused by that [prototype ALVA driver](https://github.com/nvaccess/nvda/files/1840480/alva.zip) written by @leonardder [here](https://github.com/nvaccess/nvda/issues/8106#issuecomment-375565227), which is still used with NVDA 2018.1 (installed version). Maybe it influences the portable versions of NVDA in a negative way. But as this issue also occurred with NVDA 2019.1 (Portable), it isn't really relevant here.</details>
### Expected behavior:
No errors as in NVDA 2019.1.1 (Portable). The braille table can be loaded completely again on a USB flash drive, which is mostly much slower than a SSD.
#### NVDA installed/portable/running from source:
Portable
#### NVDA version:
2019.2 Beta-18133
#### Windows version:
Win7x64
#### Other information about your system:
Optelec ALVA BC680 is connected via USB2. But it's the same result if the USB1 port is used.
#### Does the issue still occur after restarting your PC?
Not tested.
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Already works as expected with 2019.1.1 (Portable).

**Comment by leonardder** [comment] 2019-07-29 10:04
Is this the same issue as #9982?

I"m hesitant to explore the cause of this issue, as it has to deal with tables that currently are no part of liblouis. Furthermore, including tables in other tables isn't something that's going to supported this way by liblouis upstream anyway. We aren't sure whether this is caused by NVDA or liblouis as well.

**Comment by DrSooom** [comment] 2019-07-29 14:55
> Is this the same issue as #9982?

That could be the case. I decided to open a new issue, because the HUC Braille Tables aren't part of Liblouis yet. Therefore fixing #9982 should have priority.

> Furthermore, including tables in other tables isn't something that's going to supported this way by liblouis upstream anyway.

You should take a deeper look into some braille tables. There a quite a lot braille tables which includes other braille tables by using the "include" command. The only different here is that including the HUC Braille Tables will lead to multiple definitions, which has a few side effects.

See also: Issue liblouis/liblouis#688 and liblouis/liblouis#689 and PR liblouis/liblouis#730 as well as NVDA issue #8702 and the [FAQ section in the HUC Braille Tables documentation](https://danielmayr.at/huc/en.html#faq).

**Comment by DrSooom** [comment] 2019-07-29 23:03
Closing as no longer reproducible with NVDA 2019.2 RC1 Portable.

**Comment by josephsl** [comment] 2019-07-29 23:18
Hi, confirmed, although we will find out if it holds true once 2019.2 stable is installed. Thanks.

**Comment by DrSooom** [comment] 2019-08-08 02:52
This issue is back in NVDA 2019.2 RC2 (portable).

**Comment by DrSooom** [comment] 2019-08-15 11:11
… and also in NVDA 2019.2 Stable (Portable).

**Comment by leonardder** [comment] 2019-08-16 13:16
I'm pretty sure this has to do wit liblouis and not with NVDA itself.

@DrSooom Could you please provide some logging with NVDA loggign level set to debug and liblouis debugging enabled in the advanced settings?

**Comment by leonardder** [comment] 2019-08-16 13:19
Given the issue descriptions and occurrence in some NVDA versions but not in others, I'm closing this in favour of #9982, which deals with tables that are accessible from NVDA itself and doesn't require manual table overriding intervention to reproduce.

**Closed by leonardder** 2019-08-16 13:19 UTC

**Comment by DrSooom** [comment] 2019-10-02 18:34
I recently updated the issue title due to [this](https://github.com/nvaccess/nvda/issues/9982#issuecomment-535513789) and [this comment on issue #9982](https://github.com/nvaccess/nvda/issues/9982#issuecomment-537617305).
