### ISSUE TITLE
Profile switching triggers are wrongly applied to applications that don't have triggers for that profile

### ISSUE THREAD

**Issue by Neurrone** [nvaccess/nvda#11198] opened 2020-05-25 06:53 UTC
### Steps to reproduce:

1. Create a "programming" profile which has punctuation set to most and indentation indicated by tones.
2. Set the programming profile to trigger off applications such as notepad, notepad++, VS Code, VS 2019 etc.

### Actual behavior:

When I'm in an application such as Firefox which does not have a trigger to activate the programming profile and did not activate it manually, NVDA should never use the programming profile.

### Expected behavior:

NVDA starts using the programming profile when I switch to Firefox. This doesn't happen immediately but I notice this happening after some time (the interval ranges from several mins to maybe an hour?). I suspect this is partially related to how often I switch between applications that would cause this profile to fire.

When pressing nvda+control+p to view the profiles dialog, it shows that the programming profile being used. Attempting to force the use of the normal profile in e.g, Firefox doesn't work. The only way to make it use the normal profile is to restart NVDA entirely. This works for a while until it happens again, and the cycle repeats.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
Version: alpha-20220,1c4519a6

#### Windows version:
Windows 10 2004

#### Name and version of other software in use when reproducing the issue:
Multiple Firefox builds, but I am pretty sure this isn't a Firefox issue

#### Does the issue still occur after restarting your computer?
Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this has been happening for as long as I can remember (probably at least a year)? I just got around to reporting it because I personally find this really annoying when it happens.

#### If addons are disabled, is your problem still occuring?
Unknown

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
No

**Comment by CyrilleB79** [comment] 2020-05-25 07:49
I have probably also encountered this issue, even if I did not realize it was a profile issue.

I have sometimes experienced unwanted indentation announcement with beeps in Firefox. And I have actually a programming profile with indentation announced by beeps for programming. Moreover, I also switch many time back and forth between my code editor and Firefox.
Here are the information of the computer where this occurred regularly:
Windows version: Windows 10 1709 and then 1809.
Firefox version: ?
NVDA versions: many, probably at least from 2019.1 to 2019.3.1
Editor: 6pad++
Profiles: normal (for Firefox) and application 6pad++

**Comment by Neurrone** [comment] 2020-05-25 07:51
Another possibility is that instead of the wrong triggers being applied, the triggers which are supposed to be reevaluated when the application is switched doesn't happen for some reason.

**Comment by JulienCochuyt** [comment] 2020-05-25 10:32
The next time this happens, could you please check NVDA's log to see if an error occurred when focusing back Firefox, preventing the profile switch back to default?

**Comment by DrSooom** [comment] 2020-05-25 16:25
@Neurrone: I guess you interchanged the actual and the expected behavior.

Additional question: How do you switch between the applications? ALT+TAB, ALT+ESC, WIN+TAB or WIN+(1-9).

**Comment by Neurrone** [comment] 2020-05-25 16:35
@DrSooom alt+tab.

**Comment by Neurrone** [comment] 2020-05-28 12:18
@JulienCochuyt there weren't any errors the last time i saw this and it happened.

**Comment by Neurrone** [comment] 2020-06-04 15:50
In case it helps, when I switched back to Firefox and look at the currently active profile, it says "programming (editing, triggered)". Just saw this as I typed this.

Attempting to switch to normal configuration and choosing close does not switch me away from the programming profile and the only way to get back to normal is by restarting NVDA.

**Comment by CyrilleB79** [comment] 2023-09-15 08:07
@Neurrone are you still experimenting this issue.

There is a use case where profiles changes are not triggered when focusing the application:
1. Open Notpepad++
2. Create a dev  profile for Notepat++ and activate it.
3. Change some parameters in the profile, e.g. indent reporting
4. Save your config
5. Open again NVDA's settings dialog
6. Alt+tab to Firefox

Result: Notepad++ is still used while Firefox is focused; if you alt+tab to NVDA's settings dialog and close it, Firefox will be focused again, with default profile this time.

Except this corner case of settings dialog in background (or maybe other NVDA dialogs in background), I am not so sure to have seen this issue again.

**Comment by Neurrone** [comment] 2023-09-15 09:04
I haven't experienced problems with configuration profiles, but will leave this issue open due to the bug you just mentioned.

**Comment by CyrilleB79** [comment] 2024-09-03 10:09
Closing as duplicate of #8821.

**Closed by CyrilleB79** 2024-09-03 10:09 UTC

**Comment by XLTechie** [comment] 2024-09-03 10:32
@CyrilleB79 Why do you think this is a duplicate of #8821?
#8821 is about NVDA dialogs causing a reversion to normal profile at unexpected 
times.

On the contrary, the only one to mention NVDA dialogs in this issue, was you.

The initial STR and follow-up comments, do not involve NVDA dialogs, but seem to be the result of some missed event or missed extensionPoint notification. Either way, it is a different problem.

There is a separate difficulty here: @Neurrone opened this issue in 2020, but now in 2023 @Neurrone has posted a comment saying that he hasn't had problems with configuration profiles. When the original STR clearly says he has problems with configuration profiles. So I am confused about that, but it is still a separate issue from #8821.

**Comment by CyrilleB79** [comment] 2024-09-03 11:40
@Neurrone, could you clarify if you are still experimenting the current issue in another case than #8821?

In case @Neurrone or other people are experimenting this issue, we can re-open of course.

What I have described in https://github.com/nvaccess/nvda/issues/11198#issuecomment-1720856508 is the issue #8821, so it's not to take into account.

From @Neurrone's answer in https://github.com/nvaccess/nvda/issues/11198#issuecomment-1720856508,my understanding is that @Neurrone will leave this issue open due to the bug [...] just mentioned, i.e. due to #8821. Hence my "duplicate" conclusion.

**Comment by Neurrone** [comment] 2024-09-03 16:00
I haven't ran into this problem recently.
