### ISSUE TITLE
Freeze when closing context menu in Edge Chromium

### ISSUE THREAD

**Issue by Oreonan** [nvaccess/nvda#10895] opened 2020-03-23 18:25 UTC
### Steps to reproduce:
-Open Edge Chromium in a long page
-Open context menu
-Clic on any element, or press escape to exit context menu

### Actual behavior:
-When context menu will be closing, NVDA will trying to read page in integrality, and will freeze, forcing to manually restart it

### Expected behavior:
-No freeze, reading the element from which the context menu had been opened (as on other browsers)

#### NVDA installed/portable/running from source:
-Installed

#### NVDA version:
-alpha-19811,ced1faff

#### Windows version:
-10.0.19041.153

#### Name and version of other software in use when reproducing 
the issue:
-Edge 80.0.361.69

#### Does the issue still occur after restarting your computer?
-Yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
-No

#### If addons are disabled, is your problem still occuring?
-Not tested

#### Did you try to run the COM registry fixing tool in NVDA menu / tools?
-No

**Comment by feerrenrut** [comment] 2020-03-30 10:05
@Oreonan is NVDA freezing or Edge, does NVDA continue to speak if you alt+tab to another application?
Could you upload an NVDA log?

**Comment by Oreonan** [comment] 2020-03-30 10:16
@feerrenrut No, NVDA is completly freeze, so NVDA speak in 0 other application.
Yes, I attach a log in this reply.
[nvda3003.log](https://github.com/nvaccess/nvda/files/4402088/nvda3003.log)

**Comment by Qchristensen** [comment] 2020-05-13 05:04
After having this reported by a user on Twitter, I can replicate in Edge version 81.0.416.72 official build, 64-bit, on Windows 1909, build 18363.836 with NVDA 2019.2.1 and 2020.1.  Closing Edge brings NVDA back.

**Comment by Carlos-EstebanM** [comment] 2020-05-20 20:47
Hello, I also have this problem and i am the user that report this problem in Twitter.
I use the last version of Edge, and Windows 10 1909.

**Comment by Oreonan** [comment] 2020-05-22 10:03
Today, I not reproduce that with latest Edge's update (83.0.478.37)
But now, when open and close context menu, NVDA not rollback to browse mode
I must to switch bitween other window and Edge window to recover browse mode

**Comment by Carlos-EstebanM** [comment] 2020-05-22 15:09
Hello.I use Edge Stable, the version is 81.0.416.77. The version 83 is in other channel?  Enviado desde Correo para Windows 10 De: OreonanEnviado: viernes, 22 de mayo de 2020 5:03Para: nvaccess/nvdaCC: Carlos-EstebanM; CommentAsunto: Re: [nvaccess/nvda] Freeze when closing context menu in Edge Chromium (#10895) Today, I not reproduce that with latest Edge's update (83.0.478.37)But now, when open and close context menu, NVDA not rollback to browse modeI must to switch bitween other window and Edge window to recover browse mode—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Carlos-EstebanM** [comment] 2020-05-25 15:27
In my laptop, I have Edge 83, and NVDA work again with the contextual menu.
Regards.

**Comment by Adriani90** [comment] 2020-05-25 21:06
Thanks for reporting, I am closing this as works for me. I wil reopen a new issue for turn back to browse mode after context menu is closed, but note that this works again after pressing tab once.

**Closed** 2020-05-25 21:06 UTC
Labels: app/edge, bug/app-freeze, bug/freeze, close/worksforme
