### ISSUE TITLE
layered keyboard commands for script gestures

### ISSUE THREAD

**Issue by davidacm** [nvaccess/nvda#14656] opened 2023-02-21 15:23 UTC
### Is your feature request related to a problem? Please describe.

Currently, sometimes it's difficult to assign default gestures to new features in NVDA. NVDA has a large number of scripts, and add-ons add even more. Collisions often occur between scripts from different add-ons, this doesn't  happen internally in NVDA but at the cost of leaving some scripts unassigned, such as the Screen Curtain functionality which is very important for many users.

While there are scripts that require easy access and should be a single gesture, some (such as tools or utilities) could have two layered commands in sequence.

### Describe the solution you'd like

I would like to be able to assign two consecutive gestures for NVDA scripts or NVDA add-ons scripts, in case developers or users want to.

This would open up gesture combinations to many more possibilities and make it easier to find a good gesture for current and future scripts. It could be used in scripts that are important but not frequently used.

Example of use:

Screen Curtain currently does not have a gesture. We could assign a gesture without worry about causing conflicts, with a second layer in the gesture sequence.
E.g. "NVDA + z, c". or "NVDA + z, control f12"

So, the user could press "NVDA + z" and "c" to toggle the Screen Curtain state.

This is just an example, perhaps not the most practical gesture sequence, but it shows how this feature could work.

The second gesture should not be limited to single key commands and should work like any other NVDA gesture, if technically feasible.

Every time a gesture consisting of 2 sequences is used, NVDA should play a sound to indicate that it is waiting for the next command. If the user enters anything else that is not within that second layer of gestures, NVDA would produce another sound to indicate to the user that the gesture has been cancelled and is in the primary layer of gestures again.

In my opinion, if the second command is not assigned, it should be captured by NVDA and not passed to the system. This way, the user can cancel the gesture if they pressed it by mistake without affecting the system. But that is something we can discuss in this thread.

For the user, in the gesture assignment view, an additional button could be shown to add two layered gestures.

### Describe alternatives you've considered

Some add-on dvelopers implemented their own two layered scripts, but the problem is that those gestures can't be customized  by the user.

**Comment by josephsl** [comment] 2023-02-21 15:32
Hi, this provides additional justifications for investigating #3687. Thanks.

**Comment by ABuffEr** [comment] 2023-02-21 16:29
Hi,
even I know that without a working PR it's not a solid proposal, I'd want to recall again [this idea](https://nvda-addons.groups.io/g/nvda-addons/message/18189), that in my humble opinion could help here too (creating a new anonymous context for a gesture that has none previously). Reading the example code, I think today that a "@scriptContext" decorator could be better, maybe.

**Comment by jcsteh** [comment] 2023-02-23 11:48
Duplicate of #3687.

**Closed by jcsteh** 2023-02-23 11:48 UTC
