### ISSUE TITLE
no line breaks in code block in Chrome

### ISSUE THREAD

**Issue by jfayre** [nvaccess/nvda#7057] opened 2017-04-06 16:04 UTC
When reading this page:
https://home-assistant.io/cookbook/automation_for_rainy_days/ 
NVDA does not insert line breaks when reading the code example. This works in Firefox and Internet Explorer. I suspect this may be a chrome issue.

**Comment by jcsteh** [comment] 2017-04-12 02:32
Confirmed.

Technical: This is a "pre" element containing "span" elements for highlighting. Chrome doesn't expose line feed characters in this case. Even the IAText line offsets are incorrect and seem to break at the span elements. We'll need to file a bug against Chrome.

**Comment by jcsteh** [comment] 2017-04-12 02:33
P2 because this probably makes many code blocks practically unreadable.

**Comment by PratikP1** [comment] 2017-04-12 03:48
Note that this behavior is not just limited to code blocks. I’ve noticed it with certain set of page content as well. I’m not sure what’s causing it yet. I’m investigating. I’ll supply more details as I discover it.

**Comment by jfayre** [comment] 2017-04-12 12:39
I filed an issue on the Chromium bug tracker. Hopefully that is the
right place to put this:
https://bugs.chromium.org/p/chromium/issues/detail?id=710485#c2

**Comment by jcsteh** [comment] 2017-04-12 14:01
Thanks for filing. I've added further detail and copied the appropriate
engineer at Google.

**Comment by bramd** [comment] 2017-08-13 11:55
I hope this is the same issue. It seems sometimes also whitespace, not just line breaks, gets lost.
A simple testcase, open the following:

data:text/html,<pre><code><span class="keyword">def</span> <span class="title">hello</span></code></pre>

Expected: def hello
Actual: defhello

Tested in Chrome 62.0.3183.0 (Official Build) canary (64-bit).

**Comment by ehollig** [comment] 2018-10-09 22:35
It seems that [Issue 710485](https://bugs.chromium.org/p/chromium/issues/detail?id=710485) has been fixed. Closing

**Closed by ehollig** 2018-10-09 22:35 UTC
Labels: Chrome, GoogleWork, blocked, needsExternalFix, p2
