### ISSUE TITLE
nvda announces panel on opening start start + e

### ISSUE THREAD

**Issue by fernando-jose-silva** [nvaccess/nvda#15409] opened 2023-09-08 22:44 UTC
### Steps to reproduce:
I upgraded a machine to windows 11 22631.2271
Pressing start + e brings up a new explorer view called home.
### Expected behavior:
nvda should announce list and navigate with arrows to available items.

atual
nvda announces panel and tab name home.
when walking with the arrows nvda is silent.
For this window to be read, it is necessary to remove the focus from the window and return.
This happens even if we get to this window in another way, such as pressing backspace on folders until we return to the beginning.

#### NVDA installed/portable/running from source:
instaled
#### NVDA version:
nvda.exe, NVDA alpha-29134,62918ad9

#### Windows version:
11 22631.2271
#### Does the issue still occur after restarting your computer?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no
#### If NVDA add-ons are disabled, is your problem still occurring?
yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
log
[explorer.txt](https://github.com/nvaccess/nvda/files/12564040/explorer.txt)

**Comment by Brian1Gaff** [comment] 2023-09-09 10:20
Does Narrator work correctly? I thought that this was a windows bug, ie the focus is not being sent correctly on the first instance. I myself do not use 11, and indeed do not fully understand why this sort of extra view even exists.
 Brian

-- 
***@***.*** 
Sent via blueyonder.(Virgin media) 
Please address personal E-mail to:-
***@***.***, putting 'Brian Gaff'
in the display name field.

**Comment by seanbudd** [comment] 2023-09-11 03:44
Can you confirm if this is also an issue with 2023.2?

**Comment by josephsl** [comment] 2023-09-11 03:50
HI, yes, and this can be reproduced with Narrator, so this might be something going on with File Explorer itself. A feedback was filed with Microsoft a while back as this is a huge accessibility/usability regression in Windows Insider Preview builds. Thanks.

**Comment by fernando-jose-silva** [comment] 2023-09-27 15:13
just to point out that this annoying problem reached windows build 22621.2361
Will Microsoft not pay attention to this, and will it reach the stable version?
Now my request is more out of desperation, is there a way in Windows to disable the visualization of the home screen and return to the quick access view?
Or do the programmers have some really ugly command line for nvda so that it doesn't suffer from this problem, I'm willing to run it on my nvda, just so I don't see this problem all the time while working.
Just to be clear, I don't want an ugly solution to be put into nvda, ideally microsoft will fix it and everything will be fine.
Or if this reaches the stable version of Windows and Microsoft doesn't fix it, and users complain a lot, a solution, even if ugly, can be incorporated into an addon or NVDA.
But in the meantime, an ugly command line in my nvda would save some time of heartbreak.
I'm not going to downgrade Windows for this, folks.
sorry for the rant.

**Comment by josephsl** [comment] 2023-10-12 12:48
Hi, yes and no. Yes  it might be possible to work around focus event issue, and no because it is something going on with File Explorer/WinUI as it is affecting Narrator as well. Thanks.

**Comment by fernando-jose-silva** [comment] 2023-10-12 13:06
Thank you very much, I really appreciate the efforts to solve this, this problem is very bad.

**Comment by XLTechie** [comment] 2023-10-27 05:30
Should I be seeing this in 22621.2428? According to the version numbers given in other comments, it seems that I should be, but I'm not able to repro.

**Comment by XLTechie** [comment] 2023-10-28 05:32
@fernando-jose-silva you did not answer the question in the template about running the COM registration fixing tool. Can you please run the tool, restart your machine, and report back?

I have configured my version of Explorer under Windows 11 Home 22621.2428, to open on the Home display in File Explorer, and I have no trouble navigating it with either NVDA alpha-29757,7f7ae4aa, or NVDA 2023.3rc1.

I found it necessary to use the tab key to move to one of the lists where arrow keys worked, but once I got there, arrows worked just fine.

**Comment by XLTechie** [comment] 2023-10-28 06:52
@fernando-jose-silva Even if this is working differently in different versions of Win 11, and even if my suggestions above fail, are you able to turn off the home view and restore old behavior?

For example:
* Press Windows key.
* Type "`folder options`", which, on my system, is a quicker way of reaching "`File Explorer Options`".
* The very first option is a combo box called "Open File Explorer To".
* In that selector, choose "This PC", then press enter.

Please try the COM Reg Fixing Tool, and then the tab key, from my earlier comment, before doing this. I would like to find out if the inability to navigate the Home view is a general problem, or a problem of your system. @josephsl seems to suggest it is a general problem, but you say it is in stable Win 11, and I do not find that to be the case. One of those things does not add up.

**Comment by Adriani90** [comment] 2023-10-28 10:09
This is reproducible in Windows 11 22 H2 last build and NVDA last alpha when you set the windows explorer to open the home section. In fact, the window class for the home section seems not  to be handled correctly, by NVDA. I guess it is handled by UIA but NVDA tries to access it via IAccessibleHanndler. The focus does not land on the element list when you access this window for the first time, so arrow keys do not work.
However, as a workaround, pressing tab or shift+tab restores the focus and NVDA can navigate the windows properly.


Here is the log part related to the focus landing on the home window of the Windows Explorer and the arrow key navigation does not work:

```
IO - inputCore.InputManager.executeGesture (12:00:23.620) - winInputHook (15632):
Input: kb(laptop):alt+tab
IO - speech.speech.speak (12:00:23.689) - MainThread (8104):
Speaking ['Start', '2 von 2', CancellableSpeech (still valid)]
DEBUGWARNING - IAccessibleHandler.internalWinEventHandler._shouldGetEvents (12:00:24.091) - MainThread (8104):
Foreground took too long to change. Foreground still 393920 (CabinetWClass). Should be 132880 (XamlExplorerHostIslandWindow)
IO - speech.speech.speak (12:00:24.124) - MainThread (8104):
Speaking ['Start', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:24.129) - MainThread (8104):
Speaking ['Liste', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:24.131) - MainThread (8104):
Speaking ['Schnellzugriff ', 'Gruppierung', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:24.133) - MainThread (8104):
Speaking ['Liste', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:24.135) - MainThread (8104):
Speaking ['Downloads ', '2 von 7', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:26.414) - winInputHook (15632):
Input: kb(laptop):enter
IO - speech.speech.speak (12:00:26.729) - MainThread (8104):
Speaking ['Elementansicht', 'Liste', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:26.730) - MainThread (8104):
Speaking ['Anfang der Woche', 'Gruppierung', 'ausgeklappt', CancellableSpeech (still valid)]
IO - speech.speech.speak (12:00:26.735) - MainThread (8104):
Speaking ['Präsentation_AM_061123.pptx', 'Nicht ausgewählt', '1 von 70', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:28.459) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - speech.speech.speak (12:00:28.503) - MainThread (8104):
Speaking ['Anfang der Woche', 'Gruppierung', 'ausgeklappt', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:29.070) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (12:00:29.414) - winInputHook (15632):
Input: kb(laptop):downArrow
IO - speech.speech.speak (12:00:29.453) - MainThread (8104):
Speaking ['Präsentation_AM_061123.pptx', '1 von 70', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:29.786) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - speech.speech.speak (12:00:29.819) - MainThread (8104):
Speaking ['Anfang der Woche', 'Gruppierung', 'ausgeklappt', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:30.079) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (12:00:31.315) - winInputHook (15632):
Input: kb(laptop):backspace
IO - speech.speech.speak (12:00:31.648) - MainThread (8104):
Speaking ['Fenster', CancellableSpeech (still valid)]
IO - inputCore.InputManager.executeGesture (12:00:32.372) - winInputHook (15632):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (12:00:32.710) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (12:00:33.030) - winInputHook (15632):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (12:00:33.306) - winInputHook (15632):
Input: kb(laptop):rightArrow
IO - inputCore.InputManager.executeGesture (12:00:33.582) - winInputHook (15632):
Input: kb(laptop):downArrow
IO - inputCore.InputManager.executeGesture (12:00:33.841) - winInputHook (15632):
Input: kb(laptop):upArrow
IO - inputCore.InputManager.executeGesture (12:00:34.169) - winInputHook (15632):
Input: kb(laptop):leftArrow
IO - inputCore.InputManager.executeGesture (12:00:34.401) - winInputHook (15632):
Input: kb(laptop):rightArrow
```

**Comment by Adriani90** [comment] 2023-10-28 10:12
And here is the developer info for the window when you access the window for the first time and arrow key navigation does not work:
```
INFO - globalCommands.script_navigatorObject_devInfo (12:00:38.981) - MainThread (8104):
Developer info for navigator object:
name: ''
role: 3
processID: 2820
roleText: None
states: 2
isFocusable: False
hasFocus: True
Python object: <NVDAObjects.UIA.UIA object at 0x098C1690>
Python class mro: (<class 'NVDAObjects.UIA.UIA'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: ''
location: RectLTWH(left=200, top=170, width=1376, height=656)
value: None
TextInfo: <class 'NVDAObjects.NVDAObjectTextInfo'>
appModule: AppModule(explorer, appName='explorer', processID=2820)
appModule.productName: 'Betriebssystem Microsoft® Windows®'
appModule.productVersion: '10.0.22621.2428'
appModule.helperLocalBindingHandle: c_long(79968088)
windowHandle: 525770
windowClassName: 'Microsoft.UI.Content.DesktopChildSiteBridge'
windowControlID: 0
windowStyle: 1342177280
extendedWindowStyle: 2097152
windowThreadID: 15800
windowText: ''
displayText: ''
UIAElement: <POINTER(IUIAutomationElement) ptr=0x4e98218 at 9948f30>
UIA automationID: 
UIA frameworkID: XAML
UIA runtimeID: (42, 525770)
UIA providerDescription: [pid:15092,providerId:0x805CA Main:Nested [pid:2820,providerId:0x805CA Main(parent link):Unidentified Provider (unmanaged:Microsoft.UI.Xaml.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]
UIA className: Microsoft.UI.Content.DesktopChildSiteBridge
UIA patterns available: LegacyIAccessiblePattern
```

cc: @michaelDCurran, @leonardder

**Comment by josephsl** [comment] 2023-10-28 14:12
Hi,

You will get the behavior described by the original poster if you turn on "Get the latest updates as soon as they're available" toggle from Settings/Windows Update or running Windows Insider builds. The issue seems to be caused by the refined File Explorer interface introduced in Windows 11 2022 Update Moment 4 (build 22621.2428). As I noted above, this issue is also seen when using Narrator.

Thanks.

**Comment by fernando-jose-silva** [comment] 2023-12-01 22:05
hello everybody
I discovered belatedly, due to lack of experience, that when NVDA announces the panel I can do the following:
laptop keyboard layout
I press nvda + shift + down arrow and nvda announces:
list
I press nvda + shift + down arrow again and nvda announces:
quick access expanded group
Now I can walk with nvda + shift + right arrow
through the list items, at this point with the focus on a list item I press
nvda + shift + m moves the mouse pointer to the current navigation object)
and now I press nvda + [ (left mouse button click)
At this point I can move with the arrows through the list.
Is it possible to automate all these payments in NVDA?

**Comment by Adriani90** [comment] 2024-02-26 18:50
@fernando-jose-silva it seems this needs an external fix from Microsoft. Could you please report this to them?

**Comment by fernando-jose-silva** [comment] 2024-02-26 19:02
Yes, I opened not one, but several complaints on fidback hub, but no response, and after numerous updates, no news.
In this case, I truly believe that nothing will change until an nv access developer or renowned developer in this area of ​​accessibility contacts Microsoft and makes a complaint, this problem will not be resolved.
This problem is really very, very annoying for anyone who knows how to use a computer, and a big problem for beginners. I know it's not everyone's opinion, but I still argue that in these cases, where the problem is so latent, so uncomfortable, that a solution, even through subterfuge, should be adopted, whether in the core of nvda or through a complement.
Sorry for the rant, this is one of the few problems that seriously irritates me.

**Comment by josephsl** [comment] 2024-02-26 19:36
Hi, even after telling Microsoft that this is also reproducible with Narrator? Testing with their own screen reader should tell Microsoft that this is something that affects various screen readers. This is not news to me (at least to me since we’ve seen other examples, including UI Automation implementation nightmare people have talked about for years). Thanks.

**Comment by Adriani90** [comment] 2024-02-26 19:41
Not sure if Microsoft really cares about this. In the Web AIM survey narrator usage was very low at 0.7% of users or something similar, so I think they might get the signal that it is not really worth it to invest lot of ressources in developing further the aPIs or solving such bugs.

I hope they are not completely putting all accessibility related things in the hands of external screen reader developers.

 

 

Von: Joseph Lee ***@***.***> 
Gesendet: Montag, 26. Februar 2024 20:36
An: nvaccess/nvda ***@***.***>
Cc: Adriani90 ***@***.***>; Comment ***@***.***>
Betreff: Re: [nvaccess/nvda] nvda announces panel on opening start start + e (Issue #15409)

 

Hi, even after telling Microsoft that this is also reproducible with Narrator? Testing with their own screen reader should tell Microsoft that this is something that affects various screen readers. This is not news to me (at least to me since we’ve seen other examples, including UI Automation implementation nightmare people have talked about for years). Thanks.

**Comment by fernando-jose-silva** [comment] 2024-02-26 19:42
yes, in the complaints sent to Microsoft, I mentioned the narrator, and nvda. We need someone with greater access to Microsoft to advance our demands, and also creative minds willing to create solutions, even if less appropriate, to some problems. Thanks.

**Comment by josephsl** [comment] 2024-05-07 05:49
Hi,

May 2024 update: still happens in Windows 11 24H2. I advise wider awareness campaign or something similar - if an accessibility/usability issue can be reproduced when using Microsoft's own assistive technologies, chances are that we need to ask the crowd to help us (as I noted several months ago, this has to do with redesigned File Explorer interface). I'm really hesitant to advise NV Access to investigate an NVDA solution for this as it is clear that Narrator users are also experiencing this issue. I concur with the original poster's assessment (and to add my opinion for this one): this is an epic accessibility fail - consider that by default, File Explorer is set to open Home.

Thanks.

**Comment by fernando-jose-silva** [comment] 2024-05-07 20:39
please let's start this awareness campaign as soon as possible, I will be vocal in asking for this.
If I can give an opinion,
@josephsl 
and other valuable authors, if you could develop a correction, if not in the core of nvda, yes in an addon, or even in a script, I work teaching classes for the visually impaired, and users are uncomfortable with this problem, and even more so if they are a user As a beginner, this prevents him from moving forward until we teach him how to do a workaround to get out of this problem.
I accept very silly things, like opening and closing a window so that nvda gains focus again in the window, as the quickest way I'm finding to get rid of this problem is precisely to teach students how to open the nvda menu and then exit immediately after accessing the file explorer.
I've already ventured into doing this myself as a script for nvda, but I think I lack the intelligence to write this.
Thank you very much.

**Comment by tapper82** [comment] 2024-05-13 12:39
Why not just set it to open to this PC?

**Comment by fernando-jose-silva** [comment] 2024-05-13 19:28
because many very interesting features are lost, especially for beginner users, or those who just want to make their day-to-day life easier, such as easier access to folders created natively by Windows, such as documents, images, among others, access to cloud disks, access to the last files used, among other advantages.
It is not fair that everyone has access to these new functions, and that people with visual impairments are disadvantaged in accessing these functions.

**Comment by tapper82** [comment] 2024-05-13 20:47
I have documents, images,  and downloads in my this pc.
https://www.elevenforum.com/t/add-or-remove-folders-under-this-pc-in-file-explorer-in-windows-11.7122/
 I don't like that when opening to home instead of this pc windows can move files and folders around.

**Comment by fernando-jose-silva** [comment] 2024-05-13 22:19
Thank you very much, I really appreciate the records.
I will test it as soon as possible.
But I believe this still doesn't solve it, or doesn't serve as an argument to close this problem, this error has to be selected by Microsoft, or even by some developer giving Nb access, almost no one knows about these records, I believe that in the future they may even stop working, and as previously stated, this is a structural problem with the new explorer, which could spread if the visually impaired community does nothing.

**Comment by seanbudd** [comment] 2024-06-06 01:55
Apologies, this was miscategorised initially, the severity is low and there is a workaround

**Comment by fernando-jose-silva** [comment] 2024-06-07 01:13
Please help me identify if what is happening now is still related to this problem, or should I open a new problem.
As a reminder, My Computer is set to open in This Computer (My Computer), notice it is no longer in the beginning view of the first report of this problem.
I also ran the suggested registries, and on my computer I now have all the folders displayed.
Everything working fine.
Now begins the description of the problem:
if I open the file explorer and the previously opened window is WhatsApp, nvda will announce
This Computer – File Explorer
Shell Folder View
Shell Folder View
This Computer guide selected 1 of 1
and it will not be possible to navigate through the files with the arrows.
Remember, this will only occur if the previously opened window is WhatsApp, if you have another window in focus the error will not occur.
steps to reproduce:
open whatsapp
press start + e

I was reluctant to report this, as it seems very specific, and even crazy, but follow the report if it is useful.
There is also a log of the point where the error occurs.
The machine where I reported this problem is broken, as I now have another machine, follow the Windows version and WhatsApp and NVDA
WhatsApp.exe, 5319275A.51895FA4EA97F 2.2422.5.0
windows 11 26100.712
nvda.exe, NVDA alpha-32268,0562f690
Thanks.
[explorer.txt](https://github.com/user-attachments/files/15688378/explorer.txt)

**Comment by tapper82** [comment] 2024-06-07 07:31
Same prob here. You don't even need to have WhatsApp installed. All tho it's not a biggy for me because I open to this PC and not home.

**Comment by Adriani90** [comment] 2024-06-08 00:26
Thanks for the reporting @tapper82, closing as fixed.

**Closed by Adriani90** 2024-06-08 00:26 UTC
Labels: close/worksforme, blocked/needs-external-fix, p4, feature/windows-explorer, triaged
