### ISSUE TITLE
Firefox when reading current line in some edit fields only the first character is announced.

### ISSUE THREAD

**Issue by lukaszgo1** [nvaccess/nvda#9001] opened 2018-12-02 14:12 UTC
### Steps to reproduce:
1. In firefox open the following web page
https://wu.up.krakow.pl/WU/
2. Move with letter e to the first edit field.
3. type something like s111222.
4. Press tab to move to the password field.
5. Go back to the first edit box with the shift+tab and press NVDA_up arrow to read the current line.
### Actual behavior:
Only S is announced.
### Expected behavior:
The entire content should be read.
#### NVDA Installed/portable/running from source:
Installed.
#### NVDA version:
NVDA version alpha-16333,db3a6596

#### Windows version:
Windows 7 x64
#### Name and version of other software in use when reproducing the issue:
Nightly 65
#### Other information about your system:
It is working correctly with IE. Don't have access to Windows 10 machine to the with Edge at the moment.
#### Does the issue still occur after restarting your PC?
Yes
#### Have you tried any other versions of NVDA?
No
cc @jcsteh

**Comment by lukaszgo1** [comment] 2018-12-02 14:37
@Brian1Gaff This is strange. I've installed Waterfox 56.2.5 just now and I am able to reproduce it there. I've event tried with all add-ons disabled. Have you tabbed from  and back to the first edit field?

**Comment by lukaszgo1** [comment] 2018-12-02 15:50
My Nightly window is maximized. I've tried with clean config of both NVDA and Nightly, and all the time when going to the field with shift+tab and pressing NVDA+ up arow only the first character is announced.

**Comment by DrSooom** [comment] 2018-12-02 19:35
No different behaviour with NVDA 2018.4 Beta 2 Portable and Firefox 63.0.3 Portable on Win7x64 in compare with installed NVDA 2018.1.

How many characters are spoken when the cursor is located on different positions when pressing NVDA+ArrowUP in focus mode in this text field? I guess you are able to move the cursor inside this text field with the arrow keys in focus mode as usual. And is a braille display connected?

CC: @michaelDCurran and @MarcoZehe

**Comment by lukaszgo1** [comment] 2018-12-02 19:45
There is no braille display connected, and the position of the cared doesn't matter I am always getting only the first character when pressing NVDA+ up arrow. I am attaching the log demonstrating this at the debug level.
[nvda-old.log](https://github.com/nvaccess/nvda/files/2637302/nvda-old.log)

**Comment by lukaszgo1** [comment] 2018-12-02 20:05
Another discovery. If anything is entered into the password field the first edit box behaves correctly. Testing with JAWS 2018 shows, that he is also affected.

**Comment by DrSooom** [comment] 2018-12-02 20:54
Ah, okay. I always entered some text in the password field. Now I was able to reproduce it with NVDA 2018.1 and Firefox 56.0.2 as well as with NVDA 2018.4 Beta 2 Portable and Firefox 63.0.3 Portable – both on win7x64.

If a braille display is connected, press ArrowRight in focus mode in the first text field and more and more characters are shown on the braille display. But you are right, pressing NVDA+ArrowUp will only say the very first letter, wherever the cursor is located in this text field.

I also know another text field at an online banking form for SEPA transfer, which have the same behaviour, but for security and privacy reasons I'm not able to give you further information about this. Well, my bank is going to take this online banking website down and want to replace it with a complete new one – which accessibility is … ah, just forget it.

**Comment by lukaszgo1** [comment] 2019-03-30 18:21
This happens on more and more login forms for example when logging in to Twitter or PayPal. Any chance for a fix? cc @jcsteh @MarcoZehe

**Comment by Adriani90** [comment] 2020-05-12 20:20
I am closing this issue as duplicate of #5861. Let's continue the discussion there if someone has any further meaningful suggestions to this issue.

**Closed by Adriani90** 2020-05-12 20:20 UTC
Labels: close/duplicate

**Comment by jcsteh** [comment] 2020-05-13 22:33
I can't reproduce this on the PayPal or Twitter login forms, even when tabbing away and back or entering text into the password field first. I was able to reproduce it on HackerRank, though.

**Comment by lukaszgo1** [comment] 2020-05-19 08:41
I'm no longer able to reproduce this on Twitter or PayPal either - I guess these websites has changed ANother example of this behavior is login form on Audible.
