### ISSUE TITLE
Code examples in the Developer Guide shouldn't be automatically translated by Google Translate

### ISSUE THREAD

**Issue by Qchristensen** [nvaccess/nvda#15853] opened 2023-11-29 01:13 UTC
### Is your feature request related to a problem? Please describe.

Request from user Ronny via email, who uses Google Translate to translate the Developer Guide.  They would like the text translated, but not the code examples.

### Describe the solution you'd like

According to https://cloud.google.com/translate/troubleshooting we can use:

`<span translate="no"> </span>`
`<span class="notranslate"> </span>`

on the sections we don't want translated.

### Describe alternatives you've considered

I just looked that up and I'm happy for any better suggestions anyone feels would be better.

**Comment by Nael-Sayegh** [comment] 2023-12-18 15:09
Hello,
Are you talking about the developer guide available at this address?
https://github.com/nvdaaddons/DevGuide/wiki/NVDA-Add-on-Development-Guide
Thank you

**Comment by CyrilleB79** [comment] 2023-12-18 16:11
Given the issue is in NVDA repository, I guess that we are rather talking about https://github.com/nvaccess/nvda/blob/master/projectDocs/dev/developerGuide/developerGuide.t2t

The other guide (https://github.com/nvdaaddons/DevGuide/wiki/NVDA-Add-on-Development-Guide) is from NVDA add-ons community. It may be desirable to convert code tags the same way, but the decision is not NV Access' one. I don't remember if @josephsl is still maintaining it or if someone else has taken it over.

**Comment by josephsl** [comment] 2023-12-18 16:15
Hi, unless someone has other plans, I plan to incorporate Python 3.11 changes to that guide in coming weeks. Thanks.

**Comment by hwf1324** [comment] 2023-12-18 17:47
Let's see if the new document builder will take care of this for us once we move from txt2tag to markdown.

**Comment by CyrilleB79** [comment] 2023-12-18 20:35
@seanbudd, is there a plan for converting the dev documentation from t2t to markdown along with the conversion done on translatable documents (user guide, change log)?

**Comment by seanbudd** [comment] 2024-03-04 04:27
We should be able to fix this when these documents are converted to markdown with the following extended markdown syntax:

`{translate="no" .notranslate}`

https://python-markdown.github.io/extensions/attr_list/

**Comment by seanbudd** [comment] 2024-03-04 04:48
Blocked by #16144

**Comment by Nael-Sayegh** [comment] 2024-05-09 08:04
Hello,
Since #16144  has been closed, can this issue be worked on by a developer to make a PR?
Thank you

**Comment by CyrilleB79** [comment] 2024-05-09 20:56
Yes, the issue is triaged and not blocked anymore, so a PR should be accepted.

**Comment by Nael-Sayegh** [comment] 2024-05-11 21:20
Hello,
After checking, with the conversion of the guide to markdown with #16144, the html file has the <code> tag which does not translate the code snippets.
I think that this problem is solved.

**Comment by seanbudd** [comment] 2024-05-13 07:26
Actually, #16144 / #16492  did not change anything here, these files are the same in 2024.1.
It appears that switching to markdown in 2024.1 generated `<code>` tags around code formatting blocks which were not present in 2023.3.
It appears that the google translate widget handles `<code>` blocks as `notranslate`.
I assume most translator tools support this.
Closing as fixed in 2024.1

**Closed by seanbudd** 2024-05-13 07:26 UTC
Labels: component/documentation, p5, quick fix, feature/i18n, good first issue, triaged
