### ISSUE TITLE
Windows 10 1703 nvda sometimes stops responding.

### ISSUE THREAD

**Issue by gdata1** [nvaccess/nvda#7181] opened 2017-05-16 18:18 UTC
Hello. Sometimes the nvda stops responding on windows 10 1703. This happens most often when opening the start menu and in the Microsoft edge.

**Comment by josephsl** [comment] 2017-05-16 18:19
Hi, which NVDA build are you using, and do you happen to have a log of these events when they happen? Thanks.

**Comment by gdata1** [comment] 2017-05-16 18:22
only helps nvda restart using ctrl + alt + n with no errors.

**Comment by josephsl** [comment] 2017-05-16 18:24
Hi, we need concrete steps to reproduce the issues you’re having. Thanks.

**Comment by gdata1** [comment] 2017-05-16 18:25
I use nvda next-14049, 9f4fe894

**Comment by gdata1** [comment] 2017-05-16 18:32
Ok. 1. When you press start nvda becomes silent and feeling as if it is not running. 2. When you press ctrl + alt + n sound download nvda and it works as usual. It is noteworthy that the sound of the completion of the work in these cases quietly.3. Microsoft edge a similar situation occurs at some sites if you walk on them very quickly nvda stops responding and helping described in step 2. example site I unfortunately can't bring. This doesn't happen on certain sites and always on different.

**Comment by gdata1** [comment] 2017-05-16 18:33
I apologize for bad English. I'm from Russia.

**Comment by josephsl** [comment] 2017-05-16 18:36
Hi, no need to apologize for bad English. What the developers are after is a way for us to understand what’s up so we can help you. Thanks.

**Comment by josephsl** [comment] 2017-05-16 18:36
Hmmm, CC @MichaelDCurran, @JCSTeh and others, any comments? I have experienced some of the ones outlined, but cannot pinpoint to where the issue might be. Thanks.

**Comment by gdata1** [comment] 2017-05-16 18:44
I'll post the same magazine. Maybe something will help.
ERROR - eventHandler.executeEvent (21:12:27.640):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x06F732F0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 901, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 797, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1040, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 613, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 980, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, '\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0 \xe7\xe0\xe4\xe0\xed \xed\xe5\xe2\xe5\xf0\xed\xee.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (21:12:27.657):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x06F736B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 901, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 797, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1040, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 613, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 980, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, '\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0 \xe7\xe0\xe4\xe0\xed \xed\xe5\xe2\xe5\xf0\xed\xee.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (21:12:27.690):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x06F58B30> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 901, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 797, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1040, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 613, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 980, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, '\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0 \xe7\xe0\xe4\xe0\xed \xed\xe5\xe2\xe5\xf0\xed\xee.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (21:12:27.710):
error executing event: focusEntered on <NVDAObjects.UIA.UIA object at 0x06F58FD0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 901, in event_focusEntered
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 797, in _get_isPresentableFocusAncestor
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1040, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\__init__.pyc", line 613, in _get_presentationType
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 980, in _get_states
  File "NVDAObjects\UIA\__init__.pyc", line 682, in _prefetchUIACacheForPropertyIDs
COMError: (-2147024809, '\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0 \xe7\xe0\xe4\xe0\xed \xed\xe5\xe2\xe5\xf0\xed\xee.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (21:12:27.739):
error executing event: gainFocus on <NVDAObjects.UIA.ListItem object at 0x06F583B0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 143, in executeEvent
  File "eventHandler.pyc", line 91, in __init__
  File "eventHandler.pyc", line 98, in next
  File "C:\Users\nikit\AppData\Roaming\nvda\addons\wintenApps\globalPlugins\wintenObjs\__init__.py", line 199, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "appModules\explorer.pyc", line 280, in event_gainFocus
  File "eventHandler.pyc", line 98, in next
  File "NVDAObjects\__init__.pyc", line 908, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 820, in reportFocus
  File "speech.pyc", line 354, in speakObject
  File "speech.pyc", line 270, in speakObjectProperties
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "NVDAObjects\UIA\__init__.pyc", line 1217, in _get_value
  File "NVDAObjects\UIA\__init__.pyc", line 665, in _getUIACacheablePropertyValue
COMError: (-2147024809, '\xcf\xe0\xf0\xe0\xec\xe5\xf2\xf0 \xe7\xe0\xe4\xe0\xed \xed\xe5\xe2\xe5\xf0\xed\xee.', (None, None, None, 0, None))
ERROR - eventHandler.executeEvent (21:19:41.819):
error executing event: gainFocus on <NVDAObjects.UIA.edge.EdgeNode object at 0x06F584D0> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 171, in doPreGainFocus
  File "browseMode.pyc", line 1070, in event_treeInterceptor_gainFocus
  File "browseMode.pyc", line 1126, in _set_selection
  File "cursorManager.pyc", line 107, in _set_selection
  File "cursorManager.pyc", line 422, in updateSelection
  File "treeInterceptorHandler.pyc", line 158, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 610, in copy
  File "NVDAObjects\UIA\__init__.pyc", line 237, in __init__
  File "textInfos\__init__.pyc", line 238, in __init__
TypeError: cannot create weak reference to 'NoneType' object
WARNING - watchdog._watcher (21:38:08.483):
Core frozen in stack:
  File "nvda.pyw", line 199, in <module>
  File "core.pyc", line 396, in main
  File "wx\_core.pyc", line 8657, in MainLoop
  File "wx\_core.pyc", line 7952, in MainLoop
  File "core.pyc", line 367, in Notify
  File "queueHandler.pyc", line 83, in pumpAll
  File "queueHandler.pyc", line 50, in flushQueue
  File "eventHandler.pyc", line 61, in _queueEventCallback
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 118, in setFocusObject
  File "treeInterceptorHandler.pyc", line 47, in cleanup
  File "baseObject.pyc", line 21, in __get__
  File "appModules\hxmail.pyc", line 15, in _get_isAlive
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "appModules\hxmail.pyc", line 30, in _get_shouldCreateTreeInterceptor

ERROR - eventHandler.executeEvent (21:38:12.963):
error executing event: gainFocus on <NVDAObjects.IAccessible.sysListView32.ListItem object at 0x06F58650> with extra args of {}
Traceback (most recent call last):
  File "eventHandler.pyc", line 138, in executeEvent
  File "eventHandler.pyc", line 151, in doPreGainFocus
  File "api.pyc", line 118, in setFocusObject
  File "treeInterceptorHandler.pyc", line 47, in cleanup
  File "baseObject.pyc", line 21, in __get__
  File "appModules\hxmail.pyc", line 15, in _get_isAlive
  File "baseObject.pyc", line 34, in __get__
  File "baseObject.pyc", line 110, in _getPropertyViaCache
  File "appModules\hxmail.pyc", line 30, in _get_shouldCreateTreeInterceptor
COMError: (-2146233083, None, (None, None, None, 0, None))

**Comment by fernando-jose-silva** [comment] 2017-05-16 18:48
I do not know how to help in a practical way.
I have already reported in another call, that I have this problem, but on a machine with windows 7.
The symptoms are the same, when navigating with the arrows quickly the nvda freezes.
In my case I have to wait for about 15 seconds and the nvda returns to respond, few times it is necessary to restart the nvda.
Sorry if the case reported in this call is different.

**Comment by josephsl** [comment] 2017-05-16 18:49
Hi, if the underlying cause is the same, then it might be best to combine issues. Thanks.

**Comment by gdata1** [comment] 2017-05-16 18:55
Hello. I think that despite the similar symptoms of different causes. I have this happening to Microsoft edge if other browsers there is no such problem. I think here is associated with the interaction of nvda with windows 10 because this is the only version of 1703.

**Comment by fernando-jose-silva** [comment] 2017-05-16 19:11
The call I mentioned is:
3944
Thank you very much.

**Comment by ironcross32** [comment] 2017-05-20 03:24
What build of windows 10, 1703 is a large span, quickest way to get this is to type winver from the run dialog

**Comment by gdata1** [comment] 2017-05-20 08:59
Version 1703 (OS Assembly 15,063,296)

**Comment by mohdshara** [comment] 2017-05-21 11:42
I have experienced such freeze before, but for a while now this is gone. Can we hear from the original reporter if this is fixed for him?

**Comment by gdata1** [comment] 2017-05-22 14:29
Hello. If the problem is solved, I'll tell you. But at the moment the problem continues to manifest itself..

**Comment by francipvb** [comment] 2018-03-09 19:03
Hello,

What about this?

I have these problems too with Windows 10 Version 1709 (OS Build 16299.248).

Maybe a problem with the UIA Handler?

**Comment by zahra21** [comment] 2018-03-11 14:21
hi.
i can reproduce unresponsiveness of nvda in its different versions using windows xp.
i understand the reason of freeze, but specially it happens when:
1- i open skype, my browser firefox and download some files with firefox or recieve one file in skype.
2- when i open many tabs in my browser and want to navigate between them.
3- when i want to switch between my open programs using alt tab.

4- when openoffice becomes unresponsive and i want to end program!
sometimes, nvda becomes very slow and read after five or more second and sometimes completely freeze.

**Comment by Adriani90** [comment] 2018-03-11 14:42
Related to #7982.
Please note the comments provided by @dineshkaushal.

**Comment by gdata1** [comment] 2018-06-13 20:40
Hello. I do not have this problem on Windows 10 1803

**Comment by ehollig** [comment] 2018-06-14 17:37
Closing, as this is no longer an issue for the original author.

**Closed by ehollig** 2018-06-14 17:37 UTC
