### ISSUE TITLE
The content of the slide show in powerpoint 365 is overlapped by error sounds when navigating with arrow keys and the visual highlighter for the virtual cursor is enabled

### ISSUE THREAD

**Issue by Adriani90** [nvaccess/nvda#15677] opened 2023-10-24 22:13 UTC
### Steps to reproduce:
1. Open NVDA and go to vision category in settings.
2.  enable the visual highlighter for the virtual cursor in browse mode
3. Opwn a powerpoint file with a presentation
4. press f5 to open the slide show presentation
5. press the arrow keys to navigate

### Actual behavior:
Following error is written to the log and the presentation is unusable with NVDA alpha or beta while using the highlighter for the virtual cursor.
```
IO - inputCore.InputManager.executeGesture (23:59:49.474) - winInputHook (8004):
Input: kb(laptop):upArrow
IO - speech.speech.speak (23:59:49.476) - MainThread (2516):
Speaking ['Picture Bunt gezeichnete Kinder stehen im Kreis. Sie halten sich an den Händen. Ein Kind sitzt im Rollstuhl.\n']
ERROR - extensionPoints.Action.notify (23:59:49.478) - MainThread (2516):
Error running handler <bound method NVDAHighlighter.handleBrowseModeMove of <visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter object at 0x05E88710>> for <extensionPoints.Action object at 0x08DCB3F0>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 55, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 491, in handleBrowseModeMove
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 475, in updateContextRect
  File "vision\util.pyc", line 78, in getContextRect
  File "vision\util.pyc", line 47, in getCaretRect
  File "vision\util.pyc", line 93, in getRectFromTextInfo
  File "baseObject.pyc", line 41, in __get__
  File "NVDAObjects\__init__.pyc", line 68, in _get_boundingRects
AttributeError: 'ReviewableSlideshowTreeInterceptor' object has no attribute 'hasIrrelevantLocation'
```

### Expected behavior:
No error and the highlighter for the virtual cursor works correctly.

#### NVDA installed/portable/running from source:
Installed

#### NVDA version:
alpha-29726,a207ad54 (2024.1.0.29726)

#### Windows version:
Windows 11 22 H2

#### Name and version of other software in use when reproducing the issue:
Powerpoint Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64 Bit

#### Other information about your system:
n/a

#### Does the issue still occur after restarting your computer?
yes

#### Have you tried any other versions of NVDA? If so, please report their behaviors.
no

#### If NVDA add-ons are disabled, is your problem still occurring?
yes

#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
yes

**Comment by Adriani90** [comment] 2023-10-24 22:15
cc: @seanbudd, @Qchristensen could you please describe how the highlighter works visually in the slide show presentation for you when enabling the virtual cursor highlighter?

cc: @leonardder

**Comment by seanbudd** [comment] 2023-10-30 23:04
Closing as duplicate of #15461

**Closed by seanbudd** 2023-10-30 23:04 UTC
Labels: app/microsoft-office, p3, audience/low-vision, triaged
