### ISSUE TITLE
NVDA sometimes reports the language to which has been switched (by left Alt + Shift) incompletely

### ISSUE THREAD

**Issue by bhavyashah** [nvaccess/nvda#5545] opened 2015-11-26 15:39 UTC
STR
• After a long time, just randomly, press left Alt + left Shift, which is the Windows keystroke to cycle between installed languages.
Expected Result: NVDA will reports the complete name of the language to which has been switched.
Actual Result: NVDA reports only the ending word/phrase of that language’s name.

This bug can be reproduced inconsistently with Windows 7 Ultimate 32 bit, NVDA version 2015.4, applicable to older versions of NVDA as well, with English (United Kingdom) and Hindi, India (Inscript) installed on my system.
To exemplify languages being reported incompletely, the English (United Kingdom) keyboard layout would be reported simply as ‘United Kingdom’ and Hindi, India (Inscript) as ‘Inscript’.

I haven’t been able to figure out a way of reproducing this consistently, but if you change installed languages often, it is likely that once in a while, particularly when you switch languages after a long time (in my experience), the language to which has been switched will be announced partially.

**Comment by k-kolev1985** [comment] 2015-11-26 18:08
Same thing here. Sometimes NVDA will announce only the last part of the string of the language name, witch is actually the language's country, if I'm not mistaking. In my case the languages in use are English US and Bulgarian Bulgaria. Sometimes NVDA will not announce the language change at all, although that is rarely.

Test environment:
- Operating system: Windows 10 Pro (build 10586.11), 64-bit, in Bulgarian with all locale settings set to "Bulgarian".
- NVDA version: next-12845,937f433.
- Processor: Intel Core i5-2320 at 3.00GHz.
- RAM Memory: 4.00 GB.
- Graphics: Palit GeForce GT 630, 1024MB dedicated memory + 2047MB shared system memory, desktop resolution set to 1920x1080.
- Sound Card: Realtek ALC662 at Intel Cougar Point PCH - High Definition Audio Controller.

**Comment by jcsteh** [comment] 2015-11-26 20:55
NVDA only reports the layout name (not the language) if the last language it reported was the same. So, if you have English US and English UK, it'll only report UK if you switch between those two.

So, in order for this to happen, one of two things must apply:

1. You were actually using a layout for the same language before you switched. Based on your comment about Hindi, I doubt this, but I mention it here for completeness.
2. NVDA missed a language change earlier. If that happened, you should have noticed that NVDA *didn't* read the language when you switched at some point. Can you recall this happening? If so, we need to know the circumstances around that.

**Comment by k-kolev1985** [comment] 2015-11-27 11:14
I don't know about bhavyashah, but on my system NVDA sometimes misses to announce an input language change. Unfortunately however, it is hard to pin it down. But I think I can most easily reproduce it in the following scenario: changing the language with left Alt+Shift in a newly launched application (even the built-in Notepad will do). In such a case, NVDA does not announce the input language change. Note, that my default input language is Bulgarian, and not English. Should I provide a log from NVDA? And with what logging level?

**Comment by leonardder** [comment] 2018-02-09 20:30
cc @dkager

**Comment by dkager** [comment] 2018-06-15 09:17
@bhavyashah Do you still experience this problem?

Missing keyboard layout switches can happen for at least three reasons:
1. NVDA received the switch and came up with a message, but a focus change or other event cut it off before it finished. In this case the change is registered but not announced.
2. The change was discarded, for example because sayAll is running. In this case the change is not registered.
3. We are actually missing changes.

**Comment by bhavyashah** [comment] 2018-08-15 05:49
@dkager I don't think I have encountered this issue in the recent past. However, I must confess that I haven't dealth with a second language since 5 months and probably will never need to in the future. Hence, I would like to kindly invite @k-kolev1985's remarks on the present standing of this bug.
P.S. There is a bit of double announcement of languages when switching using Alt+Shift, but I don't think that that issue falls under the ambit of this ticket and I think it is too insignificant to even bother separately reporting.

**Comment by k-kolev1985** [comment] 2018-08-15 11:15
@bhavyashah I can still reproduce the issue described by me on the 27th of November 2015. NVDA still misses to announce input method changes, mainly the first such after the launch of a program, as described in my comment then. As far as I've noticed, NVDA does not miss input method announcements after the launch of a program (second and consecutive change) - only the first one. I'm running NVDA version alpha-15859,671b2023 under Windows 10 Pro version 1803 (build 17134.191), 64-bit, in Bulgarian with all locale settings set to "Bulgarian". The two input methods/languages that I have added are English U.S. and Bulgarian Bulgaria. Please let me know if you need any logs from NVDA and I'll try to provide them.

**Comment by Adriani90** [comment] 2019-02-18 23:00
I am not able to reproduce this issue in Windows 10 1809 Update with NVDA alpha-16768,a6f7fb40. @k-kolev1985 does it make a difference for you when you use the windows 10 app essentials addon from @josephsl?

**Comment by Adriani90** [comment] 2020-05-02 15:31
@k-kolev1985 could you please give an update on this? Do you still see this issue?

**Comment by k-kolev1985** [comment] 2020-05-02 17:32
@Adriani90 If you mean the main issue with NVDA reporting only part of the input method name - no, I can't remember observing it recently.

**Comment by Adriani90** [comment] 2020-05-02 17:47
yes, thank you for reporting back. I am closing this issue for now as works for me. If someone still has this issue, he or she can comment on this and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-02 17:47 UTC
Labels: close/worksforme
