### ISSUE TITLE
Loss of focus after Outlook Notifications

### ISSUE THREAD

**Issue by Jarred-F** [nvaccess/nvda#15685] opened 2023-10-25 16:46 UTC
### Steps to reproduce:
1. Open a webpage and interact in browse mode.
2. Receive a notification from Outlook.
3. Lose speech and focus untileither pressing tab, alt to jump to the menu bar, or alt + tab to set focus to a new application. 
### Actual behavior:
When using browse mode and a notification from Outlook, and possibly other apps, is received, focus and speech are lost a few seconds after the notification sound is played. Once focus is lost, pressing up or down arrow keys moves the page in the browser up and down instead of speaking by line. Single letter Nav is also disabled. Also, when repoting item information, a valid line number is given before notifications and not after receiving one.

this issue seems to be specific to Outlook notifications as I don't seem to experience the issue with notifications from Chrome.

This issue also happens with multiple sound devices including:
1. Built in speakers; Realtec_
2. Turtle Beach Stealth 700 G2; wireless USB
3. Various Bluetooth devices including Shokz OpenRun Pro, and Sennheiser Momentum 4
### Expected behavior:
I would expect to not lose speech and focus after receiving notifications from Outlook.
#### NVDA installed/portable/running from source:
Installed
#### NVDA version:
2023.3rc2 (2023.3.0.29733)
#### Windows version:
Windows 11 Home 22H2  Build: 22621.2428
#### Name and version of other software in use when reproducing the issue:
Outlook 365 2309 Build 16.0.16827.20166) 64-bit 
#### Other information about your system:
Laptop
Processor: 12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
16 GB RAM

#### Does the issue still occur after restarting your computer?
Yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
Yes, this issue happens on version 2022.x
#### If NVDA add-ons are disabled, is your problem still occurring?
Yes
#### Does the issue still occur after you run the COM Registration Fixing Tool in NVDA's tools menu?
Yes

**Comment by seanbudd** [comment] 2023-10-26 00:59
Sounds related/duplicate of #14039

**Comment by seanbudd** [comment] 2023-10-30 22:53
Closing as duplicate of #14039

**Closed by seanbudd** 2023-10-30 22:53 UTC
