### ISSUE TITLE
NVDA will play an error tone when browsing the system settings of windows10-1903 and 1909 using NVDA alpha-19146

### ISSUE THREAD

**Issue by dingpengyu** [nvaccess/nvda#10490] opened 2019-11-13 23:29 UTC
hi NVDA will play an error tone when browsing the system settings of windows10-1903 and 1909 using NVDA alpha-19146
### Steps to reproduce:
First, the case windows+i opens the settings, then use the cursor to find the system case enter, this time will play the wrong tone.
### Actual behavior:
Playing an error tone
### Expected behavior:
An error occurred
#### NVDA installed/portable/running from source:
install version
#### NVDA version:
NVDA alpha-19146,d473de81
#### Windows version:
windows10-1903
and
windows10-1909
#### Name and version of other software in use when reproducing the issue:
windows10-1909
#### Other information about your system:
none
#### Does the issue still occur after restarting your PC?
yes
#### Have you tried any other versions of NVDA? If so, please report their behaviors.
none
The following is the NVDA log:

ERROR - comtypes._comobject.call_without_this (06:58:50.252) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'Event cannot call any subscriber', (None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (06:58:50.307) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'Event cannot call any subscriber', (None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (06:58:50.362) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, 'Event cannot call any subscriber', (None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (06:58:50.392) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (06:58:50.422) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))
ERROR - comtypes._comobject.call_without_this (06:58:50.452) - Dummy-1 (2664):
Exception in IUIAutomationEventHandler.HandleAutomationEvent implementation:
Traceback (most recent call last):
  File "comtypes\_comobject.pyc", line 147, in call_without_this
  File "_UIAHandler.pyc", line 300, in IUIAutomationEventHandler_HandleAutomationEvent
  File "NVDAObjects\__init__.pyc", line 86, in __call__
  File "NVDAObjects\UIA\__init__.pyc", line 866, in findOverlayClasses
  File "comtypes\__init__.pyc", line 279, in __getattr__
  File "comtypesMonkeyPatches.pyc", line 26, in __call__
_ctypes.COMError: (-2147220991, '事件无法调用任何订户', (None, None, None, 0, None))
thanks

**Comment by dingpengyu** [comment] 2019-11-13 23:31
cc @josephsl

**Comment by josephsl** [comment] 2019-11-13 23:47
Hi, duplicate of #10422. Thanks.

**Closed** 2019-11-13 23:48 UTC
