### ISSUE TITLE
NVDA speaks extra header info and controls when using GMail keyboard shortcuts in Chrome

### ISSUE THREAD

**Issue by mjanusauskas** [nvaccess/nvda#6076] opened 2016-06-15 22:06 UTC
Using Chrome Canary and GMail standard UI:
Press J and K to select a conversation containing multiple messages and press O or Enter to open the conversation thread.
Press N and P to go to next or previous message in the conversation.
Note that NVDA first speaks extra header details and controls before reading the message body.
Try the same steps using Firefox and notice that only the message body is spoken when moving from one message to another, providing a much cleaner and more efficient experience.

**Comment by ehollig** [comment] 2017-09-08 02:05
I can confirm this using Chrome 61

**Comment by Adriani90** [comment] 2019-02-24 19:47
@mjanusauskas, @ehollig can you still reproduce this issue in NVDA last Alpha?
If you disable "focus follows browse mode" with NVDA+8 in last Alpha, can you see any difference?

**Comment by Adriani90** [comment] 2019-07-16 13:04
This issue is still reproducible in NVDA 2019.2 Beta 3 and Chrome 75.0.3770.142. But I think this could also be related to how the information is exposed to NVDA by Chromium.

**Comment by Adriani90** [comment] 2020-05-02 18:17
@mjanusauskas now with NVDA last alpha and Chrome 81 the issue is not occuring. NVDA reports the same things like in Firefox 75.
Can you confirm?

**Comment by Adriani90** [comment] 2020-05-02 19:59
I am closing as works for me, but please comment on it if you are still having this issue and we can reopen. Thanks.

**Closed by Adriani90** 2020-05-02 19:59 UTC
Labels: app/chrome, close/worksforme, p2
